In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
tweet_df = pd.read_parquet("../data/dataset/stock_tweets.parquet")
tweet_df
pd.set_option("display.max_colwidth", None)
tweet_df

,ticker,text,created_at,user_id,date
0,VZ,"gdp news "" actives on open ATUSER aapl tsla twtr c gdp amzn drys vz … "" URL board view URL",2014-10-14 13:39:49+00:00,1923902360,2014-10-14
1,VZ,rt ATUSER psw seeking alpha june trade review fxi ewj vz irbt ll uso toptrades URL URL,2015-06-20 14:18:10+00:00,3232889321,2015-06-20
2,VZ,rt ATUSER psw seeking alpha june trade review fxi ewj vz irbt ll uso toptrades URL URL,2015-06-20 16:16:05+00:00,3238685909,2015-06-20
3,VZ,rt ATUSER psw seeking alpha june trade review fxi ewj vz irbt ll uso toptrades URL URL,2015-06-20 16:25:57+00:00,2740607613,2015-06-20
4,VZ,rt ATUSER psw seeking alpha june trade review fxi ewj vz irbt ll uso toptrades URL URL,2015-06-20 16:01:01+00:00,3234872187,2015-06-20
...,...,...,...,...,...
106333,CODI,stock contest pick googl and win a free tablet enter now click here for details URL xom codi mcd gale ~,2014-09-07 00:20:34+00:00,386787305,2014-09-07
106334,CODI,codi compass diversified holdings wk low click here > URL trending codi sh sh baba codi finance finance,2015-05-18 13:34:15+00:00,2579477766,2015-05-18
106335,CODI,codi compass diversified holdings files sec form k other events URL,2014-08-09 10:38:34+00:00,2717670854,2014-08-09
106336,CODI,codi compass diversified holdings financials URL codi aapl iwm codi codi nasdaq investing,2015-06-01 19:34:12+00:00,2181403417,2015-06-01
106337,CODI,compass diversified holdings stock rating reaffirmed by william blair codi codi dinero URL,2015-11-11 11:48:54+00:00,2608959134,2015-11-11

In [3]:
for i in range(len(tweet_df["text"])):
    ticker = re.escape(tweet_df["ticker"][i])
    more_patterns = re.compile(
        rf"(?:\s*)(?:\$)?\b{ticker}\b(?:\s*)|(?:\s*)\bATUSER\b(?:\s*)|(?:\s*)\bAT_USER\b(?:\s*)|(?:\s*)\bURL\b(?:\s*)|(?:\s*)\brt\b(?:\s*)|(?:\s*)\binc\b(?:\s*)|(?:\s*)\bie\b(?:\s*)",
        flags=re.IGNORECASE
    )
    text = more_patterns.sub(" ", tweet_df.loc[i, "text"])
    tweet_df.loc[i, "text"] = re.sub(r"\s+", " ", text).strip()

In [4]:
pd.set_option("display.max_colwidth", None)
tweet_df

,ticker,text,created_at,user_id,date
0,VZ,"gdp news "" actives on open aapl tsla twtr c gdp amzn drys … "" board view",2014-10-14 13:39:49+00:00,1923902360,2014-10-14
1,VZ,psw seeking alpha june trade review fxi ewj irbt ll uso toptrades,2015-06-20 14:18:10+00:00,3232889321,2015-06-20
2,VZ,psw seeking alpha june trade review fxi ewj irbt ll uso toptrades,2015-06-20 16:16:05+00:00,3238685909,2015-06-20
3,VZ,psw seeking alpha june trade review fxi ewj irbt ll uso toptrades,2015-06-20 16:25:57+00:00,2740607613,2015-06-20
4,VZ,psw seeking alpha june trade review fxi ewj irbt ll uso toptrades,2015-06-20 16:01:01+00:00,3234872187,2015-06-20
...,...,...,...,...,...
106333,CODI,stock contest pick googl and win a free tablet enter now click here for details xom mcd gale ~,2014-09-07 00:20:34+00:00,386787305,2014-09-07
106334,CODI,compass diversified holdings wk low click here > trending sh sh baba finance finance,2015-05-18 13:34:15+00:00,2579477766,2015-05-18
106335,CODI,compass diversified holdings files sec form k other events,2014-08-09 10:38:34+00:00,2717670854,2014-08-09
106336,CODI,compass diversified holdings financials aapl iwm nasdaq investing,2015-06-01 19:34:12+00:00,2181403417,2015-06-01
106337,CODI,compass diversified holdings stock rating reaffirmed by william blair dinero,2015-11-11 11:48:54+00:00,2608959134,2015-11-11

In [ ]:
tweet_df.to_parquet("../data/dataset/stock_tweet_nomerge.parquet", index=False)