# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.optim.lr_scheduler import ReduceLROnPlateau

### Configurations

In [ ]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 783  # Number of days to use for initial training only
KELLY_FRACTION = 0.25
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [8]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.25   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [9]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [10]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [11]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # End current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [12]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [13]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [14]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [15]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [16]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [17]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [18]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [19]:
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.float32))
    def __len__(self): return self.X.shape[0]
    def __getitem__(self, idx): return self.X[idx], self.y[idx]

class LSTMClassifier(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, use_layernorm=False):
        super().__init__()
        self.lstm1 = nn.LSTM(
            input_size=n_features, hidden_size=hidden1,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )
        self.inter_drop = nn.Dropout(p=inter_dropout)  # proxy for recurrent_dropout
        self.lstm2 = nn.LSTM(
            input_size=hidden1, hidden_size=hidden2,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )

        # Normalization after temporal pooling
        self.use_layernorm = bool(use_layernorm)
        if self.use_layernorm:
            self.norm = nn.LayerNorm(normalized_shape=hidden2)
        else:
            self.norm = nn.BatchNorm1d(num_features=hidden2)

        # Head
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(p=dropout)
        self.fc_out = nn.Linear(fc, 1)  # logits

    def forward(self, x):
        # x: (B, T, F)
        out1, _ = self.lstm1(x)     # (B, T, hidden1)
        out1 = self.inter_drop(out1)
        out2, _ = self.lstm2(out1)  # (B, T, hidden2)

        last = out2[:, -1, :]       # (B, hidden2)
        if isinstance(self.norm, nn.BatchNorm1d):
            last = self.norm(last)  # BN expects (B, C)
        else:
            last = self.norm(last)  # LN expects (B, C)

        z = self.fc1(last)
        z = self.relu(z)
        z = self.drop(z)
        logits = self.fc_out(z).squeeze(-1)  # (B,)
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [20]:
from matplotlib import ticker


def train_company_models(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         sequence_length: int = None,
                         H = 1):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    #sequence length & guards
    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)

    if len(company_data_df) < sequence_length + H + 10:
        print(f"Not enough data for {ticker}.")
        return False, sequence_length

    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        print(f"No contiguous periods found for {ticker}.")
        return False, sequence_length

    # build sequences
    targets = company_data_df[f'target_{H}d'].values
    X, y = create_contiguous_sequences(
        company_data_df[feature_cols].values,
        targets,
        contiguous_periods,
        sequence_length,
        H
    )
    print(f"Created {len(X)} sequences for {ticker}.")
    if len(X) < 2:
        return False, sequence_length

    # chronological split (no shuffle)
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    # scale features (fit on train, transform both)
    scaler = MinMaxScaler()
    F = X_train.shape[-1]
    X_train_scaled = scaler.fit_transform(X_train.reshape(-1, F)).reshape(X_train.shape)
    X_val_scaled   = scaler.transform(  X_val.reshape(-1, F)).reshape(X_val.shape)
    
    print(f"[TRAIN] {ticker}: scaler fitted on {X_train.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_train has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    sector_feature_indices = [feature_cols.index('sector_ret_1d'),
                          feature_cols.index('sector_ret_5d'),
                          feature_cols.index('sector_vol_20d')]

    print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")

    # Keras fit used the scaled data
    train_ds = SequenceDataset(X_train_scaled, y_train)
    val_ds   = SequenceDataset(X_val_scaled,   y_val)

    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  drop_last=False)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_train.shape[-1]
    model = LSTMClassifier(n_features=n_features, dropout=0.3, inter_dropout=0.1).to(device)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)  # clipnorm via grad clipping below
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)
    early = EarlyStopper(patience=15, mode='min')

    for epoch in range(100):
        model.train()
        total_loss = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # clipnorm=1.0
            optimizer.step()
            total_loss += loss.item() * xb.size(0)

        train_loss = total_loss / len(train_loader.dataset)
        val_loss, _ = _evaluate(model, val_loader, device, loss_fn)

        scheduler.step(val_loss)  # ReduceLROnPlateau on val_loss

        # EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:  # stop after 'patience' non-improve epochs
            break

    # restore best weights
    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    # final validation pass for isotonic calibration (on scaled val data)
    _, validation_predictions = _evaluate(model, val_loader, device, loss_fn)

    # Keras code used 10% buffer (comment said 5%)
    pred_min, pred_max = validation_predictions.min(), validation_predictions.max()
    buffer = 0.05 * (pred_max - pred_min)
    y_min_dynamic = max(0.0, pred_min - buffer)
    y_max_dynamic = min(1.0, pred_max + buffer)

    calibrator = IsotonicRegression(y_min=y_min_dynamic, y_max=y_max_dynamic, out_of_bounds='clip')
    calibrator.fit(validation_predictions, y_val.astype(float))

    # inside train_company_models(..., H=H)
    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt"))
    joblib.dump(calibrator,      os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
    joblib.dump(scaler,          os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


    del model, scaler, calibrator, train_loader, val_loader, train_ds, val_ds
    del X_train, X_val, y_train, y_val, X_train_scaled, X_val_scaled
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [21]:
def predict_next_horizon(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 H: int) -> dict | None:

    try:
        # load artifacts
        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt")
        calibrator = joblib.load(os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
        scaler     = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        sequence_length    = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


        if not os.path.isfile(state_dict_path):
            return None
        
        if hasattr(scaler, "n_features_in_") and scaler.n_features_in_ != len(feature_cols):
            return None

        # build model skeleton with correct input dim, then load weights
        n_features = len(feature_cols)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        model = LSTMClassifier(n_features=n_features).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    # find the last contiguous block and take the most recent sequence_length rows
    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        return None

    last_start, last_end = contiguous_periods[-1]
    period_data = company_data_df.iloc[last_start:last_end + 1]
    if len(period_data) < sequence_length:
        return None

    last_sequence = period_data.tail(sequence_length)

    # scale using the saved scaler (fit  train only)
    # ensure column order matches training
    try:
        scaled_features = scaler.transform(last_sequence[feature_cols])
    except Exception:
        return None

    # shape: (1, T, F) as float32 tensor
    x = torch.from_numpy(np.asarray([scaled_features], dtype=np.float32)).to(device)

    with torch.no_grad():
        logits = model(x)                  # shape (1,)
        prob = torch.sigmoid(logits).item()  # scalar in [0,1]

    # isotonic calibration (expects iterable)
    calibrated = float(calibrator.predict([prob])[0])

    print(f"Raw prediction for {ticker}: {prob}")
    print(f"Calibrated prediction for {ticker}: {calibrated}")

    return {
        'ticker': ticker,
        'raw_prediction': prob,
        'calibrated_prediction': calibrated
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [22]:
def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                            total_capital: float, sector_threshold: float,
                            kelly_fraction: float) -> pd.DataFrame:

    investment_decisions = []

    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing. Threshold={sector_threshold:.3f}, Kelly frac={kelly_fraction:.3f}")

    for sector, group in daily_predictions_df.groupby('sector'):
        avg_sector_score = group['calibrated_prediction'].mean()
        print(f"[PORT] Sector {sector}: {len(group)} candidates, avg score={avg_sector_score:.3f}")
        if avg_sector_score < sector_threshold:
            print(f"[PORT] Sector {sector}: filtered out by confidence threshold")
            continue

        best_stock_in_sector = group.loc[group['calibrated_prediction'].idxmax()]
        ticker = best_stock_in_sector['ticker']
        p = best_stock_in_sector['calibrated_prediction']
        b_info = payout_map.get(ticker, 0.0)
        b = (b_info['b'] if isinstance(b_info, dict) else float(b_info))
        if not np.isfinite(b) or b <= 0:
            print(f"[PORT] Sector {sector}: skipping {ticker} due to invalid payout b={b}")
            continue

        if not b_info or not np.isfinite(b_info.get('b', np.nan)):
            print(f"[PORT] Sector {sector}: missing payout info for {ticker}")
            continue
        b = max(b_info['b'], 1e-6)  # avoid div-by-zero
        kelly_percentage = p - (1 - p) / b

        if kelly_percentage <= 0:
            print(f"[PORT] Sector {sector}: Kelly <= 0 for {ticker} (p={p:.3f}, b={b:.3f})")
            continue

        investment_fraction = kelly_percentage * kelly_fraction
        investment_amount = total_capital * investment_fraction

        if investment_amount < MIN_TRADE_DOLLARS:
            print(f"[PORT] Sector {sector}: allocation ${investment_amount:.2f} below minimum for {ticker}")
            continue

        print(f"[PORT] Sector {sector}: selecting {ticker} (p={p:.3f}, b={b:.3f}, kelly={kelly_percentage:.3f}) with ${investment_amount:.2f}")

        investment_decisions.append({
            'ticker': ticker,
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount,
            'predicted_prob': p
        })

    if not investment_decisions:
        print("[PORT] All candidates rejected after sizing/filters.")

    return pd.DataFrame(investment_decisions)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [23]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    files = [
        f"{ticker}_lstm_H{H}.pt",
        f"{ticker}_calibrator_H{H}.pkl",
        f"{ticker}_scaler_H{H}.pkl",
        f"{ticker}_seq_length_H{H}.pkl",
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in files)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [24]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # returns used for settlement only; not for training
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker','date'])[ret_col].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    open_positions = []
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                if pd.notna(rH):
                    pnl = pos['invest'] * rH
                    total_pnl_today += pnl
                    capital += pos['invest'] + pnl
            else:
                still_open.append(pos)
        open_positions = still_open

        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # historical slice strictly before current_date; recompute targets locally
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        cutoff = current_date - pd.Timedelta(days=H)
        historical_data = historical_data[historical_data['date'] < cutoff]
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if i == 0:
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if not have_models or need_retrain:
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)

        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df, payout_map_day, capital, SECTOR_CONFIDENCE_THRESHOLD, KELLY_FRACTION
        )

        exit_idx = i + H
        exit_date = unique_dates[exit_idx] if exit_idx < len(unique_dates) else None

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)

            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue

                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))

                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})

        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,
            'capital_end': capital,
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [25]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [26]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_and_bimeta_features.parquet')

In [27]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)
# Exclude ticker with missing meta-features across all rows
master_df = master_df[master_df['ticker'] != 'GMRE']

columns_to_check = ['EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    'lstm_prob_up_1d', 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [28]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    'lstm_prob_up_1d', 
    # 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 
    # 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength', 'lstm_prob_up_1d', 'gru_pred_ret_1d']
Total number of features: 30

In [29]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [30]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=1,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Starting simulation with 783 initial training days... (H=1)
Starting predictions from day 783 (after 783 training days)

Simulating Trading Days:   0%|          | 0/100 [00:00<?, ?it/s]

Created 770 sequences for AAPL.
[TRAIN] AAPL: scaler fitted on 616 training sequences
[TRAIN] AAPL: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] AAPL: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] AAPL: sector feature maxs = [0.03194691 0.05042416 0.01893123]
Raw prediction for AAPL: 0.5007280111312866
Calibrated prediction for AAPL: 0.5003328323364258
Created 770 sequences for ABB.
[TRAIN] ABB: scaler fitted on 616 training sequences
[TRAIN] ABB: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] ABB: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] ABB: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for ABB: 0.4930446743965149
Calibrated prediction for ABB: 0.5190532803535461
Created 708 sequences for ABBV.
[TRAIN] ABBV: scaler fitted on 566 training sequences
[TRAIN] ABBV: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] ABBV: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] ABBV: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for ABBV: 0.24774841964244843
Calibrated prediction for ABBV: 0.2857142984867096
Created 770 sequences for AEP.
[TRAIN] AEP: scaler fitted on 616 training sequences
[TRAIN] AEP: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] AEP: sector feature mins = [-0.04000807 -0.08164836  0.00493882]
[TRAIN] AEP: sector feature maxs = [0.02833403 0.06078573 0.01557388]
Raw prediction for AEP: 0.5562863349914551
Calibrated prediction for AEP: 0.5714285969734192
Created 232 sequences for AGFS.
[TRAIN] AGFS: scaler fitted on 185 training sequences
[TRAIN] AGFS: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] AGFS: sector feature mins = [-0.21470837 -0.24019047  0.00476725]
[TRAIN] AGFS: sector feature maxs = [0.35098106 0.39009354 0.07892018]
Raw prediction for AGFS: 0.5000009536743164
Calibrated prediction for AGFS: 0.4981705844402313
Created 770 sequences for AMGN.
[TRAIN] AMGN: scaler fitted on 616 training sequences
[TRAIN] AMGN: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] AMGN: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] AMGN: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for AMGN: 0.5173628926277161
Calibrated prediction for AMGN: 0.5185185074806213
Created 770 sequences for AMZN.
[TRAIN] AMZN: scaler fitted on 616 training sequences
[TRAIN] AMZN: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] AMZN: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] AMZN: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for AMZN: 0.5596551299095154
Calibrated prediction for AMZN: 0.5588235259056091
Created 770 sequences for BA.
[TRAIN] BA: scaler fitted on 616 training sequences
[TRAIN] BA: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BA: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] BA: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for BA: 0.48790764808654785
Calibrated prediction for BA: 0.5262488722801208
Created 276 sequences for BABA.
[TRAIN] BABA: scaler fitted on 220 training sequences
[TRAIN] BABA: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BABA: sector feature mins = [-0.06810713 -0.07017512  0.00432136]
[TRAIN] BABA: sector feature maxs = [0.03499886 0.13521497 0.025178  ]
Raw prediction for BABA: 0.47169432044029236
Calibrated prediction for BABA: 0.5115155577659607
Created 770 sequences for BAC.
[TRAIN] BAC: scaler fitted on 616 training sequences
[TRAIN] BAC: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BAC: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BAC: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for BAC: 0.47650665044784546
Calibrated prediction for BAC: 0.46341463923454285
Created 770 sequences for BBL.
[TRAIN] BBL: scaler fitted on 616 training sequences
[TRAIN] BBL: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BBL: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BBL: sector feature maxs = [0.05341933 0.13994116 0.03044324]
Raw prediction for BBL: 0.4842531085014343
Calibrated prediction for BBL: 0.550000011920929
Created 770 sequences for BCH.
[TRAIN] BCH: scaler fitted on 616 training sequences
[TRAIN] BCH: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BCH: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BCH: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for BCH: 0.5635503530502319
Calibrated prediction for BCH: 0.6000000238418579
Created 770 sequences for BHP.
[TRAIN] BHP: scaler fitted on 616 training sequences
[TRAIN] BHP: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BHP: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BHP: sector feature maxs = [0.05341933 0.13994116 0.03044324]
Raw prediction for BHP: 0.4878996014595032
Calibrated prediction for BHP: 0.4940555691719055
Created 770 sequences for BP.
[TRAIN] BP: scaler fitted on 616 training sequences
[TRAIN] BP: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BP: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BP: sector feature maxs = [0.05341933 0.13994116 0.03044324]
Raw prediction for BP: 0.5463749766349792
Calibrated prediction for BP: 0.5833333134651184
Created 770 sequences for BRK-A.
[TRAIN] BRK-A: scaler fitted on 616 training sequences
[TRAIN] BRK-A: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BRK-A: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BRK-A: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for BRK-A: 0.49051231145858765
Calibrated prediction for BRK-A: 0.48786410689353943
Created 770 sequences for BSAC.
[TRAIN] BSAC: scaler fitted on 616 training sequences
[TRAIN] BSAC: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BSAC: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BSAC: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for BSAC: 0.4887584447860718
Calibrated prediction for BSAC: 0.48750001192092896
Created 770 sequences for BUD.
[TRAIN] BUD: scaler fitted on 616 training sequences
[TRAIN] BUD: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] BUD: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] BUD: sector feature maxs = [0.03194691 0.05042416 0.01893123]
Raw prediction for BUD: 0.5114373564720154
Calibrated prediction for BUD: 0.6194642186164856
Created 770 sequences for C.
[TRAIN] C: scaler fitted on 616 training sequences
[TRAIN] C: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] C: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] C: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for C: 0.5157925486564636
Calibrated prediction for C: 0.5174347162246704
Created 770 sequences for CAT.
[TRAIN] CAT: scaler fitted on 616 training sequences
[TRAIN] CAT: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] CAT: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] CAT: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for CAT: 0.47747525572776794
Calibrated prediction for CAT: 0.4752475321292877
Created 770 sequences for CELG.
[TRAIN] CELG: scaler fitted on 616 training sequences
[TRAIN] CELG: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] CELG: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] CELG: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for CELG: 0.5783045291900635
Calibrated prediction for CELG: 0.5894736647605896
Created 770 sequences for CHL.
[TRAIN] CHL: scaler fitted on 616 training sequences
[TRAIN] CHL: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] CHL: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] CHL: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for CHL: 0.5491132140159607
Calibrated prediction for CHL: 0.5573236346244812
Created 770 sequences for CHTR.
[TRAIN] CHTR: scaler fitted on 616 training sequences
[TRAIN] CHTR: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] CHTR: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] CHTR: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for CHTR: 0.556240439414978
Calibrated prediction for CHTR: 0.6152653098106384
Created 770 sequences for CMCSA.
[TRAIN] CMCSA: scaler fitted on 616 training sequences
[TRAIN] CMCSA: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] CMCSA: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] CMCSA: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for CMCSA: 0.4323887526988983
Calibrated prediction for CMCSA: 0.37434905767440796
Created 770 sequences for CODI.
[TRAIN] CODI: scaler fitted on 616 training sequences
[TRAIN] CODI: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] CODI: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] CODI: sector feature maxs = [0.35098106 0.39009354 0.07892018]
Raw prediction for CODI: 0.41005563735961914
Calibrated prediction for CODI: 0.4264705777168274
Created 770 sequences for CSCO.
[TRAIN] CSCO: scaler fitted on 616 training sequences
[TRAIN] CSCO: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] CSCO: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] CSCO: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for CSCO: 0.4836619198322296
Calibrated prediction for CSCO: 0.5058823823928833
Created 770 sequences for CVX.
[TRAIN] CVX: scaler fitted on 616 training sequences
[TRAIN] CVX: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] CVX: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] CVX: sector feature maxs = [0.05341933 0.13994116 0.03044324]
Raw prediction for CVX: 0.4941117465496063
Calibrated prediction for CVX: 0.4869210720062256
Created 770 sequences for D.
[TRAIN] D: scaler fitted on 616 training sequences
[TRAIN] D: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] D: sector feature mins = [-0.04000807 -0.08164836  0.00493882]
[TRAIN] D: sector feature maxs = [0.02833403 0.06078573 0.01557388]
Raw prediction for D: 0.5123291015625
Calibrated prediction for D: 0.5089935064315796
Created 770 sequences for DHR.
[TRAIN] DHR: scaler fitted on 616 training sequences
[TRAIN] DHR: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] DHR: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] DHR: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for DHR: 0.510125994682312
Calibrated prediction for DHR: 0.5037593841552734
Created 770 sequences for DIS.
[TRAIN] DIS: scaler fitted on 616 training sequences
[TRAIN] DIS: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] DIS: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] DIS: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for DIS: 0.49695250391960144
Calibrated prediction for DIS: 0.4966834783554077
Created 770 sequences for DUK.
[TRAIN] DUK: scaler fitted on 616 training sequences
[TRAIN] DUK: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] DUK: sector feature mins = [-0.04000807 -0.08164836  0.00493882]
[TRAIN] DUK: sector feature maxs = [0.02833403 0.06078573 0.01557388]
Raw prediction for DUK: 0.5346869230270386
Calibrated prediction for DUK: 0.5725536346435547
Created 770 sequences for EXC.
[TRAIN] EXC: scaler fitted on 616 training sequences
[TRAIN] EXC: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] EXC: sector feature mins = [-0.04000807 -0.08164836  0.00493882]
[TRAIN] EXC: sector feature maxs = [0.02833403 0.06078573 0.01557388]
Raw prediction for EXC: 0.5077175498008728
Calibrated prediction for EXC: 0.5
Created 770 sequences for FB.
[TRAIN] FB: scaler fitted on 616 training sequences
[TRAIN] FB: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] FB: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] FB: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for FB: 0.5129255652427673
Calibrated prediction for FB: 0.5171394944190979
Created 770 sequences for GD.
[TRAIN] GD: scaler fitted on 616 training sequences
[TRAIN] GD: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] GD: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] GD: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for GD: 0.5303919911384583
Calibrated prediction for GD: 0.5348551273345947
Created 770 sequences for GE.
[TRAIN] GE: scaler fitted on 616 training sequences
[TRAIN] GE: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] GE: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] GE: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for GE: 0.474439412355423
Calibrated prediction for GE: 0.43939393758773804
Created 770 sequences for GOOG.
[TRAIN] GOOG: scaler fitted on 616 training sequences
[TRAIN] GOOG: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] GOOG: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] GOOG: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for GOOG: 0.6095158457756042
Calibrated prediction for GOOG: 0.6304348111152649
Created 770 sequences for HD.
[TRAIN] HD: scaler fitted on 616 training sequences
[TRAIN] HD: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] HD: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] HD: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for HD: 0.45709481835365295
Calibrated prediction for HD: 0.44859635829925537
Created 770 sequences for HON.
[TRAIN] HON: scaler fitted on 616 training sequences
[TRAIN] HON: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] HON: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] HON: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for HON: 0.5269781351089478
Calibrated prediction for HON: 0.5555555820465088
Created 770 sequences for HRG.
[TRAIN] HRG: scaler fitted on 616 training sequences
[TRAIN] HRG: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] HRG: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] HRG: sector feature maxs = [0.35098106 0.39009354 0.07892018]
Raw prediction for HRG: 0.6514551639556885
Calibrated prediction for HRG: 0.6593891382217407
Created 770 sequences for HSBC.
[TRAIN] HSBC: scaler fitted on 616 training sequences
[TRAIN] HSBC: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] HSBC: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] HSBC: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for HSBC: 0.5103968977928162
Calibrated prediction for HSBC: 0.517241358757019
Created 770 sequences for IEP.
[TRAIN] IEP: scaler fitted on 616 training sequences
[TRAIN] IEP: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] IEP: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] IEP: sector feature maxs = [0.35098106 0.39009354 0.07892018]
Raw prediction for IEP: 0.5192559957504272
Calibrated prediction for IEP: 0.5166666507720947
Created 770 sequences for INTC.
[TRAIN] INTC: scaler fitted on 616 training sequences
[TRAIN] INTC: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] INTC: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] INTC: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for INTC: 0.5703709125518799
Calibrated prediction for INTC: 0.557692289352417
Created 770 sequences for JNJ.
[TRAIN] JNJ: scaler fitted on 616 training sequences
[TRAIN] JNJ: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] JNJ: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] JNJ: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for JNJ: 0.3181113004684448
Calibrated prediction for JNJ: 0.29589736461639404
Created 770 sequences for JPM.
[TRAIN] JPM: scaler fitted on 616 training sequences
[TRAIN] JPM: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] JPM: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] JPM: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for JPM: 0.5406380891799927
Calibrated prediction for JPM: 0.5430880188941956
Created 770 sequences for KO.
[TRAIN] KO: scaler fitted on 616 training sequences
[TRAIN] KO: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] KO: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] KO: sector feature maxs = [0.03194691 0.05042416 0.01893123]
Raw prediction for KO: 0.4683015048503876
Calibrated prediction for KO: 0.4670509696006775
Created 770 sequences for LMT.
[TRAIN] LMT: scaler fitted on 616 training sequences
[TRAIN] LMT: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] LMT: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] LMT: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for LMT: 0.5653396248817444
Calibrated prediction for LMT: 0.5394853949546814
Created 770 sequences for MA.
[TRAIN] MA: scaler fitted on 616 training sequences
[TRAIN] MA: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] MA: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] MA: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for MA: 0.49507269263267517
Calibrated prediction for MA: 0.5522388219833374
Created 770 sequences for MCD.
[TRAIN] MCD: scaler fitted on 616 training sequences
[TRAIN] MCD: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] MCD: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] MCD: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for MCD: 0.5265060663223267
Calibrated prediction for MCD: 0.5366811752319336
Created 770 sequences for MDT.
[TRAIN] MDT: scaler fitted on 616 training sequences
[TRAIN] MDT: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] MDT: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] MDT: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for MDT: 0.5061436295509338
Calibrated prediction for MDT: 0.45016416907310486
Created 770 sequences for MMM.
[TRAIN] MMM: scaler fitted on 616 training sequences
[TRAIN] MMM: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] MMM: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] MMM: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for MMM: 0.5684905052185059
Calibrated prediction for MMM: 0.5712277889251709
Created 770 sequences for MO.
[TRAIN] MO: scaler fitted on 616 training sequences
[TRAIN] MO: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] MO: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] MO: sector feature maxs = [0.03194691 0.05042416 0.01893123]
Raw prediction for MO: 0.5700576305389404
Calibrated prediction for MO: 0.5405405163764954
Created 770 sequences for MRK.
[TRAIN] MRK: scaler fitted on 616 training sequences
[TRAIN] MRK: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] MRK: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] MRK: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for MRK: 0.46630626916885376
Calibrated prediction for MRK: 0.47309410572052
Created 770 sequences for MSFT.
[TRAIN] MSFT: scaler fitted on 616 training sequences
[TRAIN] MSFT: scaler.n_features_in_ = 30, len(feature_cols) = 30
[TRAIN] MSFT: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] MSFT: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for MSFT: 0.46723926067352295

Simulating Trading Days:   1%|          | 1/100 [04:19<7:08:14, 259.54s/it]

Raw prediction for XOM: 0.4981994032859802
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.507
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.969, kelly=0.182) with $4547.69
[PORT] Sector Conglomerates: 7 candidates, avg score=0.480
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.965, kelly=0.307) with $7664.77
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.484
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.038, kelly=0.253) with $6321.12
[PORT] Sector Financial: 10 candidates, avg score=0.526
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.980, kelly=0.192) with $4792.98
[PORT] Sector Healthcare: 10 candidates, avg score=0.453
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.017, kelly=0.186) with $4648.28
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.500
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.982, kelly=0.135) with $3367.21
[PORT] Sector Services: 10 candidates, avg score=0.519
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.039, kelly=0.293) with $7333.82
[PORT] Sector Technology: 10 candidates, avg score=0.513
[PORT] Sector Technology: selecting GOOG (p=0.630, b=1.063, kelly=0.283) with $7065.82
[PORT] Sector Utilities: 10 candidates, avg score=0.536
[PORT] Sector Utilities: selecting NEE (p=0.619, b=0.897, kelly=0.193) with $4832.32
Raw prediction for AAPL: 0.5005151629447937
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.49673810601234436
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24224060773849487
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5570797920227051
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.49936792254447937
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5168789625167847
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.5689501762390137
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.48614808917045593
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.47419992089271545
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4760635793209076
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.47894221544265747
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5593452453613281
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.4882866144180298
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5561304688453674
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.49060675501823425
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48884594440460205
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.5074295997619629
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5158067345619202
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47732114791870117
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.5749268531799316
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5496816635131836
Calibrated prediction for CHL: 0.5623735189437866
Raw prediction for CHTR: 0.5605441927909851
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4255554676055908
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.40333467721939087
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.48477262258529663
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4933168888092041
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5123213529586792
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.508898913860321
Calibrated prediction for DHR: 0.5037593841552734
Raw prediction for DIS: 0.4964763820171356
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5386176109313965
Calibrated prediction for DUK: 0.6000000238418579
Raw prediction for EXC: 0.5075241923332214
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5131120681762695
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5303295254707336
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4770779609680176
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.613937258720398
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.4542123079299927
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.5237804055213928
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6508365869522095
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5026426315307617
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.5323866009712219
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5668647885322571
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.32015031576156616
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.541007936000824
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46812498569488525
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5728648900985718
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.48770788311958313
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5265666842460632
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5047369003295898
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.568884015083313
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5730808973312378
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4670247435569763
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4785471558570862
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5532956123352051
Calibrated prediction for NEE: 0.6185566782951355
Raw prediction for NGG: 0.49750658869743347
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4874028265476227
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4470064640045166
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5208495259284973
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5660235285758972
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4754944145679474
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46559032797813416
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4374031126499176
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.5032365322113037
Calibrated prediction for PICO: 0.5192241072654724
Raw prediction for PM: 0.5626825094223022
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5126190781593323
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.43699178099632263
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5096707344055176
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5111849308013916
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.436383992433548
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.5162031650543213
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5024186968803406
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5037214159965515
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.45387187600135803
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5884217619895935
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.513508141040802
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.5067302584648132
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.462289035320282
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5328179001808167
Calibrated prediction for TSM: 0.5510203838348389

Simulating Trading Days:   2%|▏         | 2/100 [04:20<2:55:50, 107.66s/it]

Raw prediction for UL: 0.476047158241272
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4510819613933563
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.5094414353370667
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.48913484811782837
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.3633910119533539
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5567561388015747
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.49063366651535034
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.49972590804100037
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.548403263092041
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.4993501901626587
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.968, kelly=0.181) with $4529.28
[PORT] Sector Conglomerates: 7 candidates, avg score=0.480
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.966, kelly=0.307) with $7665.05
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.484
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.039, kelly=0.253) with $6325.97
[PORT] Sector Financial: 10 candidates, avg score=0.523
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.982, kelly=0.193) with $4809.36
[PORT] Sector Healthcare: 10 candidates, avg score=0.453
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.019, kelly=0.186) with $4659.08
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.508
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.067, kelly=0.274) with $6835.96
[PORT] Sector Services: 10 candidates, avg score=0.519
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.040, kelly=0.294) with $7342.52
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting GOOG (p=0.630, b=1.065, kelly=0.283) with $7079.34
[PORT] Sector Utilities: 10 candidates, avg score=0.543
[PORT] Sector Utilities: selecting NEE (p=0.619, b=0.899, kelly=0.194) with $4856.51
Raw prediction for AAPL: 0.5003124475479126
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.4998554289340973
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24234065413475037
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5602766871452332
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.49855929613113403
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5158858895301819
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.5787328481674194
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.4837625026702881
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.47748851776123047
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47617557644844055
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4737178385257721
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5575897693634033
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.48850569128990173
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5642485618591309
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.4908645451068878
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48906469345092773
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.5059385895729065
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5156605839729309
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.477184534072876
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.5665952563285828
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5511013865470886
Calibrated prediction for CHL: 0.5749858021736145
Raw prediction for CHTR: 0.5617915987968445
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.42253994941711426
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.3955323398113251
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.48597827553749084
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4928712844848633
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5123397707939148
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5074685215950012
Calibrated prediction for DHR: 0.5037593841552734
Raw prediction for DIS: 0.4961560070514679
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5478726625442505
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5077208280563354
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5134117007255554
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5301375389099121
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4774685204029083
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.6184020638465881
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.45126551389694214
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.5172020196914673
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6504295468330383
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.49960845708847046
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.5532616376876831
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5625048875808716
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3238638937473297
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5416133403778076
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4680766761302948
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5707827806472778
Calibrated prediction for LMT: 0.6153905987739563
Raw prediction for MA: 0.4996289312839508
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5266190767288208
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5040585398674011
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5677300095558167
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5773599147796631
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4679722189903259
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4965927004814148
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5542973279953003
Calibrated prediction for NEE: 0.6185566782951355
Raw prediction for NGG: 0.4970459043979645
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4876750111579895
Calibrated prediction for NVS: 0.5436900854110718
Raw prediction for ORCL: 0.447415292263031
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5207853317260742
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5735375881195068
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47573524713516235
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46590253710746765
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.437391996383667
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.506188690662384
Calibrated prediction for PICO: 0.5192241072654724
Raw prediction for PM: 0.5575257539749146
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5184189081192017
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.44005441665649414
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5080211758613586
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5049934387207031
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.4369892477989197
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.5188168883323669
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5025820732116699
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5038553476333618
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4506100118160248
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5762655138969421
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5240238904953003
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.5226849317550659
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.456973671913147
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5392022132873535
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4742777943611145
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.44546622037887573
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.5018765926361084
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48934605717658997
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.3607831299304962
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5573936104774475
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4914107322692871
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5001385807991028
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.548313319683075
Calibrated prediction for WMT: 0.5098039507865906

Simulating Trading Days:   3%|▎         | 3/100 [04:22<1:35:24, 59.02s/it]

Raw prediction for XOM: 0.5008957386016846
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.969, kelly=0.182) with $4544.92
[PORT] Sector Conglomerates: 7 candidates, avg score=0.480
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.968, kelly=0.307) with $7675.31
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.484
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.037, kelly=0.252) with $6301.59
[PORT] Sector Financial: 10 candidates, avg score=0.523
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.980, kelly=0.192) with $4790.54
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.016, kelly=0.186) with $4631.75
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.507
[PORT] Sector Industrial Goods: selecting LMT (p=0.615, b=1.068, kelly=0.255) with $6368.03
[PORT] Sector Services: 10 candidates, avg score=0.519
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.040, kelly=0.294) with $7338.16
[PORT] Sector Technology: 10 candidates, avg score=0.526
[PORT] Sector Technology: selecting GOOG (p=0.630, b=1.063, kelly=0.283) with $7054.34
[PORT] Sector Utilities: 10 candidates, avg score=0.547
[PORT] Sector Utilities: selecting NEE (p=0.619, b=0.900, kelly=0.195) with $4856.93
Raw prediction for AAPL: 0.500072717666626
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5036002397537231
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2394867092370987
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5631681680679321
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4981636703014374
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5146287679672241
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.5905765891075134
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.48302242159843445
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.47947704792022705
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47662654519081116
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4726746380329132
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.553727924823761
Calibrated prediction for BCH: 0.5714285969734192
Raw prediction for BHP: 0.48896947503089905
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5725978016853333
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.4911157786846161
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4892423450946808
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.5046069622039795
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5154794454574585
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47708311676979065
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.5546243786811829
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5487533211708069
Calibrated prediction for CHL: 0.5541264414787292
Raw prediction for CHTR: 0.5598356127738953
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4313278794288635
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.39508166909217834
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4871313273906708
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49198755621910095
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5123686194419861
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5075719356536865
Calibrated prediction for DHR: 0.5037593841552734
Raw prediction for DIS: 0.4960237145423889
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5554082989692688
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5076134204864502
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5138424038887024
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5298174619674683
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.47979047894477844
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.6218162178993225
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.450970321893692
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.5186498761177063
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6493836641311646
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5015113353729248
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.5700691938400269
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5553752183914185
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3295450806617737
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5421521663665771
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46796172857284546
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5637269616127014
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5199466347694397
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5265969038009644
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5040621757507324
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5677874684333801
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5803568959236145
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4684840440750122
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5136024355888367
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5542988181114197
Calibrated prediction for NEE: 0.6185566782951355
Raw prediction for NGG: 0.49504584074020386
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.48838600516319275
Calibrated prediction for NVS: 0.5436900854110718
Raw prediction for ORCL: 0.4476316273212433
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5207969546318054
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5825918912887573
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4756014943122864
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46617403626441956
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4373190104961395
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.5071858763694763
Calibrated prediction for PICO: 0.5192241072654724
Raw prediction for PM: 0.5522159337997437
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5214856863021851
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4431430697441101
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5072890520095825
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.49786823987960815
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.43527668714523315
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.5192954540252686
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.50257408618927
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5040404796600342
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4489234983921051
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5500242114067078
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5287848711013794
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.5396497249603271
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.47153592109680176
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5435148477554321
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.47199586033821106
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.42745745182037354
Calibrated prediction for UN: 0.4285714328289032

Simulating Trading Days:   4%|▍         | 4/100 [04:23<57:51, 36.16s/it]

Raw prediction for UNH: 0.49547162652015686
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4896833002567291
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.37650641798973083
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.557762086391449
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.49205392599105835
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5005653500556946
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5482953190803528
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.5032798051834106
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.967, kelly=0.181) with $4540.25
[PORT] Sector Conglomerates: 7 candidates, avg score=0.478
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.971, kelly=0.308) with $7727.37
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.485
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.036, kelly=0.252) with $6320.88
[PORT] Sector Financial: 10 candidates, avg score=0.520
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4339.43
[PORT] Sector Healthcare: 10 candidates, avg score=0.440
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.018, kelly=0.186) with $4665.04
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.499
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.983, kelly=0.135) with $3383.76
[PORT] Sector Services: 10 candidates, avg score=0.519
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.042, kelly=0.294) with $7374.40
[PORT] Sector Technology: 10 candidates, avg score=0.524
[PORT] Sector Technology: selecting GOOG (p=0.630, b=1.065, kelly=0.283) with $7100.36
[PORT] Sector Utilities: 10 candidates, avg score=0.547
[PORT] Sector Utilities: selecting NEE (p=0.619, b=0.898, kelly=0.194) with $4856.43
Raw prediction for AAPL: 0.4999842643737793
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5072566270828247
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24203301966190338
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5642431378364563
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.49798309803009033
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5135905146598816
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6108434200286865
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.48403576016426086
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.4815135896205902
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47789475321769714
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.47247475385665894
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5574398040771484
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.4890469014644623
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5717244148254395
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.49158504605293274
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4893452525138855
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.504275918006897
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5152126550674438
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47734707593917847
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.542915403842926
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5436366200447083
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5596787333488464
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4505569338798523
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4028209149837494
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4878760874271393
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49179843068122864
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5123645067214966
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5079759955406189
Calibrated prediction for DHR: 0.5037593841552734
Raw prediction for DIS: 0.49624189734458923
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5619156360626221
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5076983571052551
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5142127871513367
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5296068787574768
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4820878505706787
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.6274972558021545
Calibrated prediction for GOOG: 0.6734052300453186
Raw prediction for HD: 0.45643913745880127
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.5227195024490356
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.648744523525238
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5151622891426086
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.5834141969680786
Calibrated prediction for IEP: 0.6000000238418579
Raw prediction for INTC: 0.545981764793396
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3378140926361084
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5431309342384338
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4678910970687866
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5512287020683289
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5617933869361877
Calibrated prediction for MA: 0.6803832054138184
Raw prediction for MCD: 0.5265846252441406
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.504677951335907
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5679119229316711
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5794828534126282
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4687272906303406
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5229955911636353
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5518256425857544
Calibrated prediction for NEE: 0.6185566782951355
Raw prediction for NGG: 0.4934762120246887
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4895378053188324
Calibrated prediction for NVS: 0.5436900854110718
Raw prediction for ORCL: 0.44838523864746094
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5207862854003906
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5870074033737183
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47539979219436646
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46629512310028076
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4371999502182007
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.5098122358322144
Calibrated prediction for PICO: 0.5192241072654724
Raw prediction for PM: 0.5453760623931885
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5243932604789734
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4464300870895386
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5049523115158081
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.48951780796051025
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.4325571656227112
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.5159922242164612
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5024822354316711
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5041458010673523
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4488053023815155
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5269063115119934
Calibrated prediction for SRE: 0.5277777910232544

Simulating Trading Days:   5%|▌         | 5/100 [04:24<37:14, 23.52s/it]

Raw prediction for T: 0.5294252634048462
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.5389696955680847
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.4864666759967804
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5530661940574646
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46924349665641785
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4063253104686737
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.49521318078041077
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4902021586894989
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.40655580163002014
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5589496493339539
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.49425914883613586
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5014379620552063
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5485214591026306
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.504150927066803
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.966, kelly=0.181) with $4526.07
[PORT] Sector Conglomerates: 7 candidates, avg score=0.490
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.969, kelly=0.308) with $7711.99
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.485
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.037, kelly=0.253) with $6325.34
[PORT] Sector Financial: 10 candidates, avg score=0.538
[PORT] Sector Financial: selecting MA (p=0.680, b=0.958, kelly=0.347) with $8682.66
[PORT] Sector Healthcare: 10 candidates, avg score=0.448
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.016, kelly=0.186) with $4647.63
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.499
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.984, kelly=0.135) with $3391.23
[PORT] Sector Services: 10 candidates, avg score=0.519
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.043, kelly=0.295) with $7384.90
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting GOOG (p=0.673, b=1.067, kelly=0.367) with $9197.51
[PORT] Sector Utilities: 10 candidates, avg score=0.544
[PORT] Sector Utilities: selecting NEE (p=0.619, b=0.896, kelly=0.193) with $4834.30
Raw prediction for AAPL: 0.4997943341732025
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5102272629737854
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2411458045244217
Calibrated prediction for ABBV: 0.2488935887813568
Raw prediction for AEP: 0.5635172724723816
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.49743402004241943
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5130937099456787
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6196169257164001
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.48500579595565796
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.47996965050697327
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4785929024219513
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4709334671497345
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5533551573753357
Calibrated prediction for BCH: 0.5714285969734192
Raw prediction for BHP: 0.4889872074127197
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.562815248966217
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.491577684879303
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48898375034332275
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.49943509697914124
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5150482058525085
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47773951292037964
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.534191906452179
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5366089344024658
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5540064573287964
Calibrated prediction for CHTR: 0.5833333134651184
Raw prediction for CMCSA: 0.48820582032203674
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4111648499965668
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4868074655532837
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49203383922576904
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5124140977859497
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5076037645339966
Calibrated prediction for DHR: 0.5037593841552734
Raw prediction for DIS: 0.49666085839271545
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5596991181373596
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5077770352363586
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5140526294708252
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5295946598052979
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.48132649064064026
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.6222404837608337
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.4651382863521576
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.522793710231781
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6477422714233398
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5230547785758972
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.5918677449226379
Calibrated prediction for IEP: 0.6000000238418579
Raw prediction for INTC: 0.5352069735527039
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.35009387135505676
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.543503999710083
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46779540181159973
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5337328910827637
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5470640063285828
Calibrated prediction for MA: 0.6666666865348816
Raw prediction for MCD: 0.5264390110969543
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5051348209381104
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5668357014656067
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5745238065719604
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4684992730617523
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5275320410728455
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5469397306442261
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49184295535087585
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.49008795619010925
Calibrated prediction for NVS: 0.5436900854110718
Raw prediction for ORCL: 0.44751304388046265
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.520767331123352
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5833588242530823
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47505801916122437
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4660148322582245
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4368622601032257
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.5109763145446777
Calibrated prediction for PICO: 0.5192241072654724
Raw prediction for PM: 0.5373191237449646
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5235424637794495
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4479702115058899
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5027086138725281
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.4793959856033325
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.43175452947616577
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.5080870389938354
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5022853016853333
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5040953159332275
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4498271942138672
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.49638625979423523
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.5266373157501221
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.5348076820373535
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.4914000630378723
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5441087484359741
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46699437499046326
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3840349018573761
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4929371476173401
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4905627965927124
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.3863890469074249
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.55705326795578
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.49636927247047424
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5019914507865906
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5462013483047485
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.5055729150772095
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.967, kelly=0.181) with $4532.88
[PORT] Sector Conglomerates: 7 candidates, avg score=0.490
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.971, kelly=0.309) with $7729.31
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.485
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.036, kelly=0.252) with $6311.15
[PORT] Sector Financial: 10 candidates, avg score=0.534
[PORT] Sector Financial: selecting MA (p=0.667, b=0.960, kelly=0.319) with $8000.99
[PORT] Sector Healthcare: 10 candidates, avg score=0.445
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.016, kelly=0.185) with $4643.56
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.499
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.986, kelly=0.136) with $3418.19
[PORT] Sector Services: 10 candidates, avg score=0.540
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.045, kelly=0.295) with $7398.86
[PORT] Sector Technology: 10 candidates, avg score=0.523
[PORT] Sector Technology: selecting GOOG (p=0.630, b=1.069, kelly=0.285) with $7133.62
[PORT] Sector Utilities: 10 candidates, avg score=0.535
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.901, kelly=0.185) with $4630.17

Simulating Trading Days:   6%|▌         | 6/100 [04:25<24:54, 15.90s/it]

Raw prediction for AAPL: 0.49969595670700073
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5140458345413208
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24295374751091003
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5621829032897949
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4970109164714813
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5130243301391602
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6316436529159546
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.4855363667011261
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.47837668657302856
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4789034128189087
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4740733802318573
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5503585338592529
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4889222979545593
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5488265752792358
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.49166953563690186
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4888852536678314
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.49310654401779175
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5148921608924866
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47778505086898804
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.533959686756134
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5379088521003723
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5590672492980957
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5195109844207764
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4276898503303528
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4850292503833771
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49207407236099243
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5124676823616028
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5074195265769958
Calibrated prediction for DHR: 0.5037593841552734
Raw prediction for DIS: 0.4971528947353363
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5512306094169617
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5084236860275269
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5139744877815247
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5295766592025757
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4764159917831421
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.6123598217964172
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.4730287194252014
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5257148742675781
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6488685011863708
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5287778377532959
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.5977519154548645
Calibrated prediction for IEP: 0.6000000238418579
Raw prediction for INTC: 0.5268142819404602
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.36975526809692383
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5434389710426331
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46768417954444885
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5374915599822998
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5278986096382141
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5262887477874756
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5022202134132385
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5670304298400879
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5658771991729736
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4687027931213379
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5273522138595581
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5418035387992859
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49110928177833557
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.489149808883667
Calibrated prediction for NVS: 0.5436900854110718
Raw prediction for ORCL: 0.4464612603187561
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5208385586738586
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5853374004364014
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4748040437698364
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4659137725830078
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43666326999664307
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.5085767507553101
Calibrated prediction for PICO: 0.5192241072654724
Raw prediction for PM: 0.5266675353050232
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5195283889770508
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4534452259540558
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5067066550254822
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.4793192744255066
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.4332863688468933
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4994937479496002
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5025334358215332
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5039833784103394
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.450283020734787
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4649668335914612
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.5257911682128906
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.5359600186347961
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.5035144090652466
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5411432385444641
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4651748538017273
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.36272984743118286
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.48708605766296387
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49089959263801575
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.3825722336769104
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5569131374359131
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5016310811042786
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5024904608726501
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.543255627155304
Calibrated prediction for WMT: 0.5098039507865906

Simulating Trading Days:   7%|▋         | 7/100 [04:26<17:09, 11.07s/it]

Raw prediction for XOM: 0.505911111831665
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.494
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.967, kelly=0.181) with $4544.90
[PORT] Sector Conglomerates: 7 candidates, avg score=0.490
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.971, kelly=0.309) with $7744.89
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.472
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.985, kelly=0.074) with $1855.23
[PORT] Sector Financial: 10 candidates, avg score=0.522
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4351.09
[PORT] Sector Healthcare: 10 candidates, avg score=0.448
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.019, kelly=0.186) with $4678.45
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.499
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.988, kelly=0.137) with $3446.34
[PORT] Sector Services: 10 candidates, avg score=0.543
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.047, kelly=0.296) with $7435.99
[PORT] Sector Technology: 10 candidates, avg score=0.523
[PORT] Sector Technology: selecting GOOG (p=0.630, b=1.067, kelly=0.284) with $7129.92
[PORT] Sector Utilities: 10 candidates, avg score=0.536
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.903, kelly=0.186) with $4658.20
Raw prediction for AAPL: 0.4997289478778839
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5162218809127808
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24415507912635803
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5619583129882812
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.49603143334388733
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5132301449775696
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.639335572719574
Calibrated prediction for AMZN: 0.600551187992096
Raw prediction for BA: 0.4847368597984314
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.47780176997184753
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47854775190353394
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.48239123821258545
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.552824079990387
Calibrated prediction for BCH: 0.5714285969734192
Raw prediction for BHP: 0.4890243411064148
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5300264358520508
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4919860363006592
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48885950446128845
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.48787230253219604
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5147232413291931
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4775690734386444
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.5376462936401367
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5451467633247375
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5476468205451965
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.5391629934310913
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.44545456767082214
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4823407530784607
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4925871789455414
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5124359726905823
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5067445039749146
Calibrated prediction for DHR: 0.5037593841552734
Raw prediction for DIS: 0.4976048171520233
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5407063961029053
Calibrated prediction for DUK: 0.6000000238418579
Raw prediction for EXC: 0.5096485018730164
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5136293768882751
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5295702815055847
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4684823751449585
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.5948320031166077
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.4806108772754669
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.527653157711029
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6510403752326965
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5299549698829651
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.6040626168251038
Calibrated prediction for IEP: 0.6616165041923523
Raw prediction for INTC: 0.5185658931732178
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3835744857788086
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5430622696876526
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4676351547241211
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5404338240623474
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5097277164459229
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5259973406791687
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.49797672033309937
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5648088455200195
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5548113584518433
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46860015392303467
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5225076079368591
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5385652780532837
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49162793159484863
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4916287362575531
Calibrated prediction for NVS: 0.5436900854110718
Raw prediction for ORCL: 0.44544246792793274
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5209976434707642
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5867369771003723
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.474582701921463
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.465884804725647
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43653979897499084
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.503527820110321
Calibrated prediction for PICO: 0.5192241072654724
Raw prediction for PM: 0.5195097327232361
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5153647661209106
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.46378228068351746
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5131726861000061
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.49034616351127625
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.43761926889419556
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4878387749195099
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5027593970298767
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5037168264389038
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.45055192708969116
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4388638734817505
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5250731110572815
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.5231512188911438
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.5163102746009827
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5443261861801147
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46395114064216614
Calibrated prediction for UL: 0.45108622312545776

Simulating Trading Days:   8%|▊         | 8/100 [04:27<12:07,  7.91s/it]

Raw prediction for UN: 0.35023513436317444
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.47831854224205017
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49108096957206726
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.378846138715744
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5573304295539856
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5102800726890564
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.5029586553573608
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5397404432296753
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.5058795809745789
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.967, kelly=0.181) with $4536.01
[PORT] Sector Conglomerates: 7 candidates, avg score=0.499
[PORT] Sector Conglomerates: selecting IEP (p=0.662, b=0.985, kelly=0.318) with $7980.63
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.469
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.984, kelly=0.074) with $1844.42
[PORT] Sector Financial: 10 candidates, avg score=0.527
[PORT] Sector Financial: selecting V (p=0.581, b=1.029, kelly=0.174) with $4364.66
[PORT] Sector Healthcare: 10 candidates, avg score=0.448
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.017, kelly=0.186) with $4655.81
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.499
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.988, kelly=0.137) with $3444.83
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.050, kelly=0.297) with $7451.12
[PORT] Sector Technology: 10 candidates, avg score=0.525
[PORT] Sector Technology: selecting GOOG (p=0.630, b=1.066, kelly=0.284) with $7112.88
[PORT] Sector Utilities: 10 candidates, avg score=0.526
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.904, kelly=0.186) with $4671.04
Raw prediction for AAPL: 0.4997141659259796
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5189026594161987
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24406591057777405
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5634820461273193
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.495002418756485
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5134226083755493
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6443473696708679
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.4826054871082306
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.4804188013076782
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4772331714630127
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.49330997467041016
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.5510886311531067
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4891979396343231
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5086528062820435
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4920283555984497
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.488803893327713
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.4906482994556427
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5147222280502319
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4774085581302643
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.543774425983429
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.553476870059967
Calibrated prediction for CHL: 0.5960887670516968
Raw prediction for CHTR: 0.5297319293022156
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.5453651547431946
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4638780951499939
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4783230125904083
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49377894401550293
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5123471021652222
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5095822811126709
Calibrated prediction for DHR: 0.5037593841552734
Raw prediction for DIS: 0.4980730414390564
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5372722744941711
Calibrated prediction for DUK: 0.6000000238418579
Raw prediction for EXC: 0.5110313296318054
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5131933093070984
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5298121571540833
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.46525371074676514
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.5744021534919739
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.48611971735954285
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5280151963233948
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6513972878456116
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5230146646499634
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.6094513535499573
Calibrated prediction for IEP: 0.6616165041923523
Raw prediction for INTC: 0.511996865272522
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.3988244831562042
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5421871542930603
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4680206775665283
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5714210271835327
Calibrated prediction for LMT: 0.6242910027503967
Raw prediction for MA: 0.47764673829078674
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5256583094596863
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4919135570526123
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5661885142326355
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5492103099822998
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46848562359809875
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5137320160865784
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5390920639038086
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4935697615146637
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4927716851234436
Calibrated prediction for NVS: 0.5436900854110718
Raw prediction for ORCL: 0.4429689645767212
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5210784673690796
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5911258459091187
Calibrated prediction for PCLN: 0.6414930820465088
Raw prediction for PEP: 0.4746369421482086
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4657999873161316
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43666085600852966
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.49879103899002075
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.544060468673706
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5099217891693115
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4709794223308563
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5253138542175293
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5059335231781006
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.44673967361450195
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4794771373271942
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5028609037399292
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5034132599830627
Calibrated prediction for SO: 0.5042282938957214

Simulating Trading Days:   9%|▉         | 9/100 [04:28<08:46,  5.78s/it]

Raw prediction for SPLP: 0.4504658877849579
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.42903056740760803
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5234317183494568
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.53160560131073
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.511823832988739
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5428639054298401
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46440649032592773
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34876585006713867
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4667704999446869
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4909530282020569
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.3944883346557617
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5570375323295593
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5193349719047546
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.5031129717826843
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.537134051322937
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.5057533979415894
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.503
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.893, kelly=0.152) with $3831.39
[PORT] Sector Conglomerates: 7 candidates, avg score=0.493
[PORT] Sector Conglomerates: selecting IEP (p=0.662, b=0.987, kelly=0.319) with $8041.01
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.472
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.982, kelly=0.073) with $1831.27
[PORT] Sector Financial: 10 candidates, avg score=0.517
[PORT] Sector Financial: selecting V (p=0.581, b=1.029, kelly=0.174) with $4389.75
[PORT] Sector Healthcare: 10 candidates, avg score=0.469
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.018, kelly=0.186) with $4694.11
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.508
[PORT] Sector Industrial Goods: selecting LMT (p=0.624, b=1.068, kelly=0.273) with $6876.75
[PORT] Sector Services: 10 candidates, avg score=0.543
[PORT] Sector Services: selecting PCLN (p=0.641, b=1.051, kelly=0.300) with $7579.71
[PORT] Sector Technology: 10 candidates, avg score=0.526
[PORT] Sector Technology: selecting GOOG (p=0.630, b=1.063, kelly=0.283) with $7135.98
[PORT] Sector Utilities: 10 candidates, avg score=0.523
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.903, kelly=0.186) with $4691.91
Raw prediction for AAPL: 0.4998615086078644
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5203943252563477
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24727025628089905
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5654007792472839
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.49386829137802124
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5137119293212891
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6544469594955444
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.4796823263168335
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.48476895689964294
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4761727750301361
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.501635730266571
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5554090738296509
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.4892696142196655
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4894821345806122
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49223092198371887
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4887000620365143
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.49505582451820374
Calibrated prediction for BUD: 0.5060755014419556
Raw prediction for C: 0.5146985054016113
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4772164523601532
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.5534802675247192
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5646743774414062
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.5191585421562195
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.5343872904777527
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.47527459263801575
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47341760993003845
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4952552020549774
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5124003887176514
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5133565664291382
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4983716905117035
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5423380136489868
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5121426582336426
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5130361318588257
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5300336480140686
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4684133231639862
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.5542694926261902
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.48990893363952637
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5232042074203491
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6520472168922424
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5129321813583374
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.6086810231208801
Calibrated prediction for IEP: 0.6616165041923523
Raw prediction for INTC: 0.5062357187271118
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4142405390739441
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5413670539855957
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.468449205160141
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6033147573471069
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4674416482448578
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5253082513809204
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4854235351085663
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5662292838096619
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5429292321205139
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4686199724674225
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.49894461035728455
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.540643572807312
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49562713503837585
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.49332889914512634
Calibrated prediction for NVS: 0.5436900854110718
Raw prediction for ORCL: 0.4422720670700073
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.521151602268219
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5976162552833557
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.4747338593006134
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46581193804740906
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4367647171020508
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.49482956528663635
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5680901408195496
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5050863027572632
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.47781071066856384
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5386690497398376
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5201033353805542
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.45843616127967834
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.47431328892707825
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.502997636795044
Calibrated prediction for SNY: 0.5023937821388245

Simulating Trading Days:  10%|█         | 10/100 [04:29<06:31,  4.34s/it]

Raw prediction for SO: 0.5032305121421814
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4500167667865753
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.42821812629699707
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5239293575286865
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.49975693225860596
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.49352672696113586
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5412137508392334
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46473923325538635
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34562382102012634
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4590494930744171
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4905489683151245
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.38809144496917725
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5588459968566895
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5298283100128174
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.503168523311615
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5358684659004211
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.5047606229782104
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.504
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.894, kelly=0.153) with $3847.79
[PORT] Sector Conglomerates: 7 candidates, avg score=0.493
[PORT] Sector Conglomerates: selecting IEP (p=0.662, b=0.987, kelly=0.319) with $8035.94
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.470
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.984, kelly=0.074) with $1858.23
[PORT] Sector Financial: 10 candidates, avg score=0.515
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.986, kelly=0.194) with $4902.35
[PORT] Sector Healthcare: 10 candidates, avg score=0.469
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.016, kelly=0.186) with $4680.29
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.509
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.070, kelly=0.274) with $6919.67
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.055, kelly=0.304) with $7671.59
[PORT] Sector Technology: 10 candidates, avg score=0.540
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.095, kelly=0.362) with $9134.73
[PORT] Sector Utilities: 10 candidates, avg score=0.523
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.902, kelly=0.185) with $4670.58
Raw prediction for AAPL: 0.49975812435150146
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5188743472099304
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.23881930112838745
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.566121518611908
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.49214619398117065
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5134375095367432
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6563383340835571
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.4760779142379761
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.48677176237106323
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4743519127368927
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.5062933564186096
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.559913694858551
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.4894900321960449
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.48346978425979614
Calibrated prediction for BP: 0.5
Raw prediction for BRK-A: 0.49262502789497375
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4883459806442261
Calibrated prediction for BSAC: 0.48750001192092896
Raw prediction for BUD: 0.4941738545894623
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5148913264274597
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4767780303955078
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.5635021328926086
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.573284387588501
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.5140156745910645
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.521694540977478
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4693009555339813
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4663865864276886
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4966914653778076
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.512508749961853
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5161062479019165
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4982761740684509
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.548914909362793
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5117097496986389
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5129681825637817
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5302874445915222
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4710760712623596
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.5336214303970337
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.49312901496887207
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5096166729927063
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.6513260006904602
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5027625560760498
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.5906832218170166
Calibrated prediction for IEP: 0.6000000238418579
Raw prediction for INTC: 0.4980256259441376
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4404381513595581
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.539850652217865
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46890777349472046
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6171696186065674
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4558640718460083
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5248746275901794
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.48247379064559937
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5615677237510681
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5424116849899292
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46887537837028503
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.47891730070114136
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.541391909122467
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49632152915000916
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.48615729808807373
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43970003724098206
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5212181806564331
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6081852912902832
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.4749118983745575
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46562743186950684
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43689391016960144
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.49122193455696106
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5860821008682251
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5016606450080872
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.48082712292671204
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5483678579330444
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5319682359695435
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.4738645553588867
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4708550274372101
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5027772188186646
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5030673742294312
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.449196457862854
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4267464876174927
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5246421694755554
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.47774115204811096
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.48684871196746826
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5254749655723572
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46541643142700195
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34028083086013794
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.44780802726745605
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4897480905056
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.3890492022037506
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5590001344680786
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5377751588821411
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5034144520759583
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5317224860191345
Calibrated prediction for WMT: 0.5098039507865906

Simulating Trading Days:  11%|█         | 11/100 [04:30<04:58,  3.35s/it]

Raw prediction for XOM: 0.5024109482765198
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.503
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.893, kelly=0.152) with $3839.60
[PORT] Sector Conglomerates: 7 candidates, avg score=0.485
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.972, kelly=0.309) with $7801.54
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.470
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.986, kelly=0.075) with $1888.57
[PORT] Sector Financial: 10 candidates, avg score=0.512
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.986, kelly=0.194) with $4908.39
[PORT] Sector Healthcare: 10 candidates, avg score=0.449
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.017, kelly=0.186) with $4696.81
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.509
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.064, kelly=0.272) with $6881.66
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.052, kelly=0.303) with $7664.79
[PORT] Sector Technology: 10 candidates, avg score=0.530
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.094, kelly=0.362) with $9141.37
[PORT] Sector Utilities: 10 candidates, avg score=0.523
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.904, kelly=0.186) with $4704.22
Raw prediction for AAPL: 0.499860554933548
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5174161791801453
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.23055167496204376
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5633554458618164
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4897202253341675
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5129900574684143
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.675007700920105
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.47255587577819824
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.4894498288631439
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47222140431404114
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5085184574127197
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5649399757385254
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.4892621636390686
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4825029969215393
Calibrated prediction for BP: 0.5
Raw prediction for BRK-A: 0.4928135871887207
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4879424571990967
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48835092782974243
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5152663588523865
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4764172434806824
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.5721734762191772
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5824708938598633
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.5254720449447632
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.5062484741210938
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.46223053336143494
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.45875075459480286
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49816131591796875
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.512531042098999
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5190474987030029
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49787935614585876
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.552469789981842
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5112910866737366
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5127159357070923
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5307413935661316
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.47568273544311523
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.5137758255004883
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.49328503012657166
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5025950074195862
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6505842208862305
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.491499125957489
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.5624849200248718
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.49234074354171753
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4649101793766022
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5380423665046692
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46930840611457825
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6397492289543152
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.45058995485305786
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.524480402469635
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4817631244659424
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5632101893424988
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5405315160751343
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4689432978630066
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.45924943685531616
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5401109457015991
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4964779019355774
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.47720450162887573
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4374711811542511
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5211923122406006
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6174002885818481
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4750138223171234
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4654389023780823
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4370458722114563
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.48835575580596924
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5880163908004761
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.4991376996040344
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4796956181526184
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5441503524780273
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.543632984161377
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.48905012011528015
Calibrated prediction for SLB: 0.47480109333992004
Raw prediction for SNP: 0.46916189789772034
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5025730729103088
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5028752088546753
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4427078366279602
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.42407190799713135
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5274178385734558
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.4362793266773224
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.45834508538246155
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5041174292564392
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.465229868888855
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.33190086483955383
Calibrated prediction for UN: 0.4285714328289032

Simulating Trading Days:  12%|█▏        | 12/100 [04:32<03:55,  2.67s/it]

Raw prediction for UNH: 0.43824610114097595
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48885226249694824
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.4446679651737213
Calibrated prediction for UTX: 0.46666666865348816
Raw prediction for V: 0.5590270161628723
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5406316518783569
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5039591193199158
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5258333683013916
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.49973878264427185
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.508
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.894, kelly=0.152) with $3856.51
[PORT] Sector Conglomerates: 7 candidates, avg score=0.485
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.972, kelly=0.309) with $7822.29
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.475
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.032, kelly=0.105) with $2657.49
[PORT] Sector Financial: 10 candidates, avg score=0.511
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.984, kelly=0.193) with $4895.69
[PORT] Sector Healthcare: 10 candidates, avg score=0.449
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.019, kelly=0.187) with $4728.63
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.517
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.061, kelly=0.272) with $6877.91
[PORT] Sector Services: 10 candidates, avg score=0.543
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.050, kelly=0.330) with $8360.03
[PORT] Sector Technology: 10 candidates, avg score=0.513
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.096, kelly=0.363) with $9178.59
[PORT] Sector Utilities: 10 candidates, avg score=0.523
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.906, kelly=0.187) with $4735.94
Raw prediction for AAPL: 0.5000333786010742
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5131329894065857
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.235616073012352
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5624541640281677
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.48819223046302795
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5122101902961731
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6994664669036865
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4703950583934784
Calibrated prediction for BA: 0.5
Raw prediction for BABA: 0.4946162700653076
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4702090322971344
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5105572938919067
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5693573951721191
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.4888576865196228
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4823158085346222
Calibrated prediction for BP: 0.5
Raw prediction for BRK-A: 0.49287357926368713
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48763105273246765
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48966798186302185
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5158370733261108
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4759064018726349
Calibrated prediction for CAT: 0.4752475321292877
Raw prediction for CELG: 0.5766770243644714
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.590006947517395
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.5326654314994812
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.47807440161705017
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.45207008719444275
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.45347532629966736
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.4991374611854553
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5124768018722534
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5195462107658386
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49757760763168335
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5476698279380798
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5110717415809631
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5126542448997498
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5309072136878967
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4709164500236511
Calibrated prediction for GE: 0.43939393758773804
Raw prediction for GOOG: 0.4988243877887726
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.49044185876846313
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4941163957118988
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6495133638381958
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.4837467670440674
Calibrated prediction for HSBC: 0.47947418689727783
Raw prediction for IEP: 0.5319119095802307
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.48979875445365906
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.48064088821411133
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5358368158340454
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4697549045085907
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6265372037887573
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.44767501950263977
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5243285298347473
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4804284870624542
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5604699850082397
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5419831275939941
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4685428738594055
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.44299396872520447
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.538326621055603
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49668997526168823
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4674999713897705
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4357391595840454
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.521080732345581
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6183369755744934
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47520706057548523
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46511709690093994
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43740928173065186
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.48598936200141907
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5871260166168213
Calibrated prediction for PM: 0.5016650557518005
Raw prediction for PPL: 0.4981686472892761
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.47536998987197876
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5345655083656311
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5516343116760254
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4986904561519623
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4696148633956909
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5024639368057251
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5026402473449707
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.4343985617160797
Calibrated prediction for SPLP: 0.30125677585601807

Simulating Trading Days:  13%|█▎        | 13/100 [04:33<03:11,  2.20s/it]

Raw prediction for SRE: 0.4215555787086487
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5260306596755981
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.39668893814086914
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.43889546394348145
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4909343421459198
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4648391306400299
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3253540098667145
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4322185814380646
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48806095123291016
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.49449649453163147
Calibrated prediction for UTX: 0.5
Raw prediction for V: 0.5600568652153015
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5389727354049683
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5042557716369629
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5253974795341492
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.49810048937797546
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.491
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.895, kelly=0.153) with $3868.33
[PORT] Sector Conglomerates: 7 candidates, avg score=0.485
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.972, kelly=0.309) with $7818.54
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.464
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.982, kelly=0.073) with $1842.96
[PORT] Sector Financial: 10 candidates, avg score=0.511
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.986, kelly=0.194) with $4919.73
[PORT] Sector Healthcare: 10 candidates, avg score=0.449
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.020, kelly=0.187) with $4736.15
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.517
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.060, kelly=0.271) with $6863.51
[PORT] Sector Services: 10 candidates, avg score=0.568
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.056, kelly=0.744) with $18840.80
[PORT] Sector Technology: 10 candidates, avg score=0.513
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.098, kelly=0.363) with $9191.45
[PORT] Sector Utilities: 10 candidates, avg score=0.523
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.905, kelly=0.187) with $4728.65
Raw prediction for AAPL: 0.5001897811889648
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5082333087921143
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24246425926685333
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.559787392616272
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.48586389422416687
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5116143822669983
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7076207995414734
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4690372943878174
Calibrated prediction for BA: 0.49324214458465576
Raw prediction for BABA: 0.4975360333919525
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4683811068534851
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5150550007820129
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5772860050201416
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.48891136050224304
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.48730677366256714
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4928719699382782
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48745787143707275
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4886491000652313
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5161928534507751
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47530508041381836
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5762037634849548
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5958583950996399
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.5336688160896301
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.45460933446884155
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4469187557697296
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.44950395822525024
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49891552329063416
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5124596357345581
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5198319554328918
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4974376857280731
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5350865125656128
Calibrated prediction for DUK: 0.5903108716011047
Raw prediction for EXC: 0.5110031366348267
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5127630233764648
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5310924649238586
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.46296676993370056
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4851430356502533
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4867401421070099
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4857436418533325
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6485515236854553
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.483889639377594
Calibrated prediction for HSBC: 0.48429176211357117
Raw prediction for IEP: 0.5043626427650452
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.48923665285110474
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.48948997259140015
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5338912606239319
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47010692954063416
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6082805395126343
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.44867780804634094
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5242969393730164
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.47787073254585266
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5573719143867493
Calibrated prediction for MMM: 0.5454545617103577
Raw prediction for MO: 0.5380258560180664
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4679872691631317
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.43169966340065
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.536410927772522
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4962572753429413
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.45556455850601196
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4352455735206604
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5209919214248657
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6198164820671082
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.475464403629303
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4646453559398651
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4374559819698334
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.48433005809783936
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5825085043907166
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49614909291267395
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4700079560279846
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5313255786895752
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5555558800697327
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5053560733795166
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4710627496242523
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5024029016494751
Calibrated prediction for SNY: 0.5023937821388245

Simulating Trading Days:  14%|█▍        | 14/100 [04:34<02:40,  1.87s/it]

Raw prediction for SO: 0.5024572610855103
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.4257510006427765
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.41885924339294434
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5243217945098877
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.3482978641986847
Calibrated prediction for TM: 0.3076923191547394
Raw prediction for TOT: 0.44912877678871155
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.48967987298965454
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46341925859451294
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.318219929933548
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4270179867744446
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48734617233276367
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.5573049187660217
Calibrated prediction for UTX: 0.5555555820465088
Raw prediction for V: 0.5629144906997681
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5348240733146667
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5044897794723511
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.52452552318573
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.49875617027282715
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.513
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.892, kelly=0.152) with $3861.25
[PORT] Sector Conglomerates: 7 candidates, avg score=0.485
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.974, kelly=0.310) with $7875.16
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.461
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.981, kelly=0.072) with $1837.66
[PORT] Sector Financial: 10 candidates, avg score=0.511
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.988, kelly=0.202) with $5143.98
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.018, kelly=0.186) with $4735.31
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.519
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.060, kelly=0.271) with $6899.96
[PORT] Sector Services: 10 candidates, avg score=0.552
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $18928.67
[PORT] Sector Technology: 10 candidates, avg score=0.513
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.101, kelly=0.364) with $9252.14
[PORT] Sector Utilities: 10 candidates, avg score=0.521
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.907, kelly=0.187) with $4768.61
Raw prediction for AAPL: 0.5002077221870422
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.503092348575592
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.257996141910553
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5599743127822876
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.48364758491516113
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5112929344177246
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7161243557929993
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46836090087890625
Calibrated prediction for BA: 0.48070111870765686
Raw prediction for BABA: 0.5023078918457031
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46669045090675354
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5168505907058716
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5832441449165344
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.48891985416412354
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4876669645309448
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4927913546562195
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.487495481967926
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4886643588542938
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.516363799571991
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47460708022117615
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5676417946815491
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.6009982228279114
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.539322555065155
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.42071861028671265
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44463449716567993
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4427269697189331
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49824854731559753
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5124502778053284
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5199711322784424
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4973333477973938
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5244246125221252
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5112208127975464
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5131497979164124
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5311362147331238
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.45968976616859436
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.46824273467063904
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4857660233974457
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47914013266563416
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6482123732566833
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.4859686493873596
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.4808958172798157
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.4829844832420349
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4924015402793884
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5323872566223145
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4704188108444214
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5923501253128052
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4525199234485626
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.524437427520752
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4711734354496002
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5545031428337097
Calibrated prediction for MMM: 0.5433070659637451
Raw prediction for MO: 0.536043643951416
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4674100875854492
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.42559221386909485
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5352534055709839
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49613383412361145
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4468666613101959
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43391770124435425
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5210301280021667
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6095612645149231
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47578224539756775
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4640897512435913
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4375265836715698
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4831271469593048
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5813407897949219
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49457573890686035
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4666626453399658
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5287516713142395
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.553881049156189
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5098234415054321
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.47325992584228516
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5024054050445557
Calibrated prediction for SNY: 0.5023937821388245

Simulating Trading Days:  15%|█▌        | 15/100 [04:35<02:19,  1.64s/it]

Raw prediction for SO: 0.5026743412017822
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.41822391748428345
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.425786554813385
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5260306000709534
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.32804328203201294
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.4584929943084717
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4847884774208069
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4623240530490875
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.31942465901374817
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.424896776676178
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48700428009033203
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.5665041208267212
Calibrated prediction for UTX: 0.5555555820465088
Raw prediction for V: 0.5666887164115906
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5357574224472046
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.504433274269104
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5245842337608337
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.4967172145843506
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.513
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.895, kelly=0.153) with $3877.53
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.972, kelly=0.309) with $7839.19
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.460
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.979, kelly=0.071) with $1805.34
[PORT] Sector Financial: 10 candidates, avg score=0.512
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.987, kelly=0.202) with $5120.30
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.016, kelly=0.185) with $4698.96
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.517
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.062, kelly=0.272) with $6894.28
[PORT] Sector Services: 10 candidates, avg score=0.551
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.057, kelly=0.745) with $18888.86
[PORT] Sector Technology: 10 candidates, avg score=0.513
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.098, kelly=0.363) with $9211.33
[PORT] Sector Utilities: 10 candidates, avg score=0.515
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.908, kelly=0.188) with $4769.26
Raw prediction for AAPL: 0.5002528429031372
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.49796411395072937
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.27422279119491577
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5602597594261169
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.481197714805603
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5112760663032532
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7199659943580627
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4686298966407776
Calibrated prediction for BA: 0.48568856716156006
Raw prediction for BABA: 0.5081316828727722
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46514225006103516
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5155320763587952
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5867316126823425
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.48874014616012573
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4868637025356293
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4926588237285614
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48739975690841675
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.49592599272727966
Calibrated prediction for BUD: 0.5455928444862366
Raw prediction for C: 0.5162951350212097
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4738560914993286
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5567873120307922
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.6024579405784607
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.547219455242157
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.40411001443862915
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44657158851623535
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.43700990080833435
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49742257595062256
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5123087763786316
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5197675824165344
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49700692296028137
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5197921395301819
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5110270977020264
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5131807923316956
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5311444401741028
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.45490044355392456
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4519524574279785
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.489159494638443
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.472860187292099
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6477869749069214
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.4875538647174835
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.46164634823799133
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.47247445583343506
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.49325358867645264
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5316087007522583
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47071513533592224
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5806995630264282
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4528678059577942
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5246167182922363
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4647156298160553
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5523098111152649
Calibrated prediction for MMM: 0.5433070659637451
Raw prediction for MO: 0.5376806259155273
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4670941233634949
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4286612868309021
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5345985889434814
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.496422678232193
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4405214190483093
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43257325887680054
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5208520889282227
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5983608961105347
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47625982761383057
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4639347195625305
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4378046989440918
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4820198118686676
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5839217901229858
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49469298124313354
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4652746021747589
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5275578498840332
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5536341667175293
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5115864872932434
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.47685012221336365
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5025290846824646
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.502900242805481
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.41380929946899414
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4410870373249054
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.534747302532196
Calibrated prediction for T: 0.5185185074806213
Raw prediction for TM: 0.3299318850040436
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.4544614851474762
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.47618845105171204
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.46207287907600403
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3274083435535431
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4262862205505371
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48701661825180054
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.5655104517936707
Calibrated prediction for UTX: 0.5555555820465088
Raw prediction for V: 0.5685782432556152
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5359082818031311
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5042659640312195
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.521099328994751
Calibrated prediction for WMT: 0.5098039507865906

Simulating Trading Days:  16%|█▌        | 16/100 [04:36<02:04,  1.48s/it]

Raw prediction for XOM: 0.49295058846473694
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.513
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.896, kelly=0.154) with $3889.96
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.955, kelly=0.303) with $7674.02
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.465
[PORT] Sector Consumer Goods: selecting BUD (p=0.546, b=1.039, kelly=0.108) with $2740.46
[PORT] Sector Financial: 10 candidates, avg score=0.512
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.988, kelly=0.202) with $5115.74
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.018, kelly=0.186) with $4716.32
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.518
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.060, kelly=0.271) with $6875.38
[PORT] Sector Services: 10 candidates, avg score=0.551
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.060, kelly=0.745) with $18872.83
[PORT] Sector Technology: 10 candidates, avg score=0.500
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.100, kelly=0.364) with $9212.49
[PORT] Sector Utilities: 10 candidates, avg score=0.516
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.908, kelly=0.188) with $4762.78
Raw prediction for AAPL: 0.5004119873046875
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.49324843287467957
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.28556403517723083
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5630306005477905
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4786404073238373
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5111246109008789
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.723228931427002
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4690738022327423
Calibrated prediction for BA: 0.4939190149307251
Raw prediction for BABA: 0.5143332481384277
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46410059928894043
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5167705416679382
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5869590640068054
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.48863306641578674
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.48607924580574036
Calibrated prediction for BP: 0.5225105285644531
Raw prediction for BRK-A: 0.49252378940582275
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4873175323009491
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5033281445503235
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.516159176826477
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47331520915031433
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5469089150428772
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.6085414886474609
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.5661823153495789
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3946741819381714
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.450006365776062
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4328082799911499
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.4959021806716919
Calibrated prediction for CVX: 0.5
Raw prediction for D: 0.5122332572937012
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5194233059883118
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49633175134658813
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5222094058990479
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5106837749481201
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5131934285163879
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5313253998756409
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4523848295211792
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4372112452983856
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4970209300518036
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.46664249897003174
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6510545015335083
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.49557945132255554
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.44802266359329224
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.4616241455078125
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4957320988178253
Calibrated prediction for JNJ: 0.5081967115402222
Raw prediction for JPM: 0.5315249562263489
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4707564115524292
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5747571587562561
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4522453248500824
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5248668193817139
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.460671067237854
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5516494512557983
Calibrated prediction for MMM: 0.5433070659637451
Raw prediction for MO: 0.5402882695198059
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.466768741607666
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.43299663066864014
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.534554123878479
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49627313017845154
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4353436827659607
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4305110275745392
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5206758975982666
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.583142101764679
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4766791760921478
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46420952677726746
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43820685148239136
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.47945335507392883
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5827523469924927
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49528777599334717
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.46827009320259094
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5311017036437988
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5522591471672058
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5133731961250305
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.47920674085617065
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5027216076850891
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5032941699028015
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.40851670503616333
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4574423134326935
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.5474587678909302
Calibrated prediction for T: 0.5555555820465088
Raw prediction for TM: 0.3347730040550232
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.45688024163246155
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.46658164262771606
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.46100372076034546
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3312698006629944
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.42889297008514404
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48727479577064514
Calibrated prediction for UPS: 0.4941723644733429

Simulating Trading Days:  17%|█▋        | 17/100 [04:37<01:53,  1.37s/it]

Raw prediction for UTX: 0.5498893857002258
Calibrated prediction for UTX: 0.5555555820465088
Raw prediction for V: 0.5683919787406921
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5397578477859497
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5040131211280823
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5172752141952515
Calibrated prediction for WMT: 0.5098039507865906
Raw prediction for XOM: 0.4892542064189911
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.510
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.895, kelly=0.153) with $3883.58
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.954, kelly=0.303) with $7662.93
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.472
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.038, kelly=0.253) with $6404.83
[PORT] Sector Financial: 10 candidates, avg score=0.512
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.987, kelly=0.202) with $5111.55
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.020, kelly=0.187) with $4735.60
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.519
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.058, kelly=0.271) with $6853.04
[PORT] Sector Services: 10 candidates, avg score=0.557
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.061, kelly=0.745) with $18870.80
[PORT] Sector Technology: 10 candidates, avg score=0.503
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.098, kelly=0.363) with $9194.93
[PORT] Sector Utilities: 10 candidates, avg score=0.526
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.910, kelly=0.189) with $4785.93
Raw prediction for AAPL: 0.500527560710907
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.4893505275249481
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3058738708496094
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.563961923122406
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.47687700390815735
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5109246969223022
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7290518879890442
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.469926118850708
Calibrated prediction for BA: 0.5
Raw prediction for BABA: 0.5209599137306213
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4634064733982086
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5192427039146423
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5873517394065857
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.48889073729515076
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4846639335155487
Calibrated prediction for BP: 0.5101269483566284
Raw prediction for BRK-A: 0.49240201711654663
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4872865676879883
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5070537328720093
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5161381959915161
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47292301058769226
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5385220050811768
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.6122337579727173
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.6000584363937378
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3932736814022064
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4512457549571991
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4288044571876526
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49375006556510925
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5121946334838867
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5192719101905823
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4952700734138489
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5327839851379395
Calibrated prediction for DUK: 0.5384615659713745
Raw prediction for EXC: 0.5105741024017334
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5132120251655579
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5315454006195068
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44915392994880676
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4237513542175293
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5078778266906738
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.462188720703125
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6524427533149719
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5026949644088745
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.4400566816329956
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.4521273076534271
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.49341803789138794
Calibrated prediction for JNJ: 0.5007594227790833
Raw prediction for JPM: 0.5316120386123657
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47072073817253113
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5770602226257324
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4490211308002472
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5251252055168152
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4591972529888153
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5520678758621216
Calibrated prediction for MMM: 0.5433070659637451
Raw prediction for MO: 0.5426119565963745
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4662427604198456
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.44795137643814087
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5355235934257507
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4958476722240448
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.43326807022094727
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4293700158596039
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5205066204071045
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5836088061332703
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4770003855228424
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4646722376346588
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4385429322719574
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4749715328216553
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5763211250305176
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5001102685928345
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4758611023426056
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5284199714660645
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5491931438446045
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5148224830627441
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.479818195104599
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5030184984207153
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5037622451782227
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.40606340765953064
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4820880591869354
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.5563069581985474
Calibrated prediction for T: 0.5769744515419006
Raw prediction for TM: 0.33949047327041626
Calibrated prediction for TM: 0.3076110780239105

Simulating Trading Days:  18%|█▊        | 18/100 [04:38<01:46,  1.29s/it]

Raw prediction for TOT: 0.46537867188453674
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4560399651527405
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4603692293167114
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3347138464450836
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.43949925899505615
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4876461327075958
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.5196787118911743
Calibrated prediction for UTX: 0.5
Raw prediction for V: 0.5677141547203064
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5448471307754517
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5038389563560486
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.510876476764679
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4850873053073883
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.509
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.898, kelly=0.154) with $3915.27
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.953, kelly=0.302) with $7657.29
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.473
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.050, kelly=0.257) with $6521.91
[PORT] Sector Financial: 10 candidates, avg score=0.512
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.989, kelly=0.202) with $5133.88
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.019, kelly=0.187) with $4731.06
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.514
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.057, kelly=0.270) with $6849.78
[PORT] Sector Services: 10 candidates, avg score=0.556
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.063, kelly=0.745) with $18900.26
[PORT] Sector Technology: 10 candidates, avg score=0.505
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.096, kelly=0.362) with $9192.18
[PORT] Sector Utilities: 10 candidates, avg score=0.526
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.908, kelly=0.188) with $4772.60
Raw prediction for AAPL: 0.5002967119216919
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.4863370656967163
Calibrated prediction for ABB: 0.49367088079452515
Raw prediction for ABBV: 0.31708458065986633
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5636922121047974
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4760103225708008
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5105882883071899
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7275967001914978
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4713031053543091
Calibrated prediction for BA: 0.5134152173995972
Raw prediction for BABA: 0.5265507102012634
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46306347846984863
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5228714346885681
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5892090797424316
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.4892503321170807
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4843517541885376
Calibrated prediction for BP: 0.5073954463005066
Raw prediction for BRK-A: 0.49245527386665344
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48733294010162354
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5040185451507568
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5161930322647095
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4727564752101898
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5316370129585266
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.6086265444755554
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.6294589638710022
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3933712840080261
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.45144546031951904
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4259659945964813
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49185681343078613
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5121515393257141
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5190520882606506
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49418753385543823
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.541653037071228
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5106068849563599
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.513166069984436
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5318482518196106
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44708240032196045
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4107341766357422
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5172755718231201
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4583231508731842
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6531394124031067
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5096533894538879
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.4341253340244293
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.4453621506690979
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.49295470118522644
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.531755805015564
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.470596581697464
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5963208675384521
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4490509331226349
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.525267481803894
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.46271103620529175
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5541008710861206
Calibrated prediction for MMM: 0.5433070659637451
Raw prediction for MO: 0.5465162396430969
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.465636283159256
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.46683788299560547
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5359813570976257
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49490803480148315
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.43052175641059875
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4274648129940033
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5203622579574585
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5769675970077515
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47728443145751953
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46509087085723877
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4390866458415985
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46925339102745056
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5730180740356445
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5052042007446289
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4926770329475403
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5253276228904724
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5445475578308105
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5170844793319702
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4815984070301056
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5031930804252625
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5042575001716614
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.40529537200927734
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5119715929031372
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.5662446618080139
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.3604021370410919
Calibrated prediction for TM: 0.3076923191547394
Raw prediction for TOT: 0.47427546977996826
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4573434293270111
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.46106696128845215
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3363863229751587
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4497278332710266
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.488005131483078
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.49065321683883667
Calibrated prediction for UTX: 0.5
Raw prediction for V: 0.5669037699699402
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5512042045593262
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5036900043487549
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5084260702133179
Calibrated prediction for WMT: 0.5

Simulating Trading Days:  19%|█▉        | 19/100 [04:39<01:40,  1.24s/it]

Raw prediction for XOM: 0.4852697551250458
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.508
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.902, kelly=0.157) with $3978.52
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.952, kelly=0.302) with $7663.29
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.473
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.050, kelly=0.257) with $6533.80
[PORT] Sector Financial: 10 candidates, avg score=0.515
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.990, kelly=0.203) with $5158.95
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.018, kelly=0.186) with $4736.68
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.513
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.057, kelly=0.270) with $6868.83
[PORT] Sector Services: 10 candidates, avg score=0.556
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.065, kelly=0.745) with $18945.62
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.098, kelly=0.363) with $9226.04
[PORT] Sector Utilities: 10 candidates, avg score=0.532
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.908, kelly=0.188) with $4775.22
Raw prediction for AAPL: 0.500210702419281
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.4837667942047119
Calibrated prediction for ABB: 0.49367088079452515
Raw prediction for ABBV: 0.33403652906417847
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5610842108726501
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4753665030002594
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5102539658546448
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7247642278671265
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.47226622700691223
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.531689465045929
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4628320038318634
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5236542224884033
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5888994336128235
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.4895300269126892
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.47843021154403687
Calibrated prediction for BP: 0.5
Raw prediction for BRK-A: 0.4923841655254364
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48734867572784424
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4919874966144562
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5162938833236694
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4724869132041931
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5274590849876404
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.593718409538269
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.6341052055358887
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.40543317794799805
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4487370550632477
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4250262975692749
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49053695797920227
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5122038125991821
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5180714726448059
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.493208110332489
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5457839965820312
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5105815529823303
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5131473541259766
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5320597887039185
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44387495517730713
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.40520358085632324
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5239778161048889
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.45525237917900085
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.653059720993042
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5121802091598511
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.4316272437572479
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.4429306983947754
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4916785955429077
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5318493843078613
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47018277645111084
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6127614974975586
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4482443630695343
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5252814292907715
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.46712726354599
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5541260838508606
Calibrated prediction for MMM: 0.5433070659637451
Raw prediction for MO: 0.5445666313171387
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46499982476234436
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.48979488015174866
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5356152057647705
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4930060803890228
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4297464191913605
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4275679588317871
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5203189849853516
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5762848258018494
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4772326350212097
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46566668152809143
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4393979609012604
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46363765001296997
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5628532767295837
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5083619356155396
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5100753903388977
Calibrated prediction for PTR: 0.5
Raw prediction for RDS-B: 0.49771061539649963
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.5423941612243652
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5168293118476868
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.48238492012023926
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5034227967262268
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5046488046646118
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.40565919876098633
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.536952018737793
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5728132128715515
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.36093538999557495
Calibrated prediction for TM: 0.3076923191547394
Raw prediction for TOT: 0.46761468052864075
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.45975667238235474
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4602726101875305
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.33493512868881226
Calibrated prediction for UN: 0.4285714328289032

Simulating Trading Days:  20%|██        | 20/100 [04:40<01:36,  1.20s/it]

Raw prediction for UNH: 0.4645920395851135
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48832711577415466
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.46513643860816956
Calibrated prediction for UTX: 0.5
Raw prediction for V: 0.5671629309654236
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5546417236328125
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5034041404724121
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5059175491333008
Calibrated prediction for WMT: 0.4941715598106384
Raw prediction for XOM: 0.4844330847263336
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.508
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.981, kelly=0.187) with $4753.89
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.951, kelly=0.301) with $7659.51
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.461
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.977, kelly=0.070) with $1784.01
[PORT] Sector Financial: 10 candidates, avg score=0.515
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.986, kelly=0.201) with $5124.75
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.015, kelly=0.185) with $4706.55
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.514
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.059, kelly=0.271) with $6894.10
[PORT] Sector Services: 10 candidates, avg score=0.555
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.066, kelly=0.746) with $18968.60
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.099, kelly=0.363) with $9245.52
[PORT] Sector Utilities: 10 candidates, avg score=0.536
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.907, kelly=0.188) with $4777.35
Raw prediction for AAPL: 0.5003105401992798
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.48206549882888794
Calibrated prediction for ABB: 0.49367088079452515
Raw prediction for ABBV: 0.3533881604671478
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5600970387458801
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4748901128768921
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5100547075271606
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7183939814567566
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.47233057022094727
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5352796316146851
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4625753164291382
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5231505036354065
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5898895263671875
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.48948007822036743
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4767338037490845
Calibrated prediction for BP: 0.4615384638309479
Raw prediction for BRK-A: 0.4925050437450409
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4874236583709717
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4839647710323334
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5163050293922424
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4721660614013672
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5260028839111328
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5771245360374451
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.6436250805854797
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.42318394780158997
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44624707102775574
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4245087206363678
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.4899515211582184
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5123959183692932
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5178523063659668
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4924606382846832
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5405394434928894
Calibrated prediction for DUK: 0.6000000238418579
Raw prediction for EXC: 0.5106769800186157
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5129838585853577
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5321141481399536
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4408552944660187
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.40113258361816406
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5268793106079102
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.45302918553352356
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6523941159248352
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5172627568244934
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.4311559498310089
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.4401266574859619
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.48803287744522095
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5317650437355042
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46970951557159424
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6213066577911377
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4669244587421417
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5251995921134949
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.47285422682762146
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5538328289985657
Calibrated prediction for MMM: 0.5433070659637451
Raw prediction for MO: 0.5447407364845276
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4644511342048645
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5096103549003601
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5330858826637268
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4901394844055176
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4301641881465912
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.42764905095100403
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5202914476394653
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5772546529769897
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47704097628593445
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46613579988479614
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43975573778152466
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45754221081733704
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5528680086135864
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5075332522392273
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.527631402015686
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.46398842334747314
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.542299211025238
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5091640949249268
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4840116798877716
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5038659572601318
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5047625303268433
Calibrated prediction for SO: 0.5042282938957214

Simulating Trading Days:  21%|██        | 21/100 [04:42<01:33,  1.18s/it]

Raw prediction for SPLP: 0.40394484996795654
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5516292452812195
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5706424117088318
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.3703436553478241
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.4489824175834656
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4531342089176178
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4593084454536438
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.33369722962379456
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.47624683380126953
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48864203691482544
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.43397098779678345
Calibrated prediction for UTX: 0.46666666865348816
Raw prediction for V: 0.5694839358329773
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5560807585716248
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5030900239944458
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5027221441268921
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.48176756501197815
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.503
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.981, kelly=0.187) with $4754.71
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.950, kelly=0.301) with $7650.24
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.462
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.977, kelly=0.070) with $1791.19
[PORT] Sector Financial: 10 candidates, avg score=0.515
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.984, kelly=0.201) with $5103.45
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.015, kelly=0.185) with $4706.24
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.510
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.058, kelly=0.271) with $6885.93
[PORT] Sector Services: 10 candidates, avg score=0.555
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.064, kelly=0.745) with $18960.84
[PORT] Sector Technology: 10 candidates, avg score=0.518
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.098, kelly=0.363) with $9238.63
[PORT] Sector Utilities: 10 candidates, avg score=0.535
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.908, kelly=0.188) with $4785.98
Raw prediction for AAPL: 0.5007100105285645
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.4816497266292572
Calibrated prediction for ABB: 0.49367088079452515
Raw prediction for ABBV: 0.3695484399795532
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5618860721588135
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4757726192474365
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.510006844997406
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7075825929641724
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4712117612361908
Calibrated prediction for BA: 0.5119210481643677
Raw prediction for BABA: 0.535110354423523
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46179094910621643
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5244923830032349
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.590000331401825
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.4892396032810211
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4816471040248871
Calibrated prediction for BP: 0.5
Raw prediction for BRK-A: 0.49241992831230164
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4875905215740204
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48055002093315125
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.51630038022995
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4718986451625824
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5277190208435059
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5611451864242554
Calibrated prediction for CHL: 0.6642113924026489
Raw prediction for CHTR: 0.6421751379966736
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.43751105666160583
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4440443217754364
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4252919852733612
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.4894903302192688
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5124215483665466
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5177120566368103
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49205049872398376
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5334705710411072
Calibrated prediction for DUK: 0.5384615659713745
Raw prediction for EXC: 0.5110839009284973
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5129190683364868
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5321389436721802
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4396871328353882
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.39949464797973633
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5251316428184509
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4510895907878876
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6522240042686462
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5241907835006714
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.4428396224975586
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.4401127099990845
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.48490387201309204
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5318065881729126
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4693602919578552
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6273824572563171
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4857494831085205
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5250908732414246
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4799444377422333
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5544580221176147
Calibrated prediction for MMM: 0.5433070659637451
Raw prediction for MO: 0.5432496666908264
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46407896280288696
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5259066820144653
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5328595638275146
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4875882565975189
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.43100911378860474
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4277395009994507
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.520234227180481
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5765278339385986
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47679591178894043
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46634554862976074
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.44012656807899475
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4535214304924011
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5406637191772461
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5050208568572998
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5379567742347717
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.44016480445861816
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5484328866004944
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.49521514773368835
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4870222806930542
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5041415691375732
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5046165585517883
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.39972978830337524
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5595541000366211
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5653771162033081
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.3788958787918091
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.4374333620071411
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.446261465549469
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4575579762458801
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.328004390001297
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4907101094722748
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48903366923332214
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.4111309051513672
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5714907646179199
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5566961169242859
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5026612877845764
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5007208585739136
Calibrated prediction for WMT: 0.49180328845977783

Simulating Trading Days:  22%|██▏       | 22/100 [04:43<01:30,  1.16s/it]

Raw prediction for XOM: 0.4791701138019562
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.487
[PORT] Sector Basic Matierials: selecting BBL (p=0.565, b=0.971, kelly=0.117) with $2986.32
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.950, kelly=0.301) with $7648.96
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.462
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.975, kelly=0.069) with $1764.39
[PORT] Sector Financial: 10 candidates, avg score=0.525
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.986, kelly=0.201) with $5113.81
[PORT] Sector Healthcare: 10 candidates, avg score=0.457
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.017, kelly=0.186) with $4723.53
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.496
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.058, kelly=0.271) with $6879.73
[PORT] Sector Services: 10 candidates, avg score=0.555
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.066, kelly=0.746) with $18954.87
[PORT] Sector Technology: 10 candidates, avg score=0.518
[PORT] Sector Technology: selecting CHL (p=0.664, b=1.096, kelly=0.358) with $9099.98
[PORT] Sector Utilities: 10 candidates, avg score=0.529
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.906, kelly=0.187) with $4762.91
Raw prediction for AAPL: 0.50095534324646
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.482740581035614
Calibrated prediction for ABB: 0.49367088079452515
Raw prediction for ABBV: 0.3818778097629547
Calibrated prediction for ABBV: 0.30000001192092896
Raw prediction for AEP: 0.5662621259689331
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4755166471004486
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5103821158409119
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7089563012123108
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.47155484557151794
Calibrated prediction for BA: 0.5175330638885498
Raw prediction for BABA: 0.5408743619918823
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4603240191936493
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5255222320556641
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5890852212905884
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.488715261220932
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4893245995044708
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49213993549346924
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48771101236343384
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48000019788742065
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5161624550819397
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4717012047767639
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.533399760723114
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5465372204780579
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6618548035621643
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.44792649149894714
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4405120313167572
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.42748263478279114
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.48954740166664124
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5123280882835388
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5180690288543701
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4919935464859009
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5268024802207947
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5115406513214111
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5129637122154236
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5320367217063904
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44160979986190796
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.39771682024002075
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5202963948249817
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4513966739177704
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6497153043746948
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5289020538330078
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.458706796169281
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.4468939006328583
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4820460081100464
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5316267609596252
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46923401951789856
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.635474681854248
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4996946454048157
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5253936052322388
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.48842212557792664
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5579354763031006
Calibrated prediction for MMM: 0.5454545617103577
Raw prediction for MO: 0.5428826212882996
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46387428045272827
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5398814082145691
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5355647802352905
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4848748743534088
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4330967664718628
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4277518093585968
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5202170610427856
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6235403418540955
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.476605623960495
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.466569185256958
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.44033634662628174
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45051175355911255
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5336746573448181
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5000696778297424
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5371708869934082
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.42551544308662415
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5560799241065979
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.47793999314308167
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4877520799636841
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5044777393341064
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5044291615486145
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3930043578147888
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.558922529220581
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5615039467811584
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.397946834564209
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.4232660233974457
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.43783900141716003
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4561209976673126
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3195875883102417
Calibrated prediction for UN: 0.4285714328289032

Simulating Trading Days:  23%|██▎       | 23/100 [04:44<01:28,  1.15s/it]

Raw prediction for UNH: 0.505710780620575
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.48974907398223877
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.4189489483833313
Calibrated prediction for UTX: 0.4285714328289032
Raw prediction for V: 0.5716972947120667
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5506314039230347
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5022626519203186
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4940142035484314
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.4786519408226013
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.483
[PORT] Sector Basic Matierials: selecting BBL (p=0.565, b=0.969, kelly=0.116) with $2968.64
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.949, kelly=0.301) with $7661.28
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.462
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.974, kelly=0.069) with $1750.73
[PORT] Sector Financial: 10 candidates, avg score=0.530
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.985, kelly=0.201) with $5115.45
[PORT] Sector Healthcare: 10 candidates, avg score=0.474
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.019, kelly=0.187) with $4759.35
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.506
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.056, kelly=0.270) with $6879.12
[PORT] Sector Services: 10 candidates, avg score=0.557
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.069, kelly=0.746) with $19009.17
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.997, kelly=0.231) with $5887.09
[PORT] Sector Utilities: 10 candidates, avg score=0.529
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.905, kelly=0.187) with $4756.30
Raw prediction for AAPL: 0.5010827779769897
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.48453637957572937
Calibrated prediction for ABB: 0.49367088079452515
Raw prediction for ABBV: 0.3850092589855194
Calibrated prediction for ABBV: 0.30000001192092896
Raw prediction for AEP: 0.5695763230323792
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4747651219367981
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5112070441246033
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7094314098358154
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.47324860095977783
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5450161099433899
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4590906798839569
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5276387333869934
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5876678228378296
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.48780688643455505
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.48971885442733765
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49195683002471924
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.487754225730896
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4789469242095947
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5159544944763184
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47151896357536316
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5415468811988831
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5375460386276245
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6607886552810669
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4493613839149475
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.43970879912376404
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.43066197633743286
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.4900723695755005
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5122295022010803
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5177930593490601
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4922849237918854
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5219027996063232
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5121367573738098
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.512913703918457
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5321559309959412
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4415754973888397
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.3983999788761139
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5162182450294495
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4514344334602356
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6461079120635986
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5321856141090393
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.47992223501205444
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.45754578709602356
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.48040956258773804
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5317419171333313
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46921396255493164
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6235654354095459
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5242322087287903
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5257286429405212
Calibrated prediction for MCD: 0.5297145247459412
Raw prediction for MDT: 0.4944678843021393
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5604662299156189
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5387828350067139
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46344462037086487
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5521931648254395
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5398041009902954
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.48312023282051086
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.43549537658691406
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.42847275733947754
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5201318264007568
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6435251235961914
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4764277935028076
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4666979908943176
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4403003752231598
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4484354853630066
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5286484360694885
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49727538228034973
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5286930203437805
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.42124807834625244
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5620821118354797
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4617212414741516
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48609650135040283
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5048804879188538
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.504187285900116
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.38445574045181274
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5590586066246033
Calibrated prediction for SRE: 0.560606062412262

Simulating Trading Days:  24%|██▍       | 24/100 [04:45<01:26,  1.14s/it]

Raw prediction for T: 0.5601150393486023
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.42783287167549133
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.411662220954895
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4276169240474701
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4538453221321106
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3068164885044098
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.5148520469665527
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.4906589686870575
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.42215800285339355
Calibrated prediction for UTX: 0.4285714328289032
Raw prediction for V: 0.5714098811149597
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5382744073867798
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5021630525588989
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.48792189359664917
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.4793441593647003
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.483
[PORT] Sector Basic Matierials: selecting BBL (p=0.565, b=0.971, kelly=0.117) with $2990.81
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.950, kelly=0.301) with $7666.12
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.469
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.972, kelly=0.068) with $1732.37
[PORT] Sector Financial: 10 candidates, avg score=0.530
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.984, kelly=0.200) with $5108.13
[PORT] Sector Healthcare: 10 candidates, avg score=0.474
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.022, kelly=0.188) with $4781.76
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.509
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.058, kelly=0.270) with $6891.51
[PORT] Sector Services: 10 candidates, avg score=0.557
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.069, kelly=0.746) with $19006.16
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.998, kelly=0.231) with $5897.26
[PORT] Sector Utilities: 10 candidates, avg score=0.529
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.905, kelly=0.187) with $4753.58
Raw prediction for AAPL: 0.5011517405509949
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.48786646127700806
Calibrated prediction for ABB: 0.49367088079452515
Raw prediction for ABBV: 0.37561580538749695
Calibrated prediction for ABBV: 0.2966429889202118
Raw prediction for AEP: 0.5707406997680664
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.473190039396286
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5124401450157166
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.695526659488678
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4772717356681824
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5467243790626526
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.45815032720565796
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5246239304542542
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5818051099777222
Calibrated prediction for BCH: 0.6034389734268188
Raw prediction for BHP: 0.486969918012619
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.4873466491699219
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4918043315410614
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48771294951438904
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.47760042548179626
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5157656669616699
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47127869725227356
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5499582290649414
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.529005765914917
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6573827862739563
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.45274338126182556
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.43956130743026733
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.434962660074234
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49056485295295715
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5122330188751221
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5182762742042542
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49234530329704285
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5129299759864807
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5121095776557922
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5128642320632935
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5324867367744446
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44459980726242065
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.40273597836494446
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.514324963092804
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4555668234825134
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6415308117866516
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5311434864997864
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.503530740737915
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.46917369961738586
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.48138895630836487
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5321067571640015
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46933412551879883
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6185594797134399
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5344603061676025
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5258908271789551
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5009995698928833
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5643554925918579
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5353454351425171
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4632839858531952
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.566938579082489
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5407651662826538
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4818912148475647
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.43620765209198
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.42979905009269714
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5199704170227051
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6528744101524353
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47627824544906616
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4666633605957031
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.44030165672302246
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4470328986644745
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.525325357913971
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49520888924598694
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5100052356719971
Calibrated prediction for PTR: 0.5
Raw prediction for RDS-B: 0.42425060272216797
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5544245839118958
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4495411217212677
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4842941462993622
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5051576495170593
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5041637420654297
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3784679174423218
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5567206144332886
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5599450469017029
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.4619576632976532
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4013550877571106
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4236926734447479
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4521842896938324
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.29595014452934265
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.522294282913208
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.4914966821670532
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.4414302110671997
Calibrated prediction for UTX: 0.46666666865348816
Raw prediction for V: 0.5697036981582642
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5337549448013306
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5021182298660278
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.48248910903930664
Calibrated prediction for WMT: 0.49180328845977783

Simulating Trading Days:  25%|██▌       | 25/100 [04:46<01:25,  1.14s/it]

Raw prediction for XOM: 0.47985899448394775
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.477
[PORT] Sector Basic Matierials: selecting BBL (p=0.565, b=0.971, kelly=0.117) with $2993.07
[PORT] Sector Conglomerates: 7 candidates, avg score=0.485
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.949, kelly=0.300) with $7657.31
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.469
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.970, kelly=0.067) with $1707.81
[PORT] Sector Financial: 10 candidates, avg score=0.530
[PORT] Sector Financial: selecting BCH (p=0.603, b=0.984, kelly=0.201) with $5112.73
[PORT] Sector Healthcare: 10 candidates, avg score=0.474
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.024, kelly=0.189) with $4807.05
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.513
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.057, kelly=0.270) with $6886.26
[PORT] Sector Services: 10 candidates, avg score=0.558
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.071, kelly=0.746) with $19025.08
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.997, kelly=0.231) with $5892.07
[PORT] Sector Utilities: 10 candidates, avg score=0.529
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.904, kelly=0.186) with $4754.48
Raw prediction for AAPL: 0.5012010335922241
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.4914851784706116
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.35061782598495483
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5682989954948425
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4713422358036041
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5138981938362122
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6846796870231628
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.48211976885795593
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5464339852333069
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4577145576477051
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5123581290245056
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5701303482055664
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.48654454946517944
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.4899306893348694
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4916475713253021
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48751595616340637
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4768955409526825
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5157486200332642
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4710463285446167
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5578263401985168
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5268086194992065
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6592548489570618
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4551529288291931
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.43522095680236816
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.44016051292419434
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49127355217933655
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5122776031494141
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.51845782995224
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4924444556236267
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4984961748123169
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5121275782585144
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5131940841674805
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5328031778335571
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4464791417121887
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4077127277851105
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.510585367679596
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4595724940299988
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6367984414100647
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5262352824211121
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.5242580771446228
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.482272744178772
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4856831133365631
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5326410531997681
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46936801075935364
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6102560758590698
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5237705111503601
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5259800553321838
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5052940845489502
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.566410481929779
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5328234434127808
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4633825123310089
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.581463634967804
Calibrated prediction for MSFT: 0.5914281606674194
Raw prediction for NEE: 0.5381897687911987
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4806337356567383
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.436178982257843
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4331270158290863
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.519820511341095
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6556524038314819
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4759196937084198
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4665299654006958
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4403037428855896
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4455684721469879
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5202032327651978
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49415773153305054
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4883703291416168
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.428337424993515
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5365210771560669
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.44414687156677246
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48467132449150085
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5048919320106506
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5042269229888916
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.376407265663147
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5520153641700745
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5610823631286621
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.49712032079696655
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.39986652135849
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4455762803554535
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.45056653022766113
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.28378796577453613
Calibrated prediction for UN: 0.4285714328289032

Simulating Trading Days:  26%|██▌       | 26/100 [04:47<01:23,  1.13s/it]

Raw prediction for UNH: 0.528046727180481
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.49213895201683044
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.4557468593120575
Calibrated prediction for UTX: 0.46666666865348816
Raw prediction for V: 0.5665543675422668
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5415552258491516
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5017228126525879
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.47826439142227173
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.48065629601478577
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.466
[PORT] Sector Basic Matierials: selecting BBL (p=0.556, b=0.970, kelly=0.097) with $2468.33
[PORT] Sector Conglomerates: 7 candidates, avg score=0.473
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.949, kelly=0.300) with $7614.22
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.469
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.969, kelly=0.066) with $1685.35
[PORT] Sector Financial: 10 candidates, avg score=0.529
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.985, kelly=0.194) with $4912.77
[PORT] Sector Healthcare: 10 candidates, avg score=0.473
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.022, kelly=0.188) with $4758.44
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.058, kelly=0.271) with $6860.37
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.043, kelly=0.328) with $8311.19
[PORT] Sector Technology: 10 candidates, avg score=0.513
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.999, kelly=0.232) with $5876.00
[PORT] Sector Utilities: 10 candidates, avg score=0.529
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.904, kelly=0.186) with $4721.94
Raw prediction for AAPL: 0.501146674156189
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.4941796064376831
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.32228586077690125
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5646231174468994
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.46920087933540344
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.515317440032959
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.6690309643745422
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.48693040013313293
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5413184762001038
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.45796024799346924
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4965812563896179
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.5487597584724426
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4864027500152588
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.497091144323349
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4915538430213928
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48727506399154663
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.474282830953598
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5157855153083801
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.470744788646698
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5665847659111023
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5194419026374817
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6526386737823486
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.46434736251831055
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.43389856815338135
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4440729022026062
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.49128207564353943
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5122305750846863
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5183533430099487
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49242642521858215
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.48286011815071106
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5125846862792969
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5133543014526367
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5331298112869263
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44817912578582764
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.41058748960494995
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5034242272377014
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4642082154750824
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6334918737411499
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5198208689689636
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.5371295809745789
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.4895404279232025
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.48192504048347473
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5328890681266785
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4692135751247406
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6034801602363586
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5011084675788879
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5257954001426697
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5076697468757629
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5676804184913635
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5283925533294678
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46359002590179443
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5888453125953674
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5333274006843567
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.47918933629989624
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.43650689721107483
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43611466884613037
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5196751952171326
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6590566635131836
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4753517210483551
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4666140377521515
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4403247833251953
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.44410109519958496
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.509255588054657
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49588459730148315
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4660988748073578
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.4390772581100464
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5090914964675903
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.442388117313385
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4837740957736969
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5045234560966492
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5043198466300964
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.37531331181526184
Calibrated prediction for SPLP: 0.30125677585601807

Simulating Trading Days:  27%|██▋       | 27/100 [04:48<01:22,  1.13s/it]

Raw prediction for SRE: 0.5496973991394043
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5642869472503662
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.5171945095062256
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4072050452232361
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4666549861431122
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.44904452562332153
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2709886431694031
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.5336639285087585
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.49247369170188904
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.4566974639892578
Calibrated prediction for UTX: 0.46666666865348816
Raw prediction for V: 0.564441442489624
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.554617166519165
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.501323938369751
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.47197452187538147
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.48322805762290955
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.465
[PORT] Sector Basic Matierials: selecting BBL (p=0.550, b=0.970, kelly=0.086) with $2188.47
[PORT] Sector Conglomerates: 7 candidates, avg score=0.473
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.947, kelly=0.300) with $7602.05
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.445
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.114, kelly=0.052) with $1309.38
[PORT] Sector Financial: 10 candidates, avg score=0.517
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4445.58
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.021, kelly=0.187) with $4753.27
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.058, kelly=0.270) with $6860.04
[PORT] Sector Services: 10 candidates, avg score=0.546
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.041, kelly=0.327) with $8303.42
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.995, kelly=0.230) with $5843.92
[PORT] Sector Utilities: 10 candidates, avg score=0.522
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.903, kelly=0.186) with $4714.04
Raw prediction for AAPL: 0.5008286237716675
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.49630242586135864
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3139108121395111
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5619468688964844
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.46648672223091125
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5166804194450378
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.6850691437721252
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.4919302463531494
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5383471846580505
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.460360586643219
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.48203355073928833
Calibrated prediction for BBL: 0.5248367786407471
Raw prediction for BCH: 0.5473577380180359
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.48640501499176025
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5057286620140076
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49211639165878296
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48703765869140625
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4773436486721039
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5153028964996338
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4705880880355835
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5736744999885559
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5251731872558594
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6804435849189758
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.469777375459671
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.438339501619339
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4496666193008423
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.4912923276424408
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5121839046478271
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5190747380256653
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4927334785461426
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4717812240123749
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5131797790527344
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5142558217048645
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5330642461776733
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4496331214904785
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.42066851258277893
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4968353509902954
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4732416272163391
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6302429437637329
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5293031334877014
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.5457805395126343
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5024879574775696
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.4691939651966095
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5338467955589294
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46921148896217346
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5928322672843933
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5259280800819397
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5258716940879822
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5091590881347656
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5711797475814819
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5247598886489868
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4640381932258606
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5908825397491455
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.530055820941925
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4763443171977997
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4420080780982971
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43793269991874695
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5196520090103149
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6720328330993652
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4747847020626068
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4668823480606079
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4405267834663391
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4442842900753021
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5038818717002869
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49646592140197754
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4480615258216858
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.45537832379341125
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.4788725674152374
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.44049394130706787
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4844837188720703
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5043668150901794
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.504520833492279
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.373329758644104
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5539804697036743
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.568161129951477
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.5566490888595581
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.4134244918823242
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5256545543670654
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4481361210346222
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.26131391525268555
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.5374072194099426
Calibrated prediction for UNH: 0.5333333611488342

Simulating Trading Days:  28%|██▊       | 28/100 [04:50<01:23,  1.15s/it]

Raw prediction for UPS: 0.4927442967891693
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.4619418978691101
Calibrated prediction for UTX: 0.46666666865348816
Raw prediction for V: 0.5676240921020508
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.579119861125946
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5015568137168884
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4688588082790375
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.48851069808006287
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.463
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.029, kelly=0.070) with $1793.56
[PORT] Sector Conglomerates: 7 candidates, avg score=0.471
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.946, kelly=0.299) with $7618.76
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting TM (p=0.528, b=0.984, kelly=0.048) with $1217.22
[PORT] Sector Financial: 10 candidates, avg score=0.521
[PORT] Sector Financial: selecting V (p=0.581, b=1.034, kelly=0.176) with $4486.40
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.019, kelly=0.187) with $4749.41
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.058, kelly=0.270) with $6883.72
[PORT] Sector Services: 10 candidates, avg score=0.546
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.038, kelly=0.327) with $8311.96
[PORT] Sector Technology: 10 candidates, avg score=0.527
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.997, kelly=0.231) with $5881.85
[PORT] Sector Utilities: 10 candidates, avg score=0.522
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.902, kelly=0.185) with $4712.82
Raw prediction for AAPL: 0.5002368092536926
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.4976870119571686
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3069034516811371
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5597625970840454
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.46381646394729614
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5176985263824463
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.6882511973381042
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.49617961049079895
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5380866527557373
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4631669819355011
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4699048399925232
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5469144582748413
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4865233302116394
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5132395625114441
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49220773577690125
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4871104955673218
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4877593517303467
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5148022174835205
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4707813560962677
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5790673494338989
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5402988195419312
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6775690913200378
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.47957926988601685
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4431670606136322
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4579940438270569
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.4914173483848572
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5122494697570801
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5199869275093079
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49305495619773865
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.46736013889312744
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5136053562164307
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5152760744094849
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5329195261001587
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4522855877876282
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4288810193538666
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4890158474445343
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47921672463417053
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6274051070213318
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5442871451377869
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.5493236184120178
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5101472735404968
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.45714065432548523
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5355587005615234
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4692690372467041
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5690246224403381
Calibrated prediction for LMT: 0.5908729434013367
Raw prediction for MA: 0.5354993939399719
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.525992214679718
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5135625600814819
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5741963386535645
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5204994082450867
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46418291330337524
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5843886733055115
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5280809998512268
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4753197729587555
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.44726112484931946
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.44178470969200134
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5196873545646667
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6780962944030762
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4743373692035675
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4671003222465515
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4406566619873047
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.44430795311927795
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5042077898979187
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.498264878988266
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.43529996275901794
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.4675341546535492
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.4567674398422241
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.4385312497615814
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48520106077194214
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.50409996509552
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.504753828048706
Calibrated prediction for SO: 0.5042282938957214

Simulating Trading Days:  29%|██▉       | 29/100 [04:51<01:21,  1.15s/it]

Raw prediction for SPLP: 0.3676164746284485
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5611712336540222
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5737949013710022
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.5841477513313293
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.4201648533344269
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5619626045227051
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.44759219884872437
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2513428032398224
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.5333756804466248
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.4929257929325104
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.46671000123023987
Calibrated prediction for UTX: 0.5
Raw prediction for V: 0.5709009766578674
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5863415002822876
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5011994242668152
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46636635065078735
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.49303939938545227
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.456
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.029, kelly=0.070) with $1797.36
[PORT] Sector Conglomerates: 7 candidates, avg score=0.471
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.946, kelly=0.299) with $7637.18
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.459
[PORT] Sector Consumer Goods: selecting TM (p=0.528, b=0.983, kelly=0.048) with $1214.11
[PORT] Sector Financial: 10 candidates, avg score=0.521
[PORT] Sector Financial: selecting V (p=0.581, b=1.034, kelly=0.176) with $4493.99
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.021, kelly=0.187) with $4778.86
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting LMT (p=0.591, b=1.062, kelly=0.206) with $5244.28
[PORT] Sector Services: 10 candidates, avg score=0.546
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.037, kelly=0.326) with $8322.06
[PORT] Sector Technology: 10 candidates, avg score=0.527
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.997, kelly=0.231) with $5898.77
[PORT] Sector Utilities: 10 candidates, avg score=0.522
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.901, kelly=0.185) with $4716.94
Raw prediction for AAPL: 0.4995582401752472
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.49979230761528015
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.29849517345428467
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5574167370796204
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4607096016407013
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5184898972511292
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.6911301612854004
Calibrated prediction for AMZN: 0.6605588793754578
Raw prediction for BA: 0.49805718660354614
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5407860279083252
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4659436047077179
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.46053898334503174
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5453721880912781
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.48673754930496216
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5176239609718323
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4921519458293915
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4869592785835266
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4963147044181824
Calibrated prediction for BUD: 0.5632455945014954
Raw prediction for C: 0.5143800377845764
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4710485637187958
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5856343507766724
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.52500319480896
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6684828996658325
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4851181209087372
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.44765543937683105
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4634447693824768
Calibrated prediction for CSCO: 0.4523203670978546
Raw prediction for CVX: 0.491916686296463
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5123865604400635
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5206652283668518
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4934229254722595
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.46701064705848694
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5131001472473145
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5154685974121094
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5329940319061279
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.45386818051338196
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.43862184882164
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.48254597187042236
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4813520014286041
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6235151290893555
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5470995903015137
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.5517035722732544
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5102100968360901
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.44661152362823486
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5370155572891235
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46917667984962463
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5601968765258789
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5268179178237915
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5262377262115479
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5170460939407349
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.575958788394928
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5126485228538513
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46431148052215576
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5773074626922607
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5264527201652527
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.474513977766037
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.45330801606178284
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4422014653682709
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5197020769119263
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6713975071907043
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.473924845457077
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46708160638809204
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4405730962753296
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4442337453365326
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5036464929580688
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5012204647064209
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.42533403635025024
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.48323410749435425
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.4444873034954071
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.43855202198028564
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4862710237503052
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5039923787117004
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5049479007720947
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.35964545607566833
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5582889318466187
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5759026408195496
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.5816709995269775
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.4211444556713104
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5553790330886841
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.44675877690315247
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.24392306804656982
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.5247151255607605
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.4930034279823303
Calibrated prediction for UPS: 0.4941723644733429

Simulating Trading Days:  30%|███       | 30/100 [04:52<01:21,  1.17s/it]

Raw prediction for UTX: 0.42741885781288147
Calibrated prediction for UTX: 0.4285714328289032
Raw prediction for V: 0.5713561177253723
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.584298849105835
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5012252926826477
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46599307656288147
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.49786606431007385
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.461
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.027, kelly=0.069) with $1767.77
[PORT] Sector Conglomerates: 7 candidates, avg score=0.471
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.946, kelly=0.299) with $7635.14
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.466
[PORT] Sector Consumer Goods: selecting BUD (p=0.563, b=1.050, kelly=0.147) with $3758.00
[PORT] Sector Financial: 10 candidates, avg score=0.521
[PORT] Sector Financial: selecting V (p=0.581, b=1.034, kelly=0.176) with $4491.92
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.022, kelly=0.188) with $4784.44
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.503
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.993, kelly=0.140) with $3560.34
[PORT] Sector Services: 10 candidates, avg score=0.549
[PORT] Sector Services: selecting AMZN (p=0.661, b=1.065, kelly=0.342) with $8721.56
[PORT] Sector Technology: 10 candidates, avg score=0.521
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.995, kelly=0.230) with $5877.21
[PORT] Sector Utilities: 10 candidates, avg score=0.522
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.902, kelly=0.185) with $4722.01
Raw prediction for AAPL: 0.4989933371543884
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5021800994873047
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2869515120983124
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5581250786781311
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.45766952633857727
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5191971659660339
Calibrated prediction for AMGN: 0.5203579068183899
Raw prediction for AMZN: 0.6772980093955994
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.49745893478393555
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5464645028114319
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46872660517692566
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.453422486782074
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5418385863304138
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.48675087094306946
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5183433294296265
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49207690358161926
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48677945137023926
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.49967536330223083
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5142411589622498
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4709988236427307
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5923296213150024
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5023565292358398
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.6555642485618591
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.48468029499053955
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.44771066308021545
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4676378667354584
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49246594309806824
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5129444003105164
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5203038454055786
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.493839293718338
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.47780972719192505
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5148784518241882
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5153608918190002
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5330550074577332
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44954997301101685
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4451066553592682
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4758356809616089
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4817134439945221
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6187206506729126
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.534309446811676
Calibrated prediction for HSBC: 0.5613763928413391
Raw prediction for IEP: 0.5525311231613159
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5059640407562256
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.43577128648757935
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5379464626312256
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46897315979003906
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.564553439617157
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.4975597858428955
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5264648795127869
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5172226428985596
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5756366848945618
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5071984529495239
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46433761715888977
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5699785351753235
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5272887349128723
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4770868718624115
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4583112299442291
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.44171854853630066
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5196231603622437
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6529094576835632
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47349852323532104
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46696585416793823
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.44053739309310913
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.44464218616485596
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5024265050888062
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5047525763511658
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4157228171825409
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.49892622232437134
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.43502968549728394
Calibrated prediction for REX: 0.421782910823822
Raw prediction for SLB: 0.4352070987224579
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4873577952384949
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5038507580757141
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5048244595527649
Calibrated prediction for SO: 0.5042282938957214

Simulating Trading Days:  31%|███       | 31/100 [04:53<01:20,  1.17s/it]

Raw prediction for SPLP: 0.3492485284805298
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5780429840087891
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5754037499427795
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.5685487389564514
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.41393736004829407
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5265089869499207
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4463996887207031
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.24061939120292664
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.5113493800163269
Calibrated prediction for UNH: 0.5333333611488342
Raw prediction for UPS: 0.4929528832435608
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.37761974334716797
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5686901807785034
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5749669671058655
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5014610886573792
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46777206659317017
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.49849286675453186
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.461
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.029, kelly=0.070) with $1802.95
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.947, kelly=0.300) with $7681.88
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.471
[PORT] Sector Consumer Goods: selecting BUD (p=0.619, b=1.048, kelly=0.256) with $6569.07
[PORT] Sector Financial: 10 candidates, avg score=0.521
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4504.82
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.021, kelly=0.188) with $4806.59
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.494
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.995, kelly=0.140) with $3590.34
[PORT] Sector Services: 10 candidates, avg score=0.546
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.040, kelly=0.327) with $8380.26
[PORT] Sector Technology: 10 candidates, avg score=0.525
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.995, kelly=0.230) with $5905.67
[PORT] Sector Utilities: 10 candidates, avg score=0.522
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.900, kelly=0.184) with $4727.75
Raw prediction for AAPL: 0.4986359179019928
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5044482350349426
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2717885375022888
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5531381368637085
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.45471522212028503
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5198714733123779
Calibrated prediction for AMGN: 0.5297477841377258
Raw prediction for AMZN: 0.6705706119537354
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.49553999304771423
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.55635005235672
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47099947929382324
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.44891706109046936
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5351733565330505
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4868057668209076
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5174496173858643
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49207526445388794
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4865913987159729
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4968525469303131
Calibrated prediction for BUD: 0.5876708626747131
Raw prediction for C: 0.5143304467201233
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47071826457977295
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5965467095375061
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.47815948724746704
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.6407262682914734
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4717884361743927
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.45055583119392395
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47069913148880005
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49261096119880676
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5130882263183594
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.518803596496582
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4943704307079315
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.47265130281448364
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5150747299194336
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5152058601379395
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5330338478088379
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44211143255233765
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4471646249294281
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4695650041103363
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.48156899213790894
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6125417947769165
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.5124565958976746
Calibrated prediction for HSBC: 0.517241358757019
Raw prediction for IEP: 0.5506677627563477
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5016894936561584
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.42509928345680237
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5381518602371216
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4685578942298889
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5788187980651855
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4738393723964691
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5267844200134277
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5131109952926636
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5745423436164856
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5014602541923523
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46401700377464294
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5621275305747986
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5273568630218506
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4815223813056946
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.46197202801704407
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4407939314842224
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5197511911392212
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6380109190940857
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4731178283691406
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4667184054851532
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4405347406864166
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.44472426176071167
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5031997561454773
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.505203366279602
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.40708595514297485
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.504764199256897
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.42914626002311707
Calibrated prediction for REX: 0.421782910823822
Raw prediction for SLB: 0.42984750866889954
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48834848403930664
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5035114884376526
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5048335790634155
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3427862823009491
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5417912602424622
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5749722123146057
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.5475730895996094
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.4098871946334839
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4966418147087097
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4459973871707916
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.23846794664859772
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.49148470163345337
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4927479326725006
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.33103567361831665
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5658019781112671
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5625867247581482
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5018213391304016
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4720597267150879
Calibrated prediction for WMT: 0.44648152589797974

Simulating Trading Days:  32%|███▏      | 32/100 [04:54<01:18,  1.16s/it]

Raw prediction for XOM: 0.4954316020011902
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.463
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.031, kelly=0.071) with $1831.25
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.956, kelly=0.303) with $7772.12
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.468
[PORT] Sector Consumer Goods: selecting BUD (p=0.588, b=1.050, kelly=0.195) with $5005.45
[PORT] Sector Financial: 10 candidates, avg score=0.517
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4511.43
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.020, kelly=0.187) with $4793.18
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.502
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.063, kelly=0.272) with $6983.25
[PORT] Sector Services: 10 candidates, avg score=0.546
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.040, kelly=0.327) with $8388.26
[PORT] Sector Technology: 10 candidates, avg score=0.512
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.994, kelly=0.230) with $5903.63
[PORT] Sector Utilities: 10 candidates, avg score=0.518
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.900, kelly=0.095) with $2449.43
Raw prediction for AAPL: 0.49815741181373596
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5064848065376282
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2572760581970215
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5453866124153137
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.4521961808204651
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5204377174377441
Calibrated prediction for AMGN: 0.5297477841377258
Raw prediction for AMZN: 0.6572602987289429
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.4923095405101776
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5635069012641907
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47245165705680847
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.44636401534080505
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5220017433166504
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4867750406265259
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5151041150093079
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4922133982181549
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48628562688827515
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48931682109832764
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5145776867866516
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47045132517814636
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.597664475440979
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.46394890546798706
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.6103682518005371
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.45461317896842957
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4505455195903778
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4721103608608246
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49304428696632385
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.513185441493988
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5173925757408142
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49489879608154297
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4582323133945465
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.513935923576355
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5150836110115051
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5329282283782959
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4429629445075989
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.44360294938087463
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.463743656873703
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4807950258255005
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6092931628227234
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4898180365562439
Calibrated prediction for HSBC: 0.4864864945411682
Raw prediction for IEP: 0.5494654774665833
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.49693650007247925
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.41570016741752625
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5378776788711548
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4680399000644684
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5871183276176453
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.45034611225128174
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5269650220870972
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5054899454116821
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5726298093795776
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49416959285736084
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46336519718170166
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5520634055137634
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5265000462532043
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4855732321739197
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4641062915325165
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43860897421836853
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.51991868019104
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6233463883399963
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47275039553642273
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46677377820014954
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.44056057929992676
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4449276924133301
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5036844611167908
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5008972883224487
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4005841612815857
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5065479874610901
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.4295121133327484
Calibrated prediction for REX: 0.421782910823822
Raw prediction for SLB: 0.4279046654701233
Calibrated prediction for SLB: 0.4140401780605316
Raw prediction for SNP: 0.48863327503204346
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5031238794326782
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5046523213386536
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3335670828819275
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.48703786730766296
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.5779596567153931
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.5360892415046692
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.4084556996822357
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.46581578254699707
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.445994108915329
Calibrated prediction for UL: 0.45108622312545776

Simulating Trading Days:  33%|███▎      | 33/100 [04:55<01:17,  1.16s/it]

Raw prediction for UN: 0.23898498713970184
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4720652997493744
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49225765466690063
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.29378053545951843
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5630720257759094
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5429741144180298
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5021052360534668
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.475925087928772
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.4920414388179779
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.462
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.031, kelly=0.071) with $1827.47
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.954, kelly=0.170) with $4373.42
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.114, kelly=0.052) with $1333.91
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.581, b=1.031, kelly=0.175) with $4497.02
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.021, kelly=0.187) with $4807.17
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.502
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.063, kelly=0.272) with $6987.35
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.039, kelly=0.327) with $8385.42
[PORT] Sector Technology: 10 candidates, avg score=0.499
[PORT] Sector Technology: selecting VZ (p=0.616, b=0.994, kelly=0.230) with $5903.79
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.901, kelly=0.096) with $2452.84
Raw prediction for AAPL: 0.4976861774921417
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5082105398178101
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.24475529789924622
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5386719703674316
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.45034071803092957
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5204663872718811
Calibrated prediction for AMGN: 0.5297477841377258
Raw prediction for AMZN: 0.6528092622756958
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.48811841011047363
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5652338862419128
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47311046719551086
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4474661648273468
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5048649311065674
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48686426877975464
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5156233310699463
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4923276901245117
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4858764410018921
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48051026463508606
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5148040056228638
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4702267348766327
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5944012999534607
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.45123913884162903
Calibrated prediction for CHL: 0.39837101101875305
Raw prediction for CHTR: 0.5859301090240479
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.43149304389953613
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.45717623829841614
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4725818634033203
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4930354654788971
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.513334333896637
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5161849856376648
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4953736662864685
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4412783682346344
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5126201510429382
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5147762298583984
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5328449606895447
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44722989201545715
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.43476471304893494
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4569723308086395
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.4777073562145233
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.602077305316925
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4667240083217621
Calibrated prediction for HSBC: 0.4615384638309479
Raw prediction for IEP: 0.5464078783988953
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.502753734588623
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.40937933325767517
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.5373011231422424
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4675242304801941
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5856567621231079
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4291914999485016
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5270257592201233
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.49525338411331177
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5700592398643494
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4870394170284271
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.462590754032135
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5356255173683167
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5246784687042236
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4886140525341034
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4645833373069763
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4352247416973114
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5204200148582458
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6140439510345459
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47253385186195374
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46671435236930847
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.44058921933174133
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.44614729285240173
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5059964656829834
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4929518401622772
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.3977932333946228
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5072402954101562
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.42778709530830383
Calibrated prediction for REX: 0.421782910823822
Raw prediction for SLB: 0.4338439106941223
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4888525903224945
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.50284743309021
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5044436454772949
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.332884818315506
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4421590566635132
Calibrated prediction for SRE: 0.4647769331932068
Raw prediction for T: 0.5828453302383423
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.5344144105911255
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.4130071997642517
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4326181709766388
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4457501769065857
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.23781219124794006
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.45131850242614746
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49145978689193726
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.2570745050907135
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5612704157829285
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.523944616317749
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.5022324919700623
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4812203347682953
Calibrated prediction for WMT: 0.49180328845977783

Simulating Trading Days:  34%|███▍      | 34/100 [04:57<01:16,  1.16s/it]

Raw prediction for XOM: 0.49264422059059143
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.463
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.028, kelly=0.070) with $1796.71
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.952, kelly=0.170) with $4351.91
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.448
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.117, kelly=0.053) with $1357.56
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4510.30
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.018, kelly=0.186) with $4780.80
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.502
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.062, kelly=0.272) with $6978.45
[PORT] Sector Services: 10 candidates, avg score=0.524
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.037, kelly=0.298) with $7654.66
[PORT] Sector Technology: 10 candidates, avg score=0.484
[PORT] Sector Technology: selecting T (p=0.600, b=0.976, kelly=0.190) with $4882.21
[PORT] Sector Utilities: 10 candidates, avg score=0.503
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.899, kelly=0.095) with $2427.81
Raw prediction for AAPL: 0.4974111318588257
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.509189248085022
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2447810024023056
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5345296263694763
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.44795337319374084
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5201584696769714
Calibrated prediction for AMGN: 0.5297477841377258
Raw prediction for AMZN: 0.6548454165458679
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.4840235412120819
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5682416558265686
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47276249527931213
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.44930270314216614
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.48352569341659546
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4869779944419861
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5073502063751221
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4923575222492218
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48528873920440674
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.47686150670051575
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.514962375164032
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47020402550697327
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5816942453384399
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.44553548097610474
Calibrated prediction for CHL: 0.35839587450027466
Raw prediction for CHTR: 0.5717722773551941
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4089418053627014
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4567064046859741
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47500449419021606
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4937736392021179
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.513439953327179
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5151681303977966
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49605777859687805
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4327874779701233
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5116955041885376
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5142442584037781
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5327342748641968
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.45054805278778076
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4221222698688507
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4522506296634674
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.47412246465682983
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5956853628158569
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4443914294242859
Calibrated prediction for HSBC: 0.4615384638309479
Raw prediction for IEP: 0.5438971519470215
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5094735026359558
Calibrated prediction for INTC: 0.5199999809265137
Raw prediction for JNJ: 0.3990420997142792
Calibrated prediction for JNJ: 0.5
Raw prediction for JPM: 0.536638081073761
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4672631025314331
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5723130702972412
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4158056974411011
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5269634127616882
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4858463704586029
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5668771266937256
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4830878973007202
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4617229402065277
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5202353000640869
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.523452639579773
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49211615324020386
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4656789302825928
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43037375807762146
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5208095908164978
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5980271100997925
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.4724189341068268
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4665791690349579
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4405631721019745
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.44647014141082764
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5062099099159241
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4854169189929962
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.3965369760990143
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.508514940738678
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.4262760579586029
Calibrated prediction for REX: 0.421782910823822
Raw prediction for SLB: 0.442596435546875
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4896731972694397
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5026943683624268
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5039569139480591
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3411710262298584
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4103216826915741
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5889358520507812
Calibrated prediction for T: 0.6420084834098816

Simulating Trading Days:  35%|███▌      | 35/100 [04:58<01:15,  1.17s/it]

Raw prediction for TM: 0.5190713405609131
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4150907099246979
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.40903326869010925
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4453878700733185
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.23786459863185883
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4413474500179291
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4902491569519043
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.20939084887504578
Calibrated prediction for UTX: 0.3333333432674408
Raw prediction for V: 0.5610437989234924
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5071876049041748
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.5023120641708374
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4810042977333069
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.49561235308647156
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.463
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.030, kelly=0.071) with $1818.27
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.951, kelly=0.169) with $4342.61
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.445
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.114, kelly=0.052) with $1333.37
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.031, kelly=0.175) with $4494.21
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.018, kelly=0.186) with $4787.80
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.502
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.060, kelly=0.271) with $6970.83
[PORT] Sector Services: 10 candidates, avg score=0.524
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.038, kelly=0.299) with $7681.30
[PORT] Sector Technology: 10 candidates, avg score=0.483
[PORT] Sector Technology: selecting T (p=0.642, b=0.978, kelly=0.276) with $7088.61
[PORT] Sector Utilities: 10 candidates, avg score=0.491
[PORT] Sector Utilities: selecting PPL (p=0.530, b=0.918, kelly=0.018) with $472.13
Raw prediction for AAPL: 0.49717241525650024
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.510129988193512
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2516464293003082
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5289170742034912
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.4453832507133484
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5198028087615967
Calibrated prediction for AMGN: 0.5297477841377258
Raw prediction for AMZN: 0.6499986052513123
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.48052144050598145
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5720363259315491
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47265738248825073
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.45298314094543457
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.47311094403266907
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4870334267616272
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.4947368800640106
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4925273656845093
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4848480224609375
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.47655802965164185
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5150347352027893
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4702596366405487
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5643214583396912
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.4449353814125061
Calibrated prediction for CHL: 0.3541899621486664
Raw prediction for CHTR: 0.5627322196960449
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3887786865234375
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.45805102586746216
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4771249294281006
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49482354521751404
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5135071873664856
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5143638849258423
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4968262314796448
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4275673031806946
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5107520222663879
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5138474702835083
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5326921939849854
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4500333070755005
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.40790829062461853
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.44952934980392456
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.4721446931362152
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5924407839775085
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4246435761451721
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5427831411361694
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5166574120521545
Calibrated prediction for INTC: 0.5378316640853882
Raw prediction for JNJ: 0.38927605748176575
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5363831520080566
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46719813346862793
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5488746166229248
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.4150996506214142
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5268528461456299
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48028185963630676
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.564358651638031
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.48350006341934204
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46119508147239685
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5089724659919739
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5228168368339539
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4948429763317108
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4683105945587158
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4265579581260681
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5211220383644104
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5898646712303162
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.472461998462677
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46641793847084045
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4404515326023102
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.44760817289352417
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5101402401924133
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4772046208381653
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.3980445861816406
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5156106352806091
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.4285695552825928
Calibrated prediction for REX: 0.421782910823822
Raw prediction for SLB: 0.4557924270629883
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49050965905189514
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5026616454124451
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5035812854766846
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3546825051307678
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.40461453795433044
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5945281386375427
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5070087313652039
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4110390245914459
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.3908991515636444
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4451453685760498
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.23946383595466614
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4397483468055725
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4889357388019562
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.1627415418624878
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5624743700027466
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4904484152793884
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5026946067810059
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4787830114364624
Calibrated prediction for WMT: 0.49180328845977783

Simulating Trading Days:  36%|███▌      | 36/100 [04:59<01:14,  1.16s/it]

Raw prediction for XOM: 0.4980771243572235
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.463
[PORT] Sector Basic Matierials: selecting BP (p=0.529, b=1.032, kelly=0.072) with $1844.17
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.951, kelly=0.169) with $4364.59
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.445
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.115, kelly=0.052) with $1348.85
[PORT] Sector Financial: 10 candidates, avg score=0.486
[PORT] Sector Financial: selecting V (p=0.581, b=1.030, kelly=0.175) with $4498.13
[PORT] Sector Healthcare: 10 candidates, avg score=0.440
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.020, kelly=0.187) with $4817.44
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.999, kelly=0.142) with $3663.53
[PORT] Sector Services: 10 candidates, avg score=0.524
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.038, kelly=0.293) with $7558.96
[PORT] Sector Technology: 10 candidates, avg score=0.483
[PORT] Sector Technology: selecting T (p=0.642, b=0.980, kelly=0.277) with $7133.54
[PORT] Sector Utilities: 10 candidates, avg score=0.491
[PORT] Sector Utilities: selecting PPL (p=0.530, b=0.916, kelly=0.017) with $447.23
Raw prediction for AAPL: 0.4970216453075409
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5104249715805054
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2543996274471283
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5287795662879944
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.44255590438842773
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.518972635269165
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.6376087069511414
Calibrated prediction for AMZN: 0.5608162879943848
Raw prediction for BA: 0.47701236605644226
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5730611085891724
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4735397398471832
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.459087073802948
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.480493426322937
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48746055364608765
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.4734628200531006
Calibrated prediction for BP: 0.4615384638309479
Raw prediction for BRK-A: 0.49301472306251526
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4846874475479126
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4779280126094818
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5148282051086426
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4703965485095978
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5484632849693298
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.4589250683784485
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.5555975437164307
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.38078761100769043
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4590051770210266
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4803209900856018
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49572083353996277
Calibrated prediction for CVX: 0.5
Raw prediction for D: 0.5136256217956543
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5134150981903076
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49757418036460876
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.42526641488075256
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5108522176742554
Calibrated prediction for EXC: 0.5208333134651184
Raw prediction for FB: 0.5139598250389099
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5327082276344299
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44788625836372375
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.40083587169647217
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.448886901140213
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.4703284502029419
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5920159816741943
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.41321009397506714
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5465446710586548
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.528520405292511
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.38843074440956116
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.537187933921814
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46717461943626404
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5135201811790466
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.4200655519962311
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5265802145004272
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4823884665966034
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5619256496429443
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4951305091381073
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4608698785305023
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5049872398376465
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5227159261703491
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49825313687324524
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4700317680835724
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4244360625743866
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5215907692909241
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5916343331336975
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.4727899432182312
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46597445011138916
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4403262138366699
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4494625926017761
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5166646242141724
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4731377959251404
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.40392208099365234
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5243104100227356
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.43586042523384094
Calibrated prediction for REX: 0.421782910823822
Raw prediction for SLB: 0.4673827588558197
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.491077184677124
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5026994347572327
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5035044550895691
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.37013983726501465
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4145198464393616
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5979218482971191
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5005599856376648
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.410453200340271
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4067962169647217
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4444659352302551
Calibrated prediction for UL: 0.45108622312545776

Simulating Trading Days:  37%|███▋      | 37/100 [05:00<01:12,  1.16s/it]

Raw prediction for UN: 0.24297872185707092
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.44531136751174927
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48795923590660095
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.10860613733530045
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5640016794204712
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.481585294008255
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5032122731208801
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.47396597266197205
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5001219511032104
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.466
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.902, kelly=0.157) with $4048.75
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.955, kelly=0.171) with $4412.54
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.445
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.113, kelly=0.052) with $1331.46
[PORT] Sector Financial: 10 candidates, avg score=0.486
[PORT] Sector Financial: selecting V (p=0.581, b=1.028, kelly=0.174) with $4488.17
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.020, kelly=0.187) with $4833.03
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.002, kelly=0.143) with $3698.42
[PORT] Sector Services: 10 candidates, avg score=0.513
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.037, kelly=0.299) with $7712.20
[PORT] Sector Technology: 10 candidates, avg score=0.490
[PORT] Sector Technology: selecting T (p=0.642, b=0.981, kelly=0.277) with $7154.81
[PORT] Sector Utilities: 10 candidates, avg score=0.491
[PORT] Sector Utilities: selecting PPL (p=0.530, b=0.914, kelly=0.016) with $422.67
Raw prediction for AAPL: 0.4968019425868988
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5105770230293274
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.25946536660194397
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5271691083908081
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.44001007080078125
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5176848769187927
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.6250717639923096
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.473959743976593
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5731727480888367
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4746244251728058
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.46459466218948364
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.4839150309562683
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.487845242023468
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.44741570949554443
Calibrated prediction for BP: 0.40809041261672974
Raw prediction for BRK-A: 0.4930862486362457
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4847775399684906
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4753791391849518
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5147029757499695
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47046372294425964
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5361480712890625
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.4683064818382263
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.5528358817100525
Calibrated prediction for CHTR: 0.5833333134651184
Raw prediction for CMCSA: 0.37412959337234497
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.45479923486709595
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4825550615787506
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4972842335700989
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.513645350933075
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5125299096107483
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4981172978878021
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.42167869210243225
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.51005619764328
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5140888094902039
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5327326655387878
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44426554441452026
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.39773741364479065
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.45025572180747986
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.4690035581588745
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5922088027000427
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.401029109954834
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5513336062431335
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5404365062713623
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3892477750778198
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5384004712104797
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46712997555732727
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4891655445098877
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.4139939844608307
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.526120662689209
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48709648847579956
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5606656074523926
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49962595105171204
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4606058597564697
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.500313937664032
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5228515863418579
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5016353726387024
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4681227505207062
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.42310091853141785
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5220849514007568
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5830406546592712
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4732191264629364
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4653395414352417
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43996962904930115
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4523387551307678
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5207226872444153
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4691157639026642
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4139636754989624
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5289978981018066
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.44789570569992065
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.47386935353279114
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49161437153816223
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5027039051055908
Calibrated prediction for SNY: 0.5023937821388245

Simulating Trading Days:  38%|███▊      | 38/100 [05:01<01:11,  1.15s/it]

Raw prediction for SO: 0.5034961104393005
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.385880708694458
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4205596148967743
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5983915328979492
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4707278907299042
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4017634987831116
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4076571762561798
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4438202679157257
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2455429583787918
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.44409865140914917
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48713093996047974
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.07359731197357178
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5638774037361145
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4726276099681854
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5033636689186096
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.47120392322540283
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5015565752983093
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.462
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.904, kelly=0.157) with $4063.74
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.954, kelly=0.171) with $4405.92
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.445
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.114, kelly=0.052) with $1341.78
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.028, kelly=0.174) with $4483.72
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.021, kelly=0.187) with $4841.61
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.470
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.003, kelly=0.144) with $3714.61
[PORT] Sector Services: 10 candidates, avg score=0.509
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.035, kelly=0.292) with $7549.56
[PORT] Sector Technology: 10 candidates, avg score=0.490
[PORT] Sector Technology: selecting T (p=0.642, b=0.981, kelly=0.277) with $7153.46
[PORT] Sector Utilities: 10 candidates, avg score=0.491
[PORT] Sector Utilities: selecting PPL (p=0.530, b=0.912, kelly=0.016) with $401.63
Raw prediction for AAPL: 0.4965490400791168
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5099880695343018
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2672480642795563
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5259799361228943
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.4378533363342285
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.515985369682312
Calibrated prediction for AMGN: 0.5185185074806213
Raw prediction for AMZN: 0.6080873608589172
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.47111427783966064
Calibrated prediction for BA: 0.5103265047073364
Raw prediction for BABA: 0.5724940896034241
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4764218330383301
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4728802442550659
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.490268737077713
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4881977438926697
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4292301535606384
Calibrated prediction for BP: 0.40809041261672974
Raw prediction for BRK-A: 0.49319130182266235
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48490068316459656
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.46893739700317383
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5145756006240845
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47050386667251587
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5210019946098328
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.4822137653827667
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.5496593117713928
Calibrated prediction for CHTR: 0.5833333134651184
Raw prediction for CMCSA: 0.37174108624458313
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.45212823152542114
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4834221601486206
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4983988106250763
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5136787295341492
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5113131999969482
Calibrated prediction for DHR: 0.5131880044937134
Raw prediction for DIS: 0.49841123819351196
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4175850450992584
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5093288421630859
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5142607092857361
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5328357815742493
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44109171628952026
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.39816853404045105
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4512885808944702
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.4664698839187622
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5926525592803955
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3920591175556183
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5549547076225281
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.549911379814148
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3918929398059845
Calibrated prediction for JNJ: 0.32113856077194214
Raw prediction for JPM: 0.5393571853637695
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4670430123806
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4747433066368103
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.41186678409576416
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5255409479141235
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.49163609743118286
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5598441958427429
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49732762575149536
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46031007170677185
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4987371861934662
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5221237540245056
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5050520300865173
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4634440541267395
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4226808249950409
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5223606824874878
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5789408087730408
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47376805543899536
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46485447883605957
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4396084249019623
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4560911953449249
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5232712030410767
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4663660228252411
Calibrated prediction for PPL: 0.4806121587753296
Raw prediction for PTR: 0.42950811982154846
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5352010130882263
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.46411532163619995
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.47814661264419556
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4921247065067291
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5026596784591675
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5034855008125305
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.39910295605659485
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4276733696460724
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5985909700393677
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4320782721042633
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.3935874104499817
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.402246356010437
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.44338366389274597
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.24550628662109375
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4409216642379761
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4865214228630066
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.05234115570783615
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5635411143302917
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4698861241340637
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5035874247550964
Calibrated prediction for WFC: 0.5066666603088379

Simulating Trading Days:  39%|███▉      | 39/100 [05:02<01:10,  1.15s/it]

Raw prediction for WMT: 0.46907734870910645
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.505756676197052
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.467
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.902, kelly=0.157) with $4042.92
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.952, kelly=0.170) with $4375.61
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.445
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.114, kelly=0.052) with $1339.29
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.026, kelly=0.173) with $4464.16
[PORT] Sector Healthcare: 10 candidates, avg score=0.440
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.023, kelly=0.188) with $4851.14
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.468
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.005, kelly=0.145) with $3728.79
[PORT] Sector Services: 10 candidates, avg score=0.508
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.037, kelly=0.293) with $7556.75
[PORT] Sector Technology: 10 candidates, avg score=0.490
[PORT] Sector Technology: selecting T (p=0.642, b=0.983, kelly=0.278) with $7162.47
[PORT] Sector Utilities: 10 candidates, avg score=0.486
[PORT] Sector Utilities: Kelly <= 0 for NEE (p=0.526, b=0.898)
Raw prediction for AAPL: 0.49634137749671936
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5082088112831116
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2894400656223297
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5267508029937744
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.43629685044288635
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5142497420310974
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.5982160568237305
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.46936696767807007
Calibrated prediction for BA: 0.49935460090637207
Raw prediction for BABA: 0.572394609451294
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4779912531375885
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4825437366962433
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4912523925304413
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48847270011901855
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.42432302236557007
Calibrated prediction for BP: 0.40809041261672974
Raw prediction for BRK-A: 0.49309828877449036
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4848969280719757
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4625207781791687
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5146135687828064
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47042831778526306
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5006345510482788
Calibrated prediction for CELG: 0.5454545617103577
Raw prediction for CHL: 0.4927053451538086
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5575699210166931
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3709126114845276
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44381266832351685
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4835685193538666
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4993593692779541
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5135095715522766
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5105476379394531
Calibrated prediction for DHR: 0.5041038393974304
Raw prediction for DIS: 0.49837225675582886
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.41487935185432434
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5085601806640625
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.514228105545044
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5327582359313965
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.43775683641433716
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.39772769808769226
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4529055058956146
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.466244101524353
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5932466387748718
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3856358230113983
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5544532537460327
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5546268820762634
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3901320993900299
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5396988391876221
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4669703543186188
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.467634379863739
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.40676409006118774
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5251396894454956
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.4914553463459015
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5593163967132568
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4899340569972992
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4601355493068695
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.49786072969436646
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5211842656135559
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5081619024276733
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.45997604727745056
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4220751225948334
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.522493839263916
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5783279538154602
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4742293059825897
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46474143862724304
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43928810954093933
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4608188569545746
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5259470343589783
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.46497341990470886
Calibrated prediction for PPL: 0.4791666567325592
Raw prediction for PTR: 0.44776177406311035
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5383918285369873
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.47994866967201233
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.47705671191215515
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49288681149482727
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5027065277099609
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.503451406955719
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4106842279434204
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.43277958035469055
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5987791419029236
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.3962514400482178
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.38889357447624207
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.3875296115875244
Calibrated prediction for TSM: 0.41800421476364136

Simulating Trading Days:  40%|████      | 40/100 [05:03<01:08,  1.15s/it]

Raw prediction for UL: 0.4428611993789673
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2428545206785202
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.43797212839126587
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48603561520576477
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.042729452252388
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5629710555076599
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4648314118385315
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.503715991973877
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46679991483688354
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5062212347984314
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.484
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.900, kelly=0.156) with $4016.34
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.952, kelly=0.170) with $4376.33
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.439
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.113, kelly=0.051) with $1320.83
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4467.90
[PORT] Sector Healthcare: 10 candidates, avg score=0.432
[PORT] Sector Healthcare: selecting CELG (p=0.545, b=1.023, kelly=0.101) with $2613.79
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.466
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.006, kelly=0.145) with $3741.49
[PORT] Sector Services: 10 candidates, avg score=0.511
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.040, kelly=0.294) with $7577.87
[PORT] Sector Technology: 10 candidates, avg score=0.502
[PORT] Sector Technology: selecting T (p=0.642, b=0.985, kelly=0.278) with $7180.20
[PORT] Sector Utilities: 10 candidates, avg score=0.490
[PORT] Sector Utilities: Kelly <= 0 for NEE (p=0.526, b=0.896)
Raw prediction for AAPL: 0.4961985647678375
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5056473016738892
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.317278116941452
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5304489135742188
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.435171514749527
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5129817128181458
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.5968040823936462
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.4691024422645569
Calibrated prediction for BA: 0.49445003271102905
Raw prediction for BABA: 0.57329922914505
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4795278012752533
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.48843371868133545
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4919401705265045
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4886285066604614
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.42069873213768005
Calibrated prediction for BP: 0.40809041261672974
Raw prediction for BRK-A: 0.49305516481399536
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48503631353378296
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4552217423915863
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5145585536956787
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.470392107963562
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4843575656414032
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.5068056583404541
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5626773834228516
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3692097067832947
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4363635778427124
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4845457971096039
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.5003930926322937
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5132688283920288
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5105680823326111
Calibrated prediction for DHR: 0.5043464303016663
Raw prediction for DIS: 0.4981588125228882
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.41535383462905884
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5079406499862671
Calibrated prediction for EXC: 0.5061447620391846
Raw prediction for FB: 0.5142562985420227
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5325454473495483
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4394555985927582
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.3997986912727356
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4550056457519531
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.46808764338493347
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.594673216342926
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.38502517342567444
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.55193030834198
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5643187165260315
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3893111050128937
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5395109057426453
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4668746292591095
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4613703489303589
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.4050517976284027
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5251256823539734
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.49042966961860657
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5597990155220032
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4781643748283386
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46030330657958984
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.49948209524154663
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5203573703765869
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5110465884208679
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.45635727047920227
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4224276840686798
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5225739479064941
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5792037844657898
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47458264231681824
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46479761600494385
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4388652443885803
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4635828733444214
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5256434082984924
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4657358229160309
Calibrated prediction for PPL: 0.4791666567325592
Raw prediction for PTR: 0.4652809500694275
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5410484671592712
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.49679410457611084
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.4746743142604828
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49398744106292725
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5028854012489319
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5034463405609131
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4213542938232422
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4381985664367676
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.5991690754890442
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.36570173501968384
Calibrated prediction for TM: 0.3076923191547394
Raw prediction for TOT: 0.38425323367118835
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.38053733110427856
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.44189026951789856
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.23787328600883484
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.43246546387672424
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4857666492462158
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.04233085364103317
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5641979575157166
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4644932150840759
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5040512681007385
Calibrated prediction for WFC: 0.5066666603088379

Simulating Trading Days:  41%|████      | 41/100 [05:05<01:09,  1.17s/it]

Raw prediction for WMT: 0.4665428400039673
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5038592219352722
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.900, kelly=0.156) with $4014.01
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.950, kelly=0.169) with $4352.98
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.436
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.111, kelly=0.051) with $1307.71
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.025, kelly=0.173) with $4448.03
[PORT] Sector Healthcare: 10 candidates, avg score=0.423
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.005, kelly=0.007) with $187.89
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.466
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.008, kelly=0.146) with $3758.96
[PORT] Sector Services: 10 candidates, avg score=0.511
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.037, kelly=0.293) with $7550.46
[PORT] Sector Technology: 10 candidates, avg score=0.502
[PORT] Sector Technology: selecting T (p=0.642, b=0.982, kelly=0.278) with $7154.16
[PORT] Sector Utilities: 10 candidates, avg score=0.489
[PORT] Sector Utilities: Kelly <= 0 for NEE (p=0.526, b=0.896)
Raw prediction for AAPL: 0.4960397183895111
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5038722157478333
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.33378785848617554
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5348798632621765
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.4342505931854248
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5119285583496094
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6011614203453064
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.4696093201637268
Calibrated prediction for BA: 0.5
Raw prediction for BABA: 0.5726706385612488
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4803645610809326
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4952186644077301
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4931688606739044
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48879489302635193
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4314964711666107
Calibrated prediction for BP: 0.40809041261672974
Raw prediction for BRK-A: 0.4930110573768616
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48549923300743103
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4521203339099884
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5146539807319641
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4705834686756134
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4706995487213135
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.5132322907447815
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5646931529045105
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3710307478904724
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4262263774871826
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4842837452888489
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.5009622573852539
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5131043791770935
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5107594728469849
Calibrated prediction for DHR: 0.5066174864768982
Raw prediction for DIS: 0.4977881908416748
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4195042848587036
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5074180364608765
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5141897797584534
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5325066447257996
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4438523054122925
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4008104205131531
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4578128755092621
Calibrated prediction for HD: 0.44859635829925537
Raw prediction for HON: 0.47113317251205444
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5971128344535828
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3876664936542511
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5485466718673706
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5705322027206421
Calibrated prediction for INTC: 0.557692289352417
Raw prediction for JNJ: 0.3903215527534485
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5388482213020325
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46709808707237244
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.44976627826690674
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.4042414426803589
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5254969000816345
Calibrated prediction for MCD: 0.5249508619308472
Raw prediction for MDT: 0.48971566557884216
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5615047216415405
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4679388701915741
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4609611928462982
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5023362636566162
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5200698375701904
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5128991007804871
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4528098702430725
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4225318729877472
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5227010250091553
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5761861801147461
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4749751389026642
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4649493992328644
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4385260045528412
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4647701680660248
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5267446041107178
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4706522822380066
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.48413604497909546
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5444545745849609
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.511182427406311
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.4726235270500183
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49430111050605774
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5031155347824097
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5035812258720398
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.42904767394065857
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.44238603115081787
Calibrated prediction for SRE: 0.4992761015892029
Raw prediction for T: 0.5996568202972412
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.3619080185890198
Calibrated prediction for TM: 0.3076923191547394
Raw prediction for TOT: 0.3819003701210022
Calibrated prediction for TOT: 0.4000000059604645

Simulating Trading Days:  42%|████▏     | 42/100 [05:06<01:07,  1.16s/it]

Raw prediction for TSM: 0.37056615948677063
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.44156885147094727
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2346821427345276
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4222432076931
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4858148694038391
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.047067951411008835
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5647960305213928
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4614786207675934
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5044897794723511
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46543875336647034
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5032837986946106
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.902, kelly=0.156) with $4019.10
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.951, kelly=0.169) with $4347.56
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.436
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.114, kelly=0.052) with $1326.37
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.025, kelly=0.173) with $4437.00
[PORT] Sector Healthcare: 10 candidates, avg score=0.423
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.006, kelly=0.008) with $203.86
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.466
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.007, kelly=0.146) with $3741.28
[PORT] Sector Services: 10 candidates, avg score=0.511
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.035, kelly=0.292) with $7512.61
[PORT] Sector Technology: 10 candidates, avg score=0.504
[PORT] Sector Technology: selecting T (p=0.642, b=0.983, kelly=0.278) with $7137.57
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting PPL (p=0.530, b=0.918, kelly=0.019) with $478.34
Raw prediction for AAPL: 0.49610912799835205
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5034478902816772
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3481619954109192
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5420597791671753
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.43348243832588196
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.51101154088974
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6069275736808777
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.4703613519668579
Calibrated prediction for BA: 0.5
Raw prediction for BABA: 0.559680700302124
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4800201654434204
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.5011786222457886
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.49745285511016846
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48886731266975403
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.44477835297584534
Calibrated prediction for BP: 0.40809041261672974
Raw prediction for BRK-A: 0.49298951029777527
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4858820140361786
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4602327048778534
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.514948844909668
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4708653688430786
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4594537913799286
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5208030939102173
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5743187069892883
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.40302377939224243
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.41767898201942444
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4828748404979706
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.5012646913528442
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5129104256629944
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5111499428749084
Calibrated prediction for DHR: 0.5112507939338684
Raw prediction for DIS: 0.4964876174926758
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.42808857560157776
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5077394247055054
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5142565965652466
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.53276526927948
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4486173987388611
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4024637043476105
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4646379053592682
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47435835003852844
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6009401082992554
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.388664573431015
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5456024408340454
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5743143558502197
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3916342854499817
Calibrated prediction for JNJ: 0.31432992219924927
Raw prediction for JPM: 0.5378040671348572
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4677242338657379
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4438557028770447
Calibrated prediction for LMT: 0.4468507766723633
Raw prediction for MA: 0.4075441360473633
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5258734226226807
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4890635013580322
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5645229816436768
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.45962658524513245
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46191728115081787
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.507796049118042
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.520846962928772
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5137802958488464
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4540731906890869
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4223968982696533
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5227360129356384
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6215735077857971
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4756222665309906
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46541333198547363
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4383999705314636
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46521592140197754
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5380851626396179
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4821147620677948
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5016387104988098
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5480241775512695
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.522979736328125
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.46992170810699463
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49410730600357056
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5033881664276123
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5037803053855896
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4375079572200775
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.45895957946777344
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6013954877853394
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.38819682598114014
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.3802117109298706
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.3628157079219818
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.44221219420433044
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.24272564053535461
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4211605191230774
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4860866367816925
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.0461573526263237
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5652002692222595
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4632434546947479
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5049448609352112
Calibrated prediction for WFC: 0.5066666603088379

Simulating Trading Days:  43%|████▎     | 43/100 [05:07<01:06,  1.16s/it]

Raw prediction for WMT: 0.45007413625717163
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5033707022666931
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.901, kelly=0.156) with $4007.78
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.949, kelly=0.168) with $4324.89
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.439
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.105, kelly=0.048) with $1236.21
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.023, kelly=0.172) with $4413.09
[PORT] Sector Healthcare: 10 candidates, avg score=0.419
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.004, kelly=0.007) with $178.67
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.461
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.007, kelly=0.145) with $3731.59
[PORT] Sector Services: 10 candidates, avg score=0.522
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.032, kelly=0.324) with $8333.32
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.964, kelly=0.297) with $7640.18
[PORT] Sector Utilities: 10 candidates, avg score=0.512
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.902, kelly=0.096) with $2470.09
Raw prediction for AAPL: 0.4960559010505676
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5044140815734863
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.35946133732795715
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.5517935752868652
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.43250876665115356
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5101147890090942
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6718095541000366
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.471126914024353
Calibrated prediction for BA: 0.5105332136154175
Raw prediction for BABA: 0.5563229918479919
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4782596826553345
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.5051007270812988
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5092132091522217
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48889994621276855
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.45566287636756897
Calibrated prediction for BP: 0.40809041261672974
Raw prediction for BRK-A: 0.49316081404685974
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.485979288816452
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.47713425755500793
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5153471827507019
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47110357880592346
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4496716856956482
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5409187078475952
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5885648727416992
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4160386025905609
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4093523919582367
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.48329415917396545
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.5014825463294983
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5127302408218384
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5117194652557373
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49595537781715393
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4424726068973541
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5082567930221558
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5151312947273254
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.53302401304245
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.45033934712409973
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.41499781608581543
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.47102057933807373
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47659122943878174
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6050915718078613
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.39294540882110596
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.540058970451355
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5787554383277893
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.39203065633773804
Calibrated prediction for JNJ: 0.3247637152671814
Raw prediction for JPM: 0.5363469123840332
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4687136709690094
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.44494888186454773
Calibrated prediction for LMT: 0.49098658561706543
Raw prediction for MA: 0.42131495475769043
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5266099572181702
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4890124797821045
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5662819743156433
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.457784503698349
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4627067744731903
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5212571024894714
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5253347158432007
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5149102210998535
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.45465487241744995
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4258686304092407
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5227663516998291
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6445125341415405
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47662219405174255
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46528568863868713
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4383980333805084
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46468064188957214
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5752846598625183
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.49669063091278076
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5243315696716309
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5527729988098145
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5329937934875488
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.4690127372741699
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4938775599002838
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.503326416015625
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5040273666381836
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.44253262877464294
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.49018266797065735
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6037696599960327
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4619121253490448
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.37991347908973694
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.42072150111198425
Calibrated prediction for TSM: 0.41800421476364136

Simulating Trading Days:  44%|████▍     | 44/100 [05:08<01:04,  1.16s/it]

Raw prediction for UL: 0.4448326528072357
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2602751851081848
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.42288145422935486
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4864257276058197
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.04613808915019035
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5651583671569824
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4729800820350647
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5056989789009094
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.44426724314689636
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4994647204875946
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.494
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.900, kelly=0.156) with $4009.40
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.948, kelly=0.168) with $4317.76
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.445
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.101, kelly=0.046) with $1195.75
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.022, kelly=0.172) with $4417.55
[PORT] Sector Healthcare: 10 candidates, avg score=0.420
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.004, kelly=0.007) with $171.54
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.005, kelly=0.145) with $3724.41
[PORT] Sector Services: 10 candidates, avg score=0.529
[PORT] Sector Services: selecting PCLN (p=0.657, b=1.031, kelly=0.324) with $8345.38
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.962, kelly=0.297) with $7639.66
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.902, kelly=0.097) with $2486.34
Raw prediction for AAPL: 0.49602359533309937
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5074703693389893
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3717828691005707
Calibrated prediction for ABBV: 0.28595682978630066
Raw prediction for AEP: 0.5645037293434143
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.431010365486145
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5092727541923523
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.725841760635376
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4722765386104584
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5626282095909119
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47571390867233276
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.5089235901832581
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5168346762657166
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48882120847702026
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.46325474977493286
Calibrated prediction for BP: 0.4285714328289032
Raw prediction for BRK-A: 0.4932084083557129
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48589134216308594
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4905710518360138
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5158983469009399
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4709376096725464
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4435688257217407
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.552568793296814
Calibrated prediction for CHL: 0.5880217552185059
Raw prediction for CHTR: 0.5937132835388184
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.43701058626174927
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.40544992685317993
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4847133457660675
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.501213788986206
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5127817392349243
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5135576128959656
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49602147936820984
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.46005892753601074
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5088452100753784
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5159130096435547
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5333050489425659
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4550752639770508
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4342663586139679
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4750690162181854
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4808846116065979
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6093537211418152
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4040836989879608
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5278033018112183
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5788429379463196
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3922577202320099
Calibrated prediction for JNJ: 0.3307408094406128
Raw prediction for JPM: 0.5345624685287476
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4696393609046936
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4780365824699402
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.45656174421310425
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5275611877441406
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4874725937843323
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5706260204315186
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.45707187056541443
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4633495509624481
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5323148369789124
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.530685305595398
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5160800218582153
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.457000195980072
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4295223355293274
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5227184295654297
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6626236438751221
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.477559894323349
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4650544822216034
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43831512331962585
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46359243988990784
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6198126673698425
Calibrated prediction for PM: 0.5833333134651184
Raw prediction for PPL: 0.5156203508377075
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5490134358406067
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5543352961540222
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5416135191917419
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.46762150526046753
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49275511503219604
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5032263398170471
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5043382048606873
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4439300000667572
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5283570289611816
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6026905179023743
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5482231378555298
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.3798081576824188
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.48339396715164185
Calibrated prediction for TSM: 0.5206655859947205
Raw prediction for UL: 0.44846242666244507
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.288210391998291
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.43723031878471375
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48655641078948975
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.04444582760334015
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5671747326850891
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4829553961753845
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5061233639717102
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.43779876828193665
Calibrated prediction for WMT: 0.44648152589797974

Simulating Trading Days:  45%|████▌     | 45/100 [05:09<01:03,  1.15s/it]

Raw prediction for XOM: 0.4926460087299347
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.496
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.899, kelly=0.155) with $3985.66
[PORT] Sector Conglomerates: 7 candidates, avg score=0.476
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.950, kelly=0.169) with $4333.54
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.488
[PORT] Sector Consumer Goods: selecting PM (p=0.583, b=1.027, kelly=0.178) with $4564.61
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.024, kelly=0.172) with $4429.66
[PORT] Sector Healthcare: 10 candidates, avg score=0.420
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.001, kelly=0.006) with $141.87
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.470
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.006, kelly=0.145) with $3722.95
[PORT] Sector Services: 10 candidates, avg score=0.553
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.050, kelly=0.744) with $19118.93
[PORT] Sector Technology: 10 candidates, avg score=0.529
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.960, kelly=0.296) with $7613.92
[PORT] Sector Utilities: 10 candidates, avg score=0.527
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.901, kelly=0.185) with $4755.31
Raw prediction for AAPL: 0.49593284726142883
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.510219156742096
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3848302364349365
Calibrated prediction for ABBV: 0.30000001192092896
Raw prediction for AEP: 0.574615478515625
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4290693700313568
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5087546110153198
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7421025037765503
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4727960228919983
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5718104243278503
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4730956256389618
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5101106762886047
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5152832865715027
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4885914623737335
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4640248715877533
Calibrated prediction for BP: 0.4285714328289032
Raw prediction for BRK-A: 0.49315881729125977
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48560747504234314
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.49152296781539917
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5164199471473694
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4708312451839447
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.43851515650749207
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5447377562522888
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5861120223999023
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.46651673316955566
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4022639989852905
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.484466552734375
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.5006667971611023
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5128096342086792
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5149385333061218
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49647533893585205
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4774353504180908
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5089523792266846
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5165322422981262
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5335162878036499
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.45719534158706665
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.45414334535598755
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4768867790699005
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4810796082019806
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6143274307250977
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.41355258226394653
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.5065080523490906
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5752905607223511
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.39071112871170044
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5325519442558289
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4703875780105591
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5126291513442993
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.4827721416950226
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5281611680984497
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4857887625694275
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5721675157546997
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.45467567443847656
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4638484716415405
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5462885499000549
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5338600873947144
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5159810185432434
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4585290849208832
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4318912923336029
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5225083827972412
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6556850671768188
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4781635105609894
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46459537744522095
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4381209909915924
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4629390239715576
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.654617190361023
Calibrated prediction for PM: 0.7376610636711121
Raw prediction for PPL: 0.5328628420829773
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5626628994941711
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5499359965324402
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5430448651313782
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.46125924587249756
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4915049970149994
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5030896067619324
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5045865178108215
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4432065784931183
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5652015209197998
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.600186824798584
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5652921199798584
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.3789825737476349
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5104154348373413
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4525134861469269
Calibrated prediction for UL: 0.45108622312545776

Simulating Trading Days:  46%|████▌     | 46/100 [05:10<01:02,  1.15s/it]

Raw prediction for UN: 0.320293128490448
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4534471035003662
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48628371953964233
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.04043056070804596
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5675894618034363
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.48827430605888367
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5063362717628479
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.4364171624183655
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4868321120738983
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.490
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.899, kelly=0.155) with $3972.58
[PORT] Sector Conglomerates: 7 candidates, avg score=0.485
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.951, kelly=0.301) with $7724.20
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.503
[PORT] Sector Consumer Goods: selecting PM (p=0.738, b=1.027, kelly=0.482) with $12365.47
[PORT] Sector Financial: 10 candidates, avg score=0.497
[PORT] Sector Financial: selecting V (p=0.581, b=1.023, kelly=0.172) with $4400.36
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=0.999, kelly=0.004) with $114.07
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.005, kelly=0.144) with $3703.83
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.052, kelly=0.744) with $19072.68
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.960, kelly=0.296) with $7594.64
[PORT] Sector Utilities: 10 candidates, avg score=0.530
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.900, kelly=0.185) with $4731.37
Raw prediction for AAPL: 0.49582386016845703
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5126012563705444
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3972683250904083
Calibrated prediction for ABBV: 0.30000001192092896
Raw prediction for AEP: 0.5818206667900085
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4273274838924408
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5084717869758606
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.746941864490509
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.47247549891471863
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.580907940864563
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4706907868385315
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5127244591712952
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5063667893409729
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48835688829421997
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.470052033662796
Calibrated prediction for BP: 0.4285714328289032
Raw prediction for BRK-A: 0.49312102794647217
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.485249787569046
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48669055104255676
Calibrated prediction for BUD: 0.49318212270736694
Raw prediction for C: 0.5167232751846313
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.47065383195877075
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4358024597167969
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5303835868835449
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5838812589645386
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.48949265480041504
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4006043076515198
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4835483133792877
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49893617630004883
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5129294395446777
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5157354474067688
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4971774220466614
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.49107038974761963
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5089705586433411
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5168642401695251
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5337002277374268
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4579944610595703
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4751906991004944
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.4767773747444153
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.48084333539009094
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6189372539520264
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.4263703525066376
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4801068902015686
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5735273957252502
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.38801729679107666
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5306496024131775
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47086283564567566
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5429890751838684
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5031328797340393
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.528606653213501
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48444393277168274
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5724861025810242
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.45576944947242737
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46417856216430664
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5600028038024902
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.534936249256134
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5145810842514038
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4587550759315491
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4336414337158203
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5223738551139832
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.652803897857666
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4784659147262573
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.464187353849411
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4380217492580414
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4612836241722107
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6705222725868225
Calibrated prediction for PM: 0.7376610636711121
Raw prediction for PPL: 0.5461977124214172
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5740849375724792
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5424626469612122
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5405761003494263
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4573194086551666
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4897182285785675
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.502865195274353
Calibrated prediction for SNY: 0.5023937821388245

Simulating Trading Days:  47%|████▋     | 47/100 [05:12<01:00,  1.15s/it]

Raw prediction for SO: 0.5048582553863525
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.44258037209510803
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.605708122253418
Calibrated prediction for SRE: 0.6125012636184692
Raw prediction for T: 0.5971481800079346
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5739288330078125
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.3783034384250641
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5157150626182556
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45664048194885254
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.353324294090271
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4637913405895233
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48593470454216003
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.03822053223848343
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.567888081073761
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4924958050251007
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5064212083816528
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.43697407841682434
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4844733774662018
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.490
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.899, kelly=0.155) with $3998.91
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.950, kelly=0.301) with $7757.85
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.503
[PORT] Sector Consumer Goods: selecting PM (p=0.738, b=1.027, kelly=0.482) with $12434.92
[PORT] Sector Financial: 10 candidates, avg score=0.497
[PORT] Sector Financial: selecting V (p=0.581, b=1.022, kelly=0.171) with $4416.57
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: allocation $90.31 below minimum for SNY
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.004, kelly=0.144) with $3722.62
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.052, kelly=0.744) with $19182.87
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.961, kelly=0.297) with $7648.42
[PORT] Sector Utilities: 10 candidates, avg score=0.542
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.899, kelly=0.184) with $4742.18
Raw prediction for AAPL: 0.49576878547668457
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.514714241027832
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.41312548518180847
Calibrated prediction for ABBV: 0.30000001192092896
Raw prediction for AEP: 0.5873731970787048
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4262775182723999
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.508341372013092
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7516584992408752
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4711882770061493
Calibrated prediction for BA: 0.5115369558334351
Raw prediction for BABA: 0.5889053344726562
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46862879395484924
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5144715309143066
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.4940204620361328
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48827433586120605
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4795674979686737
Calibrated prediction for BP: 0.5
Raw prediction for BRK-A: 0.4929402768611908
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48491719365119934
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4802473783493042
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5167840123176575
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4705217778682709
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.43487444519996643
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5211182236671448
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5819424390792847
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5049204230308533
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4011288583278656
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.48198407888412476
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.497003436088562
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.513056755065918
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5161557793617249
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4978937804698944
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.49857044219970703
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5088219046592712
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5169870257377625
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5339658260345459
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.458401083946228
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.4969027042388916
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.47514256834983826
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4799201190471649
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6233970522880554
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.43390563130378723
Calibrated prediction for HSBC: 0.4615384638309479
Raw prediction for IEP: 0.4538097679615021
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5756058096885681
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.38224735856056213
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.529185950756073
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4712747633457184
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5742679834365845
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5354184508323669
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5289052128791809
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4837435185909271
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5737870931625366
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.46160027384757996
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46464747190475464
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.573509693145752
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.534572958946228
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5127467513084412
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.459343284368515
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43795278668403625
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5223804116249084
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6597540378570557
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47856172919273376
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4638451635837555
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43786686658859253
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4576593339443207
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6711392998695374
Calibrated prediction for PM: 0.7376610636711121
Raw prediction for PPL: 0.5555325150489807
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5803766846656799
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5367550849914551
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5378844141960144
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.45719000697135925
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4880058765411377
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5027577877044678
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5049766302108765
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4421483874320984
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.6311284899711609
Calibrated prediction for SRE: 0.6532158255577087
Raw prediction for T: 0.5945703387260437
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5804423093795776
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.38050857186317444
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5198053121566772
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4602982997894287
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3853926360607147
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.47397828102111816
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48560091853141785
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.034430745989084244
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5685831308364868
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4994440972805023
Calibrated prediction for VZ: 0.45679011940956116

Simulating Trading Days:  48%|████▊     | 48/100 [05:13<00:59,  1.15s/it]

Raw prediction for WFC: 0.5064369440078735
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.43485429883003235
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4830436706542969
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.497
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.901, kelly=0.156) with $4032.37
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.951, kelly=0.301) with $7782.54
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.502
[PORT] Sector Consumer Goods: selecting PM (p=0.738, b=1.028, kelly=0.482) with $12471.97
[PORT] Sector Financial: 10 candidates, avg score=0.504
[PORT] Sector Financial: selecting V (p=0.581, b=1.022, kelly=0.171) with $4427.16
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.000, kelly=0.005) with $119.40
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.481
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.054, kelly=0.269) with $6963.01
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.054, kelly=0.744) with $19235.51
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.963, kelly=0.297) with $7684.42
[PORT] Sector Utilities: 10 candidates, avg score=0.546
[PORT] Sector Utilities: selecting SRE (p=0.653, b=0.915, kelly=0.274) with $7091.82
Raw prediction for AAPL: 0.4957900047302246
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5168282389640808
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.4116358160972595
Calibrated prediction for ABBV: 0.30000001192092896
Raw prediction for AEP: 0.5922822952270508
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.42606186866760254
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5084215998649597
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7489909529685974
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46906498074531555
Calibrated prediction for BA: 0.4937554597854614
Raw prediction for BABA: 0.5873103141784668
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46704551577568054
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5145552158355713
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.4773746728897095
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4883910119533539
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4847029745578766
Calibrated prediction for BP: 0.5104685425758362
Raw prediction for BRK-A: 0.49259263277053833
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48462074995040894
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4767175614833832
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5167708992958069
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4702640771865845
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.43241673707962036
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5163546204566956
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5784047842025757
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5203710198402405
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.40201255679130554
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.48009711503982544
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4959867596626282
Calibrated prediction for CVX: 0.5
Raw prediction for D: 0.5132067799568176
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.516714870929718
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4982576370239258
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.49850594997406006
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5087133646011353
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5172533392906189
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.534162163734436
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.45791539549827576
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5183153748512268
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.47387975454330444
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47938627004623413
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6289189457893372
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.4314744174480438
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.43293341994285583
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5773047804832458
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3816271722316742
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5283173322677612
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4716954827308655
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6036813855171204
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5519639253616333
Calibrated prediction for MA: 0.6666666865348816
Raw prediction for MCD: 0.5289193987846375
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4822324514389038
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5752884149551392
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.47447237372398376
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46522805094718933
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5814862847328186
Calibrated prediction for MSFT: 0.5925455689430237
Raw prediction for NEE: 0.5337079167366028
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5101852416992188
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4581439197063446
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43892934918403625
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.522412121295929
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6768444180488586
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4786137640476227
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46360501646995544
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4377956688404083
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4563952088356018
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6611563563346863
Calibrated prediction for PM: 0.7376610636711121
Raw prediction for PPL: 0.5613514184951782
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5809153318405151
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.533210813999176
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5371865630149841
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.46409448981285095
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48867449164390564
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5027687549591064
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5051472187042236
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4395301938056946
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.6322035789489746
Calibrated prediction for SRE: 0.6532158255577087
Raw prediction for T: 0.591214656829834
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.6095597743988037
Calibrated prediction for TM: 0.5277777910232544

Simulating Trading Days:  49%|████▉     | 49/100 [05:14<00:58,  1.15s/it]

Raw prediction for TOT: 0.38387948274612427
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5127820372581482
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46300724148750305
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4128008186817169
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.47865161299705505
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48515087366104126
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.02732321433722973
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5695364475250244
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5147631168365479
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.506371796131134
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.42624104022979736
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4870784282684326
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.497
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.903, kelly=0.157) with $4049.74
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.950, kelly=0.301) with $7763.00
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.502
[PORT] Sector Consumer Goods: selecting PM (p=0.738, b=1.028, kelly=0.483) with $12459.30
[PORT] Sector Financial: 10 candidates, avg score=0.508
[PORT] Sector Financial: selecting MA (p=0.667, b=0.965, kelly=0.321) with $8296.74
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.001, kelly=0.005) with $140.37
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.479
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.053, kelly=0.269) with $6945.47
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.053, kelly=0.744) with $19209.26
[PORT] Sector Technology: 10 candidates, avg score=0.547
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.963, kelly=0.297) with $7672.18
[PORT] Sector Utilities: 10 candidates, avg score=0.546
[PORT] Sector Utilities: selecting SRE (p=0.653, b=0.917, kelly=0.275) with $7098.55
Raw prediction for AAPL: 0.4957257807254791
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5179738402366638
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.41455647349357605
Calibrated prediction for ABBV: 0.30000001192092896
Raw prediction for AEP: 0.5935476422309875
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4254487156867981
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5086151361465454
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7488398551940918
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46644383668899536
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5871245861053467
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.465921014547348
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5148130655288696
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.4705413579940796
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4884127378463745
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4825531840324402
Calibrated prediction for BP: 0.5
Raw prediction for BRK-A: 0.4923078715801239
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4843350648880005
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.46608126163482666
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5167201161384583
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4699469804763794
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.43075916171073914
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5000595450401306
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5666940808296204
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5329037308692932
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.40826040506362915
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47619763016700745
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49530696868896484
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5131998658180237
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5166361927986145
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4983052909374237
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.49410706758499146
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5082923769950867
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5171624422073364
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5342438220977783
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4549613296985626
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5326359868049622
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.47498375177383423
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4749191999435425
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6318966150283813
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.4194051921367645
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.42187198996543884
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5770489573478699
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.37963610887527466
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.527691125869751
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47186529636383057
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6195752024650574
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5533722639083862
Calibrated prediction for MA: 0.6666666865348816
Raw prediction for MCD: 0.5286732912063599
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48116669058799744
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5748651623725891
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.48355501890182495
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46555042266845703
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5830623507499695
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5316045880317688
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5072645545005798
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4539231061935425
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43507954478263855
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5223551988601685
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6696034073829651
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4785139560699463
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46320584416389465
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4375494122505188
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45565032958984375
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6409975290298462
Calibrated prediction for PM: 0.7142857313156128
Raw prediction for PPL: 0.5633208751678467
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5779935717582703
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5252903699874878
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5291911363601685
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.46552935242652893
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48870593309402466
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5025988817214966
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5050538182258606
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.44682177901268005
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.6172645688056946
Calibrated prediction for SRE: 0.6532158255577087
Raw prediction for T: 0.5878831148147583
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.6219977736473083
Calibrated prediction for TM: 0.529411792755127
Raw prediction for TOT: 0.3809537887573242
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4829237163066864
Calibrated prediction for TSM: 0.5063841938972473
Raw prediction for UL: 0.4647165536880493
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.42914196848869324
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.47798994183540344
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48477765917778015
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.022201405838131905
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5696941614151001
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5182029604911804
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.5061080455780029
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.43186336755752563
Calibrated prediction for WMT: 0.44648152589797974

Simulating Trading Days:  50%|█████     | 50/100 [05:15<00:57,  1.15s/it]

Raw prediction for XOM: 0.48504990339279175
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.900, kelly=0.156) with $4020.89
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.948, kelly=0.300) with $7746.49
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.500
[PORT] Sector Consumer Goods: selecting PM (p=0.714, b=1.029, kelly=0.437) with $11271.27
[PORT] Sector Financial: 10 candidates, avg score=0.508
[PORT] Sector Financial: selecting MA (p=0.667, b=0.968, kelly=0.322) with $8317.12
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.002, kelly=0.006) with $155.63
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.052, kelly=0.268) with $6930.60
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19216.18
[PORT] Sector Technology: 10 candidates, avg score=0.541
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.961, kelly=0.296) with $7653.28
[PORT] Sector Utilities: 10 candidates, avg score=0.542
[PORT] Sector Utilities: selecting SRE (p=0.653, b=0.918, kelly=0.275) with $7112.62
Raw prediction for AAPL: 0.4958062767982483
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5190810561180115
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.4258509874343872
Calibrated prediction for ABBV: 0.5061728358268738
Raw prediction for AEP: 0.5940073132514954
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.42486751079559326
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5086740851402283
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7703425288200378
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46451255679130554
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5880749821662903
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4653943181037903
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5204203128814697
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.4733206033706665
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4886215627193451
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4865555465221405
Calibrated prediction for BP: 0.5266780257225037
Raw prediction for BRK-A: 0.4919666647911072
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4844270944595337
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4557550847530365
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5166632533073425
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46958667039871216
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4310671389102936
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.49514874815940857
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5840668082237244
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.525905966758728
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4167505204677582
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4733812212944031
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49416446685791016
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5131474137306213
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5164223313331604
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49811315536499023
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4896899461746216
Calibrated prediction for DUK: 0.5213703513145447
Raw prediction for EXC: 0.5078915357589722
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.517042875289917
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5342215299606323
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.45231857895851135
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5462413430213928
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.4797421395778656
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4740258455276489
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6335023045539856
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.41271477937698364
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4171150326728821
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.581076979637146
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.37522244453430176
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5272623300552368
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4717177748680115
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6329801678657532
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.551093578338623
Calibrated prediction for MA: 0.6666666865348816
Raw prediction for MCD: 0.5284261107444763
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4801216125488281
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5753302574157715
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4836384356021881
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46538519859313965
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5823186039924622
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5300565958023071
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5048405528068542
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.44930946826934814
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.43111535906791687
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5222471356391907
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6626886129379272
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4782335162162781
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46285516023635864
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43733927607536316
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45494723320007324
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.619210422039032
Calibrated prediction for PM: 0.5833333134651184
Raw prediction for PPL: 0.5627896189689636
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5764402747154236
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5240024328231812
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5153392553329468
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.46703898906707764
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4891817569732666
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5025114417076111
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5048588514328003
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.45075586438179016
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.600355327129364
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5874811410903931
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.621734082698822
Calibrated prediction for TM: 0.529411792755127
Raw prediction for TOT: 0.38513830304145813
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.46779415011405945
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4652048945426941
Calibrated prediction for UL: 0.45108622312545776

Simulating Trading Days:  51%|█████     | 51/100 [05:16<00:56,  1.15s/it]

Raw prediction for UN: 0.439039945602417
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.4722995162010193
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48482102155685425
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.021945519372820854
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5708112716674805
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5317554473876953
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5057547092437744
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.4385421574115753
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.48314377665519714
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.498
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.900, kelly=0.156) with $4014.33
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.947, kelly=0.300) with $7729.08
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.488
[PORT] Sector Consumer Goods: selecting PM (p=0.583, b=1.026, kelly=0.177) with $4569.84
[PORT] Sector Financial: 10 candidates, avg score=0.508
[PORT] Sector Financial: selecting MA (p=0.667, b=0.966, kelly=0.321) with $8295.30
[PORT] Sector Healthcare: 10 candidates, avg score=0.439
[PORT] Sector Healthcare: allocation $70.14 below minimum for ABBV
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.049, kelly=0.268) with $6906.69
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19202.98
[PORT] Sector Technology: 10 candidates, avg score=0.546
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.962, kelly=0.297) with $7654.00
[PORT] Sector Utilities: 10 candidates, avg score=0.529
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.901, kelly=0.185) with $4765.39
Raw prediction for AAPL: 0.4958847761154175
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5200564861297607
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.4307762682437897
Calibrated prediction for ABBV: 0.5061728358268738
Raw prediction for AEP: 0.5993239283561707
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.42497172951698303
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.508276104927063
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7881455421447754
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4632827937602997
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5840514898300171
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4655173122882843
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5252581238746643
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.48792821168899536
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4888885021209717
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.49136823415756226
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4915410578250885
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4847525656223297
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.44930970668792725
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5165678262710571
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4693641662597656
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.42995885014533997
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.4911681115627289
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5905807018280029
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5232798457145691
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.42621028423309326
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.470792293548584
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4932428002357483
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5130434632301331
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5157185196876526
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4978393018245697
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4875602126121521
Calibrated prediction for DUK: 0.4935654401779175
Raw prediction for EXC: 0.5081996321678162
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5168597102165222
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.534168004989624
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44959473609924316
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5530314445495605
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.4869155287742615
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47672611474990845
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6351193189620972
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.41061925888061523
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4191960394382477
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5840751528739929
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.37493833899497986
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5269489884376526
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4716509282588959
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6456252932548523
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5428385138511658
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5281137824058533
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48223012685775757
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5771412253379822
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4795953929424286
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.464743435382843
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5774644017219543
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5305373072624207
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5043211579322815
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4381818175315857
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.4242015779018402
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5221296548843384
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6523117423057556
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4779564142227173
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.462345689535141
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4371017813682556
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4548940658569336
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6068469882011414
Calibrated prediction for PM: 0.5833333134651184
Raw prediction for PPL: 0.5621750950813293
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5778260231018066
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5270225405693054
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5015355348587036
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.4737960398197174
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48794034123420715
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5023995637893677
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5048207640647888
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4539808928966522
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5958413481712341
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.5961199998855591
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.6117522716522217
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.3922896087169647
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.44732773303985596
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4655015170574188
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4461466372013092
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.4534834623336792
Calibrated prediction for UNH: 0.380952388048172

Simulating Trading Days:  52%|█████▏    | 52/100 [05:17<00:56,  1.18s/it]

Raw prediction for UPS: 0.485353946685791
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.024989137426018715
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5718202590942383
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.54471755027771
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5053893327713013
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.44348400831222534
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.48318925499916077
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.499
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.902, kelly=0.157) with $4045.06
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.948, kelly=0.300) with $7746.59
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.488
[PORT] Sector Consumer Goods: selecting PM (p=0.583, b=1.027, kelly=0.178) with $4586.40
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.581, b=1.021, kelly=0.171) with $4419.75
[PORT] Sector Healthcare: 10 candidates, avg score=0.439
[PORT] Sector Healthcare: selecting ABBV (p=0.506, b=0.984, kelly=0.004) with $108.74
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.049, kelly=0.267) with $6907.03
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.057, kelly=0.745) with $19229.43
[PORT] Sector Technology: 10 candidates, avg score=0.541
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.963, kelly=0.297) with $7670.65
[PORT] Sector Utilities: 10 candidates, avg score=0.528
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.901, kelly=0.185) with $4771.60
Raw prediction for AAPL: 0.4960070550441742
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5202311873435974
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.4304664433002472
Calibrated prediction for ABBV: 0.5061728358268738
Raw prediction for AEP: 0.6020694971084595
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4255015552043915
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5075711607933044
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.803294837474823
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46272212266921997
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5836818814277649
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4661584496498108
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.526419997215271
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5063474774360657
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4891752004623413
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.49292075634002686
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4909033179283142
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4850395619869232
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.446052610874176
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.516342043876648
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46917957067489624
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4311148226261139
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.4993429481983185
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.595465362071991
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5193371772766113
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4327264428138733
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4675929844379425
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4931832551956177
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5129023194313049
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5146158337593079
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4976218640804291
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.49057838320732117
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5085510015487671
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5173594355583191
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5339236855506897
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.44324955344200134
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5579596161842346
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.4969562888145447
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.48207852244377136
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.635175883769989
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.41043317317962646
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4234126806259155
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5788601636886597
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.37556934356689453
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5267850160598755
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47165411710739136
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6298183798789978
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5305266976356506
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5278429985046387
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4850035607814789
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.578172504901886
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4716777801513672
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4637095034122467
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5703944563865662
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5322393178939819
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5047709345817566
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4230423867702484
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.41482001543045044
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5219529271125793
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.638190507888794
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47781848907470703
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46199801564216614
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43691250681877136
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45434263348579407
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6016826629638672
Calibrated prediction for PM: 0.5833333134651184
Raw prediction for PPL: 0.5614665746688843
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5814259052276611
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5306416749954224
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.49165743589401245
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.4851666986942291
Calibrated prediction for SLB: 0.4285714328289032
Raw prediction for SNP: 0.4890819191932678
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.502099335193634
Calibrated prediction for SNY: 0.5023937821388245

Simulating Trading Days:  53%|█████▎    | 53/100 [05:19<00:54,  1.17s/it]

Raw prediction for SO: 0.5048370957374573
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4562279284000397
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.591974675655365
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6132606863975525
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5852984189987183
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.40062302350997925
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4464375376701355
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4655504822731018
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4509342908859253
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.42549195885658264
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4862431287765503
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.031498782336711884
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5732902884483337
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.545062243938446
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5050082802772522
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4500235319137573
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4843370318412781
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.499
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.901, kelly=0.156) with $4018.25
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.946, kelly=0.299) with $7709.69
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.488
[PORT] Sector Consumer Goods: selecting PM (p=0.583, b=1.029, kelly=0.178) with $4597.26
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.581, b=1.023, kelly=0.172) with $4430.08
[PORT] Sector Healthcare: 10 candidates, avg score=0.437
[PORT] Sector Healthcare: selecting ABBV (p=0.506, b=0.985, kelly=0.005) with $122.13
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.047, kelly=0.267) with $6871.52
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19176.73
[PORT] Sector Technology: 10 candidates, avg score=0.541
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.964, kelly=0.297) with $7664.36
[PORT] Sector Utilities: 10 candidates, avg score=0.532
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.902, kelly=0.185) with $4778.58
Raw prediction for AAPL: 0.4961664080619812
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5195183753967285
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.4368313252925873
Calibrated prediction for ABBV: 0.5061728358268738
Raw prediction for AEP: 0.605312168598175
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.42567211389541626
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5067854523658752
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8044859170913696
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46194973587989807
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5799074769020081
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4673911929130554
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5253114700317383
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5224374532699585
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48917728662490845
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4939691722393036
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49027085304260254
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4854511320590973
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.44657158851623535
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.516044020652771
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46921730041503906
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.43033164739608765
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.493655800819397
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.6121588349342346
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5268160700798035
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.43414342403411865
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4665282964706421
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49433350563049316
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5128161907196045
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5140166282653809
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.497608482837677
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.49929895997047424
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.508341372013092
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5170122385025024
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5337548851966858
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.43455103039741516
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5588029623031616
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.5080798864364624
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.48871731758117676
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6359969973564148
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.4081381857395172
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.42844751477241516
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5727605223655701
Calibrated prediction for INTC: 0.6169837117195129
Raw prediction for JNJ: 0.3744526505470276
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5270113945007324
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4716549515724182
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5916430950164795
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.5195421576499939
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5275617241859436
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48370909690856934
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5791311264038086
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.46385839581489563
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46245020627975464
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5619634389877319
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5340117812156677
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5055351257324219
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4133230447769165
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.4035702645778656
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5217742323875427
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6339629292488098
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47781652212142944
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4620167016983032
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43669360876083374
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.45424672961235046
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5998607873916626
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5621294379234314
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5859084129333496
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5383772253990173
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.4917125403881073
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.496643990278244
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4927998185157776
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5021196007728577
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5049698948860168
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4566439688205719
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.593808650970459
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6249999403953552
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5545051097869873
Calibrated prediction for TM: 0.5277777910232544
Raw prediction for TOT: 0.4023682475090027
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.43239301443099976
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4654618203639984
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4542456865310669
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.40818819403648376
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48714110255241394
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.036694642156362534
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5732219815254211
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5401617288589478
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5046643018722534
Calibrated prediction for WFC: 0.5066666603088379

Simulating Trading Days:  54%|█████▍    | 54/100 [05:20<00:53,  1.17s/it]

Raw prediction for WMT: 0.4535021483898163
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4875173568725586
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.511
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.899, kelly=0.155) with $3974.57
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.947, kelly=0.300) with $7679.92
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.483
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.032, kelly=0.105) with $2685.96
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.581, b=1.025, kelly=0.173) with $4422.40
[PORT] Sector Healthcare: 10 candidates, avg score=0.437
[PORT] Sector Healthcare: allocation $93.33 below minimum for ABBV
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.048, kelly=0.267) with $6847.79
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.056, kelly=0.744) with $19076.98
[PORT] Sector Technology: 10 candidates, avg score=0.537
[PORT] Sector Technology: selecting T (p=0.642, b=0.980, kelly=0.277) with $7092.19
[PORT] Sector Utilities: 10 candidates, avg score=0.532
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.902, kelly=0.185) with $4742.83
Raw prediction for AAPL: 0.49631622433662415
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5179336667060852
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.4524313807487488
Calibrated prediction for ABBV: 0.5061728358268738
Raw prediction for AEP: 0.606458306312561
Calibrated prediction for AEP: 0.6143701076507568
Raw prediction for AGFS: 0.42498689889907837
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.506475567817688
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8071408867835999
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4609091281890869
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.58000248670578
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4696120023727417
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5248225331306458
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5317366123199463
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4890493154525757
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.49537062644958496
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.48972904682159424
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48560449481010437
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.44709426164627075
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.515800416469574
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46926671266555786
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4300854206085205
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.48598581552505493
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.6139554381370544
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5276107788085938
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.43508419394493103
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4666997194290161
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4951894283294678
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5127502083778381
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5135780572891235
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49754461646080017
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5089761018753052
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5077890157699585
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5166069865226746
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.53360515832901
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4275280237197876
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5624259114265442
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.5188097357749939
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.49255743622779846
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6358538866043091
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.401769757270813
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4292982518672943
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5774568319320679
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36958232522010803
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5268839597702026
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47157996892929077
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.547389030456543
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.4995117783546448
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5273687839508057
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48196619749069214
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5807770490646362
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.45662835240364075
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46136319637298584
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5571731925010681
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5308389663696289
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5049819350242615
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4067576229572296
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3853807747364044
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5215384364128113
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6307170987129211
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4778553247451782
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46201273798942566
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43653470277786255
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.45451170206069946
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.595805287361145
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5619323253631592
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5851477384567261
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5340575575828552
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.4947052299976349
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.5048887133598328
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.49582186341285706
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5021205544471741
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5052258372306824
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4548054039478302
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5867739915847778
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6322382688522339
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.522379457950592
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.3957264721393585
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.451244980096817
Calibrated prediction for TSM: 0.41800421476364136

Simulating Trading Days:  55%|█████▌    | 55/100 [05:21<00:52,  1.17s/it]

Raw prediction for UL: 0.46492406725883484
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4564882516860962
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.39767205715179443
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48785310983657837
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.049733489751815796
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5732258558273315
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.539682924747467
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5040538907051086
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4600241780281067
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4891468286514282
Calibrated prediction for XOM: 0.4654105305671692
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.511
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.899, kelly=0.155) with $3990.90
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.945, kelly=0.299) with $7686.88
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.471
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.030, kelly=0.104) with $2678.50
[PORT] Sector Financial: 10 candidates, avg score=0.503
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4454.65
[PORT] Sector Healthcare: 10 candidates, avg score=0.437
[PORT] Sector Healthcare: selecting ABBV (p=0.506, b=0.984, kelly=0.004) with $114.87
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.005, kelly=0.145) with $3716.35
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19139.41
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.965, kelly=0.298) with $7661.17
[PORT] Sector Utilities: 10 candidates, avg score=0.531
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.900, kelly=0.186) with $4775.28
Raw prediction for AAPL: 0.4964676797389984
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5156130194664001
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.46945512294769287
Calibrated prediction for ABBV: 0.5061728358268738
Raw prediction for AEP: 0.609235942363739
Calibrated prediction for AEP: 0.6195328831672668
Raw prediction for AGFS: 0.4241271913051605
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5066472887992859
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8098739385604858
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4613010883331299
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5811241865158081
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47158411145210266
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5258979201316833
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5387952923774719
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4890469014644623
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4954164922237396
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.48969918489456177
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48575612902641296
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4506342113018036
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5156404972076416
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46932074427604675
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.43074867129325867
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.49242016673088074
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.6283804774284363
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5277345180511475
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.43444183468818665
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4691074788570404
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4958367645740509
Calibrated prediction for CVX: 0.5
Raw prediction for D: 0.5125645995140076
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5140321850776672
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4977709949016571
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5179162621498108
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5076572895050049
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5165541172027588
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5334620475769043
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.42916804552078247
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5719767212867737
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5270927548408508
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.49833276867866516
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6349285840988159
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.3965778350830078
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4296438992023468
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5867087244987488
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3648437261581421
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5266315340995789
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47161635756492615
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5175215601921082
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.491547554731369
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5272819995880127
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4821946918964386
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5837896466255188
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4584521949291229
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4609295427799225
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5550248622894287
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.527266263961792
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5048068761825562
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4036450982093811
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3648335039615631
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5210811495780945
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6343932151794434
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4779694676399231
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4621768593788147
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43664854764938354
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.45496636629104614
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5962358713150024
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5637841820716858
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5830621719360352
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5317842364311218
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5022016167640686
Calibrated prediction for REX: 0.42500001192092896
Raw prediction for SLB: 0.5108887553215027
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4978051483631134
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.502386748790741
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5054632425308228
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.452830046415329
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5799890160560608
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6373865008354187
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.507162868976593
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.38946518301963806
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4948013126850128
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46440330147743225
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4575280249118805
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.3967660069465637
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4883563220500946
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.07167985290288925
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5734862685203552
Calibrated prediction for V: 0.5811987519264221

Simulating Trading Days:  56%|█████▌    | 56/100 [05:22<00:51,  1.17s/it]

Raw prediction for VZ: 0.5462419986724854
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.503576397895813
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46538597345352173
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4917796552181244
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.514
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.899, kelly=0.155) with $3973.68
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.944, kelly=0.299) with $7649.46
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.471
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.030, kelly=0.104) with $2664.51
[PORT] Sector Financial: 10 candidates, avg score=0.503
[PORT] Sector Financial: selecting V (p=0.581, b=1.028, kelly=0.174) with $4448.12
[PORT] Sector Healthcare: 10 candidates, avg score=0.437
[PORT] Sector Healthcare: selecting ABBV (p=0.506, b=0.983, kelly=0.004) with $102.42
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.004, kelly=0.144) with $3690.69
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19059.34
[PORT] Sector Technology: 10 candidates, avg score=0.561
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.966, kelly=0.298) with $7642.38
[PORT] Sector Utilities: 10 candidates, avg score=0.531
[PORT] Sector Utilities: selecting AEP (p=0.620, b=0.900, kelly=0.197) with $5037.06
Raw prediction for AAPL: 0.4965416193008423
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5132505297660828
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.44955605268478394
Calibrated prediction for ABBV: 0.5061728358268738
Raw prediction for AEP: 0.6123954653739929
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.42362624406814575
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5068637132644653
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7904824018478394
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4625503718852997
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5799060463905334
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4724617898464203
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5256693363189697
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5439263582229614
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.48883146047592163
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4914565086364746
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4897620975971222
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4857833683490753
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4458499848842621
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5156441330909729
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46947556734085083
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.43479031324386597
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.49654433131217957
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.6066473722457886
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5349348187446594
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4342109262943268
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47017255425453186
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49685603380203247
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5122330188751221
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.514957845211029
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4982735812664032
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5239931344985962
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5075340270996094
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5164154767990112
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5335158109664917
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.43236690759658813
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5796633362770081
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5319499373435974
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4998636543750763
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6345986723899841
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.39494916796684265
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4321991205215454
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.5961552858352661
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3602037727832794
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5263504385948181
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47146347165107727
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5021904110908508
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.47522208094596863
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5270799994468689
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48600804805755615
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5866809487342834
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.46275684237480164
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46085721254348755
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5531932711601257
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5262181162834167
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5048028826713562
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.3989590108394623
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.346460223197937
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5204035639762878
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6312238574028015
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4780387580394745
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46221739053726196
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4367518424987793
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4561881124973297
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5948607921600342
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5651370882987976
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5705928206443787
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5286251306533813
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.512520968914032
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5175162553787231
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.49756714701652527
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5026266574859619
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5057792067527771
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4493958353996277
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5634480118751526
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6368565559387207
Calibrated prediction for T: 0.6420084834098816

Simulating Trading Days:  57%|█████▋    | 57/100 [05:23<00:50,  1.16s/it]

Raw prediction for TM: 0.4874664843082428
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.38266074657440186
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5049659609794617
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4629228711128235
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4482394754886627
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.3935292959213257
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4887750744819641
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.08864281326532364
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5718336701393127
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5499826669692993
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5033999681472778
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46746447682380676
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4944019615650177
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.515
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.899, kelly=0.155) with $3966.88
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.945, kelly=0.299) with $7647.79
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.471
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.027, kelly=0.103) with $2629.93
[PORT] Sector Financial: 10 candidates, avg score=0.503
[PORT] Sector Financial: selecting V (p=0.581, b=1.025, kelly=0.173) with $4415.75
[PORT] Sector Healthcare: 10 candidates, avg score=0.437
[PORT] Sector Healthcare: selecting ABBV (p=0.506, b=0.985, kelly=0.005) with $119.76
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.001, kelly=0.143) with $3661.37
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.054, kelly=0.744) with $19044.55
[PORT] Sector Technology: 10 candidates, avg score=0.561
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.964, kelly=0.298) with $7616.31
[PORT] Sector Utilities: 10 candidates, avg score=0.531
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.900, kelly=0.206) with $5280.91
Raw prediction for AAPL: 0.4968646764755249
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5120663642883301
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.41639354825019836
Calibrated prediction for ABBV: 0.30000001192092896
Raw prediction for AEP: 0.6165823936462402
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.4233214855194092
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.507205605506897
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7825579643249512
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4662216007709503
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5807842016220093
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4724551737308502
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5217640399932861
Calibrated prediction for BBL: 0.5652173757553101
Raw prediction for BCH: 0.5539971590042114
Calibrated prediction for BCH: 0.5745094418525696
Raw prediction for BHP: 0.48852241039276123
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4892489016056061
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.490325927734375
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4860304296016693
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.45420220494270325
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5158758163452148
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46951228380203247
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4428134262561798
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5139360427856445
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6088954210281372
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5282303094863892
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4331720471382141
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4726008176803589
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4976637363433838
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5118632912635803
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5163110494613647
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4987961947917938
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5251783132553101
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5080769062042236
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5165055394172668
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5333129167556763
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.43279027938842773
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5929675102233887
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5330098271369934
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5046123266220093
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6319056153297424
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.3965769112110138
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4360765814781189
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6101771593093872
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.35069817304611206
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5262773036956787
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47167065739631653
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.49579644203186035
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.4995289146900177
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5271122455596924
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.49266546964645386
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5920443534851074
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4735080599784851
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4611436128616333
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5553282499313354
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5293387174606323
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5054628252983093
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4037303626537323
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.33236438035964966
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5197004675865173
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.638977587223053
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47833824157714844
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46260493993759155
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4371897578239441
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4559061825275421
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6002607345581055
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5665132999420166
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5565952062606812
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5181574821472168
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5218702554702759
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5232810974121094
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.49739131331443787
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5029599666595459
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5058848261833191
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.44546186923980713
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5475279688835144
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6336307525634766
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4862779676914215
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.3856014907360077
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5214214324951172
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4616575241088867
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4450390040874481
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.3974860608577728
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4893741011619568
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.11353946477174759
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5725301504135132
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5567483305931091
Calibrated prediction for VZ: 0.6161534786224365

Simulating Trading Days:  58%|█████▊    | 58/100 [05:24<00:49,  1.17s/it]

Raw prediction for WFC: 0.5036929249763489
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4691029489040375
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4987795352935791
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.506
[PORT] Sector Basic Matierials: selecting BBL (p=0.565, b=0.964, kelly=0.114) with $2912.36
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.944, kelly=0.299) with $7618.57
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.471
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.025, kelly=0.102) with $2607.11
[PORT] Sector Financial: 10 candidates, avg score=0.509
[PORT] Sector Financial: selecting V (p=0.581, b=1.025, kelly=0.173) with $4408.91
[PORT] Sector Healthcare: 10 candidates, avg score=0.417
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.003, kelly=0.006) with $161.48
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.463
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.000, kelly=0.142) with $3631.93
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $18989.32
[PORT] Sector Technology: 10 candidates, avg score=0.562
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.963, kelly=0.297) with $7584.94
[PORT] Sector Utilities: 10 candidates, avg score=0.533
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.902, kelly=0.207) with $5287.37
Raw prediction for AAPL: 0.49709492921829224
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.511830747127533
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3690831661224365
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.618663489818573
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.4234071373939514
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5076217651367188
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7761352062225342
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.47034454345703125
Calibrated prediction for BA: 0.5
Raw prediction for BABA: 0.5819053053855896
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4708296060562134
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.5104393362998962
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.5531657934188843
Calibrated prediction for BCH: 0.5714285969734192
Raw prediction for BHP: 0.4881286919116974
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4891963601112366
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4901464879512787
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4860519766807556
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.459626168012619
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5164110660552979
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4695832133293152
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.45759260654449463
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5223177671432495
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.608636736869812
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5196716785430908
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.43005993962287903
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.476080983877182
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4986400008201599
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5114812254905701
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5168155431747437
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4991653263568878
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5281224250793457
Calibrated prediction for DUK: 0.5382512211799622
Raw prediction for EXC: 0.5082798004150391
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5165113806724548
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5331189036369324
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4336206316947937
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6077145934104919
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5307326316833496
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5047916769981384
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6287398934364319
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.38585907220840454
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4401061534881592
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.625031054019928
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.33956825733184814
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5254912972450256
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4717055559158325
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4889649748802185
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.4988046884536743
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.527305543422699
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.49871566891670227
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5957688093185425
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.4819357395172119
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46165910363197327
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5584271550178528
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5324322581291199
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5064296126365662
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4130832850933075
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.32406848669052124
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5190081000328064
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6406666040420532
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4785180985927582
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46308591961860657
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43736451864242554
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4564947187900543
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6011382937431335
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5676915645599365
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5373478531837463
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.49910253286361694
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.5304331183433533
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5247817635536194
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4968971610069275
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5031876564025879
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5058173537254333
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4376174211502075
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5341324806213379
Calibrated prediction for SRE: 0.5484079718589783
Raw prediction for T: 0.6282981038093567
Calibrated prediction for T: 0.6420084834098816

Simulating Trading Days:  59%|█████▉    | 59/100 [05:26<00:47,  1.17s/it]

Raw prediction for TM: 0.4638357162475586
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.39940518140792847
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.52178955078125
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.46008971333503723
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.43595701456069946
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.4023401141166687
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48997819423675537
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.12658865749835968
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5742400884628296
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5603472590446472
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5035862326622009
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4708625376224518
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5017306208610535
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.504
[PORT] Sector Basic Matierials: selecting BBL (p=0.556, b=0.964, kelly=0.095) with $2421.64
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.942, kelly=0.298) with $7630.71
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.471
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.026, kelly=0.103) with $2628.27
[PORT] Sector Financial: 10 candidates, avg score=0.509
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4440.50
[PORT] Sector Healthcare: 10 candidates, avg score=0.415
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.005, kelly=0.007) with $185.95
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.000, kelly=0.142) with $3650.97
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.054, kelly=0.744) with $19067.10
[PORT] Sector Technology: 10 candidates, avg score=0.562
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.964, kelly=0.297) with $7621.33
[PORT] Sector Utilities: 10 candidates, avg score=0.532
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.903, kelly=0.207) with $5316.33
Raw prediction for AAPL: 0.49716705083847046
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5127501487731934
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.3266604244709015
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.6180073022842407
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.42361071705818176
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5081502795219421
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7803090810775757
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.47436976432800293
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5842875242233276
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4684964418411255
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4943305253982544
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.5513998866081238
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4878864884376526
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4879508912563324
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49008646607398987
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4857233762741089
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.46655216813087463
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5169711112976074
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46962979435920715
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4812811315059662
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.522533118724823
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6285011768341064
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5145126581192017
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4257831275463104
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4805460572242737
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49957454204559326
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5110757946968079
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5168830752372742
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49940598011016846
Calibrated prediction for DIS: 0.5126088261604309
Raw prediction for DUK: 0.5324482321739197
Calibrated prediction for DUK: 0.5384615659713745
Raw prediction for EXC: 0.5078226923942566
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5167937874794006
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5331310629844666
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.43332114815711975
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6262646913528442
Calibrated prediction for GOOG: 0.6624549031257629
Raw prediction for HD: 0.526574432849884
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5040398240089417
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6253501176834106
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.3737547993659973
Calibrated prediction for HSBC: 0.3662830889225006
Raw prediction for IEP: 0.4456632137298584
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6417774558067322
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.32687485218048096
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5241931080818176
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47182294726371765
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.48949986696243286
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.5071077942848206
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5278569459915161
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5066054463386536
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5995132923126221
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.48704567551612854
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46218499541282654
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5629974007606506
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5339634418487549
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5076143145561218
Calibrated prediction for NGG: 0.5134181380271912
Raw prediction for NVS: 0.4230896532535553
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3208458721637726
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5184627771377563
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6455276012420654
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47862884402275085
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4633678197860718
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43753737211227417
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45779359340667725
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5993252396583557
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5705532431602478
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5211197733879089
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.48013150691986084
Calibrated prediction for RDS-B: 0.4698277413845062
Raw prediction for REX: 0.538425862789154
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5189462900161743
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4953711926937103
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5032652020454407
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5055480003356934
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.431548535823822
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5235798358917236
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6193154454231262
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4341256320476532
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4102800786495209
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5159575939178467
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45967772603034973
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.430083304643631
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4047931134700775
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4905560314655304
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.13312096893787384
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5747265815734863
Calibrated prediction for V: 0.5811987519264221

Simulating Trading Days:  60%|██████    | 60/100 [05:27<00:47,  1.18s/it]

Raw prediction for VZ: 0.5597615838050842
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5035423636436462
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46953284740448
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5003231763839722
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.500
[PORT] Sector Basic Matierials: selecting BBL (p=0.550, b=0.962, kelly=0.082) with $2105.67
[PORT] Sector Conglomerates: 7 candidates, avg score=0.462
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.944, kelly=0.298) with $7626.68
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.470
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.028, kelly=0.103) with $2643.77
[PORT] Sector Financial: 10 candidates, avg score=0.501
[PORT] Sector Financial: selecting V (p=0.581, b=1.026, kelly=0.173) with $4423.09
[PORT] Sector Healthcare: 10 candidates, avg score=0.421
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.003, kelly=0.006) with $156.79
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.470
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.003, kelly=0.144) with $3668.35
[PORT] Sector Services: 10 candidates, avg score=0.571
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19019.10
[PORT] Sector Technology: 10 candidates, avg score=0.566
[PORT] Sector Technology: selecting GOOG (p=0.662, b=1.048, kelly=0.340) with $8696.98
[PORT] Sector Utilities: 10 candidates, avg score=0.532
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.904, kelly=0.208) with $5322.01
Raw prediction for AAPL: 0.49711641669273376
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.514064371585846
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.28458428382873535
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.6199925541877747
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.4239939749240875
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5084598064422607
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7661054730415344
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.477029949426651
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5816603899002075
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4664430022239685
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4866580665111542
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.5416852831840515
Calibrated prediction for BCH: 0.517241358757019
Raw prediction for BHP: 0.4879755973815918
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.49428001046180725
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4902132749557495
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4859100878238678
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4722367525100708
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.517418384552002
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4697517156600952
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.499550998210907
Calibrated prediction for CELG: 0.5454545617103577
Raw prediction for CHL: 0.5289044380187988
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6288588643074036
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5231838226318359
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.43314990401268005
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.48672568798065186
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4997918903827667
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5107094645500183
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5170961022377014
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49953028559684753
Calibrated prediction for DIS: 0.5126088261604309
Raw prediction for DUK: 0.5368174314498901
Calibrated prediction for DUK: 0.6000000238418579
Raw prediction for EXC: 0.5076956748962402
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5171481966972351
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5332789421081543
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.43294355273246765
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6413229703903198
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.5212815999984741
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5030269026756287
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.622589111328125
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.3674502372741699
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4520564079284668
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6549270153045654
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3200850188732147
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5229398012161255
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4720056354999542
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5041100978851318
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.525652289390564
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5283809900283813
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5141838192939758
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.6016522645950317
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49185317754745483
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4628223180770874
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5648853778839111
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5356392860412598
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5093095898628235
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4308933615684509
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.32062068581581116
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5182181596755981
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6441928148269653
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47872641682624817
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4636354446411133
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4377444088459015
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4606550633907318
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.596564769744873
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5745261907577515
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5103381872177124
Calibrated prediction for PTR: 0.5
Raw prediction for RDS-B: 0.4810640215873718
Calibrated prediction for RDS-B: 0.4844820499420166
Raw prediction for REX: 0.5439439415931702
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5097678899765015
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.49482810497283936
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5031823515892029
Calibrated prediction for SNY: 0.5023937821388245

Simulating Trading Days:  61%|██████    | 61/100 [05:28<00:46,  1.18s/it]

Raw prediction for SO: 0.5052844882011414
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4255973994731903
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5187240242958069
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6114053726196289
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4109169542789459
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.43144044280052185
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5063162446022034
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4605422616004944
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.43271225690841675
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.39862173795700073
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4907778203487396
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.11994058638811111
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5750423669815063
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.557239294052124
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5035755038261414
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4683978259563446
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5022522807121277
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.497
[PORT] Sector Basic Matierials: selecting BBL (p=0.550, b=0.962, kelly=0.082) with $2114.68
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.944, kelly=0.299) with $7662.36
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.463
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.030, kelly=0.104) with $2676.41
[PORT] Sector Financial: 10 candidates, avg score=0.500
[PORT] Sector Financial: selecting V (p=0.581, b=1.026, kelly=0.173) with $4443.10
[PORT] Sector Healthcare: 10 candidates, avg score=0.432
[PORT] Sector Healthcare: selecting CELG (p=0.545, b=1.027, kelly=0.103) with $2642.89
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.002, kelly=0.143) with $3676.42
[PORT] Sector Services: 10 candidates, avg score=0.571
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.057, kelly=0.744) with $19097.54
[PORT] Sector Technology: 10 candidates, avg score=0.568
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.049, kelly=0.386) with $9905.14
[PORT] Sector Utilities: 10 candidates, avg score=0.539
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.903, kelly=0.208) with $5328.20
Raw prediction for AAPL: 0.497134268283844
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5163987278938293
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2592618465423584
Calibrated prediction for ABBV: 0.2857142984867096
Raw prediction for AEP: 0.6205396056175232
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.42475834488868713
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5087810754776001
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7638663649559021
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4790375232696533
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5806182026863098
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4646032154560089
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.47934025526046753
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5254881381988525
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48811036348342896
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4991018772125244
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4902145266532898
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48606404662132263
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4752993583679199
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5177154541015625
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4697403311729431
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.516823410987854
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5418427586555481
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.6291906833648682
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5230712294578552
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.44926953315734863
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4932117760181427
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49981915950775146
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5103408694267273
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5184332132339478
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49944666028022766
Calibrated prediction for DIS: 0.5126088261604309
Raw prediction for DUK: 0.5433171987533569
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5079314708709717
Calibrated prediction for EXC: 0.5029040575027466
Raw prediction for FB: 0.5172742009162903
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5332639813423157
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4338266849517822
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6555256247520447
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.5156611800193787
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5055944323539734
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6207191944122314
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.3640383183956146
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4633248746395111
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.670123815536499
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.31556618213653564
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5217520594596863
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47215765714645386
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5319173336029053
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5453438758850098
Calibrated prediction for MA: 0.6550819873809814
Raw prediction for MCD: 0.5289705991744995
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.518690288066864
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.6043292284011841
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49464643001556396
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46365246176719666
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5667359828948975
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5369635820388794
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5111888647079468
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.44367510080337524
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.3253607749938965
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5180507898330688
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6417064070701599
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4788013994693756
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4642525017261505
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4379541873931885
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46173572540283203
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5878366827964783
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.5783451795578003
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.5015798211097717
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.48422113060951233
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.5488268733024597
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5013541579246521
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.49517932534217834
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5031817555427551
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5050784349441528
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.4188810884952545
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5156828761100769
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6067899465560913
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.39273765683174133
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.44933924078941345
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5036768913269043
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4613751173019409
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.43870341777801514
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.4001404345035553
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49107155203819275
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.1116395965218544
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5767337679862976
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5623188018798828
Calibrated prediction for VZ: 0.6161534786224365

Simulating Trading Days:  62%|██████▏   | 62/100 [05:29<00:44,  1.18s/it]

Raw prediction for WFC: 0.5033450722694397
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4684479534626007
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5056518316268921
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.496
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.990, kelly=0.191) with $4911.65
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.943, kelly=0.298) with $7686.95
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.465
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.032, kelly=0.105) with $2701.77
[PORT] Sector Financial: 10 candidates, avg score=0.503
[PORT] Sector Financial: selecting MA (p=0.655, b=0.967, kelly=0.298) with $7687.04
[PORT] Sector Healthcare: 10 candidates, avg score=0.446
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.026, kelly=0.189) with $4876.63
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.002, kelly=0.143) with $3695.22
[PORT] Sector Services: 10 candidates, avg score=0.571
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.057, kelly=0.745) with $19182.41
[PORT] Sector Technology: 10 candidates, avg score=0.568
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.050, kelly=0.386) with $9954.21
[PORT] Sector Utilities: 10 candidates, avg score=0.540
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.902, kelly=0.207) with $5333.96
Raw prediction for AAPL: 0.49705126881599426
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5179206132888794
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.23544426262378693
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6176323890686035
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.42541250586509705
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.50934237241745
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7496932148933411
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.47901028394699097
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5769014358520508
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.462748259305954
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.46944528818130493
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5025342702865601
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4880400598049164
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5030547380447388
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4900727868080139
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48618292808532715
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.47113797068595886
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5178090333938599
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4697814881801605
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5380531549453735
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5494420528411865
Calibrated prediction for CHL: 0.5602449178695679
Raw prediction for CHTR: 0.6252287030220032
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5293993353843689
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4583066403865814
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4995079040527344
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4997541308403015
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5100347995758057
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5195662975311279
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49895042181015015
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5511223673820496
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5079770684242249
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5170686841011047
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5332034826278687
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4350666105747223
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6579036116600037
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.5120936036109924
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5033499002456665
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6185585856437683
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.3656935691833496
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4757560193538666
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6826242208480835
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3146512508392334
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5207661986351013
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47227174043655396
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5493010878562927
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5369040966033936
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5291421413421631
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5217318534851074
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.6043280959129333
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49560195207595825
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.464415043592453
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5642199516296387
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5363474488258362
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5127800107002258
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.45149439573287964
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.33056920766830444
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.517848014831543
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6360545754432678
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47875604033470154
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4647001028060913
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43807464838027954
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4612828195095062
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5793735980987549
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.580664873123169
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4893573224544525
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.48608219623565674
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.5512322187423706
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4983949363231659
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.49646422266960144
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5030263066291809
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5049423575401306
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.41192927956581116
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5139145255088806
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6084446310997009
Calibrated prediction for T: 0.6420084834098816

Simulating Trading Days:  63%|██████▎   | 63/100 [05:30<00:43,  1.17s/it]

Raw prediction for TM: 0.36885952949523926
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.4744962751865387
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4853319227695465
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4623849391937256
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.44392117857933044
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.4018525779247284
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49124857783317566
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.09652044624090195
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5763521194458008
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5625937581062317
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5028687119483948
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.47015631198883057
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5078604817390442
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.501
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.988, kelly=0.190) with $4893.38
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.945, kelly=0.299) with $7703.66
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.460
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.101, kelly=0.047) with $1199.79
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4463.83
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.027, kelly=0.190) with $4891.38
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.001, kelly=0.143) with $3684.72
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.058, kelly=0.745) with $19177.16
[PORT] Sector Technology: 10 candidates, avg score=0.569
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.050, kelly=0.386) with $9951.84
[PORT] Sector Utilities: 10 candidates, avg score=0.541
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.903, kelly=0.208) with $5348.04
Raw prediction for AAPL: 0.4970276355743408
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5194322466850281
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.21842625737190247
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6140098571777344
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.42592668533325195
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5100681185722351
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7436855435371399
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.477874219417572
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5699255466461182
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4615961015224457
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4602530896663666
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.48094311356544495
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48791271448135376
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.507786214351654
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4901305139064789
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48618727922439575
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.46137237548828125
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5177274346351624
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4697304666042328
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5558751225471497
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5552187561988831
Calibrated prediction for CHL: 0.6115630865097046
Raw prediction for CHTR: 0.6163153648376465
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5327691435813904
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4552016854286194
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.503136396408081
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49976158142089844
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5098304748535156
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.520789623260498
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49790310859680176
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5581875443458557
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5081167817115784
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5167816877365112
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5331228971481323
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4351988732814789
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6511974930763245
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.5128410458564758
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5008839964866638
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6163431406021118
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.37500274181365967
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.48307615518569946
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6909487247467041
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.31294041872024536
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5204811096191406
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4724092483520508
Calibrated prediction for KO: 0.4768126904964447
Raw prediction for LMT: 0.5553411245346069
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5367264151573181
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5289490222930908
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5239113569259644
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.6038564443588257
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49796777963638306
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4652559757232666
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.557509183883667
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.534428060054779
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.514290452003479
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.45799365639686584
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.3365252912044525
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5176536440849304
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6326422095298767
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4788152277469635
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46511930227279663
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4383408725261688
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4596969187259674
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5742735266685486
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5823779702186584
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.47794032096862793
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.48415639996528625
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.5508840084075928
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4953438341617584
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4988037347793579
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5029148459434509
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5048331022262573
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.40436848998069763
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5126549601554871
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6179147362709045
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.36074501276016235
Calibrated prediction for TM: 0.3076923191547394
Raw prediction for TOT: 0.48742780089378357
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.46430301666259766
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.46322497725486755
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4498575031757355
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.4169122576713562
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49135729670524597
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.08119091391563416
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5746037364006042
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.564669132232666
Calibrated prediction for VZ: 0.6161534786224365

Simulating Trading Days:  64%|██████▍   | 64/100 [05:31<00:43,  1.19s/it]

Raw prediction for WFC: 0.5022983551025391
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4698534905910492
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5080486536026001
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.501
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.987, kelly=0.190) with $4902.24
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.946, kelly=0.299) with $7742.02
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.099, kelly=0.046) with $1185.69
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.581, b=1.025, kelly=0.173) with $4465.76
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.026, kelly=0.189) with $4890.30
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.003, kelly=0.144) with $3710.73
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.060, kelly=0.745) with $19256.39
[PORT] Sector Technology: 10 candidates, avg score=0.561
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.048, kelly=0.386) with $9974.30
[PORT] Sector Utilities: 10 candidates, avg score=0.541
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.905, kelly=0.209) with $5394.42
Raw prediction for AAPL: 0.49715378880500793
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5209797024726868
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.2031545341014862
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6107043027877808
Calibrated prediction for AEP: 0.6222621202468872
Raw prediction for AGFS: 0.42614227533340454
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5107030272483826
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7491921186447144
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4757750630378723
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.563585102558136
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4607699513435364
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4533242881298065
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.4633721113204956
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4877862334251404
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.512778639793396
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4901621639728546
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4862789809703827
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.45226481556892395
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5175056457519531
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4696331024169922
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.571692943572998
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5565511584281921
Calibrated prediction for CHL: 0.6233996748924255
Raw prediction for CHTR: 0.6058033108711243
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5217514038085938
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4462288022041321
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5040532946586609
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49989619851112366
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5096903443336487
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5216212272644043
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49696964025497437
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.56371009349823
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5082525014877319
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5163312554359436
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5330080986022949
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.433402419090271
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6419666409492493
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.5155079364776611
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4977574050426483
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.61454176902771
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.3874010741710663
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.48678135871887207
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.697603702545166
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3103307783603668
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5206320285797119
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47251096367836
Calibrated prediction for KO: 0.4768126904964447
Raw prediction for LMT: 0.5575513243675232
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5209824442863464
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5285921096801758
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5258206129074097
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.6032850742340088
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5010546445846558
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4660731256008148
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5460934042930603
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5327205657958984
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5156815052032471
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.46224960684776306
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.3418922424316406
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5175121426582336
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6278985142707825
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4788539707660675
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46546342968940735
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4385710060596466
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45909562706947327
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5714541077613831
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5830140709877014
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4671730101108551
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.47921133041381836
Calibrated prediction for RDS-B: 0.4553673267364502
Raw prediction for REX: 0.5489618182182312
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4925188720226288
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.499828040599823
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5028210282325745
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5047774910926819
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3927198648452759
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5078088641166687
Calibrated prediction for SRE: 0.5277777910232544

Simulating Trading Days:  65%|██████▌   | 65/100 [05:33<00:41,  1.19s/it]

Raw prediction for T: 0.6295626163482666
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.3509844243526459
Calibrated prediction for TM: 0.3076923191547394
Raw prediction for TOT: 0.48623231053352356
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.443984717130661
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4631456434726715
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4508484899997711
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.43662023544311523
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49132904410362244
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.06983815878629684
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.573115348815918
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5681087374687195
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5018067955970764
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.47483909130096436
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5071654915809631
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.496
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.985, kelly=0.189) with $4874.60
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.945, kelly=0.299) with $7719.08
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.097, kelly=0.045) with $1161.57
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.581, b=1.025, kelly=0.173) with $4459.21
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.025, kelly=0.189) with $4879.04
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.003, kelly=0.144) with $3711.30
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.060, kelly=0.745) with $19240.54
[PORT] Sector Technology: 10 candidates, avg score=0.562
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.049, kelly=0.386) with $9974.53
[PORT] Sector Utilities: 10 candidates, avg score=0.541
[PORT] Sector Utilities: selecting AEP (p=0.622, b=0.904, kelly=0.204) with $5276.11
Raw prediction for AAPL: 0.4971781075000763
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5213767886161804
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.18790607154369354
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6084569096565247
Calibrated prediction for AEP: 0.6180849075317383
Raw prediction for AGFS: 0.4255068004131317
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5111681222915649
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7462310194969177
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4729330837726593
Calibrated prediction for BA: 0.5262488722801208
Raw prediction for BABA: 0.5589141845703125
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46092018485069275
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.44784700870513916
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.45235008001327515
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4876513183116913
Calibrated prediction for BHP: 0.492535263299942
Raw prediction for BP: 0.5098885297775269
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4902489185333252
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48620954155921936
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.44126901030540466
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5171912312507629
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4695435166358948
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5850000381469727
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5483235716819763
Calibrated prediction for CHL: 0.5503087043762207
Raw prediction for CHTR: 0.5900053977966309
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5034669041633606
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.44659721851348877
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5032720565795898
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.5001519918441772
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5096973776817322
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5218077898025513
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4962150752544403
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5696049332618713
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5082564353942871
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5158712267875671
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5328354239463806
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.42967575788497925
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6273787021636963
Calibrated prediction for GOOG: 0.6723519563674927
Raw prediction for HD: 0.5190233588218689
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4922323524951935
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6123373508453369
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.3994966447353363
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4865506589412689
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7006976008415222
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.31217604875564575
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5214455127716064
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47238463163375854
Calibrated prediction for KO: 0.4768126904964447
Raw prediction for LMT: 0.5452132821083069
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5017353296279907
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5281283259391785
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5267929434776306
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.6020408868789673
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5013003945350647
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46664392948150635
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5264974236488342
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5312924981117249
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5162087678909302
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4623270332813263
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.34141805768013
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5174223780632019
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6200372576713562
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47872060537338257
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46558505296707153
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43871206045150757
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45846033096313477
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5669575929641724
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.582469642162323
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4574989676475525
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.47294336557388306
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5468471646308899
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.48921462893486023
Calibrated prediction for SLB: 0.48267385363578796
Raw prediction for SNP: 0.4972468912601471
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5027002692222595
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5047459602355957
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.38246700167655945
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4942019581794739
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.635326087474823
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.33267006278038025
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.47834134101867676
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4226105511188507
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.46185994148254395
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4439082145690918
Calibrated prediction for UN: 0.4444444477558136
Raw prediction for UNH: 0.4518777132034302
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4912120997905731
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.05895368009805679
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5708187818527222
Calibrated prediction for V: 0.5811987519264221

Simulating Trading Days:  66%|██████▌   | 66/100 [05:34<00:40,  1.18s/it]

Raw prediction for VZ: 0.572089672088623
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5013898015022278
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.479560911655426
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5052576065063477
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.488
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.983, kelly=0.188) with $4862.83
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.946, kelly=0.299) with $7745.26
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.457
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.098, kelly=0.045) with $1171.49
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4484.28
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.024, kelly=0.188) with $4872.94
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.473
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.005, kelly=0.145) with $3740.50
[PORT] Sector Services: 10 candidates, avg score=0.574
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.062, kelly=0.745) with $19269.34
[PORT] Sector Technology: 10 candidates, avg score=0.552
[PORT] Sector Technology: selecting GOOG (p=0.672, b=1.048, kelly=0.360) with $9300.39
[PORT] Sector Utilities: 10 candidates, avg score=0.540
[PORT] Sector Utilities: selecting AEP (p=0.618, b=0.903, kelly=0.195) with $5050.43
Raw prediction for AAPL: 0.4974032938480377
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5201873183250427
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.17421221733093262
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6109469532966614
Calibrated prediction for AEP: 0.6227131485939026
Raw prediction for AGFS: 0.42418697476387024
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5111982822418213
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7477691769599915
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46994975209236145
Calibrated prediction for BA: 0.5
Raw prediction for BABA: 0.5558738708496094
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4615911543369293
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.44283562898635864
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.43994227051734924
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48750627040863037
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5032100677490234
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4900968670845032
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48589882254600525
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4342862069606781
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5169697999954224
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46925967931747437
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5946050882339478
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5384442210197449
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5881087779998779
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.47875869274139404
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.44875529408454895
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5006735920906067
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.5006540417671204
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5097601413726807
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5215716361999512
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4957270622253418
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5744226574897766
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.508732259273529
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5157768726348877
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5326221585273743
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4245520234107971
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6094135046005249
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5244688391685486
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4863516688346863
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6108551621437073
Calibrated prediction for HRG: 0.6593891382217407
Raw prediction for HSBC: 0.4081747233867645
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4831521809101105
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7024112939834595
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.31525227427482605
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5222994685173035
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4722176194190979
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5289565920829773
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.4753757417201996
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5278858542442322
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.525454580783844
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.6011199951171875
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5031925439834595
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4670506417751312
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4989500641822815
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5311380624771118
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.515913724899292
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4605765640735626
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.341046005487442
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5175137519836426
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6168694496154785
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4785654842853546
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46567806601524353
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4389856159687042
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45820167660713196
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5630893707275391
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5819399952888489
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4453660845756531
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.46727216243743896
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5458077788352966
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.48330438137054443
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4914042055606842
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5027396082878113
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5046378374099731
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.37139275670051575
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.48038479685783386
Calibrated prediction for SRE: 0.5277777910232544

Simulating Trading Days:  67%|██████▋   | 67/100 [05:35<00:38,  1.18s/it]

Raw prediction for T: 0.6416099667549133
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.3282512128353119
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.4596197307109833
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4070502817630768
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.45989832282066345
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.4325507879257202
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.46554288268089294
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.490970253944397
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.052784211933612823
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5701408982276917
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5739017128944397
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5008600354194641
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.48155975341796875
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5032119154930115
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.477
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.983, kelly=0.188) with $4862.38
[PORT] Sector Conglomerates: 7 candidates, avg score=0.475
[PORT] Sector Conglomerates: selecting HRG (p=0.659, b=0.946, kelly=0.299) with $7751.63
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.098, kelly=0.045) with $1167.95
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4492.90
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.021, kelly=0.188) with $4856.89
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.471
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.004, kelly=0.144) with $3732.62
[PORT] Sector Services: 10 candidates, avg score=0.574
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.059, kelly=0.745) with $19287.83
[PORT] Sector Technology: 10 candidates, avg score=0.548
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.968, kelly=0.299) with $7741.43
[PORT] Sector Utilities: 10 candidates, avg score=0.541
[PORT] Sector Utilities: selecting AEP (p=0.623, b=0.905, kelly=0.206) with $5332.75
Raw prediction for AAPL: 0.4976075291633606
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5173306465148926
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.1630629301071167
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6157869696617126
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.4227253794670105
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5107974410057068
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7370497584342957
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4665924310684204
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5530223250389099
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4630301594734192
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.43809083104133606
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.43609943985939026
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48752331733703613
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5006734728813171
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4902743697166443
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48583945631980896
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.42904871702194214
Calibrated prediction for BUD: 0.38069671392440796
Raw prediction for C: 0.516579270362854
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4690147340297699
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5995659232139587
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5225204825401306
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5796408653259277
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.448186457157135
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4434061348438263
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4969601631164551
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.5009564757347107
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5097405910491943
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5201601982116699
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4954271912574768
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5722240805625916
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5087782740592957
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5154510140419006
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.532267153263092
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.42092499136924744
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5881586670875549
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5320749282836914
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47893795371055603
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6089229583740234
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4163769483566284
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4760964512825012
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7060918807983398
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3197470009326935
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5236730575561523
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47170716524124146
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.49993157386779785
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.4609483778476715
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5277242064476013
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5233475565910339
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5987650156021118
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5016316175460815
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4671199321746826
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4730447232723236
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5303708910942078
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5141895413398743
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.45591479539871216
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.3399171531200409
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5176088809967041
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6107450723648071
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47816720604896545
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4656551480293274
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43907156586647034
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4581853747367859
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5540741086006165
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5809305310249329
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4328327775001526
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.46824389696121216
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5456286072731018
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4760141670703888
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4857555627822876
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5027803778648376
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5045689344406128
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3679238259792328
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4462035894393921
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6452726721763611
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.31711822748184204
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.453181654214859
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.3857652246952057
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4567264914512634
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.41463956236839294
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4702797830104828
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4904628098011017
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.04993421956896782
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5699901580810547
Calibrated prediction for V: 0.5811987519264221

Simulating Trading Days:  68%|██████▊   | 68/100 [05:36<00:37,  1.18s/it]

Raw prediction for VZ: 0.5727965831756592
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5007243156433105
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4833327531814575
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5024529695510864
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.477
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.984, kelly=0.188) with $4888.19
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.946, kelly=0.167) with $4330.66
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.444
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.096, kelly=0.044) with $1151.90
[PORT] Sector Financial: 10 candidates, avg score=0.486
[PORT] Sector Financial: selecting V (p=0.581, b=1.030, kelly=0.174) with $4523.86
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.019, kelly=0.187) with $4844.85
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.006, kelly=0.145) with $3765.49
[PORT] Sector Services: 10 candidates, avg score=0.556
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.059, kelly=0.745) with $19316.55
[PORT] Sector Technology: 10 candidates, avg score=0.538
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.969, kelly=0.299) with $7763.60
[PORT] Sector Utilities: 10 candidates, avg score=0.541
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.905, kelly=0.208) with $5407.23
Raw prediction for AAPL: 0.49781838059425354
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5139356255531311
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.159475177526474
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6157308220863342
Calibrated prediction for AEP: 0.6240466833114624
Raw prediction for AGFS: 0.4207174479961395
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5098727941513062
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7147496938705444
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46328455209732056
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5576812624931335
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.46515175700187683
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.43475770950317383
Calibrated prediction for BBL: 0.42542508244514465
Raw prediction for BCH: 0.43222731351852417
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48748698830604553
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5079968571662903
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4901723563671112
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48590829968452454
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4300169050693512
Calibrated prediction for BUD: 0.38069671392440796
Raw prediction for C: 0.5163639187812805
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.468752384185791
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5996963977813721
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.5092416405677795
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5731491446495056
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4150724411010742
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.43244314193725586
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4924453794956207
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.5007359981536865
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5097351670265198
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5184261798858643
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4952918291091919
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5676514506340027
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5089638829231262
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5154165029525757
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5319483876228333
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.41965559124946594
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5691832304000854
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.538865864276886
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4752684533596039
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6061144471168518
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4213992655277252
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4601128399372101
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7091799974441528
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.32587623596191406
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5253903269767761
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47102469205856323
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.46395736932754517
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.44137558341026306
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5277763605117798
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5228480696678162
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5963220000267029
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5012306571006775
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4672935903072357
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4499499797821045
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5297374129295349
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.511849582195282
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.450916588306427
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.3399609625339508
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5176395773887634
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6041967868804932
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.4776608943939209
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46579962968826294
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4391389489173889
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45785725116729736
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5441344976425171
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5780929327011108
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4232234060764313
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.4668543040752411
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5463825464248657
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4670061767101288
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48019856214523315
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5029972791671753
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5043758153915405
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.36866384744644165
Calibrated prediction for SPLP: 0.30125677585601807

Simulating Trading Days:  69%|██████▉   | 69/100 [05:37<00:36,  1.18s/it]

Raw prediction for SRE: 0.4186748266220093
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6464223265647888
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.3095993399620056
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.44885942339897156
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.3859823942184448
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4532294273376465
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.39394742250442505
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4724208116531372
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48977434635162354
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.04977831989526749
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5707972645759583
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5694802403450012
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.5004470348358154
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4869708716869354
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5030854940414429
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.476
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.983, kelly=0.188) with $4874.30
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.945, kelly=0.167) with $4325.91
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.444
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.094, kelly=0.044) with $1134.71
[PORT] Sector Financial: 10 candidates, avg score=0.486
[PORT] Sector Financial: selecting V (p=0.581, b=1.029, kelly=0.174) with $4523.18
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.021, kelly=0.187) with $4865.69
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.463
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.008, kelly=0.146) with $3789.14
[PORT] Sector Services: 10 candidates, avg score=0.556
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.059, kelly=0.745) with $19330.41
[PORT] Sector Technology: 10 candidates, avg score=0.531
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.967, kelly=0.299) with $7751.77
[PORT] Sector Utilities: 10 candidates, avg score=0.531
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.906, kelly=0.209) with $5430.25
Raw prediction for AAPL: 0.49799251556396484
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5106207728385925
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.15856608748435974
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6114212870597839
Calibrated prediction for AEP: 0.6235947608947754
Raw prediction for AGFS: 0.4181971251964569
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5086888074874878
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6768705248832703
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.46043363213539124
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5629636645317078
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4680127501487732
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4327068030834198
Calibrated prediction for BBL: 0.42542508244514465
Raw prediction for BCH: 0.43240636587142944
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4874667227268219
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5200134515762329
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4901279807090759
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48607397079467773
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.43438950181007385
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5161150097846985
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46860119700431824
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.595515787601471
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.500867486000061
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5668174624443054
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.39633268117904663
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4307253062725067
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.48706695437431335
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.5002990365028381
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5099011063575745
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5170541405677795
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4952828586101532
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5524436831474304
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.508639395236969
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5154677033424377
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5316659212112427
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.42010298371315
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.550101637840271
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.547420859336853
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47456100583076477
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6036451458930969
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.42592939734458923
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4395051896572113
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7069364786148071
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.33614382147789
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5272598266601562
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4702547788619995
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.43975508213043213
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.43347713351249695
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5278854966163635
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.523339569568634
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5942249298095703
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5001805424690247
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46751752495765686
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4373994767665863
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.526106595993042
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5081498622894287
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.44420260190963745
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.3390490710735321
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5177871584892273
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6015728116035461
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.4770275056362152
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46581578254699707
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43900829553604126
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4568032920360565
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5343745350837708
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5725705623626709
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.4162161350250244
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.46369561553001404
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5467848181724548
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.46022137999534607
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4794314503669739
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.503226101398468
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5041476488113403
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3730149567127228
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.38565775752067566
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.650296151638031
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.3073016405105591
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.44798094034194946
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.39888253808021545
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.45019036531448364
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.37132325768470764
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.46993401646614075
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48910611867904663
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.05223005264997482
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.571682870388031
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5661525726318359
Calibrated prediction for VZ: 0.6161534786224365

Simulating Trading Days:  70%|███████   | 70/100 [05:39<00:35,  1.18s/it]

Raw prediction for WFC: 0.5001465082168579
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4913080334663391
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5033578872680664
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.476
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.982, kelly=0.188) with $4872.08
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.944, kelly=0.166) with $4317.28
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.093, kelly=0.043) with $1124.71
[PORT] Sector Financial: 10 candidates, avg score=0.486
[PORT] Sector Financial: selecting V (p=0.581, b=1.029, kelly=0.174) with $4520.72
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.020, kelly=0.187) with $4854.87
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.454
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.007, kelly=0.146) with $3781.24
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.041, kelly=0.300) with $7789.74
[PORT] Sector Technology: 10 candidates, avg score=0.529
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.965, kelly=0.298) with $7738.89
[PORT] Sector Utilities: 10 candidates, avg score=0.531
[PORT] Sector Utilities: selecting AEP (p=0.624, b=0.905, kelly=0.208) with $5398.94
Raw prediction for AAPL: 0.49815723299980164
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5076437592506409
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.1541939079761505
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.6035023331642151
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.415736585855484
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5073974132537842
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6443184018135071
Calibrated prediction for AMZN: 0.6296296119689941
Raw prediction for BA: 0.45765411853790283
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5704740881919861
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4707309901714325
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4308396279811859
Calibrated prediction for BBL: 0.42542508244514465
Raw prediction for BCH: 0.43114742636680603
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48748522996902466
Calibrated prediction for BHP: 0.4871614873409271
Raw prediction for BP: 0.5303004384040833
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4899612069129944
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4865288734436035
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.44235751032829285
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.515943706035614
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46858689188957214
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5862378478050232
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.4916383624076843
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5641198754310608
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3800433874130249
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4351517856121063
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4820641279220581
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4999690055847168
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5101218223571777
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5157868266105652
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4953788220882416
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5295236706733704
Calibrated prediction for DUK: 0.5384615659713745
Raw prediction for EXC: 0.5083098411560059
Calibrated prediction for EXC: 0.5151515007019043
Raw prediction for FB: 0.5155149698257446
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5315161943435669
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.42140865325927734
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5316802263259888
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.5574081540107727
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47307512164115906
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6021238565444946
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4306390881538391
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.4156845808029175
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7039757966995239
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.34540310502052307
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5291310548782349
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46939611434936523
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.41352900862693787
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.4258749485015869
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5281050801277161
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5256530046463013
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.590413510799408
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49968859553337097
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46767938137054443
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4319341480731964
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5209611058235168
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.504514753818512
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.434520959854126
Calibrated prediction for NVS: 0.42307692766189575
Raw prediction for ORCL: 0.33678972721099854
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5179252624511719
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5951629877090454
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.4763339161872864
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4656597375869751
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4387752115726471
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4554688632488251
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5241548418998718
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.564723014831543
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.40866196155548096
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.459844172000885
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5463345050811768
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4574459493160248
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48061856627464294
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5033423900604248
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5037544369697571
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.37623330950737
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.3583594858646393
Calibrated prediction for SRE: 0.43036380410194397

Simulating Trading Days:  71%|███████   | 71/100 [05:40<00:34,  1.17s/it]

Raw prediction for T: 0.6529775857925415
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.3162316679954529
Calibrated prediction for TM: 0.3021872341632843
Raw prediction for TOT: 0.44588834047317505
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.40965232253074646
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4476654529571533
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34859728813171387
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.46085718274116516
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48852139711380005
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.05012395977973938
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5717173218727112
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5618511438369751
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.4997166693210602
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.49663782119750977
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5037862062454224
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.476
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.981, kelly=0.187) with $4856.59
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.942, kelly=0.165) with $4294.06
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.095, kelly=0.044) with $1140.41
[PORT] Sector Financial: 10 candidates, avg score=0.486
[PORT] Sector Financial: selecting V (p=0.581, b=1.031, kelly=0.175) with $4543.60
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.019, kelly=0.187) with $4847.85
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.454
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.006, kelly=0.145) with $3763.40
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.040, kelly=0.299) with $7776.54
[PORT] Sector Technology: 10 candidates, avg score=0.529
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.964, kelly=0.298) with $7730.45
[PORT] Sector Utilities: 10 candidates, avg score=0.519
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.904, kelly=0.186) with $4833.44
Raw prediction for AAPL: 0.49826931953430176
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.507182776927948
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.14295904338359833
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5937132835388184
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.41288867592811584
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5062320828437805
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.622654139995575
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.45583295822143555
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5763195753097534
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4734773635864258
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4305151700973511
Calibrated prediction for BBL: 0.42542508244514465
Raw prediction for BCH: 0.4400976598262787
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.487697958946228
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5394762754440308
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4899713695049286
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48680511116981506
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.45102477073669434
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5157608985900879
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46852561831474304
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.571034848690033
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.4924412667751312
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5641238689422607
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3755320608615875
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44059398770332336
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.477676123380661
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4995192289352417
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5104022026062012
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5176923871040344
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49557411670684814
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5052435994148254
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.507234513759613
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5157410502433777
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5314394235610962
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4245474338531494
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5175356268882751
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.5698130130767822
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47609028220176697
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.6006067395210266
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.436489999294281
Calibrated prediction for HSBC: 0.4615384638309479
Raw prediction for IEP: 0.39223748445510864
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7016540765762329
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3543209433555603
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5308727025985718
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46861904859542847
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4068898558616638
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.42394453287124634
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5284578800201416
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5272349715232849
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5891199707984924
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.500374972820282
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.46763861179351807
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4362028241157532
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5154752731323242
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5013707280158997
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4218282699584961
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3339001536369324
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5184235572814941
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.6012663841247559
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47570252418518066
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46551042795181274
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4386696517467499
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.454235702753067
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5263249278068542
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5525486469268799
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.40301433205604553
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.45972201228141785
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.540364682674408
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4587462246417999
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4818575382232666
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5031665563583374
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5031589865684509
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3797994554042816
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.345869779586792
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6541414856910706
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.337395578622818
Calibrated prediction for TM: 0.3028290271759033
Raw prediction for TOT: 0.45219969749450684
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4346717298030853
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.44568872451782227
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3250748813152313
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.44167202711105347
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48807111382484436
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.04972313717007637
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5721288919448853
Calibrated prediction for V: 0.5811987519264221

Simulating Trading Days:  72%|███████▏  | 72/100 [05:41<00:32,  1.17s/it]

Raw prediction for VZ: 0.5556520819664001
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.4994497299194336
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.49759441614151
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5049307942390442
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.477
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.980, kelly=0.187) with $4846.39
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.944, kelly=0.166) with $4313.19
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.097, kelly=0.045) with $1166.90
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4553.94
[PORT] Sector Healthcare: 10 candidates, avg score=0.436
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.018, kelly=0.186) with $4836.57
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.454
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.006, kelly=0.145) with $3762.26
[PORT] Sector Services: 10 candidates, avg score=0.525
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.042, kelly=0.300) with $7785.64
[PORT] Sector Technology: 10 candidates, avg score=0.529
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.966, kelly=0.298) with $7744.56
[PORT] Sector Utilities: 10 candidates, avg score=0.517
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.906, kelly=0.187) with $4860.11
Raw prediction for AAPL: 0.4983702003955841
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5090272426605225
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.13444951176643372
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5793918371200562
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.41018715500831604
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.50526362657547
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6130631566047668
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.45458415150642395
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5828955173492432
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47595468163490295
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.432084321975708
Calibrated prediction for BBL: 0.42542508244514465
Raw prediction for BCH: 0.45222875475883484
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4879101514816284
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5417599678039551
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49002015590667725
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48702454566955566
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4590189456939697
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5156034231185913
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46874216198921204
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5521862506866455
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.47901830077171326
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.559490978717804
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3652694821357727
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44196414947509766
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4743838906288147
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4986957907676697
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5107758045196533
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5194299221038818
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49592769145965576
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.48461678624153137
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5060063004493713
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.515903890132904
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5315170288085938
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.43179187178611755
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5050954222679138
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5775320529937744
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4780882000923157
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5993630290031433
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.43995508551597595
Calibrated prediction for HSBC: 0.4615384638309479
Raw prediction for IEP: 0.3735954761505127
Calibrated prediction for IEP: 0.365497350692749
Raw prediction for INTC: 0.700168251991272
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.35753512382507324
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5323936343193054
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46774396300315857
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4138663113117218
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.4236375391483307
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5288365483283997
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5264174938201904
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5904698371887207
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49987658858299255
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4676157832145691
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4468342959880829
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5109812617301941
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49874383211135864
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4107646644115448
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.33261382579803467
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5190562009811401
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5976746678352356
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47507816553115845
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.465471088886261
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4384326934814453
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4532659947872162
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5340043306350708
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5359324216842651
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.3994999825954437
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.46053439378738403
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5323599576950073
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.4613538980484009
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4829474985599518
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5030557513237
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5022309422492981
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.38035473227500916
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.3451763987541199
Calibrated prediction for SRE: 0.43036380410194397

Simulating Trading Days:  73%|███████▎  | 73/100 [05:42<00:31,  1.17s/it]

Raw prediction for T: 0.6517153978347778
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.36097002029418945
Calibrated prediction for TM: 0.3076923191547394
Raw prediction for TOT: 0.46595069766044617
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4625048041343689
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.44338637590408325
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.29758068919181824
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.41925767064094543
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4877517819404602
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.047340329736471176
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5724433064460754
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.535241961479187
Calibrated prediction for VZ: 0.6161534786224365
Raw prediction for WFC: 0.49942344427108765
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4994809627532959
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5067735314369202
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.482
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.983, kelly=0.188) with $4876.54
[PORT] Sector Conglomerates: 7 candidates, avg score=0.442
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.945, kelly=0.167) with $4328.72
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.098, kelly=0.045) with $1172.17
[PORT] Sector Financial: 10 candidates, avg score=0.494
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4555.41
[PORT] Sector Healthcare: 10 candidates, avg score=0.436
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.016, kelly=0.186) with $4819.81
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.454
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.006, kelly=0.145) with $3771.81
[PORT] Sector Services: 10 candidates, avg score=0.525
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.040, kelly=0.299) with $7780.62
[PORT] Sector Technology: 10 candidates, avg score=0.505
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.967, kelly=0.299) with $7761.68
[PORT] Sector Utilities: 10 candidates, avg score=0.509
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.906, kelly=0.187) with $4857.39
Raw prediction for AAPL: 0.49848464131355286
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5135567784309387
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.13478197157382965
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5710598230361938
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.407932847738266
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.504500150680542
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.598492443561554
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.4535257816314697
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5900874733924866
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4778183698654175
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4351639151573181
Calibrated prediction for BBL: 0.42627084255218506
Raw prediction for BCH: 0.4680353105068207
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4879637360572815
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5355167984962463
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4900174140930176
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48706966638565063
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4682479798793793
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5155613422393799
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46879151463508606
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.5284559726715088
Calibrated prediction for CELG: 0.5894736647605896
Raw prediction for CHL: 0.466219425201416
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.5605697631835938
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.3602661192417145
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4394751191139221
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47158241271972656
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4983019232749939
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5109819769859314
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5210113525390625
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.496116578578949
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.46939611434936523
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.505634605884552
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5159022808074951
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5316019654273987
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.434040904045105
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.49113181233406067
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5848511457443237
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47772547602653503
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5979734063148499
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.4263949692249298
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.36019840836524963
Calibrated prediction for IEP: 0.365497350692749
Raw prediction for INTC: 0.6967581510543823
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.359706848859787
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5335931181907654
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4672935903072357
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.41689759492874146
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.4195661246776581
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5291703939437866
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5248045921325684
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5909882187843323
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.49930983781814575
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4675983488559723
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.46015676856040955
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5090121626853943
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4978969693183899
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.40309032797813416
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3319823741912842
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5197105407714844
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5970922112464905
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47463124990463257
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4656868875026703
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4382941424846649
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45238667726516724
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5483949184417725
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5205208659172058
Calibrated prediction for PPL: 0.565693736076355
Raw prediction for PTR: 0.3960123658180237
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.4625040888786316
Calibrated prediction for RDS-B: 0.44222620129585266
Raw prediction for REX: 0.5237011909484863
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.464590847492218
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48412230610847473
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5028674602508545
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.501294732093811
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3793100416660309
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.3578975200653076
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6475004553794861
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.39971789717674255
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.4763023257255554
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.4747176170349121
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.442079097032547
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.275922954082489
Calibrated prediction for UN: 0.24472057819366455
Raw prediction for UNH: 0.40350377559661865
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4877038598060608
Calibrated prediction for UPS: 0.4941723644733429

Simulating Trading Days:  74%|███████▍  | 74/100 [05:43<00:30,  1.18s/it]

Raw prediction for UTX: 0.04190026968717575
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5723794102668762
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5144742727279663
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.4994274973869324
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.5000860691070557
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5080238580703735
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.482
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.981, kelly=0.187) with $4868.03
[PORT] Sector Conglomerates: 7 candidates, avg score=0.442
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.945, kelly=0.167) with $4332.86
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.440
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.096, kelly=0.045) with $1158.20
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4577.95
[PORT] Sector Healthcare: 10 candidates, avg score=0.436
[PORT] Sector Healthcare: selecting CELG (p=0.589, b=1.017, kelly=0.186) with $4834.50
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.454
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.990, kelly=0.138) with $3593.56
[PORT] Sector Services: 10 candidates, avg score=0.525
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.039, kelly=0.299) with $7785.94
[PORT] Sector Technology: 10 candidates, avg score=0.491
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.966, kelly=0.298) with $7763.67
[PORT] Sector Utilities: 10 candidates, avg score=0.509
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.907, kelly=0.187) with $4877.40
Raw prediction for AAPL: 0.49853718280792236
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5208033323287964
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.13975045084953308
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5636526346206665
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4057924747467041
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5038987994194031
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.591771125793457
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.4533482789993286
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5968050360679626
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47855043411254883
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4383302330970764
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.4872715175151825
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4884989857673645
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5321981310844421
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.49030405282974243
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48663249611854553
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4762115776538849
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5157423615455627
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4692382514476776
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4934709966182709
Calibrated prediction for CELG: 0.48528406023979187
Raw prediction for CHL: 0.46684443950653076
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.5661541223526001
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.36977899074554443
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4343809187412262
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4709712862968445
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49813351035118103
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.511028528213501
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5244866609573364
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4956895709037781
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.46499425172805786
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5053241848945618
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5161225199699402
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5318261981010437
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4386054277420044
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.49080514907836914
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5911216139793396
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4788717031478882
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5970572829246521
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.40597036480903625
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.35252249240875244
Calibrated prediction for IEP: 0.365497350692749
Raw prediction for INTC: 0.6978209018707275
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.35891520977020264
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5340334177017212
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4670901298522949
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.463428795337677
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.41612204909324646
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5291227698326111
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5218023061752319
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5972533226013184
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5008057355880737
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4679395258426666
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.4808237552642822
Calibrated prediction for MSFT: 0.42460373044013977
Raw prediction for NEE: 0.5098572969436646
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49828216433525085
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.39686834812164307
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3340786099433899
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5201996564865112
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.593324601650238
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.4743014872074127
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46627277135849
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.438148558139801
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4529530107975006
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.571622908115387
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5069282650947571
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.39555373787879944
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.480147123336792
Calibrated prediction for RDS-B: 0.4700731635093689
Raw prediction for REX: 0.5250598192214966
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.4686313569545746
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4870370328426361
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5029515624046326
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5006915330886841
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3820304572582245
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.3734724819660187
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6428930759429932
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.43560218811035156
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4943908154964447
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5018059611320496
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.44115638732910156
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2568153142929077
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.3987497389316559
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48779383301734924
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.04529200866818428
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5721260905265808
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5025333762168884
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.49959906935691833
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.49748653173446655
Calibrated prediction for WMT: 0.49180328845977783

Simulating Trading Days:  75%|███████▌  | 75/100 [05:44<00:29,  1.18s/it]

Raw prediction for XOM: 0.507915198802948
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.486
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.981, kelly=0.187) with $4863.22
[PORT] Sector Conglomerates: 7 candidates, avg score=0.442
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.946, kelly=0.167) with $4341.33
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.445
[PORT] Sector Consumer Goods: selecting AAPL (p=0.500, b=1.095, kelly=0.044) with $1142.57
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4572.64
[PORT] Sector Healthcare: 10 candidates, avg score=0.426
[PORT] Sector Healthcare: selecting MDT (p=0.544, b=1.041, kelly=0.106) with $2752.13
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.463
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.992, kelly=0.139) with $3611.74
[PORT] Sector Services: 10 candidates, avg score=0.525
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.039, kelly=0.299) with $7773.65
[PORT] Sector Technology: 10 candidates, avg score=0.502
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.965, kelly=0.298) with $7741.50
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.907, kelly=0.188) with $4876.03
Raw prediction for AAPL: 0.49856171011924744
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5290953516960144
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.14433588087558746
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5595197081565857
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.4039230942726135
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5040025115013123
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.5913393497467041
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.45242854952812195
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5994548201560974
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47858089208602905
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.44174450635910034
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.49634629487991333
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48891186714172363
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5316962003707886
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4904714524745941
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4861653447151184
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48040273785591125
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5160459876060486
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4697495102882385
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4608907401561737
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.4888860583305359
Calibrated prediction for CHL: 0.5333333611488342
Raw prediction for CHTR: 0.5725627541542053
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.37992537021636963
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4293891489505768
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4705011248588562
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49800774455070496
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5111579298973083
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5268306732177734
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4950241446495056
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4650487005710602
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.504694402217865
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5165087580680847
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5319153070449829
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4443868398666382
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5030922293663025
Calibrated prediction for GOOG: 0.4476453363895416
Raw prediction for HD: 0.5973025560379028
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47892725467681885
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5968357920646667
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.38437768816947937
Calibrated prediction for HSBC: 0.3863636255264282
Raw prediction for IEP: 0.3491955101490021
Calibrated prediction for IEP: 0.365497350692749
Raw prediction for INTC: 0.6984966397285461
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3546466529369354
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5343952775001526
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4669778048992157
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5413917899131775
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.4139541685581207
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5287781357765198
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.518161416053772
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.6030309796333313
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5038265585899353
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4685778021812439
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5026728510856628
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5109384655952454
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49860841035842896
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.39239758253097534
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3371545672416687
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5205662250518799
Calibrated prediction for PCG: 0.5154157876968384
Raw prediction for PCLN: 0.5824797749519348
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4741077125072479
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4669531583786011
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.43798336386680603
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4551437199115753
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5924891829490662
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.49529632925987244
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.3956505358219147
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.49561038613319397
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.536055326461792
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.47192826867103577
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.48996633291244507
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5031968951225281
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5003133416175842
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3840083181858063
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.3900223672389984
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6370267868041992
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4545295238494873
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.5027307271957397
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5243349075317383
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4409199655056
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.24352969229221344
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4031318724155426
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4881548285484314
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.061367977410554886
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5720719695091248
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4947340190410614
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.49971169233322144
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.49815675616264343
Calibrated prediction for WMT: 0.49180328845977783

Simulating Trading Days:  76%|███████▌  | 76/100 [05:46<00:28,  1.20s/it]

Raw prediction for XOM: 0.5049008131027222
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.484
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.979, kelly=0.186) with $4843.24
[PORT] Sector Conglomerates: 7 candidates, avg score=0.442
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.941, kelly=0.165) with $4285.42
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.450
[PORT] Sector Consumer Goods: selecting PM (p=0.545, b=1.037, kelly=0.107) with $2787.77
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4564.33
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting MDT (p=0.544, b=1.040, kelly=0.105) with $2740.03
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.991, kelly=0.139) with $3608.12
[PORT] Sector Services: 10 candidates, avg score=0.525
[PORT] Sector Services: selecting PCLN (p=0.640, b=1.040, kelly=0.294) with $7646.59
[PORT] Sector Technology: 10 candidates, avg score=0.526
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.964, kelly=0.297) with $7739.15
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.909, kelly=0.189) with $4907.49
Raw prediction for AAPL: 0.49834325909614563
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5358675122261047
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.1398696005344391
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5597445368766785
Calibrated prediction for AEP: 0.6136363744735718
Raw prediction for AGFS: 0.40282270312309265
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5048233270645142
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6317577958106995
Calibrated prediction for AMZN: 0.5588235259056091
Raw prediction for BA: 0.45077529549598694
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.595948338508606
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47823041677474976
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4458853006362915
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5017892718315125
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4890693128108978
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5356719493865967
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4908076822757721
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48583465814590454
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48312869668006897
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5164278149604797
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4696368873119354
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4362722635269165
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5396230220794678
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5637268424034119
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.40362781286239624
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.43114814162254333
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47063353657722473
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49761727452278137
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5113816261291504
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5280131101608276
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49433302879333496
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4687317907810211
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5044000744819641
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.517446756362915
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5318662524223328
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.440420538187027
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5307706594467163
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.6027296185493469
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47988376021385193
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5980845093727112
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.36416298151016235
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.3507469594478607
Calibrated prediction for IEP: 0.365497350692749
Raw prediction for INTC: 0.6964033842086792
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3506348729133606
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5347518920898438
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4670827388763428
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.574171781539917
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.42342182993888855
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5284320712089539
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5147429704666138
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.6022309064865112
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.514621376991272
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4687783122062683
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.522434413433075
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5116503834724426
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49893149733543396
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.3896811902523041
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.34303125739097595
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5209085941314697
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5978423357009888
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47415971755981445
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46749401092529297
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.43824753165245056
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.45889219641685486
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6166852116584778
Calibrated prediction for PM: 0.5833333134651184
Raw prediction for PPL: 0.4881870448589325
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.3973899483680725
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5083789229393005
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5518344640731812
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4718625247478485
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49189281463623047
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5035781860351562
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5001547932624817
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.38158711791038513
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4136800765991211
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6292430758476257
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.49544304609298706
Calibrated prediction for TM: 0.4000000059604645

Simulating Trading Days:  77%|███████▋  | 77/100 [05:47<00:27,  1.20s/it]

Raw prediction for TOT: 0.5087073445320129
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5624901056289673
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4426559507846832
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2345801293849945
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4178866446018219
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4889851212501526
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.07512975484132767
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5730130076408386
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.500415027141571
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.49982327222824097
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.49254849553108215
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5011839270591736
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.490
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.977, kelly=0.185) with $4827.17
[PORT] Sector Conglomerates: 7 candidates, avg score=0.455
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.939, kelly=0.164) with $4263.55
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.454
[PORT] Sector Consumer Goods: selecting PM (p=0.583, b=1.036, kelly=0.181) with $4710.52
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4580.12
[PORT] Sector Healthcare: 10 candidates, avg score=0.408
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.009, kelly=0.009) with $237.31
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.049, kelly=0.267) with $6960.62
[PORT] Sector Services: 10 candidates, avg score=0.525
[PORT] Sector Services: selecting PCLN (p=0.643, b=1.043, kelly=0.300) with $7816.06
[PORT] Sector Technology: 10 candidates, avg score=0.539
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.964, kelly=0.297) with $7742.02
[PORT] Sector Utilities: 10 candidates, avg score=0.507
[PORT] Sector Utilities: selecting AEP (p=0.614, b=0.911, kelly=0.189) with $4927.13
Raw prediction for AAPL: 0.4981730282306671
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5416643023490906
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.13310983777046204
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.556421160697937
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.40163129568099976
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5062240958213806
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.6951736807823181
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.44875675439834595
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5961517095565796
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4780222475528717
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.45069676637649536
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5076808333396912
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4891597330570221
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5427471399307251
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4912251830101013
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48532646894454956
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.49420011043548584
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5165551900863647
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4692060351371765
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4202762544155121
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5526613593101501
Calibrated prediction for CHL: 0.5888440608978271
Raw prediction for CHTR: 0.5523598194122314
Calibrated prediction for CHTR: 0.5833333134651184
Raw prediction for CMCSA: 0.411452978849411
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.43129196763038635
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4720449149608612
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4970998764038086
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5115471482276917
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5281867980957031
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49401676654815674
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.47022926807403564
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.50374436378479
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5172189474105835
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5320680737495422
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.43365731835365295
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5577686429023743
Calibrated prediction for GOOG: 0.5625
Raw prediction for HD: 0.6068154573440552
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.48039689660072327
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.597277045249939
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.35520192980766296
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.358653724193573
Calibrated prediction for IEP: 0.365497350692749
Raw prediction for INTC: 0.695797860622406
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.34646427631378174
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5354200005531311
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4675002098083496
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5831682085990906
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.44898664951324463
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5282403826713562
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5149994492530823
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.598244845867157
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5668521523475647
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4682897925376892
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5280910730361938
Calibrated prediction for MSFT: 0.5319148898124695
Raw prediction for NEE: 0.5107926726341248
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49943456053733826
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.3880128562450409
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.348635196685791
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5211148262023926
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5973270535469055
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47460830211639404
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46744614839553833
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.43884485960006714
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4616509675979614
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6421113610267639
Calibrated prediction for PM: 0.7142857313156128
Raw prediction for PPL: 0.4835416376590729
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.40013211965560913
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5148074626922607
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5623247623443604
Calibrated prediction for REX: 0.5555896162986755
Raw prediction for SLB: 0.4723065197467804
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49215495586395264
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5037322044372559
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5001050233840942
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3816249668598175
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.43300971388816833
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6151260137557983
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5387810468673706
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.503638505935669
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5725110173225403
Calibrated prediction for TSM: 0.6146438717842102
Raw prediction for UL: 0.4449186325073242
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.22871184349060059
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4309191405773163
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48997563123703003
Calibrated prediction for UPS: 0.4941723644733429

Simulating Trading Days:  78%|███████▊  | 78/100 [05:48<00:26,  1.19s/it]

Raw prediction for UTX: 0.08355484157800674
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5735742449760437
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4919757843017578
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5003515481948853
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4906899631023407
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5069587230682373
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.975, kelly=0.185) with $4815.39
[PORT] Sector Conglomerates: 7 candidates, avg score=0.459
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.940, kelly=0.164) with $4284.65
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.476
[PORT] Sector Consumer Goods: selecting PM (p=0.714, b=1.033, kelly=0.438) with $11416.50
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4577.72
[PORT] Sector Healthcare: 10 candidates, avg score=0.408
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.010, kelly=0.010) with $255.83
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.048, kelly=0.267) with $6972.31
[PORT] Sector Services: 10 candidates, avg score=0.553
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.049, kelly=0.744) with $19396.93
[PORT] Sector Technology: 10 candidates, avg score=0.549
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.963, kelly=0.297) with $7748.50
[PORT] Sector Utilities: 10 candidates, avg score=0.502
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.909, kelly=0.100) with $2607.04
Raw prediction for AAPL: 0.49776697158813477
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5449264645576477
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.12839899957180023
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5520216226577759
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.40030717849731445
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5077159404754639
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7698596715927124
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4467390179634094
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5961102843284607
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47817495465278625
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.453396201133728
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5078394412994385
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4891573190689087
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.551926851272583
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.49142274260520935
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4847148358821869
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4968717396259308
Calibrated prediction for BUD: 0.5885424613952637
Raw prediction for C: 0.5168184041976929
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46876028180122375
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4141607880592346
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5601341128349304
Calibrated prediction for CHL: 0.6552293300628662
Raw prediction for CHTR: 0.5437636375427246
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.43274858593940735
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4303056001663208
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47554951906204224
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.4965905249118805
Calibrated prediction for CVX: 0.5058530569076538
Raw prediction for D: 0.5117099285125732
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.528165340423584
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49385493993759155
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4674815237522125
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5029810070991516
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5171263813972473
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.532122015953064
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.42687079310417175
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.5851337909698486
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.6094592213630676
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.48468419909477234
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5972320437431335
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3470050096511841
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.37264755368232727
Calibrated prediction for IEP: 0.365497350692749
Raw prediction for INTC: 0.6989486813545227
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.34565356373786926
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5360071063041687
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4674449563026428
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5861082673072815
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4746306538581848
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.528006374835968
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5170515775680542
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.593336820602417
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6120476126670837
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46729421615600586
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.537961483001709
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.509652853012085
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4996427595615387
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.3876914083957672
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.35713401436805725
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5213190913200378
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6028915047645569
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47487080097198486
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46723976731300354
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4387407898902893
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46246111392974854
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6494030356407166
Calibrated prediction for PM: 0.7376610636711121
Raw prediction for PPL: 0.47997844219207764
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.40141555666923523
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5207990407943726
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5653202533721924
Calibrated prediction for REX: 0.5714285969734192
Raw prediction for SLB: 0.47044292092323303
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49220046401023865
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5037190318107605
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5000796318054199
Calibrated prediction for SO: 0.49570509791374207

Simulating Trading Days:  79%|███████▉  | 79/100 [05:49<00:24,  1.19s/it]

Raw prediction for SPLP: 0.3816937506198883
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.45212411880493164
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6025475263595581
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5431115627288818
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.48560085892677307
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5788573026657104
Calibrated prediction for TSM: 0.6146438717842102
Raw prediction for UL: 0.44485029578208923
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.22181780636310577
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4419434070587158
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4906831383705139
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.08332174271345139
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5735238194465637
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.47985032200813293
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.500659167766571
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4844365417957306
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5095609426498413
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.501
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.975, kelly=0.185) with $4806.94
[PORT] Sector Conglomerates: 7 candidates, avg score=0.461
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.939, kelly=0.164) with $4267.52
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.487
[PORT] Sector Consumer Goods: selecting PM (p=0.738, b=1.033, kelly=0.484) with $12599.85
[PORT] Sector Financial: 10 candidates, avg score=0.494
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4581.46
[PORT] Sector Healthcare: 10 candidates, avg score=0.408
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.011, kelly=0.010) with $265.99
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.047, kelly=0.267) with $6947.48
[PORT] Sector Services: 10 candidates, avg score=0.550
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.048, kelly=0.743) with $19368.31
[PORT] Sector Technology: 10 candidates, avg score=0.563
[PORT] Sector Technology: selecting CHL (p=0.655, b=1.085, kelly=0.337) with $8791.06
[PORT] Sector Utilities: 10 candidates, avg score=0.512
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.907, kelly=0.099) with $2581.18
Raw prediction for AAPL: 0.49721795320510864
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5454914569854736
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.12344559282064438
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5467066168785095
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.3992486298084259
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5089966654777527
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8154386878013611
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4453934133052826
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.5976078510284424
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4779612421989441
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4557758867740631
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.5016500949859619
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48918426036834717
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5617351531982422
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.49146270751953125
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48422324657440186
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4990597665309906
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5171858668327332
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46827349066734314
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4164711534976959
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5636043548583984
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.5256381034851074
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.427417129278183
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4374952018260956
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.47924190759658813
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49633267521858215
Calibrated prediction for CVX: 0.5
Raw prediction for D: 0.5119438171386719
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5287944674491882
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49381986260414124
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4653664529323578
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5021696090698242
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5170442461967468
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5320413708686829
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.42233285307884216
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6058393716812134
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.609394371509552
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.48888006806373596
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.598675012588501
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3347468078136444
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.39160382747650146
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.700565755367279
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.34442663192749023
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5360974669456482
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4674384891986847
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5964102745056152
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.49125993251800537
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5277702808380127
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5185387134552002
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5896474123001099
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6283940672874451
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.4663139283657074
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5498614311218262
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5075363516807556
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49903133511543274
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.38850653171539307
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.36449629068374634
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5216012597084045
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5917320847511292
Calibrated prediction for PCLN: 0.6428571343421936
Raw prediction for PEP: 0.47511497139930725
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4671032428741455
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4382481575012207
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4628888964653015
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6436592936515808
Calibrated prediction for PM: 0.7142857313156128
Raw prediction for PPL: 0.4761204421520233
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4028854966163635
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5258380770683289
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5617440342903137
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.46796271204948425
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4927307069301605
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.503680944442749
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.500067412853241
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3803189992904663
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4691776931285858
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.5978346467018127
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5228736996650696
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4784703850746155
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5745111703872681
Calibrated prediction for TSM: 0.6146438717842102
Raw prediction for UL: 0.44501885771751404
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.22100555896759033
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4451618194580078
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49114790558815
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.079429492354393
Calibrated prediction for UTX: 0.1294490545988083

Simulating Trading Days:  80%|████████  | 80/100 [05:50<00:23,  1.19s/it]

Raw prediction for V: 0.5724934339523315
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4671761691570282
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5007014274597168
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4847754240036011
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5105645060539246
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.508
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.895, kelly=0.153) with $3985.05
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.939, kelly=0.164) with $4262.88
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.498
[PORT] Sector Consumer Goods: selecting PM (p=0.714, b=1.031, kelly=0.437) with $11370.36
[PORT] Sector Financial: 10 candidates, avg score=0.494
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4561.06
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting MDT (p=0.544, b=1.044, kelly=0.107) with $2790.98
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.046, kelly=0.267) with $6934.96
[PORT] Sector Services: 10 candidates, avg score=0.549
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.051, kelly=0.744) with $19344.53
[PORT] Sector Technology: 10 candidates, avg score=0.565
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.086, kelly=0.360) with $9358.31
[PORT] Sector Utilities: 10 candidates, avg score=0.512
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.906, kelly=0.099) with $2565.31
Raw prediction for AAPL: 0.4970015585422516
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.544147253036499
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.11756923049688339
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5417138338088989
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.39840081334114075
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5099497437477112
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8344032764434814
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4452703893184662
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6003369688987732
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47710612416267395
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4570833146572113
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.4925174117088318
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48920759558677673
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5674408078193665
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.4914577007293701
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48372170329093933
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5060663223266602
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5174974203109741
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.467906653881073
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.42172306776046753
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5730948448181152
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.500016450881958
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.4177916646003723
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44387537240982056
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4851783812046051
Calibrated prediction for CSCO: 0.5058823823928833
Raw prediction for CVX: 0.49603378772735596
Calibrated prediction for CVX: 0.5
Raw prediction for D: 0.5122624635696411
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5292766094207764
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4938449263572693
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4640939235687256
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5016806721687317
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5170598030090332
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5319326519966125
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.41937991976737976
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6238309741020203
Calibrated prediction for GOOG: 0.64083331823349
Raw prediction for HD: 0.6080017685890198
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.49039071798324585
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5984101295471191
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3232666254043579
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.41500329971313477
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7011901140213013
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.34393998980522156
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5356786847114563
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.467805415391922
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.6020956039428711
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.49576279520988464
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.52772456407547
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5197363495826721
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5855947732925415
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6405649781227112
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46568426489830017
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5646159052848816
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5054934024810791
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4983883798122406
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.389006644487381
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.37175002694129944
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.521877646446228
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5890145301818848
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47571995854377747
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4671875238418579
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.43796461820602417
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46369069814682007
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6408509612083435
Calibrated prediction for PM: 0.7142857313156128
Raw prediction for PPL: 0.4713808596134186
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.40336278080940247
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5294936895370483
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5512984991073608
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.4643164277076721
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49279215931892395
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5035849809646606
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.4998994767665863
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.38035425543785095
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.48326313495635986
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6007931232452393
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5148974657058716
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.46643853187561035
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5643296837806702
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4470444619655609
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.22919633984565735
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4439813196659088
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4912621080875397
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.0706460028886795
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5702342391014099
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.45609036087989807
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5010042786598206
Calibrated prediction for WFC: 0.5066666603088379

Simulating Trading Days:  81%|████████  | 81/100 [05:52<00:22,  1.19s/it]

Raw prediction for WMT: 0.4820626974105835
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5087651014328003
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.508
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.897, kelly=0.154) with $4005.27
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.941, kelly=0.165) with $4283.09
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.498
[PORT] Sector Consumer Goods: selecting PM (p=0.714, b=1.029, kelly=0.437) with $11359.07
[PORT] Sector Financial: 10 candidates, avg score=0.494
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4568.97
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting MDT (p=0.544, b=1.042, kelly=0.106) with $2769.45
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.045, kelly=0.266) with $6927.75
[PORT] Sector Services: 10 candidates, avg score=0.548
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.052, kelly=0.744) with $19353.77
[PORT] Sector Technology: 10 candidates, avg score=0.559
[PORT] Sector Technology: selecting CHL (p=0.667, b=1.085, kelly=0.359) with $9349.73
[PORT] Sector Utilities: 10 candidates, avg score=0.512
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.905, kelly=0.098) with $2552.76
Raw prediction for AAPL: 0.49703264236450195
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5421162843704224
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.11197492480278015
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5369807481765747
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.39853963255882263
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5106948018074036
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8447059392929077
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.44634124636650085
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6032464504241943
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4760552644729614
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4574558734893799
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.4817294180393219
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4891607463359833
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5697070360183716
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.4913637340068817
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48360520601272583
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5101844668388367
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5175718069076538
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46756792068481445
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4267362654209137
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5770488977432251
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.47955960035324097
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.4077010154724121
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4467576742172241
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.49099889397621155
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4955443739891052
Calibrated prediction for CVX: 0.4902775287628174
Raw prediction for D: 0.5126134753227234
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5291424989700317
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4935564696788788
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.46052810549736023
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5011102557182312
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5169668793678284
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5319069027900696
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4160996377468109
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6412461996078491
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6070674061775208
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.48750966787338257
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5983947515487671
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.31469962000846863
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.43904027342796326
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.7012993693351746
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3454057276248932
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5349858403205872
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46800628304481506
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5957056879997253
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4935048818588257
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5277658700942993
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5215635299682617
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.581375002861023
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6449742913246155
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.4653056263923645
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5787060260772705
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5039348602294922
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4974376857280731
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.38808155059814453
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.37644246220588684
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.522217869758606
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5825198888778687
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4762677550315857
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4670793116092682
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.437543660402298
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.4657016694545746
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.6246928572654724
Calibrated prediction for PM: 0.5833333134651184
Raw prediction for PPL: 0.4667457342147827
Calibrated prediction for PPL: 0.49620679020881653
Raw prediction for PTR: 0.4042753577232361
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5289131999015808
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5355474352836609
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.4621395766735077
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49291476607322693
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5033313035964966
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.49996376037597656
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.38209331035614014
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4780482351779938
Calibrated prediction for SRE: 0.5277777910232544

Simulating Trading Days:  82%|████████▏ | 82/100 [05:53<00:21,  1.19s/it]

Raw prediction for T: 0.6036888957023621
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.49969613552093506
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4574470818042755
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.551468014717102
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4486418664455414
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.24150437116622925
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.43517449498176575
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.49118146300315857
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.06122755631804466
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5689312219619751
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4443727731704712
Calibrated prediction for VZ: 0.4029945135116577
Raw prediction for WFC: 0.5014148950576782
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.48034748435020447
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5061817169189453
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.507
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.896, kelly=0.153) with $4001.14
[PORT] Sector Conglomerates: 7 candidates, avg score=0.453
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.942, kelly=0.165) with $4308.47
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.485
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.949, kelly=0.337) with $8794.93
[PORT] Sector Financial: 10 candidates, avg score=0.494
[PORT] Sector Financial: selecting V (p=0.581, b=1.031, kelly=0.175) with $4562.32
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting MDT (p=0.544, b=1.041, kelly=0.106) with $2763.13
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.044, kelly=0.266) with $6932.02
[PORT] Sector Services: 10 candidates, avg score=0.548
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.049, kelly=0.744) with $19385.02
[PORT] Sector Technology: 10 candidates, avg score=0.558
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.042, kelly=0.384) with $10015.30
[PORT] Sector Utilities: 10 candidates, avg score=0.509
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.907, kelly=0.099) with $2573.37
Raw prediction for AAPL: 0.4970274269580841
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5399876236915588
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.10829957574605942
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5349203944206238
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.3991788625717163
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5112642645835876
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.847671389579773
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4483644366264343
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6071519255638123
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47497427463531494
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4575052559375763
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.47505927085876465
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4891771972179413
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5700204372406006
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.4914241433143616
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48351922631263733
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5087401866912842
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.517513632774353
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4672214686870575
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.43052878975868225
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5803857445716858
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.4640563726425171
Calibrated prediction for CHTR: 0.47058823704719543
Raw prediction for CMCSA: 0.40794065594673157
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44023406505584717
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.4963259994983673
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4951621890068054
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5128213763237
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5291671752929688
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4929710328578949
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.45576101541519165
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5010702610015869
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5167315006256104
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5318323969841003
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.41184672713279724
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6554965376853943
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6060307025909424
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4822830259799957
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5976395010948181
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3120425045490265
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.45874708890914917
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6983912587165833
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3467317223548889
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5340594053268433
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46823740005493164
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5782362222671509
Calibrated prediction for LMT: 0.625
Raw prediction for MA: 0.4957900047302246
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5278893709182739
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5203349590301514
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5761964917182922
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6454393863677979
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46525752544403076
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5892894864082336
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5038291215896606
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49732449650764465
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.38910725712776184
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3810046911239624
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.522429347038269
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5693446397781372
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.47659608721733093
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46671581268310547
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.43704551458358765
Calibrated prediction for PG: 0.44319599866867065
Raw prediction for PICO: 0.46736380457878113
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5988791584968567
Calibrated prediction for PM: 0.5454545617103577
Raw prediction for PPL: 0.4644511938095093
Calibrated prediction for PPL: 0.4791666567325592
Raw prediction for PTR: 0.40429022908210754
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5265216827392578
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.524563729763031
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.46348491311073303
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.49343493580818176
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5030957460403442
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.499985933303833
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3862926959991455
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4648784101009369
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6066523790359497
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.46164554357528687
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.44908663630485535
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.532745897769928
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4504201114177704
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.2587452232837677
Calibrated prediction for UN: 0.23408153653144836
Raw prediction for UNH: 0.4249300956726074
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4909708499908447
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.055764734745025635
Calibrated prediction for UTX: 0.1294490545988083

Simulating Trading Days:  83%|████████▎ | 83/100 [05:54<00:20,  1.19s/it]

Raw prediction for V: 0.5685284733772278
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.43429771065711975
Calibrated prediction for VZ: 0.4029945135116577
Raw prediction for WFC: 0.5021405220031738
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4793095290660858
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5037920475006104
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.502
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.894, kelly=0.153) with $3972.63
[PORT] Sector Conglomerates: 7 candidates, avg score=0.453
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.944, kelly=0.166) with $4321.48
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.481
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.949, kelly=0.337) with $8786.85
[PORT] Sector Financial: 10 candidates, avg score=0.494
[PORT] Sector Financial: selecting V (p=0.581, b=1.030, kelly=0.175) with $4550.17
[PORT] Sector Healthcare: 10 candidates, avg score=0.418
[PORT] Sector Healthcare: selecting MDT (p=0.544, b=1.041, kelly=0.106) with $2759.69
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.475
[PORT] Sector Industrial Goods: selecting LMT (p=0.625, b=1.042, kelly=0.265) with $6907.13
[PORT] Sector Services: 10 candidates, avg score=0.542
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.048, kelly=0.743) with $19363.50
[PORT] Sector Technology: 10 candidates, avg score=0.564
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.040, kelly=0.384) with $9991.58
[PORT] Sector Utilities: 10 candidates, avg score=0.498
[PORT] Sector Utilities: selecting SRE (p=0.528, b=0.932, kelly=0.021) with $554.11
Raw prediction for AAPL: 0.49695178866386414
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5386970043182373
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.10748888552188873
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5330421924591064
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.39979472756385803
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5116609930992126
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.850736677646637
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.450665682554245
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.608492374420166
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4731166362762451
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4593401849269867
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.47095558047294617
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48935022950172424
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5716598629951477
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.49124467372894287
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4838184714317322
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5022575259208679
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5173909664154053
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4668540954589844
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4310538172721863
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5758417248725891
Calibrated prediction for CHL: 0.6666666865348816
Raw prediction for CHTR: 0.46479690074920654
Calibrated prediction for CHTR: 0.47058823704719543
Raw prediction for CMCSA: 0.42766544222831726
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4384726881980896
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.49950024485588074
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4944193959236145
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5128930807113647
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5295334458351135
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4921068549156189
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.44961845874786377
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5008395314216614
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5165174007415771
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5318228602409363
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4098392724990845
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6638713479042053
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6062673926353455
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47932252287864685
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5969091057777405
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3124270439147949
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4697115123271942
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6925032734870911
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3475003242492676
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5329669117927551
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4684956669807434
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5637996792793274
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5021364688873291
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5279819369316101
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5150409936904907
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5728887915611267
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6413983702659607
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.4654678702354431
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5947732329368591
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5037932991981506
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49753740429878235
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.3920924663543701
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.3853483498096466
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5226070284843445
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5618533492088318
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4766439199447632
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4661819338798523
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4365846812725067
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.46981748938560486
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5768749713897705
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4624367356300354
Calibrated prediction for PPL: 0.4791666567325592
Raw prediction for PTR: 0.4063195586204529
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5257042050361633
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5239430665969849
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.4727326035499573
Calibrated prediction for SLB: 0.4251968562602997
Raw prediction for SNP: 0.4951724708080292
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5030841827392578
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5001025795936584
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3865622878074646
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4459770917892456
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6081112027168274
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4275377094745636
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.44818639755249023
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5109355449676514
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45221108198165894
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.277213454246521
Calibrated prediction for UN: 0.28002265095710754
Raw prediction for UNH: 0.4154992699623108
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4907127022743225
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.05272916704416275
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5698754787445068
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4272851347923279
Calibrated prediction for VZ: 0.4029945135116577
Raw prediction for WFC: 0.5024939179420471
Calibrated prediction for WFC: 0.5066666603088379

Simulating Trading Days:  84%|████████▍ | 84/100 [05:55<00:19,  1.19s/it]

Raw prediction for WMT: 0.47683483362197876
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5025059580802917
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.502
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.896, kelly=0.153) with $3986.85
[PORT] Sector Conglomerates: 7 candidates, avg score=0.453
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.944, kelly=0.166) with $4314.85
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.480
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.948, kelly=0.337) with $8765.43
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4561.79
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.013, kelly=0.011) with $288.02
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.998, kelly=0.141) with $3677.80
[PORT] Sector Services: 10 candidates, avg score=0.542
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.050, kelly=0.744) with $19333.39
[PORT] Sector Technology: 10 candidates, avg score=0.564
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.042, kelly=0.384) with $9986.11
[PORT] Sector Utilities: 10 candidates, avg score=0.493
[PORT] Sector Utilities: selecting SRE (p=0.528, b=0.931, kelly=0.021) with $535.89
Raw prediction for AAPL: 0.49716007709503174
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5374641418457031
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.10623501241207123
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5328880548477173
Calibrated prediction for AEP: 0.48112761974334717
Raw prediction for AGFS: 0.40058618783950806
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.511961817741394
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8600398898124695
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4529465436935425
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6089193224906921
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4713590741157532
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4637035131454468
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.4694235920906067
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48947232961654663
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5709028840065002
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.49079665541648865
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4841668903827667
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.49776768684387207
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5174028277397156
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46654054522514343
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4325557053089142
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5583956241607666
Calibrated prediction for CHL: 0.6397852301597595
Raw prediction for CHTR: 0.4647279977798462
Calibrated prediction for CHTR: 0.47058823704719543
Raw prediction for CMCSA: 0.4496046304702759
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4426487386226654
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5017887949943542
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49390190839767456
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5129005312919617
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5302632451057434
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49105820059776306
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4428763687610626
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5008155107498169
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5165256261825562
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5316550731658936
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.40844324231147766
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6687911152839661
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.604873538017273
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.47807925939559937
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.59638911485672
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3147165775299072
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4729023277759552
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6852766275405884
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3496161997318268
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5319377183914185
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46882420778274536
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5457615852355957
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.513463020324707
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5280143022537231
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.507125198841095
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5699307918548584
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6377120614051819
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46603119373321533
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5956411957740784
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5036309957504272
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.49828770756721497
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.39766785502433777
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.39158669114112854
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5227835774421692
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.5610359907150269
Calibrated prediction for PCLN: 0.6399999856948853
Raw prediction for PEP: 0.4766113758087158
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4658132791519165
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43629518151283264
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4729056656360626
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5596844553947449
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.46199649572372437
Calibrated prediction for PPL: 0.4791666567325592
Raw prediction for PTR: 0.4106190800666809
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5236348509788513
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5328879952430725
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.48702192306518555
Calibrated prediction for SLB: 0.4285714328289032
Raw prediction for SNP: 0.49733811616897583
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5033156275749207
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5003284811973572
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3843614161014557
Calibrated prediction for SPLP: 0.30125677585601807

Simulating Trading Days:  85%|████████▌ | 85/100 [05:56<00:17,  1.19s/it]

Raw prediction for SRE: 0.4305495023727417
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6094922423362732
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4070241451263428
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.45306074619293213
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.499324232339859
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4530892074108124
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.29316988587379456
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4105679988861084
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4904380738735199
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.059355445206165314
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5719261169433594
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.42773571610450745
Calibrated prediction for VZ: 0.4029945135116577
Raw prediction for WFC: 0.5026365518569946
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.47577619552612305
Calibrated prediction for WMT: 0.49180328845977783
Raw prediction for XOM: 0.5020236372947693
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.503
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.897, kelly=0.154) with $3974.78
[PORT] Sector Conglomerates: 7 candidates, avg score=0.453
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.942, kelly=0.165) with $4264.88
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.488
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.950, kelly=0.338) with $8728.26
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.034, kelly=0.176) with $4549.09
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.014, kelly=0.012) with $305.50
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.996, kelly=0.141) with $3630.87
[PORT] Sector Services: 10 candidates, avg score=0.542
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.051, kelly=0.744) with $19209.90
[PORT] Sector Technology: 10 candidates, avg score=0.562
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.044, kelly=0.385) with $9931.38
[PORT] Sector Utilities: 10 candidates, avg score=0.483
[PORT] Sector Utilities: Kelly <= 0 for NEE (p=0.526, b=0.899)
Raw prediction for AAPL: 0.4974316656589508
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5369304418563843
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.1050148606300354
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5362165570259094
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.40137502551078796
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5122518539428711
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.890345573425293
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4550957977771759
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6120483875274658
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4694203734397888
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4683421850204468
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.46770212054252625
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4894789457321167
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.567411482334137
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.48990532755851746
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4844709038734436
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.49708113074302673
Calibrated prediction for BUD: 0.5980516672134399
Raw prediction for C: 0.5173541903495789
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46637070178985596
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4331640303134918
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.535287618637085
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.4956323802471161
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.4862891137599945
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4534820020198822
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5041095614433289
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4938492178916931
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5129022598266602
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5311194062232971
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4909793436527252
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.43862777948379517
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5015658140182495
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5165004730224609
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5316439867019653
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4081592559814453
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6736200451850891
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6087715029716492
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4788728952407837
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5948291420936584
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3113986551761627
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4659298360347748
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6793984770774841
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3531648516654968
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.531288743019104
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4691478908061981
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5348020792007446
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.5050005316734314
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.528651237487793
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.49857062101364136
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5683474540710449
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6345116496086121
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46657562255859375
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5937739610671997
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5032464265823364
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.4992879033088684
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4035230278968811
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.39831387996673584
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5228843092918396
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6462724208831787
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47651407122612
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4655379354953766
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43597105145454407
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.475872278213501
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5430470705032349
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4649205505847931
Calibrated prediction for PPL: 0.4791666567325592
Raw prediction for PTR: 0.41634461283683777
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5197940468788147
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5441386103630066
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5035572648048401
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.4993787407875061
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.503538966178894
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5006369948387146
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.37592288851737976
Calibrated prediction for SPLP: 0.30125677585601807

Simulating Trading Days:  86%|████████▌ | 86/100 [05:58<00:17,  1.26s/it]

Raw prediction for SRE: 0.43110862374305725
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6128817200660706
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4038805067539215
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.457100510597229
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.494798868894577
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45306500792503357
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.30064594745635986
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4096106290817261
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4901864528656006
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.0720440223813057
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5730059146881104
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4400687515735626
Calibrated prediction for VZ: 0.4029945135116577
Raw prediction for WFC: 0.5026900768280029
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.46400853991508484
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5006695985794067
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.501
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.976, kelly=0.185) with $4790.88
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.943, kelly=0.166) with $4294.73
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.486
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.950, kelly=0.338) with $8750.71
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4544.75
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.015, kelly=0.012) with $315.51
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.998, kelly=0.141) with $3664.13
[PORT] Sector Services: 10 candidates, avg score=0.562
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.048, kelly=0.743) with $19254.00
[PORT] Sector Technology: 10 candidates, avg score=0.553
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.042, kelly=0.384) with $9944.33
[PORT] Sector Utilities: 10 candidates, avg score=0.492
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.909, kelly=0.100) with $2588.24
Raw prediction for AAPL: 0.49748513102531433
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5365491509437561
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.10915044695138931
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5379486083984375
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.40207159519195557
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5126162767410278
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.9197838306427002
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4580843448638916
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6161019206047058
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4691552221775055
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.4740298092365265
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.47010424733161926
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4895395040512085
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5604457855224609
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.4890173673629761
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4848931133747101
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5031617879867554
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5172283053398132
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4663577377796173
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4400187134742737
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.5119351744651794
Calibrated prediction for CHL: 0.550000011920929
Raw prediction for CHTR: 0.5045759081840515
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.497392863035202
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4642592668533325
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5077616572380066
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4934956133365631
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.512824296951294
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5319433808326721
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4912647008895874
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.43706077337265015
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5022718906402588
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5171893835067749
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5315356254577637
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.40643489360809326
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6849222183227539
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6116032004356384
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4841451048851013
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5933871269226074
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3104321360588074
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.45262888073921204
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6719928979873657
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.35635441541671753
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5315849184989929
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46957388520240784
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5085363388061523
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.525079071521759
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5292982459068298
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4921196699142456
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.566994309425354
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6362553238868713
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46747025847435
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5881311297416687
Calibrated prediction for MSFT: 0.6000000238418579
Raw prediction for NEE: 0.5033780932426453
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5001562237739563
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4121820032596588
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.4079062342643738
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5229706764221191
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6999737024307251
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4766453206539154
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.465498149394989
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4359061121940613
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4780660569667816
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.533850371837616
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.46847522258758545
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.42820045351982117
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5119766592979431
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5513631105422974
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5183935165405273
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5015729069709778
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5039950013160706
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5008944272994995
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.36738190054893494
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.438907265663147
Calibrated prediction for SRE: 0.43036380410194397
Raw prediction for T: 0.6189103126525879
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4390331506729126
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.46386781334877014
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5264670848846436
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4528740644454956
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.30816909670829773
Calibrated prediction for UN: 0.4285714328289032

Simulating Trading Days:  87%|████████▋ | 87/100 [05:59<00:16,  1.26s/it]

Raw prediction for UNH: 0.4221736490726471
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4901054799556732
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.09095781296491623
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.576521635055542
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.46114248037338257
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5029440522193909
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4563036561012268
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5023072361946106
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.501
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.977, kelly=0.185) with $4815.54
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.945, kelly=0.167) with $4334.23
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.495
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.950, kelly=0.338) with $8787.06
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.031, kelly=0.175) with $4554.90
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.013, kelly=0.011) with $295.23
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.467
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.000, kelly=0.142) with $3701.75
[PORT] Sector Services: 10 candidates, avg score=0.562
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.048, kelly=0.743) with $19329.70
[PORT] Sector Technology: 10 candidates, avg score=0.558
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.041, kelly=0.384) with $9980.12
[PORT] Sector Utilities: 10 candidates, avg score=0.497
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.908, kelly=0.100) with $2589.49
Raw prediction for AAPL: 0.49725303053855896
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5366482734680176
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.11487440764904022
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5421716570854187
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.4033915400505066
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.513147234916687
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.926264226436615
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46102914214134216
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6176818609237671
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.47024351358413696
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.47723785042762756
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.4743039608001709
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4897681474685669
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.545701265335083
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.4881717264652252
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4853847622871399
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.50772625207901
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5170210599899292
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46652278304100037
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4469236731529236
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.47887781262397766
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.5031737089157104
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.48327839374542236
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.47028008103370667
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5113492012023926
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49305251240730286
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5126653909683228
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5315344929695129
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49172601103782654
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4408866763114929
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5033695697784424
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5175372958183289
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5314232110977173
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.40560904145240784
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6914992928504944
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6109388470649719
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4884623885154724
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5916637182235718
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.31074488162994385
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4426674246788025
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6639466285705566
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3572627604007721
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5326449871063232
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46983569860458374
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.46919992566108704
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.5371285676956177
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5297316908836365
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.48896607756614685
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5645007491111755
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.636584997177124
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46788743138313293
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5815165638923645
Calibrated prediction for MSFT: 0.5940393805503845
Raw prediction for NEE: 0.5038045644760132
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.501211404800415
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.41942188143730164
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.415811151266098
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5230103135108948
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.715360701084137
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4767746031284332
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4654749035835266
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4357299208641052
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4803639352321625
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5258230566978455
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4756017327308655
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.44256269931793213
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5028111338615417
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5527371168136597
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5298401117324829
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5049106478691101
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5041292309761047
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5010346174240112
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.358423113822937
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.4542231559753418
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6235650181770325
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4616696536540985
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.47131893038749695
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5319843888282776
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4524534344673157
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.31585893034935
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4403201639652252
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4900873303413391
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.11096270382404327
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5797713398933411
Calibrated prediction for V: 0.5811987519264221

Simulating Trading Days:  88%|████████▊ | 88/100 [06:00<00:14,  1.24s/it]

Raw prediction for VZ: 0.47599664330482483
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.503191351890564
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.45223841071128845
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5042137503623962
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.502
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.978, kelly=0.186) with $4831.19
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.943, kelly=0.166) with $4310.89
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.495
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.951, kelly=0.338) with $8789.26
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.034, kelly=0.176) with $4576.25
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.012, kelly=0.011) with $276.10
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.463
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.000, kelly=0.142) with $3701.57
[PORT] Sector Services: 10 candidates, avg score=0.562
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.048, kelly=0.743) with $19331.07
[PORT] Sector Technology: 10 candidates, avg score=0.543
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.041, kelly=0.384) with $9978.37
[PORT] Sector Utilities: 10 candidates, avg score=0.507
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.908, kelly=0.099) with $2586.23
Raw prediction for AAPL: 0.49682605266571045
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5370981693267822
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.12000666558742523
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5465099215507507
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.4045296013355255
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5134130716323853
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.9171434044837952
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4633648991584778
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6182485818862915
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.471919447183609
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.480787992477417
Calibrated prediction for BBL: 0.4324324429035187
Raw prediction for BCH: 0.4725773334503174
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4898969829082489
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5187324285507202
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4875393509864807
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48559561371803284
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.5067871809005737
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.5169163346290588
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4667297303676605
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4522826671600342
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.4488893449306488
Calibrated prediction for CHL: 0.3819020390510559
Raw prediction for CHTR: 0.49985626339912415
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.46653494238853455
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.46694856882095337
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5128213763237
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4931286871433258
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.512610912322998
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.529902994632721
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4920682907104492
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.44688522815704346
Calibrated prediction for DUK: 0.41673335433006287
Raw prediction for EXC: 0.5038425922393799
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5176265239715576
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5314693450927734
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4057745337486267
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.688022255897522
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6105819344520569
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4904252290725708
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5893375277519226
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.30597221851348877
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4414503872394562
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6535454988479614
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36080822348594666
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5337040424346924
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46991539001464844
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4400494396686554
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.5158898234367371
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5299327969551086
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4877249598503113
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5609990954399109
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.634563684463501
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.4680542051792145
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5751701593399048
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5038139820098877
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5016993880271912
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4216953217983246
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.42110657691955566
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5229741334915161
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.7134058475494385
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47668665647506714
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46541497111320496
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43552613258361816
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4816889762878418
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5193241238594055
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4822443723678589
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.45893794298171997
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.49186038970947266
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.5504791736602783
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5397393703460693
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5063579678535461
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.504002571105957
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5012694001197815
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.352772980928421
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.47018352150917053
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6267148852348328
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.46169450879096985
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.47154346108436584
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5262520909309387
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45264455676078796
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3295283615589142
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.45798513293266296
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4897981286048889
Calibrated prediction for UPS: 0.4941723644733429

Simulating Trading Days:  89%|████████▉ | 89/100 [06:01<00:13,  1.25s/it]

Raw prediction for UTX: 0.11663909256458282
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5796225070953369
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4850442707538605
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.503332257270813
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.44689980149269104
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5066622495651245
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.500
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.976, kelly=0.185) with $4808.13
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.943, kelly=0.166) with $4305.88
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.495
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.950, kelly=0.338) with $8785.90
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4570.48
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.010, kelly=0.010) with $252.08
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.454
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.002, kelly=0.143) with $3724.58
[PORT] Sector Services: 10 candidates, avg score=0.562
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.051, kelly=0.744) with $19332.51
[PORT] Sector Technology: 10 candidates, avg score=0.535
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.043, kelly=0.384) with $9992.91
[PORT] Sector Utilities: 10 candidates, avg score=0.507
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.908, kelly=0.099) with $2581.14
Raw prediction for AAPL: 0.4965288043022156
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5372920632362366
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.12759095430374146
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5497795343399048
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.40587154030799866
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5134745240211487
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.9052082300186157
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46504297852516174
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6178413033485413
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4735201299190521
Calibrated prediction for BAC: 0.4565824270248413
Raw prediction for BBL: 0.48466697335243225
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4657589793205261
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4899178147315979
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4899393320083618
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4870334565639496
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4858907163143158
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4992132782936096
Calibrated prediction for BUD: 0.6194642186164856
Raw prediction for C: 0.516974687576294
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4666183888912201
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4587983191013336
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.43383654952049255
Calibrated prediction for CHL: 0.35087719559669495
Raw prediction for CHTR: 0.5036534667015076
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.44456031918525696
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.45847564935684204
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5117684602737427
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4928675591945648
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5126821994781494
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5281181931495667
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4923587739467621
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.4549413025379181
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5042303204536438
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5176411867141724
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.531504213809967
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.40534067153930664
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6750882267951965
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6162429451942444
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4934200644493103
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5874812006950378
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.30128851532936096
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4491780698299408
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6426432132720947
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36546948552131653
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5342884063720703
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4699186384677887
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.42014649510383606
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.4897148609161377
Calibrated prediction for MA: 0.5522388219833374
Raw prediction for MCD: 0.5299738049507141
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4846555292606354
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5592764616012573
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6296300888061523
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46820154786109924
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5677393674850464
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5030212998390198
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5023001432418823
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4230256974697113
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.42492154240608215
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5229854583740234
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.7102023363113403
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4763879179954529
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4654353857040405
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4353939890861511
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.48174795508384705
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5119903087615967
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.48872727155685425
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.47547298669815063
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.48594939708709717
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.544047474861145
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5462247133255005
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5063025951385498
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5038827657699585
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5015416741371155
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.34697195887565613
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.48874056339263916
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6315029263496399
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.46067753434181213
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.463792622089386
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.5204322934150696
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4529217779636383
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34007084369659424
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.46892738342285156
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48930802941322327
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.11501847952604294
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5784973502159119
Calibrated prediction for V: 0.5811987519264221

Simulating Trading Days:  90%|█████████ | 90/100 [06:03<00:12,  1.24s/it]

Raw prediction for VZ: 0.49529924988746643
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5035709142684937
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4399934411048889
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5070425868034363
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.512
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.974, kelly=0.184) with $4763.72
[PORT] Sector Conglomerates: 7 candidates, avg score=0.466
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.942, kelly=0.165) with $4266.95
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.495
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.949, kelly=0.338) with $8726.73
[PORT] Sector Financial: 10 candidates, avg score=0.493
[PORT] Sector Financial: selecting V (p=0.581, b=1.033, kelly=0.176) with $4540.12
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.010, kelly=0.010) with $256.73
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.454
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=1.001, kelly=0.143) with $3693.62
[PORT] Sector Services: 10 candidates, avg score=0.545
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.053, kelly=0.744) with $19234.59
[PORT] Sector Technology: 10 candidates, avg score=0.532
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.042, kelly=0.384) with $9931.46
[PORT] Sector Utilities: 10 candidates, avg score=0.512
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.908, kelly=0.099) with $2564.40
Raw prediction for AAPL: 0.4963964819908142
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5351296067237854
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.134617879986763
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5512616038322449
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.40751364827156067
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5131343603134155
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8884673118591309
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46594467759132385
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6158512830734253
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4749901294708252
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.48794910311698914
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4605717957019806
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.49005764722824097
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4776891767978668
Calibrated prediction for BP: 0.4615384638309479
Raw prediction for BRK-A: 0.4869250953197479
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48643434047698975
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48850733041763306
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.517068088054657
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4664066433906555
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4633966386318207
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.4256480932235718
Calibrated prediction for CHL: 0.35087719559669495
Raw prediction for CHTR: 0.502852737903595
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.4255424737930298
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.45415282249450684
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5077186226844788
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49267664551734924
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.512847363948822
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5265026092529297
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49275916814804077
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.46589505672454834
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5043565630912781
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5176727175712585
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5315109491348267
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4056608974933624
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6522352695465088
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6177647709846497
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4942881762981415
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.586715579032898
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.29829007387161255
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4636389911174774
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6315955519676208
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36989104747772217
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.534894585609436
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4697461426258087
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.40932685136795044
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.46532803773880005
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5296330451965332
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.47949522733688354
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5584079027175903
Calibrated prediction for MMM: 0.5454545617103577
Raw prediction for MO: 0.624755859375
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46820777654647827
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5566705465316772
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5002162456512451
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5028958320617676
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.42145541310310364
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.4244288206100464
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5230123996734619
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.7027407288551331
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4759300649166107
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46540629863739014
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4353557229042053
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.482014000415802
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5058304667472839
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4942447245121002
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4939171075820923
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.4890407621860504
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.537874698638916
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5490134358406067
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5080950260162354
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.503734290599823
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5018451809883118
Calibrated prediction for SO: 0.49570509791374207

Simulating Trading Days:  91%|█████████ | 91/100 [06:04<00:11,  1.23s/it]

Raw prediction for SPLP: 0.3409756124019623
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5010702610015869
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.637803852558136
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4672318696975708
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4590302109718323
Calibrated prediction for TOT: 0.5974025726318359
Raw prediction for TSM: 0.516616940498352
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45264875888824463
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34361666440963745
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4760177731513977
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4886392056941986
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.10818904638290405
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5765509009361267
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5039489269256592
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5040649771690369
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4346708655357361
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5052129626274109
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.500
[PORT] Sector Basic Matierials: selecting TOT (p=0.597, b=0.975, kelly=0.184) with $4764.21
[PORT] Sector Conglomerates: 7 candidates, avg score=0.453
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.942, kelly=0.165) with $4269.68
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.483
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.946, kelly=0.336) with $8691.55
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.581, b=1.032, kelly=0.175) with $4530.51
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.011, kelly=0.010) with $265.41
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.452
[PORT] Sector Industrial Goods: selecting MMM (p=0.545, b=0.999, kelly=0.090) with $2335.81
[PORT] Sector Services: 10 candidates, avg score=0.545
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.051, kelly=0.744) with $19218.73
[PORT] Sector Technology: 10 candidates, avg score=0.532
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.040, kelly=0.384) with $9910.28
[PORT] Sector Utilities: 10 candidates, avg score=0.512
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.910, kelly=0.100) with $2593.21
Raw prediction for AAPL: 0.4962691366672516
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5309725403785706
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.14295466244220734
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5541542172431946
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.4092455506324768
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5129638314247131
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.880505383014679
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4672188460826874
Calibrated prediction for BA: 0.46022137999534607
Raw prediction for BABA: 0.6102532148361206
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4768073558807373
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4928620159626007
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4591125547885895
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4899827241897583
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4839949309825897
Calibrated prediction for BP: 0.5042733550071716
Raw prediction for BRK-A: 0.4869840443134308
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4867412745952606
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.48144030570983887
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5171088576316833
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4661867916584015
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4690394997596741
Calibrated prediction for CELG: 0.3943580389022827
Raw prediction for CHL: 0.43115878105163574
Calibrated prediction for CHL: 0.35087719559669495
Raw prediction for CHTR: 0.5217913389205933
Calibrated prediction for CHTR: 0.5370370149612427
Raw prediction for CMCSA: 0.4221149682998657
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4514906704425812
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5041788816452026
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.493495374917984
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5129237174987793
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5254161357879639
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49320998787879944
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.48017415404319763
Calibrated prediction for DUK: 0.46875
Raw prediction for EXC: 0.5049240589141846
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.518142819404602
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.531392514705658
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4049588739871979
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6406693458557129
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6151852011680603
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.4988619387149811
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5851360559463501
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.2989983856678009
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.4773274064064026
Calibrated prediction for IEP: 0.4444444477558136
Raw prediction for INTC: 0.6218541264533997
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3704286813735962
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5357235074043274
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4696992039680481
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.39914003014564514
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.45348384976387024
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5294907689094543
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4755745530128479
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.558057427406311
Calibrated prediction for MMM: 0.5454545617103577
Raw prediction for MO: 0.6230470538139343
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46858149766921997
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5482612252235413
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5001087784767151
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.504766583442688
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4218791127204895
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.4264615476131439
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5229069590568542
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.7165071964263916
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47560080885887146
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4658125638961792
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4354032576084137
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.48250484466552734
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.49959465861320496
Calibrated prediction for PM: 0.4682052731513977
Raw prediction for PPL: 0.4999504089355469
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5133694410324097
Calibrated prediction for PTR: 0.5
Raw prediction for RDS-B: 0.49643218517303467
Calibrated prediction for RDS-B: 0.5
Raw prediction for REX: 0.525456428527832
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.551630973815918
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5116525888442993
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5039466619491577
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5020439028739929
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.34019458293914795
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5212224721908569
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6471197605133057
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.48892754316329956
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4332897663116455
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5313109159469604
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45198947191238403
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34460777044296265
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.48640790581703186
Calibrated prediction for UNH: 0.380952388048172

Simulating Trading Days:  92%|█████████▏| 92/100 [06:05<00:09,  1.22s/it]

Raw prediction for UPS: 0.48817136883735657
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.1170295923948288
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5775158405303955
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5155290961265564
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.5047919154167175
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.4293631911277771
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5070203542709351
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.500
[PORT] Sector Basic Matierials: selecting BBL (p=0.550, b=0.967, kelly=0.085) with $2186.75
[PORT] Sector Conglomerates: 7 candidates, avg score=0.453
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.941, kelly=0.165) with $4251.02
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.479
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.945, kelly=0.336) with $8675.49
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.581, b=1.031, kelly=0.175) with $4510.82
[PORT] Sector Healthcare: 10 candidates, avg score=0.407
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.009, kelly=0.009) with $241.98
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.452
[PORT] Sector Industrial Goods: selecting MMM (p=0.545, b=0.998, kelly=0.090) with $2323.90
[PORT] Sector Services: 10 candidates, avg score=0.545
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.053, kelly=0.744) with $19201.68
[PORT] Sector Technology: 10 candidates, avg score=0.534
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.043, kelly=0.384) with $9916.01
[PORT] Sector Utilities: 10 candidates, avg score=0.512
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.908, kelly=0.100) with $2571.81
Raw prediction for AAPL: 0.4959567189216614
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5263622999191284
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.146498441696167
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5552173256874084
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.41120436787605286
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5130533576011658
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8726131319999695
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4683035910129547
Calibrated prediction for BA: 0.4796385169029236
Raw prediction for BABA: 0.6084391474723816
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4787410497665405
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4969421327114105
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.45427024364471436
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48986688256263733
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.4967062175273895
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.48696431517601013
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48662978410720825
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.47701355814933777
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.517108142375946
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.466176837682724
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.47471192479133606
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.4378332197666168
Calibrated prediction for CHL: 0.35087719559669495
Raw prediction for CHTR: 0.5386928915977478
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.4296620190143585
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.4483436346054077
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5023400187492371
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.4950648248195648
Calibrated prediction for CVX: 0.4869210720062256
Raw prediction for D: 0.5129877328872681
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5249170064926147
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4937944710254669
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.49649283289909363
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5049225091934204
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5184114575386047
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5313463807106018
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.40706104040145874
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6344504952430725
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.6078677773475647
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.502673864364624
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5824273228645325
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.29926416277885437
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.490740031003952
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.6124910116195679
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3667278587818146
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5366162657737732
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.46978843212127686
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.3921794295310974
Calibrated prediction for LMT: 0.375
Raw prediction for MA: 0.4459940791130066
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.529370129108429
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.47445976734161377
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5594151616096497
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6202280521392822
Calibrated prediction for MO: 0.6774193644523621
Raw prediction for MRK: 0.46908196806907654
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5396535396575928
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5023986101150513
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5071616768836975
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.42308416962623596
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.428174763917923
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5228338241577148
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.7154660224914551
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4755988121032715
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46644580364227295
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4352369010448456
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4814794361591339
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5013465285301208
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.502685010433197
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5276841521263123
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5059487223625183
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5136946439743042
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5547392964363098
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5151383876800537
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5041944980621338
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5022715330123901
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.3467577397823334
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5279666781425476
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6569623947143555
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5124165415763855
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4128248691558838
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5382137894630432
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45151570439338684
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34474700689315796
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4960291087627411
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4881209135055542
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.1333485096693039
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5793124437332153
Calibrated prediction for V: 0.5811987519264221

Simulating Trading Days:  93%|█████████▎| 93/100 [06:06<00:08,  1.22s/it]

Raw prediction for VZ: 0.5268551707267761
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.50535649061203
Calibrated prediction for WFC: 0.5066666603088379
Raw prediction for WMT: 0.43045905232429504
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5100585222244263
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.509
[PORT] Sector Basic Matierials: selecting BBL (p=0.550, b=0.967, kelly=0.084) with $2189.77
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.943, kelly=0.165) with $4288.91
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.482
[PORT] Sector Consumer Goods: selecting MO (p=0.677, b=0.946, kelly=0.337) with $8723.61
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.581, b=1.030, kelly=0.175) with $4525.48
[PORT] Sector Healthcare: 10 candidates, avg score=0.415
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.007, kelly=0.008) with $215.12
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.452
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.998, kelly=0.141) with $3665.59
[PORT] Sector Services: 10 candidates, avg score=0.547
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19291.96
[PORT] Sector Technology: 10 candidates, avg score=0.534
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.044, kelly=0.385) with $9970.34
[PORT] Sector Utilities: 10 candidates, avg score=0.519
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.908, kelly=0.100) with $2580.61
Raw prediction for AAPL: 0.49542954564094543
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5227279663085938
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.14427092671394348
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5516452193260193
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.41296395659446716
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5133660435676575
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8608465790748596
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4692825675010681
Calibrated prediction for BA: 0.49778974056243896
Raw prediction for BABA: 0.6092485189437866
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4809851050376892
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4977521002292633
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4510318636894226
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4898317754268646
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5128704905509949
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4870154857635498
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4865732192993164
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.47194430232048035
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5170397758483887
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46629148721694946
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.48163196444511414
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.44065824151039124
Calibrated prediction for CHL: 0.35087719559669495
Raw prediction for CHTR: 0.5479129552841187
Calibrated prediction for CHTR: 0.550000011920929
Raw prediction for CMCSA: 0.44617322087287903
Calibrated prediction for CMCSA: 0.37434905767440796
Raw prediction for CODI: 0.44209808111190796
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5037457346916199
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49667662382125854
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5131109356880188
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5240216851234436
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.49442848563194275
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.514245867729187
Calibrated prediction for DUK: 0.5357142686843872
Raw prediction for EXC: 0.5047978758811951
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5185607671737671
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5314452648162842
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4110681116580963
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6379247903823853
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.5982193350791931
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5055243372917175
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5795453190803528
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.29999423027038574
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.5021932125091553
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.6085442304611206
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3635435104370117
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5376259088516235
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47003939747810364
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.3894767463207245
Calibrated prediction for LMT: 0.375
Raw prediction for MA: 0.44244423508644104
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5293459296226501
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4776684045791626
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5614241361618042
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6116304397583008
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4694541096687317
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5342568755149841
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5056524276733398
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5094085931777954
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4243537485599518
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.42984071373939514
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5226839780807495
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.7043787837028503
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4757991433143616
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46722206473350525
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.43494588136672974
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4789116084575653
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5081309080123901
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5042861104011536
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5367758870124817
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5160396695137024
Calibrated prediction for RDS-B: 0.517241358757019
Raw prediction for REX: 0.5057700872421265
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5558367371559143
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5161381959915161
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5043249726295471
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.502575159072876
Calibrated prediction for SO: 0.49570509791374207
Raw prediction for SPLP: 0.35838666558265686
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5376991033554077
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6615992188453674
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5178122520446777
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.3979395031929016
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5380566120147705
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4514033794403076
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3426121473312378
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.5021277070045471
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48832717537879944
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.15542511641979218
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5805660486221313
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5192996859550476
Calibrated prediction for VZ: 0.47826087474823
Raw prediction for WFC: 0.50574791431427
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.4336961507797241
Calibrated prediction for WMT: 0.44648152589797974

Simulating Trading Days:  94%|█████████▍| 94/100 [06:08<00:07,  1.21s/it]

Raw prediction for XOM: 0.5105115175247192
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.511
[PORT] Sector Basic Matierials: selecting BBL (p=0.550, b=0.966, kelly=0.084) with $2182.43
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.945, kelly=0.166) with $4308.75
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.468
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.947, kelly=0.055) with $1434.82
[PORT] Sector Financial: 10 candidates, avg score=0.484
[PORT] Sector Financial: selecting V (p=0.581, b=1.030, kelly=0.174) with $4516.11
[PORT] Sector Healthcare: 10 candidates, avg score=0.415
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.006, kelly=0.008) with $199.33
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.454
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.997, kelly=0.141) with $3651.76
[PORT] Sector Services: 10 candidates, avg score=0.547
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19262.65
[PORT] Sector Technology: 10 candidates, avg score=0.534
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.046, kelly=0.385) with $9971.94
[PORT] Sector Utilities: 10 candidates, avg score=0.527
[PORT] Sector Utilities: selecting AEP (p=0.571, b=0.907, kelly=0.099) with $2557.40
Raw prediction for AAPL: 0.49496811628341675
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.519697904586792
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.13779211044311523
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5480270385742188
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.4146150052547455
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5133539438247681
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8299269676208496
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4691517651081085
Calibrated prediction for BA: 0.49536454677581787
Raw prediction for BABA: 0.6084979772567749
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4825744926929474
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.49730050563812256
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.44842612743377686
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4896836578845978
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5274462699890137
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.48720863461494446
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4866798222064972
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.46855628490448
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5170098543167114
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46612784266471863
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.48477888107299805
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.44062304496765137
Calibrated prediction for CHL: 0.35087719559669495
Raw prediction for CHTR: 0.5537040829658508
Calibrated prediction for CHTR: 0.5833333134651184
Raw prediction for CMCSA: 0.4704655110836029
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4298573136329651
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5052212476730347
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49836215376853943
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5132165551185608
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5220290422439575
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4953165650367737
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5383236408233643
Calibrated prediction for DUK: 0.6000000238418579
Raw prediction for EXC: 0.504421055316925
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5187520980834961
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5317937731742859
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.41396385431289673
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6379508972167969
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.586061954498291
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5061641335487366
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5776844024658203
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3003181219100952
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.5135292410850525
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.6009119749069214
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36617448925971985
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5384275317192078
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4701988995075226
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4055497944355011
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.4354701638221741
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5293096899986267
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4851928651332855
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5631478428840637
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.6017588973045349
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46928682923316956
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5348999500274658
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.504869282245636
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5108304619789124
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.42316654324531555
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.4288172125816345
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5225241780281067
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.69039386510849
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4762222468852997
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.4673120975494385
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.43473294377326965
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.47716161608695984
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5144197940826416
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5060862302780151
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5385405421257019
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.524674117565155
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5083100199699402
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5565670728683472
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5109444856643677
Calibrated prediction for SNP: 0.533819854259491
Raw prediction for SNY: 0.5042300820350647
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5031830072402954
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.36694303154945374
Calibrated prediction for SPLP: 0.30125677585601807

Simulating Trading Days:  95%|█████████▌| 95/100 [06:09<00:06,  1.22s/it]

Raw prediction for SRE: 0.5438299775123596
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6595697999000549
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5198562741279602
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.39002588391304016
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5203140377998352
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45158320665359497
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.34042397141456604
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4984307885169983
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48842787742614746
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.15113405883312225
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5792688131332397
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.5009724497795105
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5059534311294556
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.43656641244888306
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5076703429222107
Calibrated prediction for XOM: 0.5334905385971069
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.519
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.902, kelly=0.157) with $4047.45
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.946, kelly=0.167) with $4315.19
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.468
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.948, kelly=0.056) with $1442.35
[PORT] Sector Financial: 10 candidates, avg score=0.484
[PORT] Sector Financial: selecting V (p=0.581, b=1.030, kelly=0.175) with $4510.95
[PORT] Sector Healthcare: 10 candidates, avg score=0.415
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.007, kelly=0.008) with $215.57
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.458
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.994, kelly=0.140) with $3619.00
[PORT] Sector Services: 10 candidates, avg score=0.566
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.056, kelly=0.744) with $19238.22
[PORT] Sector Technology: 10 candidates, avg score=0.532
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.044, kelly=0.385) with $9945.58
[PORT] Sector Utilities: 10 candidates, avg score=0.534
[PORT] Sector Utilities: selecting DUK (p=0.600, b=0.905, kelly=0.158) with $4083.97
Raw prediction for AAPL: 0.4948715269565582
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5165637135505676
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.14089733362197876
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.546008825302124
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.4165997803211212
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.513200044631958
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.8016182780265808
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46924540400505066
Calibrated prediction for BA: 0.49710068106651306
Raw prediction for BABA: 0.6085585355758667
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.48398879170417786
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.49723151326179504
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.44413015246391296
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48952144384384155
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5387930274009705
Calibrated prediction for BP: 0.5285714268684387
Raw prediction for BRK-A: 0.4873724579811096
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48671358823776245
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.46566343307495117
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.517139732837677
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46595147252082825
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4892163872718811
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.4402023255825043
Calibrated prediction for CHL: 0.35087719559669495
Raw prediction for CHTR: 0.581963062286377
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.48478561639785767
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.41774100065231323
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5065227150917053
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.49956169724464417
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5133075714111328
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5210742950439453
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4962101876735687
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5573087334632874
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5039868354797363
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5188913941383362
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5319180488586426
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.41361725330352783
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6322820782661438
Calibrated prediction for GOOG: 0.6857143044471741
Raw prediction for HD: 0.5730363726615906
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5085180401802063
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.5759596228599548
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.30122101306915283
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.5215901136398315
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5952939987182617
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.3663145899772644
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5388396382331848
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47048166394233704
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.43436887860298157
Calibrated prediction for LMT: 0.4137931168079376
Raw prediction for MA: 0.4334909915924072
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5293917655944824
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.4938521981239319
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5655593276023865
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.592823326587677
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46887391805648804
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5362560749053955
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5052778124809265
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5115870833396912
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.42524969577789307
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.42674392461776733
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5223975777626038
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6788249015808105
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.476664662361145
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46706724166870117
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.4346039891242981
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.47535109519958496
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5177815556526184
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.50694340467453
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5314726233482361
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5298517346382141
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5157393217086792
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5547692179679871
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.5013750195503235
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5042412877082825
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.503703236579895
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.3760620951652527
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5374021530151367
Calibrated prediction for SRE: 0.560606062412262
Raw prediction for T: 0.6456702351570129
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.5020502805709839
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.38700082898139954
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.5049722194671631
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.4510740041732788
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.33668252825737
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4930085837841034
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.48857101798057556
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.13983497023582458
Calibrated prediction for UTX: 0.1294490545988083

Simulating Trading Days:  96%|█████████▌| 96/100 [06:10<00:04,  1.21s/it]

Raw prediction for V: 0.5789413452148438
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4877294898033142
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5061222314834595
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.4386485517024994
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5039570927619934
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.513
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.904, kelly=0.157) with $4060.44
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.947, kelly=0.168) with $4322.33
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.468
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.950, kelly=0.057) with $1465.03
[PORT] Sector Financial: 10 candidates, avg score=0.484
[PORT] Sector Financial: selecting V (p=0.581, b=1.028, kelly=0.174) with $4481.42
[PORT] Sector Healthcare: 10 candidates, avg score=0.415
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.006, kelly=0.008) with $196.88
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.464
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.996, kelly=0.141) with $3629.19
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.057, kelly=0.745) with $19208.04
[PORT] Sector Technology: 10 candidates, avg score=0.532
[PORT] Sector Technology: selecting GOOG (p=0.686, b=1.045, kelly=0.385) with $9934.32
[PORT] Sector Utilities: 10 candidates, avg score=0.535
[PORT] Sector Utilities: selecting DUK (p=0.607, b=0.907, kelly=0.174) with $4488.46
Raw prediction for AAPL: 0.4948330521583557
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5129615068435669
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.14930185675621033
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5441399812698364
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.41865864396095276
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5128278136253357
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7749545574188232
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4690108597278595
Calibrated prediction for BA: 0.4927520155906677
Raw prediction for BABA: 0.6088993549346924
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4847785532474518
Calibrated prediction for BAC: 0.47561949491500854
Raw prediction for BBL: 0.4981616735458374
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4365432858467102
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48937511444091797
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.547033429145813
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.48742297291755676
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4867429733276367
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.46367746591567993
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5174580812454224
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4657773971557617
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.49255073070526123
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.4427012503147125
Calibrated prediction for CHL: 0.35087719559669495
Raw prediction for CHTR: 0.617757260799408
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.4916914403438568
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4174537658691406
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5069329142570496
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.5006789565086365
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5133532881736755
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5205525755882263
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4971567988395691
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5667167901992798
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5034118890762329
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.519071102142334
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5318591594696045
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4132259786128998
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6216159462928772
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5587025284767151
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5088068246841431
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.572935163974762
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.30307433009147644
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.5246198177337646
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5916260480880737
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36716651916503906
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5388980507850647
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47078731656074524
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.4601755440235138
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.43349489569664
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5294921398162842
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5037546157836914
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5655909776687622
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5839136242866516
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.46797555685043335
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5366122126579285
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5070827007293701
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5105875134468079
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.42482689023017883
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.42296144366264343
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5223349928855896
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6647242903709412
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47715988755226135
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46646976470947266
Calibrated prediction for PFE: 0.47012627124786377
Raw prediction for PG: 0.434589684009552
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4745543897151947
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5222399830818176
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.505635142326355
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.5172279477119446
Calibrated prediction for PTR: 0.5488210320472717
Raw prediction for RDS-B: 0.5345864295959473
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.524276614189148
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5521028637886047
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.49239808320999146
Calibrated prediction for SNP: 0.52173912525177
Raw prediction for SNY: 0.5040725469589233
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5041007399559021
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.38499724864959717
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.5148885846138
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6336850523948669
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4785774052143097
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.392844021320343
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4867619276046753
Calibrated prediction for TSM: 0.5510203838348389
Raw prediction for UL: 0.45038098096847534
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.33472126722335815
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.48492416739463806
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4887336194515228
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.13517162203788757
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5803155303001404
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4793303906917572
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5062562227249146
Calibrated prediction for WFC: 0.5121996402740479

Simulating Trading Days:  97%|█████████▋| 97/100 [06:11<00:03,  1.21s/it]

Raw prediction for WMT: 0.4388362765312195
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.5015402436256409
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.519
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.904, kelly=0.157) with $4058.93
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.947, kelly=0.167) with $4319.26
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.468
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.950, kelly=0.057) with $1465.92
[PORT] Sector Financial: 10 candidates, avg score=0.485
[PORT] Sector Financial: selecting V (p=0.581, b=1.026, kelly=0.173) with $4461.92
[PORT] Sector Healthcare: 10 candidates, avg score=0.415
[PORT] Sector Healthcare: selecting SNY (p=0.502, b=1.005, kelly=0.007) with $183.26
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.472
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.994, kelly=0.140) with $3605.71
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.058, kelly=0.745) with $19210.31
[PORT] Sector Technology: 10 candidates, avg score=0.527
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.970, kelly=0.300) with $7736.48
[PORT] Sector Utilities: 10 candidates, avg score=0.531
[PORT] Sector Utilities: selecting DUK (p=0.607, b=0.906, kelly=0.174) with $4481.64
Raw prediction for AAPL: 0.4946554899215698
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5093144774436951
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.16053488850593567
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.542641818523407
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.4211691617965698
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5123753547668457
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7685543894767761
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46887317299842834
Calibrated prediction for BA: 0.49019914865493774
Raw prediction for BABA: 0.6128236055374146
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.4847937822341919
Calibrated prediction for BAC: 0.4772410988807678
Raw prediction for BBL: 0.4988820552825928
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4255061149597168
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4894026517868042
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5490347743034363
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.48743125796318054
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.48673567175865173
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.46065354347229004
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5177494883537292
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4656608998775482
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.49618834257125854
Calibrated prediction for CELG: 0.5454545617103577
Raw prediction for CHL: 0.4460436999797821
Calibrated prediction for CHL: 0.3619578182697296
Raw prediction for CHTR: 0.6477130651473999
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5001434683799744
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4122602939605713
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5067319869995117
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.5015093684196472
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5134997367858887
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.520420491695404
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4980018436908722
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5671038031578064
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5026745200157166
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5193131566047668
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5318102836608887
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.41268104314804077
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6140236854553223
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5457799434661865
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5084003210067749
Calibrated prediction for HON: 0.5555555820465088
Raw prediction for HRG: 0.5682255029678345
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3043607473373413
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.5241492986679077
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5907378196716309
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36493661999702454
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5387611985206604
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47096604108810425
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.47766557335853577
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.4333544373512268
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5296761393547058
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5117298364639282
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5665497183799744
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.575604259967804
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4669768214225769
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5378077626228333
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5100374817848206
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5085476636886597
Calibrated prediction for NGG: 0.5157455205917358
Raw prediction for NVS: 0.4221217632293701
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.4185979664325714
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5223718881607056
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6559923887252808
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47763365507125854
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46585291624069214
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4345952570438385
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4735838770866394
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5263957381248474
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.5009341239929199
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4970088005065918
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5356795787811279
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5341240763664246
Calibrated prediction for REX: 0.4385964870452881
Raw prediction for SLB: 0.5458202362060547
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.48396679759025574
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5039855241775513
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5043610334396362
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.39149072766304016
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.49013054370880127
Calibrated prediction for SRE: 0.5277777910232544

Simulating Trading Days:  98%|█████████▊| 98/100 [06:12<00:02,  1.21s/it]

Raw prediction for T: 0.623069167137146
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.45729780197143555
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.39893603324890137
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.46416109800338745
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.4498245418071747
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3314586281776428
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4772287607192993
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4890977740287781
Calibrated prediction for UPS: 0.4941723644733429
Raw prediction for UTX: 0.1416809856891632
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5809202790260315
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.47692298889160156
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5063864588737488
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.44107523560523987
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4986664056777954
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.498
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.905, kelly=0.158) with $4089.06
[PORT] Sector Conglomerates: 7 candidates, avg score=0.464
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.946, kelly=0.167) with $4319.65
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.468
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.952, kelly=0.058) with $1491.10
[PORT] Sector Financial: 10 candidates, avg score=0.485
[PORT] Sector Financial: selecting V (p=0.581, b=1.025, kelly=0.172) with $4457.69
[PORT] Sector Healthcare: 10 candidates, avg score=0.422
[PORT] Sector Healthcare: selecting CELG (p=0.545, b=1.012, kelly=0.096) with $2486.97
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.472
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.992, kelly=0.139) with $3594.31
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.056, kelly=0.744) with $19238.36
[PORT] Sector Technology: 10 candidates, avg score=0.515
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.973, kelly=0.301) with $7771.61
[PORT] Sector Utilities: 10 candidates, avg score=0.531
[PORT] Sector Utilities: selecting DUK (p=0.607, b=0.905, kelly=0.173) with $4473.01
Raw prediction for AAPL: 0.494503915309906
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.5059912204742432
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.16875165700912476
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5407839417457581
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.4237748980522156
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5115972757339478
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.766719400882721
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.46883538365364075
Calibrated prediction for BA: 0.489498496055603
Raw prediction for BABA: 0.6191685199737549
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.48458531498908997
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.5005406141281128
Calibrated prediction for BBL: 0.5555555820465088
Raw prediction for BCH: 0.4198755621910095
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.4892321228981018
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.5480808615684509
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.48746228218078613
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4867994487285614
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.4600653052330017
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5180194973945618
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.46559807658195496
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4965572655200958
Calibrated prediction for CELG: 0.5454545617103577
Raw prediction for CHL: 0.4500744342803955
Calibrated prediction for CHL: 0.3902079463005066
Raw prediction for CHTR: 0.6669544577598572
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5118313431739807
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.4104699194431305
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5047679543495178
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.5019263029098511
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5136218667030334
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.5197332501411438
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4989050328731537
Calibrated prediction for DIS: 0.4966834783554077
Raw prediction for DUK: 0.5600516200065613
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5021524429321289
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.5194090604782104
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.5318248867988586
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.411590576171875
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6126869916915894
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5337579846382141
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.5069335699081421
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5629638433456421
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3064064681529999
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.5202133655548096
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5899634957313538
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36833253502845764
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5385739803314209
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.47116348147392273
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.49328795075416565
Calibrated prediction for LMT: 0.5
Raw prediction for MA: 0.4374648928642273
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5298130512237549
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5170494318008423
Calibrated prediction for MDT: 0.45016416907310486
Raw prediction for MMM: 0.5673114061355591
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5684176087379456
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.4658886194229126
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5373101234436035
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5104508399963379
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5061711072921753
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4162011742591858
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.41365283727645874
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.522551953792572
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6473341584205627
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.4780682325363159
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46533694863319397
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.43472281098365784
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.47331589460372925
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5281229615211487
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.4951302111148834
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.4736364781856537
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.53387850522995
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5428513884544373
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.534591019153595
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.47985559701919556
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5038575530052185
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5044914484024048
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.38923442363739014
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.46728813648223877
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.6131767630577087
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4520428478717804
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.4005926847457886
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.4452182948589325
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.44925519824028015
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.32607120275497437
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4689927101135254
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.489488422870636
Calibrated prediction for UPS: 0.4941723644733429

Simulating Trading Days:  99%|█████████▉| 99/100 [06:14<00:01,  1.21s/it]

Raw prediction for UTX: 0.1426459103822708
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.581663191318512
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4760817587375641
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5064405202865601
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.4431719183921814
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4964812099933624
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.499
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.905, kelly=0.158) with $4100.86
[PORT] Sector Conglomerates: 7 candidates, avg score=0.476
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.945, kelly=0.166) with $4314.98
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.468
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.953, kelly=0.059) with $1519.88
[PORT] Sector Financial: 10 candidates, avg score=0.484
[PORT] Sector Financial: selecting V (p=0.581, b=1.027, kelly=0.173) with $4496.37
[PORT] Sector Healthcare: 10 candidates, avg score=0.422
[PORT] Sector Healthcare: selecting CELG (p=0.545, b=1.011, kelly=0.096) with $2479.65
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.466
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.991, kelly=0.138) with $3589.04
[PORT] Sector Services: 10 candidates, avg score=0.569
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19291.74
[PORT] Sector Technology: 10 candidates, avg score=0.517
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.971, kelly=0.300) with $7778.86
[PORT] Sector Utilities: 10 candidates, avg score=0.527
[PORT] Sector Utilities: selecting DUK (p=0.607, b=0.903, kelly=0.172) with $4465.19
Raw prediction for AAPL: 0.49445924162864685
Calibrated prediction for AAPL: 0.5003328323364258
Raw prediction for ABB: 0.504173994064331
Calibrated prediction for ABB: 0.5190532803535461
Raw prediction for ABBV: 0.1799265295267105
Calibrated prediction for ABBV: 0.2073269933462143
Raw prediction for AEP: 0.5399936437606812
Calibrated prediction for AEP: 0.5714285969734192
Raw prediction for AGFS: 0.426298588514328
Calibrated prediction for AGFS: 0.4981705844402313
Raw prediction for AMGN: 0.5107031464576721
Calibrated prediction for AMGN: 0.5018361806869507
Raw prediction for AMZN: 0.7567131519317627
Calibrated prediction for AMZN: 0.8687135577201843
Raw prediction for BA: 0.4680801331996918
Calibrated prediction for BA: 0.4754953980445862
Raw prediction for BABA: 0.6252604722976685
Calibrated prediction for BABA: 0.5115155577659607
Raw prediction for BAC: 0.48413342237472534
Calibrated prediction for BAC: 0.46341463923454285
Raw prediction for BBL: 0.4963597059249878
Calibrated prediction for BBL: 0.550000011920929
Raw prediction for BCH: 0.4171285033226013
Calibrated prediction for BCH: 0.4463878273963928
Raw prediction for BHP: 0.48893362283706665
Calibrated prediction for BHP: 0.4940555691719055
Raw prediction for BP: 0.544179379940033
Calibrated prediction for BP: 0.5833333134651184
Raw prediction for BRK-A: 0.48743918538093567
Calibrated prediction for BRK-A: 0.48786410689353943
Raw prediction for BSAC: 0.4868224561214447
Calibrated prediction for BSAC: 0.4857579469680786
Raw prediction for BUD: 0.45638954639434814
Calibrated prediction for BUD: 0.4864864945411682
Raw prediction for C: 0.5181383490562439
Calibrated prediction for C: 0.5174347162246704
Raw prediction for CAT: 0.4655664563179016
Calibrated prediction for CAT: 0.4743160307407379
Raw prediction for CELG: 0.4912841320037842
Calibrated prediction for CELG: 0.4583333432674408
Raw prediction for CHL: 0.46976569294929504
Calibrated prediction for CHL: 0.41025641560554504
Raw prediction for CHTR: 0.6782031059265137
Calibrated prediction for CHTR: 0.6152653098106384
Raw prediction for CMCSA: 0.5235419273376465
Calibrated prediction for CMCSA: 0.5357142686843872
Raw prediction for CODI: 0.41467738151550293
Calibrated prediction for CODI: 0.4264705777168274
Raw prediction for CSCO: 0.5022661089897156
Calibrated prediction for CSCO: 0.5075896382331848
Raw prediction for CVX: 0.5020568370819092
Calibrated prediction for CVX: 0.5061141848564148
Raw prediction for D: 0.5136844515800476
Calibrated prediction for D: 0.5089935064315796
Raw prediction for DHR: 0.519252598285675
Calibrated prediction for DHR: 0.5135536789894104
Raw prediction for DIS: 0.4998761713504791
Calibrated prediction for DIS: 0.5126088261604309
Raw prediction for DUK: 0.5464419722557068
Calibrated prediction for DUK: 0.6071428656578064
Raw prediction for EXC: 0.5018371343612671
Calibrated prediction for EXC: 0.4991118609905243
Raw prediction for FB: 0.519655168056488
Calibrated prediction for FB: 0.5171394944190979
Raw prediction for GD: 0.532072126865387
Calibrated prediction for GD: 0.5348551273345947
Raw prediction for GE: 0.4120611846446991
Calibrated prediction for GE: 0.43333280086517334
Raw prediction for GOOG: 0.6126838326454163
Calibrated prediction for GOOG: 0.6304348111152649
Raw prediction for HD: 0.5234248042106628
Calibrated prediction for HD: 0.5322580933570862
Raw prediction for HON: 0.502918004989624
Calibrated prediction for HON: 0.4939759075641632
Raw prediction for HRG: 0.5563566088676453
Calibrated prediction for HRG: 0.5950413346290588
Raw prediction for HSBC: 0.3073432743549347
Calibrated prediction for HSBC: 0.3523077368736267
Raw prediction for IEP: 0.5131124258041382
Calibrated prediction for IEP: 0.5166666507720947
Raw prediction for INTC: 0.5912531614303589
Calibrated prediction for INTC: 0.6552039980888367
Raw prediction for JNJ: 0.36964842677116394
Calibrated prediction for JNJ: 0.29589736461639404
Raw prediction for JPM: 0.5385869145393372
Calibrated prediction for JPM: 0.5430880188941956
Raw prediction for KO: 0.4712698459625244
Calibrated prediction for KO: 0.4670509696006775
Raw prediction for LMT: 0.5214037895202637
Calibrated prediction for LMT: 0.5357142686843872
Raw prediction for MA: 0.43852657079696655
Calibrated prediction for MA: 0.44736841320991516
Raw prediction for MCD: 0.5299262404441833
Calibrated prediction for MCD: 0.5366811752319336
Raw prediction for MDT: 0.5182211399078369
Calibrated prediction for MDT: 0.5439614653587341
Raw prediction for MMM: 0.5689419507980347
Calibrated prediction for MMM: 0.5712277889251709
Raw prediction for MO: 0.5600534081459045
Calibrated prediction for MO: 0.5405405163764954
Raw prediction for MRK: 0.465143084526062
Calibrated prediction for MRK: 0.47309410572052
Raw prediction for MSFT: 0.5370740294456482
Calibrated prediction for MSFT: 0.5423728823661804
Raw prediction for NEE: 0.5086323022842407
Calibrated prediction for NEE: 0.5256089568138123
Raw prediction for NGG: 0.5048314929008484
Calibrated prediction for NGG: 0.47023436427116394
Raw prediction for NVS: 0.4108670949935913
Calibrated prediction for NVS: 0.40667352080345154
Raw prediction for ORCL: 0.41068413853645325
Calibrated prediction for ORCL: 0.41410520672798157
Raw prediction for PCG: 0.5226568579673767
Calibrated prediction for PCG: 0.5231530666351318
Raw prediction for PCLN: 0.6389254331588745
Calibrated prediction for PCLN: 0.6569333076477051
Raw prediction for PEP: 0.47841182351112366
Calibrated prediction for PEP: 0.4763396978378296
Raw prediction for PFE: 0.46484801173210144
Calibrated prediction for PFE: 0.4598912000656128
Raw prediction for PG: 0.4348281919956207
Calibrated prediction for PG: 0.4354880154132843
Raw prediction for PICO: 0.4734167754650116
Calibrated prediction for PICO: 0.46890994906425476
Raw prediction for PM: 0.5253493189811707
Calibrated prediction for PM: 0.4938271641731262
Raw prediction for PPL: 0.48997458815574646
Calibrated prediction for PPL: 0.5303030014038086
Raw prediction for PTR: 0.44895339012145996
Calibrated prediction for PTR: 0.3970588147640228
Raw prediction for RDS-B: 0.5300827026367188
Calibrated prediction for RDS-B: 0.6000000238418579
Raw prediction for REX: 0.5484645962715149
Calibrated prediction for REX: 0.5263158082962036
Raw prediction for SLB: 0.5175930857658386
Calibrated prediction for SLB: 0.4974823594093323
Raw prediction for SNP: 0.47898876667022705
Calibrated prediction for SNP: 0.47175800800323486
Raw prediction for SNY: 0.5037842988967896
Calibrated prediction for SNY: 0.5023937821388245
Raw prediction for SO: 0.5044636130332947
Calibrated prediction for SO: 0.5042282938957214
Raw prediction for SPLP: 0.37868115305900574
Calibrated prediction for SPLP: 0.30125677585601807
Raw prediction for SRE: 0.44853705167770386
Calibrated prediction for SRE: 0.5277777910232544
Raw prediction for T: 0.609941840171814
Calibrated prediction for T: 0.6420084834098816
Raw prediction for TM: 0.4498903751373291
Calibrated prediction for TM: 0.4000000059604645
Raw prediction for TOT: 0.39989835023880005
Calibrated prediction for TOT: 0.4000000059604645
Raw prediction for TSM: 0.43780508637428284
Calibrated prediction for TSM: 0.41800421476364136
Raw prediction for UL: 0.448428750038147
Calibrated prediction for UL: 0.45108622312545776
Raw prediction for UN: 0.3153018057346344
Calibrated prediction for UN: 0.4285714328289032
Raw prediction for UNH: 0.4584430456161499
Calibrated prediction for UNH: 0.380952388048172
Raw prediction for UPS: 0.4896782636642456
Calibrated prediction for UPS: 0.4941723644733429

Simulating Trading Days: 100%|██████████| 100/100 [06:15<00:00,  3.75s/it]

Raw prediction for UTX: 0.1348031908273697
Calibrated prediction for UTX: 0.1294490545988083
Raw prediction for V: 0.5822960734367371
Calibrated prediction for V: 0.5811987519264221
Raw prediction for VZ: 0.4815468490123749
Calibrated prediction for VZ: 0.45679011940956116
Raw prediction for WFC: 0.5063579678535461
Calibrated prediction for WFC: 0.5121996402740479
Raw prediction for WMT: 0.44492945075035095
Calibrated prediction for WMT: 0.44648152589797974
Raw prediction for XOM: 0.4935053586959839
Calibrated prediction for XOM: 0.4838709533214569
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.498
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.600, b=0.907, kelly=0.159) with $4126.81
[PORT] Sector Conglomerates: 7 candidates, avg score=0.476
[PORT] Sector Conglomerates: selecting HRG (p=0.595, b=0.947, kelly=0.167) with $4352.36
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.468
[PORT] Sector Consumer Goods: selecting MO (p=0.541, b=0.952, kelly=0.058) with $1511.83
[PORT] Sector Financial: 10 candidates, avg score=0.484
[PORT] Sector Financial: selecting V (p=0.581, b=1.030, kelly=0.174) with $4534.31
[PORT] Sector Healthcare: 10 candidates, avg score=0.423
[PORT] Sector Healthcare: selecting MDT (p=0.544, b=1.023, kelly=0.098) with $2552.71
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.468
[PORT] Sector Industrial Goods: selecting MMM (p=0.571, b=0.990, kelly=0.138) with $3589.13
[PORT] Sector Services: 10 candidates, avg score=0.571
[PORT] Sector Services: selecting AMZN (p=0.869, b=1.055, kelly=0.744) with $19348.57
[PORT] Sector Technology: 10 candidates, avg score=0.519
[PORT] Sector Technology: selecting INTC (p=0.655, b=0.970, kelly=0.300) with $7790.86
[PORT] Sector Utilities: 10 candidates, avg score=0.527
[PORT] Sector Utilities: selecting DUK (p=0.607, b=0.905, kelly=0.173) with $4497.77

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'HRG', 'investment_fraction': 0.07..."
1,2017-04-12,99927.229902,69949.060931,99927.229902,99927.229902,-72.770098,-0.000728,"[{'ticker': 'HRG', 'investment_fraction': 0.07..."
2,2017-04-13,99845.063255,69891.544279,99845.063255,99845.063255,-82.166647,-0.000822,"[{'ticker': 'HRG', 'investment_fraction': 0.07..."
3,2017-04-17,100207.097760,70144.968432,100207.097760,100207.097760,362.034505,0.003626,"[{'ticker': 'HRG', 'investment_fraction': 0.07..."
4,2017-04-18,100183.518926,70128.463248,100183.518926,100183.518926,-23.578834,-0.000235,"[{'ticker': 'MA', 'investment_fraction': 0.086..."
...,...,...,...,...,...,...,...,...
95,2017-08-25,103198.925408,72239.247785,103198.925408,103198.925408,-183.922672,-0.001779,"[{'ticker': 'AMZN', 'investment_fraction': 0.1..."
96,2017-08-28,103195.766194,72237.036336,103195.766194,103195.766194,-3.159213,-0.000031,"[{'ticker': 'AMZN', 'investment_fraction': 0.1..."
97,2017-08-29,103380.562711,72366.393898,103380.562711,103380.562711,184.796517,0.001791,"[{'ticker': 'AMZN', 'investment_fraction': 0.1..."
98,2017-08-30,103679.127580,72575.389306,103679.127580,103679.127580,298.564869,0.002888,"[{'ticker': 'AMZN', 'investment_fraction': 0.1..."
99,2017-08-31,103979.575311,103979.575311,103979.575311,103979.575311,300.447731,0.002898,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'HRG', 'investment_fraction': 0.07..."
1,2017-04-12,99927.229902,69949.060931,99927.229902,99927.229902,-72.770098,-0.000728,"[{'ticker': 'HRG', 'investment_fraction': 0.07..."
2,2017-04-13,99845.063255,69891.544279,99845.063255,99845.063255,-82.166647,-0.000822,"[{'ticker': 'HRG', 'investment_fraction': 0.07..."
3,2017-04-17,100207.097760,70144.968432,100207.097760,100207.097760,362.034505,0.003626,"[{'ticker': 'HRG', 'investment_fraction': 0.07..."
4,2017-04-18,100183.518926,70128.463248,100183.518926,100183.518926,-23.578834,-0.000235,"[{'ticker': 'MA', 'investment_fraction': 0.086..."
...,...,...,...,...,...,...,...,...
95,2017-08-25,103198.925408,72239.247785,103198.925408,103198.925408,-183.922672,-0.001779,"[{'ticker': 'AMZN', 'investment_fraction': 0.1..."
96,2017-08-28,103195.766194,72237.036336,103195.766194,103195.766194,-3.159213,-0.000031,"[{'ticker': 'AMZN', 'investment_fraction': 0.1..."
97,2017-08-29,103380.562711,72366.393898,103380.562711,103380.562711,184.796517,0.001791,"[{'ticker': 'AMZN', 'investment_fraction': 0.1..."
98,2017-08-30,103679.127580,72575.389306,103679.127580,103679.127580,298.564869,0.002888,"[{'ticker': 'AMZN', 'investment_fraction': 0.1..."
99,2017-08-31,103979.575311,103979.575311,103979.575311,103979.575311,300.447731,0.002898,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $103,979.58
Total Return on Investment (ROI): 3.98%
Annualized Sharpe Ratio: 2.59
--------------------------

In [31]:
master_df_with_target = add_horizon_targets(master_df.copy(), H=1, price_col="close")
ret_col = f"ret_{1}d"

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    # Sector aggregates
    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        # top sectors by pnl
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
         # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 383
Total capital allocated: $3,049,499.44
Average position size:  $7,962.14
Completed trades with returns: 383
Winning trades: 217 (56.7%)
Losing trades:  160 (41.8%)
Total PnL: $3,979.58
Average PnL per trade: $10.39
Average return: 0.11%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Services,99,1.451496e+06,14661.574381,1769.210850,17.870817,0.001379
Technology,89,6.729817e+05,7561.592371,1557.387333,17.498734,0.002290
Utilities,29,1.017049e+05,3507.065253,362.270953,12.492102,0.003678
Financial,17,6.682323e+04,3930.778373,205.246973,12.073351,0.001837
Basic Matierials,19,7.789361e+04,4099.663680,152.476845,8.025097,0.002747
Industrial Goods,21,1.138009e+05,5419.090258,67.907325,3.233682,0.000995
Healthcare,14,4.656504e+04,3326.074121,17.963006,1.283072,-0.000292
Consumer Goods,26,1.533549e+05,5898.266309,-46.013063,-1.769733,-0.001361
Conglomerates,69,3.648793e+05,5288.105216,-106.874912,-1.548912,-0.001284

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
55,2017-04-28,2017-05-01,AMZN,Services,18840.801509,0.868714,NaN,0.025125,473.367327
203,2017-06-15,2017-06-16,AMZN,Services,19072.678530,0.868714,NaN,0.024415,465.656061
115,2017-05-23,2017-05-24,HRG,Conglomerates,7635.138511,0.659389,NaN,0.054576,416.698427
235,2017-07-03,2017-07-05,AMZN,Services,18989.315695,0.868714,NaN,0.018602,353.240608
244,2017-07-07,2017-07-10,AMZN,Services,19097.543808,0.868714,NaN,0.018094,345.556370
341,2017-08-11,2017-08-14,AMZN,Services,19254.004508,0.868714,NaN,0.015816,304.526672
70,2017-05-05,2017-05-08,AMZN,Services,18900.261441,0.868714,NaN,0.015940,301.262127
262,2017-07-17,2017-07-18,AMZN,Services,19287.825476,0.868714,NaN,0.014267,275.174300
82,2017-05-11,2017-05-12,AMZN,Services,18954.872305,0.868714,NaN,0.014489,274.635442
359,2017-08-21,2017-08-22,AMZN,Services,19201.680637,0.868714,NaN,0.014277,274.140883

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
335,2017-08-09,2017-08-10,AMZN,Services,19333.392385,0.868714,NaN,-0.025550,-493.961703
91,2017-05-16,2017-05-17,AMZN,Services,19025.079846,0.868714,NaN,-0.022058,-419.663577
350,2017-08-16,2017-08-17,AMZN,Services,19332.509885,0.868714,NaN,-0.018003,-348.039452
220,2017-06-26,2017-06-27,AMZN,Services,19176.728924,0.868714,NaN,-0.017304,-331.836460
232,2017-06-30,2017-07-03,AMZN,Services,19044.546890,0.868714,NaN,-0.014814,-282.127393
226,2017-06-28,2017-06-29,AMZN,Services,19139.412888,0.868714,NaN,-0.014541,-278.299153
200,2017-06-14,2017-06-15,AMZN,Services,19118.926450,0.868714,NaN,-0.012596,-240.829286
177,2017-06-08,2017-06-09,PCLN,Services,7550.460236,0.640000,NaN,-0.026559,-200.533828
60,2017-05-01,2017-05-02,HRG,Conglomerates,2339.012111,0.659389,NaN,-0.083250,-194.723351
217,2017-06-23,2017-06-26,AMZN,Services,19229.428587,0.868714,NaN,-0.009724,-186.980112

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Services          1769.210850
Technology        1557.387333
Utilities          362.270953
Financial          205.246973
Basic Matierials   152.476845
Industrial Goods    67.907325
Healthcare          17.963006
Consumer Goods     -46.013063
Conglomerates     -106.874912

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Services          1769.210850
Technology        1557.387333
Utilities          362.270953
Financial          205.246973
Basic Matierials   152.476845
Industrial Goods    67.907325
Healthcare          17.963006
Consumer Goods     -46.013063
Conglomerates     -106.874912

Top 10 Most Invested Tickers:

ticker
HRG     66
AMZN    61
PCLN    38
GOOG    31
INTC    25
AEP     22
LMT     17
CHL     15
CELG    14
V       13
Name: count, dtype: int64

Tickers Never Invested In (65):
{'TM', 'BSAC', 'ORCL', 'PTR', 'PEP', 'BHP', 'UL', 'ABBV', 'PFE', 'UPS', 'JPM', 'PG', 'AMGN', 'CODI', 'PCG', 'BABA', 'SNP', 'NGG', 'SPLP', 'BA', 'DIS', 'PICO', 'EXC', 'C', 'CAT', 'AAPL', 'TSM', 'HON', 'WMT', 'FB', 'UTX', 'BP', 'BBL', 'MSFT', 'AGFS', 'SLB', 'ABB', 'REX', 'MDT', 'GD', 'SRE', 'D', 'SNY', 'NVS', 'MCD', 'CHTR', 'MRK', 'CMCSA', 'BCH', 'KO', 'DHR', 'GE', 'UNH', 'BAC', 'CVX', 'BRK-A', 'XOM', 'HSBC', 'JNJ', 'HD', 'PPL', 'WFC', 'CSCO', 'SO', 'UN'}

In [32]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]