# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.optim.lr_scheduler import ReduceLROnPlateau

### Configurations

In [8]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 1100  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [9]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [10]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [11]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close_price') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [12]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # End current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [13]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [14]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [15]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close_price'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close_price']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [16]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [17]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [18]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [19]:
def calculate_historical_payouts(df):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive next-day return when target==1
      - 'avg_loss_abs': mean absolute negative next-day return when target==0
    """
    out = {}
    for t, g in df.groupby('ticker'):
        # next_day return already implicit in your create_target_variable
        r = (g['next_day_close'] - g['close_price']) / g['close_price']
        wins = r[g['target'] == 1]
        losses = r[g['target'] == 0]
        avg_win = wins[wins > 0].mean() if (wins > 0).any() else np.nan
        avg_loss_abs = (-losses[losses < 0]).mean() if (losses < 0).any() else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [20]:
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.float32))
    def __len__(self): return self.X.shape[0]
    def __getitem__(self, idx): return self.X[idx], self.y[idx]

class LSTMClassifier(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, use_layernorm=False):
        super().__init__()
        self.lstm1 = nn.LSTM(
            input_size=n_features, hidden_size=hidden1,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )
        self.inter_drop = nn.Dropout(p=inter_dropout)  # proxy for recurrent_dropout
        self.lstm2 = nn.LSTM(
            input_size=hidden1, hidden_size=hidden2,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )

        # Normalization after temporal pooling
        self.use_layernorm = bool(use_layernorm)
        if self.use_layernorm:
            self.norm = nn.LayerNorm(normalized_shape=hidden2)
        else:
            self.norm = nn.BatchNorm1d(num_features=hidden2)

        # Head
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(p=dropout)
        self.fc_out = nn.Linear(fc, 1)  # logits

    def forward(self, x):
        # x: (B, T, F)
        out1, _ = self.lstm1(x)     # (B, T, hidden1)
        out1 = self.inter_drop(out1)
        out2, _ = self.lstm2(out1)  # (B, T, hidden2)

        last = out2[:, -1, :]       # (B, hidden2)
        if isinstance(self.norm, nn.BatchNorm1d):
            last = self.norm(last)  # BN expects (B, C)
        else:
            last = self.norm(last)  # LN expects (B, C)

        z = self.fc1(last)
        z = self.relu(z)
        z = self.drop(z)
        logits = self.fc_out(z).squeeze(-1)  # (B,)
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [ ]:
def train_company_models(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         sequence_length: int = None,
                         H = 1):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    #sequence length & guards
    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)

    if len(company_data_df) < sequence_length + H + 10:
        print(f"Not enough data for {ticker}.")
        return False, sequence_length

    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        print(f"No contiguous periods found for {ticker}.")
        return False, sequence_length

    # build sequences
    targets = company_data_df[f'target_{H}d'].values
    X, y = create_contiguous_sequences(
        company_data_df[feature_cols].values,
        targets,
        contiguous_periods,
        sequence_length,
        H
    )
    print(f"Created {len(X)} sequences for {ticker}.")
    if len(X) < 2:
        return False, sequence_length

    # chronological split (no shuffle)
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    # scale features (fit on train, transform both)
    scaler = MinMaxScaler()
    F = X_train.shape[-1]
    X_train_scaled = scaler.fit_transform(X_train.reshape(-1, F)).reshape(X_train.shape)
    X_val_scaled   = scaler.transform(  X_val.reshape(-1, F)).reshape(X_val.shape)

    # Keras fit used the scaled data
    train_ds = SequenceDataset(X_train_scaled, y_train)
    val_ds   = SequenceDataset(X_val_scaled,   y_val)

    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_train.shape[-1]
    model = LSTMClassifier(n_features=n_features, dropout=0.3, inter_dropout=0.1).to(device)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)  # clipnorm via grad clipping below
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)
    early = EarlyStopper(patience=15, mode='min')

    for epoch in range(100):
        model.train()
        total_loss = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # clipnorm=1.0
            optimizer.step()
            total_loss += loss.item() * xb.size(0)

        train_loss = total_loss / len(train_loader.dataset)
        val_loss, _ = _evaluate(model, val_loader, device, loss_fn)

        scheduler.step(val_loss)  # ReduceLROnPlateau on val_loss

        # EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:  # stop after 'patience' non-improve epochs
            break

    # Restore best weights
    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    #final validation pass for isotonic calibration (on scaled val data)
    _, validation_predictions = _evaluate(model, val_loader, device, loss_fn)

    # Keras code used 10% buffer (comment said 5%)
    pred_min, pred_max = validation_predictions.min(), validation_predictions.max()
    buffer = 0.05 * (pred_max - pred_min)
    y_min_dynamic = max(0.0, pred_min - buffer)
    y_max_dynamic = min(1.0, pred_max + buffer)

    calibrator = IsotonicRegression(y_min=y_min_dynamic, y_max=y_max_dynamic, out_of_bounds='clip')
    calibrator.fit(validation_predictions, y_val.astype(float))

    # inside train_company_models(..., H=H)
    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt"))
    joblib.dump(calibrator,      os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
    joblib.dump(scaler,          os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


    del model, scaler, calibrator, train_loader, val_loader, train_ds, val_ds
    del X_train, X_val, y_train, y_val, X_train_scaled, X_val_scaled
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [ ]:
def predict_next_horizon(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 H: int) -> dict | None:

    try:
        # load artifacts
        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt")
        calibrator = joblib.load(os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
        scaler     = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        sequence_length    = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


        if not os.path.isfile(state_dict_path):
            return None
        
        if hasattr(scaler, "n_features_in_") and scaler.n_features_in_ != len(feature_cols):
            return None

        # build model skeleton with correct input dim, then load weights
        n_features = len(feature_cols)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        model = LSTMClassifier(n_features=n_features).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    # find the last contiguous block and take the most recent sequence_length rows
    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        return None

    last_start, last_end = contiguous_periods[-1]
    period_data = company_data_df.iloc[last_start:last_end + 1]
    if len(period_data) < sequence_length:
        return None

    last_sequence = period_data.tail(sequence_length)

    # scale using the saved scaler (fit  train only)
    # ensure column order matches training
    try:
        scaled_features = scaler.transform(last_sequence[feature_cols])
    except Exception:
        return None

    # shape: (1, T, F) as float32 tensor
    x = torch.from_numpy(np.asarray([scaled_features], dtype=np.float32)).to(device)

    with torch.no_grad():
        logits = model(x)                  # shape (1,)
        prob = torch.sigmoid(logits).item()  # scalar in [0,1]

    # Isotonic calibration (expects iterable)
    calibrated = float(calibrator.predict([prob])[0])

    print(f"Raw prediction for {ticker}: {prob}")
    print(f"Calibrated prediction for {ticker}: {calibrated}")

    return {
        'ticker': ticker,
        'raw_prediction': prob,
        'calibrated_prediction': calibrated
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [23]:
def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                            total_capital: float, sector_threshold: float,
                            kelly_fraction: float) -> pd.DataFrame:

    investment_decisions = []

    if daily_predictions_df.empty:
        return pd.DataFrame()

    for sector, group in daily_predictions_df.groupby('sector'):
        avg_sector_score = group['calibrated_prediction'].mean()
        if avg_sector_score < sector_threshold:
            continue

        best_stock_in_sector = group.loc[group['calibrated_prediction'].idxmax()]
        ticker = best_stock_in_sector['ticker']
        p = best_stock_in_sector['calibrated_prediction']
        b_info = payout_map.get(ticker, 0.0)
        b = (b_info['b'] if isinstance(b_info, dict) else float(b_info))
        if not np.isfinite(b) or b <= 0: 
            continue
        
        if not b_info or not np.isfinite(b_info.get('b', np.nan)): 
            continue
        b = max(b_info['b'], 1e-6)  # avoid div-by-zero
        kelly_percentage = p - (1 - p) / b

        if kelly_percentage > 0:
            investment_fraction = kelly_percentage * kelly_fraction
            investment_amount = total_capital * investment_fraction

            print(f"Investing {investment_amount} in {ticker}")

            investment_decisions.append({
                'ticker': ticker,
                'investment_fraction': investment_fraction,
                'investment_amount': investment_amount,
                'predicted_prob': p
            })

    return pd.DataFrame(investment_decisions)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [24]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    files = [
        f"{ticker}_lstm_H{H}.pt",
        f"{ticker}_calibrator_H{H}.pkl",
        f"{ticker}_scaler_H{H}.pkl",
        f"{ticker}_seq_length_H{H}.pkl",
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in files)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [ ]:
def run_simulation(master_df: pd.DataFrame, payout_map: dict, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"\nStarting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    # precompute horizon returns if not already present
    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"
    if ret_col not in master_df.columns or tgt_col not in master_df.columns:
        print("Adding horizon targets to master_df...")
        master_df = add_horizon_targets(master_df, H=H, price_col='close_price')

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: RETRAIN_INTERVAL for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    # overlapping book
    open_positions = []  # each: {'ticker','invest','entry_date','exit_date'}
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                # realize H-day return measured from entry date
                row = master_df[(master_df['date'] == pos['entry_date']) & (master_df['ticker'] == pos['ticker'])]
                if not row.empty:
                    rH = row.iloc[0][ret_col]
                    if pd.notna(rH):
                        pnl = pos['invest'] * rH
                        total_pnl_today += pnl
                        capital += pos['invest'] + pnl  # release capital
                # else: silently drop if missing
            else:
                still_open.append(pos)
        open_positions = still_open

        # equity at START (after settlements, before new entries)
        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # build prediction universe using info strictly before current_date
        historical_data = master_df[master_df['date'] < current_date]
        if i == 0:  # no "yesterday" slice for display
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)

        # size raw trades via Kelly
        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df, payout_map, capital, SECTOR_CONFIDENCE_THRESHOLD, KELLY_FRACTION
        )

        # entry logic (allow_overlap controls laddering)
        exit_idx = i + H
        if exit_idx < len(unique_dates):
            exit_date = unique_dates[exit_idx]
        else:
            exit_date = None  # can't open new trades that we cannot exit within data

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            # strongest first to grab budgets
            investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)

            # current exposures (post-settlement)
            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                # per-ticker ladder depth
                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue  # no overlapping allowed

                # base size from Kelly (already scaled by KELLY_FRACTION)
                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))  # vs equity

                # clamp by remaining budgets
                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                # lock capital and record position
                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})

        # equity at END (after entries)
        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        # log the day
        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,  # cash only
            'capital_end': capital,                               # cash only
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,                # realized PnL today
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [26]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [ ]:
master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')

Shape of master_df before dropping NaNs: (108592, 21)
Shape of master_df after dropping NaNs: (108592, 21)

In [ ]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)
columns_to_check = ['EMA_12', 'EMA_26','EMA_50','MACD_12_26_9','MACDh_12_26_9','MACDs_12_26_9','RSI_14','ATRr_14','STOCHRSIk_14_14_3_3','STOCHRSId_14_14_3_3','ATRr_14','BB_upper','BB_middle','BB_lower','OBV']
master_df = master_df.dropna(subset=columns_to_check)

In [ ]:
feature_cols = ['open','high','low', 'volume',
                # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV'
]
feature_cols.extend(new_indicator_columns)
print(f"Final feature columns: {feature_cols}")

Final feature columns: ['open', 'high', 'low', 'volume', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV']

In [33]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close_price,volume,ticker,stance_positive,stance_negative,sector,...,MACDh_12_26_9,MACDs_12_26_9,RSI_14,STOCHRSIk_14_14_3_3,STOCHRSId_14_14_3_3,ATRr_14,BB_upper,BB_middle,BB_lower,OBV
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,119292600.0,AAPL,0.0,0.0,Consumer Goods,...,-0.538077,-3.703588,25.771012,21.054629,19.582354,2.377852,94.648550,84.401357,74.154164,-1.014356e+09
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,197477700.0,AAPL,0.0,0.0,Consumer Goods,...,-0.537725,-3.838019,23.573491,15.792949,19.993462,2.380310,93.761634,83.514428,73.267223,-1.211834e+09
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,316723400.0,AAPL,0.0,0.0,Consumer Goods,...,-0.455544,-3.951905,24.836267,12.243346,16.363641,2.459547,92.716200,82.679214,72.642228,-8.951103e+08
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,205829400.0,AAPL,0.0,0.0,Consumer Goods,...,0.002769,-3.951213,43.429047,39.692073,22.576123,2.695187,91.617665,82.201285,72.784906,-6.892809e+08
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,160688500.0,AAPL,0.0,0.0,Consumer Goods,...,0.281964,-3.880722,42.011353,69.373201,40.436207,2.679612,91.027780,81.851785,72.675790,-8.499694e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104215,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,-0.107548,-0.972858,31.975492,35.117121,31.775404,0.786087,81.525829,78.243500,74.961171,-2.688251e+08
104216,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,-0.069077,-0.990127,31.851847,48.597552,38.712818,0.759224,81.303475,78.057500,74.811525,-2.758855e+08
104217,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,-0.054652,-1.003790,29.688704,55.025431,46.246701,0.732850,80.964170,77.832500,74.700830,-2.841035e+08
104218,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,-0.018917,-1.008519,32.913052,73.940933,59.187972,0.711932,80.569554,77.624500,74.679446,-2.684618e+08
104219,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,0.028984,-1.001273,36.200731,85.986580,71.650981,0.698937,80.167620,77.442500,74.717380,-2.611210e+08

In [34]:

master_df_with_target = create_target_variable(master_df)
master_df_with_target = add_horizon_targets(master_df_with_target, H=5)
payout_map = calculate_historical_payouts(master_df_with_target)

initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df_with_target,
    payout_map,
    feature_cols,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=5,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Creating target variable...
Target variable created.

Starting simulation with 1100 initial training days... (H=5)
Starting predictions from day 1100 (after 1100 training days)

Simulating Trading Days:   0%|          | 0/108 [00:00<?, ?it/s]

Created 1084 sequences for AAPL.
Raw prediction for AAPL: 0.5087817907333374
Calibrated prediction for AAPL: 0.5298623442649841
Created 1084 sequences for ABB.
Raw prediction for ABB: 0.4774821698665619
Calibrated prediction for ABB: 0.4860254228115082
Created 1003 sequences for ABBV.
Raw prediction for ABBV: 0.39725732803344727
Calibrated prediction for ABBV: 0.38162699341773987
Created 1084 sequences for AEP.
Raw prediction for AEP: 0.5610858798027039
Calibrated prediction for AEP: 0.6287878751754761
Created 527 sequences for AGFS.
Raw prediction for AGFS: 0.5149518847465515
Calibrated prediction for AGFS: 0.5159199237823486
Created 1084 sequences for AMGN.
Raw prediction for AMGN: 0.45877605676651
Calibrated prediction for AMGN: 0.5257731676101685
Created 1084 sequences for AMZN.
Raw prediction for AMZN: 0.5487561225891113
Calibrated prediction for AMZN: 0.5442163348197937
Created 1084 sequences for BA.
Raw prediction for BA: 0.3076035678386688
Calibrated prediction for BA: 0.31029826402664185
Created 571 sequences for BABA.
Raw prediction for BABA: 0.5155236124992371
Calibrated prediction for BABA: 0.5234741568565369
Created 1084 sequences for BAC.
Raw prediction for BAC: 0.447201132774353
Calibrated prediction for BAC: 0.47199904918670654
Created 1084 sequences for BBL.
Raw prediction for BBL: 0.49825361371040344
Calibrated prediction for BBL: 0.5949506163597107
Created 1084 sequences for BCH.
Raw prediction for BCH: 0.49354252219200134
Calibrated prediction for BCH: 0.4962126910686493
Created 1084 sequences for BHP.
Raw prediction for BHP: 0.5154529213905334
Calibrated prediction for BHP: 0.5199435949325562
Created 1084 sequences for BP.
Raw prediction for BP: 0.5597679615020752
Calibrated prediction for BP: 0.6445783376693726
Created 1084 sequences for BRK-A.
Raw prediction for BRK-A: 0.46057894825935364
Calibrated prediction for BRK-A: 0.464071124792099
Created 1084 sequences for BSAC.
Raw prediction for BSAC: 0.4981290102005005
Calibrated prediction for BSAC: 0.49770623445510864
Created 1084 sequences for BUD.
Raw prediction for BUD: 0.5672612190246582
Calibrated prediction for BUD: 0.5
Created 1084 sequences for C.
Raw prediction for C: 0.4880385100841522
Calibrated prediction for C: 0.5826771855354309
Created 1084 sequences for CAT.
Raw prediction for CAT: 0.5220279097557068
Calibrated prediction for CAT: 0.5253220796585083
Created 1084 sequences for CELG.
Raw prediction for CELG: 0.49623003602027893
Calibrated prediction for CELG: 0.5663716793060303
Created 1084 sequences for CHL.
Raw prediction for CHL: 0.43839043378829956
Calibrated prediction for CHL: 0.37704917788505554
Created 1084 sequences for CHTR.
Raw prediction for CHTR: 0.5606479644775391
Calibrated prediction for CHTR: 0.5970132350921631
Created 1084 sequences for CMCSA.
Raw prediction for CMCSA: 0.5100756287574768
Calibrated prediction for CMCSA: 0.5143330097198486
Created 1084 sequences for CODI.
Raw prediction for CODI: 0.5368597507476807
Calibrated prediction for CODI: 0.6060606241226196
Created 1084 sequences for CSCO.
Raw prediction for CSCO: 0.5474388599395752
Calibrated prediction for CSCO: 0.6526497602462769
Created 1084 sequences for CVX.
Raw prediction for CVX: 0.5261266827583313
Calibrated prediction for CVX: 0.5297141075134277
Created 1084 sequences for D.
Raw prediction for D: 0.31017377972602844
Calibrated prediction for D: 0.4375
Created 1084 sequences for DHR.
Raw prediction for DHR: 0.3927876055240631
Calibrated prediction for DHR: 0.3709624111652374
Created 1084 sequences for DIS.
Raw prediction for DIS: 0.5134719610214233
Calibrated prediction for DIS: 0.5825883746147156
Created 1084 sequences for DUK.
Raw prediction for DUK: 0.5016114115715027
Calibrated prediction for DUK: 0.49670282006263733
Created 1084 sequences for EXC.
Raw prediction for EXC: 0.4796181619167328
Calibrated prediction for EXC: 0.4615384638309479
Created 1084 sequences for FB.
Raw prediction for FB: 0.5623273253440857
Calibrated prediction for FB: 0.5533333420753479
Created 1084 sequences for GD.
Raw prediction for GD: 0.43592455983161926
Calibrated prediction for GD: 0.5
Created 1084 sequences for GE.
Raw prediction for GE: 0.4288586974143982
Calibrated prediction for GE: 0.4852156937122345
Created 123 sequences for GMRE.
Raw prediction for GMRE: 0.36130452156066895
Calibrated prediction for GMRE: 0.38058072328567505
Created 1084 sequences for GOOG.
Raw prediction for GOOG: 0.5891680717468262
Calibrated prediction for GOOG: 0.5714285969734192
Created 1084 sequences for HD.
Raw prediction for HD: 0.3355086147785187
Calibrated prediction for HD: 0.33898305892944336
Created 1084 sequences for HON.
Raw prediction for HON: 0.7606111764907837
Calibrated prediction for HON: 0.6666666865348816
Created 1084 sequences for HRG.
Raw prediction for HRG: 0.5581197738647461
Calibrated prediction for HRG: 0.5798162221908569
Created 1084 sequences for HSBC.
Raw prediction for HSBC: 0.5183484554290771
Calibrated prediction for HSBC: 0.5206336975097656
Created 1084 sequences for IEP.
Raw prediction for IEP: 0.4832264482975006
Calibrated prediction for IEP: 0.4739986062049866
Created 1084 sequences for INTC.
Raw prediction for INTC: 0.3748933672904968
Calibrated prediction for INTC: 0.4000000059604645
Created 1084 sequences for JNJ.
Raw prediction for JNJ: 0.45049506425857544
Calibrated prediction for JNJ: 0.4118923544883728
Created 1084 sequences for JPM.
Raw prediction for JPM: 0.5528856515884399
Calibrated prediction for JPM: 0.5765414834022522
Created 1084 sequences for KO.
Raw prediction for KO: 0.6671204566955566
Calibrated prediction for KO: 0.6891614198684692
Created 1084 sequences for LMT.
Raw prediction for LMT: 0.5884426832199097
Calibrated prediction for LMT: 0.5677965879440308
Created 1084 sequences for MA.
Raw prediction for MA: 0.6199784874916077
Calibrated prediction for MA: 0.6190476417541504
Created 1084 sequences for MCD.
Raw prediction for MCD: 0.4598124623298645
Calibrated prediction for MCD: 0.44897958636283875
Created 1084 sequences for MDT.
Raw prediction for MDT: 0.4644247591495514
Calibrated prediction for MDT: 0.4636484980583191
Created 1084 sequences for MMM.
Raw prediction for MMM: 0.5010314583778381
Calibrated prediction for MMM: 0.49658453464508057
Created 1084 sequences for MO.
Raw prediction for MO: 0.541008472442627
Calibrated prediction for MO: 0.5512070059776306
Created 1084 sequences for MRK.
Raw prediction for MRK: 0.4567984938621521
Calibrated prediction for MRK: 0.4504837989807129
Created 1084 sequences for MSFT.
Raw prediction for MSFT: 0.5562876462936401
Calibrated prediction for MSFT: 0.628171980381012
Created 1084 sequences for NEE.
Raw prediction for NEE: 0.5676625370979309
Calibrated prediction for NEE: 0.5592417120933533
Created 1084 sequences for NGG.
Raw prediction for NGG: 0.5176666378974915
Calibrated prediction for NGG: 0.5000624060630798
Created 1084 sequences for NVS.
Raw prediction for NVS: 0.5970189571380615
Calibrated prediction for NVS: 0.6666666865348816
Created 1084 sequences for ORCL.
Raw prediction for ORCL: 0.37568846344947815
Calibrated prediction for ORCL: 0.3333333432674408
Created 1084 sequences for PCG.
Raw prediction for PCG: 0.4942229986190796
Calibrated prediction for PCG: 0.48740363121032715
Created 1084 sequences for PCLN.
Raw prediction for PCLN: 0.4698367416858673
Calibrated prediction for PCLN: 0.46662724018096924
Created 1084 sequences for PEP.
Raw prediction for PEP: 0.528954803943634
Calibrated prediction for PEP: 0.5868263244628906
Created 1084 sequences for PFE.
Raw prediction for PFE: 0.47085830569267273
Calibrated prediction for PFE: 0.5029211044311523
Created 1084 sequences for PG.
Raw prediction for PG: 0.5102285146713257
Calibrated prediction for PG: 0.5043846964836121
Created 1084 sequences for PICO.
Raw prediction for PICO: 0.473031610250473
Calibrated prediction for PICO: 0.4759405851364136
Created 1084 sequences for PM.
Raw prediction for PM: 0.49698784947395325
Calibrated prediction for PM: 0.5165519118309021
Created 1084 sequences for PPL.
Raw prediction for PPL: 0.4731244444847107
Calibrated prediction for PPL: 0.5530726313591003
Created 1048 sequences for PTR.
Raw prediction for PTR: 0.4869993031024933
Calibrated prediction for PTR: 0.5029280185699463
Created 1084 sequences for RDS-B.
Raw prediction for RDS-B: 0.456156462430954
Calibrated prediction for RDS-B: 0.4423460364341736
Created 1048 sequences for REX.
Raw prediction for REX: 0.4680502414703369
Calibrated prediction for REX: 0.4000000059604645
Created 1084 sequences for SLB.
Raw prediction for SLB: 0.5174543857574463
Calibrated prediction for SLB: 0.4970414340496063
Created 1048 sequences for SNP.
Raw prediction for SNP: 0.49921268224716187
Calibrated prediction for SNP: 0.48342448472976685
Created 1084 sequences for SNY.
Raw prediction for SNY: 0.5370232462882996
Calibrated prediction for SNY: 0.5522180795669556
Created 1084 sequences for SO.
Raw prediction for SO: 0.46654173731803894
Calibrated prediction for SO: 0.46296167373657227
Created 1084 sequences for SPLP.
Raw prediction for SPLP: 0.4578689634799957
Calibrated prediction for SPLP: 0.5363636612892151
Created 1084 sequences for SRE.
Raw prediction for SRE: 0.5181576609611511
Calibrated prediction for SRE: 0.550561785697937
Created 1084 sequences for T.
Raw prediction for T: 0.5039380192756653
Calibrated prediction for T: 0.5147916078567505
Created 1084 sequences for TM.
Raw prediction for TM: 0.43672889471054077
Calibrated prediction for TM: 0.380952388048172
Created 1084 sequences for TOT.
Raw prediction for TOT: 0.47996601462364197
Calibrated prediction for TOT: 0.4789581000804901
Created 1084 sequences for TSM.
Raw prediction for TSM: 0.5156682133674622
Calibrated prediction for TSM: 0.5760757327079773
Created 1084 sequences for UL.
Raw prediction for UL: 0.358974814414978
Calibrated prediction for UL: 0.4615384638309479
Created 1084 sequences for UN.
Raw prediction for UN: 0.6323795914649963
Calibrated prediction for UN: 0.6285714507102966
Created 1084 sequences for UNH.
Raw prediction for UNH: 0.38524913787841797
Calibrated prediction for UNH: 0.4393063485622406
Created 1084 sequences for UPS.
Raw prediction for UPS: 0.48150119185447693
Calibrated prediction for UPS: 0.4850730001926422
Created 1084 sequences for UTX.
Raw prediction for UTX: 0.5737066268920898
Calibrated prediction for UTX: 0.5909090638160706
Created 1084 sequences for V.
Raw prediction for V: 0.46725767850875854
Calibrated prediction for V: 0.4683045744895935
Created 1084 sequences for VZ.
Raw prediction for VZ: 0.505902886390686
Calibrated prediction for VZ: 0.5428571701049805
Created 1084 sequences for WFC.
Raw prediction for WFC: 0.528731644153595
Calibrated prediction for WFC: 0.5224242210388184
Created 1084 sequences for WMT.
Raw prediction for WMT: 0.5198594927787781
Calibrated prediction for WMT: 0.5306313633918762
Created 1084 sequences for XOM.

Simulating Trading Days:   1%|          | 1/108 [05:31<9:50:54, 331.35s/it]

Raw prediction for XOM: 0.5055047869682312
Calibrated prediction for XOM: 0.5078077912330627
Investing 2951.7928164395526 in BP
Investing 2298.1401250940585 in CODI
Investing 3795.8737534174907 in KO
Investing 2413.969890700375 in MA
Investing 3348.2989702444934 in NVS
Investing 3482.5844277210754 in HON
Investing 2648.416649000356 in CHTR
Investing 3300.6455927276434 in CSCO
Investing 2368.4698247972565 in AEP
Raw prediction for AAPL: 0.508803129196167
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47771528363227844
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.400655061006546
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5721541047096252
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.514672577381134
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.46085596084594727
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5479218363761902
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.29356279969215393
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5157313942909241
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.447646826505661
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49542996287345886
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4934616982936859
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5153161883354187
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5542367696762085
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.460443377494812
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49790701270103455
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5701925754547119
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4831627607345581
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5215638279914856
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48797640204429626
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4330553710460663
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.560917317867279
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5098245739936829
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5370367765426636
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.5572858452796936
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5254507064819336
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.42599666118621826
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.38132256269454956
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5130446553230286
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5014640688896179
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4754687249660492
Calibrated prediction for EXC: 0.4000000059604645
Raw prediction for FB: 0.5583791136741638
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.42724210023880005
Calibrated prediction for GD: 0.43765491247177124
Raw prediction for GE: 0.42569103837013245
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.35789811611175537
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.5794503092765808
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.3230001628398895
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.7344791889190674
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5565615892410278
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5177246332168579
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48370224237442017
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.363286554813385
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.46738994121551514
Calibrated prediction for JNJ: 0.4118923544883728
Raw prediction for JPM: 0.5482516884803772
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6316738128662109
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5859549045562744
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6081083416938782
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4561239778995514
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.46454381942749023
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.5008357763290405
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5426918268203735
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45759841799736023
Calibrated prediction for MRK: 0.46116572618484497
Raw prediction for MSFT: 0.5691384673118591
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5711761116981506
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5173190832138062
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5907760262489319
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.36552974581718445
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5024809837341309
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46944108605384827
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.530735969543457
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46914348006248474
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5096102952957153
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4730689525604248
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.496698260307312
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.48269158601760864
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4872291088104248
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.45548000931739807
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.4540654122829437
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.5066745281219482
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5039864778518677
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5390133261680603
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46661195158958435
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.45400112867355347
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5188454985618591
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5043281316757202
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.42795899510383606
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.4795554280281067
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5140739679336548
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.40863341093063354
Calibrated prediction for UL: 0.5
Raw prediction for UN: 0.6068941354751587
Calibrated prediction for UN: 0.6285714507102966
Raw prediction for UNH: 0.37184661626815796
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48150673508644104
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5643028616905212
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.46699875593185425
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5111672878265381
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5290622711181641
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5131393074989319
Calibrated prediction for WMT: 0.5306313633918762

Simulating Trading Days:   2%|▏         | 2/108 [05:33<4:02:48, 137.44s/it]

Raw prediction for XOM: 0.5132855772972107
Calibrated prediction for XOM: 0.5078077912330627
Investing 2166.3741149190123 in BP
Investing 1686.6465870276513 in CODI
Investing 1951.58739047182 in UN
Investing 1771.6561461502095 in MA
Investing 2457.377149828902 in NVS
Investing 2555.931674884703 in HON
Investing 1943.7208607463983 in CHTR
Investing 2422.4034745201147 in CSCO
Investing 1738.2628251655337 in AEP
Raw prediction for AAPL: 0.5087403059005737
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47781527042388916
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.40932098031044006
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5687815546989441
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5144274830818176
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.46247121691703796
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5472773909568787
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2797064483165741
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5156950950622559
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.447868674993515
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49224114418029785
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4936254620552063
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5151532292366028
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5523557662963867
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4602876603603363
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4978189170360565
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5733042359352112
Calibrated prediction for BUD: 0.5714285969734192
Raw prediction for C: 0.4794664978981018
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5209966897964478
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4840872287750244
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.43829524517059326
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5612521171569824
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5095173716545105
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5277050137519836
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.5636181831359863
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.524398922920227
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5289828181266785
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.3722647428512573
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.513484537601471
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5019205808639526
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.46709850430488586
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.557137131690979
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.42640432715415955
Calibrated prediction for GD: 0.4227274954319
Raw prediction for GE: 0.42173871397972107
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.354836106300354
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.5738284587860107
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.3067488670349121
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.7121238112449646
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.554550051689148
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5170506238937378
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48463597893714905
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3623215854167938
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.48439666628837585
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5441604852676392
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6127195358276367
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5854309797286987
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5932728052139282
Calibrated prediction for MA: 0.5846854448318481
Raw prediction for MCD: 0.4509328305721283
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.46535900235176086
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.5005946755409241
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5444827079772949
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4586239457130432
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5802056789398193
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5724638104438782
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5167927145957947
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5889398455619812
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.346567839384079
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5119097232818604
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4690299332141876
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5354169607162476
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46783447265625
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5091986656188965
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4731237590312958
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49620601534843445
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.497547447681427
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4879686236381531
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.45526841282844543
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.44193339347839355
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.49839547276496887
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5151940584182739
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.541208028793335
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4670717716217041
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.44632306694984436
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5220226645469666
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5045643448829651
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4393932521343231
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.4792056381702423
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5125839114189148
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.46063002943992615
Calibrated prediction for UL: 0.510869562625885
Raw prediction for UN: 0.562332034111023
Calibrated prediction for UN: 0.5714285969734192
Raw prediction for UNH: 0.36809298396110535
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48169878125190735
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.558940589427948
Calibrated prediction for UTX: 0.5909090638160706

Simulating Trading Days:   3%|▎         | 3/108 [05:34<2:12:06, 75.49s/it]

Raw prediction for V: 0.468425989151001
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5246109962463379
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5294715762138367
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5037372708320618
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5157808661460876
Calibrated prediction for XOM: 0.5078077912330627
Investing 1614.5671399273451 in BP
Investing 1257.033186157349 in CODI
Investing 1064.6114812330786 in PEP
Investing 946.1109235755025 in MA
Investing 1831.4474721603597 in NVS
Investing 1904.8987272092556 in HON
Investing 1448.6269058240437 in CHTR
Investing 1805.3821002898287 in CSCO
Investing 1295.502018207258 in AEP
Raw prediction for AAPL: 0.5085965394973755
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47749024629592896
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4250488579273224
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5649800896644592
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5142369866371155
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.46416452527046204
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5467995405197144
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2708800435066223
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5152748227119446
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4479638636112213
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49121370911598206
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4939616024494171
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5150427222251892
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5550099611282349
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4601786136627197
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49810758233070374
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5749397873878479
Calibrated prediction for BUD: 0.5742807388305664
Raw prediction for C: 0.4789941906929016
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5206469297409058
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48465266823768616
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.44573870301246643
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5619580745697021
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5093090534210205
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5265517830848694
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.5695431232452393
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5231121778488159
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5908424258232117
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.36669427156448364
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5149129033088684
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.502867579460144
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4610068202018738
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5579897165298462
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.42847180366516113
Calibrated prediction for GD: 0.4595657289028168
Raw prediction for GE: 0.4168676733970642
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.35233619809150696
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.5717280507087708
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.28802624344825745
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.7032586932182312
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5524238348007202
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5168271660804749
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4859922230243683
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.36744725704193115
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5001190900802612
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5418180823326111
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6102965474128723
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5854917168617249
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5781244039535522
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4457298517227173
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.46639710664749146
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.500386118888855
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5460537075996399
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45976704359054565
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5864691138267517
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5720140933990479
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5161536335945129
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.59174644947052
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.31942981481552124
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5175755620002747
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4689488708972931
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5423394441604614
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46739670634269714
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5088540315628052
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4731496274471283
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.495846152305603
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5169283151626587
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4898028075695038
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.45683684945106506
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.430676132440567
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.4936849772930145
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5259661674499512
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5437940359115601
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46759742498397827
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43815720081329346
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.533305823802948
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5046848654747009
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.46100473403930664
Calibrated prediction for TM: 0.380952388048172

Simulating Trading Days:   4%|▎         | 4/108 [05:36<1:20:07, 46.22s/it]

Raw prediction for TOT: 0.479070246219635
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5102154612541199
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.4876514673233032
Calibrated prediction for UL: 0.510869562625885
Raw prediction for UN: 0.5031405091285706
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3616805076599121
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4820021986961365
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5565441250801086
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.4689871370792389
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.535267174243927
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5299208760261536
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.49912694096565247
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5142737030982971
Calibrated prediction for XOM: 0.5078077912330627
Investing 1225.869749972101 in BP
Investing 954.4099588764612 in CODI
Investing 808.3126294613862 in PEP
Investing 791.5161935052554 in C
Investing 1390.5374383410813 in NVS
Investing 1446.3057426966245 in HON
Investing 1099.8786355365132 in CHTR
Investing 1370.7471489764066 in CSCO
Investing 983.6176495079346 in AEP
Raw prediction for AAPL: 0.5084192752838135
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4771896302700043
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4390205442905426
Calibrated prediction for ABBV: 0.3913043439388275
Raw prediction for AEP: 0.5596024990081787
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.514062225818634
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4659882187843323
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5461439490318298
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.266263872385025
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5144068598747253
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4482741951942444
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4896042048931122
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49439606070518494
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5148959755897522
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5585135221481323
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46002310514450073
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.498492032289505
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.574214518070221
Calibrated prediction for BUD: 0.5714285969734192
Raw prediction for C: 0.4791082739830017
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5204317569732666
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4822227358818054
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4523679316043854
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5636626482009888
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5094035863876343
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5107390880584717
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.5768725872039795
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5218568444252014
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5971775650978088
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.3626886308193207
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5169541835784912
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.503912091255188
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.46152132749557495
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.561156690120697
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.43329212069511414
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4133799374103546
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.36048486828804016
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.5727261900901794
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.2620669901371002
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.7027988433837891
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5501570105552673
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5173095464706421
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4875487685203552
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.3763275444507599
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5132478475570679
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5419250130653381
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5936204195022583
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5861261487007141
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5730997920036316
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4490836560726166
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.4677117168903351
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.5002546310424805
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5470171570777893
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46127018332481384
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5880630612373352
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5706360340118408
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5156620740890503
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5955444574356079
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.2879965901374817
Calibrated prediction for ORCL: 0.22886346280574799
Raw prediction for PCG: 0.5138958096504211
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46936270594596863
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5485129952430725
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4671028256416321
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5083938837051392
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4731050729751587
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4957517981529236
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5295700430870056
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4917747974395752
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4598795771598816
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.41945314407348633
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.4944840967655182
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5351412296295166
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5435400009155273
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.468022882938385
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.430453360080719
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5499999523162842
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5047371983528137
Calibrated prediction for T: 0.5147916078567505

Simulating Trading Days:   5%|▍         | 5/108 [05:37<51:31, 30.02s/it]

Raw prediction for TM: 0.4865085482597351
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4789263606071472
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5070224404335022
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.48388952016830444
Calibrated prediction for UL: 0.510869562625885
Raw prediction for UN: 0.44739681482315063
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.35788682103157043
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48222285509109497
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5532545447349548
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.4712875783443451
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5429486036300659
Calibrated prediction for VZ: 0.5536168813705444
Raw prediction for WFC: 0.5304372906684875
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4978000521659851
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.511355996131897
Calibrated prediction for XOM: 0.5078077912330627
Investing 1178.6461177004426 in BP
Investing 917.643650763045 in CODI
Investing 777.1743634465093 in PEP
Investing 761.024969082754 in C
Investing 1336.9703863360148 in NVS
Investing 1390.5903532377952 in HON
Investing 1057.5085026335585 in CHTR
Investing 1317.9424694399718 in CSCO
Investing 945.7261865875607 in AEP
Raw prediction for AAPL: 0.508231520652771
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4766989052295685
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4503483474254608
Calibrated prediction for ABBV: 0.5
Raw prediction for AEP: 0.5524051189422607
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5139239430427551
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4688264727592468
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.545432448387146
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2653050720691681
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5132896304130554
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.44855010509490967
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4844605624675751
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4947376847267151
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5148480534553528
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5633581280708313
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.45982661843299866
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49924910068511963
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.57245272397995
Calibrated prediction for BUD: 0.5657646656036377
Raw prediction for C: 0.47883057594299316
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5202149748802185
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48327386379241943
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4641259014606476
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5659056305885315
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5098296999931335
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5016843676567078
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.5876131057739258
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.52032870054245
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5578241348266602
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.36121609807014465
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5187619924545288
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5047668218612671
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.46893560886383057
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.564579427242279
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4402620196342468
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.41067495942115784
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.38183826208114624
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.5761699676513672
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.24173559248447418
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.7143664360046387
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5494906306266785
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5179381370544434
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.488822340965271
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.3834160566329956
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5239851474761963
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5437827110290527
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5765606164932251
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5874607563018799
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5807046294212341
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4411928653717041
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.4694385528564453
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.5002394318580627
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5475016832351685
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46285080909729004
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5855258703231812
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5694782137870789
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.515014111995697
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.601456344127655
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.2638181746006012
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5108381509780884
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47010383009910583
Calibrated prediction for PCLN: 0.472580224275589
Raw prediction for PEP: 0.5537740588188171
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4670829474925995
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5078766942024231
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47299298644065857
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4956410527229309
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5355427265167236
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4939013421535492
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.46360859274864197
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.40637341141700745
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.49485817551612854
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5437656044960022
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5429801344871521
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46818074584007263
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.42354270815849304
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5694591999053955
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5047345757484436
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5117375254631042
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47897931933403015
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5029807686805725
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.44432005286216736
Calibrated prediction for UL: 0.5
Raw prediction for UN: 0.3946635127067566
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.35395944118499756
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48241254687309265
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.549530565738678
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.47335222363471985
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5443354845046997
Calibrated prediction for VZ: 0.5620273947715759
Raw prediction for WFC: 0.5308667421340942
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.49738624691963196
Calibrated prediction for WMT: 0.5306313633918762

Simulating Trading Days:   6%|▌         | 6/108 [05:38<34:26, 20.26s/it]

Raw prediction for XOM: 0.5099519491195679
Calibrated prediction for XOM: 0.5078077912330627
Investing 1918.6282753450907 in BP
Investing 1493.7622316016837 in CODI
Investing 1265.102973817936 in PEP
Investing 1238.814604314415 in C
Investing 2176.352297777025 in NVS
Investing 2263.636159383881 in HON
Investing 1721.437574943307 in CHTR
Investing 2145.3782006079005 in CSCO
Investing 1731.8604836314912 in SRE
Raw prediction for AAPL: 0.5080922842025757
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47632676362991333
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4621925354003906
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5510557293891907
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5138242840766907
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.47214874625205994
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5455018281936646
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2658454179763794
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.512019693851471
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.44892066717147827
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4764654040336609
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49483272433280945
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5145547389984131
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5673054456710815
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46053406596183777
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5002709627151489
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5695586800575256
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.47864753007888794
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5199877023696899
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48349839448928833
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4758407473564148
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5685305595397949
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5101528167724609
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4928641617298126
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.5953696966171265
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5188100337982178
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.45987361669540405
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.36135134100914
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5194712281227112
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5053030252456665
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.48481592535972595
Calibrated prediction for EXC: 0.4615384638309479
Raw prediction for FB: 0.5698834657669067
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4467463493347168
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.40892016887664795
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.40546801686286926
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.5807620882987976
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.22859300673007965
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.721013069152832
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5498910546302795
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5183912515640259
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4892253279685974
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.3907741606235504
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5323262810707092
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5460025072097778
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5567343831062317
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5888621807098389
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5953422784805298
Calibrated prediction for MA: 0.5992341637611389
Raw prediction for MCD: 0.43558230996131897
Calibrated prediction for MCD: 0.39014294743537903
Raw prediction for MDT: 0.47117504477500916
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.5002599954605103
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5477714538574219
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4641170799732208
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5814581513404846
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5690014362335205
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5143112540245056
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6070489287376404
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.245328888297081
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5029627680778503
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4709191918373108
Calibrated prediction for PCLN: 0.49075332283973694
Raw prediction for PEP: 0.5576679706573486
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4678347408771515
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.507439136505127
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47283416986465454
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4956907331943512
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5368211269378662
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49542689323425293
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4662279486656189
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.39381325244903564
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.49574580788612366
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5492512583732605
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5418508648872375
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46821022033691406
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4179462790489197
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5793546438217163
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5046381950378418
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.534168541431427
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4788452386856079
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.49903881549835205
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.4027615189552307
Calibrated prediction for UL: 0.5
Raw prediction for UN: 0.351669579744339
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.34980297088623047
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4825448989868164
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5458349585533142
Calibrated prediction for UTX: 0.5789473652839661

Simulating Trading Days:   6%|▋         | 7/108 [05:40<23:41, 14.07s/it]

Raw prediction for V: 0.47536370158195496
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5522339940071106
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5312449932098389
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4973028600215912
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.508861243724823
Calibrated prediction for XOM: 0.5078077912330627
Investing 2036.9635478290413 in BP
Investing 1585.8930330572318 in CODI
Investing 1343.1307538995545 in PEP
Investing 1393.5530758670127 in MA
Investing 2310.583219674699 in NVS
Investing 2403.250489667341 in HON
Investing 1827.6107128630993 in CHTR
Investing 2277.6987325277173 in CSCO
Investing 1838.6764754878907 in SRE
Raw prediction for AAPL: 0.5079829096794128
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4760645627975464
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4708684980869293
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5509742498397827
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.513663113117218
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4720607399940491
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5460134148597717
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.263573557138443
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5111197829246521
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.44930845499038696
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4662131071090698
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49467188119888306
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5143033862113953
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5716109275817871
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46098804473876953
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5012384653091431
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5677852630615234
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4791221618652344
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5197064876556396
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4644404351711273
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.48618370294570923
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5710777640342712
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5104207992553711
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4825403690338135
Calibrated prediction for CODI: 0.5555555820465088
Raw prediction for CSCO: 0.6012439727783203
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5175279378890991
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.38871097564697266
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.36421698331832886
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5190959572792053
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5055615901947021
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.503470242023468
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5772753953933716
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4469209611415863
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4072282910346985
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.41893270611763
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.58537757396698
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.227115660905838
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.7117751240730286
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5487545132637024
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5185037851333618
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4888257682323456
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.3984304964542389
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5384153723716736
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5483712553977966
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5482699871063232
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5883328318595886
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6050923466682434
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4308505356311798
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4726599454879761
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.5002961754798889
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5476917028427124
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46428218483924866
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5764970779418945
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.569703996181488
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.513471782207489
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6145665049552917
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.23044872283935547
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4944985508918762
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47158220410346985
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5600288510322571
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46969038248062134
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5070042014122009
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4726775288581848
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4957815408706665
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5379359126091003
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4955727756023407
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.46744266152381897
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.38158971071243286
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.49737998843193054
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5524958372116089
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5413884520530701
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46830517053604126
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4135616719722748
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5799075961112976
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5046426057815552
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5517715215682983
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4786502420902252
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.4953247606754303
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.3761831223964691
Calibrated prediction for UL: 0.4615384638309479

Simulating Trading Days:   7%|▋         | 8/108 [05:41<16:40, 10.01s/it]

Raw prediction for UN: 0.326509028673172
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3418768644332886
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48263680934906006
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5419116616249084
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.48037511110305786
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5616426467895508
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5316342711448669
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.49847912788391113
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.507917046546936
Calibrated prediction for XOM: 0.5078077912330627
Investing 1964.47909216569 in BP
Investing 1067.121060940608 in HRG
Investing 1295.3360343107447 in PEP
Investing 1606.5468257079128 in MA
Investing 2228.3621278336136 in NVS
Investing 2317.731873611655 in HON
Investing 1762.5759861358688 in CHTR
Investing 2196.6478207584146 in CSCO
Investing 1773.24797844444 in SRE
Raw prediction for AAPL: 0.507950484752655
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47571268677711487
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4767133891582489
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5605756640434265
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5135284066200256
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4696463942527771
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5460776686668396
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2573825716972351
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5110592246055603
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4498041570186615
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.45554184913635254
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4944872260093689
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5140123963356018
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5734935402870178
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46100321412086487
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5014488697052002
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5674390196800232
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4801476001739502
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5192416906356812
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4247930645942688
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.49650081992149353
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5731635689735413
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5106109380722046
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4683578312397003
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.6029270887374878
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5164893269538879
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.33947819471359253
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.3713032007217407
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5174973011016846
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5058413147926331
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5171796083450317
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5840065479278564
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.442753404378891
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4052650034427643
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.42842116951942444
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.5893515348434448
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.2352272868156433
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.6823110580444336
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5457850694656372
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.51849764585495
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48768168687820435
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4045833349227905
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5432093143463135
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5504166483879089
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5294572114944458
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5872582197189331
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6074279546737671
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.42829859256744385
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4741162955760956
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.5002554059028625
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5473557710647583
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4633618891239166
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5684025287628174
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5698067545890808
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5125745534896851
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6246280670166016
Calibrated prediction for NVS: 0.6706739664077759
Raw prediction for ORCL: 0.22007523477077484
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4891553819179535
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4719732999801636
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5589950680732727
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47165369987487793
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5066760182380676
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4726349115371704
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49577832221984863
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5407754778862
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49458181858062744
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4669196903705597
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.3693011999130249
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.4999912977218628
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5571027994155884
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5416831970214844
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46858957409858704
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.41011080145835876
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.564951479434967
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5047290325164795
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5624549984931946
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4785819947719574
Calibrated prediction for TOT: 0.4789581000804901

Simulating Trading Days:   8%|▊         | 9/108 [05:42<12:00,  7.28s/it]

Raw prediction for TSM: 0.4927283823490143
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.35181429982185364
Calibrated prediction for UL: 0.4242148995399475
Raw prediction for UN: 0.3286772072315216
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3323550522327423
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4826439619064331
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5370408892631531
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.4843689799308777
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5691816806793213
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5319901704788208
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4997822940349579
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5074361562728882
Calibrated prediction for XOM: 0.5078077912330627
Investing 1532.8276577336887 in BP
Investing 832.6444821342595 in HRG
Investing 1010.714192565771 in PEP
Investing 1253.5432001847203 in MA
Investing 1780.2532943772742 in NVS
Investing 1808.460845040759 in HON
Investing 1375.2883556667648 in CHTR
Investing 1713.9823719106007 in CSCO
Investing 1383.6154104259301 in SRE
Raw prediction for AAPL: 0.5080839991569519
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4754461348056793
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4812339246273041
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5664863586425781
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.513384222984314
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.46341052651405334
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5458089709281921
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.24351643025875092
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5114966630935669
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45056334137916565
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.45000115036964417
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4943922758102417
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5135756731033325
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5723730325698853
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4612835943698883
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5015184879302979
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5684239268302917
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4818147122859955
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5187739133834839
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.40168169140815735
Calibrated prediction for CELG: 0.38461539149284363
Raw prediction for CHL: 0.5176263451576233
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5748816728591919
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5111152529716492
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.44938626885414124
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.6044740676879883
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5157650709152222
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3459680378437042
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.38257238268852234
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.51436847448349
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5061838030815125
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5210822224617004
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5911082029342651
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4353765845298767
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4031432867050171
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.4363445043563843
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.5922293663024902
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.2493734061717987
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.630134642124176
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5397793054580688
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5184272527694702
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48622599244117737
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.41158777475357056
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5461173057556152
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.552379846572876
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5103642344474792
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5850743055343628
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6111860871315002
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4266270399093628
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.47577911615371704
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.5001294612884521
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5462850332260132
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4619129002094269
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5553231239318848
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.569747269153595
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5118478536605835
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6288319230079651
Calibrated prediction for NVS: 0.6774535179138184
Raw prediction for ORCL: 0.21550579369068146
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4859537184238434
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47225138545036316
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5575064420700073
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47306594252586365
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5062257051467896
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4730152189731598
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4955124855041504
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5441765785217285
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49343615770339966
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.46429443359375
Calibrated prediction for RDS-B: 0.4706409275531769
Raw prediction for REX: 0.3588433563709259
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.5029295682907104
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5667243003845215
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5411442518234253
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46888554096221924
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.40748706459999084
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5373222827911377
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5049197673797607
Calibrated prediction for T: 0.5147916078567505

Simulating Trading Days:   9%|▉         | 10/108 [05:43<08:52,  5.43s/it]

Raw prediction for TM: 0.565457284450531
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4785248041152954
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.4923233985900879
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.32464438676834106
Calibrated prediction for UL: 0.4137931168079376
Raw prediction for UN: 0.3450618386268616
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.32065871357917786
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4825786054134369
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5308607816696167
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.485698401927948
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5668407082557678
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5323144197463989
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5008344650268555
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5066661238670349
Calibrated prediction for XOM: 0.5078077912330627
Investing 1486.7530989135819 in BP
Investing 807.6164060979401 in HRG
Investing 980.3336013226952 in PEP
Investing 1215.8635239216694 in MA
Investing 1794.8823953954698 in NVS
Investing 1754.1011555099174 in HON
Investing 1333.9491979877705 in CHTR
Investing 1662.4625671805757 in CSCO
Investing 1192.9461417783555 in AEP
Raw prediction for AAPL: 0.5084658861160278
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47538697719573975
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4823685884475708
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5656465888023376
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.513261079788208
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.459007203578949
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5455645322799683
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.24879473447799683
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.512104868888855
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45167893171310425
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.453389048576355
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49440738558769226
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5138498544692993
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5699436068534851
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46138444542884827
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5014842748641968
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5694442987442017
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.48461398482322693
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5185952186584473
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.39756497740745544
Calibrated prediction for CELG: 0.38461539149284363
Raw prediction for CHL: 0.5281445980072021
Calibrated prediction for CHL: 0.4000000059604645
Raw prediction for CHTR: 0.5760272741317749
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5119472146034241
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.43839335441589355
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.6078879833221436
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5152840614318848
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3232189118862152
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.399512380361557
Calibrated prediction for DHR: 0.4158710837364197
Raw prediction for DIS: 0.5106996893882751
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5065869688987732
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.5203442573547363
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5975067615509033
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4392428398132324
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4034629464149475
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.44242140650749207
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.5939502716064453
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.2771396338939667
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5985073447227478
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5326066613197327
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5179199576377869
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48486536741256714
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4267064332962036
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5474012494087219
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5539904236793518
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4814763367176056
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5858123302459717
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6234681606292725
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.42530810832977295
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.477506548166275
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49997031688690186
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5442600250244141
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4608731269836426
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5361999273300171
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5694112181663513
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5111899971961975
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6273359656333923
Calibrated prediction for NVS: 0.6750409603118896
Raw prediction for ORCL: 0.212076336145401
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4850131571292877
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47256386280059814
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5506601929664612
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4738677144050598
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5056080222129822
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47356438636779785
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49501118063926697
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.54302978515625
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.493198961019516
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4608192443847656
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.35281527042388916
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.5050663948059082
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5598481297492981
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5393939018249512
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4691419005393982
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4057490825653076
Calibrated prediction for SPLP: 0.5363636612892151

Simulating Trading Days:  10%|█         | 11/108 [05:45<06:44,  4.17s/it]

Raw prediction for SRE: 0.510280430316925
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.505190372467041
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5645385384559631
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47855859994888306
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.494080126285553
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.2890070676803589
Calibrated prediction for UL: 0.4137931168079376
Raw prediction for UN: 0.3781215250492096
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3141201436519623
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4824806749820709
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5302817225456238
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.4857247471809387
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5528202056884766
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5325981974601746
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5015800595283508
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5061665177345276
Calibrated prediction for XOM: 0.5078077912330627
Investing 1829.255419060088 in BP
Investing 993.6664591155227 in HRG
Investing 1206.1723994499418 in PEP
Investing 1495.961193285185 in MA
Investing 2178.53365942253 in NVS
Investing 2158.192269207831 in HON
Investing 1641.2501853556391 in CHTR
Investing 2045.4429603824735 in CSCO
Investing 1467.7643490970265 in AEP
Raw prediction for AAPL: 0.5089184641838074
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47523033618927
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.48314568400382996
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5680304765701294
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5131532549858093
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.45995068550109863
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5459531545639038
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.27104413509368896
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.512419581413269
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45269402861595154
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4553462862968445
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4944043457508087
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.513891875743866
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5696331262588501
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46033674478530884
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5014172792434692
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5728153586387634
Calibrated prediction for BUD: 0.5714285969734192
Raw prediction for C: 0.48799246549606323
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5188673138618469
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4127790331840515
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5365251898765564
Calibrated prediction for CHL: 0.5
Raw prediction for CHTR: 0.5761737823486328
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5130048990249634
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4336338937282562
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.6148684024810791
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5155397653579712
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.30449530482292175
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.4201556444168091
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.507451593875885
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5069030523300171
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.521755576133728
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.6032949090003967
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4484686553478241
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4062674939632416
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.4465445876121521
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.5943265557289124
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.30113673210144043
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5972945094108582
Calibrated prediction for HON: 0.653322696685791
Raw prediction for HRG: 0.5249538421630859
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5174290537834167
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4837222695350647
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4472380578517914
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5513319373130798
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5558539628982544
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4645632803440094
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5885263085365295
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6447704434394836
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.42434942722320557
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4789847731590271
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49982619285583496
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5419889688491821
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4607464671134949
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5158164501190186
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5695082545280457
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5109425187110901
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6256802678108215
Calibrated prediction for NVS: 0.6723708510398865
Raw prediction for ORCL: 0.21141266822814941
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4833499491214752
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47310885787010193
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5470374822616577
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47406265139579773
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5049433708190918
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4739704728126526
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4944270849227905
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5397981405258179
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4945530593395233
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4602506756782532
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.3423847556114197
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.5066104531288147
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5445933938026428
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5364846587181091
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46959608793258667
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.40561389923095703
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.4993462860584259
Calibrated prediction for SRE: 0.550561785697937

Simulating Trading Days:  11%|█         | 12/108 [05:46<05:16,  3.30s/it]

Raw prediction for T: 0.5054190158843994
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5647437572479248
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47880494594573975
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.49822798371315
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.25930196046829224
Calibrated prediction for UL: 0.4137931168079376
Raw prediction for UN: 0.41809937357902527
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.31477025151252747
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4822468161582947
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5343634486198425
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.484355092048645
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5341579914093018
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5329685211181641
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5022270083427429
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5049985647201538
Calibrated prediction for XOM: 0.5078077912330627
Investing 1958.7519723519692 in BP
Investing 1064.0100427596947 in HRG
Investing 1291.5596924310514 in PEP
Investing 3031.9601994820637 in MA
Investing 2297.3992015537538 in NVS
Investing 2137.843450103088 in HON
Investing 1757.4374820440494 in CHTR
Investing 2190.243850714548 in CSCO
Investing 1571.6702456013152 in AEP
Raw prediction for AAPL: 0.5093429684638977
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4751167297363281
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.48403963446617126
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.571366548538208
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5130624771118164
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.46565401554107666
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5461570620536804
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3013156056404114
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5126239061355591
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4534388482570648
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.45848438143730164
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49438080191612244
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5142122507095337
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5650622248649597
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46028825640678406
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5015466213226318
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5736197829246521
Calibrated prediction for BUD: 0.5714285969734192
Raw prediction for C: 0.4910251498222351
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.51939457654953
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4425787329673767
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5454530715942383
Calibrated prediction for CHL: 0.5
Raw prediction for CHTR: 0.5758594274520874
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5135836601257324
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.42962804436683655
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.6155093312263489
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.51663738489151
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.26160338521003723
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.44358596205711365
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5062119960784912
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5069890022277832
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.5228171348571777
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.6049099564552307
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4570451080799103
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.40907013416290283
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.4474572539329529
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.5940053462982178
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.32327982783317566
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6153079867362976
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5193135738372803
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5174623131752014
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4829288721084595
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4711073935031891
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5572707653045654
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.555147111415863
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.44254907965660095
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5913758873939514
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6593259572982788
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.42649033665657043
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.48003655672073364
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4994659125804901
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5392953753471375
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4615558683872223
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4976874887943268
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5694162845611572
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5109280347824097
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6242519021034241
Calibrated prediction for NVS: 0.670067310333252
Raw prediction for ORCL: 0.21097718179225922
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4782367944717407
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4736493229866028
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5427915453910828
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47281190752983093
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5044242739677429
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4736526906490326
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4936584532260895
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5326317548751831
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49605515599250793
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.46209263801574707
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.3372343182563782
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.5091257095336914
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5318807363510132
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5343219637870789
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4700130224227905
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4068269729614258
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5029872059822083
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.505576491355896
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5620260238647461
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4796808063983917
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5026252269744873
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.23558978736400604
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4546707570552826
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.31874075531959534
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4819006323814392
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5392212271690369
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.48287272453308105
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5102539658546448
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5330837368965149
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5025694966316223
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5040576457977295
Calibrated prediction for XOM: 0.5078077912330627
Investing 1995.0591344879758 in BP
Investing 1083.732389275282 in HRG
Investing 1315.4998685346743 in PEP
Investing 3088.16020443743 in MA
Investing 2308.9150181834125 in NVS
Investing 2353.8108214963177 in HON
Investing 1790.0131059643418 in CHTR
Investing 2230.841915057426 in CSCO
Investing 1600.8025131047225 in AEP

Simulating Trading Days:  12%|█▏        | 13/108 [05:47<04:15,  2.69s/it]

Raw prediction for AAPL: 0.5097302198410034
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4750191867351532
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4849291443824768
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5690428018569946
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5130491852760315
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4779960513114929
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5457203388214111
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.31627610325813293
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5126993060112
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4534294903278351
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.46870604157447815
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4944000244140625
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5151832699775696
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5529590249061584
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46047675609588623
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5013758540153503
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5712798237800598
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.49498385190963745
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5198869109153748
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48522865772247314
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5593509674072266
Calibrated prediction for CHL: 0.6127496361732483
Raw prediction for CHTR: 0.5754753947257996
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5131182670593262
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.440683513879776
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.6068397760391235
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5186343193054199
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.23294170200824738
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.46444156765937805
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.507334291934967
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5068632960319519
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.5160117745399475
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.6050809025764465
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.465276300907135
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.40970179438591003
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.44683638215065
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.5951700806617737
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.34218478202819824
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6291456818580627
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5165159702301025
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5179702043533325
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48254328966140747
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4983276128768921
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5670632719993591
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5528877973556519
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4081309735774994
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5933709740638733
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6546745300292969
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.42787817120552063
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4816682040691376
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4988233149051666
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5366923213005066
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4620516002178192
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.48715442419052124
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5687998533248901
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5113101005554199
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6280519366264343
Calibrated prediction for NVS: 0.6761956214904785
Raw prediction for ORCL: 0.21059933304786682
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4744633138179779
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47398641705513
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5394769310951233
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47159677743911743
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.504022479057312
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47318485379219055
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49240294098854065
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5236413478851318
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4972406029701233
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.46630236506462097
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.3358652591705322
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.5132449865341187
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.521458089351654
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5346761345863342
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4701482951641083
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.40857183933258057
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5201050043106079
Calibrated prediction for SRE: 0.550561785697937

Simulating Trading Days:  13%|█▎        | 14/108 [05:49<03:33,  2.27s/it]

Raw prediction for T: 0.5056499242782593
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5514430999755859
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48123911023139954
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5077147483825684
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.22084783017635345
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.47654253244400024
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.32321012020111084
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4816910922527313
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5365096926689148
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.4864920675754547
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.4980074167251587
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5331149101257324
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5029392242431641
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5029099583625793
Calibrated prediction for XOM: 0.5078077912330627
Investing 1609.749593347144 in BP
Investing 874.4291047697404 in HRG
Investing 1061.4348927383517 in PEP
Investing 2491.73798778642 in MA
Investing 1929.6809020665569 in NVS
Investing 1899.2148890324738 in HON
Investing 1444.3044918323567 in CHTR
Investing 1799.9951998952133 in CSCO
Investing 1291.636498364126 in AEP
Raw prediction for AAPL: 0.5100722312927246
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47424066066741943
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.48550674319267273
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5643564462661743
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5130063891410828
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48879340291023254
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5451003909111023
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.304143488407135
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5126742124557495
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45331668853759766
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.48547399044036865
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4943600594997406
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5161387920379639
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.531476616859436
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.460734099149704
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5008915066719055
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5681623220443726
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4990331828594208
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5203670859336853
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5130869746208191
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5746632814407349
Calibrated prediction for CHL: 0.6363636255264282
Raw prediction for CHTR: 0.5751969218254089
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5121711492538452
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4577140212059021
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5901049375534058
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5209073424339294
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2275112420320511
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.48356109857559204
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5111624002456665
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.506615936756134
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.49961841106414795
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.6028183698654175
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4714895486831665
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4069460928440094
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.4448580741882324
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.5994724631309509
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.3598094582557678
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6325689554214478
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5166215896606445
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.518488347530365
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4824446737766266
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.506634533405304
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5780969858169556
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5499536991119385
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.39963260293006897
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5937727093696594
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6301177740097046
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.42648380994796753
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4844640791416168
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4979386329650879
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5341218709945679
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46251368522644043
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.484556645154953
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5691388249397278
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5121339559555054
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6329311728477478
Calibrated prediction for NVS: 0.6820799112319946
Raw prediction for ORCL: 0.21381863951683044
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4752427637577057
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47404512763023376
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5385525822639465
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4708031117916107
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5040411949157715
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.472671777009964
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4910159111022949
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5165895819664001
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4979647099971771
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4717871844768524
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.3347887098789215
Calibrated prediction for REX: 0.4000000059604645
Raw prediction for SLB: 0.51863032579422
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.515789270401001
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5364578366279602
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4702460467815399
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4110923409461975
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5429835319519043
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5057632923126221
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5284255743026733
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48237714171409607
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5130881071090698
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.22116975486278534
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4771457612514496
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3264620304107666
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48151469230651855
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.530590832233429
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.49705180525779724
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.49259257316589355
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.533377468585968
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5034077167510986
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5016994476318359
Calibrated prediction for XOM: 0.5078077912330627
Investing 1566.9197771220342 in BP
Investing 851.1635993681815 in HRG
Investing 1033.1938162511847 in PEP
Investing 1281.423662951377 in MA
Investing 1940.6705263998804 in NVS
Investing 1848.6834119596224 in HON
Investing 1405.8765921056317 in CHTR
Investing 1752.1036123239492 in CSCO
Investing 1257.270560902044 in AEP

Simulating Trading Days:  14%|█▍        | 15/108 [05:50<03:04,  1.98s/it]

Raw prediction for AAPL: 0.510291576385498
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47344455122947693
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4860793650150299
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.56431645154953
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5128921866416931
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4954068958759308
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5446649789810181
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2840535640716553
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5126966238021851
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45314276218414307
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5030145049095154
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49454909563064575
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5166165828704834
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.49771711230278015
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46277716755867004
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5004082918167114
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5677435994148254
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5017464756965637
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5204355120658875
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5318087339401245
Calibrated prediction for CELG: 0.610562801361084
Raw prediction for CHL: 0.5860148668289185
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.574377715587616
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5111275315284729
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.47755667567253113
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5655403733253479
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5229368209838867
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2443995475769043
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5077330470085144
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5202935338020325
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5065029263496399
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.4734571576118469
Calibrated prediction for EXC: 0.4000000059604645
Raw prediction for FB: 0.5986473560333252
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4789038300514221
Calibrated prediction for GD: 0.5584369897842407
Raw prediction for GE: 0.4022725820541382
Calibrated prediction for GE: 0.380952388048172
Raw prediction for GMRE: 0.4430902600288391
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6064395904541016
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.3770023286342621
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6230596899986267
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5185431838035583
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5186626315116882
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48293939232826233
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.49621641635894775
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.58321213722229
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5444811582565308
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.415434330701828
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5923069715499878
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5908871293067932
Calibrated prediction for MA: 0.5679137110710144
Raw prediction for MCD: 0.42440587282180786
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.48830515146255493
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4970448613166809
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5324509143829346
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4628376364707947
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.48461976647377014
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5704934597015381
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5131025314331055
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6344990730285645
Calibrated prediction for NVS: 0.6820799112319946
Raw prediction for ORCL: 0.21824884414672852
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4772852063179016
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47390779852867126
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5392774939537048
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4705289900302887
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5046719312667847
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4721735417842865
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49150142073631287
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5132172107696533
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4986231327056885
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.47765496373176575
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.3303051292896271
Calibrated prediction for REX: 0.37469935417175293
Raw prediction for SLB: 0.5224310159683228
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5099629163742065
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5380349159240723
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4701141119003296
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.41398194432258606
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5522680878639221
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5059094429016113
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4951273500919342
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48307493329048157
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5179716944694519
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.23247934877872467
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4619031250476837
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.32888349890708923
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4814612865447998
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5235220789909363
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5075049996376038
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.4916582405567169
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5334993600845337
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5042230486869812
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5042068958282471
Calibrated prediction for XOM: 0.5078077912330627
Investing 1811.6102934143123 in BP
Investing 984.0814829889545 in HRG
Investing 1194.5375761677474 in PEP
Investing 1169.715529395247 in C
Investing 2243.726036957145 in NVS
Investing 2137.374195711304 in HON
Investing 1625.418571336623 in CHTR
Investing 2240.5875947513964 in CHL
Investing 1453.6061915820335 in AEP

Simulating Trading Days:  15%|█▍        | 16/108 [05:51<02:43,  1.78s/it]

Raw prediction for AAPL: 0.5104414224624634
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47297754883766174
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4863201379776001
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5617350339889526
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5127307772636414
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5010442137718201
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5443360805511475
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2599709928035736
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5128373503684998
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45268866419792175
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5172238945960999
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49481508135795593
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5170414447784424
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4691954255104065
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4650104343891144
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.5000218749046326
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5714654326438904
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5048547387123108
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.520646333694458
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.542713463306427
Calibrated prediction for CELG: 0.610562801361084
Raw prediction for CHL: 0.591224193572998
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5732707977294922
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.510287880897522
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4951828122138977
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.5367518067359924
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5243911743164062
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.26844537258148193
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5315430164337158
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5283248424530029
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5066657066345215
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.4434513747692108
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5941050052642822
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4822039008140564
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4039810001850128
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.4423447549343109
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6151789426803589
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3911034166812897
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.5947160720825195
Calibrated prediction for HON: 0.6222428679466248
Raw prediction for HRG: 0.5220040678977966
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5188003182411194
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4840277135372162
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.46757593750953674
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5840053558349609
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5391896367073059
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.44959673285484314
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5893846750259399
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5427786111831665
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.42303407192230225
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4935120940208435
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49616482853889465
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5316588282585144
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.463162899017334
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4862135946750641
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5715686678886414
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5135271549224854
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6301965117454529
Calibrated prediction for NVS: 0.6796541810035706
Raw prediction for ORCL: 0.22494815289974213
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4800979793071747
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47374027967453003
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.543011486530304
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47016674280166626
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5059272646903992
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47180336713790894
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49284207820892334
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5147997736930847
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49879008531570435
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.48039019107818604
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.32542547583580017
Calibrated prediction for REX: 0.2990095317363739
Raw prediction for SLB: 0.5220460891723633
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5091707706451416
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5400793552398682
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4698062837123871
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.41757699847221375
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5559263229370117
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.505998969078064
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4555205702781677
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.48394641280174255
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5220279097557068
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.27114611864089966
Calibrated prediction for UL: 0.4137931168079376
Raw prediction for UN: 0.4440455436706543
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3347098231315613
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4815966784954071
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5187209844589233
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.522124171257019
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.4961996376514435
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5335604548454285
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5050171613693237
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5081402659416199
Calibrated prediction for XOM: 0.5078077912330627
Investing 1887.3582340506728 in BP
Investing 1469.416709716875 in CODI
Investing 1244.4841688407903 in PEP
Investing 1218.6242504398103 in C
Investing 2306.591505936665 in NVS
Investing 1671.3748838283198 in HON
Investing 1693.3813721102917 in CHTR
Investing 2334.272145305548 in CHL
Investing 1703.6344069415775 in SRE

Simulating Trading Days:  16%|█▌        | 17/108 [05:53<02:28,  1.63s/it]

Raw prediction for AAPL: 0.5104549527168274
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4729144871234894
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.48573052883148193
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5561893582344055
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5125407576560974
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49730509519577026
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5437735319137573
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.24103516340255737
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5133742690086365
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45190298557281494
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5217249393463135
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4951309859752655
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5170792937278748
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.48228392004966736
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4687209129333496
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4997028708457947
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5702335238456726
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.5022116899490356
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5205303430557251
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5381842851638794
Calibrated prediction for CELG: 0.610562801361084
Raw prediction for CHL: 0.6151747703552246
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.572306215763092
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5098410248756409
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4988628327846527
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.4929879605770111
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5254030227661133
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.25968778133392334
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5424045324325562
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5326008200645447
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.506976306438446
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.41810885071754456
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5887534618377686
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.48236727714538574
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4088488519191742
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.4376439154148102
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6246098875999451
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3962995707988739
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.5300707221031189
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5241161584854126
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5188288688659668
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48589932918548584
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.44023585319519043
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5826696157455444
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5308637022972107
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.46985116600990295
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5859622359275818
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.49601277709007263
Calibrated prediction for MA: 0.5
Raw prediction for MCD: 0.4236217141151428
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.49922776222229004
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4951589107513428
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5310520529747009
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4630989730358124
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.49603262543678284
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5723205208778381
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5132759809494019
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6189143657684326
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.23004263639450073
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4847148358821869
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47328534722328186
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5444449782371521
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46859344840049744
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5069403052330017
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47149398922920227
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4942593276500702
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5158710479736328
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4981839656829834
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.48468050360679626
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.32527002692222595
Calibrated prediction for REX: 0.29659831523895264
Raw prediction for SLB: 0.5318546295166016
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5130156874656677
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5387392044067383
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4694199562072754
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.42183732986450195
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.549938976764679
Calibrated prediction for SRE: 0.550561785697937

Simulating Trading Days:  17%|█▋        | 18/108 [05:54<02:18,  1.54s/it]

Raw prediction for T: 0.5061020851135254
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4143363833427429
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.4836561679840088
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.525551974773407
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.2605544626712799
Calibrated prediction for UL: 0.4137931168079376
Raw prediction for UN: 0.4181617796421051
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.34361666440963745
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48185744881629944
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5090424418449402
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5394001603126526
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.5090696215629578
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5335938930511475
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5055791735649109
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.511114776134491
Calibrated prediction for XOM: 0.5078077912330627
Investing 1957.2706926793835 in BP
Investing 1523.8475713694272 in CODI
Investing 1290.5829678914804 in PEP
Investing 1263.7651335831051 in C
Investing 2220.1854440085535 in NVS
Investing 1444.915480883193 in HON
Investing 1756.1084437305021 in CHTR
Investing 2420.739410418528 in CHL
Investing 1570.4816912464614 in AEP
Raw prediction for AAPL: 0.510323703289032
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4732462465763092
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4837467670440674
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5557791590690613
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5123487710952759
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49150505661964417
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5432930588722229
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2316979616880417
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.514079213142395
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45102646946907043
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5196691751480103
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4955906271934509
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5168296694755554
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.513721764087677
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47270438075065613
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49940139055252075
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5641801357269287
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4959733784198761
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5205480456352234
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5066678524017334
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6235964298248291
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5720439553260803
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5098080635070801
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5034118294715881
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.44326844811439514
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.525977373123169
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.23564130067825317
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5402206182479858
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5347166657447815
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5072516202926636
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.40370744466781616
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5835919380187988
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.483196496963501
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.41502100229263306
Calibrated prediction for GE: 0.4444444477558136
Raw prediction for GMRE: 0.4302595257759094
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.634463906288147
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.4050731956958771
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.462191641330719
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5232675671577454
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5186204314231873
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4881834089756012
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4183819890022278
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5821705460548401
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5229703187942505
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5060908198356628
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.589023232460022
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.46612462401390076
Calibrated prediction for MA: 0.5
Raw prediction for MCD: 0.42589500546455383
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5042071342468262
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4945584237575531
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5304011106491089
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4628793001174927
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.512056291103363
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5719201564788818
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5125659704208374
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.6006803512573242
Calibrated prediction for NVS: 0.6666666865348816
Raw prediction for ORCL: 0.23859785497188568
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4840910732746124
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47242963314056396
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5448381900787354
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4667400121688843
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5073553323745728
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4713294208049774
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4948829114437103
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5133442282676697
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49722832441329956
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4892583191394806
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.31890183687210083
Calibrated prediction for REX: 0.19781936705112457
Raw prediction for SLB: 0.5459805727005005
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.52290278673172
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.534626841545105
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4690077006816864
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4266720116138458
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5413773059844971
Calibrated prediction for SRE: 0.550561785697937

Simulating Trading Days:  18%|█▊        | 19/108 [05:55<02:10,  1.46s/it]

Raw prediction for T: 0.5063305497169495
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.37879109382629395
Calibrated prediction for TM: 0.2487177550792694
Raw prediction for TOT: 0.48274946212768555
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.528860330581665
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.2388262301683426
Calibrated prediction for UL: 0.18204978108406067
Raw prediction for UN: 0.4047381281852722
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3600693643093109
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48222213983535767
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4988037347793579
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5567383170127869
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.526770830154419
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5343165397644043
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5059564709663391
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5131878852844238
Calibrated prediction for XOM: 0.5078077912330627
Investing 1634.8048067427612 in BP
Investing 1272.7893713095616 in CODI
Investing 1077.955771422232 in PEP
Investing 1055.5562512139434 in C
Investing 1854.4036087092463 in NVS
Investing 1026.5133229916673 in GD
Investing 1466.784607622207 in CHTR
Investing 2021.9157415606935 in CHL
Investing 1311.740387956538 in AEP
Raw prediction for AAPL: 0.5102413892745972
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47380372881889343
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.48094743490219116
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5545379519462585
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5121585726737976
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48359447717666626
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5428731441497803
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2437160164117813
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5146384239196777
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4502256512641907
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5132380723953247
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4959070086479187
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5165544152259827
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5454208254814148
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4755372405052185
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4990697503089905
Calibrated prediction for BSAC: 0.5124812126159668
Raw prediction for BUD: 0.5596811771392822
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.49122390151023865
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5200636982917786
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.46124067902565
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.620941698551178
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5725278258323669
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5096909999847412
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5030261278152466
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.3962305784225464
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5261226296424866
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.22748178243637085
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5305846333503723
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5363632440567017
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.507262647151947
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.401383638381958
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5791488289833069
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.48689404129981995
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.42331549525260925
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4232143461704254
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6439377069473267
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.40880560874938965
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.4015199542045593
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5189201235771179
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5182673335075378
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4901562035083771
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4128631055355072
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5829274654388428
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5171682834625244
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5203741788864136
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5949770212173462
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.4639153778553009
Calibrated prediction for MA: 0.5
Raw prediction for MCD: 0.42374861240386963
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5085573196411133
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4942355155944824
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5300549268722534
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.463413804769516
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5289976000785828
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.571892499923706
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5122957825660706
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5740610361099243
Calibrated prediction for NVS: 0.5862069129943848
Raw prediction for ORCL: 0.25085967779159546
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4837935268878937
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4710754454135895
Calibrated prediction for PCLN: 0.49423596262931824
Raw prediction for PEP: 0.5477569699287415
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46335670351982117
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5075555443763733
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4712268114089966
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4949188232421875
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5123820304870605
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4960591793060303
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4918467700481415
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.3060770034790039
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5601295232772827
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5324717164039612
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5300102829933167
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4689304232597351
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43219488859176636
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5368286371231079
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5065934062004089
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.35128968954086304
Calibrated prediction for TM: 0.2487177550792694
Raw prediction for TOT: 0.4816228449344635
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.533044159412384
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.21416302025318146
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4087606966495514
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3802855908870697
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48272350430488586
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4947309195995331
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5766744017601013
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.5377767086029053
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5349302291870117
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5063587427139282
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5136950016021729
Calibrated prediction for XOM: 0.5078077912330627
Investing 1628.5076935860088 in BP
Investing 1267.8867072956127 in CODI
Investing 1073.8035879672877 in PEP
Investing 1051.4903485876505 in C
Investing 1310.1654359151485 in JNJ
Investing 1022.5592909719843 in GD
Investing 1461.134692346277 in CHTR
Investing 2014.1275137762432 in CHL
Investing 1306.687688318529 in AEP

Simulating Trading Days:  19%|█▊        | 20/108 [05:56<02:04,  1.41s/it]

Raw prediction for AAPL: 0.5101601481437683
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4743593633174896
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.47727280855178833
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5517050623893738
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5119872689247131
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48043882846832275
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5424043536186218
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2700827419757843
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5150632262229919
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.44974491000175476
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5117560625076294
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49631789326667786
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5166526436805725
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5639665126800537
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47724083065986633
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4987773001194
Calibrated prediction for BSAC: 0.5030344128608704
Raw prediction for BUD: 0.5600844621658325
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.48991164565086365
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5191552042961121
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.432888388633728
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6203444600105286
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5734050273895264
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5093789100646973
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4971563220024109
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.35612019896507263
Calibrated prediction for CSCO: 0.4397865831851959
Raw prediction for CVX: 0.5260046720504761
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.23164841532707214
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5166245102882385
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5396382212638855
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5070092678070068
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.40185001492500305
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5755407810211182
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.49206337332725525
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4323748052120209
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4208263158798218
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6523073315620422
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.40140482783317566
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.3631044030189514
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5145512223243713
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5168600678443909
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4912947416305542
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4187285602092743
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.583914041519165
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5142901539802551
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5424407124519348
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6017914414405823
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.48471468687057495
Calibrated prediction for MA: 0.5
Raw prediction for MCD: 0.42056846618652344
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5124724507331848
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4941258132457733
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.530031144618988
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46460196375846863
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5429316163063049
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5716144442558289
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5121936798095703
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5483664870262146
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.2628462016582489
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4858055114746094
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46954137086868286
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.553749680519104
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4593091309070587
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5075517296791077
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47114962339401245
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49501702189445496
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.511865496635437
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49508246779441833
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4925469160079956
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.2890268862247467
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5695236921310425
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5396227240562439
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5267902612686157
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46880167722702026
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43794870376586914
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5374932289123535
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.506554901599884
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.3369391858577728
Calibrated prediction for TM: 0.2487177550792694
Raw prediction for TOT: 0.48059913516044617
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5357186794281006
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.20089536905288696
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.42356225848197937
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.40289121866226196
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4833012819290161
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4921274185180664
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5944236516952515
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5429283380508423
Calibrated prediction for VZ: 0.5534939765930176
Raw prediction for WFC: 0.5359743237495422
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5067235827445984
Calibrated prediction for WMT: 0.5306313633918762

Simulating Trading Days:  19%|█▉        | 21/108 [05:58<02:00,  1.38s/it]

Raw prediction for XOM: 0.5135779976844788
Calibrated prediction for XOM: 0.5078077912330627
Investing 1870.615304661377 in BP
Investing 1456.3813782305788 in CODI
Investing 1233.4442347206636 in PEP
Investing 1638.731829434643 in V
Investing 1504.945617213802 in JNJ
Investing 1174.5815307779235 in GD
Investing 1678.3592293973306 in CHTR
Investing 2313.564601290244 in CHL
Investing 1500.9508384936225 in AEP
Raw prediction for AAPL: 0.5100167393684387
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4749135971069336
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.46719294786453247
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5480872392654419
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5118498802185059
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4819332957267761
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5421404242515564
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3011358976364136
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5152829885482788
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.44978663325309753
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5131462216377258
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4966125190258026
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.51655113697052
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5735312700271606
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4781625270843506
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49867162108421326
Calibrated prediction for BSAC: 0.49924200773239136
Raw prediction for BUD: 0.5618868470191956
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.489862322807312
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5181991457939148
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.42557018995285034
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6213482618331909
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5748701095581055
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5092389583587646
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.49110278487205505
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.33682191371917725
Calibrated prediction for CSCO: 0.4285714328289032
Raw prediction for CVX: 0.5256479382514954
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.26039788126945496
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5037781000137329
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5430110096931458
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5066580176353455
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.40121108293533325
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5723095536231995
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5018641352653503
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4415518045425415
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.42943572998046875
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6611500382423401
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3972310721874237
Calibrated prediction for HD: 0.35736483335494995
Raw prediction for HON: 0.382913738489151
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5131512880325317
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5156105756759644
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.491854727268219
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.42036959528923035
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5841326713562012
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5141057372093201
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5564499497413635
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.606660783290863
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5160267353057861
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.41773831844329834
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5165048241615295
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.494139164686203
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5303229689598083
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4658430814743042
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5524247884750366
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5710774660110474
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5121864676475525
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5263626575469971
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.28374654054641724
Calibrated prediction for ORCL: 0.22421108186244965
Raw prediction for PCG: 0.49481111764907837
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4678950011730194
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5589818954467773
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4549069106578827
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5075411796569824
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.471161812543869
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4951944649219513
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5139337778091431
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4947050213813782
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4923382103443146
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.27622583508491516
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5765150189399719
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5460703372955322
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5275817513465881
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4686048626899719
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44322192668914795
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5501647591590881
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5063751339912415
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.3393899202346802
Calibrated prediction for TM: 0.2487177550792694
Raw prediction for TOT: 0.48029837012290955
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5367791056632996
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.19462628662586212
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.43044984340667725
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.4263570010662079
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4837607145309448
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.49030187726020813
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.6071031093597412
Calibrated prediction for V: 0.6206896305084229

Simulating Trading Days:  20%|██        | 22/108 [05:59<01:56,  1.36s/it]

Raw prediction for VZ: 0.5483760237693787
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5368070602416992
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5064772963523865
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.512808620929718
Calibrated prediction for XOM: 0.5078077912330627
Investing 1949.3938138486294 in BP
Investing 1517.7149691079667 in CODI
Investing 1285.389120307118 in PEP
Investing 1707.7448703088753 in V
Investing 1568.324427296538 in JNJ
Investing 1224.0474908195133 in GD
Investing 1749.0411262272735 in CHTR
Investing 2410.9973389268253 in CHL
Investing 1564.1614137119668 in AEP
Raw prediction for AAPL: 0.5097861289978027
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4758462607860565
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.45218026638031006
Calibrated prediction for ABBV: 0.5
Raw prediction for AEP: 0.5510268807411194
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5117256045341492
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4878194034099579
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5424339175224304
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3380811810493469
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5154293775558472
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45011016726493835
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5151038765907288
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4967440366744995
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5164008140563965
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5808314085006714
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4779616892337799
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4987949728965759
Calibrated prediction for BSAC: 0.5036686062812805
Raw prediction for BUD: 0.5646048188209534
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4898657500743866
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5177450180053711
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.42942413687705994
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6189929246902466
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5766739249229431
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5092381834983826
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.48467615246772766
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.33090677857398987
Calibrated prediction for CSCO: 0.4285714328289032
Raw prediction for CVX: 0.5247702598571777
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2965373396873474
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.4916645884513855
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5437056422233582
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.506385326385498
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.397981733083725
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.568405032157898
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5105255246162415
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.45022061467170715
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4404953122138977
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6696932911872864
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.40593045949935913
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.4104986786842346
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5128421783447266
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5148152709007263
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4921582043170929
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.42099887132644653
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5831407308578491
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5157942175865173
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5732026696205139
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6091611385345459
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.5579032897949219
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4243410527706146
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5201533436775208
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49432173371315
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5314451456069946
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4664562940597534
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5573731660842896
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5713678002357483
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5122858285903931
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5111454725265503
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3045034408569336
Calibrated prediction for ORCL: 0.2469329535961151
Raw prediction for PCG: 0.5004611611366272
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46630194783210754
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5640893578529358
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4534592926502228
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5072008371353149
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47115036845207214
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49520984292030334
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5180949568748474
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4951678514480591
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.49194326996803284
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.26597920060157776
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5817260146141052
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5492272973060608
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5294113755226135
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46871116757392883
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4477311372756958
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5769601464271545
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5061912536621094
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.35391318798065186
Calibrated prediction for TM: 0.2487177550792694
Raw prediction for TOT: 0.48033055663108826
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.536405622959137
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.19498001039028168
Calibrated prediction for UL: 0.17558681964874268

Simulating Trading Days:  21%|██▏       | 23/108 [06:00<01:54,  1.35s/it]

Raw prediction for UN: 0.42589065432548523
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.45476558804512024
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48385077714920044
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4881986379623413
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.6123201251029968
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5597569346427917
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5373198986053467
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.505555272102356
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5112556219100952
Calibrated prediction for XOM: 0.5078077912330627
Investing 2083.0534609284005 in BP
Investing 1621.7766757254517 in CODI
Investing 1420.7749199464804 in PEP
Investing 1824.8359244849082 in V
Investing 1675.8561574014927 in JNJ
Investing 1333.768710542667 in LMT
Investing 1868.96364675585 in CHTR
Investing 2780.832076486615 in GOOG
Investing 1880.2797918866506 in SRE
Raw prediction for AAPL: 0.509316623210907
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47668081521987915
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.44996222853660583
Calibrated prediction for ABBV: 0.5
Raw prediction for AEP: 0.5437644124031067
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.511662483215332
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49243640899658203
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5424658060073853
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.37232139706611633
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5156135559082031
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4505344033241272
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5142295956611633
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4966728091239929
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5164376497268677
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.580136239528656
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47716280817985535
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49890580773353577
Calibrated prediction for BSAC: 0.5076460838317871
Raw prediction for BUD: 0.5673345923423767
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.48966342210769653
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5175747871398926
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.435871958732605
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6117760539054871
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5786616802215576
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5094192028045654
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4754903316497803
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.32872968912124634
Calibrated prediction for CSCO: 0.4285714328289032
Raw prediction for CVX: 0.523871660232544
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3395063579082489
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.481948584318161
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5392962098121643
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5063925981521606
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.3920527994632721
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5642226934432983
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5177878737449646
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.45590439438819885
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.45094457268714905
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6777272820472717
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4280078411102295
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.44859960675239563
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5134432315826416
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5142875909805298
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49236825108528137
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.431216835975647
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.579820454120636
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.518844723701477
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5791849493980408
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6092179417610168
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.6020127534866333
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.43947309255599976
Calibrated prediction for MCD: 0.44092774391174316
Raw prediction for MDT: 0.522796094417572
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49467748403549194
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5331416726112366
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4665711522102356
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5594355463981628
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.571328341960907
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5122018456459045
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4990488588809967
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3264227509498596
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5047768950462341
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4648687541484833
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5673651099205017
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4548954963684082
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5069884061813354
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47108030319213867
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4951283931732178
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5240967273712158
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4962983727455139
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4914746880531311
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.2582360506057739
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5851207971572876
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5501250624656677
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5299345254898071
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.468673437833786
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45139601826667786
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.601945698261261
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.506179690361023
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.36998721957206726
Calibrated prediction for TM: 0.2487177550792694
Raw prediction for TOT: 0.4806554913520813
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5345122218132019
Calibrated prediction for TSM: 0.5760757327079773

Simulating Trading Days:  22%|██▏       | 24/108 [06:02<01:51,  1.33s/it]

Raw prediction for UL: 0.18445554375648499
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.41011473536491394
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.5085254907608032
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48370492458343506
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4861604869365692
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.6103290319442749
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5734333395957947
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5375480651855469
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.5045709609985352
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5106209516525269
Calibrated prediction for XOM: 0.5078077912330627
Investing 1744.035555627218 in BP
Investing 947.3743344284417 in HRG
Investing 1189.5431506715645 in PEP
Investing 1527.843041565095 in V
Investing 1403.1097998427556 in JNJ
Investing 1116.6972417178079 in LMT
Investing 1564.7889568154244 in CHTR
Investing 2328.2503817543766 in GOOG
Investing 1574.2633941406948 in SRE
Raw prediction for AAPL: 0.50885009765625
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4773654341697693
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.45315492153167725
Calibrated prediction for ABBV: 0.5
Raw prediction for AEP: 0.5421985983848572
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5116921663284302
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49510854482650757
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.542522668838501
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4085986018180847
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5156645178794861
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4507875442504883
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5165441632270813
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49636223912239075
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5166341662406921
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5752704739570618
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47671663761138916
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49882200360298157
Calibrated prediction for BSAC: 0.504638671875
Raw prediction for BUD: 0.56880122423172
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4886392056941986
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5174755454063416
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4460645616054535
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6097817420959473
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5807822942733765
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5099037289619446
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4647868573665619
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.3286057114601135
Calibrated prediction for CSCO: 0.4285714328289032
Raw prediction for CVX: 0.5230774283409119
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3632558584213257
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.4735792577266693
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5299757122993469
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5066336393356323
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.38808321952819824
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5617757439613342
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.521806538105011
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.456984281539917
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4525717794895172
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6846718192100525
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4493027329444885
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.49536770582199097
Calibrated prediction for HON: 0.5848817825317383
Raw prediction for HRG: 0.5160386562347412
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5139305591583252
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49252238869667053
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4457376003265381
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5768513083457947
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5214917659759521
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5893101096153259
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6072524785995483
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6397014260292053
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.44754499197006226
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.5253604054450989
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49504178762435913
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5354703664779663
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4665210247039795
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5582235455513
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5721903443336487
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5120638608932495
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4906904399394989
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3516554534435272
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.502305269241333
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4636353552341461
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5697126984596252
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4588378667831421
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5063857436180115
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47087299823760986
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4949723482131958
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.533287525177002
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4978211522102356
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4907167851924896
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.25263893604278564
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5873240828514099
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.548105001449585
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5309321284294128
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46871623396873474
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4539851248264313
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6263377666473389
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5063984990119934
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.3790512681007385
Calibrated prediction for TM: 0.2487177550792694

Simulating Trading Days:  23%|██▎       | 25/108 [06:03<01:49,  1.32s/it]

Raw prediction for TOT: 0.481129914522171
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5313639044761658
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.18264348804950714
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4033200144767761
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.5668240189552307
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4835076332092285
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4845089018344879
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.6054405570030212
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5820937752723694
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5378106832504272
Calibrated prediction for WFC: 0.523809552192688
Raw prediction for WMT: 0.5039539933204651
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5114996433258057
Calibrated prediction for XOM: 0.5078077912330627
Investing 1671.9619213765588 in BP
Investing 908.2233486255742 in HRG
Investing 1140.384349011672 in PEP
Investing 2588.0367051149938 in MA
Investing 1345.1251892646683 in JNJ
Investing 1066.8600489152586 in HON
Investing 1500.1228285423538 in CHTR
Investing 2232.0336125967237 in GOOG
Investing 1509.2057273302883 in SRE
Raw prediction for AAPL: 0.5085087418556213
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47782012820243835
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.45851796865463257
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5392569899559021
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5117950439453125
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49562883377075195
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5427243709564209
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4369037449359894
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5153073072433472
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4508640170097351
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.523245632648468
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49607473611831665
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5171512961387634
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5660069584846497
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4763965606689453
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49861666560173035
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5688790678977966
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.48738718032836914
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5176230669021606
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4493896961212158
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6112991571426392
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5806502103805542
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5106595754623413
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.45149245858192444
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.32981836795806885
Calibrated prediction for CSCO: 0.4285714328289032
Raw prediction for CVX: 0.5223988890647888
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.34202882647514343
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.46801817417144775
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5214728713035583
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5069809556007385
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.38593462109565735
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5613937973976135
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5214528441429138
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4552840292453766
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.44889795780181885
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6906358003616333
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.45685315132141113
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.523810863494873
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5229879021644592
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5135611295700073
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4924735426902771
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.45652616024017334
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5714704394340515
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5234363079071045
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5818243622779846
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6037400960922241
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6694591045379639
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4514579176902771
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.5267040729522705
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49530228972435
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5378488302230835
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4665306806564331
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.555127739906311
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5725575089454651
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5119528770446777
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.48498156666755676
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.36958053708076477
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.4938056170940399
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46247100830078125
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5682671666145325
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4640141725540161
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5056358575820923
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4706553518772125
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4946214556694031
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5365809202194214
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49946847558021545
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4890531897544861
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.24978846311569214
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5867374539375305
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5436685681343079
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5321197509765625
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4690284729003906
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45568376779556274
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6470459699630737
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5067806839942932
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.38653162121772766
Calibrated prediction for TM: 0.2487177550792694
Raw prediction for TOT: 0.4812433123588562
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5277639627456665
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.17455939948558807
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.39720577001571655
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.6115202307701111
Calibrated prediction for UNH: 0.692307710647583
Raw prediction for UPS: 0.4833378493785858
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4823455214500427
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5980873107910156
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5875622630119324
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5379207134246826
Calibrated prediction for WFC: 0.523809552192688

Simulating Trading Days:  24%|██▍       | 26/108 [06:04<01:48,  1.32s/it]

Raw prediction for WMT: 0.5038902759552002
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5120577216148376
Calibrated prediction for XOM: 0.5078077912330627
Investing 1701.2335992478895 in BP
Investing 924.1239627222762 in HRG
Investing 1160.3494946809546 in PEP
Investing 2633.3464551653624 in MA
Investing 2428.6743879202904 in UNH
Investing 1255.9012779100412 in HON
Investing 1526.3860535854028 in CHTR
Investing 2271.110680124746 in GOOG
Investing 2164.759340613605 in SRE
Raw prediction for AAPL: 0.5081745386123657
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47824811935424805
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.47740307450294495
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5343078970909119
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5118982195854187
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4964069426059723
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5428393483161926
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4470796287059784
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5144785642623901
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45086944103240967
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5271106362342834
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4959414601325989
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5173813104629517
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5466975569725037
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4760778546333313
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49852579832077026
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5693444013595581
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.48638081550598145
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5177545547485352
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.46335285902023315
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.619074821472168
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5804333090782166
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5115310549736023
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4392611086368561
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.33036357164382935
Calibrated prediction for CSCO: 0.4285714328289032
Raw prediction for CVX: 0.5218309164047241
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2655188739299774
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.463399201631546
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5133879780769348
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5072099566459656
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.38821935653686523
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5636049509048462
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5160272717475891
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4514952301979065
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.44433313608169556
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6952167749404907
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.46096864342689514
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5557228922843933
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5301694869995117
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.513259768486023
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4922316074371338
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.46976739168167114
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5666073560714722
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5248762369155884
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5734140276908875
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5990056395530701
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6953859925270081
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4563753604888916
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.5265344977378845
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49546313285827637
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5396687388420105
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4663814902305603
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.550119936466217
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5730365514755249
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5117458701133728
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.48130473494529724
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3845529854297638
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.4871310889720917
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.461417555809021
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5646228194236755
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46868428587913513
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5048651099205017
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.470407098531723
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4938597083091736
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5320587158203125
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5008339881896973
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4853917360305786
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.2493659257888794
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5812376141548157
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5465186834335327
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5323612093925476
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4691948890686035
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4563373327255249
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6560781002044678
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5072857141494751
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.3917488753795624
Calibrated prediction for TM: 0.2487177550792694
Raw prediction for TOT: 0.48072537779808044
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5237455368041992
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.1712110936641693
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3935355246067047
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.6381931900978088
Calibrated prediction for UNH: 0.7667906284332275
Raw prediction for UPS: 0.4832126796245575
Calibrated prediction for UPS: 0.4850730001926422

Simulating Trading Days:  25%|██▌       | 27/108 [06:06<01:46,  1.32s/it]

Raw prediction for UTX: 0.4799065887928009
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5909833908081055
Calibrated prediction for V: 0.5555555820465088
Raw prediction for VZ: 0.5809326171875
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5379027724266052
Calibrated prediction for WFC: 0.523809552192688
Raw prediction for WMT: 0.5036284327507019
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5109238028526306
Calibrated prediction for XOM: 0.5078077912330627
Investing 1712.9152469256069 in BP
Investing 930.4695289912648 in HRG
Investing 1168.3171212231723 in PEP
Investing 2651.428525444369 in MA
Investing 3258.1271495926394 in UNH
Investing 1264.5250179143688 in HON
Investing 1536.867097520844 in CHTR
Investing 2286.705431377042 in GOOG
Investing 2179.6238224433055 in SRE
Raw prediction for AAPL: 0.507691502571106
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47850728034973145
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4996394217014313
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5375264286994934
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5120189189910889
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4992132782936096
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5424922704696655
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4329686462879181
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.513383686542511
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45090797543525696
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5256920456886292
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49576133489608765
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5173903703689575
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5242406129837036
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4747719466686249
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49841490387916565
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5707715153694153
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.48555031418800354
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.517988383769989
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4881843328475952
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6109906435012817
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5796579122543335
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5121856927871704
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4273383915424347
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.3328556716442108
Calibrated prediction for CSCO: 0.4285714328289032
Raw prediction for CVX: 0.521248996257782
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.17402072250843048
Calibrated prediction for D: 0.3333333432674408
Raw prediction for DHR: 0.4639297425746918
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5034221410751343
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.507125198841095
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3975491225719452
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5652905702590942
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5089468359947205
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4484735429286957
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4445090591907501
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6983180046081543
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4618322253227234
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5664433240890503
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5345023274421692
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5128982067108154
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4919014573097229
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4848586916923523
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5632372498512268
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5259314775466919
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5686572790145874
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5944863557815552
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7182402014732361
Calibrated prediction for MA: 0.782608687877655
Raw prediction for MCD: 0.4594915509223938
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.5248695611953735
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4955587387084961
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5407602787017822
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4660119414329529
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5437791347503662
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.572458028793335
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5114771127700806
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4789876341819763
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3953303396701813
Calibrated prediction for ORCL: 0.380952388048172
Raw prediction for PCG: 0.4787762463092804
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4605371654033661
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5600872039794922
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4720112085342407
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5042370557785034
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4701612591743469
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49242594838142395
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5187661051750183
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5020024180412292
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.47730541229248047
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.24817241728305817
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5682700276374817
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.540594220161438
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5323027968406677
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4693754315376282
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45675724744796753
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6590400338172913
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5076345205307007
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.39487382769584656
Calibrated prediction for TM: 0.27272728085517883
Raw prediction for TOT: 0.47993648052215576
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5192416906356812
Calibrated prediction for TSM: 0.5760757327079773

Simulating Trading Days:  26%|██▌       | 28/108 [06:07<01:45,  1.32s/it]

Raw prediction for UL: 0.1561667025089264
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3861609697341919
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.6321727633476257
Calibrated prediction for UNH: 0.7582796216011047
Raw prediction for UPS: 0.4831368625164032
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4769357740879059
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5824560523033142
Calibrated prediction for V: 0.5471526980400085
Raw prediction for VZ: 0.5653736591339111
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.537828803062439
Calibrated prediction for WFC: 0.523809552192688
Raw prediction for WMT: 0.5019364356994629
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5097288489341736
Calibrated prediction for XOM: 0.5078077912330627
Investing 1841.8842042124993 in BP
Investing 1000.5265181835861 in HRG
Investing 1214.4995537285108 in PEP
Investing 3538.6470614762393 in MA
Investing 3403.5714173764554 in UNH
Investing 1359.733740772265 in HON
Investing 1652.5810228954626 in CHTR
Investing 2458.87624697127 in GOOG
Investing 2343.7322406284534 in SRE
Raw prediction for AAPL: 0.5071704387664795
Calibrated prediction for AAPL: 0.5173717737197876
Raw prediction for ABB: 0.47868138551712036
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5144867300987244
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5448070764541626
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5121707916259766
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5032687783241272
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.541824460029602
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.39258143305778503
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5125417709350586
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45086947083473206
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5153042674064636
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4955485463142395
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5171852707862854
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.49821847677230835
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4725354313850403
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49823278188705444
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5733720660209656
Calibrated prediction for BUD: 0.5714285969734192
Raw prediction for C: 0.484870582818985
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5183694362640381
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5135865211486816
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5946252942085266
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5776312947273254
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5124526023864746
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4136878252029419
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.3454393744468689
Calibrated prediction for CSCO: 0.4285714328289032
Raw prediction for CVX: 0.5206693410873413
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.13776342570781708
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.4724920094013214
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.49507978558540344
Calibrated prediction for DIS: 0.5384615659713745
Raw prediction for DUK: 0.5068696737289429
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.4139467775821686
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5668357014656067
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5012462139129639
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4470548927783966
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.44893503189086914
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6999799609184265
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.46101972460746765
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5701974630355835
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5360274314880371
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5126470923423767
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4913325011730194
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5079624056816101
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5607470273971558
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5272889733314514
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5851929187774658
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5899866819381714
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7440115809440613
Calibrated prediction for MA: 0.8235294222831726
Raw prediction for MCD: 0.4594529867172241
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.5211334228515625
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4957553446292877
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5413654446601868
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46554264426231384
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5360106229782104
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5731964707374573
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.511354923248291
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4775356352329254
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.40711721777915955
Calibrated prediction for ORCL: 0.380952388048172
Raw prediction for PCG: 0.4749886989593506
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45980486273765564
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5580978393554688
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4743656814098358
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5039475560188293
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4699922502040863
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49067825078964233
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5115115642547607
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5019888281822205
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.47078895568847656
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.24621985852718353
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5464692711830139
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5340763926506042
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5324671864509583
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4694337248802185
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4563940167427063
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6552862524986267
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5078047513961792
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.39875420928001404
Calibrated prediction for TM: 0.27272728085517883
Raw prediction for TOT: 0.47944843769073486
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.514305055141449
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.14415737986564636
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.38570284843444824
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.6150271892547607
Calibrated prediction for UNH: 0.692307710647583
Raw prediction for UPS: 0.48300740122795105
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4732699692249298
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.567615270614624
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.5389872193336487
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5375866293907166
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  27%|██▋       | 29/108 [06:08<01:44,  1.33s/it]

Raw prediction for WMT: 0.4997127652168274
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.508574903011322
Calibrated prediction for XOM: 0.5078077912330627
Investing 1672.39734504186 in BP
Investing 908.459874310947 in HRG
Investing 1102.7434974276773 in PEP
Investing 3674.706989901381 in MA
Investing 2387.507864954424 in UNH
Investing 1234.613496782569 in HON
Investing 1500.5135007054305 in CHTR
Investing 2232.6148939310933 in GOOG
Investing 2128.066231173251 in SRE
Raw prediction for AAPL: 0.5066849589347839
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4785401523113251
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5183849334716797
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5477655529975891
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5122393369674683
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5095235705375671
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5411409735679626
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.38513681292533875
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5121573805809021
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45080816745758057
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49729272723197937
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49560269713401794
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5165797472000122
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4858013093471527
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4701281189918518
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4980938732624054
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5763369798660278
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.48435649275779724
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.518587052822113
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5276638865470886
Calibrated prediction for CELG: 0.5814951658248901
Raw prediction for CHL: 0.5671123266220093
Calibrated prediction for CHL: 0.6363636255264282
Raw prediction for CHTR: 0.5751999616622925
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5122637152671814
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.39720624685287476
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.36961859464645386
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.520124614238739
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.134578138589859
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.48499616980552673
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4871510863304138
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5066332817077637
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.4280315339565277
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5703914761543274
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5026640892028809
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4490720331668854
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.45228520035743713
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6998910307884216
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.45753246545791626
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5709479451179504
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5364671945571899
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5124545097351074
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.490696519613266
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5397446155548096
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5582742691040039
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5278967022895813
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.5980579257011414
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5886898636817932
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.7691080570220947
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.4572603702545166
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.5159797668457031
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4961991608142853
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5416831970214844
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46487388014793396
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5272047519683838
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5748382806777954
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5112765431404114
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4737168848514557
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.41528555750846863
Calibrated prediction for ORCL: 0.380952388048172
Raw prediction for PCG: 0.48180341720581055
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4596385061740875
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5577623248100281
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4762403070926666
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5036414861679077
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.470020592212677
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48904088139533997
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5103104710578918
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5004099011421204
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4655363857746124
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.24193845689296722
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5160964727401733
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5339067578315735
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5321775078773499
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46949437260627747
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45693641901016235
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6467443704605103
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5078953504562378
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4077082872390747
Calibrated prediction for TM: 0.27272728085517883
Raw prediction for TOT: 0.47928768396377563
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.509614884853363
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.12931042909622192
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3916543424129486
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.5841009616851807
Calibrated prediction for UNH: 0.4599984586238861
Raw prediction for UPS: 0.4828188121318817
Calibrated prediction for UPS: 0.4850730001926422

Simulating Trading Days:  28%|██▊       | 30/108 [06:10<01:43,  1.32s/it]

Raw prediction for UTX: 0.47304025292396545
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5470898747444153
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.5118527412414551
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5372848510742188
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4976363480091095
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5077036023139954
Calibrated prediction for XOM: 0.5078077912330627
Investing 1801.606092470639 in BP
Investing 978.6471194635548 in HRG
Investing 1438.2667714479942 in BUD
Investing 4066.0365852681693 in MA
Investing 968.835467232759 in ABBV
Investing 1329.9992398602392 in HON
Investing 1616.4425713302514 in CHTR
Investing 2529.0976435451958 in INTC
Investing 2292.479773798491 in SRE
Raw prediction for AAPL: 0.5062339305877686
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4783404767513275
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5097963809967041
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5493107438087463
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5122929811477661
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.518438458442688
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5407072305679321
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4083922803401947
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5122420787811279
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4507870078086853
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4740658700466156
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4955105483531952
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5156398415565491
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4858366847038269
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4682132601737976
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4980654716491699
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5787075757980347
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.48325082659721375
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5187844038009644
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.528293251991272
Calibrated prediction for CELG: 0.6031507849693298
Raw prediction for CHL: 0.5313208699226379
Calibrated prediction for CHL: 0.4000000059604645
Raw prediction for CHTR: 0.5729069113731384
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.511539101600647
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.37970834970474243
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.4089416563510895
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5196155309677124
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.160612091422081
Calibrated prediction for D: 0.3333333432674408
Raw prediction for DHR: 0.49614837765693665
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.48314934968948364
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5065484046936035
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.43518850207328796
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.574558436870575
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5083686709403992
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.45040363073349
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4580095410346985
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6977478861808777
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4527073800563812
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5798385143280029
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5347291231155396
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.512274444103241
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4899866580963135
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5686600208282471
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.553778350353241
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5294712781906128
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6020215749740601
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5894613265991211
Calibrated prediction for LMT: 0.568231463432312
Raw prediction for MA: 0.7858228087425232
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.45048925280570984
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.5110438466072083
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49690258502960205
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.541764497756958
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4639885127544403
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5174604058265686
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5752448439598083
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5115658044815063
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.47041764855384827
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.4328075349330902
Calibrated prediction for ORCL: 0.5882353186607361
Raw prediction for PCG: 0.4951547086238861
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4605294167995453
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5583801865577698
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4790510833263397
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5034420490264893
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4701984226703644
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48794013261795044
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5148186087608337
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49787911772727966
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4585358500480652
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.24070975184440613
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.4878489673137665
Calibrated prediction for SLB: 0.48436635732650757
Raw prediction for SNP: 0.5405352115631104
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5341556668281555
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46969932317733765
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45783376693725586
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6374627351760864
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5078790187835693
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.43276408314704895
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.47958722710609436
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5050849914550781
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.1178910955786705
Calibrated prediction for UL: 0.17558681964874268

Simulating Trading Days:  29%|██▊       | 31/108 [06:11<01:41,  1.32s/it]

Raw prediction for UN: 0.40467068552970886
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.5412831902503967
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48252764344215393
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.47930005192756653
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5247494578361511
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.4902191162109375
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5364194512367249
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.495950847864151
Calibrated prediction for WMT: 0.5306313633918762
Raw prediction for XOM: 0.5073613524436951
Calibrated prediction for XOM: 0.5078077912330627
Investing 1705.7583323345036 in BP
Investing 926.5818346289392 in HRG
Investing 1361.749130273461 in BUD
Investing 3849.7182119243657 in MA
Investing 1298.1827504802052 in CELG
Investing 1259.2415705472151 in HON
Investing 1530.4457485518424 in CHTR
Investing 2394.546397680481 in INTC
Investing 2170.5169027834104 in SRE
Raw prediction for AAPL: 0.5057725310325623
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.477995902299881
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4895203113555908
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5426669716835022
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5123046636581421
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5258126854896545
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.540176510810852
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.47433871030807495
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5125380754470825
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45096343755722046
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4545229971408844
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49509263038635254
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5147125720977783
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4894580543041229
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4671954810619354
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49807778000831604
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5802032947540283
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.48160940408706665
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5187810659408569
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5259749889373779
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4995019733905792
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.571022629737854
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5107202529907227
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.36585503816604614
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.46316540241241455
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5191887617111206
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.18615354597568512
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5068463087081909
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.480812668800354
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5063924789428711
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4425830841064453
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5771827697753906
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5151484608650208
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.45755162835121155
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.46181559562683105
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6934112906455994
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4445269703865051
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.6266900897026062
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5313736200332642
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5121639966964722
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4891054928302765
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5850551128387451
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5485436916351318
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5323338508605957
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5940938591957092
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5918142199516296
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7857927083969116
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.44452574849128723
Calibrated prediction for MCD: 0.44897958636283875
Raw prediction for MDT: 0.5052834749221802
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4976881742477417
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5414355993270874
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4632842242717743
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5022691488265991
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5746585130691528
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5115523934364319
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4674299359321594
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.4466838240623474
Calibrated prediction for ORCL: 0.5882353186607361
Raw prediction for PCG: 0.4969762861728668
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.462491899728775
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5593084096908569
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4811534285545349
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5033473372459412
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47049227356910706
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48730313777923584
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5163516402244568
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49553272128105164
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4528137445449829
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.23128999769687653
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.4777567684650421
Calibrated prediction for SLB: 0.48436635732650757
Raw prediction for SNP: 0.5405099391937256
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5359498858451843
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4698028564453125
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45872244238853455
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.624422013759613
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5078354477882385
Calibrated prediction for T: 0.5147916078567505

Simulating Trading Days:  30%|██▉       | 32/108 [06:12<01:40,  1.32s/it]

Raw prediction for TM: 0.46202749013900757
Calibrated prediction for TM: 0.40101000666618347
Raw prediction for TOT: 0.47994229197502136
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.502378523349762
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.1099085807800293
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4189065098762512
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.4870010018348694
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4820960462093353
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4931945502758026
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5017812252044678
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.4799540340900421
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5348734259605408
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4940827488899231
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5069014430046082
Calibrated prediction for XOM: 0.5078077912330627
Investing 1590.295894721634 in BP
Investing 863.8616970537402 in HRG
Investing 1269.5726061914168 in BUD
Investing 3589.131562311988 in MA
Investing 855.2008525282462 in ABBV
Investing 1876.2630248238947 in HON
Investing 1426.8501843899458 in CHTR
Investing 2232.460034792889 in INTC
Investing 1435.4894341658808 in SRE
Raw prediction for AAPL: 0.5053755640983582
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4776514172554016
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4626772105693817
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5339513421058655
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5123082399368286
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5299476385116577
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5395904183387756
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5326141715049744
Calibrated prediction for BA: 0.6067755818367004
Raw prediction for BABA: 0.5129739046096802
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.451394647359848
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4437583088874817
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4945628046989441
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.513614296913147
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4984096884727478
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46711498498916626
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4981901943683624
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.580928385257721
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4795939326286316
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5186526775360107
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5242382884025574
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.47249865531921387
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5695273280143738
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5099793672561646
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.3550979495048523
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.4948109984397888
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5187443494796753
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.20854714512825012
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5175720453262329
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4786960184574127
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.506037175655365
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4559183716773987
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5786365270614624
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5185182094573975
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.46613460779190063
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.46223685145378113
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6870109438896179
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4355873763561249
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.6893572807312012
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5295438766479492
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5120902061462402
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4879434108734131
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5869959592819214
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5421912670135498
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5357720851898193
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5705565810203552
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5928559303283691
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7702258229255676
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.4375838339328766
Calibrated prediction for MCD: 0.4162680208683014
Raw prediction for MDT: 0.49913811683654785
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4981742203235626
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5405562520027161
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4625183343887329
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.48115697503089905
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5733845829963684
Calibrated prediction for NEE: 0.5611634254455566
Raw prediction for NGG: 0.5113570094108582
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.46320247650146484
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.44021183252334595
Calibrated prediction for ORCL: 0.5882353186607361
Raw prediction for PCG: 0.4908156096935272
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4648666977882385
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5567366480827332
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.48028048872947693
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5032317042350769
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47062957286834717
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48661893606185913
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5142464637756348
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.493233859539032
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4491952359676361
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.21836170554161072
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.48053795099258423
Calibrated prediction for SLB: 0.48436635732650757
Raw prediction for SNP: 0.5361515283584595
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5366204977035522
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46983274817466736
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4579167068004608
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.591796875
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.507839560508728
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4832601249217987
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48001688718795776
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5002264976501465
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.10282718390226364
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.42791226506233215
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.4469614326953888
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4817533493041992
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5029363036155701
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.48082467913627625
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.4846111834049225
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5339266657829285
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  31%|███       | 33/108 [06:14<01:38,  1.32s/it]

Raw prediction for WMT: 0.49248480796813965
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5073373317718506
Calibrated prediction for XOM: 0.5078077912330627
Investing 1590.7136688940934 in BP
Investing 864.0886353906898 in HRG
Investing 1269.9061256620319 in BUD
Investing 3590.0744349391953 in MA
Investing 855.4255156425995 in ABBV
Investing 1876.7559231801777 in HON
Investing 1427.2250210206544 in CHTR
Investing 2233.0465068743924 in INTC
Investing 1435.8665403461982 in SRE
Raw prediction for AAPL: 0.5050635933876038
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47742390632629395
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.43474331498146057
Calibrated prediction for ABBV: 0.38885557651519775
Raw prediction for AEP: 0.53730309009552
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5123242735862732
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5277963876724243
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5388687252998352
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5610067844390869
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.513566255569458
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4519677758216858
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.44586873054504395
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49410003423690796
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5126914978027344
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5026264786720276
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46743348240852356
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4981646239757538
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5806185007095337
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.47584041953086853
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5183578133583069
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5209770798683167
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4462423324584961
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.568182110786438
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5093996524810791
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.3505169451236725
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.49675998091697693
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5182279944419861
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.24080760776996613
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5250045657157898
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4761770963668823
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5055305361747742
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.48718124628067017
Calibrated prediction for EXC: 0.4615384638309479
Raw prediction for FB: 0.5800672769546509
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5155482292175293
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.47543126344680786
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.460916131734848
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6790552139282227
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4309886395931244
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7459788918495178
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5286415815353394
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5120363831520081
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4868239760398865
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5810215473175049
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5393766164779663
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5369284152984619
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5388662815093994
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.59360271692276
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7420430183410645
Calibrated prediction for MA: 0.8235294222831726
Raw prediction for MCD: 0.42886680364608765
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.49384546279907227
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49829933047294617
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5389083623886108
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46145811676979065
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.46265530586242676
Calibrated prediction for MSFT: 0.5167069435119629
Raw prediction for NEE: 0.5719990134239197
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5108534097671509
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4600907862186432
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.4076085388660431
Calibrated prediction for ORCL: 0.380952388048172
Raw prediction for PCG: 0.49612486362457275
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4670800268650055
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5527554154396057
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4802461266517639
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5031581521034241
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4706592559814453
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4857162833213806
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5158379673957825
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4910256862640381
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4469548761844635
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.2046150416135788
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.48516783118247986
Calibrated prediction for SLB: 0.48436635732650757
Raw prediction for SNP: 0.5272619724273682
Calibrated prediction for SNP: 0.5384615659713745
Raw prediction for SNY: 0.5333478450775146
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46995970606803894
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4563312530517578
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5702065229415894
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5078778266906738
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5034739375114441
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4793701171875
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.49755629897117615
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09446591138839722
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4326772093772888
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.4114397466182709
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4815393388271332
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5101978778839111
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.46896475553512573
Calibrated prediction for V: 0.4683045744895935

Simulating Trading Days:  31%|███▏      | 34/108 [06:15<01:50,  1.49s/it]

Raw prediction for VZ: 0.5009056925773621
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5330601930618286
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4917156994342804
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5074716806411743
Calibrated prediction for XOM: 0.5078077912330627
Investing 1620.32837148299 in BP
Investing 880.1755833109471 in HRG
Investing 1293.5482763285593 in BUD
Investing 3560.2974438320634 in MA
Investing 914.9112483096368 in JNJ
Investing 1911.6959438663462 in HON
Investing 1453.796015758094 in CHTR
Investing 2274.619675862269 in INTC
Investing 1462.598416347027 in SRE
Raw prediction for AAPL: 0.5048832297325134
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47733262181282043
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4071524739265442
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5430497527122498
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5122681260108948
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5254079103469849
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5388849377632141
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5585467219352722
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.5138242244720459
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45228803157806396
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.45588168501853943
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49382656812667847
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5122020244598389
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5075637698173523
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46892601251602173
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49789029359817505
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5808331966400146
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.47409313917160034
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5182594060897827
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5252996683120728
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.41907799243927
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5672845244407654
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5088357925415039
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.35197538137435913
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.48418301343917847
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5180889964103699
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.27618879079818726
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5289740562438965
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.47353219985961914
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5051937103271484
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5263086557388306
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5875074863433838
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5127835273742676
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.488171249628067
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.45955890417099
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6717050075531006
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4191845953464508
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7925567030906677
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5292253494262695
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5124910473823547
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4859585165977478
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5694107413291931
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5393325090408325
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5389460921287537
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5153025388717651
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5957850813865662
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7033472061157227
Calibrated prediction for MA: 0.782608687877655
Raw prediction for MCD: 0.4234115779399872
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4903876781463623
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49809813499450684
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5370218753814697
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4603564441204071
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4535802900791168
Calibrated prediction for MSFT: 0.4401414692401886
Raw prediction for NEE: 0.5711938142776489
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5104396939277649
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4632096290588379
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.37882357835769653
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.504718542098999
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46899038553237915
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.548053503036499
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.48126447200775146
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5030866861343384
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4708472490310669
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4846299886703491
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5208821892738342
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4893421232700348
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4472692906856537
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.1890440732240677
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.48968303203582764
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5280234217643738
Calibrated prediction for SNP: 0.5384615659713745
Raw prediction for SNY: 0.5309664011001587
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4699816107749939
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4556376039981842
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5852261781692505
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5079101920127869
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5231984257698059
Calibrated prediction for TM: 0.5428571701049805

Simulating Trading Days:  32%|███▏      | 35/108 [06:17<01:51,  1.53s/it]

Raw prediction for TOT: 0.4787352681159973
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.49457934498786926
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.08744809031486511
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4303834140300751
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3894631564617157
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4814201295375824
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5218923687934875
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.4699177145957947
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5244987607002258
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5326605439186096
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.49317261576652527
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5073373317718506
Calibrated prediction for XOM: 0.5078077912330627
Investing 1922.2393088326291 in BP
Investing 1044.1760662170525 in HRG
Investing 1534.5712562915226 in BUD
Investing 3693.026122976586 in MA
Investing 1085.3839237439881 in JNJ
Investing 2267.8965291908817 in HON
Investing 1724.6774775391912 in CHTR
Investing 2698.442754282469 in INTC
Investing 1735.1200030926088 in SRE
Raw prediction for AAPL: 0.5050339102745056
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4771616756916046
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.39025822281837463
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5492557287216187
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5121741890907288
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5184156894683838
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5392136573791504
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5307708978652954
Calibrated prediction for BA: 0.5815508365631104
Raw prediction for BABA: 0.5136693716049194
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45282283425331116
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4598930776119232
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49383771419525146
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5119828581809998
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5119503140449524
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4693925380706787
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4975387156009674
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5853524208068848
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4740515649318695
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5185127854347229
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.530727207660675
Calibrated prediction for CELG: 0.610562801361084
Raw prediction for CHL: 0.39174264669418335
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5664717555046082
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5082476139068604
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.3575175106525421
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.49911215901374817
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5184997916221619
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3017346262931824
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.5293123722076416
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4728219211101532
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.505006730556488
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5631201267242432
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.594413161277771
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5054919123649597
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4995744228363037
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4591524600982666
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6632201671600342
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.405701607465744
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.8225498199462891
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5310134291648865
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5137055516242981
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4854011833667755
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5497055053710938
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.537644624710083
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5420587062835693
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5220414400100708
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5993413329124451
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6723195314407349
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.42330560088157654
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4882084131240845
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49786949157714844
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5351547598838806
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4594103991985321
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4539755880832672
Calibrated prediction for MSFT: 0.4401414692401886
Raw prediction for NEE: 0.5710547566413879
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.509975254535675
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.477068156003952
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.34736955165863037
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.507662296295166
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47062963247299194
Calibrated prediction for PCLN: 0.48429951071739197
Raw prediction for PEP: 0.5447840094566345
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4843684136867523
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5032399892807007
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47104814648628235
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48348990082740784
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5279256701469421
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48876526951789856
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.44922691583633423
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.1737172156572342
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.4936903119087219
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5357328057289124
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5301082134246826
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4699740409851074
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45792603492736816
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6024417877197266
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5080006718635559
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5391802787780762
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4782346487045288
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.49076277017593384
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09368031471967697
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.43341541290283203
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.37003394961357117
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4813384711742401
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5353782176971436
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.47434717416763306
Calibrated prediction for V: 0.4683045744895935

Simulating Trading Days:  33%|███▎      | 36/108 [06:18<01:46,  1.47s/it]

Raw prediction for VZ: 0.5382457971572876
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5325363874435425
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4941437542438507
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5068690180778503
Calibrated prediction for XOM: 0.5078077912330627
Investing 1930.0008298713558 in BP
Investing 1048.3921877316002 in HRG
Investing 1540.7674707984277 in BUD
Investing 2987.4561882946823 in MA
Investing 1563.5294630366802 in CELG
Investing 2277.053727539749 in HON
Investing 1731.6412933686927 in CHTR
Investing 2709.3383904880793 in INTC
Investing 1742.125983225695 in SRE
Raw prediction for AAPL: 0.5054869651794434
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4769876003265381
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.38676199316978455
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5477404594421387
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5120481848716736
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5115801692008972
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5391479134559631
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.47758060693740845
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5128818154335022
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45312926173210144
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4581274688243866
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49426767230033875
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5117980241775513
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5141736268997192
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.470695436000824
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4972216784954071
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5865105986595154
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.47335007786750793
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5187287330627441
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5406556129455566
Calibrated prediction for CELG: 0.610562801361084
Raw prediction for CHL: 0.3726683259010315
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5657995343208313
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5076757669448853
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.36551493406295776
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.5354999303817749
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5192670822143555
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.27185896039009094
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.527190625667572
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.47363337874412537
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5049457550048828
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.594508707523346
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6002216935157776
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.49091896414756775
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.5033785104751587
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4567428231239319
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6534211039543152
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3967514634132385
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.8358370065689087
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5292103886604309
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5153900384902954
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48473578691482544
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5232584476470947
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5325725674629211
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5456975102424622
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.534082293510437
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6003903150558472
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6534437537193298
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4236234724521637
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4857959449291229
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49800610542297363
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5334047079086304
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45858895778656006
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4574446976184845
Calibrated prediction for MSFT: 0.4401414692401886
Raw prediction for NEE: 0.5707935690879822
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5093235373497009
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.4975762367248535
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.31343719363212585
Calibrated prediction for ORCL: 0.26799508929252625
Raw prediction for PCG: 0.5091778039932251
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4719665050506592
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5451821684837341
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.48356929421424866
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5034372806549072
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47132444381713867
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.482422411441803
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5319955945014954
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48842865228652954
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4522901475429535
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.16171710193157196
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.4965206980705261
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5486927032470703
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5296030044555664
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46972766518592834
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4623425304889679
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6154651641845703
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5080074667930603
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5489391684532166
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47790053486824036
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.4867360591888428
Calibrated prediction for TSM: 0.5760757327079773

Simulating Trading Days:  34%|███▍      | 37/108 [06:20<01:41,  1.43s/it]

Raw prediction for UL: 0.09780367463827133
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.43378782272338867
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3499447703361511
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48129284381866455
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5448954105377197
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.47486746311187744
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5361729860305786
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5323141813278198
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.49206459522247314
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5075303912162781
Calibrated prediction for XOM: 0.5078077912330627
Investing 1844.0697430715595 in BP
Investing 1001.713720712393 in HRG
Investing 1472.166555595553 in BUD
Investing 2854.443107132406 in MA
Investing 1493.9150960774705 in CELG
Investing 2175.6705061024504 in HON
Investing 1654.5419388070186 in CHTR
Investing 2062.008090897522 in CSCO
Investing 1659.6169887835392 in EXC
Raw prediction for AAPL: 0.505728006362915
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4768531620502472
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3843905031681061
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5410753488540649
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5119653344154358
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5082515478134155
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5385684370994568
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4084080457687378
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.511969268321991
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45322492718696594
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.45526450872421265
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.494744211435318
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5114630460739136
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5155758261680603
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4727741777896881
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4969668686389923
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5843133926391602
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4736284613609314
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5185974836349487
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5472214221954346
Calibrated prediction for CELG: 0.610562801361084
Raw prediction for CHL: 0.35794687271118164
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.56504225730896
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5070828795433044
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.37913742661476135
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.5707825422286987
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5199934244155884
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.197113499045372
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5224945545196533
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.47596806287765503
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5048230886459351
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6099045872688293
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6046056747436523
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4715268015861511
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4999611973762512
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.44755592942237854
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6428002119064331
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.38371118903160095
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.8248225450515747
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.52280193567276
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5157254934310913
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4842210114002228
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4907395839691162
Calibrated prediction for INTC: 0.5655311346054077
Raw prediction for JNJ: 0.5261607766151428
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5479816794395447
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5307490229606628
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5975443124771118
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6454210877418518
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4239426851272583
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4835119843482971
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4978916645050049
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5314424633979797
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45832717418670654
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4591018557548523
Calibrated prediction for MSFT: 0.4401414692401886
Raw prediction for NEE: 0.5707537531852722
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5111958384513855
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5133748650550842
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2854580879211426
Calibrated prediction for ORCL: 0.2260846495628357
Raw prediction for PCG: 0.5028625130653381
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4728909134864807
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5441548824310303
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4808772802352905
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5036807656288147
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.471487432718277
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48135969042778015
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5291399359703064
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4879065752029419
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4552653431892395
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.14801162481307983
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.4984452426433563
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5535893440246582
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5294572114944458
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4693891704082489
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.46736034750938416
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5894646048545837
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5079297423362732
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5510715842247009
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47752144932746887
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.4840365946292877
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09553545713424683
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.42999520897865295
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3297821879386902
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.481214702129364
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5470988154411316
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.47200292348861694
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5160771608352661
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5319949984550476
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  35%|███▌      | 38/108 [06:21<01:38,  1.40s/it]

Raw prediction for WMT: 0.48803624510765076
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5075726509094238
Calibrated prediction for XOM: 0.5078077912330627
Investing 1552.996920648068 in BP
Investing 843.6005902065807 in HRG
Investing 1239.7959112505473 in BUD
Investing 2403.8902933020513 in MA
Investing 1258.111604853735 in CELG
Investing 1832.2569463636678 in HON
Investing 1393.3846839060002 in CHTR
Investing 1736.535305970251 in CSCO
Investing 1397.658674635084 in EXC
Raw prediction for AAPL: 0.5059288740158081
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4767267107963562
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3837325870990753
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5422815680503845
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5118734240531921
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5051827430725098
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5378035306930542
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3316793143749237
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5111204981803894
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4530107378959656
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4536060690879822
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49475497007369995
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5113005638122559
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5161026120185852
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4735580384731293
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4969422519207001
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5780699253082275
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4729480743408203
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.517987072467804
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5410221219062805
Calibrated prediction for CELG: 0.610562801361084
Raw prediction for CHL: 0.35124850273132324
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5644879937171936
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5067201852798462
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.3942059874534607
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.5917890667915344
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.52048259973526
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.14159639179706573
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5186893939971924
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4778138995170593
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5045208930969238
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6182188391685486
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6086561679840088
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4484618902206421
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4911193251609802
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4353812038898468
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6332265734672546
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.36873993277549744
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.7938290238380432
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5141583681106567
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5160908102989197
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4838842749595642
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.45447802543640137
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.519920289516449
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5478283166885376
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5030615925788879
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5924001932144165
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6327709555625916
Calibrated prediction for MA: 0.7088078856468201
Raw prediction for MCD: 0.42537787556648254
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4823135733604431
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.497537761926651
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.529267430305481
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45841512084007263
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.45984768867492676
Calibrated prediction for MSFT: 0.46098193526268005
Raw prediction for NEE: 0.5707175731658936
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5132858753204346
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5210415720939636
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2582519054412842
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.49635982513427734
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4733756184577942
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5430288910865784
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47636643052101135
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5039179921150208
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4715830981731415
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4802941381931305
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5209001898765564
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4871322214603424
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4591495990753174
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.13256190717220306
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5013088583946228
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.555414617061615
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5312904119491577
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4690169394016266
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4709756672382355
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5669591426849365
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5078489184379578
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.543934166431427
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4773685336112976
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.48245999217033386
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09454450756311417
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.42688366770744324
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.313099205493927
Calibrated prediction for UNH: 0.4393063485622406

Simulating Trading Days:  36%|███▌      | 39/108 [06:22<01:35,  1.38s/it]

Raw prediction for UPS: 0.48113372921943665
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5444697737693787
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.4701646566390991
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.49044564366340637
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5317433476448059
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4846785068511963
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5077983140945435
Calibrated prediction for XOM: 0.5078077912330627
Investing 1435.679998116019 in BP
Investing 779.8730813020835 in HRG
Investing 1146.1389059198248 in BUD
Investing 2043.4561386878843 in MA
Investing 1163.0709903355137 in CELG
Investing 1693.844085798784 in HON
Investing 1288.1252330688867 in CHTR
Investing 1605.3534760155173 in CSCO
Investing 1292.076356809247 in EXC
Raw prediction for AAPL: 0.5061529874801636
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47660091519355774
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.39002901315689087
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5478410720825195
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5117734670639038
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5010936260223389
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5371532440185547
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2753576636314392
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.510269045829773
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4527364671230316
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4532236158847809
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4945283830165863
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5112523436546326
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5151748657226562
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.475664883852005
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4970284700393677
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5703617334365845
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4709325134754181
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5171747803688049
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5252600312232971
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.34565970301628113
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5656315684318542
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5067389011383057
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.41102364659309387
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.6007941961288452
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5207194089889526
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.11620267480611801
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5161758065223694
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4813433289527893
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5040122270584106
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6231921315193176
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6109632253646851
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.43135637044906616
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.48378491401672363
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.41970470547676086
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6257847547531128
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3482421338558197
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.7467655539512634
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5069301724433899
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5164875388145447
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48379796743392944
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4132381081581116
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5151918530464172
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5458973050117493
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4560978412628174
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5880067944526672
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6105685830116272
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4251464605331421
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.48302775621414185
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49706020951271057
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5271673798561096
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45906496047973633
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.46118900179862976
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5700491070747375
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5148612856864929
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5222334265708923
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.23545129597187042
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4893167316913605
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4733794033527374
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5398803353309631
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47346314787864685
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5044523477554321
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47172582149505615
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4793204367160797
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5085608959197998
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48658743500709534
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.463695764541626
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.11753199249505997
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5052284002304077
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5574963092803955
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5323134660720825
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4688132107257843
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.47259199619293213
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5551900863647461
Calibrated prediction for SRE: 0.6345176100730896
Raw prediction for T: 0.5078630447387695
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5335647463798523
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4776340126991272
Calibrated prediction for TOT: 0.4789581000804901

Simulating Trading Days:  37%|███▋      | 40/108 [06:24<01:32,  1.36s/it]

Raw prediction for TSM: 0.48151102662086487
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09308034926652908
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4238031506538391
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3017970323562622
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4810743033885956
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5393776297569275
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.47326141595840454
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.47255104780197144
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5317372679710388
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4830651581287384
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5085469484329224
Calibrated prediction for XOM: 0.5078077912330627
Investing 1755.7715447807527 in BP
Investing 953.7494194301868 in HRG
Investing 1157.7186843280122 in PEP
Investing 1435.866237103168 in MA
Investing 991.3886370524256 in JNJ
Investing 2071.4945190037674 in HON
Investing 1575.3187571772937 in CHTR
Investing 1963.274515352786 in CSCO
Investing 1580.1508023700494 in EXC
Raw prediction for AAPL: 0.5063236355781555
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47660282254219055
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.40319135785102844
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.550665557384491
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5117276906967163
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4948362708091736
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5366752743721008
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.23724690079689026
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5093828439712524
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4525403380393982
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4534684717655182
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49418649077415466
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5113831162452698
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5120766162872314
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47668394446372986
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4969939589500427
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5624170303344727
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.46904587745666504
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5166264772415161
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5045003890991211
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.3400694727897644
Calibrated prediction for CHL: 0.3199999928474426
Raw prediction for CHTR: 0.5686209797859192
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5072944164276123
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.42658090591430664
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.6029658317565918
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5209641456604004
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.11025930196046829
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5184764266014099
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.48556143045425415
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5033206939697266
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.626023530960083
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6110888123512268
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.42260926961898804
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.4813096821308136
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4062032103538513
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.6218482255935669
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3079756498336792
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6829374432563782
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5044444799423218
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5168853402137756
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4838027358055115
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3722187280654907
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5117892026901245
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5424556732177734
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.42688387632369995
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5858741402626038
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5762853622436523
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.42457348108291626
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4859015941619873
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4965127110481262
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5250561833381653
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4600403606891632
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.46466121077537537
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.569223165512085
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5155074000358582
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5205228924751282
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2240964025259018
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.49466806650161743
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4729243814945221
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5356436371803284
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47000759840011597
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5053542256355286
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4718707799911499
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4782434403896332
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.49567610025405884
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4865257143974304
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4691501259803772
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.10468171536922455
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.510948121547699
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5606258511543274
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5322062969207764
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46849849820137024
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4737244248390198
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5463347434997559
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5079652070999146
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5217642784118652
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.478407084941864
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.48119980096817017
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.08796067535877228
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4201267957687378
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.2934490740299225
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4812464118003845
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5335151553153992
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.4828859567642212
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.460134357213974
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5319364070892334
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  38%|███▊      | 41/108 [06:25<01:30,  1.35s/it]

Raw prediction for WMT: 0.4812360107898712
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.509280800819397
Calibrated prediction for XOM: 0.5078077912330627
Investing 2036.9813564100207 in BP
Investing 1106.5048820510244 in HRG
Investing 1343.1424965018323 in PEP
Investing 1315.2324947275395 in C
Investing 1150.1725134090289 in JNJ
Investing 2403.2715005887217 in HON
Investing 1827.6266911330165 in CHTR
Investing 2277.7186457865323 in CSCO
Investing 1833.232651658025 in EXC
Raw prediction for AAPL: 0.5064470767974854
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47662782669067383
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4152396619319916
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5441246032714844
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5116502642631531
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48870155215263367
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5365277528762817
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2159498631954193
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5085493922233582
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45263800024986267
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.45476067066192627
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49380776286125183
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5116749405860901
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5001876354217529
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4768398702144623
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4967609941959381
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5557576417922974
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.46752288937568665
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5161562561988831
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48296481370925903
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.33418694138526917
Calibrated prediction for CHL: 0.3199999928474426
Raw prediction for CHTR: 0.5717352032661438
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.507515013217926
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4516713321208954
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.6020123362541199
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5214946866035461
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.11183565109968185
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5231520533561707
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4916705787181854
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5025240182876587
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6277176737785339
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6096392273902893
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4222457706928253
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.4827810227870941
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.395733118057251
Calibrated prediction for GMRE: 0.38768887519836426
Raw prediction for GOOG: 0.6217712759971619
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.2708243131637573
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.6148508191108704
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.504414975643158
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5172863602638245
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48385530710220337
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3463093936443329
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5095498561859131
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5397018194198608
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.40056800842285156
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5860843658447266
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5416931509971619
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.42309942841529846
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.49060824513435364
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49589797854423523
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5234246253967285
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4609631896018982
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4691908657550812
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5686649680137634
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5156472325325012
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.523125410079956
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.21821129322052002
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.495008260011673
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4721137583255768
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5322943329811096
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4675561487674713
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5063290596008301
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.472056120634079
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.47703105211257935
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.4860208034515381
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4872365891933441
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4733724296092987
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.0956452339887619
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5168676972389221
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5638233423233032
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5332164168357849
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4684612452983856
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4745168685913086
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5383223295211792
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5081682801246643
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5106728672981262
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47933685779571533
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.48175671696662903
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.08648137748241425
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.42179590463638306
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.28682512044906616
Calibrated prediction for UNH: 0.4393063485622406

Simulating Trading Days:  39%|███▉      | 42/108 [06:26<01:29,  1.35s/it]

Raw prediction for UPS: 0.4815657138824463
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5290350914001465
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.49881744384765625
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.4510185718536377
Calibrated prediction for VZ: 0.42500001192092896
Raw prediction for WFC: 0.5322830080986023
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47903165221214294
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5091511011123657
Calibrated prediction for XOM: 0.5078077912330627
Investing 2160.9577734890295 in BP
Investing 1173.8498826939779 in HRG
Investing 1424.889928219285 in PEP
Investing 1395.28124520289 in C
Investing 1220.175248969907 in JNJ
Investing 2549.541366522197 in HON
Investing 1938.8611941939405 in CHTR
Investing 2416.3470116918243 in CSCO
Investing 1944.8083492507446 in EXC
Raw prediction for AAPL: 0.5065418481826782
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47663357853889465
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.42321905493736267
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5454608798027039
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5116251111030579
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48371684551239014
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5364959836006165
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.20310775935649872
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5078719258308411
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.452971875667572
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.456027626991272
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4935096502304077
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5121687054634094
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.4733065664768219
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4753513038158417
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49644607305526733
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5517472624778748
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.46714073419570923
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5157127380371094
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4789048135280609
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.33222392201423645
Calibrated prediction for CHL: 0.3199999928474426
Raw prediction for CHTR: 0.575430691242218
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5074853301048279
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4985755383968353
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.5955477356910706
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5223989486694336
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.11720506101846695
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5364952087402344
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.49887827038764954
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5018055438995361
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6284673810005188
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6075729131698608
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4294314384460449
Calibrated prediction for GD: 0.4766644835472107
Raw prediction for GE: 0.48654693365097046
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3926839828491211
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6251475811004639
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.2456398904323578
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5555166602134705
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5061521530151367
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5176320672035217
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4838755130767822
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.34631747007369995
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5071572065353394
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5397531390190125
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.38249024748802185
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5897799730300903
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5293598771095276
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.42150256037712097
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4961598217487335
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4951990246772766
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5218554139137268
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46152955293655396
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.480842649936676
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5691980719566345
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5155365467071533
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.532055139541626
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.21880660951137543
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4909384250640869
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4710565507411957
Calibrated prediction for PCLN: 0.4938148260116577
Raw prediction for PEP: 0.5296676158905029
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46432197093963623
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5073634386062622
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47228798270225525
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.47595641016960144
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.4798247814178467
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4888969957828522
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.477979451417923
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.0876617282629013
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5231079459190369
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5657055377960205
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.534687340259552
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46831196546554565
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4748608469963074
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5325557589530945
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5084887146949768
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4933584928512573
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48081234097480774
Calibrated prediction for TOT: 0.4789581000804901

Simulating Trading Days:  40%|███▉      | 43/108 [06:28<01:27,  1.34s/it]

Raw prediction for TSM: 0.4824424982070923
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.08657079190015793
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4219534397125244
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.28983914852142334
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4820179343223572
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5284168124198914
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5157809853553772
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.44226881861686707
Calibrated prediction for VZ: 0.42500001192092896
Raw prediction for WFC: 0.5326289534568787
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47723695635795593
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5103169083595276
Calibrated prediction for XOM: 0.5078077912330627
Investing 1935.6018415507594 in BP
Investing 1506.9771270868753 in CODI
Investing 1276.2949849849897 in PEP
Investing 1249.7740496499623 in C
Investing 1092.9290187413274 in JNJ
Investing 1428.9188900356382 in HON
Investing 1736.6666503315403 in CHTR
Investing 2164.357759802433 in CSCO
Investing 1741.9936050833455 in EXC
Raw prediction for AAPL: 0.506636917591095
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47644907236099243
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4256364405155182
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5413128137588501
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5116296410560608
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.47729936242103577
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5366475582122803
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.1989631950855255
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5073099136352539
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4532380700111389
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4613015949726105
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4934490919113159
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5131378769874573
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4306890070438385
Calibrated prediction for BP: 0.24062934517860413
Raw prediction for BRK-A: 0.47436028718948364
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4960996210575104
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5482514500617981
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.46784400939941406
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5152018070220947
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4898271858692169
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.33867335319519043
Calibrated prediction for CHL: 0.3199999928474426
Raw prediction for CHTR: 0.5804735422134399
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5074959993362427
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5557101964950562
Calibrated prediction for CODI: 0.6997207999229431
Raw prediction for CSCO: 0.5859408974647522
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5233556032180786
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.12717866897583008
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.55739426612854
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5044424533843994
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5011999011039734
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6274464726448059
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6073240041732788
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4402427077293396
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4896377921104431
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3959500193595886
Calibrated prediction for GMRE: 0.3886358141899109
Raw prediction for GOOG: 0.6313022375106812
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.23451471328735352
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5227963924407959
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5077947974205017
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5179385542869568
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4838203489780426
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3562137186527252
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5037707686424255
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5429556369781494
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.3734557628631592
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.5939631462097168
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.539230227470398
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.41597217321395874
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5016536116600037
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.494577020406723
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.52056884765625
Calibrated prediction for MO: 0.5490517616271973
Raw prediction for MRK: 0.4616980254650116
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.49522578716278076
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.570038914680481
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5158668160438538
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5400774478912354
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.22737665474414825
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4921654760837555
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46973130106925964
Calibrated prediction for PCLN: 0.46427714824676514
Raw prediction for PEP: 0.5320542454719543
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.45907339453697205
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5083456039428711
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.472675085067749
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4750952124595642
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.4778483808040619
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49129968881607056
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4857197701931
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.0827389508485794
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5238645672798157
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5691249966621399
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5336644053459167
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46780654788017273
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.474351167678833
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5208398103713989
Calibrated prediction for SRE: 0.550561785697937

Simulating Trading Days:  41%|████      | 44/108 [06:29<01:25,  1.33s/it]

Raw prediction for T: 0.5088477730751038
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.47124025225639343
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48226049542427063
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.4838500916957855
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.08597918599843979
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4155943691730499
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.304982453584671
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48261991143226624
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5317723751068115
Calibrated prediction for UTX: 0.496442973613739
Raw prediction for V: 0.5305765867233276
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.4348394274711609
Calibrated prediction for VZ: 0.42500001192092896
Raw prediction for WFC: 0.5329576134681702
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4759223759174347
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5132066011428833
Calibrated prediction for XOM: 0.5078077912330627
Investing 1428.0013059493729 in SNP
Investing 2436.5254561332526 in CODI
Investing 1148.4647629618858 in PEP
Investing 1124.600092120585 in C
Investing 994.4724427068627 in NVS
Investing 1285.8022742726994 in HON
Investing 1562.726858901104 in CHTR
Investing 1947.5815942389318 in CSCO
Investing 1567.5202804049993 in EXC
Raw prediction for AAPL: 0.5067700147628784
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4763442575931549
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.42507052421569824
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5364362001419067
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.511671781539917
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4717044532299042
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5369300246238708
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2050340324640274
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5068316459655762
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45378702878952026
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.474204957485199
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49370354413986206
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5141846537590027
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.3833250105381012
Calibrated prediction for BP: 0.24062934517860413
Raw prediction for BRK-A: 0.4742569625377655
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4957379996776581
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5442840456962585
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.46936747431755066
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5147667527198792
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.49706995487213135
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.34598109126091003
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5865370631217957
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5075246691703796
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5820295810699463
Calibrated prediction for CODI: 0.6997207999229431
Raw prediction for CSCO: 0.5729908347129822
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5242548584938049
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.1339963674545288
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5806398391723633
Calibrated prediction for DHR: 0.6315789222717285
Raw prediction for DIS: 0.5143600702285767
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5006176829338074
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6262954473495483
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6083295941352844
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.45336484909057617
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4894878566265106
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.40208178758621216
Calibrated prediction for GMRE: 0.41540607810020447
Raw prediction for GOOG: 0.6373627781867981
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.22343145310878754
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.511002779006958
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5084428787231445
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5181023478507996
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4838540256023407
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3680870234966278
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5040447115898132
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5468885898590088
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.35889115929603577
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.5979815125465393
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.566287636756897
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4111497700214386
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5052986741065979
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49432650208473206
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5193573236465454
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.4616726040840149
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5089382529258728
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.570012092590332
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5163867473602295
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5421536564826965
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.23922090232372284
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4960138499736786
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4681132435798645
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5354640483856201
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4553022086620331
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.509483277797699
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47298017144203186
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4745081663131714
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.47614291310310364
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49454909563064575
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.49383795261383057
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.07842600345611572
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5218005180358887
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5701667666435242
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5328460931777954
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4674355685710907
Calibrated prediction for SO: 0.4706009030342102
Raw prediction for SPLP: 0.47266697883605957
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5060691833496094
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5090767741203308
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4430936276912689
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.48368650674819946
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.4847239851951599
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.08151379227638245
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.4033477306365967
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.32459044456481934
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4831385910511017
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5344468951225281
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.5429511070251465
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.43083032965660095
Calibrated prediction for VZ: 0.42500001192092896

Simulating Trading Days:  42%|████▏     | 45/108 [06:30<01:23,  1.33s/it]

Raw prediction for WFC: 0.5331426858901978
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47563764452934265
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5163875818252563
Calibrated prediction for XOM: 0.5078077912330627
Investing 1388.2594783658242 in SNP
Investing 2368.7160121382426 in CODI
Investing 1116.5025452767497 in PEP
Investing 1093.3020374372347 in C
Investing 966.7958907387458 in NVS
Investing 1651.9906682208557 in DHR
Investing 1519.2355671719702 in CHTR
Investing 1893.3796466632057 in CSCO
Investing 1523.895585905049 in EXC
Raw prediction for AAPL: 0.5068010091781616
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47617703676223755
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4251655340194702
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5321757793426514
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5117745995521545
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4635300040245056
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5369162559509277
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.22300377488136292
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.506441593170166
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45423856377601624
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4872501790523529
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4940567910671234
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5151169896125793
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.34915152192115784
Calibrated prediction for BP: 0.24062934517860413
Raw prediction for BRK-A: 0.47401389479637146
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4954659938812256
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5392888784408569
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.47151094675064087
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5143661499023438
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48424863815307617
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.3671168386936188
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5922263860702515
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5074256062507629
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.6053922772407532
Calibrated prediction for CODI: 0.6997207999229431
Raw prediction for CSCO: 0.5561978220939636
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5250949263572693
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.14172986149787903
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.602050244808197
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5253902673721313
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5000183582305908
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6256669759750366
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6085859537124634
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.46344733238220215
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4850844442844391
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4078792631626129
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.6418200731277466
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.2108112871646881
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5044952630996704
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5080246329307556
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5181598663330078
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4840560555458069
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3797430694103241
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5069993138313293
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5497110486030579
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.34640607237815857
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.6003044843673706
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6001447439193726
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.40680554509162903
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5077521204948425
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4943509101867676
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5185897350311279
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.4616048336029053
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5196483731269836
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5699743628501892
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5172411799430847
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5354611873626709
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.25267335772514343
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.49954622983932495
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46651357412338257
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5384390354156494
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.45440948009490967
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5105078220367432
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4731084406375885
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4739079177379608
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.47443827986717224
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4969732463359833
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5023602247238159
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.0743090808391571
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5185601115226746
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5678827166557312
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5297595262527466
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4670756757259369
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4701104760169983
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.4918232262134552
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5091714262962341
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.41524285078048706
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.48459529876708984
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.48536601662635803
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.07300467789173126
Calibrated prediction for UL: 0.17558681964874268

Simulating Trading Days:  43%|████▎     | 46/108 [06:32<01:22,  1.33s/it]

Raw prediction for UN: 0.39240896701812744
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3469494581222534
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4835970997810364
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5337527990341187
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.552337646484375
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.43410322070121765
Calibrated prediction for VZ: 0.42500001192092896
Raw prediction for WFC: 0.5332693457603455
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4758383631706238
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5207546949386597
Calibrated prediction for XOM: 0.5078077912330627
Investing 1480.0309030538394 in SNP
Investing 2525.3008916242643 in CODI
Investing 1190.3093737872641 in PEP
Investing 1476.28699844349 in MA
Investing 1030.7063034953396 in NVS
Investing 2240.486255439103 in DHR
Investing 1619.665216390138 in CHTR
Investing 2018.5422335984022 in CSCO
Investing 1624.6332874469158 in EXC
Raw prediction for AAPL: 0.5068358182907104
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47587934136390686
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4253029525279999
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5314116477966309
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5119993686676025
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4603976011276245
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5367873907089233
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2518211007118225
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.506301999092102
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4545879662036896
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49824321269989014
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49426278471946716
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5154280066490173
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.3666870892047882
Calibrated prediction for BP: 0.24062934517860413
Raw prediction for BRK-A: 0.4736104905605316
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4952813386917114
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5355453491210938
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.47392934560775757
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5141233205795288
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4597569704055786
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.39312106370925903
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5968911051750183
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5076082944869995
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.606013298034668
Calibrated prediction for CODI: 0.6997207999229431
Raw prediction for CSCO: 0.5403719544410706
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5257729887962341
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.16281387209892273
Calibrated prediction for D: 0.3333333432674408
Raw prediction for DHR: 0.619501531124115
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5335108041763306
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.4995826482772827
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6234359741210938
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6076253056526184
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.47314274311065674
Calibrated prediction for GD: 0.5009316802024841
Raw prediction for GE: 0.47699567675590515
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4099544584751129
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.645269513130188
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.20471782982349396
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5033978819847107
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5067204833030701
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.518165111541748
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48451846837997437
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3912983238697052
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5112338066101074
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5508323311805725
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.3371340334415436
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.6021554470062256
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6386491656303406
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4076896011829376
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5093200206756592
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4945577383041382
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.518198549747467
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.4612849950790405
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5288700461387634
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5707606673240662
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5177963376045227
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5283610224723816
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.27392497658729553
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5013945698738098
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4650435447692871
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5398659706115723
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.45495131611824036
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5113040804862976
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47314056754112244
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.47335726022720337
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.4731880724430084
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.498393714427948
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5104818940162659
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.0723099336028099
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5154767036437988
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5654111504554749
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5262427926063538
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46686577796936035
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.46727898716926575
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.4805450737476349
Calibrated prediction for SRE: 0.5416666865348816

Simulating Trading Days:  44%|████▎     | 47/108 [06:33<01:21,  1.33s/it]

Raw prediction for T: 0.5092010498046875
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.39572322368621826
Calibrated prediction for TM: 0.27272728085517883
Raw prediction for TOT: 0.48517754673957825
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.48664233088493347
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.06505169719457626
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.39047423005104065
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3710959553718567
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.483954519033432
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5355260968208313
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.5596203207969666
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.4381706118583679
Calibrated prediction for VZ: 0.42500001192092896
Raw prediction for WFC: 0.5334354043006897
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47594019770622253
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5240141153335571
Calibrated prediction for XOM: 0.5078077912330627
Investing 1626.999303618826 in SNP
Investing 2776.065542701183 in CODI
Investing 1308.5081657733401 in PEP
Investing 3071.747053250377 in MA
Investing 1120.5141150425268 in JNJ
Investing 2462.9685568358477 in DHR
Investing 1780.499429927463 in CHTR
Investing 2218.985293897151 in CSCO
Investing 1785.960834910986 in EXC
Raw prediction for AAPL: 0.5068567395210266
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47564324736595154
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.43021437525749207
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5348941087722778
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.512254536151886
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4659007489681244
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5367777347564697
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2923080325126648
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5063121914863586
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45488590002059937
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5051112174987793
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4942980706691742
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.515640377998352
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4017587900161743
Calibrated prediction for BP: 0.24062934517860413
Raw prediction for BRK-A: 0.47234731912612915
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4951132535934448
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5337193608283997
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.47617092728614807
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5141087770462036
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.44593560695648193
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.40718337893486023
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5996816158294678
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.507655918598175
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.6079140305519104
Calibrated prediction for CODI: 0.6997207999229431
Raw prediction for CSCO: 0.5285370945930481
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5262879133224487
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.21141403913497925
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.6330328583717346
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5357109904289246
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.4994158446788788
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.618621826171875
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.607705295085907
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4843205511569977
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4694960117340088
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.414122998714447
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.6483171582221985
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.20393767952919006
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5236608386039734
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5054001808166504
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5181103944778442
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4851061999797821
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.399444043636322
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5145511031150818
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5506057739257812
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.3351961672306061
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.6048740148544312
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.679686963558197
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.41180774569511414
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5107514262199402
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4948357343673706
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5178840160369873
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.46050363779067993
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5366940498352051
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5727740526199341
Calibrated prediction for NEE: 0.5592417120933533
Raw prediction for NGG: 0.5182279348373413
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5226736068725586
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3049422800540924
Calibrated prediction for ORCL: 0.24741333723068237
Raw prediction for PCG: 0.5047280788421631
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46385663747787476
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5406545996665955
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.45671191811561584
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5120932459831238
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47310513257980347
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4728816747665405
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.47623905539512634
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4993075132369995
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5161649584770203
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.07149391621351242
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5108444690704346
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5630738735198975
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5248470902442932
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4667018949985504
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4619347155094147
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.4746587574481964
Calibrated prediction for SRE: 0.5416666865348816
Raw prediction for T: 0.5092536211013794
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.39382079243659973
Calibrated prediction for TM: 0.27272728085517883
Raw prediction for TOT: 0.4854814112186432
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.48881039023399353
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.06305266171693802
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3937658369541168
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3927404582500458
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4842081665992737
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5413011908531189
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.5701459646224976
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.441976398229599
Calibrated prediction for VZ: 0.42500001192092896

Simulating Trading Days:  44%|████▍     | 48/108 [06:34<01:20,  1.34s/it]

Raw prediction for WFC: 0.5337058305740356
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4747205376625061
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5256664752960205
Calibrated prediction for XOM: 0.5078077912330627
Investing 1545.304252902809 in SNP
Investing 2636.6734638001503 in CODI
Investing 1242.8052237208094 in PEP
Investing 2917.5081849583617 in MA
Investing 1064.2507489471604 in JNJ
Investing 2339.2977349030316 in DHR
Investing 1691.0968156151946 in CHTR
Investing 1914.8971368719176 in MSFT
Investing 1696.2839919889589 in EXC
Raw prediction for AAPL: 0.5068607926368713
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.475617915391922
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.43398377299308777
Calibrated prediction for ABBV: 0.38344094157218933
Raw prediction for AEP: 0.5354728698730469
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5125025510787964
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4719561040401459
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.536897599697113
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3387576937675476
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.506499707698822
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4551139771938324
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5099634528160095
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4942639470100403
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5161683559417725
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.44460198283195496
Calibrated prediction for BP: 0.29138049483299255
Raw prediction for BRK-A: 0.47049441933631897
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49494850635528564
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5343783497810364
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4750473201274872
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5145015120506287
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.43753716349601746
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4232002794742584
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6012009382247925
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5076719522476196
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.6004963517189026
Calibrated prediction for CODI: 0.6997207999229431
Raw prediction for CSCO: 0.5151824355125427
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.526543915271759
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2806795835494995
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.6406282782554626
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5352785587310791
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.4996008574962616
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.611890971660614
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6082903146743774
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.49645134806632996
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.46639689803123474
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.41794222593307495
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6506290435791016
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.2067517191171646
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5783843994140625
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5034908056259155
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5179811120033264
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48564374446868896
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.40611013770103455
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5159941911697388
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5476616024971008
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.3787361681461334
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.607065737247467
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7154780626296997
Calibrated prediction for MA: 0.782608687877655
Raw prediction for MCD: 0.41697242856025696
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5123512744903564
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49519824981689453
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5175726413726807
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.45889103412628174
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5430091023445129
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5740630030632019
Calibrated prediction for NEE: 0.5700585842132568
Raw prediction for NGG: 0.5184540152549744
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5269288420677185
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.33725181221961975
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5047875046730042
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4630188047885895
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5436170101165771
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.45919615030288696
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5127889513969421
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4730696976184845
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4724959433078766
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.4884893000125885
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5001353025436401
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5195619463920593
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.07047336548566818
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5089164972305298
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5607474446296692
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5271773338317871
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46639591455459595
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.45554763078689575
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.47355082631111145
Calibrated prediction for SRE: 0.5416666865348816
Raw prediction for T: 0.5093157887458801
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.41129571199417114
Calibrated prediction for TM: 0.27272728085517883
Raw prediction for TOT: 0.4856914281845093
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.49071574211120605
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.06590554118156433
Calibrated prediction for UL: 0.17558681964874268

Simulating Trading Days:  45%|████▌     | 49/108 [06:36<01:18,  1.34s/it]

Raw prediction for UN: 0.396669864654541
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.4100169837474823
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48432421684265137
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5488100647926331
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.5774715542793274
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.44605574011802673
Calibrated prediction for VZ: 0.42500001192092896
Raw prediction for WFC: 0.5339833498001099
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.472723126411438
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5249819159507751
Calibrated prediction for XOM: 0.5078077912330627
Investing 1460.0425575709178 in SNP
Investing 2491.195801949472 in CODI
Investing 1174.233820941896 in PEP
Investing 3421.3261315787277 in MA
Investing 1005.5310353742394 in JNJ
Investing 2210.2276890598137 in DHR
Investing 1597.7910596782228 in CHTR
Investing 1809.2432658175985 in MSFT
Investing 1602.6920351625624 in EXC
Raw prediction for AAPL: 0.5068569183349609
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4756805896759033
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.44167834520339966
Calibrated prediction for ABBV: 0.3913043439388275
Raw prediction for AEP: 0.5352231860160828
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5127526521682739
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4806448519229889
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5367949604988098
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.38346460461616516
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5078058242797852
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4551781713962555
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5084340572357178
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4942803680896759
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.516327440738678
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.49574580788612366
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4691694974899292
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49517422914505005
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5388414859771729
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4687756896018982
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5149853229522705
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4344850480556488
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4464711546897888
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6017832159996033
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5077899098396301
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5865033864974976
Calibrated prediction for CODI: 0.6997207999229431
Raw prediction for CSCO: 0.49626561999320984
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5266128778457642
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.38540321588516235
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.6422902941703796
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5288877487182617
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5001039505004883
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.6030867099761963
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6079756617546082
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.5027468800544739
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4664934277534485
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4204896092414856
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6516637206077576
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.21388937532901764
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.6455910801887512
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5015507340431213
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5178367495536804
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48609548807144165
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.41179731488227844
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5153127908706665
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5403938293457031
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.46679019927978516
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6086074113845825
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.7458585500717163
Calibrated prediction for MA: 0.8235294222831726
Raw prediction for MCD: 0.42074280977249146
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5136497020721436
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4955965578556061
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5174813866615295
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.4569087028503418
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5472779273986816
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5761712789535522
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5189511179924011
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5372962355613708
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.36283382773399353
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5093973875045776
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.462437242269516
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5510050654411316
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46253037452697754
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5134994983673096
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4730479121208191
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4726693630218506
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.50834721326828
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5011064410209656
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5216975212097168
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.07087036222219467
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5087564587593079
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.559495210647583
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5320963859558105
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.466179221868515
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4503647983074188
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.500277042388916
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5095044374465942
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.43797168135643005
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.48587778210639954
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.49193963408470154
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.08911169320344925
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.39775288105010986
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.42801615595817566
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48426538705825806
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5566118955612183
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5789052248001099
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.4505234658718109
Calibrated prediction for VZ: 0.42500001192092896
Raw prediction for WFC: 0.5342052578926086
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4696708619594574
Calibrated prediction for WMT: 0.47951629757881165

Simulating Trading Days:  46%|████▋     | 50/108 [06:37<01:17,  1.34s/it]

Raw prediction for XOM: 0.5230443477630615
Calibrated prediction for XOM: 0.5078077912330627
Investing 1755.6073495116766 in BP
Investing 2455.9284196843764 in CODI
Investing 1157.6104174344903 in PEP
Investing 3857.5417605744387 in MA
Investing 1002.3917987348767 in NVS
Investing 2178.9379186042065 in DHR
Investing 1575.1714373918785 in CHTR
Investing 1783.630155111404 in MSFT
Investing 1580.003030704113 in EXC
Raw prediction for AAPL: 0.506898045539856
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4757813811302185
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.44856277108192444
Calibrated prediction for ABBV: 0.5
Raw prediction for AEP: 0.5331220030784607
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5128576159477234
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48750558495521545
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5379376411437988
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4134652614593506
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5094794034957886
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4547424614429474
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5042669773101807
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49455171823501587
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5161962509155273
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.543300449848175
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4705149531364441
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49570924043655396
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5434431433677673
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4617270827293396
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5154377222061157
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4302462637424469
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.484999418258667
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.6009325385093689
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5084519982337952
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5493691563606262
Calibrated prediction for CODI: 0.6997207999229431
Raw prediction for CSCO: 0.48329269886016846
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5263799428939819
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.48641160130500793
Calibrated prediction for D: 0.550000011920929
Raw prediction for DHR: 0.6375693082809448
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5265873670578003
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5008548498153687
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5906921625137329
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.6149835586547852
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.501364529132843
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.4661140441894531
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.42104578018188477
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6528528928756714
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.22294408082962036
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.6917139887809753
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5003243088722229
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5174321532249451
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48675239086151123
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4120578169822693
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5127642154693604
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5304876565933228
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5601299405097961
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6091088652610779
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.7753494381904602
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.4217577576637268
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5142765641212463
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49596744775772095
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5177429914474487
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.45512375235557556
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5478439331054688
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5788871645927429
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5198799967765808
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.551084041595459
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.38952696323394775
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5143322944641113
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4623454511165619
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5591541528701782
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4627170264720917
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5141258835792542
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4729640781879425
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.47377270460128784
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5318194031715393
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5023866891860962
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.522773265838623
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.07447721064090729
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5093455910682678
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5634326934814453
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.537043571472168
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4660778343677521
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4457683563232422
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5572884678840637
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5097740888595581
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.473863810300827
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4859054684638977
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.4942493736743927
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.13061052560806274
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.37810835242271423
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.4482078552246094
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4841463267803192
Calibrated prediction for UPS: 0.4850730001926422

Simulating Trading Days:  47%|████▋     | 51/108 [06:38<01:16,  1.34s/it]

Raw prediction for UTX: 0.5589840412139893
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5794187784194946
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.4554156959056854
Calibrated prediction for VZ: 0.42500001192092896
Raw prediction for WFC: 0.5343794822692871
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4672788083553314
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5205150842666626
Calibrated prediction for XOM: 0.5078077912330627
Investing 1711.6792267080648 in BP
Investing 2394.4771360321497 in CODI
Investing 1128.6451407796922 in PEP
Investing 3863.081051471269 in MA
Investing 977.3103418564882 in NVS
Investing 2124.417383305402 in DHR
Investing 1535.758111651508 in CHTR
Investing 2682.301145722297 in FB
Investing 1540.4688107191291 in EXC
Raw prediction for AAPL: 0.507459819316864
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4758090078830719
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.46380534768104553
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5315852165222168
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5129263401031494
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49299317598342896
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5404519438743591
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.42780816555023193
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5108679533004761
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45356810092926025
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5000185966491699
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49496281147003174
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5159090757369995
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.579238772392273
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47256335616111755
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4963188171386719
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5481179356575012
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4567091464996338
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5156488418579102
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4228944182395935
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5208345055580139
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5995587110519409
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5094602704048157
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.5187009572982788
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.4874098300933838
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5257364511489868
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5617938041687012
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.6273910999298096
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5255666971206665
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5018932819366455
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5728499293327332
Calibrated prediction for EXC: 0.6392497420310974
Raw prediction for FB: 0.626295268535614
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4952724575996399
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.46338117122650146
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4203225374221802
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6516854166984558
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.23074179887771606
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.7212147116661072
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.49844416975975037
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5172432661056519
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4878387153148651
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4095590114593506
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5089311599731445
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5227996110916138
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.6266400814056396
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6088699102401733
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.7990390658378601
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.4206264913082123
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5145462155342102
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4962041974067688
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5183928608894348
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.4543720781803131
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5396959781646729
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5819942355155945
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5208502411842346
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5637868642807007
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.41512900590896606
Calibrated prediction for ORCL: 0.380952388048172
Raw prediction for PCG: 0.5233983993530273
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4631994068622589
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.565500795841217
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46147531270980835
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.514374852180481
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4729401171207428
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4759231507778168
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5528781414031982
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5038061141967773
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.521935224533081
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.07985684275627136
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5096549987792969
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5740215182304382
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.541961669921875
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4657484292984009
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.44116607308387756
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6125077605247498
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5100774765014648
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5081194639205933
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48592957854270935
Calibrated prediction for TOT: 0.4871641993522644

Simulating Trading Days:  48%|████▊     | 52/108 [06:40<01:14,  1.34s/it]

Raw prediction for TSM: 0.49672532081604004
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.18899203836917877
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3398345112800598
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.48649466037750244
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4841438829898834
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5616098046302795
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5783708095550537
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.4611905515193939
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5351694226264954
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.46626773476600647
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.518132209777832
Calibrated prediction for XOM: 0.5078077912330627
Investing 1699.9351101025004 in BP
Investing 1323.4970506144753 in CODI
Investing 1159.4638425139817 in PEP
Investing 3836.575808188929 in MA
Investing 914.1606667209737 in ABBV
Investing 2109.84140138126 in DHR
Investing 1525.2210191520774 in CHTR
Investing 2663.897430274289 in FB
Investing 1529.899397327863 in EXC
Raw prediction for AAPL: 0.5083391666412354
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4757743179798126
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.48469680547714233
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5359520316123962
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5129697322845459
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49899208545684814
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5424277782440186
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.42552825808525085
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5117828845977783
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4526461064815521
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49511611461639404
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49516576528549194
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5155842900276184
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6020078063011169
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47449272871017456
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4968140721321106
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5514028668403625
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4511278569698334
Calibrated prediction for C: 0.5826771855354309
Raw prediction for CAT: 0.5157144069671631
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4128688871860504
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5466541647911072
Calibrated prediction for CHL: 0.5
Raw prediction for CHTR: 0.5979204177856445
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.510026752948761
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.48985978960990906
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.488504558801651
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5246275663375854
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5850384831428528
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.6136671900749207
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5242335200309753
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5028200149536133
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5425358414649963
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.6374406218528748
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.48195454478263855
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.46196794509887695
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4187465310096741
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6474591493606567
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.23315709829330444
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.7267677783966064
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.49861931800842285
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5175272226333618
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4892175793647766
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4050452709197998
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5070186853408813
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5172533988952637
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.6819410920143127
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6067754030227661
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.8126486539840698
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.4173465967178345
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5149586796760559
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4963161051273346
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5197508931159973
Calibrated prediction for MO: 0.53125
Raw prediction for MRK: 0.4545142650604248
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5204493999481201
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5831867456436157
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5213000774383545
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5698734521865845
Calibrated prediction for NVS: 0.5862069129943848
Raw prediction for ORCL: 0.4210553467273712
Calibrated prediction for ORCL: 0.4444444477558136
Raw prediction for PCG: 0.5337333679199219
Calibrated prediction for PCG: 0.5135135054588318
Raw prediction for PCLN: 0.4649173617362976
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5687872171401978
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4601810872554779
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5141317844390869
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4730822741985321
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4785657525062561
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5655772686004639
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5042625665664673
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5180981159210205
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.08605831116437912
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5093309283256531
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.578199565410614
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5445080995559692
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46539175510406494
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.43783989548683167
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6523033380508423
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5102648735046387
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5209569334983826
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4857272207736969
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.4976671636104584
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.23544715344905853
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2928340435028076
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.5211664438247681
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4840888977050781
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5609966516494751
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5706250071525574
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.46639755368232727
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5359718799591064
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  49%|████▉     | 53/108 [06:41<01:13,  1.34s/it]

Raw prediction for WMT: 0.46491363644599915
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5180470943450928
Calibrated prediction for XOM: 0.5078077912330627
Investing 1594.6841397471069 in BP
Investing 1241.5531293366357 in CODI
Investing 3351.7496977924466 in KO
Investing 3599.035372525144 in MA
Investing 941.4892635017341 in NVS
Investing 1979.211206456954 in DHR
Investing 1430.7874191174744 in CHTR
Investing 2498.963023191714 in FB
Investing 2029.178937197154 in SRE
Raw prediction for AAPL: 0.5092965960502625
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47569969296455383
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5027686357498169
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5392570495605469
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5130598545074463
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5035650730133057
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5434441566467285
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.40340355038642883
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5121085047721863
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.45211803913116455
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4945491552352905
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49495813250541687
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5155037045478821
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6169552206993103
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4762101173400879
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49713945388793945
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5543200373649597
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4454192817211151
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5159652829170227
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.40356573462486267
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5685829520225525
Calibrated prediction for CHL: 0.6363636255264282
Raw prediction for CHTR: 0.5965195298194885
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5099011659622192
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4546647369861603
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4791790544986725
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5226709842681885
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5345389246940613
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.596825122833252
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.5253739356994629
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5035866498947144
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5094895362854004
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.64627605676651
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4658876955509186
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4613751769065857
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4159088432788849
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.6412550210952759
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.238653764128685
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.7161479592323303
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.504408597946167
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5177257657051086
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49062004685401917
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.42625507712364197
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5054927468299866
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5145078301429749
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.7163443565368652
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6028057932853699
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.8010976314544678
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.41440433263778687
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5152400135993958
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4962824583053589
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5213083028793335
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4546831548213959
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5014510750770569
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5823651552200317
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5216171741485596
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5714876055717468
Calibrated prediction for NVS: 0.5862069129943848
Raw prediction for ORCL: 0.40738239884376526
Calibrated prediction for ORCL: 0.380952388048172
Raw prediction for PCG: 0.5433260798454285
Calibrated prediction for PCG: 0.5135135054588318
Raw prediction for PCLN: 0.4668443202972412
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5673735737800598
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4595480263233185
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.513585090637207
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47316521406173706
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4808734655380249
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.571643054485321
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.5041323900222778
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5110515356063843
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.09213823080062866
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.510649561882019
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5711086988449097
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5448662638664246
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4650609791278839
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.43596696853637695
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6798068284988403
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5104109644889832
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5339799523353577
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4855901002883911
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.4975596070289612
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.25609660148620605
Calibrated prediction for UL: 0.4137931168079376
Raw prediction for UN: 0.256125807762146
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.5299925804138184
Calibrated prediction for UNH: 0.4393063485622406

Simulating Trading Days:  50%|█████     | 54/108 [06:42<01:12,  1.34s/it]

Raw prediction for UPS: 0.4841172695159912
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5591262578964233
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5575953125953674
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.4722275137901306
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5366809964179993
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4639894366264343
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5174127221107483
Calibrated prediction for XOM: 0.5078077912330627
Investing 1395.895535293276 in BP
Investing 758.2618367000581 in HRG
Investing 2933.9305019431836 in KO
Investing 3150.390276451318 in MA
Investing 824.1259988056576 in NVS
Investing 1732.488596101429 in DHR
Investing 1252.4296947084472 in CHTR
Investing 2187.4496898736897 in FB
Investing 1776.2274974364877 in SRE
Raw prediction for AAPL: 0.5102996230125427
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47556570172309875
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.516470730304718
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5408089756965637
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.513208270072937
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5078132152557373
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5448051691055298
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3684619069099426
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5118669271469116
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4518989324569702
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49902212619781494
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4944617450237274
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5155449509620667
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6241630911827087
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47644883394241333
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4973081648349762
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5575605034828186
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4412754774093628
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5163367390632629
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.39603546261787415
Calibrated prediction for CELG: 0.38461539149284363
Raw prediction for CHL: 0.5977652072906494
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5947036147117615
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5090838670730591
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.430547297000885
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.455271452665329
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5209787487983704
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4449295401573181
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5767014622688293
Calibrated prediction for DHR: 0.5814636945724487
Raw prediction for DIS: 0.53012615442276
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5041096806526184
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4797014892101288
Calibrated prediction for EXC: 0.4615384638309479
Raw prediction for FB: 0.6528564691543579
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.44816580414772034
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.46147412061691284
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.41230425238609314
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.6341497898101807
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.25064826011657715
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.688319206237793
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5117485523223877
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5179474949836731
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4918302893638611
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4591057598590851
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5046733617782593
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5142863392829895
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.7414292693138123
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5979504585266113
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7630823254585266
Calibrated prediction for MA: 0.8235294222831726
Raw prediction for MCD: 0.4119822680950165
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5151457786560059
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49614420533180237
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5226923227310181
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4546360373497009
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.4864659309387207
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5815072059631348
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.52204430103302
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5737541317939758
Calibrated prediction for NVS: 0.5862069129943848
Raw prediction for ORCL: 0.3761003911495209
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5469843149185181
Calibrated prediction for PCG: 0.5135135054588318
Raw prediction for PCLN: 0.46873316168785095
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5642848014831543
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.45952290296554565
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5130921602249146
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47303521633148193
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4827785789966583
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5715785026550293
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.5038545727729797
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5033498406410217
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.09871833771467209
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5139754414558411
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5594643950462341
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5440438389778137
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46480122208595276
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.43565085530281067
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.69063800573349
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5106107592582703
Calibrated prediction for T: 0.5147916078567505

Simulating Trading Days:  51%|█████     | 55/108 [06:44<01:10,  1.33s/it]

Raw prediction for TM: 0.5423590540885925
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48548153042793274
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.4979894161224365
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.250068724155426
Calibrated prediction for UL: 0.3659015893936157
Raw prediction for UN: 0.23215852677822113
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.5194506645202637
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48413482308387756
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5537328124046326
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5458096265792847
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.479115754365921
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.536865770816803
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4632333815097809
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5152775645256042
Calibrated prediction for XOM: 0.5078077912330627
Investing 1540.7528688222997 in BP
Investing 836.9495214186092 in HRG
Investing 3238.39551277343 in KO
Investing 3385.4486516361903 in MA
Investing 909.6486555235538 in NVS
Investing 1817.8111681968708 in HON
Investing 1382.399037987361 in CHTR
Investing 2414.4495772523815 in FB
Investing 1960.5533101596598 in SRE
Raw prediction for AAPL: 0.5112218856811523
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4753233790397644
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5279587507247925
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5361303091049194
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5134676694869995
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5118599534034729
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5455600023269653
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3332597613334656
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5112826228141785
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4521179795265198
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5062403678894043
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4940260648727417
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5158513784408569
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6234411001205444
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47570130228996277
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49708491563796997
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5589008331298828
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43892553448677063
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5165343284606934
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.3890869915485382
Calibrated prediction for CELG: 0.3529411852359772
Raw prediction for CHL: 0.6144908666610718
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5934053063392639
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5082476735115051
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.41055944561958313
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.4309592545032501
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5195542573928833
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.29977190494537354
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.5546698570251465
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5332924723625183
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5044488906860352
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4582020938396454
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6570361852645874
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.43265947699546814
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.46175068616867065
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.41429251432418823
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.626917839050293
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.27778246998786926
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.6530032753944397
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5182495713233948
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.518195390701294
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49262940883636475
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5043240189552307
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5025782585144043
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5160480737686157
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.7936179041862488
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5924700498580933
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7128222584724426
Calibrated prediction for MA: 0.782608687877655
Raw prediction for MCD: 0.40715622901916504
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5149213075637817
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49602773785591125
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.523168683052063
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4546261429786682
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.4743969142436981
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.580670952796936
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5224406719207764
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5756131410598755
Calibrated prediction for NVS: 0.5862069129943848
Raw prediction for ORCL: 0.32888737320899963
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5428721308708191
Calibrated prediction for PCG: 0.5135135054588318
Raw prediction for PCLN: 0.47051480412483215
Calibrated prediction for PCLN: 0.48174017667770386
Raw prediction for PEP: 0.5622796416282654
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4600061774253845
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5126357078552246
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4730493724346161
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48445796966552734
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5689815282821655
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.5031052231788635
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4968504309654236
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.10859266668558121
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5170395970344543
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5499216318130493
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5426265597343445
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46475663781166077
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4369833171367645
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6764395833015442
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5108631253242493
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5563983917236328
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48524293303489685
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.4983392357826233
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.2274535745382309
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2136712223291397
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.4972195625305176
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48431381583213806
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5489106178283691
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.5338471531867981
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.48567771911621094
Calibrated prediction for VZ: 0.5428571701049805

Simulating Trading Days:  52%|█████▏    | 56/108 [06:45<01:09,  1.34s/it]

Raw prediction for WFC: 0.5367581248283386
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.466917484998703
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5186357498168945
Calibrated prediction for XOM: 0.5078077912330627
Investing 1657.0485554941104 in BP
Investing 900.1222866768164 in HRG
Investing 3482.828891736252 in KO
Investing 3183.5388936025547 in MA
Investing 978.3087353876673 in NVS
Investing 1955.0191541905826 in HON
Investing 1486.7422124382226 in CHTR
Investing 2596.691698752149 in FB
Investing 2108.5354415419547 in SRE
Raw prediction for AAPL: 0.5119813680648804
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47508880496025085
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.536454439163208
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5391230583190918
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5136879086494446
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5133711695671082
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5462466478347778
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.31424766778945923
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5105286240577698
Calibrated prediction for BABA: 0.5234741568565369
Raw prediction for BAC: 0.4523601233959198
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5110296010971069
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4938097596168518
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5161216855049133
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6154447793960571
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4744071662425995
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4966305196285248
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5586817264556885
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4372827410697937
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5162818431854248
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.38086098432540894
Calibrated prediction for CELG: 0.3529411852359772
Raw prediction for CHL: 0.634208083152771
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.591850996017456
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5071892142295837
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4015195071697235
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.41351407766342163
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5184918642044067
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2039371281862259
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.5293825268745422
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5352851152420044
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.504295289516449
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4499322175979614
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6581117510795593
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4201338589191437
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.46132731437683105
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.41240864992141724
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.6200422048568726
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.2956676185131073
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.590348482131958
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5219343304634094
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.518370509147644
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4929961860179901
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5367220044136047
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5011798739433289
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5172588229179382
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8070920705795288
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5869005918502808
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6608431935310364
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4044751822948456
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5148042440414429
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4962525963783264
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5225889682769775
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4547341763973236
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.46976473927497864
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.580461859703064
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5228737592697144
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5729930400848389
Calibrated prediction for NVS: 0.5862069129943848
Raw prediction for ORCL: 0.2824993133544922
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5301904082298279
Calibrated prediction for PCG: 0.5135135054588318
Raw prediction for PCLN: 0.4718882739543915
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5599784851074219
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46070313453674316
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5117731094360352
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4725955128669739
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48491495847702026
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.563453197479248
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5018356442451477
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4918261170387268
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.11791745573282242
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5189154148101807
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5411441326141357
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5386689901351929
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4650806784629822
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4389753043651581
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6524783968925476
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5110504627227783
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5744180083274841
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.4847913384437561
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.4991685748100281
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.2146151214838028
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.20465414226055145
Calibrated prediction for UN: 0.3088753819465637

Simulating Trading Days:  53%|█████▎    | 57/108 [06:46<01:08,  1.34s/it]

Raw prediction for UNH: 0.4700593054294586
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4843035340309143
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5383813977241516
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.520881175994873
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5004714727401733
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5365073084831238
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4728749096393585
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5171001553535461
Calibrated prediction for XOM: 0.5078077912330627
Investing 1737.6605348865437 in BP
Investing 943.9113711811174 in HRG
Investing 3652.261302100531 in KO
Investing 2689.731858015973 in MA
Investing 1025.9014286464305 in NVS
Investing 1282.792725997569 in HON
Investing 1559.0691410569152 in CHTR
Investing 2723.015370447993 in FB
Investing 2211.111322615706 in SRE
Raw prediction for AAPL: 0.5125818848609924
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47489768266677856
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.540765643119812
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5394489765167236
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5138816833496094
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5110361576080322
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5464011430740356
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.31321099400520325
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.509739339351654
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4524683654308319
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5166156888008118
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49380823969841003
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5166658759117126
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5973273515701294
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47202008962631226
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4960528612136841
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5571275949478149
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43719640374183655
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5159892439842224
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.37138497829437256
Calibrated prediction for CELG: 0.3529411852359772
Raw prediction for CHL: 0.6393337249755859
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5900143384933472
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5061329007148743
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.40112927556037903
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.404959499835968
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5179276466369629
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.1565646082162857
Calibrated prediction for D: 0.30260446667671204
Raw prediction for DHR: 0.5042226314544678
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5335261225700378
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5040096044540405
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.447224497795105
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6578677892684937
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.41384604573249817
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.46414726972579956
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4077059328556061
Calibrated prediction for GMRE: 0.4285714328289032
Raw prediction for GOOG: 0.6147143840789795
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3079732358455658
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.5343717932701111
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5241520404815674
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5185433030128479
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49302560091018677
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5533225536346436
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.4985818564891815
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5186178088188171
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8145209550857544
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5826422572135925
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.6117644906044006
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4026933014392853
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5150182247161865
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4964752197265625
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5215615630149841
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45516860485076904
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.46822866797447205
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5808597207069397
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5236280560493469
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.565596878528595
Calibrated prediction for NVS: 0.5862069129943848
Raw prediction for ORCL: 0.25495219230651855
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5126606822013855
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47267529368400574
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5567749738693237
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46140941977500916
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5111157894134521
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4723416268825531
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48463010787963867
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5596749782562256
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5004187822341919
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4886411428451538
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.1278345286846161
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5200976729393005
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5362218618392944
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.534442126750946
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4652963876724243
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4419710040092468
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6344642043113708
Calibrated prediction for SRE: 0.6904761791229248

Simulating Trading Days:  54%|█████▎    | 58/108 [06:48<01:06,  1.34s/it]

Raw prediction for T: 0.5112936496734619
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5939441919326782
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.484170138835907
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5011510848999023
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.20483140647411346
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.20269979536533356
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.437815397977829
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4842109978199005
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5288828611373901
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5074397921562195
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.536720335483551
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5361971259117126
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4778836965560913
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5151053071022034
Calibrated prediction for XOM: 0.5078077912330627
Investing 1889.7514031440792 in BP
Investing 1026.528370945384 in HRG
Investing 3971.9299493349777 in KO
Investing 1545.4346804736224 in MA
Investing 1115.6947086898595 in NVS
Investing 1395.0707317267834 in HON
Investing 1695.528578660681 in CHTR
Investing 2961.35062848911 in FB
Investing 2404.6415514026808 in SRE
Raw prediction for AAPL: 0.5130182504653931
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.474685937166214
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5405309200286865
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5223764181137085
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5140252709388733
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.5033824443817139
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5461785197257996
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3245103657245636
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5093262195587158
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45259883999824524
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.522764265537262
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49429911375045776
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5170753002166748
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5808541178703308
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46838152408599854
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4954364001750946
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5566105842590332
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43816113471984863
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5162041187286377
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.35784992575645447
Calibrated prediction for CELG: 0.34485960006713867
Raw prediction for CHL: 0.6369336843490601
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5874274373054504
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5053646564483643
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.40274307131767273
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.40256795287132263
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5180742740631104
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.1639583557844162
Calibrated prediction for D: 0.3333333432674408
Raw prediction for DHR: 0.4837902784347534
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5307369828224182
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5037083625793457
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4385402202606201
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.655634343624115
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.41205325722694397
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.46876028180122375
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.39496463537216187
Calibrated prediction for GMRE: 0.3843337893486023
Raw prediction for GOOG: 0.6108483672142029
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3246748745441437
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.5297922492027283
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5264137387275696
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5187444090843201
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49286723136901855
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5626511573791504
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.49399086833000183
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5199878215789795
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8280032873153687
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5807240009307861
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5855571627616882
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4033622741699219
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.515167236328125
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49665793776512146
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5209199786186218
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4560950696468353
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.4676375687122345
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5817369222640991
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5249735713005066
Calibrated prediction for NGG: 0.5000624060630798
Raw prediction for NVS: 0.5493794679641724
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.23986895382404327
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5003207325935364
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47275540232658386
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5551701784133911
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46181005239486694
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5108451247215271
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47226107120513916
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4848320186138153
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5588798522949219
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5001254081726074
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4863255023956299
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.13630738854408264
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5228092670440674
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5353744029998779
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5295181274414062
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46545299887657166
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4426578879356384
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6455603241920471
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5116555094718933
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.6107243299484253
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.48369815945625305
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5036483407020569
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.19927959144115448
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.20486213266849518
Calibrated prediction for UN: 0.3088753819465637

Simulating Trading Days:  55%|█████▍    | 59/108 [06:49<01:06,  1.36s/it]

Raw prediction for UNH: 0.4093727767467499
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48400771617889404
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5175227522850037
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.4985489845275879
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.5778446197509766
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5357491374015808
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.48090729117393494
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5122204422950745
Calibrated prediction for XOM: 0.5078077912330627
Investing 1644.802894065229 in BP
Investing 893.4703435393095 in HRG
Investing 3457.090633625758 in KO
Investing 945.2525127910104 in JPM
Investing 884.5126507049989 in ABBV
Investing 1214.2424517596526 in HON
Investing 1475.7551223465168 in CHTR
Investing 2577.5020333240145 in FB
Investing 2092.953272243228 in SRE
Raw prediction for AAPL: 0.5133015513420105
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47443264722824097
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5376825928688049
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5240136384963989
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5141304135322571
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4937933087348938
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5456275343894958
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3404715061187744
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5089853405952454
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45312219858169556
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5281577706336975
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49509409070014954
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5173596143722534
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5766834616661072
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46490922570228577
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49494150280952454
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5577751994132996
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.44040077924728394
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5166431069374084
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.34334102272987366
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.6258875131607056
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5851554870605469
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5047850012779236
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.4070640504360199
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.4050160050392151
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.518921434879303
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.19807204604148865
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.46744680404663086
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.527098536491394
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5036567449569702
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4202289283275604
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.653390109539032
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.421046644449234
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.47328636050224304
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3764548897743225
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6087202429771423
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.3508293628692627
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.5860321521759033
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5295117497444153
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5189884901046753
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49249163269996643
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5672253966331482
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.4898192882537842
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5220015048980713
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8431494832038879
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.584382951259613
Calibrated prediction for LMT: 0.5677965879440308
Raw prediction for MA: 0.5688282251358032
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.40454235672950745
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5148693323135376
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49682676792144775
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5213695168495178
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4575807452201843
Calibrated prediction for MRK: 0.4604100286960602
Raw prediction for MSFT: 0.4666059911251068
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5824747681617737
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5264683365821838
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5235450863838196
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2398127019405365
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.49298620223999023
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47231951355934143
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5585447549819946
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46169477701187134
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5110689401626587
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47220927476882935
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4853206276893616
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5618274211883545
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5011001825332642
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4855198562145233
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.14654725790023804
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5334206223487854
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5332032442092896
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5226476788520813
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4655345678329468
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4428251087665558
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6626380085945129
Calibrated prediction for SRE: 0.6904761791229248

Simulating Trading Days:  56%|█████▌    | 60/108 [06:51<01:05,  1.36s/it]

Raw prediction for T: 0.5121146440505981
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.6164098978042603
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.4835735857486725
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5060767531394958
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.19999700784683228
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.20698539912700653
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3841872215270996
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4834849536418915
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5038622617721558
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.49148228764533997
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.6164069175720215
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5354058146476746
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4826890230178833
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5087398886680603
Calibrated prediction for XOM: 0.5078077912330627
Investing 1702.0448194804403 in BP
Investing 924.5646241671693 in HRG
Investing 3577.4032406363967 in KO
Investing 978.14890057763 in JPM
Investing 915.2951884565762 in ABBV
Investing 1256.5001448305968 in HON
Investing 1527.1138991028552 in CHTR
Investing 2667.2034678736773 in FB
Investing 2165.7915895513675 in SRE
Raw prediction for AAPL: 0.5134081840515137
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4743938744068146
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5318132638931274
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5270099639892578
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5142549872398376
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4850878119468689
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5448960065841675
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3566732406616211
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5086550116539001
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4538431465625763
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5282642841339111
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49577558040618896
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5172013640403748
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5822855830192566
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46214431524276733
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4946422278881073
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5603988170623779
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4431266784667969
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5177454352378845
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.32945916056632996
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.6159970164299011
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5837806463241577
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5042333006858826
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.41229385137557983
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.4044404923915863
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5200948715209961
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.24047112464904785
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.46125781536102295
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5229954719543457
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5038689970970154
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.3938547968864441
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6503141522407532
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.43346619606018066
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4758304953575134
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3633662462234497
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6083775758743286
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.3737262189388275
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6870368123054504
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5313769578933716
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5192581415176392
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49205461144447327
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5689783096313477
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.48756441473960876
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5244423151016235
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8540802597999573
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5905182957649231
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5587977170944214
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4059649109840393
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5140405297279358
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4969762861728668
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5226895213127136
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45919522643089294
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.46569061279296875
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5830305218696594
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5274553894996643
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4969954788684845
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2577681243419647
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4943894147872925
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4715474843978882
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5625313520431519
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4615021347999573
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5115756988525391
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47222840785980225
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48627322912216187
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.567880392074585
Calibrated prediction for PPL: 0.5684130787849426
Raw prediction for PTR: 0.5026555061340332
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4859537184238434
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.1556764394044876
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5417519211769104
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.530780553817749
Calibrated prediction for SNP: 0.5384615659713745
Raw prediction for SNY: 0.5191610455513
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4655047059059143
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.44232672452926636
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6797986030578613
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5128286480903625
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.6076993346214294
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.4838133752346039
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5081940293312073
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.20048440992832184
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.20676939189434052
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3651987314224243
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4832474887371063
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4905185103416443
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.4841345548629761
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.6474335789680481
Calibrated prediction for VZ: 0.5716716051101685

Simulating Trading Days:  56%|█████▋    | 61/108 [06:52<01:03,  1.36s/it]

Raw prediction for WFC: 0.5351610779762268
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4842974841594696
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5073635578155518
Calibrated prediction for XOM: 0.5078077912330627
Investing 1736.2769967253248 in BP
Investing 943.1598219707747 in HRG
Investing 3649.3533446573188 in KO
Investing 997.8218058696796 in JPM
Investing 933.7039558192357 in ABBV
Investing 2048.4944598176407 in HON
Investing 1557.8277986834628 in CHTR
Investing 2720.847285483776 in FB
Investing 2209.3508194379424 in SRE
Raw prediction for AAPL: 0.5134388208389282
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4744097590446472
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5230695009231567
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5292150974273682
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5143332481384277
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48312240839004517
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5444840788841248
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.38166356086730957
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5083696246147156
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45460471510887146
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.522567629814148
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49589434266090393
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5169094204902649
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5914097428321838
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4604635536670685
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4945966899394989
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5608582496643066
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4457440674304962
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5184076428413391
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.31833136081695557
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.6030648350715637
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5815547704696655
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5037370324134827
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.41453817486763
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.3992033898830414
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5211727619171143
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.27083858847618103
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.46260103583335876
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5224494934082031
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5043485164642334
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.36976954340934753
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6492630243301392
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4461471140384674
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.47781434655189514
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.35722053050994873
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6102084517478943
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.39818862080574036
Calibrated prediction for HD: 0.3981131315231323
Raw prediction for HON: 0.7432241439819336
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5322707295417786
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5194669961929321
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4917142689228058
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5617541074752808
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.4877699911594391
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5266091227531433
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8480509519577026
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5983512997627258
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5531079769134521
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4070378839969635
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5132703185081482
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4971204996109009
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5245833396911621
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4605250358581543
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4664810299873352
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5823875665664673
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5281352400779724
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.48335784673690796
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2920035123825073
Calibrated prediction for ORCL: 0.2332497090101242
Raw prediction for PCG: 0.4980914890766144
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4706003665924072
Calibrated prediction for PCLN: 0.4836472272872925
Raw prediction for PEP: 0.5655573606491089
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46183156967163086
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5118026733398438
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47220125794410706
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48736873269081116
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5718586444854736
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.503324568271637
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.48961836099624634
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.1588136851787567
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5443298816680908
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5328558683395386
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.517738401889801
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4655939042568207
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.44170114398002625
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6790152192115784
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5135195851325989
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5866459012031555
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.4841998815536499
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5108004212379456
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.19260281324386597
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.20415423810482025
Calibrated prediction for UN: 0.3088753819465637

Simulating Trading Days:  57%|█████▋    | 62/108 [06:53<01:02,  1.35s/it]

Raw prediction for UNH: 0.35536181926727295
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48292210698127747
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4760805666446686
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.48180723190307617
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.6663622856140137
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5346534848213196
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4854203760623932
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5063955187797546
Calibrated prediction for XOM: 0.5078077912330627
Investing 1706.5303602951537 in BP
Investing 927.0012065121678 in HRG
Investing 3586.83107007009 in KO
Investing 980.7266980399479 in JPM
Investing 917.7073422837509 in ABBV
Investing 2013.398780936712 in HON
Investing 1531.1384298582984 in CHTR
Investing 2674.2325718545844 in FB
Investing 2171.49928094698 in SRE
Raw prediction for AAPL: 0.5135199427604675
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47438451647758484
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.5085989832878113
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5257139205932617
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5143768787384033
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48732802271842957
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5451107025146484
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.41978225111961365
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5079947710037231
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45477673411369324
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5091545581817627
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.495578408241272
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5166898965835571
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5951988101005554
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4609391689300537
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49465489387512207
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5596942901611328
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.44736817479133606
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.518763542175293
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.31567302346229553
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.5940735340118408
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5793604850769043
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.503337025642395
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.41481897234916687
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4018172323703766
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5223478674888611
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3057141602039337
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.46754905581474304
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5246938467025757
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5048640370368958
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.35710975527763367
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6516751050949097
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4550490081310272
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.48530614376068115
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.36053600907325745
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.613167405128479
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.4144003987312317
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7787064909934998
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5324477553367615
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5195508003234863
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49148690700531006
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5545444488525391
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.48627761006355286
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.527400016784668
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8463102579116821
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6051118969917297
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5548763275146484
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.40761297941207886
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5123399496078491
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4973927438259125
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5268927812576294
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4612446129322052
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.47082769870758057
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5832590460777283
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5286831259727478
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.47021418809890747
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3430439233779907
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.5046439170837402
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4697347581386566
Calibrated prediction for PCLN: 0.4643542170524597
Raw prediction for PEP: 0.5696969628334045
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4625285267829895
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5120496153831482
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47226861119270325
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48856639862060547
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5736422538757324
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.5029690861701965
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4927329421043396
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.15856552124023438
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5508102774620056
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5343543291091919
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5176688432693481
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.46636706590652466
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.4410482943058014
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6659432649612427
Calibrated prediction for SRE: 0.6904761791229248

Simulating Trading Days:  58%|█████▊    | 63/108 [06:55<01:00,  1.35s/it]

Raw prediction for T: 0.5141650438308716
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5644927024841309
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48388755321502686
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5141614675521851
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.1806577444076538
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.20128397643566132
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3537657558917999
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4827249050140381
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.46794965863227844
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.48359817266464233
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.6823230385780334
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5340183973312378
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4852727949619293
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5063179731369019
Calibrated prediction for XOM: 0.5078077912330627
Investing 1878.9390726414251 in BP
Investing 1020.6550248541753 in HRG
Investing 3949.2043044304955 in KO
Investing 1079.8083382537404 in JPM
Investing 1010.4222126869329 in ABBV
Investing 2216.810041197452 in HON
Investing 1685.8275061605239 in CHTR
Investing 2944.4070761910702 in FB
Investing 2390.883244806944 in SRE
Raw prediction for AAPL: 0.513595700263977
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47427594661712646
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.48725301027297974
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5217178463935852
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.514427900314331
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4901632070541382
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5459870100021362
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.47469764947891235
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5075929164886475
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4542982578277588
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.48529043793678284
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49526649713516235
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.516021728515625
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5907713770866394
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4644353985786438
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49478402733802795
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5573746562004089
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4460977613925934
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5188536643981934
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.31614139676094055
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.5829111337661743
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5782440304756165
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.503016471862793
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.41341105103492737
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4078158140182495
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5235065817832947
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.38381582498550415
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.4751743972301483
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5319278836250305
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5054344534873962
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.35643720626831055
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6543620228767395
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.45555707812309265
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.4931260049343109
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4049047529697418
Calibrated prediction for GMRE: 0.42773064970970154
Raw prediction for GOOG: 0.6155191659927368
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.42953452467918396
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7869591116905212
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5312228202819824
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5195068717002869
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49138468503952026
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5363830327987671
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.48034363985061646
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5261406898498535
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8323044776916504
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6084486842155457
Calibrated prediction for LMT: 0.5808747410774231
Raw prediction for MA: 0.5596844553947449
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.40899592638015747
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5106232166290283
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.497685045003891
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5293776988983154
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4612175524234772
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4749239385128021
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5850526094436646
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5291994214057922
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.45757049322128296
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.4201214909553528
Calibrated prediction for ORCL: 0.4444444477558136
Raw prediction for PCG: 0.5106605291366577
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.468861848115921
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5726373195648193
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46418488025665283
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5123238563537598
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47224941849708557
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48945382237434387
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5743347406387329
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.5005683898925781
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.49399593472480774
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.15564322471618652
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5563006401062012
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5370724201202393
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5196523666381836
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4673609137535095
Calibrated prediction for SO: 0.46296167373657227
Raw prediction for SPLP: 0.44061484932899475
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6619724035263062
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5146802067756653
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5433682203292847
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4829297661781311
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5166902542114258
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.15430417656898499
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.20366552472114563
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3565731942653656
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48257505893707275
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.46276429295539856
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.4894699156284332
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.6944348812103271
Calibrated prediction for VZ: 0.5716716051101685

Simulating Trading Days:  59%|█████▉    | 64/108 [06:56<00:59,  1.35s/it]

Raw prediction for WFC: 0.533315896987915
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4834223687648773
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5059092044830322
Calibrated prediction for XOM: 0.5078077912330627
Investing 1798.9222198119164 in BP
Investing 977.1892179514301 in HRG
Investing 3781.022746964112 in KO
Investing 1033.823417218137 in JPM
Investing 967.3921822482256 in ABBV
Investing 2122.4045517378554 in HON
Investing 1614.0345388309613 in CHTR
Investing 2819.0160025174923 in FB
Investing 2289.064641150302 in SRE
Raw prediction for AAPL: 0.5137101411819458
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47412359714508057
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4578016996383667
Calibrated prediction for ABBV: 0.585688054561615
Raw prediction for AEP: 0.5121324062347412
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5145096182823181
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49314892292022705
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5470101237297058
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5364022850990295
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.5071111917495728
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.452847421169281
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4594879150390625
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49500030279159546
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5149421691894531
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5800371170043945
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46716833114624023
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4949232041835785
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5603707432746887
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.44051289558410645
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5187184810638428
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.32837802171707153
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.5791590213775635
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5774810910224915
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5028204917907715
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.4067997634410858
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.4286109507083893
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.524511456489563
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4532398283481598
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.4828813970088959
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5391920208930969
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5061430931091309
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.35615164041519165
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6590670347213745
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4532230794429779
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5005956888198853
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4439633786678314
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6174612641334534
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.43323031067848206
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7865400910377502
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5291882157325745
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5192575454711914
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4911850690841675
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.5116866827011108
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.46955034136772156
Calibrated prediction for JNJ: 0.48395657539367676
Raw prediction for JPM: 0.5225632190704346
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8318442106246948
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6105810403823853
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.5586390495300293
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4110281765460968
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5074589848518372
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4979267120361328
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5319448709487915
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4604687988758087
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.48087605834007263
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5876343846321106
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5298806428909302
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.44796210527420044
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.5106034278869629
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.5153504610061646
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4680849313735962
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5773791670799255
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46595168113708496
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5124617218971252
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4721899926662445
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49026551842689514
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5777232646942139
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.4978654086589813
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4929872453212738
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.1512393355369568
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5614058375358582
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.537347674369812
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5230016708374023
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4683906137943268
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44044947624206543
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6681274771690369
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5151054263114929
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5286352038383484
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4816587269306183
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5194783210754395
Calibrated prediction for TSM: 0.5760757327079773

Simulating Trading Days:  60%|██████    | 65/108 [06:57<00:58,  1.35s/it]

Raw prediction for UL: 0.14526040852069855
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2107265591621399
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3605722486972809
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4822382628917694
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4671350121498108
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5029832720756531
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.7080152034759521
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5324823260307312
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4810568690299988
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5072146654129028
Calibrated prediction for XOM: 0.5078077912330627
Investing 1871.3061034869545 in BP
Investing 1016.5087337713488 in HRG
Investing 3933.161126086217 in KO
Investing 1075.4217437874047 in JPM
Investing 1006.3174912008928 in ABBV
Investing 2207.8045109425543 in HON
Investing 1678.9790300488469 in CHTR
Investing 2932.445768494607 in FB
Investing 2381.170562620876 in SRE
Raw prediction for AAPL: 0.5138733386993408
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47388505935668945
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.42248114943504333
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5033197999000549
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5146034955978394
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49323445558547974
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5480972528457642
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.573604166507721
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.5064235329627991
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45109879970550537
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4409719705581665
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49474164843559265
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.513935387134552
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5677173733711243
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4688946008682251
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49515265226364136
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5645703673362732
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4355229139328003
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5182477235794067
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.3467922508716583
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.5739753246307373
Calibrated prediction for CHL: 0.6363636255264282
Raw prediction for CHTR: 0.5765179991722107
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.502741813659668
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.39412060379981995
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.45568013191223145
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5254627466201782
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4990008771419525
Calibrated prediction for D: 0.550000011920929
Raw prediction for DHR: 0.4879430830478668
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5466537475585938
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5069655776023865
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.351578027009964
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.66356360912323
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4439476728439331
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5064470767974854
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4635007977485657
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6181365251541138
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.4248414635658264
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.773891031742096
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5269842743873596
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5187324285507202
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49080905318260193
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4780645966529846
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.4603405296802521
Calibrated prediction for JNJ: 0.4118923544883728
Raw prediction for JPM: 0.5180580019950867
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.829630970954895
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6101372838020325
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.5661197304725647
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4128442108631134
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5024916529655457
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4979616403579712
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5341318249702454
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4592246115207672
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.48674076795578003
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5890936255455017
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5303558111190796
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.44809839129447937
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.6066349744796753
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.5159082412719727
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4673520624637604
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5802918076515198
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4672277569770813
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5121938586235046
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47213056683540344
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49088120460510254
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5820609927177429
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.49593642354011536
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4901438355445862
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.147284135222435
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.562843382358551
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5383903980255127
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5267273783683777
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46939754486083984
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44062724709510803
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6729490756988525
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5154159665107727
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.512831449508667
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.48038962483406067
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5222322940826416
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.14169028401374817
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.22120517492294312
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3641572594642639
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4818783700466156
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4730065166950226
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.51827472448349
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.7154602408409119
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.532248854637146
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  61%|██████    | 66/108 [06:59<00:56,  1.35s/it]

Raw prediction for WMT: 0.4787878394126892
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5091977119445801
Calibrated prediction for XOM: 0.5078077912330627
Investing 1793.9764097297627 in BP
Investing 974.5026135873896 in HRG
Investing 3770.6275112964227 in KO
Investing 1030.981107404109 in JPM
Investing 585.9570002163631 in SNY
Investing 2116.5693857063347 in HON
Investing 1609.5970438647091 in CHTR
Investing 2811.2656297590406 in FB
Investing 2282.7712734570136 in SRE
Raw prediction for AAPL: 0.5140104293823242
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4738456904888153
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3821660280227661
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4962354302406311
Calibrated prediction for AEP: 0.4117647111415863
Raw prediction for AGFS: 0.5146596431732178
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.49125906825065613
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5495485067367554
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5776975750923157
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.5055334568023682
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4495779275894165
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.43457040190696716
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4944804608821869
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5129483342170715
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5590285658836365
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47048577666282654
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4955138862133026
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5711930394172668
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4297477900981903
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5177002549171448
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.37186554074287415
Calibrated prediction for CELG: 0.3529411852359772
Raw prediction for CHL: 0.568042516708374
Calibrated prediction for CHL: 0.6363636255264282
Raw prediction for CHTR: 0.5764344930648804
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5027816891670227
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.37822580337524414
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.5005596280097961
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5258983373641968
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5399398803710938
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.4861522614955902
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5542070865631104
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.507746160030365
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3461555242538452
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.670086681842804
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.43339455127716064
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5083981156349182
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4706268906593323
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6170018911361694
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.407277911901474
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7511705756187439
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.525192379951477
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5177454352378845
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4903149902820587
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.44588351249694824
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.45647141337394714
Calibrated prediction for JNJ: 0.4118923544883728
Raw prediction for JPM: 0.5139816999435425
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8250006437301636
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6084932684898376
Calibrated prediction for LMT: 0.5818395614624023
Raw prediction for MA: 0.5865570306777954
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.41786858439445496
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4958128035068512
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4978128671646118
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5360049605369568
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4577901065349579
Calibrated prediction for MRK: 0.46936261653900146
Raw prediction for MSFT: 0.4919686019420624
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5887487530708313
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5303441882133484
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.45404353737831116
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.6945739984512329
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.5083015561103821
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46700021624565125
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5819861888885498
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46766602993011475
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5113793015480042
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4721362888813019
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49129968881607056
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5871135592460632
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.49526241421699524
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.48622941970825195
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.14319439232349396
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5550612807273865
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.536737322807312
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5292865633964539
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.47048065066337585
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44108572602272034
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6705549359321594
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.515579879283905
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.49492520093917847
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4799549877643585
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5249995589256287
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.15285609662532806
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.23211891949176788
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3666779696941376
Calibrated prediction for UNH: 0.4393063485622406

Simulating Trading Days:  62%|██████▏   | 67/108 [07:00<00:55,  1.35s/it]

Raw prediction for UPS: 0.4814799129962921
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4795876741409302
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5287396907806396
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.713503897190094
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5324064493179321
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47716203331947327
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5118899941444397
Calibrated prediction for XOM: 0.5078077912330627
Investing 1705.429901566521 in BP
Investing 926.4034283577945 in HRG
Investing 3584.5180965355867 in KO
Investing 980.0942749196969 in JPM
Investing 557.0355238683088 in SNY
Investing 2012.100437634858 in HON
Investing 1530.1510728858793 in CHTR
Investing 2672.5080888658485 in FB
Investing 2170.098986294429 in SRE
Raw prediction for AAPL: 0.5140982866287231
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47385239601135254
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.35296496748924255
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.48270952701568604
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5147415399551392
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4853426516056061
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5504875779151917
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5355989336967468
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.5049270987510681
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.44849321246147156
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.43554604053497314
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4942455291748047
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5123926401138306
Calibrated prediction for BHP: 0.5092528462409973
Raw prediction for BP: 0.5540263652801514
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4710914194583893
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49581682682037354
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5797029137611389
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.42330512404441833
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5171114802360535
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.40126827359199524
Calibrated prediction for CELG: 0.38461539149284363
Raw prediction for CHL: 0.5874693393707275
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5772327184677124
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5029347538948059
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.374161958694458
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.5528238415718079
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5260781049728394
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5135640501976013
Calibrated prediction for D: 0.5605588555335999
Raw prediction for DHR: 0.4787951111793518
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5586428046226501
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5086315274238586
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3411565124988556
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6751691102981567
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4217223823070526
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5077748894691467
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.46942174434661865
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6145142912864685
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3891354203224182
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.7207760214805603
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5233832597732544
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5170154571533203
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.489753395318985
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.42000487446784973
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.4593788981437683
Calibrated prediction for JNJ: 0.4118923544883728
Raw prediction for JPM: 0.5108770728111267
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8096733689308167
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6043497920036316
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6029802560806274
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4185708165168762
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.48827019333839417
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49739697575569153
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5375829935073853
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45665499567985535
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.49678146839141846
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5887591242790222
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5303362607955933
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4638727903366089
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.748929500579834
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.501544177532196
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4670338034629822
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5828940868377686
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46759137511253357
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5104410648345947
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4722652733325958
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49164995551109314
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5919409990310669
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.4944637417793274
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.48183873295783997
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.14245738089084625
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5385993123054504
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5357944965362549
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5310702919960022
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4714547097682953
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4415189325809479
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6693498492240906
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5155798196792603
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.46822789311408997
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.47994503378868103
Calibrated prediction for TOT: 0.4789581000804901

Simulating Trading Days:  63%|██████▎   | 68/108 [07:01<00:54,  1.35s/it]

Raw prediction for TSM: 0.5282512903213501
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.16321252286434174
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.23382879793643951
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3672553300857544
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4812220633029938
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4795514941215515
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5331147909164429
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.706518292427063
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5326551198959351
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4763445258140564
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.513094425201416
Calibrated prediction for XOM: 0.5078077912330627
Investing 1771.5510355668 in BP
Investing 962.3209674888358 in HRG
Investing 3723.4932611962663 in KO
Investing 1448.770671125759 in MA
Investing 578.6323191882339 in SNY
Investing 2090.1114790365996 in HON
Investing 1589.4764805370664 in CHTR
Investing 2776.123760960264 in FB
Investing 2254.2357812074542 in SRE
Raw prediction for AAPL: 0.5141875147819519
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47377902269363403
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3469237983226776
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4691709280014038
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5148031115531921
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48088863492012024
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5510042905807495
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4597468376159668
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5043867826461792
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.44781363010406494
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4363427758216858
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4938597083091736
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5118448138237
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5529290437698364
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.47114455699920654
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49592697620391846
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5849941372871399
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.41842716932296753
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5167346596717834
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4313966929912567
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6071999073028564
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5779391527175903
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5031052231788635
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.38016223907470703
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.5890339612960815
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.526146411895752
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4855368137359619
Calibrated prediction for D: 0.550000011920929
Raw prediction for DHR: 0.46847137808799744
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5573151707649231
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5093890428543091
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3343731164932251
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.679742157459259
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4136275351047516
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5127809643745422
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.46669062972068787
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6116531491279602
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.358425110578537
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6856697797775269
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5230288505554199
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5165125131607056
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48899126052856445
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.3951886296272278
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.46906566619873047
Calibrated prediction for JNJ: 0.42438051104545593
Raw prediction for JPM: 0.5095617175102234
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8132418990135193
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6002259254455566
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6066642999649048
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4189686179161072
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.48130151629447937
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4968332350254059
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5389111638069153
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45587262511253357
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5014984011650085
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5881532430648804
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5300627946853638
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.48337066173553467
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.777588963508606
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.4993944466114044
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4672587215900421
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5836001634597778
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4673534333705902
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5095432996749878
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4724317491054535
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49152106046676636
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5960650444030762
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.49350234866142273
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4775741994380951
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.14243528246879578
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5215948820114136
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5369457006454468
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5318905711174011
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4722789227962494
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4414961636066437
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6640705466270447
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5154067873954773
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.44099652767181396
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.48037171363830566
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5321308970451355
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.18068699538707733
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.23451410233974457
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3667653203010559
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4810516834259033
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4837205410003662
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5355966687202454
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7033610939979553
Calibrated prediction for VZ: 0.5716716051101685

Simulating Trading Days:  64%|██████▍   | 69/108 [07:03<00:52,  1.35s/it]

Raw prediction for WFC: 0.5324569344520569
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47604164481163025
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5135457515716553
Calibrated prediction for XOM: 0.5078077912330627
Investing 1671.69477769017 in BP
Investing 908.0782339968772 in HRG
Investing 3513.612712554354 in KO
Investing 1367.1084356972742 in MA
Investing 865.3045011315425 in CELG
Investing 1972.2990611884131 in HON
Investing 1499.883141060642 in CHTR
Investing 2619.6431828643613 in FB
Investing 2127.1722391678886 in SRE
Raw prediction for AAPL: 0.5142068862915039
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4736189544200897
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.34570884704589844
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.45809364318847656
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5148097276687622
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4792352616786957
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5510545969009399
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.367862731218338
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5039257407188416
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.44752049446105957
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4363349676132202
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49338066577911377
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.511197566986084
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5588690042495728
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4715800881385803
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4958260953426361
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5862945914268494
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.41461849212646484
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.516496479511261
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.443517804145813
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6186673045158386
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5777838230133057
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5033836960792542
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.38402673602104187
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.6080745458602905
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5261590480804443
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4438284933567047
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.45451703667640686
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5513646006584167
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.510018527507782
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3297164738178253
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6814529895782471
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.40770232677459717
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5206770300865173
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.46389874815940857
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6098210215568542
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3215123414993286
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6529276371002197
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.523432731628418
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5161153674125671
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48810040950775146
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.366019070148468
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.48138487339019775
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5093598961830139
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8115037679672241
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5956808924674988
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5995959639549255
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.41194528341293335
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4757955074310303
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4963856637477875
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5400518774986267
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45521998405456543
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5071103572845459
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5869641900062561
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5295442342758179
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5036671161651611
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.7799335718154907
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.49169984459877014
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4671573340892792
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5830767154693604
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46831414103507996
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.508802056312561
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4724331498146057
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4909633696079254
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5981689095497131
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.4923483729362488
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.474920392036438
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.1458103358745575
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5174043774604797
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5419899821281433
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5313964486122131
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.47277119755744934
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44213399291038513
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6538680791854858
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5153363347053528
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.41691330075263977
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.4813382923603058
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.535399854183197
Calibrated prediction for TSM: 0.5760757327079773

Simulating Trading Days:  65%|██████▍   | 70/108 [07:04<00:51,  1.35s/it]

Raw prediction for UL: 0.19106781482696533
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.22872698307037354
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3650656044483185
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48093175888061523
Calibrated prediction for UPS: 0.4779593050479889
Raw prediction for UTX: 0.4862249195575714
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5355861186981201
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7048826217651367
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5323716402053833
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4758128821849823
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5142841339111328
Calibrated prediction for XOM: 0.5078077912330627
Investing 1808.5488593543075 in BP
Investing 982.4184870450728 in HRG
Investing 3801.256274954227 in KO
Investing 1479.0274127734363 in MA
Investing 1021.1891142944106 in JNJ
Investing 2133.7622543431667 in HON
Investing 1622.6717820331269 in CHTR
Investing 2834.101507950465 in FB
Investing 2301.3141981055164 in SRE
Raw prediction for AAPL: 0.5141206383705139
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4734290540218353
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3461495339870453
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.45354899764060974
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5147870182991028
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.47819599509239197
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5505132675170898
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.29019010066986084
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5034883618354797
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4474622905254364
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.432729572057724
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49326032400131226
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5106256604194641
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5699500441551208
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.470531702041626
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4957289397716522
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5821733474731445
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.41245129704475403
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5162824392318726
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.45678773522377014
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.625153660774231
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5776779055595398
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5036934614181519
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.3866223394870758
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.612141489982605
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5262320041656494
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4154456853866577
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.43695273995399475
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5428119897842407
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.510469913482666
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.32784411311149597
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6804251670837402
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4056512415409088
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.528464138507843
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.46069878339767456
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.609919548034668
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.29252955317497253
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.6178430318832397
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5239485502243042
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5156821012496948
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48727947473526
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3520839214324951
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.495245099067688
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5114132761955261
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8092405200004578
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5924303531646729
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5963331460952759
Calibrated prediction for MA: 0.6062001585960388
Raw prediction for MCD: 0.4089503884315491
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.47222772240638733
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4960138499736786
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5412362813949585
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45472434163093567
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5128615498542786
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5861354470252991
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5291609168052673
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5210331082344055
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.7606649994850159
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.4864628314971924
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4666305482387543
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.584262490272522
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.47053369879722595
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5082455277442932
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47237446904182434
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4901491701602936
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.600109875202179
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.49213406443595886
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.47454485297203064
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.15103979408740997
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5190863609313965
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5463716387748718
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5306012034416199
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.47316616773605347
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44354692101478577
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6344429850578308
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5155017971992493
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.40145716071128845
Calibrated prediction for TM: 0.27272728085517883
Raw prediction for TOT: 0.4822108745574951
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5381636619567871
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.18915414810180664
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2187410295009613
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.37342947721481323
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48082292079925537
Calibrated prediction for UPS: 0.4779593050479889

Simulating Trading Days:  66%|██████▌   | 71/108 [07:05<00:50,  1.37s/it]

Raw prediction for UTX: 0.48851150274276733
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5334990620613098
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7106176018714905
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.532332181930542
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47641777992248535
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5148674845695496
Calibrated prediction for XOM: 0.5078077912330627
Investing 1735.6113485617905 in BP
Investing 942.7982364607448 in HRG
Investing 3647.9542675765647 in KO
Investing 1268.951312704098 in MA
Investing 980.0052714251383 in JNJ
Investing 2047.709114750143 in HON
Investing 1557.2305637864663 in CHTR
Investing 2719.804176001674 in FB
Investing 2208.503805788429 in SRE
Raw prediction for AAPL: 0.5139756202697754
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4732988178730011
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3539043068885803
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.44775962829589844
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5147593021392822
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4745137691497803
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5498682856559753
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.24212615191936493
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5032620429992676
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4474964737892151
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.42827102541923523
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.49291935563087463
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5102419257164001
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5810362100601196
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46959856152534485
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49557173252105713
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5769745707511902
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4120147228240967
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.515933632850647
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4647673964500427
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6286883354187012
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5773729681968689
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5042777061462402
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.39523404836654663
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.602337121963501
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5263892412185669
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3904789686203003
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.4184202551841736
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5350304841995239
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5108341574668884
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3290019929409027
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6765028238296509
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.40741968154907227
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5325437188148499
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.45669835805892944
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6129364371299744
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.2747102975845337
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5743008255958557
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5240140557289124
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5153051614761353
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4867335855960846
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3446729779243469
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5095968842506409
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5152422189712524
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.8051009774208069
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5902316570281982
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5876168012619019
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4081800580024719
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4697609543800354
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4956333339214325
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5424647927284241
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45469194650650024
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5207250118255615
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5862322449684143
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5289737582206726
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5354050993919373
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.7060163617134094
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.48380669951438904
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46575650572776794
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5860178470611572
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.47172290086746216
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5078588128089905
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47232764959335327
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4894426167011261
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.601691484451294
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.4920646548271179
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4752595126628876
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.1586456149816513
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5206207633018494
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5464825630187988
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5293266177177429
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4734717011451721
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44686275720596313
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6265893578529358
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5158512592315674
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.3986782431602478
Calibrated prediction for TM: 0.27272728085517883

Simulating Trading Days:  67%|██████▋   | 72/108 [07:07<00:49,  1.37s/it]

Raw prediction for TOT: 0.4826244115829468
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5402276515960693
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.17420679330825806
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.21178442239761353
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3811646103858948
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4807700216770172
Calibrated prediction for UPS: 0.4779593050479889
Raw prediction for UTX: 0.4832775592803955
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5339851379394531
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7168540358543396
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5322331786155701
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4786079227924347
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5163052082061768
Calibrated prediction for XOM: 0.5078077912330627
Investing 1698.1203158567387 in BP
Investing 922.4328017989442 in HRG
Investing 3569.154614148638 in KO
Investing 975.8935258302081 in JPM
Investing 969.5686671358128 in NVS
Investing 1253.602959447973 in HON
Investing 1523.592743865202 in CHTR
Investing 2661.053541881708 in FB
Investing 1532.8177475937339 in SRE
Raw prediction for AAPL: 0.5136491656303406
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47319018840789795
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.37020614743232727
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4414863586425781
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5147085785865784
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4681876003742218
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5490471720695496
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.21088972687721252
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5034672617912292
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.44782447814941406
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.42411062121391296
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4929385781288147
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5100160837173462
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5839676856994629
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46881479024887085
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4955004155635834
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5686087608337402
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.41258397698402405
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5154063105583191
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.465610533952713
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6354871988296509
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.577398419380188
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5049467086791992
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.4090273678302765
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.581699788570404
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5265582799911499
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.34273043274879456
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.40014904737472534
Calibrated prediction for DHR: 0.46850061416625977
Raw prediction for DIS: 0.5306376814842224
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5110302567481995
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.33401066064834595
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6701826453208923
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.40800121426582336
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5321190357208252
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.45260414481163025
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6189191341400146
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.26091140508651733
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.5120266079902649
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5228231549263
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5149796009063721
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48643314838409424
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.34380635619163513
Calibrated prediction for INTC: 0.3929726481437683
Raw prediction for JNJ: 0.5227775573730469
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5209828019142151
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.777457058429718
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5903317332267761
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.574894905090332
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.40888580679893494
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.46794021129608154
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4952322244644165
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5432227849960327
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45488592982292175
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5324481725692749
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5867603421211243
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5288001894950867
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5412254929542542
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.6156446933746338
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.48793524503707886
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46468010544776917
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5846415162086487
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4730428457260132
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5075168013572693
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4722951650619507
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4885517954826355
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.6030952334403992
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.4916958212852478
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4752765893936157
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.16966785490512848
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5205164551734924
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5367167592048645
Calibrated prediction for SNP: 0.6086956262588501
Raw prediction for SNY: 0.5253718495368958
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.47359299659729004
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45076245069503784
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6084966063499451
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5162912011146545
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.41054657101631165
Calibrated prediction for TM: 0.27272728085517883
Raw prediction for TOT: 0.4824887812137604
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5419257879257202
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.14847120642662048
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.21138381958007812
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3829455077648163
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4807683229446411
Calibrated prediction for UPS: 0.4779593050479889
Raw prediction for UTX: 0.4723447263240814
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5375886559486389
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7164940237998962
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5322152972221375
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  68%|██████▊   | 73/108 [07:08<00:47,  1.36s/it]

Raw prediction for WMT: 0.48171311616897583
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5172358751296997
Calibrated prediction for XOM: 0.5078077912330627
Investing 1804.5744457838507 in BP
Investing 980.2595531868117 in HRG
Investing 3792.902746407945 in KO
Investing 1037.0716974966501 in JPM
Investing 1030.3503372570246 in NVS
Investing 1332.1905666251225 in HON
Investing 1619.1058464392097 in CHTR
Investing 2827.8733701619885 in FB
Investing 1628.9091600415031 in SRE
Raw prediction for AAPL: 0.5131402611732483
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4730706512928009
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3849475085735321
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4285028278827667
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5146122574806213
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4586528241634369
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5484559535980225
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.1894315928220749
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5041030645370483
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4483672082424164
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4199477732181549
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.49323171377182007
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5098063349723816
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5760020613670349
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46786603331565857
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49538740515708923
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5606881380081177
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.41341927647590637
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5148632526397705
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4526282250881195
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6356995701789856
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5775585174560547
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5058655142784119
Calibrated prediction for CMCSA: 0.5046131610870361
Raw prediction for CODI: 0.4224756062030792
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5566074252128601
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.52666175365448
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.28163978457450867
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.38994160294532776
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5271244049072266
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5110132098197937
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.34320175647735596
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6627076864242554
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.41021156311035156
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.526531457901001
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4484161138534546
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6275702118873596
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.2620634138584137
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.4380824565887451
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5218986868858337
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5147198438644409
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48635950684547424
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.3417660593986511
Calibrated prediction for INTC: 0.37003904581069946
Raw prediction for JNJ: 0.5360013246536255
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5264422297477722
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.7423121333122253
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5919931530952454
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.546268105506897
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4120236933231354
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4667165279388428
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4948634207248688
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5437194108963013
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45529329776763916
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5487604141235352
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5872994065284729
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.528805673122406
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5427370071411133
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.5190640687942505
Calibrated prediction for ORCL: 0.6595744490623474
Raw prediction for PCG: 0.4998587667942047
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4635907709598541
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5830559134483337
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.473422646522522
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5072944164276123
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47227275371551514
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4875410497188568
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.6039170622825623
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.49080824851989746
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.47441110014915466
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.17952975630760193
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.520125687122345
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5178452134132385
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5213971734046936
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.47377777099609375
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4547591507434845
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5855293869972229
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5168274641036987
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.42285826802253723
Calibrated prediction for TM: 0.3333333432674408
Raw prediction for TOT: 0.48208773136138916
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5432592034339905
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.11948764324188232
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.21889856457710266
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.37922826409339905
Calibrated prediction for UNH: 0.4393063485622406

Simulating Trading Days:  69%|██████▊   | 74/108 [07:10<00:46,  1.36s/it]

Raw prediction for UPS: 0.4808256924152374
Calibrated prediction for UPS: 0.4779593050479889
Raw prediction for UTX: 0.4667280614376068
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5455431938171387
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.707100510597229
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5321723222732544
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.482705682516098
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5169854760169983
Calibrated prediction for XOM: 0.5078077912330627
Investing 1714.9598844447257 in BP
Investing 931.5801927633266 in HRG
Investing 3604.5484689684968 in KO
Investing 985.5710650536282 in JPM
Investing 979.1834853077273 in NVS
Investing 963.4575482839175 in LMT
Investing 1538.701593497881 in CHTR
Investing 2687.442127670586 in FB
Investing 1548.0180778368035 in SRE
Raw prediction for AAPL: 0.5125595331192017
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47303491830825806
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3954620063304901
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.40705472230911255
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5144818425178528
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4475233256816864
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5479655265808105
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.1739606410264969
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5051240921020508
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.44883742928504944
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4134516417980194
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.493606299161911
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5096297264099121
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5526719093322754
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46685054898262024
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49503782391548157
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5571295619010925
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.41409561038017273
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5145241618156433
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4340476393699646
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.629920244216919
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5788300037384033
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5070531964302063
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4298504889011383
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.528569757938385
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5266396403312683
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.24259039759635925
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.38792356848716736
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5241813659667969
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.510765790939331
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3554088771343231
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6549824476242065
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.41006597876548767
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.518084704875946
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.44472214579582214
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6383178234100342
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.27881908416748047
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.3660973310470581
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5184547305107117
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5144863128662109
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4865490794181824
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.343546599149704
Calibrated prediction for INTC: 0.3900528848171234
Raw prediction for JNJ: 0.5466634631156921
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.533105731010437
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6979019045829773
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5939621329307556
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5180475115776062
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4158070683479309
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4663081765174866
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4944838583469391
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5436137914657593
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45590052008628845
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5646017789840698
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5872100591659546
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5290750861167908
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5383424162864685
Calibrated prediction for NVS: 0.5833333134651184
Raw prediction for ORCL: 0.42357808351516724
Calibrated prediction for ORCL: 0.5
Raw prediction for PCG: 0.4989701211452484
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4625711739063263
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5789607167243958
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.47234392166137695
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5070361495018005
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4723239839076996
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4860028326511383
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.6059836745262146
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.4896208941936493
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4723104238510132
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.18963667750358582
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.52054363489151
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5067710280418396
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5202507972717285
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4740082323551178
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4562227725982666
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5577504634857178
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5173358917236328
Calibrated prediction for T: 0.5147916078567505

Simulating Trading Days:  69%|██████▉   | 75/108 [07:11<00:44,  1.36s/it]

Raw prediction for TM: 0.4317621886730194
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.4813733696937561
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.543332576751709
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09370433539152145
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.23399430513381958
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3700178861618042
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4811173379421234
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.46558383107185364
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5565283298492432
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.690239429473877
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5320044755935669
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47924867272377014
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5162168741226196
Calibrated prediction for XOM: 0.5078077912330627
Investing 1852.888971380457 in BP
Investing 1006.5043974404883 in HRG
Investing 3894.4515061473453 in KO
Investing 1127.0210163202153 in JPM
Investing 1057.9362802250098 in NVS
Investing 1040.9455531879892 in LMT
Investing 1662.4547540136064 in CHTR
Investing 2903.585048694212 in FB
Investing 1672.5205352835965 in SRE
Raw prediction for AAPL: 0.5119200944900513
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47298672795295715
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.40139076113700867
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4014585316181183
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5143042802810669
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.43557581305503845
Calibrated prediction for AMGN: 0.41819900274276733
Raw prediction for AMZN: 0.5473111271858215
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.16824905574321747
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5062134265899658
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4494721293449402
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4068108797073364
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4939729869365692
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5095247030258179
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5233327150344849
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4658704102039337
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49453502893447876
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5593574047088623
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.41493409872055054
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5142009854316711
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.41041767597198486
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.6062830686569214
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.5801008939743042
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5084096789360046
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4359883666038513
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.49499762058258057
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5264215469360352
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.21631987392902374
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.39472079277038574
Calibrated prediction for DHR: 0.3709624111652374
Raw prediction for DIS: 0.5222744941711426
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5104158520698547
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3683021664619446
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.648431122303009
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.41576188802719116
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5081469416618347
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4333341121673584
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6499843001365662
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3028291165828705
Calibrated prediction for HD: 0.2875095009803772
Raw prediction for HON: 0.324400931596756
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5133044123649597
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5143863558769226
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4871159493923187
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.34881600737571716
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5552343130111694
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5408458709716797
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6476792097091675
Calibrated prediction for KO: 0.6000000238418579
Raw prediction for LMT: 0.5960437059402466
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5046087503433228
Calibrated prediction for MA: 0.5
Raw prediction for MCD: 0.4209142029285431
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4679308831691742
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4940599203109741
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5434644818305969
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45651519298553467
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5763763785362244
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5881029963493347
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5298611521720886
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.531276285648346
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.35308459401130676
Calibrated prediction for ORCL: 0.3333333432674408
Raw prediction for PCG: 0.49133265018463135
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46171844005584717
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5748809576034546
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4710410535335541
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5067083835601807
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4723663628101349
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48405247926712036
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.6039268374443054
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.48877575993537903
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.47012394666671753
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.19824005663394928
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5242651104927063
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5149569511413574
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5202341079711914
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.47438040375709534
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4555552899837494
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5641041398048401
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5177628993988037
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4418848752975464
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.48074477910995483
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5439096093177795
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.0750160738825798
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2555825114250183
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3599778711795807
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4814947843551636
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.471866250038147
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5688800811767578
Calibrated prediction for V: 0.5405405163764954

Simulating Trading Days:  70%|███████   | 76/108 [07:12<00:43,  1.36s/it]

Raw prediction for VZ: 0.6665700674057007
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5317773818969727
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4727056622505188
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5152364373207092
Calibrated prediction for XOM: 0.5078077912330627
Investing 1874.6046741679854 in BP
Investing 1018.3005442613493 in HRG
Investing 1280.4810873985023 in KO
Investing 1140.2296077705028 in JPM
Investing 1058.4872379667001 in JNJ
Investing 1053.1453474553102 in LMT
Investing 1681.9385838023802 in CHTR
Investing 2937.614821071117 in FB
Investing 1692.122335181621 in SRE
Raw prediction for AAPL: 0.5112932920455933
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.472931444644928
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.40152740478515625
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.40353530645370483
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5141053795814514
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.42600056529045105
Calibrated prediction for AMGN: 0.41819900274276733
Raw prediction for AMZN: 0.5466281175613403
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.16632574796676636
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5072077512741089
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4502820670604706
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4014858603477478
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4943029582500458
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5096020102500916
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.49171414971351624
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46444711089134216
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49411383271217346
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5608291625976562
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.41599297523498535
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.514208972454071
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.39601072669029236
Calibrated prediction for CELG: 0.38461539149284363
Raw prediction for CHL: 0.566702127456665
Calibrated prediction for CHL: 0.6363636255264282
Raw prediction for CHTR: 0.5812329649925232
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5097805261611938
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.45249083638191223
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4611125886440277
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5260928869247437
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.1956651508808136
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.4095158576965332
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5215542316436768
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5098481178283691
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.3926320970058441
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6420329213142395
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.42057639360427856
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.4984746277332306
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.41861534118652344
Calibrated prediction for GMRE: 0.43024611473083496
Raw prediction for GOOG: 0.6619618535041809
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.33066973090171814
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.31981194019317627
Calibrated prediction for HON: 0.446345716714859
Raw prediction for HRG: 0.5116503238677979
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5144739747047424
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48800256848335266
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.357352614402771
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5618320107460022
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5479227304458618
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6113232970237732
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.5998010039329529
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5153638124465942
Calibrated prediction for MA: 0.5510043501853943
Raw prediction for MCD: 0.4237460494041443
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.47068360447883606
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4935375154018402
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5431585907936096
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45716509222984314
Calibrated prediction for MRK: 0.4504837989807129
Raw prediction for MSFT: 0.5842487215995789
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5878127813339233
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5308439135551453
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.517764151096344
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3009846806526184
Calibrated prediction for ORCL: 0.24308109283447266
Raw prediction for PCG: 0.49163341522216797
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4608933925628662
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5708977580070496
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4693455994129181
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5063978433609009
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4723470211029053
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4824683666229248
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5981343388557434
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.4881933033466339
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.468022882938385
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.20648765563964844
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5288529992103577
Calibrated prediction for SLB: 0.4970414340496063
Raw prediction for SNP: 0.5304763913154602
Calibrated prediction for SNP: 0.5384615659713745
Raw prediction for SNY: 0.5216482877731323
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4747293293476105
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4521481692790985
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5860669016838074
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5182169675827026
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4520832300186157
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.48015096783638
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5443166494369507
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.06458431482315063
Calibrated prediction for UL: 0.17558681964874268

Simulating Trading Days:  71%|███████▏  | 77/108 [07:14<00:42,  1.36s/it]

Raw prediction for UN: 0.27978917956352234
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3490316569805145
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4817931354045868
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.48443150520324707
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5808464884757996
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.6431202292442322
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.531486988067627
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.46907782554626465
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5140011310577393
Calibrated prediction for XOM: 0.5078077912330627
Investing 1862.5352991973111 in BP
Investing 1011.7443613653546 in HRG
Investing 1270.3675110840143 in PEP
Investing 1132.8884019800312 in JPM
Investing 1051.6723187718767 in JNJ
Investing 1046.3648212610603 in LMT
Investing 1671.1096619900702 in CHTR
Investing 2918.701406801171 in FB
Investing 1681.2278467377446 in SRE
Raw prediction for AAPL: 0.5106443762779236
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4729732871055603
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.39679601788520813
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.40454354882240295
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5139170289039612
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.42047223448753357
Calibrated prediction for AMGN: 0.41819900274276733
Raw prediction for AMZN: 0.5457338690757751
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.17084446549415588
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5079325437545776
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4507943391799927
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.3967202603816986
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.49447837471961975
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5097349882125854
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.4659925103187561
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46359947323799133
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49385935068130493
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5636289715766907
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4174051582813263
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5144411325454712
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.3797358572483063
Calibrated prediction for CELG: 0.3529411852359772
Raw prediction for CHL: 0.5268880724906921
Calibrated prediction for CHL: 0.4000000059604645
Raw prediction for CHTR: 0.582461953163147
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5106703042984009
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4687516391277313
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4230327010154724
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5257061123847961
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2112140953540802
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.4311836063861847
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5218560099601746
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5090578198432922
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.43043577671051025
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6357403993606567
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4265764057636261
Calibrated prediction for GD: 0.4257935881614685
Raw prediction for GE: 0.4912690818309784
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.40108126401901245
Calibrated prediction for GMRE: 0.41103795170783997
Raw prediction for GOOG: 0.6734300851821899
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.3505847454071045
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.3364446461200714
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.51271653175354
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5147901773452759
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4890817701816559
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.3685426712036133
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5693320035934448
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.554172158241272
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5656877160072327
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6026079654693604
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5401993989944458
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4261503219604492
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.47323697805404663
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49291181564331055
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5425544381141663
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45774027705192566
Calibrated prediction for MRK: 0.467231810092926
Raw prediction for MSFT: 0.5875702500343323
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5872501134872437
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5318063497543335
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.49750494956970215
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.26590919494628906
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.49374666810035706
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4600628912448883
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5671226978302002
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4665929079055786
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5061297416687012
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47230589389801025
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4809035360813141
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5875239372253418
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.4876880347728729
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4657807946205139
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.21557579934597015
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5335845351219177
Calibrated prediction for SLB: 0.49720025062561035
Raw prediction for SNP: 0.5439558625221252
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5250564217567444
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.475163996219635
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44869470596313477
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6072035431861877
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5186364650726318
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4616346061229706
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.4796334207057953
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.543735921382904
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.0591411218047142
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2997225224971771
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.33611932396888733
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48206740617752075
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.4956681728363037
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.5916160345077515
Calibrated prediction for V: 0.5555555820465088
Raw prediction for VZ: 0.620495617389679
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5310918688774109
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4675113260746002
Calibrated prediction for WMT: 0.47951629757881165

Simulating Trading Days:  72%|███████▏  | 78/108 [07:15<00:40,  1.36s/it]

Raw prediction for XOM: 0.5134504437446594
Calibrated prediction for XOM: 0.5078077912330627
Investing 1928.540839834152 in BP
Investing 1047.599109238845 in HRG
Investing 1315.3874870343843 in PEP
Investing 1173.0363183637503 in JPM
Investing 1088.942055352576 in JNJ
Investing 1083.446467853462 in LMT
Investing 1730.331356607423 in CHTR
Investing 3022.135937355542 in FB
Investing 1740.8081150985436 in SRE
Raw prediction for AAPL: 0.5100626349449158
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4728299677371979
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3910299837589264
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4128126800060272
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5137677192687988
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.42014309763908386
Calibrated prediction for AMGN: 0.41819900274276733
Raw prediction for AMZN: 0.5448215007781982
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.18013973534107208
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5082857608795166
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45097774267196655
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.39420086145401
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4941926598548889
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5101586580276489
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.46110716462135315
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46285274624824524
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49381399154663086
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5669041872024536
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4209556579589844
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5149782299995422
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.3605554401874542
Calibrated prediction for CELG: 0.3529411852359772
Raw prediction for CHL: 0.4864542484283447
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5835158228874207
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5113840699195862
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.47909578680992126
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.3938790261745453
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.525276780128479
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2687864303588867
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.4664473533630371
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5276865363121033
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5080704689025879
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.47434675693511963
Calibrated prediction for EXC: 0.4000000059604645
Raw prediction for FB: 0.6291128993034363
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4321817457675934
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.48679471015930176
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.37453389167785645
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6840847134590149
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.36556193232536316
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.3903375267982483
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5151650905609131
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5151297450065613
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4900035560131073
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.3803280293941498
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5760994553565979
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.558062732219696
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5246501564979553
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.60511714220047
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5701767802238464
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4290160834789276
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4750298857688904
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4922873079776764
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5414745211601257
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4585883915424347
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5877302289009094
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5869119167327881
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5321672558784485
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.48242947459220886
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.24541586637496948
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.498483270406723
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45916521549224854
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5646791458129883
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46317413449287415
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5058902502059937
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4723655879497528
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.47996634244918823
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5730968713760376
Calibrated prediction for PPL: 0.6032158136367798
Raw prediction for PTR: 0.48727813363075256
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.46204498410224915
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.22222276031970978
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5380102396011353
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5463418960571289
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5265931487083435
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.47566643357276917
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44487714767456055
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.619114875793457
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5190024375915527
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4726197421550751
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47913607954978943
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5425611138343811
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.05486106500029564
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.32176634669303894
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3218640387058258
Calibrated prediction for UNH: 0.4393063485622406

Simulating Trading Days:  73%|███████▎  | 79/108 [07:16<00:39,  1.36s/it]

Raw prediction for UPS: 0.4822598993778229
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5078449845314026
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.6027941703796387
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5972883701324463
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5304678082466125
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.46674513816833496
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5136892199516296
Calibrated prediction for XOM: 0.5078077912330627
Investing 1899.2760207050305 in BP
Investing 1031.7022208668361 in HRG
Investing 1295.4270194634298 in PEP
Investing 1663.8397324428595 in V
Investing 1528.0037087886028 in JNJ
Investing 1067.0056104638181 in LMT
Investing 1704.0742853861993 in CHTR
Investing 2976.2762595288937 in FB
Investing 1714.3920633486375 in SRE
Raw prediction for AAPL: 0.5095697641372681
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4722336232662201
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3864971399307251
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4407433271408081
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5136643648147583
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.42387625575065613
Calibrated prediction for AMGN: 0.41819900274276733
Raw prediction for AMZN: 0.5442148447036743
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.19240008294582367
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5082023739814758
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45082786679267883
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.3941628932952881
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4940473735332489
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5108091235160828
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.4826502501964569
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4622892439365387
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49404793977737427
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5706486105918884
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4257781505584717
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5156946778297424
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.33861640095710754
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.46879634261131287
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5848013162612915
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5115786194801331
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4874761700630188
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.38032066822052
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5247944593429565
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.34260982275009155
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.5026767253875732
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5378482341766357
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5069970488548279
Calibrated prediction for DUK: 0.5125879049301147
Raw prediction for EXC: 0.5136457681655884
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.6222213506698608
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4377203583717346
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.49174609780311584
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3486717641353607
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6929120421409607
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.3751351237297058
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.4579724371433258
Calibrated prediction for HON: 0.5
Raw prediction for HRG: 0.5169334411621094
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5150390863418579
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4908008873462677
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.39577919244766235
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5823354721069336
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5608327388763428
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4786127805709839
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6069573760032654
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6019842028617859
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4289078414440155
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.47621169686317444
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49184054136276245
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5401562452316284
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45973384380340576
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5862376093864441
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5862666964530945
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5326796174049377
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4712083339691162
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.24054813385009766
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5030106902122498
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45833107829093933
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5602957010269165
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4602971374988556
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5059607028961182
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47247520089149475
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4794377386569977
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5562571287155151
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48720529675483704
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.45914486050605774
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.23034213483333588
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5418804883956909
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5440161228179932
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5269713401794434
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4758799374103546
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4421021640300751
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.624900221824646
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5191259384155273
Calibrated prediction for T: 0.5147916078567505

Simulating Trading Days:  74%|███████▍  | 80/108 [07:18<00:38,  1.36s/it]

Raw prediction for TM: 0.48431193828582764
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4791812300682068
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.541481077671051
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.05227063596248627
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3433690071105957
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.31045252084732056
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48233863711357117
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5128354430198669
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.6139608025550842
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5718656182289124
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.529880702495575
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4670233428478241
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5143224000930786
Calibrated prediction for XOM: 0.5078077912330627
Investing 1978.6095464480647 in BP
Investing 1540.4610937671382 in CODI
Investing 1304.6533575065657 in PEP
Investing 1733.3389894266022 in V
Investing 1591.8290402544494 in JNJ
Investing 1111.5748653498304 in LMT
Investing 1775.2541558810342 in CHTR
Investing 3100.5965198173735 in FB
Investing 1786.0029115921884 in SRE
Raw prediction for AAPL: 0.5091190934181213
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47209250926971436
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.381973534822464
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.461250901222229
Calibrated prediction for AEP: 0.38065075874328613
Raw prediction for AGFS: 0.5135626792907715
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4307205379009247
Calibrated prediction for AMGN: 0.41819900274276733
Raw prediction for AMZN: 0.5434660911560059
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.2029757797718048
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5077921748161316
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4506630599498749
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.39520248770713806
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4941904544830322
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5116462707519531
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5066432952880859
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46145766973495483
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4944361746311188
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5739518404006958
Calibrated prediction for BUD: 0.5714285969734192
Raw prediction for C: 0.4297807812690735
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5166061520576477
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.3242270350456238
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.4472162127494812
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5858556628227234
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5118013620376587
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.48985132575035095
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.3745884895324707
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5244792699813843
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4427849054336548
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5324156880378723
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.547494113445282
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5060209631919861
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5426532626152039
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.614852249622345
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4451311230659485
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5007628202438354
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3266007602214813
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.7003811597824097
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4067856967449188
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.515412449836731
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5198848843574524
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5153490900993347
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.49134042859077454
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4098970592021942
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5855196118354797
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5621777772903442
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.46240028738975525
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6081069707870483
Calibrated prediction for LMT: 0.5734795928001404
Raw prediction for MA: 0.635403573513031
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4251699447631836
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.47707369923591614
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4918819069862366
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5393802523612976
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46084821224212646
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5824239253997803
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5871263146400452
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5335106253623962
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.46072059869766235
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2442915439605713
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5100889801979065
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4575757384300232
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5590299367904663
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4603208899497986
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5063214302062988
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47255685925483704
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.47938069701194763
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5426927208900452
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4874259829521179
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4587666988372803
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.23988541960716248
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.544022262096405
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5449188947677612
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.52628093957901
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4757426679134369
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44038116931915283
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6409986019134521
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5192049741744995
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.499925434589386
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.479563444852829
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5396214723587036
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.057088952511548996
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.36703363060951233
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.30053645372390747
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4823569655418396
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.514509379863739
Calibrated prediction for UTX: 0.4863581657409668

Simulating Trading Days:  75%|███████▌  | 81/108 [07:19<00:36,  1.36s/it]

Raw prediction for V: 0.6278897523880005
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.548701822757721
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5294349193572998
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4683266580104828
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.515278697013855
Calibrated prediction for XOM: 0.5078077912330627
Investing 2023.9283464207472 in BP
Investing 1575.744380608373 in CODI
Investing 1334.5356173231467 in PEP
Investing 3132.8469758133247 in MA
Investing 1628.2888774140856 in JNJ
Investing 1494.1241448510773 in HON
Investing 1815.9152292774863 in CHTR
Investing 3171.6137216346024 in FB
Investing 2575.3769468131413 in SRE
Raw prediction for AAPL: 0.508696436882019
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47207289934158325
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.37846311926841736
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4937344789505005
Calibrated prediction for AEP: 0.4117647111415863
Raw prediction for AGFS: 0.5134157538414001
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.43786880373954773
Calibrated prediction for AMGN: 0.41819900274276733
Raw prediction for AMZN: 0.5425810813903809
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.20772798359394073
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5072112679481506
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45041894912719727
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.397594690322876
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.49431705474853516
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5126930475234985
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5233925580978394
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4611462354660034
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4947158694267273
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5763506889343262
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.42759206891059875
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5172252655029297
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.32447201013565063
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.41288039088249207
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5862435102462769
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5120125412940979
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.48378312587738037
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.371086984872818
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5242713689804077
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5107142925262451
Calibrated prediction for D: 0.550000011920929
Raw prediction for DHR: 0.5516994595527649
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5546721816062927
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.505305290222168
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5606560707092285
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.6084194183349609
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.45693737268447876
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5101061463356018
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.30842065811157227
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.7065141201019287
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.43220651149749756
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5320708155632019
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.521490752696991
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5155988335609436
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4916343688964844
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4241705536842346
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5834240317344666
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5612311363220215
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.444903165102005
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6088250279426575
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.6668121814727783
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.40701568126678467
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4778481423854828
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49235183000564575
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5395734906196594
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4615310728549957
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5761074423789978
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5880691409111023
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5340681672096252
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.45292434096336365
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.25134018063545227
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.517047643661499
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4568796455860138
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5588380694389343
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4625891447067261
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5068484544754028
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4726078510284424
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.47993701696395874
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5359265804290771
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48772355914115906
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4591004550457001
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.24734456837177277
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5447732210159302
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5511353611946106
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5250898003578186
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4756593108177185
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43955856561660767
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.663975179195404
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5192709565162659
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5107275247573853
Calibrated prediction for TM: 0.5428571701049805

Simulating Trading Days:  76%|███████▌  | 82/108 [07:20<00:35,  1.37s/it]

Raw prediction for TOT: 0.47995486855506897
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5376823544502258
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.06271256506443024
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.38303104043006897
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.2909920811653137
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4823268949985504
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5248786211013794
Calibrated prediction for UTX: 0.4863581657409668
Raw prediction for V: 0.6402255892753601
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5307600498199463
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5290241837501526
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4698443114757538
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5173560380935669
Calibrated prediction for XOM: 0.5078077912330627
Investing 1878.9236983203357 in BP
Investing 1462.8499395524948 in CODI
Investing 1499.9913314427001 in BUD
Investing 2908.393687195857 in MA
Investing 1511.629878051388 in JNJ
Investing 1387.0773977537276 in HON
Investing 1685.8137119647681 in CHTR
Investing 2508.323184000914 in GOOG
Investing 2390.8636815293326 in SRE
Raw prediction for AAPL: 0.5082713961601257
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47194769978523254
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.37003234028816223
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5115184783935547
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5132684111595154
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.44932541251182556
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5413718223571777
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.22964750230312347
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5068453550338745
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45024001598358154
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4005838930606842
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.49412256479263306
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5130501985549927
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5341020226478577
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4608018398284912
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49505290389060974
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5778164863586426
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4243079125881195
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5166265368461609
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.3295436501502991
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.3774288296699524
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5867718458175659
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5123475193977356
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.47674041986465454
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.37954726815223694
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5239934325218201
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5589427947998047
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.558391273021698
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5598189234733582
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5049418807029724
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5661497712135315
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.6027684807777405
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4789290428161621
Calibrated prediction for GD: 0.5586886405944824
Raw prediction for GE: 0.5214071869850159
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.2943043112754822
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.709279477596283
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4436219036579132
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5194473266601562
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.522817075252533
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5157417058944702
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4917559027671814
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.438126802444458
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5750868916511536
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5597021579742432
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.39792120456695557
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6096124649047852
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.6916472911834717
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4024635851383209
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4792695939540863
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4932502210140228
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5408225059509277
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46151554584503174
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5688716173171997
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5883133411407471
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5341219305992126
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4488512873649597
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.25916892290115356
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5213145017623901
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45617303252220154
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5580640435218811
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4663965404033661
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5074623823165894
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4726923406124115
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4809747636318207
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.534489631652832
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48743194341659546
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4592334032058716
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.25104498863220215
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5443333387374878
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5552213191986084
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5243270993232727
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.47541481256484985
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4385833740234375
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6778028607368469
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5192359685897827
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5072450041770935
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47997742891311646
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5356486439704895
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.06611796468496323
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3887966573238373
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.29334744811058044
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4823121428489685
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5380825996398926
Calibrated prediction for UTX: 0.5789473652839661

Simulating Trading Days:  77%|███████▋  | 83/108 [07:22<00:34,  1.38s/it]

Raw prediction for V: 0.6488840579986572
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5167253017425537
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5288106799125671
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4708140194416046
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5195816159248352
Calibrated prediction for XOM: 0.5078077912330627
Investing 1743.4083997553967 in BP
Investing 947.0336582451307 in HRG
Investing 1391.8061117304826 in BUD
Investing 2698.629001585119 in MA
Investing 1402.6052410068178 in JNJ
Investing 1287.035970921275 in HON
Investing 1564.2262580910424 in CHTR
Investing 2327.4131420012786 in GOOG
Investing 2218.425276542395 in SRE
Raw prediction for AAPL: 0.5079741477966309
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4717956483364105
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.35847920179367065
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4998719394207001
Calibrated prediction for AEP: 0.4790867865085602
Raw prediction for AGFS: 0.5130522847175598
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4668017327785492
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5405160784721375
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.28157830238342285
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5066766142845154
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4501873850822449
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.3979566693305969
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4931686818599701
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5128414034843445
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5391387343406677
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4600668251514435
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49513939023017883
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5800332427024841
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4220561683177948
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5155459642410278
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.3505273759365082
Calibrated prediction for CELG: 0.29411548376083374
Raw prediction for CHL: 0.3530541658401489
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5904225707054138
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5128213167190552
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.47159886360168457
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4003913104534149
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5234279036521912
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5541084408760071
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.5584083199501038
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5640087723731995
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5047971606254578
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5635166764259338
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.598233699798584
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.49668779969215393
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.5293962359428406
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.2860574424266815
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.7080774903297424
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.45415568351745605
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5359205007553101
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5260012149810791
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5158124566078186
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4916253983974457
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4491334855556488
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5640519857406616
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5580670237541199
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.3405374586582184
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.6120827794075012
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.7142894864082336
Calibrated prediction for MA: 0.782608687877655
Raw prediction for MCD: 0.3997441530227661
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4817684292793274
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49418869614601135
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5414144396781921
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4613093435764313
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5618339776992798
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5884945392608643
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5339094996452332
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4487442672252655
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.27226608991622925
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5265688896179199
Calibrated prediction for PCG: 0.5135135054588318
Raw prediction for PCLN: 0.45554035902023315
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.556601881980896
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4698251485824585
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5081270933151245
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4728935658931732
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48217639327049255
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5356271862983704
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4864935278892517
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4576742649078369
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.2471347600221634
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5430567264556885
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5544519424438477
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5234181880950928
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.47502967715263367
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4375939667224884
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6893165111541748
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.518690824508667
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.48816466331481934
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4796484410762787
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5340836048126221
Calibrated prediction for TSM: 0.5760757327079773

Simulating Trading Days:  78%|███████▊  | 84/108 [07:23<00:32,  1.37s/it]

Raw prediction for UL: 0.06565459072589874
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.386749804019928
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.30853354930877686
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4828625023365021
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5523027777671814
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.6571225523948669
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5018320083618164
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5288997888565063
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47179439663887024
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5213817358016968
Calibrated prediction for XOM: 0.5078077912330627
Investing 1532.757589484867 in BP
Investing 832.6064204901733 in HRG
Investing 1223.6383518317487 in BUD
Investing 2944.7497989185595 in MA
Investing 865.4647935764982 in JNJ
Investing 1131.5272730396298 in HON
Investing 1375.2254888165871 in CHTR
Investing 2046.1987895491309 in GOOG
Investing 1950.3796011321785 in SRE
Raw prediction for AAPL: 0.5080907344818115
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47169187664985657
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.34677553176879883
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.49747979640960693
Calibrated prediction for AEP: 0.4117647111415863
Raw prediction for AGFS: 0.5127650499343872
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48173004388809204
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5416461825370789
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.3659292757511139
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5065876841545105
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.450385183095932
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.39170050621032715
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4927055835723877
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5124487280845642
Calibrated prediction for BHP: 0.5133191347122192
Raw prediction for BP: 0.5386874675750732
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4597186744213104
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49510666728019714
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5805019736289978
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4224008023738861
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5147777199745178
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.38951176404953003
Calibrated prediction for CELG: 0.3529411852359772
Raw prediction for CHL: 0.34471938014030457
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5940566658973694
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5132749080657959
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.46834295988082886
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.43373748660087585
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5221647620201111
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.5286421775817871
Calibrated prediction for D: 0.574999988079071
Raw prediction for DHR: 0.5521529316902161
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5682404637336731
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5046883225440979
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5606357455253601
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5924867987632751
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.503206193447113
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.5337091088294983
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.282866507768631
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.702196478843689
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.45365750789642334
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.5705373287200928
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5313610434532166
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5158928632736206
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4911263585090637
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.45639610290527344
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5529653429985046
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5580670237541199
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.3030441999435425
Calibrated prediction for KO: 0.26544901728630066
Raw prediction for LMT: 0.6133643984794617
Calibrated prediction for LMT: 0.6169540286064148
Raw prediction for MA: 0.7427366375923157
Calibrated prediction for MA: 0.8235294222831726
Raw prediction for MCD: 0.4002273976802826
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.48477497696876526
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4950832724571228
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5458803772926331
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4614241123199463
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5502215027809143
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5882288217544556
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5338292121887207
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4488376975059509
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2865264415740967
Calibrated prediction for ORCL: 0.22725413739681244
Raw prediction for PCG: 0.5268259048461914
Calibrated prediction for PCG: 0.5135135054588318
Raw prediction for PCLN: 0.455138623714447
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5573990345001221
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.47075948119163513
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5088842511177063
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4730788767337799
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4851181209087372
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5362300276756287
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4852997362613678
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4547525644302368
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.24291817843914032
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5423824787139893
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5499081611633301
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5247950553894043
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.4746113717556
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43705078959465027
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.699386715888977
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5178278684616089
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.46424591541290283
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.47922295331954956
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5331254601478577
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.06808321923017502
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.38368871808052063
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.327828586101532
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4828075170516968
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5642285943031311
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.6623522639274597
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.4908890724182129
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5287654995918274
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  79%|███████▊  | 85/108 [07:25<00:31,  1.36s/it]

Raw prediction for WMT: 0.47229260206222534
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5234179496765137
Calibrated prediction for XOM: 0.5078077912330627
Investing 1595.8544990642747 in BP
Investing 866.8811762567123 in HRG
Investing 1274.0101777310883 in BUD
Investing 3506.5217604912386 in MA
Investing 901.092184495378 in JNJ
Investing 1375.607584506245 in LMT
Investing 1431.837492511392 in CHTR
Investing 2130.4318221508915 in GOOG
Investing 2030.6681778662974 in SRE
Raw prediction for AAPL: 0.508474588394165
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47161146998405457
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.33788731694221497
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5042514204978943
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5125422477722168
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.48839864134788513
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5434824824333191
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.47172921895980835
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5062270760536194
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45072823762893677
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.38242629170417786
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.49233463406562805
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5120143294334412
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5390366911888123
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4599144756793976
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4950254261493683
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5813676714897156
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.42141467332839966
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.51405268907547
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.44199177622795105
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.34483760595321655
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6031359434127808
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5134499073028564
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4672313332557678
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.47267740964889526
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5202645063400269
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4928446412086487
Calibrated prediction for D: 0.550000011920929
Raw prediction for DHR: 0.5377792716026306
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5712782144546509
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5045450329780579
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5590015649795532
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5906160473823547
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.49704083800315857
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.5346856117248535
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.2817913889884949
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6926558017730713
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.44786331057548523
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.6593621969223022
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5383802056312561
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5158153176307678
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4903828203678131
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.45822274684906006
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5464269518852234
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5582820773124695
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.2951938509941101
Calibrated prediction for KO: 0.261412113904953
Raw prediction for LMT: 0.6117249727249146
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.7723977565765381
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.4018237590789795
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.48743414878845215
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.495363712310791
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5505883693695068
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4626491367816925
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5317389965057373
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5881324410438538
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5337190628051758
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4488978087902069
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2941553592681885
Calibrated prediction for ORCL: 0.23560526967048645
Raw prediction for PCG: 0.5262560248374939
Calibrated prediction for PCG: 0.5135135054588318
Raw prediction for PCLN: 0.45498141646385193
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5592426061630249
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4693480432033539
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5097042322158813
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4732518196105957
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4878670275211334
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5349838137626648
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48454758524894714
Calibrated prediction for PTR: 0.45583903789520264
Raw prediction for RDS-B: 0.4509240984916687
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.23721420764923096
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5425354242324829
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5480071902275085
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5264459252357483
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.47404545545578003
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43642669916152954
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.7118589878082275
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5167909264564514
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.44859299063682556
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.4791155457496643
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5313554406166077
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.07016684114933014
Calibrated prediction for UL: 0.17558681964874268

Simulating Trading Days:  80%|███████▉  | 86/108 [07:26<00:30,  1.37s/it]

Raw prediction for UN: 0.37670278549194336
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3460071384906769
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48250699043273926
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5721396207809448
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.659287691116333
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.49560919404029846
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5287845730781555
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4720451235771179
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5236436724662781
Calibrated prediction for XOM: 0.5078077912330627
Investing 1871.2799572220927 in BP
Investing 1016.494530907083 in HRG
Investing 1493.8891435798262 in BUD
Investing 4223.283213318776 in MA
Investing 1056.6099512482933 in JNJ
Investing 2207.773663054334 in HON
Investing 1678.9555710164975 in CHTR
Investing 2498.118952170551 in GOOG
Investing 2381.1372924273487 in SRE
Raw prediction for AAPL: 0.5086789727210999
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.47146251797676086
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3334387540817261
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5171957015991211
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5123981237411499
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4879923462867737
Calibrated prediction for AMGN: 0.540229856967926
Raw prediction for AMZN: 0.5455739498138428
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5814535021781921
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.5055102109909058
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.451060950756073
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.3769294321537018
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.49191898107528687
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5116470456123352
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5363872051239014
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4608229398727417
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4948010742664337
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5834322571754456
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.41866040229797363
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5135263204574585
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4706452190876007
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.35093575716018677
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6103193759918213
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.513292670249939
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.46717140078544617
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5054876804351807
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5180737972259521
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.45590874552726746
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5163771510124207
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5740550756454468
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5043572187423706
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5594248175621033
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5906917452812195
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4808672070503235
Calibrated prediction for GD: 0.5757575631141663
Raw prediction for GE: 0.534940779209137
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.2823600172996521
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6801800727844238
Calibrated prediction for GOOG: 0.6767431497573853
Raw prediction for HD: 0.4296443462371826
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7311562299728394
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5450084805488586
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5156753659248352
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4893132448196411
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.4611625671386719
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5468393564224243
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5566223859786987
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.29839545488357544
Calibrated prediction for KO: 0.261412113904953
Raw prediction for LMT: 0.6070165634155273
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7839237451553345
Calibrated prediction for MA: 0.8323679566383362
Raw prediction for MCD: 0.40470919013023376
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4894140660762787
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49506253004074097
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5560007095336914
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46378791332244873
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5095152854919434
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5876343250274658
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5335696935653687
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4480290710926056
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2840553820133209
Calibrated prediction for ORCL: 0.22454915940761566
Raw prediction for PCG: 0.5248044729232788
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4550163149833679
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5640975832939148
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46726351976394653
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5105783343315125
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47322240471839905
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49012836813926697
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5306445360183716
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48407548666000366
Calibrated prediction for PTR: 0.45583903789520264
Raw prediction for RDS-B: 0.44708865880966187
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.22936077415943146
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5433338284492493
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5472412109375
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.528626024723053
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4730444550514221
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4352261424064636
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.703465461730957
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.5158214569091797
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.44457167387008667
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.47899994254112244
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.528928816318512
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.0780147910118103
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.366687536239624
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.35631176829338074
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4821576178073883
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5730790495872498
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.649567186832428
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5155525803565979
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5289410948753357
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  81%|████████  | 87/108 [07:27<00:28,  1.37s/it]

Raw prediction for WMT: 0.47146230936050415
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5231853127479553
Calibrated prediction for XOM: 0.5078077912330627
Investing 1991.2424942079138 in BP
Investing 1081.6591591548238 in HRG
Investing 1589.658208463869 in BUD
Investing 4494.026116711729 in MA
Investing 1124.3462671677858 in JNJ
Investing 2349.307872667548 in HON
Investing 1786.5887282083331 in CHTR
Investing 2658.266388174523 in GOOG
Investing 2533.785360616555 in SRE
Raw prediction for AAPL: 0.5084848403930664
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4712532162666321
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3329537808895111
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5288645029067993
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5123822689056396
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4820132553577423
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5465126633644104
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.6756688356399536
Calibrated prediction for BA: 0.71875
Raw prediction for BABA: 0.5043973326683044
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4513024687767029
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.3756725788116455
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4914615750312805
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5115123987197876
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5394865274429321
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4620644450187683
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4943336546421051
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5864655375480652
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4159630239009857
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5131797790527344
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48103877902030945
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.3626854419708252
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6155931353569031
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5130758285522461
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.46711108088493347
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.533053457736969
Calibrated prediction for CSCO: 0.543972373008728
Raw prediction for CVX: 0.5160324573516846
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3934289216995239
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.4973900318145752
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5733863711357117
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5040487051010132
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5610207915306091
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5932593941688538
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.46295231580734253
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5342321991920471
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.2892550826072693
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6662611961364746
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.40388184785842896
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.775272786617279
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5490439534187317
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.515555739402771
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4881533086299896
Calibrated prediction for IEP: 0.49252477288246155
Raw prediction for INTC: 0.46575111150741577
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5509012341499329
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5520790219306946
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.3108929693698883
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.6011351346969604
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.7672141790390015
Calibrated prediction for MA: 0.8298418521881104
Raw prediction for MCD: 0.4065406918525696
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.49078884720802307
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49431660771369934
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5605103373527527
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4644300639629364
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4867032468318939
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5872053503990173
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5332785248756409
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.44642767310142517
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2637059986591339
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5215451717376709
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45527413487434387
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5708956122398376
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4666431248188019
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5112465620040894
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4731307923793793
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4923776090145111
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5241187810897827
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48422771692276
Calibrated prediction for PTR: 0.45583903789520264
Raw prediction for RDS-B: 0.4443170428276062
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.21907228231430054
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5447914004325867
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5480637550354004
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5292373895645142
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4719478189945221
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.434283584356308
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6770215034484863
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.515075147151947
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4491158723831177
Calibrated prediction for TM: 0.380952388048172
Raw prediction for TOT: 0.4788534343242645
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5260457396507263
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.0931619331240654
Calibrated prediction for UL: 0.17558681964874268

Simulating Trading Days:  81%|████████▏ | 88/108 [07:29<00:27,  1.37s/it]

Raw prediction for UN: 0.35538795590400696
Calibrated prediction for UN: 0.3947368562221527
Raw prediction for UNH: 0.3605015277862549
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48187172412872314
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5681748390197754
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.6363275647163391
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.536510705947876
Calibrated prediction for VZ: 0.5428571701049805
Raw prediction for WFC: 0.5292268991470337
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.47062259912490845
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5225872993469238
Calibrated prediction for XOM: 0.5078077912330627
Investing 1931.3746565203496 in BP
Investing 1049.1384615693157 in HRG
Investing 1541.8642306435654 in BUD
Investing 4325.997030891136 in MA
Investing 1090.5421574105785 in JNJ
Investing 2923.0891166879155 in BA
Investing 1732.873922349213 in CHTR
Investing 1144.3241163748685 in TSM
Investing 2457.6056631935858 in SRE
Raw prediction for AAPL: 0.5083738565444946
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4712667167186737
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.33488455414772034
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5351477265357971
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5124028325080872
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4738520681858063
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5469950437545776
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.7409164309501648
Calibrated prediction for BA: 0.761133074760437
Raw prediction for BABA: 0.503143846988678
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4512186050415039
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.3817971646785736
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.49096059799194336
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5116400122642517
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5488430857658386
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46338674426078796
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4937216341495514
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5872625112533569
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.41471660137176514
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5129209756851196
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4772241413593292
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.3853321373462677
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6189207434654236
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5131112933158875
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.46683642268180847
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5488996505737305
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.514490008354187
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.30582481622695923
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.47589150071144104
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5705481171607971
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5036934018135071
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5606638789176941
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5961802005767822
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.44646140933036804
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5313560366630554
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.301306813955307
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6520646214485168
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3885234296321869
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.7578943371772766
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5505266189575195
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5154431462287903
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4870615303516388
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4714682400226593
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5553127527236938
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5468824505805969
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.328779399394989
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.5962649583816528
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.730708658695221
Calibrated prediction for MA: 0.8222439289093018
Raw prediction for MCD: 0.40826427936553955
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4918021261692047
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49325230717658997
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5643202662467957
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4644850790500641
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4675215482711792
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5866896510124207
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5329340100288391
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.445805162191391
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.2354040890932083
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.518858015537262
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45565178990364075
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5756863355636597
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4646645784378052
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5117204785346985
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47309091687202454
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49428457021713257
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5170169472694397
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4851565957069397
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4426919221878052
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.21034063398838043
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5474029183387756
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.547468364238739
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5280696749687195
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.47093263268470764
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4332517385482788
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.6353520750999451
Calibrated prediction for SRE: 0.6904761791229248
Raw prediction for T: 0.514459490776062
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4656260907649994
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.47882258892059326
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5240830779075623
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.10919015854597092
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3345947265625
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.35904577374458313
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48171940445899963
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5554413199424744
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.6223254203796387
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.5577840209007263
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5295477509498596
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  82%|████████▏ | 89/108 [07:30<00:26,  1.37s/it]

Raw prediction for WMT: 0.4696910083293915
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5217076539993286
Calibrated prediction for XOM: 0.5078077912330627
Investing 1630.3044269716324 in BP
Investing 885.5946579956802 in HRG
Investing 1301.5124085433652 in BUD
Investing 3568.079242308228 in MA
Investing 920.5441839176003 in JNJ
Investing 2927.902287418957 in BA
Investing 1462.746763012551 in CHTR
Investing 1822.979272704819 in CSCO
Investing 2074.5044877380797 in SRE
Raw prediction for AAPL: 0.5082443952560425
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.471284419298172
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.34013476967811584
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5406169891357422
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5124316215515137
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.46686995029449463
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5473986268043518
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.7732656002044678
Calibrated prediction for BA: 0.761133074760437
Raw prediction for BABA: 0.5019670724868774
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.450776606798172
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.3956572413444519
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4905345141887665
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.511911153793335
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5608984231948853
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4645049273967743
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4930848479270935
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5859780311584473
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.41379836201667786
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.512661874294281
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.46188050508499146
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4126475751399994
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6204390525817871
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5134541988372803
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4663219749927521
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5497665405273438
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5134907364845276
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.2664683163166046
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.45360779762268066
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5623416304588318
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5032456517219543
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5544402599334717
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.598374605178833
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4338572919368744
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5259889960289001
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.315259724855423
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6381946802139282
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3744315803050995
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6954939365386963
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5517880320549011
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5153188109397888
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4861375093460083
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4806669354438782
Calibrated prediction for INTC: 0.4000000059604645
Raw prediction for JNJ: 0.5592441558837891
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5403695106506348
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.34490346908569336
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.5930257439613342
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6838363409042358
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.40862464904785156
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4928654730319977
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49207913875579834
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5672382712364197
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46401289105415344
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.45737236738204956
Calibrated prediction for MSFT: 0.4401414692401886
Raw prediction for NEE: 0.5871012806892395
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5326892137527466
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4482495188713074
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.21033304929733276
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5139858722686768
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45608827471733093
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5782255530357361
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46060580015182495
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5121340751647949
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4731633961200714
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49588289856910706
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5135003328323364
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48657920956611633
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4417126774787903
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.20483724772930145
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5494365096092224
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5476162433624268
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5256599187850952
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.4704819321632385
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43172401189804077
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5889681577682495
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5140133500099182
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.4959476888179779
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47877973318099976
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5230633616447449
Calibrated prediction for TSM: 0.5760757327079773

Simulating Trading Days:  83%|████████▎ | 90/108 [07:31<00:24,  1.38s/it]

Raw prediction for UL: 0.1172742173075676
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.3065655529499054
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.35086557269096375
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4815869927406311
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5367703437805176
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.6067550182342529
Calibrated prediction for V: 0.6206896305084229
Raw prediction for VZ: 0.579339325428009
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5294241309165955
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4684606194496155
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5201845765113831
Calibrated prediction for XOM: 0.5078077912330627
Investing 1542.0726246505942 in BP
Investing 837.6664235456354 in HRG
Investing 1231.0747751485474 in BUD
Investing 2386.9805307903994 in MA
Investing 870.7244869827945 in JNJ
Investing 2769.444706389914 in BA
Investing 1383.5831533794726 in CHTR
Investing 1724.3199400282722 in CSCO
Investing 1391.9604312314789 in SRE
Raw prediction for AAPL: 0.5079812407493591
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.4712095558643341
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.34764447808265686
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5406126379966736
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5124934315681458
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4601111114025116
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5473935008049011
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.7740767002105713
Calibrated prediction for BA: 0.761133074760437
Raw prediction for BABA: 0.5013826489448547
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45064935088157654
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.40996265411376953
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.4901876151561737
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5121382474899292
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.5610327124595642
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46369633078575134
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4925006031990051
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5834335088729858
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4134841561317444
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5123394727706909
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4377168118953705
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4392246603965759
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6206321120262146
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5140340924263
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4679501950740814
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5351073145866394
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5129820108413696
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.27562499046325684
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.43485069274902344
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5497572422027588
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5027523040771484
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5398702025413513
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5984647870063782
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.42557138204574585
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5205878019332886
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.32486745715141296
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6255040764808655
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.36416953802108765
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.628947377204895
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5530523061752319
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5153425931930542
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48551511764526367
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.49317702651023865
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5633895397186279
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5345884561538696
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.35241684317588806
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.5915578007698059
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6389731764793396
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.4098373055458069
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.49457505345344543
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4911424517631531
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5689608454704285
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4632972776889801
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.45461082458496094
Calibrated prediction for MSFT: 0.4401414692401886
Raw prediction for NEE: 0.5876269340515137
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5324212312698364
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.45603832602500916
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.1902831792831421
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5099771022796631
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45641425251960754
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5754860639572144
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4572087228298187
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5123137831687927
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4732436537742615
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4966180622577667
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5130529999732971
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48831334710121155
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.44120872020721436
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.20173674821853638
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5502381920814514
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5507561564445496
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.524742841720581
Calibrated prediction for SNY: 0.49595797061920166
Raw prediction for SO: 0.46997982263565063
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43105974793434143
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5556906461715698
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5137597322463989
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.524090588092804
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47881701588630676
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5226922631263733
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.10976285487413406
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2817782461643219
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3409118056297302
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4814469814300537
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5354223847389221
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.5889742970466614
Calibrated prediction for V: 0.5555555820465088

Simulating Trading Days:  84%|████████▍ | 91/108 [07:33<00:23,  1.38s/it]

Raw prediction for VZ: 0.6001903414726257
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5296661257743835
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.46714910864830017
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5195174813270569
Calibrated prediction for XOM: 0.5078077912330627
Investing 1625.6885402163955 in BP
Investing 883.0872706729676 in HRG
Investing 1297.8274318059032 in BUD
Investing 2516.409948918488 in MA
Investing 917.9378438771402 in JNJ
Investing 2919.6125072002833 in BA
Investing 1458.6052828705892 in CHTR
Investing 1817.8178649697127 in CSCO
Investing 1467.4368024660434 in SRE
Raw prediction for AAPL: 0.5075741410255432
Calibrated prediction for AAPL: 0.5298623442649841
Raw prediction for ABB: 0.471203088760376
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.35704854130744934
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5374387502670288
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5125662088394165
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.45529618859291077
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5470162034034729
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.7480021715164185
Calibrated prediction for BA: 0.761133074760437
Raw prediction for BABA: 0.5012103319168091
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4504620134830475
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.42202746868133545
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.48992010951042175
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5123374462127686
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.558008074760437
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4605187177658081
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4919435679912567
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.579425036907196
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4133320450782776
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5120552182197571
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4297831952571869
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4774865508079529
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.6210706233978271
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5144333839416504
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.47241783142089844
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5173691511154175
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5126864910125732
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.31407350301742554
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.42685842514038086
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.5347907543182373
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5023175477981567
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.5157690048217773
Calibrated prediction for EXC: 0.5333333611488342
Raw prediction for FB: 0.5972074866294861
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.424203485250473
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5154397487640381
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.33216267824172974
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6146286725997925
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3715040683746338
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.5786316394805908
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5541070103645325
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5156148076057434
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48539140820503235
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5074901580810547
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5658128261566162
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5295654535293579
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.35970988869667053
Calibrated prediction for KO: 0.3799999952316284
Raw prediction for LMT: 0.5912384986877441
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6045970320701599
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.40976423025131226
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.4981224834918976
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.4906812310218811
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5698961019515991
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4622800648212433
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.45530587434768677
Calibrated prediction for MSFT: 0.4401414692401886
Raw prediction for NEE: 0.5881897211074829
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5320601463317871
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.47147655487060547
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.17270389199256897
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5058639049530029
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4564526379108429
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5717934370040894
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4560757279396057
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5122772455215454
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47337424755096436
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4965270459651947
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5157622694969177
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4892585575580597
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.44141146540641785
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.20136387646198273
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5492366552352905
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.5548438429832458
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5257275700569153
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.46935898065567017
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4319866895675659
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5313400626182556
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5136920809745789
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5353739857673645
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47899582982063293
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5235794186592102
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.10382837057113647
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.26761069893836975
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3335970640182495
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48150429129600525
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5388445258140564
Calibrated prediction for UTX: 0.5789473652839661
Raw prediction for V: 0.5713098645210266
Calibrated prediction for V: 0.5405405163764954

Simulating Trading Days:  85%|████████▌ | 92/108 [07:34<00:22,  1.41s/it]

Raw prediction for VZ: 0.6206842064857483
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5299742817878723
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4658392667770386
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.518714427947998
Calibrated prediction for XOM: 0.5078077912330627
Investing 1851.8506373966018 in BP
Investing 1005.9403659540342 in HRG
Investing 1478.378236276822 in BUD
Investing 1514.4395148104525 in MA
Investing 1045.6392717439421 in JNJ
Investing 3325.7823676915696 in BA
Investing 1661.5231367961817 in CHTR
Investing 1195.0573794100558 in INTC
Investing 1485.894379266044 in AEP
Raw prediction for AAPL: 0.5070348381996155
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47133100032806396
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.36682477593421936
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5362448692321777
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5126612782478333
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4518934190273285
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5468453764915466
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.7075464129447937
Calibrated prediction for BA: 0.71875
Raw prediction for BABA: 0.5013065934181213
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45058926939964294
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4335571229457855
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4898310899734497
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5124540328979492
Calibrated prediction for BHP: 0.5137037634849548
Raw prediction for BP: 0.5558153986930847
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4580303132534027
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49133455753326416
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5767881870269775
Calibrated prediction for BUD: 0.6060606241226196
Raw prediction for C: 0.4142654538154602
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5118772983551025
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4356742203235626
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5059066414833069
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.6235650181770325
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5140016674995422
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4746076166629791
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5099220275878906
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5123895406723022
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.3597027659416199
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.4248739778995514
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.517793595790863
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5019697546958923
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4863230586051941
Calibrated prediction for EXC: 0.4615384638309479
Raw prediction for FB: 0.5954301357269287
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.42490607500076294
Calibrated prediction for GD: 0.41515254974365234
Raw prediction for GE: 0.5095471143722534
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3374931514263153
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6057279706001282
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.3998951315879822
Calibrated prediction for HD: 0.4707334339618683
Raw prediction for HON: 0.5707868933677673
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.5544717311859131
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5160183310508728
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4858054220676422
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5201436281204224
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5655379891395569
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5269909501075745
Calibrated prediction for JPM: 0.5714285969734192
Raw prediction for KO: 0.38756486773490906
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5914303660392761
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5854302644729614
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.40996289253234863
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5033859610557556
Calibrated prediction for MDT: 0.4636484980583191
Raw prediction for MMM: 0.49044468998908997
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5701161623001099
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4611881375312805
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.45674359798431396
Calibrated prediction for MSFT: 0.4401414692401886
Raw prediction for NEE: 0.5895084738731384
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5315466523170471
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4921129047870636
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.1577201634645462
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5031355619430542
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.45693907141685486
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5684025287628174
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.45742931962013245
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5119866728782654
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47343695163726807
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4956643283367157
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5221985578536987
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49069514870643616
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.44279322028160095
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.20214855670928955
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.556411862373352
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.55812007188797
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.527091383934021
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4688791334629059
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43583858013153076
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5252735614776611
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5138534903526306
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5414413809776306
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47916632890701294
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5263400077819824
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09401905536651611
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.26184797286987305
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.33059969544410706
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48147279024124146
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.549389123916626
Calibrated prediction for UTX: 0.5880411267280579
Raw prediction for V: 0.5547163486480713
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.6380261182785034
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5303220748901367
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  86%|████████▌ | 93/108 [07:36<00:21,  1.42s/it]

Raw prediction for WMT: 0.4648253321647644
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5182093381881714
Calibrated prediction for XOM: 0.5078077912330627
Investing 2025.087353872781 in BP
Investing 1100.0439628908327 in HRG
Investing 1616.677398309938 in BUD
Investing 1163.7983595337905 in JPM
Investing 1143.4566174830788 in JNJ
Investing 3064.921031485786 in BA
Investing 1816.9551175159788 in CHTR
Investing 1306.8524735871288 in INTC
Investing 1624.89666060356 in AEP
Raw prediction for AAPL: 0.5066567063331604
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4714084565639496
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3724585175514221
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5358173847198486
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5127791166305542
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4528038501739502
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5475022792816162
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.6490908861160278
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.5012646317481995
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.451176255941391
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.44801458716392517
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4895913898944855
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5127708911895752
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5510215759277344
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4564206600189209
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4905450642108917
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5732309818267822
Calibrated prediction for BUD: 0.5714285969734192
Raw prediction for C: 0.4169043302536011
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5120223760604858
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.46514958143234253
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5558953881263733
Calibrated prediction for CHL: 0.5
Raw prediction for CHTR: 0.6249018907546997
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5130612850189209
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4734969437122345
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5259796380996704
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5122630000114441
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.39205583930015564
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.42758244276046753
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.504246711730957
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5017495155334473
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.44985687732696533
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.5973275899887085
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.43114814162254333
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5066160559654236
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.34254026412963867
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.5992135405540466
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.42989975214004517
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.6226162314414978
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5545069575309753
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.516635000705719
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4865083694458008
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5295640230178833
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5654252767562866
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5292413234710693
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4078616797924042
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5935360193252563
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5741841793060303
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4065258204936981
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5096794366836548
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49034756422042847
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5700591206550598
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46016988158226013
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.4607725739479065
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5895832777023315
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5309726595878601
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.51131272315979
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.1471102386713028
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5010571479797363
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4585181474685669
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5678156614303589
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4580145478248596
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5116901993751526
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4734819531440735
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49455568194389343
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5281574726104736
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4925388693809509
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4460499584674835
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.20523367822170258
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5673343539237976
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5611636638641357
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5293118953704834
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4685954451560974
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44001999497413635
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5413802266120911
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5140992403030396
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5476021766662598
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.47950640320777893
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5303555727005005
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09576942026615143
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2629127502441406
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.34358468651771545
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48148417472839355
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5619575381278992
Calibrated prediction for UTX: 0.5909090638160706

Simulating Trading Days:  87%|████████▋ | 94/108 [07:37<00:20,  1.46s/it]

Raw prediction for V: 0.5414491891860962
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.6511655449867249
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5307544469833374
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4629795551300049
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5180121660232544
Calibrated prediction for XOM: 0.5078077912330627
Investing 1907.857722289174 in BP
Investing 1036.3638711412868 in HRG
Investing 1301.2802856469016 in PEP
Investing 1160.4557976114222 in JPM
Investing 1077.263424511414 in JNJ
Investing 2250.9288446490605 in HON
Investing 1711.773986132681 in CHTR
Investing 2678.2538590575346 in INTC
Investing 1530.8335395635204 in AEP
Raw prediction for AAPL: 0.5066202282905579
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47151046991348267
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.37222570180892944
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5375626683235168
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5129314661026001
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.45605653524398804
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5485525727272034
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.5636353492736816
Calibrated prediction for BA: 0.6261682510375977
Raw prediction for BABA: 0.5009467005729675
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4522431790828705
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4664859473705292
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.48931893706321716
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5131881833076477
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5375562906265259
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4552803635597229
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.48980510234832764
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5689489245414734
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4206032156944275
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5123924016952515
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4910033643245697
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5941346287727356
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.625346839427948
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5121599435806274
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4825502932071686
Calibrated prediction for CODI: 0.5555555820465088
Raw prediction for CSCO: 0.5398537516593933
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5124372243881226
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.44715985655784607
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.43206408619880676
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4929177165031433
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.501720666885376
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.4096018075942993
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6006209254264832
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.4377846121788025
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5059807300567627
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3453655242919922
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.593722403049469
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.4583330750465393
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.6905830502510071
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5541344285011292
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5173860192298889
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4870910942554474
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5381100177764893
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5680395364761353
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5353296399116516
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.43819189071655273
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5964745283126831
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5729449987411499
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4072597622871399
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5153138637542725
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49030256271362305
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5700403451919556
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4594789445400238
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.46297478675842285
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5900221467018127
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5307245850563049
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5265852212905884
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.13854679465293884
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5012024641036987
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4612641930580139
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5685055255889893
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.45874834060668945
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5117151737213135
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47361090779304504
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49328017234802246
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5360243320465088
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49437183141708374
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4505102038383484
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.20579111576080322
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.587693452835083
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5614985823631287
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.531231164932251
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4684520363807678
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44485190510749817
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5653907060623169
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5142940282821655
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5616917014122009
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4807946979999542
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5335561633110046
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.1034143716096878
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.26271089911460876
Calibrated prediction for UN: 0.3088753819465637

Simulating Trading Days:  88%|████████▊ | 95/108 [07:39<00:19,  1.47s/it]

Raw prediction for UNH: 0.36790794134140015
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48144835233688354
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5733804702758789
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5280895233154297
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.6646884679794312
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5312247276306152
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.45942339301109314
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5180503129959106
Calibrated prediction for XOM: 0.5078077912330627
Investing 1853.644684598402 in BP
Investing 1006.9149070224514 in HRG
Investing 1264.303546580957 in PEP
Investing 1127.480679415031 in JPM
Investing 1046.6522725614388 in JNJ
Investing 2186.9672143510807 in HON
Investing 1663.1327973563261 in CHTR
Investing 2602.1495061436676 in INTC
Investing 1673.2026840228466 in SRE
Raw prediction for AAPL: 0.5065900683403015
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4715809226036072
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.36741629242897034
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5350523591041565
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5130659341812134
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4560261368751526
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5486913323402405
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.4522097408771515
Calibrated prediction for BA: 0.578125
Raw prediction for BABA: 0.5003687739372253
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4528530240058899
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.48195964097976685
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4890776574611664
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.513472318649292
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.509300947189331
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.45640724897384644
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4894103407859802
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5635655522346497
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42278221249580383
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5128712058067322
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.497433066368103
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5930386781692505
Calibrated prediction for CHL: 0.6737086772918701
Raw prediction for CHTR: 0.6256305575370789
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5113205909729004
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4873417615890503
Calibrated prediction for CODI: 0.6060606241226196
Raw prediction for CSCO: 0.531379759311676
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5131102204322815
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.48221442103385925
Calibrated prediction for D: 0.550000011920929
Raw prediction for DHR: 0.43790701031684875
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4835950434207916
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5019131302833557
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.37028807401657104
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6034701466560364
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.44151511788368225
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5061412453651428
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.345113605260849
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.5912922024726868
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.4770382046699524
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7479939460754395
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5537833571434021
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5180919170379639
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4871334731578827
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5573481917381287
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5732014775276184
Calibrated prediction for JNJ: 0.5877389311790466
Raw prediction for JPM: 0.5420655608177185
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4605637788772583
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.5988790392875671
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5785179138183594
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.408193975687027
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5198553800582886
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49022066593170166
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5697738528251648
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45917755365371704
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.46515268087387085
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5898658633232117
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.530356228351593
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5324056148529053
Calibrated prediction for NVS: 0.5254815816879272
Raw prediction for ORCL: 0.12988470494747162
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.49864447116851807
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46431103348731995
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5653231143951416
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4598183035850525
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5118122696876526
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47358813881874084
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4920026659965515
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5426328778266907
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49594175815582275
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.45710939168930054
Calibrated prediction for RDS-B: 0.4423460364341736
Raw prediction for REX: 0.20376378297805786
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6062144637107849
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5585351586341858
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5322023630142212
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4682246446609497
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44871097803115845
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5838345289230347
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5145959258079529
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5711491703987122
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.48224180936813354
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5351935625076294
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.11341781169176102
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2590358555316925
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.39817601442337036
Calibrated prediction for UNH: 0.4393063485622406

Simulating Trading Days:  89%|████████▉ | 96/108 [07:40<00:17,  1.48s/it]

Raw prediction for UPS: 0.48148539662361145
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5787243843078613
Calibrated prediction for UTX: 0.6263754963874817
Raw prediction for V: 0.512737512588501
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.6855787038803101
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5314381718635559
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4554634690284729
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5206255316734314
Calibrated prediction for XOM: 0.5078077912330627
Investing 1830.9659767723535 in BP
Investing 1425.512100804569 in CODI
Investing 2100.071105383408 in TM
Investing 1113.6863394746838 in JPM
Investing 1230.567611275955 in JNJ
Investing 2160.2104195394795 in HON
Investing 1642.7849372186458 in CHTR
Investing 2570.313098195661 in INTC
Investing 1652.7316222708284 in SRE
Raw prediction for AAPL: 0.5064084529876709
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47168874740600586
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.36144256591796875
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5302704572677612
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5132156014442444
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.45477136969566345
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5483295321464539
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.33734139800071716
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.4999532699584961
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4529265761375427
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49523890018463135
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.48878487944602966
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5139651298522949
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4647386968135834
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4584523141384125
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4893878996372223
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5568169951438904
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42433443665504456
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5133207440376282
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4951019883155823
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5699390769004822
Calibrated prediction for CHL: 0.6363636255264282
Raw prediction for CHTR: 0.6251240968704224
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5106004476547241
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4819836914539337
Calibrated prediction for CODI: 0.5555555820465088
Raw prediction for CSCO: 0.4936610162258148
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5143727660179138
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.4720104932785034
Calibrated prediction for D: 0.550000011920929
Raw prediction for DHR: 0.4438857436180115
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4771033227443695
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5021906495094299
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.33561256527900696
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6053369641304016
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.44261884689331055
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5083010792732239
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3416344225406647
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.5935297012329102
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.49370622634887695
Calibrated prediction for HD: 0.5693792104721069
Raw prediction for HON: 0.7775280475616455
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5543215870857239
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5187405943870544
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48656442761421204
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5820919275283813
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5787520408630371
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5464313626289368
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.46490004658699036
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6008988618850708
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5740463733673096
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.40986794233322144
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5242324471473694
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49010834097862244
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5687757730484009
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4591121971607208
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.47316405177116394
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5892624258995056
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5300133228302002
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5300584435462952
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.12492407858371735
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4964589774608612
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4671599566936493
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.5580830574035645
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4608546793460846
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5117766857147217
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4735490083694458
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.49027520418167114
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5458589792251587
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4971153736114502
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.4647633135318756
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.1991041749715805
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6181510090827942
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5517107844352722
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5319792032241821
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4679151177406311
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45193082094192505
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5918795466423035
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.514928936958313
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5758063197135925
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.4832143485546112
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.53575199842453
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.11448536068201065
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2513272166252136
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.41668421030044556
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4816010594367981
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.581628680229187
Calibrated prediction for UTX: 0.6263754963874817
Raw prediction for V: 0.49952611327171326
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.7062151432037354
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5315587520599365
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  90%|████████▉ | 97/108 [07:42<00:16,  1.46s/it]

Raw prediction for WMT: 0.4529537856578827
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5245160460472107
Calibrated prediction for XOM: 0.5078077912330627
Investing 1775.7701778159596 in BP
Investing 964.6128399608504 in HRG
Investing 2036.7629369098406 in TM
Investing 1080.113456049243 in JPM
Investing 1428.6409074188953 in JNJ
Investing 2095.0893077695073 in HON
Investing 1593.2619923504103 in CHTR
Investing 2492.829143374674 in INTC
Investing 1602.908827358743 in SRE
Raw prediction for AAPL: 0.506209135055542
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47147300839424133
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.35825812816619873
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.520349383354187
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5133867263793945
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.44997990131378174
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5481533408164978
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.25127407908439636
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.49992531538009644
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4525626003742218
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5009300708770752
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4884849190711975
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5142199993133545
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4506208300590515
Calibrated prediction for BP: 0.3333333432674408
Raw prediction for BRK-A: 0.4602683484554291
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4895407557487488
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5497420430183411
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42548540234565735
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5136554837226868
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.48841592669487
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5405102968215942
Calibrated prediction for CHL: 0.5
Raw prediction for CHTR: 0.623737096786499
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5102316737174988
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4754154086112976
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.44072166085243225
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5162990093231201
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.39510682225227356
Calibrated prediction for D: 0.4523809552192688
Raw prediction for DHR: 0.4536653459072113
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.47610530257225037
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5025158524513245
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.3119608163833618
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6072476506233215
Calibrated prediction for FB: 0.5533333420753479
Raw prediction for GD: 0.441020667552948
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5116262435913086
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3323691189289093
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6001109480857849
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.5059061050415039
Calibrated prediction for HD: 0.5888888835906982
Raw prediction for HON: 0.784752607345581
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5545822381973267
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5191899538040161
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48556628823280334
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.6067614555358887
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.582631528377533
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5487960577011108
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4536094665527344
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6023920178413391
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5541788935661316
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.40902066230773926
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5278688073158264
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4899426996707916
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5666203498840332
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.459125280380249
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.48576533794403076
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5881931185722351
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5298509001731873
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5207939743995667
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.12336665391921997
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.49199366569519043
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.46959203481674194
Calibrated prediction for PCLN: 0.4615384638309479
Raw prediction for PEP: 0.549532949924469
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4614071547985077
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5112810730934143
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4735817313194275
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48794931173324585
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.544264554977417
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49832242727279663
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.47077807784080505
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.19520874321460724
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6252985596656799
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5485734343528748
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5309821367263794
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4676141142845154
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45400112867355347
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.584538996219635
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5153376460075378
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5823296308517456
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.48430678248405457
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5362364649772644
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.1079268753528595
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.24507272243499756
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.4226963222026825
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4818577766418457
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5789239406585693
Calibrated prediction for UTX: 0.6263754963874817
Raw prediction for V: 0.4931045472621918
Calibrated prediction for V: 0.4683045744895935

Simulating Trading Days:  91%|█████████ | 98/108 [07:43<00:15,  1.52s/it]

Raw prediction for VZ: 0.7260124683380127
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5317545533180237
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.45072993636131287
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5286520719528198
Calibrated prediction for XOM: 0.5078077912330627
Investing 1501.089768431286 in SNP
Investing 994.5508184816761 in HRG
Investing 2099.9764486226804 in TM
Investing 1113.6361421546544 in JPM
Investing 1472.9805834302738 in JNJ
Investing 2160.1130521121195 in HON
Investing 1642.7108917730745 in CHTR
Investing 2570.1972461603145 in INTC
Investing 1652.6571284971103 in SRE
Raw prediction for AAPL: 0.5061054229736328
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47146451473236084
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3550531566143036
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5046610832214355
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5135918259620667
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4499780535697937
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.548771321773529
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.20086781680583954
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5007068514823914
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.452202707529068
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5048980712890625
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4882260262966156
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.514326810836792
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.4905311167240143
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4606826901435852
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4895986020565033
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5451555848121643
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.428151935338974
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5141465067863464
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.49576878547668457
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.5080223679542542
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.6214288473129272
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5104082226753235
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.474079966545105
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4174366295337677
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5187416672706604
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.31283125281333923
Calibrated prediction for D: 0.4375
Raw prediction for DHR: 0.46421894431114197
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4760951101779938
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5029370784759521
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.3013579249382019
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6123948097229004
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.44720205664634705
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5176227688789368
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3184754252433777
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6097302436828613
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.5192668437957764
Calibrated prediction for HD: 0.5888888835906982
Raw prediction for HON: 0.791181743144989
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5540617108345032
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5196040272712708
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4843834638595581
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.6328306198120117
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5834146738052368
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5513153672218323
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.4824383854866028
Calibrated prediction for KO: 0.5
Raw prediction for LMT: 0.6063774228096008
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5277521014213562
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.41061240434646606
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5313289165496826
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.48995712399482727
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5639947056770325
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45877352356910706
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5066217184066772
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5888117551803589
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5296772122383118
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5142730474472046
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.1268765777349472
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4906570315361023
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47170600295066833
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5461496114730835
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.46264904737472534
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5106614828109741
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4737195074558258
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4855002760887146
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5426191687583923
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5001346468925476
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.47740089893341064
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.19605357944965363
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6301099061965942
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5521266460418701
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5304250121116638
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46764829754829407
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4545179009437561
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5884539484977722
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5157232284545898
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5909915566444397
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.48521333932876587
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5371756553649902
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.10705051571130753
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2442118525505066
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.42020541429519653
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48214900493621826
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5746614336967468
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.49869823455810547
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.7452986836433411
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5323041081428528
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.448274165391922
Calibrated prediction for WMT: 0.47951629757881165

Simulating Trading Days:  92%|█████████▏| 99/108 [07:45<00:13,  1.53s/it]

Raw prediction for XOM: 0.5345319509506226
Calibrated prediction for XOM: 0.5078077912330627
Investing 1785.8300973089179 in BP
Investing 970.0774702565425 in HRG
Investing 2048.3014070494587 in TM
Investing 1086.2324091361115 in JPM
Investing 1436.7343041278414 in JNJ
Investing 2106.9582027594215 in HON
Investing 1602.287984325311 in CHTR
Investing 2798.4998832342853 in FB
Investing 1611.9894696396116 in SRE
Raw prediction for AAPL: 0.5061196684837341
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4717714488506317
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3508862555027008
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.4994749128818512
Calibrated prediction for AEP: 0.46336501836776733
Raw prediction for AGFS: 0.5138338208198547
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4539453983306885
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5498685836791992
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.1705830693244934
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5017805695533752
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4521579444408417
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5073245167732239
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4880933165550232
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.514365553855896
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5384963154792786
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.46053892374038696
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4895819127559662
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5443846583366394
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43152758479118347
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.514853835105896
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5082636475563049
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.4803284704685211
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.6182801127433777
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5110673308372498
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.47544053196907043
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.44175049662590027
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5205691456794739
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.21291257441043854
Calibrated prediction for D: 0.4000000059604645
Raw prediction for DHR: 0.48190826177597046
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.47603538632392883
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5035358667373657
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.29766008257865906
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6191636919975281
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.45636650919914246
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5254576206207275
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3075898289680481
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.619480550289154
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.5243366360664368
Calibrated prediction for HD: 0.5888888835906982
Raw prediction for HON: 0.7947109341621399
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5532904267311096
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5199833512306213
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4830060601234436
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.6484711766242981
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5784363150596619
Calibrated prediction for JNJ: 0.6078431606292725
Raw prediction for JPM: 0.5535968542098999
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.5534671545028687
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6111079454421997
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.5146930813789368
Calibrated prediction for MA: 0.5267131924629211
Raw prediction for MCD: 0.4145944118499756
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5344834923744202
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.490384578704834
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5614076852798462
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4582805335521698
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.522769570350647
Calibrated prediction for MSFT: 0.5199999809265137
Raw prediction for NEE: 0.5896144509315491
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5294836759567261
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5143486857414246
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.13405875861644745
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.49342697858810425
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.473698228597641
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.549228847026825
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4646328091621399
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5102455615997314
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47377774119377136
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.4843290448188782
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5417845845222473
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.501304030418396
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.48771747946739197
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.19826975464820862
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6319001913070679
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5584835410118103
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5304626226425171
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46754685044288635
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.45272302627563477
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5942171812057495
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5161198377609253
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5992795825004578
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.485347718000412
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5379292964935303
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.11120696365833282
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.24570700526237488
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.4081723392009735
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48222142457962036
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5711326003074646
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5081321001052856
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.7614476680755615
Calibrated prediction for VZ: 0.5716716051101685

Simulating Trading Days:  93%|█████████▎| 100/108 [07:46<00:12,  1.54s/it]

Raw prediction for WFC: 0.5327454209327698
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4481068253517151
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5406907796859741
Calibrated prediction for XOM: 0.5078077912330627
Investing 1846.1113317611896 in BP
Investing 1002.8227283354166 in HRG
Investing 2117.4424398573 in TM
Investing 1122.8985122684653 in JPM
Investing 1485.2317046158623 in JNJ
Investing 2178.079213427273 in HON
Investing 1656.3736993038644 in CHTR
Investing 2892.964092248408 in FB
Investing 1666.4026611858674 in SRE
Raw prediction for AAPL: 0.5062288641929626
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4721027612686157
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.347701758146286
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5069341659545898
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5140986442565918
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4606116712093353
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5511021614074707
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.14969396591186523
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5029921531677246
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45208337903022766
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5079147219657898
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.48801007866859436
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5143325924873352
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.5820608735084534
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.460300475358963
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4898448586463928
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.544269323348999
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4356561601161957
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5157185196876526
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5210695862770081
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.46088913083076477
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.6146432757377625
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5118547677993774
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4677802622318268
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4931960701942444
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5224510431289673
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.14542652666568756
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5098270773887634
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.476518452167511
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5041308999061584
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.29632803797721863
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6261477470397949
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.46852561831474304
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5342499017715454
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.304029256105423
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6265774965286255
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.5222142338752747
Calibrated prediction for HD: 0.5888888835906982
Raw prediction for HON: 0.7903611660003662
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.553999125957489
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5203194618225098
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4819066524505615
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.6536433696746826
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.566960334777832
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5558989644050598
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6209739446640015
Calibrated prediction for KO: 0.5185185074806213
Raw prediction for LMT: 0.6141173243522644
Calibrated prediction for LMT: 0.6169540286064148
Raw prediction for MA: 0.5288792848587036
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.41967859864234924
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.536271870136261
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49115556478500366
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5587382912635803
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4577595591545105
Calibrated prediction for MRK: 0.4680563509464264
Raw prediction for MSFT: 0.5278273820877075
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.589870035648346
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5287073254585266
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.519565761089325
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.14474281668663025
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4985802173614502
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47555026412010193
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.553640604019165
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4684605002403259
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5098062753677368
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4737836718559265
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48354873061180115
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5424307584762573
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.5013604164123535
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.49697571992874146
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.2043038010597229
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6339474320411682
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5581878423690796
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5310198664665222
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4678262174129486
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.44838130474090576
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5911405086517334
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5164841413497925
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.603981077671051
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.48531413078308105
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5379163026809692
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.11490266770124435
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2454194575548172
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.38903069496154785
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4820246696472168
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5708186626434326
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5174353718757629
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.7735139727592468
Calibrated prediction for VZ: 0.5716716051101685

Simulating Trading Days:  94%|█████████▎| 101/108 [07:48<00:11,  1.60s/it]

Raw prediction for WFC: 0.5331456065177917
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.44898271560668945
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5452103614807129
Calibrated prediction for XOM: 0.5078077912330627
Investing 1885.1262696482884 in BP
Investing 1024.015960717806 in HRG
Investing 2162.191574890087 in TM
Investing 1146.6293756004588 in JPM
Investing 1064.428210318053 in JNJ
Investing 2224.109820445961 in HON
Investing 1691.3788021296584 in CHTR
Investing 2954.102774638165 in FB
Investing 1701.619711860183 in SRE
Raw prediction for AAPL: 0.5063604116439819
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4722222089767456
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3488161265850067
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5163372159004211
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5144000053405762
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.46292343735694885
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5516611933708191
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.13246993720531464
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5043060183525085
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45192959904670715
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.5032512545585632
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.48788222670555115
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5143415927886963
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6192895174026489
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4604782462120056
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49021202325820923
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5438048839569092
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4381749629974365
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5159903168678284
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.5187497138977051
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.45244744420051575
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.610888659954071
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5123413801193237
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4433140456676483
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5325155258178711
Calibrated prediction for CSCO: 0.4424809515476227
Raw prediction for CVX: 0.524257242679596
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.10769582539796829
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5405225157737732
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.47708964347839355
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5046136975288391
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.2991393208503723
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6314520239830017
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.469462513923645
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5401328802108765
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3190535306930542
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6313786506652832
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.5103582143783569
Calibrated prediction for HD: 0.5888888835906982
Raw prediction for HON: 0.7738151550292969
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5561628937721252
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5206065773963928
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48128053545951843
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.6486311554908752
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.555021345615387
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5566439032554626
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6717756390571594
Calibrated prediction for KO: 0.7372183799743652
Raw prediction for LMT: 0.6132156252861023
Calibrated prediction for LMT: 0.6063260436058044
Raw prediction for MA: 0.5546121597290039
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4227274954319
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.537085235118866
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4918798804283142
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5561114549636841
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4580160081386566
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5281221866607666
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5893371105194092
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5275493860244751
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5229227542877197
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.15738166868686676
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.5022528767585754
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4771100580692291
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5594264268875122
Calibrated prediction for PEP: 0.5868263244628906
Raw prediction for PFE: 0.4695919156074524
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5091755390167236
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47375696897506714
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48292532563209534
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5421463251113892
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49931570887565613
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.507919430732727
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.21093851327896118
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6343125104904175
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5490107536315918
Calibrated prediction for SNP: 0.6183196306228638
Raw prediction for SNY: 0.5311404466629028
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46843937039375305
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4422757923603058
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5803452730178833
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5167618989944458
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.6023343801498413
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.48475995659828186
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5374288558959961
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.11029055714607239
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.24173235893249512
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3642693758010864
Calibrated prediction for UNH: 0.4393063485622406

Simulating Trading Days:  94%|█████████▍| 102/108 [07:50<00:09,  1.58s/it]

Raw prediction for UPS: 0.48184195160865784
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5702558755874634
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5268174409866333
Calibrated prediction for V: 0.4683045744895935
Raw prediction for VZ: 0.7810331583023071
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5335279703140259
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4507213234901428
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5480465888977051
Calibrated prediction for XOM: 0.5078077912330627
Investing 1800.6951173158475 in BP
Investing 978.1522703315134 in HRG
Investing 2900.7488429955138 in KO
Investing 1095.2740679805422 in JPM
Investing 1016.7545335891843 in JNJ
Investing 2124.496251807301 in HON
Investing 1615.6252233939945 in CHTR
Investing 2821.7942362728836 in FB
Investing 1625.4074626240852 in SRE
Raw prediction for AAPL: 0.5065011978149414
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4725966155529022
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3545445501804352
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5197795033454895
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5147119164466858
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4625120162963867
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5520554184913635
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.12058193236589432
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5055052042007446
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4518628418445587
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.49161669611930847
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.487709641456604
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5142595171928406
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6421867609024048
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4603494703769684
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4904307425022125
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.544051468372345
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43885868787765503
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.51585853099823
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.510295569896698
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.43991827964782715
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.60663902759552
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5120980739593506
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.42226260900497437
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5521032810211182
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5254400372505188
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.09849406778812408
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5670897364616394
Calibrated prediction for DHR: 0.5
Raw prediction for DIS: 0.4771801829338074
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5049136281013489
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.3071102499961853
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6360211968421936
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.46851062774658203
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5446929931640625
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3460746705532074
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6355149149894714
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.49622052907943726
Calibrated prediction for HD: 0.5888888835906982
Raw prediction for HON: 0.7454821467399597
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5590594410896301
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5208370685577393
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4811301529407501
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.6317178606987
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5485052466392517
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5560612082481384
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.6913142800331116
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.610645592212677
Calibrated prediction for LMT: 0.5833333134651184
Raw prediction for MA: 0.5758023858070374
Calibrated prediction for MA: 0.5675675868988037
Raw prediction for MCD: 0.4256969094276428
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5367966294288635
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49245092272758484
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5535803437232971
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.45930978655815125
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5271183848381042
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5899192690849304
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5265008211135864
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5235985517501831
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.17248116433620453
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4961157441139221
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.47831934690475464
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.566085934638977
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.46789559721946716
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5087907910346985
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47380438446998596
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.482561856508255
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5375927090644836
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.49654656648635864
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5163134336471558
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.21570919454097748
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6331691145896912
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5266873240470886
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5312834978103638
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46906089782714844
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4368445873260498
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5608900785446167
Calibrated prediction for SRE: 0.6363636255264282
Raw prediction for T: 0.5169535875320435
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5908385515213013
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.4838990569114685
Calibrated prediction for TOT: 0.4871641993522644
Raw prediction for TSM: 0.5369974970817566
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.10213815420866013
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2387065589427948
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3429405987262726
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48171892762184143
Calibrated prediction for UPS: 0.4850730001926422

Simulating Trading Days:  95%|█████████▌| 103/108 [07:51<00:07,  1.54s/it]

Raw prediction for UTX: 0.5716222524642944
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5374183654785156
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7839952707290649
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5339286923408508
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.45136526226997375
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5491358041763306
Calibrated prediction for XOM: 0.5078077912330627
Investing 1873.2447490699496 in BP
Investing 1017.5618218594653 in HRG
Investing 3937.2358231280778 in KO
Investing 1139.4024323758726 in JPM
Investing 1057.7193622749892 in JNJ
Investing 2210.09176392339 in HON
Investing 1680.7184276142586 in CHTR
Investing 2935.4837391536407 in FB
Investing 1690.8947912283438 in SRE
Raw prediction for AAPL: 0.5065901279449463
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4730508029460907
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3635815978050232
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5231480598449707
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5149896144866943
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.459007203578949
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5527254343032837
Calibrated prediction for AMZN: 0.5442163348197937
Raw prediction for BA: 0.11067000776529312
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5064330697059631
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45196130871772766
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.47594743967056274
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.4874532222747803
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5140015482902527
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6537578701972961
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.45915523171424866
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.490323007106781
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5448690056800842
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4375177323818207
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5153971910476685
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4953750669956207
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.43219661712646484
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.6024718880653381
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5113809108734131
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4181426167488098
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.5498231053352356
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5261974334716797
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.09801151603460312
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.5852993130683899
Calibrated prediction for DHR: 0.6315789222717285
Raw prediction for DIS: 0.4778040051460266
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5050190687179565
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.32128748297691345
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6410092115402222
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4652242958545685
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5480281710624695
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.37073519825935364
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6411516070365906
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.47184401750564575
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.7088770866394043
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5566194653511047
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.521008312702179
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48133376240730286
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.603691577911377
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5443648099899292
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5544450879096985
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.7044610381126404
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6075814366340637
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.5942471027374268
Calibrated prediction for MA: 0.5915349125862122
Raw prediction for MCD: 0.42902541160583496
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5349124073982239
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49289706349372864
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5515789985656738
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.46115657687187195
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5287578105926514
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5908821821212769
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5263087749481201
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5178354382514954
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.19222582876682281
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.48615363240242004
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4792005121707916
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5747620463371277
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4636983871459961
Calibrated prediction for PFE: 0.5029211044311523
Raw prediction for PG: 0.5089172124862671
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.4738702178001404
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48263347148895264
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5290954113006592
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4931362271308899
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5220073461532593
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.2166898548603058
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6300365924835205
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.5119510293006897
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5311435461044312
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.46957889199256897
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43248406052589417
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5421974658966064
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5170522332191467
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.579584002494812
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.4829012453556061
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5365795493125916
Calibrated prediction for TSM: 0.5760757327079773

Simulating Trading Days:  96%|█████████▋| 104/108 [07:53<00:06,  1.62s/it]

Raw prediction for UL: 0.09581901878118515
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.23771123588085175
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.32436156272888184
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48151689767837524
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5714834332466125
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5464439392089844
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7837205529212952
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5343549847602844
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.45232775807380676
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5495083928108215
Calibrated prediction for XOM: 0.5078077912330627
Investing 1819.2148180547288 in BP
Investing 988.2123227798144 in HRG
Investing 3823.6742716971266 in KO
Investing 1150.0930697925653 in MA
Investing 1027.2116006994904 in JNJ
Investing 2146.346166557442 in HON
Investing 1632.2415263737269 in CHTR
Investing 2850.8156871003685 in FB
Investing 1459.7079366104936 in AEP
Raw prediction for AAPL: 0.506616473197937
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4733167588710785
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3747102916240692
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5266703367233276
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5152369141578674
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.45634743571281433
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5539472103118896
Calibrated prediction for AMZN: 0.5600000023841858
Raw prediction for BA: 0.1040579155087471
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5069991946220398
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.45219704508781433
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4521026015281677
Calibrated prediction for BBL: 0.5949506163597107
Raw prediction for BCH: 0.48711445927619934
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5137701630592346
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6578904986381531
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4582245647907257
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4902971684932709
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.545050323009491
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43593090772628784
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5151191353797913
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.483991414308548
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.424871563911438
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5983296632766724
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5105960965156555
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.41120249032974243
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.536213219165802
Calibrated prediction for CSCO: 0.6526497602462769
Raw prediction for CVX: 0.5264813303947449
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.09784512966871262
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.6010898351669312
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.4815123677253723
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5048953890800476
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.34471386671066284
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6474650502204895
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4684879779815674
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.548702597618103
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.38322120904922485
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6477697491645813
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.43086206912994385
Calibrated prediction for HD: 0.4912280738353729
Raw prediction for HON: 0.6689085364341736
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5496349334716797
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5211387872695923
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48183995485305786
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5698872208595276
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5396366119384766
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5518779158592224
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.7030026912689209
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6049154996871948
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6124367117881775
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4321407079696655
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5310651063919067
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49342188239097595
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5496079325675964
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.462961345911026
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5296196937561035
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5914008021354675
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.526831328868866
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5109142065048218
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.21425500512123108
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.47643184661865234
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4798157811164856
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5822359919548035
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.45928123593330383
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5092614889144897
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47394442558288574
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48302266001701355
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5171873569488525
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4899015724658966
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5245974659919739
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.21570155024528503
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6196894645690918
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.49842581152915955
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5310457944869995
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4698539078235626
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.43012532591819763
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5425347089767456
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5170940160751343
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.570780336856842
Calibrated prediction for TM: 0.6564311981201172
Raw prediction for TOT: 0.4815666675567627
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5362315773963928
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.09025798738002777
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.2386992871761322
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.31179365515708923
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48129531741142273
Calibrated prediction for UPS: 0.4850730001926422

Simulating Trading Days:  97%|█████████▋| 105/108 [07:55<00:04,  1.63s/it]

Raw prediction for UTX: 0.5690629482269287
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5517169237136841
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7795841693878174
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5349386930465698
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4535493850708008
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5491282939910889
Calibrated prediction for XOM: 0.5078077912330627
Investing 2137.270825617847 in BP
Investing 1160.9829394704311 in HRG
Investing 4492.172879452649 in KO
Investing 1747.8555380241637 in MA
Investing 1206.8005186208766 in JNJ
Investing 2652.6321193406875 in DHR
Investing 1917.6087178152932 in CHTR
Investing 3349.227994838164 in FB
Investing 1714.910826296149 in AEP
Raw prediction for AAPL: 0.5065373182296753
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.473576158285141
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.3879035413265228
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5299543142318726
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5154405832290649
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.4524000585079193
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5549525618553162
Calibrated prediction for AMZN: 0.5803965926170349
Raw prediction for BA: 0.09891863167285919
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5069906115531921
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4525342881679535
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.42479535937309265
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.48675426840782166
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5132904052734375
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.6571322679519653
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4567681849002838
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.49026060104370117
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.54535973072052
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43513813614845276
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5147151350975037
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.46872854232788086
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.43485984206199646
Calibrated prediction for CHL: 0.37704917788505554
Raw prediction for CHTR: 0.5942866802215576
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5097060203552246
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.41063740849494934
Calibrated prediction for CODI: 0.43421053886413574
Raw prediction for CSCO: 0.515951931476593
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5263582468032837
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.10178691148757935
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.6147547364234924
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.48709410429000854
Calibrated prediction for DIS: 0.4732688069343567
Raw prediction for DUK: 0.5045597553253174
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.3731982409954071
Calibrated prediction for EXC: 0.32951706647872925
Raw prediction for FB: 0.6532685160636902
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4763270914554596
Calibrated prediction for GD: 0.5327168107032776
Raw prediction for GE: 0.547646164894104
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.3931819200515747
Calibrated prediction for GMRE: 0.38058072328567505
Raw prediction for GOOG: 0.6537894010543823
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.39556440711021423
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.6272933483123779
Calibrated prediction for HON: 0.6666666865348816
Raw prediction for HRG: 0.5411871671676636
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5211748480796814
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.48247867822647095
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.5384746193885803
Calibrated prediction for INTC: 0.7106270790100098
Raw prediction for JNJ: 0.5316206812858582
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5493423342704773
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.7026954293251038
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.6022237539291382
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6278684139251709
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.4330501854419708
Calibrated prediction for MCD: 0.3570921719074249
Raw prediction for MDT: 0.5265411734580994
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49393007159233093
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.547614336013794
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4644298553466797
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5304160714149475
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.59064781665802
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5274028182029724
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.5062817335128784
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.24062566459178925
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.4735497534275055
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.4803211987018585
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5873646140098572
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.4575091600418091
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5094961524009705
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47408992052078247
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.483425498008728
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5078408122062683
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48704659938812256
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.5242199897766113
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.21502844989299774
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.6026125550270081
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.4889172315597534
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5307225584983826
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.47011157870292664
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4308029115200043
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5417732000350952
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5169232487678528
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5654746294021606
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4802115559577942
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5361984968185425
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.08472048491239548
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.24078871309757233
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.3043424189090729
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48103898763656616
Calibrated prediction for UPS: 0.4850730001926422
Raw prediction for UTX: 0.5668917298316956
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5538187026977539
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7721958756446838
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5354666709899902
Calibrated prediction for WFC: 0.5224242210388184

Simulating Trading Days:  98%|█████████▊| 106/108 [07:56<00:03,  1.56s/it]

Raw prediction for WMT: 0.4553322494029999
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5483448505401611
Calibrated prediction for XOM: 0.5078077912330627
Investing 2539.204576366027 in BP
Investing 1379.3166301860663 in HRG
Investing 5336.967967097052 in KO
Investing 2076.5561050011834 in MA
Investing 1433.7506332437706 in JNJ
Investing 3151.484377230598 in DHR
Investing 2278.232956531553 in CHTR
Investing 3979.08161654142 in FB
Investing 2037.4158323767954 in AEP
Raw prediction for AAPL: 0.5063790678977966
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.4737405776977539
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.39757898449897766
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5341724753379822
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5156157612800598
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.45092740654945374
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5552859902381897
Calibrated prediction for AMZN: 0.5803965926170349
Raw prediction for BA: 0.0938306450843811
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5063509941101074
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4528825581073761
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.4018312096595764
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.48657864332199097
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.51267409324646
Calibrated prediction for BHP: 0.5199435949325562
Raw prediction for BP: 0.648883044719696
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4550469219684601
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.48971250653266907
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5442918539047241
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4361143112182617
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5142836570739746
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4474886953830719
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.45896032452583313
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5906078815460205
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.5087258815765381
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.4186479449272156
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4967622756958008
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5259695649147034
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.10444431751966476
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.6241117119789124
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.4943731725215912
Calibrated prediction for DIS: 0.5384615659713745
Raw prediction for DUK: 0.5040619969367981
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.40308818221092224
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6579205393791199
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.47528865933418274
Calibrated prediction for GD: 0.5223515033721924
Raw prediction for GE: 0.5450986623764038
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.399664044380188
Calibrated prediction for GMRE: 0.4048506021499634
Raw prediction for GOOG: 0.6581970453262329
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.3600717782974243
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.5790707468986511
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.535553514957428
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5211254358291626
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4833000600337982
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.509983241558075
Calibrated prediction for INTC: 0.6000000238418579
Raw prediction for JNJ: 0.5253841876983643
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.5479779839515686
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.7027297019958496
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.5981515645980835
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6363884210586548
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.43201330304145813
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5216258764266968
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.4941657483577728
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5454866290092468
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4652850925922394
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5320889949798584
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5900678634643555
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5280824303627014
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.4994160830974579
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.27096837759017944
Calibrated prediction for ORCL: 0.2237062305212021
Raw prediction for PCG: 0.46849024295806885
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.48050621151924133
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5882920622825623
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.45674648880958557
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5094764828681946
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47420594096183777
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.48361796140670776
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.5035770535469055
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.4853760600090027
Calibrated prediction for PTR: 0.5029280185699463
Raw prediction for RDS-B: 0.520832359790802
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.21385468542575836
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5773987770080566
Calibrated prediction for SLB: 0.5887866020202637
Raw prediction for SNP: 0.4900188446044922
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5308231711387634
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.4703788161277771
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4352027177810669
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5433956980705261
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5167295336723328
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5632466673851013
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.4792781472206116
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5362619161605835
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.07619916647672653
Calibrated prediction for UL: 0.17558681964874268

Simulating Trading Days:  99%|█████████▉| 107/108 [07:57<00:01,  1.51s/it]

Raw prediction for UN: 0.2444174736738205
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.29696354269981384
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.48092612624168396
Calibrated prediction for UPS: 0.4779593050479889
Raw prediction for UTX: 0.5668448209762573
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.5550352931022644
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7626001834869385
Calibrated prediction for VZ: 0.5716716051101685
Raw prediction for WFC: 0.5357148051261902
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.45632827281951904
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5471645593643188
Calibrated prediction for XOM: 0.5078077912330627
Investing 2803.206830600743 in BP
Investing 1522.7248073222681 in HRG
Investing 5891.8549530478 in KO
Investing 4339.095332775743 in MA
Investing 1582.818338425885 in JNJ
Investing 3479.145640729532 in DHR
Investing 2515.1018728033278 in CHTR
Investing 4392.788541272255 in FB
Investing 2249.246882764536 in AEP
Raw prediction for AAPL: 0.5061795115470886
Calibrated prediction for AAPL: 0.5054746270179749
Raw prediction for ABB: 0.47379234433174133
Calibrated prediction for ABB: 0.4860254228115082
Raw prediction for ABBV: 0.4126559793949127
Calibrated prediction for ABBV: 0.38162699341773987
Raw prediction for AEP: 0.5417680740356445
Calibrated prediction for AEP: 0.6287878751754761
Raw prediction for AGFS: 0.5157891511917114
Calibrated prediction for AGFS: 0.5159199237823486
Raw prediction for AMGN: 0.45128390192985535
Calibrated prediction for AMGN: 0.5257731676101685
Raw prediction for AMZN: 0.5546340346336365
Calibrated prediction for AMZN: 0.5714285969734192
Raw prediction for BA: 0.0870283991098404
Calibrated prediction for BA: 0.31029826402664185
Raw prediction for BABA: 0.5053754448890686
Calibrated prediction for BABA: 0.5055591464042664
Raw prediction for BAC: 0.4531714618206024
Calibrated prediction for BAC: 0.47199904918670654
Raw prediction for BBL: 0.3888724148273468
Calibrated prediction for BBL: 0.37950950860977173
Raw prediction for BCH: 0.48665621876716614
Calibrated prediction for BCH: 0.4962126910686493
Raw prediction for BHP: 0.5122779011726379
Calibrated prediction for BHP: 0.509179413318634
Raw prediction for BP: 0.6319904923439026
Calibrated prediction for BP: 0.6445783376693726
Raw prediction for BRK-A: 0.4541807770729065
Calibrated prediction for BRK-A: 0.464071124792099
Raw prediction for BSAC: 0.4890133738517761
Calibrated prediction for BSAC: 0.49770623445510864
Raw prediction for BUD: 0.5420100092887878
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4363240897655487
Calibrated prediction for C: 0.4216713011264801
Raw prediction for CAT: 0.5136005282402039
Calibrated prediction for CAT: 0.5170960426330566
Raw prediction for CELG: 0.4171443581581116
Calibrated prediction for CELG: 0.5663716793060303
Raw prediction for CHL: 0.49477702379226685
Calibrated prediction for CHL: 0.38461539149284363
Raw prediction for CHTR: 0.5877597332000732
Calibrated prediction for CHTR: 0.5970132350921631
Raw prediction for CMCSA: 0.507769763469696
Calibrated prediction for CMCSA: 0.5143330097198486
Raw prediction for CODI: 0.43002915382385254
Calibrated prediction for CODI: 0.5066666603088379
Raw prediction for CSCO: 0.4721325635910034
Calibrated prediction for CSCO: 0.44117647409439087
Raw prediction for CVX: 0.5254024267196655
Calibrated prediction for CVX: 0.5297141075134277
Raw prediction for D: 0.14300763607025146
Calibrated prediction for D: 0.1136857122182846
Raw prediction for DHR: 0.6283797025680542
Calibrated prediction for DHR: 0.6721311211585999
Raw prediction for DIS: 0.502761960029602
Calibrated prediction for DIS: 0.5825883746147156
Raw prediction for DUK: 0.5034459829330444
Calibrated prediction for DUK: 0.49670282006263733
Raw prediction for EXC: 0.42456284165382385
Calibrated prediction for EXC: 0.37142857909202576
Raw prediction for FB: 0.6599446535110474
Calibrated prediction for FB: 0.7164179086685181
Raw prediction for GD: 0.4665795862674713
Calibrated prediction for GD: 0.5
Raw prediction for GE: 0.5430312752723694
Calibrated prediction for GE: 0.4852156937122345
Raw prediction for GMRE: 0.4035288691520691
Calibrated prediction for GMRE: 0.42172378301620483
Raw prediction for GOOG: 0.6613064408302307
Calibrated prediction for GOOG: 0.5742574334144592
Raw prediction for HD: 0.32285356521606445
Calibrated prediction for HD: 0.33898305892944336
Raw prediction for HON: 0.5155417919158936
Calibrated prediction for HON: 0.6000000238418579
Raw prediction for HRG: 0.535300076007843
Calibrated prediction for HRG: 0.5798162221908569
Raw prediction for HSBC: 0.5209882855415344
Calibrated prediction for HSBC: 0.5206336975097656
Raw prediction for IEP: 0.4842838644981384
Calibrated prediction for IEP: 0.4739986062049866
Raw prediction for INTC: 0.4832267165184021
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5250375270843506
Calibrated prediction for JNJ: 0.5714285969734192
Raw prediction for JPM: 0.546973466873169
Calibrated prediction for JPM: 0.5765414834022522
Raw prediction for KO: 0.7050554156303406
Calibrated prediction for KO: 0.8098210096359253
Raw prediction for LMT: 0.59505695104599
Calibrated prediction for LMT: 0.5714285969734192
Raw prediction for MA: 0.6374704837799072
Calibrated prediction for MA: 0.7272727489471436
Raw prediction for MCD: 0.43231454491615295
Calibrated prediction for MCD: 0.3529411852359772
Raw prediction for MDT: 0.5185548067092896
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.49403223395347595
Calibrated prediction for MMM: 0.49658453464508057
Raw prediction for MO: 0.5435807108879089
Calibrated prediction for MO: 0.5512070059776306
Raw prediction for MRK: 0.4655940532684326
Calibrated prediction for MRK: 0.4774205684661865
Raw prediction for MSFT: 0.5362343192100525
Calibrated prediction for MSFT: 0.628171980381012
Raw prediction for NEE: 0.5894777774810791
Calibrated prediction for NEE: 0.5761207342147827
Raw prediction for NGG: 0.5288028120994568
Calibrated prediction for NGG: 0.5322580933570862
Raw prediction for NVS: 0.49820688366889954
Calibrated prediction for NVS: 0.4267627000808716
Raw prediction for ORCL: 0.3006492257118225
Calibrated prediction for ORCL: 0.24271388351917267
Raw prediction for PCG: 0.4656784236431122
Calibrated prediction for PCG: 0.48740363121032715
Raw prediction for PCLN: 0.48008236289024353
Calibrated prediction for PCLN: 0.5005483031272888
Raw prediction for PEP: 0.5883592367172241
Calibrated prediction for PEP: 0.5902615785598755
Raw prediction for PFE: 0.45669451355934143
Calibrated prediction for PFE: 0.43841809034347534
Raw prediction for PG: 0.5094180107116699
Calibrated prediction for PG: 0.5043846964836121
Raw prediction for PICO: 0.47431284189224243
Calibrated prediction for PICO: 0.4759405851364136
Raw prediction for PM: 0.483467161655426
Calibrated prediction for PM: 0.5165519118309021
Raw prediction for PPL: 0.507263720035553
Calibrated prediction for PPL: 0.5530726313591003
Raw prediction for PTR: 0.48469558358192444
Calibrated prediction for PTR: 0.48498350381851196
Raw prediction for RDS-B: 0.515164315700531
Calibrated prediction for RDS-B: 0.5058749914169312
Raw prediction for REX: 0.21671843528747559
Calibrated prediction for REX: 0.14517387747764587
Raw prediction for SLB: 0.5524792075157166
Calibrated prediction for SLB: 0.5
Raw prediction for SNP: 0.4952779710292816
Calibrated prediction for SNP: 0.48342448472976685
Raw prediction for SNY: 0.5324831604957581
Calibrated prediction for SNY: 0.5522180795669556
Raw prediction for SO: 0.47052857279777527
Calibrated prediction for SO: 0.4767346680164337
Raw prediction for SPLP: 0.4422038197517395
Calibrated prediction for SPLP: 0.5363636612892151
Raw prediction for SRE: 0.5487903356552124
Calibrated prediction for SRE: 0.550561785697937
Raw prediction for T: 0.5166406631469727
Calibrated prediction for T: 0.5147916078567505
Raw prediction for TM: 0.5628060698509216
Calibrated prediction for TM: 0.5428571701049805
Raw prediction for TOT: 0.478911429643631
Calibrated prediction for TOT: 0.4789581000804901
Raw prediction for TSM: 0.5358166694641113
Calibrated prediction for TSM: 0.5760757327079773
Raw prediction for UL: 0.07561251521110535
Calibrated prediction for UL: 0.17558681964874268
Raw prediction for UN: 0.24993844330310822
Calibrated prediction for UN: 0.3088753819465637
Raw prediction for UNH: 0.2903675138950348
Calibrated prediction for UNH: 0.4393063485622406
Raw prediction for UPS: 0.4809078276157379
Calibrated prediction for UPS: 0.4779593050479889
Raw prediction for UTX: 0.5623658895492554
Calibrated prediction for UTX: 0.5909090638160706
Raw prediction for V: 0.55463045835495
Calibrated prediction for V: 0.5405405163764954
Raw prediction for VZ: 0.7539690136909485
Calibrated prediction for VZ: 0.5716716051101685

Simulating Trading Days: 100%|██████████| 108/108 [07:59<00:00,  4.44s/it]

Raw prediction for WFC: 0.5356542468070984
Calibrated prediction for WFC: 0.5224242210388184
Raw prediction for WMT: 0.4568769037723541
Calibrated prediction for WMT: 0.47951629757881165
Raw prediction for XOM: 0.5459955334663391
Calibrated prediction for XOM: 0.5078077912330627
Investing 3065.6221291146076 in BP
Investing 1665.2709371710978 in HRG
Investing 6443.4064330979145 in KO
Investing 4745.289047988133 in MA
Investing 1730.989976079263 in JNJ
Investing 3804.837284998818 in DHR
Investing 2750.5469357718075 in CHTR
Investing 4804.008613862905 in FB
Investing 2459.8045860808998 in AEP

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-03-30,100000.000000,73391.807950,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'KO', 'investment_fraction': 0.037..."
1,2017-03-31,73391.807950,54697.847726,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'NVS', 'investment_fraction': 0.03..."
2,2017-04-03,54697.847726,41529.667772,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'NVS', 'investment_fraction': 0.03..."
3,2017-04-04,41529.667772,39929.838949,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'PEP', 'investment_fraction': 0.01..."
4,2017-04-05,39929.838949,38391.639616,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'PEP', 'investment_fraction': 0.01..."
...,...,...,...,...,...,...,...,...
95,2017-08-15,62028.946157,49986.102384,104169.960248,104169.960248,7.751402,0.000074,"[{'ticker': 'HON', 'investment_fraction': 0.03..."
96,2017-08-16,60159.038532,49228.864546,104110.113840,104110.113840,-59.846408,-0.000575,"[{'ticker': 'INTC', 'investment_fraction': 0.0..."
97,2017-08-17,62026.150319,50631.008420,104069.797991,104069.797991,-40.315849,-0.000387,"[{'ticker': 'INTC', 'investment_fraction': 0.0..."
98,2017-08-18,60499.845632,53538.077666,103980.519005,103980.519005,-89.278986,-0.000858,"[{'ticker': 'FB', 'investment_fraction': 0.046..."
99,2017-08-21,62542.036198,51832.757659,103871.963821,103871.963821,-108.555184,-0.001044,"[{'ticker': 'FB', 'investment_fraction': 0.046..."

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
8,2017-04-11,51928.700727,48831.798852,100043.047974,100043.047974,-11.144916,-0.000111,"[{'ticker': 'MA', 'investment_fraction': 0.024..."
9,2017-04-12,50367.799889,47386.903740,100040.849678,100040.849678,-2.198296,-0.000022,"[{'ticker': 'AEP', 'investment_fraction': 0.02..."
10,2017-04-13,61970.996368,50650.557525,99935.072479,99935.072479,-105.777199,-0.001057,"[{'ticker': 'NVS', 'investment_fraction': 0.03..."
11,2017-04-17,66358.043879,51412.737477,99968.329546,99968.329546,33.257067,0.000333,"[{'ticker': 'MA', 'investment_fraction': 0.045..."
12,2017-04-18,67588.047622,51422.015165,99931.590891,99931.590891,-36.738655,-0.000368,"[{'ticker': 'MA', 'investment_fraction': 0.045..."
...,...,...,...,...,...,...,...,...
103,2017-08-25,61630.843734,61630.843734,103814.948484,103814.948484,40.459220,0.000390,[]
104,2017-08-28,72405.854968,72405.854968,103880.681179,103880.681179,65.732694,0.000633,[]
105,2017-08-29,86022.452600,86022.452600,103814.321647,103814.321647,-66.359532,-0.000639,[]
106,2017-08-30,94966.246106,94966.246106,103798.883973,103798.883973,-15.437674,-0.000149,[]
107,2017-08-31,103856.277176,103856.277176,103856.277176,103856.277176,57.393203,0.000553,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $103,856.28
Total Return on Investment (ROI): 3.86%
Annualized Sharpe Ratio: 4.50
--------------------------

In [35]:
ret_col = f"ret_{5}d"
if ret_col not in master_df_with_target.columns:
    master_df_with_target = add_horizon_targets(master_df_with_target, H=5, price_col='close_price')

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    # Sector aggregates
    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        # top sectors by pnl
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 615
Total capital allocated: $1,095,199.92
Average position size:  $1,780.81
Completed trades with returns: 615
Winning trades: 326 (53.0%)
Losing trades:  285 (46.3%)
Total PnL: $3,856.28
Average PnL per trade: $6.27
Average return: 0.33%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Services,63,104975.071697,1666.270979,1010.830869,16.044934,0.009255
Financial,71,142889.654709,2012.530348,866.578621,12.205333,0.006147
Technology,69,164513.077496,2384.247500,583.918230,8.462583,0.002149
Utilities,67,119302.433228,1780.633332,551.692427,8.234215,0.005393
Industrial Goods,68,129347.256576,1902.165538,381.156450,5.605242,0.003467
Healthcare,76,103068.909370,1356.169860,314.877859,4.143130,0.004345
Conglomerates,68,81385.513813,1196.845791,190.474901,2.801101,-0.000588
Basic Matierials,65,117658.328344,1810.128128,72.362418,1.113268,0.000313
Consumer Goods,68,132059.675750,1942.054055,-115.614597,-1.700215,-0.000640

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
481,2017-07-25,2017-08-01,CHTR,Services,1815.915229,0.597013,NaN,0.113276,205.699431
401,2017-07-06,2017-07-13,FB,Technology,2776.123761,0.716418,NaN,0.070152,194.750016
203,2017-05-18,2017-05-25,MA,Financial,3693.026123,0.782609,NaN,0.048864,180.457577
489,2017-07-26,2017-08-02,CHTR,Services,1685.813712,0.597013,NaN,0.105428,177.731473
395,2017-07-05,2017-07-12,FB,Technology,2672.508089,0.716418,NaN,0.056938,152.166187
418,2017-07-11,2017-07-18,FB,Technology,2719.804176,0.716418,NaN,0.048883,132.951021
388,2017-07-03,2017-07-11,FB,Technology,2811.265630,0.716418,NaN,0.046082,129.549880
77,2017-04-18,2017-04-25,HON,Industrial Goods,2353.810821,0.666667,NaN,0.050536,118.952758
216,2017-05-19,2017-05-26,CHTR,Services,1731.641293,0.597013,NaN,0.068592,118.776856
225,2017-05-22,2017-05-30,CHTR,Services,1654.541939,0.597013,NaN,0.071108,117.651198

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
132,2017-05-01,2017-05-08,CHTR,Services,1749.041126,0.597013,NaN,-0.059075,-103.324328
164,2017-05-09,2017-05-16,UNH,Healthcare,3403.571417,0.758280,NaN,-0.029554,-100.590621
541,2017-08-09,2017-08-16,BP,Basic Matierials,1851.850637,0.644578,NaN,-0.051715,-95.767667
361,2017-06-26,2017-07-03,FB,Technology,2720.847285,0.716418,NaN,-0.033596,-91.409470
538,2017-08-08,2017-08-15,BP,Basic Matierials,1625.688540,0.644578,NaN,-0.053914,-87.646633
533,2017-08-07,2017-08-14,BP,Basic Matierials,1542.072625,0.644578,NaN,-0.056327,-86.859601
373,2017-06-28,2017-07-06,FB,Technology,2944.407076,0.716418,NaN,-0.028844,-84.927388
372,2017-06-28,2017-07-06,KO,Consumer Goods,3949.204304,0.809821,NaN,-0.020300,-80.169022
575,2017-08-16,2017-08-23,INTC,Technology,2492.829143,0.710627,NaN,-0.032114,-80.054620
518,2017-08-03,2017-08-10,MA,Financial,4325.997031,0.829842,NaN,-0.017091,-73.937315

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Services          1010.830869
Financial          866.578621
Technology         583.918230
Utilities          551.692427
Industrial Goods   381.156450
Healthcare         314.877859
Conglomerates      190.474901
Basic Matierials    72.362418
Consumer Goods    -115.614597

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Services          1010.830869
Financial          866.578621
Technology         583.918230
Utilities          551.692427
Industrial Goods   381.156450
Healthcare         314.877859
Conglomerates      190.474901
Basic Matierials    72.362418
Consumer Goods    -115.614597

In [36]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]