# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.optim.lr_scheduler import ReduceLROnPlateau

### Configurations

In [7]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 783  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [8]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [9]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [10]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [11]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # End current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [12]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [13]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [14]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [15]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [16]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [17]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [18]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [19]:
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.float32))
    def __len__(self): return self.X.shape[0]
    def __getitem__(self, idx): return self.X[idx], self.y[idx]

class LSTMClassifier(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, use_layernorm=False):
        super().__init__()
        self.lstm1 = nn.LSTM(
            input_size=n_features, hidden_size=hidden1,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )
        self.inter_drop = nn.Dropout(p=inter_dropout)  # proxy for recurrent_dropout
        self.lstm2 = nn.LSTM(
            input_size=hidden1, hidden_size=hidden2,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )

        # Normalization after temporal pooling
        self.use_layernorm = bool(use_layernorm)
        if self.use_layernorm:
            self.norm = nn.LayerNorm(normalized_shape=hidden2)
        else:
            self.norm = nn.BatchNorm1d(num_features=hidden2)

        # Head
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(p=dropout)
        self.fc_out = nn.Linear(fc, 1)  # logits

    def forward(self, x):
        # x: (B, T, F)
        out1, _ = self.lstm1(x)     # (B, T, hidden1)
        out1 = self.inter_drop(out1)
        out2, _ = self.lstm2(out1)  # (B, T, hidden2)

        last = out2[:, -1, :]       # (B, hidden2)
        if isinstance(self.norm, nn.BatchNorm1d):
            last = self.norm(last)  # BN expects (B, C)
        else:
            last = self.norm(last)  # LN expects (B, C)

        z = self.fc1(last)
        z = self.relu(z)
        z = self.drop(z)
        logits = self.fc_out(z).squeeze(-1)  # (B,)
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [20]:
from matplotlib import ticker


def train_company_models(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         sequence_length: int = None,
                         H = 1):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    #sequence length & guards
    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)

    if len(company_data_df) < sequence_length + H + 10:
        print(f"Not enough data for {ticker}.")
        return False, sequence_length

    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        print(f"No contiguous periods found for {ticker}.")
        return False, sequence_length

    # build sequences
    targets = company_data_df[f'target_{H}d'].values
    X, y = create_contiguous_sequences(
        company_data_df[feature_cols].values,
        targets,
        contiguous_periods,
        sequence_length,
        H
    )
    print(f"Created {len(X)} sequences for {ticker}.")
    if len(X) < 2:
        return False, sequence_length

    # chronological split (no shuffle)
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    # scale features (fit on train, transform both)
    scaler = MinMaxScaler()
    F = X_train.shape[-1]
    X_train_scaled = scaler.fit_transform(X_train.reshape(-1, F)).reshape(X_train.shape)
    X_val_scaled   = scaler.transform(  X_val.reshape(-1, F)).reshape(X_val.shape)
    
    print(f"[TRAIN] {ticker}: scaler fitted on {X_train.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_train has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    sector_feature_indices = [feature_cols.index('sector_ret_1d'),
                          feature_cols.index('sector_ret_5d'),
                          feature_cols.index('sector_vol_20d')]

    print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")

    # Keras fit used the scaled data
    train_ds = SequenceDataset(X_train_scaled, y_train)
    val_ds   = SequenceDataset(X_val_scaled,   y_val)

    train_bs = min(32, len(train_ds))
    if train_bs < 2:
        print(f"[TRAIN] {ticker}: too few samples for BatchNorm (train size={len(train_ds)})")
        return False, sequence_length
    if len(train_ds) % train_bs == 1 and train_bs > 2:
        train_bs -= 1  # avoid batch size 1 for BatchNorm
    val_bs = min(32, len(val_ds))

    train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=True, drop_last=False)
    val_loader   = DataLoader(val_ds,   batch_size=val_bs, shuffle=False, drop_last=False)

    n_features = X_train.shape[-1]
    model = LSTMClassifier(n_features=n_features, dropout=0.3, inter_dropout=0.1).to(device)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)  # clipnorm via grad clipping below
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)
    early = EarlyStopper(patience=15, mode='min')

    for epoch in range(100):
        model.train()
        total_loss = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # clipnorm=1.0
            optimizer.step()
            total_loss += loss.item() * xb.size(0)

        train_loss = total_loss / len(train_loader.dataset)
        val_loss, _ = _evaluate(model, val_loader, device, loss_fn)

        scheduler.step(val_loss)  # ReduceLROnPlateau on val_loss

        # EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:  # stop after 'patience' non-improve epochs
            break

    # restore best weights
    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    # final validation pass for isotonic calibration (on scaled val data)
    _, validation_predictions = _evaluate(model, val_loader, device, loss_fn)

    # Keras code used 10% buffer (comment said 5%)
    pred_min, pred_max = validation_predictions.min(), validation_predictions.max()
    buffer = 0.05 * (pred_max - pred_min)
    y_min_dynamic = max(0.0, pred_min - buffer)
    y_max_dynamic = min(1.0, pred_max + buffer)

    calibrator = IsotonicRegression(y_min=y_min_dynamic, y_max=y_max_dynamic, out_of_bounds='clip')
    calibrator.fit(validation_predictions, y_val.astype(float))

    # inside train_company_models(..., H=H)
    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt"))
    joblib.dump(calibrator,      os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
    joblib.dump(scaler,          os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


    del model, scaler, calibrator, train_loader, val_loader, train_ds, val_ds
    del X_train, X_val, y_train, y_val, X_train_scaled, X_val_scaled
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [21]:
def predict_next_horizon(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 H: int) -> dict | None:

    try:
        # load artifacts
        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt")
        calibrator = joblib.load(os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
        scaler     = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        sequence_length    = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


        if not os.path.isfile(state_dict_path):
            return None
        
        if hasattr(scaler, "n_features_in_") and scaler.n_features_in_ != len(feature_cols):
            return None

        # build model skeleton with correct input dim, then load weights
        n_features = len(feature_cols)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        model = LSTMClassifier(n_features=n_features).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    # find the last contiguous block and take the most recent sequence_length rows
    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        return None

    last_start, last_end = contiguous_periods[-1]
    period_data = company_data_df.iloc[last_start:last_end + 1]
    if len(period_data) < sequence_length:
        return None

    last_sequence = period_data.tail(sequence_length)

    # scale using the saved scaler (fit  train only)
    # ensure column order matches training
    try:
        scaled_features = scaler.transform(last_sequence[feature_cols])
    except Exception:
        return None

    # shape: (1, T, F) as float32 tensor
    x = torch.from_numpy(np.asarray([scaled_features], dtype=np.float32)).to(device)

    with torch.no_grad():
        logits = model(x)                  # shape (1,)
        prob = torch.sigmoid(logits).item()  # scalar in [0,1]

    # isotonic calibration (expects iterable)
    calibrated = float(calibrator.predict([prob])[0])

    print(f"Raw prediction for {ticker}: {prob}")
    print(f"Calibrated prediction for {ticker}: {calibrated}")

    return {
        'ticker': ticker,
        'raw_prediction': prob,
        'calibrated_prediction': calibrated
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [22]:
def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                            total_capital: float, sector_threshold: float,
                            kelly_fraction: float, top_k: int = 3, softmax_alpha: float = 1) -> pd.DataFrame:

    investment_decisions = []

    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")

    # sector-level filter
    df = daily_predictions_df.copy()
    df = df.groupby('sector').filter(lambda g: g['calibrated_prediction'].mean() >= sector_threshold)
    if df.empty:
        print("[PORT] No sectors cleared confidence threshold.")
        return pd.DataFrame()

    candidates = []
    for _, row in df.iterrows():
        ticker = row['ticker']
        p = float(row['calibrated_prediction'])
        b_info = payout_map.get(ticker, 0.0)
        b = (b_info['b'] if isinstance(b_info, dict) else float(b_info))
        if not np.isfinite(b) or b <= 0:
            continue
        if not b_info or not np.isfinite(b_info.get('b', np.nan)):
            continue
        b = max(b_info['b'], 1e-6)  # avoid div-by-zero
        kelly_percentage = p - (1 - p) / b
        if kelly_percentage <= 0:
            continue
        investment_fraction = kelly_percentage * kelly_fraction
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            continue
        cand = row.to_dict()
        cand.update({
            'kelly_percentage': kelly_percentage,
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount,
        })
        candidates.append(cand)

    if not candidates:
        print("[PORT] All candidates rejected after sizing/filters.")
        return pd.DataFrame()

    cand_df = pd.DataFrame(candidates)

    rows = []
    alpha = max(softmax_alpha, 1e-6)
    for sector, group in cand_df.groupby('sector'):
        if group.empty:
            continue
        top_group = group.sort_values('calibrated_prediction', ascending=False).head(max(1, top_k))
        logits = top_group['calibrated_prediction'].to_numpy() * 100.0 * alpha
        logits = logits - logits.max()  # stabilize
        weights = np.exp(logits)
        probs = weights / weights.sum()
        choice_idx = np.random.choice(len(top_group), p=probs)
        choice = top_group.iloc[choice_idx]

        print(f"[PORT] Sector {sector}: sampled {choice['ticker']} from top-{len(top_group)} (p={choice['calibrated_prediction']:.3f})")

        rows.append({
            'ticker': choice['ticker'],
            'investment_fraction': choice['investment_fraction'],
            'investment_amount': choice['investment_amount'],
            'predicted_prob': choice['calibrated_prediction']
        })

    if not rows:
        print("[PORT] All sector winners rejected after sampling.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [23]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    files = [
        f"{ticker}_lstm_H{H}.pt",
        f"{ticker}_calibrator_H{H}.pkl",
        f"{ticker}_scaler_H{H}.pkl",
        f"{ticker}_seq_length_H{H}.pkl",
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in files)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [24]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # returns used for settlement only; not for training
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker','date'])[ret_col].to_dict()
    close_lookup = master_df.set_index(['ticker', 'date'])['close'].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    early_exit_lookup = None
    early_exit_threshold = 0.4  # exit when p_up_1d < threshold (downside signal)
    if H > 1:
        early_exit_path = 'stocknet-dataset/h1_early_exit_df.parquet'
        if not os.path.exists(early_exit_path):
            early_exit_path = 'stocknet-dataset/h1_exit_df.parquet'
        if os.path.exists(early_exit_path):
            try:
                h1_exit_df = pd.read_parquet(early_exit_path)
                h1_exit_df['date'] = pd.to_datetime(h1_exit_df['date'])
                h1_exit_df = h1_exit_df.drop_duplicates(subset=['date', 'ticker'])
                early_exit_lookup = h1_exit_df.set_index(['date', 'ticker'])['p_up_1d'].to_dict()
                print(f"[EARLY EXIT] Loaded {len(h1_exit_df)} signals from {early_exit_path}")
            except Exception as exc:
                print(f"[EARLY EXIT] Failed to load signals: {exc}")
                early_exit_lookup = None
        else:
            print("[EARLY EXIT] No 1d exit signal file found; early exit disabled.")

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    open_positions = []
    prev_equity_end = capital
    total_early_exits = 0
    early_exit_pnl_total = 0.0
    early_exit_counterfactual_total = 0.0
    early_exit_counterfactual_count = 0

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = pd.to_datetime(unique_dates[i])
        prev_date = pd.to_datetime(unique_dates[i-1]) if i > 0 else None
        early_exits_today = 0

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                if pd.notna(rH):
                    pnl = pos['invest'] * rH
                    total_pnl_today += pnl
                    capital += pos['invest'] + pnl
            else:
                still_open.append(pos)
        open_positions = still_open

        # early-exit check (signal at current_date predicts tomorrow)
        if H > 1 and early_exit_lookup:
            remaining = []
            for pos in open_positions:
                p_up_1d = early_exit_lookup.get((current_date, pos['ticker']))
                if p_up_1d is None or not np.isfinite(p_up_1d):
                    remaining.append(pos)
                    continue
                if float(p_up_1d) < early_exit_threshold:
                    entry_close = close_lookup.get((pos['ticker'], pos['entry_date']))
                    exit_close = close_lookup.get((pos['ticker'], current_date))
                    if entry_close is None or exit_close is None:
                        remaining.append(pos)
                        continue
                    if not np.isfinite(entry_close) or not np.isfinite(exit_close):
                        remaining.append(pos)
                        continue
                    r_exit = (exit_close / entry_close) - 1.0
                    pnl = pos['invest'] * r_exit
                    total_pnl_today += pnl
                    capital += pos['invest'] + pnl
                    early_exits_today += 1
                    total_early_exits += 1
                    early_exit_pnl_total += pnl

                    planned_rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                    if pd.notna(planned_rH):
                        early_exit_counterfactual_total += pos['invest'] * planned_rH
                        early_exit_counterfactual_count += 1

                    print(
                        f"[EARLY EXIT] {current_date}: {pos['ticker']} p_up_1d={p_up_1d:.3f} -> exit; "
                        f"r={r_exit:.4f}, PnL=${pnl:.2f}"
                    )
                else:
                    remaining.append(pos)
            open_positions = remaining

        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # historical slice strictly before current_date; recompute targets locally
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        cutoff = current_date - pd.Timedelta(days=H)
        historical_data = historical_data[historical_data['date'] < cutoff]
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if prev_date is None:
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == prev_date]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if not have_models or need_retrain:
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)

        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df, payout_map_day, capital, SECTOR_CONFIDENCE_THRESHOLD, KELLY_FRACTION
        )

        exit_idx = i + H
        exit_date = pd.to_datetime(unique_dates[exit_idx]) if exit_idx < len(unique_dates) else None

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)

            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue

                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))

                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})

        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,
            'capital_end': capital,
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,
            'daily_return': daily_return,
            'early_exits_today': early_exits_today,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    print(f"[EARLY EXIT] Total early exits: {total_early_exits}")
    if total_early_exits > 0:
        print(f"[EARLY EXIT] PnL realized from early exits: ${early_exit_pnl_total:,.2f}")
        if early_exit_counterfactual_count > 0:
            print(
                f"[EARLY EXIT] PnL if held to horizon: ${early_exit_counterfactual_total:,.2f} "
                f"(n={early_exit_counterfactual_count})"
            )
            print(
                f"[EARLY EXIT] Delta vs hold-to-horizon: "
                f"${early_exit_pnl_total - early_exit_counterfactual_total:,.2f}"
            )
        else:
            print("[EARLY EXIT] Counterfactual PnL unavailable for early exits.")
    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [25]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [26]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_and_bimeta_features.parquet')

In [27]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)
# Exclude ticker with missing meta-features across all rows
master_df = master_df[master_df['ticker'] != 'GMRE']

columns_to_check = ['EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower',
    
    'lstm_prob_up_1d', 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [28]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    # 'lstm_prob_up_1d', 
    # 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    # 'gru_pred_ret_1d', 
    # 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength']
Total number of features: 28

In [29]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [ ]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=5,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Starting simulation with 783 initial training days... (H=5)
[EARLY EXIT] Loaded 8613 signals from stocknet-dataset/h1_exit_df.parquet
Starting predictions from day 783 (after 783 training days)

Simulating Trading Days:   0%|          | 0/100 [00:00<?, ?it/s]

Raw prediction for AAPL: 0.5011709928512573
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.4897612929344177
Calibrated prediction for ABB: 0.5138888955116272
Raw prediction for ABBV: 0.5034603476524353
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49120187759399414
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.7661342620849609
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.47884663939476013
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5334091186523438
Calibrated prediction for AMZN: 0.5335751175880432
Raw prediction for BA: 0.3096003830432892
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5383180975914001
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44556117057800293
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4981757402420044
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4881763756275177
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.505877673625946
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5551674365997314
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4713161885738373
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46966028213500977
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.577431321144104
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5390297770500183
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48374319076538086
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5705918073654175
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49331751465797424
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5225189924240112
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.5221790075302124
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.44459474086761475
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.6487925052642822
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4650692343711853
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4788721203804016
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5222352743148804
Calibrated prediction for DHR: 0.5184097290039062
Raw prediction for DIS: 0.4581899642944336
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5328972339630127
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4519823491573334
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5257323384284973
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4700952470302582
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4684792459011078
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5537706017494202
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5153746008872986
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5437225699424744
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5090465545654297
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5051431059837341
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.48028281331062317
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.3992939889431
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5113264918327332
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4817360043525696
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4877910017967224
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4913826286792755
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.41941237449645996
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5706874132156372
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.16486720740795135
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48585790395736694
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2906564176082611
Calibrated prediction for MO: 0.5535454750061035
Raw prediction for MRK: 0.47736895084381104
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6120395660400391
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5147983431816101
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5541349053382874
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.40513911843299866
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3154163658618927
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5240492820739746
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5273128151893616
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4607389569282532
Calibrated prediction for PEP: 0.5061016082763672
Raw prediction for PFE: 0.49058297276496887
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.42869138717651367
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4919939935207367
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5140641331672668
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5896791219711304
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5082512497901917
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46234130859375
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.4732082486152649
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6102579236030579
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5406565070152283
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4988288879394531
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.463815301656723
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4819065034389496
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.47457659244537354
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6546921133995056
Calibrated prediction for T: 0.6666666865348816
Raw prediction for TM: 0.4867282807826996
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5050888061523438
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5131297707557678
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.48231345415115356
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6912049651145935
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.5376741886138916
Calibrated prediction for UNH: 0.47727271914482117

Simulating Trading Days:   1%|          | 1/100 [00:01<02:07,  1.29s/it]

Raw prediction for UPS: 0.48898202180862427
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.44547832012176514
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5168054103851318
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.565706193447113
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5045995712280273
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.5028073191642761
Calibrated prediction for WMT: 0.5194805264472961
Raw prediction for XOM: 0.6704583764076233
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.500739336013794
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.4904598891735077
Calibrated prediction for ABB: 0.5138888955116272
Raw prediction for ABBV: 0.5024609565734863
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4904932677745819
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8134698271751404
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.48020872473716736
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5341697335243225
Calibrated prediction for AMZN: 0.5335751175880432
Raw prediction for BA: 0.3120920658111572
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5359100103378296
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4450259804725647
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4983605444431305
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4878205358982086
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5064284801483154
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5576056838035583
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47193729877471924
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46993565559387207
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5761439204216003
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5394600033760071
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4838615357875824
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5599027872085571
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49428898096084595
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5215437412261963
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.522225022315979
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.456533819437027
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.6628756523132324
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46430736780166626
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4666246175765991
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5222972631454468
Calibrated prediction for DHR: 0.5184097290039062
Raw prediction for DIS: 0.4582980275154114
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5330665111541748
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4496191740036011
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5258051156997681
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.46211928129196167
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4800145626068115
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5517967343330383
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5145713090896606
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5442872047424316
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5083831548690796
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.503667950630188
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.47270554304122925
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.40777841210365295
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5117768049240112
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.47993218898773193
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48735082149505615
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49158552289009094
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4253845810890198
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5634855031967163
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1673569232225418
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48552507162094116
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.30015310645103455
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4774724841117859
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.612069308757782
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.513827919960022
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5522761940956116
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.412540078163147
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3127612769603729
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5247471928596497
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5277001261711121
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46762385964393616
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.48986127972602844
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4325063228607178
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49206840991973877
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5141640901565552
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6393073797225952
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5089830756187439
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4627515375614166
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.46980127692222595
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6072733998298645
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5391384959220886
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49893438816070557
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4638074040412903
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48134636878967285
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4627735912799835
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6579204201698303
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4870469272136688
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5049086809158325
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5126208662986755
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.49405136704444885
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6547974944114685
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.5193518400192261
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48891010880470276
Calibrated prediction for UPS: 0.488449364900589
Raw prediction for UTX: 0.44705623388290405
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5164681673049927
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5633907914161682
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5045738220214844
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.49938955903053284
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:   2%|▏         | 2/100 [00:02<02:00,  1.23s/it]

Raw prediction for XOM: 0.6652703285217285
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5002825260162354
Calibrated prediction for AAPL: 0.5272117853164673
Raw prediction for ABB: 0.49791043996810913
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5014636516571045
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48991185426712036
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8325394988059998
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4823702573776245
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.535442054271698
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.31900298595428467
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5320401191711426
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44446247816085815
Calibrated prediction for BAC: 0.4537438750267029
Raw prediction for BBL: 0.49848422408103943
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4877888262271881
Calibrated prediction for BCH: 0.5055257081985474
Raw prediction for BHP: 0.5064874291419983
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5639113187789917
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.472577303647995
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.47037819027900696
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5741175413131714
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5397805571556091
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48401784896850586
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5620294213294983
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4956604540348053
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5221457481384277
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.522244930267334
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.4694038927555084
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.6740214824676514
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.463477224111557
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4497949182987213
Calibrated prediction for D: 0.5384615659713745
Raw prediction for DHR: 0.5224315524101257
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4583255648612976
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5332131385803223
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4486393332481384
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5259848237037659
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4693520963191986
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4916954040527344
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.555006742477417
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5141000151634216
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5460528135299683
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5082241296768188
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5041180849075317
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4649340510368347
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.41818663477897644
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5122711658477783
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.48085781931877136
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48705554008483887
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4917739927768707
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4349493086338043
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5638174414634705
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1747017204761505
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.485382080078125
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3099484443664551
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47754767537117004
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6108413338661194
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5133082270622253
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5498422980308533
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.4292333126068115
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3115292191505432
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5222651958465576
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5281280875205994
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4743908643722534
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.48849090933799744
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4199957251548767
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49227187037467957
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5143598914146423
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.664878249168396
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5099039673805237
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46346136927604675
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.46495321393013
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6085243821144104
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.533129870891571
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4991762638092041
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4641275107860565
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4806598424911499
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.45557695627212524
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6597896814346313
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4874174892902374
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5050175786018372
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.512037992477417
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4999542236328125
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6126728653907776
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4932895004749298
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4889850616455078
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4452168643474579
Calibrated prediction for UTX: 0.6818181872367859

Simulating Trading Days:   3%|▎         | 3/100 [00:03<01:53,  1.17s/it]

Raw prediction for V: 0.5163232088088989
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.56297767162323
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5047184228897095
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.49558717012405396
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6618368029594421
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5000012516975403
Calibrated prediction for AAPL: 0.503137469291687
Raw prediction for ABB: 0.5032824873924255
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5005912780761719
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48957574367523193
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8860569596290588
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4846201539039612
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5381953716278076
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3266761600971222
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5277572870254517
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4444692134857178
Calibrated prediction for BAC: 0.4545596241950989
Raw prediction for BBL: 0.49846023321151733
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48759332299232483
Calibrated prediction for BCH: 0.499236136674881
Raw prediction for BHP: 0.5052650570869446
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5711745619773865
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4731876254081726
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.47056668996810913
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5719946622848511
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5402623414993286
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4842940866947174
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5633217096328735
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49741846323013306
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5245386362075806
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.5223127603530884
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.46685150265693665
Calibrated prediction for CODI: 0.4440469443798065
Raw prediction for CSCO: 0.684745728969574
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4627280533313751
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43348783254623413
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.522704005241394
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4582898020744324
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5333037376403809
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4497576355934143
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5262585282325745
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4745193421840668
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.500054121017456
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5598286390304565
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5141974091529846
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5472740530967712
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5088217258453369
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5047464370727539
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4853479266166687
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.435709148645401
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.512676477432251
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.48209714889526367
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48673945665359497
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4920091927051544
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4726540744304657
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5663307905197144
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.18015718460083008
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4852118194103241
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.322659432888031
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4780663847923279
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6097432374954224
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.513222336769104
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5469779372215271
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.4449561536312103
Calibrated prediction for NVS: 0.4583333432674408
Raw prediction for ORCL: 0.3146044611930847
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5189105868339539
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.528471052646637
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4795082211494446
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4893590211868286
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4132658839225769
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4925306737422943
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5146417021751404
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6726820468902588
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5105488300323486
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4637162387371063
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4583050310611725
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6086440682411194
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5306289792060852
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4994596242904663
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46451184153556824
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4801875650882721
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.44715383648872375
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6604164242744446
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4877498149871826
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5048615336418152
Calibrated prediction for TOT: 0.5130005478858948

Simulating Trading Days:   4%|▍         | 4/100 [00:04<01:49,  1.14s/it]

Raw prediction for TSM: 0.5113965272903442
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.501028835773468
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.561649739742279
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.46964746713638306
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48912665247917175
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4349202513694763
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5163548588752747
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5650545954704285
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5046133399009705
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.49226540327072144
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6553316116333008
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5000951886177063
Calibrated prediction for AAPL: 0.5111775398254395
Raw prediction for ABB: 0.5086352825164795
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5001295804977417
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48930034041404724
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8663860559463501
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4849699139595032
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5404248237609863
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.33127695322036743
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5257140398025513
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4444810748100281
Calibrated prediction for BAC: 0.45599618554115295
Raw prediction for BBL: 0.49817952513694763
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4874267876148224
Calibrated prediction for BCH: 0.4938123822212219
Raw prediction for BHP: 0.5036529898643494
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5765070915222168
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47404396533966064
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4706803262233734
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5704129338264465
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.540679931640625
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4844173192977905
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5345937609672546
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5011051297187805
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5294885635375977
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.5222592353820801
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.47787824273109436
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.6906947493553162
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46223971247673035
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.42304727435112
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5232119560241699
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4581528306007385
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5333937406539917
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.45493951439857483
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5266037583351135
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4581158459186554
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5058995485305786
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5651475191116333
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5150353908538818
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5459142327308655
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5083478093147278
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5063428282737732
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4892929196357727
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.45849481225013733
Calibrated prediction for INTC: 0.5185185074806213
Raw prediction for JNJ: 0.5130394697189331
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4834841787815094
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4864708483219147
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49143800139427185
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4935741126537323
Calibrated prediction for MA: 0.5762563347816467
Raw prediction for MCD: 0.5695180296897888
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1862775981426239
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48491182923316956
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3331712484359741
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4786900281906128
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6065190434455872
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.513407289981842
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5443602204322815
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.45934852957725525
Calibrated prediction for NVS: 0.4583333432674408
Raw prediction for ORCL: 0.31574445962905884
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5191338062286377
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5287633538246155
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48302987217903137
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4890006184577942
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4051387310028076
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49275511503219604
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5148153305053711
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6777892112731934
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5107367038726807
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4636184275150299
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.45285460352897644
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6083157062530518
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5233445763587952
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5000688433647156
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46500736474990845
Calibrated prediction for SO: 0.4545454680919647

Simulating Trading Days:   5%|▌         | 5/100 [00:05<01:47,  1.13s/it]

Raw prediction for SPLP: 0.4797249734401703
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4401690661907196
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6612802743911743
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4880143105983734
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5046209692955017
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5108797550201416
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.49755552411079407
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5008987784385681
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4411925673484802
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4893244206905365
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.41882503032684326
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5163149237632751
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5669382214546204
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5044814348220825
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4901424050331116
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.645356297492981
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5006498098373413
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5140183568000793
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49952706694602966
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48899513483047485
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8550636768341064
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.48497384786605835
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5417131781578064
Calibrated prediction for AMZN: 0.5590608716011047
Raw prediction for BA: 0.33741721510887146
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5250200629234314
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44461876153945923
Calibrated prediction for BAC: 0.4726719856262207
Raw prediction for BBL: 0.4975678026676178
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48718541860580444
Calibrated prediction for BCH: 0.4859514832496643
Raw prediction for BHP: 0.501376211643219
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5742821097373962
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4752345383167267
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4702357053756714
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5685970783233643
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5410876274108887
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48456549644470215
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.47965359687805176
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5052480697631836
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5369828939437866
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.5222259163856506
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.48898202180862427
Calibrated prediction for CODI: 0.5
Raw prediction for CSCO: 0.6943802833557129
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4617835283279419
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.41403326392173767
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5239980816841125
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45791760087013245
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5335868000984192
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.46153900027275085
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5268491506576538
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.42582544684410095
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5111060738563538
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5696521997451782
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5172345638275146
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5420718789100647
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5074678659439087
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.506866991519928
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4889199435710907
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.4890909492969513
Calibrated prediction for INTC: 0.5333333611488342
Raw prediction for JNJ: 0.5133345127105713
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4842771291732788
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4861612915992737
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4911027252674103
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5040904879570007
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5706064701080322
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.19194409251213074
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4846866726875305
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.33935025334358215
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4793541729450226
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6015896201133728
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5133682489395142
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5408519506454468
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.4822731018066406
Calibrated prediction for NVS: 0.4583333432674408
Raw prediction for ORCL: 0.31853827834129333
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5215863585472107
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5289395451545715
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48220956325531006
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.49150487780570984
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.39773431420326233
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49293893575668335
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5149452090263367
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6845530271530151
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.510200023651123
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46307677030563354
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4481012523174286
Calibrated prediction for REX: 0.4444444477558136
Raw prediction for SLB: 0.6044391393661499
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5029590725898743
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.500866711139679
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46560969948768616
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4795475900173187
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.43341994285583496
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6636788845062256
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.48812028765678406
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5036869645118713
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5104387998580933
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4912909269332886
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.44948455691337585
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4167889654636383
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4895758032798767
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4007493853569031
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5163454413414001
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5692505240440369
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5042711496353149
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:   6%|▌         | 6/100 [00:06<01:48,  1.15s/it]

Raw prediction for WMT: 0.4886600375175476
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6403325200080872
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

UnboundLocalError: cannot access local variable 'early_exit_counterfactual_total' where it is not associated with a value

In [ ]:
H = 5
master_df_with_target = add_horizon_targets(master_df.copy(), H=H, price_col="close")
ret_col = f"ret_{H}d"

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    # Sector aggregates
    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        # top sectors by pnl
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
         # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 591
Total capital allocated: $1,208,462.50
Average position size:  $2,044.78
Completed trades with returns: 591
Winning trades: 357 (60.4%)
Losing trades:  229 (38.7%)
Total PnL: $9,675.28
Average PnL per trade: $16.37
Average return: 0.71%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Conglomerates,59,196137.019401,3324.356261,4641.969080,78.677442,0.022024
Services,62,134391.855401,2167.610571,1784.452420,28.781491,0.013747
Financial,68,103944.947491,1528.602169,1127.003325,16.573578,0.009867
Technology,62,156923.761043,2531.028404,835.860478,13.481621,0.005444
Industrial Goods,67,117222.125287,1749.583960,650.223545,9.704829,0.007829
Utilities,63,119400.490863,1895.245887,407.738827,6.472045,0.003325
Healthcare,70,81048.172874,1157.831041,316.791650,4.525595,0.002390
Consumer Goods,65,167832.415406,2582.037160,93.061016,1.431708,0.003366
Basic Matierials,75,131561.713194,1754.156176,-181.821494,-2.424287,-0.001091

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
97,2017-05-04,2017-05-11,AGFS,Conglomerates,3570.449950,0.780890,NaN,0.314176,1121.750559
104,2017-05-05,2017-05-12,AGFS,Conglomerates,3788.456573,0.780890,NaN,0.249104,943.719469
1,2017-04-11,2017-04-19,AGFS,Conglomerates,5945.864698,0.780890,NaN,0.158000,939.446622
89,2017-05-03,2017-05-10,AGFS,Conglomerates,3463.848700,0.780890,NaN,0.212569,736.307949
7,2017-04-12,2017-04-20,AGFS,Conglomerates,4178.581958,0.780890,NaN,0.129630,541.668032
16,2017-04-13,2017-04-21,AGFS,Conglomerates,2882.773633,0.780890,NaN,0.180698,520.911868
343,2017-06-30,2017-07-10,AGFS,Conglomerates,3159.423043,0.722726,NaN,0.111421,352.024852
337,2017-06-29,2017-07-07,AGFS,Conglomerates,3781.174317,0.780890,NaN,0.083447,315.528910
349,2017-07-03,2017-07-11,AGFS,Conglomerates,2873.272462,0.705882,NaN,0.097297,279.561645
36,2017-04-20,2017-04-27,AGFS,Conglomerates,4058.799788,0.780890,NaN,0.060109,243.971572

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
65,2017-04-27,2017-05-04,AGFS,Conglomerates,3737.768839,0.780890,NaN,-0.103093,-385.336994
440,2017-07-24,2017-07-31,AGFS,Conglomerates,3079.764282,0.705882,NaN,-0.102417,-315.418897
445,2017-07-25,2017-08-01,AGFS,Conglomerates,3103.883705,0.705882,NaN,-0.093533,-290.317067
433,2017-07-21,2017-07-28,AGFS,Conglomerates,3156.230940,0.705882,NaN,-0.085155,-268.769953
481,2017-08-01,2017-08-08,AGFS,Conglomerates,3975.014956,0.780890,NaN,-0.061146,-243.058239
226,2017-06-05,2017-06-12,AGFS,Conglomerates,4038.715307,0.780890,NaN,-0.051351,-207.393489
466,2017-07-28,2017-08-04,AGFS,Conglomerates,3431.782307,0.705882,NaN,-0.054088,-185.618414
219,2017-06-02,2017-06-09,AGFS,Conglomerates,4034.465470,0.780890,NaN,-0.044595,-179.915352
57,2017-04-26,2017-05-03,AGFS,Conglomerates,3461.624215,0.780890,NaN,-0.050877,-176.117723
240,2017-06-07,2017-06-14,UN,Consumer Goods,4473.007120,0.864865,NaN,-0.037108,-165.984561

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Conglomerates     4641.969080
Services          1784.452420
Financial         1127.003325
Technology         835.860478
Industrial Goods   650.223545
Utilities          407.738827
Healthcare         316.791650
Consumer Goods      93.061016
Basic Matierials  -181.821494

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Conglomerates     4641.969080
Services          1784.452420
Financial         1127.003325
Technology         835.860478
Industrial Goods   650.223545
Utilities          407.738827
Healthcare         316.791650
Consumer Goods      93.061016
Basic Matierials  -181.821494

Top 10 Most Invested Tickers:

ticker
AGFS    57
MA      48
CELG    46
PPL     42
CSCO    41
UTX     33
BP      31
MCD     31
CHTR    30
MO      23
Name: count, dtype: int64

Tickers Never Invested In (50):
{'NVS', 'PTR', 'DHR', 'ORCL', 'SNY', 'RDS-B', 'LMT', 'BCH', 'FB', 'PCLN', 'MDT', 'PICO', 'MMM', 'BAC', 'HRG', 'TSM', 'SO', 'INTC', 'NEE', 'TM', 'BHP', 'BRK-A', 'UPS', 'CVX', 'KO', 'BSAC', 'EXC', 'HD', 'DUK', 'CHL', 'TOT', 'BABA', 'CMCSA', 'UL', 'V', 'GE', 'BUD', 'AMGN', 'AEP', 'MSFT', 'CAT', 'WMT', 'REX', 'SPLP', 'DIS', 'WFC', 'PCG', 'BBL', 'IEP', 'PM'}

In [ ]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]