# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.optim.lr_scheduler import ReduceLROnPlateau

### Configurations

In [ ]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 783  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

ALLOCATION_MODE = "KELLY_ONLY"  # {"KELLY_ONLY", "HYBRID_KELLY_MPT", "MPT_ONLY"}
MPT_WINDOW_DAYS = 60
MPT_LAMBDA = 1.0
MPT_RIDGE_EPS = 1e-4
MPT_MAX_WEIGHT = 0.30
MPT_LONG_ONLY = True
MPT_USE_EQUAL_FALLBACK = True
MPT_ONLY_BUDGET_FRACTION = 0.25

In [8]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [9]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [10]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [11]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # End current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [12]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [13]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [14]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [15]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [16]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [17]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [18]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [19]:
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.float32))
    def __len__(self): return self.X.shape[0]
    def __getitem__(self, idx): return self.X[idx], self.y[idx]

class LSTMClassifier(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, use_layernorm=False):
        super().__init__()
        self.lstm1 = nn.LSTM(
            input_size=n_features, hidden_size=hidden1,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )
        self.inter_drop = nn.Dropout(p=inter_dropout)  # proxy for recurrent_dropout
        self.lstm2 = nn.LSTM(
            input_size=hidden1, hidden_size=hidden2,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )

        # Normalization after temporal pooling
        self.use_layernorm = bool(use_layernorm)
        if self.use_layernorm:
            self.norm = nn.LayerNorm(normalized_shape=hidden2)
        else:
            self.norm = nn.BatchNorm1d(num_features=hidden2)

        # Head
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(p=dropout)
        self.fc_out = nn.Linear(fc, 1)  # logits

    def forward(self, x):
        # x: (B, T, F)
        out1, _ = self.lstm1(x)     # (B, T, hidden1)
        out1 = self.inter_drop(out1)
        out2, _ = self.lstm2(out1)  # (B, T, hidden2)

        last = out2[:, -1, :]       # (B, hidden2)
        if isinstance(self.norm, nn.BatchNorm1d):
            last = self.norm(last)  # BN expects (B, C)
        else:
            last = self.norm(last)  # LN expects (B, C)

        z = self.fc1(last)
        z = self.relu(z)
        z = self.drop(z)
        logits = self.fc_out(z).squeeze(-1)  # (B,)
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [20]:
from matplotlib import ticker


def train_company_models(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         sequence_length: int = None,
                         H = 1):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    #sequence length & guards
    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)

    if len(company_data_df) < sequence_length + H + 10:
        print(f"Not enough data for {ticker}.")
        return False, sequence_length

    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        print(f"No contiguous periods found for {ticker}.")
        return False, sequence_length

    # build sequences
    targets = company_data_df[f'target_{H}d'].values
    X, y = create_contiguous_sequences(
        company_data_df[feature_cols].values,
        targets,
        contiguous_periods,
        sequence_length,
        H
    )
    print(f"Created {len(X)} sequences for {ticker}.")
    if len(X) < 2:
        return False, sequence_length

    # chronological split (no shuffle)
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    # scale features (fit on train, transform both)
    scaler = MinMaxScaler()
    F = X_train.shape[-1]
    X_train_scaled = scaler.fit_transform(X_train.reshape(-1, F)).reshape(X_train.shape)
    X_val_scaled   = scaler.transform(  X_val.reshape(-1, F)).reshape(X_val.shape)
    
    print(f"[TRAIN] {ticker}: scaler fitted on {X_train.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_train has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    sector_feature_indices = [feature_cols.index('sector_ret_1d'),
                          feature_cols.index('sector_ret_5d'),
                          feature_cols.index('sector_vol_20d')]

    print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")

    # Keras fit used the scaled data
    train_ds = SequenceDataset(X_train_scaled, y_train)
    val_ds   = SequenceDataset(X_val_scaled,   y_val)

    train_bs = min(32, len(train_ds))
    if train_bs < 2:
        print(f"[TRAIN] {ticker}: too few samples for BatchNorm (train size={len(train_ds)})")
        return False, sequence_length
    if len(train_ds) % train_bs == 1 and train_bs > 2:
        train_bs -= 1  # avoid batch size 1 for BatchNorm
    val_bs = min(32, len(val_ds))

    train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=True, drop_last=False)
    val_loader   = DataLoader(val_ds,   batch_size=val_bs, shuffle=False, drop_last=False)

    n_features = X_train.shape[-1]
    model = LSTMClassifier(n_features=n_features, dropout=0.3, inter_dropout=0.1).to(device)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)  # clipnorm via grad clipping below
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)
    early = EarlyStopper(patience=15, mode='min')

    for epoch in range(100):
        model.train()
        total_loss = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # clipnorm=1.0
            optimizer.step()
            total_loss += loss.item() * xb.size(0)

        train_loss = total_loss / len(train_loader.dataset)
        val_loss, _ = _evaluate(model, val_loader, device, loss_fn)

        scheduler.step(val_loss)  # ReduceLROnPlateau on val_loss

        # EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:  # stop after 'patience' non-improve epochs
            break

    # restore best weights
    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    # final validation pass for isotonic calibration (on scaled val data)
    _, validation_predictions = _evaluate(model, val_loader, device, loss_fn)

    # Keras code used 10% buffer (comment said 5%)
    pred_min, pred_max = validation_predictions.min(), validation_predictions.max()
    buffer = 0.05 * (pred_max - pred_min)
    y_min_dynamic = max(0.0, pred_min - buffer)
    y_max_dynamic = min(1.0, pred_max + buffer)

    calibrator = IsotonicRegression(y_min=y_min_dynamic, y_max=y_max_dynamic, out_of_bounds='clip')
    calibrator.fit(validation_predictions, y_val.astype(float))

    # inside train_company_models(..., H=H)
    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt"))
    joblib.dump(calibrator,      os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
    joblib.dump(scaler,          os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


    del model, scaler, calibrator, train_loader, val_loader, train_ds, val_ds
    del X_train, X_val, y_train, y_val, X_train_scaled, X_val_scaled
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [21]:
def predict_next_horizon(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 H: int) -> dict | None:

    try:
        # load artifacts
        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt")
        calibrator = joblib.load(os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
        scaler     = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        sequence_length    = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


        if not os.path.isfile(state_dict_path):
            return None
        
        if hasattr(scaler, "n_features_in_") and scaler.n_features_in_ != len(feature_cols):
            return None

        # build model skeleton with correct input dim, then load weights
        n_features = len(feature_cols)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        model = LSTMClassifier(n_features=n_features).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    # find the last contiguous block and take the most recent sequence_length rows
    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        return None

    last_start, last_end = contiguous_periods[-1]
    period_data = company_data_df.iloc[last_start:last_end + 1]
    if len(period_data) < sequence_length:
        return None

    last_sequence = period_data.tail(sequence_length)

    # scale using the saved scaler (fit  train only)
    # ensure column order matches training
    try:
        scaled_features = scaler.transform(last_sequence[feature_cols])
    except Exception:
        return None

    # shape: (1, T, F) as float32 tensor
    x = torch.from_numpy(np.asarray([scaled_features], dtype=np.float32)).to(device)

    with torch.no_grad():
        logits = model(x)                  # shape (1,)
        prob = torch.sigmoid(logits).item()  # scalar in [0,1]

    # isotonic calibration (expects iterable)
    calibrated = float(calibrator.predict([prob])[0])

    print(f"Raw prediction for {ticker}: {prob}")
    print(f"Calibrated prediction for {ticker}: {calibrated}")

    return {
        'ticker': ticker,
        'raw_prediction': prob,
        'calibrated_prediction': calibrated
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [22]:
def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                            total_capital: float, sector_threshold: float,
                            kelly_fraction: float, top_k: int = 3, softmax_alpha: float = 1) -> pd.DataFrame:

    investment_decisions = []

    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")

    # sector-level filter
    df = daily_predictions_df.copy()
    df = df.groupby('sector').filter(lambda g: g['calibrated_prediction'].mean() >= sector_threshold)
    if df.empty:
        print("[PORT] No sectors cleared confidence threshold.")
        return pd.DataFrame()

    candidates = []
    for _, row in df.iterrows():
        ticker = row['ticker']
        p = float(row['calibrated_prediction'])
        b_info = payout_map.get(ticker, 0.0)
        b = (b_info['b'] if isinstance(b_info, dict) else float(b_info))
        if not np.isfinite(b) or b <= 0:
            continue
        if not b_info or not np.isfinite(b_info.get('b', np.nan)):
            continue
        b = max(b_info['b'], 1e-6)  # avoid div-by-zero
        kelly_percentage = p - (1 - p) / b
        if kelly_percentage <= 0:
            continue
        investment_fraction = kelly_percentage * kelly_fraction
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            continue

        avg_win = b_info.get('avg_win', np.nan) if isinstance(b_info, dict) else np.nan
        avg_loss = b_info.get('avg_loss_abs', np.nan) if isinstance(b_info, dict) else np.nan
        if np.isfinite(avg_win) and np.isfinite(avg_loss):
            expected_rise = p * avg_win - (1.0 - p) * avg_loss
        else:
            expected_rise = p

        cand = row.to_dict()
        cand.update({
            'kelly_percentage': kelly_percentage,
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount,
            'expected_rise': expected_rise,
            'prob_up': p,
        })
        candidates.append(cand)

    if not candidates:
        print("[PORT] All candidates rejected after sizing/filters.")
        return pd.DataFrame()

    cand_df = pd.DataFrame(candidates)

    rows = []
    alpha = max(softmax_alpha, 1e-6)
    for sector, group in cand_df.groupby('sector'):
        if group.empty:
            continue
        top_group = group.sort_values('calibrated_prediction', ascending=False).head(max(1, top_k))
        logits = top_group['calibrated_prediction'].to_numpy() * 100.0 * alpha
        logits = logits - logits.max()  # stabilize
        weights = np.exp(logits)
        probs = weights / weights.sum()
        choice_idx = np.random.choice(len(top_group), p=probs)
        choice = top_group.iloc[choice_idx]

        print(f"[PORT] Sector {sector}: sampled {choice['ticker']} from top-{len(top_group)} (p={choice['calibrated_prediction']:.3f})")

        rows.append({
            'ticker': choice['ticker'],
            'sector': choice.get('sector', sector),
            'expected_rise': choice.get('expected_rise', np.nan),
            'prob_up': choice.get('prob_up', np.nan),
            'investment_fraction': choice['investment_fraction'],
            'investment_amount': choice['investment_amount'],
            'predicted_prob': choice['calibrated_prediction']
        })

    if not rows:
        print("[PORT] All sector winners rejected after sampling.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [23]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    files = [
        f"{ticker}_lstm_H{H}.pt",
        f"{ticker}_calibrator_H{H}.pkl",
        f"{ticker}_scaler_H{H}.pkl",
        f"{ticker}_seq_length_H{H}.pkl",
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in files)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [24]:
def _project_to_simplex(v):
    v = np.asarray(v, dtype=np.float64)
    if v.size == 0:
        return v
    if np.all(v >= 0) and np.isclose(v.sum(), 1.0):
        return v
    u = np.sort(v)[::-1]
    cssv = np.cumsum(u) - 1.0
    ind = np.arange(1, len(v) + 1)
    cond = u - cssv / ind > 0
    if not np.any(cond):
        return np.ones_like(v) / len(v)
    rho = ind[cond][-1]
    theta = cssv[cond][-1] / rho
    w = np.maximum(v - theta, 0.0)
    return w


def _apply_max_weight_cap(w, max_w, tol=1e-8):
    if max_w is None:
        return w
    w = np.maximum(w, 0.0)
    if w.size == 0:
        return w
    cap = float(max_w)
    w = np.minimum(w, cap)
    total = w.sum()
    if total <= 0:
        return w
    if total > 1.0 + tol:
        w = _project_to_simplex(w)
        w = np.minimum(w, cap)
    if total < 1.0 - tol:
        remaining = 1.0 - w.sum()
        for _ in range(100):
            room = cap - w
            room[room < 0] = 0.0
            if room.sum() <= tol:
                break
            add = remaining * (room / room.sum())
            w += add
            remaining = 1.0 - w.sum()
            if abs(remaining) <= tol:
                break
    if w.sum() > 0:
        w = w / w.sum()
    return w


def compute_mpt_weights(mu, Sigma, risk_lambda=1.0, long_only=True,
                        ridge_eps=1e-4, max_weight=None,
                        use_equal_fallback=True):
    mu = np.asarray(mu, dtype=np.float64)
    n = mu.size
    if n == 0:
        return mu
    if Sigma is None:
        return np.ones(n) / n if use_equal_fallback else mu / np.maximum(mu.sum(), 1e-12)
    Sigma = np.asarray(Sigma, dtype=np.float64)
    if Sigma.shape != (n, n):
        return np.ones(n) / n if use_equal_fallback else mu / np.maximum(mu.sum(), 1e-12)

    Sigma_reg = Sigma + ridge_eps * np.eye(n)

    def _fallback():
        w = np.ones(n) / n if use_equal_fallback else np.maximum(mu, 0.0)
        w = w / np.maximum(w.sum(), 1e-12)
        return _apply_max_weight_cap(w, max_weight)

    try:
        try:
            import scipy.optimize as opt
            def obj(w):
                return -(mu @ w - risk_lambda * (w @ Sigma_reg @ w))
            cons = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1.0},)
            bounds = None
            if long_only:
                upper = max_weight if max_weight is not None else 1.0
                bounds = [(0.0, upper) for _ in range(n)]
            x0 = np.ones(n) / n
            res = opt.minimize(obj, x0, method='SLSQP', bounds=bounds, constraints=cons)
            if not res.success or not np.isfinite(res.x).all():
                raise ValueError('MPT optimization failed')
            w = res.x
        except Exception:
            inv = np.linalg.pinv(Sigma_reg)
            w = inv @ mu
            if long_only:
                w = np.maximum(w, 0.0)
            if w.sum() <= 0:
                return _fallback()
            w = w / w.sum()
        if long_only:
            w = _apply_max_weight_cap(w, max_weight)
        if not np.isfinite(w).all() or w.sum() <= 0:
            return _fallback()
        return w
    except Exception:
        return _fallback()


def build_covariance_matrix(master_df, tickers, end_date, window_days, min_obs=20):
    df = master_df[master_df['date'] < end_date].copy()
    if df.empty:
        return None, []
    df = df[df['ticker'].isin(tickers)].copy()
    if df.empty:
        return None, []
    df['date'] = pd.to_datetime(df['date'])
    unique_dates = sorted(df['date'].unique())
    if not unique_dates:
        return None, []
    if len(unique_dates) > window_days:
        unique_dates = unique_dates[-window_days:]
    df = df[df['date'].isin(unique_dates)]
    pivot = df.pivot_table(index='date', columns='ticker', values='close', aggfunc='last').sort_index()
    rets = pivot.pct_change().dropna(how='all')
    if rets.empty:
        return None, []
    min_obs = max(5, min_obs)
    good_cols = [c for c in rets.columns if rets[c].count() >= min_obs]
    rets = rets[good_cols]
    if rets.shape[0] < min_obs or rets.shape[1] == 0:
        return None, []
    Sigma = rets.cov().values
    return Sigma, list(rets.columns)

In [ ]:
def compute_mpt_weights_for_today(
    tickers,
    historical_data,
    current_date,
    mu,
    window_days=MPT_WINDOW_DAYS,
    ridge_eps=MPT_RIDGE_EPS,
    risk_aversion=MPT_LAMBDA,
    long_only=MPT_LONG_ONLY,
    max_weight=MPT_MAX_WEIGHT,
    use_equal_fallback=MPT_USE_EQUAL_FALLBACK,
):
    if len(tickers) == 0:
        return np.array([]), True

    Sigma, cov_tickers = build_covariance_matrix(
        historical_data,
        tickers,
        current_date,
        window_days=window_days,
        min_obs=20,
    )
    if Sigma is None or set(cov_tickers) != set(tickers):
        w = np.ones(len(tickers)) / len(tickers)
        return w, True

    order = [cov_tickers.index(t) for t in tickers]
    Sigma = Sigma[np.ix_(order, order)]

    w = compute_mpt_weights(
        mu,
        Sigma,
        risk_lambda=risk_aversion,
        long_only=long_only,
        ridge_eps=ridge_eps,
        max_weight=max_weight,
        use_equal_fallback=use_equal_fallback,
    )
    if not np.isfinite(w).all() or w.sum() <= 0:
        w = np.ones(len(tickers)) / len(tickers)
        return w, True
    return w, False


def apply_allocation_mode(
    investment_df,
    historical_data,
    current_date,
    capital,
    open_positions,
    allocation_mode=ALLOCATION_MODE,
):
    meta = {
        'allocation_mode': allocation_mode,
        'budget_pre_caps': 0.0,
        'mpt_used': False,
        'mpt_fallback_used': False,
        'weights': None,
    }

    if investment_df is None or investment_df.empty:
        return investment_df, meta

    mode = str(allocation_mode).upper().strip()
    if mode not in {"KELLY_ONLY", "HYBRID_KELLY_MPT", "MPT_ONLY"}:
        mode = "KELLY_ONLY"
        meta['allocation_mode'] = mode

    budget_pre_caps = float(investment_df['investment_amount'].sum())
    tickers = investment_df['ticker'].tolist()

    if mode == "KELLY_ONLY":
        meta['budget_pre_caps'] = budget_pre_caps
        return investment_df, meta

    if mode == "MPT_ONLY":
        equity = float(capital + sum(p['invest'] for p in open_positions))
        budget_pre_caps = float(MPT_ONLY_BUDGET_FRACTION * equity)

    meta['budget_pre_caps'] = budget_pre_caps

    if len(tickers) == 1:
        if mode == "MPT_ONLY":
            meta['mpt_used'] = True
            meta['weights'] = {tickers[0]: 1.0}
            investment_df = investment_df.copy()
            investment_df['investment_amount'] = budget_pre_caps
        return investment_df, meta

    mu = investment_df['expected_rise'].astype(float).values
    mu = np.nan_to_num(mu, nan=0.0, posinf=0.0, neginf=0.0)

    w, fallback = compute_mpt_weights_for_today(
        tickers,
        historical_data,
        current_date,
        mu,
    )
    meta['mpt_used'] = True
    meta['mpt_fallback_used'] = bool(fallback)

    if np.isfinite(w).all() and w.sum() > 0:
        w = w / w.sum()
        meta['weights'] = {t: float(w[i]) for i, t in enumerate(tickers)}
        investment_df = investment_df.copy()
        investment_df['investment_amount'] = budget_pre_caps * w
        return investment_df, meta

    return investment_df, meta

In [25]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # returns used for settlement only; not for training
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker','date'])[ret_col].to_dict()
    close_lookup = master_df.set_index(['ticker', 'date'])['close'].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    early_exit_lookup = None
    early_exit_threshold = 0.4  # exit when p_up_1d < threshold (downside signal)
    if H > 1:
        early_exit_path = 'stocknet-dataset/h1_early_exit_df.parquet'
        if not os.path.exists(early_exit_path):
            early_exit_path = 'stocknet-dataset/h1_exit_df.parquet'
        if os.path.exists(early_exit_path):
            try:
                h1_exit_df = pd.read_parquet(early_exit_path)
                h1_exit_df['date'] = pd.to_datetime(h1_exit_df['date'])
                h1_exit_df = h1_exit_df.drop_duplicates(subset=['date', 'ticker'])
                early_exit_lookup = h1_exit_df.set_index(['date', 'ticker'])['p_up_1d'].to_dict()
                print(f"[EARLY EXIT] Loaded {len(h1_exit_df)} signals from {early_exit_path}")
            except Exception as exc:
                print(f"[EARLY EXIT] Failed to load signals: {exc}")
                early_exit_lookup = None
        else:
            print("[EARLY EXIT] No 1d exit signal file found; early exit disabled.")

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    open_positions = []
    prev_equity_end = capital
    total_early_exits = 0
    early_exit_pnl_total = 0.0
    early_exit_counterfactual_total = 0.0
    early_exit_counterfactual_count = 0

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = pd.to_datetime(unique_dates[i])
        prev_date = pd.to_datetime(unique_dates[i-1]) if i > 0 else None
        early_exits_today = 0
        exits_today = []

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                entry_close = close_lookup.get((pos['ticker'], pos['entry_date']))
                exit_close = close_lookup.get((pos['ticker'], current_date))
                r_exit = np.nan
                if entry_close is not None and exit_close is not None and np.isfinite(entry_close) and np.isfinite(exit_close):
                    r_exit = (exit_close / entry_close) - 1.0
                elif pd.notna(rH):
                    r_exit = rH
                if pd.notna(r_exit):
                    pnl = pos['invest'] * r_exit
                    total_pnl_today += pnl
                    capital += pos['invest'] + pnl
                    exits_today.append({
                        'date': pos['entry_date'],
                        'exit_date': current_date,
                        'ticker': pos['ticker'],
                        'sector': pos.get('sector', sectors_by_ticker.get(pos['ticker'], 'UNKNOWN')),
                        'allocated_amount': pos['invest'],
                        'prob_up': pos.get('prob_up', np.nan),
                        'expected_rise': pos.get('expected_rise', np.nan),
                        'actual_return': r_exit,
                        'pnl': pnl,
                        'exit_reason': 'scheduled',
                    })
            else:
                still_open.append(pos)
        open_positions = still_open

        # early-exit check (signal at current_date predicts tomorrow)
        if H > 1 and early_exit_lookup:
            remaining = []
            for pos in open_positions:
                p_up_1d = early_exit_lookup.get((current_date, pos['ticker']))
                if p_up_1d is None or not np.isfinite(p_up_1d):
                    remaining.append(pos)
                    continue
                if float(p_up_1d) < early_exit_threshold:
                    entry_close = close_lookup.get((pos['ticker'], pos['entry_date']))
                    exit_close = close_lookup.get((pos['ticker'], current_date))
                    if entry_close is None or exit_close is None:
                        remaining.append(pos)
                        continue
                    if not np.isfinite(entry_close) or not np.isfinite(exit_close):
                        remaining.append(pos)
                        continue
                    r_exit = (exit_close / entry_close) - 1.0
                    pnl = pos['invest'] * r_exit
                    total_pnl_today += pnl
                    capital += pos['invest'] + pnl
                    early_exits_today += 1
                    total_early_exits += 1
                    early_exit_pnl_total += pnl

                    planned_rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                    if pd.notna(planned_rH):
                        early_exit_counterfactual_total += pos['invest'] * planned_rH
                        early_exit_counterfactual_count += 1

                    exits_today.append({
                        'date': pos['entry_date'],
                        'exit_date': current_date,
                        'ticker': pos['ticker'],
                        'sector': pos.get('sector', sectors_by_ticker.get(pos['ticker'], 'UNKNOWN')),
                        'allocated_amount': pos['invest'],
                        'prob_up': pos.get('prob_up', np.nan),
                        'expected_rise': pos.get('expected_rise', np.nan),
                        'actual_return': r_exit,
                        'pnl': pnl,
                        'exit_reason': 'early_exit',
                    })

                    print(
                        f"[EARLY EXIT] {current_date}: {pos['ticker']} p_up_1d={p_up_1d:.3f} -> exit; "
                        f"r={r_exit:.4f}, PnL=${pnl:.2f}"
                    )
                else:
                    remaining.append(pos)
            open_positions = remaining

        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # historical slice strictly before current_date; recompute targets locally
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        cutoff = current_date - pd.Timedelta(days=H)
        historical_data = historical_data[historical_data['date'] < cutoff]
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if prev_date is None:
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == prev_date]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if not have_models or need_retrain:
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)

        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df, payout_map_day, capital, SECTOR_CONFIDENCE_THRESHOLD, KELLY_FRACTION
        )

        investment_decision_df, alloc_meta = apply_allocation_mode(
            investment_decision_df,
            historical_data,
            current_date,
            capital,
            open_positions,
            allocation_mode=ALLOCATION_MODE,
        )

        exit_idx = i + H
        exit_date = pd.to_datetime(unique_dates[exit_idx]) if exit_idx < len(unique_dates) else None

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)

            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0
            budget_post_caps = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue

                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))

                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                capital -= amt
                total_open += amt
                new_today_open += amt
                budget_post_caps += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {
                    'ticker': tkr,
                    'invest': amt,
                    'entry_date': current_date,
                    'exit_date': exit_date,
                    'sector': sec,
                    'prob_up': float(trade.get('prob_up', trade.get('predicted_prob', np.nan))),
                    'expected_rise': float(trade.get('expected_rise', np.nan)),
                }
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})

        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,
            'capital_end': capital,
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,
            'daily_return': daily_return,
            'early_exits_today': early_exits_today,
            'allocation_mode': alloc_meta['allocation_mode'],
            'budget_pre_caps': float(alloc_meta['budget_pre_caps']),
            'budget_post_caps': float(budget_post_caps) if 'budget_post_caps' in locals() else 0.0,
            'mpt_used': bool(alloc_meta['mpt_used']),
            'mpt_fallback_used': bool(alloc_meta['mpt_fallback_used']),
            'mpt_weights': alloc_meta.get('weights'),
            'exits_today': exits_today,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    print(f"[EARLY EXIT] Total early exits: {total_early_exits}")
    if total_early_exits > 0:
        print(f"[EARLY EXIT] PnL realized from early exits: ${early_exit_pnl_total:,.2f}")
        if early_exit_counterfactual_count > 0:
            print(
                f"[EARLY EXIT] PnL if held to horizon: ${early_exit_counterfactual_total:,.2f} "
                f"(n={early_exit_counterfactual_count})"
            )
            print(
                f"[EARLY EXIT] Delta vs hold-to-horizon: "
                f"${early_exit_pnl_total - early_exit_counterfactual_total:,.2f}"
            )
        else:
            print("[EARLY EXIT] Counterfactual PnL unavailable for early exits.")
    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [26]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [27]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_and_bimeta_features.parquet')

In [28]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)
# Exclude ticker with missing meta-features across all rows
master_df = master_df[master_df['ticker'] != 'GMRE']

columns_to_check = ['EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower',
    
    'lstm_prob_up_1d', 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [29]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    # 'lstm_prob_up_1d', 
    # 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    # 'gru_pred_ret_1d', 
    # 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength']
Total number of features: 28

In [30]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [31]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=5,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Starting simulation with 783 initial training days... (H=5)
[EARLY EXIT] Loaded 8613 signals from stocknet-dataset/h1_exit_df.parquet
Starting predictions from day 783 (after 783 training days)

Simulating Trading Days:   0%|          | 0/100 [00:00<?, ?it/s]

Raw prediction for AAPL: 0.5011709928512573
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.4897612929344177
Calibrated prediction for ABB: 0.5138888955116272
Raw prediction for ABBV: 0.5034603476524353
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49120187759399414
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.7661342620849609
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.47884663939476013
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5334091186523438
Calibrated prediction for AMZN: 0.5335751175880432
Raw prediction for BA: 0.3096003830432892
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5383180975914001
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44556117057800293
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4981757402420044
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4881763756275177
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.505877673625946
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5551674365997314
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4713161885738373
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46966028213500977
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.577431321144104
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5390297770500183
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48374319076538086
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5705918073654175
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49331751465797424
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5225189924240112
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.5221790075302124
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.44459474086761475
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.6487925052642822
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4650692343711853
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4788721203804016
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5222352743148804
Calibrated prediction for DHR: 0.5184097290039062
Raw prediction for DIS: 0.4581899642944336
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5328972339630127
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4519823491573334
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5257323384284973
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4700952470302582
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4684792459011078
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5537706017494202
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5153746008872986
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5437225699424744
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5090465545654297
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5051431059837341
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.48028281331062317
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.3992939889431
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5113264918327332
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4817360043525696
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4877910017967224
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4913826286792755
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.41941237449645996
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5706874132156372
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.16486720740795135
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48585790395736694
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2906564176082611
Calibrated prediction for MO: 0.5535454750061035
Raw prediction for MRK: 0.47736895084381104
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6120395660400391
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5147983431816101
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5541349053382874
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.40513911843299866
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3154163658618927
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5240492820739746
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5273128151893616
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4607389569282532
Calibrated prediction for PEP: 0.5061016082763672
Raw prediction for PFE: 0.49058297276496887
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.42869138717651367
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4919939935207367
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5140641331672668
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5896791219711304
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5082512497901917
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46234130859375
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.4732082486152649
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6102579236030579
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5406565070152283
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4988288879394531
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.463815301656723
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4819065034389496
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.47457659244537354
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6546921133995056
Calibrated prediction for T: 0.6666666865348816
Raw prediction for TM: 0.4867282807826996
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5050888061523438
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5131297707557678
Calibrated prediction for TSM: 0.5204885601997375

Simulating Trading Days:   1%|          | 1/100 [00:01<02:21,  1.43s/it]

Raw prediction for UL: 0.48231345415115356
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6912049651145935
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.5376741886138916
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48898202180862427
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.44547832012176514
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5168054103851318
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.565706193447113
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5045995712280273
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.5028073191642761
Calibrated prediction for WMT: 0.5194805264472961
Raw prediction for XOM: 0.6704583764076233
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.500739336013794
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.4904598891735077
Calibrated prediction for ABB: 0.5138888955116272
Raw prediction for ABBV: 0.5024609565734863
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4904932677745819
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8134698271751404
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.48020872473716736
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5341697335243225
Calibrated prediction for AMZN: 0.5335751175880432
Raw prediction for BA: 0.3120920658111572
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5359100103378296
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4450259804725647
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4983605444431305
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4878205358982086
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5064284801483154
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5576056838035583
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47193729877471924
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46993565559387207
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5761439204216003
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5394600033760071
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4838615357875824
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5599027872085571
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49428898096084595
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5215437412261963
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.522225022315979
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.456533819437027
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.6628756523132324
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46430736780166626
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4666246175765991
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5222972631454468
Calibrated prediction for DHR: 0.5184097290039062
Raw prediction for DIS: 0.4582980275154114
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5330665111541748
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4496191740036011
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5258051156997681
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.46211928129196167
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4800145626068115
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5517967343330383
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5145713090896606
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5442872047424316
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5083831548690796
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.503667950630188
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.47270554304122925
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.40777841210365295
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5117768049240112
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.47993218898773193
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48735082149505615
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49158552289009094
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4253845810890198
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5634855031967163
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1673569232225418
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48552507162094116
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.30015310645103455
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4774724841117859
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.612069308757782
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.513827919960022
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5522761940956116
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.412540078163147
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3127612769603729
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5247471928596497
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5277001261711121
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46762385964393616
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.48986127972602844
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4325063228607178
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49206840991973877
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5141640901565552
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6393073797225952
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5089830756187439
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4627515375614166
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.46980127692222595
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6072733998298645
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5391384959220886
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49893438816070557
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4638074040412903
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48134636878967285
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4627735912799835
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6579204201698303
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4870469272136688
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5049086809158325
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5126208662986755
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.49405136704444885
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6547974944114685
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.5193518400192261
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48891010880470276
Calibrated prediction for UPS: 0.488449364900589
Raw prediction for UTX: 0.44705623388290405
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5164681673049927
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5633907914161682
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5045738220214844
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.49938955903053284
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6652703285217285
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:   2%|▏         | 2/100 [00:02<02:03,  1.26s/it]

Raw prediction for AAPL: 0.5002825260162354
Calibrated prediction for AAPL: 0.5272117853164673
Raw prediction for ABB: 0.49791043996810913
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5014636516571045
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48991185426712036
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8325394988059998
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4823702573776245
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.535442054271698
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.31900298595428467
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5320401191711426
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44446247816085815
Calibrated prediction for BAC: 0.4537438750267029
Raw prediction for BBL: 0.49848422408103943
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4877888262271881
Calibrated prediction for BCH: 0.5055257081985474
Raw prediction for BHP: 0.5064874291419983
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5639113187789917
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.472577303647995
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.47037819027900696
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5741175413131714
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5397805571556091
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48401784896850586
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5620294213294983
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4956604540348053
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5221457481384277
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.522244930267334
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.4694038927555084
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.6740214824676514
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.463477224111557
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4497949182987213
Calibrated prediction for D: 0.5384615659713745
Raw prediction for DHR: 0.5224315524101257
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4583255648612976
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5332131385803223
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4486393332481384
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5259848237037659
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4693520963191986
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4916954040527344
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.555006742477417
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5141000151634216
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5460528135299683
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5082241296768188
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5041180849075317
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4649340510368347
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.41818663477897644
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5122711658477783
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.48085781931877136
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48705554008483887
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4917739927768707
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4349493086338043
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5638174414634705
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1747017204761505
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.485382080078125
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3099484443664551
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47754767537117004
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6108413338661194
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5133082270622253
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5498422980308533
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.4292333126068115
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3115292191505432
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5222651958465576
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5281280875205994
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4743908643722534
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.48849090933799744
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4199957251548767
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49227187037467957
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5143598914146423
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.664878249168396
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5099039673805237
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46346136927604675
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.46495321393013
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6085243821144104
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.533129870891571
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4991762638092041
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4641275107860565
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4806598424911499
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.45557695627212524
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6597896814346313
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4874174892902374
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5050175786018372
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.512037992477417
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4999542236328125
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6126728653907776
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4932895004749298
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4889850616455078
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4452168643474579
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5163232088088989
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.56297767162323
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5047184228897095
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.49558717012405396
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6618368029594421
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:   3%|▎         | 3/100 [00:03<01:56,  1.20s/it]

Raw prediction for AAPL: 0.5000012516975403
Calibrated prediction for AAPL: 0.503137469291687
Raw prediction for ABB: 0.5032824873924255
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5005912780761719
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48957574367523193
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8860569596290588
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4846201539039612
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5381953716278076
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3266761600971222
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5277572870254517
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4444692134857178
Calibrated prediction for BAC: 0.4545596241950989
Raw prediction for BBL: 0.49846023321151733
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48759332299232483
Calibrated prediction for BCH: 0.499236136674881
Raw prediction for BHP: 0.5052650570869446
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5711745619773865
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4731876254081726
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.47056668996810913
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5719946622848511
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5402623414993286
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4842940866947174
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5633217096328735
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49741846323013306
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5245386362075806
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.5223127603530884
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.46685150265693665
Calibrated prediction for CODI: 0.4440469443798065
Raw prediction for CSCO: 0.684745728969574
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4627280533313751
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43348783254623413
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.522704005241394
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4582898020744324
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5333037376403809
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4497576355934143
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5262585282325745
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4745193421840668
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.500054121017456
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5598286390304565
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5141974091529846
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5472740530967712
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5088217258453369
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5047464370727539
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4853479266166687
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.435709148645401
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.512676477432251
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.48209714889526367
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48673945665359497
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4920091927051544
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4726540744304657
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5663307905197144
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.18015718460083008
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4852118194103241
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.322659432888031
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4780663847923279
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6097432374954224
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.513222336769104
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5469779372215271
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.4449561536312103
Calibrated prediction for NVS: 0.4583333432674408
Raw prediction for ORCL: 0.3146044611930847
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5189105868339539
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.528471052646637
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4795082211494446
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4893590211868286
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4132658839225769
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4925306737422943
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5146417021751404
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6726820468902588
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5105488300323486
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4637162387371063
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4583050310611725
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6086440682411194
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5306289792060852
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4994596242904663
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46451184153556824
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4801875650882721
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.44715383648872375
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6604164242744446
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4877498149871826
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5048615336418152
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5113965272903442
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.501028835773468
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.561649739742279
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.46964746713638306
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48912665247917175
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4349202513694763
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5163548588752747
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5650545954704285
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5046133399009705
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.49226540327072144
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6553316116333008
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:   4%|▍         | 4/100 [00:04<01:52,  1.17s/it]

Raw prediction for AAPL: 0.5000951886177063
Calibrated prediction for AAPL: 0.5111775398254395
Raw prediction for ABB: 0.5086352825164795
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5001295804977417
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48930034041404724
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8663860559463501
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4849699139595032
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5404248237609863
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.33127695322036743
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5257140398025513
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4444810748100281
Calibrated prediction for BAC: 0.45599618554115295
Raw prediction for BBL: 0.49817952513694763
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4874267876148224
Calibrated prediction for BCH: 0.4938123822212219
Raw prediction for BHP: 0.5036529898643494
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5765070915222168
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47404396533966064
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4706803262233734
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5704129338264465
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.540679931640625
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4844173192977905
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5345937609672546
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5011051297187805
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5294885635375977
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.5222592353820801
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.47787824273109436
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.6906947493553162
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46223971247673035
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.42304727435112
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5232119560241699
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4581528306007385
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5333937406539917
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.45493951439857483
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5266037583351135
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4581158459186554
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5058995485305786
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5651475191116333
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5150353908538818
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5459142327308655
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5083478093147278
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5063428282737732
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4892929196357727
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.45849481225013733
Calibrated prediction for INTC: 0.5185185074806213
Raw prediction for JNJ: 0.5130394697189331
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4834841787815094
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4864708483219147
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49143800139427185
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4935741126537323
Calibrated prediction for MA: 0.5762563347816467
Raw prediction for MCD: 0.5695180296897888
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1862775981426239
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48491182923316956
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3331712484359741
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4786900281906128
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6065190434455872
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.513407289981842
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5443602204322815
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.45934852957725525
Calibrated prediction for NVS: 0.4583333432674408
Raw prediction for ORCL: 0.31574445962905884
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5191338062286377
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5287633538246155
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48302987217903137
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4890006184577942
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4051387310028076
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49275511503219604
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5148153305053711
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6777892112731934
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5107367038726807
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4636184275150299
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.45285460352897644
Calibrated prediction for REX: 0.6000000238418579
Raw prediction for SLB: 0.6083157062530518
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5233445763587952
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5000688433647156
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46500736474990845
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4797249734401703
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4401690661907196
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6612802743911743
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4880143105983734
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5046209692955017
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5108797550201416
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.49755552411079407
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5008987784385681
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4411925673484802
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4893244206905365
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.41882503032684326
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5163149237632751
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5669382214546204
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5044814348220825
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4901424050331116
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.645356297492981
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:   5%|▌         | 5/100 [00:05<01:49,  1.15s/it]

Raw prediction for AAPL: 0.5006498098373413
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5140183568000793
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49952706694602966
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48899513483047485
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8550636768341064
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.48497384786605835
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5417131781578064
Calibrated prediction for AMZN: 0.5590608716011047
Raw prediction for BA: 0.33741721510887146
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5250200629234314
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44461876153945923
Calibrated prediction for BAC: 0.4726719856262207
Raw prediction for BBL: 0.4975678026676178
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48718541860580444
Calibrated prediction for BCH: 0.4859514832496643
Raw prediction for BHP: 0.501376211643219
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5742821097373962
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4752345383167267
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4702357053756714
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5685970783233643
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5410876274108887
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48456549644470215
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.47965359687805176
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5052480697631836
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5369828939437866
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.5222259163856506
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.48898202180862427
Calibrated prediction for CODI: 0.5
Raw prediction for CSCO: 0.6943802833557129
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4617835283279419
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.41403326392173767
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5239980816841125
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45791760087013245
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5335868000984192
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.46153900027275085
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5268491506576538
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.42582544684410095
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5111060738563538
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5696521997451782
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5172345638275146
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5420718789100647
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5074678659439087
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.506866991519928
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4889199435710907
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.4890909492969513
Calibrated prediction for INTC: 0.5333333611488342
Raw prediction for JNJ: 0.5133345127105713
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4842771291732788
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4861612915992737
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4911027252674103
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5040904879570007
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5706064701080322
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.19194409251213074
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4846866726875305
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.33935025334358215
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4793541729450226
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6015896201133728
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5133682489395142
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5408519506454468
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.4822731018066406
Calibrated prediction for NVS: 0.4583333432674408
Raw prediction for ORCL: 0.31853827834129333
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5215863585472107
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5289395451545715
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48220956325531006
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.49150487780570984
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.39773431420326233
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49293893575668335
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5149452090263367
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6845530271530151
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.510200023651123
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46307677030563354
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4481012523174286
Calibrated prediction for REX: 0.4444444477558136
Raw prediction for SLB: 0.6044391393661499
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5029590725898743
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.500866711139679
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46560969948768616
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4795475900173187
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.43341994285583496
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6636788845062256
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.48812028765678406
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5036869645118713
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5104387998580933
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4912909269332886
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.44948455691337585
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4167889654636383
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4895758032798767
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4007493853569031
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5163454413414001
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5692505240440369
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5042711496353149
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4886600375175476
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6403325200080872
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:   6%|▌         | 6/100 [00:07<01:47,  1.15s/it]

Raw prediction for AAPL: 0.5014623999595642
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5165768265724182
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4986547827720642
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48848724365234375
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8487579226493835
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4834882915019989
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5417414307594299
Calibrated prediction for AMZN: 0.5608077645301819
Raw prediction for BA: 0.3408765494823456
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5251799821853638
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44521844387054443
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49711382389068604
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4872869551181793
Calibrated prediction for BCH: 0.4892583191394806
Raw prediction for BHP: 0.49844297766685486
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5737435817718506
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4765498638153076
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46951180696487427
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5669640302658081
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5414620637893677
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48469483852386475
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4287359416484833
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5099162459373474
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.546360433101654
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.5221195220947266
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.49556440114974976
Calibrated prediction for CODI: 0.5629571676254272
Raw prediction for CSCO: 0.6971969604492188
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46159854531288147
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4103974401950836
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5247406959533691
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45749175548553467
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5337465405464172
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4643326699733734
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5272456407546997
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3701319396495819
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5108785033226013
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5743862986564636
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5201764702796936
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5367680191993713
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5063790082931519
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.509128749370575
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.49273577332496643
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5234164595603943
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5136650800704956
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.48601314425468445
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48598918318748474
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49091818928718567
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.524067223072052
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5743618011474609
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.20017656683921814
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4844306707382202
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.34339413046836853
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48014479875564575
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5940120816230774
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5133001208305359
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5380523800849915
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.49215981364250183
Calibrated prediction for NVS: 0.48175621032714844
Raw prediction for ORCL: 0.32071271538734436
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.524247944355011
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5291270613670349
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4815129339694977
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.49619776010513306
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.39285168051719666
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4929758906364441
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5150532722473145
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6932193040847778
Calibrated prediction for PPL: 0.728076159954071
Raw prediction for PTR: 0.5095341801643372
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4625299572944641
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.44404295086860657
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.5997354984283447
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.48767897486686707
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.501487672328949
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46563416719436646
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.47955697774887085
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4286837875843048
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6685841083526611
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4881414771080017
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5033547282218933
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5102071762084961
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.48419061303138733
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.4181990623474121
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.3931899964809418
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48975861072540283
Calibrated prediction for UPS: 0.4929138123989105

Simulating Trading Days:   7%|▋         | 7/100 [00:08<01:48,  1.17s/it]

Raw prediction for UTX: 0.35666152834892273
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.516309380531311
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5703548192977905
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5042604804039001
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.48757460713386536
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6359355449676514
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.728)
Raw prediction for AAPL: 0.5023680329322815
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5202733278274536
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49796319007873535
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4880814552307129
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.8264301419258118
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.481577605009079
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5415105223655701
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3610897958278656
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5260463356971741
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44621697068214417
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49652010202407837
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48762544989585876
Calibrated prediction for BCH: 0.5
Raw prediction for BHP: 0.4963487684726715
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5598171949386597
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4780837595462799
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46871450543403625
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5648806095123291
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.541731059551239
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4846768081188202
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4065249264240265
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5135791897773743
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5525080561637878
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.5220195651054382
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.49757033586502075
Calibrated prediction for CODI: 0.6000000238418579
Raw prediction for CSCO: 0.7001399397850037
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4615480303764343
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4048141837120056
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.525291383266449
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45708855986595154
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5338780879974365
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4628848731517792
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5275969505310059
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3458400070667267
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5135598182678223
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5776562690734863
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5229883193969727
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5338402986526489
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5054312944412231
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5104280710220337
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.48426416516304016
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5446667075157166
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5139784216880798
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.48728469014167786
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48569774627685547
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4918791949748993
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5398661494255066
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5790833830833435
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.2075933814048767
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48425421118736267
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3473263084888458
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48081377148628235
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5816338062286377
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5130841135978699
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5344686508178711
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.4914605915546417
Calibrated prediction for NVS: 0.4725521504878998
Raw prediction for ORCL: 0.3197570741176605
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5258360505104065
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5293939113616943
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47578850388526917
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5032928586006165
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.3838290870189667
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49254611134529114
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.515099823474884
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6876238584518433
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.50920569896698
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46216830611228943
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.43974944949150085
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.5950556397438049
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.45901915431022644
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5016452074050903
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4653128385543823
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.47976014018058777
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.42839285731315613
Calibrated prediction for SRE: 0.4322940707206726

Simulating Trading Days:   8%|▊         | 8/100 [00:09<01:46,  1.16s/it]

Raw prediction for T: 0.6725584864616394
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4880562424659729
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5027491450309753
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5101336240768433
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.46978452801704407
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.40729382634162903
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.36552363634109497
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48985567688941956
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.34460315108299255
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5164718627929688
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.570059597492218
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5041660070419312
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.48669421672821045
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.635001003742218
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled AMZN from top-3 (p=0.558)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-04-24 00:00:00: MA p_up_1d=0.336 -> exit; r=0.0125, PnL=$48.40
Raw prediction for AAPL: 0.5033028721809387
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.526076078414917
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49740245938301086
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4876910448074341
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.8162015080451965
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4815615713596344
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5416609048843384
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3884861469268799
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5269209146499634
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44756582379341125
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4965290427207947
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4882102906703949
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.4957508444786072
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5514231324195862
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47917914390563965
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46832236647605896
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5641760230064392
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5417184829711914
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48456618189811707
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4458589553833008
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5163997411727905
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5566250681877136
Calibrated prediction for CHTR: 0.564765453338623
Raw prediction for CMCSA: 0.5219565629959106
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5125540494918823
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.7050015330314636
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46221300959587097
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.40304020047187805
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5255411267280579
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45684048533439636
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5339678525924683
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4611869156360626
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5279436707496643
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.33677151799201965
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5174456834793091
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5793513655662537
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5243009924888611
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5338196158409119
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5049523711204529
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5133305191993713
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4771581292152405
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5627947449684143
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5143085718154907
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.48919710516929626
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4856284558773041
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4935223162174225
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5622640252113342
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5819826722145081
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.2151358425617218
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4839487075805664
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.35574987530708313
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48148661851882935
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5682517290115356
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5132784843444824
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5320702791213989
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.4950771927833557
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.31988126039505005
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5271191000938416
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5297695398330688
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47048309445381165
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5106279253959656
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.37850600481033325
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4915712773799896
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5150957107543945
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6765302419662476
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5096438527107239
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46259403228759766
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4346911907196045
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.5919966101646423
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.44257810711860657
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5013597011566162
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46540170907974243
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48017647862434387
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.43568041920661926
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6745169162750244
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4879355728626251
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5036835074424744
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5101664662361145
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4604857563972473
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.43442943692207336
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.33934634923934937
Calibrated prediction for UNH: 0.3803180456161499
Raw prediction for UPS: 0.48991507291793823
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3726274371147156
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5165985822677612
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5711127519607544
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5041642785072327
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4861030876636505
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:   9%|▉         | 9/100 [00:10<01:45,  1.16s/it]

Raw prediction for XOM: 0.6245021224021912
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-04-25 00:00:00: MA p_up_1d=0.317 -> exit; r=0.0037, PnL=$12.07
Raw prediction for AAPL: 0.5043637156486511
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5264905691146851
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49704709649086
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48749497532844543
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.7996688485145569
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4821295142173767
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5420915484428406
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.40856224298477173
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5282925367355347
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4489777088165283
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4971023499965668
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48838213086128235
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.49740293622016907
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.544105589389801
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4798746407032013
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46803581714630127
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5630798935890198
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.541733980178833
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4844569265842438
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.49255281686782837
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5180580019950867
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5591745972633362
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5219489336013794
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5234314203262329
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.7080921530723572
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4634558856487274
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.39923447370529175
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5255621075630188
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45681634545326233
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5340137481689453
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.45977097749710083
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5279630422592163
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3273018002510071
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5147054195404053
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5780797004699707
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5243525505065918
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.534925103187561
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5054346323013306
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5122756361961365
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.47008275985717773
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5700896978378296
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5145012736320496
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4874749183654785
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4853777587413788
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49447983503341675
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5783672332763672
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.583980143070221
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.21708059310913086
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4836750030517578
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3662901818752289
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48245248198509216
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5562020540237427
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5136705636978149
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.529723048210144
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.49463820457458496
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.31511828303337097
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5270127654075623
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.530011773109436
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46451109647750854
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5134906768798828
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.35665103793144226
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.49026134610176086
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5149788856506348
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6487393975257874
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5101686120033264
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46321138739585876
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4286745488643646
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.5910272598266602
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.45660239458084106
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5005502700805664
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4658747613430023
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48070862889289856
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.44954466819763184
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6734309792518616
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.48799756169319153
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5053030252456665
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5103073120117188
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4480735957622528
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.45789635181427
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3277508616447449
Calibrated prediction for UNH: 0.3333333432674408
Raw prediction for UPS: 0.48992106318473816
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.41050592064857483
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5167736411094666
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.571489691734314
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.503741443157196
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.48575544357299805
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6128767728805542
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:  10%|█         | 10/100 [00:11<01:45,  1.17s/it]

[EARLY EXIT] 2017-04-26 00:00:00: MA p_up_1d=0.317 -> exit; r=0.0003, PnL=$1.07
Raw prediction for AAPL: 0.5050863027572632
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5362280011177063
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4964795708656311
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48738163709640503
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.8467130661010742
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4862598180770874
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5420351028442383
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4203239381313324
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5292327404022217
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4495903551578522
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49771252274513245
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48887258768081665
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5010216236114502
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5315234661102295
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.480083703994751
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4675486385822296
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5614479780197144
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5415781736373901
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4844420850276947
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5706049799919128
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5195013284683228
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5632011294364929
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5218956470489502
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5425022840499878
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.7077675461769104
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4650419056415558
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.3968811333179474
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5257017612457275
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45688962936401367
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5339993238449097
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.45782291889190674
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5278292894363403
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3270944356918335
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5012218952178955
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5774142742156982
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5243854522705078
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5356077551841736
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5070103406906128
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5126518607139587
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4744144678115845
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5596114993095398
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5147032141685486
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.48408326506614685
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48507440090179443
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49518007040023804
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5814362168312073
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5896180272102356
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.22542764246463776
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48331373929977417
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3808072507381439
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4833187460899353
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.550786554813385
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5146598815917969
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5292975902557373
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.5046349167823792
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.30941322445869446
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5261350870132446
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5300846695899963
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46020492911338806
Calibrated prediction for PEP: 0.5023519992828369
Raw prediction for PFE: 0.5111281275749207
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.35485899448394775
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4887125492095947
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5148266553878784
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6139422059059143
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5106965899467468
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4641866385936737
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.425192654132843
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.5941165089607239
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.47412991523742676
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5006234645843506
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4663391709327698
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4813121259212494
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4684641659259796
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.6734172701835632
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.48786622285842896
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5070093870162964
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5103815197944641
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.44070449471473694
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.49561962485313416
Calibrated prediction for UN: 0.5199999809265137

Simulating Trading Days:  11%|█         | 11/100 [00:12<01:43,  1.16s/it]

Raw prediction for UNH: 0.3275230824947357
Calibrated prediction for UNH: 0.3333333432674408
Raw prediction for UPS: 0.4898059666156769
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.44306638836860657
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.516819417476654
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5736494064331055
Calibrated prediction for VZ: 0.5573403835296631
Raw prediction for WFC: 0.50332111120224
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4852219223976135
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5901103615760803
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-04-27 00:00:00: MA p_up_1d=0.333 -> exit; r=0.0080, PnL=$33.42
Raw prediction for AAPL: 0.505620539188385
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5438929200172424
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4960678815841675
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48732590675354004
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.8952351808547974
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4895782470703125
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5414139032363892
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.41971883177757263
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5297184586524963
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4491441547870636
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49841514229774475
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4892154037952423
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5053617358207703
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.521892786026001
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.48065221309661865
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4674180746078491
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5613256096839905
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5411294102668762
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48442211747169495
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6224543452262878
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5206298828125
Calibrated prediction for CHL: 0.4796298146247864
Raw prediction for CHTR: 0.5649275183677673
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5218397974967957
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5682055950164795
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.7026887536048889
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46672961115837097
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4008745551109314
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5258668661117554
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4571978747844696
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5340597033500671
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4556964635848999
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5275405645370483
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3316740393638611
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4873192310333252
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5823214054107666
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5247417092323303
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5353977680206299
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5090060830116272
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.5145450234413147
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.485256165266037
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5269063115119934
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5148093104362488
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.47947943210601807
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4849221408367157
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4954576790332794
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.528289258480072
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5931975245475769
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.22830776870250702
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.482890248298645
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.39558055996894836
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4841350018978119
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5500443577766418
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5161505341529846
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5313428044319153
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.5170387625694275
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.30393171310424805
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5274637937545776
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.529957115650177
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.45709922909736633
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.5119251012802124
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.38324037194252014
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.48706650733947754
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5147603750228882
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5822763442993164
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5110971331596375
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46534600853919983
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.42187628149986267
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6028063893318176
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.48362594842910767
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.500941812992096
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4671958386898041
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4819236695766449
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4977293014526367
Calibrated prediction for SRE: 0.5625
Raw prediction for T: 0.6698832511901855
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4874492585659027
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5084400773048401
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5103822350502014
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.44212961196899414
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5376043319702148
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3266007602214813
Calibrated prediction for UNH: 0.3333333432674408
Raw prediction for UPS: 0.489616721868515
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.43366241455078125
Calibrated prediction for UTX: 0.6208620071411133
Raw prediction for V: 0.5173670053482056
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5768411159515381
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5029652714729309
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.48451289534568787
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5642173290252686
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:  12%|█▏        | 12/100 [00:14<01:41,  1.15s/it]

Raw prediction for AAPL: 0.5054998993873596
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5498819947242737
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4958273768424988
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4874034821987152
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.8857154846191406
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.49079814553260803
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5407513976097107
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.41709181666374207
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5301814079284668
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4484465420246124
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4990360140800476
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4893215596675873
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5087474584579468
Calibrated prediction for BHP: 0.5239219665527344
Raw prediction for BP: 0.5190001726150513
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.48139476776123047
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46667757630348206
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5621700882911682
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5409191250801086
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4845941662788391
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6575118899345398
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5217878222465515
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5634565353393555
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5217891931533813
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5926170945167542
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.694286584854126
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4678870141506195
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.40902459621429443
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5256845355033875
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4575440585613251
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5341992378234863
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4550361633300781
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5271852016448975
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3362683057785034
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4801180958747864
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5942409038543701
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5257567167282104
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5328792333602905
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5107718706130981
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.512315571308136
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4973805248737335
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.4801942706108093
Calibrated prediction for INTC: 0.5185185074806213
Raw prediction for JNJ: 0.5146927237510681
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4721176028251648
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4851497709751129
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4951254725456238
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4948744475841522
Calibrated prediction for MA: 0.6022840142250061
Raw prediction for MCD: 0.5964714884757996
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.22890064120292664
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4826403558254242
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.437191903591156
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4849115014076233
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5503132343292236
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5179368257522583
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5348906517028809
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.5244831442832947
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.29710420966148376
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5314783453941345
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5298432111740112
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.45974859595298767
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.5088704228401184
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.45386049151420593
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.48528817296028137
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5150067806243896
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.561366617679596
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.511399507522583
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46624451875686646
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.41947588324546814
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6099976301193237
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5064752101898193
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5011506080627441
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46772632002830505
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4823322594165802
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5299100875854492
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6641411781311035
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4867948293685913
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5093058347702026
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5103439688682556
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4429863691329956
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5570634603500366
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.32026466727256775
Calibrated prediction for UNH: 0.32835495471954346
Raw prediction for UPS: 0.4893752336502075
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4636041820049286
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.519147515296936
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.581077516078949
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  13%|█▎        | 13/100 [00:15<01:41,  1.16s/it]

Raw prediction for WFC: 0.5024785399436951
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.48366257548332214
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5472815036773682
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.602)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-01 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0006, PnL=$-1.43
Raw prediction for AAPL: 0.5057179927825928
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5464127063751221
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49578601121902466
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4873826503753662
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.8477286100387573
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4925561845302582
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5404340624809265
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.40892863273620605
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5311516523361206
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44751444458961487
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49928048253059387
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.489408016204834
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5109603404998779
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5395852327346802
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48234230279922485
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4660767614841461
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5651230216026306
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5407042503356934
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4847618639469147
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.68497633934021
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5222520232200623
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5567471981048584
Calibrated prediction for CHTR: 0.5685127973556519
Raw prediction for CMCSA: 0.5217260122299194
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.6034740805625916
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6825782060623169
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4685618281364441
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.41472959518432617
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5249772071838379
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4578750431537628
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5343716144561768
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.45077213644981384
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5267959833145142
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3351694941520691
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.47819262742996216
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.6099585890769958
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5275152325630188
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5268263816833496
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5122166872024536
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.5110021233558655
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.5089858174324036
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.4343116581439972
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5146815776824951
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.46573683619499207
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48572373390197754
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49434083700180054
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.49925777316093445
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5991377830505371
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.2376403659582138
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4823921322822571
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4693664312362671
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4857581555843353
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5560262799263
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5194242000579834
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5360032916069031
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.521833062171936
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.29474136233329773
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5348522663116455
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5297541618347168
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46338436007499695
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5035265684127808
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.5557664632797241
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.483762264251709
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5153433680534363
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5517860054969788
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5115160346031189
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4668203294277191
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.41812342405319214
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6209821701049805
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5217848420143127
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5018073916435242
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46788400411605835
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48294439911842346
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5532365441322327
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6555794477462769
Calibrated prediction for T: 0.6666666865348816
Raw prediction for TM: 0.48588261008262634
Calibrated prediction for TM: 0.4762147068977356

Simulating Trading Days:  14%|█▍        | 14/100 [00:16<01:39,  1.16s/it]

Raw prediction for TOT: 0.5097992420196533
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5101412534713745
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4552282691001892
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5863165855407715
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3172433078289032
Calibrated prediction for UNH: 0.290012001991272
Raw prediction for UPS: 0.4890700578689575
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.49355795979499817
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5208727121353149
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5849713683128357
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5022472739219666
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4826600253582001
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5253838300704956
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5057450532913208
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5390492081642151
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49564093351364136
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4874130189418793
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.7912810444831848
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.48984915018081665
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5405339598655701
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.40004536509513855
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5330442786216736
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4460999369621277
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49934080243110657
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48943930864334106
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5119065046310425
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5634901523590088
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4841456115245819
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4651561975479126
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.566234290599823
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5402619242668152
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4849306046962738
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6858428120613098
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5233240127563477
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5488815903663635
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.5216436386108398
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5968301892280579
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6598872542381287
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4688166081905365
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4156135618686676
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5239683985710144
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4580398499965668
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5344792008399963
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.44269388914108276
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5263352394104004
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3346790075302124
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.47539612650871277
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.6269245743751526
Calibrated prediction for GOOG: 0.6072596311569214
Raw prediction for HD: 0.5299772620201111
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5180037021636963
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5123819708824158
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.5089556574821472
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.5174599289894104
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.3953486979007721
Calibrated prediction for INTC: 0.4509046971797943
Raw prediction for JNJ: 0.5146009922027588
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4567522704601288
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48619386553764343
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49380889534950256
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5331271290779114
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.6073495149612427
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.25446128845214844
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48241037130355835
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.49832621216773987
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48659518361091614
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5679498314857483
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5203428864479065
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5347847938537598
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.48425325751304626
Calibrated prediction for NVS: 0.4583333432674408
Raw prediction for ORCL: 0.2872847318649292
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5365381836891174
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5295599102973938
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46617549657821655
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.49208900332450867
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.6175572276115417
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.48240309953689575
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5156559944152832
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5390878915786743
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5112868547439575
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46673938632011414
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.41832414269447327
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6302323341369629
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5331297516822815
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.5016136765480042
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4680483639240265
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48363012075424194
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5693933963775635
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6448417901992798
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.4850631356239319
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5092991590499878
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5101031064987183
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.45587119460105896
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5586817860603333
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.31804507970809937
Calibrated prediction for UNH: 0.30018699169158936
Raw prediction for UPS: 0.4888021945953369
Calibrated prediction for UPS: 0.488449364900589
Raw prediction for UTX: 0.4823245704174042
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5230178236961365
Calibrated prediction for V: 0.5184025168418884

Simulating Trading Days:  15%|█▌        | 15/100 [00:17<01:38,  1.16s/it]

Raw prediction for VZ: 0.5865265130996704
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5018250346183777
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.481203556060791
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.514353334903717
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-03 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0108, PnL=$42.30
[EARLY EXIT] 2017-05-03 00:00:00: BP p_up_1d=0.379 -> exit; r=-0.0017, PnL=$-4.14
Raw prediction for AAPL: 0.5054166316986084
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5418769121170044
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4956742823123932
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48766598105430603
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.7676816582679749
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4858279824256897
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5405415296554565
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3973594903945923
Calibrated prediction for BA: 0.6025905609130859
Raw prediction for BABA: 0.5355082154273987
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44476449489593506
Calibrated prediction for BAC: 0.4903223514556885
Raw prediction for BBL: 0.499427855014801
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4890843331813812
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5124645829200745
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5781038999557495
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4860553741455078
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4640271067619324
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.566716730594635
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5397211313247681
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4856761395931244
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6366732716560364
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5233010053634644
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5435006022453308
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.5215227603912354
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5780112743377686
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6340674161911011
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.468661367893219
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.41575124859809875
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5234247446060181
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45783522725105286
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.534547746181488
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.43615928292274475
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.525949239730835
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.34823888540267944
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4711647629737854
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.6425819993019104
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5325573682785034
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5116239190101624
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5118430852890015
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.5045619010925293
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.498313307762146
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.3745422661304474
Calibrated prediction for INTC: 0.4375
Raw prediction for JNJ: 0.5143030881881714
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4489689767360687
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48683685064315796
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4948374927043915
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5452523827552795
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.61960369348526
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.27044641971588135
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4828678369522095
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5029397010803223
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48683205246925354
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5840455889701843
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5210642218589783
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5327658653259277
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.43012183904647827
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.28124287724494934
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5371017456054688
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5291805267333984
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46582818031311035
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.47894030809402466
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.6444750428199768
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.48109570145606995
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5158752202987671
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5203779935836792
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5109983682632446
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46629998087882996
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4173007011413574
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6399352550506592
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5543729662895203
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.500746488571167
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46842148900032043
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48424193263053894
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5808494687080383
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6351861953735352
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.4846169948577881
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5085414052009583
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5101621747016907
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.45289430022239685
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.53521329164505
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3213793933391571
Calibrated prediction for UNH: 0.3333333432674408
Raw prediction for UPS: 0.4886644780635834
Calibrated prediction for UPS: 0.488449364900589
Raw prediction for UTX: 0.5409032106399536
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5253992676734924
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5876469612121582
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5014517307281494
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4794265031814575
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.512180745601654
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:  16%|█▌        | 16/100 [00:18<01:40,  1.19s/it]

[EARLY EXIT] 2017-05-04 00:00:00: BP p_up_1d=0.379 -> exit; r=-0.0107, PnL=$-52.14
Raw prediction for AAPL: 0.504463791847229
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.53819739818573
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49658840894699097
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48783400654792786
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.7426941990852356
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4802045524120331
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5397728085517883
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.4045361876487732
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5388878583908081
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4435119032859802
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49927714467048645
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4884283244609833
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5124494433403015
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5835651755332947
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4877825379371643
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46308183670043945
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5682991743087769
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5392299890518188
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48624566197395325
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5604037046432495
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5224704146385193
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5390161275863647
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.5214666128158569
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5621687769889832
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6117026209831238
Calibrated prediction for CSCO: 0.5454545617103577
Raw prediction for CVX: 0.46820417046546936
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.41791900992393494
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5230110883712769
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4575135111808777
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5345426201820374
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4333789050579071
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5255670547485352
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3860826790332794
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.46124669909477234
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.6570645570755005
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5352517366409302
Calibrated prediction for HD: 0.5420458912849426
Raw prediction for HON: 0.5058730244636536
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5111033916473389
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.49990716576576233
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.47755348682403564
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.3741112947463989
Calibrated prediction for INTC: 0.4375
Raw prediction for JNJ: 0.5139152407646179
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4436057507991791
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48766371607780457
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4967820346355438
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5190410017967224
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.6247623562812805
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.28316453099250793
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4831826686859131
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5153308510780334
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4864165782928467
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5997306108474731
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5215597748756409
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5312443375587463
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.37380409240722656
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.27680131793022156
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5388994216918945
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5284217596054077
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4687249958515167
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.46399205923080444
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.6592420935630798
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.4798702597618103
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.516010582447052
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5099148154258728
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5106591582298279
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46577179431915283
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.42137300968170166
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6483977437019348
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5610169768333435
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49949994683265686
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46895265579223633
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48485609889030457
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5905870795249939
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.623885452747345
Calibrated prediction for T: 0.5929393768310547
Raw prediction for TM: 0.48449742794036865
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5078357458114624
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5106416940689087
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.44701722264289856
Calibrated prediction for UL: 0.44285714626312256

Simulating Trading Days:  17%|█▋        | 17/100 [00:19<01:38,  1.18s/it]

Raw prediction for UN: 0.5341230630874634
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3397919237613678
Calibrated prediction for UNH: 0.39123067259788513
Raw prediction for UPS: 0.48876020312309265
Calibrated prediction for UPS: 0.488449364900589
Raw prediction for UTX: 0.5295866131782532
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5272313356399536
Calibrated prediction for V: 0.5277777910232544
Raw prediction for VZ: 0.590765655040741
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5011637806892395
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47733619809150696
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5110072493553162
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-05 00:00:00: MA p_up_1d=0.381 -> exit; r=0.0014, PnL=$7.08
[EARLY EXIT] 2017-05-05 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0286, PnL=$98.19
Raw prediction for AAPL: 0.5039256811141968
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5337756872177124
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49932676553726196
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48798951506614685
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.7371384501457214
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.477535605430603
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5386542677879333
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.41755789518356323
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5420639514923096
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44278988242149353
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49901315569877625
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4878562390804291
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.512485921382904
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5866298079490662
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48922181129455566
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4623538553714752
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5710843801498413
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5390710830688477
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4864836037158966
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5033261179924011
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5218586325645447
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5360927581787109
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.5215001106262207
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5512096881866455
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5889214873313904
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4674815237522125
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.41910719871520996
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5228098630905151
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4571942687034607
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5345317125320435
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4319876730442047
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5252637267112732
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.43283218145370483
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4485376179218292
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.672650933265686
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5376477241516113
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.50229412317276
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5110209584236145
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.49511629343032837
Calibrated prediction for HSBC: 0.5885555744171143
Raw prediction for IEP: 0.4684453308582306
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.38351428508758545
Calibrated prediction for INTC: 0.4375
Raw prediction for JNJ: 0.5135961771011353
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4416051506996155
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.488494873046875
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49892300367355347
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4727114140987396
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.626186192035675
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.30187445878982544
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48375022411346436
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5171458125114441
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48601651191711426
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.613874077796936
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5216336846351624
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5296032428741455
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.3298233151435852
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.2766905426979065
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5407918691635132
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5276455879211426
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4726104736328125
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4521430432796478
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.6472370624542236
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.47885286808013916
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5160024762153625
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.49836114048957825
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5102892518043518
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4654366672039032
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4275522828102112
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6559247374534607
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5343659520149231
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49836355447769165
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4692988991737366
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.485341876745224
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5970342755317688
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6115156412124634
Calibrated prediction for T: 0.5909090638160706
Raw prediction for TM: 0.4846322536468506
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5069261789321899
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5112826824188232
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4434725046157837
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.561060905456543
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.36843961477279663
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.489081472158432
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5056869983673096
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5279603600502014
Calibrated prediction for V: 0.5277777910232544
Raw prediction for VZ: 0.592293918132782
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5009844303131104
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47542232275009155
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  18%|█▊        | 18/100 [00:21<01:36,  1.17s/it]

Raw prediction for XOM: 0.5160304307937622
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.589)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-08 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0037, PnL=$13.68
Raw prediction for AAPL: 0.5034093260765076
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5279571413993835
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5026406645774841
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48806053400039673
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.7502412796020508
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.47658753395080566
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5365082621574402
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.43047845363616943
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5447888374328613
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44258567690849304
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49883779883384705
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4875338077545166
Calibrated prediction for BCH: 0.49729782342910767
Raw prediction for BHP: 0.5122488141059875
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5871027112007141
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.49015507102012634
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46188849210739136
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5727782845497131
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5394447445869446
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4863954782485962
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.47602567076683044
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5214856863021851
Calibrated prediction for CHL: 0.5076159238815308
Raw prediction for CHTR: 0.5353279113769531
Calibrated prediction for CHTR: 0.5049760937690735
Raw prediction for CMCSA: 0.5213958621025085
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5387393236160278
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5704328417778015
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4667675793170929
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.42368075251579285
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5227658748626709
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45679953694343567
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5345144271850586
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4319485127925873
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5248297452926636
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.490925669670105
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.43584874272346497
Calibrated prediction for GE: 0.4000000059604645
Raw prediction for GOOG: 0.6924543380737305
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5391432642936707
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5007167458534241
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5115795731544495
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.491380900144577
Calibrated prediction for HSBC: 0.5625
Raw prediction for IEP: 0.46349987387657166
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.3928874731063843
Calibrated prediction for INTC: 0.4375
Raw prediction for JNJ: 0.5133318901062012
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.44210630655288696
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48912209272384644
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5004441738128662
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.44694018363952637
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6285054087638855
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.31980669498443604
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4846498370170593
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5169718861579895
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4860574007034302
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6278250813484192
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5217200517654419
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5292633771896362
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.29407939314842224
Calibrated prediction for NVS: 0.27861082553863525
Raw prediction for ORCL: 0.277789443731308
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5434946417808533
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5268967747688293
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4773523807525635
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4548555910587311
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.6198383569717407
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.4782540798187256
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5161219835281372
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5013735890388489
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5100761651992798
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46514809131622314
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.43174195289611816
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.660398006439209
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5199924111366272
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4974868893623352
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46915963292121887
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4857097864151001
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.601266086101532
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5967272520065308
Calibrated prediction for T: 0.5909090638160706
Raw prediction for TM: 0.48494064807891846
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5063561201095581
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.511715829372406
Calibrated prediction for TSM: 0.5204885601997375

Simulating Trading Days:  19%|█▉        | 19/100 [00:22<01:34,  1.17s/it]

Raw prediction for UL: 0.44008731842041016
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5866433382034302
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.40091991424560547
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48940902948379517
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4699242413043976
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5278174877166748
Calibrated prediction for V: 0.5277777910232544
Raw prediction for VZ: 0.5933789014816284
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5009220838546753
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47335249185562134
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5288362503051758
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled HSBC from top-3 (p=0.562)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-09 00:00:00: BP p_up_1d=0.379 -> exit; r=-0.0023, PnL=$-9.56
Raw prediction for AAPL: 0.5023624300956726
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5238901972770691
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5058988928794861
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.4882226288318634
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.7665541768074036
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4776948392391205
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5351958870887756
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.4540153741836548
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5471456050872803
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44284752011299133
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49887362122535706
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4872297942638397
Calibrated prediction for BCH: 0.4873966872692108
Raw prediction for BHP: 0.5122184753417969
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5912575125694275
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4906984567642212
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46172821521759033
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5740430951118469
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.53997403383255
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4862690567970276
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.47756826877593994
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5196742415428162
Calibrated prediction for CHL: 0.44232165813446045
Raw prediction for CHTR: 0.5374696254730225
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.52129727602005
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5356243848800659
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5640891194343567
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.46625104546546936
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4293782413005829
Calibrated prediction for D: 0.476337730884552
Raw prediction for DHR: 0.5228126645088196
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4565293490886688
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.534502387046814
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4326535165309906
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5242627859115601
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5463624000549316
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.42487332224845886
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7065455913543701
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5396115779876709
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5005072355270386
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5117747187614441
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.4869377017021179
Calibrated prediction for HSBC: 0.5625
Raw prediction for IEP: 0.4559280276298523
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.4427243769168854
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.5131230354309082
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4442785382270813
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48961493372917175
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.501099705696106
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5017479658126831
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.6298601031303406
Calibrated prediction for MCD: 0.6588357090950012
Raw prediction for MDT: 0.34601888060569763
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48517513275146484
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5256571173667908
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48604291677474976
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6359778046607971
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5219134092330933
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.529781699180603
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.26583102345466614
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2742661237716675
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5470372438430786
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5262656807899475
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48310038447380066
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4621009826660156
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.5832388401031494
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.47767508029937744
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5162761211395264
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.514296293258667
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5101686716079712
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4650442600250244
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.43366682529449463
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6651384830474854
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5187773108482361
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4965880811214447
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.469651460647583
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.486045241355896
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.6022909879684448
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5824368000030518
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.48528987169265747
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5065243244171143
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5119838714599609
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4378455579280853
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6017757058143616
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4433508515357971
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4897378087043762
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4256899058818817
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5271551012992859
Calibrated prediction for V: 0.5277777910232544

Simulating Trading Days:  20%|██        | 20/100 [00:23<01:34,  1.18s/it]

Raw prediction for VZ: 0.594366729259491
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5007389187812805
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47157537937164307
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5376332998275757
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled MCD from top-3 (p=0.659)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-10 00:00:00: BP p_up_1d=0.379 -> exit; r=-0.0096, PnL=$-26.72
Raw prediction for AAPL: 0.5014089941978455
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5199024677276611
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5088842511177063
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.4881311357021332
Calibrated prediction for AEP: 0.48969176411628723
Raw prediction for AGFS: 0.8412913680076599
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4782904386520386
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5349675416946411
Calibrated prediction for AMZN: 0.5432276129722595
Raw prediction for BA: 0.4788376986980438
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5497645735740662
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4433535933494568
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4988991618156433
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4870193898677826
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5122833847999573
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5912472009658813
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4908621311187744
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4615910053253174
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.574521005153656
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5404322743415833
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4861299693584442
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4992622435092926
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5179606080055237
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5441039800643921
Calibrated prediction for CHTR: 0.5438596606254578
Raw prediction for CMCSA: 0.5211123824119568
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5523191690444946
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5596534013748169
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4658524990081787
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43014955520629883
Calibrated prediction for D: 0.49104270339012146
Raw prediction for DHR: 0.5229056477546692
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4561280906200409
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5345466732978821
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4316541254520416
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5236738324165344
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5809849500656128
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.41632965207099915
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7169740796089172
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5396142601966858
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5008438229560852
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5121446251869202
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.4821144938468933
Calibrated prediction for HSBC: 0.5625
Raw prediction for IEP: 0.45807382464408875
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.4968021810054779
Calibrated prediction for INTC: 0.5333333611488342
Raw prediction for JNJ: 0.5129182934761047
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4472605586051941
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4897443652153015
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5006423592567444
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5476261377334595
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6307470202445984
Calibrated prediction for MCD: 0.75
Raw prediction for MDT: 0.38241904973983765
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48569369316101074
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5266611576080322
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4858063757419586
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6414403319358826
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5216776728630066
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5297036170959473
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.246880903840065
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2695460021495819
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5482648015022278
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.525641918182373
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4861176311969757
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4700148105621338
Calibrated prediction for PFE: 0.45939725637435913
Raw prediction for PG: 0.5216437578201294
Calibrated prediction for PG: 0.5384615659713745
Raw prediction for PICO: 0.4771772027015686
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5163507461547852
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5283947587013245
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5104669332504272
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46519580483436584
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4333327114582062
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6698216199874878
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5084032416343689
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49572452902793884
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4693010449409485
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4863538146018982
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5969618558883667
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5730389952659607
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4855656623840332
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5068861842155457
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5123047232627869
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4347468912601471
Calibrated prediction for UL: 0.44285714626312256

Simulating Trading Days:  21%|██        | 21/100 [00:24<01:36,  1.22s/it]

Raw prediction for UN: 0.5963708758354187
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.5042697787284851
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49003899097442627
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.384698748588562
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5263157486915588
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5938653349876404
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5005985498428345
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4700907766819
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5501114130020142
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled GD from top-3 (p=0.604)
[PORT] Sector Services: sampled MCD from top-3 (p=0.750)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-11 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0057, PnL=$15.08
Raw prediction for AAPL: 0.5005359053611755
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5170249342918396
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5115232467651367
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.48815080523490906
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8751036524772644
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.47886011004447937
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5359770059585571
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.5062047243118286
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5506648421287537
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44369158148765564
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.498703271150589
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4868527948856354
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5118341445922852
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.582411527633667
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.49087050557136536
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46140313148498535
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5741769671440125
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5407434105873108
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4859561324119568
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5321745276451111
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5162480473518372
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5595349073410034
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5208389163017273
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5688717365264893
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.552474319934845
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.46534237265586853
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43291720747947693
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5229886174201965
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45554035902023315
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5345548391342163
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.43287578225135803
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5232001543045044
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5876062512397766
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.41036686301231384
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7253759503364563
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5390563607215881
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5018449425697327
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5124666690826416
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.47663986682891846
Calibrated prediction for HSBC: 0.5625
Raw prediction for IEP: 0.4595952033996582
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5403066277503967
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.512840986251831
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.44983869791030884
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48963236808776855
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49947091937065125
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5807152390480042
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6338396668434143
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.41946539282798767
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.48619091510772705
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5223059058189392
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4847169816493988
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6449840068817139
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5214710831642151
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5296764969825745
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2392958551645279
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.270367830991745
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5486562848091125
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5252024531364441
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48854848742485046
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4709872007369995
Calibrated prediction for PFE: 0.5545692443847656
Raw prediction for PG: 0.4526979923248291
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4768754243850708
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5163745880126953
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5510569214820862
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5107228755950928
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4650668501853943
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.43357428908348083
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6726139187812805
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.48792049288749695
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4950810670852661
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4687751829624176
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48664727807044983
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5869611501693726
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5651235580444336
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.48584699630737305
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5066081285476685
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.512615442276001
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4355463981628418
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6007183790206909
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.5550881028175354
Calibrated prediction for UNH: 0.4917801320552826
Raw prediction for UPS: 0.49024271965026855
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3552689850330353
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5255508422851562
Calibrated prediction for V: 0.5184025168418884

Simulating Trading Days:  22%|██▏       | 22/100 [00:26<01:34,  1.21s/it]

Raw prediction for VZ: 0.5928328037261963
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5004425048828125
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4694473445415497
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5738211870193481
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-12 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0051, PnL=$11.38
Raw prediction for AAPL: 0.4994712769985199
Calibrated prediction for AAPL: 0.4986749589443207
Raw prediction for ABB: 0.5156345367431641
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5138436555862427
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4884369671344757
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8852172493934631
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4777047336101532
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5374345779418945
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.5256354808807373
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.550571620464325
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4436019957065582
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4985606372356415
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4867796301841736
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.512721836566925
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5718464851379395
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4909605085849762
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4613400995731354
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5719269514083862
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5408954620361328
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48568984866142273
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5464288592338562
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.514113187789917
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5732360482215881
Calibrated prediction for CHTR: 0.5980610251426697
Raw prediction for CMCSA: 0.5206404328346252
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5785369277000427
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.547373354434967
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.46514275670051575
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43082335591316223
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5232775807380676
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4547819197177887
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5345442891120911
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4341691732406616
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5229499936103821
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5817175507545471
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.40758055448532104
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7305744886398315
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5383261442184448
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5026004910469055
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5116140246391296
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.47039633989334106
Calibrated prediction for HSBC: 0.5625
Raw prediction for IEP: 0.4542235732078552
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5789468884468079
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5126816034317017
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.45236822962760925
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4890241026878357
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49801763892173767
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.6026522517204285
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6340042352676392
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.4510374367237091
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.4866880476474762
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5269452333450317
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4836009442806244
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.645633339881897
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5210469365119934
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5293355584144592
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.232741117477417
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2706044316291809
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5478145480155945
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5248935222625732
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.49018874764442444
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.46489518880844116
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.3834661841392517
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.47656306624412537
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5164082050323486
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5590174198150635
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5111714005470276
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46505627036094666
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4333162009716034
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6737951636314392
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.46565893292427063
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4942532181739807
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4676874577999115
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48693758249282837
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5722519159317017
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5608720779418945
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.48615148663520813
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5065330862998962
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5128254890441895
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4275227189064026
Calibrated prediction for UL: 0.4032802879810333
Raw prediction for UN: 0.5763395428657532
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.5916086435317993
Calibrated prediction for UNH: 0.5263158082962036
Raw prediction for UPS: 0.4903474450111389
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3546655476093292
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5250939726829529
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5925429463386536
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  23%|██▎       | 23/100 [00:27<01:34,  1.23s/it]

Raw prediction for WFC: 0.5004801154136658
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.46883511543273926
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5950638055801392
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled GD from top-3 (p=0.604)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.4988732635974884
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5127516984939575
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5152531266212463
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48877838253974915
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8841133713722229
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4771132469177246
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5391259789466858
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.5333422422409058
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5486363768577576
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44341370463371277
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4985046982765198
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4865633547306061
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5132048726081848
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5494859218597412
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4909915328025818
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4613817036151886
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5698840022087097
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5411838293075562
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48529869318008423
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5784593224525452
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5112496018409729
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5826495885848999
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5204620361328125
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5729855298995972
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5440251231193542
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4649008512496948
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4245779812335968
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5235973596572876
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45376065373420715
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5344787836074829
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4330422580242157
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5227065682411194
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5581796169281006
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.406864196062088
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7334501147270203
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5369699597358704
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.503505527973175
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5078664422035217
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.4616762697696686
Calibrated prediction for HSBC: 0.5625
Raw prediction for IEP: 0.44898679852485657
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6166706085205078
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.512608528137207
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4538819491863251
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48809605836868286
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49624037742614746
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.625359296798706
Calibrated prediction for MA: 0.75
Raw prediction for MCD: 0.6303683519363403
Calibrated prediction for MCD: 0.7256132960319519
Raw prediction for MDT: 0.4712720215320587
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.4870143532752991
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5007418990135193
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.481791228055954
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6434709429740906
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5201058983802795
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5279914140701294
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2291521579027176
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2698844075202942
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5455446243286133
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5247913599014282
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4860425889492035
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4567146599292755
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.30640360713005066
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4761875867843628
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5162469744682312
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5449874401092529
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.511404812335968
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4643070101737976
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4321284890174866
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6710978746414185
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.47334960103034973
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4935716688632965
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46675175428390503
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4871706962585449
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5492393970489502
Calibrated prediction for SRE: 0.5960687398910522

Simulating Trading Days:  24%|██▍       | 24/100 [00:28<01:31,  1.21s/it]

Raw prediction for T: 0.5599882006645203
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4866497218608856
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5054177641868591
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5128868222236633
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.424755722284317
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5803403258323669
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.6142805814743042
Calibrated prediction for UNH: 0.5263158082962036
Raw prediction for UPS: 0.4903797209262848
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.33605706691741943
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5248244404792786
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5915335416793823
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5005165338516235
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4681744873523712
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6178524494171143
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.750)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled MCD from top-3 (p=0.726)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.497774600982666
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5124651789665222
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5151470303535461
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4889775216579437
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8771138191223145
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4782785177230835
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5405494570732117
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.532228410243988
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5452424883842468
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4430624544620514
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4984453022480011
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4865710735321045
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5129218697547913
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5211933851242065
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4908847510814667
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.461635559797287
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5689751505851746
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5414939522743225
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4848388433456421
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6351969838142395
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5077989101409912
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5884149074554443
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5202987790107727
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5726788640022278
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5392903089523315
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4646649658679962
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4199470281600952
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5239808559417725
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4528326094150543
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5344048142433167
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.43301236629486084
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5224622488021851
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5324764847755432
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4071916341781616
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7331280708312988
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.535789430141449
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5044716000556946
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5020176768302917
Calibrated prediction for HRG: 0.5089868903160095
Raw prediction for HSBC: 0.4569936692714691
Calibrated prediction for HSBC: 0.5625
Raw prediction for IEP: 0.44442448019981384
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6555153131484985
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5127997398376465
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4556000232696533
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4869706928730011
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4948246479034424
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.6512059569358826
Calibrated prediction for MA: 0.7692307829856873
Raw prediction for MCD: 0.6264468431472778
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.4848935604095459
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.4871896505355835
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.473658949136734
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47955894470214844
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6391274929046631
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5194225311279297
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5260667204856873
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.22981850802898407
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2651994228363037
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5436385869979858
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5247424840927124
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4811055362224579
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.44777438044548035
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.2473173290491104
Calibrated prediction for PG: 0.20000000298023224
Raw prediction for PICO: 0.47576314210891724
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5161346793174744
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5061994791030884
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5116122961044312
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4633500576019287
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.43126460909843445
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6636806130409241
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.48873189091682434
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49322065711021423
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4669453501701355
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4873286187648773
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5275008678436279
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5570099949836731
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4869508147239685
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5044918060302734
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5129721760749817
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.41811975836753845
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5692571401596069
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.6031381487846375
Calibrated prediction for UNH: 0.5263158082962036
Raw prediction for UPS: 0.4903786778450012
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3070577383041382
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5236662030220032
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5907466411590576
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5007433295249939
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4671851396560669
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  25%|██▌       | 25/100 [00:29<01:29,  1.19s/it]

Raw prediction for XOM: 0.6322925090789795
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.769)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.4963831901550293
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5139294862747192
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5143211483955383
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4891015887260437
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.9096965789794922
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4795215427875519
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5413140654563904
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.5211192965507507
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5421162843704224
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44275397062301636
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49827659130096436
Calibrated prediction for BBL: 0.497940331697464
Raw prediction for BCH: 0.48667722940444946
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5121252536773682
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.49714699387550354
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.49033087491989136
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4618242383003235
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5693673491477966
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5418723225593567
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4844842851161957
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6846235990524292
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5037143230438232
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5907988548278809
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5201114416122437
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5652993321418762
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5430386662483215
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4645118713378906
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.42662283778190613
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5243141651153564
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4520871341228485
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5343649387359619
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.43906816840171814
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.522241473197937
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4994816780090332
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.40817734599113464
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7305567264556885
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5350808501243591
Calibrated prediction for HD: 0.5390069484710693
Raw prediction for HON: 0.5050115585327148
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4963117837905884
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4544002115726471
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.46833309531211853
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6912406086921692
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5129615068435669
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.45725589990615845
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4862034320831299
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49391239881515503
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.6919295191764832
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.6216544508934021
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.4833486080169678
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.48716646432876587
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4428654611110687
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47821182012557983
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6355018615722656
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5192849636077881
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5251413583755493
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.23392832279205322
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2632608413696289
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5438801050186157
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5247113704681396
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47703298926353455
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4436941146850586
Calibrated prediction for PFE: 0.3642178773880005
Raw prediction for PG: 0.22318029403686523
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.47535383701324463
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5158609747886658
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4971616268157959
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5115650296211243
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4624052345752716
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.42961812019348145
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6524322032928467
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.4991278350353241
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4928012192249298
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46785300970077515
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48735421895980835
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.510731041431427
Calibrated prediction for SRE: 0.5625
Raw prediction for T: 0.5517515540122986
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.48746830224990845
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5036764740943909
Calibrated prediction for TOT: 0.5130005478858948

Simulating Trading Days:  26%|██▌       | 26/100 [00:30<01:27,  1.18s/it]

Raw prediction for TSM: 0.5131176114082336
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.41391438245773315
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5740087628364563
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.583107054233551
Calibrated prediction for UNH: 0.5
Raw prediction for UPS: 0.4903292655944824
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.27927491068840027
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5220486521720886
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5898070335388184
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5008398294448853
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.46616408228874207
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6423508524894714
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.4949198365211487
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5182930827140808
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5126244425773621
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48885664343833923
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8970040678977966
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.48253631591796875
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5416987538337708
Calibrated prediction for AMZN: 0.5581690669059753
Raw prediction for BA: 0.5203258991241455
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5397121906280518
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44255897402763367
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4981144964694977
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4867491126060486
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5113964676856995
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.4836824834346771
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4890713095664978
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4619586765766144
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5700275301933289
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5422531366348267
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48433777689933777
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7153530120849609
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49949219822883606
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5941904187202454
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5197937488555908
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5545823574066162
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5517335534095764
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.46429648995399475
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43725237250328064
Calibrated prediction for D: 0.5102781057357788
Raw prediction for DHR: 0.5246383547782898
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45144662261009216
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5343875885009766
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4448353350162506
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5220747590065002
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.48962122201919556
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4108216464519501
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7250841856002808
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5347980856895447
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5063110589981079
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4906737208366394
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.45070403814315796
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.4843284785747528
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7265611886978149
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5131394863128662
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.45822590589523315
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4858085513114929
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49424272775650024
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7420878410339355
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.6194270253181458
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.4747069776058197
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.4869554340839386
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.42576295137405396
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4768834114074707
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6304718852043152
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5187105536460876
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5235816240310669
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2373771369457245
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2625000476837158
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5450004935264587
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5253775715827942
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4758160412311554
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4462854564189911
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.20681269466876984
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.4749920070171356
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5155548453330994
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.49293825030326843
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5112125873565674
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4615814685821533
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.42845144867897034
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.638184666633606
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5182269215583801
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49247556924819946
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4686906337738037
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.487509161233902
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.49769726395606995
Calibrated prediction for SRE: 0.5625
Raw prediction for T: 0.5417512059211731
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.48860231041908264
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.503345251083374
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5133005976676941
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4039943814277649
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5684548616409302
Calibrated prediction for UN: 0.5199999809265137

Simulating Trading Days:  27%|██▋       | 27/100 [00:31<01:28,  1.21s/it]

Raw prediction for UNH: 0.5576953291893005
Calibrated prediction for UNH: 0.49715083837509155
Raw prediction for UPS: 0.49032989144325256
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.28086188435554504
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5203003883361816
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5896607041358948
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.500920832157135
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4665016829967499
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6501305103302002
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.4940544664859772
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5199411511421204
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5102719664573669
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.4885186553001404
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.7901681065559387
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4875476360321045
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5418183207511902
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5178816318511963
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5399381518363953
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44239625334739685
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49786481261253357
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.487016886472702
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5103457570075989
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.4718465209007263
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.48733797669410706
Calibrated prediction for BRK-A: 0.4675458073616028
Raw prediction for BSAC: 0.4623557925224304
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5703563094139099
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5424900054931641
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4842450022697449
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7283483147621155
Calibrated prediction for CELG: 0.6000000238418579
Raw prediction for CHL: 0.49578166007995605
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.594001054763794
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5196525454521179
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5414141416549683
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5665229558944702
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.46417686343193054
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4502699375152588
Calibrated prediction for D: 0.5384615659713745
Raw prediction for DHR: 0.5247859358787537
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45130014419555664
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5343884229660034
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4510326683521271
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5219323039054871
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5032446384429932
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.41214483976364136
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7144439816474915
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5342327356338501
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5077924132347107
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.484963059425354
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.44808945059776306
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.499530166387558
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7557092308998108
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5132748484611511
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.45986858010292053
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4857653081417084
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4954959750175476
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7793264985084534
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.6128748655319214
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.46279606223106384
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.48672690987586975
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.40522539615631104
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4750378429889679
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6233532428741455
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5178493857383728
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5232594609260559
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.23993515968322754
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.272044837474823
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5481382012367249
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5264069437980652
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.474582701921463
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4493313431739807
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.193431556224823
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.4748477041721344
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5152466893196106
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5031144618988037
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5106121897697449
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46095508337020874
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.42669710516929626
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6235944628715515
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5312029719352722
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4926953911781311
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4695264399051666
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48773473501205444
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4866305887699127
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.5315870046615601
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4900400936603546
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5036846995353699
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5135229825973511
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3947230279445648
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5677719712257385
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.5175321698188782
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49035826325416565
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.2714060842990875
Calibrated prediction for UTX: 0.3399044871330261

Simulating Trading Days:  28%|██▊       | 28/100 [00:33<01:27,  1.21s/it]

Raw prediction for V: 0.5186819434165955
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5925769209861755
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5013523101806641
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4675017297267914
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6563671231269836
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.600)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.4931192994117737
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5210186839103699
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5078113675117493
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.4882391095161438
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.519803524017334
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4925694763660431
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.541743278503418
Calibrated prediction for AMZN: 0.5609219670295715
Raw prediction for BA: 0.5271987318992615
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5417686104774475
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44256752729415894
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4976411759853363
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48722147941589355
Calibrated prediction for BCH: 0.4871259033679962
Raw prediction for BHP: 0.5091353058815002
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.46239984035491943
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.48531287908554077
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46233877539634705
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5692217350006104
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5426284074783325
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48426204919815063
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7309578061103821
Calibrated prediction for CELG: 0.6000000238418579
Raw prediction for CHL: 0.4931943714618683
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5920442938804626
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5195111632347107
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5162431597709656
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5853081941604614
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4640505313873291
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4584693908691406
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5247532725334167
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45137831568717957
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5342724919319153
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4516248404979706
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5217292308807373
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5197474956512451
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.41576170921325684
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6967142224311829
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.532584547996521
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.511915385723114
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.47968369722366333
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4431591331958771
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5127303004264832
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7759417295455933
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5133110880851746
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.46275439858436584
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48588746786117554
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4969739317893982
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7954092025756836
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.6056947708129883
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.44198787212371826
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.48686403036117554
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3849252462387085
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4740058183670044
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.611418604850769
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.516471803188324
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5229142308235168
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.23961511254310608
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2870163023471832
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5495843887329102
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.527580976486206
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47419553995132446
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.45176219940185547
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.1837562769651413
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.4750930070877075
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5150853395462036
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5014066100120544
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5098882913589478
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4605706036090851
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.42112064361572266
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6143207550048828
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.543231189250946
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49291807413101196
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46980273723602295
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48807206749916077
Calibrated prediction for SPLP: 0.5045595169067383

Simulating Trading Days:  29%|██▉       | 29/100 [00:34<01:24,  1.20s/it]

Raw prediction for SRE: 0.476052850484848
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.5234559178352356
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4914777874946594
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5044320225715637
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5136904120445251
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3855339586734772
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.577919602394104
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4874125123023987
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49028605222702026
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.29390114545822144
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.517634928226471
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5963842868804932
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5016932487487793
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.46883606910705566
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6571950912475586
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.632)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.600)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-23 00:00:00: MA p_up_1d=0.380 -> exit; r=0.0240, PnL=$108.67
[EARLY EXIT] 2017-05-23 00:00:00: MA p_up_1d=0.380 -> exit; r=0.0289, PnL=$152.05
[EARLY EXIT] 2017-05-23 00:00:00: MA p_up_1d=0.380 -> exit; r=0.0172, PnL=$91.67
Raw prediction for AAPL: 0.4922255277633667
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5213831663131714
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5054848790168762
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.48831304907798767
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.24828404188156128
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4961417019367218
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.541583240032196
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.533549964427948
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5441878437995911
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4427996873855591
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4974829852581024
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48725372552871704
Calibrated prediction for BCH: 0.4881761074066162
Raw prediction for BHP: 0.5063843131065369
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.4560980498790741
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4830927550792694
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46219193935394287
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5679126381874084
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5427478551864624
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4842459559440613
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7285517454147339
Calibrated prediction for CELG: 0.6000000238418579
Raw prediction for CHL: 0.49153193831443787
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5901827216148376
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5193607211112976
Calibrated prediction for CMCSA: 0.5289620161056519
Raw prediction for CODI: 0.47904157638549805
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.5870814919471741
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4638234078884125
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4656117260456085
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5247026681900024
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45147016644477844
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5340772271156311
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.45045822858810425
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5215942859649658
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5399777293205261
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.42048463225364685
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.677619218826294
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5302612781524658
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5165954828262329
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4760400950908661
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4364400804042816
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5188154578208923
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7827957272529602
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5132209658622742
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.46594712138175964
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4860319495201111
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49767130613327026
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7954350709915161
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.599907398223877
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.4070039987564087
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.4869236648082733
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3640540540218353
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4734998047351837
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5982862710952759
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5154231190681458
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5225691795349121
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2354351431131363
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3032236099243164
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5487452149391174
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.528579592704773
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47020223736763
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.45382487773895264
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.17587845027446747
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.47532975673675537
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5149303674697876
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.490063339471817
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5091667771339417
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46030017733573914
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.4127421975135803
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6114766597747803
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5597512722015381
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49307557940483093
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46988001465797424
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48810797929763794
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.46678489446640015
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.5192867517471313
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4924145042896271
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5048004984855652
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5136755704879761
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.37747108936309814
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5915369987487793
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4723985195159912
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4901675581932068
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3193446695804596
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5172968506813049
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.599797248840332
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5017958879470825
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47106748819351196
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  30%|███       | 30/100 [00:35<01:22,  1.18s/it]

Raw prediction for XOM: 0.6624186635017395
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.632)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.600)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-24 00:00:00: MA p_up_1d=0.317 -> exit; r=0.0092, PnL=$52.71
Raw prediction for AAPL: 0.49155867099761963
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5176987051963806
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5036135315895081
Calibrated prediction for ABBV: 0.5
Raw prediction for AEP: 0.48887714743614197
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.15152904391288757
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4983101487159729
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5418322086334229
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5345883965492249
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5466187000274658
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44311198592185974
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4969637393951416
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4873294234275818
Calibrated prediction for BCH: 0.49064144492149353
Raw prediction for BHP: 0.5035148859024048
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.4461897015571594
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.48119738698005676
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46186181902885437
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5657740831375122
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5427694916725159
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48417651653289795
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7273739576339722
Calibrated prediction for CELG: 0.6000000238418579
Raw prediction for CHL: 0.48959606885910034
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5906396508216858
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5191757678985596
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.4478389620780945
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.5763633847236633
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.46346771717071533
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.47766992449760437
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5246509313583374
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45152637362480164
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5338786244392395
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4543378949165344
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5215073823928833
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5500458478927612
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.42390120029449463
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6548345685005188
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5284690260887146
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.52126145362854
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4743952453136444
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4295674264431
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5235511064529419
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7806093096733093
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.513193666934967
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4672335386276245
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4859478175640106
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4983714520931244
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7774311304092407
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.5984092354774475
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3730281591415405
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48682543635368347
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.340849906206131
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.472944974899292
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5868505835533142
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5153730511665344
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5221028327941895
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.24097229540348053
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.30691632628440857
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5490143299102783
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5293905735015869
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46385806798934937
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.45570021867752075
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.16867908835411072
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.47545579075813293
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5146321058273315
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.49193665385246277
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5083066821098328
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46006569266319275
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.4015692472457886
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6128489375114441
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5534569025039673
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4930846095085144
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4701876640319824
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4881039261817932
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4623987078666687
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.5136821269989014
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4928521513938904
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5043273568153381
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5135816335678101
Calibrated prediction for TSM: 0.5204885601997375

Simulating Trading Days:  31%|███       | 31/100 [00:36<01:21,  1.18s/it]

Raw prediction for UL: 0.3701568841934204
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5973925590515137
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.47597962617874146
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4899451732635498
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3547896444797516
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5176241993904114
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6027310490608215
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5018675923347473
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4729211926460266
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6671895384788513
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.600)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-25 00:00:00: MA p_up_1d=0.317 -> exit; r=0.0101, PnL=$59.08
Raw prediction for AAPL: 0.49114689230918884
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5188153982162476
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5020807981491089
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48955240845680237
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.1288934201002121
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.5012274384498596
Calibrated prediction for AMGN: 0.5
Raw prediction for AMZN: 0.5421977639198303
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5334383249282837
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5471559762954712
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4437738358974457
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49659454822540283
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48846006393432617
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5020392537117004
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.44239288568496704
Calibrated prediction for BP: 0.6224607229232788
Raw prediction for BRK-A: 0.48022496700286865
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46208542585372925
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5633596181869507
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5423902869224548
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4840695559978485
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7410847544670105
Calibrated prediction for CELG: 0.6000000238418579
Raw prediction for CHL: 0.48794233798980713
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5944975018501282
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5189396142959595
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.4317001700401306
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.5590213537216187
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4634966552257538
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.48634403944015503
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5244222283363342
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45140641927719116
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5338611602783203
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.46548667550086975
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5222518444061279
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5793243050575256
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.4277667999267578
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6418051719665527
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5266494154930115
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5271201133728027
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4738433361053467
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4304407238960266
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5330513715744019
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7789027094841003
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5132982134819031
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4697118401527405
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4858333170413971
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4993542432785034
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7144078016281128
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.5992821455001831
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.34439823031425476
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.486587792634964
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3407450020313263
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4726499915122986
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5833523273468018
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5157471895217896
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5214226245880127
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2639099061489105
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3176462948322296
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5493676066398621
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5300373435020447
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.45954248309135437
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4599875509738922
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.1631413996219635
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.4757303297519684
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5142797827720642
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5048198699951172
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5076303482055664
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46034494042396545
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.39019104838371277
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6171392798423767
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5326416492462158
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49321600794792175
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4699409604072571
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48838141560554504
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.46422237157821655
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.5111815333366394
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4931472837924957
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.504313051700592
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5132985711097717
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3637673854827881
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5981852412223816
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.48510289192199707
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4898104965686798
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.38121336698532104
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5182458162307739
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6064337491989136
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5021818280220032
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47462543845176697
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  32%|███▏      | 32/100 [00:37<01:19,  1.17s/it]

Raw prediction for XOM: 0.6661304831504822
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.600)
[PORT] Sector Industrial Goods: sampled GD from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-26 00:00:00: MA p_up_1d=0.317 -> exit; r=-0.0024, PnL=$-15.03
Raw prediction for AAPL: 0.49148494005203247
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5199710726737976
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5011411309242249
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4899735450744629
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.12177100777626038
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.50147545337677
Calibrated prediction for AMGN: 0.5
Raw prediction for AMZN: 0.5431826114654541
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5236834287643433
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.545190155506134
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44547802209854126
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49643784761428833
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.489021360874176
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.5006852746009827
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.4398471415042877
Calibrated prediction for BP: 0.5300664305686951
Raw prediction for BRK-A: 0.47926250100135803
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4621884822845459
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5633636116981506
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5420624613761902
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4840349853038788
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7505925893783569
Calibrated prediction for CELG: 0.6000000238418579
Raw prediction for CHL: 0.4879513084888458
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5991252660751343
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5188338160514832
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.43260157108306885
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.5600947141647339
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4639476239681244
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4888361394405365
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5239549875259399
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4516139328479767
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5338777899742126
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4805586040019989
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5229754447937012
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5879744291305542
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.43205058574676514
Calibrated prediction for GE: 0.4000000059604645
Raw prediction for GOOG: 0.629349946975708
Calibrated prediction for GOOG: 0.6511393189430237
Raw prediction for HD: 0.5247483849525452
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5342716574668884
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.47454437613487244
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4308960735797882
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5387696027755737
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.76040118932724
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5132396221160889
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.47235265374183655
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4857177734375
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5002294182777405
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.6358968615531921
Calibrated prediction for MA: 0.7692307829856873
Raw prediction for MCD: 0.5951147079467773
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.31683531403541565
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48640066385269165
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3535454273223877
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.472409188747406
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5825789570808411
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5162913799285889
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.519950807094574
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.30406132340431213
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3344273269176483
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5490781664848328
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5306646823883057
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4568656086921692
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4643740952014923
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.16940271854400635
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.47606733441352844
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5138498544692993
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5253865122795105
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5071326494216919
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46075546741485596
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.3803671598434448
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.621895968914032
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5202726125717163
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4933568239212036
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46926817297935486
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.488891065120697
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4644221365451813
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.5075491666793823
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4934147894382477
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5040836334228516
Calibrated prediction for TOT: 0.5130005478858948

Simulating Trading Days:  33%|███▎      | 33/100 [00:38<01:18,  1.16s/it]

Raw prediction for TSM: 0.5123579502105713
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3625423014163971
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6107558608055115
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.49510982632637024
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48976930975914
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.392007440328598
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5182663798332214
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6082245111465454
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5022621750831604
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4762524664402008
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6631161570549011
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.769)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.600)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.651)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-05-30 00:00:00: MA p_up_1d=0.317 -> exit; r=0.0002, PnL=$0.93
Raw prediction for AAPL: 0.49262136220932007
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5223220586776733
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5001152753829956
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49033889174461365
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.12298456579446793
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.5014249682426453
Calibrated prediction for AMGN: 0.5
Raw prediction for AMZN: 0.5435065031051636
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4990788996219635
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5415728092193604
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44733965396881104
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49642056226730347
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48887720704078674
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.49946483969688416
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.4320280849933624
Calibrated prediction for BP: 0.3333333432674408
Raw prediction for BRK-A: 0.47865188121795654
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4622909128665924
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5625573992729187
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5417619943618774
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48409536480903625
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7655429840087891
Calibrated prediction for CELG: 0.7907392978668213
Raw prediction for CHL: 0.48702380061149597
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6003461480140686
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5188506841659546
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.4316229820251465
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.5784441828727722
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.46454373002052307
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.487059086561203
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5234284400939941
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45186781883239746
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5338371396064758
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.497096985578537
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5236596465110779
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5568726658821106
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4356178641319275
Calibrated prediction for GE: 0.4000000059604645
Raw prediction for GOOG: 0.6083166599273682
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5227531790733337
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5389760136604309
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4748845100402832
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4287201762199402
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.541361391544342
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7475566267967224
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5129890441894531
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4757375419139862
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4855269193649292
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4989601671695709
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5550457239151001
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5915789008140564
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.2898105978965759
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4861225187778473
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3614065647125244
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4722505509853363
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5765123963356018
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5170354247093201
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5180164575576782
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.34058043360710144
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3428348898887634
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5483450889587402
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.531151533126831
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.45606738328933716
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.46644335985183716
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.17008906602859497
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.47655537724494934
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5133917331695557
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5409888029098511
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5068091750144958
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46140262484550476
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.3755151629447937
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.627380907535553
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5177315473556519
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4934980273246765
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46853628754615784
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48940160870552063
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4684140384197235
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.5026564002037048
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4934154152870178
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5035392045974731
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5116173028945923
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3629353642463684
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6268587708473206
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.4890907108783722
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48968639969825745
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4025028347969055
Calibrated prediction for UTX: 0.38461539149284363

Simulating Trading Days:  34%|███▍      | 34/100 [00:40<01:17,  1.18s/it]

Raw prediction for V: 0.5180034637451172
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6068730354309082
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5020643472671509
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4768027365207672
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6640632748603821
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.727)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.791)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled VZ from top-3 (p=0.615)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.4936929941177368
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.523874819278717
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4991045594215393
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4905858635902405
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.1675165444612503
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.5018491744995117
Calibrated prediction for AMGN: 0.5
Raw prediction for AMZN: 0.5429916381835938
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4614745080471039
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5372148752212524
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.448710173368454
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49653691053390503
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48850250244140625
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.498049259185791
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.4226563572883606
Calibrated prediction for BP: 0.3333333432674408
Raw prediction for BRK-A: 0.47879090905189514
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46229591965675354
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.56026291847229
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5415507555007935
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.4839487075805664
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7824929356575012
Calibrated prediction for CELG: 0.7907392978668213
Raw prediction for CHL: 0.48557138442993164
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5964986085891724
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5190389752388
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.42258039116859436
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.5953361392021179
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.4650639593601227
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.48987776041030884
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5232416391372681
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4522271752357483
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5336772799491882
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5204222202301025
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5240440964698792
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5079365372657776
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4397538900375366
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5859650373458862
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5206266641616821
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5393543243408203
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4746878743171692
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.42701852321624756
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5395937561988831
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7299336194992065
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5128361582756042
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.47828564047813416
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48524630069732666
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4959042966365814
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5040005445480347
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5843615531921387
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.2681834101676941
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4858246445655823
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.36226195096969604
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47171151638031006
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5702438950538635
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5189611315727234
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.519954264163971
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.3698119819164276
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3368314504623413
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.546359658241272
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5314195156097412
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4543946087360382
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4653518795967102
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.17259173095226288
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.4771035313606262
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5130508542060852
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5271381139755249
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.50649094581604
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46204113960266113
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.37025320529937744
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.630554735660553
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5222692489624023
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4936835765838623
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4701755940914154
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4897955060005188
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.47336286306381226
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.5003461241722107
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.49322643876075745
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.503278374671936
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5112382769584656
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.36217108368873596
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6290395855903625
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.467159628868103
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4896230101585388
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3943900167942047
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5177993178367615
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6034846305847168
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5018025636672974
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47646811604499817
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6538094282150269
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.727)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.791)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled GOOG from top-3 (p=0.597)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:  35%|███▌      | 35/100 [00:41<01:16,  1.17s/it]

Raw prediction for AAPL: 0.4945238530635834
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5265184044837952
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49840685725212097
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49104297161102295
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.2911323606967926
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.5019740462303162
Calibrated prediction for AMGN: 0.5
Raw prediction for AMZN: 0.5416629910469055
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.41911011934280396
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5320367813110352
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44899559020996094
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4965985417366028
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48798519372940063
Calibrated prediction for BCH: 0.5055404305458069
Raw prediction for BHP: 0.4967634677886963
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.41061097383499146
Calibrated prediction for BP: 0.3333333432674408
Raw prediction for BRK-A: 0.4798484146595001
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4620436131954193
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5567111372947693
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5410802960395813
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.483787477016449
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7798469662666321
Calibrated prediction for CELG: 0.7907392978668213
Raw prediction for CHL: 0.48375067114830017
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5904970169067383
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5192028880119324
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.4296860694885254
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.60591059923172
Calibrated prediction for CSCO: 0.5454545617103577
Raw prediction for CVX: 0.4652322232723236
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.48569566011428833
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5235506892204285
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45262208580970764
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5334784984588623
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5328853130340576
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5242897272109985
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.44878315925598145
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4477302134037018
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5678821802139282
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5188298225402832
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5371271371841431
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.47414469718933105
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4259204864501953
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5341171622276306
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7097200155258179
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5126000642776489
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4787183105945587
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4847351908683777
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4936554431915283
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.47550252079963684
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5784554481506348
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.24240955710411072
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4854430854320526
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3568815588951111
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4709513485431671
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5662499666213989
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5203823447227478
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.519996166229248
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.3706802427768707
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3253733217716217
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5421298146247864
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5314900875091553
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4524146020412445
Calibrated prediction for PEP: 0.49461644887924194
Raw prediction for PFE: 0.46479111909866333
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.17990241944789886
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.4776494801044464
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5127453804016113
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.502549409866333
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5060920715332031
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4625281095504761
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3665074110031128
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6323868632316589
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5242792367935181
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49375271797180176
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4697078764438629
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48991483449935913
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.48788246512413025
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.499264121055603
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.49298736453056335
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.503082811832428
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5111730694770813
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3643685579299927
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6347205638885498
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.45001518726348877
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4895156919956207
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3877846896648407
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5179610848426819
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6000533699989319
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5016255378723145
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47540926933288574
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  36%|███▌      | 36/100 [00:42<01:14,  1.17s/it]

Raw prediction for XOM: 0.6354476809501648
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.727)
[PORT] Sector Financial: sampled C from top-3 (p=0.551)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.791)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled VZ from top-3 (p=0.615)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.49512210488319397
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5261262059211731
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49775853753089905
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4915507137775421
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.690934419631958
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.5013558864593506
Calibrated prediction for AMGN: 0.5
Raw prediction for AMZN: 0.5398465991020203
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3732750117778778
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.527681291103363
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44852572679519653
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4967099130153656
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4874732792377472
Calibrated prediction for BCH: 0.49532654881477356
Raw prediction for BHP: 0.4959687292575836
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.3999003767967224
Calibrated prediction for BP: 0.3333333432674408
Raw prediction for BRK-A: 0.48178061842918396
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.462099552154541
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5523446798324585
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5405013561248779
Calibrated prediction for C: 0.5507315993309021
Raw prediction for CAT: 0.48357468843460083
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7519086599349976
Calibrated prediction for CELG: 0.6000000238418579
Raw prediction for CHL: 0.4820079505443573
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5830406546592712
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5194096565246582
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.4705009162425995
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.6116238832473755
Calibrated prediction for CSCO: 0.5454545617103577
Raw prediction for CVX: 0.4652174711227417
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.47966405749320984
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5242120623588562
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45308926701545715
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5333334803581238
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5370568037033081
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5242667198181152
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.39782997965812683
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4511796534061432
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5537524819374084
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5171255469322205
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5337278246879578
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4759385287761688
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4258771538734436
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5393140316009521
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6793858408927917
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5124014616012573
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.47703608870506287
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48381149768829346
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4928184747695923
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.460515558719635
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5708513259887695
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.21957288682460785
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48493435978889465
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.35151171684265137
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4696648120880127
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5667840242385864
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5206844806671143
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.518661379814148
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.35250067710876465
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.3084583878517151
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5374984741210938
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5313868522644043
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4494986832141876
Calibrated prediction for PEP: 0.45305606722831726
Raw prediction for PFE: 0.465791255235672
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.19333310425281525
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.4781199097633362
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5125617980957031
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.475919246673584
Calibrated prediction for PPL: 0.6000000238418579
Raw prediction for PTR: 0.505815327167511
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46312329173088074
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3637070059776306
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6338042616844177
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.528083086013794
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4938872754573822
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46940818428993225
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4896671175956726
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5063665509223938
Calibrated prediction for SRE: 0.5625
Raw prediction for T: 0.5044586062431335
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.49274423718452454
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5034573674201965
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5112032890319824
Calibrated prediction for TSM: 0.5204885601997375

Simulating Trading Days:  37%|███▋      | 37/100 [00:43<01:13,  1.17s/it]

Raw prediction for UL: 0.36456942558288574
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6324933171272278
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.4338836371898651
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48942235112190247
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.36221185326576233
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5187009572982788
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5988205671310425
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5015522241592407
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47335782647132874
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6156137585639954
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.727)
[PORT] Sector Financial: sampled C from top-3 (p=0.551)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.600)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled VZ from top-3 (p=0.615)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49564608931541443
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.524880051612854
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4973256289958954
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49189648032188416
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8409349918365479
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4994991719722748
Calibrated prediction for AMGN: 0.5
Raw prediction for AMZN: 0.5386686325073242
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.328530877828598
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5247097611427307
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4478617310523987
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4969005882740021
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48680582642555237
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49620479345321655
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.39268314838409424
Calibrated prediction for BP: 0.3112063407897949
Raw prediction for BRK-A: 0.4837735891342163
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46218448877334595
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5477880835533142
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5400817394256592
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4833112359046936
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.7017965316772461
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.48054683208465576
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5746598839759827
Calibrated prediction for CHTR: 0.6363636255264282
Raw prediction for CMCSA: 0.5194878578186035
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5016264319419861
Calibrated prediction for CODI: 0.6000000238418579
Raw prediction for CSCO: 0.6162807941436768
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4652726352214813
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4756374657154083
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5250331163406372
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.453478068113327
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5331829190254211
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5378094911575317
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5239478349685669
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3690508306026459
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4568372368812561
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5452407002449036
Calibrated prediction for GOOG: 0.409834086894989
Raw prediction for HD: 0.5159611701965332
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5284186601638794
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.48009324073791504
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.42558926343917847
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5384728312492371
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6453872323036194
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.512222409248352
Calibrated prediction for JNJ: 0.5204856991767883
Raw prediction for JPM: 0.4735381007194519
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4825613498687744
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49324285984039307
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.44575679302215576
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5641623735427856
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.20703907310962677
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48451054096221924
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.343119740486145
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4681902229785919
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5703058838844299
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5204916596412659
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5155207514762878
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.3225098252296448
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.2890338599681854
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5316353440284729
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5311519503593445
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4461112320423126
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.46715202927589417
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.2099456638097763
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.47870418429374695
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5124245285987854
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4522768259048462
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5058000087738037
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4640231132507324
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.362164705991745
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6392369270324707
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.519610583782196
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4939541518688202
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46911755204200745
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48954498767852783
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5276287198066711
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5105788707733154
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.49267199635505676
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5042058825492859
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5113074779510498
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.36100661754608154
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6326779127120972
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.410339891910553
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48919054865837097
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3405340909957886
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5199969410896301
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5979781150817871
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  38%|███▊      | 38/100 [00:44<01:12,  1.17s/it]

Raw prediction for WFC: 0.5014888048171997
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.47032085061073303
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6016417741775513
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.727)
[PORT] Sector Financial: sampled C from top-3 (p=0.537)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.636)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.4961032569408417
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5245641469955444
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4970106780529022
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4919759929180145
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8699517250061035
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.49804216623306274
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5375533103942871
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.2988869547843933
Calibrated prediction for BA: 0.34994617104530334
Raw prediction for BABA: 0.5220366716384888
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44762226939201355
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4972837567329407
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4860047996044159
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4971855580806732
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.37848442792892456
Calibrated prediction for BP: 0.3112063407897949
Raw prediction for BRK-A: 0.48567113280296326
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.462204247713089
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5438502430915833
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5398396849632263
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48303255438804626
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6445294618606567
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4790608286857605
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5651962161064148
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5195924639701843
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5232696533203125
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6232813596725464
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4657120108604431
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4756375253200531
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5257025361061096
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4538886249065399
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5329883098602295
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5372697710990906
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5236393213272095
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3678674101829529
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.46133482456207275
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.539324164390564
Calibrated prediction for GOOG: 0.409834086894989
Raw prediction for HD: 0.5151916742324829
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5232349634170532
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4861063063144684
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4252665936946869
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5268482565879822
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6187911033630371
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5120699405670166
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.47034475207328796
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4813843071460724
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4947274625301361
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.453502357006073
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5590670108795166
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.20337249338626862
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4842149615287781
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.33026760816574097
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4667503833770752
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5766196846961975
Calibrated prediction for MSFT: 0.5862069129943848
Raw prediction for NEE: 0.5201922059059143
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5123351812362671
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.30663707852363586
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.27290254831314087
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5268860459327698
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5308145880699158
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.442011296749115
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.46860212087631226
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.2301364690065384
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.47927913069725037
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5122923254966736
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4387262761592865
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.50595623254776
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4647771120071411
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.36286112666130066
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6445786952972412
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5173147320747375
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49396374821662903
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4693545699119568
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4893520474433899
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5496823787689209
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5214690566062927
Calibrated prediction for T: 0.5567010045051575

Simulating Trading Days:  39%|███▉      | 39/100 [00:46<01:11,  1.17s/it]

Raw prediction for TM: 0.49282366037368774
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5050132274627686
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5116384625434875
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.36022496223449707
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6533398628234863
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.38279497623443604
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4889419674873352
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3235336244106293
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5212073922157288
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.59920734167099
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5014001131057739
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.46696943044662476
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5877606272697449
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.727)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.4963459074497223
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5253087878227234
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4969460368156433
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4920145571231842
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8873315453529358
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.49756455421447754
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5369436144828796
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.2867527902126312
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.5199422836303711
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44789281487464905
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4979020059108734
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4855934977531433
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49899744987487793
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.35960447788238525
Calibrated prediction for BP: 0.3112063407897949
Raw prediction for BRK-A: 0.4873347580432892
Calibrated prediction for BRK-A: 0.4675177037715912
Raw prediction for BSAC: 0.4622558057308197
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5414586663246155
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.539682924747467
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48282426595687866
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6291899085044861
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.47810131311416626
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5618363618850708
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5196670889854431
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5450916290283203
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6272466778755188
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46662643551826477
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4743553400039673
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5261799097061157
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4544549584388733
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5327630043029785
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5332126021385193
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.523438036441803
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.38409870862960815
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4675038158893585
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5396025776863098
Calibrated prediction for GOOG: 0.409834086894989
Raw prediction for HD: 0.51475590467453
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.520404040813446
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49299323558807373
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4276447296142578
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5175119638442993
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5941373705863953
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5119691491127014
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.47012433409690857
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4804222583770752
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4973428249359131
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4782606065273285
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5556502342224121
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.21107402443885803
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4842686951160431
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3212070167064667
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4656257927417755
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5861064195632935
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5193188786506653
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5091376900672913
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2996048629283905
Calibrated prediction for NVS: 0.28947368264198303
Raw prediction for ORCL: 0.26133525371551514
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5222219824790955
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5303863286972046
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4394347071647644
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.4733406901359558
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.25637131929397583
Calibrated prediction for PG: 0.20000000298023224
Raw prediction for PICO: 0.4798668920993805
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5121481418609619
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4288572072982788
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5066028833389282
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4654174745082855
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3638346791267395
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6541351079940796
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5178831815719604
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4939737617969513
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4691387414932251
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4890705347061157
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5720708966255188
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5315263271331787
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.49298006296157837
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5061267614364624
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5120139122009277
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.35971540212631226
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6756119728088379
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.3649786710739136
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4887622594833374
Calibrated prediction for UPS: 0.488449364900589
Raw prediction for UTX: 0.3383266031742096
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5218597054481506
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.602170467376709
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  40%|████      | 40/100 [00:47<01:10,  1.17s/it]

Raw prediction for WFC: 0.5014580488204956
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.46402931213378906
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5730688571929932
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49666252732276917
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5232722759246826
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49709638953208923
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49192696809768677
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.9180368781089783
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4961217939853668
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5381098389625549
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.2902369797229767
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.5178143978118896
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44861936569213867
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4985298216342926
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48577287793159485
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5023471117019653
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.3545219898223877
Calibrated prediction for BP: 0.3112063407897949
Raw prediction for BRK-A: 0.4890577495098114
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4624943137168884
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5388343334197998
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5396876335144043
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4826826751232147
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6590002775192261
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.47820451855659485
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5655494928359985
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.519599974155426
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5683910250663757
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6315682530403137
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46774083375930786
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.478259414434433
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.526496171951294
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4550723135471344
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5324696898460388
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5317843556404114
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5235729813575745
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.41750985383987427
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.47046956419944763
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5487107634544373
Calibrated prediction for GOOG: 0.43798333406448364
Raw prediction for HD: 0.5145018100738525
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5189489722251892
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5014599561691284
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.430953711271286
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5155360698699951
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5816857814788818
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5118406414985657
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.473092645406723
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4797002375125885
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49951303005218506
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5037898421287537
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5613790154457092
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.23356881737709045
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4846653938293457
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3174722194671631
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.46463268995285034
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5997841954231262
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5187212824821472
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5076984167098999
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2919254004955292
Calibrated prediction for NVS: 0.27156636118888855
Raw prediction for ORCL: 0.25815725326538086
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5178350806236267
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5298207402229309
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4410572946071625
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.48256251215934753
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.288331001996994
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4805389940738678
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5121598839759827
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4257138967514038
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5076525807380676
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46601784229278564
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.36500412225723267
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6637673377990723
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5149484276771545
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.493938684463501
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4686906337738037
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4886949956417084
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5867835879325867
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5439388155937195
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4928613007068634
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5071173906326294
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.512434720993042
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3606967628002167
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6967028379440308
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.35843947529792786
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48882296681404114
Calibrated prediction for UPS: 0.488449364900589
Raw prediction for UTX: 0.3621571362018585
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.522610068321228
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6054896116256714
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5016167759895325
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4615604281425476
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5636516809463501
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.588)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)

Simulating Trading Days:  41%|████      | 41/100 [00:48<01:09,  1.18s/it]

Raw prediction for AAPL: 0.4972141981124878
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5190555453300476
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49780070781707764
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4917043447494507
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.9415141940116882
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.49335581064224243
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5391392111778259
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.30412423610687256
Calibrated prediction for BA: 0.5158212184906006
Raw prediction for BABA: 0.5161954164505005
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44988948106765747
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4991375207901001
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4854470193386078
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5058883428573608
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.3630506098270416
Calibrated prediction for BP: 0.3112063407897949
Raw prediction for BRK-A: 0.4901803433895111
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4622119963169098
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5361281633377075
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.539899468421936
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4825569689273834
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6765927076339722
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4795641601085663
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5716665983200073
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5194830894470215
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5858389735221863
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6342997550964355
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4686245918273926
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4770476520061493
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5267871618270874
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45572948455810547
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5322551131248474
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5262324213981628
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.523844301700592
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4585217535495758
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4731108844280243
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5558676719665527
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5142876505851746
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5182645320892334
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.509070098400116
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.4318806231021881
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5152279138565063
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5842249393463135
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5116556286811829
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4764392673969269
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.47907668352127075
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5013372898101807
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5371802449226379
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5644927620887756
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.25517773628234863
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48511838912963867
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.3068923056125641
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4637414515018463
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6101208925247192
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5179941654205322
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5063417553901672
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.27419349551200867
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.25393837690353394
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.514219343662262
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5291468501091003
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.44316068291664124
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.4912564158439636
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.3201764225959778
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.481068879365921
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5120574831962585
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4243953227996826
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5087829828262329
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4663313925266266
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3668496310710907
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6698657274246216
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5267518758773804
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4938196837902069
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46778228878974915
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48825275897979736
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5977266430854797
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5554970502853394
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.49267083406448364
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5082126259803772
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5130119323730469
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.35935643315315247
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6998539566993713
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.3570910394191742
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48905807733535767
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.39622923731803894
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5232342481613159
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6087861657142639
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5014317631721497
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4589948356151581
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  42%|████▏     | 42/100 [00:49<01:08,  1.18s/it]

Raw prediction for XOM: 0.5470245480537415
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-06-12 00:00:00: MA p_up_1d=0.317 -> exit; r=-0.0185, PnL=$-53.29
Raw prediction for AAPL: 0.4975310266017914
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.511223554611206
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.4990173876285553
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49143731594085693
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.9541613459587097
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4891165494918823
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5400751829147339
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3232758045196533
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5148494243621826
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.451137512922287
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4995212256908417
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4850643575191498
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5094294548034668
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.3957875669002533
Calibrated prediction for BP: 0.3112063407897949
Raw prediction for BRK-A: 0.4907721281051636
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46190348267555237
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5319743752479553
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5400248765945435
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4824453890323639
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6577906608581543
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4824257493019104
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5791216492652893
Calibrated prediction for CHTR: 0.6363636255264282
Raw prediction for CMCSA: 0.5193081498146057
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5960535407066345
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6341522932052612
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4690924286842346
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.47654303908348083
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5270280241966248
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45611563324928284
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5320109128952026
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5209037661552429
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5240316390991211
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4908684492111206
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.47499793767929077
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5616968870162964
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5143983364105225
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5172175765037537
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5152924656867981
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.4330694079399109
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.515884518623352
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5840131044387817
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5113988518714905
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4797755181789398
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.47852057218551636
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5023980140686035
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.576328456401825
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.570063054561615
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.27393025159835815
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48566296696662903
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2962215542793274
Calibrated prediction for MO: 0.6857596635818481
Raw prediction for MRK: 0.4626629054546356
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6210928559303284
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.517299234867096
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5064908862113953
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.24602332711219788
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.25309908390045166
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5091778635978699
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5285542011260986
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4460228979587555
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.5001915097236633
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.3551075756549835
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4810667932033539
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5120123028755188
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4238949418067932
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5097222328186035
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4666927456855774
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.37132081389427185
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6752079725265503
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5255162715911865
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4934908449649811
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4667111337184906
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4878549873828888
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6069594621658325
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5670672655105591
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.492416113615036
Calibrated prediction for TM: 0.4762147068977356

Simulating Trading Days:  43%|████▎     | 43/100 [00:50<01:07,  1.18s/it]

Raw prediction for TOT: 0.5090749859809875
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5135806798934937
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.353943794965744
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6854123473167419
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.35787612199783325
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48929715156555176
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.42475494742393494
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5236682891845703
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6118733286857605
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5012910962104797
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45648011565208435
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5347005128860474
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.636)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49752914905548096
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.506199300289154
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5010880827903748
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49119657278060913
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.951374351978302
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.48512354493141174
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.540833592414856
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3559085428714752
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5143496990203857
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4522206485271454
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.499796599149704
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48449161648750305
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.511390745639801
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.43292221426963806
Calibrated prediction for BP: 0.3333333432674408
Raw prediction for BRK-A: 0.49095210433006287
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46178755164146423
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5277249217033386
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5400490760803223
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48228150606155396
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6058008670806885
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4851206839084625
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5881587266921997
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5190204381942749
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5953413248062134
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6368436217308044
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46941933035850525
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.47716018557548523
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5272887945175171
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4563291370868683
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5318397879600525
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5155144333839417
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5239784121513367
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5360754132270813
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4764460325241089
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5636702179908752
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5147958993911743
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5167707204818726
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5203193426132202
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.43329811096191406
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.512225866317749
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5865679383277893
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5110700130462646
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4812740087509155
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.47811052203178406
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5031622648239136
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.6266260147094727
Calibrated prediction for MA: 0.75
Raw prediction for MCD: 0.5741240382194519
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.2851944863796234
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4865012764930725
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2856747508049011
Calibrated prediction for MO: 0.43519318103790283
Raw prediction for MRK: 0.46184372901916504
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6306276917457581
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5167043209075928
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5068491101264954
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.222396120429039
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2504165470600128
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.503602921962738
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5280287265777588
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4469926953315735
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.5108039379119873
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4003472924232483
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.48080649971961975
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5120419859886169
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.42474550008773804
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5102554559707642
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4667344093322754
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3763042390346527
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6762339472770691
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5262945294380188
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4929550290107727
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4659295082092285
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4875467121601105
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6143565773963928
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5782172083854675
Calibrated prediction for T: 0.5567010045051575
Raw prediction for TM: 0.4923384487628937
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5096350908279419
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5142174959182739
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.34810298681259155
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6758828163146973
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.369996041059494
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4896267056465149
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4434356987476349
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5239837169647217
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.613832950592041
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5010378360748291
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  44%|████▍     | 44/100 [00:51<01:06,  1.18s/it]

Raw prediction for WMT: 0.4538596570491791
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5211182832717896
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-2 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.750)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.593)
[EARLY EXIT] 2017-06-14 00:00:00: MA p_up_1d=0.381 -> exit; r=0.0015, PnL=$3.93
Raw prediction for AAPL: 0.4976540505886078
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.503924548625946
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5038950443267822
Calibrated prediction for ABBV: 0.5
Raw prediction for AEP: 0.4910042881965637
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.9224112629890442
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4828886389732361
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5414143800735474
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.39828380942344666
Calibrated prediction for BA: 0.603232204914093
Raw prediction for BABA: 0.5145801901817322
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4532126784324646
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5000796318054199
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4840756058692932
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5131204724311829
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.46439406275749207
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.49115562438964844
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4615490734577179
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5248162150382996
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5399121642112732
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4821229577064514
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5716381072998047
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4877626895904541
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5964719653129578
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5186756253242493
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5877062678337097
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6434503793716431
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4695272743701935
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.47882160544395447
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5274212956428528
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45636725425720215
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5316910147666931
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5110898613929749
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5240191221237183
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5822451114654541
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.4823233485221863
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5675953030586243
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5154849290847778
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5182558298110962
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5244741439819336
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.43404513597488403
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.5061655044555664
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.596772313117981
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5106180906295776
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.481598824262619
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4777970314025879
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5040583610534668
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.67513108253479
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.5741546154022217
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.29943665862083435
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.487214058637619
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2693626582622528
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4616219103336334
Calibrated prediction for MRK: 0.49753454327583313
Raw prediction for MSFT: 0.6401475071907043
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5159661769866943
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5079088807106018
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.20654234290122986
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2540144920349121
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5011110305786133
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5275991559028625
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.44609007239341736
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.5169925689697266
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.4599187970161438
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.48055410385131836
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5120800137519836
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4331565797328949
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.510695219039917
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46666231751441956
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3820437490940094
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6748119592666626
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5328077673912048
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4925808310508728
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4652807414531708
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48725706338882446
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6197001934051514
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.5909152626991272
Calibrated prediction for T: 0.5590301752090454

Simulating Trading Days:  45%|████▌     | 45/100 [00:53<01:04,  1.18s/it]

Raw prediction for TM: 0.4925343096256256
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.510012686252594
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5150914192199707
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.34623512625694275
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.679793119430542
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.3864462971687317
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48991942405700684
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.46502596139907837
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5240907073020935
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6149298548698425
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5008148550987244
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45055240392684937
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5199850797653198
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.632)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-2 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49743980169296265
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5072618126869202
Calibrated prediction for ABB: 0.5199999809265137
Raw prediction for ABBV: 0.5068952441215515
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.490660697221756
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8400260210037231
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4809875786304474
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5419694781303406
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4384508430957794
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.51556396484375
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.45360079407691956
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5001698136329651
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48378580808639526
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.514861524105072
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5006236433982849
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4913419187068939
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46088701486587524
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5242547988891602
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5395846962928772
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48201048374176025
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5598813891410828
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4903745651245117
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.602910578250885
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.518355131149292
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.579618513584137
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6460826396942139
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4694221317768097
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.47695475816726685
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5273058414459229
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45649099349975586
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.53166264295578
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5044888257980347
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5240715742111206
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.609049379825592
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.49140307307243347
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5699555277824402
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5162778496742249
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5218233466148376
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5276185274124146
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.43541595339775085
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.4980214238166809
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6069304943084717
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5101472735404968
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4790080189704895
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.47793304920196533
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5044723153114319
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7170849442481995
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.5677489638328552
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3181311786174774
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48766225576400757
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2539721131324768
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46219584345817566
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.646953821182251
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5149755477905273
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.508415699005127
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2080259621143341
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.26177331805229187
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.4984237849712372
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5273703336715698
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4482867121696472
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.5179630517959595
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.5220047831535339
Calibrated prediction for PG: 0.5384615659713745
Raw prediction for PICO: 0.4801870286464691
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5121043920516968
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4578767418861389
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5111801028251648
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46676260232925415
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3875829875469208
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6723999977111816
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5221441388130188
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49278372526168823
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46412622928619385
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4870254397392273
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6234865784645081
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6011151075363159
Calibrated prediction for T: 0.5909090638160706
Raw prediction for TM: 0.49304473400115967
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5103957056999207
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5160273909568787
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3475242853164673
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.6924865245819092
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.4039064943790436
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.490201860666275
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4886331260204315
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5241159200668335
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6149629950523376
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5005670189857483
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  46%|████▌     | 46/100 [00:54<01:03,  1.18s/it]

Raw prediction for WMT: 0.4480232894420624
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5195291042327881
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.632)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.4969477951526642
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5129790306091309
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5100888013839722
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.49026793241500854
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.6871930360794067
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4801163375377655
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.545814573764801
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.467385470867157
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5170643925666809
Calibrated prediction for BABA: 0.5442423820495605
Raw prediction for BAC: 0.452911913394928
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5001142621040344
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48360687494277954
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5153744220733643
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5303365588188171
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4913296699523926
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46061205863952637
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5279337167739868
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5390467643737793
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48204660415649414
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5745432376861572
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49407926201820374
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.621664822101593
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5176671743392944
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.566895067691803
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6436207890510559
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46908459067344666
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4757668077945709
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5269104242324829
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4563252925872803
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5315619707107544
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.49851882457733154
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5240197777748108
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.6134827733039856
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.4991733431816101
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5712999701499939
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5165227055549622
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.525556206703186
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5295526385307312
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.43553388118743896
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.4930132031440735
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6116783022880554
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5098146200180054
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4734072983264923
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4788302481174469
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5044339895248413
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7431308627128601
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.5780937075614929
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3355086147785187
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4879411458969116
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2457854449748993
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4640160799026489
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6523827314376831
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5141907930374146
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.510205090045929
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2143239825963974
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.27475136518478394
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5007509589195251
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5272471904754639
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.45510804653167725
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.5165968537330627
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.5974045395851135
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.4796917140483856
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5123205184936523
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5125688314437866
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5114836692810059
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46679797768592834
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3930324614048004
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6684228181838989
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5119515061378479
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49326205253601074
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46348297595977783
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4868795871734619
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6260123252868652
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6114364266395569
Calibrated prediction for T: 0.5909090638160706
Raw prediction for TM: 0.4937747120857239
Calibrated prediction for TM: 0.4762147068977356

Simulating Trading Days:  47%|████▋     | 47/100 [00:55<01:02,  1.18s/it]

Raw prediction for TOT: 0.5104913711547852
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5168197751045227
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3613920509815216
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.7225927710533142
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.42900505661964417
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49035128951072693
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5190122723579407
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5239832997322083
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6144607067108154
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5002858638763428
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.44667166471481323
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5241000056266785
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.4967866837978363
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5207494497299194
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5130112767219543
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48974061012268066
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.4094602167606354
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4784512221813202
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.54712975025177
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4892113506793976
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5192302465438843
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.45078715682029724
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49994027614593506
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48357731103897095
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5149534940719604
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5520665049552917
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4919537305831909
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.460846483707428
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5321484804153442
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5382574200630188
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48213571310043335
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5776631236076355
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4992871880531311
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6345928907394409
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5170955657958984
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5600416660308838
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6425253748893738
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4682508409023285
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4724351167678833
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.526242733001709
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4558435380458832
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5316225290298462
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4940354824066162
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5246660709381104
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.6103072166442871
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.5012046098709106
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5810434222221375
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5172680616378784
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5293606519699097
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5303847193717957
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.42957088351249695
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.4842168688774109
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6310645341873169
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5094700455665588
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4645040035247803
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4803115129470825
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5039308071136475
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.7166135311126709
Calibrated prediction for MA: 0.7948718070983887
Raw prediction for MCD: 0.5920438766479492
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3506365716457367
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4881089925765991
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.25193774700164795
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46543389558792114
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6598702073097229
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5135365724563599
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5125571489334106
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.221902996301651
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3033120334148407
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5065272450447083
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5275188684463501
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4654234051704407
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.516019344329834
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.6721341609954834
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.47906750440597534
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5128544569015503
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5883815884590149
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5117107033729553
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4666729271411896
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3978748023509979
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6639297008514404
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5029117465019226
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49347132444381714
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46365389227867126
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.486754834651947
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6265444159507751
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6260045766830444
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.4943222999572754
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5102464556694031
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.51727294921875
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3813922107219696
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.7407189011573792
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.4520217478275299
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49055784940719604
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5329629778862
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5240434408187866
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6123026013374329
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.49966904520988464
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.44646844267845154
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  48%|████▊     | 48/100 [00:56<01:01,  1.18s/it]

Raw prediction for XOM: 0.5517310500144958
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.795)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.49794721603393555
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5298249125480652
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5151384472846985
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4888661205768585
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.2051156908273697
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.477099746465683
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.547868013381958
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5014485716819763
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5221288204193115
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4482386112213135
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4998292922973633
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48339006304740906
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5144867897033691
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.567537248134613
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4920401871204376
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4609355330467224
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5348778367042542
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5375468134880066
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4825206398963928
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5697807669639587
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.506089448928833
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6428934931755066
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5167349576950073
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5614646673202515
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6435278654098511
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46683216094970703
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4627644121646881
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5253766179084778
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.455645352602005
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.53180992603302
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.48611757159233093
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5259221196174622
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.6091479659080505
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.5099852681159973
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.591421902179718
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5173557996749878
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5326388478279114
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5299493670463562
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.42017388343811035
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.46809515357017517
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6666378378868103
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5091155767440796
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.45547306537628174
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48191890120506287
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5024527907371521
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.6443074345588684
Calibrated prediction for MA: 0.7692307829856873
Raw prediction for MCD: 0.6047434210777283
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.35684528946876526
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48823103308677673
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.25814247131347656
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46622100472450256
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6577925086021423
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5125178098678589
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5148677229881287
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2272971272468567
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3373609781265259
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.517815887928009
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5282636284828186
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47256147861480713
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5155534744262695
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.735698401927948
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4785655438899994
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5137816667556763
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6543445587158203
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5118985176086426
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4663253426551819
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4027738571166992
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6586949229240417
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.4947362244129181
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49380457401275635
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4627549946308136
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.48653101921081543
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.6186126470565796
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6376227140426636
Calibrated prediction for T: 0.6000000238418579
Raw prediction for TM: 0.4945306181907654
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5101895928382874
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5175191760063171
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.40898269414901733
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.7451527714729309
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.4784156084060669
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49073848128318787
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5563067197799683
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5239235162734985
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6103898882865906
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.4992755353450775
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.44797104597091675
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5845279097557068
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.769)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:  49%|████▉     | 49/100 [00:57<01:00,  1.19s/it]

Raw prediction for AAPL: 0.49971839785575867
Calibrated prediction for AAPL: 0.5
Raw prediction for ABB: 0.5349329113960266
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5165535807609558
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48780858516693115
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.12156300991773605
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4764973521232605
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5486593842506409
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.504550576210022
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5246400833129883
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4460735321044922
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4998946487903595
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.482759565114975
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5144206881523132
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5748082399368286
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.49186286330223083
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4605826139450073
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5369600057601929
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5371447801589966
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4826083779335022
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5455795526504517
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5113286375999451
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6448030471801758
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5165708065032959
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5478770732879639
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.643277645111084
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46530160307884216
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.44661372900009155
Calibrated prediction for D: 0.5384615659713745
Raw prediction for DHR: 0.5245509147644043
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4557686150074005
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5318052768707275
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.47150442004203796
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5268070697784424
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5870521664619446
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.5192742943763733
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.593156635761261
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5173770189285278
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5332634449005127
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5286940932273865
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.4087698459625244
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4432064890861511
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7070968747138977
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5088372230529785
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.45007482171058655
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4833676517009735
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5004013776779175
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5850740671157837
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6036432981491089
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.35595399141311646
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4883328974246979
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.26039010286331177
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46781083941459656
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6467578411102295
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5110326409339905
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5159846544265747
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2245437055826187
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.37142518162727356
Calibrated prediction for ORCL: 0.4794520437717438
Raw prediction for PCG: 0.5274092555046082
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5290281176567078
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4750719666481018
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5180702209472656
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7739347815513611
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.478556364774704
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5146633386611938
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6971726417541504
Calibrated prediction for PPL: 0.75
Raw prediction for PTR: 0.5119534134864807
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4656708538532257
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.40617629885673523
Calibrated prediction for REX: 0.36910319328308105
Raw prediction for SLB: 0.6513488292694092
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5005996823310852
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4941074848175049
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4616239368915558
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.486307829618454
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.6036092042922974
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6502218246459961
Calibrated prediction for T: 0.6666666865348816
Raw prediction for TM: 0.4947129487991333
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5103064775466919
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5175461173057556
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4358716905117035
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.7227333784103394
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.4937545955181122
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49078550934791565
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5590655207633972
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5236867666244507
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6094079613685608
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.4990183413028717
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.450064480304718
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  50%|█████     | 50/100 [00:59<00:59,  1.19s/it]

Raw prediction for XOM: 0.6051474213600159
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.750)
Raw prediction for AAPL: 0.5015590190887451
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5399616956710815
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5178136825561523
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4867856800556183
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.1085783988237381
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4753606617450714
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5486193299293518
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.500199019908905
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5256842970848083
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.4452633261680603
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4999566078186035
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4821119010448456
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5149531960487366
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5840399861335754
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4914398491382599
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.46016404032707214
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5385159254074097
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5371396541595459
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4823749363422394
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5073169469833374
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5142872333526611
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6426276564598083
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5164535641670227
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5355747938156128
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6384152173995972
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46417245268821716
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4270251393318176
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5239092707633972
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4559893012046814
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5314434766769409
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4522276818752289
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5274608731269836
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5558795928955078
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.523552417755127
Calibrated prediction for GE: 0.5781235098838806
Raw prediction for GOOG: 0.5897505879402161
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5186508893966675
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5327164530754089
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5261602997779846
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.40084636211395264
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4196561872959137
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7480814456939697
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5084143280982971
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4474499821662903
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4846309423446655
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49784010648727417
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5586439967155457
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5973970890045166
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3503614664077759
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48848623037338257
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2559811472892761
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4693368673324585
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6350839734077454
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5094130039215088
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5168086290359497
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.21503010392189026
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3910519778728485
Calibrated prediction for ORCL: 0.4794520437717438
Raw prediction for PCG: 0.5297436714172363
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5296481251716614
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47306883335113525
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5232234001159668
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7931486368179321
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.47882455587387085
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5153272747993469
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.7165279388427734
Calibrated prediction for PPL: 0.75
Raw prediction for PTR: 0.5119994282722473
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46523141860961914
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4064790904521942
Calibrated prediction for REX: 0.37062641978263855
Raw prediction for SLB: 0.6455695033073425
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5001575350761414
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49416646361351013
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4603578746318817
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4862937331199646
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5831794142723083
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6621379256248474
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49456560611724854
Calibrated prediction for TM: 0.4762147068977356

Simulating Trading Days:  51%|█████     | 51/100 [01:00<00:58,  1.19s/it]

Raw prediction for TOT: 0.5107527375221252
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5173059105873108
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.45722687244415283
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6793233752250671
Calibrated prediction for UN: 0.8648648858070374
Raw prediction for UNH: 0.4961501955986023
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49078118801116943
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5561878681182861
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5234259366989136
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.607970654964447
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.49891629815101624
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45228511095046997
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6138235330581665
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled UN from top-3 (p=0.865)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.750)
Raw prediction for AAPL: 0.5033422708511353
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5457088351249695
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5184924006462097
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4859440326690674
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.17150412499904633
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4752173125743866
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5484820008277893
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.48436427116394043
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5248135924339294
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44489720463752747
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49985045194625854
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48154547810554504
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5150952935218811
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5926740765571594
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.49076902866363525
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4599300026893616
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5402554273605347
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5373455286026001
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.482193261384964
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.48354291915893555
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.515794575214386
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6400226354598999
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5164024233818054
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5250840187072754
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.627410888671875
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46360793709754944
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.40582072734832764
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5235688090324402
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4564895033836365
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5310800075531006
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4357551336288452
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5280388593673706
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5152732729911804
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.522808849811554
Calibrated prediction for GE: 0.5781235098838806
Raw prediction for GOOG: 0.5893053412437439
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5211149454116821
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5303288698196411
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5234069228172302
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.3974137306213379
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.39696037769317627
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7796555757522583
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5080785751342773
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.44732704758644104
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4855203628540039
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4957796633243561
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5405665636062622
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5913137197494507
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3467426002025604
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48861950635910034
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.2456786185503006
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.47066882252693176
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6234450936317444
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5079073905944824
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5179336667060852
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.2128608375787735
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3968902826309204
Calibrated prediction for ORCL: 0.4794520437717438
Raw prediction for PCG: 0.5282979011535645
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5301979780197144
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4691493511199951
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.52898770570755
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7991650104522705
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4792355000972748
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.515828549861908
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.7134664058685303
Calibrated prediction for PPL: 0.75
Raw prediction for PTR: 0.5119114518165588
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4650993347167969
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.405313640832901
Calibrated prediction for REX: 0.3647635281085968
Raw prediction for SLB: 0.6417967081069946
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.4988023042678833
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4941027760505676
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.45937487483024597
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4864460229873657
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5540120601654053
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6710838675498962
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49422264099121094
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5112397074699402
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5168907642364502
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4748857021331787
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.6308938264846802
Calibrated prediction for UN: 0.7272727489471436
Raw prediction for UNH: 0.487101674079895
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4908464550971985
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.55998694896698
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5230023264884949
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6064761877059937
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.499060720205307
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4540150761604309
Calibrated prediction for WMT: 0.4833378791809082

Simulating Trading Days:  52%|█████▏    | 52/100 [01:01<00:56,  1.18s/it]

Raw prediction for XOM: 0.6246753334999084
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.750)
[EARLY EXIT] 2017-06-26 00:00:00: UTX p_up_1d=0.119 -> exit; r=-0.0029, PnL=$-5.23
[EARLY EXIT] 2017-06-26 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0011, PnL=$0.58
Raw prediction for AAPL: 0.5049026012420654
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5452499389648438
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5186739563941956
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4853858947753906
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.5296723246574402
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4753805100917816
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5493072867393494
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.463101327419281
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5211201310157776
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44516804814338684
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49994218349456787
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48119714856147766
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5159091949462891
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5960608720779419
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.489803284406662
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4596703052520752
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5411603450775146
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5376274585723877
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4821333885192871
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4645785093307495
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5166165232658386
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6438933610916138
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5161152482032776
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5241469144821167
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6168940663337708
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46323710680007935
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.38999927043914795
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5233107805252075
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.456999272108078
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5307184457778931
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4228547513484955
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5284217000007629
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.47692495584487915
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5193095207214355
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5901771783828735
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5253767371177673
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.527109682559967
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5208473205566406
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.3966289162635803
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.39852526783943176
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7958115339279175
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.507735013961792
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4488508701324463
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4862552881240845
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4940028488636017
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5256450176239014
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5977518558502197
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.34895622730255127
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48911750316619873
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.23283056914806366
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4725736677646637
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6150628328323364
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5068566799163818
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5196476578712463
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.21078065037727356
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3941161632537842
Calibrated prediction for ORCL: 0.4794520437717438
Raw prediction for PCG: 0.5238959789276123
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5308014154434204
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4670828580856323
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5350775718688965
Calibrated prediction for PFE: 0.5732513666152954
Raw prediction for PG: 0.7979458570480347
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4797120690345764
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5162001848220825
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.7028767466545105
Calibrated prediction for PPL: 0.75
Raw prediction for PTR: 0.5117440819740295
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46507003903388977
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4022871255874634
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.642419159412384
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.506991982460022
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49409019947052
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4586157202720642
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.48639073967933655
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.5220979452133179
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.680084764957428
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49384742975234985
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5110698938369751
Calibrated prediction for TOT: 0.5130005478858948

Simulating Trading Days:  53%|█████▎    | 53/100 [01:02<00:55,  1.18s/it]

Raw prediction for TSM: 0.5165936946868896
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.48452407121658325
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5792416930198669
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4829833209514618
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49086374044418335
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5625556111335754
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5223007798194885
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6064838767051697
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.4991598427295685
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45459121465682983
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6741959452629089
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.750)
[EARLY EXIT] 2017-06-27 00:00:00: UTX p_up_1d=0.119 -> exit; r=-0.0023, PnL=$-4.92
[EARLY EXIT] 2017-06-27 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0077, PnL=$14.00
Raw prediction for AAPL: 0.5059877038002014
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5390313863754272
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5189703106880188
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4850796163082123
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.7912067174911499
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4747276306152344
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5481337308883667
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4439642131328583
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5175537467002869
Calibrated prediction for BABA: 0.5605446696281433
Raw prediction for BAC: 0.44525954127311707
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5000036358833313
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4807429015636444
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5162729024887085
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5885007977485657
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4889087975025177
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.4597502648830414
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5421631932258606
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5378447771072388
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48187902569770813
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4327743351459503
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.515717089176178
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6393947601318359
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5161547064781189
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5140807628631592
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6031109690666199
Calibrated prediction for CSCO: 0.5454545617103577
Raw prediction for CVX: 0.4632314443588257
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.3797825574874878
Calibrated prediction for D: 0.3657268285751343
Raw prediction for DHR: 0.5233182907104492
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4572163224220276
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5306063294410706
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4158872067928314
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5281791687011719
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4437721073627472
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5129711627960205
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5874364376068115
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.529134213924408
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5217074155807495
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5169334411621094
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.3993406891822815
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.40429985523223877
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7957038879394531
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5072551965713501
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.45061275362968445
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48635217547416687
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4928582012653351
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5104336738586426
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5905410051345825
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3482780456542969
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48943090438842773
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.21332786977291107
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4738316833972931
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6059953570365906
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5065469145774841
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5223106145858765
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.19918566942214966
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3674543797969818
Calibrated prediction for ORCL: 0.4794520437717438
Raw prediction for PCG: 0.5211776494979858
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5311099886894226
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4640887379646301
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5390444397926331
Calibrated prediction for PFE: 0.5732513666152954
Raw prediction for PG: 0.7749582529067993
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48003605008125305
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5161882042884827
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6811667084693909
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5113834738731384
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46474581956863403
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3969264626502991
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.640462338924408
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5238394141197205
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4933590590953827
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.45900759100914
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.48643913865089417
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4991253912448883
Calibrated prediction for SRE: 0.5625
Raw prediction for T: 0.6852251291275024
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.493867963552475
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5108639597892761
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5165113210678101
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.486025869846344
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5321754217147827
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4662835896015167
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4909781515598297
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5565841197967529
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.521207869052887
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6061961054801941
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  54%|█████▍    | 54/100 [01:03<00:54,  1.18s/it]

Raw prediction for WFC: 0.49926093220710754
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4543137848377228
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6860373616218567
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-06-28 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0075, PnL=$21.64
[EARLY EXIT] 2017-06-28 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0034, PnL=$7.66
Raw prediction for AAPL: 0.5065021514892578
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5366964936256409
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5195054411888123
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48495689034461975
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.8276269435882568
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4726618230342865
Calibrated prediction for AMGN: 0.4761904776096344
Raw prediction for AMZN: 0.5462350845336914
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.43209612369537354
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5140922665596008
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4452918767929077
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4998932182788849
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48038843274116516
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.516465425491333
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5770418643951416
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48766371607780457
Calibrated prediction for BRK-A: 0.4677419364452362
Raw prediction for BSAC: 0.45979467034339905
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5431618690490723
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5380028486251831
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.481564998626709
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.3960171937942505
Calibrated prediction for CELG: 0.4000000059604645
Raw prediction for CHL: 0.5138815641403198
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6346360445022583
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5162035226821899
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5137232542037964
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5952525734901428
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.463363915681839
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.37543538212776184
Calibrated prediction for D: 0.3657268285751343
Raw prediction for DHR: 0.523556649684906
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4571588933467865
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5306105017662048
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4137805700302124
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5277883410453796
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.42566078901290894
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5089731812477112
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5853970050811768
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5321458578109741
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.519088089466095
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5131444931030273
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.4054061770439148
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4049454629421234
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7956634163856506
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.506580650806427
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.45285362005233765
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4862610399723053
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49250754714012146
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5152005553245544
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5874302983283997
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.35061758756637573
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4896499216556549
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.1961657702922821
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4741657078266144
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6001164317131042
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5065076947212219
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5259203910827637
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.18566247820854187
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3345659673213959
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5196520686149597
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5311779975891113
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46021074056625366
Calibrated prediction for PEP: 0.5023928284645081
Raw prediction for PFE: 0.5414664149284363
Calibrated prediction for PFE: 0.5732513666152954
Raw prediction for PG: 0.7587454915046692
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48033738136291504
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5160054564476013
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6612961888313293
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5109870433807373
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46471107006073
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.39087817072868347
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6397048234939575
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5165188908576965
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49236997961997986
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.45947492122650146
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4866441786289215
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4832807779312134
Calibrated prediction for SRE: 0.4322940707206726

Simulating Trading Days:  55%|█████▌    | 55/100 [01:04<00:53,  1.18s/it]

Raw prediction for T: 0.6934486627578735
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49404898285865784
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5106950402259827
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5165820717811584
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4867314398288727
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5033963322639465
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4607546925544739
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49107030034065247
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5513531565666199
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5197250843048096
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6085739731788635
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.49954360723495483
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45441558957099915
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6895555853843689
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.573)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-06-29 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0069, PnL=$-26.35
[EARLY EXIT] 2017-06-29 00:00:00: BP p_up_1d=0.379 -> exit; r=-0.0116, PnL=$-33.84
Raw prediction for AAPL: 0.5066357254981995
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5377134680747986
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5199801325798035
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4844796359539032
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.7880192399024963
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4673094153404236
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5446476936340332
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.428253710269928
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5114942193031311
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4455638825893402
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4998118281364441
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48022764921188354
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5168953537940979
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5688295364379883
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4862001836299896
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.459923654794693
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5443092584609985
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5380796790122986
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4811383783817291
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.3436105251312256
Calibrated prediction for CELG: 0.3913043439388275
Raw prediction for CHL: 0.5124993324279785
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6302990913391113
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5162716507911682
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5157827734947205
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5918436646461487
Calibrated prediction for CSCO: 0.41267725825309753
Raw prediction for CVX: 0.46392807364463806
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.3814963102340698
Calibrated prediction for D: 0.37983185052871704
Raw prediction for DHR: 0.524068295955658
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45702141523361206
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5305612087249756
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.41553109884262085
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5272881388664246
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4160909652709961
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.509032130241394
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.584461510181427
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5341029167175293
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5193475484848022
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5099465847015381
Calibrated prediction for HRG: 0.5931089520454407
Raw prediction for HSBC: 0.4128093421459198
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.4058428704738617
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7917485237121582
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5056782960891724
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4551781713962555
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4861450493335724
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49327006936073303
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5386559963226318
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5847529172897339
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.36112186312675476
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4897805154323578
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.18839260935783386
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4735945463180542
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5956959128379822
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5070120692253113
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5319242477416992
Calibrated prediction for NGG: 0.44940492510795593
Raw prediction for NVS: 0.16674436628818512
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2999997138977051
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5196409821510315
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5309884548187256
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.45789235830307007
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.5400128960609436
Calibrated prediction for PFE: 0.5732513666152954
Raw prediction for PG: 0.7546220421791077
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4806368052959442
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.515964150428772
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6583104729652405
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5108557343482971
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4650518596172333
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.38443371653556824
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6403399109840393
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.509838342666626
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49128493666648865
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4600698947906494
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4864842891693115
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4765876531600952
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.7006464600563049
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4943007528781891
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5107772350311279
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5168026685714722
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4860381484031677
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.48380792140960693
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4571346938610077
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49121084809303284
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5479668378829956
Calibrated prediction for UTX: 0.741931140422821
Raw prediction for V: 0.5181980729103088
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6122379899024963
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  56%|█████▌    | 56/100 [01:06<00:52,  1.19s/it]

Raw prediction for WFC: 0.49984532594680786
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4550432562828064
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6861218214035034
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled ABBV from top-3 (p=0.536)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.742)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
[EARLY EXIT] 2017-06-30 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0038, PnL=$14.04
[EARLY EXIT] 2017-06-30 00:00:00: BP p_up_1d=0.379 -> exit; r=-0.0060, PnL=$-20.74
Raw prediction for AAPL: 0.5065650939941406
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5382657647132874
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5209693312644958
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48451411724090576
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.6359927654266357
Calibrated prediction for AGFS: 0.7227257490158081
Raw prediction for AMGN: 0.46027228236198425
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5426843762397766
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4316674768924713
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5095617771148682
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44638586044311523
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4998506009578705
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48027873039245605
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.517643928527832
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5722985863685608
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4842967092990875
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4602493643760681
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5460183024406433
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5382726192474365
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48072350025177
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.2922805845737457
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.5121484398841858
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6253490447998047
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5164362192153931
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5222684741020203
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.5973948836326599
Calibrated prediction for CSCO: 0.5445908308029175
Raw prediction for CVX: 0.4648527503013611
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.39064502716064453
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5245950818061829
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45674172043800354
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5304896235466003
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4149983525276184
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5267479419708252
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.42880547046661377
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5026131868362427
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.585312008857727
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5347050428390503
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5229014158248901
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5045273303985596
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.419528990983963
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.39908701181411743
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7843114733695984
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5044946074485779
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.45748960971832275
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48614901304244995
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49536147713661194
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5701414346694946
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5799810290336609
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3715762794017792
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4897671341896057
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.1873714178800583
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.47197797894477844
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5950847864151001
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.507497251033783
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5391169786453247
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.15839844942092896
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2815406620502472
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.521916389465332
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5306811332702637
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.45981565117836
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.536378800868988
Calibrated prediction for PFE: 0.5732513666152954
Raw prediction for PG: 0.7705402970314026
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4809453785419464
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5160763263702393
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6640099883079529
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5110364556312561
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46559518575668335
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.379973828792572
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6434983015060425
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5155635476112366
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4898558557033539
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46048563718795776
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.486374169588089
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.46947112679481506
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.7137904763221741
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49438294768333435
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5112159848213196
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5168386697769165
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4872627854347229
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.4751800298690796
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4521464407444
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49136775732040405
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5184852480888367
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.516732931137085
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6153504848480225
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5001295804977417
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4556506276130676
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6787917017936707
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.723)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.573)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:  57%|█████▋    | 57/100 [01:07<00:51,  1.20s/it]

[EARLY EXIT] 2017-07-03 00:00:00: MA p_up_1d=0.381 -> exit; r=-0.0060, PnL=$-22.47
[EARLY EXIT] 2017-07-03 00:00:00: MA p_up_1d=0.381 -> exit; r=-0.0055, PnL=$-23.56
[EARLY EXIT] 2017-07-03 00:00:00: BP p_up_1d=0.379 -> exit; r=0.0107, PnL=$40.87
Raw prediction for AAPL: 0.5065420269966125
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5334020256996155
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5217453241348267
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48459717631340027
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.48488491773605347
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4542601704597473
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5418384075164795
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4363039433956146
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5077143907546997
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4478176534175873
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4999656677246094
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4807319939136505
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.517529308795929
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5790805220603943
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48214536905288696
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4604528844356537
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5477818846702576
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5383908748626709
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48049283027648926
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.2562433183193207
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.5116181373596191
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6234588623046875
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5165202617645264
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5280731916427612
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.602938711643219
Calibrated prediction for CSCO: 0.5454545617103577
Raw prediction for CVX: 0.4659172594547272
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.40154463052749634
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5249694585800171
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4564165771007538
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5303696990013123
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4135274589061737
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5264199376106262
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.45524862408638
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.49135932326316833
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5866292119026184
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5346255302429199
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5304187536239624
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49958300590515137
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4264184534549713
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.3951466679573059
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7751709818840027
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5035329461097717
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.46005693078041077
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48633241653442383
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49753162264823914
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5824559330940247
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5803056955337524
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.37197554111480713
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4897729754447937
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.18731412291526794
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4693496823310852
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5937278866767883
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5081643462181091
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5459167957305908
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14580567181110382
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.26196226477622986
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5267978310585022
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5303271412849426
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4627564251422882
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5318604111671448
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7935681939125061
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4810945391654968
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5164640545845032
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6742399334907532
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5114182829856873
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4661569595336914
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.37752124667167664
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6506991386413574
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5312151908874512
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.48873788118362427
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4607400894165039
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4862397313117981
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.46256524324417114
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.7280898094177246
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4939122796058655
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5117892026901245
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5173752903938293
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.48991620540618896
Calibrated prediction for UL: 0.44285714626312256

Simulating Trading Days:  58%|█████▊    | 58/100 [01:08<00:50,  1.19s/it]

Raw prediction for UN: 0.46760034561157227
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4455096423625946
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4914948344230652
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.47125861048698425
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5156331062316895
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6282920241355896
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5003916621208191
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45643436908721924
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6750311851501465
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5062180161476135
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.529899001121521
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5222355723381042
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4847552478313446
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.37351781129837036
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4511179029941559
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5409582257270813
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.44788020849227905
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5062475204467773
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44955208897590637
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4999716281890869
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4809643626213074
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5170156955718994
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5838747024536133
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4797830879688263
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46088284254074097
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5489069819450378
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5384608507156372
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48028820753097534
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.23003990948200226
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.5111684203147888
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6184450387954712
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5167974829673767
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5224975347518921
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6082279086112976
Calibrated prediction for CSCO: 0.5454545617103577
Raw prediction for CVX: 0.46704694628715515
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4055671691894531
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5251933932304382
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45627039670944214
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5300801992416382
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4059363007545471
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5262945890426636
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.49809062480926514
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.47782763838768005
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.5913346409797668
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.532375693321228
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5365479588508606
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49510982632637024
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.43140557408332825
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.39224183559417725
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7703359723091125
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5027954578399658
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.46232184767723083
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48634472489356995
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4999714493751526
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5878357887268066
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5804424285888672
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3647584617137909
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.489740252494812
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.184912770986557
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46689462661743164
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5946254730224609
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5087414979934692
Calibrated prediction for NEE: 0.5023362636566162
Raw prediction for NGG: 0.5501546263694763
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14136163890361786
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.25233131647109985
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5309938192367554
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5300289988517761
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4649433195590973
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5221039056777954
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8127999901771545
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.481181800365448
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.516737163066864
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6735766530036926
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5115877985954285
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4664754867553711
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3776402473449707
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6584264039993286
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5461180210113525
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4874393939971924
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46062031388282776
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4861578941345215
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4545634686946869
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.7476733326911926
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49331822991371155
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5123441219329834
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5179361701011658
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.48929131031036377
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.454723984003067
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.43462732434272766
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4914608597755432
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.41586416959762573
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5146130919456482
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6397370100021362
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  59%|█████▉    | 59/100 [01:09<00:48,  1.19s/it]

Raw prediction for WFC: 0.5004878044128418
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45717453956604004
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6616829037666321
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled T from top-3 (p=0.703)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.505813479423523
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5273290872573853
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5217182040214539
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4848833382129669
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.32656657695770264
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.451951265335083
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5409296154975891
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.46690407395362854
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5046761631965637
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4505341053009033
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4997013807296753
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48137277364730835
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5164154171943665
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5812406539916992
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4775521159172058
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46111685037612915
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5496111512184143
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5382996201515198
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4801863133907318
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.23678959906101227
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.5117092132568359
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.614477813243866
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5170505046844482
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.513505220413208
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6172962188720703
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4680117964744568
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4124416708946228
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5251188278198242
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4562215805053711
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5298362970352173
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4030802547931671
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5268229842185974
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5334612727165222
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4652375876903534
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.6006409525871277
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5293910503387451
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5424089431762695
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4911763370037079
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.43537816405296326
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.39244991540908813
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7718046307563782
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5020380020141602
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.46410176157951355
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48648834228515625
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5017837882041931
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5767142176628113
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5823962092399597
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3617081344127655
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48964861035346985
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.18649807572364807
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46486109495162964
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5975228548049927
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5101922750473022
Calibrated prediction for NEE: 0.5228320956230164
Raw prediction for NGG: 0.5542488694190979
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14411640167236328
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.247191920876503
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5365604162216187
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.529792308807373
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46883007884025574
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5111225843429565
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8347589373588562
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48141586780548096
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5170512795448303
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6731224656105042
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5114381909370422
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46635204553604126
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.38022175431251526
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6670096516609192
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5477156639099121
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.48646610975265503
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4608999788761139
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.486098974943161
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4529503583908081
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.7704752683639526
Calibrated prediction for T: 0.7028569579124451

Simulating Trading Days:  60%|██████    | 60/100 [01:10<00:47,  1.19s/it]

Raw prediction for TM: 0.492715060710907
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5119308233261108
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5182904601097107
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4856175482273102
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.4357200562953949
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.42592793703079224
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49128827452659607
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.37935739755630493
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5141229629516602
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6526395082473755
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5004580020904541
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4580134451389313
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6511605381965637
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled CODI from top-3 (p=0.660)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled ABBV from top-3 (p=0.536)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5057867169380188
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5284245014190674
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5199511647224426
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4851643443107605
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.5134395956993103
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4520793557167053
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5416415929794312
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.48657453060150146
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5032909512519836
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.45034945011138916
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4992994964122772
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.481808066368103
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5151583552360535
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5701524019241333
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47611626982688904
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46118301153182983
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5503252148628235
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.537996232509613
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.480328232049942
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.25215139985084534
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.5130073428153992
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6074663996696472
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5174805521965027
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5055167078971863
Calibrated prediction for CODI: 0.6000000238418579
Raw prediction for CSCO: 0.6265361309051514
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46879372000694275
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4191369116306305
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5248286128044128
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45638057589530945
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5297004580497742
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4057582914829254
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5273250937461853
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5392969250679016
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.45260390639305115
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.6099907755851746
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5267082452774048
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5454587340354919
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4878358244895935
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4357988238334656
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.40811118483543396
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7618242502212524
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5011903047561646
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4631602168083191
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48639988899230957
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5015254020690918
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5332612991333008
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.582115650177002
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3577421307563782
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48947906494140625
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.18336890637874603
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4639509618282318
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.596675455570221
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5118325352668762
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5579049587249756
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14798878133296967
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.24493539333343506
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5424166917800903
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5296024084091187
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47138699889183044
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5001457929611206
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8450037837028503
Calibrated prediction for PG: 0.8734714388847351
Raw prediction for PICO: 0.4815916419029236
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5172014832496643
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6688950657844543
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5106269717216492
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4657251536846161
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.382541686296463
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6753900051116943
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5514350533485413
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.48568153381347656
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46079546213150024
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4860214591026306
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.45338112115859985
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.7876884341239929
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49232029914855957
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5106799006462097
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5184271335601807
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.47400251030921936
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.40000271797180176
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4176555275917053
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49114125967025757
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3791463375091553
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5149047374725342
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6601519584655762
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  61%|██████    | 61/100 [01:12<00:46,  1.19s/it]

Raw prediction for WFC: 0.5000938773155212
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4588373601436615
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6452898383140564
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.873)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5054059028625488
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5382772088050842
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5174806118011475
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.4854619801044464
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.6123600006103516
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.45447349548339844
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.542415201663971
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5114119648933411
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.5010185241699219
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44832417368888855
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49891024827957153
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.48281046748161316
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5134620070457458
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5575107336044312
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4758090078830719
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4616779088973999
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5530715584754944
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5370238423347473
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4804651439189911
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.2961030602455139
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.515009880065918
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6002052426338196
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5177888870239258
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.494865745306015
Calibrated prediction for CODI: 0.5256661176681519
Raw prediction for CSCO: 0.6406206488609314
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46927395462989807
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.42545247077941895
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.5243264436721802
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4566004276275635
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5297196507453918
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.41296324133872986
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5280343890190125
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.539091944694519
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4423576295375824
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.6225025057792664
Calibrated prediction for GOOG: 0.5972222089767456
Raw prediction for HD: 0.5245131254196167
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5481887459754944
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4845901429653168
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4332024157047272
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.4146336615085602
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.753326416015625
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5005525350570679
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4602803885936737
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48675113916397095
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5007300972938538
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.43903276324272156
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5839203000068665
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.3509403467178345
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48925164341926575
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.1898743063211441
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4635313153266907
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.598291277885437
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5131063461303711
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.562889814376831
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.15901345014572144
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.25055456161499023
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5476693511009216
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5293180346488953
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.477724552154541
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.48834171891212463
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8467329740524292
Calibrated prediction for PG: 0.8734714388847351
Raw prediction for PICO: 0.4818003177642822
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5174655914306641
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6728174686431885
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5098564028739929
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46516960859298706
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3864973485469818
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6840628385543823
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.549955427646637
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.48573312163352966
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46071523427963257
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4860270917415619
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.45656219124794006
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8030292391777039
Calibrated prediction for T: 0.7028569579124451

Simulating Trading Days:  62%|██████▏   | 62/100 [01:13<00:45,  1.18s/it]

Raw prediction for TM: 0.4920300245285034
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5096961259841919
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5182719230651855
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.46912309527397156
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.39550065994262695
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.41297534108161926
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49102452397346497
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.37960249185562134
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5159497857093811
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6695395112037659
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.4999134838581085
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4592909812927246
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6418786644935608
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-2 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.873)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.505489706993103
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5468420386314392
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5148001909255981
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48559102416038513
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.6499972939491272
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4557659924030304
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5427159667015076
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5263981223106384
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.49818557500839233
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4462372064590454
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4986266791820526
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4828796684741974
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5108402967453003
Calibrated prediction for BHP: 0.525137186050415
Raw prediction for BP: 0.5509558320045471
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4755074083805084
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46174854040145874
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5568718314170837
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5363267660140991
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48067277669906616
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.3551674783229828
Calibrated prediction for CELG: 0.3913043439388275
Raw prediction for CHL: 0.517566442489624
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5897429585456848
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5181543231010437
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.4804794490337372
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.6597846150398254
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4695727825164795
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.42781201004981995
Calibrated prediction for D: 0.4615384638309479
Raw prediction for DHR: 0.523921012878418
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45692703127861023
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5298255085945129
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4160023629665375
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5286694765090942
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.518537163734436
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.43462038040161133
Calibrated prediction for GE: 0.4000000059604645
Raw prediction for GOOG: 0.6332834362983704
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.522986888885498
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5490641593933105
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.481675386428833
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.4251488745212555
Calibrated prediction for HSBC: 0.5
Raw prediction for IEP: 0.41447362303733826
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7411608695983887
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5004763007164001
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4561738967895508
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4870706796646118
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4989108443260193
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.3965398967266083
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5836533308029175
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.33211788535118103
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4889581501483917
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.19488494098186493
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46428734064102173
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5987265706062317
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5135478377342224
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5668157935142517
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.1726379245519638
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.257557213306427
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5509754419326782
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5290802717208862
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4812282919883728
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4783186912536621
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8329389095306396
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48182207345962524
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5175475478172302
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6751823425292969
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5091280341148376
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4647606313228607
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3908984959125519
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6914756894111633
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5597776770591736
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.48622193932533264
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4600790739059448
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.48612073063850403
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.4602157175540924
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8148592114448547
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4917944073677063
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5093299150466919
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5182091593742371
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.46541720628738403
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.39237430691719055
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4131312370300293
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.490948885679245
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.37858933210372925
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5170828104019165
Calibrated prediction for V: 0.5184025168418884

Simulating Trading Days:  63%|██████▎   | 63/100 [01:14<00:44,  1.19s/it]

Raw prediction for VZ: 0.6755326986312866
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.4996040165424347
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45955780148506165
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6285936236381531
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.505355179309845
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5534830689430237
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5125927329063416
Calibrated prediction for ABBV: 0.5355574488639832
Raw prediction for AEP: 0.48577457666397095
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.5942477583885193
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4561613202095032
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5431710481643677
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5279819369316101
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.49535849690437317
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44404929876327515
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49802762269973755
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4825269877910614
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5075694918632507
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5479288101196289
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4758724272251129
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4618350863456726
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5604822039604187
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5358275771141052
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4807286858558655
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4205315113067627
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5204174518585205
Calibrated prediction for CHL: 0.4713365137577057
Raw prediction for CHTR: 0.5868420004844666
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5185748338699341
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.4605914354324341
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.6847437620162964
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4695415794849396
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4290858507156372
Calibrated prediction for D: 0.47076335549354553
Raw prediction for DHR: 0.5236572623252869
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4571499824523926
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.529920756816864
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.41760969161987305
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5295225381851196
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.48857739567756653
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.42680686712265015
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6412057876586914
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5217919945716858
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5482153296470642
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.47950273752212524
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.41043952107429504
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.41567856073379517
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7301483750343323
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5006696581840515
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.45172473788261414
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48744454979896545
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4972885847091675
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.3753363788127899
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5821400880813599
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.30099135637283325
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4885532557964325
Calibrated prediction for MMM: 0.48949840664863586
Raw prediction for MO: 0.19885294139385223
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4650692343711853
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5972467660903931
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5134251713752747
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5697981119155884
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.1802380383014679
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.27166324853897095
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5544012784957886
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5291944146156311
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48373404145240784
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.47177252173423767
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8026302456855774
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4817999303340912
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5175754427909851
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6832342743873596
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5087535977363586
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.464245080947876
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3958330750465393
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6945039629936218
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5747830271720886
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.48670998215675354
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.45987170934677124
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.486333429813385
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.46269527077674866
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8264365792274475
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49159175157546997
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5088205337524414
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5182892084121704
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4680206775665283
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.40635597705841064
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.41531622409820557
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4908677637577057
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3909285366535187
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5175514817237854
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6769508123397827
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.4992123246192932
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  64%|██████▍   | 64/100 [01:15<00:43,  1.21s/it]

Raw prediction for WMT: 0.45976462960243225
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6175447702407837
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.604)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5052089691162109
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5572767853736877
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5104033946990967
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.4859333336353302
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.5551803112030029
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4546092450618744
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5441659688949585
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.5129277110099792
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.4929385781288147
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44238951802253723
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49714186787605286
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48217806220054626
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5040022730827332
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5514780282974243
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.476586252450943
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46073389053344727
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5624750256538391
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.535480260848999
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4806911051273346
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.46321791410446167
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5242325067520142
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5892128348350525
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5189977884292603
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.4583856165409088
Calibrated prediction for CODI: 0.38372093439102173
Raw prediction for CSCO: 0.7067091464996338
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46928688883781433
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43183815479278564
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5234931111335754
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45735910534858704
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5298411250114441
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.41985180974006653
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5301434397697449
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4485321640968323
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4176512360572815
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6461667418479919
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5215315222740173
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5457032918930054
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4785027503967285
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.39543089270591736
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4253375828266144
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7039852738380432
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5009961724281311
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.44918572902679443
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48781493306159973
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49516570568084717
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.3653217852115631
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.580607533454895
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.26692020893096924
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4879993796348572
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.20325104892253876
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46556851267814636
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5974394679069519
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5128559470176697
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5735783576965332
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.19239342212677002
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.29232531785964966
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5566158890724182
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5293998718261719
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.486629843711853
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4644084572792053
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.7625612020492554
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48184680938720703
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5175851583480835
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6908700466156006
Calibrated prediction for PPL: 0.7068465948104858
Raw prediction for PTR: 0.5084382891654968
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4640653133392334
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3999899923801422
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6939698457717896
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5636215806007385
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4871414005756378
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.45968863368034363
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.48652130365371704
Calibrated prediction for SPLP: 0.4853333532810211
Raw prediction for SRE: 0.46261924505233765
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8338733315467834
Calibrated prediction for T: 0.7028569579124451

Simulating Trading Days:  65%|██████▌   | 65/100 [01:16<00:42,  1.20s/it]

Raw prediction for TM: 0.49122247099876404
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5084026455879211
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5188498497009277
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4716416895389557
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.4048141837120056
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4166252613067627
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49068859219551086
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.40310412645339966
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5178848505020142
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6738048195838928
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.49918118119239807
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4598780572414398
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5976901650428772
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.707)
Raw prediction for AAPL: 0.5052915811538696
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5603421926498413
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5080355405807495
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.48608455061912537
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.47589948773384094
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4553355276584625
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5440405011177063
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.48676714301109314
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.4907993972301483
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44161996245384216
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4965446889400482
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48185810446739197
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5008049011230469
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5566527843475342
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47707054018974304
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4600611627101898
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.56315016746521
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.535323977470398
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48071524500846863
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.49506691098213196
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.528744637966156
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5928171277046204
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5193789005279541
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.4710439145565033
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.7266494035720825
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46891069412231445
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43224549293518066
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.523287296295166
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.457366019487381
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5297917127609253
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4211480915546417
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5307251811027527
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.41416454315185547
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4160456955432892
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.648567795753479
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5214871168136597
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5434516072273254
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.47904184460639954
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3835165798664093
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.44502976536750793
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6809634566307068
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5015707015991211
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.44891220331192017
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48833709955215454
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49357178807258606
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.3797175884246826
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5794149041175842
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.24102097749710083
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4874851703643799
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.20522086322307587
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4665606915950775
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5977268815040588
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5123682618141174
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5761249661445618
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.21018020808696747
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3239247798919678
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5587539672851562
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5295358896255493
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4885002374649048
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4573400914669037
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.707169234752655
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4820108413696289
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5175654292106628
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6912307739257812
Calibrated prediction for PPL: 0.710106372833252
Raw prediction for PTR: 0.5080302953720093
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46402671933174133
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.40404796600341797
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6914792060852051
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5599456429481506
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4880180060863495
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.45995521545410156
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.48660004138946533
Calibrated prediction for SPLP: 0.5019893646240234
Raw prediction for SRE: 0.46002230048179626
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8365966081619263
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49074727296829224
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5085874795913696
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5208389759063721
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4809875786304474
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.4227111339569092
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4176191985607147
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4904981255531311
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4378066658973694
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5175495147705078
Calibrated prediction for V: 0.5184025168418884

Simulating Trading Days:  66%|██████▌   | 66/100 [01:18<00:40,  1.20s/it]

Raw prediction for VZ: 0.6734210252761841
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.49919936060905457
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4596567153930664
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.580651581287384
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.710)
Raw prediction for AAPL: 0.5055306553840637
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5600016713142395
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5059967637062073
Calibrated prediction for ABBV: 0.5135135054588318
Raw prediction for AEP: 0.4862686097621918
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.28340429067611694
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.45573022961616516
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.543384850025177
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.447795569896698
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.4892982244491577
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44124075770378113
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49628522992134094
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48139360547065735
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49750328063964844
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5686778426170349
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47762206196784973
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45933860540390015
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5629456043243408
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5355094075202942
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4806075096130371
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5017651319503784
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.532737672328949
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5937173962593079
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5198226571083069
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.4805751144886017
Calibrated prediction for CODI: 0.4615384638309479
Raw prediction for CSCO: 0.744746208190918
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46894288063049316
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4308166205883026
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.523042619228363
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45730283856391907
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5298014283180237
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.42108848690986633
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5308645963668823
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3865617513656616
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.41547733545303345
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.648488461971283
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5212954878807068
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5407701730728149
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.48035281896591187
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.373217910528183
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4613286256790161
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6552813649177551
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5020788311958313
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.44951003789901733
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48862043023109436
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49215173721313477
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.39646995067596436
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5804832577705383
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.21367214620113373
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4870072901248932
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.20417456328868866
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46800699830055237
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5994256138801575
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5120685696601868
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5766774415969849
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.21894632279872894
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.34774914383888245
Calibrated prediction for ORCL: 0.2433069795370102
Raw prediction for PCG: 0.5598155856132507
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5294228792190552
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48854830861091614
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.45317861437797546
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.6383612155914307
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.48214226961135864
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.517551064491272
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6814522743225098
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5075611472129822
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46420177817344666
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.40753138065338135
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.689302921295166
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5704959630966187
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4885862171649933
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4605352282524109
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4867980480194092
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4576064348220825
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8358537554740906
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49035173654556274
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5096156597137451
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5223948955535889
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4878878891468048
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.4226388931274414
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4176558554172516
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4903612434864044
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4541590213775635
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.517205536365509
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6741058230400085
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.49902069568634033
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45926254987716675
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.564831018447876
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.615)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:  67%|██████▋   | 67/100 [01:19<00:39,  1.20s/it]

Raw prediction for AAPL: 0.5053606033325195
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5577254891395569
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5040314197540283
Calibrated prediction for ABBV: 0.5
Raw prediction for AEP: 0.48651209473609924
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.10735197365283966
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4571685194969177
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5423673987388611
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4063103199005127
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.48845311999320984
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44086384773254395
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4960910379886627
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4811381995677948
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4944203794002533
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5802610516548157
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47809019684791565
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45913150906562805
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5613772869110107
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5358657240867615
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48047536611557007
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5113720297813416
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5343993306159973
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5931371450424194
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5201985836029053
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.48825526237487793
Calibrated prediction for CODI: 0.5
Raw prediction for CSCO: 0.7533922791481018
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4692472219467163
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4327630400657654
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5227850079536438
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45698875188827515
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5299143195152283
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.42049264907836914
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5304491519927979
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3740682005882263
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4145663380622864
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6478190422058105
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5209720134735107
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5372934937477112
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.48168429732322693
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.36872056126594543
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.474368155002594
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6463881134986877
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5026494264602661
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4529000222682953
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.488830029964447
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4914766550064087
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.42163336277008057
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5814014673233032
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.19125597178936005
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4866042733192444
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.20732630789279938
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.46933093667030334
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6018433570861816
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5123741030693054
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5773359537124634
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.21964311599731445
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3592979907989502
Calibrated prediction for ORCL: 0.4794520437717438
Raw prediction for PCG: 0.5611340403556824
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5290437340736389
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.49125030636787415
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.44950878620147705
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.5801833868026733
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.48223355412483215
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5174736380577087
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.673518180847168
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5073290467262268
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4643450677394867
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4105009436607361
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6861804127693176
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5804325938224792
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.48925039172172546
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46120262145996094
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4871317744255066
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.45589685440063477
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8310149312019348
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4901331961154938
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5103057622909546
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5225895643234253
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4906187951564789
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.4131295680999756
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4204573333263397
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49018600583076477
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4568922817707062
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5165529847145081
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.674804151058197
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.4991336464881897
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  68%|██████▊   | 68/100 [01:20<00:38,  1.20s/it]

Raw prediction for WMT: 0.457707017660141
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5436121225357056
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.615)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5050410032272339
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5549513697624207
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5023083090782166
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48673346638679504
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.04755127429962158
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4574896991252899
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5408203601837158
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3667709529399872
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.48858097195625305
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.440751314163208
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49605923891067505
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.481076180934906
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4917706549167633
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5911557078361511
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4786056876182556
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4589248299598694
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5607584118843079
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5362948179244995
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48037609457969666
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5139860510826111
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5335256457328796
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5888400077819824
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5205647349357605
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.4941871762275696
Calibrated prediction for CODI: 0.5
Raw prediction for CSCO: 0.7527821063995361
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4695645868778229
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.43329980969429016
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.522659957408905
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4565257728099823
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5300609469413757
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4202311635017395
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5296338200569153
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.37419119477272034
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4136880040168762
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6482563614845276
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5206068158149719
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5331900119781494
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4829998016357422
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3675537705421448
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4808403551578522
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6468978524208069
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5033270716667175
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4582776427268982
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.489033579826355
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4917287230491638
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4385389983654022
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5801164507865906
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1741848737001419
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48625990748405457
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.21408894658088684
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.47114497423171997
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6072441339492798
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5131810903549194
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5780959129333496
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.21686162054538727
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3538685441017151
Calibrated prediction for ORCL: 0.4794520437717438
Raw prediction for PCG: 0.5628179907798767
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5284005403518677
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4945337474346161
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.44551777839660645
Calibrated prediction for PFE: 0.4000000059604645
Raw prediction for PG: 0.5283849835395813
Calibrated prediction for PG: 0.5384615659713745
Raw prediction for PICO: 0.4823342561721802
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5174577236175537
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6635827422142029
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.507289469242096
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46456676721572876
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4121897220611572
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6828738451004028
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6005129218101501
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.48980939388275146
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4614151120185852
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.4876103103160858
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.45734643936157227
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8261678814888
Calibrated prediction for T: 0.7028569579124451

Simulating Trading Days:  69%|██████▉   | 69/100 [01:21<00:37,  1.19s/it]

Raw prediction for TM: 0.49010270833969116
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5106878876686096
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5218501091003418
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.48829880356788635
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.3970687687397003
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.42583876848220825
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48997923731803894
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4444342255592346
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5160553455352783
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6755772233009338
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.499361127614975
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.45610785484313965
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5318661332130432
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (p=0.532)
[PORT] Sector Financial: sampled C from top-3 (p=0.537)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5047504901885986
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5472831130027771
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5012239813804626
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48691728711128235
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.02800465002655983
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.45621412992477417
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5390684008598328
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3300624191761017
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.48989802598953247
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4410454332828522
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4960635304450989
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48100554943084717
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.48950374126434326
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.588513195514679
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47915276885032654
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4585351049900055
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.560535728931427
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5366835594177246
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48026901483535767
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5053681135177612
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5309646129608154
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5822697877883911
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5209842324256897
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5044207572937012
Calibrated prediction for CODI: 0.6000000238418579
Raw prediction for CSCO: 0.7480788826942444
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4697822332382202
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4315526783466339
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5226303339004517
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45590490102767944
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5301623940467834
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.41906481981277466
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5285908579826355
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3701295852661133
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.41189324855804443
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6522938013076782
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5205075144767761
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5275826454162598
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4840497374534607
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.36698997020721436
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4842066466808319
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6412568688392639
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5038455128669739
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4648786187171936
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4889315962791443
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4926782548427582
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4370577335357666
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5781741738319397
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.16109663248062134
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48603555560112
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.21641327440738678
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.472900927066803
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.61576908826828
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5140343904495239
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5777519941329956
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.21132728457450867
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.336536705493927
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5639047622680664
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5278760194778442
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.49342361092567444
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.448973685503006
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4739725589752197
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.48246413469314575
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5173128247261047
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6461078524589539
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5072684288024902
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46451127529144287
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.41210442781448364
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6793426275253296
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6153721809387207
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.48984310030937195
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4618837535381317
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.48784828186035156
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4595954120159149
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.8219562768936157
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49024513363838196
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5105608105659485
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5205788612365723
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4771139621734619
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.36738064885139465
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4294690191745758
Calibrated prediction for UNH: 0.47727271914482117

Simulating Trading Days:  70%|███████   | 70/100 [01:22<00:36,  1.21s/it]

Raw prediction for UPS: 0.4897794723510742
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.4113558530807495
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5160629749298096
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6728033423423767
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.49957674741744995
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4548770487308502
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5268146991729736
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled AAPL from top-2 (p=0.532)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled BA from top-3 (p=0.600)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.680)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5039088726043701
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5424209833145142
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.5003728866577148
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48688313364982605
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.02013271115720272
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.45337024331092834
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5375377535820007
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.30397510528564453
Calibrated prediction for BA: 0.5110980272293091
Raw prediction for BABA: 0.49217885732650757
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4417736232280731
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4960978627204895
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48081934452056885
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4877132773399353
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5705296993255615
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47933751344680786
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4582825005054474
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5613834261894226
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5371262431144714
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48006463050842285
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4811544418334961
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5261441469192505
Calibrated prediction for CHL: 0.531493604183197
Raw prediction for CHTR: 0.5773714780807495
Calibrated prediction for CHTR: 0.6363636255264282
Raw prediction for CMCSA: 0.5213220715522766
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5128505825996399
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.7406383752822876
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4697701632976532
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4358636736869812
Calibrated prediction for D: 0.5
Raw prediction for DHR: 0.5228590965270996
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4552479386329651
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5304495096206665
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.42228394746780396
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5275593400001526
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3690636157989502
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4100048840045929
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6590216755867004
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.521370530128479
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5215665102005005
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4857974648475647
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.36438629031181335
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.48032137751579285
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6306062340736389
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5043346285820007
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4709492325782776
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4887196123600006
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49427860975265503
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4320012331008911
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5799306631088257
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.15093174576759338
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4858613610267639
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.22131946682929993
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.474233478307724
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6264634728431702
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5154181718826294
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5780072808265686
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.20706334710121155
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3187836706638336
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5617996454238892
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5274268388748169
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4923548400402069
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4498087763786316
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4318126142024994
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4825519621372223
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5172391533851624
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6195877194404602
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.507012665271759
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4642135500907898
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.41173282265663147
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6756072044372559
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6176868677139282
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.48996949195861816
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46293795108795166
Calibrated prediction for SO: 0.44999998807907104
Raw prediction for SPLP: 0.48798853158950806
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.46693962812423706
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.817743718624115
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49032503366470337
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5102106928825378
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5188372731208801
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4593189060688019
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.34540459513664246
Calibrated prediction for UN: 0.4545454680919647

Simulating Trading Days:  71%|███████   | 71/100 [01:24<00:35,  1.23s/it]

Raw prediction for UNH: 0.4319687783718109
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4896238446235657
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.38624873757362366
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5166522860527039
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6653188467025757
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.4997348487377167
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4539758265018463
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5273348689079285
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled AAPL from top-2 (p=0.532)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.636)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5030943155288696
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5367196798324585
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49967947602272034
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48651668429374695
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.02047557197511196
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4485555589199066
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5369808077812195
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.2848376929759979
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.49543410539627075
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4425601065158844
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49600809812545776
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48100438714027405
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4859805703163147
Calibrated prediction for BHP: 0.48324835300445557
Raw prediction for BP: 0.5428019762039185
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4797334671020508
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45829981565475464
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5628730654716492
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.537367045879364
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4797971248626709
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4457336664199829
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.519899308681488
Calibrated prediction for CHL: 0.45110827684402466
Raw prediction for CHTR: 0.5747671127319336
Calibrated prediction for CHTR: 0.6363636255264282
Raw prediction for CMCSA: 0.5216348767280579
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5151726007461548
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.730694591999054
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46936091780662537
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.44186028838157654
Calibrated prediction for D: 0.5384615659713745
Raw prediction for DHR: 0.5232353210449219
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.454870343208313
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5306949019432068
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4241988956928253
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5266053080558777
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.36274445056915283
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4075181484222412
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6689997315406799
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5236098170280457
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5175907015800476
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4871366322040558
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3625807762145996
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.46915385127067566
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6256921291351318
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5046613216400146
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4775073230266571
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48816239833831787
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49584275484085083
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.43453752994537354
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5819672346115112
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1420043706893921
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4857120215892792
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.21903954446315765
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.47522205114364624
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6375324726104736
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5163291692733765
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5772443413734436
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.19770213961601257
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.29814770817756653
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5576815605163574
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5270738005638123
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4872787594795227
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4517952501773834
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.3845042586326599
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.48270517587661743
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.516879677772522
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.6004005670547485
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5066011548042297
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4636403024196625
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.41130006313323975
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6705016493797302
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6000092625617981
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4900926351547241
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46357688307762146
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4878687262535095
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4779689311981201
Calibrated prediction for SRE: 0.4322940707206726
Raw prediction for T: 0.811116099357605
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4903871715068817
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5091583728790283
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5188894271850586
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.43674778938293457
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.33306610584259033
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4308580458164215
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4895324110984802
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.36390674114227295
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.51754230260849
Calibrated prediction for V: 0.5184025168418884

Simulating Trading Days:  72%|███████▏  | 72/100 [01:25<00:34,  1.22s/it]

Raw prediction for VZ: 0.6515533328056335
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5000042915344238
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4530559778213501
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5409995317459106
Calibrated prediction for XOM: 0.5931671261787415
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled AAPL from top-2 (p=0.532)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.636)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.50199294090271
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5345988273620605
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4994039535522461
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4864119589328766
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.026081345975399017
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.44310617446899414
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5373274087905884
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.2759000360965729
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.4993320107460022
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4438578486442566
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49608519673347473
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48094063997268677
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4843825101852417
Calibrated prediction for BHP: 0.4818759858608246
Raw prediction for BP: 0.5216512680053711
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4798448979854584
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45834189653396606
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5648844242095947
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5375080704689026
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.47952550649642944
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4088780879974365
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5135754942893982
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5723667740821838
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5219050049781799
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5176008343696594
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.7166811227798462
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46869802474975586
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4550057053565979
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5240837335586548
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45466887950897217
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5310226678848267
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4273843765258789
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5259315371513367
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.37187501788139343
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.40555062890052795
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6831456422805786
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5267417430877686
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5149350166320801
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4875603914260864
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.35964885354042053
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.44442862272262573
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6234900951385498
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5049692988395691
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4847809076309204
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4873809516429901
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49716904759407043
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4369991719722748
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5815557241439819
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.14236560463905334
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4855971932411194
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.21811243891716003
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4760592579841614
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6466208100318909
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.517245352268219
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5783347487449646
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.19060395658016205
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2868548333644867
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5536832213401794
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5268136262893677
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48159241676330566
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4530170261859894
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.3392486572265625
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4829157590866089
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5164534449577332
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.5552718043327332
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5063484311103821
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46326521039009094
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.4113185703754425
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.663740336894989
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5872631072998047
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49031975865364075
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4645037055015564
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48769548535346985
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.4971880316734314
Calibrated prediction for SRE: 0.5625
Raw prediction for T: 0.8051562905311584
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49059295654296875
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5084015130996704
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5192335844039917
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.41616398096084595
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.33903810381889343
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4284708797931671
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4894527196884155
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3607374429702759
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.518595814704895
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6336331963539124
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  73%|███████▎  | 73/100 [01:26<00:33,  1.22s/it]

Raw prediction for WFC: 0.5002842545509338
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4515852928161621
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5510203838348389
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled AAPL from top-2 (p=0.532)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)
Raw prediction for AAPL: 0.5008399486541748
Calibrated prediction for AAPL: 0.5315276980400085
Raw prediction for ABB: 0.5343761444091797
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4992278814315796
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48665761947631836
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.04512351006269455
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4380185604095459
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5381088256835938
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.2804297208786011
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.5035541653633118
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4455219507217407
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4962625503540039
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48093682527542114
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4835786521434784
Calibrated prediction for BHP: 0.4818759858608246
Raw prediction for BP: 0.5126222968101501
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4796809256076813
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4587833285331726
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5667993426322937
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5375187397003174
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4792129397392273
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.38301539421081543
Calibrated prediction for CELG: 0.3913043439388275
Raw prediction for CHL: 0.5097194910049438
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5708323121070862
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5221402049064636
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5258329510688782
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.7052193284034729
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4680900573730469
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4717658460140228
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5250621438026428
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4546016454696655
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5313403010368347
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4360466003417969
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5254791378974915
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.38506242632865906
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.40226924419403076
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6995694637298584
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5292745232582092
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5142478346824646
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.48909345269203186
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.35796308517456055
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.41864848136901855
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6181436777114868
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5052947402000427
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4928855299949646
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48646289110183716
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4984573721885681
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.44624391198158264
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5803248286247253
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1477060317993164
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4854632019996643
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2194094955921173
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4770953953266144
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6548974514007568
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5180094242095947
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5797082781791687
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.18290720880031586
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2787932753562927
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5499891638755798
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5266062617301941
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4757038354873657
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4536113739013672
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.29615554213523865
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4831319749355316
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5159150958061218
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.49864932894706726
Calibrated prediction for PPL: 0.7037037014961243
Raw prediction for PTR: 0.5062462687492371
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46296316385269165
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.41080421209335327
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6589245796203613
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5841287970542908
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49067285656929016
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.465362012386322
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48740679025650024
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5196749567985535
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7999783158302307
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49082237482070923
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5077646374702454
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.51950603723526
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.39908894896507263
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.3527905344963074
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.4250328540802002
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4894605576992035
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.3820003569126129
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5196295380592346
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6172383427619934
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5006702542304993
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.44950276613235474
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.562616765499115
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled AAPL from top-2 (p=0.532)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled UNH from top-3 (p=0.477)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (p=0.578)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.704)

Simulating Trading Days:  74%|███████▍  | 74/100 [01:27<00:31,  1.23s/it]

Raw prediction for AAPL: 0.4996635317802429
Calibrated prediction for AAPL: 0.49980220198631287
Raw prediction for ABB: 0.5339515209197998
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4989476799964905
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.48745986819267273
Calibrated prediction for AEP: 0.48517054319381714
Raw prediction for AGFS: 0.11705555021762848
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.43342429399490356
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5386638045310974
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.28853994607925415
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.5073844194412231
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4472641944885254
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4965793788433075
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4805329442024231
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.483335018157959
Calibrated prediction for BHP: 0.4818759858608246
Raw prediction for BP: 0.5211856365203857
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4794951379299164
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45857715606689453
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5683588981628418
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5374932289123535
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4789782762527466
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.3478580415248871
Calibrated prediction for CELG: 0.3913043439388275
Raw prediction for CHL: 0.5061637163162231
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5685657262802124
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5223628878593445
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5398787260055542
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6918544173240662
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4675573408603668
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.4927738904953003
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5258856415748596
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4545712172985077
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5317053198814392
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.45231980085372925
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5250002145767212
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3885793685913086
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4003780782222748
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7163805365562439
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5312732458114624
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.514134407043457
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49225082993507385
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3546696901321411
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.39481183886528015
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6176406145095825
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5056495666503906
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.5002689957618713
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48544150590896606
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49923357367515564
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4626006782054901
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.578895092010498
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.15542620420455933
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48515474796295166
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.22116579115390778
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4779335856437683
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.660947322845459
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5187891125679016
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5818623900413513
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.16838987171649933
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.26974546909332275
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.547160804271698
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5264264941215515
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4697502851486206
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.45406296849250793
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.25857341289520264
Calibrated prediction for PG: 0.20000000298023224
Raw prediction for PICO: 0.4832494854927063
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5154061913490295
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.43631699681282043
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5062639713287354
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46270063519477844
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.40889522433280945
Calibrated prediction for REX: 0.375
Raw prediction for SLB: 0.6568095684051514
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.596365213394165
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49137645959854126
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46709948778152466
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48719051480293274
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5418237447738647
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7945350408554077
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4910782277584076
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5072542428970337
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5198127627372742
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3859941363334656
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.3711587190628052
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.419216513633728
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48958784341812134
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.40788084268569946
Calibrated prediction for UTX: 0.38461539149284363
Raw prediction for V: 0.5206412076950073
Calibrated prediction for V: 0.5184025168418884

Simulating Trading Days:  75%|███████▌  | 75/100 [01:29<00:30,  1.22s/it]

Raw prediction for VZ: 0.608301043510437
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5009547472000122
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4466191530227661
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5825022459030151
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PEP from top-2 (p=0.517)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled MRK from top-3 (p=0.510)
[PORT] Sector Industrial Goods: sampled HON from top-3 (p=0.558)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49839702248573303
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.547675371170044
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4985499382019043
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4887111186981201
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.28609564900398254
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4299390912055969
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.539671003818512
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3047856092453003
Calibrated prediction for BA: 0.5367682576179504
Raw prediction for BABA: 0.5098046660423279
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44858884811401367
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49695757031440735
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.48013025522232056
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4841737151145935
Calibrated prediction for BHP: 0.4818759858608246
Raw prediction for BP: 0.5329856872558594
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47943350672721863
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4586343765258789
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5689777731895447
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5372800827026367
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4789392650127411
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.30432605743408203
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.5031329393386841
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5701256990432739
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5224369764328003
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5523226261138916
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6784358024597168
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46702736616134644
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5149880647659302
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5260977745056152
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4545814096927643
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5321377515792847
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4715951979160309
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.524497389793396
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.39171528816223145
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4092010259628296
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7314415574073792
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5333531498908997
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5160539746284485
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4960165321826935
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3507342040538788
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.37440070509910583
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6167539954185486
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5060169696807861
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.5061901211738586
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48447152972221375
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5000017285346985
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4885399341583252
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.5830962061882019
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.16326352953910828
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4850422739982605
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.22539326548576355
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4785478711128235
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6680992841720581
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.51987624168396
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5841593146324158
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14978736639022827
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2600598633289337
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.543800950050354
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5262278318405151
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4657488465309143
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.45472437143325806
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.23910097777843475
Calibrated prediction for PG: 0.1715323030948639
Raw prediction for PICO: 0.4834462106227875
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5150405168533325
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.386715292930603
Calibrated prediction for PPL: 0.5
Raw prediction for PTR: 0.5062941312789917
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46246957778930664
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.40476933121681213
Calibrated prediction for REX: 0.36202532052993774
Raw prediction for SLB: 0.6561300754547119
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6001091003417969
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49186044931411743
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.469868004322052
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4870304763317108
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5631905794143677
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7903955578804016
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49141308665275574
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5068375468254089
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5200384259223938
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.37351980805397034
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.3890199363231659
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.41182345151901245
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48969772458076477
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.45400556921958923
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5214920043945312
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6003757119178772
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.501220703125
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  76%|███████▌  | 76/100 [01:30<00:29,  1.22s/it]

Raw prediction for WMT: 0.44370338320732117
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.599564790725708
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (p=0.633)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PEP from top-2 (p=0.517)
[PORT] Sector Financial: sampled C from top-3 (p=0.537)
[PORT] Sector Healthcare: sampled JNJ from top-3 (p=0.503)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-07-31 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0025, PnL=$-9.97
Raw prediction for AAPL: 0.4976096451282501
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5689117312431335
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4982626736164093
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4900944232940674
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.621895432472229
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4284363389015198
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5402162671089172
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.31759557127952576
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.511286735534668
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44968700408935547
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49762335419654846
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4796941876411438
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4863513112068176
Calibrated prediction for BHP: 0.4873161017894745
Raw prediction for BP: 0.5473198890686035
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4795657992362976
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45794913172721863
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5699451565742493
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5370675921440125
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4791623055934906
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.24940691888332367
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.5015053153038025
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5705142617225647
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5225744247436523
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.562374472618103
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6668671369552612
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46681106090545654
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5366007685661316
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5258805751800537
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4546504318714142
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5324764847755432
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4910370111465454
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5240023136138916
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.3852418065071106
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.42994046211242676
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.7440019249916077
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5330243110656738
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5176981687545776
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.498421311378479
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3472485840320587
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.3546178340911865
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6145046353340149
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5064318776130676
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.510399341583252
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48350924253463745
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.500490128993988
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5146082639694214
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.5852054953575134
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.16936826705932617
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48497989773750305
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.22876673936843872
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.47937554121017456
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6738471984863281
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5213048458099365
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5860256552696228
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.1352704018354416
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.25212186574935913
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.539513885974884
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5261114835739136
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46043044328689575
Calibrated prediction for PEP: 0.5039353966712952
Raw prediction for PFE: 0.4572952687740326
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.23513498902320862
Calibrated prediction for PG: 0.17005498707294464
Raw prediction for PICO: 0.48370805382728577
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.514904260635376
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.3600105941295624
Calibrated prediction for PPL: 0.3333333432674408
Raw prediction for PTR: 0.5064646601676941
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4625839293003082
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3990044891834259
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.656083345413208
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5971855521202087
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4922819137573242
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.47311311960220337
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.48696860671043396
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5828355550765991
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7867212295532227
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49190711975097656
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5071743130683899
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5201423168182373
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.36443448066711426
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.413765549659729
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.40384867787361145
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4898533225059509
Calibrated prediction for UPS: 0.4929138123989105

Simulating Trading Days:  77%|███████▋  | 77/100 [01:31<00:28,  1.24s/it]

Raw prediction for UTX: 0.49339011311531067
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5225134491920471
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5958523750305176
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5015037059783936
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4408302307128906
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6075121760368347
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled AAPL from top-1 (p=0.495)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled JNJ from top-3 (p=0.503)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-01 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0026, PnL=$11.19
[EARLY EXIT] 2017-08-01 00:00:00: MA p_up_1d=0.317 -> exit; r=0.0132, PnL=$31.50
Raw prediction for AAPL: 0.4967721104621887
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5903149247169495
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49771031737327576
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4913436472415924
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8160780072212219
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.42804986238479614
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5407737493515015
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.3283577263355255
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5117322206497192
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.45057302713394165
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4982770085334778
Calibrated prediction for BBL: 0.4979775547981262
Raw prediction for BCH: 0.47908589243888855
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.489175021648407
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5600879788398743
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4798003137111664
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45636656880378723
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5712132453918457
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5368854999542236
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.47939756512641907
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.20938462018966675
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.5002633333206177
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5719618797302246
Calibrated prediction for CHTR: 0.5882353186607361
Raw prediction for CMCSA: 0.5225839614868164
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5705021023750305
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6603380441665649
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4669302701950073
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.563459575176239
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5254240036010742
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4547877013683319
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.53265780210495
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5092617869377136
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5234917402267456
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.39694249629974365
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.4496621787548065
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.754309892654419
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5306825041770935
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5183264017105103
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5007861256599426
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.34401726722717285
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.34031185507774353
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6207102537155151
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5065168738365173
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.5123886466026306
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4827680289745331
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5008403062820435
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5472820997238159
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.5899603962898254
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1740490347146988
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48500949144363403
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.24114181101322174
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.4798921048641205
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6757189631462097
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5228537321090698
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5897892713546753
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.12935051321983337
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.24719369411468506
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5370947122573853
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5260086059570312
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4587917923927307
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.46210750937461853
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.25226151943206787
Calibrated prediction for PG: 0.20000000298023224
Raw prediction for PICO: 0.4840307831764221
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5150718092918396
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.35430800914764404
Calibrated prediction for PPL: 0.3333333432674408
Raw prediction for PTR: 0.5066925287246704
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4628466069698334
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3929884731769562
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6573031544685364
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5973886847496033
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49256497621536255
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4762003421783447
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.48698902130126953
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5954902768135071
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.782106339931488
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49258679151535034
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5076315999031067
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5201770663261414
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.360592246055603
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.44213536381721497
Calibrated prediction for UN: 0.4962124824523926
Raw prediction for UNH: 0.3918176293373108
Calibrated prediction for UNH: 0.47727271914482117

Simulating Trading Days:  78%|███████▊  | 78/100 [01:32<00:27,  1.25s/it]

Raw prediction for UPS: 0.49003681540489197
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.511391818523407
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5234651565551758
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5959630608558655
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5015572905540466
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.43852242827415466
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6064736843109131
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled AAPL from top-1 (p=0.495)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled MRK from top-3 (p=0.510)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.596)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-02 00:00:00: MA p_up_1d=0.317 -> exit; r=0.0086, PnL=$43.94
Raw prediction for AAPL: 0.49608588218688965
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.6173108220100403
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4967615604400635
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4925422966480255
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8896822929382324
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4283507764339447
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5417131781578064
Calibrated prediction for AMZN: 0.5590608716011047
Raw prediction for BA: 0.3393231928348541
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5111895203590393
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.45032793283462524
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4984503984451294
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4784991145133972
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49195072054862976
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.56259685754776
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48059165477752686
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.456310510635376
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5718632936477661
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5363445281982422
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4801952838897705
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.20741502940654755
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.4990830719470978
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.574786365032196
Calibrated prediction for CHTR: 0.6363636255264282
Raw prediction for CMCSA: 0.5225203037261963
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5699548125267029
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.651319682598114
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4668726921081543
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5837489366531372
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5248498916625977
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4549785554409027
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5326865911483765
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5222024321556091
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5231451392173767
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4053550064563751
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.47987496852874756
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.7646809816360474
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5279174447059631
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5179983973503113
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5029227137565613
Calibrated prediction for HRG: 0.5690544843673706
Raw prediction for HSBC: 0.34009861946105957
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.334699422121048
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6314727067947388
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5062879920005798
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.5110200643539429
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48214492201805115
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5013701915740967
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5715585947036743
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6086913347244263
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.17665648460388184
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4856557846069336
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.25722649693489075
Calibrated prediction for MO: 0.18548348546028137
Raw prediction for MRK: 0.48043888807296753
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6774172186851501
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5240771770477295
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5931423902511597
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.13064570724964142
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.24799644947052002
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5378943681716919
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5259632468223572
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4584260880947113
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.46508416533470154
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.2821970283985138
Calibrated prediction for PG: 0.375
Raw prediction for PICO: 0.48424023389816284
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5154523253440857
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.3536345660686493
Calibrated prediction for PPL: 0.3333333432674408
Raw prediction for PTR: 0.5069050192832947
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46295425295829773
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.39039406180381775
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.658669114112854
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.5965542793273926
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.492732435464859
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.47802093625068665
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.48706570267677307
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6012526750564575
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7802425622940063
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4932457506656647
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5071521401405334
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5199282169342041
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.35921332240104675
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.4583665132522583
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3730250597000122
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.490202397108078
Calibrated prediction for UPS: 0.4929138123989105

Simulating Trading Days:  79%|███████▉  | 79/100 [01:34<00:26,  1.24s/it]

Raw prediction for UTX: 0.58808833360672
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5245151519775391
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5974127650260925
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5013967752456665
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4365634620189667
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6118149757385254
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-2 (p=0.520)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled MRK from top-3 (p=0.510)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.636)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-03 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0062, PnL=$12.85
[EARLY EXIT] 2017-08-03 00:00:00: MA p_up_1d=0.317 -> exit; r=-0.0055, PnL=$-11.84
Raw prediction for AAPL: 0.495429128408432
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.6468783020973206
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.49552926421165466
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4932783544063568
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.9051737189292908
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.43291589617729187
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5422258973121643
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.34842678904533386
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5109477043151855
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4497586488723755
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49848562479019165
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4780119061470032
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4934234917163849
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5658175349235535
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48137277364730835
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4562578499317169
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5709265470504761
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5358811020851135
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4810672402381897
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.2310197949409485
Calibrated prediction for CELG: 0.23976589739322662
Raw prediction for CHL: 0.49838435649871826
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5772656202316284
Calibrated prediction for CHTR: 0.6363636255264282
Raw prediction for CMCSA: 0.5224279761314392
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5618403553962708
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6509843468666077
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46648451685905457
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5921661853790283
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5245502591133118
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45505037903785706
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5326862931251526
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5250174403190613
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5230051279067993
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.4813464283943176
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.5039305686950684
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.7696287631988525
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5255283117294312
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5163009762763977
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5046395659446716
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.33971890807151794
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.3339427411556244
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6330496668815613
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5061549544334412
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.5086103081703186
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48169052600860596
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5018754601478577
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5991628170013428
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6238553524017334
Calibrated prediction for MCD: 0.5961538553237915
Raw prediction for MDT: 0.1802513748407364
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4856500029563904
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.27702873945236206
Calibrated prediction for MO: 0.22978496551513672
Raw prediction for MRK: 0.4815102815628052
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6784313917160034
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5245732069015503
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5946022272109985
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.13395282626152039
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2490301877260208
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5378237366676331
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5258913040161133
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4578852653503418
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.46740400791168213
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.32276755571365356
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4843143820762634
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5159952640533447
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.3470640778541565
Calibrated prediction for PPL: 0.3229007422924042
Raw prediction for PTR: 0.5069600939750671
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46285316348075867
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3924558162689209
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6589646339416504
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6017393469810486
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.4930257201194763
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4785946011543274
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.4870256781578064
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6030223965644836
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.76923006772995
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49355819821357727
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5064547657966614
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5196658372879028
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.35921981930732727
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.45929229259490967
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3584651052951813
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4903338551521301
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.6974848508834839
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5253170132637024
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.5992108583450317
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  80%|████████  | 80/100 [01:35<00:24,  1.23s/it]

Raw prediction for WFC: 0.5013596415519714
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.43433675169944763
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6152005195617676
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled BP from top-3 (p=0.658)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled UN from top-2 (p=0.520)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled JNJ from top-3 (p=0.503)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled CHTR from top-3 (p=0.636)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-04 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0032, PnL=$6.62
[EARLY EXIT] 2017-08-04 00:00:00: MA p_up_1d=0.317 -> exit; r=-0.0005, PnL=$-1.20
Raw prediction for AAPL: 0.4945152699947357
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.6604483127593994
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4930559992790222
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49352213740348816
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.9289069771766663
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.44096148014068604
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5437107682228088
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.3562670946121216
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5092762112617493
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44913598895072937
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4984480142593384
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.477324903011322
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4940066337585449
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5656206011772156
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4821988046169281
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4563009738922119
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5674874782562256
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5356575846672058
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.481484055519104
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.3136616051197052
Calibrated prediction for CELG: 0.28402385115623474
Raw prediction for CHL: 0.49893322587013245
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5883470177650452
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5220990777015686
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5598903894424438
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6551458239555359
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4655771553516388
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5958300828933716
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5238936543464661
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4548167884349823
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5326482057571411
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5225077867507935
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5231477618217468
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5816525220870972
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.5080553889274597
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.7720082998275757
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5246022939682007
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5163870453834534
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5058405995368958
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.341093510389328
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.35676583647727966
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6127650737762451
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5065279603004456
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.506299614906311
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48120996356010437
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5021692514419556
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.6161002516746521
Calibrated prediction for MA: 0.75
Raw prediction for MCD: 0.6481489539146423
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.19222936034202576
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4852652847766876
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.2960267961025238
Calibrated prediction for MO: 0.6811326742172241
Raw prediction for MRK: 0.4812781512737274
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6834515929222107
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5247922539710999
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5957909822463989
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14231719076633453
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.26255008578300476
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5372523665428162
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5258022546768188
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.46048852801322937
Calibrated prediction for PEP: 0.5043432712554932
Raw prediction for PFE: 0.4728095531463623
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.3842601478099823
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.48433881998062134
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5165261030197144
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.34675905108451843
Calibrated prediction for PPL: 0.3212275505065918
Raw prediction for PTR: 0.5069050192832947
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4624938368797302
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.39514726400375366
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6572872400283813
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6065535545349121
Calibrated prediction for SNP: 0.4622011184692383
Raw prediction for SNY: 0.49355781078338623
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.47900599241256714
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.4868983030319214
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.6034210324287415
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7562747597694397
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4933875799179077
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5059143900871277
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5192082524299622
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.35329028964042664
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.42708539962768555
Calibrated prediction for UN: 0.4545454680919647
Raw prediction for UNH: 0.35321566462516785
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49050047993659973
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.7274673581123352
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5255453586578369
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6020045280456543
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5013760328292847
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  81%|████████  | 81/100 [01:36<00:23,  1.23s/it]

Raw prediction for WMT: 0.43226441740989685
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6211257576942444
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled XOM from top-3 (p=0.647)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-2 (p=0.681)
[PORT] Sector Financial: sampled MA from top-3 (p=0.750)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-07 00:00:00: MA p_up_1d=0.317 -> exit; r=0.0043, PnL=$28.63
[EARLY EXIT] 2017-08-07 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0244, PnL=$-63.85
Raw prediction for AAPL: 0.4934784173965454
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.658939778804779
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4894500970840454
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49379587173461914
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8704053163528442
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.44841036200523376
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5444371700286865
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.365169882774353
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5078253746032715
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44878003001213074
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49829602241516113
Calibrated prediction for BBL: 0.49967309832572937
Raw prediction for BCH: 0.4766583740711212
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49396201968193054
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5641811490058899
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48343798518180847
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4568288326263428
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5665169358253479
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5357450246810913
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48145776987075806
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.409145712852478
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4991115629673004
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.5929797291755676
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5219286680221558
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5554140210151672
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.664250373840332
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4642622172832489
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.596202552318573
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5233204960823059
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45461058616638184
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5325936675071716
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.517585813999176
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5230222940444946
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.6582943201065063
Calibrated prediction for GD: 0.6315789222717285
Raw prediction for GE: 0.49800533056259155
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.7604060769081116
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5242476463317871
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5180758833885193
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5071558356285095
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.3410029411315918
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.38314497470855713
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6015785932540894
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5069755911827087
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.505618155002594
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48110267519950867
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5018750429153442
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5992963910102844
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6560479402542114
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.20270612835884094
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4846985936164856
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.36592450737953186
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48051169514656067
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6765373349189758
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5248520374298096
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5970149636268616
Calibrated prediction for NGG: 0.6036604046821594
Raw prediction for NVS: 0.14435993134975433
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.2751263678073883
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5368527173995972
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5258917212486267
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.467667818069458
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4797919690608978
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.5001215934753418
Calibrated prediction for PG: 0.4749999940395355
Raw prediction for PICO: 0.4845905900001526
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5169300436973572
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.3480222821235657
Calibrated prediction for PPL: 0.32815685868263245
Raw prediction for PTR: 0.5068904161453247
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4620577096939087
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.39799433946609497
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6541538238525391
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6103898882865906
Calibrated prediction for SNP: 0.6666666865348816
Raw prediction for SNY: 0.4940548241138458
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4792250394821167
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.4869016110897064
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.60185307264328
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7328201532363892
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49270355701446533
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5051630139350891
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5190178751945496
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3531081974506378
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.43836623430252075
Calibrated prediction for UN: 0.46111246943473816
Raw prediction for UNH: 0.3573061525821686
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4906897246837616
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.7155047655105591
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5252349972724915
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6032639741897583
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  82%|████████▏ | 82/100 [01:37<00:22,  1.24s/it]

Raw prediction for WFC: 0.5015127062797546
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4299814701080322
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6369677782058716
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.667)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled NGG from top-3 (p=0.604)
[EARLY EXIT] 2017-08-08 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0028, PnL=$-4.15
[EARLY EXIT] 2017-08-08 00:00:00: MA p_up_1d=0.333 -> exit; r=-0.0041, PnL=$-6.25
Raw prediction for AAPL: 0.4941859543323517
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.6485183835029602
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48557808995246887
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.494123250246048
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.791631281375885
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.45277923345565796
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5462898015975952
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.3756794333457947
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5052465200424194
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44873085618019104
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49813148379325867
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4759790897369385
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49328678846359253
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5655878782272339
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4845176935195923
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45729807019233704
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5668624043464661
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5359737873077393
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4811570346355438
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4936504364013672
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4991019368171692
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6027770638465881
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5218114256858826
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5498363375663757
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.672442615032196
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4629173278808594
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5940711498260498
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5228588581085205
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4544701874256134
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5325291752815247
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5124431848526001
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5228114724159241
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.700253427028656
Calibrated prediction for GD: 0.6363636255264282
Raw prediction for GE: 0.4789744019508362
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.745236337184906
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.524888813495636
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5228619575500488
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5074094533920288
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.33588650822639465
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4016639292240143
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5952433347702026
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5073365569114685
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.5049399733543396
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.480979859828949
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5004069805145264
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5859090089797974
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6663814187049866
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.21011075377464294
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4841807186603546
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4068317115306854
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47964048385620117
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6651727557182312
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5245083570480347
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.597151517868042
Calibrated prediction for NGG: 0.6178560256958008
Raw prediction for NVS: 0.14363570511341095
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.29480844736099243
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5348942875862122
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5260255336761475
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.470260888338089
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4868350625038147
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.6108679175376892
Calibrated prediction for PG: 0.6153846383094788
Raw prediction for PICO: 0.4850381016731262
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5175248384475708
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.34500652551651
Calibrated prediction for PPL: 0.3116143047809601
Raw prediction for PTR: 0.506975531578064
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46151280403137207
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.3996654152870178
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6490631699562073
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6174664497375488
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.494430810213089
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4787653088569641
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.486876517534256
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5991010665893555
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7137677669525146
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49203845858573914
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5045710802078247
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5185407400131226
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.35956093668937683
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.4606296122074127
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3686107397079468
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4906163811683655
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.6784890294075012
Calibrated prediction for UTX: 0.75

Simulating Trading Days:  83%|████████▎ | 83/100 [01:39<00:21,  1.25s/it]

Raw prediction for V: 0.5247587561607361
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6038526892662048
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5015594959259033
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.428241103887558
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6412001848220825
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled MO from top-3 (p=0.707)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled NGG from top-3 (p=0.618)
[EARLY EXIT] 2017-08-09 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0084, PnL=$-10.61
[EARLY EXIT] 2017-08-09 00:00:00: MA p_up_1d=0.333 -> exit; r=-0.0009, PnL=$-1.16
Raw prediction for AAPL: 0.4956915080547333
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.6367429494857788
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4825800955295563
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49442848563194275
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8028966784477234
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.45501238107681274
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5468529462814331
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.39033210277557373
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.5027417540550232
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44858136773109436
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49790021777153015
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.47516727447509766
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49227532744407654
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5647080540657043
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48506054282188416
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45764079689979553
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5677785873413086
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5362638235092163
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.48075366020202637
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.537757158279419
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4989245533943176
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6081522703170776
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5218164324760437
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5531800985336304
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6777616143226624
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46173328161239624
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5903257727622986
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5225822329521179
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45440593361854553
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5325016975402832
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.506965160369873
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5224676132202148
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.7055214643478394
Calibrated prediction for GD: 0.6363636255264282
Raw prediction for GE: 0.4595150053501129
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.7277804613113403
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5261893272399902
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5276230573654175
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5058117508888245
Calibrated prediction for HRG: 0.5925925970077515
Raw prediction for HSBC: 0.33046749234199524
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.430740624666214
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.580422580242157
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5076916217803955
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.5030744075775146
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4809335172176361
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49831175804138184
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5813495516777039
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6669010519981384
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.21432887017726898
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.48374831676483154
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4340739846229553
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4783894121646881
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6501585245132446
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5239691734313965
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5962870717048645
Calibrated prediction for NGG: 0.5
Raw prediction for NVS: 0.13909812271595
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.30670639872550964
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5310713052749634
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5261339545249939
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4735337197780609
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.49297410249710083
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.6963205933570862
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4853420853614807
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5179809331893921
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.3347492814064026
Calibrated prediction for PPL: 0.30520927906036377
Raw prediction for PTR: 0.5070582628250122
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46108245849609375
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.39735570549964905
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6432531476020813
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6208175420761108
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4949103593826294
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4772868752479553
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.48677119612693787
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5953348875045776
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6994969248771667
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49147462844848633
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.503667414188385
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5177883505821228
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.37073618173599243
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.4724492132663727
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3799215257167816
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49035242199897766
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.6418384909629822
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5239882469177246
Calibrated prediction for V: 0.5184025168418884

Simulating Trading Days:  84%|████████▍ | 84/100 [01:40<00:19,  1.23s/it]

Raw prediction for VZ: 0.6039869785308838
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5016109943389893
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4263853430747986
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6378032565116882
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled SRE from top-3 (p=0.596)
[EARLY EXIT] 2017-08-10 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0038, PnL=$-4.16
[EARLY EXIT] 2017-08-10 00:00:00: MA p_up_1d=0.381 -> exit; r=-0.0158, PnL=$-15.76
Raw prediction for AAPL: 0.4959704577922821
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.624896764755249
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48048490285873413
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4947487711906433
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8013189435005188
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.45548978447914124
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5475124716758728
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.40608835220336914
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.49833449721336365
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4477498531341553
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49794259667396545
Calibrated prediction for BBL: 0.49546077847480774
Raw prediction for BCH: 0.4744827449321747
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4914931356906891
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5645041465759277
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4857082962989807
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.458309143781662
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5678073763847351
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5364909172058105
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4803313612937927
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5564404726028442
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49937909841537476
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6140708327293396
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5216808915138245
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5577191710472107
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6801654100418091
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46093958616256714
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5867091417312622
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5224338173866272
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45453721284866333
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5324459671974182
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.5021076798439026
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5221852660179138
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.6853503584861755
Calibrated prediction for GD: 0.6363636255264282
Raw prediction for GE: 0.4393979609012604
Calibrated prediction for GE: 0.41025641560554504
Raw prediction for GOOG: 0.7088794112205505
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5279823541641235
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5316795706748962
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.5030453205108643
Calibrated prediction for HRG: 0.577191948890686
Raw prediction for HSBC: 0.324420690536499
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4575346112251282
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5665314197540283
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5081301331520081
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4979824423789978
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4812217652797699
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49640145897865295
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5565240383148193
Calibrated prediction for MA: 0.7179487347602844
Raw prediction for MCD: 0.6669657230377197
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.21776682138442993
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48337820172309875
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.49552080035209656
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47743263840675354
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6343991756439209
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5236103534698486
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5953645706176758
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.13444533944129944
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.31520289182662964
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5267407894134521
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5263187885284424
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48145732283592224
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.49727874994277954
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7531455755233765
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48559871315956116
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5185626745223999
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.3260607421398163
Calibrated prediction for PPL: 0.30520927906036377
Raw prediction for PTR: 0.5072180032730103
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4607161283493042
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.39338165521621704
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6372319459915161
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.629416823387146
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4952715337276459
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4755415916442871
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.4868055582046509
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5872501134872437
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6905257701873779
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4908841848373413
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5033948421478271
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5169228911399841
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.3832401931285858
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.4854677617549896
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.38717344403266907
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4900272488594055
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.605503499507904
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5235021710395813
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6043296456336975
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5015355348587036
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  85%|████████▌ | 85/100 [01:41<00:18,  1.23s/it]

Raw prediction for WMT: 0.42526671290397644
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6354773640632629
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.718)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-11 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0011, PnL=$1.43
Raw prediction for AAPL: 0.4960516393184662
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.6134512424468994
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4791099727153778
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4947962760925293
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8432298302650452
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4544762372970581
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5476213693618774
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4201034903526306
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.49366089701652527
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.446778804063797
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4983414113521576
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4737282693386078
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49182334542274475
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5643824934959412
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48620834946632385
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4589398503303528
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5672536492347717
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5367429852485657
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.47988903522491455
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5477814674377441
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4997701644897461
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6176480650901794
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5215502381324768
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5596808195114136
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.682009220123291
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46067166328430176
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5829934477806091
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5223983526229858
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.454618901014328
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5323663353919983
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4946269989013672
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5218477249145508
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.6533443927764893
Calibrated prediction for GD: 0.6315789222717285
Raw prediction for GE: 0.417704701423645
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6888619661331177
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5302515029907227
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5308600664138794
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.500205934047699
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3164096772670746
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.48328205943107605
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5641534924507141
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5083655118942261
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.49154219031333923
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48159804940223694
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4954483211040497
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5253919959068298
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.6657953262329102
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.22036588191986084
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48292186856269836
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5436352491378784
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47676849365234375
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6187163591384888
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5232167840003967
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5935306549072266
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.131725013256073
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.31219807267189026
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5204232335090637
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.526515781879425
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48516884446144104
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.49891385436058044
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7872263193130493
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48578065633773804
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5188101530075073
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.3186725974082947
Calibrated prediction for PPL: 0.30520927906036377
Raw prediction for PTR: 0.5075735449790955
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4605525732040405
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.38811975717544556
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6341941952705383
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6336442828178406
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4951510727405548
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.47404342889785767
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.48679319024086
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5814725756645203
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6842381358146667
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4908924698829651
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5036638379096985
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5161018967628479
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.40063709020614624
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5106624364852905
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.39122703671455383
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4897105097770691
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5599583387374878
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5233873724937439
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6058778762817383
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5015137195587158
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.42425426840782166
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6272603869438171
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)

Simulating Trading Days:  86%|████████▌ | 86/100 [01:42<00:17,  1.22s/it]

[EARLY EXIT] 2017-08-14 00:00:00: MA p_up_1d=0.381 -> exit; r=0.0268, PnL=$32.32
[EARLY EXIT] 2017-08-14 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0022, PnL=$4.24
Raw prediction for AAPL: 0.49599871039390564
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.6043928861618042
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.47811880707740784
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4946010112762451
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.8325244784355164
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4534555673599243
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5467724204063416
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4315870404243469
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.4898831248283386
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4454602599143982
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49876531958580017
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4732256531715393
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4932679831981659
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5593689680099487
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.48661306500434875
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45960381627082825
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5654088258743286
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5369038581848145
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4794616997241974
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5198674201965332
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5007655620574951
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6180479526519775
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5213921666145325
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5571985244750977
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6825820207595825
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46066731214523315
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5810887217521667
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.522440493106842
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45457252860069275
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5322250127792358
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4868396818637848
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.521467387676239
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.6199191212654114
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.39048853516578674
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6710779070854187
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5324276685714722
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5265399813652039
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49773791432380676
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3071337938308716
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.5018553733825684
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5736203193664551
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.508502185344696
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4840572774410248
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4819256365299225
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4954123795032501
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4893779158592224
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6629709601402283
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.22044959664344788
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4825097620487213
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5545766353607178
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47646892070770264
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.605902910232544
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5230206847190857
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5924098491668701
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.13070818781852722
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.30534136295318604
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5165823101997375
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5267567038536072
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.48540017008781433
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.49670544266700745
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8015788793563843
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48600339889526367
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5188283920288086
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.3216494619846344
Calibrated prediction for PPL: 0.30520927906036377
Raw prediction for PTR: 0.507979154586792
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46040990948677063
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.38483837246894836
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6356678605079651
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6371804475784302
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4947342574596405
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4731496274471283
Calibrated prediction for SO: 0.4914637506008148
Raw prediction for SPLP: 0.4866798222064972
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5806057453155518
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6822465062141418
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4913344383239746
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5036625862121582
Calibrated prediction for TOT: 0.5130005478858948

Simulating Trading Days:  87%|████████▋ | 87/100 [01:43<00:15,  1.22s/it]

Raw prediction for TSM: 0.5154669880867004
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4163203239440918
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5320510268211365
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3899472653865814
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4894821047782898
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.496317058801651
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5234512686729431
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6065714955329895
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5015794038772583
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.42321503162384033
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.622532844543457
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled C from top-3 (p=0.537)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49544304609298706
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.6004865765571594
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4777870774269104
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4943492114543915
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.7865917682647705
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.45236873626708984
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5458483695983887
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4353357255458832
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.48708319664001465
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4445142149925232
Calibrated prediction for BAC: 0.46000993251800537
Raw prediction for BBL: 0.498981773853302
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.47290658950805664
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4942346513271332
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5460917949676514
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.486462265253067
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46007129549980164
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5624703168869019
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5369042158126831
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4791453182697296
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.47712481021881104
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5015708804130554
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6178642511367798
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.521223783493042
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5518274307250977
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6783774495124817
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46085500717163086
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5785133242607117
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5226848125457764
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45440319180488586
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5321113467216492
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4735815227031708
Calibrated prediction for EXC: 0.557894766330719
Raw prediction for FB: 0.5209736227989197
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5963764190673828
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.36824002861976624
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6546221375465393
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5345064401626587
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5232295989990234
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4958568215370178
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3035391867160797
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.509099006652832
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.5897271633148193
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5085896849632263
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.47800007462501526
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48213040828704834
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4961182773113251
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.48750513792037964
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.659442126750946
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.21704085171222687
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4821806252002716
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5327467322349548
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47671353816986084
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5971865057945251
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5223605036735535
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5910002589225769
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.13394415378570557
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.29970690608024597
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5123704075813293
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5269526243209839
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4806347191333771
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4938564896583557
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7983956933021545
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48610126972198486
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5185969471931458
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.32920223474502563
Calibrated prediction for PPL: 0.30520927906036377
Raw prediction for PTR: 0.5084335207939148
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46037545800209045
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.3838411271572113
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6433647871017456
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6352433562278748
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.49421805143356323
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.47160032391548157
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48664864897727966
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5825785398483276
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6867637038230896
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49195539951324463
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5032778382301331
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5152719020843506
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4240531623363495
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.5187733173370361
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.3823802173137665
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4893181025981903
Calibrated prediction for UPS: 0.4929138123989105

Simulating Trading Days:  88%|████████▊ | 88/100 [01:45<00:14,  1.22s/it]

Raw prediction for UTX: 0.47064781188964844
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5227993130683899
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6064208745956421
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5018230676651001
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.422563761472702
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6221526265144348
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.4942850172519684
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5964297652244568
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.477981299161911
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.494057297706604
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.7139813899993896
Calibrated prediction for AGFS: 0.7808899283409119
Raw prediction for AMGN: 0.4519882798194885
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5444449782371521
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.43042322993278503
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.4856029152870178
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4437084496021271
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4991688132286072
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.47273901104927063
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.49481841921806335
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5327379107475281
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4854716956615448
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4607977867126465
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5593878030776978
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5367904901504517
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4788615107536316
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.45797914266586304
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5019265413284302
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6178799271583557
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.521144449710846
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5425467491149902
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6744988560676575
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46114790439605713
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5755196809768677
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5228086113929749
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4538179934024811
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5319814085960388
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.45544081926345825
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5205920934677124
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.592029333114624
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.34786751866340637
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6426146626472473
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5364448428153992
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5218881368637085
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49447837471961975
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3054960072040558
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.5099478363990784
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6098198890686035
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5086420178413391
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4723665416240692
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4823741018772125
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4968942105770111
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.505145251750946
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.6558179259300232
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.21635732054710388
Calibrated prediction for MDT: 0.15463599562644958
Raw prediction for MMM: 0.4820420742034912
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5003622770309448
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4775007367134094
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.592833399772644
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5211918354034424
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5900221467018127
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.13855884969234467
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3019406795501709
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5081157088279724
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5269933938980103
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47523409128189087
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.4951016306877136
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7932857275009155
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48618122935295105
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5183793306350708
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.34283339977264404
Calibrated prediction for PPL: 0.30520927906036377
Raw prediction for PTR: 0.508916974067688
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46048861742019653
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.3846103250980377
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.657069742679596
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6380069851875305
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.49384579062461853
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46979475021362305
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48687979578971863
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5853950381278992
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.6945476531982422
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49239420890808105
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5034815669059753
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5156728029251099
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4270554780960083
Calibrated prediction for UL: 0.39589381217956543
Raw prediction for UN: 0.5009230375289917
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.37174099683761597
Calibrated prediction for UNH: 0.47727271914482117

Simulating Trading Days:  89%|████████▉ | 89/100 [01:46<00:13,  1.23s/it]

Raw prediction for UPS: 0.48923254013061523
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.46064814925193787
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5216363668441772
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6049507260322571
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5020365118980408
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.421676367521286
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6212776899337769
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.781)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled PFE from top-3 (p=0.561)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.4929092824459076
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5942259430885315
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4793066382408142
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4938212037086487
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.537327229976654
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.451602578163147
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5442143678665161
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.4219164550304413
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.48408398032188416
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4436584413051605
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.49942201375961304
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4725617468357086
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4960031807422638
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5231175422668457
Calibrated prediction for BP: 0.6341248750686646
Raw prediction for BRK-A: 0.4839909076690674
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4616628587245941
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5567672252655029
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5367864966392517
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.478655606508255
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.4587610960006714
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5017877817153931
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6265855431556702
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5208731889724731
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5429528951644897
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6734566688537598
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46139469742774963
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5741913914680481
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5229301452636719
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4525294005870819
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5317957401275635
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.4382566809654236
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.520426869392395
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5854060053825378
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.33692049980163574
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6345222592353821
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5382910966873169
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5223618149757385
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4933134615421295
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3078403174877167
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4908750057220459
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6277995705604553
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5086365342140198
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4687711298465729
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4826650321483612
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49731171131134033
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.510711669921875
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.6671565771102905
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.21910697221755981
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4819301962852478
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.47248679399490356
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47831833362579346
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5899316668510437
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5198593735694885
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5898581743240356
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14332203567028046
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.30795207619667053
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.506608784198761
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5278173685073853
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47090068459510803
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5002043843269348
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7852659821510315
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4862081706523895
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5179688930511475
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.36623090505599976
Calibrated prediction for PPL: 0.3333333432674408
Raw prediction for PTR: 0.5095499157905579
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4607325792312622
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.38718467950820923
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.6778907179832458
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6459715366363525
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4936354160308838
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4686378538608551
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48748019337654114
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5895242094993591
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7036478519439697
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4925723671913147
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5042207837104797
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5164824724197388
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4238017797470093
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.48092833161354065
Calibrated prediction for UN: 0.5199999809265137

Simulating Trading Days:  90%|█████████ | 90/100 [01:47<00:12,  1.23s/it]

Raw prediction for UNH: 0.3632972240447998
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4891955554485321
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.49575671553611755
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.520327091217041
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6043214797973633
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5017827153205872
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4226911962032318
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6211477518081665
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49166780710220337
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5963572263717651
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48004665970802307
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4936026334762573
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.3507712781429291
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4546835720539093
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.544059157371521
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.40458282828330994
Calibrated prediction for BA: 0.6041666865348816
Raw prediction for BABA: 0.48283591866493225
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4443329870700836
Calibrated prediction for BAC: 0.438865602016449
Raw prediction for BBL: 0.4997405707836151
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4728373885154724
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4974525570869446
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5131562948226929
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4815847873687744
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4625767767429352
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5545562505722046
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5366019010543823
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4784267246723175
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5170737504959106
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.5010324716567993
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6304675936698914
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5206912755966187
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.554543673992157
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6795339584350586
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4616486430168152
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5695202350616455
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5228394269943237
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45142677426338196
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5316423773765564
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.41703104972839355
Calibrated prediction for EXC: 0.4583333432674408
Raw prediction for FB: 0.5206640362739563
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5966055989265442
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.33074578642845154
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6322104930877686
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5397201776504517
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5256481170654297
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49199631810188293
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.31454527378082275
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.470084011554718
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6474572420120239
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5090101957321167
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.469818115234375
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4830598533153534
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.49833959341049194
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5142221450805664
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.6782116293907166
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.23969906568527222
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4819779396057129
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.466980904340744
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47882553935050964
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5912612080574036
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5187153816223145
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5891797542572021
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.1540030986070633
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.32442665100097656
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5049879550933838
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5289477109909058
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47124210000038147
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5021161437034607
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7938237190246582
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4862188398838043
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5177726149559021
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.38625138998031616
Calibrated prediction for PPL: 0.5
Raw prediction for PTR: 0.5103837251663208
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46140363812446594
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.38922521471977234
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.7012742757797241
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6465973854064941
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.49400126934051514
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46766290068626404
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4880123436450958
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5931849479675293
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7185021042823792
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.492947518825531
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5054634809494019
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5170711874961853
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.42465510964393616
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.49626490473747253
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.36590877175331116
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48922330141067505
Calibrated prediction for UPS: 0.4929138123989105

Simulating Trading Days:  91%|█████████ | 91/100 [01:48<00:11,  1.23s/it]

Raw prediction for UTX: 0.5311840772628784
Calibrated prediction for UTX: 0.6818181872367859
Raw prediction for V: 0.5184421539306641
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6039385795593262
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5017639994621277
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4240669012069702
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6170358061790466
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.682)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.4914526343345642
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5979899764060974
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48068374395370483
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49328869581222534
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.26260268688201904
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4573203921318054
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5439144968986511
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.3723599910736084
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.4815559387207031
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44595855474472046
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4999045431613922
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.47310516238212585
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.4990508258342743
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5010585784912109
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.4789382219314575
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4633818566799164
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5522515177726746
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5363858342170715
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4781897962093353
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5688934922218323
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.49941161274909973
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6305662393569946
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5205506682395935
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5636528134346008
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6884910464286804
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4620282053947449
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5648557543754578
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5227262377738953
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4507702887058258
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.531520664691925
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.40383005142211914
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5210743546485901
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5895981788635254
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.32774823904037476
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6304043531417847
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.540619432926178
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.531669020652771
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4911448061466217
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3252757489681244
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4568104147911072
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6733686327934265
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5093735456466675
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4750975966453552
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48338109254837036
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4995073676109314
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.5121789574623108
Calibrated prediction for MA: 0.6190476417541504
Raw prediction for MCD: 0.678017258644104
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.25384557247161865
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4820152521133423
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4638316035270691
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4790562391281128
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5905025005340576
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5179645419120789
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.589207649230957
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.1606934666633606
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.33501136302948
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5060157775878906
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5302098989486694
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.47167903184890747
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.503660261631012
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8064696192741394
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4863310754299164
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.517363965511322
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.41061511635780334
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5110640525817871
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46228066086769104
Calibrated prediction for RDS-B: 0.4591546058654785
Raw prediction for REX: 0.39028415083885193
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.7167237997055054
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6472331285476685
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4941856563091278
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4671555757522583
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4883432388305664
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.593080997467041
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.732928991317749
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49326178431510925
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5063157081604004
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5177434682846069
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4288351535797119
Calibrated prediction for UL: 0.4240281879901886
Raw prediction for UN: 0.5183975696563721
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.38670042157173157
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4893413186073303
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5576063990592957
Calibrated prediction for UTX: 0.75

Simulating Trading Days:  92%|█████████▏| 92/100 [01:50<00:09,  1.23s/it]

Raw prediction for V: 0.5162141919136047
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6031264066696167
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.501703679561615
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4257424473762512
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.6094101667404175
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.619)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-22 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0036, PnL=$6.96
Raw prediction for AAPL: 0.49167656898498535
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5973036289215088
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48141729831695557
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.4928811192512512
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.20459815859794617
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4574381709098816
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5436679124832153
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.33301836252212524
Calibrated prediction for BA: 0.6000000238418579
Raw prediction for BABA: 0.4801158905029297
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4476460814476013
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5001106858253479
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4729154407978058
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5007566809654236
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.4964192807674408
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.47663331031799316
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4637191891670227
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5502142906188965
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5362104177474976
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.47804731130599976
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5875573754310608
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4964755177497864
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6298428773880005
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5204137563705444
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5649725198745728
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6915791034698486
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4628284275531769
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5552033185958862
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5227099657058716
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4502680003643036
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5315238237380981
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.392506867647171
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5212987661361694
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5741303563117981
Calibrated prediction for GD: 0.6037735939025879
Raw prediction for GE: 0.3252582252025604
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6286841034889221
Calibrated prediction for GOOG: 0.6390929222106934
Raw prediction for HD: 0.5411030650138855
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5369039177894592
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4905226230621338
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3297156095504761
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.4563027620315552
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.6979079842567444
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5096835494041443
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4807785153388977
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4835367798805237
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5000344514846802
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.49078279733657837
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6769951581954956
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.2653689384460449
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4819858968257904
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4540018141269684
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4791831970214844
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.5925005078315735
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5168933868408203
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.587920606136322
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.15742337703704834
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.33445867896080017
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5056886076927185
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5313189625740051
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4674394130706787
Calibrated prediction for PEP: 0.517241358757019
Raw prediction for PFE: 0.5038098096847534
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8127899765968323
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48640912771224976
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5169786810874939
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4319867789745331
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5116947293281555
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.4633428752422333
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.390461802482605
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.7295611500740051
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6549724340438843
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4941265285015106
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4663391709327698
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48857033252716064
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5881711840629578
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7458930015563965
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4935353100299835
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5075446963310242
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5182843804359436
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4340333640575409
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5406541228294373
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.41032835841178894
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.48952922224998474
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5742462277412415
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5149886608123779
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6014112830162048
Calibrated prediction for VZ: 0.6145011186599731

Simulating Trading Days:  93%|█████████▎| 93/100 [01:51<00:08,  1.23s/it]

Raw prediction for WFC: 0.5012388825416565
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4274764358997345
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5932081341743469
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.593)
[EARLY EXIT] 2017-08-23 00:00:00: UTX p_up_1d=0.377 -> exit; r=0.0116, PnL=$19.15
Raw prediction for AAPL: 0.49188029766082764
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5963011980056763
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4818309247493744
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49241623282432556
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.19202446937561035
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4575766921043396
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.542940080165863
Calibrated prediction for AMZN: 0.5625287890434265
Raw prediction for BA: 0.2943580150604248
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.47910207509994507
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44845953583717346
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5002018809318542
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.47264108061790466
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5024537444114685
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.49774664640426636
Calibrated prediction for BP: 0.6315789222717285
Raw prediction for BRK-A: 0.47472965717315674
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.46393606066703796
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5474743843078613
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5357717871665955
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.47796136140823364
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.593831479549408
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4933352768421173
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6308221220970154
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5201506614685059
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5616797804832458
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6888560652732849
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4639664590358734
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5443096160888672
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5230721235275269
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4498869478702545
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.531484842300415
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.38026976585388184
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5213943123817444
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.554193377494812
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.3218786120414734
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6287252902984619
Calibrated prediction for GOOG: 0.6398380994796753
Raw prediction for HD: 0.5412763357162476
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5406842827796936
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4901604652404785
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3324074447154999
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.46889036893844604
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.724358856678009
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5099924206733704
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4844284951686859
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48342326283454895
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5005794167518616
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.46988674998283386
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.677793025970459
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.2799319326877594
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.4820077419281006
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4418526887893677
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4792008399963379
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6013969779014587
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5161622166633606
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5866454839706421
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.1513167768716812
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3281059265136719
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5046865344047546
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5322073101997375
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.45854952931404114
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.5029478669166565
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.8038597106933594
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48643913865089417
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5165343284606934
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.44732972979545593
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5121704936027527
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46447139978408813
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.39007991552352905
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.7407597899436951
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6510955691337585
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.49402791261672974
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4657101631164551
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4887842833995819
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5800073742866516
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7602772116661072
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4937058687210083
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5087253451347351
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5187207460403442
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.43469586968421936
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5447301864624023
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4252403676509857
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4896722137928009
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5873145461082458
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5145567655563354
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.600932240486145
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.500899076461792
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  94%|█████████▍| 94/100 [01:52<00:07,  1.23s/it]

Raw prediction for WMT: 0.4298672378063202
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5740184783935547
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-24 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0148, PnL=$-22.44
Raw prediction for AAPL: 0.4917578399181366
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5917569398880005
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4822463095188141
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49209651350975037
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.26403871178627014
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.45584702491760254
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5417022109031677
Calibrated prediction for AMZN: 0.5583828091621399
Raw prediction for BA: 0.25842225551605225
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.47905218601226807
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44874119758605957
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5000144243240356
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4725026488304138
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5033648014068604
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5279143452644348
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4733763039112091
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4630018472671509
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5448350310325623
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5352665185928345
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4779641330242157
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.5883472561836243
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4906005561351776
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6297978162765503
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.51991868019104
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5607291460037231
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6825002431869507
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46536555886268616
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.532235860824585
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5237115025520325
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.44988375902175903
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5312879681587219
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.36914631724357605
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.521541178226471
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5217291712760925
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.3205181360244751
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6316473484039307
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5400498509407043
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5422475337982178
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4900187849998474
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.33536601066589355
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.49687162041664124
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7463332414627075
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5101601481437683
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4863375127315521
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48294273018836975
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5010204315185547
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.44178885221481323
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6737430095672607
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.2976769208908081
Calibrated prediction for MDT: 0.31578946113586426
Raw prediction for MMM: 0.48214253783226013
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.43694841861724854
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.47918200492858887
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6145754456520081
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5158827900886536
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.586097240447998
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14045685529708862
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3134686052799225
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5023875832557678
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5328197479248047
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4480926990509033
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.5024088621139526
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7878493666648865
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48641782999038696
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5159580707550049
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4511266052722931
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5124991536140442
Calibrated prediction for PTR: 0.5125657320022583
Raw prediction for RDS-B: 0.46536391973495483
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3889111280441284
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.747757077217102
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6381691098213196
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4936840236186981
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4652392566204071
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4888722002506256
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.569398820400238
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7745153307914734
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4937867820262909
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5089830756187439
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5191420316696167
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4319545328617096
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5285804271697998
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4406331777572632
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4897996187210083
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.6003518104553223
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5148157477378845
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6017204523086548
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5006109476089478
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  95%|█████████▌| 95/100 [01:53<00:06,  1.23s/it]

Raw prediction for WMT: 0.43278300762176514
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5482841730117798
Calibrated prediction for XOM: 0.6466009020805359
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled CODI from top-3 (p=0.660)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] 2017-08-25 00:00:00: UTX p_up_1d=0.377 -> exit; r=-0.0020, PnL=$-5.87
Raw prediction for AAPL: 0.4916078746318817
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5866823792457581
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48242098093032837
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49192777276039124
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.3279397487640381
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.45722338557243347
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.541658341884613
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.2318502962589264
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.479959636926651
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.44900116324424744
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5000065565109253
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4726150929927826
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5043002367019653
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.5719189047813416
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4724763035774231
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4621778726577759
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5425035357475281
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5347530245780945
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4778914451599121
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6117466688156128
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4887029826641083
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6337283253669739
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.519477128982544
Calibrated prediction for CMCSA: 0.5299521684646606
Raw prediction for CODI: 0.5597413778305054
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6810219287872314
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4669506549835205
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5246229767799377
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5242825746536255
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.44990506768226624
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5311194062232971
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.3669060468673706
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5220280289649963
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.51744145154953
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.32000645995140076
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6415759325027466
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5375779867172241
Calibrated prediction for HD: 0.5447222590446472
Raw prediction for HON: 0.5446819067001343
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4901669919490814
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3382851183414459
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.5203779339790344
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7696895003318787
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5102471709251404
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.4878407418727875
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.482513427734375
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5021904706954956
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.41160374879837036
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6719670295715332
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.32830652594566345
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.48232144117355347
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4404692053794861
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4789958894252777
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6281993389129639
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5163154006004333
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5866954326629639
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14022473990917206
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.3091225028038025
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.505989134311676
Calibrated prediction for PCG: 0.45090925693511963
Raw prediction for PCLN: 0.5333151817321777
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4431808292865753
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.49828672409057617
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.7734029293060303
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4866124093532562
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5154162645339966
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.45977339148521423
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5129022002220154
Calibrated prediction for PTR: 0.5136004686355591
Raw prediction for RDS-B: 0.46618130803108215
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.38639965653419495
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.751979649066925
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6348608136177063
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4937041401863098
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4657125473022461
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4888796806335449
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5585399270057678
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.7914387583732605
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.49388301372528076
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5096531510353088
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5194407105445862
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4311741590499878
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5240258574485779
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4459201991558075
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4899028241634369
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.587517261505127
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5154654383659363
Calibrated prediction for V: 0.5184025168418884

Simulating Trading Days:  96%|█████████▌| 96/100 [01:55<00:04,  1.24s/it]

Raw prediction for VZ: 0.6112250089645386
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5005350112915039
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.43585556745529175
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.5186623930931091
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49197566509246826
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5822927355766296
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48260292410850525
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49205321073532104
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.326067179441452
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.4600540101528168
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5416489243507385
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.21448342502117157
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.4815160036087036
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4497416317462921
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.5000346302986145
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4725675880908966
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5053879618644714
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.6063507795333862
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47180500626564026
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4612732231616974
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5407555103302002
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5344358086585999
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4779071807861328
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6414546966552734
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.48816797137260437
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6333504319190979
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.519223153591156
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5516536831855774
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.6930932998657227
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.46813634037971497
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5151731967926025
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5247019529342651
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4501771330833435
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5309373140335083
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.36562249064445496
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5227306485176086
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5251621603965759
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.3242367208003998
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6556912064552307
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5343426465988159
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5478065609931946
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.490882009267807
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3402957618236542
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.5219793319702148
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7812396287918091
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5101742148399353
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.48937878012657166
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48236405849456787
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5031207203865051
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.3869590163230896
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6671380996704102
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.3615266680717468
Calibrated prediction for MDT: 0.3461538553237915
Raw prediction for MMM: 0.4824163019657135
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4590131342411041
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4795156717300415
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6349632740020752
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5165371894836426
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5868561267852783
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.14870578050613403
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.307978093624115
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5116782188415527
Calibrated prediction for PCG: 0.5352627038955688
Raw prediction for PCLN: 0.5338558554649353
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.44533661007881165
Calibrated prediction for PEP: 0.4381181597709656
Raw prediction for PFE: 0.49326542019844055
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.754864513874054
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4869357645511627
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5150437355041504
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.46492311358451843
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5131426453590393
Calibrated prediction for PTR: 0.5136004686355591
Raw prediction for RDS-B: 0.46681147813796997
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.38579970598220825
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.7561512589454651
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6485316753387451
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.49390819668769836
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.46531274914741516
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48869186639785767
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5461513996124268
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.8065590858459473
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4938969314098358
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.51006019115448
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5196214914321899
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.43221819400787354
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5265392661094666
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.44970017671585083
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.49016183614730835
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5722906589508057
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5162584781646729
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6310615539550781
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5004684925079346
Calibrated prediction for WFC: 0.50567626953125

Simulating Trading Days:  97%|█████████▋| 97/100 [01:56<00:03,  1.23s/it]

Raw prediction for WMT: 0.4386068284511566
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.4991520643234253
Calibrated prediction for XOM: 0.53125
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
Raw prediction for AAPL: 0.49286454916000366
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5797586441040039
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48315155506134033
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49227413535118103
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.31835269927978516
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.46325743198394775
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5416651368141174
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.2016303837299347
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.4835011065006256
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.4508970081806183
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49990180134773254
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.4724534749984741
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5058373212814331
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.6305735111236572
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4713684022426605
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4602636992931366
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5393420457839966
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5342186093330383
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.4779064655303955
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6715778112411499
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4880637228488922
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6279153823852539
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5190739035606384
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5378596186637878
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.707334578037262
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4687354266643524
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5082498788833618
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5248845219612122
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45062050223350525
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5308021903038025
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.364280104637146
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5234405398368835
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5473057627677917
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.3265574872493744
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.666354238986969
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5307527780532837
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.55057293176651
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.4919722378253937
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.34246641397476196
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.5113002061843872
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7883890271186829
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5098928213119507
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.49158164858818054
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48253676295280457
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.502865731716156
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.3891201615333557
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6624443531036377
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.3935312330722809
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.48249155282974243
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.4863339960575104
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.48000508546829224
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6340472102165222
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5160401463508606
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5861856341362
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.1596149355173111
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.309442937374115
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5171154141426086
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5343846082687378
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.44947168231010437
Calibrated prediction for PEP: 0.45267122983932495
Raw prediction for PFE: 0.48596370220184326
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.724533200263977
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.48734238743782043
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5148047208786011
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4708430767059326
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5129748582839966
Calibrated prediction for PTR: 0.5136004686355591
Raw prediction for RDS-B: 0.4671359062194824
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.3866974711418152
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.7595318555831909
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6574187874794006
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.49407634139060974
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4649169445037842
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4884021580219269
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5361562371253967
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.8192765116691589
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4938788414001465
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5100331902503967
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5196650624275208
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.4334056079387665
Calibrated prediction for UL: 0.44285714626312256
Raw prediction for UN: 0.5291547775268555
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.46263939142227173
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.4904939532279968
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5634307861328125
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5167232155799866
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6461105346679688
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5003799796104431
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.44105765223503113
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.4805837571620941
Calibrated prediction for XOM: 0.5263158082962036
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled C from top-3 (p=0.537)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)

Simulating Trading Days:  98%|█████████▊| 98/100 [01:57<00:02,  1.23s/it]

Raw prediction for AAPL: 0.4935944378376007
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5784543752670288
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.48405522108078003
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49244144558906555
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.41029536724090576
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.46354660391807556
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5414695143699646
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.1874653398990631
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.48613718152046204
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.45150503516197205
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.49975156784057617
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.47222357988357544
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5058937668800354
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.6430178880691528
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.4713554382324219
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.4584742486476898
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5380157828330994
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5340017080307007
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.47804558277130127
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6743438839912415
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4878753125667572
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6193076968193054
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5190349817276001
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.5154843926429749
Calibrated prediction for CODI: 0.6603077054023743
Raw prediction for CSCO: 0.7191821932792664
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4691302478313446
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5062057375907898
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5250095725059509
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.4510120749473572
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5306696891784668
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.36197105050086975
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5237189531326294
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5367966890335083
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.3230912685394287
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6729630827903748
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.5275508761405945
Calibrated prediction for HD: 0.5348837375640869
Raw prediction for HON: 0.5507307648658752
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49335697293281555
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.34425950050354004
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.5068069100379944
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7874651551246643
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5096851587295532
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.49233582615852356
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.48301196098327637
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.5012853741645813
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.3951198160648346
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6573814749717712
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.42846745252609253
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.48268014192581177
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.5141620635986328
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4804648160934448
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6306340098381042
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5152599811553955
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5843157768249512
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.1654909998178482
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.30420830845832825
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5191808938980103
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5348299145698547
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4557816684246063
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4834097921848297
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.6948952078819275
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4876420497894287
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5147352814674377
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.4776383638381958
Calibrated prediction for PPL: 0.6000000238418579
Raw prediction for PTR: 0.5125404596328735
Calibrated prediction for PTR: 0.5136004686355591
Raw prediction for RDS-B: 0.4672875702381134
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.38920050859451294
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.7612009048461914
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.657328188419342
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4939841628074646
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4646371901035309
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.48812785744667053
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5251641869544983
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.8253656625747681
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4937730133533478
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5096784234046936
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5197522640228271
Calibrated prediction for TSM: 0.5204885601997375
Raw prediction for UL: 0.42998823523521423
Calibrated prediction for UL: 0.4422569274902344

Simulating Trading Days:  99%|█████████▉| 99/100 [01:58<00:01,  1.24s/it]

Raw prediction for UN: 0.5174490809440613
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.4615703821182251
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.490756630897522
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.5767143368721008
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5172595977783203
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.6505171060562134
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5001614689826965
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4433504045009613
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.46652498841285706
Calibrated prediction for XOM: 0.5263158082962036
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled JPM from top-3 (p=0.540)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled PPL from top-3 (p=0.600)
Raw prediction for AAPL: 0.4942416846752167
Calibrated prediction for AAPL: 0.49523910880088806
Raw prediction for ABB: 0.5759978294372559
Calibrated prediction for ABB: 0.5777682065963745
Raw prediction for ABBV: 0.4853902757167816
Calibrated prediction for ABBV: 0.4920310378074646
Raw prediction for AEP: 0.49244943261146545
Calibrated prediction for AEP: 0.49717235565185547
Raw prediction for AGFS: 0.49675068259239197
Calibrated prediction for AGFS: 0.7058823704719543
Raw prediction for AMGN: 0.46400102972984314
Calibrated prediction for AMGN: 0.43275272846221924
Raw prediction for AMZN: 0.5409270524978638
Calibrated prediction for AMZN: 0.5581395626068115
Raw prediction for BA: 0.17799001932144165
Calibrated prediction for BA: 0.255067378282547
Raw prediction for BABA: 0.4890449643135071
Calibrated prediction for BABA: 0.5143052935600281
Raw prediction for BAC: 0.45166656374931335
Calibrated prediction for BAC: 0.4973319470882416
Raw prediction for BBL: 0.4995056390762329
Calibrated prediction for BBL: 0.5010122060775757
Raw prediction for BCH: 0.47203904390335083
Calibrated prediction for BCH: 0.4823146164417267
Raw prediction for BHP: 0.5051605701446533
Calibrated prediction for BHP: 0.5056179761886597
Raw prediction for BP: 0.644358217716217
Calibrated prediction for BP: 0.6582278609275818
Raw prediction for BRK-A: 0.47152748703956604
Calibrated prediction for BRK-A: 0.46744540333747864
Raw prediction for BSAC: 0.45723724365234375
Calibrated prediction for BSAC: 0.48030078411102295
Raw prediction for BUD: 0.5374061465263367
Calibrated prediction for BUD: 0.4681812822818756
Raw prediction for C: 0.5336698889732361
Calibrated prediction for C: 0.5372885465621948
Raw prediction for CAT: 0.478060781955719
Calibrated prediction for CAT: 0.4831085205078125
Raw prediction for CELG: 0.6683090329170227
Calibrated prediction for CELG: 0.5824176073074341
Raw prediction for CHL: 0.4867415428161621
Calibrated prediction for CHL: 0.4380493760108948
Raw prediction for CHTR: 0.6088217496871948
Calibrated prediction for CHTR: 0.6797494888305664
Raw prediction for CMCSA: 0.5189110040664673
Calibrated prediction for CMCSA: 0.5184553861618042
Raw prediction for CODI: 0.49818289279937744
Calibrated prediction for CODI: 0.6000000238418579
Raw prediction for CSCO: 0.7228642702102661
Calibrated prediction for CSCO: 0.7346938848495483
Raw prediction for CVX: 0.4693502187728882
Calibrated prediction for CVX: 0.4715467691421509
Raw prediction for D: 0.5091014504432678
Calibrated prediction for D: 0.6092303395271301
Raw prediction for DHR: 0.5252286791801453
Calibrated prediction for DHR: 0.5264612436294556
Raw prediction for DIS: 0.45124566555023193
Calibrated prediction for DIS: 0.47572293877601624
Raw prediction for DUK: 0.5306070446968079
Calibrated prediction for DUK: 0.5308995842933655
Raw prediction for EXC: 0.36137330532073975
Calibrated prediction for EXC: 0.40226680040359497
Raw prediction for FB: 0.5238162279129028
Calibrated prediction for FB: 0.5437261462211609
Raw prediction for GD: 0.5270902514457703
Calibrated prediction for GD: 0.5348837375640869
Raw prediction for GE: 0.318058043718338
Calibrated prediction for GE: 0.368339478969574
Raw prediction for GOOG: 0.6780838370323181
Calibrated prediction for GOOG: 0.6666666865348816
Raw prediction for HD: 0.525456428527832
Calibrated prediction for HD: 0.5189655423164368
Raw prediction for HON: 0.5496572852134705
Calibrated prediction for HON: 0.5580855011940002
Raw prediction for HRG: 0.49423515796661377
Calibrated prediction for HRG: 0.4945119619369507
Raw prediction for HSBC: 0.3473958671092987
Calibrated prediction for HSBC: 0.39440616965293884
Raw prediction for IEP: 0.49771392345428467
Calibrated prediction for IEP: 0.36486485600471497
Raw prediction for INTC: 0.7814968824386597
Calibrated prediction for INTC: 0.6201955080032349
Raw prediction for JNJ: 0.5095611214637756
Calibrated prediction for JNJ: 0.5031769871711731
Raw prediction for JPM: 0.49159806966781616
Calibrated prediction for JPM: 0.5398507714271545
Raw prediction for KO: 0.4836280047893524
Calibrated prediction for KO: 0.486714243888855
Raw prediction for LMT: 0.4996001422405243
Calibrated prediction for LMT: 0.5116209387779236
Raw prediction for MA: 0.4075571298599243
Calibrated prediction for MA: 0.5384615659713745
Raw prediction for MCD: 0.6536335945129395
Calibrated prediction for MCD: 0.7658193707466125
Raw prediction for MDT: 0.4551738500595093
Calibrated prediction for MDT: 0.41860464215278625
Raw prediction for MMM: 0.4826911389827728
Calibrated prediction for MMM: 0.47710198163986206
Raw prediction for MO: 0.534967839717865
Calibrated prediction for MO: 0.7067669034004211
Raw prediction for MRK: 0.4811239540576935
Calibrated prediction for MRK: 0.5095897316932678
Raw prediction for MSFT: 0.6269165873527527
Calibrated prediction for MSFT: 0.6319780945777893
Raw prediction for NEE: 0.5144501328468323
Calibrated prediction for NEE: 0.5354850888252258
Raw prediction for NGG: 0.5822051167488098
Calibrated prediction for NGG: 0.4754098355770111
Raw prediction for NVS: 0.16973567008972168
Calibrated prediction for NVS: 0.2574159801006317
Raw prediction for ORCL: 0.298818975687027
Calibrated prediction for ORCL: 0.20715348422527313
Raw prediction for PCG: 0.5180179476737976
Calibrated prediction for PCG: 0.5673834681510925
Raw prediction for PCLN: 0.5350677371025085
Calibrated prediction for PCLN: 0.5328987240791321
Raw prediction for PEP: 0.4622384309768677
Calibrated prediction for PEP: 0.5166299343109131
Raw prediction for PFE: 0.48656708002090454
Calibrated prediction for PFE: 0.5614035129547119
Raw prediction for PG: 0.678212583065033
Calibrated prediction for PG: 0.7894737124443054
Raw prediction for PICO: 0.4879607856273651
Calibrated prediction for PICO: 0.47776350378990173
Raw prediction for PM: 0.5146873593330383
Calibrated prediction for PM: 0.5191575288772583
Raw prediction for PPL: 0.47199714183807373
Calibrated prediction for PPL: 0.5932203531265259
Raw prediction for PTR: 0.5118728280067444
Calibrated prediction for PTR: 0.503956139087677
Raw prediction for RDS-B: 0.46715468168258667
Calibrated prediction for RDS-B: 0.4677354693412781
Raw prediction for REX: 0.39317333698272705
Calibrated prediction for REX: 0.36107510328292847
Raw prediction for SLB: 0.7614246606826782
Calibrated prediction for SLB: 0.6331362724304199
Raw prediction for SNP: 0.6417211294174194
Calibrated prediction for SNP: 0.7121211886405945
Raw prediction for SNY: 0.4939498007297516
Calibrated prediction for SNY: 0.5086206793785095
Raw prediction for SO: 0.4645266532897949
Calibrated prediction for SO: 0.4545454680919647
Raw prediction for SPLP: 0.4877772629261017
Calibrated prediction for SPLP: 0.5045595169067383
Raw prediction for SRE: 0.5181851387023926
Calibrated prediction for SRE: 0.5960687398910522
Raw prediction for T: 0.8269046545028687
Calibrated prediction for T: 0.7028569579124451
Raw prediction for TM: 0.4935615658760071
Calibrated prediction for TM: 0.4762147068977356
Raw prediction for TOT: 0.5089958906173706
Calibrated prediction for TOT: 0.5130005478858948
Raw prediction for TSM: 0.5197806358337402
Calibrated prediction for TSM: 0.5204885601997375

Simulating Trading Days: 100%|██████████| 100/100 [01:59<00:00,  1.20s/it]

Raw prediction for UL: 0.42462560534477234
Calibrated prediction for UL: 0.3837940990924835
Raw prediction for UN: 0.504864513874054
Calibrated prediction for UN: 0.5199999809265137
Raw prediction for UNH: 0.45329251885414124
Calibrated prediction for UNH: 0.47727271914482117
Raw prediction for UPS: 0.490923136472702
Calibrated prediction for UPS: 0.4929138123989105
Raw prediction for UTX: 0.593291699886322
Calibrated prediction for UTX: 0.75
Raw prediction for V: 0.5175606608390808
Calibrated prediction for V: 0.5184025168418884
Raw prediction for VZ: 0.648307204246521
Calibrated prediction for VZ: 0.6145011186599731
Raw prediction for WFC: 0.5000134110450745
Calibrated prediction for WFC: 0.50567626953125
Raw prediction for WMT: 0.4453279674053192
Calibrated prediction for WMT: 0.4833378791809082
Raw prediction for XOM: 0.45438945293426514
Calibrated prediction for XOM: 0.5263158082962036
[PORT] Received 87 predictions for sizing.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (p=0.712)
[PORT] Sector Conglomerates: sampled AGFS from top-3 (p=0.706)
[PORT] Sector Consumer Goods: sampled PG from top-3 (p=0.789)
[PORT] Sector Financial: sampled MA from top-3 (p=0.538)
[PORT] Sector Healthcare: sampled CELG from top-3 (p=0.582)
[PORT] Sector Industrial Goods: sampled UTX from top-3 (p=0.750)
[PORT] Sector Services: sampled MCD from top-3 (p=0.766)
[PORT] Sector Technology: sampled CSCO from top-3 (p=0.735)
[PORT] Sector Utilities: sampled D from top-3 (p=0.609)
[EARLY EXIT] Total early exits: 60
[EARLY EXIT] PnL realized from early exits: $592.60
[EARLY EXIT] PnL if held to horizon: $1,941.18 (n=60)
[EARLY EXIT] Delta vs hold-to-horizon: $-1,348.58

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,early_exits_today,use_mpt,mpt_fallback_used,mpt_weights,budget_pre_mpt,budget_post_caps,mpt_hhi,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.1189428233011087, 'AGFS': 0.25, 'UN':...",34355.169851,30000.000000,0.211281,"[{'ticker': 'UN', 'investment_fraction': 0.073..."
1,2017-04-12,70000.000000,48129.407501,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.1629283484893179, 'AGFS': 0.249999999...",21870.592499,21870.592499,0.190409,"[{'ticker': 'AGFS', 'investment_fraction': 0.0..."
2,2017-04-13,48129.407501,33091.356933,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.16504325275126427, 'AGFS': 0.24999999...",15038.050568,15038.050568,0.190592,"[{'ticker': 'AGFS', 'investment_fraction': 0.0..."
3,2017-04-17,33091.356933,30000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.24976929108123544, 'AGFS': 0.24999999...",10020.695334,3091.356933,0.210396,"[{'ticker': 'MO', 'investment_fraction': 0.042..."
4,2017-04-18,30000.000000,30000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.15196785493245726, 'AGFS': 0.25, 'MO'...",8941.375513,0.000000,0.188982,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2017-08-25,65000.691563,65000.691563,112440.397311,112440.397311,317.989032,0.002836,1,True,False,"{'SNP': 0.25, 'AGFS': 0.24999999999999978, 'PG...",22781.432511,8985.808424,0.216317,[]
96,2017-08-28,87919.935206,87919.935206,112748.632097,112748.632097,308.234785,0.002741,0,True,False,"{'SNP': 0.24999999999999964, 'AGFS': 0.2499999...",30994.246817,8985.808424,0.216061,[]
97,2017-08-29,101641.038878,101641.038878,112864.489769,112864.489769,115.857672,0.001028,0,True,False,"{'SNP': 0.2499999999999999, 'AGFS': 0.24999999...",35616.904060,8985.808424,0.215406,[]
98,2017-08-30,106928.618927,106928.618927,112974.236239,112974.236239,109.746471,0.000972,0,True,False,"{'SNP': 0.2500000000000001, 'AGFS': 0.25000000...",37429.617450,8985.808424,0.215935,[]
99,2017-08-31,113113.215447,113113.215447,113113.215447,113113.215447,138.979207,0.001230,0,True,False,"{'SNP': 0.24999999999999972, 'AGFS': 0.2499999...",39630.285315,8985.808424,0.215210,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,early_exits_today,use_mpt,mpt_fallback_used,mpt_weights,budget_pre_mpt,budget_post_caps,mpt_hhi,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.1189428233011087, 'AGFS': 0.25, 'UN':...",34355.169851,30000.000000,0.211281,"[{'ticker': 'UN', 'investment_fraction': 0.073..."
1,2017-04-12,70000.000000,48129.407501,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.1629283484893179, 'AGFS': 0.249999999...",21870.592499,21870.592499,0.190409,"[{'ticker': 'AGFS', 'investment_fraction': 0.0..."
2,2017-04-13,48129.407501,33091.356933,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.16504325275126427, 'AGFS': 0.24999999...",15038.050568,15038.050568,0.190592,"[{'ticker': 'AGFS', 'investment_fraction': 0.0..."
3,2017-04-17,33091.356933,30000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.24976929108123544, 'AGFS': 0.24999999...",10020.695334,3091.356933,0.210396,"[{'ticker': 'MO', 'investment_fraction': 0.042..."
4,2017-04-18,30000.000000,30000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'BP': 0.15196785493245726, 'AGFS': 0.25, 'MO'...",8941.375513,0.000000,0.188982,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2017-08-25,65000.691563,65000.691563,112440.397311,112440.397311,317.989032,0.002836,1,True,False,"{'SNP': 0.25, 'AGFS': 0.24999999999999978, 'PG...",22781.432511,8985.808424,0.216317,[]
96,2017-08-28,87919.935206,87919.935206,112748.632097,112748.632097,308.234785,0.002741,0,True,False,"{'SNP': 0.24999999999999964, 'AGFS': 0.2499999...",30994.246817,8985.808424,0.216061,[]
97,2017-08-29,101641.038878,101641.038878,112864.489769,112864.489769,115.857672,0.001028,0,True,False,"{'SNP': 0.2499999999999999, 'AGFS': 0.24999999...",35616.904060,8985.808424,0.215406,[]
98,2017-08-30,106928.618927,106928.618927,112974.236239,112974.236239,109.746471,0.000972,0,True,False,"{'SNP': 0.2500000000000001, 'AGFS': 0.25000000...",37429.617450,8985.808424,0.215935,[]
99,2017-08-31,113113.215447,113113.215447,113113.215447,113113.215447,138.979207,0.001230,0,True,False,"{'SNP': 0.24999999999999972, 'AGFS': 0.2499999...",39630.285315,8985.808424,0.215210,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $113,113.22
Total Return on Investment (ROI): 13.11%
Annualized Sharpe Ratio: 5.89
--------------------------

In [32]:
import numpy as np
import pandas as pd

all_trades = []
sector_lookup = None
if 'sector' in master_df.columns:
    sector_lookup = master_df.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    exits = row.get('exits_today', [])
    if not isinstance(exits, list):
        continue
    for ex in exits:
        if not isinstance(ex, dict):
            continue
        ticker = ex.get('ticker')
        if ticker is None:
            continue
        allocated = ex.get('allocated_amount', ex.get('invest', np.nan))
        sector = ex.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = ex.get('prob_up', np.nan)
        expected_rise = ex.get('expected_rise', np.nan)
        exit_date = ex.get('exit_date')
        actual_return = ex.get('actual_return', np.nan)
        pnl = ex.get('pnl', np.nan)
        exit_reason = ex.get('exit_reason', 'unknown')
        all_trades.append({
            'date': ex.get('date', row.get('date')),
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': actual_return,
            'pnl': pnl,
            'exit_reason': exit_reason,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))

        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        all_tickers = master_df['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 347
Total capital allocated: $1,344,841.57
Average position size:  $3,875.62
Completed trades with returns: 347
Winning trades: 216 (62.2%)
Losing trades:  127 (36.6%)
Total PnL: $14,461.80
Average PnL per trade: $41.68
Average return: 0.81%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Conglomerates,57,301212.247964,5284.425403,7510.228078,131.758387,0.022386
Services,44,207898.399893,4724.963634,3047.451166,69.260254,0.012878
Financial,35,137961.878993,3941.767971,2148.342123,61.381204,0.012945
Technology,51,245251.697293,4808.856810,1492.304213,29.260867,0.007405
Utilities,21,39205.319303,1866.919967,293.828880,13.991851,0.006329
Basic Matierials,48,161730.986924,3369.395561,146.055521,3.042823,0.001485
Healthcare,30,75596.569538,2519.885651,137.255468,4.575182,-0.000393
Industrial Goods,20,46884.406987,2344.220349,74.103849,3.705192,0.000031
Consumer Goods,41,129100.064768,3148.782068,-387.773991,-9.457902,-0.001226

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
60,2017-05-04,2017-05-11,AGFS,Conglomerates,5020.753660,0.780890,NaN,0.314176,1577.401533
1,2017-04-11,2017-04-19,AGFS,Conglomerates,8588.792463,0.780890,NaN,0.158000,1357.029209
66,2017-05-05,2017-05-12,AGFS,Conglomerates,5339.384437,0.780890,NaN,0.249104,1330.061715
56,2017-05-03,2017-05-10,AGFS,Conglomerates,4888.417440,0.780890,NaN,0.212569,1039.127552
5,2017-04-12,2017-04-20,AGFS,Conglomerates,5467.648125,0.780890,NaN,0.129630,708.769201
11,2017-04-13,2017-04-21,AGFS,Conglomerates,3759.512642,0.780890,NaN,0.180698,679.336987
205,2017-07-03,2017-07-11,AGFS,Conglomerates,6806.306862,0.705882,NaN,0.097297,662.235262
200,2017-06-30,2017-07-10,AGFS,Conglomerates,5884.044241,0.722726,NaN,0.111421,655.603815
195,2017-06-29,2017-07-07,AGFS,Conglomerates,7067.451463,0.780890,NaN,0.083447,589.759972
111,2017-05-23,2017-05-31,CHTR,Services,5730.491937,0.679749,NaN,0.083942,481.030897

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
41,2017-04-27,2017-05-04,AGFS,Conglomerates,5286.597662,0.780890,NaN,-0.103093,-545.010068
249,2017-07-21,2017-07-28,AGFS,Conglomerates,5132.787862,0.705882,NaN,-0.085155,-437.084352
252,2017-07-24,2017-07-31,AGFS,Conglomerates,4249.084616,0.705882,NaN,-0.102417,-435.176675
256,2017-07-25,2017-08-01,AGFS,Conglomerates,3753.874146,0.705882,NaN,-0.093533,-351.112940
276,2017-08-01,2017-08-08,AGFS,Conglomerates,5080.502636,0.780890,NaN,-0.061146,-310.654938
37,2017-04-26,2017-05-03,AGFS,Conglomerates,5286.083404,0.780890,NaN,-0.050877,-268.941085
313,2017-08-11,2017-08-18,AGFS,Conglomerates,6313.134366,0.780890,NaN,-0.039726,-250.795749
133,2017-06-02,2017-06-09,CHTR,Services,4098.707376,0.679749,NaN,-0.057191,-234.407598
134,2017-06-05,2017-06-12,AGFS,Conglomerates,4524.014201,0.780890,NaN,-0.051351,-232.314243
319,2017-08-14,2017-08-21,CSCO,Technology,6303.401086,0.734694,NaN,-0.036432,-229.646522

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Conglomerates     7510.228078
Services          3047.451166
Financial         2148.342123
Technology        1492.304213
Utilities          293.828880
Basic Matierials   146.055521
Healthcare         137.255468
Industrial Goods    74.103849
Consumer Goods    -387.773991

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Conglomerates     7510.228078
Services          3047.451166
Financial         2148.342123
Technology        1492.304213
Utilities          293.828880
Basic Matierials   146.055521
Healthcare         137.255468
Industrial Goods    74.103849
Consumer Goods    -387.773991

Top 10 Most Invested Tickers:

ticker
AGFS    57
CSCO    40
MA      35
BP      31
CELG    30
CHTR    30
UTX     20
PPL     20
PG      17
MCD     14
Name: count, dtype: int64

Tickers Never Invested In (70):
{'AMZN', 'VZ', 'SO', 'PICO', 'EXC', 'DUK', 'V', 'PFE', 'ORCL', 'MMM', 'INTC', 'FB', 'PCG', 'IEP', 'BBL', 'TSM', 'CHL', 'TM', 'PEP', 'UL', 'BCH', 'DIS', 'RDS-B', 'PTR', 'HON', 'ABBV', 'DHR', 'CAT', 'SPLP', 'AEP', 'BA', 'PCLN', 'NVS', 'WFC', 'AMGN', 'REX', 'LMT', 'SRE', 'UPS', 'BABA', 'BHP', 'ABB', 'NEE', 'BRK-A', 'GE', 'NGG', 'PM', 'GD', 'AAPL', 'HRG', 'HSBC', 'CVX', 'KO', 'BSAC', 'JNJ', 'UNH', 'TOT', 'MSFT', 'SNY', 'BUD', 'T', 'C', 'CODI', 'WMT', 'BAC', 'HD', 'JPM', 'MRK', 'MDT', 'CMCSA'}

In [33]:
# folder_path = 'trained_models/'
# if os.path.exists(folder_path):
#     for filename in os.listdir(folder_path):
#         file_path = os.path.join(folder_path, filename)
#         try:
#             if os.path.isfile(file_path) or os.path.islink(file_path):
#                 os.unlink(file_path)
#             elif os.path.isdir(file_path):
#                 shutil.rmtree(file_path)
#         except Exception as e:
#             print(f'Failed to delete {file_path}. Reason: {e}')
# else:
#     print(f"Folder not found: {folder_path}")

# print(f"Contents of {folder_path} after deletion attempt:")
# if os.path.exists(folder_path):
#     print(os.listdir(folder_path))
# else:
#     print("Folder does not exist.")