# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.optim.lr_scheduler import ReduceLROnPlateau

### Configurations

In [7]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 1100  # Number of days to use for initial training only
KELLY_FRACTION = 0.25
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [8]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.25   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [9]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [10]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [11]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # End current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [12]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [13]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [14]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [15]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [16]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [ ]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [18]:
def calculate_historical_payouts(df):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive next-day return when target==1
      - 'avg_loss_abs': mean absolute negative next-day return when target==0
    """
    out = {}
    for t, g in df.groupby('ticker'):
        # next_day return already implicit in your create_target_variable
        r = (g['next_day_close'] - g['close']) / g['close']
        wins = r[g['target'] == 1]
        losses = r[g['target'] == 0]
        avg_win = wins[wins > 0].mean() if (wins > 0).any() else np.nan
        avg_loss_abs = (-losses[losses < 0]).mean() if (losses < 0).any() else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [19]:
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.float32))
    def __len__(self): return self.X.shape[0]
    def __getitem__(self, idx): return self.X[idx], self.y[idx]

class LSTMClassifier(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, use_layernorm=False):
        super().__init__()
        self.lstm1 = nn.LSTM(
            input_size=n_features, hidden_size=hidden1,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )
        self.inter_drop = nn.Dropout(p=inter_dropout)  # proxy for recurrent_dropout
        self.lstm2 = nn.LSTM(
            input_size=hidden1, hidden_size=hidden2,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )

        # Normalization after temporal pooling
        self.use_layernorm = bool(use_layernorm)
        if self.use_layernorm:
            self.norm = nn.LayerNorm(normalized_shape=hidden2)
        else:
            self.norm = nn.BatchNorm1d(num_features=hidden2)

        # Head
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(p=dropout)
        self.fc_out = nn.Linear(fc, 1)  # logits

    def forward(self, x):
        # x: (B, T, F)
        out1, _ = self.lstm1(x)     # (B, T, hidden1)
        out1 = self.inter_drop(out1)
        out2, _ = self.lstm2(out1)  # (B, T, hidden2)

        last = out2[:, -1, :]       # (B, hidden2)
        if isinstance(self.norm, nn.BatchNorm1d):
            last = self.norm(last)  # BN expects (B, C)
        else:
            last = self.norm(last)  # LN expects (B, C)

        z = self.fc1(last)
        z = self.relu(z)
        z = self.drop(z)
        logits = self.fc_out(z).squeeze(-1)  # (B,)
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [ ]:
from matplotlib import ticker


def train_company_models(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         sequence_length: int = None,
                         H = 1):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    #sequence length & guards
    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)

    if len(company_data_df) < sequence_length + H + 10:
        print(f"Not enough data for {ticker}.")
        return False, sequence_length

    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        print(f"No contiguous periods found for {ticker}.")
        return False, sequence_length

    # build sequences
    targets = company_data_df[f'target_{H}d'].values
    X, y = create_contiguous_sequences(
        company_data_df[feature_cols].values,
        targets,
        contiguous_periods,
        sequence_length,
        H
    )
    print(f"Created {len(X)} sequences for {ticker}.")
    if len(X) < 2:
        return False, sequence_length

    # chronological split (no shuffle)
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    # scale features (fit on train, transform both)
    scaler = MinMaxScaler()
    F = X_train.shape[-1]
    X_train_scaled = scaler.fit_transform(X_train.reshape(-1, F)).reshape(X_train.shape)
    X_val_scaled   = scaler.transform(  X_val.reshape(-1, F)).reshape(X_val.shape)
    
    print(f"[TRAIN] {ticker}: scaler fitted on {X_train.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_train has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    sector_feature_indices = [feature_cols.index('sector_ret_1d'),
                          feature_cols.index('sector_ret_5d'),
                          feature_cols.index('sector_vol_20d')]

    print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")

    # Keras fit used the scaled data
    train_ds = SequenceDataset(X_train_scaled, y_train)
    val_ds   = SequenceDataset(X_val_scaled,   y_val)

    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_train.shape[-1]
    model = LSTMClassifier(n_features=n_features, dropout=0.3, inter_dropout=0.1).to(device)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)  # clipnorm via grad clipping below
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)
    early = EarlyStopper(patience=15, mode='min')

    for epoch in range(100):
        model.train()
        total_loss = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # clipnorm=1.0
            optimizer.step()
            total_loss += loss.item() * xb.size(0)

        train_loss = total_loss / len(train_loader.dataset)
        val_loss, _ = _evaluate(model, val_loader, device, loss_fn)

        scheduler.step(val_loss)  # ReduceLROnPlateau on val_loss

        # EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:  # stop after 'patience' non-improve epochs
            break

    # restore best weights
    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    # final validation pass for isotonic calibration (on scaled val data)
    _, validation_predictions = _evaluate(model, val_loader, device, loss_fn)

    # Keras code used 10% buffer (comment said 5%)
    pred_min, pred_max = validation_predictions.min(), validation_predictions.max()
    buffer = 0.05 * (pred_max - pred_min)
    y_min_dynamic = max(0.0, pred_min - buffer)
    y_max_dynamic = min(1.0, pred_max + buffer)

    calibrator = IsotonicRegression(y_min=y_min_dynamic, y_max=y_max_dynamic, out_of_bounds='clip')
    calibrator.fit(validation_predictions, y_val.astype(float))

    # inside train_company_models(..., H=H)
    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt"))
    joblib.dump(calibrator,      os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
    joblib.dump(scaler,          os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


    del model, scaler, calibrator, train_loader, val_loader, train_ds, val_ds
    del X_train, X_val, y_train, y_val, X_train_scaled, X_val_scaled
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [ ]:
def predict_next_horizon(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 H: int) -> dict | None:

    try:
        # load artifacts
        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt")
        calibrator = joblib.load(os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
        scaler     = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        sequence_length    = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


        if not os.path.isfile(state_dict_path):
            return None
        
        if hasattr(scaler, "n_features_in_") and scaler.n_features_in_ != len(feature_cols):
            return None

        # build model skeleton with correct input dim, then load weights
        n_features = len(feature_cols)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        model = LSTMClassifier(n_features=n_features).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    # find the last contiguous block and take the most recent sequence_length rows
    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        return None

    last_start, last_end = contiguous_periods[-1]
    period_data = company_data_df.iloc[last_start:last_end + 1]
    if len(period_data) < sequence_length:
        return None

    last_sequence = period_data.tail(sequence_length)

    # scale using the saved scaler (fit  train only)
    # ensure column order matches training
    try:
        scaled_features = scaler.transform(last_sequence[feature_cols])
    except Exception:
        return None

    # shape: (1, T, F) as float32 tensor
    x = torch.from_numpy(np.asarray([scaled_features], dtype=np.float32)).to(device)

    with torch.no_grad():
        logits = model(x)                  # shape (1,)
        prob = torch.sigmoid(logits).item()  # scalar in [0,1]

    # isotonic calibration (expects iterable)
    calibrated = float(calibrator.predict([prob])[0])

    print(f"Raw prediction for {ticker}: {prob}")
    print(f"Calibrated prediction for {ticker}: {calibrated}")

    return {
        'ticker': ticker,
        'raw_prediction': prob,
        'calibrated_prediction': calibrated
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [22]:
def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                            total_capital: float, sector_threshold: float,
                            kelly_fraction: float) -> pd.DataFrame:

    investment_decisions = []

    if daily_predictions_df.empty:
        return pd.DataFrame()

    for sector, group in daily_predictions_df.groupby('sector'):
        avg_sector_score = group['calibrated_prediction'].mean()
        if avg_sector_score < sector_threshold:
            continue

        best_stock_in_sector = group.loc[group['calibrated_prediction'].idxmax()]
        ticker = best_stock_in_sector['ticker']
        p = best_stock_in_sector['calibrated_prediction']
        b_info = payout_map.get(ticker, 0.0)
        b = (b_info['b'] if isinstance(b_info, dict) else float(b_info))
        if not np.isfinite(b) or b <= 0: 
            continue
        
        if not b_info or not np.isfinite(b_info.get('b', np.nan)): 
            continue
        b = max(b_info['b'], 1e-6)  # avoid div-by-zero
        kelly_percentage = p - (1 - p) / b

        if kelly_percentage > 0:
            investment_fraction = kelly_percentage * kelly_fraction
            investment_amount = total_capital * investment_fraction

            print(f"Investing {investment_amount} in {ticker}")

            investment_decisions.append({
                'ticker': ticker,
                'investment_fraction': investment_fraction,
                'investment_amount': investment_amount,
                'predicted_prob': p
            })

    return pd.DataFrame(investment_decisions)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [23]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    files = [
        f"{ticker}_lstm_H{H}.pt",
        f"{ticker}_calibrator_H{H}.pkl",
        f"{ticker}_scaler_H{H}.pkl",
        f"{ticker}_seq_length_H{H}.pkl",
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in files)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [ ]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # returns used for settlement only; not for training
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker','date'])[ret_col].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: RETRAIN_INTERVAL for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    open_positions = []
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                if pd.notna(rH):
                    pnl = pos['invest'] * rH
                    total_pnl_today += pnl
                    capital += pos['invest'] + pnl
            else:
                still_open.append(pos)
        open_positions = still_open

        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # historical slice strictly before current_date; recompute targets locally
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if i == 0:
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)

        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df, payout_map_day, capital, SECTOR_CONFIDENCE_THRESHOLD, KELLY_FRACTION
        )

        exit_idx = i + H
        exit_date = unique_dates[exit_idx] if exit_idx < len(unique_dates) else None

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)

            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue

                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))

                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})

        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,
            'capital_end': capital,
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [25]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [26]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_features.parquet')

In [27]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)

columns_to_check = ['EMA_12', 'EMA_26','EMA_50','MACD_12_26_9','MACDh_12_26_9','MACDs_12_26_9','RSI_14','ATRr_14',
                    'STOCHRSIk_14_14_3_3','STOCHRSId_14_14_3_3','ATRr_14','BB_upper','BB_middle','BB_lower','OBV',
                    
                    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
                    # 'sector_ret_60d', 
                    'sector_vol_20d', 'sector_dispersion_1d',
                    # 'sector_rel_strength',
                    
                    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
                    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,sector_close_mean,sector_volume_mean,sector_ret_1d,sector_ret_5d,sector_ret_20d,sector_range,sector_vol_20d,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-12-13,75.878571,76.805717,75.114288,75.669998,156314900.0,AAPL,0.0,0.0,Consumer Goods,...,62.547998,19829560.0,-0.006623,-0.002006,0.056416,0.698142,0.008085,1554.712849,0.002853,0.005430
1,2012-12-14,73.535713,74.018570,72.225716,72.827141,252394800.0,AAPL,0.0,0.0,Consumer Goods,...,62.332714,29416920.0,-0.003442,-0.007518,0.045959,0.581286,0.008149,1550.069802,-0.007258,0.013233
2,2012-12-17,72.704285,74.285713,71.604286,74.118568,189401800.0,AAPL,0.0,0.0,Consumer Goods,...,62.372857,24089840.0,0.000644,-0.005215,0.039231,0.782143,0.008074,1562.391712,-0.017465,0.008229
3,2012-12-18,75.000000,76.414284,74.321426,76.271431,156421300.0,AAPL,0.0,0.0,Consumer Goods,...,62.862143,22884370.0,0.007845,-0.001921,0.021354,1.029286,0.006088,1572.637095,-0.030002,0.014815
4,2012-12-19,75.924286,76.242859,75.071426,75.187141,112342300.0,AAPL,0.0,0.0,Consumer Goods,...,62.554713,17363510.0,-0.004891,-0.006516,0.012048,0.846144,0.006179,1566.784191,-0.032355,0.010914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102535,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,61.025001,2428780.0,-0.001767,0.021766,-0.016313,0.593999,0.006240,3101.328695,-0.007883,0.005228
102536,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,61.073999,2215970.0,0.000803,0.015446,-0.022362,0.690000,0.005981,3102.507723,-0.016661,0.002030
102537,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,60.999000,2459030.0,-0.001228,0.010118,-0.024219,0.485999,0.005966,3128.753695,-0.017629,0.004873
102538,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,61.345000,4155760.0,0.005672,0.012494,-0.011871,0.461999,0.005997,3141.201722,-0.008376,0.006185
102539,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,61.787000,2870660.0,0.007205,0.010698,-0.007804,0.636000,0.006197,3136.813139,-0.001766,0.007085

In [28]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength']
Total number of features: 28

In [29]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,sector_close_mean,sector_volume_mean,sector_ret_1d,sector_ret_5d,sector_ret_20d,sector_range,sector_vol_20d,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-12-13,75.878571,76.805717,75.114288,75.669998,156314900.0,AAPL,0.0,0.0,Consumer Goods,...,62.547998,19829560.0,-0.006623,-0.002006,0.056416,0.698142,0.008085,1554.712849,0.002853,0.005430
1,2012-12-14,73.535713,74.018570,72.225716,72.827141,252394800.0,AAPL,0.0,0.0,Consumer Goods,...,62.332714,29416920.0,-0.003442,-0.007518,0.045959,0.581286,0.008149,1550.069802,-0.007258,0.013233
2,2012-12-17,72.704285,74.285713,71.604286,74.118568,189401800.0,AAPL,0.0,0.0,Consumer Goods,...,62.372857,24089840.0,0.000644,-0.005215,0.039231,0.782143,0.008074,1562.391712,-0.017465,0.008229
3,2012-12-18,75.000000,76.414284,74.321426,76.271431,156421300.0,AAPL,0.0,0.0,Consumer Goods,...,62.862143,22884370.0,0.007845,-0.001921,0.021354,1.029286,0.006088,1572.637095,-0.030002,0.014815
4,2012-12-19,75.924286,76.242859,75.071426,75.187141,112342300.0,AAPL,0.0,0.0,Consumer Goods,...,62.554713,17363510.0,-0.004891,-0.006516,0.012048,0.846144,0.006179,1566.784191,-0.032355,0.010914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102535,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,61.025001,2428780.0,-0.001767,0.021766,-0.016313,0.593999,0.006240,3101.328695,-0.007883,0.005228
102536,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,61.073999,2215970.0,0.000803,0.015446,-0.022362,0.690000,0.005981,3102.507723,-0.016661,0.002030
102537,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,60.999000,2459030.0,-0.001228,0.010118,-0.024219,0.485999,0.005966,3128.753695,-0.017629,0.004873
102538,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,61.345000,4155760.0,0.005672,0.012494,-0.011871,0.461999,0.005997,3141.201722,-0.008376,0.006185
102539,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,61.787000,2870660.0,0.007205,0.010698,-0.007804,0.636000,0.006197,3136.813139,-0.001766,0.007085

In [30]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=1,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Creating target variable...
Target variable created.

Starting simulation with 1100 initial training days... (H=1)
Starting predictions from day 1100 (after 1100 training days)

Simulating Trading Days:   0%|          | 0/88 [00:00<?, ?it/s]

Created 1088 sequences for AAPL.
Raw prediction for AAPL: 0.5266602039337158
Calibrated prediction for AAPL: 0.522911787033081
Created 1088 sequences for ABB.
Raw prediction for ABB: 0.47540000081062317
Calibrated prediction for ABB: 0.49531206488609314
Created 1027 sequences for ABBV.
Raw prediction for ABBV: 0.5083483457565308
Calibrated prediction for ABBV: 0.5058823823928833
Created 1088 sequences for AEP.
Raw prediction for AEP: 0.5243576765060425
Calibrated prediction for AEP: 0.5691056847572327
Created 551 sequences for AGFS.
Raw prediction for AGFS: 0.4949460029602051
Calibrated prediction for AGFS: 0.4797990918159485
Created 1088 sequences for AMGN.
Raw prediction for AMGN: 0.48971715569496155
Calibrated prediction for AMGN: 0.5024599432945251
Created 1088 sequences for AMZN.
Raw prediction for AMZN: 0.5920154452323914
Calibrated prediction for AMZN: 0.6181818246841431
Created 1088 sequences for BA.
Raw prediction for BA: 0.32426944375038147
Calibrated prediction for BA: 0.4000000059604645
Created 595 sequences for BABA.
Raw prediction for BABA: 0.47136861085891724
Calibrated prediction for BABA: 0.47545257210731506
Created 1088 sequences for BAC.
Raw prediction for BAC: 0.33638572692871094
Calibrated prediction for BAC: 0.3218058943748474
Created 1088 sequences for BBL.
Raw prediction for BBL: 0.5082268118858337
Calibrated prediction for BBL: 0.5106155872344971
Created 1088 sequences for BCH.
Raw prediction for BCH: 0.4745490252971649
Calibrated prediction for BCH: 0.48674941062927246
Created 1088 sequences for BHP.
Raw prediction for BHP: 0.5151885747909546
Calibrated prediction for BHP: 0.5218049883842468
Created 1088 sequences for BP.
Raw prediction for BP: 0.5313031673431396
Calibrated prediction for BP: 0.5656565427780151
Created 1088 sequences for BRK-A.
Raw prediction for BRK-A: 0.48843175172805786
Calibrated prediction for BRK-A: 0.5485914349555969
Created 1088 sequences for BSAC.
Raw prediction for BSAC: 0.4823152422904968
Calibrated prediction for BSAC: 0.48594197630882263
Created 1088 sequences for BUD.
Raw prediction for BUD: 0.5757424831390381
Calibrated prediction for BUD: 0.5789473652839661
Created 1088 sequences for C.
Raw prediction for C: 0.5102789402008057
Calibrated prediction for C: 0.4392523467540741
Created 1088 sequences for CAT.
Raw prediction for CAT: 0.4666183888912201
Calibrated prediction for CAT: 0.453125
Created 1088 sequences for CELG.
Raw prediction for CELG: 0.5359172224998474
Calibrated prediction for CELG: 0.5396860837936401
Created 1088 sequences for CHL.
Raw prediction for CHL: 0.5091202855110168
Calibrated prediction for CHL: 0.5247524976730347
Created 1088 sequences for CHTR.
Raw prediction for CHTR: 0.5647327303886414
Calibrated prediction for CHTR: 0.557692289352417
Created 1088 sequences for CMCSA.
Raw prediction for CMCSA: 0.5317069888114929
Calibrated prediction for CMCSA: 0.5143383145332336
Created 1088 sequences for CODI.
Raw prediction for CODI: 0.4779188334941864
Calibrated prediction for CODI: 0.4771241843700409
Created 1088 sequences for CSCO.
Raw prediction for CSCO: 0.4243866503238678
Calibrated prediction for CSCO: 0.40063804388046265
Created 1088 sequences for CVX.
Raw prediction for CVX: 0.5036501288414001
Calibrated prediction for CVX: 0.5479452013969421
Created 1088 sequences for D.
Raw prediction for D: 0.5644724369049072
Calibrated prediction for D: 0.529411792755127
Created 1088 sequences for DHR.
Raw prediction for DHR: 0.5420063138008118
Calibrated prediction for DHR: 0.5817272067070007
Created 1088 sequences for DIS.
Raw prediction for DIS: 0.4941278100013733
Calibrated prediction for DIS: 0.4653465449810028
Created 1088 sequences for DUK.
Raw prediction for DUK: 0.5276180505752563
Calibrated prediction for DUK: 0.5880694389343262
Created 1088 sequences for EXC.
Raw prediction for EXC: 0.5058684349060059
Calibrated prediction for EXC: 0.53125
Created 1088 sequences for FB.
Raw prediction for FB: 0.536024272441864
Calibrated prediction for FB: 0.5397321581840515
Created 1088 sequences for GD.
Raw prediction for GD: 0.5257143378257751
Calibrated prediction for GD: 0.517510712146759
Created 1088 sequences for GE.
Raw prediction for GE: 0.4782906770706177
Calibrated prediction for GE: 0.4285714328289032
Created 147 sequences for GMRE.
Raw prediction for GMRE: 0.45169466733932495
Calibrated prediction for GMRE: 0.4525027275085449
Created 1088 sequences for GOOG.
Raw prediction for GOOG: 0.5334852933883667
Calibrated prediction for GOOG: 0.5066900849342346
Created 1088 sequences for HD.
Raw prediction for HD: 0.48461130261421204
Calibrated prediction for HD: 0.4769230782985687
Created 1088 sequences for HON.
Raw prediction for HON: 0.49487176537513733
Calibrated prediction for HON: 0.4502500295639038
Created 1088 sequences for HRG.
Raw prediction for HRG: 0.49949803948402405
Calibrated prediction for HRG: 0.5267831683158875
Created 1088 sequences for HSBC.
Raw prediction for HSBC: 0.4471070468425751
Calibrated prediction for HSBC: 0.45389091968536377
Created 1088 sequences for IEP.
Raw prediction for IEP: 0.5357972383499146
Calibrated prediction for IEP: 0.5736196637153625
Created 1088 sequences for INTC.
Raw prediction for INTC: 0.605785608291626
Calibrated prediction for INTC: 0.5933333039283752
Created 1088 sequences for JNJ.
Raw prediction for JNJ: 0.4717276394367218
Calibrated prediction for JNJ: 0.5476400852203369
Created 1088 sequences for JPM.
Raw prediction for JPM: 0.5021844506263733
Calibrated prediction for JPM: 0.5195775628089905
Created 1088 sequences for KO.
Raw prediction for KO: 0.46045783162117004
Calibrated prediction for KO: 0.45985400676727295
Created 1088 sequences for LMT.
Raw prediction for LMT: 0.681279718875885
Calibrated prediction for LMT: 0.6721311211585999
Created 1088 sequences for MA.
Raw prediction for MA: 0.5448340177536011
Calibrated prediction for MA: 0.5569620132446289
Created 1088 sequences for MCD.
Raw prediction for MCD: 0.5689010620117188
Calibrated prediction for MCD: 0.5977476239204407
Created 1088 sequences for MDT.
Raw prediction for MDT: 0.4538266360759735
Calibrated prediction for MDT: 0.4443422555923462
Created 1088 sequences for MMM.
Raw prediction for MMM: 0.514465868473053
Calibrated prediction for MMM: 0.5416079759597778
Created 1088 sequences for MO.
Raw prediction for MO: 0.4798860549926758
Calibrated prediction for MO: 0.4939759075641632
Created 1088 sequences for MRK.
Raw prediction for MRK: 0.5149760246276855
Calibrated prediction for MRK: 0.5142857432365417
Created 1088 sequences for MSFT.
Raw prediction for MSFT: 0.40957146883010864
Calibrated prediction for MSFT: 0.4094128906726837
Created 1088 sequences for NEE.
Raw prediction for NEE: 0.5171643495559692
Calibrated prediction for NEE: 0.5476190447807312
Created 1088 sequences for NGG.
Raw prediction for NGG: 0.4793553352355957
Calibrated prediction for NGG: 0.4375
Created 1088 sequences for NVS.
Raw prediction for NVS: 0.5178402662277222
Calibrated prediction for NVS: 0.5904762148857117
Created 1088 sequences for ORCL.
Raw prediction for ORCL: 0.4911305010318756
Calibrated prediction for ORCL: 0.474683552980423
Created 1088 sequences for PCG.
Raw prediction for PCG: 0.5077370405197144
Calibrated prediction for PCG: 0.49035224318504333
Created 1088 sequences for PCLN.
Raw prediction for PCLN: 0.4931561052799225
Calibrated prediction for PCLN: 0.5
Created 1088 sequences for PEP.
Raw prediction for PEP: 0.48201465606689453
Calibrated prediction for PEP: 0.4909090995788574
Created 1088 sequences for PFE.
Raw prediction for PFE: 0.49848008155822754
Calibrated prediction for PFE: 0.4881695508956909
Created 1088 sequences for PG.
Raw prediction for PG: 0.4323855936527252
Calibrated prediction for PG: 0.47422680258750916
Created 1088 sequences for PICO.
Raw prediction for PICO: 0.490111768245697
Calibrated prediction for PICO: 0.48641470074653625
Created 1088 sequences for PM.
Raw prediction for PM: 0.5250381231307983
Calibrated prediction for PM: 0.5296733975410461
Created 1088 sequences for PPL.
Raw prediction for PPL: 0.5270564556121826
Calibrated prediction for PPL: 0.5354330539703369
Created 1056 sequences for PTR.
Raw prediction for PTR: 0.4487462639808655
Calibrated prediction for PTR: 0.4124999940395355
Created 1088 sequences for RDS-B.
Raw prediction for RDS-B: 0.5443746447563171
Calibrated prediction for RDS-B: 0.5723684430122375
Created 1056 sequences for REX.
Raw prediction for REX: 0.5057504177093506
Calibrated prediction for REX: 0.5118483304977417
Created 1088 sequences for SLB.
Raw prediction for SLB: 0.5343953371047974
Calibrated prediction for SLB: 0.5435546636581421
Created 1056 sequences for SNP.
Raw prediction for SNP: 0.4602212905883789
Calibrated prediction for SNP: 0.42712241411209106
Created 1088 sequences for SNY.
Raw prediction for SNY: 0.4735651910305023
Calibrated prediction for SNY: 0.44897958636283875
Created 1088 sequences for SO.
Raw prediction for SO: 0.5399003624916077
Calibrated prediction for SO: 0.5335198044776917
Created 1088 sequences for SPLP.
Raw prediction for SPLP: 0.4489128291606903
Calibrated prediction for SPLP: 0.4380781352519989
Created 1088 sequences for SRE.
Raw prediction for SRE: 0.513299286365509
Calibrated prediction for SRE: 0.5061770677566528
Created 1088 sequences for T.
Raw prediction for T: 0.5024499893188477
Calibrated prediction for T: 0.4953271150588989
Created 1088 sequences for TM.
Raw prediction for TM: 0.4151346683502197
Calibrated prediction for TM: 0.40625
Created 1088 sequences for TOT.
Raw prediction for TOT: 0.456609845161438
Calibrated prediction for TOT: 0.5
Created 1088 sequences for TSM.
Raw prediction for TSM: 0.4967997074127197
Calibrated prediction for TSM: 0.4761904776096344
Created 1088 sequences for UL.
Raw prediction for UL: 0.41512900590896606
Calibrated prediction for UL: 0.4285714328289032
Created 1088 sequences for UN.
Raw prediction for UN: 0.3766970634460449
Calibrated prediction for UN: 0.39393940567970276
Created 1088 sequences for UNH.
Raw prediction for UNH: 0.43986809253692627
Calibrated prediction for UNH: 0.4444444477558136
Created 1088 sequences for UPS.
Raw prediction for UPS: 0.5475263595581055
Calibrated prediction for UPS: 0.5230769515037537
Created 1088 sequences for UTX.
Raw prediction for UTX: 0.4774647057056427
Calibrated prediction for UTX: 0.4891962707042694
Created 1088 sequences for V.
Raw prediction for V: 0.55312180519104
Calibrated prediction for V: 0.5523256063461304
Created 1088 sequences for VZ.
Raw prediction for VZ: 0.5211520195007324
Calibrated prediction for VZ: 0.5337837934494019
Created 1088 sequences for WFC.
Raw prediction for WFC: 0.5017716288566589
Calibrated prediction for WFC: 0.4878625273704529
Created 1088 sequences for WMT.
Raw prediction for WMT: 0.5290535092353821
Calibrated prediction for WMT: 0.5
Created 1088 sequences for XOM.

Simulating Trading Days:   1%|          | 1/88 [06:22<9:14:32, 382.44s/it]

Raw prediction for XOM: 0.47290363907814026
Calibrated prediction for XOM: 0.44186046719551086
Investing 2328.37947930431 in RDS-B
Investing 4099.816621545168 in IEP
Investing 4477.021568757337 in BUD
Investing 2921.352844870935 in MA
Investing 4578.858456817747 in NVS
Investing 9014.366625815126 in LMT
Investing 6592.037757989861 in AMZN
Investing 4461.05725079803 in INTC
Investing 3482.6657520057342 in DUK
Raw prediction for AAPL: 0.5271258354187012
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4738101661205292
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5063982009887695
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5194732546806335
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.4932798743247986
Calibrated prediction for AGFS: 0.4797990918159485
Raw prediction for AMGN: 0.48875075578689575
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5906413197517395
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3236960470676422
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.471557080745697
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3350396156311035
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5082494616508484
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47596830129623413
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5150140523910522
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5374729633331299
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4902900755405426
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4821934700012207
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5712028741836548
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.5103706121444702
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.46276986598968506
Calibrated prediction for CAT: 0.453125
Raw prediction for CELG: 0.5350074768066406
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5035001039505005
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5617152452468872
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5288803577423096
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4786304831504822
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4104456901550293
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.5067635178565979
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.567597508430481
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5447641015052795
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4952526390552521
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.5163675546646118
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.5078108906745911
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5359112620353699
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.519993007183075
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.468335896730423
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45181652903556824
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.533513069152832
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.4855011999607086
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.48980826139450073
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4994675815105438
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4476671814918518
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5395426154136658
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6058192849159241
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47289782762527466
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5018624663352966
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4616067707538605
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6721871495246887
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5478222370147705
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.5779315233230591
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.44941937923431396
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5177504420280457
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4801441431045532
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5138888955116272
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.40243276953697205
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5157808661460876
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.481839656829834
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5222938060760498
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4870867431163788
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5097173452377319
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49208924174308777
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48284509778022766
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4974300265312195
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.43401554226875305
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.48917582631111145
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5246050953865051
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5277574062347412
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4469374418258667
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5375580191612244
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5051098465919495
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.554291844367981
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.46320489048957825
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.46669337153434753
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5396255254745483
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45014795660972595
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5141510367393494
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.5023265480995178
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4089336395263672
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.45368871092796326
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.48395562171936035
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.41505858302116394
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.37528905272483826
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.441016286611557
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5455777645111084
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.47650882601737976
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5534513592720032
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5232827663421631
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5018188953399658
Calibrated prediction for WFC: 0.4878625273704529

Simulating Trading Days:   2%|▏         | 2/88 [06:24<3:47:10, 158.49s/it]

Raw prediction for WMT: 0.52797931432724
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4746391475200653
Calibrated prediction for XOM: 0.44186046719551086
Investing 2330.728944463245 in RDS-B
Investing 4103.953565886055 in IEP
Investing 4481.5391339931975 in BUD
Investing 2924.300653330418 in MA
Investing 4583.478781171062 in NVS
Investing 9023.46262606142 in LMT
Investing 6598.689492888079 in AMZN
Investing 4465.558707143924 in INTC
Investing 2835.256856812337 in AEP
Raw prediction for AAPL: 0.5273891687393188
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4724864661693573
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5047879219055176
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5245671272277832
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.4917873740196228
Calibrated prediction for AGFS: 0.4797990918159485
Raw prediction for AMGN: 0.4880911707878113
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5924673676490784
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.32679858803749084
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4716992974281311
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.33258676528930664
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5080191493034363
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4768596589565277
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5148027539253235
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5393756031990051
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4890109896659851
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4822736978530884
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5682823061943054
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.5029494166374207
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.460422158241272
Calibrated prediction for CAT: 0.453125
Raw prediction for CELG: 0.534433901309967
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.49921244382858276
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5632309317588806
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.528459370136261
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.48018041253089905
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.3935720920562744
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.5045140385627747
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5717421174049377
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5460202693939209
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4951350688934326
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.510334849357605
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.5101187825202942
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5357363820075989
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5135279893875122
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.46063128113746643
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4519728124141693
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5365878939628601
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.48724880814552307
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.4884141683578491
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4992981255054474
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4482775032520294
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5478842854499817
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5978221297264099
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47374337911605835
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5013585686683655
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.462808221578598
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6618267893791199
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5513083934783936
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.587424635887146
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.44724559783935547
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5213290452957153
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4820142686367035
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5143161416053772
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.40233907103538513
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5149763822555542
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.48421183228492737
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5234881639480591
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.48403728008270264
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5100810527801514
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4910461902618408
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4841180145740509
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4963860809803009
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4358769655227661
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.4886505901813507
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5241048336029053
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5293875932693481
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4441143572330475
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5328319668769836
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5045471787452698
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5725651383399963
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.46746453642845154
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4595903158187866
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5395721197128296
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4508123993873596
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5170688033103943
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.5023138523101807
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4089723229408264
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.45113635063171387
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4690968096256256
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.41400012373924255
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3775458335876465
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.44284120202064514
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5454965233802795
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.47584161162376404
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5533673763275146
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5253522396087646
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.501553475856781
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5263938307762146
Calibrated prediction for WMT: 0.5

Simulating Trading Days:   3%|▎         | 3/88 [06:25<2:03:03, 86.87s/it]

Raw prediction for XOM: 0.4726025462150574
Calibrated prediction for XOM: 0.44186046719551086
Investing 2335.3918352073715 in RDS-B
Investing 4112.163995992976 in IEP
Investing 4490.504967363474 in BUD
Investing 2930.151052400567 in MA
Investing 4592.648556504823 in NVS
Investing 9041.515098640433 in LMT
Investing 6611.8909285302825 in AMZN
Investing 4474.492569836263 in INTC
Investing 2840.9291135482636 in AEP
Raw prediction for AAPL: 0.5277222394943237
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47143039107322693
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5037546753883362
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.52837073802948
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.491916686296463
Calibrated prediction for AGFS: 0.4797990918159485
Raw prediction for AMGN: 0.48761463165283203
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5959613919258118
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.32922983169555664
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4718623757362366
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3304424583911896
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5079262852668762
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47696414589881897
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5148773789405823
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5410524010658264
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4868257939815521
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.48231589794158936
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.566335141658783
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.4945628046989441
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.45836183428764343
Calibrated prediction for CAT: 0.453125
Raw prediction for CELG: 0.5340145826339722
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4961523115634918
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.573926568031311
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5288549661636353
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.48090970516204834
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.3798098564147949
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.501594066619873
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5770719647407532
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5460348725318909
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4932025074958801
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5128645896911621
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.5121901035308838
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5355629920959473
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.508491039276123
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45334592461586
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4519501030445099
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.540896475315094
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.4886532127857208
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.48578086495399475
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49981629848480225
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4488093852996826
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5503686666488647
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5863202214241028
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4741547405719757
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5006351470947266
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46287837624549866
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6546922326087952
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5541834831237793
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.5960695147514343
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4478398263454437
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5236228704452515
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4835900366306305
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5135422945022583
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.40928494930267334
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5145630240440369
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4826379716396332
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5244914889335632
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4815858006477356
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5109884142875671
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4900767207145691
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4852178990840912
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49566707015037537
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.43813297152519226
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.4885910451412201
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5232675075531006
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5322282314300537
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.44087278842926025
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5317043662071228
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5042421221733093
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5883758664131165
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.47076722979545593
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4522208571434021
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5396140217781067
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4516025185585022
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5213673710823059
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.5022459030151367
Calibrated prediction for T: 0.4953271150588989

Simulating Trading Days:   5%|▍         | 4/88 [06:27<1:14:24, 53.14s/it]

Raw prediction for TM: 0.4089801013469696
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.44928666949272156
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.45524513721466064
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.41383323073387146
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3790425658226013
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.443718284368515
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5485827922821045
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.4755135178565979
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5527609586715698
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5266584753990173
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5010857582092285
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5223132371902466
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.473960280418396
Calibrated prediction for XOM: 0.44186046719551086
Investing 2334.2979426574707 in RDS-B
Investing 4110.2378671561055 in IEP
Investing 4488.401624423314 in BUD
Investing 2928.778575903055 in MA
Investing 4590.497369725571 in NVS
Investing 9037.280072270505 in LMT
Investing 6608.793932934752 in AMZN
Investing 4472.396727068921 in INTC
Investing 2839.598428416434 in AEP
Raw prediction for AAPL: 0.5279320478439331
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4707406759262085
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5028309226036072
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5351659059524536
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.49189770221710205
Calibrated prediction for AGFS: 0.4797990918159485
Raw prediction for AMGN: 0.4873013496398926
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6096717715263367
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3330773115158081
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4718693196773529
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3291991353034973
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5079881548881531
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47680187225341797
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.514973521232605
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.541257917881012
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4859892427921295
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.48222652077674866
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5656856894493103
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.48807957768440247
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.45665162801742554
Calibrated prediction for CAT: 0.453125
Raw prediction for CELG: 0.5338768362998962
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4943939745426178
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5941571593284607
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.5310000777244568
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4825825095176697
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.3671490252017975
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.49771180748939514
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5853930711746216
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5467858910560608
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48626741766929626
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5203860998153687
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.5148106217384338
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5354697108268738
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5050557851791382
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.445184588432312
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4520181119441986
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5454813241958618
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.4899275302886963
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.48423683643341064
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5009467601776123
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44921237230300903
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.550593912601471
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5746267437934875
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47471150755882263
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5001736879348755
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46238085627555847
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6503744721412659
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5565647482872009
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.601681113243103
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.45287880301475525
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5250295996665955
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.48529088497161865
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.510780930519104
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.4179091155529022
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.51517653465271
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4797040522098541
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.525378942489624
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4790734052658081
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5116892457008362
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4894856810569763
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48632317781448364
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49548572301864624
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4405178129673004
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.4884050488471985
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.522311806678772
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.537153959274292
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.43830010294914246
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5273199081420898
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.504044771194458
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6006873250007629
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.47068729996681213
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4515397548675537
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.53996741771698
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4521369934082031
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5267196893692017
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.5020522475242615
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.40954992175102234
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4484345018863678
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.44256290793418884
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.413929283618927
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.37907469272613525
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4476321041584015
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.552188515663147
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.47508704662323
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5520693063735962
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5243584513664246
Calibrated prediction for VZ: 0.5337837934494019

Simulating Trading Days:   6%|▌         | 5/88 [06:28<47:47, 34.54s/it]

Raw prediction for WFC: 0.5006324648857117
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5178070664405823
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4787478446960449
Calibrated prediction for XOM: 0.44186046719551086
Investing 2340.333214944106 in RDS-B
Investing 4120.864790239834 in IEP
Investing 4500.006280984136 in BUD
Investing 4204.466022849562 in MA
Investing 4602.365992428394 in NVS
Investing 9060.645746793032 in LMT
Investing 6625.8808138091445 in AMZN
Investing 4483.960003345037 in INTC
Investing 3500.5455117662386 in DUK
Raw prediction for AAPL: 0.527899980545044
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4702962338924408
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.502223551273346
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5324138402938843
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.49164441227912903
Calibrated prediction for AGFS: 0.4797990918159485
Raw prediction for AMGN: 0.48682865500450134
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6166212558746338
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.33711808919906616
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4717944860458374
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3307902216911316
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5081159472465515
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47672829031944275
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5151512622833252
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5370362401008606
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4862574338912964
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.48214390873908997
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5651501417160034
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.4847787618637085
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.45448243618011475
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5338277816772461
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.49261853098869324
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.614263117313385
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5346707701683044
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4850679934024811
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.3583374619483948
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.49222907423973083
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5885046124458313
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5475807785987854
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.47636041045188904
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.526788592338562
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.5166814923286438
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5355587601661682
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5029945373535156
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.437256783246994
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45220324397087097
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.550212562084198
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.49095970392227173
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.48352938890457153
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.502345860004425
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44939103722572327
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5516685247421265
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5654942393302917
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4750334918498993
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5002518892288208
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4614548087120056
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6623231768608093
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5595053434371948
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.604007363319397
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4639560878276825
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5257374048233032
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.49030351638793945
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5082384347915649
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.43002694845199585
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5156722068786621
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.474590927362442
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.525405764579773
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.47754332423210144
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5116790533065796
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4889678359031677
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48706966638565063
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49585938453674316
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4400057792663574
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.48822614550590515
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5212863087654114
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5400914549827576
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.43882542848587036
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5205428004264832
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5039836168289185
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6092615127563477
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4778287708759308
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4540351927280426
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5403340458869934
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45334193110466003
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5308120250701904
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.5017738938331604
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.41168007254600525
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4477443993091583
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4347686469554901
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.4131343960762024
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.37988293170928955
Calibrated prediction for UN: 0.39393940567970276

Simulating Trading Days:   7%|▋         | 6/88 [06:30<31:52, 23.33s/it]

Raw prediction for UNH: 0.45271167159080505
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5541111826896667
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.47480887174606323
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5523640513420105
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5215171575546265
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5002880096435547
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.515606701374054
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.48783496022224426
Calibrated prediction for XOM: 0.44186046719551086
Investing 2341.9000258651763 in RDS-B
Investing 4123.623634970308 in IEP
Investing 4503.018954111581 in BUD
Investing 4207.280837099005 in MA
Investing 4605.447193538412 in NVS
Investing 9066.71168587272 in LMT
Investing 8831.16190906696 in CHTR
Investing 4486.961933778713 in INTC
Investing 3502.8890639162123 in DUK
Raw prediction for AAPL: 0.5280143022537231
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.46993106603622437
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5017610788345337
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5183749198913574
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.4916013181209564
Calibrated prediction for AGFS: 0.4797990918159485
Raw prediction for AMGN: 0.48645472526550293
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6234707236289978
Calibrated prediction for AMZN: 0.7142857313156128
Raw prediction for BA: 0.33914846181869507
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4715094566345215
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3317125737667084
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.50812166929245
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47626686096191406
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5154615640640259
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.520341157913208
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.487450510263443
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4818718433380127
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5586234927177429
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4821430742740631
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.45225030183792114
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5339336395263672
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.49361151456832886
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6254682540893555
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5401608347892761
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4875497817993164
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.3529144525527954
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.4909277558326721
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5874623656272888
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5470975637435913
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4675896465778351
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5287740230560303
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.5177268981933594
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5358284711837769
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5029627084732056
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.43092507123947144
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45239341259002686
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5578458309173584
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.4914121627807617
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.4822215735912323
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5034040808677673
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4496378004550934
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5524775385856628
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5594584345817566
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47641128301620483
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5001074075698853
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45790544152259827
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6703587770462036
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5632316470146179
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.6058928370475769
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4746781289577484
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5262693166732788
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.49431705474853516
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5055119395256042
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4423503279685974
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5162464380264282
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4644373953342438
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5249029397964478
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.476981520652771
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5120022296905518
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4884357154369354
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48703494668006897
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49665603041648865
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4394906759262085
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.4884639382362366
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5199980139732361
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5400989651679993
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.44023793935775757
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5092710852622986
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.503937304019928
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6135881543159485
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4835290312767029
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4592786431312561
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5406414270401001
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45365238189697266
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.533719539642334
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.5013230443000793
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.40678006410598755
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4464591145515442
Calibrated prediction for TOT: 0.5

Simulating Trading Days:   8%|▊         | 7/88 [06:31<21:52, 16.20s/it]

Raw prediction for TSM: 0.42778998613357544
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.4137427508831024
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.37972933053970337
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.46134188771247864
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5558006167411804
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.4744613766670227
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5528882741928101
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5148898363113403
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4999465346336365
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5140157341957092
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4936830401420593
Calibrated prediction for XOM: 0.5454545617103577
Investing 2334.0145775923006 in RDS-B
Investing 4109.738917214965 in IEP
Investing 1585.6943987392767 in PM
Investing 4193.114435867531 in MA
Investing 4589.9401201292085 in NVS
Investing 9036.18301888677 in LMT
Investing 11252.5022983998 in AMZN
Investing 4471.853813944219 in INTC
Investing 3491.0944312615034 in DUK
Raw prediction for AAPL: 0.5279436111450195
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4696964621543884
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.501724898815155
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5091840028762817
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.49221697449684143
Calibrated prediction for AGFS: 0.4797990918159485
Raw prediction for AMGN: 0.48618146777153015
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6265486478805542
Calibrated prediction for AMZN: 0.7142857313156128
Raw prediction for BA: 0.3382658064365387
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4710937440395355
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.33400997519493103
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5080175995826721
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47631704807281494
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5155432224273682
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.4932738244533539
Calibrated prediction for BP: 0.5161863565444946
Raw prediction for BRK-A: 0.4868302047252655
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4817315936088562
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5517723560333252
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4804103374481201
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4510761797428131
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5339502096176147
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.49158942699432373
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6355447173118591
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5447853207588196
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4906284213066101
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.347854882478714
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.488996297121048
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5838925838470459
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5464557409286499
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.46177732944488525
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5231831073760986
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.5185285210609436
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5363273024559021
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.50046706199646
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.43037787079811096
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4524994194507599
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5653184652328491
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.49144354462623596
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.48167094588279724
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5044010877609253
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4499534070491791
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5534111857414246
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5510890483856201
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47987210750579834
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5000833868980408
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45432427525520325
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6731327176094055
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5714097619056702
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.6073793768882751
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4865927994251251
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5266587734222412
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4980440139770508
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.50326007604599
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.453034907579422
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5157824158668518
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.45107266306877136
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5246589779853821
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4753665328025818
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5119621753692627
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4880286753177643
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4865918457508087
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49757376313209534
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4379117786884308
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.48882657289505005
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5188952088356018
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.535561740398407
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.44160544872283936
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.49402710795402527
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5038381218910217
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6117619276046753
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.48978400230407715
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4653257131576538
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5408025979995728
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45368263125419617
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5355966091156006
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.5008100867271423
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.40129730105400085
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.44397756457328796
Calibrated prediction for TOT: 0.4750725328922272
Raw prediction for TSM: 0.42034026980400085
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.414347767829895
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.37871307134628296
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.47069427371025085
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5558990836143494
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.47410058975219727
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5536857843399048
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.506214439868927
Calibrated prediction for VZ: 0.5337837934494019

Simulating Trading Days:   9%|▉         | 8/88 [06:33<15:24, 11.56s/it]

Raw prediction for WFC: 0.49983376264572144
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5120678544044495
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4942154884338379
Calibrated prediction for XOM: 0.5454545617103577
Investing 2336.317801134291 in RDS-B
Investing 4113.794439196892 in IEP
Investing 1587.2591741715478 in PM
Investing 4197.252233452717 in MA
Investing 4594.469508352616 in NVS
Investing 9045.099993809996 in LMT
Investing 11263.606354239379 in AMZN
Investing 4476.266673692182 in INTC
Investing 3494.5394701051287 in DUK
Raw prediction for AAPL: 0.5279683470726013
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4697200357913971
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5022575855255127
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5149387121200562
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.4955301582813263
Calibrated prediction for AGFS: 0.4797990918159485
Raw prediction for AMGN: 0.48606473207473755
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.624823808670044
Calibrated prediction for AMZN: 0.7142857313156128
Raw prediction for BA: 0.33314844965934753
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.47074487805366516
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.33435556292533875
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5081451535224915
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4764288067817688
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5155354738235474
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.4721057415008545
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.48171886801719666
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48163798451423645
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5431571006774902
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.47641491889953613
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44996917247772217
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5346234440803528
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.48822638392448425
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6401997804641724
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5473077893257141
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.49224886298179626
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.3449152112007141
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.48557671904563904
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5781527757644653
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5456545352935791
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.45927882194519043
Calibrated prediction for DIS: 0.4569750428199768
Raw prediction for DUK: 0.5164822936058044
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.519351065158844
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5370063185691833
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.4968497157096863
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.43174514174461365
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45248380303382874
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5750274062156677
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.48992297053337097
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.4800461232662201
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5052498579025269
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.45032185316085815
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5444667339324951
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5400471091270447
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48224398493766785
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49957358837127686
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4514337480068207
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6751322746276855
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5811436176300049
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6083963513374329
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.49690622091293335
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5266103148460388
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.49886462092399597
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5041599869728088
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4604204297065735
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5162746906280518
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4429163932800293
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5264528393745422
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4745887219905853
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5117899179458618
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4877035915851593
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48605671525001526
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4984368681907654
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.43721482157707214
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.48929792642593384
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5180001854896545
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5311394929885864
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.44319701194763184
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4750795066356659
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5037437677383423
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6024622321128845
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4913260340690613
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.471994012594223
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5407368540763855
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4531124234199524
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.537093460559845
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.500372588634491
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3982427716255188
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.44288375973701477
Calibrated prediction for TOT: 0.4393501281738281
Raw prediction for TSM: 0.4125397205352783
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.4145010709762573
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.374191552400589
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.47979816794395447
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5567077994346619
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.47381776571273804
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5549378991127014
Calibrated prediction for V: 0.5523256063461304

Simulating Trading Days:  10%|█         | 9/88 [06:35<11:15,  8.55s/it]

Raw prediction for VZ: 0.4963633418083191
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49957501888275146
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5107519626617432
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4936966896057129
Calibrated prediction for XOM: 0.5454545617103577
Investing 2402.4923503649275 in SNP
Investing 4108.095411512417 in IEP
Investing 1585.060271404348 in PM
Investing 5595.024733804521 in MA
Investing 4588.104579499075 in NVS
Investing 9032.569402883426 in LMT
Investing 11248.002364932521 in AMZN
Investing 4470.065496634476 in INTC
Investing 2838.118291773399 in AEP
Raw prediction for AAPL: 0.5278289318084717
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.46978896856307983
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5032846927642822
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5326403379440308
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.4992421567440033
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4868227243423462
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6283448338508606
Calibrated prediction for AMZN: 0.7142857313156128
Raw prediction for BA: 0.3348204791545868
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4705600440502167
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.33560362458229065
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5080963373184204
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47644463181495667
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5155863165855408
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.45353832840919495
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.4723452031612396
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4816821217536926
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5365433096885681
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.47129595279693604
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4503404200077057
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5353572368621826
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4844443202018738
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6431008577346802
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.548342227935791
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4935332238674164
Calibrated prediction for CODI: 0.5
Raw prediction for CSCO: 0.3459470272064209
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.4828110337257385
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5676111578941345
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5450841188430786
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.46328258514404297
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5123511552810669
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.5197422504425049
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5377692580223083
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.49082502722740173
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4376888573169708
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4524587094783783
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5836412310600281
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.4857567548751831
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.4803439676761627
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5059586763381958
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4507070481777191
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5391359329223633
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5274961590766907
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4834705591201782
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4990306794643402
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4504099488258362
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6801220774650574
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.590031087398529
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6087508201599121
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5054860711097717
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5260867476463318
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.49892276525497437
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5045028328895569
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.46585965156555176
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5181747078895569
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4333246946334839
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5274388790130615
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.47425204515457153
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5123522877693176
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4884764552116394
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4856402575969696
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49926602840423584
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4367692768573761
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.4895302653312683
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5174544453620911
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5284436345100403
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4450792968273163
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.45667141675949097
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5035271048545837
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5861693620681763
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4905208945274353
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4791502356529236
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5405365824699402
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45302149653434753
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5379178524017334
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49980783462524414
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4049831032752991
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4432006776332855
Calibrated prediction for TOT: 0.4393501281738281
Raw prediction for TSM: 0.4080483019351959
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.41471797227859497
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3673713803291321
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.48968932032585144
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5620875954627991
Calibrated prediction for UPS: 0.5820285081863403

Simulating Trading Days:  11%|█▏        | 10/88 [06:37<08:24,  6.47s/it]

Raw prediction for UTX: 0.47389698028564453
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5565335750579834
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.48172396421432495
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49919721484184265
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5088824033737183
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.49330756068229675
Calibrated prediction for XOM: 0.5454545617103577
Investing 2401.3636330837817 in SNP
Investing 4106.1653831887625 in IEP
Investing 1584.3155926877978 in PM
Investing 5592.396129761506 in MA
Investing 4585.9490375986825 in NVS
Investing 9028.325802616964 in LMT
Investing 11242.717929939112 in AMZN
Investing 4467.965410791066 in INTC
Investing 2836.784912642609 in AEP
Raw prediction for AAPL: 0.5277281403541565
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.46999478340148926
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5048685073852539
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5516847372055054
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5034399628639221
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48798424005508423
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6243435144424438
Calibrated prediction for AMZN: 0.7142857313156128
Raw prediction for BA: 0.34145277738571167
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4706137478351593
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3372947573661804
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5080527663230896
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4761408865451813
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5146769285202026
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.43422290682792664
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.45929545164108276
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48183539509773254
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5310139656066895
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4658312499523163
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44970762729644775
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5356220006942749
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4801514148712158
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6447382569313049
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5486749410629272
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4947790205478668
Calibrated prediction for CODI: 0.5173588395118713
Raw prediction for CSCO: 0.35246726870536804
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.4806976318359375
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5556314587593079
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5434591770172119
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4685395658016205
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5111644268035889
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.5210503935813904
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.538613498210907
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.48805198073387146
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.43949827551841736
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4524093270301819
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5927747488021851
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4829622507095337
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.4810468256473541
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5063679814338684
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4509948194026947
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5318542122840881
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5170205235481262
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.48350563645362854
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4985315501689911
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4501672685146332
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6769793629646301
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5977851748466492
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6085717678070068
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5114952921867371
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5242583155632019
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4973943829536438
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5026429295539856
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4733942747116089
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5208241939544678
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.43323588371276855
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5283867716789246
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.47574305534362793
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5134935975074768
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48911917209625244
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4852559566497803
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.5000349879264832
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.43689602613449097
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.48957377672195435
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5171098709106445
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.528994083404541
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.445412278175354
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.44490382075309753
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5033438801765442
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5669009685516357
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49067848920822144
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4846934974193573
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5404256582260132
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4538608193397522
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5391964912414551
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49925497174263
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4200766384601593
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4431725740432739
Calibrated prediction for TOT: 0.4393501281738281
Raw prediction for TSM: 0.4039972126483917
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.41503557562828064
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3588870167732239
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.5020390152931213
Calibrated prediction for UNH: 0.5
Raw prediction for UPS: 0.5677801966667175
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.4737471044063568
Calibrated prediction for UTX: 0.4891962707042694

Simulating Trading Days:  12%|█▎        | 11/88 [06:38<06:24,  5.00s/it]

Raw prediction for V: 0.558303952217102
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.46405062079429626
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.49894532561302185
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5082667469978333
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.49300915002822876
Calibrated prediction for XOM: 0.5454545617103577
Investing 2404.8497333528667 in SNP
Investing 4112.126373040541 in IEP
Investing 1586.6155704745406 in PM
Investing 5600.514705967208 in MA
Investing 4592.60653750987 in NVS
Investing 9041.43237613889 in LMT
Investing 11259.039174027612 in AMZN
Investing 4955.919169175158 in GOOG
Investing 2840.903121359962 in AEP
Raw prediction for AAPL: 0.5275201797485352
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4703727960586548
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5065183043479919
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5533877611160278
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5067237019538879
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48963186144828796
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6184049844741821
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3537766635417938
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4707791209220886
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3391433358192444
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5079734921455383
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47503677010536194
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5126048922538757
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.4183610677719116
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.444654643535614
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.48183807730674744
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5273714065551758
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.46034756302833557
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44913449883461
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5356475710868835
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.47271716594696045
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6477578282356262
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5493956804275513
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.49491584300994873
Calibrated prediction for CODI: 0.5206822156906128
Raw prediction for CSCO: 0.3672560155391693
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.4787589907646179
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5436751246452332
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5443152785301208
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4695746898651123
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5063296556472778
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.5206348299980164
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5393533706665039
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.48858508467674255
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.44188830256462097
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45245230197906494
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6025733351707458
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4831179976463318
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.48771780729293823
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.506310760974884
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.45119139552116394
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5199822187423706
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5085711479187012
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.48361149430274963
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49798718094825745
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45009979605674744
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6778124570846558
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5977964401245117
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6066445112228394
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5175434350967407
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5230031609535217
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4963928461074829
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5024838447570801
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4841812551021576
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5225762724876404
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.43233785033226013
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5315294861793518
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.47759878635406494
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5135664939880371
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48967260122299194
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48490458726882935
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.5006516575813293
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.43654507398605347
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.489742249250412
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5169143676757812
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.529679536819458
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4442654550075531
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.43418267369270325
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5034483075141907
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5492701530456543
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49100175499916077
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48970457911491394
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5403448343276978
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.455108642578125
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.539925754070282
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49869686365127563
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.43866658210754395
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.44420260190963745
Calibrated prediction for TOT: 0.4913848042488098
Raw prediction for TSM: 0.402055025100708
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.41461560130119324
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3522469103336334
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.514904797077179
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5746135711669922
Calibrated prediction for UPS: 0.5820285081863403

Simulating Trading Days:  14%|█▎        | 12/88 [06:40<05:03,  4.00s/it]

Raw prediction for UTX: 0.47258687019348145
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5602428913116455
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.45345866680145264
Calibrated prediction for VZ: 0.4166666567325592
Raw prediction for WFC: 0.49897220730781555
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5069561004638672
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4903338551521301
Calibrated prediction for XOM: 0.5454545617103577
Investing 2406.1346387499993 in SNP
Investing 4114.323472217729 in IEP
Investing 1587.4632953370979 in PM
Investing 5603.507047431465 in MA
Investing 4595.060356077039 in NVS
Investing 9046.263191593507 in LMT
Investing 8811.244659017226 in CHTR
Investing 4958.567104802865 in GOOG
Investing 2842.4210090278443 in AEP
Raw prediction for AAPL: 0.5272101759910583
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4708530008792877
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5079271793365479
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5426424741744995
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5089545249938965
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4914531409740448
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6127009987831116
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3642643690109253
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4709802269935608
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3404189646244049
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5080770254135132
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4732922911643982
Calibrated prediction for BCH: 0.4668968915939331
Raw prediction for BHP: 0.5103152394294739
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4145708382129669
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.43524810671806335
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4815811514854431
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5250243544578552
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4563586711883545
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44867438077926636
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.535506546497345
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4690713882446289
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6507230401039124
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5499683618545532
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4945935904979706
Calibrated prediction for CODI: 0.512854814529419
Raw prediction for CSCO: 0.38662952184677124
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.47857844829559326
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.534414529800415
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5434237718582153
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4727570712566376
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.49476557970046997
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.5179954767227173
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5400079488754272
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.4931185245513916
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4434356093406677
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45259860157966614
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6112856268882751
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4823162853717804
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.4954042136669159
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5059545040130615
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.45129531621932983
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5148273706436157
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5019218921661377
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.4857654571533203
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4979115128517151
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4500574469566345
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6764038801193237
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5945402383804321
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6050980687141418
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5192757844924927
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5243315696716309
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.49510982632637024
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5028303265571594
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4940294921398163
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.522787868976593
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.42585909366607666
Calibrated prediction for NGG: 0.4015027582645416
Raw prediction for NVS: 0.5333396196365356
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.481224000453949
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5133933424949646
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4902478754520416
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4841368496417999
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.5010406970977783
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4354449212551117
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.4895854592323303
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5166865587234497
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5294418931007385
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.44292008876800537
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4286789894104004
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.503817617893219
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5331039428710938
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4877622723579407
Calibrated prediction for SNP: 0.4545454680919647
Raw prediction for SNY: 0.4935857951641083
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5403538346290588
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4542452096939087
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5400691628456116
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49823546409606934
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4532569646835327
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4455370008945465
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.40939459204673767
Calibrated prediction for TSM: 0.4206155836582184

Simulating Trading Days:  15%|█▍        | 13/88 [06:42<04:08,  3.32s/it]

Raw prediction for UL: 0.414204478263855
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3459777235984802
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.5240764617919922
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5815249085426331
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.47111067175865173
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5606710910797119
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.45482131838798523
Calibrated prediction for VZ: 0.4166666567325592
Raw prediction for WFC: 0.499166339635849
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5039690732955933
Calibrated prediction for WMT: 0.4853345453739166
Raw prediction for XOM: 0.48960360884666443
Calibrated prediction for XOM: 0.5454545617103577
Investing 2675.144317265295 in XOM
Investing 2917.7691413580096 in AGFS
Investing 1586.4443690221542 in PM
Investing 5599.910390549147 in MA
Investing 4592.110978961162 in NVS
Investing 9040.456773489292 in LMT
Investing 8805.589089482577 in CHTR
Investing 4955.384407903769 in GOOG
Investing 2840.596577828235 in AEP
Raw prediction for AAPL: 0.5269452929496765
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47110655903816223
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5086774230003357
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5294482111930847
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5108243227005005
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4930493235588074
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6076869368553162
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3721030056476593
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.47112739086151123
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.3423316776752472
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5083284974098206
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4713194668292999
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5085013508796692
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4200078248977661
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.4306436777114868
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4811621606349945
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5238843560218811
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.45195472240448
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44824665784835815
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5353883504867554
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4682091176509857
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6547024250030518
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5518664717674255
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4933076500892639
Calibrated prediction for CODI: 0.5
Raw prediction for CSCO: 0.4012186825275421
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.4783935546875
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5288164615631104
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5437090396881104
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.47418031096458435
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4815971851348877
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.5130919218063354
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5405109524726868
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.500434160232544
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.44509974122047424
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4526483714580536
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.615879237651825
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.48311322927474976
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5052871108055115
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5056042671203613
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4513086676597595
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5114417672157288
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5005868077278137
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.4893815219402313
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49848273396492004
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.44964170455932617
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6755779385566711
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5904583930969238
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6064401268959045
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5202788710594177
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5255430340766907
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4929937422275543
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5021532773971558
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4972991943359375
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5214340686798096
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.41970404982566833
Calibrated prediction for NGG: 0.4015027582645416
Raw prediction for NVS: 0.5359624028205872
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.48269084095954895
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5139670968055725
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49097171425819397
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4830010235309601
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.5012471675872803
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.433414489030838
Calibrated prediction for PG: 0.47422680258750916
Raw prediction for PICO: 0.4895557463169098
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5164391398429871
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5299442410469055
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4418558180332184
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.42246344685554504
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5045552849769592
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5219385623931885
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4860759973526001
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.49784767627716064
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5406208038330078
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45370057225227356
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5408156514167786
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.497893363237381
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4643723666667938
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4464564621448517
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4182644486427307
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.412529855966568
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.34023797512054443
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.5299819707870483
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5848645567893982
Calibrated prediction for UPS: 0.5820285081863403

Simulating Trading Days:  16%|█▌        | 14/88 [06:44<03:28,  2.81s/it]

Raw prediction for UTX: 0.4687310755252838
Calibrated prediction for UTX: 0.47999998927116394
Raw prediction for V: 0.5592036247253418
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.4636801481246948
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.4993132948875427
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5028036236763
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.4929725229740143
Calibrated prediction for XOM: 0.5454545617103577
Investing 2662.940153828829 in XOM
Investing 2904.458109410615 in AGFS
Investing 1579.206917854585 in PM
Investing 5574.363274756273 in MA
Investing 4571.1615024996745 in NVS
Investing 8999.213685670853 in LMT
Investing 8765.417481652365 in CHTR
Investing 4932.777657002795 in GOOG
Investing 2827.6376115888656 in AEP
Raw prediction for AAPL: 0.5258914828300476
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47128018736839294
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5090934038162231
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5144200921058655
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5118770003318787
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49454978108406067
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6122387647628784
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3860805928707123
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.47119471430778503
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.342698872089386
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5083240270614624
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4707361161708832
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5075017809867859
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.42643865942955017
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.430055171251297
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4810692369937897
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5251761674880981
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4446190595626831
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.449257493019104
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5353361368179321
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4688604474067688
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6593698263168335
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5530020594596863
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4904681444168091
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.41327857971191406
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.4751971662044525
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5269953012466431
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5455407500267029
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48212873935699463
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4769338369369507
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.50660640001297
Calibrated prediction for EXC: 0.5416666865348816
Raw prediction for FB: 0.5407577753067017
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.506790816783905
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45021870732307434
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4527321457862854
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6250396370887756
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.48152607679367065
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5185298919677734
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.5051321387290955
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4511447846889496
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5076301097869873
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.49919822812080383
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.4927304685115814
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4985411465167999
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45034322142601013
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6684492826461792
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5911040306091309
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6075853705406189
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5198100209236145
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5266723036766052
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4900450110435486
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5044323801994324
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.49883803725242615
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5198497772216797
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.40684664249420166
Calibrated prediction for NGG: 0.4015027582645416
Raw prediction for NVS: 0.5363158583641052
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.48802244663238525
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.515605628490448
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.491822212934494
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.481825053691864
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.5015924572944641
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.43051981925964355
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49044594168663025
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5159327983856201
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5312718152999878
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4404285252094269
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.42054906487464905
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5054501891136169
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5120598673820496
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.4869130551815033
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.49926692247390747
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5406976938247681
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45459553599357605
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5406471490859985
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4978005290031433
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4769900143146515
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.44589924812316895
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.440219908952713
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.40902218222618103
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3354509770870209
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.5342875719070435
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5882180333137512
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.4673980474472046
Calibrated prediction for UTX: 0.4537791907787323
Raw prediction for V: 0.5592693090438843
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.48076871037483215
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4995744228363037
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5039958953857422
Calibrated prediction for WMT: 0.48566317558288574
Raw prediction for XOM: 0.49967536330223083
Calibrated prediction for XOM: 0.5454545617103577
Investing 2663.5480379022324 in XOM
Investing 2905.1211261231915 in AGFS
Investing 1579.567412149807 in PM
Investing 5575.635765483945 in MA
Investing 4572.204986811678 in NVS
Investing 9001.267985939228 in LMT
Investing 8767.418411968492 in CHTR
Investing 4933.9036894339115 in GOOG
Investing 2828.283092061632 in AEP

Simulating Trading Days:  17%|█▋        | 15/88 [06:45<02:58,  2.44s/it]

Raw prediction for AAPL: 0.5247488617897034
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47176849842071533
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5096550583839417
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5039759874343872
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5123409628868103
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49534738063812256
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6155377626419067
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.40008479356765747
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4709455370903015
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.34302881360054016
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5082389116287231
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4709376096725464
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5067673325538635
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.43134963512420654
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.426692396402359
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4810793101787567
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5293376445770264
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43793046474456787
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.45039865374565125
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5353676080703735
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.469999223947525
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6634958386421204
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.554793119430542
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.48858642578125
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.42198416590690613
Calibrated prediction for CSCO: 0.39646002650260925
Raw prediction for CVX: 0.47502365708351135
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5244395732879639
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5459716320037842
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48499369621276855
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4787271320819855
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4979947507381439
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5410690307617188
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.514943540096283
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45610398054122925
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4528115689754486
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6306353211402893
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4812983274459839
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5285753607749939
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5046379566192627
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4506182372570038
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5047557353973389
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.49739891290664673
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.4938196837902069
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4977310597896576
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4510059654712677
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6567947864532471
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5913071632385254
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6055802702903748
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5230487585067749
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5276006460189819
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.48587754368782043
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5029272437095642
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.49422770738601685
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5186291337013245
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4035681486129761
Calibrated prediction for NGG: 0.4015027582645416
Raw prediction for NVS: 0.535519003868103
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4915563762187958
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5167793035507202
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49263519048690796
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48074644804000854
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.5020051002502441
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.43063318729400635
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49118393659591675
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5155425071716309
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5346133708953857
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.43829789757728577
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.41961419582366943
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5065096020698547
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5040171146392822
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.48764556646347046
Calibrated prediction for SNP: 0.4545454680919647
Raw prediction for SNY: 0.49896395206451416
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5407581329345703
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45673027634620667
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5409549474716187
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.497439444065094
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.48647540807724
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.44588422775268555
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4573436379432678
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.4063672125339508
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  18%|█▊        | 16/88 [06:47<02:39,  2.22s/it]

Raw prediction for UN: 0.3322206735610962
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.5308337211608887
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5868400931358337
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.4682167172431946
Calibrated prediction for UTX: 0.47999998927116394
Raw prediction for V: 0.5587350726127625
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.4896080791950226
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.499726802110672
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5020534992218018
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5061994194984436
Calibrated prediction for XOM: 0.5454545617103577
Investing 2670.8398774002058 in XOM
Investing 2913.074306119354 in AGFS
Investing 1583.8917013616874 in PM
Investing 5590.89985703496 in MA
Investing 4584.722044676316 in NVS
Investing 9025.910230230571 in LMT
Investing 8791.420459974355 in CHTR
Investing 4947.410948657269 in GOOG
Investing 2836.025917071234 in AEP
Raw prediction for AAPL: 0.5237151384353638
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47290146350860596
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5103700757026672
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.49002060294151306
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5115534067153931
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49605196714401245
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6151761412620544
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.40588557720184326
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4705427289009094
Calibrated prediction for BABA: 0.47545257210731506
Raw prediction for BAC: 0.34454986453056335
Calibrated prediction for BAC: 0.33203792572021484
Raw prediction for BBL: 0.5081572532653809
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47123610973358154
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5063447952270508
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4372910261154175
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.4247683882713318
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4810943901538849
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5308938026428223
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4304029643535614
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4510880410671234
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5354650616645813
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4697194993495941
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.664919912815094
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5553884506225586
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.48774662613868713
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4274040460586548
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47722870111465454
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5206711888313293
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5470810532569885
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4842740595340729
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4816247224807739
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.49090462923049927
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5411123633384705
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5257494449615479
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45694464445114136
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4529135823249817
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6353994011878967
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4807424247264862
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5327238440513611
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5040615797042847
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4496144652366638
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5020661354064941
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.49895909428596497
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.493899405002594
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49681365489959717
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4505881667137146
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6546176075935364
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5913323760032654
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6022294163703918
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5260885953903198
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5271319150924683
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4808071553707123
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5022309422492981
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.49573835730552673
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5173567533493042
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.40202030539512634
Calibrated prediction for NGG: 0.4015027582645416
Raw prediction for NVS: 0.5302582383155823
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4921330213546753
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5179646611213684
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.493116170167923
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4799582064151764
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.5022602081298828
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.43038445711135864
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4915671944618225
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5152710676193237
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.537320077419281
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4356900155544281
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.42050260305404663
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5078321099281311
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.49820342659950256
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.4863971769809723
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4981493651866913
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5407699942588806
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4598921835422516
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5395846962928772
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4969445466995239
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4889088571071625
Calibrated prediction for TM: 0.4833333194255829

Simulating Trading Days:  19%|█▉        | 17/88 [06:49<02:27,  2.08s/it]

Raw prediction for TOT: 0.4500551223754883
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.46669748425483704
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.40586912631988525
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3312758803367615
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.523716926574707
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5879567861557007
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.470267653465271
Calibrated prediction for UTX: 0.47999998927116394
Raw prediction for V: 0.5593988299369812
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.4911385476589203
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4998154044151306
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5017400979995728
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5123555660247803
Calibrated prediction for XOM: 0.5454545617103577
Investing 2678.6399295169513 in XOM
Investing 2921.5817915736297 in AGFS
Investing 1588.5173765743577 in PM
Investing 5607.227795910438 in MA
Investing 4598.1114923896985 in NVS
Investing 9052.269942316865 in LMT
Investing 8817.095356604537 in CHTR
Investing 4961.859610881096 in GOOG
Investing 2844.3083866212723 in AEP
Raw prediction for AAPL: 0.5228309631347656
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4735766351222992
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5111483335494995
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4941391944885254
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5111986994743347
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4972132444381714
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6085609793663025
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.40521034598350525
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.47020676732063293
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.34704360365867615
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5077991485595703
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4712868928909302
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5058948993682861
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4358145296573639
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.42668649554252625
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4810866713523865
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5327597856521606
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42660191655158997
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4519089162349701
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5354264974594116
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.47115057706832886
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6625403761863708
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5529695153236389
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4857798218727112
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4320690333843231
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4790833592414856
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.528639018535614
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5472618937492371
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.47938084602355957
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.48702070116996765
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4875693917274475
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5409802794456482
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5363883972167969
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.45340994000434875
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45300695300102234
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6331313252449036
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.47910383343696594
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.533417284488678
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.503020703792572
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44824913144111633
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.4987727701663971
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5052908658981323
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.49406954646110535
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49644601345062256
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.44960933923721313
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6551319360733032
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5873972177505493
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5998095870018005
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5233719944953918
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5253490805625916
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4778187572956085
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5012129545211792
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4954380691051483
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5175026059150696
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4526735842227936
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.5276831984519958
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4912644028663635
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.522197425365448
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49326565861701965
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4790094494819641
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.5023257732391357
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.42991676926612854
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49198129773139954
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5157186388969421
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5361571907997131
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4315221607685089
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.42269477248191833
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5089091062545776
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.49426284432411194
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.4864926338195801
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4984949231147766
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5404900312423706
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4639810621738434
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.534930944442749
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4964804947376251
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.48671647906303406
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4523913562297821
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4682822525501251
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.40621134638786316
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  20%|██        | 18/88 [06:50<02:17,  1.97s/it]

Raw prediction for UN: 0.3328912854194641
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.5094221234321594
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5904746651649475
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.4726291596889496
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5601039528846741
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.4808560609817505
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4998294711112976
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5078418254852295
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.507681667804718
Calibrated prediction for XOM: 0.5454545617103577
Investing 2682.372195635902 in XOM
Investing 2925.6525592099506 in AGFS
Investing 1590.7307272821633 in PM
Investing 5615.040591536048 in MA
Investing 4604.518242152926 in NVS
Investing 9064.882865775899 in LMT
Investing 8829.380601031902 in CHTR
Investing 4968.773186800208 in GOOG
Investing 2848.2714858442237 in AEP
Raw prediction for AAPL: 0.5219976902008057
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47382912039756775
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5117518305778503
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4709535539150238
Calibrated prediction for AEP: 0.5
Raw prediction for AGFS: 0.5109243988990784
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49786895513534546
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6024977564811707
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.4022712707519531
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4698798954486847
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3498627245426178
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.507474958896637
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4709349572658539
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.505540132522583
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4374490976333618
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.43895775079727173
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4810202419757843
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5309603214263916
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.429167777299881
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4530211389064789
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.535539448261261
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.47252821922302246
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6558420658111572
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5483676195144653
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4839935898780823
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4353088140487671
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4800622761249542
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5224814414978027
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5451108813285828
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.47575411200523376
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.480538010597229
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4849919080734253
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.540809690952301
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5438272953033447
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4513261616230011
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45306503772735596
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6264412999153137
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4774898290634155
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.531460165977478
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5017295479774475
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44686973094940186
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.49718207120895386
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5171641111373901
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.49243253469467163
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49714192748069763
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.447040855884552
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.656913161277771
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.580388069152832
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5969260931015015
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5127226710319519
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.523076593875885
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4747864007949829
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.4994890093803406
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.49315696954727173
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5170934796333313
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.49654126167297363
Calibrated prediction for NGG: 0.4615384638309479
Raw prediction for NVS: 0.522783100605011
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4895271062850952
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5221173763275146
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49337902665138245
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4781925082206726
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.5021240711212158
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4292910397052765
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4921416640281677
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.516414225101471
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.533650815486908
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.42744025588035583
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.42776134610176086
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5096606612205505
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.487724632024765
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.48598721623420715
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4981708228588104
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5403947830200195
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4670514166355133
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5299363732337952
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4961159825325012
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.47930142283439636
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4533478915691376
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.46567991375923157
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.40709707140922546
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3347444236278534
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.49177780747413635
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5930691957473755
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.475372314453125
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.560011088848114
Calibrated prediction for V: 0.5523256063461304

Simulating Trading Days:  22%|██▏       | 19/88 [06:52<02:12,  1.92s/it]

Raw prediction for VZ: 0.4639398753643036
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.49988749623298645
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5131287574768066
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.49634361267089844
Calibrated prediction for XOM: 0.5454545617103577
Investing 2693.660084954977 in XOM
Investing 2937.964214664835 in AGFS
Investing 1597.424799199262 in PM
Investing 4224.133597911856 in MA
Investing 4623.89485676653 in NVS
Investing 9103.0294714728 in LMT
Investing 8866.536172187383 in CHTR
Investing 4989.682649653812 in GOOG
Investing 2113.7174738191925 in PPL
Raw prediction for AAPL: 0.5214288234710693
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4740549325942993
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5120064616203308
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.44336867332458496
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5127067565917969
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49805280566215515
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5947886109352112
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.39556920528411865
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4695248603820801
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3543708920478821
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5073108673095703
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4701996445655823
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5051239132881165
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4394385516643524
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.45708367228507996
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48091185092926025
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5294354557991028
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43489789962768555
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.45355722308158875
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.535460352897644
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.47265535593032837
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6445288062095642
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5424829721450806
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4821479022502899
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.43864724040031433
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.480508953332901
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5086490511894226
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5412988066673279
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4680861234664917
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4684532880783081
Calibrated prediction for DUK: 0.47767946124076843
Raw prediction for EXC: 0.48217031359672546
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5407038927078247
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5458081364631653
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.45691147446632385
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.452697217464447
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6171953678131104
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4773769974708557
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5261697769165039
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5002892017364502
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44572409987449646
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4945560395717621
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5333621501922607
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.49058103561401367
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4979218542575836
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4444522261619568
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.657661497592926
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5736544132232666
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5953201651573181
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4983951151371002
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5203102231025696
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4726685881614685
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.49508053064346313
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.48730090260505676
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5159679055213928
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.5368627905845642
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.5170345902442932
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.4872452914714813
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5207679271697998
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49332165718078613
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4773125648498535
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.5018141269683838
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4284844398498535
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4924505650997162
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5172812938690186
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5291932225227356
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.42273032665252686
Calibrated prediction for PTR: 0.4027489721775055
Raw prediction for RDS-B: 0.4397062063217163
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5102066993713379
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.4824144244194031
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.4875575006008148
Calibrated prediction for SNP: 0.4545454680919647
Raw prediction for SNY: 0.49948906898498535
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5401929616928101
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4706733524799347
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5251932144165039
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4958513081073761
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.47214484214782715
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4529128968715668
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.45933422446250916
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.4079989194869995
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3373514711856842
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4742511808872223
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  23%|██▎       | 20/88 [06:54<02:03,  1.81s/it]

Raw prediction for UPS: 0.5922237038612366
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.47817501425743103
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5586003661155701
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.44729775190353394
Calibrated prediction for VZ: 0.40557557344436646
Raw prediction for WFC: 0.5001068115234375
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5179779529571533
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4858267903327942
Calibrated prediction for XOM: 0.44186046719551086
Investing 725.1023145140604 in BBL
Investing 2946.269602500312 in AGFS
Investing 1601.9405902457072 in PM
Investing 4236.074882841199 in MA
Investing 4636.966234526758 in NVS
Investing 9128.763001466456 in LMT
Investing 8891.601154701375 in CHTR
Investing 4517.670078104488 in INTC
Investing 6677.130242438395 in NGG
Raw prediction for AAPL: 0.5211666226387024
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4742874205112457
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5118510723114014
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4206151068210602
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5123599767684937
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4978358745574951
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.586236298084259
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.38346925377845764
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4691116213798523
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3587978780269623
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5074383020401001
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46966150403022766
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5051334500312805
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4486027657985687
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.4728758633136749
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4806709587574005
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5295774936676025
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4402933120727539
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.45352575182914734
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5348832607269287
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4722287952899933
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6287447214126587
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5357043147087097
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4803972840309143
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4411791265010834
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48191097378730774
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.4963931739330292
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5375005602836609
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4642840325832367
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4525538980960846
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.48166322708129883
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5404791831970215
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5431868433952332
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4668417274951935
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45262643694877625
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6074599623680115
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4761321246623993
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5165801644325256
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.49866509437561035
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.445015549659729
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4917069375514984
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5497893691062927
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4895303547382355
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49831482768058777
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4418301284313202
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.6560541987419128
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5675947666168213
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5943411588668823
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4847894310951233
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5171518921852112
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.47279468178749084
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.48974505066871643
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.47974422574043274
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5147297978401184
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.5617755055427551
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.5112372040748596
Calibrated prediction for NVS: 0.5904762148857117
Raw prediction for ORCL: 0.48355865478515625
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5213817358016968
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4931793510913849
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4767916202545166
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.5015047788619995
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4275229275226593
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49298331141471863
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5184944868087769
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5239377617835999
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4200669825077057
Calibrated prediction for PTR: 0.39499160647392273
Raw prediction for RDS-B: 0.4636656939983368
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.510700523853302
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.4834716320037842
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.48786917328834534
Calibrated prediction for SNP: 0.4545454680919647
Raw prediction for SNY: 0.5009992122650146
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.539854884147644
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.47456374764442444
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5202201008796692
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4954690933227539
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.46485981345176697
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.44976648688316345
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.44983771443367004
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.4088691473007202
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3393952250480652
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.45884642004966736
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.588945746421814
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.48078858852386475
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5568374991416931
Calibrated prediction for V: 0.5523256063461304

Simulating Trading Days:  24%|██▍       | 21/88 [06:55<01:57,  1.76s/it]

Raw prediction for VZ: 0.4270753860473633
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5002360343933105
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5211503505706787
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4859626889228821
Calibrated prediction for XOM: 0.44186046719551086
Investing 725.6321440164189 in BBL
Investing 2948.4224304889426 in AGFS
Investing 1603.1111221399635 in PM
Investing 4239.170166640746 in MA
Investing 4640.354448111677 in NVS
Investing 9135.433353858665 in LMT
Investing 8898.098213834503 in CHTR
Investing 4520.971122441806 in INTC
Investing 6682.009196101513 in NGG
Raw prediction for AAPL: 0.5209464430809021
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.474181592464447
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.511204719543457
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.403433233499527
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5099427700042725
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49742329120635986
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5789024829864502
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.36959540843963623
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4687865972518921
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.36361756920814514
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5077700614929199
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46882158517837524
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5054382085800171
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4465758800506592
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.4835997223854065
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4805183708667755
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.52923583984375
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4441171884536743
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.45274969935417175
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5343095660209656
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.47100844979286194
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6097258925437927
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5303061008453369
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4796202480792999
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.443965345621109
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.482208788394928
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.4843430817127228
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5348594784736633
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.46470925211906433
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.43634846806526184
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.48400425910949707
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5400282144546509
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5356207489967346
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.47639796137809753
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4527527689933777
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5996283292770386
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.47472047805786133
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.508656919002533
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.497060090303421
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44452792406082153
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.49207618832588196
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5690587162971497
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48824989795684814
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4982042610645294
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.43909114599227905
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.642388641834259
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5601604580879211
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5956440567970276
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4740966856479645
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5141247510910034
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4734199047088623
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.48612281680107117
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4712375998497009
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5134426951408386
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.5787349343299866
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.5059524774551392
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.48168352246284485
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5209657549858093
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4926496148109436
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.47640857100486755
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.5011312365531921
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4270600974559784
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4932088255882263
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5199589133262634
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5193127989768982
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4183353781700134
Calibrated prediction for PTR: 0.39499160647392273
Raw prediction for RDS-B: 0.48666277527809143
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5110161304473877
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.48753175139427185
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.48569756746292114
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.5023791790008545
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5395553112030029
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4773781895637512
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5162079334259033
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4951687455177307
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4578315317630768
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.447395920753479
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4433114230632782
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.41096463799476624
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.340211421251297
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.45226481556892395
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5863368511199951
Calibrated prediction for UPS: 0.5820285081863403

Simulating Trading Days:  25%|██▌       | 22/88 [06:57<01:51,  1.69s/it]

Raw prediction for UTX: 0.48292475938796997
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5554287433624268
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.411155641078949
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5003593564033508
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5229892730712891
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4868229627609253
Calibrated prediction for XOM: 0.44186046719551086
Investing 2358.3350822336147 in RDS-B
Investing 2946.7786778205577 in AGFS
Investing 1602.2173837945058 in PM
Investing 4236.806818973499 in MA
Investing 3019.8054645796406 in JNJ
Investing 9130.340327568749 in LMT
Investing 8893.137502461772 in CHTR
Investing 4518.4506700570455 in INTC
Investing 6678.283959740303 in NGG
Raw prediction for AAPL: 0.5206456780433655
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4739948809146881
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5104556083679199
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.3938656747341156
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5075226426124573
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49681830406188965
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5723815560340881
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.35705283284187317
Calibrated prediction for BA: 0.46666666865348816
Raw prediction for BABA: 0.4685214161872864
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3704005479812622
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5080817937850952
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46855202317237854
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5059983134269714
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4375341534614563
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.49114376306533813
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4806111454963684
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5295813679695129
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4463205933570862
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4512077867984772
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5337502360343933
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4707099199295044
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5939573645591736
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.5265323519706726
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4798714518547058
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.44753164052963257
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48355868458747864
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.47473660111427307
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5326012372970581
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.46893125772476196
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4230726361274719
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4881085455417633
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5395205020904541
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5246028900146484
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.48296424746513367
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4528481364250183
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5937833786010742
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.47305065393447876
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5031726360321045
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4956534802913666
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.44415390491485596
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4906681478023529
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5856512188911438
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4868973195552826
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49756094813346863
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.43765103816986084
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.6257452368736267
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5568106770515442
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5969139933586121
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.46752601861953735
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5102212429046631
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4748809039592743
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.4836212694644928
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4607659578323364
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5128245949745178
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.5874873995780945
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.5051467418670654
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.4808129668235779
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5207560658454895
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49226805567741394
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.47612178325653076
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.5007033944129944
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4265291094779968
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.493756502866745
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5212065577507019
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5158116221427917
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.41830047965049744
Calibrated prediction for PTR: 0.39499160647392273
Raw prediction for RDS-B: 0.5088282823562622
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.511238694190979
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.4964071810245514
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.48472297191619873
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.5039514899253845
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5392419695854187
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4794436991214752
Calibrated prediction for SPLP: 0.49326133728027344
Raw prediction for SRE: 0.5124619603157043
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4948497712612152
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4508206844329834
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4519437849521637
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4377627670764923
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.4116540551185608
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3415907025337219
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4489683508872986
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5823161005973816
Calibrated prediction for UPS: 0.5820285081863403

Simulating Trading Days:  26%|██▌       | 23/88 [06:59<01:50,  1.70s/it]

Raw prediction for UTX: 0.4842536747455597
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5549237132072449
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.3940179646015167
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5005381107330322
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5229029059410095
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.48690342903137207
Calibrated prediction for XOM: 0.44186046719551086
Investing 2359.2430384979457 in RDS-B
Investing 2947.913184184933 in AGFS
Investing 1602.8342356241697 in PM
Investing 4238.437984672143 in MA
Investing 3020.968086172001 in JNJ
Investing 9133.855497977884 in LMT
Investing 6679.417735935377 in AMZN
Investing 4520.190268310854 in INTC
Investing 6680.855091299133 in NGG
Raw prediction for AAPL: 0.5203688144683838
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47379592061042786
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5101592540740967
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.39552003145217896
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5058687925338745
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4959271550178528
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5710439085960388
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3435496389865875
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46823030710220337
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3764059543609619
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5081993341445923
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4690086543560028
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5070157051086426
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4332957863807678
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.4967131018638611
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.48084232211112976
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5293756127357483
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4469297230243683
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44928985834121704
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5334622263908386
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4716970920562744
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5831921696662903
Calibrated prediction for CHTR: 0.5619586110115051
Raw prediction for CMCSA: 0.5244547128677368
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4808955788612366
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.45193150639533997
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48246580362319946
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.47328245639801025
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5285820960998535
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4743956923484802
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.41484159231185913
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4903113842010498
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5390411019325256
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5126622915267944
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.48478201031684875
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4529051184654236
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5975372791290283
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.47478657960891724
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.49857446551322937
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4944811761379242
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.4437495768070221
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.48877882957458496
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5991520285606384
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48657673597335815
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4968451261520386
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4368206262588501
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.602633535861969
Calibrated prediction for LMT: 0.5185185074806213
Raw prediction for MA: 0.5553714036941528
Calibrated prediction for MA: 0.5807626843452454
Raw prediction for MCD: 0.5985283851623535
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.47123849391937256
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.511273980140686
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4780365228652954
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.48159828782081604
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.45091480016708374
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5133570432662964
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.610868513584137
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.5064175128936768
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.48211345076560974
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5226772427558899
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49188125133514404
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4761999547481537
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.4997875392436981
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.42592525482177734
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49452826380729675
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5227321982383728
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5132398009300232
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.42122015357017517
Calibrated prediction for PTR: 0.3961099684238434
Raw prediction for RDS-B: 0.5284974575042725
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5112241506576538
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5088658928871155
Calibrated prediction for SLB: 0.48148149251937866
Raw prediction for SNP: 0.48376762866973877
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.504578173160553
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5389668345451355
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4786416292190552
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5097214579582214
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.49468523263931274
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.44263720512390137
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.4550725817680359
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.44470125436782837
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.4113689661026001
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  27%|██▋       | 24/88 [07:00<01:46,  1.66s/it]

Raw prediction for UN: 0.342838317155838
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4492962956428528
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5759050846099854
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.48467156291007996
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5558602809906006
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.3792338967323303
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5008509159088135
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5233362913131714
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.49130353331565857
Calibrated prediction for XOM: 0.5454545617103577
Investing 2359.2761420893858 in RDS-B
Investing 2947.95454766977 in AGFS
Investing 1602.8567257062919 in PM
Investing 4161.955413258861 in MA
Investing 3021.0104747227547 in JNJ
Investing 4819.244035107815 in DHR
Investing 6679.511457825059 in AMZN
Investing 4520.253693116791 in INTC
Investing 7967.423551250273 in NGG
Raw prediction for AAPL: 0.5203359127044678
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47361060976982117
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5097770094871521
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.3921644687652588
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5049927234649658
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49473798274993896
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5650195479393005
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.33290815353393555
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46805787086486816
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3804319500923157
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5078730583190918
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46949154138565063
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5081260204315186
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.42810720205307007
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.49876245856285095
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.480812668800354
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.527945876121521
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.44730058312416077
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4478660523891449
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5334982872009277
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4772314429283142
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5763741135597229
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.522934079170227
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4816661477088928
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.45659831166267395
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47924578189849854
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.46747535467147827
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5247176885604858
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4783135652542114
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.40672528743743896
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4901907742023468
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5386616587638855
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.49974560737609863
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.484526664018631
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4529237449169159
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.602636992931366
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.47615817189216614
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.4952548146247864
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4936344027519226
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.4435326159000397
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4889017641544342
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6083204746246338
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4863549768924713
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49659264087677
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.43470922112464905
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.5856360197067261
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5524948835372925
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6026071906089783
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.47705724835395813
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.513999342918396
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4796030819416046
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.47987040877342224
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.44545650482177734
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5132232308387756
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6235306859016418
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.5038679242134094
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.482632040977478
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5229283571243286
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49117714166641235
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.47621914744377136
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.4984085261821747
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4255814850330353
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49584126472473145
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5241840481758118
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5119296312332153
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.42108064889907837
Calibrated prediction for PTR: 0.395496666431427
Raw prediction for RDS-B: 0.5481507182121277
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5109871625900269
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5240819454193115
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.48537522554397583
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.5024242997169495
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.538709819316864
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4763314425945282
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5078166127204895
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.49451252818107605
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.42959097027778625
Calibrated prediction for TM: 0.40625

Simulating Trading Days:  28%|██▊       | 25/88 [07:02<01:49,  1.74s/it]

Raw prediction for TOT: 0.4579031467437744
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.44852739572525024
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.41258299350738525
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.34423592686653137
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.448423832654953
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5701271891593933
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.4842125177383423
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.555851936340332
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.36758697032928467
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5011190176010132
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5243822336196899
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4853442311286926
Calibrated prediction for XOM: 0.44186046719551086
Investing 2361.6586377726826 in RDS-B
Investing 2950.931515418089 in AGFS
Investing 1604.4753574390556 in PM
Investing 2963.1072775699977 in MA
Investing 3024.0612174004846 in JNJ
Investing 4824.110709214149 in DHR
Investing 6686.256707747651 in AMZN
Investing 4524.818434275797 in INTC
Investing 7975.4693886489595 in NGG
Raw prediction for AAPL: 0.5203871130943298
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4734031856060028
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5088973045349121
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.39239758253097534
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5048186182975769
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49320128560066223
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5598247051239014
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.32293248176574707
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46789538860321045
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.38655391335487366
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5078916549682617
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46999162435531616
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5099378228187561
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.44669440388679504
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.5003948211669922
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.480793833732605
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5286191701889038
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4469662010669708
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.446304589509964
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5336511135101318
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4840698540210724
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5710278153419495
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.522252082824707
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4824882447719574
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4611458480358124
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47945186495780945
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.46117499470710754
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5209763050079346
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4806675910949707
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.39914217591285706
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4910416603088379
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5384167432785034
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.48935192823410034
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.48331552743911743
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4529743194580078
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6068719625473022
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4761526584625244
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.49048396944999695
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49299687147140503
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.44345876574516296
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.49063393473625183
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6154300570487976
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4861697256565094
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49663686752319336
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4326150417327881
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.576357364654541
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5519558787345886
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6075331568717957
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4834624230861664
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.516861081123352
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4806481599807739
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4782291650772095
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.439769983291626
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5127813220024109
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6238724589347839
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.49954289197921753
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.48260727524757385
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.52217036485672
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49039289355278015
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4760850965976715
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.4971194267272949
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4246147871017456
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49744221568107605
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.525835394859314
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.51132732629776
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.42146939039230347
Calibrated prediction for PTR: 0.397205650806427
Raw prediction for RDS-B: 0.5649510622024536
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5104774832725525
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5379927158355713
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4866325557231903
Calibrated prediction for SNP: 0.42712241411209106
Raw prediction for SNY: 0.4990665018558502
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5384688973426819
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4726886451244354
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5066899657249451
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.49447745084762573
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.41455620527267456
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.46222928166389465
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4486900269985199
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.414170503616333
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  30%|██▉       | 26/88 [07:04<01:47,  1.73s/it]

Raw prediction for UN: 0.3448234498500824
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.44761043787002563
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5669941902160645
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.4840036630630493
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.556032657623291
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.36108729243278503
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.501349151134491
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5245505571365356
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.484078049659729
Calibrated prediction for XOM: 0.44186046719551086
Investing 2362.506359146591 in RDS-B
Investing 2951.9907572909615 in AGFS
Investing 1605.051286590143 in PM
Investing 2964.1708899533473 in MA
Investing 3025.1467093039273 in JNJ
Investing 4825.842331935949 in DHR
Investing 4654.474727208411 in MCD
Investing 4526.442625527843 in INTC
Investing 7978.3321969141225 in NGG
Raw prediction for AAPL: 0.5202521085739136
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4727155566215515
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5072954893112183
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.3961934447288513
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5054525136947632
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49164626002311707
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5573226809501648
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.3200291693210602
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46781766414642334
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3931732773780823
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5076347589492798
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4702339172363281
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5115312933921814
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.4652978777885437
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.5010796785354614
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.48069414496421814
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5305622220039368
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.44756409525871277
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44541114568710327
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5332891941070557
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4933754503726959
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5709776878356934
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5220516324043274
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4814927875995636
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46432289481163025
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.479015976190567
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.45450711250305176
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5184987783432007
Calibrated prediction for DHR: 0.49618321657180786
Raw prediction for DIS: 0.48223721981048584
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.3949563801288605
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4923166036605835
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5381221175193787
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.47918036580085754
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4822656512260437
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4530498683452606
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6084165573120117
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.47605007886886597
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.4881590008735657
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4924824833869934
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.44357985258102417
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.493775874376297
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6202470064163208
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48526033759117126
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49664464592933655
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4317610561847687
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.5656570196151733
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5523041486740112
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6091952919960022
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.484832227230072
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5203744173049927
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.48082616925239563
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4789491295814514
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4349956810474396
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.512827455997467
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6198365688323975
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.4945834279060364
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.48093050718307495
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5198187828063965
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48961660265922546
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4759686589241028
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.49621301889419556
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42401665449142456
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49855026602745056
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5275754332542419
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5112587809562683
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.42337387800216675
Calibrated prediction for PTR: 0.4055781364440918
Raw prediction for RDS-B: 0.5761711001396179
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.5097336769104004
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5498107671737671
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4882003664970398
Calibrated prediction for SNP: 0.4545454680919647
Raw prediction for SNY: 0.4944850206375122
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5383746027946472
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.46903812885284424
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.506310224533081
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4945153295993805
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.40454813838005066
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.46763938665390015
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.44065824151039124
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.41594937443733215
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.34241095185279846
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4463837146759033
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5651351809501648
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.4840324819087982
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5564912557601929
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.35693714022636414
Calibrated prediction for VZ: 0.374971479177475

Simulating Trading Days:  31%|███       | 27/88 [07:06<01:50,  1.81s/it]

Raw prediction for WFC: 0.5015839338302612
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5238439440727234
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4786466956138611
Calibrated prediction for XOM: 0.44186046719551086
Investing 4439.823409354908 in RDS-B
Investing 2945.7790703163305 in AGFS
Investing 1601.6738789387464 in PM
Investing 2957.9335730978564 in MA
Investing 3018.781084898051 in JNJ
Investing 1896.8694069840833 in MMM
Investing 4644.680611164741 in MCD
Investing 4516.917919317649 in INTC
Investing 7961.5438983517215 in NGG
Raw prediction for AAPL: 0.5203637480735779
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4721240699291229
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5056177973747253
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.41046300530433655
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5062214136123657
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4899531304836273
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.556045413017273
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.3233923614025116
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46782806515693665
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.4004092812538147
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5073833465576172
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4702887535095215
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5124505162239075
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.4837474226951599
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.5017194151878357
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4807370603084564
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5327267646789551
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4489142894744873
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44525283575057983
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5322934985160828
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5051127076148987
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5722753405570984
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5218528509140015
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4799005091190338
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4665033519268036
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4796990156173706
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.45152848958969116
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5166216492652893
Calibrated prediction for DHR: 0.49618321657180786
Raw prediction for DIS: 0.481868177652359
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.39619606733322144
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.49361473321914673
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5377987027168274
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.47071224451065063
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.48640507459640503
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.45313191413879395
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6114323735237122
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.47537311911582947
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.48854517936706543
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4921509027481079
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.44372159242630005
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4969255328178406
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6241676807403564
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48474371433258057
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49685394763946533
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4311825931072235
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.552870512008667
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5545738935470581
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.605413556098938
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4866750240325928
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5239952802658081
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.48014888167381287
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4814627468585968
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.43149420619010925
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5141761898994446
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6177424788475037
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.48982900381088257
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.48066744208335876
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.518190324306488
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48903757333755493
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.47585365176200867
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.4956948459148407
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4232405424118042
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49804258346557617
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5290808081626892
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5123411417007446
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.42708826065063477
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5825156569480896
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.508816123008728
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5576307773590088
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49155354499816895
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4901318848133087
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5383389592170715
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.46522068977355957
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5067924857139587
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4946760833263397
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3997877836227417
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.47308820486068726
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.43107885122299194
Calibrated prediction for TSM: 0.4332200288772583
Raw prediction for UL: 0.4164719581604004
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3378126323223114
Calibrated prediction for UN: 0.3459798991680145

Simulating Trading Days:  32%|███▏      | 28/88 [07:07<01:45,  1.75s/it]

Raw prediction for UNH: 0.4432448744773865
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5639694333076477
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.4844297170639038
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5576201677322388
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.35615089535713196
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5018522143363953
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5214685797691345
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4729267954826355
Calibrated prediction for XOM: 0.44186046719551086
Investing 4440.109564211807 in RDS-B
Investing 2945.9689312433543 in AGFS
Investing 1601.7771097921764 in PM
Investing 2958.1242174051376 in MA
Investing 3018.9756509403715 in JNJ
Investing 1896.991663737036 in MMM
Investing 4644.979969448413 in MCD
Investing 4517.209043058765 in INTC
Investing 7962.057034628747 in NGG
Raw prediction for AAPL: 0.5204702615737915
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47208771109580994
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5042449831962585
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4264921247959137
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5073180794715881
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48832830786705017
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5555857419967651
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.3266943395137787
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46791762113571167
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.40423890948295593
Calibrated prediction for BAC: 0.5714285969734192
Raw prediction for BBL: 0.5074292421340942
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4702908396720886
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.512852132320404
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5030075907707214
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.5017836689949036
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4809507429599762
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5346998572349548
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4510028660297394
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4449571967124939
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5313959121704102
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5152037143707275
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5750513672828674
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5225350260734558
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4760192930698395
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46655797958374023
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48449549078941345
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.4514334797859192
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5142229199409485
Calibrated prediction for DHR: 0.49618321657180786
Raw prediction for DIS: 0.4800732433795929
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4027034044265747
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4938908815383911
Calibrated prediction for EXC: 0.5
Raw prediction for FB: 0.5376688838005066
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.46660053730010986
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4900168478488922
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.45318737626075745
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6133794784545898
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.47475287318229675
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.49139487743377686
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49199920892715454
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.4440029561519623
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4990001618862152
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6257634162902832
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4846660792827606
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.49772727489471436
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.43238696455955505
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.5405686497688293
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5572818517684937
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5973313450813293
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.48876118659973145
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5268072485923767
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4798523485660553
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.486379474401474
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4304199814796448
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5164750814437866
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6163311004638672
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.48782628774642944
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.48048484325408936
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5172647833824158
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.488552063703537
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4763875901699066
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.4955679774284363
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4225127100944519
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4970356523990631
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.530225932598114
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5168415307998657
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.43294960260391235
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5863350033760071
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.5076450705528259
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5618554353713989
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49558594822883606
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.49016445875167847
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.538292646408081
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.46281352639198303
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5070232152938843
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4948163628578186
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4077630639076233
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.47613731026649475
Calibrated prediction for TOT: 0.5260158181190491

Simulating Trading Days:  33%|███▎      | 29/88 [07:09<01:39,  1.69s/it]

Raw prediction for TSM: 0.4212437570095062
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.4154922664165497
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.33442336320877075
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.43860387802124023
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5634819269180298
Calibrated prediction for UPS: 0.5820285081863403
Raw prediction for UTX: 0.48490744829177856
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5586541295051575
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.35552075505256653
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5020976662635803
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5186376571655273
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4677242338657379
Calibrated prediction for XOM: 0.44186046719551086
Investing 4437.141712704199 in RDS-B
Investing 2943.9997910211337 in AGFS
Investing 1600.7064522911846 in PM
Investing 4232.811403019946 in MA
Investing 3016.9577116738965 in JNJ
Investing 1895.7236793578847 in MMM
Investing 4641.875178765712 in MCD
Investing 4514.189656830848 in INTC
Investing 7956.735048170497 in NGG
Raw prediction for AAPL: 0.5205208659172058
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4723111093044281
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5031704902648926
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.45647022128105164
Calibrated prediction for AEP: 0.5
Raw prediction for AGFS: 0.508952796459198
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48691970109939575
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5934380292892456
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3294016718864441
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46784335374832153
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.4026886224746704
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5075103640556335
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4703872501850128
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5132849812507629
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5141943693161011
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.5019659399986267
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.48132017254829407
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5387377142906189
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.45435866713523865
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4439658224582672
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5309029221534729
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5242021679878235
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5858993530273438
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.5280497670173645
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.470943421125412
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4646907150745392
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.49229028820991516
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.45445379614830017
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5151564478874207
Calibrated prediction for DHR: 0.49618321657180786
Raw prediction for DIS: 0.4786060154438019
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.41547590494155884
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.49486809968948364
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5376628041267395
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.4709390699863434
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4931515157222748
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4532066583633423
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6156244874000549
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4819110333919525
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.49673014879226685
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4919547736644745
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.44463488459587097
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5001577138900757
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6258251070976257
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48397964239120483
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.4991317093372345
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.43601298332214355
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.5400614142417908
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.561372697353363
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5869017243385315
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4893741011619568
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5280571579933167
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4800855219364166
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4943350553512573
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.43162021040916443
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5200305581092834
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6165093779563904
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.4873787462711334
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.4814218282699585
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5162930488586426
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4888443350791931
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.47763359546661377
Calibrated prediction for PEP: 0.4750824272632599
Raw prediction for PFE: 0.4959584176540375
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42359620332717896
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4961053133010864
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5315735936164856
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.525041937828064
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.43837523460388184
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.587764322757721
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.5064316987991333
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5645017027854919
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4978254735469818
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.492672860622406
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5384120941162109
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45999518036842346
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5092762112617493
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.49502280354499817
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4251978397369385
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4780190885066986
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.4131512939929962
Calibrated prediction for TSM: 0.4206155836582184
Raw prediction for UL: 0.4122494161128998
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  34%|███▍      | 30/88 [07:11<01:39,  1.72s/it]

Raw prediction for UN: 0.3327048718929291
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.43865177035331726
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5545339584350586
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.484908789396286
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5597242712974548
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.3587176501750946
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5020790696144104
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5178077220916748
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4621292054653168
Calibrated prediction for XOM: 0.44186046719551086
Investing 4424.538679078701 in RDS-B
Investing 2935.6378024343217 in AGFS
Investing 1596.1598863825463 in PM
Investing 4220.788738904911 in MA
Investing 3008.388497087383 in JNJ
Investing 1890.3391613905646 in MMM
Investing 6651.604025877602 in AMZN
Investing 4501.367780109168 in INTC
Investing 7934.135139072673 in NGG
Raw prediction for AAPL: 0.5203710198402405
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47260668873786926
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5025620460510254
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4954123795032501
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5097187161445618
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48565566539764404
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6267516016960144
Calibrated prediction for AMZN: 0.7142857313156128
Raw prediction for BA: 0.331391304731369
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4683399796485901
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.39559927582740784
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.50774747133255
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47065773606300354
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5135835409164429
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.523085355758667
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5045617818832397
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4816323518753052
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5421807765960693
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4580216705799103
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4428528845310211
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5303325653076172
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5327786803245544
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5945284962654114
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.5329380631446838
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4662241041660309
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46537455916404724
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.5005863308906555
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.46084660291671753
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.517887532711029
Calibrated prediction for DHR: 0.49618321657180786
Raw prediction for DIS: 0.47997283935546875
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.43443742394447327
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.49680936336517334
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5378054976463318
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.48025059700012207
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.49470704793930054
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4532383680343628
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.628346860408783
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.48471570014953613
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5031443238258362
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4923121929168701
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.4453931748867035
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5049467086791992
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6219983696937561
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48316097259521484
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5010928511619568
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.44158971309661865
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.54393070936203
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5674769282341003
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5824476480484009
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.49191558361053467
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5285331606864929
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4818016588687897
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.49745336174964905
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4399195611476898
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5248925089836121
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6259716749191284
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.4870092570781708
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.48739829659461975
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.515946090221405
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48958590626716614
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.47938892245292664
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4962480068206787
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4244586229324341
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49507907032966614
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5332244038581848
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5351859331130981
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.44658491015434265
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5883801579475403
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.5052471160888672
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5655726194381714
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49758580327033997
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4960719347000122
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5386335849761963
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4569389224052429
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5133123993873596
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4953186810016632
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4457479417324066
Calibrated prediction for TM: 0.42966172099113464
Raw prediction for TOT: 0.47865724563598633
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.43113765120506287
Calibrated prediction for TSM: 0.43365368247032166
Raw prediction for UL: 0.4078787863254547
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3346329927444458
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.43867403268814087
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5488681793212891
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.4851672649383545
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5632767677307129
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.3662935197353363
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5021100044250488
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5174698829650879
Calibrated prediction for WMT: 0.5

Simulating Trading Days:  35%|███▌      | 31/88 [07:13<01:40,  1.76s/it]

Raw prediction for XOM: 0.4649514853954315
Calibrated prediction for XOM: 0.44186046719551086
Investing 4416.545735700682 in RDS-B
Investing 2930.3345632866613 in AGFS
Investing 1593.2764184055466 in PM
Investing 4687.274154134365 in V
Investing 3002.953833575455 in JNJ
Investing 1886.9242576055237 in MMM
Investing 11306.306293538488 in AMZN
Investing 4493.236044712623 in INTC
Investing 7919.802098383026 in NGG
Raw prediction for AAPL: 0.5204899311065674
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4733859896659851
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5021324753761292
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.532505989074707
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.508935809135437
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48466169834136963
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6512969136238098
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.33419573307037354
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46901264786720276
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.396239310503006
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5080956816673279
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4710140824317932
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5137481093406677
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5308836698532104
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5072739124298096
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4816322326660156
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5458546280860901
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4658426344394684
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4415239095687866
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5298758149147034
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5365806818008423
Calibrated prediction for CHL: 0.5326846241950989
Raw prediction for CHTR: 0.6031325459480286
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5401595830917358
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.462667316198349
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46537041664123535
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.5082069635391235
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.4657403528690338
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5244624614715576
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48236575722694397
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4579783082008362
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.49795666337013245
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5382705926895142
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.49178946018218994
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.49381470680236816
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4533139765262604
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6446413993835449
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4859520196914673
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5106219053268433
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49307042360305786
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.44579175114631653
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5148323178291321
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6107385158538818
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4821219742298126
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5031547546386719
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.44728511571884155
Calibrated prediction for KO: 0.44293633103370667
Raw prediction for LMT: 0.5714579224586487
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5775758624076843
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5777886509895325
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4899979531764984
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5281863212585449
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4838376045227051
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.498302161693573
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4593107998371124
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5306106805801392
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6353751420974731
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.48556727170944214
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.49610960483551025
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5143476128578186
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4905985891819
Calibrated prediction for PCLN: 0.49335020780563354
Raw prediction for PEP: 0.4811594486236572
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4963253438472748
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42532259225845337
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4941648244857788
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5346342921257019
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5459479093551636
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.453568696975708
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5850674510002136
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.5041661858558655
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.565859317779541
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4961302578449249
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.501994788646698
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5389333367347717
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.453782856464386
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5197674632072449
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4953724443912506
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.46514737606048584
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4782288372516632
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.4606907367706299
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.40671753883361816
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.33935117721557617
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.44376495480537415
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5447278022766113
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.4848760664463043
Calibrated prediction for UTX: 0.4891962707042694

Simulating Trading Days:  36%|███▋      | 32/88 [07:15<01:42,  1.84s/it]

Raw prediction for V: 0.5670247077941895
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.3747049570083618
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5019829273223877
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5158399939537048
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4740700125694275
Calibrated prediction for XOM: 0.44186046719551086
Investing 4432.335134091913 in RDS-B
Investing 2940.8106734886505 in AGFS
Investing 1598.9724708463048 in PM
Investing 4704.031421785937 in V
Investing 3013.689561736385 in JNJ
Investing 4807.565404220464 in DHR
Investing 11477.804232257973 in AMZN
Investing 9662.818193556837 in GOOG
Investing 7948.11583450043 in NGG
Raw prediction for AAPL: 0.5208056569099426
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47394850850105286
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5018389225006104
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5517410039901733
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.507596492767334
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48377129435539246
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6635023355484009
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.3344789743423462
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4695536494255066
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.39497309923171997
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.508069634437561
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47091802954673767
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.513778805732727
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5367143154144287
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5100181102752686
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4813586175441742
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5478754043579102
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.46710410714149475
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4406585991382599
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5293958187103271
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5376746654510498
Calibrated prediction for CHL: 0.5406579971313477
Raw prediction for CHTR: 0.6107181310653687
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5469785928726196
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4595654010772705
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4663277566432953
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.511921226978302
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.47493404150009155
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5301099419593811
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48329582810401917
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.47728416323661804
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.49717044830322266
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5391541719436646
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5063206553459167
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4928511083126068
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.453385591506958
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6532676219940186
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.48827674984931946
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5132810473442078
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.4940069913864136
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.44561922550201416
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5248895287513733
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5925373435020447
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48125413060188293
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5045856833457947
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.451140820980072
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5954071879386902
Calibrated prediction for LMT: 0.5185185074806213
Raw prediction for MA: 0.5851913094520569
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5747507810592651
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4886350929737091
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5280375480651855
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.484963983297348
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4989396333694458
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4767548143863678
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5351957082748413
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.6282682418823242
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.48549994826316833
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5029183626174927
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5121795535087585
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4910440146923065
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48254328966140747
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4961310625076294
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42571502923965454
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49425578117370605
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5352246761322021
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5553012490272522
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4571619927883148
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5743513107299805
Calibrated prediction for RDS-B: 0.597220778465271
Raw prediction for REX: 0.5035861730575562
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5619773268699646
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49585869908332825
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.5070738792419434
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5392553210258484
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4516892433166504
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5262838006019592
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4955287575721741
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4760507345199585
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.47961345314979553
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.4792652130126953
Calibrated prediction for TSM: 0.4482758641242981
Raw prediction for UL: 0.40953508019447327
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3477625250816345
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4523519277572632
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5394293665885925
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.48544061183929443
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5704583525657654
Calibrated prediction for V: 0.5828738808631897

Simulating Trading Days:  38%|███▊      | 33/88 [07:16<01:38,  1.79s/it]

Raw prediction for VZ: 0.38178837299346924
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5017107725143433
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5134310126304626
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4776361286640167
Calibrated prediction for XOM: 0.44186046719551086
Investing 3682.26478722513 in RDS-B
Investing 4140.630853654303 in IEP
Investing 1597.6136888851486 in PM
Investing 5639.336412398689 in MA
Investing 3011.1285751730297 in JNJ
Investing 4803.4800098391115 in DHR
Investing 11468.050572561619 in AMZN
Investing 9654.60688079522 in GOOG
Investing 7941.361649160776 in NGG
Raw prediction for AAPL: 0.5210736989974976
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47431832551956177
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5017244815826416
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5533676743507385
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5064609050750732
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4829474687576294
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6623507738113403
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.3324681222438812
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4699151813983917
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3917267918586731
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5080013871192932
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4703032970428467
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5136680006980896
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5452931523323059
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5132200121879578
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4808776080608368
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5498511791229248
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4619614779949188
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.439797043800354
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5289314389228821
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.5375593304634094
Calibrated prediction for CHL: 0.5398173928260803
Raw prediction for CHTR: 0.6159775257110596
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5510803461074829
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45632290840148926
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46611446142196655
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.5116844177246094
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.49065059423446655
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5355706214904785
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48656222224235535
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.49197518825531006
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4986954629421234
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5397948026657104
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5209541916847229
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.49349409341812134
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.453444242477417
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6574499607086182
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.48832055926322937
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5147654414176941
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.49500149488449097
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.4449213743209839
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5339639782905579
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5740607380867004
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48012760281562805
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5053496360778809
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45543381571769714
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6147140860557556
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5934397578239441
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5738506317138672
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4890894591808319
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5277305245399475
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.48768049478530884
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.49882012605667114
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.491026371717453
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5383151173591614
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.6109616756439209
Calibrated prediction for NGG: 0.6614461541175842
Raw prediction for NVS: 0.4848731458187103
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5084639191627502
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.512130081653595
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4914626479148865
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4835987389087677
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49570924043655396
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4252372682094574
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49481964111328125
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5351254940032959
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5622689723968506
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4588032364845276
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5604994297027588
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5032123327255249
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5539528727531433
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49852076172828674
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.5082274675369263
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5393519401550293
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45108726620674133
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.531347930431366
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49570056796073914
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.48185867071151733
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4805729389190674
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.4910711944103241
Calibrated prediction for TSM: 0.4761904776096344
Raw prediction for UL: 0.41413775086402893
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3581423759460449
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4598586857318878
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  39%|███▊      | 34/88 [07:18<01:36,  1.79s/it]

Raw prediction for UPS: 0.538108766078949
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.48626816272735596
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5732982754707336
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.39033257961273193
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5010533332824707
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5116050839424133
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.48125138878822327
Calibrated prediction for XOM: 0.44186046719551086
Investing 2345.267610210457 in RDS-B
Investing 4129.553286213138 in IEP
Investing 1593.3395398462565 in PM
Investing 5624.249308128906 in MA
Investing 3003.0728027450045 in JNJ
Investing 9079.749354432135 in LMT
Investing 11437.369715434708 in AMZN
Investing 9628.777589892468 in GOOG
Investing 7920.115860209167 in NGG
Raw prediction for AAPL: 0.5214225053787231
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47460734844207764
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5014927387237549
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.551233172416687
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5056360960006714
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4825914800167084
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6602296829223633
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.32708388566970825
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4699587821960449
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3895776867866516
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5078123807907104
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4696565568447113
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5135050415992737
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5529875159263611
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5135762095451355
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.480464369058609
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5506128072738647
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.45288747549057007
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43768373131752014
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5284877419471741
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.5369215607643127
Calibrated prediction for CHL: 0.5351690649986267
Raw prediction for CHTR: 0.6203640699386597
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5525228977203369
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4539031684398651
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46404191851615906
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.49816781282424927
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5089847445487976
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5421575903892517
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48968490958213806
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4988037347793579
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.49962911009788513
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5401424765586853
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5353207588195801
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.49363672733306885
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4535342752933502
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6612049341201782
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4868556261062622
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5147963166236877
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.496038019657135
Calibrated prediction for HRG: 0.4944938123226166
Raw prediction for HSBC: 0.4440774917602539
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5425838828086853
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.558316171169281
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4791279137134552
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5054898858070374
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45933371782302856
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6384860873222351
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.6007735133171082
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5746976137161255
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4913957417011261
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5268364548683167
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4933305084705353
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.49976491928100586
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.5027078986167908
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5401115417480469
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.5926235914230347
Calibrated prediction for NGG: 0.6597396731376648
Raw prediction for NVS: 0.485144704580307
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5125414133071899
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5143099427223206
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49212390184402466
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48424237966537476
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49497923254966736
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4242416322231293
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49538758397102356
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.534803569316864
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5663279294967651
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4590960144996643
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5480257868766785
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5029827356338501
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5438772439956665
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4985147714614868
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.5084339380264282
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5393234491348267
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4509131908416748
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5346729755401611
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4957432150840759
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4850867986679077
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4804098904132843
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.49907705187797546
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.4206276834011078
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3684084415435791
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4663196802139282
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5361499786376953
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.48663130402565
Calibrated prediction for UTX: 0.4891962707042694

Simulating Trading Days:  40%|███▉      | 35/88 [07:19<01:29,  1.69s/it]

Raw prediction for V: 0.5748072862625122
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.40271130204200745
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.5004934668540955
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5120365619659424
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.48542386293411255
Calibrated prediction for XOM: 0.44186046719551086
Investing 2351.3029292362435 in RDS-B
Investing 4140.180291595285 in IEP
Investing 1597.4398448167879 in PM
Investing 5638.722768943074 in MA
Investing 3010.8009197169536 in JNJ
Investing 9103.115209906198 in LMT
Investing 11466.8026785422 in AMZN
Investing 9653.5563163501 in GOOG
Investing 7853.268449529142 in NGG
Raw prediction for AAPL: 0.5217629075050354
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4748656451702118
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5015565752983093
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.54555344581604
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5062599182128906
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48265647888183594
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.645018458366394
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.320242702960968
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4695856273174286
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3881460130214691
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5080117583274841
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4690482020378113
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.513757050037384
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5602622032165527
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5115455389022827
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4802182912826538
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5512393116950989
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.44152846932411194
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43466439843177795
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5280238389968872
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.533913254737854
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6274386048316956
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5537834763526917
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4510548412799835
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46275705099105835
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48760759830474854
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5220551490783691
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5482234358787537
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.49230584502220154
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.49954086542129517
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4973489046096802
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5405448079109192
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5460518002510071
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4911454916000366
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4534098505973816
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.663682222366333
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4891035556793213
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5141298770904541
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.4970294237136841
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4437660872936249
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5463718175888062
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5441759824752808
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4791683554649353
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5050340890884399
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4655561149120331
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6573553085327148
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.6030935645103455
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5758336782455444
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4921794533729553
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5255623459815979
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5011991262435913
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.500640869140625
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.5075926184654236
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5409688353538513
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.574722409248352
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.4848047196865082
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5161153078079224
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5167854428291321
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49312251806259155
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48482465744018555
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4941113293170929
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.422214150428772
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49737149477005005
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5345749855041504
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5675598382949829
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.45909249782562256
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5401391386985779
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5032458305358887
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5359482765197754
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4959704577922821
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.5077992677688599
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5392663478851318
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45140981674194336
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5358359813690186
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49578049778938293
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4909413158893585
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.47880658507347107
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5036444664001465
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.42580002546310425
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3770517408847809
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.47173887491226196
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  41%|████      | 36/88 [07:21<01:25,  1.64s/it]

Raw prediction for UPS: 0.5273699760437012
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4863937199115753
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.575473427772522
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.41905173659324646
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49980807304382324
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.515794038772583
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5037155747413635
Calibrated prediction for XOM: 0.5454545617103577
Investing 2358.423778134186 in RDS-B
Investing 4152.718700789656 in IEP
Investing 1602.277642455303 in PM
Investing 5655.799468127926 in MA
Investing 3019.9190380778464 in JNJ
Investing 9130.683715479981 in LMT
Investing 11501.529539212144 in AMZN
Investing 9682.79181595407 in GOOG
Investing 6678.535126936407 in NGG
Raw prediction for AAPL: 0.5222901105880737
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47462567687034607
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5015628337860107
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5422931909561157
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5065323114395142
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4826362431049347
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6332895755767822
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.3104405403137207
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46928897500038147
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3847741484642029
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5078868865966797
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4689812660217285
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5138635039329529
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5583672523498535
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5078554749488831
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.48009049892425537
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.551778256893158
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43044599890708923
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4329829812049866
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5277871489524841
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.5280066132545471
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6311051249504089
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5538170337677002
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4489702582359314
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46053752303123474
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48006144165992737
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5308358669281006
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5509936213493347
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4902048408985138
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.49303779006004333
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.49489927291870117
Calibrated prediction for EXC: 0.53125
Raw prediction for FB: 0.5408317446708679
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5517532229423523
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.48720020055770874
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4534730911254883
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6597668528556824
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4918198883533478
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5079231262207031
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49770718812942505
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4434800446033478
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5476129651069641
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5363047122955322
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47846320271492004
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5053375363349915
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46687206625938416
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6683400869369507
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.6034203171730042
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5813190340995789
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4939698576927185
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5251377820968628
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5073140859603882
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4996253550052643
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.5050554871559143
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.540505588054657
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.5521109700202942
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.48211443424224854
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5128868222236633
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5162509083747864
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4934270977973938
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48482707142829895
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49329954385757446
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42034733295440674
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4980296492576599
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5343794822692871
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5670018196105957
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4582642614841461
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.531544029712677
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5037463307380676
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5330195426940918
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49533990025520325
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.5018538236618042
Calibrated prediction for SNY: 0.5135135054588318
Raw prediction for SO: 0.5394182205200195
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45176810026168823
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5363237261772156
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49580979347229004
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.49746033549308777
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.47833898663520813
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5017457008361816
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.4312429130077362
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  42%|████▏     | 37/88 [07:23<01:21,  1.60s/it]

Raw prediction for UN: 0.3834105134010315
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4728318452835083
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5191810727119446
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4872736632823944
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5756329298019409
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.43166565895080566
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4994083642959595
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5210915803909302
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5075234770774841
Calibrated prediction for XOM: 0.5454545617103577
Investing 2356.586649446476 in RDS-B
Investing 4149.483879835108 in IEP
Investing 1601.0295248566244 in PM
Investing 5651.393800431066 in MA
Investing 3017.5666279847783 in JNJ
Investing 9123.57123588762 in LMT
Investing 11492.570254598017 in AMZN
Investing 9675.24926368372 in GOOG
Investing 6673.3327843433035 in NGG
Raw prediction for AAPL: 0.5226675868034363
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4741934835910797
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5015415549278259
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5387786626815796
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5070452094078064
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48262903094291687
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6387160420417786
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.30400344729423523
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4690573811531067
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3799658417701721
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.507869303226471
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46970847249031067
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5141659379005432
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5570514798164368
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5021857023239136
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.48005422949790955
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5530366897583008
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4205482304096222
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43202969431877136
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5275788307189941
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.5228822231292725
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6353325843811035
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5536304116249084
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.44805607199668884
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4569759666919708
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47400912642478943
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5400232672691345
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5512857437133789
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4883089065551758
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.48600348830223083
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.49319326877593994
Calibrated prediction for EXC: 0.48846083879470825
Raw prediction for FB: 0.5408467054367065
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5519900321960449
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.48648127913475037
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4535559415817261
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6575864553451538
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4933444559574127
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5037806630134583
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4982546269893646
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4434381425380707
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5486810207366943
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5315026044845581
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47589191794395447
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5055952668190002
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46706387400627136
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6735990047454834
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.6022486090660095
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.586861252784729
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4958997964859009
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5250198245048523
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5084089636802673
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4957725405693054
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.5034276247024536
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5399360060691833
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.533588171005249
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.47994497418403625
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5104626417160034
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5151911377906799
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49358928203582764
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48458465933799744
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49254634976387024
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4197796583175659
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4980967044830322
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5343541502952576
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5656546950340271
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4567736089229584
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5221258401870728
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5043267607688904
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5303035378456116
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49647367000579834
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.49372413754463196
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5395005345344543
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45373058319091797
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5361519455909729
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49598580598831177
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.5045533180236816
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.47809985280036926
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.4997223913669586
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.43562859296798706
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3865775465965271
Calibrated prediction for UN: 0.39393940567970276

Simulating Trading Days:  43%|████▎     | 38/88 [07:24<01:17,  1.56s/it]

Raw prediction for UNH: 0.47018152475357056
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5186069011688232
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4889102578163147
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.574963390827179
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.44722414016723633
Calibrated prediction for VZ: 0.40194517374038696
Raw prediction for WFC: 0.49912309646606445
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5247718691825867
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5124515891075134
Calibrated prediction for XOM: 0.5454545617103577
Investing 2361.3506725677944 in RDS-B
Investing 4157.872384093892 in IEP
Investing 1604.2661305108754 in PM
Investing 5662.818532358176 in MA
Investing 3023.6668735196563 in JNJ
Investing 9142.015244439981 in LMT
Investing 11515.803378841143 in AMZN
Investing 9694.80853225869 in GOOG
Investing 6686.823445375579 in NGG
Raw prediction for AAPL: 0.5230705738067627
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4738314747810364
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5018588900566101
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5315150022506714
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.508407711982727
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.482182115316391
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6449340581893921
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.29875388741493225
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46889349818229675
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.37449324131011963
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5077746510505676
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4710640013217926
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5145823359489441
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5475596189498901
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4937101900577545
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4801430404186249
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.553783118724823
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4127303957939148
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4319489300251007
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.527068018913269
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.5166413187980652
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6399826407432556
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5540464520454407
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.44874316453933716
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4540961980819702
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4733045697212219
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5495774745941162
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5480313897132874
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4851018786430359
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.48196741938591003
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.49246734380722046
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5407623648643494
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.54811692237854
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.486206591129303
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.45358577370643616
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6529378294944763
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4960712194442749
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.502989649772644
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4987718164920807
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44354721903800964
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5476751923561096
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5282390117645264
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47368955612182617
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5052359104156494
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46624383330345154
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6802449822425842
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5999799966812134
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5912030339241028
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5047256946563721
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5253631472587585
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5070053935050964
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4877876937389374
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.49859312176704407
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5402491688728333
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.5290376543998718
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.47529736161231995
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5069193243980408
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.514011800289154
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4935811460018158
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4843814969062805
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4916900098323822
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4201269745826721
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49832382798194885
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5345743298530579
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5639950037002563
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4555909335613251
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5162590146064758
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5053859353065491
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5302251577377319
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4993551969528198
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48391106724739075
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5396884083747864
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4536541700363159
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5370180010795593
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4962381422519684
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.5103928446769714
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.4784446954727173
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.49630823731422424
Calibrated prediction for TSM: 0.4761904776096344
Raw prediction for UL: 0.4390218257904053
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.38753238320350647
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4588073492050171
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5182738304138184
Calibrated prediction for UPS: 0.4920634925365448

Simulating Trading Days:  44%|████▍     | 39/88 [07:25<01:15,  1.53s/it]

Raw prediction for UTX: 0.4905131161212921
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.57373046875
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.46577128767967224
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49900591373443604
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5330721139907837
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5154547691345215
Calibrated prediction for XOM: 0.5454545617103577
Investing 2358.621037073448 in RDS-B
Investing 4153.066034841139 in IEP
Investing 1602.4116572117198 in PM
Investing 5656.272520093441 in MA
Investing 3020.1716245856796 in JNJ
Investing 9131.44740731567 in LMT
Investing 11502.491528968962 in AMZN
Investing 9683.601686198945 in GOOG
Investing 6679.093720674809 in NGG
Raw prediction for AAPL: 0.5234655737876892
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47344905138015747
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5019805431365967
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5354048609733582
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5091197490692139
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.481538861989975
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.653753936290741
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.2952508330345154
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4688219130039215
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.36947619915008545
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5075082182884216
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4725418984889984
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.515036404132843
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5304275751113892
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.48194053769111633
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48028379678726196
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5542892217636108
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4064929485321045
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43161913752555847
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5267879962921143
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.5127511620521545
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6436848044395447
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5552288293838501
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.4507657289505005
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4531933069229126
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47343578934669495
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.555625855922699
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5422985553741455
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48231691122055054
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.485045850276947
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4919823408126831
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.540716290473938
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5415149927139282
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4821743071079254
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4535810649394989
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6491333842277527
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.49707135558128357
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5089024305343628
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49937450885772705
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44379323720932007
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5464722514152527
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5230216979980469
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4713664948940277
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5045032501220703
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46574926376342773
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6753420829772949
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5969738364219666
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5951969623565674
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5121623873710632
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5256593823432922
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5036574602127075
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4789979159832001
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.49107667803764343
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5410436987876892
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.5311050415039062
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.4720873534679413
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5078989863395691
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5118946433067322
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4931621849536896
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4845735728740692
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49083662033081055
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4214806854724884
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49818283319473267
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5348746180534363
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5635638236999512
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4540400505065918
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5188273787498474
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5065218806266785
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5340315103530884
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5033729076385498
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.47332867980003357
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5400461554527283
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.453554630279541
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5390341281890869
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.496514230966568
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.5109626054763794
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.4815123677253723
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.4931398034095764
Calibrated prediction for TSM: 0.4761904776096344
Raw prediction for UL: 0.44130444526672363
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3873567283153534
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4433234930038452
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5240857005119324
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.490988552570343
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5721560716629028
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.48031118512153625
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49909207224845886
Calibrated prediction for WFC: 0.4878625273704529

Simulating Trading Days:  45%|████▌     | 40/88 [07:27<01:14,  1.56s/it]

Raw prediction for WMT: 0.5404497981071472
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.5121303796768188
Calibrated prediction for XOM: 0.5454545617103577
Investing 2361.435334820255 in RDS-B
Investing 4158.021457607441 in IEP
Investing 1604.3236487718154 in PM
Investing 5663.02156318193 in MA
Investing 3023.775282004333 in JNJ
Investing 9142.343016003779 in LMT
Investing 11516.216258581655 in AMZN
Investing 9695.156123295063 in GOOG
Investing 6687.06319017133 in NGG
Raw prediction for AAPL: 0.5239978432655334
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4733107089996338
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5020135045051575
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5446888208389282
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5096237659454346
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4814999997615814
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6573978066444397
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.2891845405101776
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46871963143348694
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.364688515663147
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5072231292724609
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4735156297683716
Calibrated prediction for BCH: 0.4736842215061188
Raw prediction for BHP: 0.5153922438621521
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5184902548789978
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.4678697884082794
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4805430769920349
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5540685653686523
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4024619460105896
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4312377870082855
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5268458127975464
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.5058304667472839
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.649328351020813
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5565758943557739
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.452693909406662
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.451934814453125
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47719162702560425
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5605073571205139
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5351802706718445
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48179545998573303
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.49416714906692505
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.49154022336006165
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.540540874004364
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5345585346221924
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4757920503616333
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534751772880554
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6455954313278198
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5007863640785217
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5174412131309509
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.500074028968811
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4439452290534973
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5452619194984436
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5195945501327515
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.46898022294044495
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5037925839424133
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46646177768707275
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6644412279129028
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5935357809066772
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5979620218276978
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5115038156509399
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5254300832748413
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5010240077972412
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.47261664271354675
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4851987957954407
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5420401096343994
Calibrated prediction for NEE: 0.5559631586074829
Raw prediction for NGG: 0.537828266620636
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.4794202446937561
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5012727379798889
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5101930499076843
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49278348684310913
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4848368167877197
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49023139476776123
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42233091592788696
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4983542561531067
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5350527763366699
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5642099380493164
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4530320465564728
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5309543013572693
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5073868632316589
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5426912307739258
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5057559013366699
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4639383852481842
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5404981374740601
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45254623889923096
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5412076711654663
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4966191053390503
Calibrated prediction for T: 0.4953271150588989

Simulating Trading Days:  47%|████▋     | 41/88 [07:29<01:11,  1.53s/it]

Raw prediction for TM: 0.5058348774909973
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.48504191637039185
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.4887617528438568
Calibrated prediction for TSM: 0.4761904776096344
Raw prediction for UL: 0.4431499242782593
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.38749438524246216
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4329267740249634
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5272347927093506
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.49087828397750854
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5707228779792786
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.49193862080574036
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4991621673107147
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5479207038879395
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.5075297951698303
Calibrated prediction for XOM: 0.5454545617103577
Investing 2355.00101111618 in RDS-B
Investing 4146.691883753676 in IEP
Investing 1599.9522660241753 in PM
Investing 5647.5912385215925 in MA
Investing 3015.536246750684 in JNJ
Investing 9117.43240612543 in LMT
Investing 11484.837434795449 in AMZN
Investing 9668.739235252868 in GOOG
Investing 6668.842606884241 in NGG
Raw prediction for AAPL: 0.5243473649024963
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4728579521179199
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5021886229515076
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5498542189598083
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5095574855804443
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48057326674461365
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6536627411842346
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.286660373210907
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4686749279499054
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.362130343914032
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5069517493247986
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47446197271347046
Calibrated prediction for BCH: 0.4736842215061188
Raw prediction for BHP: 0.5155490040779114
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5127620697021484
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.45184123516082764
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4806787669658661
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5542265772819519
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4011446535587311
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43198052048683167
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5269317030906677
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.5010356903076172
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6499847173690796
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5578405857086182
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.45280081033706665
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.45174458622932434
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4836832582950592
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5656833052635193
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5300980806350708
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4831116795539856
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5064319968223572
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.48948729038238525
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5402790307998657
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5276198983192444
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.47065412998199463
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534689486026764
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6475547552108765
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5014981627464294
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5277385115623474
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5006826519966125
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44394367933273315
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5463274717330933
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5185185074806213
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.4670450985431671
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5030726194381714
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4660848379135132
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6463978886604309
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5898032784461975
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6007679104804993
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.510768473148346
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5248691439628601
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5002977848052979
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.469099760055542
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4829372763633728
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5420095324516296
Calibrated prediction for NEE: 0.5557547211647034
Raw prediction for NGG: 0.5290684103965759
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.49098142981529236
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.49608296155929565
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5087845921516418
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4922778308391571
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4851333796977997
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49000319838523865
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.422793984413147
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49859222769737244
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5348941087722778
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5646477341651917
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4520101249217987
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5435525178909302
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5079582333564758
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5548487901687622
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5068494081497192
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4527077078819275
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5409581661224365
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45178642868995667
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5420161485671997
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49669450521469116
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4955589473247528
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.48827990889549255
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.49204301834106445
Calibrated prediction for TSM: 0.4761904776096344
Raw prediction for UL: 0.44389915466308594
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3876914083957672
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.42523816227912903
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.531609833240509
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.49112796783447266
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5686628818511963
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.4991191625595093
Calibrated prediction for VZ: 0.5337837934494019

Simulating Trading Days:  48%|████▊     | 42/88 [07:30<01:10,  1.54s/it]

Raw prediction for WFC: 0.49920791387557983
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5523644089698792
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.5011723041534424
Calibrated prediction for XOM: 0.5454545617103577
Investing 2343.058348168311 in RDS-B
Investing 4125.663211883654 in IEP
Investing 1591.8386004437307 in PM
Investing 5618.951217430037 in MA
Investing 3000.2438826149437 in JNJ
Investing 9071.196153290564 in LMT
Investing 11426.595615854649 in AMZN
Investing 9619.707199482009 in GOOG
Investing 6635.023623737114 in NGG
Raw prediction for AAPL: 0.5244312882423401
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47233015298843384
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5028330683708191
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.555987536907196
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5094223618507385
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4800296425819397
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6554884314537048
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.2898205518722534
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.468671977519989
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3617328405380249
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5070744156837463
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47502967715263367
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5157830715179443
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5152319073677063
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.44175538420677185
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.480765163898468
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5558950304985046
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4028284549713135
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4334462881088257
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5269472002983093
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.4979388117790222
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6508955955505371
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5583224892616272
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.45103758573532104
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.45311683416366577
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4858882427215576
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5733570456504822
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5282605886459351
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48725900053977966
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5166682004928589
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.48632892966270447
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5401329398155212
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5242387056350708
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4658093750476837
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534873962402344
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6545348763465881
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5016847848892212
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5383630394935608
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5013140439987183
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4438928961753845
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5456286072731018
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.518186628818512
Calibrated prediction for INTC: 0.5
Raw prediction for JNJ: 0.4632266163825989
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5029102563858032
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46691229939460754
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6290057301521301
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5875056385993958
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6019733548164368
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5115222334861755
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5239707231521606
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.501230001449585
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.46856287121772766
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4854206144809723
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5416980981826782
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.5275738835334778
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.49753859639167786
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.49349886178970337
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5080050230026245
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4919417202472687
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48578736186027527
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.490199476480484
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4236709177494049
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4987199306488037
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5347403883934021
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5645350217819214
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4516296088695526
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5488397479057312
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5080872178077698
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5674316883087158
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5040501356124878
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.44267430901527405
Calibrated prediction for SNY: 0.4166666567325592
Raw prediction for SO: 0.5415617823600769
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4514380693435669
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5425748229026794
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49691954255104065
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4854609966278076
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4886956810951233
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5041717290878296
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.44489145278930664
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  49%|████▉     | 43/88 [07:32<01:09,  1.55s/it]

Raw prediction for UN: 0.386243999004364
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4226146340370178
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5352907776832581
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.49233555793762207
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5667527914047241
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5021706819534302
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4991820156574249
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5546764731407166
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.4999176859855652
Calibrated prediction for XOM: 0.5454545617103577
Investing 2351.592568331474 in RDS-B
Investing 4140.690288864815 in IEP
Investing 1597.6366212617047 in PM
Investing 5639.417360244238 in MA
Investing 3011.1717973454643 in JNJ
Investing 9104.236553319839 in LMT
Investing 11468.215186608133 in AMZN
Investing 9654.745464410289 in GOOG
Investing 6659.190649896332 in NGG
Raw prediction for AAPL: 0.5249974727630615
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47212880849838257
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5041690468788147
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5621209144592285
Calibrated prediction for AEP: 0.6000000238418579
Raw prediction for AGFS: 0.5105315446853638
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.47962287068367004
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.648147463798523
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.29369401931762695
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46859732270240784
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.36048832535743713
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5074235200881958
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47531530261039734
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5159164667129517
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.515192985534668
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.4356434941291809
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.48083505034446716
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5574326515197754
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4068545997142792
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4352225959300995
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5269851088523865
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.495037704706192
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6454232335090637
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5587120652198792
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.44693276286125183
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4538882374763489
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47948306798934937
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5805843472480774
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5274950265884399
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4902564287185669
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5236018896102905
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.48238158226013184
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5401851534843445
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5250899195671082
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4613634943962097
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45342835783958435
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6587199568748474
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5021451711654663
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5416770577430725
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5016032457351685
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44366520643234253
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.544335126876831
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5221765041351318
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4575612246990204
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5034632086753845
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46736249327659607
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6244812607765198
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5816904306411743
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.601963460445404
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5160676836967468
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5254865288734436
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5028035640716553
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.46965324878692627
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4871045649051666
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5421014428138733
Calibrated prediction for NEE: 0.556381344795227
Raw prediction for NGG: 0.528653621673584
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.49883756041526794
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.49138200283050537
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5070870518684387
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.491523414850235
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4863150715827942
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49059295654296875
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4244368076324463
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49908459186553955
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5343769788742065
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5635029077529907
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4500746428966522
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5455722808837891
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5078935623168945
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5834767818450928
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4996337592601776
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4349246025085449
Calibrated prediction for SNY: 0.4166666567325592
Raw prediction for SO: 0.5421035289764404
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4508436620235443
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.542833149433136
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49682381749153137
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.47471189498901367
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.48598790168762207
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5162312984466553
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44749969244003296
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  50%|█████     | 44/88 [07:33<01:07,  1.53s/it]

Raw prediction for UN: 0.3813832998275757
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4197995662689209
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5336832404136658
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.49324384331703186
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5654923319816589
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5046299695968628
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4989432394504547
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5577822923660278
Calibrated prediction for WMT: 0.5714285969734192
Raw prediction for XOM: 0.4986794888973236
Calibrated prediction for XOM: 0.5454545617103577
Investing 2339.7934586337115 in RDS-B
Investing 4119.914385929621 in IEP
Investing 1589.620483600237 in PM
Investing 5611.121598061166 in MA
Investing 2996.063250552898 in JNJ
Investing 9058.556069696258 in LMT
Investing 11410.673446237544 in AMZN
Investing 9606.302803733155 in GOOG
Investing 6625.778177840345 in NGG
Raw prediction for AAPL: 0.5252214074134827
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47214800119400024
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5058189034461975
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5669310092926025
Calibrated prediction for AEP: 0.6204460263252258
Raw prediction for AGFS: 0.5111487507820129
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.47980284690856934
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.646306037902832
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.30546194314956665
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4684825837612152
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.36042240262031555
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5076671242713928
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47558915615081787
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5144616961479187
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5142052173614502
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.43426352739334106
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4813259243965149
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5606659650802612
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4156593382358551
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43769049644470215
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5274167060852051
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.49498599767684937
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6380783915519714
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5581461787223816
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.44261783361434937
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.45734602212905884
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4771813750267029
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5878233909606934
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5299178957939148
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.49483591318130493
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.529129147529602
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.47961491346359253
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5402387976646423
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5281237363815308
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45988768339157104
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45342689752578735
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6674202084541321
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5002338886260986
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5480343103408813
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5018435120582581
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4434144198894501
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5432383418083191
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5289979577064514
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.44893041253089905
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5058272480964661
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4697364568710327
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6188209652900696
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5811775326728821
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5997816324234009
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5205410718917847
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5296875238418579
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5047751665115356
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4751428961753845
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4934654235839844
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.544208824634552
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.538672149181366
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.49741607904434204
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.4965064823627472
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5072894096374512
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49130162596702576
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4876987636089325
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49148666858673096
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42686182260513306
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.498867928981781
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5341536998748779
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5626250505447388
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4480534791946411
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5358670949935913
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5074396133422852
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.600386381149292
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49998676776885986
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.433154821395874
Calibrated prediction for SNY: 0.4166666567325592
Raw prediction for SO: 0.5422797203063965
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45053789019584656
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5425609946250916
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4968707263469696
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4692871868610382
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.48127833008766174
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5293023586273193
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4460417926311493
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  51%|█████     | 45/88 [07:35<01:05,  1.53s/it]

Raw prediction for UN: 0.3720398247241974
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.421455055475235
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5366103053092957
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4932655394077301
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5654704570770264
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.505055844783783
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4988758862018585
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5588165521621704
Calibrated prediction for WMT: 0.5714285969734192
Raw prediction for XOM: 0.5013934969902039
Calibrated prediction for XOM: 0.5454545617103577
Investing 2336.097343490159 in RDS-B
Investing 4113.406256805752 in IEP
Investing 1587.1093985639677 in PM
Investing 5602.257844966045 in MA
Investing 1797.4851482962674 in CELG
Investing 9044.246487735349 in LMT
Investing 11392.648281337992 in AMZN
Investing 9591.127959502604 in GOOG
Investing 6615.311596283512 in NGG
Raw prediction for AAPL: 0.5259590744972229
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.472596675157547
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5076940655708313
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5700335502624512
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.5118990540504456
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48011523485183716
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6471360325813293
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.31581971049308777
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46829137206077576
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3592361509799957
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5077778100967407
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47555556893348694
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5123168230056763
Calibrated prediction for BHP: 0.5218049883842468
Raw prediction for BP: 0.5134187936782837
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.43267616629600525
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4813554286956787
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5618268251419067
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42383429408073425
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43953636288642883
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5282106995582581
Calibrated prediction for CELG: 0.5251784324645996
Raw prediction for CHL: 0.49836066365242004
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.627182126045227
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5572625398635864
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.43778982758522034
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46189284324645996
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47626155614852905
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5971243381500244
Calibrated prediction for D: 0.6666666865348816
Raw prediction for DHR: 0.5292022824287415
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.49810704588890076
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.5290711522102356
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.4773927628993988
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5403068661689758
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5338842272758484
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4587545692920685
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534817934036255
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6738734245300293
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4968288838863373
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5478211641311646
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5018640160560608
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.444088876247406
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5425426363945007
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5400551557540894
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.44151803851127625
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.507621705532074
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4721219539642334
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6137363314628601
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5766398906707764
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5957192182540894
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5249367356300354
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5326393842697144
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5044801831245422
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4819604158401489
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.49781861901283264
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5466939210891724
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5452863574028015
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.49245312809944153
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.501859188079834
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5075927376747131
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49099358916282654
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48896560072898865
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.4926847517490387
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42774930596351624
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4992392957210541
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5334948301315308
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5630903244018555
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4445470869541168
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.521949052810669
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.50682133436203
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6147228479385376
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5003257989883423
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.43316641449928284
Calibrated prediction for SNY: 0.4166666567325592
Raw prediction for SO: 0.5421978831291199
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45030081272125244
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5425328612327576
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4967280328273773
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.46370935440063477
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4770699441432953
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5378599762916565
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4443269371986389
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3623538911342621
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.42434757947921753
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5398066639900208
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.4936794936656952
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5644596815109253
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5047812461853027
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49858909845352173
Calibrated prediction for WFC: 0.4878625273704529

Simulating Trading Days:  52%|█████▏    | 46/88 [07:36<01:04,  1.53s/it]

Raw prediction for WMT: 0.559196412563324
Calibrated prediction for WMT: 0.5714285969734192
Raw prediction for XOM: 0.4984705150127411
Calibrated prediction for XOM: 0.5454545617103577
Investing 2330.69660158663 in RDS-B
Investing 4103.896616465089 in IEP
Investing 1583.4402157457969 in PM
Investing 4658.336941501787 in V
Investing 1793.3296051257628 in CELG
Investing 9023.337409982973 in LMT
Investing 11366.310015453375 in AMZN
Investing 9568.954565565346 in GOOG
Investing 7820.260208055111 in D
Raw prediction for AAPL: 0.5264575481414795
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47310203313827515
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5093561410903931
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5743029713630676
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.5126180052757263
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4804612696170807
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.652160108089447
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.3267259895801544
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46805620193481445
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3610800802707672
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5079992413520813
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47521811723709106
Calibrated prediction for BCH: 0.48674941062927246
Raw prediction for BHP: 0.5098589658737183
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5121641755104065
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.43656525015830994
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.48127126693725586
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5621132254600525
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42700305581092834
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4408087432384491
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5294726490974426
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5030496716499329
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6257879734039307
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5575936436653137
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.43238571286201477
Calibrated prediction for CODI: 0.4444444477558136
Raw prediction for CSCO: 0.4702547788619995
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4768192768096924
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.6072164177894592
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5304315090179443
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5019136667251587
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.5298166275024414
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.47531402111053467
Calibrated prediction for EXC: 0.4714173972606659
Raw prediction for FB: 0.5405242443084717
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5406180024147034
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4540744125843048
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4536196291446686
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6802612543106079
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4916047751903534
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.546346127986908
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.501691460609436
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44514504075050354
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5405391454696655
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5502609610557556
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4353860914707184
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5087670087814331
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4740467369556427
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6136846542358398
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5787960290908813
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5889435410499573
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.532814085483551
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5332067608833313
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5035256147384644
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.48793426156044006
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.5025492310523987
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5482433438301086
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5474382042884827
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.484445720911026
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5101393461227417
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5061575174331665
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4908311069011688
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4901379346847534
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.4939539134502411
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4295048713684082
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.499846875667572
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5327967405319214
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5649658441543579
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4412616491317749
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5098091959953308
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5061069130897522
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6244452595710754
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4973686635494232
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.43432942032814026
Calibrated prediction for SNY: 0.4166666567325592
Raw prediction for SO: 0.5421046018600464
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4502456486225128
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.543296754360199
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4964640438556671
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.45696884393692017
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.47395074367523193
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5429210066795349
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44129469990730286
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.35730433464050293
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.42579492926597595
Calibrated prediction for UNH: 0.4444444477558136

Simulating Trading Days:  53%|█████▎    | 47/88 [07:38<01:03,  1.54s/it]

Raw prediction for UPS: 0.5455426573753357
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.49408331513404846
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5648400783538818
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.504813551902771
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49821528792381287
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5572426319122314
Calibrated prediction for WMT: 0.5714285969734192
Raw prediction for XOM: 0.4860953092575073
Calibrated prediction for XOM: 0.44186046719551086
Investing 2341.4663457262363 in RDS-B
Investing 4122.860009857707 in IEP
Investing 1590.7570179294598 in PM
Investing 4679.862307326706 in V
Investing 2514.710671293488 in CELG
Investing 9065.03268474533 in LMT
Investing 11418.83175963687 in AMZN
Investing 9613.171042426597 in GOOG
Investing 8684.184395547365 in D
Raw prediction for AAPL: 0.5268996953964233
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4734343886375427
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5107207298278809
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5780015587806702
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.5138263702392578
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48073938488960266
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6487511396408081
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.3314429223537445
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4676949381828308
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3631015121936798
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5086700320243835
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47400838136672974
Calibrated prediction for BCH: 0.4736842215061188
Raw prediction for BHP: 0.5085338950157166
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5203959345817566
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4466080069541931
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4810967445373535
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5632423162460327
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.427427738904953
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.44065675139427185
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5306611657142639
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5010201930999756
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6278693079948425
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5583962202072144
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.4304467737674713
Calibrated prediction for CODI: 0.4444444477558136
Raw prediction for CSCO: 0.4805346131324768
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4813131093978882
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.616294801235199
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5340471863746643
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5019495487213135
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.5297015309333801
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.47342371940612793
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5409339070320129
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5490235686302185
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4442311227321625
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45367664098739624
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6799131035804749
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.48925867676734924
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5431716442108154
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5013867020606995
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4460162818431854
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5365450978279114
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.563815712928772
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4313632845878601
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5102874040603638
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.47577759623527527
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6233575344085693
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5810171365737915
Calibrated prediction for MA: 0.6051159501075745
Raw prediction for MCD: 0.5819410085678101
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5405299067497253
Calibrated prediction for MDT: 0.53125
Raw prediction for MMM: 0.5309141278266907
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5042539238929749
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4915544092655182
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.501014769077301
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5498625040054321
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5481845140457153
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.475166916847229
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5161317586898804
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5056750774383545
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4907737970352173
Calibrated prediction for PCLN: 0.4987306296825409
Raw prediction for PEP: 0.4911594092845917
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.4951687455177307
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.429924339056015
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5006048679351807
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5321394801139832
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5666468143463135
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4409007728099823
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4975755214691162
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5054176449775696
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.627377986907959
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4952842891216278
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4407407343387604
Calibrated prediction for SNY: 0.4166666567325592
Raw prediction for SO: 0.5418932437896729
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45051348209381104
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.544066846370697
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4961245656013489
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.44670766592025757
Calibrated prediction for TM: 0.454740971326828
Raw prediction for TOT: 0.47146496176719666
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.549214243888855
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44004735350608826
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.35788923501968384
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.42185327410697937
Calibrated prediction for UNH: 0.4444444477558136

Simulating Trading Days:  55%|█████▍    | 48/88 [07:39<01:01,  1.53s/it]

Raw prediction for UPS: 0.5439512729644775
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.4939763844013214
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.566392183303833
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5076969265937805
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4978034794330597
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5557249188423157
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.482779860496521
Calibrated prediction for XOM: 0.44186046719551086
Investing 2338.335012725937 in RDS-B
Investing 4117.346350595405 in IEP
Investing 4496.164126168308 in BUD
Investing 5343.839446683474 in MA
Investing 2511.347651993382 in CELG
Investing 9052.90966788184 in LMT
Investing 11403.560916740034 in AMZN
Investing 9600.31497905519 in GOOG
Investing 8672.570701748991 in D
Raw prediction for AAPL: 0.5272250175476074
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47382012009620667
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5115126967430115
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5796687006950378
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.5154179930686951
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4812721908092499
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.646138072013855
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.3378037214279175
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4674045741558075
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3628706932067871
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5091678500175476
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47233957052230835
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5076640844345093
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5249560475349426
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.456590473651886
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48098206520080566
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5659327507019043
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.42309677600860596
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.439921498298645
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.531782865524292
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5004143118858337
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6310614943504333
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5585000514984131
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.43351173400878906
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4910183846950531
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48393338918685913
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.6266409754753113
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5410316586494446
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5007176995277405
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.5277365446090698
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.4725325107574463
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5411552786827087
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5542546510696411
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.43861815333366394
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45369449257850647
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6790554523468018
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.48733314871788025
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5433284044265747
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5011407136917114
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.446815550327301
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5310816168785095
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5798773765563965
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4290144145488739
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5111969113349915
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.47755375504493713
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6399993300437927
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5815142393112183
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5773794651031494
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5420098304748535
Calibrated prediction for MDT: 0.53125
Raw prediction for MMM: 0.5283830165863037
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5036323070526123
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4970179796218872
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.5009922981262207
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5511213541030884
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5484452843666077
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.4667505919933319
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5240236520767212
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5066995024681091
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4908190369606018
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4920809268951416
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.4963480830192566
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4304506182670593
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5004650354385376
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5314732789993286
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.568484902381897
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.44118037819862366
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.48617956042289734
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.504701554775238
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6266734600067139
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49599120020866394
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4530465006828308
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5416579842567444
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.450235515832901
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5447643399238586
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49599489569664
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.43403440713882446
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4713660776615143
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5542609691619873
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4395067095756531
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.36079758405685425
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4218025207519531
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5444986820220947
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.49355170130729675
Calibrated prediction for UTX: 0.4891962707042694

Simulating Trading Days:  56%|█████▌    | 49/88 [07:41<01:00,  1.56s/it]

Raw prediction for V: 0.5672595500946045
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.50977623462677
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49723440408706665
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5532341599464417
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.481961190700531
Calibrated prediction for XOM: 0.44186046719551086
Investing 2345.755035413276 in RDS-B
Investing 4130.411545773505 in IEP
Investing 4510.4313888319575 in BUD
Investing 5625.418215612122 in MA
Investing 2519.3166797213053 in CELG
Investing 9081.636430623937 in LMT
Investing 11439.746784144903 in AMZN
Investing 9630.778772550353 in GOOG
Investing 8700.090569951928 in D
Raw prediction for AAPL: 0.5276710391044617
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4742525815963745
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.51217120885849
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5782229900360107
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.5168753862380981
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4818534553050995
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6397696137428284
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.33852115273475647
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46713143587112427
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3612343370914459
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5089037418365479
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46998289227485657
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5067489147186279
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5272871255874634
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4632427990436554
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48086267709732056
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.566565215587616
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.41401901841163635
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43888503313064575
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5327365398406982
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5005970001220703
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6328794360160828
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5583150386810303
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.43790820240974426
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5010470151901245
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48359817266464233
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.6369478106498718
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5449668169021606
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4958239793777466
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.5271068215370178
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.47231951355934143
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5412752628326416
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5592110753059387
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4352838695049286
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4537328779697418
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6717668771743774
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.48842138051986694
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5387129783630371
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5009955167770386
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4474433958530426
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5277958512306213
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5970561504364014
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4274637997150421
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5112398266792297
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.47816088795661926
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.649330735206604
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5784255266189575
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5791981816291809
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.541744589805603
Calibrated prediction for MDT: 0.53125
Raw prediction for MMM: 0.5256569981575012
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5032917261123657
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.50077223777771
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4947478473186493
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5511326789855957
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5452471375465393
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.4633895754814148
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5269511342048645
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5072853565216064
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49058660864830017
Calibrated prediction for PCLN: 0.49298229813575745
Raw prediction for PEP: 0.49246230721473694
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.49737292528152466
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4299454092979431
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49989691376686096
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5305731296539307
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5701431035995483
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.43962401151657104
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4792744219303131
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5041628479957581
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6226068735122681
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5007720589637756
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4628295600414276
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5414703488349915
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4503507614135742
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5453439950942993
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49572452902793884
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4211020767688751
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4738909900188446
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5574871301651001
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4408796429634094
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.36669835448265076
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.4218105971813202
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.5422130227088928
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.49360746145248413
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5668608546257019
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5116471648216248
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49667027592658997
Calibrated prediction for WFC: 0.4878625273704529

Simulating Trading Days:  57%|█████▋    | 50/88 [07:42<00:57,  1.52s/it]

Raw prediction for WMT: 0.5529927015304565
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.48369500041007996
Calibrated prediction for XOM: 0.44186046719551086
Investing 3424.7469877891463 in BP
Investing 4138.943529071993 in IEP
Investing 4519.748359998636 in BUD
Investing 4698.118725240518 in V
Investing 2524.520705421112 in CELG
Investing 9100.395910034242 in LMT
Investing 11463.377293458467 in AMZN
Investing 9650.672587664953 in GOOG
Investing 8718.061909276243 in D
Raw prediction for AAPL: 0.5279123783111572
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47461557388305664
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5124666094779968
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5759866833686829
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.5179893374443054
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48271334171295166
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6363129615783691
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.33710622787475586
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46685975790023804
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3584292531013489
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5079233050346375
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4685320556163788
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5059610605239868
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5290360450744629
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4658588767051697
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48080572485923767
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5675687193870544
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.40377530455589294
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4381011426448822
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5337435603141785
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5032702088356018
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6317867040634155
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5566189289093018
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.43960750102996826
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5071125030517578
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4801992177963257
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.645811140537262
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5496652722358704
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48856908082962036
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5276853442192078
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.4724588990211487
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5412447452545166
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5610315203666687
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.43352705240249634
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.453753262758255
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6612358093261719
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.4924648106098175
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5328641533851624
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5008614659309387
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44789919257164
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5255597233772278
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6095694899559021
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.42670121788978577
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5109841227531433
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.47766485810279846
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6498699188232422
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5758768320083618
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.584661066532135
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5384632349014282
Calibrated prediction for MDT: 0.53125
Raw prediction for MMM: 0.5237246751785278
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5028572082519531
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5054606199264526
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4841606914997101
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5502176284790039
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5416093468666077
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.4646141231060028
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5251465439796448
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5084690451622009
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49004271626472473
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.49297335743904114
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.4983169734477997
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42964982986450195
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49896693229675293
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.529701292514801
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5713192820549011
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4363575875759125
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4755879044532776
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.503666341304779
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6160979270935059
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5048289895057678
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.46905332803726196
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5411795973777771
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45173919200897217
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5455033183097839
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49524256587028503
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.41217464208602905
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4765176475048065
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5578118562698364
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4429958164691925
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3728404641151428
Calibrated prediction for UN: 0.39393940567970276

Simulating Trading Days:  58%|█████▊    | 51/88 [07:44<00:59,  1.61s/it]

Raw prediction for UNH: 0.42971304059028625
Calibrated prediction for UNH: 0.4444444477558136
Raw prediction for UPS: 0.540364682674408
Calibrated prediction for UPS: 0.5230769515037537
Raw prediction for UTX: 0.49332907795906067
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5654838681221008
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5138001441955566
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.496414452791214
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5511868596076965
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.4829983413219452
Calibrated prediction for XOM: 0.44186046719551086
Investing 3426.4822106048205 in BP
Investing 4141.040615154568 in IEP
Investing 4522.038389160889 in BUD
Investing 4700.499129641734 in V
Investing 2525.7998089409652 in CELG
Investing 9105.006824262668 in LMT
Investing 11469.185463783228 in AMZN
Investing 9655.56231158337 in GOOG
Investing 8722.479105637718 in D
Raw prediction for AAPL: 0.5281721949577332
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4749414622783661
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5127206444740295
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5732663869857788
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.5185819864273071
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48365917801856995
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6292551755905151
Calibrated prediction for AMZN: 0.7142857313156128
Raw prediction for BA: 0.3314562737941742
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4667021930217743
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.35352030396461487
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5069602131843567
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46786078810691833
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.505329966545105
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5304203629493713
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.46561378240585327
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4807927906513214
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5696241855621338
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.39314335584640503
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43782106041908264
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5346030592918396
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5056233406066895
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6264040470123291
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.552451491355896
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.43809059262275696
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5115086436271667
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4778352975845337
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.6526724696159363
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5533580780029297
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4810551106929779
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5295260548591614
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.4727081060409546
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5409237146377563
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5605149269104004
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.42928972840309143
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45377853512763977
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6496776342391968
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.49723169207572937
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5257130265235901
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5006489753723145
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44828492403030396
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5240650177001953
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.621052622795105
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4263417720794678
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5101778507232666
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.47726595401763916
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6489636898040771
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5694354176521301
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5911638736724854
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5340602397918701
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5225149393081665
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5020731091499329
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5099266767501831
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.47039875388145447
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5488520860671997
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5381165742874146
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.4666000306606293
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5207977294921875
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5098313689231873
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4893239736557007
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4934530556201935
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.4991559386253357
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.43034473061561584
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49853670597076416
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5289140343666077
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5721948742866516
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4327741265296936
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4759136438369751
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5033251047134399
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6073756814002991
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5064998865127563
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.47238239645957947
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5409727096557617
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.454385906457901
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5448170900344849
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49471867084503174
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.40166500210762024
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4787876605987549
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5552770495414734
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44619515538215637
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3767735958099365
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.44050824642181396
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5384810566902161
Calibrated prediction for UPS: 0.5

Simulating Trading Days:  59%|█████▉    | 52/88 [07:46<00:58,  1.64s/it]

Raw prediction for UTX: 0.49290022253990173
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5631517171859741
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5159928202629089
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49618929624557495
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5483768582344055
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.48069795966148376
Calibrated prediction for XOM: 0.44186046719551086
Investing 3433.9068812058513 in BP
Investing 4150.013626138793 in IEP
Investing 4531.836964907415 in BUD
Investing 4710.684402919968 in V
Investing 2531.2728365047715 in CELG
Investing 9124.736001983498 in LMT
Investing 11362.774815428662 in AMZN
Investing 9676.48446007997 in GOOG
Investing 8741.379403436813 in D
Raw prediction for AAPL: 0.528578519821167
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4749358594417572
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5130964517593384
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5699610710144043
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.5185583233833313
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4844052195549011
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6174080967903137
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3215984106063843
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46667996048927307
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3490561246871948
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5062039494514465
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4674516022205353
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.504618227481842
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5316546559333801
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4638807475566864
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4808385968208313
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5704302191734314
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.3848065435886383
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43765807151794434
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5352331399917603
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5034044981002808
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6170358657836914
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5469087362289429
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4380187690258026
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5137645602226257
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.47861430048942566
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.6557070016860962
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5542877316474915
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4752463698387146
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5349283218383789
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.47287502884864807
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5404676795005798
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5585358738899231
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.42354726791381836
Calibrated prediction for GE: 0.4166666567325592
Raw prediction for GMRE: 0.4537859857082367
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6370904445648193
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5001839995384216
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5150374174118042
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.5003322958946228
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4486352205276489
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5236312747001648
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6294562220573425
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.42679160833358765
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5091667771339417
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4756409227848053
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6393449306488037
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5614245533943176
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.5958658456802368
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.531594455242157
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5214695334434509
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5010461211204529
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5101227164268494
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.45634666085243225
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5476760864257812
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5287759900093079
Calibrated prediction for NGG: 0.6363636255264282
Raw prediction for NVS: 0.47008001804351807
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5143142938613892
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5121702551841736
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48843857645988464
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.49324482679367065
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.4998224377632141
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4305172860622406
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4982268810272217
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5279961824417114
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5724988579750061
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.43045300245285034
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.47746893763542175
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5030810236930847
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5989362597465515
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5046699643135071
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.47149723768234253
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5408519506454468
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4572083353996277
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5428104400634766
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4940887987613678
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.38969314098358154
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.47990089654922485
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5507504343986511
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44906511902809143
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.37767720222473145
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.45058831572532654
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5370458364486694
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4928140640258789
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5602074265480042
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5171470642089844
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.4962529242038727
Calibrated prediction for WFC: 0.4878625273704529

Simulating Trading Days:  60%|██████    | 53/88 [07:47<00:57,  1.63s/it]

Raw prediction for WMT: 0.5451607704162598
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.47461217641830444
Calibrated prediction for XOM: 0.44186046719551086
Investing 3430.403676530619 in BP
Investing 4145.77986336062 in IEP
Investing 4527.213673422796 in BUD
Investing 4229.8865556079445 in MA
Investing 2528.690481437526 in CELG
Investing 9115.427124681857 in LMT
Investing 8878.611739005311 in CHTR
Investing 6243.676404813791 in TSM
Investing 8732.46161904327 in D
Raw prediction for AAPL: 0.5287017226219177
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47443753480911255
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5130158066749573
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5697030425071716
Calibrated prediction for AEP: 0.6296296119689941
Raw prediction for AGFS: 0.518354594707489
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4848038852214813
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6098312735557556
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3094583749771118
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4668980538845062
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.34431129693984985
Calibrated prediction for BAC: 0.3270092308521271
Raw prediction for BBL: 0.5055913925170898
Calibrated prediction for BBL: 0.5051909685134888
Raw prediction for BCH: 0.4671245515346527
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5040357708930969
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5311333537101746
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.46233949065208435
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48058849573135376
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5693010687828064
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.3788449764251709
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.438183069229126
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5355963706970215
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4994543194770813
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.609200656414032
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5406412482261658
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.44035542011260986
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5148547291755676
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48142194747924805
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.6572636961936951
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.552566647529602
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4730369448661804
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.537663996219635
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.4740389287471771
Calibrated prediction for EXC: 0.46486613154411316
Raw prediction for FB: 0.5399268269538879
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5530716180801392
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4190939962863922
Calibrated prediction for GE: 0.4166666567325592
Raw prediction for GMRE: 0.453812837600708
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6262183785438538
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5023479461669922
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.502321183681488
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5001396536827087
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4489723742008209
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5256420969963074
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6356963515281677
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.42817503213882446
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5084967017173767
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4736088216304779
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6269838809967041
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5486525893211365
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.5971332788467407
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5268276929855347
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5208901762962341
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5006791949272156
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5091792345046997
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.4414477050304413
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5468983054161072
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.5167329907417297
Calibrated prediction for NGG: 0.5714285969734192
Raw prediction for NVS: 0.4709712266921997
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5084921717643738
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5161053538322449
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4876818060874939
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.49299442768096924
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.5002688765525818
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.43087345361709595
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49805164337158203
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5272901654243469
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5720574855804443
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.42811137437820435
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4767489731311798
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5030753016471863
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5908092856407166
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5010243058204651
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.46966633200645447
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5406755805015564
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4596182107925415
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5398252606391907
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4935450851917267
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3812275230884552
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.478684663772583
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5434975028038025
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.45064935088157654
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3746933937072754
Calibrated prediction for UN: 0.39393940567970276
Raw prediction for UNH: 0.460122674703598
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  61%|██████▏   | 54/88 [07:49<00:54,  1.61s/it]

Raw prediction for UPS: 0.5367216467857361
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.493411660194397
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5569543242454529
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5148035287857056
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49611711502075195
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5429974794387817
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.46430572867393494
Calibrated prediction for XOM: 0.44186046719551086
Investing 3437.2726323114985 in BP
Investing 4154.08127078783 in IEP
Investing 4536.278854510983 in BUD
Investing 2960.0194980592496 in MA
Investing 2533.753868938933 in CELG
Investing 9133.679631310055 in LMT
Investing 8896.390052341456 in CHTR
Investing 6256.178588573739 in TSM
Investing 8749.947284981017 in D
Raw prediction for AAPL: 0.5289419889450073
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47375914454460144
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5125836730003357
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5652962923049927
Calibrated prediction for AEP: 0.6000000238418579
Raw prediction for AGFS: 0.5181663036346436
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.484519362449646
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5954919457435608
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.2937106490135193
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46749749779701233
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3403379023075104
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5051596164703369
Calibrated prediction for BBL: 0.5051909685134888
Raw prediction for BCH: 0.4669491946697235
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5038987994194031
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5407405495643616
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4623921811580658
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4805113673210144
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5648974180221558
Calibrated prediction for BUD: 0.5789473652839661
Raw prediction for C: 0.3748302459716797
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43865033984184265
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5356684923171997
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.49417844414711
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6016749739646912
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5354284048080444
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4418847858905792
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5138904452323914
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4867086112499237
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.648790180683136
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5464194416999817
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.47214606404304504
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5387963652610779
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.4733797311782837
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5393739938735962
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5459840893745422
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.42178037762641907
Calibrated prediction for GE: 0.4166666567325592
Raw prediction for GMRE: 0.4538223147392273
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6132379174232483
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5046866536140442
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.48782530426979065
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49979594349861145
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44921597838401794
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5284806489944458
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6411392092704773
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4299483597278595
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5075550079345703
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.47125527262687683
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6063806414604187
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5417105555534363
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.5965572595596313
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.521840512752533
Calibrated prediction for MDT: 0.5
Raw prediction for MMM: 0.5207054018974304
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5004653334617615
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5065667629241943
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4268086850643158
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.545739471912384
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.497965008020401
Calibrated prediction for NGG: 0.4615384638309479
Raw prediction for NVS: 0.46925118565559387
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5019592642784119
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5162911415100098
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4870668947696686
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4920792579650879
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.5004440546035767
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4302018880844116
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4980614483356476
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5265202522277832
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5718709230422974
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4270675778388977
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4694969952106476
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5031782984733582
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5809973478317261
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4966781437397003
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.46580252051353455
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5405553579330444
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.46024876832962036
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5358713269233704
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4928518235683441
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3708491623401642
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.47573021054267883
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5333462953567505
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.45091697573661804
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.36618927121162415
Calibrated prediction for UN: 0.39393940567970276

Simulating Trading Days:  62%|██████▎   | 55/88 [07:51<00:51,  1.57s/it]

Raw prediction for UNH: 0.46504467725753784
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5323560833930969
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.49407291412353516
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5549555420875549
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.5033243298530579
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.496122270822525
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5418701767921448
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.45620667934417725
Calibrated prediction for XOM: 0.43509554862976074
Investing 3436.348920901461 in BP
Investing 4152.964928653088 in IEP
Investing 4535.0598029589955 in BUD
Investing 2959.224040707805 in MA
Investing 2533.0729635789785 in CELG
Investing 9131.225102678325 in LMT
Investing 8893.999291445087 in CHTR
Investing 6254.49734179361 in TSM
Investing 8747.595878209151 in D
Raw prediction for AAPL: 0.5288580656051636
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4729461371898651
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5117878913879395
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5633032917976379
Calibrated prediction for AEP: 0.6000000238418579
Raw prediction for AGFS: 0.5176772475242615
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4834791123867035
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5789149403572083
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.2807369828224182
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4682326912879944
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.33978331089019775
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.5048116445541382
Calibrated prediction for BBL: 0.5051909685134888
Raw prediction for BCH: 0.46686458587646484
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.503562867641449
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5504841804504395
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.46253281831741333
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48040229082107544
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5624956488609314
Calibrated prediction for BUD: 0.5237770080566406
Raw prediction for C: 0.37550243735313416
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43885114789009094
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5353850722312927
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4883390963077545
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5959729552268982
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.5306556820869446
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4418261647224426
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5100947618484497
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.49162158370018005
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.6380137801170349
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5384461283683777
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4725591838359833
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.53830486536026
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.47162914276123047
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5388674139976501
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5352786183357239
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.43521812558174133
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45381131768226624
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.603843629360199
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5070116519927979
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.47679612040519714
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4992907643318176
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44934380054473877
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5333659052848816
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.645392894744873
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.43259790539741516
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5063994526863098
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4677778482437134
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5824662446975708
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5357499718666077
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.5941011905670166
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5187029838562012
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5202107429504395
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.49927446246147156
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5050660967826843
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4181153476238251
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5450089573860168
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.48876258730888367
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4672766327857971
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.49811941385269165
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5152255296707153
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4865417182445526
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.49088993668556213
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.5004818439483643
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4282397925853729
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49800682067871094
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5258689522743225
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.569698691368103
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.42495447397232056
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.460472047328949
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5032786726951599
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.568121075630188
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49937236309051514
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4631096422672272
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5403021574020386
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45988330245018005
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.530859112739563
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4921356737613678
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3654256761074066
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4729209244251251
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5260806679725647
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4497337341308594
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.35548707842826843
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.46890828013420105
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5285404324531555
Calibrated prediction for UPS: 0.5

Simulating Trading Days:  64%|██████▎   | 56/88 [07:52<00:49,  1.53s/it]

Raw prediction for UTX: 0.49421507120132446
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5532980561256409
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.48929187655448914
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49615901708602905
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5405118465423584
Calibrated prediction for WMT: 0.557692289352417
Raw prediction for XOM: 0.45621174573898315
Calibrated prediction for XOM: 0.43509554862976074
Investing 3437.3613349837938 in BP
Investing 4154.1884715103415 in IEP
Investing 1602.8447361919536 in PM
Investing 2960.0958846795766 in MA
Investing 2533.819255297001 in CELG
Investing 4819.207986723371 in DHR
Investing 6679.461494470811 in AMZN
Investing 6256.340036273275 in TSM
Investing 8750.173087176434 in D
Raw prediction for AAPL: 0.5286903977394104
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4721779525279999
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.511212170124054
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5561057329177856
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5171480178833008
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48186805844306946
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5627921223640442
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.2699798047542572
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46883416175842285
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3414386510848999
Calibrated prediction for BAC: 0.3218058943748474
Raw prediction for BBL: 0.504634439945221
Calibrated prediction for BBL: 0.5051909685134888
Raw prediction for BCH: 0.4668051600456238
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5033706426620483
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5582142472267151
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.46137693524360657
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48047834634780884
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5602380633354187
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.3802279829978943
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4387204647064209
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5349715352058411
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4814726710319519
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5907842516899109
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.5283082127571106
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4423351287841797
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5027868747711182
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4918445646762848
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.6225371956825256
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5304325819015503
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.47374171018600464
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5367489457130432
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.46779799461364746
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5385406613349915
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5238491296768188
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4523169994354248
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45375868678092957
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5957815051078796
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5107953548431396
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.4689269959926605
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49895957112312317
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44929608702659607
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5387895703315735
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6469107270240784
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4384293854236603
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5049362182617188
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4647841155529022
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.564411461353302
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5326889753341675
Calibrated prediction for MA: 0.5563225746154785
Raw prediction for MCD: 0.5898897647857666
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5162914991378784
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5193290710449219
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.49719732999801636
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5041088461875916
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.413610577583313
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5427789092063904
Calibrated prediction for NEE: 0.5605059862136841
Raw prediction for NGG: 0.48079967498779297
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.46603402495384216
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.49630919098854065
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.513053834438324
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48607733845710754
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4893641471862793
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.500315248966217
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.4240078926086426
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49734312295913696
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5253015160560608
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5664458870887756
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.42271530628204346
Calibrated prediction for PTR: 0.40268293023109436
Raw prediction for RDS-B: 0.4504045844078064
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5033589601516724
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5538017749786377
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5023431777954102
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.46229666471481323
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5401521921157837
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4580145478248596
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5256796479225159
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4914730191230774
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.36350318789482117
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.46936216950416565
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5195822715759277
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44720733165740967
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3445715010166168
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.469414085149765
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5238569378852844
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4939410090446472
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5543999075889587
Calibrated prediction for V: 0.5523256063461304

Simulating Trading Days:  65%|██████▍   | 57/88 [07:54<00:49,  1.59s/it]

Raw prediction for VZ: 0.4710354804992676
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.49618834257125854
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5386008024215698
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4608733355998993
Calibrated prediction for XOM: 0.44186046719551086
Investing 3442.8064399997793 in BP
Investing 4160.769098415449 in IEP
Investing 1605.383793643976 in PM
Investing 2932.4449910770813 in MA
Investing 2537.8330643185313 in CELG
Investing 4826.84206735217 in DHR
Investing 6690.042392358229 in AMZN
Investing 6266.250669806767 in TSM
Investing 8764.03418780697 in D
Raw prediction for AAPL: 0.5284994840621948
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47176653146743774
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.510982871055603
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5389305949211121
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5166653394699097
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4802384376525879
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5480453968048096
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.25912031531333923
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4693073630332947
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.34420153498649597
Calibrated prediction for BAC: 0.3246955871582031
Raw prediction for BBL: 0.5045925974845886
Calibrated prediction for BBL: 0.5051909685134888
Raw prediction for BCH: 0.46665364503860474
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5032798051834106
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5561758279800415
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4601634740829468
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4804726243019104
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5567914843559265
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.38607603311538696
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43770813941955566
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5342936515808105
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.47440823912620544
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5854699015617371
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.5267120003700256
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.44499269127845764
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4951271116733551
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.49144360423088074
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.6039814352989197
Calibrated prediction for D: 0.6826310157775879
Raw prediction for DHR: 0.5226624011993408
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4759732484817505
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.5315712690353394
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.462645560503006
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5382529497146606
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5123433470726013
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4641698896884918
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45363837480545044
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5905895233154297
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5139923095703125
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.46185195446014404
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4988846182823181
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44883522391319275
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5435060858726501
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.647294819355011
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4462370276451111
Calibrated prediction for JNJ: 0.407931387424469
Raw prediction for JPM: 0.5038096308708191
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.46169313788414
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5427104830741882
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5303066372871399
Calibrated prediction for MA: 0.5188352465629578
Raw prediction for MCD: 0.5853782296180725
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5167215466499329
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5176295638084412
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4959045946598053
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5024460554122925
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.41388705372810364
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5393536686897278
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.47916722297668457
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.46212145686149597
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.494128555059433
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5121973752975464
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48552945256233215
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4875752329826355
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49983155727386475
Calibrated prediction for PFE: 0.5071089863777161
Raw prediction for PG: 0.42209988832473755
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49649766087532043
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5252677798271179
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5597060322761536
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.42144614458084106
Calibrated prediction for PTR: 0.3971034586429596
Raw prediction for RDS-B: 0.4415372908115387
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5035251379013062
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5413486957550049
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5022462606430054
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4659586548805237
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5399125218391418
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4561699628829956
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5207642316818237
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4908384680747986
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3657773435115814
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4636729657649994
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5108913779258728
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44370007514953613
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.33440589904785156
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4666895866394043
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  66%|██████▌   | 58/88 [07:55<00:46,  1.56s/it]

Raw prediction for UPS: 0.5208647847175598
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.49234437942504883
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5552507042884827
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.45317962765693665
Calibrated prediction for VZ: 0.4166666567325592
Raw prediction for WFC: 0.49602779746055603
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5352992415428162
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.46906036138534546
Calibrated prediction for XOM: 0.44186046719551086
Investing 3437.8305820501455 in BP
Investing 4154.755575333117 in IEP
Investing 1603.0635465284233 in PM
Investing 3206.0366705747956 in V
Investing 2534.1651564509216 in CELG
Investing 4819.8658748502 in DHR
Investing 4648.710496520687 in MCD
Investing 6257.194112677242 in TSM
Investing 8751.36760606784 in D
Raw prediction for AAPL: 0.5280991792678833
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4719047546386719
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5106081366539001
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.5057412981987
Calibrated prediction for AEP: 0.5691056847572327
Raw prediction for AGFS: 0.5157735347747803
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.47895053029060364
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5425828099250793
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.2527455687522888
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4695287346839905
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.35148149728775024
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5049114227294922
Calibrated prediction for BBL: 0.5051909685134888
Raw prediction for BCH: 0.46722412109375
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5037314295768738
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5539829134941101
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.46060478687286377
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4804973900318146
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5536015629768372
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.3923942446708679
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43644267320632935
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5334453582763672
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4675523340702057
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5825472474098206
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5260378122329712
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.44920381903648376
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.48724856972694397
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4900650978088379
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5925715565681458
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.524095892906189
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4811558723449707
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.513410210609436
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.45944562554359436
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5379977226257324
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.49943119287490845
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.47344884276390076
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45361196994781494
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.587205708026886
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.5223203301429749
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.46218764781951904
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49888038635253906
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4479391276836395
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5498512387275696
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6483814716339111
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4570479691028595
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.503174901008606
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4585357904434204
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5429061055183411
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5303062200546265
Calibrated prediction for MA: 0.5188352465629578
Raw prediction for MCD: 0.580620288848877
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5151797533035278
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5153290033340454
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.49492478370666504
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5001930594444275
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.41590020060539246
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5357006192207336
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4779735505580902
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.458064466714859
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.4938018023967743
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5124527812004089
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48509481549263
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48571720719337463
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49908411502838135
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.420771062374115
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4958856999874115
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5257229804992676
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5501691699028015
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.421063631772995
Calibrated prediction for PTR: 0.3954218626022339
Raw prediction for RDS-B: 0.434347003698349
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5037912130355835
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5318150520324707
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49908554553985596
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.47211727499961853
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5396023988723755
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4542263150215149
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.516491711139679
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49027085304260254
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3717978298664093
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.45841172337532043
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5062648057937622
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.43932396173477173
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3252415060997009
Calibrated prediction for UN: 0.3459798991680145

Simulating Trading Days:  67%|██████▋   | 59/88 [07:57<00:44,  1.54s/it]

Raw prediction for UNH: 0.4582967758178711
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.519936203956604
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.49064645171165466
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5566648840904236
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.43296194076538086
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49602967500686646
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5303271412849426
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4780236780643463
Calibrated prediction for XOM: 0.44186046719551086
Investing 3438.107559243636 in BP
Investing 4155.090313334722 in IEP
Investing 1603.1927012472224 in PM
Investing 3206.294972727286 in V
Investing 3021.6437101280935 in JNJ
Investing 4820.254199082926 in DHR
Investing 4649.085031203518 in MCD
Investing 6257.698238759982 in TSM
Investing 2870.5851838782432 in AEP
Raw prediction for AAPL: 0.5277795195579529
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.472747266292572
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.509490430355072
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4633122682571411
Calibrated prediction for AEP: 0.5
Raw prediction for AGFS: 0.5152387619018555
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.47806453704833984
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.536688506603241
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.24684485793113708
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46959981322288513
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.35961294174194336
Calibrated prediction for BAC: 0.3684210479259491
Raw prediction for BBL: 0.5055909752845764
Calibrated prediction for BBL: 0.5051909685134888
Raw prediction for BCH: 0.46817436814308167
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5043849945068359
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5466117858886719
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.46453309059143066
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4805040955543518
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5508339405059814
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.3997962474822998
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43519553542137146
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5323529243469238
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4581444263458252
Calibrated prediction for CHL: 0.523809552192688
Raw prediction for CHTR: 0.5786128044128418
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5245931148529053
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4534788727760315
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4784347116947174
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48763561248779297
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5827221274375916
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5285728573799133
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48593801259994507
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4928359389305115
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4597596526145935
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5377699732780457
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.48794353008270264
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.47926193475723267
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4535636007785797
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.584915816783905
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.5289507508277893
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.4637599587440491
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.4988401532173157
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44706642627716064
Calibrated prediction for HSBC: 0.45389091968536377
Raw prediction for IEP: 0.5551459789276123
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.64936763048172
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.46681615710258484
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5022698640823364
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4555443525314331
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5570684671401978
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5303981900215149
Calibrated prediction for MA: 0.5188352465629578
Raw prediction for MCD: 0.5779341459274292
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5101636052131653
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5143888592720032
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4920524060726166
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.49931085109710693
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4209011197090149
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5324081182479858
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.478596955537796
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.46092358231544495
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.49422526359558105
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5130396485328674
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4846418797969818
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4836139976978302
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49824392795562744
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4205258786678314
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4953943192958832
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.52631676197052
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.538454532623291
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.41975557804107666
Calibrated prediction for PTR: 0.39499160647392273
Raw prediction for RDS-B: 0.42912256717681885
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5042146444320679
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.525543212890625
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.499809205532074
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4780721664428711
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5392410159111023
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45293867588043213
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5140621662139893
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.48979851603507996
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3797237277030945
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.453678697347641
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5043516755104065
Calibrated prediction for TSM: 0.5

Simulating Trading Days:  68%|██████▊   | 60/88 [07:58<00:43,  1.54s/it]

Raw prediction for UL: 0.435805082321167
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3168134093284607
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4501946270465851
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5192034840583801
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.48918870091438293
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5582794547080994
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.4125586450099945
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4960905909538269
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5257655382156372
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.48606258630752563
Calibrated prediction for XOM: 0.44186046719551086
Investing 3435.6324470024365 in BP
Investing 4152.099041328071 in IEP
Investing 1602.0385541440612 in PM
Investing 3203.9867436218424 in V
Investing 3019.468412466049 in JNJ
Investing 4816.78407199462 in DHR
Investing 4645.738129725649 in MCD
Investing 4517.946348382565 in INTC
Investing 2119.822408744223 in PPL
Raw prediction for AAPL: 0.527337908744812
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47413644194602966
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5080691576004028
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4337325692176819
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5148945450782776
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4773913025856018
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5342430472373962
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.24249720573425293
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4695184528827667
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.36871102452278137
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5065751671791077
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46958184242248535
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5051996111869812
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5307056903839111
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4698416292667389
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.48039481043815613
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5498191714286804
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4078204929828644
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4342512786388397
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5311073660850525
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4524971842765808
Calibrated prediction for CHL: 0.523809552192688
Raw prediction for CHTR: 0.5777434706687927
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5240655541419983
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45692354440689087
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4699752926826477
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48347240686416626
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5732685923576355
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5339155793190002
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48916783928871155
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.47629550099372864
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4588322639465332
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5376036167144775
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.4779360294342041
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4875950217247009
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.45355868339538574
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5833459496498108
Calibrated prediction for GOOG: 0.5066900849342346
Raw prediction for HD: 0.5351055860519409
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.4654625654220581
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49890586733818054
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44610679149627686
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5596418380737305
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6489009857177734
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.473659873008728
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.501430869102478
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4542355537414551
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.561356246471405
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5300613641738892
Calibrated prediction for MA: 0.5188352465629578
Raw prediction for MCD: 0.5751609206199646
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.504543125629425
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5161541104316711
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.48766830563545227
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.49910396337509155
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4301401674747467
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.530451774597168
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.48395320773124695
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.46107593178749084
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.49378132820129395
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5127596855163574
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48418188095092773
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48204556107521057
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49760740995407104
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4211715757846832
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49487918615341187
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5269289612770081
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5276035666465759
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4186120927333832
Calibrated prediction for PTR: 0.39499160647392273
Raw prediction for RDS-B: 0.42560991644859314
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5052902102470398
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5216780304908752
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5020652413368225
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4817934036254883
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.539077877998352
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45249488949775696
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5128777623176575
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4895215630531311
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.3917488157749176
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4491484463214874
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5017682909965515
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.4318646490573883
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  69%|██████▉   | 61/88 [08:00<00:41,  1.52s/it]

Raw prediction for UN: 0.3102095425128937
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4432954788208008
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5187546610832214
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.48852047324180603
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5594228506088257
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.3949681222438812
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49609678983688354
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5222267508506775
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4899899959564209
Calibrated prediction for XOM: 0.5454545617103577
Investing 3442.263273070433 in BP
Investing 4160.112659485671 in IEP
Investing 1605.1305144077448 in PM
Investing 3210.1704897439454 in V
Investing 3025.296035231208 in JNJ
Investing 4826.080542988296 in DHR
Investing 5646.975847602244 in HD
Investing 4526.666057746936 in INTC
Investing 1646.067636907226 in NEE
Raw prediction for AAPL: 0.5269985795021057
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47565755248069763
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5072655081748962
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.42776066064834595
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5148369073867798
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.47704315185546875
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5379050374031067
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.23828044533729553
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46926194429397583
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.37498265504837036
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5077551603317261
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.470682829618454
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5067802667617798
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5230712890625
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4772961139678955
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.480174720287323
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5497901439666748
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4154200255870819
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4358125627040863
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5301756262779236
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.45396727323532104
Calibrated prediction for CHL: 0.523809552192688
Raw prediction for CHTR: 0.578441321849823
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.524570107460022
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45951712131500244
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.46447160840034485
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48091113567352295
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5604601502418518
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5439250469207764
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.49053558707237244
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.46853262186050415
Calibrated prediction for DUK: 0.5
Raw prediction for EXC: 0.4625467360019684
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.537388026714325
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.4680923521518707
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.5021609663963318
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.453544020652771
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.5938639044761658
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5407465100288391
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.46723276376724243
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49894359707832336
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44521331787109375
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5625847578048706
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6481815576553345
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4766440987586975
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5017086267471313
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4538772404193878
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.605183482170105
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5296719670295715
Calibrated prediction for MA: 0.5188352465629578
Raw prediction for MCD: 0.5791162252426147
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4959724247455597
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5193694829940796
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.482932448387146
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5000200271606445
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4371476471424103
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5294647812843323
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.49087774753570557
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4577990770339966
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.4973444938659668
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.511354923248291
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48385390639305115
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48097842931747437
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4973328113555908
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4213901162147522
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4952060282230377
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5273516178131104
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5193653106689453
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.42042630910873413
Calibrated prediction for PTR: 0.39499160647392273
Raw prediction for RDS-B: 0.42268866300582886
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5061280131340027
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5223048329353333
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4996372163295746
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4840903580188751
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5389833450317383
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4514595568180084
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5130976438522339
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4893307089805603
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.40536120533943176
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.44929495453834534
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5020396709442139
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.4285244643688202
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.30559542775154114
Calibrated prediction for UN: 0.3459798991680145

Simulating Trading Days:  70%|███████   | 62/88 [08:01<00:38,  1.50s/it]

Raw prediction for UNH: 0.44018983840942383
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.516335666179657
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4885781407356262
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5610766410827637
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.38307812809944153
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49606266617774963
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5179836750030518
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4971790611743927
Calibrated prediction for XOM: 0.5454545617103577
Investing 3444.691124498181 in BP
Investing 4163.046814911533 in IEP
Investing 1606.2626237503432 in PM
Investing 3212.4346445713268 in V
Investing 3027.429796862969 in JNJ
Investing 9153.392391462854 in LMT
Investing 5650.958697630398 in HD
Investing 4529.858745748815 in INTC
Investing 1647.2286194775306 in NEE
Raw prediction for AAPL: 0.5267559885978699
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4778388440608978
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5075605511665344
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4302029311656952
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5150055885314941
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.47805875539779663
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5418861508369446
Calibrated prediction for AMZN: 0.523809552192688
Raw prediction for BA: 0.22957806289196014
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4690432548522949
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3800927400588989
Calibrated prediction for BAC: 0.4802528917789459
Raw prediction for BBL: 0.5085053443908691
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4716014564037323
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5082129240036011
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5162877440452576
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.48459991812705994
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4797149896621704
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5507969856262207
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42433348298072815
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43743255734443665
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5297743678092957
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4598194658756256
Calibrated prediction for CHL: 0.523809552192688
Raw prediction for CHTR: 0.5800992846488953
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5258079171180725
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4612025320529938
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4601224362850189
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.482021301984787
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5512102842330933
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5549050569534302
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4901178479194641
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.469173789024353
Calibrated prediction for DUK: 0.5
Raw prediction for EXC: 0.46580955386161804
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5372791886329651
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.46808773279190063
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.513420820236206
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.45351287722587585
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6082969903945923
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5441760420799255
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.4668017327785492
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.499104380607605
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4445912539958954
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5634879469871521
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6460272669792175
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.476521760225296
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5018625855445862
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4532161355018616
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6709172129631042
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5311554074287415
Calibrated prediction for MA: 0.5188352465629578
Raw prediction for MCD: 0.5865651369094849
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4887969493865967
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5241296291351318
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.48102498054504395
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5029370188713074
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.44056203961372375
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5291792750358582
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4934297800064087
Calibrated prediction for NGG: 0.4569407105445862
Raw prediction for NVS: 0.45496222376823425
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.4999157190322876
Calibrated prediction for ORCL: 0.474683552980423
Raw prediction for PCG: 0.5109255909919739
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48348769545555115
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4800606071949005
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4975029528141022
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4210892915725708
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4963705241680145
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5276054739952087
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5141849517822266
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4246864914894104
Calibrated prediction for PTR: 0.4113486111164093
Raw prediction for RDS-B: 0.4220729470252991
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5064379572868347
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5284143090248108
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.495914101600647
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4859466254711151
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5387992262840271
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4505891799926758
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.514434278011322
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4887748956680298
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.41764771938323975
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4511861801147461
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5018428564071655
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.4261535704135895
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3037371337413788
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.44213688373565674
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5156475901603699
Calibrated prediction for UPS: 0.4920634925365448

Simulating Trading Days:  72%|███████▏  | 63/88 [08:03<00:37,  1.48s/it]

Raw prediction for UTX: 0.48966559767723083
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5620675086975098
Calibrated prediction for V: 0.5523256063461304
Raw prediction for VZ: 0.3746376037597656
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4959776699542999
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5135351419448853
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.49933913350105286
Calibrated prediction for XOM: 0.5454545617103577
Investing 3097.3219238944666 in BP
Investing 4160.093151872179 in IEP
Investing 1605.1229876246398 in PM
Investing 3210.1554366022915 in V
Investing 3025.2818490034333 in JNJ
Investing 9146.898100624101 in LMT
Investing 5646.949367785169 in HD
Investing 4526.644831290084 in INTC
Investing 1646.059918161636 in NEE
Raw prediction for AAPL: 0.5260964632034302
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4792200028896332
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5088818073272705
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4275512993335724
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5168739557266235
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4802008867263794
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5676639080047607
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.22446036338806152
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4687226712703705
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.38399335741996765
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5087478756904602
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47204968333244324
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5090376734733582
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5149408578872681
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.4915752708911896
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.47925859689712524
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5526346564292908
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43153783679008484
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4375860095024109
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5299401879310608
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4641976058483124
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5790393352508545
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5284706354141235
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.46077677607536316
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4611522853374481
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.48663508892059326
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5491910576820374
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5616901516914368
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.49208059906959534
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.47280725836753845
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.46842044591903687
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5373478531837463
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.47637391090393066
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.518407940864563
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4532180726528168
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6277514696121216
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5482858419418335
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.4703652560710907
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.49955812096595764
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4444871246814728
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5541983246803284
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6468251347541809
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47499674558639526
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5015699863433838
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45147597789764404
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6901319622993469
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5380192399024963
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.5941495299339294
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.48224276304244995
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5292792916297913
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4854336380958557
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5009236931800842
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.43933287262916565
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.52939373254776
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4950198233127594
Calibrated prediction for NGG: 0.4615384638309479
Raw prediction for NVS: 0.45476529002189636
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5100570917129517
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5117104649543762
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4836030900478363
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.479288786649704
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4980182945728302
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4194783866405487
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49806299805641174
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5275338888168335
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5119298696517944
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.42813393473625183
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4218738377094269
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5061593055725098
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5352060794830322
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49429574608802795
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4888378381729126
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5386091470718384
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45020657777786255
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5165101885795593
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.48854249715805054
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.42664965987205505
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.45199111104011536
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5069810152053833
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4219990372657776
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3048958480358124
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.44934654235839844
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5133349895477295
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.49043142795562744
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5628036260604858
Calibrated prediction for V: 0.5828738808631897

Simulating Trading Days:  73%|███████▎  | 64/88 [08:04<00:35,  1.48s/it]

Raw prediction for VZ: 0.3595110774040222
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49592599272727966
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5108871459960938
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.49766409397125244
Calibrated prediction for XOM: 0.5454545617103577
Investing 3098.902738073584 in BP
Investing 4162.216384265362 in IEP
Investing 1605.942211857836 in PM
Investing 4724.535765242581 in V
Investing 3026.825895298988 in JNJ
Investing 9151.566503382259 in LMT
Investing 6692.369463017705 in AMZN
Investing 6268.430328353517 in TSM
Investing 1646.9000358252965 in NEE
Raw prediction for AAPL: 0.52485191822052
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47995394468307495
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5103803873062134
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4225226640701294
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.51642906665802
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4827061891555786
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6002644300460815
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.2213367074728012
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.468754380941391
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.388500839471817
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5092125535011292
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47226792573928833
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5092675089836121
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5232263803482056
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4975089728832245
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.479055792093277
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.55056232213974
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43283870816230774
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4361136555671692
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5310044884681702
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4679949879646301
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5728776454925537
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5302272439002991
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45967432856559753
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4628373682498932
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.49054154753685
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5474346280097961
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5674169063568115
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.49325400590896606
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.47322598099708557
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.46752601861953735
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5372207760810852
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.48934656381607056
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.5117352604866028
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4531745910644531
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6446101665496826
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5480976700782776
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.4772613048553467
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5001860857009888
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44442471861839294
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.545676589012146
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6490908265113831
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47267359495162964
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5011827349662781
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45091426372528076
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6898707747459412
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5487872362136841
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6008806824684143
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4817807972431183
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5327155590057373
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5041237473487854
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.49857813119888306
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.44816139340400696
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5288830399513245
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.49568498134613037
Calibrated prediction for NGG: 0.4615384638309479
Raw prediction for NVS: 0.45444709062576294
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5120427012443542
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.511127233505249
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48349839448928833
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4791243076324463
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49837273359298706
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4196113646030426
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.498856782913208
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5276010632514954
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.511003851890564
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4307757318019867
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.42315706610679626
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5055192112922668
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5413941144943237
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4929061532020569
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.49011194705963135
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5385110378265381
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4497412443161011
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.519141435623169
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4884156882762909
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4341290593147278
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.45299917459487915
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5112425684928894
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4187065362930298
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.30521252751350403
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4576531946659088
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  74%|███████▍  | 65/88 [08:06<00:34,  1.49s/it]

Raw prediction for UPS: 0.5153176188468933
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.49072888493537903
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5634337067604065
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.337119996547699
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4962402582168579
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5075005888938904
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5069557428359985
Calibrated prediction for XOM: 0.5454545617103577
Investing 3443.0094287120196 in BP
Investing 4161.014418382149 in IEP
Investing 1605.478447466258 in PM
Investing 4723.171412628598 in V
Investing 3025.951807763721 in JNJ
Investing 9148.92371173005 in LMT
Investing 6690.436838898784 in AMZN
Investing 9702.13473614676 in GOOG
Investing 1646.4244436231213 in NEE
Raw prediction for AAPL: 0.5240282416343689
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47996556758880615
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5116202235221863
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4131395220756531
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5155256390571594
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4849511981010437
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.650189995765686
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.21933840215206146
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4685664772987366
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3913259208202362
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5093688368797302
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47208210825920105
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5088755488395691
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.532709538936615
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5019140243530273
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.478831946849823
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5452214479446411
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43524977564811707
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4340062737464905
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5327942371368408
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4749757647514343
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5668985247612
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5325250029563904
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4580915868282318
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.467480331659317
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.49214375019073486
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5471448302268982
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5718585848808289
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4949490427970886
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.47010308504104614
Calibrated prediction for DUK: 0.5011563897132874
Raw prediction for EXC: 0.4656522572040558
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.537216305732727
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5028703212738037
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.49877437949180603
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4531659185886383
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6603707671165466
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5490178465843201
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.4898979663848877
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5010251998901367
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4443638324737549
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5386027693748474
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6523706912994385
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47065234184265137
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5013592839241028
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4508136510848999
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6812816858291626
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5620076060295105
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.6032257080078125
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.48530423641204834
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5340560078620911
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5102648735046387
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4957931637763977
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4604374170303345
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5284109115600586
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4944699704647064
Calibrated prediction for NGG: 0.4615384638309479
Raw prediction for NVS: 0.45549237728118896
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5153178572654724
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.510712742805481
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48352012038230896
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.47903522849082947
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49850529432296753
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4199804365634918
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4986398220062256
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5274168252944946
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5103964805603027
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4329984188079834
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.42530280351638794
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5048385262489319
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5473769903182983
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4939819574356079
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4906803369522095
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5385332703590393
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4491367042064667
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5211389064788818
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4884418547153473
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4286555051803589
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4543861448764801
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5186368823051453
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.41904354095458984
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3030426800251007
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4653123915195465
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.517823338508606
Calibrated prediction for UPS: 0.4920634925365448

Simulating Trading Days:  75%|███████▌  | 66/88 [08:07<00:32,  1.48s/it]

Raw prediction for UTX: 0.4904535710811615
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5644276142120361
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.3172643780708313
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4966554641723633
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5036972761154175
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5121389627456665
Calibrated prediction for XOM: 0.5454545617103577
Investing 3447.6668485604227 in BP
Investing 4166.643096299803 in IEP
Investing 1607.65020660379 in PM
Investing 4729.560530271187 in V
Investing 3030.0450663799375 in JNJ
Investing 9161.299622911474 in LMT
Investing 11540.095080924657 in AMZN
Investing 9715.258985681248 in GOOG
Investing 1648.6515911350277 in NEE
Raw prediction for AAPL: 0.5236233472824097
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47965744137763977
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5124155879020691
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4066777527332306
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5156574845314026
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4866209924221039
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6787404417991638
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.22051523625850677
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4684247076511383
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.39233869314193726
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5094904899597168
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4715898334980011
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5084259510040283
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5461094379425049
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5046135187149048
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.47837385535240173
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5414798259735107
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.43623459339141846
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.43197566270828247
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.53455650806427
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.4818485975265503
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5601987242698669
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5319091081619263
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45688241720199585
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.47266602516174316
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4861040413379669
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5499037504196167
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5763463377952576
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4935072064399719
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.46605929732322693
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.46567997336387634
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5376335978507996
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5155296325683594
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4894803762435913
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.45301005244255066
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6699345111846924
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5471125245094299
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.5031700134277344
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5015661716461182
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44434717297554016
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5275488495826721
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6545850038528442
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47021809220314026
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5021800994873047
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45037660002708435
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6765639781951904
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5733284950256348
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.6032936573028564
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.49024054408073425
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5333871841430664
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5106565356254578
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4930756986141205
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.47214341163635254
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5276566743850708
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.48864153027534485
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.45659783482551575
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5146136283874512
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5118699073791504
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4833618700504303
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4792899191379547
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49845850467681885
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42007946968078613
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49822402000427246
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5270204544067383
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5092477202415466
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.435312956571579
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4277231693267822
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5046762824058533
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5509788393974304
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4925716817378998
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4928251802921295
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5386577248573303
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4490619897842407
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5216208100318909
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.48870182037353516
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.415360689163208
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.45824873447418213
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5219364762306213
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4193843603134155
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.30340856313705444
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4692665934562683
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5207715630531311
Calibrated prediction for UPS: 0.4920634925365448

Simulating Trading Days:  76%|███████▌  | 67/88 [08:08<00:30,  1.47s/it]

Raw prediction for UTX: 0.4903184771537781
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5671176314353943
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.3021809160709381
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49675846099853516
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5005578398704529
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5173859596252441
Calibrated prediction for XOM: 0.5454545617103577
Investing 3449.570225046994 in BP
Investing 4168.943402810202 in IEP
Investing 1608.5377528013462 in PM
Investing 4732.171610372762 in V
Investing 3031.7178836171965 in JNJ
Investing 9166.357362842455 in LMT
Investing 11546.466098367655 in AMZN
Investing 9720.622553661146 in GOOG
Investing 1649.5617732410583 in NEE
Raw prediction for AAPL: 0.5230792760848999
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47916048765182495
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5128586292266846
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.40489301085472107
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5155633091926575
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48777759075164795
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6926390528678894
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.22429539263248444
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4680025577545166
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.39449456334114075
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5094493627548218
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47092732787132263
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5078943371772766
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5461136102676392
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5071836709976196
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4779936969280243
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5422543287277222
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4349803328514099
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4298001825809479
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5358995795249939
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.48923665285110474
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5556217432022095
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5315865278244019
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4564104676246643
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4800190329551697
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4788358807563782
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5539922118186951
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5786740779876709
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.49159008264541626
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4597450792789459
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4685209393501282
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.538363516330719
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5271669030189514
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.48247385025024414
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.45302265882492065
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6768741011619568
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5435570478439331
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.5117188692092896
Calibrated prediction for HON: 0.4855760931968689
Raw prediction for HRG: 0.5018526911735535
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44437164068222046
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5220649838447571
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6558681726455688
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4704769551753998
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5033043026924133
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45141592621803284
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6704264879226685
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.577347457408905
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.6017894744873047
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4950672686100006
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5313030481338501
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5135894417762756
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.4918130934238434
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.48224303126335144
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.526748776435852
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.48442938923835754
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.45724421739578247
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5151952505111694
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.51378333568573
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4833616614341736
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4801669120788574
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49836277961730957
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4194980263710022
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4979865849018097
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5267344117164612
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.507125198841095
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4370097815990448
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.43041297793388367
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.504867434501648
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5539745688438416
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49253079295158386
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.49541881680488586
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5386088490486145
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.44913750886917114
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5206960439682007
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.489338755607605
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.40744927525520325
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.46115177869796753
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5224980115890503
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4180145859718323
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3072091341018677
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4704113304615021
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5234212279319763
Calibrated prediction for UPS: 0.49342775344848633
Raw prediction for UTX: 0.49082696437835693
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5695114731788635
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.2957996129989624
Calibrated prediction for VZ: 0.374971479177475

Simulating Trading Days:  77%|███████▋  | 68/88 [08:10<00:29,  1.46s/it]

Raw prediction for WFC: 0.4969845414161682
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.4976580739021301
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5145854353904724
Calibrated prediction for XOM: 0.5454545617103577
Investing 3444.835084574645 in BP
Investing 4163.2207964141235 in IEP
Investing 1606.329752465743 in PM
Investing 4725.675874425229 in V
Investing 3027.5563188091446 in JNJ
Investing 9153.774928828601 in LMT
Investing 11530.61654744737 in AMZN
Investing 9707.27929340917 in GOOG
Investing 1647.2974602384127 in NEE
Raw prediction for AAPL: 0.5227875709533691
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47849592566490173
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5129520893096924
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.3998955488204956
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5161526203155518
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48855212330818176
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6949052214622498
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.23085938394069672
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46746817231178284
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.39860817790031433
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5095064043998718
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4703024923801422
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.507582426071167
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5408015847206116
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5093827247619629
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4774530827999115
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5417137145996094
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4295750856399536
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.42698097229003906
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5368147492408752
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.49747154116630554
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5534645915031433
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.533180832862854
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45654743909835815
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4886714220046997
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4720982015132904
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5527008175849915
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5815708637237549
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48954179883003235
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.451478511095047
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.470884770154953
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5391373038291931
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5371843576431274
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.47436219453811646
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4530352056026459
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6790469884872437
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5398080348968506
Calibrated prediction for HD: 0.6004399061203003
Raw prediction for HON: 0.5145483016967773
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.5020759701728821
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44423186779022217
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5161497592926025
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6549617052078247
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47066426277160645
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5042253136634827
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4525221586227417
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6631028652191162
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5807253122329712
Calibrated prediction for MA: 0.58946692943573
Raw prediction for MCD: 0.5998638868331909
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5006901621818542
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5279157161712646
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5155113339424133
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4912727475166321
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4893224835395813
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5255723595619202
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.47647222876548767
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4541441798210144
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.514139711856842
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5154001712799072
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48332878947257996
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48119041323661804
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49804654717445374
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4196423888206482
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4985700845718384
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5260396003723145
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5048930048942566
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4371611177921295
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4335172474384308
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5055391192436218
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5548466444015503
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.495040625333786
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4957481622695923
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5382982492446899
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4482744336128235
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.518265426158905
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4899882674217224
Calibrated prediction for T: 0.4953271150588989

Simulating Trading Days:  78%|███████▊  | 69/88 [08:11<00:27,  1.45s/it]

Raw prediction for TM: 0.40481409430503845
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.46177318692207336
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5226433873176575
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.41917428374290466
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3113560676574707
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4665288031101227
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5250962972640991
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4920579493045807
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5718369483947754
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.2950161397457123
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49730148911476135
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.4961533844470978
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5083944797515869
Calibrated prediction for XOM: 0.5454545617103577
Investing 3447.871990374447 in BP
Investing 2956.946591981876 in AGFS
Investing 1607.7458644194041 in PM
Investing 4615.520247271838 in MA
Investing 3030.2253590151586 in JNJ
Investing 9161.844735216697 in LMT
Investing 11540.781735448685 in AMZN
Investing 9715.837059474215 in GOOG
Investing 1648.749688600054 in NEE
Raw prediction for AAPL: 0.5229431986808777
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47766828536987305
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5127281546592712
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4001655578613281
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5163078308105469
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48912280797958374
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6890105605125427
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.2384844869375229
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4668947458267212
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.4003104269504547
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5096856355667114
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4698210060596466
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5077446699142456
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5352593660354614
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5118303894996643
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.47704383730888367
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5421473383903503
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42234739661216736
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4245554506778717
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5372881889343262
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5060984492301941
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5492330193519592
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5370935797691345
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4551852345466614
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.49716490507125854
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4641341269016266
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5507299304008484
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5839139223098755
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.48521026968955994
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.44192540645599365
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.474992573261261
Calibrated prediction for EXC: 0.469765841960907
Raw prediction for FB: 0.5399353504180908
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5433077216148376
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4660177230834961
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45308491587638855
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6759806871414185
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5344353318214417
Calibrated prediction for HD: 0.5717172622680664
Raw prediction for HON: 0.5102581977844238
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.502472460269928
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4439336657524109
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5130141973495483
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.650980532169342
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47092026472091675
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5055290460586548
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4527603089809418
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.651360034942627
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5842064619064331
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5972356200218201
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5010474324226379
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5252040028572083
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5152942538261414
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4934206008911133
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4920342266559601
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5250403881072998
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4732329249382019
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4494326412677765
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5136706829071045
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.5156754851341248
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48323410749435425
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48192885518074036
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49741625785827637
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.42006048560142517
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4991581439971924
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5251462459564209
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5038315653800964
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4373226761817932
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.436178058385849
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5062918066978455
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5552144646644592
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49553582072257996
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.49425286054611206
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5382159948348999
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4470025897026062
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5152228474617004
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49061650037765503
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4064331650733948
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.46429669857025146
Calibrated prediction for TOT: 0.5134687423706055
Raw prediction for TSM: 0.5208644866943359
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4225163459777832
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  80%|███████▉  | 70/88 [08:13<00:26,  1.45s/it]

Raw prediction for UN: 0.3187049329280853
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4610563814640045
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5264142751693726
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4937923848628998
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5745680332183838
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.2964880168437958
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4976036846637726
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.49506494402885437
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5028044581413269
Calibrated prediction for XOM: 0.5454545617103577
Investing 3450.3854585333106 in BP
Investing 2959.1021798712045 in AGFS
Investing 1608.9178969220736 in PM
Investing 5679.2385692464095 in MA
Investing 3032.4343664769576 in JNJ
Investing 9168.523638923885 in LMT
Investing 11549.194863169618 in AMZN
Investing 9722.919818681596 in GOOG
Investing 1649.951612527567 in NEE
Raw prediction for AAPL: 0.5231462717056274
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4771285057067871
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5123512148857117
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.39823171496391296
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5158034563064575
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.489378958940506
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6802801489830017
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.24475030601024628
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4664194583892822
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.40147629380226135
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5095182061195374
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46986380219459534
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.50839763879776
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.535925567150116
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5093382596969604
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.47674068808555603
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5444758534431458
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4150109887123108
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4228929579257965
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5372483730316162
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5149909853935242
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5478713512420654
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5428852438926697
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45272302627563477
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5040479898452759
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4558725953102112
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5464441776275635
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5860682129859924
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4791159927845001
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4328656792640686
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.47798603773117065
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5405958294868469
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5453073978424072
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4606700539588928
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4531571567058563
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6701251864433289
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5286067724227905
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.5043274760246277
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.503013014793396
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4435255825519562
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5127575993537903
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.6450471878051758
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47107744216918945
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5060722827911377
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45227137207984924
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.648105263710022
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5876463651657104
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5941990613937378
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.49417802691459656
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5221449136734009
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5152733325958252
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.4961705207824707
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4906757175922394
Calibrated prediction for MSFT: 0.5
Raw prediction for NEE: 0.5249133110046387
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4687659442424774
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4443424642086029
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5147606730461121
Calibrated prediction for ORCL: 0.5454545617103577
Raw prediction for PCG: 0.515022337436676
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48318785429000854
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4821327328681946
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4966282844543457
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.419971227645874
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5001979470252991
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5241206288337708
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5041443109512329
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.43904048204421997
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.43916216492652893
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.506853461265564
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5604295134544373
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4942602217197418
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.491075336933136
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5381970405578613
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.446708619594574
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5125112533569336
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4912276864051819
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.41272056102752686
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4666038751602173
Calibrated prediction for TOT: 0.5260158181190491

Simulating Trading Days:  81%|████████  | 71/88 [08:14<00:25,  1.48s/it]

Raw prediction for TSM: 0.5154728889465332
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4273848831653595
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3276243209838867
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4547882676124573
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.526699423789978
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4947530925273895
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5761336088180542
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.30196255445480347
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49832597374916077
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.4954032599925995
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5040957927703857
Calibrated prediction for XOM: 0.5454545617103577
Investing 3451.6016864502158 in BP
Investing 2960.1452351249977 in AGFS
Investing 1609.4850251127532 in PM
Investing 5681.240446595389 in MA
Investing 3033.5032706260786 in JNJ
Investing 9171.755455931137 in LMT
Investing 11553.265844043835 in AMZN
Investing 9726.347055046757 in GOOG
Investing 1650.5332047110535 in NEE
Raw prediction for AAPL: 0.5230932831764221
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47673705220222473
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5119196176528931
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.39537960290908813
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5154772400856018
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48963722586631775
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6754018068313599
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.2509418725967407
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4661887586116791
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3973328769207001
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5090312957763672
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4701458811759949
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5088979601860046
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5293610692024231
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.5009408593177795
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4764832556247711
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5457288026809692
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.40795472264289856
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.42175745964050293
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5370587110519409
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5217739343643188
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5466185212135315
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5473609566688538
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4501408040523529
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5093177556991577
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.45572924613952637
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5430901050567627
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5878229141235352
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4718281328678131
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.42502009868621826
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.48045840859413147
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5410012602806091
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5443762540817261
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.45984163880348206
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45321494340896606
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6655528545379639
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5242773294448853
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.5009369254112244
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5036869645118713
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4431154131889343
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5179396867752075
Calibrated prediction for IEP: 0.551054060459137
Raw prediction for INTC: 0.638734757900238
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47107383608818054
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5060139298439026
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4517746567726135
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.642143964767456
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.59227454662323
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5923529267311096
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.48417460918426514
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5208547711372375
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5157036185264587
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.5001018643379211
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.48705556988716125
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5253443121910095
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4666501581668854
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4440128207206726
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5165354013442993
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5142364501953125
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48316124081611633
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48215633630752563
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49587392807006836
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.41958993673324585
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5013974905014038
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5228598117828369
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5062122344970703
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4407217502593994
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.44098272919654846
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5070260167121887
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5755584836006165
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49536025524139404
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48810818791389465
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5381760597229004
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.44694551825523376
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5104361772537231
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.49185940623283386
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4207330644130707
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4646000266075134
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5082521438598633
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4323047697544098
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  82%|████████▏ | 72/88 [08:16<00:23,  1.47s/it]

Raw prediction for UN: 0.3339642584323883
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4508030116558075
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5248774886131287
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4952065050601959
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5768053531646729
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.3136287331581116
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4987320899963379
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.49613648653030396
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.507327139377594
Calibrated prediction for XOM: 0.5454545617103577
Investing 3452.4248261312046 in BP
Investing 3046.6984377922145 in IEP
Investing 1609.8688558992917 in PM
Investing 5682.595311633028 in MA
Investing 3034.226701989629 in JNJ
Investing 9173.942740718296 in LMT
Investing 11556.021072608759 in AMZN
Investing 9728.66659911336 in GOOG
Investing 1650.9268246878082 in NEE
Raw prediction for AAPL: 0.5228917002677917
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.476641982793808
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5114814043045044
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.40148699283599854
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5148885250091553
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4897516965866089
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6805716156959534
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.258737713098526
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.466035395860672
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3923183083534241
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5086618065834045
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.470366895198822
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5089661478996277
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5171976685523987
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.4870908856391907
Calibrated prediction for BRK-A: 0.5485914349555969
Raw prediction for BSAC: 0.4762446880340576
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5456282496452332
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.39963647723197937
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4205898940563202
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5370326638221741
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5262075662612915
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5470549464225769
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5492672920227051
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45121124386787415
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5137712359428406
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4535139203071594
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.543069064617157
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5895576477050781
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4727743864059448
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.4219193458557129
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4830152988433838
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5412611961364746
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5424709320068359
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.46071377396583557
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45328420400619507
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6630762219429016
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5192015767097473
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.49977949261665344
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5043346881866455
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44300949573516846
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5262420773506165
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6343140602111816
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4715588688850403
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5049414038658142
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45225420594215393
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6425703167915344
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5946527123451233
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5901964902877808
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.47313329577445984
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5216869115829468
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5150861144065857
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.5027083158493042
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.48268213868141174
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5266599655151367
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.46897828578948975
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.44840699434280396
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5189703106880188
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5137161612510681
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48463156819343567
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48202890157699585
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4952811300754547
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4185546040534973
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5017776489257812
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5213297009468079
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5097401142120361
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.44205597043037415
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4412137269973755
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5068827867507935
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.5915026068687439
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4980069398880005
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48590874671936035
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5382363200187683
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4493221938610077
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.509706974029541
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.492445707321167
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.42955607175827026
Calibrated prediction for TM: 0.40625
Raw prediction for TOT: 0.4621649384498596
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5034893751144409
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.43688637018203735
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  83%|████████▎ | 73/88 [08:17<00:22,  1.48s/it]

Raw prediction for UN: 0.33618226647377014
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.44816356897354126
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5262216925621033
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4957217872142792
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5769026279449463
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.3363798260688782
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49897000193595886
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.49729496240615845
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5072149634361267
Calibrated prediction for XOM: 0.5454545617103577
Investing 3090.621010132429 in BP
Investing 4151.092981357876 in IEP
Investing 1601.6503777436453 in PM
Investing 5653.585317890435 in MA
Investing 3018.7367906355453 in JNJ
Investing 9127.109206583227 in LMT
Investing 11497.026884104895 in AMZN
Investing 9679.001166034517 in GOOG
Investing 1642.4987431111335 in NEE
Raw prediction for AAPL: 0.5223397612571716
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4764651358127594
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5110800266265869
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.40943342447280884
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5146591067314148
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4902573823928833
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.692966639995575
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.26948314905166626
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4658927619457245
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3890787959098816
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5083274841308594
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4709607660770416
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5090811252593994
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5072800517082214
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.47334933280944824
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.476291686296463
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5437294840812683
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.39583438634872437
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4190129339694977
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5369699597358704
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5293383002281189
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5447739362716675
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5463648438453674
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.45513492822647095
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5186243653297424
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4534117579460144
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.545807957649231
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5910159349441528
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4865550398826599
Calibrated prediction for DIS: 0.4653465449810028
Raw prediction for DUK: 0.42191633582115173
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4854292571544647
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.541517972946167
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.538705587387085
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.4641212224960327
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4533061385154724
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.665047824382782
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5142496228218079
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.5057463645935059
Calibrated prediction for HON: 0.4502500295639038
Raw prediction for HRG: 0.5047399401664734
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4431290328502655
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5301052927970886
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6290687322616577
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4751109778881073
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5036243796348572
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4538246691226959
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6309577822685242
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.6004887223243713
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5912945866584778
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.467899352312088
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.522865891456604
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5149843096733093
Calibrated prediction for MO: 0.5
Raw prediction for MRK: 0.5052920579910278
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4792739748954773
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5275284647941589
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4697408676147461
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4560120403766632
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5263217687606812
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5131441354751587
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48569732904434204
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48233097791671753
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49505674839019775
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.418028324842453
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5013549327850342
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.519994854927063
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5136778950691223
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4438903033733368
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4395473003387451
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.506670355796814
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6073835492134094
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5036956667900085
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4872872531414032
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5383463501930237
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45203426480293274
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5103223323822021
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.493085652589798
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.44248077273368835
Calibrated prediction for TM: 0.4285714328289032
Raw prediction for TOT: 0.45659732818603516
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.511340856552124
Calibrated prediction for TSM: 0.6132082343101501

Simulating Trading Days:  84%|████████▍ | 74/88 [08:19<00:20,  1.48s/it]

Raw prediction for UL: 0.43767812848091125
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3342285752296448
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4504949152469635
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.526159942150116
Calibrated prediction for UPS: 0.5
Raw prediction for UTX: 0.4954071342945099
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5771186947822571
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.3666994571685791
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4992171823978424
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5003894567489624
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5110015869140625
Calibrated prediction for XOM: 0.5454545617103577
Investing 3097.468607819324 in BP
Investing 4160.2901668439135 in IEP
Investing 1605.1990035330564 in PM
Investing 5666.111434039432 in MA
Investing 3025.4251212322542 in JNJ
Investing 9147.331282239264 in LMT
Investing 11522.499762998703 in AMZN
Investing 9700.446016690325 in GOOG
Investing 1646.1378727738072 in NEE
Raw prediction for AAPL: 0.5219213366508484
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4765041768550873
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5107275247573853
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4296620786190033
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5150334239006042
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4906768798828125
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6966999173164368
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.27901721000671387
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4656900465488434
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3833489716053009
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5080409646034241
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.471585214138031
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5093114376068115
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4936612546443939
Calibrated prediction for BP: 0.5281184911727905
Raw prediction for BRK-A: 0.45890313386917114
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4767816960811615
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5416616797447205
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.3923683166503906
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.41691499948501587
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5373100638389587
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5290150046348572
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5446975231170654
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5407861471176147
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.46051838994026184
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5222731232643127
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4542282819747925
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5504472255706787
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5884407758712769
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4947524070739746
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.42879247665405273
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.48930010199546814
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5418487191200256
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5339725017547607
Calibrated prediction for GD: 0.5572916865348816
Raw prediction for GE: 0.46998441219329834
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4533722996711731
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6638287901878357
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.510325014591217
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.5134694576263428
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.5048945546150208
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4432778060436249
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5306676626205444
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6191825270652771
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47996237874031067
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5019598007202148
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45515206456184387
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6074442863464355
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.6028836965560913
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5938274264335632
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4604693651199341
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5236982703208923
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5140690207481384
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5069808959960938
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4744020104408264
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5284433960914612
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.47081834077835083
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.46114230155944824
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5306288599967957
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5126559138298035
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48663559556007385
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48274022340774536
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49489715695381165
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.41835764050483704
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5014640688896179
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5189235210418701
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5189281702041626
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.44660425186157227
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.43631482124328613
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5065452456474304
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6249295473098755
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5033871531486511
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48781493306159973
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5385952591896057
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4548857510089874
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5132083892822266
Calibrated prediction for SRE: 0.5061770677566528
Raw prediction for T: 0.4935785233974457
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.45865508913993835
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.45361819863319397
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5174147486686707
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.43796494603157043
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  85%|████████▌ | 75/88 [08:20<00:19,  1.46s/it]

Raw prediction for UN: 0.3318116068840027
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.45868492126464844
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5231398940086365
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.494949609041214
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5771514773368835
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.3956010639667511
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49961715936660767
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5034701824188232
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.5150890946388245
Calibrated prediction for XOM: 0.5454545617103577
Investing 2442.2578894263747 in SNP
Investing 4176.091727309151 in IEP
Investing 1611.2958496894169 in PM
Investing 5687.632385424337 in MA
Investing 3036.916251915205 in JNJ
Investing 9182.074557961667 in LMT
Investing 11566.264373017199 in AMZN
Investing 9737.290125664767 in GOOG
Investing 1652.3902124154158 in NEE
Raw prediction for AAPL: 0.5215304493904114
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4765726923942566
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5105521082878113
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4482702314853668
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5149940252304077
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4908142387866974
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6867696046829224
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.2871130108833313
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4652918875217438
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3759004473686218
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5076024532318115
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4717846214771271
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5092512965202332
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.47073158621788025
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.44555866718292236
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.47706446051597595
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5398705005645752
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.3907347023487091
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4144360423088074
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5376128554344177
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5249241590499878
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5451058149337769
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5361829400062561
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.46579843759536743
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5235268473625183
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4551762640476227
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5536291599273682
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5830196738243103
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.4969736933708191
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.43948835134506226
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.49117201566696167
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5421718955039978
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.531330406665802
Calibrated prediction for GD: 0.5223464369773865
Raw prediction for GE: 0.4763104319572449
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534962773323059
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6558238863945007
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5087428092956543
Calibrated prediction for HD: 0.508674144744873
Raw prediction for HON: 0.5196545720100403
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.5048556327819824
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4432893395423889
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5276618003845215
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.6065399646759033
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.48619577288627625
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5008677244186401
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45573025941848755
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.58625727891922
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.600614070892334
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.5977998971939087
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.45659464597702026
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5241549015045166
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.513342559337616
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5063758492469788
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.46559983491897583
Calibrated prediction for MSFT: 0.46296295523643494
Raw prediction for NEE: 0.5290731191635132
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4703138470649719
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.46293550729751587
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5303924083709717
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5118411183357239
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4874342978000641
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48277613520622253
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.494928240776062
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4189794957637787
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5013920068740845
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5181384682655334
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5239309668540955
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4498973488807678
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.4390597939491272
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.506458044052124
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.643704891204834
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5044026970863342
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48742082715034485
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5388147830963135
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4568495750427246
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5162239074707031
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49391478300094604
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.47522732615470886
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.45946505665779114
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5210193395614624
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4381343424320221
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3331727385520935
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.46879246830940247
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  86%|████████▋ | 76/88 [08:22<00:17,  1.46s/it]

Raw prediction for UPS: 0.5198876261711121
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4948986768722534
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5771928429603577
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.4171298146247864
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.4997137188911438
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5057520270347595
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5150321125984192
Calibrated prediction for XOM: 0.5454545617103577
Investing 2440.9983522900293 in SNP
Investing 4173.938006099731 in IEP
Investing 1610.464861705261 in PM
Investing 5684.699122627506 in MA
Investing 3035.3500336972934 in JNJ
Investing 4842.119107747364 in DHR
Investing 11560.299343865414 in AMZN
Investing 9732.268347017336 in GOOG
Investing 1651.5380309790157 in NEE
Raw prediction for AAPL: 0.5211830735206604
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4763767719268799
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5102300643920898
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4667242765426636
Calibrated prediction for AEP: 0.5
Raw prediction for AGFS: 0.5151835083961487
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4908895194530487
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6807546019554138
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.2933579087257385
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4649520516395569
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3720642030239105
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5072540640830994
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47162050008773804
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5094752907752991
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4612294137477875
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.43853065371513367
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4770907163619995
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5395154356956482
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.3955559730529785
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.41259482502937317
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5377318263053894
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5194287896156311
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5490545034408569
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5327233672142029
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4697284400463104
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5216060876846313
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.44985055923461914
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5574329495429993
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5776751637458801
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5013117790222168
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.45070335268974304
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.49176234006881714
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.542310357093811
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5279546976089478
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.48169276118278503
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4535383880138397
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6446865200996399
Calibrated prediction for GOOG: 0.671248197555542
Raw prediction for HD: 0.5104709267616272
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.5274891257286072
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5048189759254456
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44323256611824036
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5203403234481812
Calibrated prediction for IEP: 0.5736196637153625
Raw prediction for INTC: 0.5923396944999695
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.49233299493789673
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5009307265281677
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4550446569919586
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5701258182525635
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5939149260520935
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6025164723396301
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4493114948272705
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5241468548774719
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5119871497154236
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5063308477401733
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.4538254737854004
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5294710993766785
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4721273183822632
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4645945727825165
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.52894127368927
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5119786858558655
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.48834824562072754
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4821755588054657
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.49506083130836487
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.41890501976013184
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5012925863265991
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5173153877258301
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5282353758811951
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4538479745388031
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.45993563532829285
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5065551996231079
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6596097350120544
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5051354765892029
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48804572224617004
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5390459299087524
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45937469601631165
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5185704231262207
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4942934215068817
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4876866936683655
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4613366425037384
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5215583443641663
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4399271309375763
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.33722609281539917
Calibrated prediction for UN: 0.3459798991680145

Simulating Trading Days:  88%|████████▊ | 77/88 [08:23<00:16,  1.46s/it]

Raw prediction for UNH: 0.47715163230895996
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5191819071769714
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.49462538957595825
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.576573371887207
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.43915030360221863
Calibrated prediction for VZ: 0.374971479177475
Raw prediction for WFC: 0.49983376264572144
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5053320527076721
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.5142858028411865
Calibrated prediction for XOM: 0.5454545617103577
Investing 2442.790976185601 in SNP
Investing 4177.003268721211 in IEP
Investing 1611.647557216449 in PM
Investing 5688.873860179784 in MA
Investing 3037.5791384390986 in JNJ
Investing 4845.675070171348 in DHR
Investing 11568.789013194493 in AMZN
Investing 9739.415544302663 in GOOG
Investing 1652.7508898635783 in NEE
Raw prediction for AAPL: 0.5207844376564026
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47590792179107666
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5100328326225281
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4719278812408447
Calibrated prediction for AEP: 0.5
Raw prediction for AGFS: 0.5160183310508728
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.490474671125412
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.67430579662323
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.2973244786262512
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4647834002971649
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.37144556641578674
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5072203874588013
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4713227450847626
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5099515914916992
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4800771474838257
Calibrated prediction for BP: 0.4354838728904724
Raw prediction for BRK-A: 0.4365665018558502
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.47714662551879883
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5413485765457153
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4012672007083893
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4113716781139374
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5377131700515747
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5145478248596191
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5521067380905151
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.53106689453125
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4724210202693939
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5164625644683838
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.44036322832107544
Calibrated prediction for CVX: 0.36033275723457336
Raw prediction for D: 0.561785876750946
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.569908857345581
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5036324262619019
Calibrated prediction for DIS: 0.47826087474823
Raw prediction for DUK: 0.46309712529182434
Calibrated prediction for DUK: 0.3922998309135437
Raw prediction for EXC: 0.4908880889415741
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5423646569252014
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5243732333183289
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4848475754261017
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4534062147140503
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6309294104576111
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5098638534545898
Calibrated prediction for HD: 0.5128205418586731
Raw prediction for HON: 0.5307668447494507
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5046375393867493
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44307565689086914
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5099964737892151
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5788264274597168
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4962756037712097
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5010524392127991
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4526911973953247
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5643998980522156
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5839017629623413
Calibrated prediction for MA: 0.6103866100311279
Raw prediction for MCD: 0.6084638237953186
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.44139185547828674
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.523844301700592
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5085890293121338
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.505462646484375
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.44033244252204895
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5290552973747253
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.47174322605133057
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.46395519375801086
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5264291167259216
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.512327253818512
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4892255663871765
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.48113521933555603
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4952295422554016
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4177250862121582
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5014986395835876
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5166916847229004
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5306040048599243
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4584663212299347
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.481426477432251
Calibrated prediction for RDS-B: 0.4791666567325592
Raw prediction for REX: 0.5068079829216003
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6736415028572083
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5048881769180298
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48661747574806213
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.539351224899292
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.46132609248161316
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5200895071029663
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49456197023391724
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.49573665857315063
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.46548667550086975
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5209488868713379
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44236302375793457
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.339821994304657
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4821872115135193
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  89%|████████▊ | 78/88 [08:25<00:14,  1.46s/it]

Raw prediction for UPS: 0.5162956714630127
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4943346679210663
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5751544237136841
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.4625619947910309
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5000727772712708
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5046886205673218
Calibrated prediction for WMT: 0.49415090680122375
Raw prediction for XOM: 0.5096391439437866
Calibrated prediction for XOM: 0.5454545617103577
Investing 2431.554654321341 in SNP
Investing 2950.4882010130036 in AGFS
Investing 1604.2343193008132 in PM
Investing 5662.70624356366 in MA
Investing 3023.6069168203016 in JNJ
Investing 4823.385989661036 in DHR
Investing 11515.575030418551 in AMZN
Investing 6261.763958030251 in TSM
Investing 2122.7278520443124 in PPL
Raw prediction for AAPL: 0.5201736688613892
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47492101788520813
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5099702477455139
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4664398431777954
Calibrated prediction for AEP: 0.5
Raw prediction for AGFS: 0.5167606472969055
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4903015196323395
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6745160818099976
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.3046392500400543
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46484068036079407
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.37399283051490784
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5072634816169739
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4713281989097595
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5102264881134033
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.4990997314453125
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.4374200105667114
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4771255552768707
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5439130067825317
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4082649350166321
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.410683810710907
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5376194715499878
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5130094289779663
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.560373842716217
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5333777070045471
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4738663136959076
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5105685591697693
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4390731155872345
Calibrated prediction for CVX: 0.36033275723457336
Raw prediction for D: 0.5670832395553589
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5638227462768555
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.51251620054245
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.4783426523208618
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.48940807580947876
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5424647927284241
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5186042189598083
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4868181049823761
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4532780349254608
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6261338591575623
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5088384747505188
Calibrated prediction for HD: 0.5093866586685181
Raw prediction for HON: 0.5375195741653442
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5043965578079224
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4430809020996094
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4972921907901764
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5650012493133545
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4989982545375824
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.500813901424408
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4515412151813507
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5534650683403015
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5735822916030884
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.6111688613891602
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.436134397983551
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5240758657455444
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.5028060674667358
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5064682960510254
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.43006566166877747
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5297356843948364
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.4822852313518524
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4618581235408783
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5276080369949341
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.512231707572937
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4903743863105774
Calibrated prediction for PCLN: 0.4885042607784271
Raw prediction for PEP: 0.4803418815135956
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4955982565879822
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4173617362976074
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5022093057632446
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5162686109542847
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5317642092704773
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.462154358625412
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5047579407691956
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5073309540748596
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6841384768486023
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5127085447311401
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48731470108032227
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5398073196411133
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4622904658317566
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5220057964324951
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49508094787597656
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.5018513798713684
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.4699380099773407
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5237029790878296
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44284579157829285
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.33839261531829834
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4892229437828064
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5137864351272583
Calibrated prediction for UPS: 0.4920634925365448

Simulating Trading Days:  90%|████████▉ | 79/88 [08:26<00:13,  1.45s/it]

Raw prediction for UTX: 0.4944508671760559
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5734140276908875
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.489428848028183
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5004445314407349
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5034877061843872
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.4988879859447479
Calibrated prediction for XOM: 0.5454545617103577
Investing 2361.336532138079 in RDS-B
Investing 2950.529039101977 in AGFS
Investing 1604.256523715609 in PM
Investing 4719.57662421111 in V
Investing 3023.648766954882 in JNJ
Investing 4823.452750770649 in DHR
Investing 11515.734418982624 in AMZN
Investing 6261.850627915445 in TSM
Investing 2122.7572329951863 in PPL
Raw prediction for AAPL: 0.5196908712387085
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47426941990852356
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5103018283843994
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.45030903816223145
Calibrated prediction for AEP: 0.5
Raw prediction for AGFS: 0.5169320702552795
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4902040958404541
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6708701252937317
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.31028419733047485
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46525123715400696
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3799670934677124
Calibrated prediction for BAC: 0.44117647409439087
Raw prediction for BBL: 0.5073859691619873
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47126874327659607
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5105503797531128
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5116310119628906
Calibrated prediction for BP: 0.5588235259056091
Raw prediction for BRK-A: 0.4384707808494568
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4770057499408722
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5460541844367981
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4138224124908447
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.41065752506256104
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.537614643573761
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.513397216796875
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5665392875671387
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5381820797920227
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4757559597492218
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5040519833564758
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.44372543692588806
Calibrated prediction for CVX: 0.36033275723457336
Raw prediction for D: 0.565464437007904
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5577805042266846
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.517724871635437
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.49580007791519165
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.4864584505558014
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5426811575889587
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5137936472892761
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4874805510044098
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.45330825448036194
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6243841052055359
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5083780884742737
Calibrated prediction for HD: 0.5059576630592346
Raw prediction for HON: 0.5429845452308655
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5043321847915649
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4431699514389038
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4886800944805145
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5519793629646301
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.49929502606391907
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5003864765167236
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45282483100891113
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5491339564323425
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5638983249664307
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.6118496656417847
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.43550243973731995
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5240116119384766
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4966783821582794
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5085649490356445
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.42601442337036133
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5314118266105652
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.49265292286872864
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4610556960105896
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5282027721405029
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5122498869895935
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49142253398895264
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48013874888420105
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4962162971496582
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4169562757015228
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5023945569992065
Calibrated prediction for PICO: 0.5
Raw prediction for PM: 0.5156481862068176
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.532454788684845
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.46617597341537476
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5297667384147644
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5077588558197021
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6926339864730835
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5185468792915344
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4878382384777069
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5402029752731323
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.4603022038936615
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5240058898925781
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4954710304737091
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.507127583026886
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.4722635746002197
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5269461274147034
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4424794316291809
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  91%|█████████ | 80/88 [08:28<00:11,  1.47s/it]

Raw prediction for UN: 0.33566123247146606
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.5008008480072021
Calibrated prediction for UNH: 0.5
Raw prediction for UPS: 0.51044100522995
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.49566787481307983
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5718719363212585
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5039441585540771
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5008296966552734
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5023679733276367
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.488216370344162
Calibrated prediction for XOM: 0.44186046719551086
Investing 2361.094982746832 in RDS-B
Investing 2950.2272191438515 in AGFS
Investing 1604.0924186922746 in PM
Investing 4719.093842174325 in V
Investing 3023.339467323482 in JNJ
Investing 4822.959342880753 in DHR
Investing 11514.556434141918 in AMZN
Investing 6261.210081264569 in TSM
Investing 2122.5400887167593 in PPL
Raw prediction for AAPL: 0.5194082856178284
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4738149344921112
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5108246803283691
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.43331897258758545
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5166914463043213
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.49034714698791504
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6631574630737305
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.31461969017982483
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4659354090690613
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.38769644498825073
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5074253082275391
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4712371826171875
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5107899904251099
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5230289697647095
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.44002294540405273
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.47695183753967285
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5460190773010254
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4168245494365692
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4104221761226654
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5377687811851501
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5174459218978882
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5702245831489563
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.544006884098053
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4769246578216553
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5009374022483826
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.44675976037979126
Calibrated prediction for CVX: 0.36033275723457336
Raw prediction for D: 0.563906192779541
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5519148111343384
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5219255685806274
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.5104373097419739
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.48544904589653015
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5428771376609802
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5113751292228699
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.48423901200294495
Calibrated prediction for GE: 0.4913793206214905
Raw prediction for GMRE: 0.4533887505531311
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6278930902481079
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5058130621910095
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.548276960849762
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5044119954109192
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44321388006210327
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.48267990350723267
Calibrated prediction for IEP: 0.4507042169570923
Raw prediction for INTC: 0.5414549112319946
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4975913465023041
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5000715255737305
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4544602036476135
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.545204758644104
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5584765076637268
Calibrated prediction for MA: 0.5822784900665283
Raw prediction for MCD: 0.6105930209159851
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4402993619441986
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5234760642051697
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4900315999984741
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.5085834264755249
Calibrated prediction for MRK: 0.5142857432365417
Raw prediction for MSFT: 0.43228963017463684
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5336050391197205
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.49748557806015015
Calibrated prediction for NGG: 0.4615384638309479
Raw prediction for NVS: 0.46141278743743896
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5285972952842712
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.512438178062439
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4923844337463379
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.4802001118659973
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4971686899662018
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.41632047295570374
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5013570189476013
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5153874158859253
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5340282320976257
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4690849184989929
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5523594617843628
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5080310702323914
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6992548108100891
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5181037187576294
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.48757943511009216
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5405073165893555
Calibrated prediction for SO: 0.5335198044776917
Raw prediction for SPLP: 0.45701175928115845
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5244892835617065
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4957129955291748
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.5096383094787598
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.47284072637557983
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5290759801864624
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44219771027565
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3345057964324951
Calibrated prediction for UN: 0.3459798991680145

Simulating Trading Days:  92%|█████████▏| 81/88 [08:29<00:10,  1.47s/it]

Raw prediction for UNH: 0.5103763937950134
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5116045475006104
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4967390298843384
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5715739727020264
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.5044737458229065
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5011419653892517
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.502446174621582
Calibrated prediction for WMT: 0.484067440032959
Raw prediction for XOM: 0.47896236181259155
Calibrated prediction for XOM: 0.44186046719551086
Investing 2370.132943942262 in RDS-B
Investing 2961.5203010906444 in AGFS
Investing 1610.2326735909394 in PM
Investing 4737.157913012146 in V
Investing 3034.9124133446926 in JNJ
Investing 4841.420997200725 in DHR
Investing 11558.632642424436 in AMZN
Investing 6285.177170333163 in TSM
Investing 2130.6648931391755 in PPL
Raw prediction for AAPL: 0.5190652012825012
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4734594225883484
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.510794997215271
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.41829973459243774
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5170544981956482
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4904821217060089
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6486994028091431
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.31467896699905396
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4665982723236084
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.3941342234611511
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5075623393058777
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4711390435695648
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5108414888381958
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5340739488601685
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.442330926656723
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4769727885723114
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5464881062507629
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.42073261737823486
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.41028425097465515
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5376559495925903
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5202547907829285
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5720338821411133
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5481581687927246
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.47632482647895813
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4995201528072357
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4486687183380127
Calibrated prediction for CVX: 0.5050645470619202
Raw prediction for D: 0.5586820244789124
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5475094318389893
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5203486084938049
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.5191152691841125
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.48432332277297974
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5430280566215515
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5145829916000366
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4745381474494934
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534243047237396
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6256662011146545
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.5028948783874512
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5494379997253418
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5045155882835388
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4430842399597168
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4792921841144562
Calibrated prediction for IEP: 0.4507042169570923
Raw prediction for INTC: 0.5331176519393921
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4966311752796173
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5003440380096436
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4563618004322052
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5548257231712341
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.551706850528717
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6098496317863464
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.4547431170940399
Calibrated prediction for MDT: 0.4443422555923462
Raw prediction for MMM: 0.5222790837287903
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4831628203392029
Calibrated prediction for MO: 0.4939759075641632
Raw prediction for MRK: 0.50633704662323
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.436643123626709
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5345596075057983
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.49457135796546936
Calibrated prediction for NGG: 0.4615384638309479
Raw prediction for NVS: 0.45964592695236206
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.526282012462616
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5135709643363953
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49326732754707336
Calibrated prediction for PCLN: 0.5
Raw prediction for PEP: 0.48078104853630066
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.498031884431839
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.41503772139549255
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5007635354995728
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5155357718467712
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5353383421897888
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4689154326915741
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5703760981559753
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5080153346061707
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.7032261490821838
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5156621932983398
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4856029748916626
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5407821536064148
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45256826281547546
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5242711305618286
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4955376386642456
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.5095845460891724
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.47271662950515747
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5280323624610901
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4430634081363678
Calibrated prediction for UL: 0.4285714328289032

Simulating Trading Days:  93%|█████████▎| 82/88 [08:30<00:08,  1.47s/it]

Raw prediction for UN: 0.3347040116786957
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.5101690292358398
Calibrated prediction for UNH: 0.5272727012634277
Raw prediction for UPS: 0.5123568773269653
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4974081218242645
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5715115666389465
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.4995774030685425
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5014538168907166
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5039525032043457
Calibrated prediction for WMT: 0.48513150215148926
Raw prediction for XOM: 0.4702780246734619
Calibrated prediction for XOM: 0.44186046719551086
Investing 2366.742183936711 in RDS-B
Investing 2957.283490401088 in AGFS
Investing 1607.9290422426648 in PM
Investing 4730.380839332598 in V
Investing 3030.570606418705 in JNJ
Investing 4834.494762649494 in DHR
Investing 11542.096629378013 in AMZN
Investing 6276.185469073773 in TSM
Investing 3540.046638053353 in DUK
Raw prediction for AAPL: 0.5187395811080933
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4729406535625458
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5095793604850769
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4091586768627167
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5178692936897278
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4905160963535309
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6351085901260376
Calibrated prediction for AMZN: 0.7169754505157471
Raw prediction for BA: 0.31572145223617554
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4671977162361145
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.4004891812801361
Calibrated prediction for BAC: 0.550000011920929
Raw prediction for BBL: 0.5077329277992249
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.47093304991722107
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5107775330543518
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5461887121200562
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.44611039757728577
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.477045476436615
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5465860962867737
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4277227520942688
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.41089460253715515
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5374619364738464
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5249550342559814
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5771805644035339
Calibrated prediction for CHTR: 0.557692289352417
Raw prediction for CMCSA: 0.5501430034637451
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.47460734844207764
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.49890008568763733
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4582459330558777
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5496364235877991
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5460590124130249
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5207474827766418
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.5220353007316589
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.48236337304115295
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.5430643558502197
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5164533257484436
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4648253321647644
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45343175530433655
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6199794411659241
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4986844062805176
Calibrated prediction for HD: 0.5
Raw prediction for HON: 0.5515226125717163
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5048165321350098
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4429834187030792
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.47911718487739563
Calibrated prediction for IEP: 0.4507042169570923
Raw prediction for INTC: 0.5274445414543152
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.49563801288604736
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5011283755302429
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4571407735347748
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5680475234985352
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5467736124992371
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6090222597122192
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.46868255734443665
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5222230553627014
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.47591373324394226
Calibrated prediction for MO: 0.4720177948474884
Raw prediction for MRK: 0.5046008825302124
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.44093507528305054
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5359523296356201
Calibrated prediction for NEE: 0.5476190447807312
Raw prediction for NGG: 0.49206778407096863
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.45879891514778137
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5242819786071777
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5143826603889465
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4940478801727295
Calibrated prediction for PCLN: 0.5212342739105225
Raw prediction for PEP: 0.4817352294921875
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4984941780567169
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4148579239845276
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5001376271247864
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5156430602073669
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5347479581832886
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4659610986709595
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5822705030441284
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.5076180100440979
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.7037968039512634
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.51235431432724
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4846998453140259
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5410223007202148
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.44848906993865967
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5228391885757446
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49541109800338745
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.5047505497932434
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.4706614911556244
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5245233774185181
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44464346766471863
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3337821662425995
Calibrated prediction for UN: 0.3459798991680145

Simulating Trading Days:  94%|█████████▍| 83/88 [08:32<00:07,  1.46s/it]

Raw prediction for UNH: 0.5059049129486084
Calibrated prediction for UNH: 0.5
Raw prediction for UPS: 0.5158500075340271
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4961340129375458
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5712701082229614
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.4953943192958832
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5017958879470825
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5084927678108215
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.462984561920166
Calibrated prediction for XOM: 0.44186046719551086
Investing 4455.971708430683 in RDS-B
Investing 2956.4933075849563 in AGFS
Investing 1607.4994054145207 in PM
Investing 4729.1168869029 in V
Investing 3029.7608413677594 in JNJ
Investing 4833.2029910968095 in DHR
Investing 11539.0125941652 in AMZN
Investing 6274.508479388944 in TSM
Investing 3539.1007415808726 in DUK
Raw prediction for AAPL: 0.5185777544975281
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47220200300216675
Calibrated prediction for ABB: 0.49531206488609314
Raw prediction for ABBV: 0.5078908205032349
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4015815556049347
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5185863971710205
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4900667667388916
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.618571937084198
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.31455495953559875
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46754446625709534
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.40584054589271545
Calibrated prediction for BAC: 0.5714285969734192
Raw prediction for BBL: 0.5081369876861572
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4704954922199249
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5106033086776733
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5589296817779541
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4498896300792694
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4769221246242523
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5471882820129395
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4362375736236572
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4118089973926544
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5372214913368225
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5280060172080994
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.58384770154953
Calibrated prediction for CHTR: 0.5703150629997253
Raw prediction for CMCSA: 0.5515244007110596
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.473993182182312
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5000490546226501
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4720216393470764
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.5360593199729919
Calibrated prediction for D: 0.529411792755127
Raw prediction for DHR: 0.5436356663703918
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5207647085189819
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.5200808048248291
Calibrated prediction for DUK: 0.5880694389343262
Raw prediction for EXC: 0.47929325699806213
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.543138861656189
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5177518129348755
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.4576413333415985
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534304141998291
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6107544898986816
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4946120083332062
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5488207340240479
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5048554539680481
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.44294044375419617
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.48114654421806335
Calibrated prediction for IEP: 0.4507042169570923
Raw prediction for INTC: 0.5238041877746582
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.49286943674087524
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5017005205154419
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4588623642921448
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5796661376953125
Calibrated prediction for LMT: 0.4864864945411682
Raw prediction for MA: 0.5444425344467163
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6070737242698669
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.48543640971183777
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5237253308296204
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4685893654823303
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.5005531907081604
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.441377729177475
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5377572774887085
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.4833686649799347
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4560050964355469
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.522346556186676
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.514655351638794
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4948010742664337
Calibrated prediction for PCLN: 0.5212342739105225
Raw prediction for PEP: 0.4832448661327362
Calibrated prediction for PEP: 0.4909090995788574
Raw prediction for PFE: 0.4984076917171478
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4159889221191406
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.4999821186065674
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5163000822067261
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5324128866195679
Calibrated prediction for PPL: 0.56117182970047
Raw prediction for PTR: 0.4641469120979309
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5869527459144592
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.507086455821991
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.7033238410949707
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.5077391862869263
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4815483093261719
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5413053631782532
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4453170895576477
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5211521983146667
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4953170418739319
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.49917078018188477
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.4653794467449188
Calibrated prediction for TOT: 0.5260158181190491
Raw prediction for TSM: 0.5195524096488953
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.44576868414878845
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3317944407463074
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.49399644136428833
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5175960063934326
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.4954533576965332
Calibrated prediction for UTX: 0.4891962707042694

Simulating Trading Days:  95%|█████████▌| 84/88 [08:33<00:05,  1.46s/it]

Raw prediction for V: 0.570576548576355
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.49389198422431946
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5018841624259949
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.515091598033905
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4585628807544708
Calibrated prediction for XOM: 0.4416404962539673
Investing 4455.462613693897 in RDS-B
Investing 2956.155528245068 in AGFS
Investing 1607.3157486186 in PM
Investing 4728.576585331368 in V
Investing 3029.414691212645 in JNJ
Investing 4832.650797688595 in DHR
Investing 6698.093339883384 in AMZN
Investing 6273.791616838688 in TSM
Investing 3538.696399345691 in DUK
Raw prediction for AAPL: 0.518578052520752
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47149839997291565
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5063186883926392
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.39746618270874023
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.519656777381897
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.48939037322998047
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6101469397544861
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3134622573852539
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4677823483943939
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.40937718749046326
Calibrated prediction for BAC: 0.5714285969734192
Raw prediction for BBL: 0.5086562037467957
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46972113847732544
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5108271837234497
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5701850652694702
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4535287916660309
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.476661741733551
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5467032194137573
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.44323697686195374
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.41289573907852173
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5368937253952026
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5309628844261169
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5905413031578064
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.5537289977073669
Calibrated prediction for CMCSA: 0.5143383145332336
Raw prediction for CODI: 0.4721851050853729
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5015294551849365
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.4853637218475342
Calibrated prediction for CVX: 0.5076923370361328
Raw prediction for D: 0.520317792892456
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5410780310630798
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5223779678344727
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.5134754776954651
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.47649767994880676
Calibrated prediction for EXC: 0.4722222089767456
Raw prediction for FB: 0.543327808380127
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5163077712059021
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45436763763427734
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534801244735718
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6054581999778748
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4897180199623108
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5434280633926392
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5044129490852356
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4427797794342041
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.4863142669200897
Calibrated prediction for IEP: 0.4507042169570923
Raw prediction for INTC: 0.5219963788986206
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4877282977104187
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5019514560699463
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45983731746673584
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.5908359885215759
Calibrated prediction for LMT: 0.5185185074806213
Raw prediction for MA: 0.5447406768798828
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6038855314254761
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.49846336245536804
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5252940654754639
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4624306261539459
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.4963622987270355
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.4418451189994812
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5402436852455139
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.47486811876296997
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.4532168209552765
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5207269191741943
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5150893926620483
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.49542924761772156
Calibrated prediction for PCLN: 0.5212342739105225
Raw prediction for PEP: 0.48473653197288513
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.49781346321105957
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.41682523488998413
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49966666102409363
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5169057250022888
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.528290331363678
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.459475576877594
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5864483714103699
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.506405234336853
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.7012677788734436
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.49757009744644165
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4794935882091522
Calibrated prediction for SNY: 0.5
Raw prediction for SO: 0.5414535403251648
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.44272714853286743
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5190807580947876
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.49516451358795166
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4938405156135559
Calibrated prediction for TM: 0.5
Raw prediction for TOT: 0.4602537453174591
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.512704610824585
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.445882648229599
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3305068910121918
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4838889539241791
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5201358199119568
Calibrated prediction for UPS: 0.4920634925365448

Simulating Trading Days:  97%|█████████▋| 85/88 [08:35<00:04,  1.46s/it]

Raw prediction for UTX: 0.49510595202445984
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5702230334281921
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.49249887466430664
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5019690990447998
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5249462127685547
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4551205039024353
Calibrated prediction for XOM: 0.43509554862976074
Investing 4456.461531036677 in RDS-B
Investing 2956.818300056023 in AGFS
Investing 1607.676109756338 in PM
Investing 4729.636734987486 in V
Investing 3030.0938877710955 in JNJ
Investing 4833.7342808444355 in DHR
Investing 6699.595056356149 in AMZN
Investing 6275.1982046151825 in TSM
Investing 2065.5082532522897 in NEE
Raw prediction for AAPL: 0.5184886455535889
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47094255685806274
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5050656199455261
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.3965226411819458
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5211874842643738
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4882809519767761
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.6077601909637451
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3113395869731903
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4678206443786621
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.4143871068954468
Calibrated prediction for BAC: 0.5714285969734192
Raw prediction for BBL: 0.5090125203132629
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46937915682792664
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5107603669166565
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5810584425926208
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4558006525039673
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.4764958322048187
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5464093685150146
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4519416391849518
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.4138792157173157
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5362123250961304
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5333818793296814
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.5961260795593262
Calibrated prediction for CHTR: 0.5757575631141663
Raw prediction for CMCSA: 0.555735170841217
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.46815037727355957
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.5005868673324585
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.49796968698501587
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.5066476464271545
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5378319621086121
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5217477083206177
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.5022332668304443
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.473940372467041
Calibrated prediction for EXC: 0.46435976028442383
Raw prediction for FB: 0.543563723564148
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5161439776420593
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45328399538993835
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.453406423330307
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6051912307739258
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.4862946569919586
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5361873507499695
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5037413835525513
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4425986707210541
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.49125468730926514
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.521121084690094
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4817056357860565
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5019675493240356
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.4598085284233093
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6021379828453064
Calibrated prediction for LMT: 0.5185185074806213
Raw prediction for MA: 0.5470668077468872
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.6014887690544128
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.505649209022522
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.526314377784729
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4583311080932617
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.49167346954345703
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.44188636541366577
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5418531894683838
Calibrated prediction for NEE: 0.5555555820465088
Raw prediction for NGG: 0.47266557812690735
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.44960907101631165
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5186004042625427
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5160167813301086
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4960695803165436
Calibrated prediction for PCLN: 0.5212342739105225
Raw prediction for PEP: 0.4862195551395416
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.4968145787715912
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.41708654165267944
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.49977585673332214
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5173780918121338
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5242289304733276
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.45403003692626953
Calibrated prediction for PTR: 0.42391303181648254
Raw prediction for RDS-B: 0.5804415941238403
Calibrated prediction for RDS-B: 0.6111587882041931
Raw prediction for REX: 0.5056933164596558
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6967449188232422
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4955892860889435
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4768374264240265
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5414773225784302
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.44397830963134766
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5171065926551819
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4949447214603424
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4911201298236847
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.4569409489631653
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5059071183204651
Calibrated prediction for TSM: 0.6132082343101501
Raw prediction for UL: 0.4456179738044739
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.3293132483959198
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4731900990009308
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5207118391990662
Calibrated prediction for UPS: 0.4920634925365448

Simulating Trading Days:  98%|█████████▊| 86/88 [08:36<00:02,  1.47s/it]

Raw prediction for UTX: 0.4952937662601471
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.5696219205856323
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.49354198575019836
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5022078156471252
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.529679536819458
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4540482759475708
Calibrated prediction for XOM: 0.43509554862976074
Investing 4458.91113198379 in RDS-B
Investing 2958.4435861395705 in AGFS
Investing 1608.5598074823663 in PM
Investing 4732.236493236231 in V
Investing 3031.7594515385895 in JNJ
Investing 4836.391258805534 in DHR
Investing 6703.277649436113 in AMZN
Investing 6278.64751778849 in TSM
Investing 2066.64360939487 in NEE
Raw prediction for AAPL: 0.5186494588851929
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.4707467257976532
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5039973855018616
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4015967845916748
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5223404765129089
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4869154095649719
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.604441225528717
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.30609309673309326
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.4676498770713806
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.4159065783023834
Calibrated prediction for BAC: 0.5714285969734192
Raw prediction for BBL: 0.5090100169181824
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.46932467818260193
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.5101221203804016
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5910908579826355
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.455601304769516
Calibrated prediction for BRK-A: 0.4464285671710968
Raw prediction for BSAC: 0.47641074657440186
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5485597252845764
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4558848738670349
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.41462981700897217
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5353386998176575
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5349512100219727
Calibrated prediction for CHL: 0.5247524976730347
Raw prediction for CHTR: 0.6008508801460266
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5578629970550537
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.46322324872016907
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.49946752190589905
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.5116521716117859
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.49351614713668823
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5366500020027161
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.5180410742759705
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.4867649972438812
Calibrated prediction for DUK: 0.5068492889404297
Raw prediction for EXC: 0.47162818908691406
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5436901450157166
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5202881097793579
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45367708802223206
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.45341455936431885
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6056610345840454
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.48396244645118713
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5251477956771851
Calibrated prediction for HON: 0.5634920597076416
Raw prediction for HRG: 0.5030441284179688
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.4422188997268677
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.49774205684661865
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5203255414962769
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.4756638705730438
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5013229250907898
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45962128043174744
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6266785264015198
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.548562228679657
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.5998711585998535
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5066347122192383
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.5252598524093628
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.45518752932548523
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.4895721971988678
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.437652587890625
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5423593521118164
Calibrated prediction for NEE: 0.5581396818161011
Raw prediction for NGG: 0.47319138050079346
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.44554948806762695
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.518057107925415
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.515123724937439
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.4967085123062134
Calibrated prediction for PCLN: 0.5212342739105225
Raw prediction for PEP: 0.4873659908771515
Calibrated prediction for PEP: 0.5
Raw prediction for PFE: 0.495731920003891
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4168233275413513
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.5000453591346741
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.5174328088760376
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.5216717720031738
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4472741186618805
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5727265477180481
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5048896670341492
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.6874079704284668
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4967605769634247
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.4741048216819763
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.5414736866950989
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.4465320408344269
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5161635279655457
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4947291612625122
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.49006688594818115
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.45169293880462646
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.5005548000335693
Calibrated prediction for TSM: 0.5
Raw prediction for UL: 0.4464423954486847
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.32683196663856506
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.4626621901988983
Calibrated prediction for UNH: 0.4819277226924896

Simulating Trading Days:  99%|█████████▉| 87/88 [08:38<00:01,  1.49s/it]

Raw prediction for UPS: 0.5188465714454651
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.49538207054138184
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.568854808807373
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.49744948744773865
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.502415657043457
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.5330967903137207
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4498276710510254
Calibrated prediction for XOM: 0.43509554862976074
Investing 2369.30582019857 in RDS-B
Investing 2960.4867962972876 in AGFS
Investing 1609.6707381600177 in PM
Investing 4735.504750138947 in V
Investing 3033.8532963346033 in JNJ
Investing 9172.813753851224 in LMT
Investing 8934.507485023121 in CHTR
Investing 4539.470048805304 in INTC
Investing 2203.957242739931 in NEE
Raw prediction for AAPL: 0.5189269185066223
Calibrated prediction for AAPL: 0.522911787033081
Raw prediction for ABB: 0.47057750821113586
Calibrated prediction for ABB: 0.4696768820285797
Raw prediction for ABBV: 0.5031161308288574
Calibrated prediction for ABBV: 0.5058823823928833
Raw prediction for AEP: 0.4196450114250183
Calibrated prediction for AEP: 0.4026344120502472
Raw prediction for AGFS: 0.5230565071105957
Calibrated prediction for AGFS: 0.5360358953475952
Raw prediction for AMGN: 0.4854353368282318
Calibrated prediction for AMGN: 0.5024599432945251
Raw prediction for AMZN: 0.5943072438240051
Calibrated prediction for AMZN: 0.6181818246841431
Raw prediction for BA: 0.3001154363155365
Calibrated prediction for BA: 0.4000000059604645
Raw prediction for BABA: 0.46726736426353455
Calibrated prediction for BABA: 0.467303991317749
Raw prediction for BAC: 0.41396066546440125
Calibrated prediction for BAC: 0.5714285969734192
Raw prediction for BBL: 0.5086275935173035
Calibrated prediction for BBL: 0.5106155872344971
Raw prediction for BCH: 0.4701262414455414
Calibrated prediction for BCH: 0.46558457612991333
Raw prediction for BHP: 0.508647084236145
Calibrated prediction for BHP: 0.5031564831733704
Raw prediction for BP: 0.5993123054504395
Calibrated prediction for BP: 0.5656565427780151
Raw prediction for BRK-A: 0.4538717269897461
Calibrated prediction for BRK-A: 0.4220716655254364
Raw prediction for BSAC: 0.4763917922973633
Calibrated prediction for BSAC: 0.48594197630882263
Raw prediction for BUD: 0.5530446767807007
Calibrated prediction for BUD: 0.5
Raw prediction for C: 0.4567190408706665
Calibrated prediction for C: 0.4392523467540741
Raw prediction for CAT: 0.41551607847213745
Calibrated prediction for CAT: 0.45101046562194824
Raw prediction for CELG: 0.5338781476020813
Calibrated prediction for CELG: 0.5396860837936401
Raw prediction for CHL: 0.5367581844329834
Calibrated prediction for CHL: 0.5339783430099487
Raw prediction for CHTR: 0.602822482585907
Calibrated prediction for CHTR: 0.6446646451950073
Raw prediction for CMCSA: 0.5589826107025146
Calibrated prediction for CMCSA: 0.5507246255874634
Raw prediction for CODI: 0.45977622270584106
Calibrated prediction for CODI: 0.4771241843700409
Raw prediction for CSCO: 0.4978782832622528
Calibrated prediction for CSCO: 0.5147929191589355
Raw prediction for CVX: 0.5223138332366943
Calibrated prediction for CVX: 0.5479452013969421
Raw prediction for D: 0.48808640241622925
Calibrated prediction for D: 0.4881889820098877
Raw prediction for DHR: 0.5359662175178528
Calibrated prediction for DHR: 0.5817272067070007
Raw prediction for DIS: 0.512026309967041
Calibrated prediction for DIS: 0.5283018946647644
Raw prediction for DUK: 0.4717061519622803
Calibrated prediction for DUK: 0.5054414868354797
Raw prediction for EXC: 0.47141504287719727
Calibrated prediction for EXC: 0.46325361728668213
Raw prediction for FB: 0.5435804128646851
Calibrated prediction for FB: 0.5397321581840515
Raw prediction for GD: 0.5250260829925537
Calibrated prediction for GD: 0.517510712146759
Raw prediction for GE: 0.45788535475730896
Calibrated prediction for GE: 0.4285714328289032
Raw prediction for GMRE: 0.4534144401550293
Calibrated prediction for GMRE: 0.4525027275085449
Raw prediction for GOOG: 0.6028867959976196
Calibrated prediction for GOOG: 0.5729166865348816
Raw prediction for HD: 0.48282888531684875
Calibrated prediction for HD: 0.4769230782985687
Raw prediction for HON: 0.5135575532913208
Calibrated prediction for HON: 0.5333333611488342
Raw prediction for HRG: 0.5024012923240662
Calibrated prediction for HRG: 0.5267831683158875
Raw prediction for HSBC: 0.442185640335083
Calibrated prediction for HSBC: 0.4444518983364105
Raw prediction for IEP: 0.5037575960159302
Calibrated prediction for IEP: 0.5192307829856873
Raw prediction for INTC: 0.5222603678703308
Calibrated prediction for INTC: 0.5933333039283752
Raw prediction for JNJ: 0.47102516889572144
Calibrated prediction for JNJ: 0.5476400852203369
Raw prediction for JPM: 0.5008695721626282
Calibrated prediction for JPM: 0.5195775628089905
Raw prediction for KO: 0.45947402715682983
Calibrated prediction for KO: 0.45985400676727295
Raw prediction for LMT: 0.6417636275291443
Calibrated prediction for LMT: 0.6721311211585999
Raw prediction for MA: 0.5482901334762573
Calibrated prediction for MA: 0.5569620132446289
Raw prediction for MCD: 0.5984936356544495
Calibrated prediction for MCD: 0.5977476239204407
Raw prediction for MDT: 0.5042855739593506
Calibrated prediction for MDT: 0.49242424964904785
Raw prediction for MMM: 0.523185670375824
Calibrated prediction for MMM: 0.5416079759597778
Raw prediction for MO: 0.4526592493057251
Calibrated prediction for MO: 0.46937939524650574
Raw prediction for MRK: 0.48792150616645813
Calibrated prediction for MRK: 0.4722222089767456
Raw prediction for MSFT: 0.430563747882843
Calibrated prediction for MSFT: 0.4094128906726837
Raw prediction for NEE: 0.5422390103340149
Calibrated prediction for NEE: 0.5573192238807678
Raw prediction for NGG: 0.4757741391658783
Calibrated prediction for NGG: 0.4375
Raw prediction for NVS: 0.44371962547302246
Calibrated prediction for NVS: 0.4566338360309601
Raw prediction for ORCL: 0.5162320137023926
Calibrated prediction for ORCL: 0.5721595287322998
Raw prediction for PCG: 0.5143272280693054
Calibrated prediction for PCG: 0.49035224318504333
Raw prediction for PCLN: 0.497145414352417
Calibrated prediction for PCLN: 0.5212342739105225
Raw prediction for PEP: 0.48843294382095337
Calibrated prediction for PEP: 0.5010351538658142
Raw prediction for PFE: 0.4944579601287842
Calibrated prediction for PFE: 0.4881695508956909
Raw prediction for PG: 0.4167822003364563
Calibrated prediction for PG: 0.41960060596466064
Raw prediction for PICO: 0.500472366809845
Calibrated prediction for PICO: 0.48641470074653625
Raw prediction for PM: 0.517300546169281
Calibrated prediction for PM: 0.5296733975410461
Raw prediction for PPL: 0.521551787853241
Calibrated prediction for PPL: 0.5354330539703369
Raw prediction for PTR: 0.4409545958042145
Calibrated prediction for PTR: 0.4124999940395355
Raw prediction for RDS-B: 0.5637746453285217
Calibrated prediction for RDS-B: 0.5723684430122375
Raw prediction for REX: 0.5043221712112427
Calibrated prediction for REX: 0.5118483304977417
Raw prediction for SLB: 0.669766902923584
Calibrated prediction for SLB: 0.5435546636581421
Raw prediction for SNP: 0.4970052242279053
Calibrated prediction for SNP: 0.5460165739059448
Raw prediction for SNY: 0.47159457206726074
Calibrated prediction for SNY: 0.44897958636283875
Raw prediction for SO: 0.541413426399231
Calibrated prediction for SO: 0.5455653071403503
Raw prediction for SPLP: 0.45056116580963135
Calibrated prediction for SPLP: 0.4380781352519989
Raw prediction for SRE: 0.5171214938163757
Calibrated prediction for SRE: 0.5353535413742065
Raw prediction for T: 0.4945688545703888
Calibrated prediction for T: 0.4953271150588989
Raw prediction for TM: 0.4909207224845886
Calibrated prediction for TM: 0.4833333194255829
Raw prediction for TOT: 0.44713908433914185
Calibrated prediction for TOT: 0.5
Raw prediction for TSM: 0.4945705533027649
Calibrated prediction for TSM: 0.4761904776096344

Simulating Trading Days: 100%|██████████| 88/88 [08:39<00:00,  5.91s/it]

Raw prediction for UL: 0.4453590214252472
Calibrated prediction for UL: 0.4285714328289032
Raw prediction for UN: 0.32286760210990906
Calibrated prediction for UN: 0.3459798991680145
Raw prediction for UNH: 0.45184147357940674
Calibrated prediction for UNH: 0.4819277226924896
Raw prediction for UPS: 0.5156669020652771
Calibrated prediction for UPS: 0.4920634925365448
Raw prediction for UTX: 0.49476179480552673
Calibrated prediction for UTX: 0.4891962707042694
Raw prediction for V: 0.567950963973999
Calibrated prediction for V: 0.5828738808631897
Raw prediction for VZ: 0.49981826543807983
Calibrated prediction for VZ: 0.5337837934494019
Raw prediction for WFC: 0.5027205944061279
Calibrated prediction for WFC: 0.4878625273704529
Raw prediction for WMT: 0.536789059638977
Calibrated prediction for WMT: 0.5
Raw prediction for XOM: 0.4498571753501892
Calibrated prediction for XOM: 0.43509554862976074
Investing 2371.831442676566 in RDS-B
Investing 2963.642603342033 in AGFS
Investing 1611.3866080843693 in PM
Investing 4740.552683225359 in V
Investing 3037.0873102870623 in JNJ
Investing 9182.591750598496 in LMT
Investing 8944.03145307386 in CHTR
Investing 4544.309013659783 in INTC
Investing 2163.11637706716 in NEE

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-28,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
1,2017-05-01,100100.905595,70070.633916,100100.905595,100100.905595,100.905595,0.001009,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
2,2017-05-02,100301.168945,70210.818261,100301.168945,100301.168945,200.263350,0.002001,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
3,2017-05-03,100254.188091,70177.931664,100254.188091,100254.188091,-46.980853,-0.000468,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
4,2017-05-04,100513.392930,70359.375051,100513.392930,100513.392930,259.204839,0.002585,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
...,...,...,...,...,...,...,...,...
83,2017-08-25,101608.843665,71126.190566,101608.843665,101608.843665,-11.610136,-0.000114,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
84,2017-08-28,101631.624428,71142.137100,101631.624428,101631.624428,22.780763,0.000224,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
85,2017-08-29,101687.488688,71181.242081,101687.488688,101687.488688,55.864260,0.000550,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
86,2017-08-30,101757.717814,71230.402470,101757.717814,101757.717814,70.229127,0.000691,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
87,2017-08-31,101866.189071,101866.189071,101866.189071,101866.189071,108.471257,0.001066,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-28,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
1,2017-05-01,100100.905595,70070.633916,100100.905595,100100.905595,100.905595,0.001009,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
2,2017-05-02,100301.168945,70210.818261,100301.168945,100301.168945,200.263350,0.002001,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
3,2017-05-03,100254.188091,70177.931664,100254.188091,100254.188091,-46.980853,-0.000468,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
4,2017-05-04,100513.392930,70359.375051,100513.392930,100513.392930,259.204839,0.002585,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
...,...,...,...,...,...,...,...,...
83,2017-08-25,101608.843665,71126.190566,101608.843665,101608.843665,-11.610136,-0.000114,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
84,2017-08-28,101631.624428,71142.137100,101631.624428,101631.624428,22.780763,0.000224,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
85,2017-08-29,101687.488688,71181.242081,101687.488688,101687.488688,55.864260,0.000550,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
86,2017-08-30,101757.717814,71230.402470,101757.717814,101757.717814,70.229127,0.000691,"[{'ticker': 'LMT', 'investment_fraction': 0.09..."
87,2017-08-31,101866.189071,101866.189071,101866.189071,101866.189071,108.471257,0.001066,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $101,866.19
Total Return on Investment (ROI): 1.87%
Annualized Sharpe Ratio: 1.61
--------------------------

In [31]:
master_df_with_target = add_horizon_targets(master_df.copy(), H=1, price_col="close")
ret_col = f"ret_{1}d"

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    # Sector aggregates
    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        # top sectors by pnl
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
         # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 417
Total capital allocated: $2,636,270.44
Average position size:  $6,321.99
Completed trades with returns: 417
Winning trades: 229 (54.9%)
Losing trades:  184 (44.1%)
Total PnL: $1,866.19
Average PnL per trade: $4.48
Average return: 0.06%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Industrial Goods,82,639916.344752,7803.857863,915.412567,11.163568,0.001142
Services,87,813407.894681,9349.516031,847.431038,9.740587,0.001339
Financial,42,179419.136400,4271.884200,288.818068,6.876621,0.001472
Consumer Goods,5,15802.553681,3160.510736,286.467742,57.293548,0.009260
Healthcare,32,106585.306818,3330.790838,112.753283,3.523540,0.000208
Basic Matierials,23,76284.519223,3316.718227,43.547544,1.893371,-0.000041
Conglomerates,17,43206.432676,2541.554863,-12.376076,-0.728004,-0.003481
Technology,85,512565.314926,6030.180176,-244.654459,-2.878288,0.000475
Utilities,44,249082.931924,5660.975726,-371.210637,-8.436605,-0.001013

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
88,2017-05-23,2017-05-24,CHTR,Services,8829.380601,0.644665,NaN,0.032153,283.889547
180,2017-06-15,2017-06-16,AMZN,Services,11437.369715,0.716975,NaN,0.024415,279.241352
22,2017-05-03,2017-05-04,BUD,Consumer Goods,4488.401624,0.578947,NaN,0.056883,255.311590
279,2017-07-24,2017-07-25,MCD,Services,4645.738130,0.597748,NaN,0.047547,220.890567
216,2017-07-03,2017-07-05,AMZN,Services,11366.310015,0.716975,NaN,0.018602,211.436912
227,2017-07-07,2017-07-10,AMZN,Services,11439.746784,0.716975,NaN,0.018094,206.994020
167,2017-06-12,2017-06-13,AMZN,Services,11306.306294,0.714286,NaN,0.016457,186.073526
72,2017-05-18,2017-05-19,LMT,Industrial Goods,9001.267986,0.672131,NaN,0.020462,184.187313
344,2017-08-11,2017-08-14,AMZN,Services,11522.499763,0.716975,NaN,0.015816,182.243050
185,2017-06-16,2017-06-19,GOOG,Technology,9653.556316,0.671248,NaN,0.018717,180.686674

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
338,2017-08-09,2017-08-10,AMZN,Services,11556.021073,0.716975,NaN,-0.025550,-295.252470
31,2017-05-05,2017-05-08,CHTR,Services,8831.161909,0.644665,NaN,-0.032768,-289.377667
203,2017-06-26,2017-06-27,GOOG,Technology,9668.739235,0.671248,NaN,-0.026190,-253.224800
209,2017-06-28,2017-06-29,GOOG,Technology,9654.745464,0.671248,NaN,-0.024136,-233.030484
311,2017-07-28,2017-07-31,AMZN,Services,6692.369463,0.618182,NaN,-0.031626,-211.653957
354,2017-08-16,2017-08-17,AMZN,Services,11568.789013,0.716975,NaN,-0.018003,-208.270680
154,2017-06-08,2017-06-09,NGG,Utilities,7956.735048,0.661446,NaN,-0.025127,-199.930042
201,2017-06-26,2017-06-27,AMZN,Services,11484.837435,0.716975,NaN,-0.017304,-198.735030
63,2017-05-16,2017-05-17,CHTR,Services,8805.589089,0.644665,NaN,-0.021562,-189.865263
109,2017-05-30,2017-05-31,NGG,Utilities,6678.283960,0.636364,NaN,-0.025743,-171.919797

TOP 10 SECTORS BY TOTAL PnL

                   total_pnl
sector
Industrial Goods  915.412567
Services          847.431038
Financial         288.818068
Consumer Goods    286.467742
Healthcare        112.753283
Basic Matierials   43.547544
Conglomerates     -12.376076
Technology       -244.654459
Utilities        -371.210637

BOTTOM 10 SECTORS BY TOTAL PnL

                   total_pnl
sector
Industrial Goods  915.412567
Services          847.431038
Financial         288.818068
Consumer Goods    286.467742
Healthcare        112.753283
Basic Matierials   43.547544
Conglomerates     -12.376076
Technology       -244.654459
Utilities        -371.210637

Top 10 Most Invested Tickers:

ticker
AMZN     61
LMT      60
GOOG     41
INTC     27
MA       25
NVS      19
DHR      19
TSM      17
V        17
RDS-B    17
Name: count, dtype: int64

Tickers Never Invested In (62):
{'BA', 'AMGN', 'MRK', 'EXC', 'REX', 'FB', 'ABB', 'BRK-A', 'PEP', 'SLB', 'VZ', 'CAT', 'SO', 'XOM', 'KO', 'PG', 'SNP', 'ORCL', 'HRG', 'TM', 'PFE', 'CELG', 'HSBC', 'SRE', 'GE', 'CHL', 'CODI', 'UTX', 'PCG', 'UPS', 'T', 'CVX', 'PICO', 'SPLP', 'CMCSA', 'GMRE', 'TOT', 'JPM', 'BABA', 'SNY', 'PTR', 'DIS', 'PCLN', 'MSFT', 'UNH', 'UL', 'CSCO', 'WFC', 'BCH', 'WMT', 'BHP', 'MO', 'AAPL', 'BAC', 'HON', 'ABBV', 'C', 'MDT', 'BBL', 'UN', 'BSAC', 'GD'}

In [32]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]