# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from torch.optim.lr_scheduler import ReduceLROnPlateau

### Configurations

In [7]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 783  # Number of days to use for initial training only
KELLY_FRACTION = 0.25
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [8]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.25   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [9]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [10]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [11]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # End current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [12]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [13]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [14]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [15]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [16]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [17]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [18]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [19]:
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.from_numpy(X.astype(np.float32))
        self.y = torch.from_numpy(y.astype(np.float32))
    def __len__(self): return self.X.shape[0]
    def __getitem__(self, idx): return self.X[idx], self.y[idx]

class LSTMClassifier(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, use_layernorm=False):
        super().__init__()
        self.lstm1 = nn.LSTM(
            input_size=n_features, hidden_size=hidden1,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )
        self.inter_drop = nn.Dropout(p=inter_dropout)  # proxy for recurrent_dropout
        self.lstm2 = nn.LSTM(
            input_size=hidden1, hidden_size=hidden2,
            num_layers=1, batch_first=True, bidirectional=False, dropout=0.1
        )

        # Normalization after temporal pooling
        self.use_layernorm = bool(use_layernorm)
        if self.use_layernorm:
            self.norm = nn.LayerNorm(normalized_shape=hidden2)
        else:
            self.norm = nn.BatchNorm1d(num_features=hidden2)

        # Head
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(p=dropout)
        self.fc_out = nn.Linear(fc, 1)  # logits

    def forward(self, x):
        # x: (B, T, F)
        out1, _ = self.lstm1(x)     # (B, T, hidden1)
        out1 = self.inter_drop(out1)
        out2, _ = self.lstm2(out1)  # (B, T, hidden2)

        last = out2[:, -1, :]       # (B, hidden2)
        if isinstance(self.norm, nn.BatchNorm1d):
            last = self.norm(last)  # BN expects (B, C)
        else:
            last = self.norm(last)  # LN expects (B, C)

        z = self.fc1(last)
        z = self.relu(z)
        z = self.drop(z)
        logits = self.fc_out(z).squeeze(-1)  # (B,)
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [20]:
from matplotlib import ticker


def train_company_models(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         sequence_length: int = None,
                         H = 1):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    #sequence length & guards
    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)

    if len(company_data_df) < sequence_length + H + 10:
        print(f"Not enough data for {ticker}.")
        return False, sequence_length

    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        print(f"No contiguous periods found for {ticker}.")
        return False, sequence_length

    # build sequences
    targets = company_data_df[f'target_{H}d'].values
    X, y = create_contiguous_sequences(
        company_data_df[feature_cols].values,
        targets,
        contiguous_periods,
        sequence_length,
        H
    )
    print(f"Created {len(X)} sequences for {ticker}.")
    if len(X) < 2:
        return False, sequence_length

    # chronological split (no shuffle)
    X_train, X_val, y_train, y_val = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    # scale features (fit on train, transform both)
    scaler = MinMaxScaler()
    F = X_train.shape[-1]
    X_train_scaled = scaler.fit_transform(X_train.reshape(-1, F)).reshape(X_train.shape)
    X_val_scaled   = scaler.transform(  X_val.reshape(-1, F)).reshape(X_val.shape)
    
    print(f"[TRAIN] {ticker}: scaler fitted on {X_train.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_train has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    sector_feature_indices = [feature_cols.index('sector_ret_1d'),
                          feature_cols.index('sector_ret_5d'),
                          feature_cols.index('sector_vol_20d')]

    print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")

    # Keras fit used the scaled data
    train_ds = SequenceDataset(X_train_scaled, y_train)
    val_ds   = SequenceDataset(X_val_scaled,   y_val)

    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  drop_last=False)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_train.shape[-1]
    model = LSTMClassifier(n_features=n_features, dropout=0.3, inter_dropout=0.1).to(device)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)  # clipnorm via grad clipping below
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)
    early = EarlyStopper(patience=15, mode='min')

    for epoch in range(100):
        model.train()
        total_loss = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # clipnorm=1.0
            optimizer.step()
            total_loss += loss.item() * xb.size(0)

        train_loss = total_loss / len(train_loader.dataset)
        val_loss, _ = _evaluate(model, val_loader, device, loss_fn)

        scheduler.step(val_loss)  # ReduceLROnPlateau on val_loss

        # EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:  # stop after 'patience' non-improve epochs
            break

    # restore best weights
    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    # final validation pass for isotonic calibration (on scaled val data)
    _, validation_predictions = _evaluate(model, val_loader, device, loss_fn)

    # Keras code used 10% buffer (comment said 5%)
    pred_min, pred_max = validation_predictions.min(), validation_predictions.max()
    buffer = 0.05 * (pred_max - pred_min)
    y_min_dynamic = max(0.0, pred_min - buffer)
    y_max_dynamic = min(1.0, pred_max + buffer)

    calibrator = IsotonicRegression(y_min=y_min_dynamic, y_max=y_max_dynamic, out_of_bounds='clip')
    calibrator.fit(validation_predictions, y_val.astype(float))

    # inside train_company_models(..., H=H)
    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt"))
    joblib.dump(calibrator,      os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
    joblib.dump(scaler,          os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


    del model, scaler, calibrator, train_loader, val_loader, train_ds, val_ds
    del X_train, X_val, y_train, y_val, X_train_scaled, X_val_scaled
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [21]:
def predict_next_horizon(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 H: int) -> dict | None:

    try:
        # load artifacts
        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstm_H{H}.pt")
        calibrator = joblib.load(os.path.join(model_save_path, f"{ticker}_calibrator_H{H}.pkl"))
        scaler     = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        sequence_length    = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))


        if not os.path.isfile(state_dict_path):
            return None
        
        if hasattr(scaler, "n_features_in_") and scaler.n_features_in_ != len(feature_cols):
            return None

        # build model skeleton with correct input dim, then load weights
        n_features = len(feature_cols)
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        model = LSTMClassifier(n_features=n_features).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    # find the last contiguous block and take the most recent sequence_length rows
    contiguous_periods = identify_contiguous_periods(company_data_df)
    if not contiguous_periods:
        return None

    last_start, last_end = contiguous_periods[-1]
    period_data = company_data_df.iloc[last_start:last_end + 1]
    if len(period_data) < sequence_length:
        return None

    last_sequence = period_data.tail(sequence_length)

    # scale using the saved scaler (fit  train only)
    # ensure column order matches training
    try:
        scaled_features = scaler.transform(last_sequence[feature_cols])
    except Exception:
        return None

    # shape: (1, T, F) as float32 tensor
    x = torch.from_numpy(np.asarray([scaled_features], dtype=np.float32)).to(device)

    with torch.no_grad():
        logits = model(x)                  # shape (1,)
        prob = torch.sigmoid(logits).item()  # scalar in [0,1]

    # isotonic calibration (expects iterable)
    calibrated = float(calibrator.predict([prob])[0])

    print(f"Raw prediction for {ticker}: {prob}")
    print(f"Calibrated prediction for {ticker}: {calibrated}")

    return {
        'ticker': ticker,
        'raw_prediction': prob,
        'calibrated_prediction': calibrated
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [22]:
def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                            total_capital: float, sector_threshold: float,
                            kelly_fraction: float) -> pd.DataFrame:

    investment_decisions = []

    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing. Threshold={sector_threshold:.3f}, Kelly frac={kelly_fraction:.3f}")

    for sector, group in daily_predictions_df.groupby('sector'):
        avg_sector_score = group['calibrated_prediction'].mean()
        print(f"[PORT] Sector {sector}: {len(group)} candidates, avg score={avg_sector_score:.3f}")
        if avg_sector_score < sector_threshold:
            print(f"[PORT] Sector {sector}: filtered out by confidence threshold")
            continue

        best_stock_in_sector = group.loc[group['calibrated_prediction'].idxmax()]
        ticker = best_stock_in_sector['ticker']
        p = best_stock_in_sector['calibrated_prediction']
        b_info = payout_map.get(ticker, 0.0)
        b = (b_info['b'] if isinstance(b_info, dict) else float(b_info))
        if not np.isfinite(b) or b <= 0:
            print(f"[PORT] Sector {sector}: skipping {ticker} due to invalid payout b={b}")
            continue

        if not b_info or not np.isfinite(b_info.get('b', np.nan)):
            print(f"[PORT] Sector {sector}: missing payout info for {ticker}")
            continue
        b = max(b_info['b'], 1e-6)  # avoid div-by-zero
        kelly_percentage = p - (1 - p) / b

        if kelly_percentage <= 0:
            print(f"[PORT] Sector {sector}: Kelly <= 0 for {ticker} (p={p:.3f}, b={b:.3f})")
            continue

        investment_fraction = kelly_percentage * kelly_fraction
        investment_amount = total_capital * investment_fraction

        if investment_amount < MIN_TRADE_DOLLARS:
            print(f"[PORT] Sector {sector}: allocation ${investment_amount:.2f} below minimum for {ticker}")
            continue

        print(f"[PORT] Sector {sector}: selecting {ticker} (p={p:.3f}, b={b:.3f}, kelly={kelly_percentage:.3f}) with ${investment_amount:.2f}")

        investment_decisions.append({
            'ticker': ticker,
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount,
            'predicted_prob': p
        })

    if not investment_decisions:
        print("[PORT] All candidates rejected after sizing/filters.")

    return pd.DataFrame(investment_decisions)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [23]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    files = [
        f"{ticker}_lstm_H{H}.pt",
        f"{ticker}_calibrator_H{H}.pkl",
        f"{ticker}_scaler_H{H}.pkl",
        f"{ticker}_seq_length_H{H}.pkl",
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in files)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [24]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # returns used for settlement only; not for training
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker','date'])[ret_col].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    open_positions = []
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                if pd.notna(rH):
                    pnl = pos['invest'] * rH
                    total_pnl_today += pnl
                    capital += pos['invest'] + pnl
            else:
                still_open.append(pos)
        open_positions = still_open

        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # historical slice strictly before current_date; recompute targets locally
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if i == 0:
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if not have_models or need_retrain:
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)

        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df, payout_map_day, capital, SECTOR_CONFIDENCE_THRESHOLD, KELLY_FRACTION
        )

        exit_idx = i + H
        exit_date = unique_dates[exit_idx] if exit_idx < len(unique_dates) else None

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)

            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue

                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))

                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})

        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,
            'capital_end': capital,
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [25]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [26]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_and_bimeta_features.parquet')

In [27]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)
# Exclude ticker with missing meta-features across all rows
master_df = master_df[master_df['ticker'] != 'GMRE']

columns_to_check = ['EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    'lstm_prob_up_1d', 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [28]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    # 'lstm_prob_up_1d', 
    # 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 
    # 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength', 'gru_pred_ret_1d']
Total number of features: 29

In [29]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [30]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=1,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Starting simulation with 783 initial training days... (H=1)
Starting predictions from day 783 (after 783 training days)

Simulating Trading Days:   0%|          | 0/100 [00:00<?, ?it/s]

Created 770 sequences for AAPL.
[TRAIN] AAPL: scaler fitted on 616 training sequences
[TRAIN] AAPL: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] AAPL: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] AAPL: sector feature maxs = [0.03194691 0.05042416 0.01893123]
Raw prediction for AAPL: 0.4934487044811249
Calibrated prediction for AAPL: 0.4895158112049103
Created 770 sequences for ABB.
[TRAIN] ABB: scaler fitted on 616 training sequences
[TRAIN] ABB: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] ABB: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] ABB: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for ABB: 0.5154024958610535
Calibrated prediction for ABB: 0.5300073027610779
Created 708 sequences for ABBV.
[TRAIN] ABBV: scaler fitted on 566 training sequences
[TRAIN] ABBV: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] ABBV: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] ABBV: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for ABBV: 0.456821471452713
Calibrated prediction for ABBV: 0.46666666865348816
Created 770 sequences for AEP.
[TRAIN] AEP: scaler fitted on 616 training sequences
[TRAIN] AEP: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] AEP: sector feature mins = [-0.04000807 -0.08164836  0.00493882]
[TRAIN] AEP: sector feature maxs = [0.02833403 0.06078573 0.01557388]
Raw prediction for AEP: 0.5357863306999207
Calibrated prediction for AEP: 0.5263158082962036
Created 232 sequences for AGFS.
[TRAIN] AGFS: scaler fitted on 185 training sequences
[TRAIN] AGFS: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] AGFS: sector feature mins = [-0.21470837 -0.24019047  0.00476725]
[TRAIN] AGFS: sector feature maxs = [0.35098106 0.39009354 0.07892018]
Raw prediction for AGFS: 0.4909098744392395
Calibrated prediction for AGFS: 0.4911747872829437
Created 770 sequences for AMGN.
[TRAIN] AMGN: scaler fitted on 616 training sequences
[TRAIN] AMGN: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] AMGN: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] AMGN: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for AMGN: 0.49056553840637207
Calibrated prediction for AMGN: 0.4965362250804901
Created 770 sequences for AMZN.
[TRAIN] AMZN: scaler fitted on 616 training sequences
[TRAIN] AMZN: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] AMZN: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] AMZN: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for AMZN: 0.5290002822875977
Calibrated prediction for AMZN: 0.48571428656578064
Created 770 sequences for BA.
[TRAIN] BA: scaler fitted on 616 training sequences
[TRAIN] BA: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BA: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] BA: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for BA: 0.46156755089759827
Calibrated prediction for BA: 0.4838709533214569
Created 276 sequences for BABA.
[TRAIN] BABA: scaler fitted on 220 training sequences
[TRAIN] BABA: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BABA: sector feature mins = [-0.06810713 -0.07017512  0.00432136]
[TRAIN] BABA: sector feature maxs = [0.03499886 0.13521497 0.025178  ]
Raw prediction for BABA: 0.5147371888160706
Calibrated prediction for BABA: 0.51587975025177
Created 770 sequences for BAC.
[TRAIN] BAC: scaler fitted on 616 training sequences
[TRAIN] BAC: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BAC: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BAC: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for BAC: 0.4980965852737427
Calibrated prediction for BAC: 0.49456852674484253
Created 770 sequences for BBL.
[TRAIN] BBL: scaler fitted on 616 training sequences
[TRAIN] BBL: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BBL: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BBL: sector feature maxs = [0.05341933 0.13994116 0.03044324]
Raw prediction for BBL: 0.47410762310028076
Calibrated prediction for BBL: 0.546875
Created 770 sequences for BCH.
[TRAIN] BCH: scaler fitted on 616 training sequences
[TRAIN] BCH: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BCH: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BCH: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for BCH: 0.5434197187423706
Calibrated prediction for BCH: 0.49253731966018677
Created 770 sequences for BHP.
[TRAIN] BHP: scaler fitted on 616 training sequences
[TRAIN] BHP: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BHP: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BHP: sector feature maxs = [0.05341933 0.13994116 0.03044324]
Raw prediction for BHP: 0.4602595567703247
Calibrated prediction for BHP: 0.5
Created 770 sequences for BP.
[TRAIN] BP: scaler fitted on 616 training sequences
[TRAIN] BP: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BP: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BP: sector feature maxs = [0.05341933 0.13994116 0.03044324]
Raw prediction for BP: 0.5436075329780579
Calibrated prediction for BP: 0.5306122303009033
Created 770 sequences for BRK-A.
[TRAIN] BRK-A: scaler fitted on 616 training sequences
[TRAIN] BRK-A: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BRK-A: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BRK-A: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for BRK-A: 0.4249553382396698
Calibrated prediction for BRK-A: 0.4140874445438385
Created 770 sequences for BSAC.
[TRAIN] BSAC: scaler fitted on 616 training sequences
[TRAIN] BSAC: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BSAC: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BSAC: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for BSAC: 0.46862736344337463
Calibrated prediction for BSAC: 0.46436169743537903
Created 770 sequences for BUD.
[TRAIN] BUD: scaler fitted on 616 training sequences
[TRAIN] BUD: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] BUD: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] BUD: sector feature maxs = [0.03194691 0.05042416 0.01893123]
Raw prediction for BUD: 0.5913200974464417
Calibrated prediction for BUD: 0.48275861144065857
Created 770 sequences for C.
[TRAIN] C: scaler fitted on 616 training sequences
[TRAIN] C: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] C: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] C: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for C: 0.49447038769721985
Calibrated prediction for C: 0.4886363744735718
Created 770 sequences for CAT.
[TRAIN] CAT: scaler fitted on 616 training sequences
[TRAIN] CAT: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] CAT: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] CAT: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for CAT: 0.4713868498802185
Calibrated prediction for CAT: 0.4598650634288788
Created 770 sequences for CELG.
[TRAIN] CELG: scaler fitted on 616 training sequences
[TRAIN] CELG: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] CELG: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] CELG: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for CELG: 0.5762548446655273
Calibrated prediction for CELG: 0.6164138317108154
Created 770 sequences for CHL.
[TRAIN] CHL: scaler fitted on 616 training sequences
[TRAIN] CHL: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] CHL: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] CHL: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for CHL: 0.47918036580085754
Calibrated prediction for CHL: 0.4482758641242981
Created 770 sequences for CHTR.
[TRAIN] CHTR: scaler fitted on 616 training sequences
[TRAIN] CHTR: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] CHTR: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] CHTR: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for CHTR: 0.5462745428085327
Calibrated prediction for CHTR: 0.5287356376647949
Created 770 sequences for CMCSA.
[TRAIN] CMCSA: scaler fitted on 616 training sequences
[TRAIN] CMCSA: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] CMCSA: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] CMCSA: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for CMCSA: 0.4141395092010498
Calibrated prediction for CMCSA: 0.4105546772480011
Created 770 sequences for CODI.
[TRAIN] CODI: scaler fitted on 616 training sequences
[TRAIN] CODI: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] CODI: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] CODI: sector feature maxs = [0.35098106 0.39009354 0.07892018]
Raw prediction for CODI: 0.39303651452064514
Calibrated prediction for CODI: 0.37554362416267395
Created 770 sequences for CSCO.
[TRAIN] CSCO: scaler fitted on 616 training sequences
[TRAIN] CSCO: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] CSCO: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] CSCO: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for CSCO: 0.4880256652832031
Calibrated prediction for CSCO: 0.48795363306999207
Created 770 sequences for CVX.
[TRAIN] CVX: scaler fitted on 616 training sequences
[TRAIN] CVX: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] CVX: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] CVX: sector feature maxs = [0.05341933 0.13994116 0.03044324]
Raw prediction for CVX: 0.4609008729457855
Calibrated prediction for CVX: 0.4444444477558136
Created 770 sequences for D.
[TRAIN] D: scaler fitted on 616 training sequences
[TRAIN] D: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] D: sector feature mins = [-0.04000807 -0.08164836  0.00493882]
[TRAIN] D: sector feature maxs = [0.02833403 0.06078573 0.01557388]
Raw prediction for D: 0.5183514356613159
Calibrated prediction for D: 0.537190854549408
Created 770 sequences for DHR.
[TRAIN] DHR: scaler fitted on 616 training sequences
[TRAIN] DHR: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] DHR: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] DHR: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for DHR: 0.48024025559425354
Calibrated prediction for DHR: 0.47676196694374084
Created 770 sequences for DIS.
[TRAIN] DIS: scaler fitted on 616 training sequences
[TRAIN] DIS: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] DIS: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] DIS: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for DIS: 0.5110018849372864
Calibrated prediction for DIS: 0.5080798864364624
Created 770 sequences for DUK.
[TRAIN] DUK: scaler fitted on 616 training sequences
[TRAIN] DUK: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] DUK: sector feature mins = [-0.04000807 -0.08164836  0.00493882]
[TRAIN] DUK: sector feature maxs = [0.02833403 0.06078573 0.01557388]
Raw prediction for DUK: 0.5684854984283447
Calibrated prediction for DUK: 0.6087533831596375
Created 770 sequences for EXC.
[TRAIN] EXC: scaler fitted on 616 training sequences
[TRAIN] EXC: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] EXC: sector feature mins = [-0.04000807 -0.08164836  0.00493882]
[TRAIN] EXC: sector feature maxs = [0.02833403 0.06078573 0.01557388]
Raw prediction for EXC: 0.5071066617965698
Calibrated prediction for EXC: 0.508815586566925
Created 770 sequences for FB.
[TRAIN] FB: scaler fitted on 616 training sequences
[TRAIN] FB: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] FB: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] FB: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for FB: 0.5200826525688171
Calibrated prediction for FB: 0.5195395946502686
Created 770 sequences for GD.
[TRAIN] GD: scaler fitted on 616 training sequences
[TRAIN] GD: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] GD: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] GD: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for GD: 0.5139558911323547
Calibrated prediction for GD: 0.5108832716941833
Created 770 sequences for GE.
[TRAIN] GE: scaler fitted on 616 training sequences
[TRAIN] GE: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] GE: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] GE: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for GE: 0.4712853729724884
Calibrated prediction for GE: 0.4675324559211731
Created 770 sequences for GOOG.
[TRAIN] GOOG: scaler fitted on 616 training sequences
[TRAIN] GOOG: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] GOOG: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] GOOG: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for GOOG: 0.6125202178955078
Calibrated prediction for GOOG: 0.6363636255264282
Created 770 sequences for HD.
[TRAIN] HD: scaler fitted on 616 training sequences
[TRAIN] HD: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] HD: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] HD: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for HD: 0.4509512484073639
Calibrated prediction for HD: 0.44056737422943115
Created 770 sequences for HON.
[TRAIN] HON: scaler fitted on 616 training sequences
[TRAIN] HON: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] HON: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] HON: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for HON: 0.5267314314842224
Calibrated prediction for HON: 0.5290878415107727
Created 770 sequences for HRG.
[TRAIN] HRG: scaler fitted on 616 training sequences
[TRAIN] HRG: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] HRG: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] HRG: sector feature maxs = [0.35098106 0.39009354 0.07892018]
Raw prediction for HRG: 0.6399234533309937
Calibrated prediction for HRG: 0.6500897407531738
Created 770 sequences for HSBC.
[TRAIN] HSBC: scaler fitted on 616 training sequences
[TRAIN] HSBC: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] HSBC: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] HSBC: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for HSBC: 0.49578261375427246
Calibrated prediction for HSBC: 0.5232758522033691
Created 770 sequences for IEP.
[TRAIN] IEP: scaler fitted on 616 training sequences
[TRAIN] IEP: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] IEP: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] IEP: sector feature maxs = [0.35098106 0.39009354 0.07892018]
Raw prediction for IEP: 0.4926172196865082
Calibrated prediction for IEP: 0.5054945349693298
Created 770 sequences for INTC.
[TRAIN] INTC: scaler fitted on 616 training sequences
[TRAIN] INTC: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] INTC: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] INTC: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for INTC: 0.5145136117935181
Calibrated prediction for INTC: 0.5064935088157654
Created 770 sequences for JNJ.
[TRAIN] JNJ: scaler fitted on 616 training sequences
[TRAIN] JNJ: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] JNJ: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] JNJ: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for JNJ: 0.3424435555934906
Calibrated prediction for JNJ: 0.3636363744735718
Created 770 sequences for JPM.
[TRAIN] JPM: scaler fitted on 616 training sequences
[TRAIN] JPM: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] JPM: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] JPM: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for JPM: 0.5249449014663696
Calibrated prediction for JPM: 0.5448257327079773
Created 770 sequences for KO.
[TRAIN] KO: scaler fitted on 616 training sequences
[TRAIN] KO: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] KO: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] KO: sector feature maxs = [0.03194691 0.05042416 0.01893123]
Raw prediction for KO: 0.4397999048233032
Calibrated prediction for KO: 0.4374203383922577
Created 770 sequences for LMT.
[TRAIN] LMT: scaler fitted on 616 training sequences
[TRAIN] LMT: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] LMT: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] LMT: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for LMT: 0.5259900093078613
Calibrated prediction for LMT: 0.5426117777824402
Created 770 sequences for MA.
[TRAIN] MA: scaler fitted on 616 training sequences
[TRAIN] MA: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] MA: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] MA: sector feature maxs = [0.03246263 0.0680742  0.01782321]
Raw prediction for MA: 0.48998579382896423
Calibrated prediction for MA: 0.4821428656578064
Created 770 sequences for MCD.
[TRAIN] MCD: scaler fitted on 616 training sequences
[TRAIN] MCD: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] MCD: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] MCD: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
Raw prediction for MCD: 0.5584084391593933
Calibrated prediction for MCD: 0.5628662705421448
Created 770 sequences for MDT.
[TRAIN] MDT: scaler fitted on 616 training sequences
[TRAIN] MDT: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] MDT: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] MDT: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for MDT: 0.47930070757865906
Calibrated prediction for MDT: 0.47352921962738037
Created 770 sequences for MMM.
[TRAIN] MMM: scaler fitted on 616 training sequences
[TRAIN] MMM: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] MMM: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] MMM: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
Raw prediction for MMM: 0.6057080626487732
Calibrated prediction for MMM: 0.5652173757553101
Created 770 sequences for MO.
[TRAIN] MO: scaler fitted on 616 training sequences
[TRAIN] MO: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] MO: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] MO: sector feature maxs = [0.03194691 0.05042416 0.01893123]
Raw prediction for MO: 0.5177910923957825
Calibrated prediction for MO: 0.5736433863639832
Created 770 sequences for MRK.
[TRAIN] MRK: scaler fitted on 616 training sequences
[TRAIN] MRK: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] MRK: sector feature mins = [-0.0410257  -0.11491243  0.00396423]
[TRAIN] MRK: sector feature maxs = [0.04369867 0.0870226  0.02237914]
Raw prediction for MRK: 0.5025067329406738
Calibrated prediction for MRK: 0.5
Created 770 sequences for MSFT.
[TRAIN] MSFT: scaler fitted on 616 training sequences
[TRAIN] MSFT: scaler.n_features_in_ = 29, len(feature_cols) = 29
[TRAIN] MSFT: sector feature mins = [-0.0442555  -0.11070618  0.00542731]
[TRAIN] MSFT: sector feature maxs = [0.09751891 0.16866831 0.02562898]
Raw prediction for MSFT: 0.5043687224388123
Calibrated prediction for MSFT: 0.4886363744735718

Simulating Trading Days:   1%|          | 1/100 [04:14<7:00:26, 254.81s/it]

Raw prediction for XOM: 0.5049846172332764
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.979, kelly=0.084) with $2095.82
[PORT] Sector Conglomerates: 7 candidates, avg score=0.510
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.104, kelly=0.375) with $9387.08
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.495
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.989, kelly=0.147) with $3665.02
[PORT] Sector Financial: 10 candidates, avg score=0.499
[PORT] Sector Financial: selecting V (p=0.593, b=1.023, kelly=0.195) with $4863.26
[PORT] Sector Healthcare: 10 candidates, avg score=0.484
[PORT] Sector Healthcare: selecting CELG (p=0.616, b=1.017, kelly=0.239) with $5983.83
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.494
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.982, kelly=0.123) with $3063.96
[PORT] Sector Services: 10 candidates, avg score=0.514
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.039, kelly=0.219) with $5471.06
[PORT] Sector Technology: 10 candidates, avg score=0.507
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.063, kelly=0.294) with $7353.53
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.893, kelly=0.171) with $4270.07
Raw prediction for AAPL: 0.4928080439567566
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5160712003707886
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4531618654727936
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5368480086326599
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.49027320742607117
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.49038755893707275
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5382320284843445
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4608447551727295
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5147264003753662
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4979805648326874
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4647725820541382
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5404258966445923
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.46115201711654663
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5647512078285217
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.4278312027454376
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46866676211357117
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5910042524337769
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.49200212955474854
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.47039276361465454
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5714325904846191
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.48210757970809937
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.547203779220581
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.41230693459510803
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.38682985305786133
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4888004660606384
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4657328724861145
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.518112063407898
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4795728623867035
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5102470517158508
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5700594782829285
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5073462724685669
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5200092196464539
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5137705206871033
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.47457554936408997
Calibrated prediction for GE: 0.4675324559211731
Raw prediction for GOOG: 0.6225181818008423
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.44610849022865295
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5262801051139832
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6371592283248901
Calibrated prediction for HRG: 0.6500897407531738
Raw prediction for HSBC: 0.4927119314670563
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.49562373757362366
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5137969255447388
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3466574251651764
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5254244208335876
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.43876171112060547
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5259857773780823
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.48653146624565125
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5583522319793701
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4790790379047394
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6048240661621094
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5211336016654968
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5125980377197266
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.5072404742240906
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5346924066543579
Calibrated prediction for NEE: 0.5846154093742371
Raw prediction for NGG: 0.5098476409912109
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.49522164463996887
Calibrated prediction for NVS: 0.44999998807907104
Raw prediction for ORCL: 0.40959274768829346
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.5023618936538696
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5397455096244812
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5017830729484558
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5035684704780579
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4416956603527069
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4514167010784149
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.5051968097686768
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5034025311470032
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4604385793209076
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5085881948471069
Calibrated prediction for RDS-B: 0.5675675868988037
Raw prediction for REX: 0.5954431891441345
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4343820810317993
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49591144919395447
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.521576464176178
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.45321914553642273
Calibrated prediction for SO: 0.4141654372215271

Simulating Trading Days:   2%|▏         | 2/100 [04:16<2:52:33, 105.65s/it]

Raw prediction for SPLP: 0.397731751203537
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4622695744037628
Calibrated prediction for SRE: 0.47058823704719543
Raw prediction for T: 0.5111634135246277
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.599216103553772
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.4603121876716614
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5159116387367249
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.511216938495636
Calibrated prediction for UL: 0.4137931168079376
Raw prediction for UN: 0.5107285380363464
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.48773086071014404
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.537171483039856
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.47740814089775085
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.579443097114563
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.46330776810646057
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5172498226165771
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.5068284273147583
Calibrated prediction for WMT: 0.5454545617103577
Raw prediction for XOM: 0.5062375664710999
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.506
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.028, kelly=0.203) with $5057.06
[PORT] Sector Conglomerates: 7 candidates, avg score=0.510
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.103, kelly=0.375) with $9366.86
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.495
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.987, kelly=0.146) with $3643.19
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.593, b=1.026, kelly=0.196) with $4881.75
[PORT] Sector Healthcare: 10 candidates, avg score=0.483
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.019, kelly=0.138) with $3455.00
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.511
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.981, kelly=0.122) with $3039.87
[PORT] Sector Services: 10 candidates, avg score=0.514
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.040, kelly=0.219) with $5477.37
[PORT] Sector Technology: 10 candidates, avg score=0.507
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.065, kelly=0.295) with $7359.52
[PORT] Sector Utilities: 10 candidates, avg score=0.515
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.895, kelly=0.172) with $4284.68
Raw prediction for AAPL: 0.4920427203178406
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5167776942253113
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.45245909690856934
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5389993786811829
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4899751543998718
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4898393154144287
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5493066310882568
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4599728286266327
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5147882103919983
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49804016947746277
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.45247921347618103
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5398208498954773
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4590056836605072
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5820150375366211
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.43229708075523376
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4686714708805084
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.592066764831543
Calibrated prediction for BUD: 0.516323447227478
Raw prediction for C: 0.4887186288833618
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46955618262290955
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5605000853538513
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.4890163540840149
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5493078231811523
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.416172057390213
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.37908244132995605
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4893839657306671
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4710627496242523
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5195209383964539
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.47877973318099976
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.509590208530426
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5749348998069763
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5074946880340576
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.520004153251648
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5134846568107605
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.47455355525016785
Calibrated prediction for GE: 0.4675324559211731
Raw prediction for GOOG: 0.6325587034225464
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.44170746207237244
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5259328484535217
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6329847574234009
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4918877184391022
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.49858105182647705
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5137826204299927
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3523349463939667
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5259794592857361
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.4380396008491516
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.525043785572052
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4912846088409424
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.558514416217804
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4789726436138153
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6037722826004028
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5257606506347656
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5199140906333923
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.5112758874893188
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5359654426574707
Calibrated prediction for NEE: 0.5846154093742371
Raw prediction for NGG: 0.5084964036941528
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4976799190044403
Calibrated prediction for NVS: 0.44999998807907104
Raw prediction for ORCL: 0.41193491220474243
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.5019868612289429
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5423101782798767
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5017859935760498
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5064508318901062
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4414103329181671
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.455241322517395
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.5040385723114014
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5038418769836426
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46097037196159363
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5244608521461487
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5832282900810242
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.43254855275154114
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4962001442909241
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5219433307647705
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4599311649799347
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3860345184803009
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.45400702953338623
Calibrated prediction for SRE: 0.47058823704719543

Simulating Trading Days:   3%|▎         | 3/100 [04:17<1:33:36, 57.90s/it]

Raw prediction for T: 0.5198389887809753
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6007007956504822
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.45639368891716003
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5193406343460083
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.502652645111084
Calibrated prediction for UL: 0.4137931168079376
Raw prediction for UN: 0.48831847310066223
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.4789610505104065
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.538999617099762
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.47817206382751465
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5818873643875122
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.4645070433616638
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5188912153244019
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.50587397813797
Calibrated prediction for WMT: 0.5454545617103577
Raw prediction for XOM: 0.5071507692337036
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.507
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.026, kelly=0.202) with $5029.50
[PORT] Sector Conglomerates: 7 candidates, avg score=0.506
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.103, kelly=0.375) with $9354.05
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.499
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.987, kelly=0.146) with $3639.72
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.593, b=1.028, kelly=0.196) with $4897.16
[PORT] Sector Healthcare: 10 candidates, avg score=0.483
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.016, kelly=0.137) with $3426.02
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.511
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.983, kelly=0.123) with $3058.47
[PORT] Sector Services: 10 candidates, avg score=0.514
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.040, kelly=0.220) with $5472.68
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.063, kelly=0.294) with $7331.88
[PORT] Sector Utilities: 10 candidates, avg score=0.525
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.902, kelly=0.223) with $5557.15
Raw prediction for AAPL: 0.49109557271003723
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.517611563205719
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4533746540546417
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5409412384033203
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.48957860469818115
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4889083802700043
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5604486465454102
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45979395508766174
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5148767828941345
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4982757568359375
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4496937096118927
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5385087132453918
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4585680365562439
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.6040018796920776
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.4352884888648987
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4687357246875763
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5923599004745483
Calibrated prediction for BUD: 0.5314067602157593
Raw prediction for C: 0.4838078022003174
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4691055715084076
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5457745790481567
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.49063360691070557
Calibrated prediction for CHL: 0.5185101628303528
Raw prediction for CHTR: 0.5513806939125061
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4249975383281708
Calibrated prediction for CMCSA: 0.4371704161167145
Raw prediction for CODI: 0.3793669044971466
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4899313747882843
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.48239201307296753
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5192893147468567
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4781349003314972
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5091241598129272
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5806196331977844
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5074471235275269
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5200294256210327
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5130605101585388
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4805000424385071
Calibrated prediction for GE: 0.4675324559211731
Raw prediction for GOOG: 0.6378992795944214
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.44082969427108765
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5263164043426514
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6274552941322327
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4928446412086487
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.5034558773040771
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5135858654975891
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.35742464661598206
Calibrated prediction for JNJ: 0.37464192509651184
Raw prediction for JPM: 0.5265230536460876
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.43716058135032654
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5239027738571167
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.501292884349823
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5585819482803345
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47889190912246704
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6028144955635071
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5319513082504272
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5185448527336121
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.5147610306739807
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5326282978057861
Calibrated prediction for NEE: 0.5714285969734192
Raw prediction for NGG: 0.5062495470046997
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.5022526979446411
Calibrated prediction for NVS: 0.44999998807907104
Raw prediction for ORCL: 0.41301020979881287
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.501213788986206
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5450871586799622
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5017729997634888
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5080702304840088
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4407041668891907
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4573748707771301
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.5003761053085327
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5036879181861877
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4612056612968445
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.537774384021759
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5706436038017273
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4318619668483734
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49678945541381836
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5222063064575195
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4622729420661926
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3742925822734833
Calibrated prediction for SPLP: 0.4395604431629181

Simulating Trading Days:   4%|▍         | 4/100 [04:18<56:44, 35.46s/it]

Raw prediction for SRE: 0.4412565231323242
Calibrated prediction for SRE: 0.43770715594291687
Raw prediction for T: 0.5245213508605957
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6018357276916504
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.4665382504463196
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5221678018569946
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.48262158036231995
Calibrated prediction for UL: 0.3792762756347656
Raw prediction for UN: 0.46095630526542664
Calibrated prediction for UN: 0.404113233089447
Raw prediction for UNH: 0.47205498814582825
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5414313673973083
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.49476394057273865
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.584326982498169
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.4673056900501251
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5208142399787903
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.5049536228179932
Calibrated prediction for WMT: 0.5454545617103577
Raw prediction for XOM: 0.5083508491516113
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.507
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.026, kelly=0.202) with $5038.14
[PORT] Sector Conglomerates: 7 candidates, avg score=0.506
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.105, kelly=0.376) with $9392.33
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.492
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.986, kelly=0.146) with $3640.23
[PORT] Sector Financial: 10 candidates, avg score=0.496
[PORT] Sector Financial: selecting V (p=0.593, b=1.027, kelly=0.196) with $4889.87
[PORT] Sector Healthcare: 10 candidates, avg score=0.481
[PORT] Sector Healthcare: selecting MRK (p=0.545, b=1.006, kelly=0.093) with $2334.22
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.511
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.983, kelly=0.123) with $3071.82
[PORT] Sector Services: 10 candidates, avg score=0.517
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.042, kelly=0.220) with $5495.79
[PORT] Sector Technology: 10 candidates, avg score=0.515
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.065, kelly=0.295) with $7368.68
[PORT] Sector Utilities: 10 candidates, avg score=0.521
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.904, kelly=0.224) with $5587.14
Raw prediction for AAPL: 0.49030208587646484
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5184829831123352
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.45509105920791626
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5424050688743591
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.48909494280815125
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48851150274276733
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5751103758811951
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.46003955602645874
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5149351954460144
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49880215525627136
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4504736065864563
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5398863554000854
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.45710209012031555
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.6111046671867371
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.4363950788974762
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46887463331222534
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5944095849990845
Calibrated prediction for BUD: 0.6368734836578369
Raw prediction for C: 0.47966960072517395
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46882620453834534
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5343302488327026
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4905734658241272
Calibrated prediction for CHL: 0.5130433440208435
Raw prediction for CHTR: 0.5562793016433716
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.438711553812027
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.39203256368637085
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.49050667881965637
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.491342157125473
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5203084945678711
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4777470827102661
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5090903639793396
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5851444005966187
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5074612498283386
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5200759768486023
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5128147602081299
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4899781346321106
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.6464207172393799
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4456148147583008
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.526636004447937
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6232613921165466
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4978715479373932
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.5085251331329346
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5137867331504822
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3658336400985718
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5273451209068298
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.436608225107193
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5229225754737854
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5131681561470032
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5584260821342468
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47889378666877747
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6013319492340088
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5370780229568481
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5158585906028748
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.5159305930137634
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5261610150337219
Calibrated prediction for NEE: 0.5714285969734192
Raw prediction for NGG: 0.5050512552261353
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.5082926154136658
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.41370338201522827
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.5006542801856995
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5464280843734741
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.501607358455658
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5115209221839905
Calibrated prediction for PFE: 0.5190011858940125
Raw prediction for PG: 0.44008851051330566
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.46011415123939514
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.49836722016334534
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5031511187553406
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4615917205810547
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5407449007034302
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5565935969352722
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4317130744457245
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4976159632205963
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5223749876022339
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4620180130004883
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3675055205821991
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4293336570262909
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:   5%|▌         | 5/100 [04:19<36:30, 23.06s/it]

Raw prediction for T: 0.5253682136535645
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6000140309333801
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.4692818224430084
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5259681940078735
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4558171331882477
Calibrated prediction for UL: 0.3558844327926636
Raw prediction for UN: 0.43793052434921265
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.468729168176651
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5456079840660095
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5213204026222229
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5878555178642273
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.47301581501960754
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5247927904129028
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.5045067071914673
Calibrated prediction for WMT: 0.48243749141693115
Raw prediction for XOM: 0.5081890225410461
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.507
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.023, kelly=0.201) with $5020.44
[PORT] Sector Conglomerates: 7 candidates, avg score=0.506
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.108, kelly=0.377) with $9422.26
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.495
[PORT] Sector Consumer Goods: selecting BUD (p=0.637, b=1.037, kelly=0.287) with $7173.45
[PORT] Sector Financial: 10 candidates, avg score=0.511
[PORT] Sector Financial: selecting V (p=0.593, b=1.027, kelly=0.196) with $4899.02
[PORT] Sector Healthcare: 10 candidates, avg score=0.492
[PORT] Sector Healthcare: selecting MRK (p=0.545, b=1.004, kelly=0.093) with $2318.17
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.984, kelly=0.123) with $3084.09
[PORT] Sector Services: 10 candidates, avg score=0.513
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.043, kelly=0.221) with $5516.27
[PORT] Sector Technology: 10 candidates, avg score=0.523
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.067, kelly=0.466) with $11646.01
[PORT] Sector Utilities: 10 candidates, avg score=0.520
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.902, kelly=0.223) with $5579.10
Raw prediction for AAPL: 0.48966673016548157
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5198143124580383
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.45700517296791077
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5429815053939819
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4883934557437897
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4886425733566284
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5829004049301147
Calibrated prediction for AMZN: 0.6178990006446838
Raw prediction for BA: 0.4602191746234894
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5150412321090698
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49929094314575195
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.45509445667266846
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5375134944915771
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4576294720172882
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5999444723129272
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.4366380572319031
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46862611174583435
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5928859114646912
Calibrated prediction for BUD: 0.5584726929664612
Raw prediction for C: 0.4700860381126404
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4683363735675812
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.527449369430542
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.48387277126312256
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5620354413986206
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.45140916109085083
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.40957939624786377
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.49058860540390015
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.49417629837989807
Calibrated prediction for CVX: 0.4615384638309479
Raw prediction for D: 0.5211492776870728
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.47749122977256775
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5095529556274414
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5849260687828064
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5075536370277405
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5199559926986694
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5127171277999878
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.497609406709671
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.6298001408576965
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.4547985792160034
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5263822078704834
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6193690299987793
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.5005165338516235
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.5133822560310364
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.513582170009613
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.37407198548316956
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5276473760604858
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.43612179160118103
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5222705602645874
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5050302743911743
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5580597519874573
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47864556312561035
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6007041931152344
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5427929759025574
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.510518491268158
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5157298445701599
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5166319012641907
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5037791728973389
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.511753261089325
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.41296908259391785
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4998756945133209
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5439430475234985
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5017573833465576
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5110175609588623
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4389512538909912
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4606742858886719
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.49290329217910767
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5024264454841614
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46186935901641846
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5356154441833496
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5392835736274719
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.43208205699920654
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4980383813381195
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5224180817604065
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4559650123119354
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.367093563079834
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4218546152114868
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:   6%|▌         | 6/100 [04:20<24:24, 15.58s/it]

Raw prediction for T: 0.5218655467033386
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5914914608001709
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.4618281126022339
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5254690647125244
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.428239107131958
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.419545441865921
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.46392568945884705
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5478290319442749
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5300752520561218
Calibrated prediction for UTX: 0.5842176675796509
Raw prediction for V: 0.5819637179374695
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.4830102026462555
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.527636706829071
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.5021865963935852
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5075573325157166
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.508
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.024, kelly=0.201) with $5020.62
[PORT] Sector Conglomerates: 7 candidates, avg score=0.480
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.971, kelly=0.235) with $5867.04
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.479
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.990, kelly=0.147) with $3676.25
[PORT] Sector Financial: 10 candidates, avg score=0.511
[PORT] Sector Financial: selecting V (p=0.593, b=1.029, kelly=0.197) with $4920.60
[PORT] Sector Healthcare: 10 candidates, avg score=0.487
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.016, kelly=0.074) with $1850.50
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.519
[PORT] Sector Industrial Goods: selecting UTX (p=0.584, b=1.016, kelly=0.175) with $4377.98
[PORT] Sector Services: 10 candidates, avg score=0.526
[PORT] Sector Services: selecting AMZN (p=0.618, b=1.060, kelly=0.257) with $6434.79
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.069, kelly=0.296) with $7408.56
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.901, kelly=0.222) with $5562.68
Raw prediction for AAPL: 0.48916253447532654
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5219564437866211
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4635651409626007
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.543612003326416
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.48774057626724243
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4889473617076874
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5901352763175964
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4601999819278717
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5150933861732483
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4998359680175781
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4708998501300812
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5366076827049255
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.45942530035972595
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5771586298942566
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.43480393290519714
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4685335159301758
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5910065770149231
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4648805260658264
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4686967134475708
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5304761528968811
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4870406985282898
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5708457231521606
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4605374038219452
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4354735016822815
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4903860092163086
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5015160441398621
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.5220850706100464
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.47736358642578125
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5104507207870483
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5802686810493469
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5077456831932068
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5199293494224548
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5124749541282654
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.5004870295524597
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.6081095337867737
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.46078118681907654
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5259715914726257
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6204845309257507
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.5022978186607361
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.5177488327026367
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5136510729789734
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3929912745952606
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5274973511695862
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.4356245696544647
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5223957300186157
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.49432259798049927
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5580537915229797
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4783579707145691
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6011860370635986
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5467300415039062
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5098412036895752
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5128762722015381
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5074412822723389
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5051684975624084
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.5128496289253235
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.41497480869293213
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49937593936920166
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5421993732452393
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5018053650856018
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.511182963848114
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43784913420677185
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.46052640676498413
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.48380613327026367
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5018472671508789
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4623487591743469
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5227341651916504
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5247694253921509
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.4354848861694336
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49792757630348206
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5225532650947571
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4465314745903015
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3683064579963684
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4198763966560364
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:   7%|▋         | 7/100 [04:21<16:47, 10.83s/it]

Raw prediction for T: 0.5216794610023499
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5746193528175354
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.4583379328250885
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5266723036766052
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4106106758117676
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.40792131423950195
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4590706527233124
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5516749620437622
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.5281572937965393
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5743379592895508
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.49656596779823303
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5298904180526733
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.49991387128829956
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5069549083709717
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.515
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.023, kelly=0.200) with $5015.04
[PORT] Sector Conglomerates: 7 candidates, avg score=0.492
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.971, kelly=0.235) with $5869.54
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.472
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.990, kelly=0.147) with $3685.69
[PORT] Sector Financial: 10 candidates, avg score=0.501
[PORT] Sector Financial: selecting V (p=0.593, b=1.027, kelly=0.196) with $4899.46
[PORT] Sector Healthcare: 10 candidates, avg score=0.485
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.019, kelly=0.075) with $1880.21
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.988, kelly=0.125) with $3132.63
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.062, kelly=0.375) with $9388.62
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.067, kelly=0.296) with $7393.98
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.903, kelly=0.223) with $5582.83
Raw prediction for AAPL: 0.48893705010414124
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5234800577163696
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4692176878452301
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5433529019355774
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4867371916770935
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4892757833003998
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5966346263885498
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4597901701927185
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5151447653770447
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5001816153526306
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.48983246088027954
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5379500389099121
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.46370238065719604
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5460973381996155
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.43609708547592163
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4690457284450531
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5899052023887634
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4654195308685303
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46901369094848633
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5363394618034363
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.49652165174484253
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5761396288871765
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.46247079968452454
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4651797115802765
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4897918403148651
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5132154226303101
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.5210212469100952
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4772794246673584
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5113275647163391
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5707110166549683
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5080186724662781
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198961496353149
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5123037695884705
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.49492916464805603
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.5732442140579224
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.4622580409049988
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5257940292358398
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6254230737686157
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.501878023147583
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.5212739706039429
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5136275887489319
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4035604000091553
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5270102620124817
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.4352650046348572
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5222542881965637
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4853053092956543
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.557940661907196
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47784194350242615
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6020102500915527
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5498145222663879
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5087765455245972
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5090969800949097
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5023384690284729
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5105866193771362
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.5141842365264893
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.41672009229660034
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49902403354644775
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5381796360015869
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5016845464706421
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.50938880443573
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4383523166179657
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4605492055416107
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4787585437297821
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5012381672859192
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46319469809532166
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5040326714515686
Calibrated prediction for RDS-B: 0.5675675868988037
Raw prediction for REX: 0.5176825523376465
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.44395142793655396
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49768131971359253
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5227320194244385
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4382898509502411
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.37245041131973267
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.41216304898262024
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:   8%|▊         | 8/100 [04:22<11:50,  7.72s/it]

Raw prediction for T: 0.5258432626724243
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5421553254127502
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.4575726389884949
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5294225215911865
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4057316780090332
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4033341407775879
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.45331496000289917
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.554941713809967
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.5189762711524963
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5636619329452515
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5119379162788391
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5309118032455444
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4968833923339844
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5064029693603516
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.518
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.020, kelly=0.199) with $4987.60
[PORT] Sector Conglomerates: 7 candidates, avg score=0.493
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.969, kelly=0.238) with $5953.83
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.462
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.984, kelly=0.140) with $3508.13
[PORT] Sector Financial: 10 candidates, avg score=0.500
[PORT] Sector Financial: selecting V (p=0.580, b=1.029, kelly=0.172) with $4292.62
[PORT] Sector Healthcare: 10 candidates, avg score=0.485
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.017, kelly=0.074) with $1857.12
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.988, kelly=0.125) with $3132.24
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.060, kelly=0.375) with $9372.42
[PORT] Sector Technology: 10 candidates, avg score=0.534
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.093, kelly=0.306) with $7660.27
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.904, kelly=0.224) with $5596.02
Raw prediction for AAPL: 0.4888431429862976
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5254415273666382
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.47348788380622864
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5434492230415344
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4855514466762543
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4895935654640198
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6016811728477478
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45881929993629456
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5151687264442444
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5002293586730957
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5038425326347351
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5385981202125549
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4719441533088684
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.49961352348327637
Calibrated prediction for BP: 0.5220001339912415
Raw prediction for BRK-A: 0.4399510324001312
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4693027436733246
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.592275083065033
Calibrated prediction for BUD: 0.5270425081253052
Raw prediction for C: 0.46279799938201904
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46928223967552185
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5425370335578918
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.505075991153717
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.578203558921814
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4574788212776184
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.49038344621658325
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.4887979030609131
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5191870927810669
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.5206376910209656
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.47778940200805664
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5122905373573303
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5640692710876465
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5082974433898926
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198292136192322
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5121789574623108
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4880741834640503
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.5360061526298523
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.4615773558616638
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5253376960754395
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6277225613594055
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4990444481372833
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.5214864611625671
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5136269927024841
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4076199531555176
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5263705253601074
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.43637946248054504
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.523576021194458
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.47037559747695923
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5575922131538391
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47712215781211853
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6039955615997314
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5515165328979492
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5084216594696045
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5065868496894836
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5014095306396484
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.518721878528595
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.5133644342422485
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.41852355003356934
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49872058629989624
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.537563681602478
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5019922852516174
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5065730810165405
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.44075682759284973
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.45602306723594666
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4851665794849396
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5007702708244324
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46381720900535583
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4839629828929901
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5186107158660889
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.4572347402572632
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49733445048332214
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5229441523551941
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4345706105232239
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3754340410232544
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.40876448154449463
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5290302038192749
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5122775435447693
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.45456087589263916
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5312360525131226
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.41157498955726624
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.406202495098114
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.44746506214141846
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.55472332239151
Calibrated prediction for UPS: 0.5640879273414612

Simulating Trading Days:   9%|▉         | 9/100 [04:23<08:36,  5.68s/it]

Raw prediction for UTX: 0.5102106332778931
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5492702722549438
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5276356339454651
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5303761959075928
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.49388644099235535
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5058093667030334
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.506
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.975, kelly=0.132) with $3297.40
[PORT] Sector Conglomerates: 7 candidates, avg score=0.503
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.971, kelly=0.239) with $5975.94
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.470
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.982, kelly=0.139) with $3490.81
[PORT] Sector Financial: 10 candidates, avg score=0.500
[PORT] Sector Financial: selecting V (p=0.580, b=1.029, kelly=0.172) with $4298.20
[PORT] Sector Healthcare: 10 candidates, avg score=0.485
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.018, kelly=0.075) with $1872.57
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.987, kelly=0.124) with $3117.12
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.062, kelly=0.375) with $9398.73
[PORT] Sector Technology: 10 candidates, avg score=0.538
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.095, kelly=0.307) with $7689.39
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.903, kelly=0.224) with $5597.64
Raw prediction for AAPL: 0.4889746904373169
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5274088978767395
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4761354625225067
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5440871715545654
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.48430442810058594
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4898201525211334
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6082605123519897
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4576343595981598
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5152132511138916
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5001605749130249
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5113502740859985
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5420742034912109
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4808785617351532
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.45800966024398804
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.44378042221069336
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.469428151845932
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5957564115524292
Calibrated prediction for BUD: 0.6470588445663452
Raw prediction for C: 0.46448174118995667
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4692525267601013
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5544599890708923
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5188754796981812
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5771356821060181
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.448176771402359
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.5043162107467651
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.48743095993995667
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.524786114692688
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.5216228365898132
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.47893598675727844
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5129320025444031
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5657528638839722
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5084254741668701
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198439359664917
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5120643973350525
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4867536425590515
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.5038579106330872
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.45945096015930176
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5246112942695618
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6312448382377625
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.49589812755584717
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.5189188718795776
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5136368274688721
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4122455418109894
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5257028341293335
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.438521146774292
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5243849754333496
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4583142399787903
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5573354363441467
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4766462445259094
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6067602634429932
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5516161918640137
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5115206837654114
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.5022390484809875
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.49869728088378906
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5240673422813416
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.5131697058677673
Calibrated prediction for NVS: 0.5
Raw prediction for ORCL: 0.4197467267513275
Calibrated prediction for ORCL: 0.39606255292892456
Raw prediction for PCG: 0.49836161732673645
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5394354462623596
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5019722580909729
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5065085887908936
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4424254298210144
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4507211148738861
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4969634711742401
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5006380677223206
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46429967880249023
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47554659843444824
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5198794603347778
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.4742371737957001
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49643996357917786
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5232934951782227
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4317181408405304
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3749772608280182
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4106636047363281
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5344116687774658
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.4605887532234192
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.4478483498096466
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5322006940841675
Calibrated prediction for TSM: 0.5770066976547241

Simulating Trading Days:  10%|█         | 10/100 [04:24<06:23,  4.27s/it]

Raw prediction for UL: 0.421075701713562
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4131285846233368
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4444000720977783
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5521296262741089
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.4936935007572174
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5399911403656006
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5355350375175476
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.529836893081665
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.49095624685287476
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5050002932548523
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.498
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.974, kelly=0.132) with $3298.93
[PORT] Sector Conglomerates: 7 candidates, avg score=0.503
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.972, kelly=0.239) with $5992.59
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.476
[PORT] Sector Consumer Goods: selecting BUD (p=0.647, b=1.045, kelly=0.309) with $7752.72
[PORT] Sector Financial: 10 candidates, avg score=0.500
[PORT] Sector Financial: selecting V (p=0.580, b=1.028, kelly=0.171) with $4298.15
[PORT] Sector Healthcare: 10 candidates, avg score=0.493
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.016, kelly=0.137) with $3445.89
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.989, kelly=0.126) with $3148.20
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.061, kelly=0.375) with $9404.27
[PORT] Sector Technology: 10 candidates, avg score=0.533
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.095, kelly=0.307) with $7695.04
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.902, kelly=0.223) with $5584.54
Raw prediction for AAPL: 0.48926734924316406
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5284695029258728
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4740629196166992
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5446643233299255
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4824585020542145
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48988062143325806
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6076419949531555
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4563455581665039
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5153008699417114
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49979445338249207
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5139099955558777
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5465066432952881
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4878142476081848
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.4390518069267273
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.45176494121551514
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46930861473083496
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5945178270339966
Calibrated prediction for BUD: 0.642443060874939
Raw prediction for C: 0.46791526675224304
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46836256980895996
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5611345767974854
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5325239896774292
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5743372440338135
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.43718957901000977
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.50588059425354
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.4853551685810089
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5268572568893433
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.5213953852653503
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48029324412345886
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5130189061164856
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5710057020187378
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5081692934036255
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198087096214294
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5120575428009033
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4871390163898468
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.46832263469696045
Calibrated prediction for GOOG: 0.529411792755127
Raw prediction for HD: 0.45727771520614624
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5238969922065735
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6323665380477905
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.491515576839447
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.5124095678329468
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5128365755081177
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4188048839569092
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5246276259422302
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44149723649024963
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5241578221321106
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4519895017147064
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5574356317520142
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4765683710575104
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6102892160415649
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5525804758071899
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5136981010437012
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.49820947647094727
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.4968849718570709
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5259796977043152
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.5051921606063843
Calibrated prediction for NVS: 0.44999998807907104
Raw prediction for ORCL: 0.41890233755111694
Calibrated prediction for ORCL: 0.3951612114906311
Raw prediction for PCG: 0.49801236391067505
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5466433763504028
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5022898316383362
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5009361505508423
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4431094527244568
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.44288763403892517
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.5050171613693237
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5003719925880432
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.464550256729126
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4731554388999939
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5218523740768433
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.4917297065258026
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4955637753009796
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5233493447303772
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.42852893471717834
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.37291911244392395
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4099331200122833
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:  11%|█         | 11/100 [04:25<04:53,  3.30s/it]

Raw prediction for T: 0.5360515117645264
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.41034674644470215
Calibrated prediction for TM: 0.38340163230895996
Raw prediction for TOT: 0.451445072889328
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5293534398078918
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4310820400714874
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.41371679306030273
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4415726661682129
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5441237092018127
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4734005331993103
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5295496582984924
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5370512008666992
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.528268039226532
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.48749786615371704
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5046032071113586
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.503
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.972, kelly=0.131) with $3272.92
[PORT] Sector Conglomerates: 7 candidates, avg score=0.503
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.972, kelly=0.239) with $5984.20
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.475
[PORT] Sector Consumer Goods: selecting BUD (p=0.642, b=1.046, kelly=0.300) with $7522.48
[PORT] Sector Financial: 10 candidates, avg score=0.492
[PORT] Sector Financial: selecting V (p=0.580, b=1.026, kelly=0.171) with $4276.14
[PORT] Sector Healthcare: 10 candidates, avg score=0.488
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.017, kelly=0.138) with $3450.29
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.513
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.988, kelly=0.125) with $3136.18
[PORT] Sector Services: 10 candidates, avg score=0.532
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.059, kelly=0.374) with $9375.92
[PORT] Sector Technology: 10 candidates, avg score=0.529
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.094, kelly=0.307) with $7675.35
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.904, kelly=0.224) with $5601.84
Raw prediction for AAPL: 0.4898281693458557
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.528392493724823
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4671909511089325
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5436587333679199
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4798787534236908
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48976626992225647
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.605165958404541
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45491790771484375
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5153928995132446
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4993865191936493
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5132001042366028
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5514163970947266
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4881470501422882
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.4322907030582428
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.46040093898773193
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46892234683036804
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5904707312583923
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4731525182723999
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46701809763908386
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5636425614356995
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5434003472328186
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5703167915344238
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4261022210121155
Calibrated prediction for CMCSA: 0.44470345973968506
Raw prediction for CODI: 0.5065791606903076
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.4829787015914917
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5213825702667236
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.5212676525115967
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4818663001060486
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5129063725471497
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5749222636222839
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5079137682914734
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198560953140259
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5118696689605713
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.49464988708496094
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.4423679709434509
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45214566588401794
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5228444933891296
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.631097674369812
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4878791570663452
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.5042321681976318
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.511746883392334
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.42492324113845825
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5230968594551086
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44418424367904663
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5239596962928772
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.44828343391418457
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5581806302070618
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4765513241291046
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6147421598434448
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.5546192526817322
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5133580565452576
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.4975188672542572
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.49576079845428467
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5250136256217957
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.49352923035621643
Calibrated prediction for NVS: 0.44999998807907104
Raw prediction for ORCL: 0.4202566146850586
Calibrated prediction for ORCL: 0.39660683274269104
Raw prediction for PCG: 0.4975218176841736
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5506129264831543
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.502310037612915
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4942724406719208
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4426420032978058
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4376024007797241
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.5045220851898193
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.500074565410614
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4644373655319214
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47112569212913513
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5255974531173706
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5060641169548035
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49512338638305664
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5231493711471558
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.42400795221328735
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3705488443374634
Calibrated prediction for SPLP: 0.4395604431629181

Simulating Trading Days:  12%|█▏        | 12/100 [04:26<03:50,  2.62s/it]

Raw prediction for SRE: 0.4087347388267517
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5399330854415894
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.3584645390510559
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4412713050842285
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5267921090126038
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4324081838130951
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.406500905752182
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4385184943675995
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5347756743431091
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.45966386795043945
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.520952045917511
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5397847890853882
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5261585712432861
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.48375725746154785
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5035668611526489
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.503
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.974, kelly=0.132) with $3297.17
[PORT] Sector Conglomerates: 7 candidates, avg score=0.500
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.972, kelly=0.239) with $5995.90
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.984, kelly=0.141) with $3522.89
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.526, b=1.028, kelly=0.066) with $1644.85
[PORT] Sector Healthcare: 10 candidates, avg score=0.488
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.019, kelly=0.139) with $3477.32
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.491
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.991, kelly=0.126) with $3167.10
[PORT] Sector Services: 10 candidates, avg score=0.531
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.056, kelly=0.374) with $9370.96
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.096, kelly=0.307) with $7703.61
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.906, kelly=0.225) with $5628.81
Raw prediction for AAPL: 0.4906212091445923
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5273072123527527
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.45769643783569336
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5429427623748779
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.47728151082992554
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4894084632396698
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6065711379051208
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4543047547340393
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5155414342880249
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4988382160663605
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5104139447212219
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5567342638969421
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.48531535267829895
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.42557492852211
Calibrated prediction for BP: 0.43244853615760803
Raw prediction for BRK-A: 0.46644631028175354
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46856778860092163
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5882694125175476
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.48496681451797485
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.465210884809494
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5658649206161499
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5530372858047485
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5624748468399048
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4178003966808319
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.5005069375038147
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.48103535175323486
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5131393671035767
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.5199544429779053
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4829278886318207
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5128284692764282
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5722827911376953
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5078145265579224
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5199828147888184
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5115256905555725
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4937061071395874
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.4260505437850952
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.44639959931373596
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.52257239818573
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6271220445632935
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.48607757687568665
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.4945783019065857
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5106730461120605
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4293336570262909
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5214251279830933
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4465165436267853
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5222253203392029
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4457795023918152
Calibrated prediction for MA: 0.4432597756385803
Raw prediction for MCD: 0.5595165491104126
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47620585560798645
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6187909245491028
Calibrated prediction for MMM: 0.5652173757553101
Raw prediction for MO: 0.556190550327301
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5066636800765991
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.4995489716529846
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.49543988704681396
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5244814157485962
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4868525564670563
Calibrated prediction for NVS: 0.44999998807907104
Raw prediction for ORCL: 0.42531144618988037
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4972189664840698
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5500021576881409
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5023074150085449
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4901256263256073
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.44392943382263184
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4316072463989258
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5033248066902161
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.4997957646846771
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46411389112472534
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4723384976387024
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.532794713973999
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.515419065952301
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4944664239883423
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5227367281913757
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.42035332322120667
Calibrated prediction for SO: 0.4141654372215271

Simulating Trading Days:  13%|█▎        | 13/100 [04:27<03:07,  2.16s/it]

Raw prediction for SPLP: 0.36621981859207153
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4087124466896057
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5372631549835205
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.3193165361881256
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.42937278747558594
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5263530015945435
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.42887043952941895
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.40015920996665955
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.43486398458480835
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5243694186210632
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4485754668712616
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5171746015548706
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5454513430595398
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5236407518386841
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4813965857028961
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5021672248840332
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.490
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.972, kelly=0.131) with $3276.91
[PORT] Sector Conglomerates: 7 candidates, avg score=0.498
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.972, kelly=0.239) with $5994.60
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.982, kelly=0.140) with $3499.97
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.526, b=1.030, kelly=0.067) with $1668.08
[PORT] Sector Healthcare: 10 candidates, avg score=0.483
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.020, kelly=0.139) with $3486.82
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.491
[PORT] Sector Industrial Goods: selecting MMM (p=0.565, b=0.990, kelly=0.126) with $3163.36
[PORT] Sector Services: 10 candidates, avg score=0.527
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.056, kelly=0.374) with $9368.93
[PORT] Sector Technology: 10 candidates, avg score=0.515
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.098, kelly=0.308) with $7720.83
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.905, kelly=0.224) with $5623.90
Raw prediction for AAPL: 0.49138325452804565
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.52552729845047
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44803521037101746
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5406692028045654
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.47467002272605896
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4891207218170166
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.596091628074646
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45397666096687317
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5156762003898621
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49827826023101807
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5111064910888672
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5640789270401001
Calibrated prediction for BCH: 0.5111111402511597
Raw prediction for BHP: 0.48599791526794434
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.42514538764953613
Calibrated prediction for BP: 0.4281296133995056
Raw prediction for BRK-A: 0.47057873010635376
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4684143662452698
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5835261940956116
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.49545085430145264
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46348121762275696
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5639559030532837
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5613002181053162
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5529124140739441
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4110804796218872
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.49715253710746765
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.47977176308631897
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5065656900405884
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.5189451575279236
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48354285955429077
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5129908323287964
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5642802119255066
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5078771710395813
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5200121998786926
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5109601616859436
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4898020625114441
Calibrated prediction for GE: 0.5108374953269958
Raw prediction for GOOG: 0.41272255778312683
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4432040750980377
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5225202441215515
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.623350203037262
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.48604828119277954
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.48682644963264465
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5095713138580322
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.43374237418174744
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5199907422065735
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44883671402931213
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5211167335510254
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4467098116874695
Calibrated prediction for MA: 0.4607316851615906
Raw prediction for MCD: 0.560953676700592
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47596126794815063
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6215434670448303
Calibrated prediction for MMM: 0.5893078446388245
Raw prediction for MO: 0.5549073219299316
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.49856171011924744
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5021960735321045
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.49407657980918884
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5238041281700134
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.47917500138282776
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.43112245202064514
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4967361092567444
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5523566603660583
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5021823644638062
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4851204752922058
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.44419535994529724
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4271116256713867
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5015671253204346
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.4996141791343689
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46348974108695984
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47462400794029236
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5467966794967651
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5218324661254883
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.4940510392189026
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5222133994102478
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4149235785007477
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.36375734210014343
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.40978047251701355
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5304630398750305
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.28773629665374756
Calibrated prediction for TM: 0.3477618992328644

Simulating Trading Days:  14%|█▍        | 14/100 [04:29<02:42,  1.89s/it]

Raw prediction for TOT: 0.4312850832939148
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5271382927894592
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4181712865829468
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.39634624123573303
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4321911931037903
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5152283310890198
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4400463104248047
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5163784027099609
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5411899089813232
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.521304190158844
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4788057208061218
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5011287927627563
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.501
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.972, kelly=0.131) with $3281.40
[PORT] Sector Conglomerates: 7 candidates, avg score=0.527
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.111, kelly=0.377) with $9480.62
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.981, kelly=0.139) with $3494.29
[PORT] Sector Financial: 10 candidates, avg score=0.487
[PORT] Sector Financial: selecting V (p=0.526, b=1.032, kelly=0.067) with $1688.45
[PORT] Sector Healthcare: 10 candidates, avg score=0.474
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.018, kelly=0.138) with $3469.30
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.493
[PORT] Sector Industrial Goods: selecting MMM (p=0.589, b=0.992, kelly=0.176) with $4409.01
[PORT] Sector Services: 10 candidates, avg score=0.527
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.373) with $9380.77
[PORT] Sector Technology: 10 candidates, avg score=0.515
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.101, kelly=0.309) with $7754.47
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.907, kelly=0.225) with $5651.81
Raw prediction for AAPL: 0.4921409785747528
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5239795446395874
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4427718222141266
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5388907790184021
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.47193533182144165
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48888638615608215
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5783281922340393
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45384374260902405
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5157869458198547
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.497377872467041
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.511105477809906
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5699049234390259
Calibrated prediction for BCH: 0.5111111402511597
Raw prediction for BHP: 0.4861893653869629
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.4195076823234558
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.47429707646369934
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46844130754470825
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5785586833953857
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.501592218875885
Calibrated prediction for C: 0.5135135054588318
Raw prediction for CAT: 0.4621184170246124
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.555092990398407
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5693527460098267
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.546757698059082
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4062974154949188
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.49006912112236023
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.47803473472595215
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.49474188685417175
Calibrated prediction for CVX: 0.4615384638309479
Raw prediction for D: 0.5192214846611023
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4837912917137146
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5131288766860962
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5556493997573853
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5080103278160095
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5199306607246399
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5104826092720032
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.48424577713012695
Calibrated prediction for GE: 0.4675324559211731
Raw prediction for GOOG: 0.390168696641922
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4421831965446472
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5229191184043884
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.621324360370636
Calibrated prediction for HRG: 0.623306393623352
Raw prediction for HSBC: 0.49210691452026367
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.4853041172027588
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5088192820549011
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4370352625846863
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5189645886421204
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.45088475942611694
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5204235315322876
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4483012855052948
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5625194311141968
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47550541162490845
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6240142583847046
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5526246428489685
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.49628570675849915
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5020366311073303
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.49314913153648376
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5241724848747253
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.47534772753715515
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.4305659234523773
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4969939589500427
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5447674989700317
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5020301938056946
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.47955530881881714
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4445006847381592
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4250962436199188
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5014476180076599
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.4999645948410034
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46272456645965576
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.475238561630249
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5646529197692871
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5254361629486084
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.49459919333457947
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.521553635597229
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.41583162546157837
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3627910315990448
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.41479167342185974
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.52248215675354
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.27080395817756653
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4342755079269409
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.527244508266449
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.40611541271209717
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3977202773094177
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.43080422282218933
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5116543173789978
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.43124574422836304
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5207332968711853
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5380162596702576
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5195946097373962
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.47692403197288513
Calibrated prediction for WMT: 0.48148149251937866

Simulating Trading Days:  15%|█▌        | 15/100 [04:30<02:26,  1.72s/it]

Raw prediction for XOM: 0.5004876255989075
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.491
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.970, kelly=0.130) with $3264.96
[PORT] Sector Conglomerates: 7 candidates, avg score=0.527
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.109, kelly=0.377) with $9479.28
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.979, kelly=0.138) with $3473.15
[PORT] Sector Financial: 10 candidates, avg score=0.491
[PORT] Sector Financial: selecting V (p=0.526, b=1.029, kelly=0.066) with $1664.37
[PORT] Sector Healthcare: 10 candidates, avg score=0.474
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.016, kelly=0.137) with $3447.81
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.493
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.993, kelly=0.251) with $6311.59
[PORT] Sector Services: 10 candidates, avg score=0.508
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.050, kelly=0.223) with $5612.89
[PORT] Sector Technology: 10 candidates, avg score=0.515
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.098, kelly=0.308) with $7744.94
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.908, kelly=0.225) with $5670.71
Raw prediction for AAPL: 0.492940217256546
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5223774909973145
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4369807839393616
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5376385450363159
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4692782163619995
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4888100326061249
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5555119514465332
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4540463984012604
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5158911943435669
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4966551661491394
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5081456303596497
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5748870372772217
Calibrated prediction for BCH: 0.6111133694648743
Raw prediction for BHP: 0.48447751998901367
Calibrated prediction for BHP: 0.5023697018623352
Raw prediction for BP: 0.4154813289642334
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.47658753395080566
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46836185455322266
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5799630880355835
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4973846971988678
Calibrated prediction for C: 0.5135135054588318
Raw prediction for CAT: 0.46117421984672546
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5441020727157593
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5732420086860657
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5442395210266113
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4042457938194275
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4804474115371704
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4763832688331604
Calibrated prediction for CSCO: 0.47826087474823
Raw prediction for CVX: 0.47787612676620483
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5191347002983093
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4838012158870697
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5129459500312805
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5493887066841125
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5081457495689392
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198551416397095
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5101129412651062
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.478341281414032
Calibrated prediction for GE: 0.4675324559211731
Raw prediction for GOOG: 0.3726922571659088
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4441825747489929
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5237374305725098
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.619767963886261
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.49762535095214844
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.48627954721450806
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5079897046089172
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4405977725982666
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5184864401817322
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4532943069934845
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5200535655021667
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.45157134532928467
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5645359754562378
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4751127064228058
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6252678632736206
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5497943758964539
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.49380284547805786
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5067086219787598
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.49328550696372986
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5250357389450073
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4699822664260864
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.4327664375305176
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49720901250839233
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5404647588729858
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.501994788646698
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.47426271438598633
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.44523054361343384
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.42281919717788696
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5053013563156128
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5001659989356995
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4623725116252899
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4747399389743805
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5787448287010193
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5271961688995361
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.4954153895378113
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5209212303161621
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.42405956983566284
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.36395686864852905
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.41998958587646484
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5203753113746643
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.2727505564689636
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.42613548040390015
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5223522186279297
Calibrated prediction for TSM: 0.5770066976547241

Simulating Trading Days:  16%|█▌        | 16/100 [04:31<02:10,  1.55s/it]

Raw prediction for UL: 0.3991428017616272
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.40318480134010315
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.42989155650138855
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5121952891349792
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.43336597084999084
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5264138579368591
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5348262190818787
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5179810523986816
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.47316616773605347
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.49951523542404175
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.484
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.971, kelly=0.130) with $3278.26
[PORT] Sector Conglomerates: 7 candidates, avg score=0.516
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.108, kelly=0.377) with $9486.22
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.977, kelly=0.137) with $3454.20
[PORT] Sector Financial: 10 candidates, avg score=0.512
[PORT] Sector Financial: selecting BCH (p=0.611, b=0.988, kelly=0.217) with $5473.65
[PORT] Sector Healthcare: 10 candidates, avg score=0.466
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.018, kelly=0.075) with $1884.68
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.493
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.994, kelly=0.251) with $6325.79
[PORT] Sector Services: 10 candidates, avg score=0.508
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.049, kelly=0.223) with $5607.85
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.100, kelly=0.308) with $7768.36
[PORT] Sector Utilities: 10 candidates, avg score=0.495
[PORT] Sector Utilities: selecting DUK (p=0.562, b=0.898, kelly=0.075) with $1899.27
Raw prediction for AAPL: 0.49377354979515076
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5209884643554688
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4370916187763214
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5381061434745789
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4674029052257538
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48877403140068054
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.540755569934845
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45426470041275024
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5160086750984192
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4961605966091156
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5075346231460571
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.576917290687561
Calibrated prediction for BCH: 0.6111133694648743
Raw prediction for BHP: 0.484025776386261
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.41246023774147034
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4763534963130951
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46811234951019287
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5811262726783752
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4927930533885956
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46036630868911743
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5320941209793091
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5786404013633728
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5478536486625671
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4054346978664398
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.46943825483322144
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4750062823295593
Calibrated prediction for CSCO: 0.47826087474823
Raw prediction for CVX: 0.46759387850761414
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5186309218406677
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48372796177864075
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5122597217559814
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5495481491088867
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5081372261047363
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5197732448577881
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5099737644195557
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4736861288547516
Calibrated prediction for GE: 0.4675324559211731
Raw prediction for GOOG: 0.35886386036872864
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4477590024471283
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5240854620933533
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6234776973724365
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.5028637647628784
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.4868026077747345
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5068795680999756
Calibrated prediction for INTC: 0.5057387948036194
Raw prediction for JNJ: 0.444532185792923
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5183845162391663
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4540551006793976
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5203902721405029
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.45572829246520996
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.566003143787384
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47481274604797363
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6263176798820496
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.547452986240387
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4881714880466461
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5135610699653625
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.49209970235824585
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5250424742698669
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.46321648359298706
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.43600693345069885
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49729272723197937
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5362367630004883
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.501900851726532
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.46890735626220703
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4460892379283905
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4227660298347473
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5068044662475586
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5002365112304688
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4624235928058624
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47443652153015137
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5896545648574829
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5279847979545593
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.49617481231689453
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5203195214271545
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4364353120326996
Calibrated prediction for SO: 0.4141654372215271

Simulating Trading Days:  17%|█▋        | 17/100 [04:32<01:58,  1.42s/it]

Raw prediction for SPLP: 0.36375853419303894
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4235415458679199
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.527694046497345
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.28154104948043823
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.42603233456611633
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5182963609695435
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.39385801553726196
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4038591980934143
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4308740198612213
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5172780156135559
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4339717626571655
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5296398401260376
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5326290726661682
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.516624391078949
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4686426520347595
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.49877113103866577
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.484
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.970, kelly=0.130) with $3262.28
[PORT] Sector Conglomerates: 7 candidates, avg score=0.516
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.107, kelly=0.376) with $9476.50
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.976, kelly=0.137) with $3450.34
[PORT] Sector Financial: 10 candidates, avg score=0.507
[PORT] Sector Financial: selecting BCH (p=0.611, b=0.987, kelly=0.217) with $5471.92
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.020, kelly=0.076) with $1908.47
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.493
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.993, kelly=0.251) with $6322.55
[PORT] Sector Services: 10 candidates, avg score=0.508
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.051, kelly=0.223) with $5628.73
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.098, kelly=0.308) with $7753.67
[PORT] Sector Utilities: 10 candidates, avg score=0.495
[PORT] Sector Utilities: selecting DUK (p=0.562, b=0.899, kelly=0.076) with $1916.55
Raw prediction for AAPL: 0.4945891499519348
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5195562839508057
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4376167953014374
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5388005375862122
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4659746587276459
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4887353777885437
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5359579920768738
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45459219813346863
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.51600581407547
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4958859980106354
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5100327134132385
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5753757357597351
Calibrated prediction for BCH: 0.6111133694648743
Raw prediction for BHP: 0.4865153729915619
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.41008076071739197
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4758141338825226
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4678385853767395
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5797618627548218
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4893215596675873
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4598010778427124
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.522022008895874
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5836963057518005
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5625477433204651
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.41220420598983765
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4563746154308319
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.47373801469802856
Calibrated prediction for CSCO: 0.47826087474823
Raw prediction for CVX: 0.4619157910346985
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5169547200202942
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4836617410182953
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5107393264770508
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5554021000862122
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5081943869590759
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5197387337684631
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5098668336868286
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.46865344047546387
Calibrated prediction for GE: 0.4675324559211731
Raw prediction for GOOG: 0.35225924849510193
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4520549476146698
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5246651768684387
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6278786063194275
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.5064439177513123
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.48761212825775146
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5058964490890503
Calibrated prediction for INTC: 0.5025018453598022
Raw prediction for JNJ: 0.446824312210083
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5183587074279785
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4536661207675934
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.521091878414154
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4594326615333557
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5671060085296631
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47482725977897644
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6277452707290649
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5439068078994751
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4757934510707855
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5187143683433533
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.49334806203842163
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5249039530754089
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.45863407850265503
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.4378471374511719
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49757376313209534
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5414783358573914
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5017271637916565
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.46851304173469543
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4459582269191742
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4188903272151947
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5058679580688477
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5005791187286377
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46268925070762634
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4740408957004547
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5945096611976624
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5279300808906555
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.49687325954437256
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5198365449905396
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4505298435688019
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.364736407995224
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.42595383524894714
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5439306497573853
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.29053592681884766
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4324794411659241
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5149703025817871
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.3885890245437622
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4045245349407196
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4373440146446228
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5222806334495544
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.43440666794776917
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5298658013343811
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5305193662643433
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5154440402984619
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.46477991342544556
Calibrated prediction for WMT: 0.4189581871032715

Simulating Trading Days:  18%|█▊        | 18/100 [04:34<01:49,  1.34s/it]

Raw prediction for XOM: 0.4988915026187897
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.489
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.970, kelly=0.130) with $3275.33
[PORT] Sector Conglomerates: 7 candidates, avg score=0.516
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.108, kelly=0.377) with $9510.92
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.975, kelly=0.136) with $3438.44
[PORT] Sector Financial: 10 candidates, avg score=0.507
[PORT] Sector Financial: selecting BCH (p=0.611, b=0.989, kelly=0.218) with $5501.10
[PORT] Sector Healthcare: 10 candidates, avg score=0.458
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.019, kelly=0.075) with $1901.39
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.493
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.994, kelly=0.251) with $6346.73
[PORT] Sector Services: 10 candidates, avg score=0.502
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.053, kelly=0.224) with $5655.20
[PORT] Sector Technology: 10 candidates, avg score=0.512
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.096, kelly=0.307) with $7757.56
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.908, kelly=0.226) with $5697.36
Raw prediction for AAPL: 0.4949937164783478
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5180265307426453
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.43860021233558655
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5386751294136047
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.464731901884079
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4886517822742462
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5415405631065369
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45488327741622925
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5160219669342041
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49577030539512634
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5145130157470703
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5736962556838989
Calibrated prediction for BCH: 0.6000000238418579
Raw prediction for BHP: 0.48948603868484497
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.41096124053001404
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.47649821639060974
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4677838087081909
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5706775188446045
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4901883006095886
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45936793088912964
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5095391273498535
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5842908024787903
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5781819224357605
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4220496714115143
Calibrated prediction for CMCSA: 0.41706833243370056
Raw prediction for CODI: 0.44467100501060486
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.47282299399375916
Calibrated prediction for CSCO: 0.473532497882843
Raw prediction for CVX: 0.45823773741722107
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5154590606689453
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4836365282535553
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5088735818862915
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5629912614822388
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5081671476364136
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5197820067405701
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5098860859870911
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4651969373226166
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.34669530391693115
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4551439881324768
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5250552892684937
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6337737441062927
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.5080788731575012
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.4879874587059021
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5053175687789917
Calibrated prediction for INTC: 0.5025018453598022
Raw prediction for JNJ: 0.44670361280441284
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5183249711990356
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4530705213546753
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5223822593688965
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.46521511673927307
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.56798255443573
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4752446115016937
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6301059722900391
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5408663153648376
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4659041464328766
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.525006115436554
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.49241113662719727
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5240976214408875
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4516282379627228
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.43761879205703735
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49733805656433105
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5461528301239014
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5021345615386963
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.46827787160873413
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4461524188518524
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4126119911670685
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5044650435447693
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5009464025497437
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4640061855316162
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47579821944236755
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5955048203468323
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.528237521648407
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.4975729286670685
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5194027423858643
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4591182470321655
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.36617109179496765
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4226587414741516
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.556135892868042
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.3088282644748688
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.44139882922172546
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5138406157493591
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.3827010989189148
Calibrated prediction for UL: 0.3333333432674408

Simulating Trading Days:  19%|█▉        | 19/100 [04:35<01:43,  1.28s/it]

Raw prediction for UN: 0.4048473834991455
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4447700083255768
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5257649421691895
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4328489899635315
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5286908745765686
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5296851992607117
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5144071578979492
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4621886909008026
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.4984700083732605
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.500
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.971, kelly=0.130) with $3288.23
[PORT] Sector Conglomerates: 7 candidates, avg score=0.516
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.106, kelly=0.376) with $9503.76
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.455
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.975, kelly=0.136) with $3445.81
[PORT] Sector Financial: 10 candidates, avg score=0.506
[PORT] Sector Financial: selecting BCH (p=0.600, b=0.990, kelly=0.196) with $4955.57
[PORT] Sector Healthcare: 10 candidates, avg score=0.458
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.018, kelly=0.075) with $1898.30
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.997, kelly=0.252) with $6376.29
[PORT] Sector Services: 10 candidates, avg score=0.509
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.054, kelly=0.225) with $5676.94
[PORT] Sector Technology: 10 candidates, avg score=0.516
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.098, kelly=0.308) with $7780.43
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.908, kelly=0.225) with $5695.54
Raw prediction for AAPL: 0.49518510699272156
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5168601870536804
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4398760199546814
Calibrated prediction for ABBV: 0.44026532769203186
Raw prediction for AEP: 0.5374312996864319
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.46364083886146545
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.488492488861084
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5523460507392883
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4550918638706207
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5159286856651306
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4955940842628479
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5160605907440186
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5682204365730286
Calibrated prediction for BCH: 0.5111111402511597
Raw prediction for BHP: 0.49210819602012634
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.41211697459220886
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.47765490412712097
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46768084168434143
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5550830960273743
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.49187958240509033
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45899316668510437
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5045533776283264
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5779654383659363
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5917627811431885
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4322664737701416
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.43583106994628906
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.47248217463493347
Calibrated prediction for CSCO: 0.47058597207069397
Raw prediction for CVX: 0.45287343859672546
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5164000988006592
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48345300555229187
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5071718096733093
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5682417154312134
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5080141425132751
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198677182197571
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5098327994346619
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4603157341480255
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.34491264820098877
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45686790347099304
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5256183743476868
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6386383771896362
Calibrated prediction for HRG: 0.6500897407531738
Raw prediction for HSBC: 0.507636547088623
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.4886820614337921
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5051832795143127
Calibrated prediction for INTC: 0.5025018453598022
Raw prediction for JNJ: 0.44811323285102844
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5183077454566956
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.45148637890815735
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.523279070854187
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4698300063610077
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.568749189376831
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.475742906332016
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6326347589492798
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5380035042762756
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4578992426395416
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.532768726348877
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.49070098996162415
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5223178267478943
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4443308413028717
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.43834149837493896
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4968946874141693
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5522514581680298
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5020738244056702
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4723116457462311
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.44473639130592346
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4068237543106079
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.49460792541503906
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5010373592376709
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46532633900642395
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47461265325546265
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.595265805721283
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5261967778205872
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.49875736236572266
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5190609097480774
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.45861169695854187
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.36829525232315063
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4200296998023987
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:  20%|██        | 20/100 [04:36<01:38,  1.23s/it]

Raw prediction for T: 0.5516186952590942
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.3142848014831543
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.43223872780799866
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5123997926712036
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.3736943006515503
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4046289622783661
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4543297290802002
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5292460322380066
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.43203485012054443
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5310294032096863
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5306766033172607
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5134568214416504
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.46103259921073914
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.498406320810318
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.489
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.972, kelly=0.130) with $3306.26
[PORT] Sector Conglomerates: 7 candidates, avg score=0.520
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.107, kelly=0.376) with $9536.21
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.450
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.977, kelly=0.137) with $3475.28
[PORT] Sector Financial: 10 candidates, avg score=0.497
[PORT] Sector Financial: selecting V (p=0.580, b=1.034, kelly=0.174) with $4408.82
[PORT] Sector Healthcare: 10 candidates, avg score=0.465
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.015, kelly=0.074) with $1863.65
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.998, kelly=0.253) with $6406.43
[PORT] Sector Services: 10 candidates, avg score=0.513
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.052, kelly=0.224) with $5670.18
[PORT] Sector Technology: 10 candidates, avg score=0.516
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.099, kelly=0.308) with $7812.74
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.901, kelly=0.174) with $4419.09
Raw prediction for AAPL: 0.49537786841392517
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5161263346672058
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4404313564300537
Calibrated prediction for ABBV: 0.45106226205825806
Raw prediction for AEP: 0.537229597568512
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.46294158697128296
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4883723556995392
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5626487135887146
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45514628291130066
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5157893300056458
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.495388388633728
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5117256045341492
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5662397742271423
Calibrated prediction for BCH: 0.5111111402511597
Raw prediction for BHP: 0.49096065759658813
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.41060784459114075
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4777928292751312
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4676355719566345
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5438528060913086
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.49658453464508057
Calibrated prediction for C: 0.501626193523407
Raw prediction for CAT: 0.45894762873649597
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5061363577842712
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5695176124572754
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6062924861907959
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.44091713428497314
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4316222667694092
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.47229740023612976
Calibrated prediction for CSCO: 0.47058597207069397
Raw prediction for CVX: 0.44733068346977234
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5126675367355347
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4831797182559967
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5058014988899231
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5662976503372192
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.507856547832489
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198968648910522
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.509678304195404
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4548611342906952
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.3427980840206146
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45608919858932495
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.526556670665741
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6432551741600037
Calibrated prediction for HRG: 0.6500897407531738
Raw prediction for HSBC: 0.5073262453079224
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.48907771706581116
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5047799944877625
Calibrated prediction for INTC: 0.5025018453598022
Raw prediction for JNJ: 0.4519346356391907
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5183175206184387
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44864335656166077
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5236481428146362
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.48314863443374634
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5693568587303162
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47640490531921387
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6343065500259399
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5369162559509277
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4516756236553192
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5411381125450134
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4878371059894562
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.519260585308075
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.43759047985076904
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.43832698464393616
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4966043531894684
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5586327314376831
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5021381974220276
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4799056053161621
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.44362443685531616
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.4004625976085663
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4801984131336212
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5011720657348633
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4669383466243744
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4713538587093353
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5961255431175232
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5186305642127991
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.499358594417572
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5188301205635071
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.45224839448928833
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.36649611592292786
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.41329553723335266
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.536484956741333
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.3196299076080322
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4160686433315277
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5104977488517761
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.36728957295417786
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.39916273951530457
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4631023406982422
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5324873328208923
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4327383041381836
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5379144549369812
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.532463014125824
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5128579139709473
Calibrated prediction for WFC: 0.4904371201992035

Simulating Trading Days:  21%|██        | 21/100 [04:37<01:35,  1.21s/it]

Raw prediction for WMT: 0.45761367678642273
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49870800971984863
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.491
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.971, kelly=0.130) with $3307.71
[PORT] Sector Conglomerates: 7 candidates, avg score=0.520
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.108, kelly=0.377) with $9567.46
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.447
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.977, kelly=0.137) with $3489.94
[PORT] Sector Financial: 10 candidates, avg score=0.498
[PORT] Sector Financial: selecting V (p=0.580, b=1.032, kelly=0.173) with $4396.55
[PORT] Sector Healthcare: 10 candidates, avg score=0.465
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.015, kelly=0.074) with $1868.23
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.999, kelly=0.253) with $6433.53
[PORT] Sector Services: 10 candidates, avg score=0.513
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.050, kelly=0.223) with $5667.04
[PORT] Sector Technology: 10 candidates, avg score=0.516
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.098, kelly=0.308) with $7824.17
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.900, kelly=0.174) with $4424.47
Raw prediction for AAPL: 0.49545517563819885
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5153143405914307
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44102033972740173
Calibrated prediction for ABBV: 0.46251338720321655
Raw prediction for AEP: 0.538458526134491
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4637589752674103
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48830515146255493
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5681020617485046
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45480242371559143
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5157171487808228
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49498793482780457
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5150645971298218
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5645811557769775
Calibrated prediction for BCH: 0.5111111402511597
Raw prediction for BHP: 0.4890420734882355
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.4170757532119751
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.47594183683395386
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4677478075027466
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5362540483474731
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4988408088684082
Calibrated prediction for C: 0.5135135054588318
Raw prediction for CAT: 0.45885318517684937
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5073874592781067
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5594443082809448
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6154007911682129
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4468461871147156
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.431354820728302
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4726221263408661
Calibrated prediction for CSCO: 0.47058597207069397
Raw prediction for CVX: 0.4446832835674286
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5096632838249207
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48290786147117615
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5049692988395691
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5587404370307922
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5078718662261963
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5199464559555054
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5094568729400635
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.45192858576774597
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.34549200534820557
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4527014195919037
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5271452069282532
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.64798903465271
Calibrated prediction for HRG: 0.6500897407531738
Raw prediction for HSBC: 0.5080915689468384
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.4894683361053467
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5045920610427856
Calibrated prediction for INTC: 0.5025018453598022
Raw prediction for JNJ: 0.4533754885196686
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5184870958328247
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44529783725738525
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5237740874290466
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.49650105834007263
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5698125958442688
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47707194089889526
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6352785229682922
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5365356206893921
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.45112693309783936
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5482301712036133
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.48913347721099854
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5165730714797974
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4325718879699707
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4400155246257782
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49665603041648865
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5643154382705688
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.502052903175354
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.48737502098083496
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4428742527961731
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.39901745319366455
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.46455103158950806
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5015808939933777
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4677760899066925
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.46172115206718445
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5989957451820374
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5031433701515198
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4990854263305664
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5186192989349365
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4497168958187103
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3626883327960968
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.40562865138053894
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5221211910247803
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.32691144943237305
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4023166596889496
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5099421143531799
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.3604612350463867
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3916952311992645
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4729919731616974
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5365817546844482
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.43654346466064453
Calibrated prediction for UTX: 0.3193990886211395

Simulating Trading Days:  22%|██▏       | 22/100 [04:38<01:31,  1.17s/it]

Raw prediction for V: 0.5476065874099731
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5326645374298096
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5124990940093994
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.45245999097824097
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.4991236925125122
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.971, kelly=0.130) with $3303.99
[PORT] Sector Conglomerates: 7 candidates, avg score=0.520
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.110, kelly=0.377) with $9581.11
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.447
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.975, kelly=0.136) with $3465.99
[PORT] Sector Financial: 10 candidates, avg score=0.499
[PORT] Sector Financial: selecting V (p=0.580, b=1.030, kelly=0.172) with $4379.13
[PORT] Sector Healthcare: 10 candidates, avg score=0.466
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.017, kelly=0.074) with $1891.07
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.999, kelly=0.253) with $6434.09
[PORT] Sector Services: 10 candidates, avg score=0.513
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.042, kelly=0.220) with $5591.32
[PORT] Sector Technology: 10 candidates, avg score=0.516
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.096, kelly=0.307) with $7809.10
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.906, kelly=0.225) with $5711.13
Raw prediction for AAPL: 0.49548208713531494
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5144798159599304
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44167542457580566
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5409501194953918
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4643501937389374
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48831483721733093
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5747608542442322
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45503249764442444
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.51565021276474
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4946449100971222
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5159014463424683
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5609470009803772
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4840618669986725
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.42043569684028625
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.47076067328453064
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.467926949262619
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5330138206481934
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.498293399810791
Calibrated prediction for C: 0.5135135054588318
Raw prediction for CAT: 0.4592273235321045
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.512588381767273
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5484941005706787
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6259372234344482
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4518462121486664
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4329198896884918
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4733027219772339
Calibrated prediction for CSCO: 0.47826087474823
Raw prediction for CVX: 0.44191858172416687
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5003992915153503
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4826616942882538
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5042760372161865
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5527448058128357
Calibrated prediction for DUK: 0.5906809568405151
Raw prediction for EXC: 0.5079188346862793
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5199969410896301
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5094040632247925
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4553912878036499
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.35201412439346313
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45002174377441406
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5279260873794556
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6493377089500427
Calibrated prediction for HRG: 0.6500897407531738
Raw prediction for HSBC: 0.5079583525657654
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.48980796337127686
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5047865509986877
Calibrated prediction for INTC: 0.5025018453598022
Raw prediction for JNJ: 0.4560246467590332
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5186249613761902
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4433347284793854
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5238442420959473
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5095759630203247
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5698957443237305
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4778823256492615
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.635019838809967
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5358383059501648
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.44992795586586
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5554625988006592
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4917728304862976
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5158066749572754
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.43295684456825256
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.44139936566352844
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4966106414794922
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5904547572135925
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5020766854286194
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4956551194190979
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.44260352849960327
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.39783012866973877
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.45544013381004333
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5019570589065552
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.467389315366745
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4474301338195801
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.6054551005363464
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.48178791999816895
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49840429425239563
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.518491804599762
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.45021337270736694
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3567667007446289
Calibrated prediction for SPLP: 0.3333333432674408
Raw prediction for SRE: 0.3974025249481201
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5071135759353638
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.3473324477672577
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.38281574845314026
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5100595951080322
Calibrated prediction for TSM: 0.568965494632721

Simulating Trading Days:  23%|██▎       | 23/100 [04:39<01:28,  1.15s/it]

Raw prediction for UL: 0.34648290276527405
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3805093467235565
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.483014851808548
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5452086329460144
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.44903621077537537
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5558236241340637
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.531699538230896
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5124092102050781
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4455508291721344
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.499318391084671
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.474
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.969, kelly=0.129) with $3268.63
[PORT] Sector Conglomerates: 7 candidates, avg score=0.505
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.108, kelly=0.377) with $9533.30
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.447
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.974, kelly=0.136) with $3438.02
[PORT] Sector Financial: 10 candidates, avg score=0.507
[PORT] Sector Financial: selecting V (p=0.580, b=1.033, kelly=0.173) with $4387.23
[PORT] Sector Healthcare: 10 candidates, avg score=0.474
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.019, kelly=0.076) with $1912.15
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.997, kelly=0.252) with $6392.90
[PORT] Sector Services: 10 candidates, avg score=0.513
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.043, kelly=0.221) with $5584.07
[PORT] Sector Technology: 10 candidates, avg score=0.517
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.097, kelly=0.308) with $7792.34
[PORT] Sector Utilities: 10 candidates, avg score=0.509
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.905, kelly=0.224) with $5675.00
Raw prediction for AAPL: 0.49551600217819214
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5134784579277039
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4458175301551819
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5437214970588684
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.46524307131767273
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48846951127052307
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5823960304260254
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4556456208229065
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5157410502433777
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4944457411766052
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5107755661010742
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5560234189033508
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.47460848093032837
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.41621506214141846
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4657817482948303
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4681813716888428
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5303828716278076
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4970548152923584
Calibrated prediction for C: 0.5135135054588318
Raw prediction for CAT: 0.4594787657260895
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.518851101398468
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5411680340766907
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6319938898086548
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4553386867046356
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.43561851978302
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.47415998578071594
Calibrated prediction for CSCO: 0.47826087474823
Raw prediction for CVX: 0.44004252552986145
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.49277690052986145
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48246702551841736
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.503742516040802
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.548637330532074
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.508138120174408
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5200115442276001
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5095100402832031
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.45456382632255554
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.359825074672699
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45210883021354675
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5287764668464661
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6477005481719971
Calibrated prediction for HRG: 0.6500897407531738
Raw prediction for HSBC: 0.5078561902046204
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.4902202785015106
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5055895447731018
Calibrated prediction for INTC: 0.5025018453598022
Raw prediction for JNJ: 0.4559754729270935
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5188997983932495
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4423549473285675
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5232815742492676
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5234174132347107
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5695009827613831
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47857511043548584
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6338010430335999
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5349287986755371
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.44496914744377136
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5590278506278992
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4968952238559723
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5194653272628784
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.43548426032066345
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4408775866031647
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4968896210193634
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6028594970703125
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5018936395645142
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5021476149559021
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.44199955463409424
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.3965021073818207
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.45064204931259155
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5021671056747437
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46595069766044617
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.43542414903640747
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.6119561791419983
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4604838788509369
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49763381481170654
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5184502005577087
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4556700587272644
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3489200174808502
Calibrated prediction for SPLP: 0.2606547772884369
Raw prediction for SRE: 0.3903926908969879
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4942713975906372
Calibrated prediction for T: 0.4600202739238739
Raw prediction for TM: 0.3822135031223297
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.3622209429740906
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5086170434951782
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.3293556869029999
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.36692818999290466
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4942823350429535
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5546858310699463
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.4660128653049469
Calibrated prediction for UTX: 0.375
Raw prediction for V: 0.5636723637580872
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.525134801864624
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5137687921524048
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.438032865524292
Calibrated prediction for WMT: 0.4189581871032715

Simulating Trading Days:  24%|██▍       | 24/100 [04:40<01:27,  1.14s/it]

Raw prediction for XOM: 0.49954336881637573
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.474
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.971, kelly=0.130) with $3299.25
[PORT] Sector Conglomerates: 7 candidates, avg score=0.494
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.104, kelly=0.376) with $9533.96
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.447
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.972, kelly=0.135) with $3430.06
[PORT] Sector Financial: 10 candidates, avg score=0.507
[PORT] Sector Financial: selecting V (p=0.580, b=1.032, kelly=0.173) with $4391.85
[PORT] Sector Healthcare: 10 candidates, avg score=0.474
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.022, kelly=0.077) with $1943.46
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.495
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.000, kelly=0.253) with $6431.30
[PORT] Sector Services: 10 candidates, avg score=0.520
[PORT] Sector Services: selecting PCLN (p=0.650, b=1.041, kelly=0.314) with $7966.25
[PORT] Sector Technology: 10 candidates, avg score=0.504
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.100, kelly=0.309) with $7832.08
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.905, kelly=0.224) with $5687.68
Raw prediction for AAPL: 0.49547940492630005
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5131112933158875
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44854483008384705
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5455991625785828
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.46609067916870117
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4887603223323822
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5798760652542114
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45688343048095703
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5158782601356506
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49445247650146484
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.49999457597732544
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5471926927566528
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4638232886791229
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.40564826130867004
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4607587456703186
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4681837856769562
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5281096696853638
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.49452319741249084
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4596295654773712
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5264179110527039
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5336713790893555
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6377767324447632
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4577820897102356
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.43757131695747375
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4751552939414978
Calibrated prediction for CSCO: 0.47826087474823
Raw prediction for CVX: 0.4381287693977356
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.48755714297294617
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4825262129306793
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5032579898834229
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5438067317008972
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5079107284545898
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5200164914131165
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5096588134765625
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4575212299823761
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.3685860335826874
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45519596338272095
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5304222702980042
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6425749659538269
Calibrated prediction for HRG: 0.6500897407531738
Raw prediction for HSBC: 0.5068663954734802
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.4898844063282013
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5066959261894226
Calibrated prediction for INTC: 0.5025018453598022
Raw prediction for JNJ: 0.45498037338256836
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5192736387252808
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44217005372047424
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5229595303535461
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5305800437927246
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5693601965904236
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4790307879447937
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6320587396621704
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5345946550369263
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.44462817907333374
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5640314221382141
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.49631717801094055
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5237851738929749
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4367810785770416
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4370238780975342
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4966127574443817
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6068251729011536
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5017687678337097
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5059725642204285
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4415551722049713
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.39581412076950073
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.44812655448913574
Calibrated prediction for PM: 0.524553120136261
Raw prediction for PPL: 0.5021164417266846
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.464300274848938
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4261724352836609
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.6131590008735657
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.44487616419792175
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4977416396141052
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5185171365737915
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4591582417488098
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3429318368434906
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3844316601753235
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.48243263363838196
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.43524304032325745
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.350315123796463
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5065369009971619
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.31535080075263977
Calibrated prediction for UL: 0.3333333432674408

Simulating Trading Days:  25%|██▌       | 25/100 [04:41<01:25,  1.15s/it]

Raw prediction for UN: 0.357911616563797
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.5040041208267212
Calibrated prediction for UNH: 0.4661315679550171
Raw prediction for UPS: 0.5655450224876404
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.494577556848526
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5664299130439758
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5206206440925598
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5160596370697021
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.42896685004234314
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49973204731941223
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.472
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.971, kelly=0.130) with $3298.86
[PORT] Sector Conglomerates: 7 candidates, avg score=0.491
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.103, kelly=0.375) with $9523.37
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.452
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.970, kelly=0.134) with $3405.66
[PORT] Sector Financial: 10 candidates, avg score=0.504
[PORT] Sector Financial: selecting V (p=0.580, b=1.031, kelly=0.173) with $4380.84
[PORT] Sector Healthcare: 10 candidates, avg score=0.477
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.024, kelly=0.078) with $1968.04
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.999, kelly=0.253) with $6425.46
[PORT] Sector Services: 10 candidates, avg score=0.520
[PORT] Sector Services: selecting PCLN (p=0.650, b=1.043, kelly=0.315) with $7981.79
[PORT] Sector Technology: 10 candidates, avg score=0.499
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.100, kelly=0.309) with $7829.47
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.904, kelly=0.224) with $5684.42
Raw prediction for AAPL: 0.49531614780426025
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5129387378692627
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4477164149284363
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5451339483261108
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4666374921798706
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48907485604286194
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.578743040561676
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4581719636917114
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5159817934036255
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4944843053817749
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.48599088191986084
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5350720286369324
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4539826512336731
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4002053439617157
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4555884599685669
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46773645281791687
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5270971059799194
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.49174055457115173
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4595451056957245
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5343611836433411
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5288395285606384
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6436485052108765
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.46000173687934875
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4400380849838257
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.47598394751548767
Calibrated prediction for CSCO: 0.47826087474823
Raw prediction for CVX: 0.43784263730049133
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.48487550020217896
Calibrated prediction for D: 0.5278298258781433
Raw prediction for DHR: 0.4825548529624939
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5027811527252197
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5339013338088989
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.507495641708374
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5199605822563171
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.509966254234314
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4586727023124695
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.37602099776268005
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4584137797355652
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5314247012138367
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6359608769416809
Calibrated prediction for HRG: 0.6500897407531738
Raw prediction for HSBC: 0.5054810047149658
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.489905446767807
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5080259442329407
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4550112783908844
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5197219848632812
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4420483708381653
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5225303769111633
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5265272259712219
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.569056510925293
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47906777262687683
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6306548714637756
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.535911500453949
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4485696256160736
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5673370361328125
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4907439351081848
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.527057409286499
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4390190839767456
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.42924579977989197
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4962076246738434
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6104751229286194
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5016696453094482
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5070217251777649
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.44105756282806396
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.3928051292896271
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4438943564891815
Calibrated prediction for PM: 0.5
Raw prediction for PPL: 0.5021073818206787
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4626398980617523
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.42388904094696045
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.6065587997436523
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4356522560119629
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49810823798179626
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5186803936958313
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4594045579433441
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.34037917852401733
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.37760987877845764
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.48002639412879944
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.4882136583328247
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.3507426679134369
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5095378160476685
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.30354148149490356
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3497917652130127
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.5109155178070068
Calibrated prediction for UNH: 0.47826087474823

Simulating Trading Days:  26%|██▌       | 26/100 [04:43<01:26,  1.17s/it]

Raw prediction for UPS: 0.5759605169296265
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.5169900059700012
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5628522038459778
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5229619741439819
Calibrated prediction for VZ: 0.5538639426231384
Raw prediction for WFC: 0.5185974836349487
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.42054885625839233
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49996936321258545
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.470
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.970, kelly=0.080) with $2013.24
[PORT] Sector Conglomerates: 7 candidates, avg score=0.491
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.105, kelly=0.376) with $9487.48
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.969, kelly=0.134) with $3376.24
[PORT] Sector Financial: 10 candidates, avg score=0.507
[PORT] Sector Financial: selecting V (p=0.580, b=1.033, kelly=0.174) with $4382.17
[PORT] Sector Healthcare: 10 candidates, avg score=0.482
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.022, kelly=0.077) with $1935.06
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.515
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.997, kelly=0.253) with $6374.07
[PORT] Sector Services: 10 candidates, avg score=0.520
[PORT] Sector Services: selecting PCLN (p=0.650, b=1.043, kelly=0.314) with $7934.41
[PORT] Sector Technology: 10 candidates, avg score=0.502
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.097, kelly=0.308) with $7767.73
[PORT] Sector Utilities: 10 candidates, avg score=0.505
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.904, kelly=0.224) with $5650.28
Raw prediction for AAPL: 0.4950232207775116
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5128946304321289
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44618138670921326
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5434795618057251
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4669473469257355
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4893454313278198
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5728650689125061
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4593842327594757
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5160651206970215
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4946834146976471
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.46632900834083557
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.521720290184021
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.44947493076324463
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.4071190357208252
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.45146265625953674
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46710002422332764
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5250168442726135
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.488959401845932
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45925450325012207
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5421053767204285
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.5195751786231995
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6484715342521667
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4636680781841278
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4453679025173187
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4765327572822571
Calibrated prediction for CSCO: 0.47826087474823
Raw prediction for CVX: 0.44040367007255554
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.48469483852386475
Calibrated prediction for D: 0.5216408371925354
Raw prediction for DHR: 0.48265740275382996
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5023044347763062
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5183910131454468
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5069665312767029
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5199694037437439
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5102720260620117
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4594288170337677
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.37807756662368774
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.46038365364074707
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5318406820297241
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6314529180526733
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.5030425786972046
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.49019595980644226
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5090047121047974
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4552162289619446
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5199182629585266
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4415294826030731
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5219504237174988
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5142214298248291
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5689507722854614
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47900688648223877
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.629514217376709
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5386338233947754
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.45278263092041016
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5704302191734314
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.48674046993255615
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5298240780830383
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4376561641693115
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.420171320438385
Calibrated prediction for ORCL: 0.39651578664779663
Raw prediction for PCG: 0.4964243173599243
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.611305832862854
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5016391277313232
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5066705942153931
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.44035547971725464
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.3898102641105652
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4334249496459961
Calibrated prediction for PM: 0.5
Raw prediction for PPL: 0.5022168159484863
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4605114161968231
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4297737181186676
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5886945128440857
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.43234962224960327
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4975971281528473
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5189465284347534
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4647924304008484
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.33523160219192505
Calibrated prediction for SPLP: 0.2373877763748169

Simulating Trading Days:  27%|██▋       | 27/100 [04:44<01:29,  1.23s/it]

Raw prediction for SRE: 0.3699842095375061
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4800538718700409
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5269502401351929
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.36124110221862793
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5136479139328003
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.2938651442527771
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3422433137893677
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.5164369940757751
Calibrated prediction for UNH: 0.47826087474823
Raw prediction for UPS: 0.5810978412628174
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.5286266803741455
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5545386075973511
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5275604724884033
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5208656787872314
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4129306375980377
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5007174611091614
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.467
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.970, kelly=0.080) with $2017.91
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.102, kelly=0.375) with $9469.24
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.970, kelly=0.134) with $3384.79
[PORT] Sector Financial: 10 candidates, avg score=0.507
[PORT] Sector Financial: selecting V (p=0.580, b=1.032, kelly=0.173) with $4364.93
[PORT] Sector Healthcare: 10 candidates, avg score=0.479
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.021, kelly=0.076) with $1925.26
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.515
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.994, kelly=0.251) with $6342.72
[PORT] Sector Services: 10 candidates, avg score=0.520
[PORT] Sector Services: selecting PCLN (p=0.650, b=1.041, kelly=0.314) with $7920.91
[PORT] Sector Technology: 10 candidates, avg score=0.502
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.097, kelly=0.308) with $7769.53
[PORT] Sector Utilities: 10 candidates, avg score=0.504
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.903, kelly=0.223) with $5639.98
Raw prediction for AAPL: 0.4946724474430084
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5134045481681824
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4478045403957367
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5409278869628906
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4667584002017975
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.49011579155921936
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5814453363418579
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4608369767665863
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5160931348800659
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49559515714645386
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.45237934589385986
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5173768997192383
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.44403254985809326
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.4221718907356262
Calibrated prediction for BP: 0.3982318639755249
Raw prediction for BRK-A: 0.4547804892063141
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46683642268180847
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5287839770317078
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4855248034000397
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4597393870353699
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5542449951171875
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5212443470954895
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6562408208847046
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.47108083963394165
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4543114900588989
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.47760888934135437
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.44477754831314087
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4887264370918274
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4828436076641083
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5018119215965271
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5055516362190247
Calibrated prediction for DUK: 0.5141481757164001
Raw prediction for EXC: 0.5065648555755615
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5203492045402527
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5106266736984253
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.46032190322875977
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.39689764380455017
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4636783003807068
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5327675938606262
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6268510818481445
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.5008105635643005
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.4909764230251312
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5116630792617798
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4554596245288849
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5206751823425293
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4405834376811981
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5215151906013489
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5163624286651611
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5684394836425781
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47919654846191406
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.627799928188324
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.541158139705658
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4598795771598816
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5691046118736267
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.48195406794548035
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5329524874687195
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.43533140420913696
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.42144614458084106
Calibrated prediction for ORCL: 0.3978765904903412
Raw prediction for PCG: 0.49681735038757324
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6143152713775635
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5017305612564087
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.509675920009613
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4405688941478729
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.3887026011943817
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.42214033007621765
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5026645064353943
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45744597911834717
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4361857771873474
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5604129433631897
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4312504529953003
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49713805317878723
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5193217992782593
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.46741190552711487
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3264397978782654
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.36609947681427
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4816485047340393
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5791307091712952
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.37222424149513245
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5239467024803162
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2874883711338043
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.338422566652298
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.5193356275558472
Calibrated prediction for UNH: 0.5455684661865234
Raw prediction for UPS: 0.5844534635543823
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.535875141620636
Calibrated prediction for UTX: 0.5842176675796509
Raw prediction for V: 0.5566672682762146
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5359039306640625
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5233518481254578
Calibrated prediction for WFC: 0.5161290168762207

Simulating Trading Days:  28%|██▊       | 28/100 [04:45<01:26,  1.20s/it]

Raw prediction for WMT: 0.4083958566188812
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5015593767166138
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.468
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.970, kelly=0.080) with $2012.57
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.105, kelly=0.376) with $9505.65
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.457
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.984, kelly=0.145) with $3657.76
[PORT] Sector Financial: 10 candidates, avg score=0.507
[PORT] Sector Financial: selecting V (p=0.580, b=1.034, kelly=0.174) with $4399.99
[PORT] Sector Healthcare: 10 candidates, avg score=0.489
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.019, kelly=0.139) with $3505.08
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.519
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.992, kelly=0.251) with $6341.37
[PORT] Sector Services: 10 candidates, avg score=0.520
[PORT] Sector Services: selecting PCLN (p=0.650, b=1.038, kelly=0.313) with $7918.04
[PORT] Sector Technology: 10 candidates, avg score=0.504
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.096, kelly=0.307) with $7773.02
[PORT] Sector Utilities: 10 candidates, avg score=0.501
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.902, kelly=0.223) with $5635.85
Raw prediction for AAPL: 0.49398672580718994
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5134291648864746
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44793882966041565
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5383024215698242
Calibrated prediction for AEP: 0.5401471853256226
Raw prediction for AGFS: 0.4662354588508606
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4908786714076996
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5860145092010498
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4620826542377472
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5160353183746338
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49629804491996765
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4420011043548584
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5170283913612366
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.439603716135025
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.43369272351264954
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.45509660243988037
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46699610352516174
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5375933051109314
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4739628732204437
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4607316255569458
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5611142516136169
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5258393287658691
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6605191826820374
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4756010174751282
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4662899374961853
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4788565933704376
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.44865381717681885
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.495451956987381
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4829908311367035
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5015344023704529
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5000479817390442
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5064839720726013
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5204185843467712
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5112083554267883
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.46040162444114685
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4126013517379761
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4659240245819092
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5331816673278809
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.62404865026474
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.49988308548927307
Calibrated prediction for HSBC: 0.5232758522033691
Raw prediction for IEP: 0.4933641850948334
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5137646794319153
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4530948996543884
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5217466354370117
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4402469992637634
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.520807683467865
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5123291015625
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5683526396751404
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47980427742004395
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6252653002738953
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5426000952720642
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.46057555079460144
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5602365732192993
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.47860246896743774
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.535266637802124
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.4304857850074768
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.420431524515152
Calibrated prediction for ORCL: 0.39679354429244995
Raw prediction for PCG: 0.49696746468544006
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6144804358482361
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.501663327217102
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5113129615783691
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.44136208295822144
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.3877789378166199
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.41462668776512146
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5031646490097046
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45447230339050293
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4413580298423767
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5291118025779724
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.430402934551239
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49734461307525635
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5196325182914734
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.46792125701904297
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.31539231538772583
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3680071234703064
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.488715261220932
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.6130752563476562
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.3803996741771698
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5326963067054749
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.282330721616745
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3398089110851288
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.5164787173271179
Calibrated prediction for UNH: 0.47826087474823

Simulating Trading Days:  29%|██▉       | 29/100 [04:46<01:23,  1.17s/it]

Raw prediction for UPS: 0.585846483707428
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.5306660532951355
Calibrated prediction for UTX: 0.5842176675796509
Raw prediction for V: 0.5618013143539429
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5378404259681702
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5249418020248413
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4053550064563751
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5023752450942993
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.473
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.970, kelly=0.080) with $2014.51
[PORT] Sector Conglomerates: 7 candidates, avg score=0.458
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.946, kelly=0.229) with $5780.07
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.457
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.983, kelly=0.144) with $3649.42
[PORT] Sector Financial: 10 candidates, avg score=0.507
[PORT] Sector Financial: selecting V (p=0.580, b=1.034, kelly=0.174) with $4393.82
[PORT] Sector Healthcare: 10 candidates, avg score=0.482
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.021, kelly=0.139) with $3521.88
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.519
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.991, kelly=0.250) with $6323.25
[PORT] Sector Services: 10 candidates, avg score=0.539
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.066, kelly=0.377) with $9519.08
[PORT] Sector Technology: 10 candidates, avg score=0.504
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.095, kelly=0.307) with $7763.73
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting AEP (p=0.540, b=0.901, kelly=0.030) with $755.12
Raw prediction for AAPL: 0.4929240942001343
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.513344943523407
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4495076835155487
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5352268815040588
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.46477481722831726
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.491341233253479
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5937109589576721
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4624950885772705
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5159106254577637
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.497191846370697
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4328901767730713
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5176174640655518
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4360790252685547
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.4403029978275299
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.45330214500427246
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4670155346393585
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5467847585678101
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.45536118745803833
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46126705408096313
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5693036317825317
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.5089478492736816
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.6622426509857178
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4762745201587677
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4764477610588074
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.47998613119125366
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4525744616985321
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4964568614959717
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.483309805393219
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5014808773994446
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4993124008178711
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5066262483596802
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5205144882202148
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.511734127998352
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.45752254128456116
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4258711040019989
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4670734703540802
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5328795313835144
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.616784930229187
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4943443238735199
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.49829548597335815
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5149929523468018
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4475860595703125
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5226787328720093
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4397904872894287
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.520943820476532
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5055716037750244
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5681777596473694
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48021385073661804
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6238378882408142
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5428768992424011
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.46261751651763916
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5567852854728699
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.47622838616371155
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5360249876976013
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.42388448119163513
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.41824281215667725
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.497151255607605
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6057125926017761
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5013224482536316
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.512269914150238
Calibrated prediction for PFE: 0.534149706363678
Raw prediction for PG: 0.4408094882965088
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.3870719373226166
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4062660336494446
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5036353468894958
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4522835612297058
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.45744091272354126
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5018950700759888
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.4300409257411957
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4977753162384033
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5198978185653687
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4641170799732208
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.30889207124710083
Calibrated prediction for SPLP: 0.2373877763748169

Simulating Trading Days:  30%|███       | 30/100 [04:47<01:21,  1.16s/it]

Raw prediction for SRE: 0.36338451504707336
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.483871191740036
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.6148175597190857
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.3828204870223999
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5348336100578308
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2798716723918915
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3429516851902008
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.5086925029754639
Calibrated prediction for UNH: 0.47826087474823
Raw prediction for UPS: 0.5878161787986755
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.4927629828453064
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5652481317520142
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.53550124168396
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.525958776473999
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4057169556617737
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.503393828868866
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.473
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.968, kelly=0.079) with $1988.36
[PORT] Sector Conglomerates: 7 candidates, avg score=0.458
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.946, kelly=0.224) with $5671.00
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.457
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.986, kelly=0.145) with $3673.42
[PORT] Sector Financial: 10 candidates, avg score=0.502
[PORT] Sector Financial: selecting V (p=0.580, b=1.034, kelly=0.174) with $4391.02
[PORT] Sector Healthcare: 10 candidates, avg score=0.484
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.022, kelly=0.140) with $3527.53
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.515
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.993, kelly=0.251) with $6342.75
[PORT] Sector Services: 10 candidates, avg score=0.539
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.065, kelly=0.376) with $9512.80
[PORT] Sector Technology: 10 candidates, avg score=0.504
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.094, kelly=0.307) with $7748.39
[PORT] Sector Utilities: 10 candidates, avg score=0.487
[PORT] Sector Utilities: selecting D (p=0.537, b=0.887, kelly=0.015) with $385.60
Raw prediction for AAPL: 0.4916938543319702
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5136076807975769
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.451649934053421
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5387231111526489
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4635109305381775
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4915992319583893
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5935738682746887
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4621241092681885
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5158168077468872
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49825990200042725
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.42292770743370056
Calibrated prediction for BBL: 0.47300824522972107
Raw prediction for BCH: 0.5167970657348633
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.43263110518455505
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.44046714901924133
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4515572488307953
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4669504463672638
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5548553466796875
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.44027993083000183
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.46104705333709717
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5798884034156799
Calibrated prediction for CELG: 0.6164138317108154
Raw prediction for CHL: 0.483466774225235
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.6619579792022705
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.46796563267707825
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4828389286994934
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4813278019428253
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4534822106361389
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4899750351905823
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4836161136627197
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5016212463378906
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5025789737701416
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5069998502731323
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5206170082092285
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.511878252029419
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4466867446899414
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4304542541503906
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4667782485485077
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5324503183364868
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6044667363166809
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4850825369358063
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.5026766061782837
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5156650543212891
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.441789835691452
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5234221816062927
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4390457272529602
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.521744430065155
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.49345752596855164
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5684565305709839
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48006924986839294
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6237699389457703
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5440921783447266
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4598489999771118
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5531245470046997
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4703308343887329
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.543299674987793
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.42125681042671204
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.41549575328826904
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49954622983932495
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5879288911819458
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5010836720466614
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5120699405670166
Calibrated prediction for PFE: 0.5301380157470703
Raw prediction for PG: 0.4400060474872589
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.38712072372436523
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3988895118236542
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5054978132247925
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45007458329200745
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47556397318840027
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.47967004776000977
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.4282988905906677
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49773532152175903
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5201987028121948
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.46190518140792847
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3028046190738678
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.36920851469039917
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47416502237319946
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5945962071418762
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.3769983947277069
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5319085717201233
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2801763713359833
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.34503841400146484
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4957254230976105
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5904418230056763
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.4521746337413788
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5639018416404724
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5313761830329895
Calibrated prediction for VZ: 0.556209146976471

Simulating Trading Days:  31%|███       | 31/100 [04:49<01:19,  1.16s/it]

Raw prediction for WFC: 0.5264876484870911
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.40873414278030396
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5039364099502563
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.465
[PORT] Sector Basic Matierials: Kelly <= 0 for RDS-B (p=0.521, b=0.906)
[PORT] Sector Conglomerates: 7 candidates, avg score=0.452
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.947, kelly=0.225) with $5703.84
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.457
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.985, kelly=0.145) with $3676.70
[PORT] Sector Financial: 10 candidates, avg score=0.492
[PORT] Sector Financial: selecting V (p=0.580, b=1.033, kelly=0.173) with $4399.36
[PORT] Sector Healthcare: 10 candidates, avg score=0.484
[PORT] Sector Healthcare: selecting CELG (p=0.616, b=1.021, kelly=0.241) with $6110.37
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.492
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.995, kelly=0.251) with $6378.50
[PORT] Sector Services: 10 candidates, avg score=0.535
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.063, kelly=0.376) with $9533.67
[PORT] Sector Technology: 10 candidates, avg score=0.485
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.072, kelly=0.182) with $4624.99
[PORT] Sector Utilities: 10 candidates, avg score=0.505
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.900, kelly=0.222) with $5634.27
Raw prediction for AAPL: 0.4904623329639435
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5139808058738708
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4523138999938965
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5359920859336853
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4623633325099945
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.491861492395401
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5909417271614075
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.46126633882522583
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5157030820846558
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.499137282371521
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.41753503680229187
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.5122029185295105
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4301275908946991
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.43748003244400024
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4534620940685272
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4664319157600403
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5605292916297913
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.434183806180954
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4604145288467407
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5829223394393921
Calibrated prediction for CELG: 0.6164138317108154
Raw prediction for CHL: 0.46152263879776
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.6596604585647583
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4551602602005005
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4846121370792389
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4827097952365875
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.45188233256340027
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4813937544822693
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.48355212807655334
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5019207000732422
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4997752606868744
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5072287321090698
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5207514762878418
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5115788578987122
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4342184066772461
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4287397861480713
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4677523970603943
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5322005152702332
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5883399844169617
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4747042655944824
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.5059628486633301
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5161693692207336
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.43097519874572754
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.523759126663208
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4371514618396759
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5222117900848389
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.48133420944213867
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.568790078163147
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4791351556777954
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6242775917053223
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5451818108558655
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4561684727668762
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5494177937507629
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4684344530105591
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5508321523666382
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.4219997823238373
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4140011966228485
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4991232752799988
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5721765160560608
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5007676482200623
Calibrated prediction for PEP: 0.5000962615013123
Raw prediction for PFE: 0.5101428031921387
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43902477622032166
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.38641831278800964
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3923828899860382
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5054417848587036
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.44804084300994873
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4919620454311371
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.46122539043426514
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.42463481426239014
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4975678026676178
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.520458996295929
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4560259282588959
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.2987874150276184
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.36317703127861023
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47141197323799133
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5621964335441589
Calibrated prediction for TM: 0.4821428656578064

Simulating Trading Days:  32%|███▏      | 32/100 [04:50<01:18,  1.16s/it]

Raw prediction for TOT: 0.3719974458217621
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5285417437553406
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.28274813294410706
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.34789031744003296
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.48156100511550903
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5920318365097046
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.42116937041282654
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5585419535636902
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5222207307815552
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5266885757446289
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4134049415588379
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5039143562316895
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.459
[PORT] Sector Basic Matierials: Kelly <= 0 for RDS-B (p=0.521, b=0.906)
[PORT] Sector Conglomerates: 7 candidates, avg score=0.452
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.956, kelly=0.228) with $5806.64
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.444
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.974, kelly=0.136) with $3449.89
[PORT] Sector Financial: 10 candidates, avg score=0.489
[PORT] Sector Financial: selecting V (p=0.580, b=1.033, kelly=0.174) with $4410.88
[PORT] Sector Healthcare: 10 candidates, avg score=0.483
[PORT] Sector Healthcare: selecting CELG (p=0.616, b=1.020, kelly=0.240) with $6106.58
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.492
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.997, kelly=0.252) with $6413.19
[PORT] Sector Services: 10 candidates, avg score=0.535
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.063, kelly=0.376) with $9548.96
[PORT] Sector Technology: 10 candidates, avg score=0.482
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.070, kelly=0.182) with $4617.94
[PORT] Sector Utilities: 10 candidates, avg score=0.489
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.942, kelly=0.118) with $2993.59
Raw prediction for AAPL: 0.48935839533805847
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5141590237617493
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.45139357447624207
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.530423641204834
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.46155819296836853
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.49202221632003784
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5776420831680298
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.46006348729133606
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5156216025352478
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4996437132358551
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4143887460231781
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.5027146339416504
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.42779305577278137
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.4295394718647003
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.45738887786865234
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46598511934280396
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5637917518615723
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.434154748916626
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4593987762928009
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5809078812599182
Calibrated prediction for CELG: 0.6164138317108154
Raw prediction for CHL: 0.44714003801345825
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6528943777084351
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.43850216269493103
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4808602035045624
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48361846804618835
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4499172568321228
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4739651679992676
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4831429421901703
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5025116205215454
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4921705424785614
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5074788331985474
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5208266973495483
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.510977566242218
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4273298382759094
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4214725196361542
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4683375358581543
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5321148037910461
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5802227854728699
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.46459537744522095
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.5085015296936035
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5164401531219482
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.42109888792037964
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5236671566963196
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.43486109375953674
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5222964286804199
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4679018557071686
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5693211555480957
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.477855920791626
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6252438426017761
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5464096069335938
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.45138514041900635
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5432619452476501
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4677763879299164
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.558307945728302
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.42495641112327576
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4114457666873932
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4977702796459198
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5566412210464478
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5005995035171509
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5090344548225403
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4381462037563324
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.3890385925769806
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.38593339920043945
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5051347613334656
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.44638195633888245
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5005163550376892
Calibrated prediction for RDS-B: 0.5675675868988037
Raw prediction for REX: 0.4473324418067932
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.42205074429512024
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49745839834213257
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5206595063209534
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.44753459095954895
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.2917950451374054
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.35628101229667664
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47112029790878296
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5309582948684692
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.36877042055130005
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5251182317733765
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.28408798575401306
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.35096877813339233
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4688291549682617
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5908498764038086
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.39864394068717957
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5474397540092468
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5146339535713196
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5264514684677124
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4160095155239105
Calibrated prediction for WMT: 0.4189581871032715

Simulating Trading Days:  33%|███▎      | 33/100 [04:51<01:16,  1.14s/it]

Raw prediction for XOM: 0.5029891133308411
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.464
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.568, b=0.906, kelly=0.090) with $2299.39
[PORT] Sector Conglomerates: 7 candidates, avg score=0.452
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.954, kelly=0.228) with $5788.13
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.444
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.977, kelly=0.137) with $3486.46
[PORT] Sector Financial: 10 candidates, avg score=0.489
[PORT] Sector Financial: selecting V (p=0.580, b=1.031, kelly=0.173) with $4396.06
[PORT] Sector Healthcare: 10 candidates, avg score=0.483
[PORT] Sector Healthcare: selecting CELG (p=0.616, b=1.021, kelly=0.241) with $6120.18
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.492
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.998, kelly=0.253) with $6428.64
[PORT] Sector Services: 10 candidates, avg score=0.515
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.039, kelly=0.219) with $5568.46
[PORT] Sector Technology: 10 candidates, avg score=0.480
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.068, kelly=0.181) with $4599.92
[PORT] Sector Utilities: 10 candidates, avg score=0.489
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.941, kelly=0.117) with $2977.68
Raw prediction for AAPL: 0.48836326599121094
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5140875577926636
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44727182388305664
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5253908038139343
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.46003344655036926
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4919276535511017
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5588150024414062
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4586013853549957
Calibrated prediction for BA: 0.4838709533214569
Raw prediction for BABA: 0.5155015587806702
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49996161460876465
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.41866910457611084
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.4891280233860016
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.42658257484436035
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.42893552780151367
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4624538719654083
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4656013250350952
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5628241300582886
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4354986548423767
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45800045132637024
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5728064775466919
Calibrated prediction for CELG: 0.6164138317108154
Raw prediction for CHL: 0.43498438596725464
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6416551470756531
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.42529526352882385
Calibrated prediction for CMCSA: 0.43920063972473145
Raw prediction for CODI: 0.48380357027053833
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4842219650745392
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4537990391254425
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.469759076833725
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4824516177177429
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5031354427337646
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4834387004375458
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5077450275421143
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5208030343055725
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5104166269302368
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.42645877599716187
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.405000239610672
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4667150676250458
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5318151712417603
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5627481937408447
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4551515579223633
Calibrated prediction for HSBC: 0.47297295928001404
Raw prediction for IEP: 0.5106248259544373
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5169568061828613
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.41372162103652954
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5233780145645142
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.43202176690101624
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.522222638130188
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4482707977294922
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5696784853935242
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4766544997692108
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6269617676734924
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5487367510795593
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4445492625236511
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5375985503196716
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.46733129024505615
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5635584592819214
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.4274338483810425
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.40765559673309326
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4969642758369446
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5476605892181396
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5004827976226807
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5078780651092529
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43699342012405396
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.38967064023017883
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3775210380554199
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5051351189613342
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4456237554550171
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5049005150794983
Calibrated prediction for RDS-B: 0.5675675868988037
Raw prediction for REX: 0.4329676628112793
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.4256587624549866
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4976886510848999
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5209263563156128
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4395619332790375
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.29524677991867065
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3506614863872528
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47207921743392944
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5066626071929932
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.37488096952438354
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5209856033325195
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2817208170890808
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3527287542819977
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4565485119819641
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5854631066322327
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.3807291090488434
Calibrated prediction for UTX: 0.3193990886211395

Simulating Trading Days:  34%|███▍      | 34/100 [04:52<01:14,  1.12s/it]

Raw prediction for V: 0.5344659090042114
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5067339539527893
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5258591175079346
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4208645522594452
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5021266937255859
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.464
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.568, b=0.904, kelly=0.089) with $2271.82
[PORT] Sector Conglomerates: 7 candidates, avg score=0.456
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.952, kelly=0.227) with $5770.01
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.444
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.975, kelly=0.137) with $3474.01
[PORT] Sector Financial: 10 candidates, avg score=0.489
[PORT] Sector Financial: selecting V (p=0.580, b=1.033, kelly=0.173) with $4411.27
[PORT] Sector Healthcare: 10 candidates, avg score=0.480
[PORT] Sector Healthcare: selecting CELG (p=0.616, b=1.018, kelly=0.240) with $6097.66
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.492
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.998, kelly=0.253) with $6424.59
[PORT] Sector Services: 10 candidates, avg score=0.514
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.037, kelly=0.218) with $5548.64
[PORT] Sector Technology: 10 candidates, avg score=0.477
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.070, kelly=0.182) with $4622.17
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.940, kelly=0.117) with $2972.59
Raw prediction for AAPL: 0.4875546097755432
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5142375826835632
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44186195731163025
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5214401483535767
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4573343098163605
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.49161848425865173
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5478118062019348
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45730534195899963
Calibrated prediction for BA: 0.4725061357021332
Raw prediction for BABA: 0.5154184103012085
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5001125931739807
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.42754870653152466
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4760593771934509
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4271269738674164
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.4158499240875244
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.46490612626075745
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4651881754398346
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5628028512001038
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.435908704996109
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45691147446632385
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5570133924484253
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.42714864015579224
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.6287618279457092
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4138297140598297
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4848617613315582
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4852057695388794
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.46209919452667236
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.46783849596977234
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4816466271877289
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5038438439369202
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.47680750489234924
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5078817009925842
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5207919478416443
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5096456408500671
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4274672567844391
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.3884570896625519
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4626825749874115
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5321277976036072
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5458361506462097
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.44530361890792847
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5126692652702332
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5175395607948303
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.40571966767311096
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5229806900024414
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.42808547616004944
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5216863751411438
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.432235449552536
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5698672533035278
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47608882188796997
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6290513873100281
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5534684658050537
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4397774934768677
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.532688319683075
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4677688777446747
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5668985843658447
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.42993852496147156
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4088626801967621
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49606236815452576
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5379189252853394
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5001553893089294
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.509303629398346
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4364027976989746
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.38919949531555176
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3716960549354553
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5054007768630981
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4453378915786743
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.49923941493034363
Calibrated prediction for RDS-B: 0.5675675868988037
Raw prediction for REX: 0.42298784852027893
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.43269607424736023
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49754494428634644
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5211881399154663
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4290967583656311
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.30666255950927734
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.35587140917778015
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47297024726867676
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.4858459234237671
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.37531888484954834
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5181496739387512
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.28318971395492554
Calibrated prediction for UL: 0.3333333432674408

Simulating Trading Days:  35%|███▌      | 35/100 [04:53<01:12,  1.11s/it]

Raw prediction for UN: 0.3563781976699829
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.44812989234924316
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5729500651359558
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.3802671432495117
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5234660506248474
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.49656614661216736
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5252485275268555
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.41760703921318054
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5020365715026855
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.472
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.568, b=0.903, kelly=0.088) with $2254.37
[PORT] Sector Conglomerates: 7 candidates, avg score=0.454
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.951, kelly=0.207) with $5262.21
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.435
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.976, kelly=0.137) with $3484.75
[PORT] Sector Financial: 10 candidates, avg score=0.478
[PORT] Sector Financial: selecting V (p=0.580, b=1.031, kelly=0.173) with $4395.97
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.018, kelly=0.138) with $3522.30
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.491
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.998, kelly=0.253) with $6441.47
[PORT] Sector Services: 10 candidates, avg score=0.511
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.038, kelly=0.219) with $5574.81
[PORT] Sector Technology: 10 candidates, avg score=0.461
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.069, kelly=0.181) with $4621.74
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.939, kelly=0.116) with $2965.81
Raw prediction for AAPL: 0.48688173294067383
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5142691731452942
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.43800899386405945
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5178742408752441
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.454386442899704
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.49124640226364136
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5432925224304199
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4561651051044464
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5153433680534363
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5003076195716858
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4409882426261902
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.47105321288108826
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.42917245626449585
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.39427879452705383
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.46597445011138916
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46478939056396484
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5640770196914673
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.438089519739151
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4559582769870758
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5368802547454834
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.42353811860084534
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.6159682273864746
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4068198502063751
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.49282875657081604
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.48601841926574707
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4744345247745514
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4669947028160095
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4809434413909912
Calibrated prediction for DHR: 0.47826087474823
Raw prediction for DIS: 0.5046476721763611
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.47252723574638367
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5078379511833191
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5208133459091187
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5089192986488342
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4310314953327179
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.3729066550731659
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45904216170310974
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5324490666389465
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5336840152740479
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.4368801712989807
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5141836404800415
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.518280565738678
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3972536623477936
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5230023264884949
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.42476627230644226
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5208641886711121
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.42522087693214417
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5696077942848206
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4760969877243042
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6314895749092102
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5592076778411865
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4370436668395996
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5291053652763367
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4666115343570709
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5672416090965271
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.43586522340774536
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4102066457271576
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49467170238494873
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5339727997779846
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.49976611137390137
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5109111070632935
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.436572790145874
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.3906080424785614
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3685019016265869
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.505807638168335
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4465634226799011
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4892788827419281
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.41443413496017456
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.4446089565753937
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4971456527709961
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5214014649391174
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.41523486375808716
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.32393917441368103
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.36705246567726135
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47447505593299866
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.4622124135494232
Calibrated prediction for TM: 0.3962264060974121

Simulating Trading Days:  36%|███▌      | 36/100 [04:54<01:10,  1.11s/it]

Raw prediction for TOT: 0.3735470473766327
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5163841247558594
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.28788846731185913
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3632837235927582
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.44418659806251526
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5531861186027527
Calibrated prediction for UPS: 0.5640879273414612
Raw prediction for UTX: 0.39092472195625305
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.517128586769104
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.4889358580112457
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5250760316848755
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4157189130783081
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5023584365844727
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.467
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.971, kelly=0.080) with $2048.21
[PORT] Sector Conglomerates: 7 candidates, avg score=0.465
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.951, kelly=0.207) with $5283.60
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.435
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.975, kelly=0.136) with $3485.61
[PORT] Sector Financial: 10 candidates, avg score=0.473
[PORT] Sector Financial: selecting V (p=0.526, b=1.030, kelly=0.066) with $1694.16
[PORT] Sector Healthcare: 10 candidates, avg score=0.468
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.020, kelly=0.076) with $1933.58
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.999, kelly=0.253) with $6467.93
[PORT] Sector Services: 10 candidates, avg score=0.511
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.038, kelly=0.219) with $5587.08
[PORT] Sector Technology: 10 candidates, avg score=0.460
[PORT] Sector Technology: selecting TSM (p=0.569, b=1.069, kelly=0.166) with $4233.47
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.934, kelly=0.114) with $2911.99
Raw prediction for AAPL: 0.48633694648742676
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5141981244087219
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.43626970052719116
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5179956555366516
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.45154452323913574
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4906117916107178
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5351523756980896
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4551030099391937
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5152365565299988
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5007330775260925
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4618266522884369
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.47635573148727417
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4352940022945404
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.37454915046691895
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.47149935364723206
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4647344946861267
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5668476819992065
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4395740032196045
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45472338795661926
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5206469893455505
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.42981019616127014
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.6039664149284363
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.402683824300766
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.49872130155563354
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.48696279525756836
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4986233711242676
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.46828946471214294
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4802788496017456
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.505544900894165
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4698945879936218
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5077499151229858
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.520949125289917
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5084667801856995
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4326170086860657
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.3742308020591736
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45941030979156494
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5328487753868103
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5273904800415039
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.4318869709968567
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5158562660217285
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.519565224647522
Calibrated prediction for INTC: 0.5212751626968384
Raw prediction for JNJ: 0.39403030276298523
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5239980816841125
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4220941960811615
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5202223062515259
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.42570745944976807
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5695186853408813
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4767591655254364
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6348196864128113
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5684645175933838
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4340616762638092
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5278963446617126
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4647018313407898
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5696698427200317
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.43891170620918274
Calibrated prediction for NVS: 0.43103447556495667
Raw prediction for ORCL: 0.4156157970428467
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49471989274024963
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.53498375415802
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.49952390789985657
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5062486529350281
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4370027482509613
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.3947223722934723
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3669188916683197
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5072919726371765
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4494055211544037
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4811150133609772
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.41449210047721863
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.4568012058734894
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49696940183639526
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5214613676071167
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4063362181186676
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.34533748030662537
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.37843942642211914
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4751870334148407
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.4409901797771454
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.37540367245674133
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5214422345161438
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2934708297252655
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.37248215079307556
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.44480180740356445
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5289376378059387
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.39322108030319214
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5136789679527283
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.4854218363761902
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5253622531890869
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.41424280405044556
Calibrated prediction for WMT: 0.4189581871032715

Simulating Trading Days:  37%|███▋      | 37/100 [04:55<01:09,  1.11s/it]

Raw prediction for XOM: 0.5026180744171143
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.475
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.970, kelly=0.080) with $2034.67
[PORT] Sector Conglomerates: 7 candidates, avg score=0.465
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.955, kelly=0.208) with $5327.64
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.440
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.978, kelly=0.138) with $3520.26
[PORT] Sector Financial: 10 candidates, avg score=0.473
[PORT] Sector Financial: selecting V (p=0.526, b=1.028, kelly=0.065) with $1674.69
[PORT] Sector Healthcare: 10 candidates, avg score=0.471
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.020, kelly=0.076) with $1942.33
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.002, kelly=0.254) with $6500.46
[PORT] Sector Services: 10 candidates, avg score=0.509
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.037, kelly=0.218) with $5586.47
[PORT] Sector Technology: 10 candidates, avg score=0.462
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.070, kelly=0.182) with $4644.93
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.936, kelly=0.115) with $2936.51
Raw prediction for AAPL: 0.48581069707870483
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5142198204994202
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.43367865681648254
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5176123976707458
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.44901615381240845
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4897344708442688
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5336239337921143
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4541779160499573
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.515216588973999
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5010660886764526
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.47763684391975403
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.48193296790122986
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.44351673126220703
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.34497612714767456
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4782440960407257
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.464571475982666
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5682976245880127
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4386120140552521
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45347699522972107
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.504675567150116
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4317631125450134
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5922670960426331
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.3998691737651825
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.49800267815589905
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.4876716732978821
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5082027316093445
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.4687923491001129
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4796428978443146
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5064426064491272
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.46824169158935547
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5074523091316223
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209840536117554
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5080912113189697
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4286336302757263
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.3788841962814331
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45753681659698486
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5331447720527649
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5240275859832764
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.42840850353240967
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5176055431365967
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5201277136802673
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3904452323913574
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5249144434928894
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.41991961002349854
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.520165205001831
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.42110586166381836
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5690693855285645
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47727900743484497
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6382185816764832
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5735299587249756
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.430961012840271
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5283301472663879
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4642156958580017
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.572145402431488
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.43720543384552
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.42139995098114014
Calibrated prediction for ORCL: 0.39782726764678955
Raw prediction for PCG: 0.4940110445022583
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5291127562522888
Calibrated prediction for PCLN: 0.5714285969734192
Raw prediction for PEP: 0.4994325041770935
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.49713167548179626
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4368712604045868
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.39887896180152893
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.36646780371665955
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5076856017112732
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4527805745601654
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4768255054950714
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.4228284955024719
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.46596792340278625
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49659594893455505
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5213568210601807
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.39668262004852295
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.36683735251426697
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.3869030773639679
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47536399960517883
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.40406718850135803
Calibrated prediction for TM: 0.3586843013763428
Raw prediction for TOT: 0.3706654906272888
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5220783948898315
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.29562175273895264
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3769277334213257
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4445011019706726
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5059202313423157
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.39323416352272034
Calibrated prediction for UTX: 0.3193990886211395

Simulating Trading Days:  38%|███▊      | 38/100 [04:56<01:08,  1.10s/it]

Raw prediction for V: 0.5094640254974365
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.4806470572948456
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5256808400154114
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4143964648246765
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5025072693824768
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.475
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.968, kelly=0.079) with $2008.79
[PORT] Sector Conglomerates: 7 candidates, avg score=0.494
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.954, kelly=0.208) with $5320.28
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.436
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.979, kelly=0.138) with $3535.09
[PORT] Sector Financial: 10 candidates, avg score=0.475
[PORT] Sector Financial: selecting JPM (p=0.545, b=1.038, kelly=0.106) with $2714.08
[PORT] Sector Healthcare: 10 candidates, avg score=0.468
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.021, kelly=0.076) with $1952.32
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.003, kelly=0.255) with $6512.70
[PORT] Sector Services: 10 candidates, avg score=0.505
[PORT] Sector Services: selecting CHTR (p=0.598, b=1.145, kelly=0.247) with $6318.36
[PORT] Sector Technology: 10 candidates, avg score=0.465
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.069, kelly=0.181) with $4636.20
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.935, kelly=0.115) with $2927.91
Raw prediction for AAPL: 0.48539331555366516
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.514415979385376
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.430739164352417
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.517234742641449
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4471224844455719
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4894971251487732
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5306798219680786
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4532764256000519
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5151792168617249
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5016226768493652
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4860096275806427
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.48875221610069275
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.45049089193344116
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.3350755572319031
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4829520583152771
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4645209312438965
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5677758455276489
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.438603013753891
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45196616649627686
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4900311529636383
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.43979334831237793
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.581393301486969
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.39861616492271423
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4959205985069275
Calibrated prediction for CODI: 0.5372527837753296
Raw prediction for CSCO: 0.48796147108078003
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5188762545585632
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.47232770919799805
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.47904282808303833
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5070103406906128
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4663985073566437
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5072973966598511
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209240317344666
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5077869892120361
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4201023578643799
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.38484588265419006
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4554821848869324
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5331238508224487
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5213481783866882
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.426116019487381
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5191050171852112
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5201138854026794
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.388495534658432
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5256967544555664
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.41807717084884644
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5206142663955688
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4184856712818146
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5692355632781982
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47759366035461426
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6417628526687622
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5753424167633057
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.42880773544311523
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5288577079772949
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4632105529308319
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5764659643173218
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.4327528774738312
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4259966313838959
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4931384325027466
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5268227458000183
Calibrated prediction for PCLN: 0.5714285969734192
Raw prediction for PEP: 0.49959704279899597
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4888501465320587
Calibrated prediction for PFE: 0.45919492840766907
Raw prediction for PG: 0.4365290701389313
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4030763804912567
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3685300052165985
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5080776810646057
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45629680156707764
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4754181206226349
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.43763068318367004
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.47047996520996094
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4961375296115875
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5210721492767334
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.3890526294708252
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.38602808117866516
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.3941098749637604
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47698721289634705
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.36545529961586
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.3697449564933777
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5217443704605103
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.29302358627319336
Calibrated prediction for UL: 0.3333333432674408

Simulating Trading Days:  39%|███▉      | 39/100 [04:57<01:06,  1.10s/it]

Raw prediction for UN: 0.3757891058921814
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4436050057411194
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.48958030343055725
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3890374004840851
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5053357481956482
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.47826051712036133
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5261297821998596
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4165414869785309
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.502467155456543
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.476
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.968, kelly=0.079) with $2012.28
[PORT] Sector Conglomerates: 7 candidates, avg score=0.494
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.952, kelly=0.207) with $5291.37
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.435
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.982, kelly=0.139) with $3559.25
[PORT] Sector Financial: 10 candidates, avg score=0.475
[PORT] Sector Financial: selecting JPM (p=0.545, b=1.036, kelly=0.105) with $2689.34
[PORT] Sector Healthcare: 10 candidates, avg score=0.452
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.008, kelly=0.044) with $1127.36
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.005, kelly=0.255) with $6521.94
[PORT] Sector Services: 10 candidates, avg score=0.505
[PORT] Sector Services: selecting CHTR (p=0.598, b=1.141, kelly=0.246) with $6282.81
[PORT] Sector Technology: 10 candidates, avg score=0.474
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.068, kelly=0.181) with $4619.06
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.937, kelly=0.115) with $2949.31
Raw prediction for AAPL: 0.48500069975852966
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5146698951721191
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4273839294910431
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5171576142311096
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4462568759918213
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4892248809337616
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.52923983335495
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45285460352897644
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5151673555374146
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5021194815635681
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.49025362730026245
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.49330249428749084
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.45795688033103943
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.34074240922927856
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4830595850944519
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.464436411857605
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5666221380233765
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.43821024894714355
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45096126198768616
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4787256419658661
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4462270438671112
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5755658745765686
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.3989255428314209
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.48510172963142395
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48787960410118103
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5245497822761536
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.47501322627067566
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.47845402359962463
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5071836113929749
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.46431317925453186
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5072309374809265
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209038853645325
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5074660778045654
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4090902805328369
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.38348421454429626
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4520508050918579
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5336638689041138
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5182298421859741
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.424207866191864
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5194728374481201
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5196679830551147
Calibrated prediction for INTC: 0.5263074636459351
Raw prediction for JNJ: 0.38396310806274414
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5261256694793701
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.4170732796192169
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5208142995834351
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.41389140486717224
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5692801475524902
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4775116741657257
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6445088982582092
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5731921792030334
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4312492907047272
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5305665135383606
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.46434545516967773
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5779798030853271
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.4279671609401703
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.42881444096565247
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49204739928245544
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5275892019271851
Calibrated prediction for PCLN: 0.5714285969734192
Raw prediction for PEP: 0.4997311532497406
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4851958751678467
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4363165497779846
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4088713824748993
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.37318286299705505
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5078717470169067
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4586915075778961
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4745706617832184
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.455831915140152
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.47060540318489075
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4956248998641968
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5207708477973938
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.3846559524536133
Calibrated prediction for SO: 0.4141654372215271

Simulating Trading Days:  40%|████      | 40/100 [04:58<01:06,  1.11s/it]

Raw prediction for SPLP: 0.40146881341934204
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.3966084420681
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.47941750288009644
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.33915361762046814
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.3751074969768524
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5189608931541443
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2857021391391754
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.37234535813331604
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4409366548061371
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.47980833053588867
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3926541805267334
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5009406805038452
Calibrated prediction for V: 0.4871591627597809
Raw prediction for VZ: 0.4783641993999481
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5261019468307495
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.41995760798454285
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5022905468940735
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.481
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.967, kelly=0.128) with $3280.37
[PORT] Sector Conglomerates: 7 candidates, avg score=0.483
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.952, kelly=0.207) with $5295.49
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.435
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.980, kelly=0.139) with $3546.83
[PORT] Sector Financial: 10 candidates, avg score=0.471
[PORT] Sector Financial: selecting JPM (p=0.545, b=1.034, kelly=0.104) with $2670.27
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.007, kelly=0.044) with $1114.71
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.006, kelly=0.256) with $6537.28
[PORT] Sector Services: 10 candidates, avg score=0.499
[PORT] Sector Services: selecting PCLN (p=0.571, b=1.040, kelly=0.159) with $4071.45
[PORT] Sector Technology: 10 candidates, avg score=0.473
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.065, kelly=0.180) with $4600.74
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.936, kelly=0.115) with $2940.81
Raw prediction for AAPL: 0.48478963971138
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5147109627723694
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.42537984251976013
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5181165933609009
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.44588690996170044
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4890774190425873
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5326350331306458
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45298200845718384
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5151835680007935
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.502801239490509
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4916708171367645
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.49527356028556824
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4650648534297943
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.35134318470954895
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4833804666996002
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4644700586795807
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5644508600234985
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.43923452496528625
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4506012797355652
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4700731039047241
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.45365944504737854
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5701770186424255
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4008471965789795
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.474685937166214
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4879148006439209
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5258479118347168
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.48056262731552124
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.47796016931533813
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5068941712379456
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.46394118666648865
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5072101354598999
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209918022155762
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5074846148490906
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4002353549003601
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.3894672095775604
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.44900962710380554
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5345422625541687
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5155445337295532
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.42233648896217346
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5193197727203369
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5197979211807251
Calibrated prediction for INTC: 0.532670795917511
Raw prediction for JNJ: 0.37943917512893677
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5263513922691345
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.4160546064376831
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5206107497215271
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4151843190193176
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5693041086196899
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47757387161254883
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6459413766860962
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.569294810295105
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4369741380214691
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5335975885391235
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.46666419506073
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5776920318603516
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.42267292737960815
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.43397659063339233
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4914191961288452
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5322731733322144
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.49978122115135193
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4831463396549225
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.43588343262672424
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41549333930015564
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.37684354186058044
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5082575678825378
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4607142210006714
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47479018568992615
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.47534042596817017
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.46674826741218567
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49522674083709717
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5205990076065063
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.38328084349632263
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.4084711968898773
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.40184518694877625
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.48098304867744446
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.32434019446372986
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.376817911863327
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5168372392654419
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.2781960368156433
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3688561022281647
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.436989963054657
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4728270471096039
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.40652525424957275
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.4996289312839508
Calibrated prediction for V: 0.4871591627597809
Raw prediction for VZ: 0.4829471707344055
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5257720351219177
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.42330923676490784
Calibrated prediction for WMT: 0.4189581871032715

Simulating Trading Days:  41%|████      | 41/100 [05:00<01:05,  1.11s/it]

Raw prediction for XOM: 0.501420259475708
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.481
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.969, kelly=0.129) with $3299.88
[PORT] Sector Conglomerates: 7 candidates, avg score=0.483
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.950, kelly=0.206) with $5280.55
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.430
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.980, kelly=0.138) with $3539.88
[PORT] Sector Financial: 10 candidates, avg score=0.471
[PORT] Sector Financial: selecting JPM (p=0.545, b=1.034, kelly=0.105) with $2676.66
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.005, kelly=0.043) with $1095.60
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.008, kelly=0.256) with $6559.56
[PORT] Sector Services: 10 candidates, avg score=0.502
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.037, kelly=0.218) with $5587.34
[PORT] Sector Technology: 10 candidates, avg score=0.473
[PORT] Sector Technology: selecting TSM (p=0.569, b=1.063, kelly=0.164) with $4182.48
[PORT] Sector Utilities: 10 candidates, avg score=0.488
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.935, kelly=0.114) with $2921.04
Raw prediction for AAPL: 0.4847196042537689
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5145394802093506
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.42440858483314514
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5187726020812988
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4457835555076599
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4890090525150299
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5357781648635864
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4533114433288574
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5152563452720642
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5034050941467285
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.49650081992149353
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.4966137111186981
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.47299259901046753
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.3809388279914856
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.48421406745910645
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46470245718955994
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5635928511619568
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.44071921706199646
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4503823518753052
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.46039557456970215
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4577542245388031
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5666760802268982
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.40342599153518677
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.45671939849853516
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4876921772956848
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.527317464351654
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.4924941658973694
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.47767373919487
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5063793659210205
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4663889706134796
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5071757435798645
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5210754871368408
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5078001022338867
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.39798375964164734
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.39305078983306885
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.44616976380348206
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5352987051010132
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5158427357673645
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.4219374358654022
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5190186500549316
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5193344950675964
Calibrated prediction for INTC: 0.5099758505821228
Raw prediction for JNJ: 0.3763952851295471
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5261112451553345
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.41599056124687195
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5206229090690613
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4194612205028534
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5697380900382996
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4778237044811249
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6466434597969055
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5651997923851013
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.44800370931625366
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5365778207778931
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.46996909379959106
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5741856098175049
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.41670724749565125
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.43671515583992004
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49084627628326416
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5353441834449768
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.49991026520729065
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4818182587623596
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.43566375970840454
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4207446873188019
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3809449374675751
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.509490430355072
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4627131521701813
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4744235873222351
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.4953286051750183
Calibrated prediction for REX: 0.42853134870529175
Raw prediction for SLB: 0.46229657530784607
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49474573135375977
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5206961631774902
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.3807711899280548
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.4051344096660614
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4072498679161072
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.48251253366470337
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.33281585574150085
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.3788917362689972
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5133007168769836
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.27734729647636414
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.37073320150375366
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.43086662888526917
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.46894142031669617
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.41880670189857483
Calibrated prediction for UTX: 0.3193990886211395

Simulating Trading Days:  42%|████▏     | 42/100 [05:01<01:04,  1.10s/it]

Raw prediction for V: 0.4996240437030792
Calibrated prediction for V: 0.4871591627597809
Raw prediction for VZ: 0.48652711510658264
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5251296162605286
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.42217692732810974
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5002913475036621
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.481
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.968, kelly=0.129) with $3283.52
[PORT] Sector Conglomerates: 7 candidates, avg score=0.483
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.951, kelly=0.207) with $5265.23
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.430
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.980, kelly=0.139) with $3535.44
[PORT] Sector Financial: 10 candidates, avg score=0.471
[PORT] Sector Financial: selecting JPM (p=0.545, b=1.035, kelly=0.105) with $2673.45
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.006, kelly=0.043) with $1107.07
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.007, kelly=0.256) with $6527.00
[PORT] Sector Services: 10 candidates, avg score=0.502
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.035, kelly=0.218) with $5544.80
[PORT] Sector Technology: 10 candidates, avg score=0.470
[PORT] Sector Technology: selecting TSM (p=0.569, b=1.063, kelly=0.163) with $4163.65
[PORT] Sector Utilities: 10 candidates, avg score=0.493
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.935, kelly=0.114) with $2909.75
Raw prediction for AAPL: 0.4849321246147156
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5140800476074219
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4237067997455597
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5213630199432373
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.44561660289764404
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4888606369495392
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5271493196487427
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4535817503929138
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5151404738426208
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5037541389465332
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5017434358596802
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.4991324841976166
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.48004963994026184
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.40417802333831787
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.485368549823761
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46508923172950745
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5672568678855896
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.44278478622436523
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4502176344394684
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4518468379974365
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4650952219963074
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5690014958381653
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4109981060028076
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4385518729686737
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4872680604457855
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.525537371635437
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.5064452886581421
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4778440594673157
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5056754946708679
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4705473780632019
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5073246359825134
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5210821628570557
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5082583427429199
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4024951756000519
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.3979136645793915
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45147988200187683
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5354979634284973
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5202189087867737
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.4245133399963379
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5185887217521667
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.51862633228302
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.37549635767936707
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5254140496253967
Calibrated prediction for JPM: 0.5448257327079773
Raw prediction for KO: 0.4174548387527466
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5210647583007812
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4287196099758148
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5712226033210754
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47811681032180786
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6477076411247253
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5604628920555115
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.463764488697052
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5381855368614197
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4772725999355316
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5715535283088684
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.41466671228408813
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4366936981678009
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.491156667470932
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5614921450614929
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5000972747802734
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4855038821697235
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.43704742193222046
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4243846535682678
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.3911587595939636
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5097571611404419
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4644920825958252
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47353243827819824
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5157846808433533
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.45785215497016907
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4943934381008148
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5210802555084229
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.3845047652721405
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.40083378553390503
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4216279983520508
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4856390357017517
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.3626408576965332
Calibrated prediction for TM: 0.3477618992328644

Simulating Trading Days:  43%|████▎     | 43/100 [05:02<01:03,  1.11s/it]

Raw prediction for TOT: 0.37900468707084656
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5109851360321045
Calibrated prediction for TSM: 0.568965494632721
Raw prediction for UL: 0.28830990195274353
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.38517075777053833
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.42852655053138733
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4711175560951233
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4137573838233948
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5031763911247253
Calibrated prediction for V: 0.4871591627597809
Raw prediction for VZ: 0.4915531873703003
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5237701535224915
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.41036415100097656
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49927327036857605
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.481
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.970, kelly=0.130) with $3299.09
[PORT] Sector Conglomerates: 7 candidates, avg score=0.489
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.949, kelly=0.206) with $5237.63
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.435
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.979, kelly=0.138) with $3516.49
[PORT] Sector Financial: 10 candidates, avg score=0.471
[PORT] Sector Financial: selecting JPM (p=0.545, b=1.038, kelly=0.106) with $2706.23
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.004, kelly=0.043) with $1081.31
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.007, kelly=0.256) with $6509.83
[PORT] Sector Services: 10 candidates, avg score=0.502
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.032, kelly=0.216) with $5501.37
[PORT] Sector Technology: 10 candidates, avg score=0.472
[PORT] Sector Technology: selecting TSM (p=0.569, b=1.058, kelly=0.162) with $4112.47
[PORT] Sector Utilities: 10 candidates, avg score=0.493
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.930, kelly=0.112) with $2846.68
Raw prediction for AAPL: 0.48550623655319214
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5139034986495972
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.42519429326057434
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5255085825920105
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.44458162784576416
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4887230098247528
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5439258813858032
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45383623242378235
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.515348494052887
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5037986040115356
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5051680207252502
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5081730484962463
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.48476240038871765
Calibrated prediction for BHP: 0.5283173322677612
Raw prediction for BP: 0.42030468583106995
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.49298810958862305
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4653664827346802
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5742613673210144
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.45046761631965637
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45014438033103943
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4442930817604065
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.490817666053772
Calibrated prediction for CHL: 0.5352411270141602
Raw prediction for CHTR: 0.5726436972618103
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4252200126647949
Calibrated prediction for CMCSA: 0.4386875033378601
Raw prediction for CODI: 0.4238583743572235
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48749664425849915
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5178371667861938
Calibrated prediction for CVX: 0.5333333611488342
Raw prediction for D: 0.5128011703491211
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.478313148021698
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5051849484443665
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4815554916858673
Calibrated prediction for DUK: 0.4602268636226654
Raw prediction for EXC: 0.5073896050453186
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5212565660476685
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.50877845287323
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4072036147117615
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.43178483843803406
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.45559078454971313
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5355598330497742
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5270285606384277
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.42862674593925476
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5168008208274841
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.519496500492096
Calibrated prediction for INTC: 0.517909586429596
Raw prediction for JNJ: 0.37280797958374023
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5240936279296875
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.42184656858444214
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5214872360229492
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4490237534046173
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.572590172290802
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47840142250061035
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6488224267959595
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5563510060310364
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.47206997871398926
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.537993311882019
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4851371943950653
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.570926308631897
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.41138261556625366
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4449726343154907
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4921574890613556
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5837159752845764
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5005778670310974
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4823664426803589
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.43938738107681274
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.42564713954925537
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4113466143608093
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5100381970405579
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4671914279460907
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4729101061820984
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5367294549942017
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.45459800958633423
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4948410093784332
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5215383172035217
Calibrated prediction for SNY: 0.5226953625679016
Raw prediction for SO: 0.3921031653881073
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3940972685813904
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.43705061078071594
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4880445897579193
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.43558022379875183
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.3789369761943817
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5200344324111938
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.312039852142334
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.41029465198516846
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.42997634410858154
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.47500482201576233
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4046678841114044
Calibrated prediction for UTX: 0.3193990886211395

Simulating Trading Days:  44%|████▍     | 44/100 [05:03<01:02,  1.12s/it]

Raw prediction for V: 0.5125724077224731
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5003277659416199
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5212611556053162
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.39871689677238464
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49836137890815735
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.486
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.971, kelly=0.130) with $3317.58
[PORT] Sector Conglomerates: 7 candidates, avg score=0.489
[PORT] Sector Conglomerates: selecting HRG (p=0.613, b=0.948, kelly=0.205) with $5231.62
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.440
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.982, kelly=0.139) with $3551.95
[PORT] Sector Financial: 10 candidates, avg score=0.478
[PORT] Sector Financial: selecting V (p=0.526, b=1.022, kelly=0.063) with $1604.72
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting SNY (p=0.523, b=1.004, kelly=0.047) with $1202.76
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.005, kelly=0.255) with $6509.28
[PORT] Sector Services: 10 candidates, avg score=0.504
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.031, kelly=0.216) with $5502.61
[PORT] Sector Technology: 10 candidates, avg score=0.483
[PORT] Sector Technology: selecting TSM (p=0.577, b=1.057, kelly=0.177) with $4508.43
[PORT] Sector Utilities: 10 candidates, avg score=0.493
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.930, kelly=0.112) with $2857.49
Raw prediction for AAPL: 0.4860647916793823
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5141587257385254
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.42782536149024963
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5320308804512024
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.44249221682548523
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48848778009414673
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5641818642616272
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4540020227432251
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5156500339508057
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5035513043403625
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5072038769721985
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5135014057159424
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4855332374572754
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.43121618032455444
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4999481439590454
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46508583426475525
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5803489685058594
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.45655331015586853
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4500167667865753
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4393005669116974
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.5042321085929871
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5787511467933655
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.44170942902565
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.41707128286361694
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4876757562160492
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5032606720924377
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.5163370370864868
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.47939351201057434
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5051200985908508
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4970417320728302
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5073853731155396
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5213339924812317
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.509452223777771
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4077744781970978
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.46933451294898987
Calibrated prediction for GOOG: 0.529411792755127
Raw prediction for HD: 0.4639284610748291
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5356664061546326
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5362410545349121
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.4342980682849884
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5122649073600769
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5191957354545593
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3700626492500305
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.522431492805481
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4266336262226105
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5232473015785217
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4793928563594818
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5735688805580139
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47833824157714844
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6498953104019165
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5513806939125061
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.47259336709976196
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5421661734580994
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.49417978525161743
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5698254704475403
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.40919023752212524
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4505782425403595
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49322980642318726
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6065881252288818
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5008962154388428
Calibrated prediction for PEP: 0.5041191577911377
Raw prediction for PFE: 0.4797708988189697
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4410382807254791
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.42584913969039917
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.437206894159317
Calibrated prediction for PM: 0.5
Raw prediction for PPL: 0.5095967650413513
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46964481472969055
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.47305828332901
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.558169960975647
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4523420035839081
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49578535556793213
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5220701098442078
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4010395407676697
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3880004286766052
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4373411238193512
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4908992350101471
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5228602290153503
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.3789297044277191
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5278785228729248
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3472011685371399
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4405636787414551
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4392264187335968
Calibrated prediction for UNH: 0.41128528118133545

Simulating Trading Days:  45%|████▌     | 45/100 [05:05<01:12,  1.31s/it]

Raw prediction for UPS: 0.4770677089691162
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3932088017463684
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5277009010314941
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5082371234893799
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5189244747161865
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.3875507712364197
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.4978673756122589
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.493
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.970, kelly=0.130) with $3305.03
[PORT] Sector Conglomerates: 7 candidates, avg score=0.506
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.087, kelly=0.371) with $9449.30
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.462
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.982, kelly=0.140) with $3557.34
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.580, b=1.024, kelly=0.170) with $4330.42
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.001, kelly=0.050) with $1262.36
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.006, kelly=0.256) with $6512.16
[PORT] Sector Services: 10 candidates, avg score=0.518
[PORT] Sector Services: selecting PCLN (p=0.650, b=1.032, kelly=0.311) with $7918.86
[PORT] Sector Technology: 10 candidates, avg score=0.513
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.103, kelly=0.309) with $7883.72
[PORT] Sector Utilities: 10 candidates, avg score=0.494
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.932, kelly=0.113) with $2874.08
Raw prediction for AAPL: 0.48614174127578735
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5143654942512512
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.42929279804229736
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5369756817817688
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.44049811363220215
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4882901608943939
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5864660143852234
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4540310502052307
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.51597660779953
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.502975344657898
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5043273568153381
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5127807855606079
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4823533594608307
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4282551109790802
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.5059639811515808
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4642946422100067
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5821803212165833
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4600675106048584
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.44996699690818787
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.43611347675323486
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4978621006011963
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5830868482589722
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.45506030321121216
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.41428375244140625
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48735615611076355
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.47755810618400574
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5169297456741333
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48033738136291504
Calibrated prediction for DHR: 0.47676196694374084
Raw prediction for DIS: 0.5055039525032043
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5145320892333984
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5073204040527344
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5212645530700684
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5100077390670776
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.40705692768096924
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.49495673179626465
Calibrated prediction for GOOG: 0.5714285969734192
Raw prediction for HD: 0.4668703079223633
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5355907082557678
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5481767058372498
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.4365406036376953
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.505740225315094
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.51787930727005
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3657795786857605
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5208023190498352
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.43138715624809265
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5249365568161011
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5055111050605774
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5736176371574402
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4782443046569824
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6515394449234009
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5436989665031433
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4737423062324524
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5485060214996338
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5000900626182556
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5640935897827148
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.40678325295448303
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.44758376479148865
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49348410964012146
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6095448732376099
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5009720325469971
Calibrated prediction for PEP: 0.5064915418624878
Raw prediction for PFE: 0.4791366159915924
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4415532648563385
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.42819568514823914
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.46279269456863403
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5084872841835022
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4711311459541321
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4748796224594116
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5731741189956665
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4478054940700531
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49671944975852966
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5224730968475342
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.40605777502059937
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.376812607049942
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.4302136301994324
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4912519156932831
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5554063320159912
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.3776078522205353
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5292378067970276
Calibrated prediction for TSM: 0.5770066976547241

Simulating Trading Days:  46%|████▌     | 46/100 [05:06<01:14,  1.39s/it]

Raw prediction for UL: 0.38553911447525024
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.46593180298805237
Calibrated prediction for UN: 0.4492723047733307
Raw prediction for UNH: 0.4493370056152344
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4716533124446869
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3770318031311035
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5386959910392761
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5123374462127686
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5166317820549011
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.3776993751525879
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.4973243772983551
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.480
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.970, kelly=0.130) with $3301.17
[PORT] Sector Conglomerates: 7 candidates, avg score=0.502
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.085, kelly=0.370) with $9424.16
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.474
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.983, kelly=0.140) with $3563.86
[PORT] Sector Financial: 10 candidates, avg score=0.490
[PORT] Sector Financial: selecting V (p=0.580, b=1.023, kelly=0.169) with $4307.90
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=0.999, kelly=0.049) with $1234.82
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.005, kelly=0.255) with $6496.40
[PORT] Sector Services: 10 candidates, avg score=0.537
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.052, kelly=0.373) with $9481.98
[PORT] Sector Technology: 10 candidates, avg score=0.520
[PORT] Sector Technology: selecting CHL (p=0.638, b=1.100, kelly=0.309) with $7854.70
[PORT] Sector Utilities: 10 candidates, avg score=0.503
[PORT] Sector Utilities: selecting NGG (p=0.572, b=0.930, kelly=0.112) with $2846.37
Raw prediction for AAPL: 0.48593631386756897
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5147079229354858
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4309197664260864
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5407684445381165
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.43901321291923523
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4880738854408264
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6097422242164612
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45383843779563904
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5162168145179749
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5023424625396729
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5040021538734436
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5064969062805176
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.47846198081970215
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.431546151638031
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.5104113221168518
Calibrated prediction for BRK-A: 0.5142857432365417
Raw prediction for BSAC: 0.4634377062320709
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5813634991645813
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4619484543800354
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.44996029138565063
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4354400038719177
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.48584166169166565
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5902701020240784
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4647586941719055
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.41453367471694946
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48696568608283997
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.46629732847213745
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.519138514995575
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4811140298843384
Calibrated prediction for DHR: 0.4848833382129669
Raw prediction for DIS: 0.5060856342315674
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5305022597312927
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5072323083877563
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5212166905403137
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5102380514144897
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4067232310771942
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5183025598526001
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.4642561376094818
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5357014536857605
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5615065693855286
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4350931942462921
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4983324706554413
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5174880027770996
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3599204421043396
Calibrated prediction for JNJ: 0.3970351219177246
Raw prediction for JPM: 0.5195971131324768
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4364453852176666
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5262889266014099
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5212350487709045
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5738163590431213
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47818928956985474
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6531003713607788
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5367380976676941
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.47561338543891907
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.554977297782898
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5023621320724487
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5575006008148193
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.40331047773361206
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.44462937116622925
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4934886395931244
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6095162630081177
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5009177923202515
Calibrated prediction for PEP: 0.5047943592071533
Raw prediction for PFE: 0.4767591655254364
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4413994252681732
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.42781275510787964
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.48110851645469666
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5086653232574463
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.472141832113266
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.47739943861961365
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5823221206665039
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.44340288639068604
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4974527955055237
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5227614045143127
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.40494972467422485
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3654245138168335
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.42318907380104065
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4887911379337311
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5745986104011536
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.3794696033000946
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5308496356010437
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4147845208644867
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.48382821679115295
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.456916481256485
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4667105972766876
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.36554741859436035
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5450436472892761
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5155597925186157
Calibrated prediction for VZ: 0.52173912525177

Simulating Trading Days:  47%|████▋     | 47/100 [05:08<01:13,  1.39s/it]

Raw prediction for WFC: 0.5146166682243347
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.3718069791793823
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.4969181716442108
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.480
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.971, kelly=0.130) with $3314.29
[PORT] Sector Conglomerates: 7 candidates, avg score=0.504
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.087, kelly=0.371) with $9463.60
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.484
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.989, kelly=0.147) with $3746.98
[PORT] Sector Financial: 10 candidates, avg score=0.500
[PORT] Sector Financial: selecting V (p=0.580, b=1.022, kelly=0.169) with $4309.39
[PORT] Sector Healthcare: 10 candidates, avg score=0.447
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=0.997, kelly=0.048) with $1214.79
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.004, kelly=0.255) with $6510.26
[PORT] Sector Services: 10 candidates, avg score=0.537
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.052, kelly=0.373) with $9504.59
[PORT] Sector Technology: 10 candidates, avg score=0.506
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.050, kelly=0.258) with $6585.10
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.899, kelly=0.222) with $5652.75
Raw prediction for AAPL: 0.48569390177726746
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5148497223854065
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.43118491768836975
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5469030141830444
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4381199777126312
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4878355860710144
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6285141706466675
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4532639682292938
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5163596272468567
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5016629695892334
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.504299521446228
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.4982526898384094
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.475795179605484
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4385327994823456
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.511533796787262
Calibrated prediction for BRK-A: 0.5142857432365417
Raw prediction for BSAC: 0.4629034101963043
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5797078013420105
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.459703654050827
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4497407078742981
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4357493817806244
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4831365942955017
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.597431480884552
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.46947112679481506
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4165209233760834
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48635199666023254
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.46203678846359253
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5196411609649658
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48192471265792847
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5068180561065674
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5409615635871887
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.507044792175293
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5211776494979858
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5102996230125427
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.40791916847229004
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5436122417449951
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.45444151759147644
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5355082750320435
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5758578181266785
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.43005630373954773
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.49063703417778015
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5176913142204285
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.35312318801879883
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5186606049537659
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4408223628997803
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5273268818855286
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5206151008605957
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5732200145721436
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4782271981239319
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6545835733413696
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5320366024971008
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4776918590068817
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5591578483581543
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.49975597858428955
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5506656169891357
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.4024584889411926
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.44149166345596313
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.493579238653183
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.61198490858078
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5008692145347595
Calibrated prediction for PEP: 0.5032743215560913
Raw prediction for PFE: 0.47463586926460266
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4406610131263733
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.42305347323417664
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4902060627937317
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5085344910621643
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.47242507338523865
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.48129212856292725
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5871412754058838
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4416912794113159
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49839869141578674
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5230265855789185
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4001636505126953
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.35885336995124817
Calibrated prediction for SPLP: 0.3333333432674408

Simulating Trading Days:  48%|████▊     | 48/100 [05:09<01:09,  1.33s/it]

Raw prediction for SRE: 0.4177398979663849
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4884133040904999
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.5821331739425659
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.3864259421825409
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5316497683525085
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.43174654245376587
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4948216676712036
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.4630424678325653
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.4625910222530365
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.35304781794548035
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5530720353126526
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.517754852771759
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5131552815437317
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.3688056170940399
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.4967814087867737
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.480
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.969, kelly=0.129) with $3299.92
[PORT] Sector Conglomerates: 7 candidates, avg score=0.488
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.089, kelly=0.371) with $9487.12
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.484
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.989, kelly=0.147) with $3753.21
[PORT] Sector Financial: 10 candidates, avg score=0.500
[PORT] Sector Financial: selecting V (p=0.580, b=1.022, kelly=0.169) with $4313.58
[PORT] Sector Healthcare: 10 candidates, avg score=0.449
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.000, kelly=0.049) with $1243.24
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.005, kelly=0.255) with $6523.94
[PORT] Sector Services: 10 candidates, avg score=0.537
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.054, kelly=0.373) with $9529.95
[PORT] Sector Technology: 10 candidates, avg score=0.506
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.052, kelly=0.259) with $6608.16
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.898, kelly=0.221) with $5646.48
Raw prediction for AAPL: 0.48551225662231445
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5157873630523682
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4303939640522003
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.551729679107666
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4382486641407013
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4875742793083191
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6231762766838074
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45250043272972107
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5163820385932922
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5011090040206909
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.50916588306427
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.48918190598487854
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.47749966382980347
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4396628141403198
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.5098435878753662
Calibrated prediction for BRK-A: 0.5142857432365417
Raw prediction for BSAC: 0.4625166952610016
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5790136456489563
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.45353376865386963
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.44879862666130066
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4352457523345947
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.47888481616973877
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.6034226417541504
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4724693298339844
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.41954290866851807
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48589974641799927
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4626488983631134
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5211395621299744
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4827589690685272
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5074250102043152
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5443484783172607
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5066702365875244
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5211421251296997
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5102593898773193
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.40803614258766174
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5706664323806763
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.4520537555217743
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5355184674263
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5921509265899658
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4230791926383972
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4859331250190735
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5182704329490662
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.35091856122016907
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5182255506515503
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44384849071502686
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5277806520462036
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.5092900395393372
Calibrated prediction for MA: 0.5769230723381042
Raw prediction for MCD: 0.5730516910552979
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47822707891464233
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.656417965888977
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5342782735824585
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4814939498901367
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5584776997566223
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4946567714214325
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5433394312858582
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.4021279513835907
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4341580271720886
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.493960440158844
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6258845329284668
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.500956654548645
Calibrated prediction for PEP: 0.5060103535652161
Raw prediction for PFE: 0.46913769841194153
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.44017598032951355
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.42145341634750366
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.48852816224098206
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5084389448165894
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.47248509526252747
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4821486175060272
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5891032218933105
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4443402886390686
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49936673045158386
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5231726169586182
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.39864498376846313
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3560381531715393
Calibrated prediction for SPLP: 0.3333333432674408
Raw prediction for SRE: 0.4143332839012146
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.49386924505233765
Calibrated prediction for T: 0.44410625100135803
Raw prediction for TM: 0.6189712882041931
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.390168696641922
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5333885550498962
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.44059908390045166
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.5013965964317322
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.46642807126045227
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.45419856905937195
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3374468684196472
Calibrated prediction for UTX: 0.3193990886211395

Simulating Trading Days:  49%|████▉     | 49/100 [05:10<01:05,  1.28s/it]

Raw prediction for V: 0.5602589249610901
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5223913788795471
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5120159387588501
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.3733172118663788
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49699243903160095
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.480
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.967, kelly=0.128) with $3267.00
[PORT] Sector Conglomerates: 7 candidates, avg score=0.488
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.087, kelly=0.371) with $9441.59
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.484
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.991, kelly=0.148) with $3761.48
[PORT] Sector Financial: 10 candidates, avg score=0.500
[PORT] Sector Financial: selecting V (p=0.580, b=1.021, kelly=0.169) with $4292.16
[PORT] Sector Healthcare: 10 candidates, avg score=0.443
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.001, kelly=0.049) with $1258.92
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.003, kelly=0.255) with $6482.52
[PORT] Sector Services: 10 candidates, avg score=0.537
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.053, kelly=0.373) with $9490.63
[PORT] Sector Technology: 10 candidates, avg score=0.506
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.054, kelly=0.259) with $6604.32
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.899, kelly=0.222) with $5639.91
Raw prediction for AAPL: 0.4852158725261688
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5166109800338745
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4301738142967224
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5546813011169434
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.43807971477508545
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48736894130706787
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.619037926197052
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4516308605670929
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5165426135063171
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5005938410758972
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5065139532089233
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.4849545955657959
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.47797664999961853
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4257919490337372
Calibrated prediction for BP: 0.4346306324005127
Raw prediction for BRK-A: 0.5078508853912354
Calibrated prediction for BRK-A: 0.5142857432365417
Raw prediction for BSAC: 0.46231257915496826
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5759987235069275
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4467123746871948
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.44747522473335266
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4356739819049835
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4603445827960968
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.6061316728591919
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.46894708275794983
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.42499056458473206
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4850612282752991
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.45950353145599365
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5208867788314819
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48311829566955566
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.507497251033783
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.542174756526947
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5065650939941406
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5210223197937012
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5100299119949341
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4075830280780792
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5828973054885864
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.44817987084388733
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.535355269908905
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6020068526268005
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4169798195362091
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4837339222431183
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5184099674224854
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.34662190079689026
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5177772641181946
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4456896185874939
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5273037552833557
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.49534177780151367
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5724852681159973
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47811248898506165
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6580685973167419
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5386195182800293
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4803586006164551
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5550535917282104
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4907788038253784
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5366840362548828
Calibrated prediction for NGG: 0.5720627903938293
Raw prediction for NVS: 0.3966480493545532
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4277459383010864
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.4934643507003784
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6156661510467529
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5010941624641418
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4604058861732483
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4386957585811615
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41539207100868225
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4834430515766144
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5074910521507263
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4714793562889099
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.48324036598205566
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5853103995323181
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.44750216603279114
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4988172650337219
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5231815576553345
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.39948979020118713
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3669545650482178
Calibrated prediction for SPLP: 0.4395604431629181

Simulating Trading Days:  50%|█████     | 50/100 [05:11<01:02,  1.24s/it]

Raw prediction for SRE: 0.3996819853782654
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.4968051016330719
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6448447108268738
Calibrated prediction for TM: 0.704994261264801
Raw prediction for TOT: 0.3882291913032532
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5302731394767761
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4445399343967438
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4994105398654938
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.4677310287952423
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.44490212202072144
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3265339732170105
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5643812417984009
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5251914858818054
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5113393068313599
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.3796464800834656
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49749284982681274
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.965, kelly=0.127) with $3244.86
[PORT] Sector Conglomerates: 7 candidates, avg score=0.516
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.084, kelly=0.370) with $9420.56
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.494
[PORT] Sector Consumer Goods: selecting TM (p=0.705, b=0.991, kelly=0.407) with $10372.54
[PORT] Sector Financial: 10 candidates, avg score=0.491
[PORT] Sector Financial: selecting V (p=0.580, b=1.022, kelly=0.169) with $4306.91
[PORT] Sector Healthcare: 10 candidates, avg score=0.443
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.002, kelly=0.050) with $1273.48
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.003, kelly=0.255) with $6483.48
[PORT] Sector Services: 10 candidates, avg score=0.537
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.373) with $9508.09
[PORT] Sector Technology: 10 candidates, avg score=0.524
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.055, kelly=0.260) with $6611.23
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.899, kelly=0.221) with $5637.71
Raw prediction for AAPL: 0.4850499927997589
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5175316333770752
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.43306252360343933
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5564330816268921
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.43823593854904175
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4871504604816437
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6200742125511169
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.451020210981369
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5166203379631042
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5000666975975037
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5077415704727173
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.4859877824783325
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.48080286383628845
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.41981860995292664
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.5017188191413879
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4622350335121155
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5738352537155151
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.44064638018608093
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.446339875459671
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.43901512026786804
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4574585556983948
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6130641102790833
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.47119271755218506
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4362102746963501
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48436853289604187
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.45924651622772217
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5199429392814636
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48320311307907104
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5070777535438538
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5381781458854675
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.506712794303894
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5210124850273132
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5095572471618652
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.41449791193008423
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.598638653755188
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.4471522271633148
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5357635617256165
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6086564660072327
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4149332642555237
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4838324189186096
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5196859240531921
Calibrated prediction for INTC: 0.5271860361099243
Raw prediction for JNJ: 0.3393566310405731
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5173988342285156
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4462399482727051
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5264505743980408
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.47957539558410645
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5721815824508667
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4780481457710266
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6585664749145508
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5413771867752075
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4734412431716919
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.55040442943573
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.48869791626930237
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5333775281906128
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3902550935745239
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.42777177691459656
Calibrated prediction for ORCL: 0.4000000059604645
Raw prediction for PCG: 0.49274054169654846
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6043136119842529
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5010440945625305
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4509386420249939
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4376890957355499
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41004544496536255
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.47666260600090027
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5067294836044312
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.470090389251709
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4804370701313019
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5733057856559753
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4497792422771454
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49811503291130066
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5231255292892456
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.3997096121311188
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.376146137714386
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.38706520199775696
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5009779930114746
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6584025025367737
Calibrated prediction for TM: 0.704994261264801
Raw prediction for TOT: 0.39466455578804016
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5294328927993774
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.445748507976532
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4968659579753876
Calibrated prediction for UN: 0.4516128897666931

Simulating Trading Days:  51%|█████     | 51/100 [05:12<01:00,  1.24s/it]

Raw prediction for UNH: 0.465509831905365
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.441449910402298
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.33666467666625977
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5692892670631409
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.527398943901062
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.511332094669342
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.3869873285293579
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49784260988235474
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.474
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.963, kelly=0.126) with $3221.76
[PORT] Sector Conglomerates: 7 candidates, avg score=0.516
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.086, kelly=0.371) with $9443.61
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.494
[PORT] Sector Consumer Goods: selecting TM (p=0.705, b=0.991, kelly=0.407) with $10379.07
[PORT] Sector Financial: 10 candidates, avg score=0.481
[PORT] Sector Financial: selecting V (p=0.580, b=1.020, kelly=0.168) with $4291.92
[PORT] Sector Healthcare: 10 candidates, avg score=0.442
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.001, kelly=0.050) with $1262.22
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.005, kelly=0.255) with $6506.51
[PORT] Sector Services: 10 candidates, avg score=0.537
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.373) with $9513.74
[PORT] Sector Technology: 10 candidates, avg score=0.524
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.055, kelly=0.260) with $6616.41
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.901, kelly=0.222) with $5664.80
Raw prediction for AAPL: 0.48503372073173523
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5182802677154541
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.43988025188446045
Calibrated prediction for ABBV: 0.4403476119041443
Raw prediction for AEP: 0.5603384375572205
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.43866997957229614
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4869520366191864
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.617774486541748
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4506163001060486
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5167253613471985
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4996163249015808
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.5053311586380005
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.49349433183670044
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4835086464881897
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.41549161076545715
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4929974377155304
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4624008536338806
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.571938157081604
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4352162182331085
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4457543194293976
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4430205225944519
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.45544004440307617
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6190176606178284
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.47247114777565
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.45117178559303284
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48372751474380493
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4586915969848633
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5195848941802979
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48295119404792786
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5066156983375549
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5338853001594543
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5069968104362488
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209205746650696
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5090811252593994
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4275588393211365
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6042905449867249
Calibrated prediction for GOOG: 0.6242864727973938
Raw prediction for HD: 0.44880053400993347
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5365097522735596
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6148095726966858
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4156251549720764
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.48560214042663574
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5218267440795898
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3342372179031372
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5172203779220581
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4466608166694641
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5256328582763672
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.46376970410346985
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5717989802360535
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4784766137599945
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6585783362388611
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5418145060539246
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4617099165916443
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5445960164070129
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.49237924814224243
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5315988659858704
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.37863874435424805
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4222859740257263
Calibrated prediction for ORCL: 0.39877307415008545
Raw prediction for PCG: 0.49233242869377136
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5883177518844604
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5010029077529907
Calibrated prediction for PEP: 0.5074576139450073
Raw prediction for PFE: 0.4366976022720337
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.43740251660346985
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4074563682079315
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.47569739818573
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5061677694320679
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46913838386535645
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4735432267189026
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5550011992454529
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4564474821090698
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49774229526519775
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5229424238204956
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.40694117546081543
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3868045210838318
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.37708580493927
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5130712985992432
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6581487059593201
Calibrated prediction for TM: 0.704994261264801
Raw prediction for TOT: 0.4078899621963501
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5275528430938721
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4451007843017578
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.49361494183540344
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.4588870704174042
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.44265735149383545
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.36083486676216125
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.572938859462738
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5255671143531799
Calibrated prediction for VZ: 0.556209146976471

Simulating Trading Days:  52%|█████▏    | 52/100 [05:14<00:58,  1.23s/it]

Raw prediction for WFC: 0.5121050477027893
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.39211422204971313
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49798014760017395
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.475
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.962, kelly=0.126) with $3214.27
[PORT] Sector Conglomerates: 7 candidates, avg score=0.516
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.084, kelly=0.370) with $9448.87
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.494
[PORT] Sector Consumer Goods: selecting TM (p=0.705, b=0.991, kelly=0.407) with $10401.55
[PORT] Sector Financial: 10 candidates, avg score=0.482
[PORT] Sector Financial: selecting V (p=0.593, b=1.021, kelly=0.194) with $4946.24
[PORT] Sector Healthcare: 10 candidates, avg score=0.441
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.004, kelly=0.051) with $1293.66
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.006, kelly=0.256) with $6534.83
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.057, kelly=0.374) with $9553.60
[PORT] Sector Technology: 10 candidates, avg score=0.526
[PORT] Sector Technology: selecting GOOG (p=0.624, b=1.056, kelly=0.269) with $6861.15
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.901, kelly=0.222) with $5678.79
Raw prediction for AAPL: 0.4852132797241211
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5186928510665894
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.44943860173225403
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.561368465423584
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4389122724533081
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4866371154785156
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6189891695976257
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45054325461387634
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5168431401252747
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4993817210197449
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4988991618156433
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5035635828971863
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.48547422885894775
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.413420170545578
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.48215213418006897
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4626471996307373
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5708057880401611
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.43009114265441895
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.445826917886734
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4497266411781311
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4639144539833069
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.624255895614624
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.47520896792411804
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4666394293308258
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4830266535282135
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.455471009016037
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5185953378677368
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4823509752750397
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.505992591381073
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5332412719726562
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5072108507156372
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5208156108856201
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5087487101554871
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4431832432746887
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6135109663009644
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.4552046060562134
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5376109480857849
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6196418404579163
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4179386794567108
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4867091178894043
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5239592790603638
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3303409814834595
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5172638297080994
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4471047520637512
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5236765146255493
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.44914087653160095
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5712907314300537
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47885221242904663
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6578111052513123
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.537407636642456
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.45055335760116577
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5361744165420532
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.49576327204704285
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5310364365577698
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3644935190677643
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.4073683023452759
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.491747111082077
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5707281231880188
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5008578896522522
Calibrated prediction for PEP: 0.5029199719429016
Raw prediction for PFE: 0.41974806785583496
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4376634955406189
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4047987461090088
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4802696108818054
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5051120519638062
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46827608346939087
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.46546471118927
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5393879413604736
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.46939337253570557
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49803057312965393
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5225619077682495
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.41719499230384827
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3919173777103424
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.36908623576164246
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5357043147087097
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6439482569694519
Calibrated prediction for TM: 0.704994261264801

Simulating Trading Days:  53%|█████▎    | 53/100 [05:15<00:56,  1.21s/it]

Raw prediction for TOT: 0.4227048456668854
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5278015732765198
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4436558783054352
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.49129733443260193
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.44807684421539307
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.45126011967658997
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3889446556568146
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.576910674571991
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5203557014465332
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5136573910713196
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.3972853422164917
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49804654717445374
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.480
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.960, kelly=0.125) with $3192.85
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.946, kelly=0.224) with $5719.32
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.494
[PORT] Sector Consumer Goods: selecting TM (p=0.705, b=0.993, kelly=0.408) with $10400.22
[PORT] Sector Financial: 10 candidates, avg score=0.475
[PORT] Sector Financial: selecting V (p=0.593, b=1.023, kelly=0.194) with $4959.49
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.005, kelly=0.051) with $1305.30
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.005, kelly=0.255) with $6514.32
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.374) with $9526.02
[PORT] Sector Technology: 10 candidates, avg score=0.525
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.056, kelly=0.292) with $7448.57
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.902, kelly=0.223) with $5688.23
Raw prediction for AAPL: 0.4856783449649811
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5190219283103943
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4574604034423828
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5625233054161072
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4388008117675781
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48606330156326294
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6142773032188416
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4504823386669159
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5168740153312683
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49941930174827576
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4921019375324249
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5134525299072266
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4841807186603546
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4182239770889282
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4717811346054077
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4629407227039337
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5704396963119507
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42669540643692017
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4459848701953888
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4559061825275421
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4549962878227234
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.632361888885498
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4783024489879608
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4745441973209381
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48268923163414
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.45389217138290405
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5189660787582397
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48163101077079773
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5055645108222961
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5375974774360657
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5073659420013428
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.520679771900177
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5087593793869019
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.45271632075309753
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6063565015792847
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.46584081649780273
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5383703708648682
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6257959604263306
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.41965192556381226
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4865574240684509
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.525461733341217
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.32718756794929504
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5175671577453613
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4478943645954132
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5216684937477112
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.43770694732666016
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5709336400032043
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47887709736824036
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6565678119659424
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5302221775054932
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.45021164417266846
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.531660258769989
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.49610984325408936
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5298904180526733
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.353589802980423
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3838352859020233
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49171674251556396
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5646180510520935
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5006921887397766
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.41113701462745667
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.43780139088630676
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4046669006347656
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.48639750480651855
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5040609836578369
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4680770933628082
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4663138687610626
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5294302105903625
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.48385089635849
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4986380636692047
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5221072435379028
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.4321635961532593
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.39280965924263
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.3635765314102173
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5528944730758667
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6273126602172852
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.4313058853149414
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5264768004417419
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4419463276863098
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4888390898704529
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.439218133687973
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4622764587402344
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4043392837047577
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5773884654045105
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5142531394958496
Calibrated prediction for VZ: 0.52173912525177

Simulating Trading Days:  54%|█████▍    | 54/100 [05:16<00:54,  1.19s/it]

Raw prediction for WFC: 0.5158177614212036
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4025908410549164
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.498341828584671
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.475
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.962, kelly=0.126) with $3200.68
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.947, kelly=0.229) with $5812.79
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.480
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.994, kelly=0.149) with $3786.42
[PORT] Sector Financial: 10 candidates, avg score=0.470
[PORT] Sector Financial: selecting V (p=0.593, b=1.025, kelly=0.195) with $4952.50
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.004, kelly=0.051) with $1285.01
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.007, kelly=0.256) with $6505.08
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.056, kelly=0.374) with $9487.32
[PORT] Sector Technology: 10 candidates, avg score=0.523
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.055, kelly=0.292) with $7405.36
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.902, kelly=0.223) with $5652.93
Raw prediction for AAPL: 0.4860672056674957
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5189816355705261
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4638987183570862
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5646440386772156
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.438190758228302
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48556986451148987
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6144164204597473
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4506823718547821
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5169116258621216
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5001175403594971
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.48447784781455994
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5179879069328308
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.48115167021751404
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.42466214299201965
Calibrated prediction for BP: 0.42327070236206055
Raw prediction for BRK-A: 0.46313536167144775
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4631485641002655
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5702292919158936
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42295604944229126
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.44645020365715027
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4601215124130249
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.44644737243652344
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6367303729057312
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.47911155223846436
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4745387136936188
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48258650302886963
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.45265868306159973
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.519894540309906
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48101505637168884
Calibrated prediction for DHR: 0.47826087474823
Raw prediction for DIS: 0.5054633617401123
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5462570786476135
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5070269107818604
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5206769704818726
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5087540745735168
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4526976943016052
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6079115271568298
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.4740332067012787
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5387328267097473
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6294049024581909
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4212183952331543
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.48716312646865845
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.527988612651825
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.32368555665016174
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5179677605628967
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44765982031822205
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5202125310897827
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4249717891216278
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5706852674484253
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4787452518939972
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6554672122001648
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5229917168617249
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.45367899537086487
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5296435952186584
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4882945716381073
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5287891030311584
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.34796425700187683
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.37010762095451355
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49156835675239563
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5598554015159607
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5005655288696289
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4088621735572815
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4369216859340668
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4054803252220154
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.49318572878837585
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.5033938884735107
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4677085876464844
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.47330260276794434
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5220324397087097
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.49496713280677795
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.4989233613014221
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5215463638305664
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.44199058413505554
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3861600160598755
Calibrated prediction for SPLP: 0.4395604431629181

Simulating Trading Days:  55%|█████▌    | 55/100 [05:17<00:53,  1.20s/it]

Raw prediction for SRE: 0.36098596453666687
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5618982911109924
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5887516140937805
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.43213334679603577
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.529455840587616
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.43909528851509094
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4872957468032837
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.433104544878006
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4730173945426941
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.43025264143943787
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.57614666223526
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.508582353591919
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5181540250778198
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4117404818534851
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.49875035881996155
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.475
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.962, kelly=0.076) with $1927.88
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.945, kelly=0.228) with $5804.48
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.480
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.996, kelly=0.150) with $3809.13
[PORT] Sector Financial: 10 candidates, avg score=0.476
[PORT] Sector Financial: selecting V (p=0.593, b=1.027, kelly=0.196) with $4979.96
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting SNY (p=0.524, b=1.005, kelly=0.051) with $1300.20
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.005, kelly=0.255) with $6495.89
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.373) with $9499.69
[PORT] Sector Technology: 10 candidates, avg score=0.521
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.050, kelly=0.290) with $7383.58
[PORT] Sector Utilities: 10 candidates, avg score=0.506
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.900, kelly=0.222) with $5643.19
Raw prediction for AAPL: 0.48642265796661377
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.518697202205658
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4698912799358368
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5692235231399536
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.43750104308128357
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4852021336555481
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6209640502929688
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4513559341430664
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5169010758399963
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5010321736335754
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.48879894614219666
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5209903717041016
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.48113444447517395
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4260045886039734
Calibrated prediction for BP: 0.43676865100860596
Raw prediction for BRK-A: 0.4566449522972107
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4632876515388489
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.570981502532959
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42213067412376404
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4474520981311798
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.46259167790412903
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.44777771830558777
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6421642303466797
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.47929996252059937
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4657396376132965
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48276934027671814
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.46519437432289124
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5204879641532898
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4806860387325287
Calibrated prediction for DHR: 0.47826087474823
Raw prediction for DIS: 0.505728542804718
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5533373355865479
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5067874789237976
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5208589434623718
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5089276432991028
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.45121681690216064
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6288954615592957
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.4806780219078064
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5391658544540405
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6313245892524719
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4218885004520416
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4876773953437805
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5313712358474731
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.32392460107803345
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5182710886001587
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44747596979141235
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5196547508239746
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.41856932640075684
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5707234740257263
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4789678156375885
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6541886329650879
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5171154141426086
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4559897482395172
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5280073881149292
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4881744384765625
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5275136232376099
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.34869855642318726
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3661661744117737
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4919905364513397
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5632792711257935
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5004960894584656
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4126478433609009
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.43694016337394714
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.40728873014450073
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.49946799874305725
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.5022480487823486
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4676379859447479
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4790721535682678
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5206500291824341
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5030631422996521
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49921920895576477
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5210509300231934
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.45437610149383545
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3764665424823761
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.35288020968437195
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5641238689422607
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5531315803527832
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.42724400758743286
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5357210040092468
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.4358299970626831
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4845603406429291
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.43102139234542847
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4818698465824127
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4637543857097626
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5735443234443665
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5060454607009888
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5201537013053894
Calibrated prediction for WFC: 0.5161290168762207

Simulating Trading Days:  56%|█████▌    | 56/100 [05:18<00:51,  1.18s/it]

Raw prediction for WMT: 0.42025190591812134
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.4998427629470825
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.964, kelly=0.127) with $3211.74
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.944, kelly=0.228) with $5772.74
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.474
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.980, kelly=0.138) with $3505.33
[PORT] Sector Financial: 10 candidates, avg score=0.476
[PORT] Sector Financial: selecting V (p=0.593, b=1.028, kelly=0.196) with $4969.19
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.005, kelly=0.043) with $1081.60
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.488
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.004, kelly=0.255) with $6457.86
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.373) with $9458.31
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.051, kelly=0.291) with $7358.57
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.900, kelly=0.222) with $5620.23
Raw prediction for AAPL: 0.48683780431747437
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5182708501815796
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4726097881793976
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5740352869033813
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4375857412815094
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48501017689704895
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6218222975730896
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4521137475967407
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5169335007667542
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5017536878585815
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.497568815946579
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5233749151229858
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4795391857624054
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.41577574610710144
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4542466402053833
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46334412693977356
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5680481791496277
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42443302273750305
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.44824570417404175
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.46297433972358704
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4456670880317688
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6412370800971985
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4754759967327118
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4560851454734802
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4825435280799866
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.47899267077445984
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5198805928230286
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4806600511074066
Calibrated prediction for DHR: 0.47826087474823
Raw prediction for DIS: 0.5065012574195862
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5586435198783875
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5067376494407654
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5208491086959839
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.509367823600769
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.45016855001449585
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6346409916877747
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.4829398989677429
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5388668775558472
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6331557035446167
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4220176637172699
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.48826706409454346
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.533751904964447
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.32477983832359314
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5182463526725769
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44710561633110046
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5205817818641663
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4135805368423462
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5705480575561523
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4795089364051819
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6534214615821838
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5130102038383484
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.45952677726745605
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5261154174804688
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4923824667930603
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5253311991691589
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3470574617385864
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3570639193058014
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49238121509552
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5625335574150085
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5004470944404602
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.41575393080711365
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4368214011192322
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4113211929798126
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5035849809646606
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.500781774520874
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4665165841579437
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4780087471008301
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5250590443611145
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5107269287109375
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.49952206015586853
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5205549001693726
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.46572256088256836
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.36614271998405457
Calibrated prediction for SPLP: 0.4395604431629181
Raw prediction for SRE: 0.3414844274520874
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5603922605514526
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5119398236274719
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.4178827404975891
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5370051264762878
Calibrated prediction for TSM: 0.5770066976547241

Simulating Trading Days:  57%|█████▋    | 57/100 [05:19<00:50,  1.17s/it]

Raw prediction for UL: 0.42102745175361633
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.46847933530807495
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.42947259545326233
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.48626071214675903
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4846447706222534
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.565716564655304
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.506574273109436
Calibrated prediction for VZ: 0.4943828284740448
Raw prediction for WFC: 0.5207600593566895
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.42690086364746094
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5011720061302185
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.475
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.962, kelly=0.126) with $3187.84
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.945, kelly=0.228) with $5768.78
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.474
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.975, kelly=0.137) with $3453.39
[PORT] Sector Financial: 10 candidates, avg score=0.474
[PORT] Sector Financial: selecting V (p=0.580, b=1.025, kelly=0.170) with $4304.88
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.002, kelly=0.041) with $1045.42
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.511
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.001, kelly=0.254) with $6426.04
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.054, kelly=0.373) with $9441.17
[PORT] Sector Technology: 10 candidates, avg score=0.520
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.047, kelly=0.289) with $7315.23
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.900, kelly=0.222) with $5615.90
Raw prediction for AAPL: 0.4875105619430542
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.518520712852478
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.47098132967948914
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5802227854728699
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4377792179584503
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48482546210289
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6295957565307617
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4534928798675537
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5169097781181335
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5020397901535034
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4969593286514282
Calibrated prediction for BBL: 0.5714285969734192
Raw prediction for BCH: 0.5286692976951599
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4734497368335724
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.40720829367637634
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.4556194245815277
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.463833749294281
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5713835954666138
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4347303807735443
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.44952279329299927
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.46324029564857483
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4563569724559784
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6405770182609558
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.47396141290664673
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4454825818538666
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4831714332103729
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4891706705093384
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5174160003662109
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48091697692871094
Calibrated prediction for DHR: 0.47826087474823
Raw prediction for DIS: 0.5072429180145264
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5638224482536316
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5069370865821838
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209879875183105
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5097610950469971
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.44758057594299316
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6559246182441711
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.48302844166755676
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5393593907356262
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6309806108474731
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.4214101731777191
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.48964935541152954
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.537179708480835
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.32459917664527893
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5177908539772034
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44777795672416687
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5213626623153687
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.42299583554267883
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5710157155990601
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48027604818344116
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6517474055290222
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5103026628494263
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.46953678131103516
Calibrated prediction for MRK: 0.4761904776096344
Raw prediction for MSFT: 0.5250645875930786
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5001456141471863
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5242806077003479
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3466323912143707
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3571159541606903
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49284064769744873
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5703823566436768
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5004379749298096
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.42310240864753723
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.43896597623825073
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41154128313064575
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5094261765480042
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.4998047649860382
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4655103385448456
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.47369325160980225
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5344790816307068
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5182896852493286
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.49981772899627686
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.520308256149292
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4788041114807129
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3553790748119354
Calibrated prediction for SPLP: 0.3333333432674408
Raw prediction for SRE: 0.3347600996494293
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5562779903411865
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.48964112997055054
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.4181636571884155
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5417847633361816
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.41023799777030945
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4604514241218567
Calibrated prediction for UN: 0.3995307683944702
Raw prediction for UNH: 0.4298287332057953
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.49467360973358154
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5105064511299133
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5648224353790283
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5063640475273132
Calibrated prediction for VZ: 0.46595844626426697

Simulating Trading Days:  58%|█████▊    | 58/100 [05:21<00:48,  1.16s/it]

Raw prediction for WFC: 0.5201685428619385
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4334094226360321
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.501611053943634
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.486
[PORT] Sector Basic Matierials: selecting BBL (p=0.571, b=0.964, kelly=0.127) with $3201.09
[PORT] Sector Conglomerates: 7 candidates, avg score=0.472
[PORT] Sector Conglomerates: selecting HRG (p=0.625, b=0.944, kelly=0.228) with $5750.46
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.461
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.974, kelly=0.136) with $3425.87
[PORT] Sector Financial: 10 candidates, avg score=0.481
[PORT] Sector Financial: selecting V (p=0.580, b=1.025, kelly=0.170) with $4302.59
[PORT] Sector Healthcare: 10 candidates, avg score=0.438
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.003, kelly=0.042) with $1057.96
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.511
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.000, kelly=0.253) with $6397.11
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.373) with $9428.29
[PORT] Sector Technology: 10 candidates, avg score=0.526
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.047, kelly=0.461) with $11631.26
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.902, kelly=0.223) with $5626.23
Raw prediction for AAPL: 0.4883076548576355
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5185836553573608
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.46891868114471436
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.584960401058197
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4381631910800934
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48463112115859985
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6415292024612427
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45477911829948425
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5168665051460266
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5018373727798462
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4874965250492096
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5253027677536011
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.4641191363334656
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4071478843688965
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.45604339241981506
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46391820907592773
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.573711633682251
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4378659129142761
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45029908418655396
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.464125394821167
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4571439027786255
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6367970705032349
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4698849618434906
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4357259273529053
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4842860996723175
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.49595755338668823
Calibrated prediction for CVX: 0.4615384638309479
Raw prediction for D: 0.514131486415863
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4811549782752991
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5078491568565369
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5697353482246399
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5070744752883911
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209900736808777
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5102607011795044
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.44301268458366394
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6779940724372864
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4795594811439514
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5391867756843567
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6271151304244995
Calibrated prediction for HRG: 0.625
Raw prediction for HSBC: 0.42351922392845154
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4907006323337555
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5406230092048645
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3239026963710785
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5170292258262634
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4489055275917053
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5220373868942261
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4208082854747772
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5712693929672241
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.481003999710083
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.650188148021698
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5082767605781555
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.47916677594184875
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5225539207458496
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.5069690942764282
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5234556794166565
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3474405109882355
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.35765746235847473
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4924594759941101
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.575177013874054
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5003170371055603
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.43222010135650635
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4399551749229431
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.41225916147232056
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5137019157409668
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.4987507164478302
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4639672636985779
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4710579812526703
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5430026054382324
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.522232174873352
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.500121533870697
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5202724933624268
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4902542531490326
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3441450893878937
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3305821120738983
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5515177249908447
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.46041184663772583
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.4267808496952057
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.543225109577179
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.39544677734375
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4509633779525757
Calibrated prediction for UN: 0.35549506545066833

Simulating Trading Days:  59%|█████▉    | 59/100 [05:22<00:46,  1.15s/it]

Raw prediction for UNH: 0.43021491169929504
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5029913187026978
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5232733488082886
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5642278790473938
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5055304169654846
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5185775756835938
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4394772946834564
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5015906095504761
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.483
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.964, kelly=0.077) with $1945.90
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.088, kelly=0.371) with $9397.34
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.452
[PORT] Sector Consumer Goods: selecting PM (p=0.561, b=1.026, kelly=0.133) with $3374.16
[PORT] Sector Financial: 10 candidates, avg score=0.481
[PORT] Sector Financial: selecting V (p=0.580, b=1.027, kelly=0.171) with $4329.53
[PORT] Sector Healthcare: 10 candidates, avg score=0.441
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.005, kelly=0.043) with $1084.08
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.000, kelly=0.254) with $6421.15
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.054, kelly=0.373) with $9454.15
[PORT] Sector Technology: 10 candidates, avg score=0.523
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.047, kelly=0.461) with $11666.47
[PORT] Sector Utilities: 10 candidates, avg score=0.511
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.903, kelly=0.223) with $5651.06
Raw prediction for AAPL: 0.4890340268611908
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5186899900436401
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4646967351436615
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5885082483291626
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4385773837566376
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48444628715515137
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6583921909332275
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4558334946632385
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5167462229728699
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5012689828872681
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.46672889590263367
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5214853882789612
Calibrated prediction for BCH: 0.49253731966018677
Raw prediction for BHP: 0.45734643936157227
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4047694504261017
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.45852547883987427
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4637109041213989
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5780102014541626
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4408899247646332
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4506363272666931
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4683725833892822
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4522221088409424
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6391147971153259
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.46710729598999023
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.42552468180656433
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4853529930114746
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.49615156650543213
Calibrated prediction for CVX: 0.4615384638309479
Raw prediction for D: 0.5105391144752502
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4814736843109131
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5083901882171631
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5739364624023438
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5071950554847717
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5210446715354919
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5105136036872864
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.43592551350593567
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7048184275627136
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4743659496307373
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5388633608818054
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6214434504508972
Calibrated prediction for HRG: 0.6239194273948669
Raw prediction for HSBC: 0.42274293303489685
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.49172717332839966
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.543458878993988
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.32149890065193176
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5159429311752319
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4504348337650299
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5228493213653564
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.422025591135025
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5718450546264648
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48166394233703613
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6493492722511292
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5058935284614563
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.48385435342788696
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5188855528831482
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5154613852500916
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5217530131340027
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.35155174136161804
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3607310950756073
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49141502380371094
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.58287513256073
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5002313256263733
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.43877607583999634
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4401717185974121
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.41401246190071106
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5182676315307617
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.49739569425582886
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4621797502040863
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47108766436576843
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5531550645828247
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.518024206161499
Calibrated prediction for SLB: 0.45269179344177246
Raw prediction for SNP: 0.5004470348358154
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5205035209655762
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.501834511756897
Calibrated prediction for SO: 0.5512372255325317

Simulating Trading Days:  60%|██████    | 60/100 [05:23<00:45,  1.14s/it]

Raw prediction for SPLP: 0.33616238832473755
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.32799744606018066
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5447096228599548
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.42624303698539734
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.42728549242019653
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5428376197814941
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.38949957489967346
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.45192253589630127
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.42929720878601074
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5135399103164673
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5329118371009827
Calibrated prediction for UTX: 0.5842176675796509
Raw prediction for V: 0.5666564106941223
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5038152933120728
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5159251689910889
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4441947042942047
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5019650459289551
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.475
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.962, kelly=0.076) with $1925.86
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.088, kelly=0.371) with $9399.20
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.452
[PORT] Sector Consumer Goods: selecting PM (p=0.561, b=1.028, kelly=0.134) with $3396.05
[PORT] Sector Financial: 10 candidates, avg score=0.479
[PORT] Sector Financial: selecting V (p=0.580, b=1.026, kelly=0.171) with $4324.46
[PORT] Sector Healthcare: 10 candidates, avg score=0.441
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.003, kelly=0.042) with $1056.77
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.003, kelly=0.254) with $6445.16
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.374) with $9462.97
[PORT] Sector Technology: 10 candidates, avg score=0.519
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.048, kelly=0.461) with $11674.29
[PORT] Sector Utilities: 10 candidates, avg score=0.524
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.904, kelly=0.224) with $5670.95
Raw prediction for AAPL: 0.48968765139579773
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5186517834663391
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.46061304211616516
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5930195450782776
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4395867586135864
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48427578806877136
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6580623984336853
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4562804400920868
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5166847109794617
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5006844401359558
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.45176956057548523
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5133724808692932
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.45182937383651733
Calibrated prediction for BHP: 0.4890578091144562
Raw prediction for BP: 0.4191786050796509
Calibrated prediction for BP: 0.39187318086624146
Raw prediction for BRK-A: 0.46189478039741516
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46317556500434875
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5821990370750427
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4414621889591217
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.45020031929016113
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.47846630215644836
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.44978654384613037
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6392725110054016
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4649113714694977
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.43360435962677
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48632192611694336
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5008202195167542
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.5069193840026855
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48193883895874023
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5087577104568481
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5762534737586975
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.507331371307373
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5210088491439819
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5106685757637024
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4270860552787781
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7134228944778442
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.47021281719207764
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.538387656211853
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6162849068641663
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.42224565148353577
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.49276480078697205
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.545075535774231
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.322846919298172
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.5148909091949463
Calibrated prediction for JPM: 0.5134379863739014
Raw prediction for KO: 0.4523483216762543
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.524076521396637
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4261513948440552
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5720633268356323
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4821476936340332
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6491300463676453
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.504510223865509
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.4827006757259369
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5121455192565918
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5219271779060364
Calibrated prediction for NEE: 0.5714285969734192
Raw prediction for NGG: 0.5213528275489807
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3548678457736969
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.35662826895713806
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4907976984977722
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5850749611854553
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5002710223197937
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4453463554382324
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.4400947391986847
Calibrated prediction for PG: 0.4615384638309479
Raw prediction for PICO: 0.41814127564430237
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5173817873001099
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.4962722659111023
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4604867398738861
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47534117102622986
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5624058842658997
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5080826878547668
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5005889534950256
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.520969808101654
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.512791097164154
Calibrated prediction for SO: 0.5512372255325317

Simulating Trading Days:  61%|██████    | 61/100 [05:24<00:43,  1.13s/it]

Raw prediction for SPLP: 0.328633189201355
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3282912075519562
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5371862649917603
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.38541361689567566
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4459024667739868
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5440790057182312
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.38936135172843933
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.45910701155662537
Calibrated prediction for UN: 0.38732850551605225
Raw prediction for UNH: 0.4251294732093811
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5177600979804993
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5287296175956726
Calibrated prediction for UTX: 0.5842176675796509
Raw prediction for V: 0.571258544921875
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5084832310676575
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5134167671203613
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4454711377620697
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5023623704910278
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.488
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.962, kelly=0.076) with $1933.60
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.087, kelly=0.371) with $9428.85
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.450
[PORT] Sector Consumer Goods: selecting PM (p=0.561, b=1.030, kelly=0.135) with $3429.68
[PORT] Sector Financial: 10 candidates, avg score=0.476
[PORT] Sector Financial: selecting V (p=0.593, b=1.026, kelly=0.196) with $4974.76
[PORT] Sector Healthcare: 10 candidates, avg score=0.441
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.002, kelly=0.041) with $1054.21
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.002, kelly=0.254) with $6463.10
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.057, kelly=0.374) with $9506.57
[PORT] Sector Technology: 10 candidates, avg score=0.526
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.049, kelly=0.461) with $11723.66
[PORT] Sector Utilities: 10 candidates, avg score=0.534
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.903, kelly=0.223) with $5677.26
Raw prediction for AAPL: 0.49027425050735474
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5191949605941772
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4568077325820923
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5964884757995605
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.44116830825805664
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48408442735671997
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6614192128181458
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4564300775527954
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.516656756401062
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4999719262123108
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4374139904975891
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.5008721351623535
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4463062584400177
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.43489354848861694
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4628610610961914
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4629722535610199
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5860839486122131
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.43922486901283264
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.44959020614624023
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.49721986055374146
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4569990634918213
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.639905571937561
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.463325172662735
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.460319459438324
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4882636070251465
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.504515528678894
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.5030226707458496
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4827331304550171
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5086104273796082
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5785200595855713
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5074425935745239
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5210326910018921
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5104953646659851
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4247623682022095
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7202972173690796
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.46782517433166504
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5383394956588745
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6125862002372742
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.421919047832489
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4946506917476654
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5470007061958313
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.327822744846344
Calibrated prediction for JNJ: 0.3072104752063751
Raw prediction for JPM: 0.514078676700592
Calibrated prediction for JPM: 0.5134379863739014
Raw prediction for KO: 0.4538804292678833
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5253026485443115
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4247046411037445
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5725783109664917
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48230746388435364
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6475317478179932
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5038016438484192
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.48575377464294434
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5080729126930237
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5255895853042603
Calibrated prediction for NEE: 0.5714285969734192
Raw prediction for NGG: 0.5213462114334106
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3626413643360138
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.35825487971305847
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4904807507991791
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5847631096839905
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.500150740146637
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4568580389022827
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.43979161977767944
Calibrated prediction for PG: 0.4544054865837097
Raw prediction for PICO: 0.4218916594982147
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.5134091377258301
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.49533697962760925
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4588039815425873
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4798274338245392
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5724093317985535
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.49712201952934265
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5011968612670898
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5215769410133362
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.5202134847640991
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.3219904899597168
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3307841420173645
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5290012955665588
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.34732410311698914
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.46270284056663513
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5480808019638062
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3954773545265198
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.47015053033828735
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.42324715852737427
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5206940174102783
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.529261589050293
Calibrated prediction for UTX: 0.5842176675796509
Raw prediction for V: 0.5784432291984558
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5130439400672913
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5114210247993469
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.44790640473365784
Calibrated prediction for WMT: 0.4189581871032715

Simulating Trading Days:  62%|██████▏   | 62/100 [05:25<00:42,  1.13s/it]

Raw prediction for XOM: 0.5026688575744629
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.493
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.961, kelly=0.075) with $1918.36
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.086, kelly=0.371) with $9439.39
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.456
[PORT] Sector Consumer Goods: selecting PM (p=0.561, b=1.032, kelly=0.135) with $3450.10
[PORT] Sector Financial: 10 candidates, avg score=0.476
[PORT] Sector Financial: selecting V (p=0.593, b=1.026, kelly=0.196) with $4980.57
[PORT] Sector Healthcare: 10 candidates, avg score=0.450
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.026, kelly=0.078) with $1997.38
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.516
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.002, kelly=0.254) with $6479.40
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.057, kelly=0.374) with $9529.20
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.050, kelly=0.461) with $11753.88
[PORT] Sector Utilities: 10 candidates, avg score=0.534
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.902, kelly=0.223) with $5672.44
Raw prediction for AAPL: 0.4906425476074219
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5197165608406067
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.45096608996391296
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5981429815292358
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.44259586930274963
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4840027689933777
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6517888307571411
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4560757279396057
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5166534185409546
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4990692734718323
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4208592176437378
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.48269975185394287
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4398462176322937
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.450488805770874
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4638999402523041
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4628271162509918
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5863136053085327
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4322817921638489
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4486614465713501
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5116403102874756
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4549330174922943
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6396015286445618
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.45984265208244324
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4781932830810547
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48971304297447205
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5047248601913452
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.500782310962677
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48326757550239563
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5079421997070312
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5821442008018494
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5075812935829163
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209652185440063
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5105365514755249
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.42143329977989197
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7082158923149109
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4678305983543396
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5381237268447876
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6090465188026428
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4209064245223999
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5001159906387329
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5486944317817688
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3319511413574219
Calibrated prediction for JNJ: 0.3538207411766052
Raw prediction for JPM: 0.5134221315383911
Calibrated prediction for JPM: 0.5134379863739014
Raw prediction for KO: 0.45521706342697144
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5259569883346558
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4150739014148712
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5726692080497742
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.482285737991333
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6460448503494263
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5037266612052917
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.49002909660339355
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5025849938392639
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5247815847396851
Calibrated prediction for NEE: 0.5714285969734192
Raw prediction for NGG: 0.520505428314209
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3663826882839203
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3544468879699707
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4897659420967102
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5793502330780029
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5000657439231873
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.46652641892433167
Calibrated prediction for PFE: 0.3810107707977295
Raw prediction for PG: 0.43879660964012146
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.422278493642807
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.505493700504303
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.4941573739051819
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45684006810188293
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.483351469039917
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5834710001945496
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.49020639061927795
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5019029378890991
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5220628976821899
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.5258328914642334
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.3150533139705658
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3330613672733307
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5268276929855347
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.31319546699523926
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4808219373226166
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5469986200332642
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3999865651130676
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.47626057267189026
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.42209821939468384
Calibrated prediction for UNH: 0.41128528118133545

Simulating Trading Days:  63%|██████▎   | 63/100 [05:26<00:41,  1.13s/it]

Raw prediction for UPS: 0.5200490355491638
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5225100517272949
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5804933905601501
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5161949396133423
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5093986392021179
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4510391354560852
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5023496150970459
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting TOT (p=0.545, b=0.988, kelly=0.085) with $2177.47
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.087, kelly=0.371) with $9447.10
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.454
[PORT] Sector Consumer Goods: selecting PM (p=0.561, b=1.030, kelly=0.135) with $3432.13
[PORT] Sector Financial: 10 candidates, avg score=0.476
[PORT] Sector Financial: selecting V (p=0.593, b=1.027, kelly=0.196) with $4987.59
[PORT] Sector Healthcare: 10 candidates, avg score=0.455
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.027, kelly=0.079) with $2015.95
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.001, kelly=0.254) with $6470.49
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.058, kelly=0.374) with $9534.68
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.050, kelly=0.461) with $11753.30
[PORT] Sector Utilities: 10 candidates, avg score=0.534
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.903, kelly=0.223) with $5687.24
Raw prediction for AAPL: 0.49090367555618286
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5202097296714783
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4444340765476227
Calibrated prediction for ABBV: 0.46666666865348816
Raw prediction for AEP: 0.5985898375511169
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.443824827671051
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4840944707393646
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6302425861358643
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4555223882198334
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5166431665420532
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4981010854244232
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.405790239572525
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.46676281094551086
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4343651235103607
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.4632754325866699
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.46342429518699646
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.462782621383667
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5848363637924194
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42604517936706543
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4477390646934509
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5257725715637207
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.45720455050468445
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6369478106498718
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.45417988300323486
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4730551838874817
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4903436005115509
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5032694339752197
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.5010284185409546
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4837741553783417
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5070108771324158
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5847568511962891
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5076446533203125
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209012031555176
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5103533267974854
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4172378480434418
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6875768303871155
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.46926817297935486
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5378994345664978
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6058328151702881
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.419637531042099
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5042269229888916
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5489369630813599
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.33653897047042847
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5130828619003296
Calibrated prediction for JPM: 0.5134379863739014
Raw prediction for KO: 0.45629990100860596
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5258178114891052
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.40978091955184937
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.572779655456543
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4822014570236206
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6452099680900574
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5037456154823303
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.4942902624607086
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.49714112281799316
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.5202436447143555
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5200852155685425
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3699246644973755
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.34724411368370056
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4893253445625305
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5695698857307434
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.50003582239151
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4766346514225006
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.43840450048446655
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4206434488296509
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.49704697728157043
Calibrated prediction for PM: 0.5609756112098694
Raw prediction for PPL: 0.49334806203842163
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4549320340156555
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4829583466053009
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5915557742118835
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4858098030090332
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5025590062141418
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5223997831344604
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.5305269956588745
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.30824947357177734
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.333909809589386
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5356423854827881
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.29514238238334656
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.481172651052475
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5456144213676453
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.40533557534217834
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.48038148880004883
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.4285898804664612
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5194283723831177
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5133366584777832
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5808145403862
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5189266204833984
Calibrated prediction for VZ: 0.52173912525177

Simulating Trading Days:  64%|██████▍   | 64/100 [05:27<00:41,  1.14s/it]

Raw prediction for WFC: 0.5081884264945984
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.45382159948349
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5021165609359741
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting TOT (p=0.545, b=0.987, kelly=0.085) with $2170.62
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.090, kelly=0.372) with $9481.56
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.454
[PORT] Sector Consumer Goods: selecting PM (p=0.561, b=1.030, kelly=0.135) with $3435.30
[PORT] Sector Financial: 10 candidates, avg score=0.469
[PORT] Sector Financial: selecting V (p=0.593, b=1.025, kelly=0.195) with $4982.20
[PORT] Sector Healthcare: 10 candidates, avg score=0.462
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.026, kelly=0.078) with $1997.59
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.003, kelly=0.254) with $6492.49
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.060, kelly=0.375) with $9567.90
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.048, kelly=0.461) with $11761.26
[PORT] Sector Utilities: 10 candidates, avg score=0.524
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.905, kelly=0.224) with $5722.76
Raw prediction for AAPL: 0.4912441074848175
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5207870602607727
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4375033974647522
Calibrated prediction for ABBV: 0.4285714328289032
Raw prediction for AEP: 0.5986423492431641
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.44482067227363586
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48453986644744873
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6063910126686096
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45471274852752686
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5167117118835449
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4972127676010132
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.39208701252937317
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.4579460322856903
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4304673373699188
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.47562265396118164
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4629160761833191
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4626905918121338
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5828584432601929
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4200550317764282
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4469034671783447
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5393208861351013
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.46019473671913147
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.6304190754890442
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.44670751690864563
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.455606073141098
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4902917742729187
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5022792816162109
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.49993622303009033
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.484180212020874
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5060968995094299
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.586060643196106
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5076940059661865
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5209084153175354
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5101961493492126
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4107673168182373
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6619522571563721
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4721861481666565
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5376996994018555
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.6021814346313477
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4186749756336212
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5073046088218689
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5485687255859375
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3410888910293579
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5131752490997314
Calibrated prediction for JPM: 0.5134379863739014
Raw prediction for KO: 0.4575158357620239
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5253263115882874
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.40282049775123596
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5725588798522949
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4820701777935028
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6448729634284973
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5041412115097046
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.4989300072193146
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.49167853593826294
Calibrated prediction for MSFT: 0.47058823704719543
Raw prediction for NEE: 0.5163896679878235
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5196806192398071
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.37366774678230286
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.34044939279556274
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.48900631070137024
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5595425963401794
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.4999791383743286
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4853183925151825
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4384334981441498
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41949835419654846
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4894232153892517
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.49251851439476013
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45326244831085205
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4785800278186798
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5954400897026062
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.48189684748649597
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5024691820144653
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5225627422332764
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.5339824557304382
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.301672101020813
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.33214372396469116
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5470387935638428
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.28169840574264526
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.47567540407180786
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5441282987594604
Calibrated prediction for TSM: 0.5770066976547241

Simulating Trading Days:  65%|██████▌   | 65/100 [05:28<00:40,  1.15s/it]

Raw prediction for UL: 0.4044240415096283
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4797384738922119
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.43840765953063965
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5180111527442932
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4986528754234314
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5764200687408447
Calibrated prediction for V: 0.5925925970077515
Raw prediction for VZ: 0.5212641954421997
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.507512629032135
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4554273784160614
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5016300082206726
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting TOT (p=0.545, b=0.985, kelly=0.084) with $2147.83
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.090, kelly=0.372) with $9503.55
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.450
[PORT] Sector Consumer Goods: selecting PM (p=0.529, b=1.030, kelly=0.071) with $1812.89
[PORT] Sector Financial: 10 candidates, avg score=0.469
[PORT] Sector Financial: selecting V (p=0.593, b=1.025, kelly=0.195) with $4987.70
[PORT] Sector Healthcare: 10 candidates, avg score=0.458
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.025, kelly=0.078) with $1992.74
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.003, kelly=0.255) with $6506.40
[PORT] Sector Services: 10 candidates, avg score=0.533
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.060, kelly=0.375) with $9583.55
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.049, kelly=0.461) with $11788.12
[PORT] Sector Utilities: 10 candidates, avg score=0.524
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.904, kelly=0.224) with $5715.99
Raw prediction for AAPL: 0.4916129410266876
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5215736627578735
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.43259871006011963
Calibrated prediction for ABBV: 0.4252780079841614
Raw prediction for AEP: 0.5984650254249573
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.44515907764434814
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48501691222190857
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5806178450584412
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4537307620048523
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.516802966594696
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49669426679611206
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.3800460994243622
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.4522184133529663
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4280928671360016
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.4701380729675293
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.46519044041633606
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46240323781967163
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5788725018501282
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4157980680465698
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4459879994392395
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.550430178642273
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4566195607185364
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6216253638267517
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.43474823236465454
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.44988152384757996
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48998796939849854
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5000445246696472
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.4981772303581238
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4844357669353485
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5052914023399353
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5878204703330994
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5076571106910706
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5208021998405457
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5100201964378357
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4011830687522888
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6235774159431458
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.47312450408935547
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5373620390892029
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5973271727561951
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.41855502128601074
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5095047354698181
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5475263595581055
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3452327251434326
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5135971307754517
Calibrated prediction for JPM: 0.5134379863739014
Raw prediction for KO: 0.4575567841529846
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5242771506309509
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3965010344982147
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5723665952682495
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4819094240665436
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6454725861549377
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5050729513168335
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.5009264349937439
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.4872227609157562
Calibrated prediction for MSFT: 0.46271318197250366
Raw prediction for NEE: 0.5123067498207092
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5182048678398132
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3761492669582367
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3309619128704071
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4888482093811035
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5509659647941589
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5000208020210266
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.49024713039398193
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43804603815078735
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41812291741371155
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.47940391302108765
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.49183234572410583
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45211419463157654
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.47686225175857544
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.597152590751648
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.47713372111320496
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5016777515411377
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5224767327308655
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.5343838930130005
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.29935193061828613
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.32283467054367065
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5519006252288818
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.2697899639606476
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4708283841609955
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5418192148208618
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3940418064594269
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.46883460879325867
Calibrated prediction for UN: 0.4516128897666931
Raw prediction for UNH: 0.4487853944301605
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5152498483657837
Calibrated prediction for UPS: 0.5426356792449951

Simulating Trading Days:  66%|██████▌   | 66/100 [05:30<00:39,  1.16s/it]

Raw prediction for UTX: 0.48112308979034424
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5676792860031128
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5214946269989014
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5074867010116577
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4561617374420166
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5009336471557617
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.479
[PORT] Sector Basic Matierials: selecting TOT (p=0.545, b=0.983, kelly=0.083) with $2131.79
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.090, kelly=0.372) with $9522.40
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.450
[PORT] Sector Consumer Goods: selecting PM (p=0.529, b=1.031, kelly=0.071) with $1821.01
[PORT] Sector Financial: 10 candidates, avg score=0.468
[PORT] Sector Financial: selecting V (p=0.580, b=1.027, kelly=0.171) with $4379.36
[PORT] Sector Healthcare: 10 candidates, avg score=0.465
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.024, kelly=0.077) with $1982.65
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.005, kelly=0.255) with $6539.86
[PORT] Sector Services: 10 candidates, avg score=0.513
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.041, kelly=0.220) with $5622.78
[PORT] Sector Technology: 10 candidates, avg score=0.516
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.048, kelly=0.289) with $7407.19
[PORT] Sector Utilities: 10 candidates, avg score=0.524
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.903, kelly=0.223) with $5722.25
Raw prediction for AAPL: 0.4919864535331726
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5217763185501099
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4268667697906494
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.6007629632949829
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4448474645614624
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48528555035591125
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5632434487342834
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4527778625488281
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5169252157211304
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4963917136192322
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.3691537380218506
Calibrated prediction for BBL: 0.35300374031066895
Raw prediction for BCH: 0.44556236267089844
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4262714684009552
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.45207229256629944
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4656507968902588
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4621596038341522
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5760701298713684
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4115995168685913
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.44533276557922363
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5600771307945251
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.4538913369178772
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6154700517654419
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4210347831249237
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4515947997570038
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4891556203365326
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4971775412559509
Calibrated prediction for CVX: 0.4615384638309479
Raw prediction for D: 0.4933895468711853
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4843302071094513
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5046800374984741
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5862165093421936
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5077919363975525
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5207884311676025
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5096815824508667
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.388970285654068
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5846142172813416
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.4696783721446991
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5372231006622314
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5929988622665405
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.41901665925979614
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5106849074363708
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5467194318771362
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.350572794675827
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.5140680074691772
Calibrated prediction for JPM: 0.5134379863739014
Raw prediction for KO: 0.4569900929927826
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5231850147247314
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.38921040296554565
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5728515982627869
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48161864280700684
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6465414762496948
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5064001083374023
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.5005781054496765
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.48393216729164124
Calibrated prediction for MSFT: 0.46271318197250366
Raw prediction for NEE: 0.5112268328666687
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5165475606918335
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.37743237614631653
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.32468321919441223
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4891030192375183
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5475178956985474
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5001782774925232
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4944608807563782
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43809518218040466
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41737133264541626
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4704659879207611
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.4911612570285797
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4508296847343445
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4760841131210327
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5979833602905273
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4696144461631775
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5009820461273193
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.522197961807251
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.5364616513252258
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.2967931032180786
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3124672770500183
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:  67%|██████▋   | 67/100 [05:31<00:37,  1.15s/it]

Raw prediction for T: 0.5557158589363098
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.26429659128189087
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4613915681838989
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5406163930892944
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.37584561109542847
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.44998398423194885
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4590930938720703
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5133327841758728
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4746740162372589
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.558049738407135
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5219601392745972
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5075078010559082
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4594189524650574
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5003340244293213
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.467
[PORT] Sector Basic Matierials: selecting TOT (p=0.545, b=0.983, kelly=0.083) with $2122.37
[PORT] Sector Conglomerates: 7 candidates, avg score=0.491
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.089, kelly=0.371) with $9503.04
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.441
[PORT] Sector Consumer Goods: selecting PM (p=0.529, b=1.033, kelly=0.072) with $1841.65
[PORT] Sector Financial: 10 candidates, avg score=0.468
[PORT] Sector Financial: selecting V (p=0.580, b=1.027, kelly=0.171) with $4378.22
[PORT] Sector Healthcare: 10 candidates, avg score=0.467
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.021, kelly=0.140) with $3570.18
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.004, kelly=0.255) with $6523.02
[PORT] Sector Services: 10 candidates, avg score=0.509
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.039, kelly=0.219) with $5605.54
[PORT] Sector Technology: 10 candidates, avg score=0.515
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.047, kelly=0.257) with $6580.77
[PORT] Sector Utilities: 10 candidates, avg score=0.524
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.905, kelly=0.224) with $5739.53
Raw prediction for AAPL: 0.4922533929347992
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.521641731262207
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.42090940475463867
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.6032567620277405
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4441905617713928
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4852953553199768
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5517299175262451
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4518560767173767
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5171338319778442
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4965537488460541
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.3635222017765045
Calibrated prediction for BBL: 0.35300374031066895
Raw prediction for BCH: 0.44108596444129944
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4257117807865143
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.42898109555244446
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.46771636605262756
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4624101221561432
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5670093894004822
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.410898894071579
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.44449275732040405
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.565240740776062
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.4497891366481781
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6076805591583252
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.40797820687294006
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4470512270927429
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4879482388496399
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.497585266828537
Calibrated prediction for CVX: 0.4615384638309479
Raw prediction for D: 0.48756203055381775
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48379212617874146
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5044827461242676
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5812243819236755
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5078018307685852
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.520745575428009
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5093852877616882
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.37702706456184387
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5406829714775085
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.4649646580219269
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5372257828712463
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.586540699005127
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4189852774143219
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5102392435073853
Calibrated prediction for IEP: 0.5142186880111694
Raw prediction for INTC: 0.5451387763023376
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3541218936443329
Calibrated prediction for JNJ: 0.3636363744735718
Raw prediction for JPM: 0.514824390411377
Calibrated prediction for JPM: 0.5134379863739014
Raw prediction for KO: 0.4548216164112091
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5219154953956604
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.39106884598731995
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5731765031814575
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48106691241264343
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6477379202842712
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5086619257926941
Calibrated prediction for MO: 0.49964639544487
Raw prediction for MRK: 0.49845045804977417
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.4836379885673523
Calibrated prediction for MSFT: 0.46271318197250366
Raw prediction for NEE: 0.5080603957176208
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5125874280929565
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.37537387013435364
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.31981518864631653
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.488504558801651
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5450049638748169
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.500302255153656
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4958976209163666
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4372274875640869
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4178182780742645
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.45604801177978516
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.4903457760810852
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4494801163673401
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4808177947998047
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5984204411506653
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.46054086089134216
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5012988448143005
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5218457579612732
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.5362425446510315
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.3041906952857971
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.2976526618003845
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5514010190963745
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.2558016777038574
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4569684863090515
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5375271439552307
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.34931495785713196
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4246337413787842
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4639489948749542
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5083577036857605
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.47653329372406006
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5484346151351929
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.523406982421875
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5083400011062622
Calibrated prediction for WFC: 0.4904371201992035

Simulating Trading Days:  68%|██████▊   | 68/100 [05:32<00:36,  1.14s/it]

Raw prediction for WMT: 0.4655718207359314
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5004695057868958
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.467
[PORT] Sector Basic Matierials: selecting TOT (p=0.545, b=0.984, kelly=0.084) with $2144.29
[PORT] Sector Conglomerates: 7 candidates, avg score=0.488
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.090, kelly=0.372) with $9519.38
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.441
[PORT] Sector Consumer Goods: selecting PM (p=0.529, b=1.035, kelly=0.073) with $1868.06
[PORT] Sector Financial: 10 candidates, avg score=0.468
[PORT] Sector Financial: selecting V (p=0.580, b=1.030, kelly=0.172) with $4405.60
[PORT] Sector Healthcare: 10 candidates, avg score=0.469
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.019, kelly=0.139) with $3552.57
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.006, kelly=0.256) with $6551.92
[PORT] Sector Services: 10 candidates, avg score=0.515
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.041, kelly=0.220) with $5628.36
[PORT] Sector Technology: 10 candidates, avg score=0.518
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.049, kelly=0.258) with $6603.07
[PORT] Sector Utilities: 10 candidates, avg score=0.524
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.905, kelly=0.224) with $5737.95
Raw prediction for AAPL: 0.49244260787963867
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5209084153175354
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4169350564479828
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.6030102968215942
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4430350363254547
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48489466309547424
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5458912253379822
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45100143551826477
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5173623561859131
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4969884157180786
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.357419490814209
Calibrated prediction for BBL: 0.35300374031066895
Raw prediction for BCH: 0.43845146894454956
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4251832067966461
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.43543922901153564
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4679056704044342
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46271416544914246
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5574267506599426
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.41006821393966675
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4438275992870331
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5664164423942566
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.44877728819847107
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.6011461019515991
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.3972000777721405
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4371100068092346
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48662737011909485
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.49085259437561035
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4744229316711426
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.482957124710083
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5044445395469666
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5734319090843201
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5076763033866882
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5207420587539673
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5090472102165222
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.36251088976860046
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5078161358833313
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.46104466915130615
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5376372933387756
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5772938132286072
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.4186997711658478
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5074182748794556
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.543647050857544
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.36096030473709106
Calibrated prediction for JNJ: 0.40636515617370605
Raw prediction for JPM: 0.5156790614128113
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4510575532913208
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.520868182182312
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3964875638484955
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5737265944480896
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.480896532535553
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6490694284439087
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5108639597892761
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.49833282828330994
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.4847189486026764
Calibrated prediction for MSFT: 0.46271318197250366
Raw prediction for NEE: 0.5030998587608337
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5092582702636719
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3735302686691284
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3194234371185303
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4886602759361267
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5425651669502258
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5003947019577026
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.49814674258232117
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43614986538887024
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4173678159713745
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.441567599773407
Calibrated prediction for PM: 0.5
Raw prediction for PPL: 0.4893639385700226
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4482532739639282
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.48837053775787354
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5996882319450378
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.44993191957473755
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5014529824256897
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5215985178947449
Calibrated prediction for SNY: 0.5244196653366089
Raw prediction for SO: 0.5376554727554321
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.31377387046813965
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.2864459455013275
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5445252656936646
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.2484130561351776
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4574601650238037
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5375389456748962
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.31793341040611267
Calibrated prediction for UL: 0.3333333432674408

Simulating Trading Days:  69%|██████▉   | 69/100 [05:33<00:35,  1.14s/it]

Raw prediction for UN: 0.4025929868221283
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4666416645050049
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.5004649758338928
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4888434410095215
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5406476855278015
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.521904706954956
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.509182333946228
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.474200040102005
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5000255107879639
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.465
[PORT] Sector Basic Matierials: selecting TOT (p=0.545, b=0.983, kelly=0.083) with $2127.12
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.093, kelly=0.372) with $9546.96
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.441
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.978, kelly=0.137) with $3523.69
[PORT] Sector Financial: 10 candidates, avg score=0.468
[PORT] Sector Financial: selecting V (p=0.580, b=1.029, kelly=0.172) with $4405.97
[PORT] Sector Healthcare: 10 candidates, avg score=0.473
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.021, kelly=0.139) with $3574.24
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.008, kelly=0.257) with $6576.11
[PORT] Sector Services: 10 candidates, avg score=0.515
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.042, kelly=0.220) with $5642.13
[PORT] Sector Technology: 10 candidates, avg score=0.515
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.050, kelly=0.258) with $6614.51
[PORT] Sector Utilities: 10 candidates, avg score=0.519
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.906, kelly=0.225) with $5762.00
Raw prediction for AAPL: 0.4925292134284973
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5203867554664612
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.41509711742401123
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.6006491780281067
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.441461443901062
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4841340482234955
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5345949530601501
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.45031479001045227
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5175251960754395
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.497755765914917
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.35329148173332214
Calibrated prediction for BBL: 0.35300374031066895
Raw prediction for BCH: 0.4383472800254822
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4250413775444031
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.46506601572036743
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.46621227264404297
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46324482560157776
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.55018150806427
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.41088593006134033
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4432171583175659
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5628900527954102
Calibrated prediction for CELG: 0.5652173757553101
Raw prediction for CHL: 0.4471326470375061
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5947847962379456
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.38956379890441895
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.43367812037467957
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48530346155166626
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.48241177201271057
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.46092092990875244
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.48196685314178467
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5047286152839661
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.560506284236908
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5074530839920044
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.520573616027832
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5087377429008484
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.35392558574676514
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.47970879077911377
Calibrated prediction for GOOG: 0.529411792755127
Raw prediction for HD: 0.4608112573623657
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5380562543869019
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5699231624603271
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.417554646730423
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5023137927055359
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5419588088989258
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3694215714931488
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5168053507804871
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4468801021575928
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5200784206390381
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3926782011985779
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5743581652641296
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4809549152851105
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6496343016624451
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5125535726547241
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5007728934288025
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.4870750904083252
Calibrated prediction for MSFT: 0.46271318197250366
Raw prediction for NEE: 0.49868372082710266
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5047518610954285
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3715427815914154
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3171796202659607
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4887024462223053
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5444917678833008
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.500532329082489
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.49757495522499084
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4347195625305176
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41545572876930237
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.42612093687057495
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4874112010002136
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.44703227281570435
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4952017068862915
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.6009426116943359
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.44097280502319336
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5021538138389587
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5213942527770996
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.5359764695167542
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.32168835401535034
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.2789163589477539
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5416377782821655
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.24420730769634247
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4582103490829468
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5393542647361755
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2953698933124542
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3824871778488159
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4664001166820526
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.4909314215183258
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5054686069488525
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.533412516117096
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5175702571868896
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5106670260429382
Calibrated prediction for WFC: 0.4904371201992035

Simulating Trading Days:  70%|███████   | 70/100 [05:34<00:34,  1.15s/it]

Raw prediction for WMT: 0.48181742429733276
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.499788373708725
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.465
[PORT] Sector Basic Matierials: selecting TOT (p=0.545, b=0.982, kelly=0.083) with $2118.26
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.095, kelly=0.373) with $9554.64
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.430
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.976, kelly=0.137) with $3506.24
[PORT] Sector Financial: 10 candidates, avg score=0.468
[PORT] Sector Financial: selecting V (p=0.580, b=1.029, kelly=0.172) with $4395.53
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting CELG (p=0.565, b=1.020, kelly=0.139) with $3555.32
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.007, kelly=0.256) with $6560.00
[PORT] Sector Services: 10 candidates, avg score=0.515
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.041, kelly=0.220) with $5629.63
[PORT] Sector Technology: 10 candidates, avg score=0.506
[PORT] Sector Technology: selecting T (p=0.590, b=0.962, kelly=0.164) with $4194.73
[PORT] Sector Utilities: 10 candidates, avg score=0.519
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.905, kelly=0.224) with $5745.59
Raw prediction for AAPL: 0.49261680245399475
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5199840068817139
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.4127857983112335
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5959790945053101
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.43979060649871826
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48321130871772766
Calibrated prediction for AMGN: 0.4902982711791992
Raw prediction for AMZN: 0.5296944379806519
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.44968605041503906
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5176844000816345
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.49860864877700806
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.3500310182571411
Calibrated prediction for BBL: 0.35300374031066895
Raw prediction for BCH: 0.43961989879608154
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4258643090724945
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.4851934313774109
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.46408265829086304
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4635237455368042
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5453765392303467
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.41201597452163696
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4423588216304779
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5527993440628052
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4430035948753357
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5889601111412048
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.38439878821372986
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.43356937170028687
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48429811000823975
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4740240275859833
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4513796269893646
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4809750020503998
Calibrated prediction for DHR: 0.47826087474823
Raw prediction for DIS: 0.5052920579910278
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5427246689796448
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5072484016418457
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5203748345375061
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5084089040756226
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.349518746137619
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4591315984725952
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4629640281200409
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5381919145584106
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.566943347454071
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.41527605056762695
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.49544456601142883
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5402699708938599
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3761489689350128
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.517928957939148
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4420958459377289
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.519842803478241
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.38552260398864746
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.574955403804779
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48124849796295166
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6502902507781982
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5151492953300476
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5030477046966553
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.49365079402923584
Calibrated prediction for MSFT: 0.47058823704719543
Raw prediction for NEE: 0.49409160017967224
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5010576248168945
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3672676086425781
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3159664571285248
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.48895934224128723
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5445902347564697
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5007482767105103
Calibrated prediction for PEP: 0.4994901418685913
Raw prediction for PFE: 0.49407634139060974
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43343329429626465
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41314709186553955
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.41306301951408386
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4856616258621216
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4462106227874756
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.49960505962371826
Calibrated prediction for RDS-B: 0.5675675868988037
Raw prediction for REX: 0.600811243057251
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.43553775548934937
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5029603838920593
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5213042497634888
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.5305253863334656
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.3235737979412079
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.2752070724964142
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5363199710845947
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.24728012084960938
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4558059871196747
Calibrated prediction for TOT: 0.5454545617103577

Simulating Trading Days:  71%|███████   | 71/100 [05:35<00:33,  1.15s/it]

Raw prediction for TSM: 0.5403605699539185
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2809447944164276
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.36662888526916504
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4619314670562744
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.48223116993904114
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5122767686843872
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.526226282119751
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5144041776657104
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5119419097900391
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.488253653049469
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.49996131658554077
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.470
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.568, b=0.894, kelly=0.084) with $2152.05
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.096, kelly=0.373) with $9562.93
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.431
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.974, kelly=0.136) with $3485.27
[PORT] Sector Financial: 10 candidates, avg score=0.468
[PORT] Sector Financial: selecting V (p=0.580, b=1.031, kelly=0.173) with $4418.69
[PORT] Sector Healthcare: 10 candidates, avg score=0.471
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.019, kelly=0.075) with $1930.43
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.511
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.006, kelly=0.256) with $6545.82
[PORT] Sector Services: 10 candidates, avg score=0.515
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.040, kelly=0.219) with $5615.54
[PORT] Sector Technology: 10 candidates, avg score=0.492
[PORT] Sector Technology: selecting T (p=0.590, b=0.964, kelly=0.164) with $4209.98
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.904, kelly=0.224) with $5726.57
Raw prediction for AAPL: 0.4925799071788788
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5204840302467346
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.407155841588974
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5891699194908142
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.43791815638542175
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4825732707977295
Calibrated prediction for AMGN: 0.4810773730278015
Raw prediction for AMZN: 0.5238215327262878
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.44931522011756897
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.517728865146637
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.4996523857116699
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.3526349365711212
Calibrated prediction for BBL: 0.35300374031066895
Raw prediction for BCH: 0.4485641121864319
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4272853434085846
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.5049403309822083
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4624674320220947
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4638814330101013
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5415610671043396
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.41751721501350403
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.44159168004989624
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5357975959777832
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4459438920021057
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5857807993888855
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.38070428371429443
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.42553961277008057
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4833569824695587
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.47040286660194397
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.44652247428894043
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.48082467913627625
Calibrated prediction for DHR: 0.47826087474823
Raw prediction for DIS: 0.5061236023902893
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5262759327888489
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5072111487388611
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5202189087867737
Calibrated prediction for FB: 0.5225412249565125
Raw prediction for GD: 0.5080116391181946
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3530549108982086
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4475474953651428
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4735746681690216
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.538849413394928
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5644482970237732
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.41094592213630676
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4860113263130188
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5391371846199036
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3815430700778961
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.518846333026886
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4372932016849518
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5205644965171814
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3842316269874573
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5755646824836731
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4813505709171295
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6507573127746582
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5184323787689209
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5020920038223267
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.49972906708717346
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.4876777231693268
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.49840080738067627
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3605023920536041
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3187394440174103
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.48959532380104065
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5514068603515625
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5010873079299927
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4892052710056305
Calibrated prediction for PFE: 0.4770280122756958
Raw prediction for PG: 0.4332487881183624
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4112406373023987
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4061466455459595
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.48434901237487793
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.445771723985672
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5070910453796387
Calibrated prediction for RDS-B: 0.5675675868988037
Raw prediction for REX: 0.5949113368988037
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4355866611003876
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5033425092697144
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5211837887763977
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.5173172950744629
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.32225754857063293
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.28161415457725525
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5293782949447632
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.2592417597770691
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.46563684940338135
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5437157154083252
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2705756723880768
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.35408511757850647
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4523640275001526
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.47560960054397583
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5164746642112732
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5213304162025452
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5116702318191528
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5131245255470276
Calibrated prediction for WFC: 0.4904371201992035

Simulating Trading Days:  72%|███████▏  | 72/100 [05:36<00:32,  1.15s/it]

Raw prediction for WMT: 0.490866482257843
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5007026791572571
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.478
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.568, b=0.895, kelly=0.084) with $2160.57
[PORT] Sector Conglomerates: 7 candidates, avg score=0.487
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.098, kelly=0.374) with $9569.53
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.431
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.976, kelly=0.137) with $3503.16
[PORT] Sector Financial: 10 candidates, avg score=0.463
[PORT] Sector Financial: selecting V (p=0.526, b=1.032, kelly=0.067) with $1725.39
[PORT] Sector Healthcare: 10 candidates, avg score=0.464
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.018, kelly=0.075) with $1921.83
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.511
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.006, kelly=0.256) with $6542.45
[PORT] Sector Services: 10 candidates, avg score=0.515
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.042, kelly=0.220) with $5629.60
[PORT] Sector Technology: 10 candidates, avg score=0.494
[PORT] Sector Technology: selecting T (p=0.590, b=0.966, kelly=0.165) with $4232.29
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.906, kelly=0.225) with $5751.39
Raw prediction for AAPL: 0.49259135127067566
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5213184356689453
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3977951109409332
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5734874606132507
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4364282190799713
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48220956325531006
Calibrated prediction for AMGN: 0.4810773730278015
Raw prediction for AMZN: 0.5259246230125427
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4489636719226837
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5178117156028748
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5005602836608887
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.3598140478134155
Calibrated prediction for BBL: 0.35300374031066895
Raw prediction for BCH: 0.46031486988067627
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.42891770601272583
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.5191632509231567
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4622991681098938
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46401068568229675
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5402621626853943
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.42306867241859436
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.44097355008125305
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5141485929489136
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.4370075464248657
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5812748670578003
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.3778766393661499
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4142937660217285
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48249733448028564
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.47023043036460876
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.44533804059028625
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4812588691711426
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5070555806159973
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5166311860084534
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5074094533920288
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5200209617614746
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5076758861541748
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3664643466472626
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4371434450149536
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4842081069946289
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.538985550403595
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5616763830184937
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.40540993213653564
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4769631326198578
Calibrated prediction for IEP: 0.46978840231895447
Raw prediction for INTC: 0.5382260084152222
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3870779573917389
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5196382999420166
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4319729804992676
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5218733549118042
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3844648003578186
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5760564804077148
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.481189101934433
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6510851383209229
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5220196843147278
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5025681853294373
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5052876472473145
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.48221221566200256
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.4972887635231018
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3573804497718811
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3224421739578247
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49048036336898804
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5521299839019775
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5012953877449036
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.48653078079223633
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4332755506038666
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.41007542610168457
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4066566526889801
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4847157597541809
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.44540947675704956
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5146465301513672
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5848303437232971
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4379015266895294
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5034981369972229
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5210779905319214
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.49980735778808594
Calibrated prediction for SO: 0.5512372255325317
Raw prediction for SPLP: 0.31686902046203613
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.297219455242157
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5173133611679077
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.2804763913154602
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.4809838831424713
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5453445911407471
Calibrated prediction for TSM: 0.5770066976547241

Simulating Trading Days:  73%|███████▎  | 73/100 [05:38<00:30,  1.14s/it]

Raw prediction for UL: 0.2624289393424988
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3436986207962036
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4402506947517395
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4698350429534912
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5008026957511902
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5165902376174927
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5065966844558716
Calibrated prediction for VZ: 0.4974130392074585
Raw prediction for WFC: 0.5141231417655945
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.4920903444290161
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5009046792984009
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.478
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.896, kelly=0.094) with $2410.49
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.096, kelly=0.373) with $9554.18
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.431
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.975, kelly=0.136) with $3490.58
[PORT] Sector Financial: 10 candidates, avg score=0.463
[PORT] Sector Financial: selecting V (p=0.526, b=1.032, kelly=0.067) with $1721.47
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.016, kelly=0.074) with $1897.15
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.006, kelly=0.256) with $6547.87
[PORT] Sector Services: 10 candidates, avg score=0.523
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.040, kelly=0.219) with $5615.13
[PORT] Sector Technology: 10 candidates, avg score=0.491
[PORT] Sector Technology: selecting T (p=0.590, b=0.966, kelly=0.165) with $4230.67
[PORT] Sector Utilities: 10 candidates, avg score=0.514
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.906, kelly=0.224) with $5744.42
Raw prediction for AAPL: 0.4925515353679657
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5231216549873352
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3902450501918793
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5602510571479797
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4351542592048645
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4820868968963623
Calibrated prediction for AMGN: 0.4810773730278015
Raw prediction for AMZN: 0.5237593054771423
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.448720246553421
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5178131461143494
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5013942122459412
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.37215450406074524
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.47102344036102295
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4324820041656494
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.5186561346054077
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.46265658736228943
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4637562334537506
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5432180166244507
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4262276291847229
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4411642551422119
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4888477623462677
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4228186011314392
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5789380073547363
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.3764740824699402
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.40242889523506165
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4817259609699249
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4709872007369995
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4456790089607239
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4819164574146271
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5078595876693726
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5074877738952637
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5077250599861145
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5198160409927368
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.50736004114151
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.38546618819236755
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4214247465133667
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4975586533546448
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5390880703926086
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.560034453868866
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3982153534889221
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4734961688518524
Calibrated prediction for IEP: 0.46978840231895447
Raw prediction for INTC: 0.5372322797775269
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3921157717704773
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5202596783638
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4270278215408325
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5229345560073853
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.38405275344848633
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5765308141708374
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4809969663619995
Calibrated prediction for MDT: 0.48429057002067566
Raw prediction for MMM: 0.6514021158218384
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5238211154937744
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5041496157646179
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5127159953117371
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.48082900047302246
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.499433696269989
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3554914891719818
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.32517489790916443
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4919586777687073
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5533766746520996
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5012761950492859
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.48646193742752075
Calibrated prediction for PFE: 0.4399999976158142
Raw prediction for PG: 0.4340185523033142
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.40817561745643616
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4130672514438629
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.48568424582481384
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.44522184133529663
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5172434449195862
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5709882974624634
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.44204580783843994
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5039451122283936
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5209662914276123
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4906187951564789
Calibrated prediction for SO: 0.4141654372215271

Simulating Trading Days:  74%|███████▍  | 74/100 [05:39<00:29,  1.13s/it]

Raw prediction for SPLP: 0.3095952272415161
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3118315637111664
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5052616596221924
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.3147743046283722
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.48673391342163086
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5435497760772705
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.25915542244911194
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.33952486515045166
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4305870831012726
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4657554626464844
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.47432026267051697
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5105099081993103
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5009260177612305
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5150725245475769
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.49167656898498535
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5008785724639893
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.484
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.896, kelly=0.094) with $2412.82
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.098, kelly=0.374) with $9598.37
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.431
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.976, kelly=0.137) with $3509.05
[PORT] Sector Financial: 10 candidates, avg score=0.463
[PORT] Sector Financial: selecting V (p=0.526, b=1.033, kelly=0.068) with $1743.79
[PORT] Sector Healthcare: 10 candidates, avg score=0.452
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.009, kelly=0.045) with $1145.48
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.990, kelly=0.250) with $6409.58
[PORT] Sector Services: 10 candidates, avg score=0.523
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.039, kelly=0.219) with $5624.48
[PORT] Sector Technology: 10 candidates, avg score=0.475
[PORT] Sector Technology: selecting T (p=0.590, b=0.968, kelly=0.166) with $4269.45
[PORT] Sector Utilities: 10 candidates, avg score=0.501
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.907, kelly=0.225) with $5773.47
Raw prediction for AAPL: 0.49247288703918457
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5257046818733215
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3867603540420532
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5496309399604797
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4338451623916626
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4820080101490021
Calibrated prediction for AMGN: 0.4810773730278015
Raw prediction for AMZN: 0.5193036198616028
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.44841673970222473
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5177599787712097
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5019596815109253
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.3882167339324951
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.485712468624115
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.441466361284256
Calibrated prediction for BHP: 0.4761904776096344
Raw prediction for BP: 0.51698237657547
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4660114049911499
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46356523036956787
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5462396144866943
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4316422939300537
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.44158992171287537
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4616222083568573
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.42049434781074524
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5799673199653625
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.37695348262786865
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.3947799503803253
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4813224971294403
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4781780242919922
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.44513002038002014
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4830019474029541
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5083528161048889
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.500548779964447
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5079019665718079
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5196686387062073
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5071637630462646
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4130500853061676
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.4324797987937927
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4987776577472687
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5387006402015686
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5589476227760315
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3890363276004791
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4718572199344635
Calibrated prediction for IEP: 0.46978840231895447
Raw prediction for INTC: 0.5372823476791382
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.39102858304977417
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5205735564231873
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4224708676338196
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5256213545799255
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3860836625099182
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5767025351524353
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.48050329089164734
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6501913070678711
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5234735608100891
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5078867673873901
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5197953581809998
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.48260003328323364
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5011789798736572
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.35055431723594666
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.33140140771865845
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4933256506919861
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5494843125343323
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5012058019638062
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.4905741512775421
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4343562126159668
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4085906445980072
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.42186781764030457
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4859050214290619
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.44595223665237427
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5197978615760803
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5606812834739685
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.44721707701683044
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5054538249969482
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5209810733795166
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4884693920612335
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.31336694955825806
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3288380801677704
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5009487271308899
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.35148027539253235
Calibrated prediction for TM: 0.3477618992328644

Simulating Trading Days:  75%|███████▌  | 75/100 [05:40<00:31,  1.26s/it]

Raw prediction for TOT: 0.48697659373283386
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5441502332687378
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.259612500667572
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.33856791257858276
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.42541366815567017
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4634946584701538
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4647851586341858
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5062366127967834
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.49493104219436646
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5154582858085632
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.48823028802871704
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5020353198051453
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.484
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.895, kelly=0.093) with $2398.54
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.096, kelly=0.373) with $9593.20
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.431
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.976, kelly=0.137) with $3512.94
[PORT] Sector Financial: 10 candidates, avg score=0.470
[PORT] Sector Financial: selecting V (p=0.526, b=1.033, kelly=0.068) with $1743.28
[PORT] Sector Healthcare: 10 candidates, avg score=0.458
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.011, kelly=0.046) with $1172.14
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.992, kelly=0.250) with $6432.14
[PORT] Sector Services: 10 candidates, avg score=0.523
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.039, kelly=0.219) with $5621.87
[PORT] Sector Technology: 10 candidates, avg score=0.475
[PORT] Sector Technology: selecting T (p=0.590, b=0.982, kelly=0.172) with $4425.56
[PORT] Sector Utilities: 10 candidates, avg score=0.492
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.907, kelly=0.225) with $5779.92
Raw prediction for AAPL: 0.4923866391181946
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5291491746902466
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.38501080870628357
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5426575541496277
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.43212661147117615
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48213833570480347
Calibrated prediction for AMGN: 0.4810773730278015
Raw prediction for AMZN: 0.5148407220840454
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4479678273200989
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.517783522605896
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5022029280662537
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.39923375844955444
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.4954966604709625
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.451741099357605
Calibrated prediction for BHP: 0.4878840148448944
Raw prediction for BP: 0.5141130685806274
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4686371088027954
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46297353506088257
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.545333743095398
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.43498268723487854
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.441135972738266
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4389403462409973
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.42907577753067017
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5802428722381592
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.37982258200645447
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.39076095819473267
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48109400272369385
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4785274863243103
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.44618546962738037
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4843621551990509
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.508539617061615
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.49893367290496826
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5078318119049072
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5193654298782349
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.508179783821106
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4334222376346588
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.460947722196579
Calibrated prediction for GOOG: 0.38311025500297546
Raw prediction for HD: 0.4953324794769287
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5379993319511414
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.55878084897995
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.38076913356781006
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4711627960205078
Calibrated prediction for IEP: 0.46978840231895447
Raw prediction for INTC: 0.5369188785552979
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3861997425556183
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5205761790275574
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.41975176334381104
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5293520092964172
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3869152367115021
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5768426060676575
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4799743592739105
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6494183540344238
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5222396850585938
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5142607688903809
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.526633620262146
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4822979271411896
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5012811422348022
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.34451866149902344
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.33463186025619507
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49443721771240234
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5442018508911133
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5010035037994385
Calibrated prediction for PEP: 0.507476270198822
Raw prediction for PFE: 0.4968896806240082
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43451836705207825
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4115848243236542
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.4325677752494812
Calibrated prediction for PM: 0.495015025138855
Raw prediction for PPL: 0.4860985279083252
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.446959525346756
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5216435790061951
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5606290102005005
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4525091350078583
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.506472647190094
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5209234356880188
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4839375913143158
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.31724244356155396
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3448599576950073
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5145203471183777
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.3828434348106384
Calibrated prediction for TM: 0.3477618992328644
Raw prediction for TOT: 0.48442816734313965
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5455386638641357
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.26263538002967834
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.34028351306915283
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.42556124925613403
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4645524322986603
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4664236605167389
Calibrated prediction for UTX: 0.375
Raw prediction for V: 0.503452479839325
Calibrated prediction for V: 0.48833489418029785
Raw prediction for VZ: 0.49272531270980835
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5156378149986267
Calibrated prediction for WFC: 0.4904371201992035

Simulating Trading Days:  76%|███████▌  | 76/100 [05:42<00:32,  1.37s/it]

Raw prediction for WMT: 0.4832445979118347
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5029493570327759
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.485
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.896, kelly=0.094) with $2410.55
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.096, kelly=0.373) with $9598.41
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.441
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.983, kelly=0.140) with $3591.56
[PORT] Sector Financial: 10 candidates, avg score=0.466
[PORT] Sector Financial: selecting JPM (p=0.518, b=1.057, kelly=0.062) with $1583.25
[PORT] Sector Healthcare: 10 candidates, avg score=0.463
[PORT] Sector Healthcare: selecting MRK (p=0.545, b=1.009, kelly=0.095) with $2439.88
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.495
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.991, kelly=0.250) with $6430.44
[PORT] Sector Services: 10 candidates, avg score=0.523
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.040, kelly=0.219) with $5639.97
[PORT] Sector Technology: 10 candidates, avg score=0.479
[PORT] Sector Technology: selecting T (p=0.590, b=0.991, kelly=0.176) with $4529.53
[PORT] Sector Utilities: 10 candidates, avg score=0.492
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.909, kelly=0.226) with $5809.67
Raw prediction for AAPL: 0.49216291308403015
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5322916507720947
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3836687505245209
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5384722948074341
Calibrated prediction for AEP: 0.6314609050750732
Raw prediction for AGFS: 0.4309050440788269
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.482445627450943
Calibrated prediction for AMGN: 0.4810773730278015
Raw prediction for AMZN: 0.5123716592788696
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4476912319660187
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.517649233341217
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5021632313728333
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4029720425605774
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.5006581544876099
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.45911160111427307
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5160366296768188
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4704311490058899
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4624524414539337
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.537611186504364
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4368533790111542
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.44037970900535583
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.42230409383773804
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4490971267223358
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5782638192176819
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.3870069682598114
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.39090725779533386
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48123857378959656
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4708874821662903
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.44928839802742004
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4853112995624542
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.508821964263916
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5009035468101501
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5076752305030823
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5189039707183838
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5092159509658813
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.43451398611068726
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5158377289772034
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.48917514085769653
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5390918254852295
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5628028512001038
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3760002553462982
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4721077084541321
Calibrated prediction for IEP: 0.46978840231895447
Raw prediction for INTC: 0.5370869040489197
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.38460955023765564
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5206381678581238
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4182281494140625
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5304129719734192
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.39382433891296387
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5769246816635132
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4797431230545044
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6466357111930847
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5261489748954773
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5099082589149475
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5278462171554565
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4822317361831665
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5026635527610779
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.34062835574150085
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.33795541524887085
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4959781765937805
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5543745160102844
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5013411641120911
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5039892196655273
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43596184253692627
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4192894399166107
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.44370535016059875
Calibrated prediction for PM: 0.5
Raw prediction for PPL: 0.4866592586040497
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4478905200958252
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5242946743965149
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5667517185211182
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.45476144552230835
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5071306228637695
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5208348035812378
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.47622498869895935
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.31475478410720825
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3609680235385895
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5293542146682739
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.41924986243247986
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.4866155683994293
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.556279718875885
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2654305398464203
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.34451183676719666
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.432193785905838
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.46942001581192017
Calibrated prediction for UPS: 0.5426356792449951

Simulating Trading Days:  77%|███████▋  | 77/100 [05:43<00:31,  1.35s/it]

Raw prediction for UTX: 0.45510828495025635
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5064627528190613
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.4981588125228882
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5158253312110901
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.47619980573654175
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.503032386302948
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.486
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.896, kelly=0.094) with $2410.06
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.096, kelly=0.373) with $9602.58
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.446
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.952, kelly=0.126) with $3241.75
[PORT] Sector Financial: 10 candidates, avg score=0.470
[PORT] Sector Financial: selecting V (p=0.526, b=1.033, kelly=0.068) with $1749.04
[PORT] Sector Healthcare: 10 candidates, avg score=0.458
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.009, kelly=0.045) with $1147.35
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.993, kelly=0.251) with $6455.87
[PORT] Sector Services: 10 candidates, avg score=0.523
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.043, kelly=0.220) with $5668.49
[PORT] Sector Technology: 10 candidates, avg score=0.512
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.043, kelly=0.256) with $6580.66
[PORT] Sector Utilities: 10 candidates, avg score=0.492
[PORT] Sector Utilities: selecting AEP (p=0.631, b=0.911, kelly=0.227) with $5832.41
Raw prediction for AAPL: 0.49171537160873413
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5342860817909241
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3816905915737152
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5340539216995239
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.42880189418792725
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48288363218307495
Calibrated prediction for AMGN: 0.4810773730278015
Raw prediction for AMZN: 0.5262226462364197
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4475090503692627
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5177047252655029
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5020812153816223
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.40352863073349
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.5068580508232117
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4622748792171478
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5270103216171265
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.47488123178482056
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46202075481414795
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5407655835151672
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4391500949859619
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4394972622394562
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4095925986766815
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4554976522922516
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5684233903884888
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.39163029193878174
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.39123839139938354
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4814830720424652
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.46751850843429565
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4518684148788452
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4859541058540344
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5092153549194336
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5032893419265747
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5074543952941895
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5185012221336365
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5100749135017395
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4252186119556427
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.5659600496292114
Calibrated prediction for GOOG: 0.6200000047683716
Raw prediction for HD: 0.48151254653930664
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.540215253829956
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5652952194213867
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.37500834465026855
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4767155945301056
Calibrated prediction for IEP: 0.46978840231895447
Raw prediction for INTC: 0.5355530381202698
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3802647888660431
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5206996202468872
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.41833236813545227
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5302788615226746
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.41414785385131836
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5770023465156555
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.479775071144104
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6447481513023376
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5477501749992371
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5015555024147034
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5340397357940674
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.481648713350296
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5049166083335876
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.33896389603614807
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3390054702758789
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4968297779560089
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5556168556213379
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5017920732498169
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5055790543556213
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43896588683128357
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4251597821712494
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.44735369086265564
Calibrated prediction for PM: 0.5158328413963318
Raw prediction for PPL: 0.487012654542923
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4488365948200226
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5299546122550964
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5775401592254639
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.45494377613067627
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5074700713157654
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5206732153892517
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.46705570816993713
Calibrated prediction for SO: 0.4141654372215271

Simulating Trading Days:  78%|███████▊  | 78/100 [05:44<00:28,  1.29s/it]

Raw prediction for SPLP: 0.3153555393218994
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.36914488673210144
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5250341892242432
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.46719059348106384
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.4851197898387909
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5535073280334473
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.27203312516212463
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3568708896636963
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4390691816806793
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4811740815639496
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4309794306755066
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5131241679191589
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.5007411241531372
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5168550610542297
Calibrated prediction for WFC: 0.4904371201992035
Raw prediction for WMT: 0.46880650520324707
Calibrated prediction for WMT: 0.48148149251937866
Raw prediction for XOM: 0.5023841261863708
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.488
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.896, kelly=0.094) with $2411.84
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.094, kelly=0.373) with $9553.63
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.448
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.945, kelly=0.123) with $3142.58
[PORT] Sector Financial: 10 candidates, avg score=0.470
[PORT] Sector Financial: selecting V (p=0.526, b=1.032, kelly=0.067) with $1728.49
[PORT] Sector Healthcare: 10 candidates, avg score=0.458
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.010, kelly=0.045) with $1160.22
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.993, kelly=0.251) with $6433.95
[PORT] Sector Services: 10 candidates, avg score=0.516
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.041, kelly=0.220) with $5630.12
[PORT] Sector Technology: 10 candidates, avg score=0.512
[PORT] Sector Technology: selecting GOOG (p=0.620, b=1.043, kelly=0.256) with $6551.70
[PORT] Sector Utilities: 10 candidates, avg score=0.481
[PORT] Sector Utilities: selecting AEP (p=0.526, b=0.909, kelly=0.005) with $133.16
Raw prediction for AAPL: 0.490970253944397
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5355276465415955
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.38371896743774414
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5300868153572083
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.42691847681999207
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4835472106933594
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5469763875007629
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4474649727344513
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5176459550857544
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5020975470542908
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.39847007393836975
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.508863627910614
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4614744186401367
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5417132377624512
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4805448353290558
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46146655082702637
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5391820669174194
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.44017496705055237
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4387045204639435
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.40460556745529175
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.46399620175361633
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5583388805389404
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.3948284685611725
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.3936227560043335
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48206230998039246
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.46617984771728516
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.45625928044319153
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4864446818828583
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5095040798187256
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5042241215705872
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.507430374622345
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5184078812599182
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5105425715446472
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.4100092351436615
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6164358854293823
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.47530966997146606
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5415807962417603
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5715975761413574
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.37342125177383423
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.47896838188171387
Calibrated prediction for IEP: 0.46978840231895447
Raw prediction for INTC: 0.5342223048210144
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3772527873516083
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5208330154418945
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4184513986110687
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5299139618873596
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4447228014469147
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5772032737731934
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4799387753009796
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.643385648727417
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5630785226821899
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.49277305603027344
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5422676801681519
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4802809953689575
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5062892436981201
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.33885785937309265
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3422781527042389
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4972214996814728
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5598841309547424
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5016677975654602
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5051748156547546
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43960773944854736
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.42897868156433105
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.45342543721199036
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.48741284012794495
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.44965529441833496
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.536766529083252
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5870222449302673
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.45386314392089844
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.508029043674469
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5205642580986023
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.456612229347229
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3152955174446106
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.37205401062965393
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5216323733329773
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.46974366903305054
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.47694283723831177
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5504797101020813
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.2740463614463806
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3645132780075073
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4434681534767151
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4910500943660736
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.401987224817276
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5215044021606445
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.49999725818634033
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5175267457962036
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4604416489601135
Calibrated prediction for WMT: 0.4189581871032715

Simulating Trading Days:  79%|███████▉  | 79/100 [05:45<00:26,  1.24s/it]

Raw prediction for XOM: 0.501916229724884
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.488
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.895, kelly=0.094) with $2395.73
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.089, kelly=0.371) with $9515.03
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.945, kelly=0.123) with $3142.89
[PORT] Sector Financial: 10 candidates, avg score=0.473
[PORT] Sector Financial: selecting V (p=0.526, b=1.033, kelly=0.068) with $1738.18
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.011, kelly=0.046) with $1169.26
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.994, kelly=0.251) with $6438.58
[PORT] Sector Services: 10 candidates, avg score=0.510
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.043, kelly=0.220) with $5644.97
[PORT] Sector Technology: 10 candidates, avg score=0.516
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.041, kelly=0.287) with $7348.19
[PORT] Sector Utilities: 10 candidates, avg score=0.481
[PORT] Sector Utilities: selecting AEP (p=0.526, b=0.907, kelly=0.004) with $108.80
Raw prediction for AAPL: 0.4901348054409027
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5360205769538879
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3843162953853607
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5266475677490234
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.42609745264053345
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4841162860393524
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.5814964771270752
Calibrated prediction for AMZN: 0.48571428656578064
Raw prediction for BA: 0.4476624131202698
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5177054405212402
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.501960813999176
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.39561063051223755
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.5058159828186035
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.45956453680992126
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5611562728881836
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.48294195532798767
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46087637543678284
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5384107828140259
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4384261667728424
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.43804335594177246
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.40939611196517944
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4724024534225464
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.542575478553772
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.3944145739078522
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.39769455790519714
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48240965604782104
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4682101309299469
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.46190232038497925
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.48687586188316345
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5099514126777649
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5051345825195312
Calibrated prediction for DUK: 0.489431768655777
Raw prediction for EXC: 0.5075172781944275
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5184137225151062
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.510857343673706
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.39753997325897217
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6512424349784851
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4686814546585083
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5421531796455383
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5816280245780945
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.37015631794929504
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.48071789741516113
Calibrated prediction for IEP: 0.46978840231895447
Raw prediction for INTC: 0.5316435694694519
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3776914179325104
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5207757353782654
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4187621772289276
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5299151539802551
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.46529096364974976
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5773460865020752
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4800635874271393
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6418598890304565
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5685328245162964
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.48723092675209045
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5491178035736084
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4773673713207245
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5077957510948181
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3400358259677887
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3411034941673279
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49759283661842346
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5555797219276428
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5014130473136902
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5066747069358826
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4392859637737274
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.43099910020828247
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.45762765407562256
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.48821911215782166
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4504912197589874
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5461117625236511
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5866891145706177
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4522867202758789
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5084490776062012
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.520592451095581
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4445171356201172
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.31182023882865906
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3692111074924469
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5262535214424133
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.4420018494129181
Calibrated prediction for TM: 0.3962264060974121

Simulating Trading Days:  80%|████████  | 80/100 [05:47<00:24,  1.22s/it]

Raw prediction for TOT: 0.4714982211589813
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5429521203041077
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.28042280673980713
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.3725481927394867
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4437812566757202
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4984841048717499
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3759159743785858
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5277730226516724
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.497339129447937
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5178762674331665
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.45385661721229553
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5022477507591248
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.026, kelly=0.202) with $5178.88
[PORT] Sector Conglomerates: 7 candidates, avg score=0.470
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.090, kelly=0.372) with $9536.19
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.944, kelly=0.122) with $3127.41
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.580, b=1.032, kelly=0.173) with $4439.93
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.011, kelly=0.046) with $1168.37
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.996, kelly=0.252) with $6463.95
[PORT] Sector Services: 10 candidates, avg score=0.502
[PORT] Sector Services: selecting PCLN (p=0.602, b=1.045, kelly=0.221) with $5676.06
[PORT] Sector Technology: 10 candidates, avg score=0.524
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.043, kelly=0.460) with $11795.75
[PORT] Sector Utilities: 10 candidates, avg score=0.483
[PORT] Sector Utilities: allocation $96.34 below minimum for AEP
Raw prediction for AAPL: 0.489439994096756
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5359687805175781
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3821775019168854
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5256912708282471
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4256356954574585
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48477989435195923
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6168642044067383
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.44817134737968445
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5176301598548889
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5018078088760376
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.3927047550678253
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.5008642673492432
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4577973484992981
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.572981059551239
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.4872095286846161
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4604601562023163
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5444155931472778
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4378589689731598
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.437383770942688
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.41754937171936035
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4851061999797821
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5293307304382324
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.3941688537597656
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4005737602710724
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.483030766248703
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4673401415348053
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4660334587097168
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.48711979389190674
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5099857449531555
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5061413049697876
Calibrated prediction for DUK: 0.5490944385528564
Raw prediction for EXC: 0.5076671242713928
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5184234380722046
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5109663605690002
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3866380751132965
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6789209842681885
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.46328598260879517
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5420178771018982
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5862889289855957
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3661874830722809
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4826951324939728
Calibrated prediction for IEP: 0.5
Raw prediction for INTC: 0.5287187695503235
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3805133104324341
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5202360153198242
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4202953279018402
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5297026038169861
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4778138995170593
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5774524807929993
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4801813066005707
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6409695744514465
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5723675489425659
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4888755679130554
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5544453263282776
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4739483594894409
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5099270343780518
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3418880105018616
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.34084293246269226
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4981592893600464
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5546486973762512
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5016341209411621
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5090458989143372
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43967875838279724
Calibrated prediction for PG: 0.4342016279697418
Raw prediction for PICO: 0.4311697781085968
Calibrated prediction for PICO: 0.41745099425315857
Raw prediction for PM: 0.46482986211776733
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.4896529018878937
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45114246010780334
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.554725170135498
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5784267783164978
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.45153915882110596
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5086188316345215
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5206892490386963
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4317774176597595
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3100931644439697
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.36751702427864075
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5299167633056641
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.43313291668891907
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.46386125683784485
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5417986512184143
Calibrated prediction for TSM: 0.5770066976547241

Simulating Trading Days:  81%|████████  | 81/100 [05:48<00:23,  1.23s/it]

Raw prediction for UL: 0.2942231595516205
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.38870203495025635
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.44206714630126953
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5046765804290771
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.35298848152160645
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5299188494682312
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.4970557391643524
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5183593034744263
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4480420649051666
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5025394558906555
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.027, kelly=0.202) with $5196.56
[PORT] Sector Conglomerates: 7 candidates, avg score=0.474
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.089, kelly=0.372) with $9551.76
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.946, kelly=0.123) with $3163.42
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.580, b=1.033, kelly=0.173) with $4453.99
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.009, kelly=0.045) with $1153.18
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.997, kelly=0.252) with $6487.50
[PORT] Sector Services: 10 candidates, avg score=0.521
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.052, kelly=0.372) with $9575.56
[PORT] Sector Technology: 10 candidates, avg score=0.524
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.044, kelly=0.460) with $11820.71
[PORT] Sector Utilities: 10 candidates, avg score=0.489
[PORT] Sector Utilities: selecting DUK (p=0.549, b=0.902, kelly=0.049) with $1261.83
Raw prediction for AAPL: 0.4887883961200714
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.535714328289032
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.37955060601234436
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5247054100036621
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4256666302680969
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4853573143482208
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6498801112174988
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.44896674156188965
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5175338983535767
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5017552375793457
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.39544886350631714
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.49399226903915405
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.45635786652565
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5791411399841309
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.4925023317337036
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46003371477127075
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5494841933250427
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.43733006715774536
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4366219639778137
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4258410930633545
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4923330545425415
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5188368558883667
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.3966597616672516
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.40320631861686707
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48374855518341064
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4652458727359772
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.470693439245224
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4873604476451874
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5097898244857788
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.505567193031311
Calibrated prediction for DUK: 0.5150701403617859
Raw prediction for EXC: 0.5077074766159058
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5184706449508667
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5108832120895386
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.37393200397491455
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7007949352264404
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4592500329017639
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5416182279586792
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5902301073074341
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3611583411693573
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.48944541811943054
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5258297920227051
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.38224130868911743
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5194286108016968
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.42183563113212585
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5291378498077393
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.48035916686058044
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.577592134475708
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4801570177078247
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6418891549110413
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.574436366558075
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4907267093658447
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5583109855651855
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.47122299671173096
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5109984874725342
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.34056153893470764
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3404448628425598
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49831825494766235
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5512997508049011
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5015344619750977
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5073292851448059
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4390040934085846
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4330061078071594
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.47035762667655945
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.49072107672691345
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4518944025039673
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5624379515647888
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5648877024650574
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4520280957221985
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5086851716041565
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5207727551460266
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.42019110918045044
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3108470141887665
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3666565716266632
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5318467617034912
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.42214223742485046
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.4580446779727936
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5396209359169006
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.31348544359207153
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.406032532453537
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.43686872720718384
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.508060097694397
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.3380553126335144
Calibrated prediction for UTX: 0.3193990886211395

Simulating Trading Days:  82%|████████▏ | 82/100 [05:49<00:21,  1.22s/it]

Raw prediction for V: 0.5318818092346191
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.4962511658668518
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5187293291091919
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4431271553039551
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5021971464157104
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.026, kelly=0.202) with $5187.88
[PORT] Sector Conglomerates: 7 candidates, avg score=0.477
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.088, kelly=0.371) with $9554.53
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.949, kelly=0.124) with $3196.05
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.580, b=1.031, kelly=0.173) with $4442.70
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.009, kelly=0.045) with $1148.47
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.995, kelly=0.252) with $6473.30
[PORT] Sector Services: 10 candidates, avg score=0.521
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.049, kelly=0.372) with $9568.51
[PORT] Sector Technology: 10 candidates, avg score=0.543
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.042, kelly=0.459) with $11823.63
[PORT] Sector Utilities: 10 candidates, avg score=0.485
[PORT] Sector Utilities: allocation $98.87 below minimum for AEP
Raw prediction for AAPL: 0.48852765560150146
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.535354733467102
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.37730225920677185
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.524581789970398
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.425650030374527
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48597392439842224
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6700615286827087
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.44990113377571106
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5174040198326111
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5017279386520386
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.40343931317329407
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.48896241188049316
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.45785465836524963
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5800457000732422
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.4991075396537781
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4597606956958771
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5515784621238708
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.43820375204086304
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4358312487602234
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.43531811237335205
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.49755311012268066
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.5111215114593506
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.401998370885849
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4054824411869049
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48470667004585266
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4636271297931671
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4745129644870758
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4875437617301941
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5089873671531677
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5038338899612427
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.507930338382721
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5184133648872375
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5106803178787231
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.35901185870170593
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7119576334953308
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4554237127304077
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5413822531700134
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5929561853408813
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.355188250541687
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.49597227573394775
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5228644609451294
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3837328255176544
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.51849764585495
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.423639178276062
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5283547043800354
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.47817277908325195
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.577704668045044
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47970300912857056
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6443226337432861
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5750997066497803
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.49465227127075195
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.559572696685791
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4716751277446747
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5127817392349243
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3389080762863159
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.339616060256958
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4985054135322571
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5451267957687378
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5012795925140381
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5044147968292236
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43772101402282715
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4351426064968109
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.47034358978271484
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.4918636679649353
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45252206921577454
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5682126879692078
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5532077550888062
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.4559077024459839
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5090947151184082
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5207266211509705
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.41453662514686584
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3133739233016968
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3652127981185913
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:  83%|████████▎ | 83/100 [05:50<00:20,  1.20s/it]

Raw prediction for T: 0.5322638154029846
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.41091999411582947
Calibrated prediction for TM: 0.38565802574157715
Raw prediction for TOT: 0.4519467055797577
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5360836982727051
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3345510959625244
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4221908152103424
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4300173819065094
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5096737146377563
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.33817511796951294
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5349032878875732
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.49624818563461304
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.52029949426651
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.43936872482299805
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.501883864402771
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.026, kelly=0.202) with $5190.93
[PORT] Sector Conglomerates: 7 candidates, avg score=0.477
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.086, kelly=0.371) with $9545.15
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.448
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.949, kelly=0.124) with $3197.52
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.580, b=1.030, kelly=0.172) with $4437.22
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.011, kelly=0.045) with $1171.39
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.997, kelly=0.252) with $6497.90
[PORT] Sector Services: 10 candidates, avg score=0.521
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.048, kelly=0.371) with $9563.54
[PORT] Sector Technology: 10 candidates, avg score=0.543
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.040, kelly=0.459) with $11817.56
[PORT] Sector Utilities: 10 candidates, avg score=0.481
[PORT] Sector Utilities: allocation $96.28 below minimum for AEP
Raw prediction for AAPL: 0.4885513186454773
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.534980297088623
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.37503302097320557
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5233272910118103
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.425595223903656
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4865184724330902
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6790986657142639
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4506935775279999
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5172863006591797
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5013764500617981
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.41185644268989563
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.4840628504753113
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4615288972854614
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5837609171867371
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.5014251470565796
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.45949500799179077
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5523541569709778
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.43704259395599365
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.43507057428359985
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.44276267290115356
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.49540138244628906
Calibrated prediction for CHL: 0.6377968788146973
Raw prediction for CHTR: 0.509054958820343
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.41086751222610474
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4114247262477875
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48526719212532043
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.46549126505851746
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4788791239261627
Calibrated prediction for D: 0.4838709533214569
Raw prediction for DHR: 0.4876663386821747
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5077021718025208
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5013523101806641
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5080664753913879
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5183043479919434
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5104249119758606
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3488636612892151
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7158858180046082
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4524163603782654
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5417289137840271
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5959768891334534
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3489016890525818
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4993296265602112
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5199261903762817
Calibrated prediction for INTC: 0.5389524102210999
Raw prediction for JNJ: 0.38500332832336426
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5173540115356445
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.42552679777145386
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5281509160995483
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.47297239303588867
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.577815592288971
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47869712114334106
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6462669968605042
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5748723149299622
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.49827468395233154
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5556473731994629
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.47303810715675354
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5138034820556641
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3364109992980957
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.33901530504226685
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4980415105819702
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.540300726890564
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5010625720024109
Calibrated prediction for PEP: 0.5075154304504395
Raw prediction for PFE: 0.5017456412315369
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.436111718416214
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4379114806652069
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4640030860900879
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.49246519804000854
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.453482985496521
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.575027346611023
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5448521375656128
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.46765363216400146
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5100002288818359
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5205626487731934
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4097183048725128
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3124634325504303
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3625994324684143
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5322698354721069
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.4097578227519989
Calibrated prediction for TM: 0.38108354806900024
Raw prediction for TOT: 0.4493502974510193
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5320602059364319
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.34964385628700256
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.43064141273498535
Calibrated prediction for UN: 0.35549506545066833

Simulating Trading Days:  84%|████████▍ | 84/100 [05:51<00:19,  1.21s/it]

Raw prediction for UNH: 0.42371320724487305
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5100866556167603
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.35668283700942993
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5391823649406433
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.49736419320106506
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5210820436477661
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.43478572368621826
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5021299719810486
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.027, kelly=0.202) with $5192.23
[PORT] Sector Conglomerates: 7 candidates, avg score=0.477
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.086, kelly=0.370) with $9520.19
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.448
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.948, kelly=0.124) with $3185.06
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.580, b=1.032, kelly=0.173) with $4448.66
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.013, kelly=0.046) with $1194.64
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.998, kelly=0.253) with $6492.24
[PORT] Sector Services: 10 candidates, avg score=0.521
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.050, kelly=0.372) with $9560.82
[PORT] Sector Technology: 10 candidates, avg score=0.543
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.042, kelly=0.459) with $11806.29
[PORT] Sector Utilities: 10 candidates, avg score=0.481
[PORT] Sector Utilities: selecting AEP (p=0.526, b=0.909, kelly=0.005) with $128.66
Raw prediction for AAPL: 0.48877644538879395
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.534878134727478
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3723260760307312
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5218504071235657
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4255852997303009
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48697060346603394
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6870877742767334
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4514024257659912
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5172526240348816
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5008315443992615
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.41765281558036804
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.4814358651638031
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4654463827610016
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5832948684692383
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.4978925883769989
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4594442844390869
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5551444888114929
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.4340292811393738
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4345218539237976
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4520948529243469
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.48566365242004395
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5077517032623291
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4191042482852936
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4185959994792938
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4858715832233429
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4667495787143707
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4845310151576996
Calibrated prediction for D: 0.5160287022590637
Raw prediction for DHR: 0.4877600073814392
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.506311297416687
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.498522013425827
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5080620646476746
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5182160139083862
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5101380348205566
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.34182706475257874
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7182648181915283
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.44920986890792847
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5425394177436829
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5985482931137085
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.34393060207366943
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4975565969944
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5174485445022583
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.38717949390411377
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5163838863372803
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.42716073989868164
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5281542539596558
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.46662431955337524
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5780194401741028
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4776133596897125
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6476848125457764
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5752036571502686
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.501436710357666
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5514369010925293
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4747486412525177
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5149182677268982
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3351230323314667
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.33947861194610596
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4974599778652191
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5395175814628601
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5009147524833679
Calibrated prediction for PEP: 0.5046992301940918
Raw prediction for PFE: 0.4995496869087219
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.435026079416275
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.44226768612861633
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.45594948530197144
Calibrated prediction for PM: 0.5285714268684387
Raw prediction for PPL: 0.4933428168296814
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4547209143638611
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5797250866889954
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5440212488174438
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.48507654666900635
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5106003284454346
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5203235149383545
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4045541286468506
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3108322322368622
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.36380454897880554
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.529856264591217
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.41741934418678284
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.44871968030929565
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5294017791748047
Calibrated prediction for TSM: 0.5770066976547241

Simulating Trading Days:  85%|████████▌ | 85/100 [05:53<00:18,  1.23s/it]

Raw prediction for UL: 0.3560081124305725
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.43414437770843506
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.41913464665412903
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5079689621925354
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.38901299238204956
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5436716675758362
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5021166205406189
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5221404433250427
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4301067590713501
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5023766160011292
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.027, kelly=0.202) with $5165.03
[PORT] Sector Conglomerates: 7 candidates, avg score=0.477
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.087, kelly=0.371) with $9477.46
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.950, kelly=0.125) with $3193.58
[PORT] Sector Financial: 10 candidates, avg score=0.483
[PORT] Sector Financial: selecting V (p=0.580, b=1.034, kelly=0.174) with $4440.87
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.014, kelly=0.047) with $1206.46
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.996, kelly=0.252) with $6436.38
[PORT] Sector Services: 10 candidates, avg score=0.521
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.051, kelly=0.372) with $9514.25
[PORT] Sector Technology: 10 candidates, avg score=0.521
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.044, kelly=0.460) with $11749.71
[PORT] Sector Utilities: 10 candidates, avg score=0.484
[PORT] Sector Utilities: selecting AEP (p=0.526, b=0.910, kelly=0.006) with $140.83
Raw prediction for AAPL: 0.48906731605529785
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5351201891899109
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.36852458119392395
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5222336649894714
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.42563754320144653
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48739534616470337
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6911174654960632
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.452111154794693
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5171104669570923
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5002961158752441
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4222857356071472
Calibrated prediction for BBL: 0.40740740299224854
Raw prediction for BCH: 0.4800466001033783
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4687711000442505
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5763639211654663
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.49160873889923096
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.459564745426178
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5598657727241516
Calibrated prediction for BUD: 0.43589743971824646
Raw prediction for C: 0.43058353662490845
Calibrated prediction for C: 0.42166969180107117
Raw prediction for CAT: 0.4339224696159363
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.45758652687072754
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.4703243374824524
Calibrated prediction for CHL: 0.4482758641242981
Raw prediction for CHTR: 0.5153878331184387
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4256279170513153
Calibrated prediction for CMCSA: 0.44146907329559326
Raw prediction for CODI: 0.43013569712638855
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48664960265159607
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4665704369544983
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4924882650375366
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48790204524993896
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5045126080513
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4955688416957855
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5081539154052734
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5181415677070618
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5099083185195923
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3366563022136688
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7238843441009521
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4512397348880768
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5429275631904602
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5988810062408447
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3395066559314728
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4931199848651886
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5158593654632568
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3872741162776947
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5157142281532288
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.42884019017219543
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5291920304298401
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4545641243457794
Calibrated prediction for MA: 0.4821428656578064
Raw prediction for MCD: 0.5788681507110596
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47665512561798096
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6486616730690002
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5754722356796265
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5044339895248413
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5469357967376709
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4743923544883728
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5164670348167419
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3372384011745453
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3411369025707245
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49738553166389465
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5807962417602539
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.5008615851402283
Calibrated prediction for PEP: 0.5030356049537659
Raw prediction for PFE: 0.496049165725708
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43418028950691223
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4455919563770294
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.44697999954223633
Calibrated prediction for PM: 0.5116164684295654
Raw prediction for PPL: 0.4948813021183014
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45630937814712524
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5798189043998718
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.550105631351471
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5042717456817627
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5110437870025635
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5200710892677307
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4026382267475128
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3045640289783478
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3678855299949646
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5292810797691345
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.4333520531654358
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.4461900591850281
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5285405516624451
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.35346242785453796
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4291544258594513
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.41636189818382263
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5106443762779236
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4219229221343994
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.545529842376709
Calibrated prediction for V: 0.5799999833106995

Simulating Trading Days:  86%|████████▌ | 86/100 [05:54<00:17,  1.21s/it]

Raw prediction for VZ: 0.5081594586372375
Calibrated prediction for VZ: 0.5
Raw prediction for WFC: 0.5227174162864685
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.42681315541267395
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5025668144226074
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.495
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.025, kelly=0.201) with $5160.27
[PORT] Sector Conglomerates: 7 candidates, avg score=0.489
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.088, kelly=0.371) with $9502.36
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.447
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.950, kelly=0.125) with $3198.16
[PORT] Sector Financial: 10 candidates, avg score=0.477
[PORT] Sector Financial: selecting V (p=0.580, b=1.032, kelly=0.173) with $4433.72
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.015, kelly=0.048) with $1217.83
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.998, kelly=0.253) with $6470.37
[PORT] Sector Services: 10 candidates, avg score=0.524
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.048, kelly=0.371) with $9512.44
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.042, kelly=0.459) with $11762.63
[PORT] Sector Utilities: 10 candidates, avg score=0.487
[PORT] Sector Utilities: selecting D (p=0.537, b=0.889, kelly=0.017) with $428.11
Raw prediction for AAPL: 0.48938632011413574
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5356313586235046
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3686898946762085
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5222204923629761
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4261030852794647
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48806026577949524
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6997489929199219
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4530974328517914
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5170725584030151
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.500159740447998
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4312451481819153
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4791033864021301
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4727054238319397
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5613303184509277
Calibrated prediction for BP: 0.5957446694374084
Raw prediction for BRK-A: 0.48016101121902466
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46005430817604065
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.568901002407074
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42896297574043274
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.43373793363571167
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.47060248255729675
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.45374515652656555
Calibrated prediction for CHL: 0.4285714328289032
Raw prediction for CHTR: 0.5201545357704163
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.42457693815231323
Calibrated prediction for CMCSA: 0.4343022406101227
Raw prediction for CODI: 0.43936315178871155
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48796600103378296
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4675634503364563
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.4993949234485626
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4880496859550476
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5027772188186646
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4944666028022766
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5081419944763184
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5182182788848877
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5095660090446472
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.33456993103027344
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7391154170036316
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.45680931210517883
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5437832474708557
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5991535782814026
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.33852702379226685
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4877283573150635
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.515579879283905
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.39482080936431885
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5155901312828064
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.430542528629303
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5299770832061768
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4472365379333496
Calibrated prediction for MA: 0.47062402963638306
Raw prediction for MCD: 0.5793108940124512
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4766375422477722
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6488348245620728
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5766769647598267
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.506377637386322
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5395100712776184
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.47486764192581177
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5175172686576843
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3442875146865845
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3494819700717926
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49704331159591675
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6136651635169983
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5009540915489197
Calibrated prediction for PEP: 0.5059301257133484
Raw prediction for PFE: 0.49685561656951904
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43477752804756165
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4482221305370331
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4434491991996765
Calibrated prediction for PM: 0.5
Raw prediction for PPL: 0.4960583746433258
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4579314589500427
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5751156210899353
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5560494661331177
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5221810936927795
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5113446116447449
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5201519727706909
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.3995594382286072
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.2999156713485718
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.37549230456352234
Calibrated prediction for SRE: 0.4285714328289032

Simulating Trading Days:  87%|████████▋ | 87/100 [05:55<00:15,  1.20s/it]

Raw prediction for T: 0.534454345703125
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.467979371547699
Calibrated prediction for TM: 0.3962264060974121
Raw prediction for TOT: 0.44636741280555725
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5351117253303528
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3519444763660431
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4305574595928192
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4208175837993622
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5089238882064819
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.45143604278564453
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5539515614509583
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5153725147247314
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5237166285514832
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4240417778491974
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5024721622467041
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.520
[PORT] Sector Basic Matierials: selecting BP (p=0.596, b=1.025, kelly=0.201) with $5168.82
[PORT] Sector Conglomerates: 7 candidates, avg score=0.489
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.085, kelly=0.370) with $9516.06
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.451
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.950, kelly=0.125) with $3210.38
[PORT] Sector Financial: 10 candidates, avg score=0.475
[PORT] Sector Financial: selecting V (p=0.580, b=1.031, kelly=0.173) with $4439.79
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.013, kelly=0.047) with $1201.12
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.000, kelly=0.253) with $6510.45
[PORT] Sector Services: 10 candidates, avg score=0.528
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.048, kelly=0.371) with $9540.87
[PORT] Sector Technology: 10 candidates, avg score=0.528
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.041, kelly=0.459) with $11796.23
[PORT] Sector Utilities: 10 candidates, avg score=0.487
[PORT] Sector Utilities: selecting D (p=0.537, b=0.890, kelly=0.017) with $440.94
Raw prediction for AAPL: 0.48941463232040405
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5361757278442383
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.36801186203956604
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5238670706748962
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.427094966173172
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4887257516384125
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.704932451248169
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4539739489555359
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5171037316322327
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.500226616859436
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4408954977989197
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.47724777460098267
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.47686681151390076
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5364145040512085
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4671533405780792
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4607769250869751
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.572319507598877
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42766129970550537
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4335058033466339
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.48239704966545105
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.42717796564102173
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5232456922531128
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.41658613085746765
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4360542297363281
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48894596099853516
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.47063708305358887
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5075953006744385
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48798519372940063
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.501426100730896
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.4951637089252472
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5081064701080322
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.518187403678894
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5094373822212219
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3358839750289917
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7423419952392578
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4618892967700958
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5442947149276733
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5981670022010803
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3393893539905548
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4858786165714264
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5146313309669495
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.3983573615550995
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5160589814186096
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.43237993121147156
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5305302143096924
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.43728965520858765
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5792151689529419
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4765079617500305
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6486544609069824
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5779533982276917
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5076440572738647
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5327470302581787
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.47716784477233887
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5195721387863159
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.35028573870658875
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.35403233766555786
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49701398611068726
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6261813044548035
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5008412003517151
Calibrated prediction for PEP: 0.5023977756500244
Raw prediction for PFE: 0.49682947993278503
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43505433201789856
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.45197615027427673
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.43953895568847656
Calibrated prediction for PM: 0.5
Raw prediction for PPL: 0.49728769063949585
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45946037769317627
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.564897358417511
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5596545934677124
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5380691885948181
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5114446878433228
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5202065110206604
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.40034613013267517
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.2980048954486847
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3839681148529053
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5361593961715698
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5051126480102539
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.4433746337890625
Calibrated prediction for TOT: 0.5454545617103577
Raw prediction for TSM: 0.5371581315994263
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3522178530693054
Calibrated prediction for UL: 0.3333333432674408

Simulating Trading Days:  88%|████████▊ | 88/100 [05:56<00:14,  1.21s/it]

Raw prediction for UN: 0.43431583046913147
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.42921575903892517
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.5036571621894836
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.46647465229034424
Calibrated prediction for UTX: 0.375
Raw prediction for V: 0.5619943141937256
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5206814408302307
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.524670422077179
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4178875684738159
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5027004480361938
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.514
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.899, kelly=0.096) with $2454.84
[PORT] Sector Conglomerates: 7 candidates, avg score=0.489
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.084, kelly=0.370) with $9487.18
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.459
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.951, kelly=0.125) with $3207.70
[PORT] Sector Financial: 10 candidates, avg score=0.471
[PORT] Sector Financial: selecting V (p=0.580, b=1.034, kelly=0.174) with $4452.96
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.012, kelly=0.046) with $1180.76
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.495
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.000, kelly=0.253) with $6498.57
[PORT] Sector Services: 10 candidates, avg score=0.526
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.048, kelly=0.372) with $9528.00
[PORT] Sector Technology: 10 candidates, avg score=0.518
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.041, kelly=0.459) with $11773.55
[PORT] Sector Utilities: 10 candidates, avg score=0.487
[PORT] Sector Utilities: selecting D (p=0.537, b=0.889, kelly=0.017) with $425.92
Raw prediction for AAPL: 0.4891180992126465
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5370103716850281
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3669509291648865
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5252103805541992
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4276312589645386
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48907023668289185
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6997998952865601
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4543917179107666
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5170294642448425
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5004098415374756
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.44984668493270874
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4744829535484314
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.48085689544677734
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4972911775112152
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.45528578758239746
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46126946806907654
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5735588669776917
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42633628845214844
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.43303775787353516
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.4854946732521057
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.40573182702064514
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5262810587882996
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4071349501609802
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4265154302120209
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4891815185546875
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4712364375591278
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5160915851593018
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4877622723579407
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.500289797782898
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.49827879667282104
Calibrated prediction for DUK: 0.4736842215061188
Raw prediction for EXC: 0.5079018473625183
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5181611776351929
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5094432234764099
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3395088016986847
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7297847270965576
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4673230051994324
Calibrated prediction for HD: 0.44056737422943115
Raw prediction for HON: 0.5441873073577881
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5953710675239563
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3400972783565521
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.48635971546173096
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5133508443832397
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4022968113422394
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5168296098709106
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4337334632873535
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5314767956733704
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4224618077278137
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5786186456680298
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47624456882476807
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6487985253334045
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5787407755851746
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.506125807762146
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5278082489967346
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4778148829936981
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5194935202598572
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.35153043270111084
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3553398847579956
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49658846855163574
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6249855756759644
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5007520318031311
Calibrated prediction for PEP: 0.499607652425766
Raw prediction for PFE: 0.49521854519844055
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43468135595321655
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4532339870929718
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.43499594926834106
Calibrated prediction for PM: 0.5
Raw prediction for PPL: 0.4979100823402405
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4611303210258484
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5482549667358398
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5594831705093384
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.546348512172699
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5110914707183838
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5202618837356567
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.40005096793174744
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.29928433895111084
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3911187946796417
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5372850894927979
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5374906063079834
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.4355386197566986
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5366676449775696
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3584284484386444
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.44177690148353577
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.43925678730010986
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.49610665440559387
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4589833915233612
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5623909831047058
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5237964987754822
Calibrated prediction for VZ: 0.556209146976471

Simulating Trading Days:  89%|████████▉ | 89/100 [05:58<00:13,  1.20s/it]

Raw prediction for WFC: 0.5249257683753967
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.4064010977745056
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5029440522193909
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.494
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.901, kelly=0.096) with $2471.77
[PORT] Sector Conglomerates: 7 candidates, avg score=0.489
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.084, kelly=0.370) with $9484.19
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.459
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.950, kelly=0.125) with $3206.46
[PORT] Sector Financial: 10 candidates, avg score=0.471
[PORT] Sector Financial: selecting V (p=0.580, b=1.033, kelly=0.173) with $4447.90
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.010, kelly=0.045) with $1157.78
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.002, kelly=0.254) with $6518.13
[PORT] Sector Services: 10 candidates, avg score=0.526
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.051, kelly=0.372) with $9544.97
[PORT] Sector Technology: 10 candidates, avg score=0.522
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.043, kelly=0.460) with $11786.74
[PORT] Sector Utilities: 10 candidates, avg score=0.487
[PORT] Sector Utilities: selecting D (p=0.537, b=0.888, kelly=0.016) with $408.13
Raw prediction for AAPL: 0.4886486530303955
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.537752091884613
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.36756300926208496
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.526428759098053
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4284367859363556
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.489082396030426
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6927043199539185
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4544861912727356
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5169041752815247
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5006908178329468
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4580230116844177
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4678495526313782
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4863506555557251
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.4595576524734497
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4433993399143219
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4615756869316101
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5735557079315186
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42659297585487366
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.4328010380268097
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.48957034945487976
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.39246609807014465
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5328553318977356
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4006194770336151
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4165051281452179
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4888322055339813
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.47463855147361755
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5226247310638428
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4874112010002136
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.4993813633918762
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5060061812400818
Calibrated prediction for DUK: 0.5410864353179932
Raw prediction for EXC: 0.5076707601547241
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5181767344474792
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5092462301254272
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3460853099822998
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.7093700170516968
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4766823351383209
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5441942811012268
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5942331552505493
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.34040895104408264
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4889196753501892
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5132212042808533
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.40737274289131165
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5173296332359314
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4339348077774048
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5325565338134766
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.4072815179824829
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5780053734779358
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4756508469581604
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6489397287368774
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5780311822891235
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5049125552177429
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.521981418132782
Calibrated prediction for MSFT: 0.529411792755127
Raw prediction for NEE: 0.4769671857357025
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5198984146118164
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.35427534580230713
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3571104109287262
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4964141547679901
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6206533312797546
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5007955431938171
Calibrated prediction for PEP: 0.5009691119194031
Raw prediction for PFE: 0.4951065480709076
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4338648319244385
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4534192383289337
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4212695062160492
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4982389509677887
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4628032147884369
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.5301865935325623
Calibrated prediction for RDS-B: 0.571814239025116
Raw prediction for REX: 0.5574937462806702
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.55108243227005
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5106011629104614
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5203295350074768
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.39954686164855957
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.2981467843055725
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3975818455219269
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.539592444896698
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5618041753768921
Calibrated prediction for TM: 0.4821428656578064

Simulating Trading Days:  90%|█████████ | 90/100 [05:59<00:11,  1.19s/it]

Raw prediction for TOT: 0.42559701204299927
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5367695093154907
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3608262836933136
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.44339361786842346
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4463532567024231
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4892675578594208
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.44814079999923706
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5571823120117188
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5246792435646057
Calibrated prediction for VZ: 0.556209146976471
Raw prediction for WFC: 0.5248979926109314
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.39371180534362793
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5029707551002502
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.499
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.572, b=0.902, kelly=0.097) with $2464.83
[PORT] Sector Conglomerates: 7 candidates, avg score=0.477
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.086, kelly=0.370) with $9420.27
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.949, kelly=0.124) with $3163.82
[PORT] Sector Financial: 10 candidates, avg score=0.471
[PORT] Sector Financial: selecting V (p=0.580, b=1.033, kelly=0.173) with $4405.19
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.010, kelly=0.045) with $1153.90
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=1.001, kelly=0.254) with $6454.75
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.053, kelly=0.373) with $9477.99
[PORT] Sector Technology: 10 candidates, avg score=0.522
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.042, kelly=0.459) with $11682.21
[PORT] Sector Utilities: 10 candidates, avg score=0.493
[PORT] Sector Utilities: selecting DUK (p=0.541, b=0.905, kelly=0.034) with $858.48
Raw prediction for AAPL: 0.48817360401153564
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5383495688438416
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3683869540691376
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5276168584823608
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4296530485153198
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48865729570388794
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6833038330078125
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45427629351615906
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5168699622154236
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5010294914245605
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.46477484703063965
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.46207818388938904
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.49462369084358215
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.4397295415401459
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4339929521083832
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46161946654319763
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5724228024482727
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.42862468957901
Calibrated prediction for C: 0.4187776744365692
Raw prediction for CAT: 0.43252986669540405
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.48979830741882324
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.3806474506855011
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5378174185752869
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.39948469400405884
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.412638783454895
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4880400002002716
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.47719401121139526
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5264027714729309
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48674476146698
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.4989350438117981
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5152656435966492
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5074702501296997
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5181998610496521
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5090245008468628
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.35415545105934143
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6762499213218689
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4816713333129883
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5438694357872009
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5954385995864868
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.33976519107818604
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4928721487522125
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5134009122848511
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.4105604887008667
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5177632570266724
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.43221738934516907
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5337626338005066
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3932138979434967
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5772373676300049
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47509241104125977
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6490572690963745
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5790229439735413
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5036473274230957
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5158703327178955
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.4733577370643616
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5225876569747925
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3560110926628113
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.35689079761505127
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4963783323764801
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.612879753112793
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5008956789970398
Calibrated prediction for PEP: 0.5041024088859558
Raw prediction for PFE: 0.49451765418052673
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43313515186309814
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4545024335384369
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4059498608112335
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4986911714076996
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46484655141830444
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.511879563331604
Calibrated prediction for RDS-B: 0.5675675868988037
Raw prediction for REX: 0.5523400902748108
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5533719658851624
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.510897696018219
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.520237147808075
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.39808544516563416
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.2951951324939728
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.40048110485076904
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5437284708023071
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5797491073608398
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.42043250799179077
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5371699333190918
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.359244167804718
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4397352635860443
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4516247510910034
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4806043207645416
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.43349623680114746
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5481129884719849
Calibrated prediction for V: 0.5799999833106995

Simulating Trading Days:  91%|█████████ | 91/100 [06:00<00:10,  1.19s/it]

Raw prediction for VZ: 0.5172579288482666
Calibrated prediction for VZ: 0.52173912525177
Raw prediction for WFC: 0.5244057774543762
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.38235539197921753
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5035055875778198
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.499
[PORT] Sector Basic Matierials: selecting RDS-B (p=0.568, b=0.903, kelly=0.089) with $2261.48
[PORT] Sector Conglomerates: 7 candidates, avg score=0.477
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.081, kelly=0.369) with $9407.19
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.994, kelly=0.149) with $3796.39
[PORT] Sector Financial: 10 candidates, avg score=0.471
[PORT] Sector Financial: selecting V (p=0.580, b=1.032, kelly=0.173) with $4408.58
[PORT] Sector Healthcare: 10 candidates, avg score=0.460
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.011, kelly=0.046) with $1164.96
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.999, kelly=0.253) with $6449.92
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.051, kelly=0.372) with $9489.86
[PORT] Sector Technology: 10 candidates, avg score=0.514
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.040, kelly=0.459) with $11696.06
[PORT] Sector Utilities: 10 candidates, avg score=0.495
[PORT] Sector Utilities: selecting DUK (p=0.562, b=0.905, kelly=0.079) with $2021.30
Raw prediction for AAPL: 0.48774299025535583
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5384902358055115
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.37091755867004395
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5296260118484497
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4309752881526947
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4882766306400299
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6742619872093201
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45427143573760986
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5168394446372986
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5014989972114563
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.469022661447525
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4573596119880676
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4981112480163574
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.4552873373031616
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.42789095640182495
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4618643820285797
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5723750591278076
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.43186214566230774
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4329174757003784
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.49653297662734985
Calibrated prediction for CELG: 0.5262482166290283
Raw prediction for CHL: 0.37775754928588867
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5483176112174988
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.40764451026916504
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4097713530063629
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48788630962371826
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.47973161935806274
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5276262760162354
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48587194085121155
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.49879637360572815
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5247782468795776
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5074970126152039
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5184292793273926
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5087647438049316
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3643162250518799
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6605649590492249
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4870367646217346
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5443171858787537
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5941793918609619
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3403540849685669
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.4976721704006195
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5148641467094421
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.41513147950172424
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.518348217010498
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.43031075596809387
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5341383814811707
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.38329315185546875
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5772807598114014
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4749875068664551
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6483321785926819
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5807467699050903
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5063554048538208
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5105491876602173
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.4744454324245453
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5249500274658203
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3606018126010895
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.36080440878868103
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49687445163726807
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6172463893890381
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5008814930915833
Calibrated prediction for PEP: 0.5036585330963135
Raw prediction for PFE: 0.49899357557296753
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4330390989780426
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.45618966221809387
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.39390647411346436
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4992224872112274
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46715015172958374
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4944225251674652
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5388979911804199
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5546987056732178
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5117028951644897
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.520175039768219
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.40431076288223267
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.30002570152282715
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.4022383391857147
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.552215039730072
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5962933301925659
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.4126650094985962
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5431951284408569
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3547106683254242
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.43706682324409485
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.45788314938545227
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4734900891780853
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4389684498310089
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5404648780822754
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.5038098096847534
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5237355828285217
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.3750295341014862
Calibrated prediction for WMT: 0.4189581871032715

Simulating Trading Days:  92%|█████████▏| 92/100 [06:01<00:09,  1.19s/it]

Raw prediction for XOM: 0.5040138959884644
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.496
[PORT] Sector Basic Matierials: selecting BHP (p=0.549, b=0.940, kelly=0.069) with $1746.04
[PORT] Sector Conglomerates: 7 candidates, avg score=0.448
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.941, kelly=0.222) with $5656.17
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.992, kelly=0.148) with $3772.33
[PORT] Sector Financial: 10 candidates, avg score=0.478
[PORT] Sector Financial: selecting V (p=0.580, b=1.031, kelly=0.172) with $4387.49
[PORT] Sector Healthcare: 10 candidates, avg score=0.468
[PORT] Sector Healthcare: selecting CELG (p=0.526, b=1.006, kelly=0.056) with $1413.45
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.998, kelly=0.253) with $6432.18
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.053, kelly=0.373) with $9490.34
[PORT] Sector Technology: 10 candidates, avg score=0.505
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.043, kelly=0.460) with $11692.66
[PORT] Sector Utilities: 10 candidates, avg score=0.495
[PORT] Sector Utilities: selecting DUK (p=0.562, b=0.905, kelly=0.079) with $2012.84
Raw prediction for AAPL: 0.487375408411026
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5380238890647888
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.37208470702171326
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5299900770187378
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.432129830121994
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4881356358528137
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6682537198066711
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45429086685180664
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5170060992240906
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.501975417137146
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4716852903366089
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4510660171508789
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.499108225107193
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.4876018166542053
Calibrated prediction for BP: 0.44897958636283875
Raw prediction for BRK-A: 0.4223249852657318
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46185624599456787
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5720438957214355
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4340704679489136
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.43348851799964905
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5044398903846741
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.37737226486206055
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.557774007320404
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.4200665354728699
Calibrated prediction for CMCSA: 0.4105546772480011
Raw prediction for CODI: 0.4078417420387268
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48826536536216736
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.48344266414642334
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5258959531784058
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48502296209335327
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.49879756569862366
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5366750359535217
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5074270963668823
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5185075998306274
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5088679790496826
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.37326428294181824
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6540351510047913
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4900827407836914
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5445456504821777
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.590801477432251
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.34090352058410645
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5035933256149292
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5166255235671997
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.41385722160339355
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5190500617027283
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4297339618206024
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5344502329826355
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.37587955594062805
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5769063234329224
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47527459263801575
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6464735865592957
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5822758078575134
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5123798251152039
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.5072696805000305
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.47676923871040344
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5260664820671082
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.36626729369163513
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3634091317653656
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49688127636909485
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6164857149124146
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5006446838378906
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5052695274353027
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4329931437969208
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.45496508479118347
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.3891391158103943
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4992849826812744
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4691266119480133
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.48104438185691833
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5254116654396057
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5555969476699829
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5126138925552368
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5200091600418091
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4096636176109314
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.31516844034194946
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.4028078019618988
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5621322393417358
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6109801530838013
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.40689486265182495
Calibrated prediction for TOT: 0.4333333373069763
Raw prediction for TSM: 0.5457448959350586
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3517982065677643
Calibrated prediction for UL: 0.3333333432674408

Simulating Trading Days:  93%|█████████▎| 93/100 [06:02<00:08,  1.18s/it]

Raw prediction for UN: 0.4352812170982361
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.46747130155563354
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.4693993330001831
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4513978660106659
Calibrated prediction for UTX: 0.3193990886211395
Raw prediction for V: 0.5336223244667053
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.4904986619949341
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5231160521507263
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.37035706639289856
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5040031671524048
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.496
[PORT] Sector Basic Matierials: selecting BHP (p=0.549, b=0.940, kelly=0.068) with $1746.75
[PORT] Sector Conglomerates: 7 candidates, avg score=0.448
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.943, kelly=0.223) with $5695.43
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.992, kelly=0.148) with $3786.67
[PORT] Sector Financial: 10 candidates, avg score=0.478
[PORT] Sector Financial: selecting V (p=0.580, b=1.030, kelly=0.172) with $4399.05
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting MRK (p=0.545, b=1.004, kelly=0.093) with $2372.34
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.489
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.998, kelly=0.253) with $6451.86
[PORT] Sector Services: 10 candidates, avg score=0.534
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.373) with $9537.70
[PORT] Sector Technology: 10 candidates, avg score=0.505
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.044, kelly=0.460) with $11746.62
[PORT] Sector Utilities: 10 candidates, avg score=0.495
[PORT] Sector Utilities: selecting DUK (p=0.562, b=0.904, kelly=0.078) with $2002.63
Raw prediction for AAPL: 0.48682069778442383
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.537426233291626
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.37046146392822266
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5286926627159119
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4331098198890686
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48840728402137756
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6687887907028198
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4542235732078552
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5172475576400757
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5026388764381409
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.472586452960968
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4467253088951111
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4994049072265625
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.5133841633796692
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4175320565700531
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4617295265197754
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5710200667381287
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4361637234687805
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4341898560523987
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5123704671859741
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.3753454089164734
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5667113661766052
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.43297356367111206
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.40493297576904297
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4889961779117584
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.49207839369773865
Calibrated prediction for CVX: 0.4444444477558136
Raw prediction for D: 0.5229812264442444
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48435062170028687
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.49889880418777466
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5509982705116272
Calibrated prediction for DUK: 0.5625
Raw prediction for EXC: 0.5074777603149414
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5185306668281555
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5089946389198303
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.37951889634132385
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6647239923477173
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.49314096570014954
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5444769859313965
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5883951187133789
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3411101996898651
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5090113878250122
Calibrated prediction for IEP: 0.5054945349693298
Raw prediction for INTC: 0.5187790393829346
Calibrated prediction for INTC: 0.5064935088157654
Raw prediction for JNJ: 0.40931347012519836
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5198188424110413
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.43103209137916565
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5351651906967163
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3718665838241577
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5766847729682922
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4757758677005768
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6442357301712036
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5810800194740295
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5151403546333313
Calibrated prediction for MRK: 0.5454545617103577
Raw prediction for MSFT: 0.5078412890434265
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.47940459847450256
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5267941951751709
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.36950013041496277
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.36671093106269836
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49650847911834717
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6133273839950562
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.500607430934906
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5109405517578125
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4323427081108093
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4513101279735565
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.38836076855659485
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.4995355010032654
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.47003793716430664
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.47358593344688416
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5148618817329407
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5564793348312378
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5126863718032837
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5198125839233398
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.413418173789978
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3311104476451874
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.4071120023727417
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5653965473175049
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6104191541671753
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.4025394022464752
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5461282730102539
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.35310012102127075
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.43478333950042725
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.47515177726745605
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.4701421558856964
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.46793994307518005
Calibrated prediction for UTX: 0.375
Raw prediction for V: 0.5293545126914978
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.47749558091163635
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5227654576301575
Calibrated prediction for WFC: 0.5161290168762207

Simulating Trading Days:  94%|█████████▍| 94/100 [06:03<00:07,  1.18s/it]

Raw prediction for WMT: 0.3683602809906006
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5040863752365112
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.504
[PORT] Sector Basic Matierials: selecting BHP (p=0.549, b=0.939, kelly=0.068) with $1737.20
[PORT] Sector Conglomerates: 7 candidates, avg score=0.448
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.945, kelly=0.224) with $5710.61
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.990, kelly=0.147) with $3759.36
[PORT] Sector Financial: 10 candidates, avg score=0.478
[PORT] Sector Financial: selecting V (p=0.580, b=1.030, kelly=0.172) with $4389.71
[PORT] Sector Healthcare: 10 candidates, avg score=0.475
[PORT] Sector Healthcare: selecting MRK (p=0.545, b=1.004, kelly=0.093) with $2363.84
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.495
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.997, kelly=0.252) with $6434.51
[PORT] Sector Services: 10 candidates, avg score=0.539
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.373) with $9524.62
[PORT] Sector Technology: 10 candidates, avg score=0.505
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.046, kelly=0.460) with $11742.57
[PORT] Sector Utilities: 10 candidates, avg score=0.495
[PORT] Sector Utilities: selecting DUK (p=0.562, b=0.906, kelly=0.080) with $2029.25
Raw prediction for AAPL: 0.4860873222351074
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5369361639022827
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.36587876081466675
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5262309908866882
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4342467188835144
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.4885677099227905
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6588296890258789
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4536423981189728
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.517500102519989
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5031753182411194
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.47115787863731384
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.44528090953826904
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4973401725292206
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.529018223285675
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.42238864302635193
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46155714988708496
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5706290006637573
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.43921932578086853
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4342120289802551
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5107913017272949
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.3743027448654175
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5750545859336853
Calibrated prediction for CHTR: 0.5287356376647949
Raw prediction for CMCSA: 0.44002413749694824
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.40443313121795654
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4892100393772125
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4972311556339264
Calibrated prediction for CVX: 0.4615384638309479
Raw prediction for D: 0.5141502618789673
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4840061068534851
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.4991953372955322
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5662209987640381
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5075291395187378
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5185145735740662
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5091623663902283
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3811228275299072
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6567148566246033
Calibrated prediction for GOOG: 0.7241417765617371
Raw prediction for HD: 0.4953681528568268
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.543785572052002
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5885260701179504
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.34181585907936096
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5141627192497253
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5198849439620972
Calibrated prediction for INTC: 0.5369324684143066
Raw prediction for JNJ: 0.40561169385910034
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5203348994255066
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.433685302734375
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5368272066116333
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.36810576915740967
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5763184428215027
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4764881432056427
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6433508396148682
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5813608765602112
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.510665774345398
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.507358968257904
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.4777792990207672
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5255600810050964
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.370337575674057
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.364813894033432
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.49568673968315125
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6079967021942139
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5006014704704285
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5113943219184875
Calibrated prediction for PFE: 0.5164331197738647
Raw prediction for PG: 0.4317721724510193
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.44874513149261475
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.3911278545856476
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.49996304512023926
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46991780400276184
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4721592664718628
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5088049173355103
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5558119416236877
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5114258527755737
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5195891857147217
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4191095232963562
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3328363299369812
Calibrated prediction for SPLP: 0.2373877763748169

Simulating Trading Days:  95%|█████████▌| 95/100 [06:05<00:05,  1.19s/it]

Raw prediction for SRE: 0.4087178111076355
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5657285451889038
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.6024680137634277
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.39939895272254944
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5415396094322205
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3540838658809662
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4338260591030121
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4759672284126282
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.4704577624797821
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4754866659641266
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5230283737182617
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.46582260727882385
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5225701928138733
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.3668258488178253
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5034814476966858
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.506
[PORT] Sector Basic Matierials: selecting BHP (p=0.549, b=0.938, kelly=0.068) with $1722.00
[PORT] Sector Conglomerates: 7 candidates, avg score=0.451
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.946, kelly=0.224) with $5716.65
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.993, kelly=0.148) with $3780.73
[PORT] Sector Financial: 10 candidates, avg score=0.478
[PORT] Sector Financial: selecting V (p=0.580, b=1.030, kelly=0.172) with $4386.65
[PORT] Sector Healthcare: 10 candidates, avg score=0.471
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.011, kelly=0.072) with $1826.64
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.994, kelly=0.251) with $6404.75
[PORT] Sector Services: 10 candidates, avg score=0.539
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.056, kelly=0.374) with $9520.17
[PORT] Sector Technology: 10 candidates, avg score=0.508
[PORT] Sector Technology: selecting GOOG (p=0.724, b=1.044, kelly=0.460) with $11720.71
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.905, kelly=0.176) with $4495.39
Raw prediction for AAPL: 0.4854021966457367
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5368056893348694
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.362848162651062
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5242478847503662
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4357474744319916
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48843106627464294
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6505308747291565
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45316651463508606
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5177213549613953
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5036420822143555
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.46583661437034607
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.44205307960510254
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.49372047185897827
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.5345144867897034
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4297443628311157
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4614716172218323
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5705845952033997
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4423014521598816
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4343462288379669
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5132117867469788
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.374702125787735
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.5864501595497131
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4450378715991974
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.40730106830596924
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4893818497657776
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.4995189905166626
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.5039289593696594
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4838287830352783
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.4994983971118927
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5778682827949524
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5075518488883972
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.518580973148346
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5090534090995789
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3796573579311371
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6401383280754089
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.49785831570625305
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5435878038406372
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5897681713104248
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3433142900466919
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5186439752578735
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5211327075958252
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.4054314196109772
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.520498514175415
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.436219722032547
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5383210778236389
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.36979585886001587
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5762799978256226
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.4772200286388397
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6420373916625977
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5813227295875549
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.5057636499404907
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5080735087394714
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.47925662994384766
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5247259736061096
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3729923367500305
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.36612534523010254
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4944942891597748
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.6038259267807007
Calibrated prediction for PCLN: 0.6499999761581421
Raw prediction for PEP: 0.5004885792732239
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5101179480552673
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43142229318618774
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.44579213857650757
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.39470186829566956
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5004689693450928
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4686696231365204
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.4723111093044281
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5115052461624146
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5540156960487366
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5092675685882568
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5195027589797974
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4260745942592621
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.33158421516418457
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.4065842032432556
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5597706437110901
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5789771676063538
Calibrated prediction for TM: 0.5757575631141663
Raw prediction for TOT: 0.38997381925582886
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5366955399513245
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.34859082102775574
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4303359389305115
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4720808267593384
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.4721147119998932
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.48348546028137207
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5202834606170654
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.45588040351867676
Calibrated prediction for VZ: 0.43023255467414856

Simulating Trading Days:  96%|█████████▌| 96/100 [06:06<00:04,  1.18s/it]

Raw prediction for WFC: 0.5223686099052429
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.367681622505188
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5026646256446838
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.512
[PORT] Sector Basic Matierials: selecting BHP (p=0.549, b=0.940, kelly=0.069) with $1746.87
[PORT] Sector Conglomerates: 7 candidates, avg score=0.451
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.947, kelly=0.225) with $5723.98
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.458
[PORT] Sector Consumer Goods: selecting TM (p=0.576, b=0.994, kelly=0.149) with $3786.17
[PORT] Sector Financial: 10 candidates, avg score=0.473
[PORT] Sector Financial: selecting V (p=0.526, b=1.028, kelly=0.065) with $1664.85
[PORT] Sector Healthcare: 10 candidates, avg score=0.471
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.010, kelly=0.071) with $1811.13
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.996, kelly=0.252) with $6412.00
[PORT] Sector Services: 10 candidates, avg score=0.545
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.057, kelly=0.374) with $9519.51
[PORT] Sector Technology: 10 candidates, avg score=0.500
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.045, kelly=0.288) with $7342.29
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.907, kelly=0.177) with $4513.87
Raw prediction for AAPL: 0.48489344120025635
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5361959338188171
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3619181215763092
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5221121907234192
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4370929002761841
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48802703619003296
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6385593414306641
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45269662141799927
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5179262757301331
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5037948489189148
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.45898494124412537
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4359741508960724
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4895756244659424
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.535515546798706
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4367203414440155
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46121084690093994
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5708218812942505
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.44417691230773926
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.43444499373435974
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5098084807395935
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.37650707364082336
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.598079264163971
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.44927406311035156
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.41427847743034363
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.48927783966064453
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5024068355560303
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.49607017636299133
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48355647921562195
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.4999901056289673
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5847110748291016
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5076424479484558
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5186964869499207
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5089981555938721
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3757587671279907
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6195629835128784
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.49613437056541443
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5433861017227173
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5867223143577576
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.34571319818496704
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5215955972671509
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5221210718154907
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.4022323787212372
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5204759240150452
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.43900126218795776
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5392825603485107
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3726319372653961
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5762110352516174
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47826120257377625
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.640311598777771
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5802276134490967
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.498398095369339
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.507491409778595
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.4826931357383728
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5237856507301331
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.37233343720436096
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3686055839061737
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4931051433086395
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5986766219139099
Calibrated prediction for PCLN: 0.6155471801757812
Raw prediction for PEP: 0.500129759311676
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5061259865760803
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43181031942367554
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4436548352241516
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4022979140281677
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5004743933677673
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46684765815734863
Calibrated prediction for PTR: 0.46864190697669983
Raw prediction for RDS-B: 0.47309792041778564
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5168562531471252
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.551730215549469
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5074165463447571
Calibrated prediction for SNP: 0.5127428770065308
Raw prediction for SNY: 0.5194081664085388
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4323948919773102
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.3281630277633667
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.39889395236968994
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5499153733253479
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5517736077308655
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.3855400085449219
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5328449010848999
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.340101033449173
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.42733636498451233
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4645348787307739
Calibrated prediction for UNH: 0.43396225571632385
Raw prediction for UPS: 0.47280353307724
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.4921915829181671
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.519624650478363
Calibrated prediction for V: 0.5263158082962036

Simulating Trading Days:  97%|█████████▋| 97/100 [06:07<00:03,  1.20s/it]

Raw prediction for VZ: 0.44908612966537476
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.521963894367218
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.3701925575733185
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5022986531257629
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.512
[PORT] Sector Basic Matierials: selecting BHP (p=0.549, b=0.941, kelly=0.069) with $1752.84
[PORT] Sector Conglomerates: 7 candidates, avg score=0.451
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.947, kelly=0.225) with $5716.83
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.950, kelly=0.125) with $3173.10
[PORT] Sector Financial: 10 candidates, avg score=0.473
[PORT] Sector Financial: selecting V (p=0.526, b=1.026, kelly=0.065) with $1641.97
[PORT] Sector Healthcare: 10 candidates, avg score=0.471
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.012, kelly=0.072) with $1832.08
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.994, kelly=0.251) with $6386.97
[PORT] Sector Services: 10 candidates, avg score=0.542
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.058, kelly=0.374) with $9519.02
[PORT] Sector Technology: 10 candidates, avg score=0.500
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.046, kelly=0.289) with $7344.59
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.906, kelly=0.177) with $4503.81
Raw prediction for AAPL: 0.48449480533599854
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5352944135665894
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.3631863594055176
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5202772617340088
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4388478398323059
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.487536758184433
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6377623677253723
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.4523875117301941
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5181077718734741
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5038238763809204
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.45002421736717224
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4283759295940399
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4872887134552002
Calibrated prediction for BHP: 0.5486187934875488
Raw prediction for BP: 0.5269988775253296
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.4437630772590637
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.46080487966537476
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5706356167793274
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.44506242871284485
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.434540331363678
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.5077420473098755
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.37692636251449585
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.6101016998291016
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.4541865587234497
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.4197503626346588
Calibrated prediction for CODI: 0.37554362416267395
Raw prediction for CSCO: 0.4891742765903473
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.5027523040771484
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.4921495318412781
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4832635223865509
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5006877183914185
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5872761607170105
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.507726788520813
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5188111066818237
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5089733004570007
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.36937350034713745
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6096386909484863
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.49384957551956177
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.543262779712677
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5761545300483704
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.3484199345111847
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5228163003921509
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5230586528778076
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3976224362850189
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5203887224197388
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.44108566641807556
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5399614572525024
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.37373673915863037
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.576225221157074
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.479094535112381
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6383659839630127
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5796660780906677
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4899752736091614
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5072171688079834
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.4861035943031311
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5224502682685852
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3714351952075958
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.37128832936286926
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4917706549167633
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5974479913711548
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.4998481869697571
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.5018269419670105
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.4322412610054016
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.44145530462265015
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.40732717514038086
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.500468373298645
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.46487653255462646
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.4755914807319641
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5273642539978027
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5459644794464111
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5057322978973389
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5192973017692566
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.434042751789093
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.31951552629470825
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.39175188541412354
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5438506007194519
Calibrated prediction for T: 0.589911937713623

Simulating Trading Days:  98%|█████████▊| 98/100 [06:08<00:02,  1.19s/it]

Raw prediction for TM: 0.5278142690658569
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.377673864364624
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5291873216629028
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.33092325925827026
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4227617681026459
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4587094485759735
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.47603923082351685
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5038112998008728
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5202481150627136
Calibrated prediction for V: 0.5263158082962036
Raw prediction for VZ: 0.4468831419944763
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5211607217788696
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.37404850125312805
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5020623207092285
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.508
[PORT] Sector Basic Matierials: selecting BHP (p=0.549, b=0.940, kelly=0.068) with $1739.15
[PORT] Sector Conglomerates: 7 candidates, avg score=0.451
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.946, kelly=0.225) with $5719.96
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.952, kelly=0.126) with $3199.20
[PORT] Sector Financial: 10 candidates, avg score=0.473
[PORT] Sector Financial: selecting V (p=0.526, b=1.025, kelly=0.064) with $1631.18
[PORT] Sector Healthcare: 10 candidates, avg score=0.468
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.012, kelly=0.072) with $1837.36
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.992, kelly=0.251) with $6382.66
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.056, kelly=0.374) with $9520.08
[PORT] Sector Technology: 10 candidates, avg score=0.500
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.048, kelly=0.289) with $7373.14
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.905, kelly=0.176) with $4495.23
Raw prediction for AAPL: 0.4841904938220978
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5344200730323792
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.36435171961784363
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5186969041824341
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.44079118967056274
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48690298199653625
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6437885165214539
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.45211803913116455
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5182639956474304
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5037156939506531
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.4374546706676483
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.42276731133461
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.48219940066337585
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.5142394304275513
Calibrated prediction for BP: 0.5306122303009033
Raw prediction for BRK-A: 0.44554805755615234
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4605605900287628
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5716673135757446
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.44611257314682007
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.4345826506614685
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.50010746717453
Calibrated prediction for CELG: 0.5333333611488342
Raw prediction for CHL: 0.3781466484069824
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.6203111410140991
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.45824703574180603
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.42642712593078613
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.48873862624168396
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.50052410364151
Calibrated prediction for CVX: 0.5249999761581421
Raw prediction for D: 0.48883289098739624
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.4829024076461792
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.5016217827796936
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.5857625603675842
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5078244805335999
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5189003944396973
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5091368556022644
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.3615771234035492
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6109473705291748
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.49075013399124146
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.5431274175643921
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.5616101622581482
Calibrated prediction for HRG: 0.6229507923126221
Raw prediction for HSBC: 0.35177287459373474
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5220625400543213
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5233940482139587
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.39334461092948914
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5201533436775208
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4424336850643158
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.5404041409492493
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.3762388229370117
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5761381387710571
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.47968393564224243
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6364263892173767
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5795658826828003
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4827682375907898
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.5068634152412415
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.4867011606693268
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5211472511291504
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.3687635362148285
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.3734220266342163
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.4908688962459564
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5969030261039734
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.49970608949661255
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4953063726425171
Calibrated prediction for PFE: 0.5151515007019043
Raw prediction for PG: 0.43296918272972107
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4417506456375122
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.4101475179195404
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.5004937648773193
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.4625019133090973
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.48049935698509216
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5394517183303833
Calibrated prediction for REX: 0.4677419364452362
Raw prediction for SLB: 0.5352218747138977
Calibrated prediction for SLB: 0.5397986173629761
Raw prediction for SNP: 0.5045119524002075
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5190898180007935
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4321424663066864
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.30509528517723083
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3865538537502289
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.5374601483345032
Calibrated prediction for T: 0.589911937713623
Raw prediction for TM: 0.5174108743667603
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.37113675475120544
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5248607397079468
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.3230608403682709
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.4180874228477478
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4532322883605957
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.4792984127998352
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5110204219818115
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5218266844749451
Calibrated prediction for V: 0.5662165880203247
Raw prediction for VZ: 0.44686582684516907
Calibrated prediction for VZ: 0.43023255467414856

Simulating Trading Days:  99%|█████████▉| 99/100 [06:09<00:01,  1.18s/it]

Raw prediction for WFC: 0.5207188725471497
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.37646484375
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5016984939575195
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.503
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.961, kelly=0.075) with $1924.15
[PORT] Sector Conglomerates: 7 candidates, avg score=0.463
[PORT] Sector Conglomerates: selecting HRG (p=0.623, b=0.945, kelly=0.224) with $5716.25
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.953, kelly=0.126) with $3228.29
[PORT] Sector Financial: 10 candidates, avg score=0.476
[PORT] Sector Financial: selecting V (p=0.566, b=1.027, kelly=0.144) with $3673.60
[PORT] Sector Healthcare: 10 candidates, avg score=0.468
[PORT] Sector Healthcare: selecting CELG (p=0.533, b=1.011, kelly=0.072) with $1826.55
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.991, kelly=0.250) with $6382.66
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.374) with $9534.85
[PORT] Sector Technology: 10 candidates, avg score=0.500
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.048, kelly=0.289) with $7385.25
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.903, kelly=0.176) with $4484.33
Raw prediction for AAPL: 0.48411449790000916
Calibrated prediction for AAPL: 0.4895158112049103
Raw prediction for ABB: 0.5334176421165466
Calibrated prediction for ABB: 0.5300073027610779
Raw prediction for ABBV: 0.36447954177856445
Calibrated prediction for ABBV: 0.4076898992061615
Raw prediction for AEP: 0.5178132057189941
Calibrated prediction for AEP: 0.5263158082962036
Raw prediction for AGFS: 0.4426044225692749
Calibrated prediction for AGFS: 0.4911747872829437
Raw prediction for AMGN: 0.48656153678894043
Calibrated prediction for AMGN: 0.4965362250804901
Raw prediction for AMZN: 0.6472432613372803
Calibrated prediction for AMZN: 0.6783495545387268
Raw prediction for BA: 0.451519250869751
Calibrated prediction for BA: 0.4546239376068115
Raw prediction for BABA: 0.5183715224266052
Calibrated prediction for BABA: 0.51587975025177
Raw prediction for BAC: 0.5035562515258789
Calibrated prediction for BAC: 0.49456852674484253
Raw prediction for BBL: 0.42509564757347107
Calibrated prediction for BBL: 0.546875
Raw prediction for BCH: 0.4197086691856384
Calibrated prediction for BCH: 0.45835116505622864
Raw prediction for BHP: 0.4736332893371582
Calibrated prediction for BHP: 0.5
Raw prediction for BP: 0.4995516836643219
Calibrated prediction for BP: 0.5162981152534485
Raw prediction for BRK-A: 0.4456464350223541
Calibrated prediction for BRK-A: 0.4140874445438385
Raw prediction for BSAC: 0.4604087173938751
Calibrated prediction for BSAC: 0.46436169743537903
Raw prediction for BUD: 0.5708842873573303
Calibrated prediction for BUD: 0.48275861144065857
Raw prediction for C: 0.4452904164791107
Calibrated prediction for C: 0.4886363744735718
Raw prediction for CAT: 0.434222012758255
Calibrated prediction for CAT: 0.4598650634288788
Raw prediction for CELG: 0.48928800225257874
Calibrated prediction for CELG: 0.44749316573143005
Raw prediction for CHL: 0.38832351565361023
Calibrated prediction for CHL: 0.3333333432674408
Raw prediction for CHTR: 0.6288830637931824
Calibrated prediction for CHTR: 0.5981503129005432
Raw prediction for CMCSA: 0.462009072303772
Calibrated prediction for CMCSA: 0.4576271176338196
Raw prediction for CODI: 0.43349289894104004
Calibrated prediction for CODI: 0.46226415038108826
Raw prediction for CSCO: 0.4880775213241577
Calibrated prediction for CSCO: 0.48795363306999207
Raw prediction for CVX: 0.49422842264175415
Calibrated prediction for CVX: 0.4615384638309479
Raw prediction for D: 0.4856906533241272
Calibrated prediction for D: 0.537190854549408
Raw prediction for DHR: 0.48272112011909485
Calibrated prediction for DHR: 0.48573315143585205
Raw prediction for DIS: 0.502790093421936
Calibrated prediction for DIS: 0.5080798864364624
Raw prediction for DUK: 0.579552948474884
Calibrated prediction for DUK: 0.6087533831596375
Raw prediction for EXC: 0.5079545378684998
Calibrated prediction for EXC: 0.508815586566925
Raw prediction for FB: 0.5187904834747314
Calibrated prediction for FB: 0.5195395946502686
Raw prediction for GD: 0.5094032287597656
Calibrated prediction for GD: 0.5108832716941833
Raw prediction for GE: 0.35438305139541626
Calibrated prediction for GE: 0.43296676874160767
Raw prediction for GOOG: 0.6130699515342712
Calibrated prediction for GOOG: 0.6363636255264282
Raw prediction for HD: 0.48679640889167786
Calibrated prediction for HD: 0.5223880410194397
Raw prediction for HON: 0.542447566986084
Calibrated prediction for HON: 0.5290878415107727
Raw prediction for HRG: 0.545829176902771
Calibrated prediction for HRG: 0.6133333444595337
Raw prediction for HSBC: 0.3561566174030304
Calibrated prediction for HSBC: 0.41698122024536133
Raw prediction for IEP: 0.5200160145759583
Calibrated prediction for IEP: 0.5299563407897949
Raw prediction for INTC: 0.5243512392044067
Calibrated prediction for INTC: 0.5419793725013733
Raw prediction for JNJ: 0.3889468014240265
Calibrated prediction for JNJ: 0.4285714328289032
Raw prediction for JPM: 0.5201565027236938
Calibrated prediction for JPM: 0.5178571343421936
Raw prediction for KO: 0.4431338906288147
Calibrated prediction for KO: 0.4374203383922577
Raw prediction for LMT: 0.541756272315979
Calibrated prediction for LMT: 0.5426117777824402
Raw prediction for MA: 0.37758415937423706
Calibrated prediction for MA: 0.42780840396881104
Raw prediction for MCD: 0.5761052966117859
Calibrated prediction for MCD: 0.5628662705421448
Raw prediction for MDT: 0.479764848947525
Calibrated prediction for MDT: 0.47352921962738037
Raw prediction for MMM: 0.6346443295478821
Calibrated prediction for MMM: 0.6267484426498413
Raw prediction for MO: 0.5791893601417542
Calibrated prediction for MO: 0.5736433863639832
Raw prediction for MRK: 0.4837925136089325
Calibrated prediction for MRK: 0.5
Raw prediction for MSFT: 0.503760814666748
Calibrated prediction for MSFT: 0.4886363744735718
Raw prediction for NEE: 0.48470818996429443
Calibrated prediction for NEE: 0.4784289300441742
Raw prediction for NGG: 0.5217131972312927
Calibrated prediction for NGG: 0.4939759075641632
Raw prediction for NVS: 0.36555689573287964
Calibrated prediction for NVS: 0.397896409034729
Raw prediction for ORCL: 0.37584221363067627
Calibrated prediction for ORCL: 0.39493823051452637
Raw prediction for PCG: 0.48992404341697693
Calibrated prediction for PCG: 0.4989130198955536
Raw prediction for PCLN: 0.5929486155509949
Calibrated prediction for PCLN: 0.6020408272743225
Raw prediction for PEP: 0.49964475631713867
Calibrated prediction for PEP: 0.4985800087451935
Raw prediction for PFE: 0.4890700578689575
Calibrated prediction for PFE: 0.4702380895614624
Raw prediction for PG: 0.43344801664352417
Calibrated prediction for PG: 0.4336414337158203
Raw prediction for PICO: 0.4412652552127838
Calibrated prediction for PICO: 0.4326923191547394
Raw prediction for PM: 0.40778785943984985
Calibrated prediction for PM: 0.39898690581321716
Raw prediction for PPL: 0.49976325035095215
Calibrated prediction for PPL: 0.5060964822769165
Raw prediction for PTR: 0.45994219183921814
Calibrated prediction for PTR: 0.4459293484687805
Raw prediction for RDS-B: 0.48906612396240234
Calibrated prediction for RDS-B: 0.5208333134651184
Raw prediction for REX: 0.5503690242767334
Calibrated prediction for REX: 0.6723315119743347
Raw prediction for SLB: 0.5148606300354004
Calibrated prediction for SLB: 0.4221733808517456
Raw prediction for SNP: 0.5039104223251343
Calibrated prediction for SNP: 0.4942278563976288
Raw prediction for SNY: 0.5188661813735962
Calibrated prediction for SNY: 0.5202111601829529
Raw prediction for SO: 0.4297958314418793
Calibrated prediction for SO: 0.4141654372215271
Raw prediction for SPLP: 0.287282794713974
Calibrated prediction for SPLP: 0.2373877763748169
Raw prediction for SRE: 0.3804594874382019
Calibrated prediction for SRE: 0.4285714328289032
Raw prediction for T: 0.536719560623169
Calibrated prediction for T: 0.589911937713623

Simulating Trading Days: 100%|██████████| 100/100 [06:11<00:00,  3.71s/it]

Raw prediction for TM: 0.5138720273971558
Calibrated prediction for TM: 0.4821428656578064
Raw prediction for TOT: 0.3656183183193207
Calibrated prediction for TOT: 0.4285714328289032
Raw prediction for TSM: 0.5241418480873108
Calibrated prediction for TSM: 0.5770066976547241
Raw prediction for UL: 0.31224551796913147
Calibrated prediction for UL: 0.3333333432674408
Raw prediction for UN: 0.40721404552459717
Calibrated prediction for UN: 0.35549506545066833
Raw prediction for UNH: 0.4462355077266693
Calibrated prediction for UNH: 0.41128528118133545
Raw prediction for UPS: 0.48099321126937866
Calibrated prediction for UPS: 0.5426356792449951
Raw prediction for UTX: 0.5120789408683777
Calibrated prediction for UTX: 0.5479452013969421
Raw prediction for V: 0.5236908197402954
Calibrated prediction for V: 0.5799999833106995
Raw prediction for VZ: 0.45237213373184204
Calibrated prediction for VZ: 0.43023255467414856
Raw prediction for WFC: 0.5205983519554138
Calibrated prediction for WFC: 0.5161290168762207
Raw prediction for WMT: 0.3786671757698059
Calibrated prediction for WMT: 0.4189581871032715
Raw prediction for XOM: 0.5007885694503784
Calibrated prediction for XOM: 0.5001449584960938
[PORT] Received 87 predictions for sizing. Threshold=0.300, Kelly frac=0.250
[PORT] Sector Basic Matierials: 10 candidates, avg score=0.484
[PORT] Sector Basic Matierials: selecting BBL (p=0.547, b=0.963, kelly=0.076) with $1954.24
[PORT] Sector Conglomerates: 7 candidates, avg score=0.491
[PORT] Sector Conglomerates: selecting REX (p=0.672, b=1.083, kelly=0.370) with $9471.33
[PORT] Sector Consumer Goods: 10 candidates, avg score=0.449
[PORT] Sector Consumer Goods: selecting MO (p=0.574, b=0.952, kelly=0.126) with $3227.67
[PORT] Sector Financial: 10 candidates, avg score=0.478
[PORT] Sector Financial: selecting V (p=0.580, b=1.030, kelly=0.172) with $4407.20
[PORT] Sector Healthcare: 10 candidates, avg score=0.455
[PORT] Sector Healthcare: selecting SNY (p=0.520, b=1.005, kelly=0.043) with $1092.24
[PORT] Sector Industrial Goods: 10 candidates, avg score=0.512
[PORT] Sector Industrial Goods: selecting MMM (p=0.627, b=0.990, kelly=0.250) with $6395.09
[PORT] Sector Services: 10 candidates, avg score=0.541
[PORT] Sector Services: selecting AMZN (p=0.678, b=1.055, kelly=0.374) with $9568.86
[PORT] Sector Technology: 10 candidates, avg score=0.500
[PORT] Sector Technology: selecting GOOG (p=0.636, b=1.048, kelly=0.289) with $7408.06
[PORT] Sector Utilities: 10 candidates, avg score=0.500
[PORT] Sector Utilities: selecting DUK (p=0.609, b=0.905, kelly=0.176) with $4518.55

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'REX', 'investment_fraction': 0.09..."
1,2017-04-12,99831.887339,69882.321137,99831.887339,99831.887339,-168.112661,-0.001681,"[{'ticker': 'REX', 'investment_fraction': 0.09..."
2,2017-04-13,99712.756773,69798.929741,99712.756773,99712.756773,-119.130565,-0.001193,"[{'ticker': 'REX', 'investment_fraction': 0.09..."
3,2017-04-17,99940.281142,69958.196800,99940.281142,99940.281142,227.524369,0.002282,"[{'ticker': 'REX', 'investment_fraction': 0.09..."
4,2017-04-18,100067.093837,70046.965686,100067.093837,100067.093837,126.812695,0.001269,"[{'ticker': 'GOOG', 'investment_fraction': 0.1..."
...,...,...,...,...,...,...,...,...
95,2017-08-25,101801.802012,71261.261408,101801.802012,101801.802012,-111.837755,-0.001097,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
96,2017-08-28,101722.648443,71205.853910,101722.648443,101722.648443,-79.153569,-0.000778,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
97,2017-08-29,101898.097426,71328.668198,101898.097426,101898.097426,175.448983,0.001725,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
98,2017-08-30,102112.255006,71478.578504,102112.255006,102112.255006,214.157580,0.002102,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
99,2017-08-31,102452.583378,102452.583378,102452.583378,102452.583378,340.328372,0.003333,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'REX', 'investment_fraction': 0.09..."
1,2017-04-12,99831.887339,69882.321137,99831.887339,99831.887339,-168.112661,-0.001681,"[{'ticker': 'REX', 'investment_fraction': 0.09..."
2,2017-04-13,99712.756773,69798.929741,99712.756773,99712.756773,-119.130565,-0.001193,"[{'ticker': 'REX', 'investment_fraction': 0.09..."
3,2017-04-17,99940.281142,69958.196800,99940.281142,99940.281142,227.524369,0.002282,"[{'ticker': 'REX', 'investment_fraction': 0.09..."
4,2017-04-18,100067.093837,70046.965686,100067.093837,100067.093837,126.812695,0.001269,"[{'ticker': 'GOOG', 'investment_fraction': 0.1..."
...,...,...,...,...,...,...,...,...
95,2017-08-25,101801.802012,71261.261408,101801.802012,101801.802012,-111.837755,-0.001097,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
96,2017-08-28,101722.648443,71205.853910,101722.648443,101722.648443,-79.153569,-0.000778,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
97,2017-08-29,101898.097426,71328.668198,101898.097426,101898.097426,175.448983,0.001725,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
98,2017-08-30,102112.255006,71478.578504,102112.255006,102112.255006,214.157580,0.002102,"[{'ticker': 'AMZN', 'investment_fraction': 0.0..."
99,2017-08-31,102452.583378,102452.583378,102452.583378,102452.583378,340.328372,0.003333,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $102,452.58
Total Return on Investment (ROI): 2.45%
Annualized Sharpe Ratio: 1.78
--------------------------

In [31]:
master_df_with_target = add_horizon_targets(master_df.copy(), H=1, price_col="close")
ret_col = f"ret_{1}d"

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    # Sector aggregates
    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        # top sectors by pnl
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
         # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 460
Total capital allocated: $3,019,644.39
Average position size:  $6,564.44
Completed trades with returns: 460
Winning trades: 245 (53.3%)
Losing trades:  212 (46.1%)
Total PnL: $2,452.58
Average PnL per trade: $5.33
Average return: 0.07%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Technology,91,716148.156415,7869.759961,1171.215122,12.870496,0.001748
Services,97,699727.715838,7213.687792,1012.697217,10.440177,0.001028
Industrial Goods,58,366042.400572,6311.075872,328.901263,5.670711,0.000980
Conglomerates,95,740894.666948,7798.891231,162.915353,1.714898,0.000797
Financial,11,31547.223042,2867.929367,82.198934,7.472630,0.002099
Utilities,65,292330.156286,4497.387020,74.386244,1.144404,-0.000240
Basic Matierials,15,38267.340197,2551.156013,-76.292423,-5.086162,-0.001790
Healthcare,7,28278.164373,4039.737768,-133.691176,-19.098739,-0.001896
Consumer Goods,21,106408.568012,5067.074667,-169.747155,-8.083198,-0.001340

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
347,2017-07-24,2017-07-25,REX,Conglomerates,9569.532072,0.672332,NaN,0.034784,332.871031
91,2017-05-09,2017-05-10,REX,Conglomerates,9536.205840,0.672332,NaN,0.033910,323.371867
139,2017-05-23,2017-05-24,HRG,Conglomerates,5671.004967,0.622951,NaN,0.054576,309.503075
86,2017-05-08,2017-05-09,REX,Conglomerates,9503.755414,0.672332,NaN,0.029684,282.110353
420,2017-08-17,2017-08-18,REX,Conglomerates,9352.124623,0.672332,NaN,0.027725,259.291473
57,2017-04-28,2017-05-01,AMZN,Services,9368.933648,0.678350,NaN,0.025125,235.390574
81,2017-05-05,2017-05-08,REX,Conglomerates,9510.921338,0.672332,NaN,0.024642,234.365326
424,2017-08-21,2017-08-22,GOOG,Technology,11692.661967,0.724142,NaN,0.019886,232.522710
240,2017-06-15,2017-06-16,AMZN,Services,9481.983540,0.678350,NaN,0.024415,231.500945
262,2017-06-22,2017-06-23,REX,Conglomerates,9443.609662,0.672332,NaN,0.024411,230.530510

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
417,2017-08-16,2017-08-17,REX,Conglomerates,9434.777884,0.672332,NaN,-0.050042,-472.136493
372,2017-07-31,2017-08-01,REX,Conglomerates,9602.576426,0.672332,NaN,-0.046009,-441.807440
101,2017-05-11,2017-05-12,REX,Conglomerates,9581.109741,0.672332,NaN,-0.038748,-371.248898
249,2017-06-19,2017-06-20,REX,Conglomerates,9487.117277,0.672332,NaN,-0.038088,-361.348229
115,2017-05-16,2017-05-17,REX,Conglomerates,9523.368376,0.672332,NaN,-0.035290,-336.075467
349,2017-07-24,2017-07-25,MMM,Industrial Goods,6542.453795,0.626748,NaN,-0.050524,-330.549721
127,2017-05-19,2017-05-22,REX,Conglomerates,9505.651446,0.672332,NaN,-0.028010,-266.253920
401,2017-08-09,2017-08-10,AMZN,Services,9560.819858,0.678350,NaN,-0.025550,-244.275747
415,2017-08-16,2017-08-17,GOOG,Technology,11786.736504,0.724142,NaN,-0.017239,-203.193816
400,2017-08-09,2017-08-10,GOOG,Technology,11806.291754,0.724142,NaN,-0.016968,-200.332566

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Technology        1171.215122
Services          1012.697217
Industrial Goods   328.901263
Conglomerates      162.915353
Financial           82.198934
Utilities           74.386244
Basic Matierials   -76.292423
Healthcare        -133.691176
Consumer Goods    -169.747155

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Technology        1171.215122
Services          1012.697217
Industrial Goods   328.901263
Conglomerates      162.915353
Financial           82.198934
Utilities           74.386244
Basic Matierials   -76.292423
Healthcare        -133.691176
Consumer Goods    -169.747155

Top 10 Most Invested Tickers:

ticker
REX     61
MMM     58
AMZN    52
AEP     47
GOOG    47
PCLN    43
HRG     34
CHL     25
MO      14
TSM     12
Name: count, dtype: int64

Tickers Never Invested In (65):
{'SNP', 'JNJ', 'DIS', 'UN', 'ABB', 'SLB', 'RDS-B', 'BA', 'SRE', 'WFC', 'CSCO', 'CVX', 'DHR', 'PEP', 'BRK-A', 'UNH', 'UTX', 'PM', 'MA', 'BAC', 'CODI', 'MDT', 'BABA', 'EXC', 'HSBC', 'PTR', 'NEE', 'HD', 'PCG', 'MRK', 'KO', 'VZ', 'PG', 'WMT', 'SNY', 'BSAC', 'UPS', 'SPLP', 'FB', 'D', 'GD', 'SO', 'UL', 'CAT', 'LMT', 'PICO', 'BHP', 'AMGN', 'PPL', 'PFE', 'AAPL', 'CMCSA', 'HON', 'GE', 'XOM', 'MCD', 'ABBV', 'ORCL', 'NVS', 'AGFS', 'TOT', 'IEP', 'C', 'MSFT', 'INTC'}

In [32]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]