# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as Fnn
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [7]:
pandas_ta_classic_path = None
for sp in site.getsitepackages():
    pandas_ta_classic_path = os.path.join(sp, 'pandas_ta_classic')
    if os.path.exists(pandas_ta_classic_path):
        break

if pandas_ta_classic_path:
    squeeze_pro_path = os.path.join(pandas_ta_classic_path, 'momentum', 'squeeze_pro.py')
    if os.path.exists(squeeze_pro_path):
        try:
            with open(squeeze_pro_path, 'r') as f:
                lines = f.readlines()

            new_lines = []
            fixed = False
            for line in lines:
                if "from numpy import NaN as npNaN" in line:
                    new_lines.append(line.replace("from numpy import NaN as npNaN", "# from numpy import NaN as npNaN\nimport numpy as np\n"))
                    fixed = True
                    print("Modified import statement in squeeze_pro.py")
                else:
                    new_lines.append(line)

            if fixed:
                with open(squeeze_pro_path, 'w') as f:
                    f.writelines(new_lines)
                print("Successfully patched pandas_ta_classic/momentum/squeeze_pro.py")
            else:
                print("Could not find the problematic import line in squeeze_pro.py")

        except Exception as e:
            print(f"Error modifying squeeze_pro.py: {e}")
    else:
        print(f"Could not find squeeze_pro.py at {squeeze_pro_path}")
else:
    print("Could not find the pandas_ta_classic library installation path.")

import pandas_ta_classic as ta

Could not find the problematic import line in squeeze_pro.py

### Configurations

In [8]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 783  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

ALLOCATION_MODE = "KELLY_ONLY"  # {"KELLY_ONLY", "HYBRID_KELLY_MPT", "MPT_ONLY"}
MPT_WINDOW_DAYS = 60
MPT_LAMBDA = 1.0
MPT_RIDGE_EPS = 1e-4
MPT_MAX_WEIGHT = 0.30
MPT_LONG_ONLY = True
MPT_USE_EQUAL_FALLBACK = True
MPT_ONLY_BUDGET_FRACTION = 0.25

In [9]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [10]:
BUCKET_BINS   = [-np.inf, -0.02, -0.005, 0.0, 0.005, 0.02, np.inf]
K = len(BUCKET_BINS) - 1

In [11]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

In [12]:
CALIBRATION_LOGGED = set()

In [13]:
def bucketize_with_edges(x, edges):
    # x: 1D np array of returns; edges: len K+1
    return np.clip(np.digitize(x, edges[1:-1], right=True), 0, len(edges)-2).astype(np.int64)

def make_cumulative_targets(y_idx, K):
    # y_idx in [0..K-1] -> T: [N,K-1] with T[:,k]=1(y>k)
    y = y_idx.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def ordinal_to_class_probs(P_rep):
    # P_rep: [N,K-1] with P(y>k) (after sigmoid), repaired monotone
    N, K1 = P_rep.shape; K = K1+1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:,0] = 1.0 - P_rep[:,0]
    for c in range(1, K-1):
        Pc[:,c] = np.clip(P_rep[:,c-1] - P_rep[:,c], 0., 1.)
    Pc[:,K-1] = P_rep[:,K1-1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)

def monotone_repair_numpy(P):
    P = np.asarray(P, dtype=np.float32).copy()
    for k in range(P.shape[1]-2, -1, -1):
        P[:,k] = np.maximum(P[:,k], P[:,k+1])
    return P

In [14]:
# multiclass calibration tuned for macro-F1 balance
def _class_dist(y_hat, K):
    hist = np.bincount(y_hat, minlength=K).astype(np.float32)
    return hist / max(1, y_hat.size)

def _balance_penalty(p_hat, p_target, norm="l1"):
    if norm == "l1":
        return float(np.abs(p_hat - p_target).sum())
    elif norm == "l2":
        return float(np.sqrt(((p_hat - p_target) ** 2).sum()))
    else:
        return float(np.abs(p_hat - p_target).sum())

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    # decode ordinal cumulative probs to class indices using per-head taus.
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def tune_temperature_and_taus(
    Z_val,
    y_val_idx,
    K,
    T_grid=np.linspace(0.6, 2.5, 15),
    tau_grid=np.linspace(0.2, 0.8, 31),
    lambda_balance=0.05,
    target_priors="uniform",
    coord_rounds=3,
):
    """Learn a temperature T and per-head taus by maximizing macro-F1 with a balance penalty."""
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.detach().cpu().numpy()

    N, K_1 = Z_val.shape
    assert K_1 == K - 1

    if isinstance(target_priors, str) and target_priors == "uniform":
        p_target = np.ones(K, dtype=np.float32) / K
    else:
        p_target = np.asarray(target_priors, dtype=np.float32)
        p_target = p_target / p_target.sum()

    best = {"score": -1e9, "T": 1.0, "taus": np.full(K_1, 0.5, np.float32)}

    for T in T_grid:
        P_cum = 1.0 / (1.0 + np.exp(-(Z_val / T)))
        P_rep = monotone_repair_numpy(P_cum)

        taus = np.full(K_1, 0.5, dtype=np.float32)
        for _ in range(coord_rounds):
            for k in range(K_1):
                best_k = (taus[k], -1e9)
                for tau in tau_grid:
                    taus_try = taus.copy()
                    taus_try[k] = tau
                    y_hat = decode_ordinal_with_taus(P_rep, taus_try)
                    f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
                    p_hat = _class_dist(y_hat, K)
                    score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")
                    if score > best_k[1]:
                        best_k = (tau, score)
                taus[k] = best_k[0]

        y_hat = decode_ordinal_with_taus(P_rep, taus)
        f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
        p_hat = _class_dist(y_hat, K)
        score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")

        if score > best["score"]:
            best.update({"score": score, "T": float(T), "taus": taus.astype(np.float32)})

    return best["T"], best["taus"]

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [15]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [16]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # end current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [17]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [18]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [19]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [20]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [21]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [22]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [23]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [24]:
class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):  # T: float32 matrix [N, K-1] with 0/1
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)
    def __len__(self): return len(self.X)
    def __getitem__(self, i): return self.X[i], self.T[i]
    
class LSTMOrdinal(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, head='CORAL', K=6):
        super().__init__()
        self.K = K
        self.lstm1 = nn.LSTM(n_features, hidden1, num_layers=1, batch_first=True, dropout=0.1)
        self.inter_drop = nn.Dropout(inter_dropout)
        self.lstm2 = nn.LSTM(hidden1, hidden2, num_layers=1, batch_first=True, dropout=0.1)

        self.norm = nn.BatchNorm1d(hidden2)
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(dropout)

        if head.upper() == 'CORAL':
            self.w = nn.Linear(fc, 1, bias=False)
            self._beta = nn.Parameter(torch.zeros(K-1))
            self.softplus = nn.Softplus()
            self.head_type = 'CORAL'
        else:
            self.fc_out = nn.Linear(fc, K-1)
            self.head_type = 'CORN'

    def forward(self, x):
        out1,_ = self.lstm1(x)
        out1 = self.inter_drop(out1)
        out2,_ = self.lstm2(out1)
        last = out2[:, -1, :]
        last = self.norm(last)
        z = self.relu(self.fc1(last))
        z = self.drop(z)
        if self.head_type == 'CORAL':
            base = self.w(z)                              # [B,1]
            deltas = self.softplus(self._beta)            # ≥0
            b = torch.cumsum(deltas, dim=0)               # [K-1]
            logits = base - b                              # broadcast -> [B,K-1]
        else:
            logits = self.fc_out(z)                        # [B,K-1]
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [25]:
def train_company_models(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 sequence_length: int = None,
                                 H: int = 1,
                                 K: int = K,        # global K
                                 head_type: str = 'CORAL'):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"[TRAIN] {ticker}: preparing data (H={H}) with {len(company_data_df)} rows")

    ret_col = f"ret_{H}d"
    if ret_col not in company_data_df.columns:
        company_data_df = add_horizon_targets(company_data_df, H=H, price_col='close')

    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)
    if len(company_data_df) < sequence_length + H + 10:
        print(f"[TRAIN] {ticker}: insufficient history for sequence length {sequence_length}")
        return False, sequence_length

    contigs = identify_contiguous_periods(company_data_df)
    if not contigs:
        print(f"[TRAIN] {ticker}: no contiguous periods found")
        return False, sequence_length

    rets = company_data_df[ret_col].values
    y_idx_all = bucketize_with_edges(rets, BUCKET_BINS)
    X_all = company_data_df[feature_cols].values

    X_seq, y_seq = create_contiguous_sequences(
        X_all, y_idx_all, contigs, sequence_length, H
    )
    if len(X_seq) < 40:
        print(f"[TRAIN] {ticker}: too few sequences ({len(X_seq)})")
        return False, sequence_length
    print(f"[TRAIN] {ticker}: built {len(X_seq)} sequences (seq_len={sequence_length})")

    X_tr, X_val, y_tr, y_val = train_test_split(X_seq, y_seq, test_size=0.2, shuffle=False)

    scaler = MinMaxScaler()
    F = X_tr.shape[-1]
    X_tr = scaler.fit_transform(X_tr.reshape(-1, F)).reshape(X_tr.shape)
    X_val = scaler.transform(X_val.reshape(-1, F)).reshape(X_val.shape)
    print(f"[TRAIN] {ticker}: scaler fitted on {X_tr.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_tr has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    # sector_feature_indices = [feature_cols.index('sector_ret_1d'),
    #                       feature_cols.index('sector_ret_5d'),
    #                       feature_cols.index('sector_vol_20d')]

    # print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    # print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")


    T_tr  = make_cumulative_targets(y_tr, K)
    T_val = make_cumulative_targets(y_val, K)

    train_ds = OrdinalSequenceDataset(X_tr, T_tr)
    val_ds   = OrdinalSequenceDataset(X_val, T_val)
    train_bs = min(32, len(train_ds))
    if train_bs < 2:
        print(f"[TRAIN] {ticker}: too few samples for BatchNorm (train size={len(train_ds)})")
        return False, sequence_length
    if len(train_ds) % train_bs == 1 and train_bs > 2:
        train_bs -= 1  # avoid batch size 1 for BatchNorm
    val_bs = min(32, len(val_ds))
    train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=True, drop_last=False)
    val_loader   = DataLoader(val_ds,   batch_size=val_bs, shuffle=False, drop_last=False)

    n_features = X_tr.shape[-1]
    model = LSTMOrdinal(n_features=n_features, head=head_type, K=K).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    pos_rate = T_tr.mean(axis=0)
    pos_w = ((1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)).astype(np.float32)
    pos_w = torch.tensor(pos_w, dtype=torch.float32, device=device) 
    print(f"[TRAIN] {ticker}: model n_features = {n_features}")

    
    def loss_fn(logits, T):
        losses = []
        for k in range(logits.shape[1]):
            losses.append(Fnn.binary_cross_entropy_with_logits(logits[:,k], T[:,k], pos_weight=pos_w[k]))
        return torch.stack(losses).mean()

    early = EarlyStopper(patience=15, mode='min')
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)

    for epoch in range(100):
        model.train()
        tot = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            l = loss_fn(logits, yb)
            l.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tot += l.item() * xb.size(0)

        model.eval()
        with torch.no_grad():
            vtot = 0.0
            for xb, yb in val_loader:
                xb, yb = xb.to(device), yb.to(device)
                logits = model(xb)
                l = loss_fn(logits, yb)
                vtot += l.item() * xb.size(0)
            val_loss = vtot / len(val_loader.dataset)

        scheduler.step(val_loss)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:
            break

    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    ret_seq_full = company_data_df[ret_col].values[sequence_length:]
    ret_train = ret_seq_full[:len(y_tr)]
    mu_c = np.array([ret_train[y_tr==c].mean() if np.any(y_tr==c) else 0.0 for c in range(K)], dtype=np.float32)


    taus = None
    temperature = 1.0
    try:
        model.eval()
        batch = 256
        logits_list = []
        for start in range(0, len(X_val), batch):
            xb = torch.from_numpy(X_val[start:start+batch].astype(np.float32)).to(device)
            with torch.no_grad():
                logits = model(xb)
            logits_list.append(logits.cpu().numpy())
        if logits_list:
            val_logits = np.vstack(logits_list)
            T_star, taus = tune_temperature_and_taus(
                Z_val=val_logits,
                y_val_idx=y_val,
                K=K,
                T_grid=np.linspace(0.6, 2.5, 15),
                tau_grid=np.linspace(0.2, 0.8, 31),
                lambda_balance=0.05,
                target_priors="uniform",
                coord_rounds=3,
            )
            temperature = float(T_star)
            print(f"[CAL] {ticker}: taus={np.round(taus, 3)} | temperature={temperature:.3f}")
        else:
            print(f"[CAL] {ticker}: no validation logits -> skipping calibration")
    except Exception as exc:
        print(f"[CAL] {ticker}: calibration failed ({exc})")
        taus = None
        temperature = 1.0

    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt"))
    joblib.dump(scaler, os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
    joblib.dump(BUCKET_BINS, os.path.join(model_save_path, f"{ticker}_edges_H{H}.pkl"))
    joblib.dump(mu_c, os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))
    if taus is not None and len(taus) == (K - 1) and np.all(np.isfinite(taus)):
        joblib.dump(taus, os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored taus")
    if temperature is not None and np.isfinite(temperature):
        joblib.dump(float(temperature), os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored temperature scale {temperature:.3f}")
    print(f"[SAVE] {ticker}: artifacts persisted (H={H})")

    del model, scaler, train_loader, val_loader, train_ds, val_ds
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [26]:

def predict_next_horizon(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         H: int,
                         K: int = 6,
                         head: str = "CORAL") -> dict | None:
    """
    Ordinal inference with optional calibration artifacts. Returns class probs plus
    summary stats so the simulator can log decisions.
    """
    try:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt")
        if not os.path.isfile(state_dict_path):
            return None

        scaler   = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        seq_len  = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
        mu_c     = joblib.load(os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))

        taus_path = os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl")
        T_path    = os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl")
        taus = joblib.load(taus_path) if os.path.isfile(taus_path) else None
        temperature = float(joblib.load(T_path)) if os.path.isfile(T_path) else 1.0

        n_features = len(feature_cols)
        model = LSTMOrdinal(n_features=n_features, head=head.upper(), K=K).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    if 'CALIBRATION_LOGGED' not in globals():
        globals()['CALIBRATION_LOGGED'] = set()
    if ticker not in CALIBRATION_LOGGED:
        if taus is not None:
            print(f"[CAL] {ticker}: loaded taus {np.round(taus,3)}")
        else:
            print(f"[CAL] {ticker}: no taus artifact found")
        print(f"[CAL] {ticker}: temperature scaling {temperature:.3f}")
        CALIBRATION_LOGGED.add(ticker)

    contiguous = identify_contiguous_periods(company_data_df)
    if not contiguous:
        return None
    start, end = contiguous[-1]
    period = company_data_df.iloc[start:end+1]
    if len(period) < seq_len:
        return None

    try:
        last_seq = period.tail(seq_len)
        X_scaled = scaler.transform(last_seq[feature_cols])
    except Exception:
        return None

    x = torch.from_numpy(np.asarray([X_scaled], dtype=np.float32)).to(device)

    with torch.no_grad():
        z = model(x)
        if temperature and temperature > 0 and temperature != 1.0:
            z = z / temperature
        P_cum = torch.sigmoid(z).cpu().numpy()
        P_cum = monotone_repair_numpy(P_cum)
        Pc    = ordinal_to_class_probs(P_cum)

    mu_c = np.asarray(mu_c, dtype=np.float32).reshape(-1)
    if mu_c.shape[0] != K:
        return None
    expected_rise = float((Pc[0] * mu_c).sum())

    top_bucket_idx = K - 1
    prob_top_bucket = float(Pc[0, top_bucket_idx])
    bucket_idx = int(np.argmax(Pc[0]))

    class_idx = None
    if taus is not None:
        taus = np.asarray(taus, dtype=np.float32).reshape(-1)
        if taus.shape[0] == (K - 1):
            class_idx = int(decode_ordinal_with_taus(P_cum, taus=taus)[0])

    positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
    prob_up = float(Pc[0, positive_buckets].sum()) if positive_buckets else prob_top_bucket

    return {
        'ticker': ticker,
        'expected_rise': expected_rise,
        'predicted_prob': prob_up,  # probability of positive move
        'prob_up': prob_up,
        'prob_bucket_top': prob_top_bucket,
        'bucket_idx': bucket_idx,
        'class_idx': class_idx,
        'class_probs': Pc[0].tolist(),
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [27]:
def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                              total_capital: float, sector_threshold: float,
                              kelly_fraction: float, top_k: int = 3, softmax_alpha: float = 1) -> pd.DataFrame:
    """Pick one name per sector via softmax over top-K expected_rise, then size with Kelly."""
    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")
    df = daily_predictions_df.copy()

    if 'prob_up' not in df.columns and 'class_probs' in df.columns:
        positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
        def _sum_up(probs):
            if isinstance(probs, (list, tuple)) and len(probs) == K and positive_buckets:
                return float(sum(probs[i] for i in positive_buckets))
            return np.nan
        df['prob_up'] = df['class_probs'].apply(_sum_up)

    if 'prob_up' not in df.columns and 'predicted_prob' in df.columns:
        df['prob_up'] = df['predicted_prob']

    if 'expected_rise' not in df.columns:
        print("[PORT] Missing expected_rise; cannot size portfolio.")
        return pd.DataFrame()

    # base filters
    df = df[(df['prob_up'] >= sector_threshold) & (df['expected_rise'] > 0)]
    print(f"[PORT] {len(df)} tickers cleared prob_up ≥ {sector_threshold:.3f} and positive expected return.")
    if df.empty:
        return pd.DataFrame()

    candidates = []
    for _, row in df.iterrows():
        ticker = row['ticker']
        p_up = float(row['prob_up'])
        payout = payout_map.get(ticker, {})
        b = payout.get('b') if isinstance(payout, dict) else float(payout)
        if not np.isfinite(b) or b <= 0:
            continue
        kelly_pct = p_up - (1.0 - p_up) / b
        if kelly_pct <= 0:
            continue
        investment_fraction = min(MAX_POSITION_SIZE, kelly_pct * kelly_fraction)
        investment_fraction = max(0.0, investment_fraction)
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            continue
        enriched = row.to_dict()
        enriched.update({
            'kelly_pct': kelly_pct,
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount,
        })
        candidates.append(enriched)

    if not candidates:
        print("[PORT] All candidates rejected after quality filters.")
        return pd.DataFrame()

    cand_df = pd.DataFrame(candidates)

    rows = []
    alpha = max(softmax_alpha, 1e-6)
    for sector, group in cand_df.groupby('sector'):
        if group.empty:
            continue
        top_group = group.sort_values('expected_rise', ascending=False).head(max(1, top_k))
        logits = (top_group['expected_rise'].to_numpy() * 100.0 * alpha)
        logits = logits - logits.max()  # stabilize
        weights = np.exp(logits)
        probs = weights / weights.sum()
        choice_idx = np.random.choice(len(top_group), p=probs)
        choice = top_group.iloc[choice_idx]

        print(f"[PORT] Sector {sector}: sampled {choice['ticker']} from top-{len(top_group)} (expected={choice['expected_rise']:.4f}, p_up={choice['prob_up']:.3f})")

        rows.append({
            'ticker': choice['ticker'],
            'sector': sector,
            'prob_up': float(choice['prob_up']),
            'predicted_prob': float(choice['prob_up']),
            'expected_rise': choice['expected_rise'],
            'bucket_idx': choice.get('bucket_idx', np.nan),
            'investment_fraction': choice['investment_fraction'],
            'investment_amount': choice['investment_amount'],
        })

    if not rows:
        print("[PORT] All sector winners rejected after sizing.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [28]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    """Check the minimal set of artifacts needed for ordinal inference."""
    required = [
        f"{ticker}_lstmORD_H{H}.pt",      # model weights (ordinal head)
        f"{ticker}_scaler_H{H}.pkl",      # feature scaler
        f"{ticker}_seq_length_H{H}.pkl",  # sequence length
        f"{ticker}_mu_c_H{H}.pkl",        # per-class train means μ_c for expected return
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in required)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [29]:
def _project_to_simplex(v):
    v = np.asarray(v, dtype=np.float64)
    if v.size == 0:
        return v
    if np.all(v >= 0) and np.isclose(v.sum(), 1.0):
        return v
    u = np.sort(v)[::-1]
    cssv = np.cumsum(u) - 1.0
    ind = np.arange(1, len(v) + 1)
    cond = u - cssv / ind > 0
    if not np.any(cond):
        return np.ones_like(v) / len(v)
    rho = ind[cond][-1]
    theta = cssv[cond][-1] / rho
    w = np.maximum(v - theta, 0.0)
    return w


def _apply_max_weight_cap(w, max_w, tol=1e-8):
    if max_w is None:
        return w
    w = np.maximum(w, 0.0)
    if w.size == 0:
        return w
    cap = float(max_w)
    w = np.minimum(w, cap)
    total = w.sum()
    if total <= 0:
        return w
    if total > 1.0 + tol:
        w = _project_to_simplex(w)
        w = np.minimum(w, cap)
    if total < 1.0 - tol:
        remaining = 1.0 - w.sum()
        for _ in range(100):
            room = cap - w
            room[room < 0] = 0.0
            if room.sum() <= tol:
                break
            add = remaining * (room / room.sum())
            w += add
            remaining = 1.0 - w.sum()
            if abs(remaining) <= tol:
                break
    if w.sum() > 0:
        w = w / w.sum()
    return w


def compute_mpt_weights(mu, Sigma, risk_lambda=1.0, long_only=True,
                        ridge_eps=1e-4, max_weight=None,
                        use_equal_fallback=True):
    mu = np.asarray(mu, dtype=np.float64)
    n = mu.size
    if n == 0:
        return mu
    if Sigma is None:
        return np.ones(n) / n if use_equal_fallback else mu / np.maximum(mu.sum(), 1e-12)
    Sigma = np.asarray(Sigma, dtype=np.float64)
    if Sigma.shape != (n, n):
        return np.ones(n) / n if use_equal_fallback else mu / np.maximum(mu.sum(), 1e-12)

    Sigma_reg = Sigma + ridge_eps * np.eye(n)

    def _fallback():
        w = np.ones(n) / n if use_equal_fallback else np.maximum(mu, 0.0)
        w = w / np.maximum(w.sum(), 1e-12)
        return _apply_max_weight_cap(w, max_weight)

    try:
        try:
            import scipy.optimize as opt
            def obj(w):
                return -(mu @ w - risk_lambda * (w @ Sigma_reg @ w))
            cons = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1.0},)
            bounds = None
            if long_only:
                upper = max_weight if max_weight is not None else 1.0
                bounds = [(0.0, upper) for _ in range(n)]
            x0 = np.ones(n) / n
            res = opt.minimize(obj, x0, method='SLSQP', bounds=bounds, constraints=cons)
            if not res.success or not np.isfinite(res.x).all():
                raise ValueError('MPT optimization failed')
            w = res.x
        except Exception:
            inv = np.linalg.pinv(Sigma_reg)
            w = inv @ mu
            if long_only:
                w = np.maximum(w, 0.0)
            if w.sum() <= 0:
                return _fallback()
            w = w / w.sum()
        if long_only:
            w = _apply_max_weight_cap(w, max_weight)
        if not np.isfinite(w).all() or w.sum() <= 0:
            return _fallback()
        return w
    except Exception:
        return _fallback()


def build_covariance_matrix(master_df, tickers, end_date, window_days, min_obs=20):
    df = master_df[master_df['date'] < end_date].copy()
    if df.empty:
        return None, []
    df = df[df['ticker'].isin(tickers)].copy()
    if df.empty:
        return None, []
    df['date'] = pd.to_datetime(df['date'])
    unique_dates = sorted(df['date'].unique())
    if not unique_dates:
        return None, []
    if len(unique_dates) > window_days:
        unique_dates = unique_dates[-window_days:]
    df = df[df['date'].isin(unique_dates)]
    pivot = df.pivot_table(index='date', columns='ticker', values='close', aggfunc='last').sort_index()
    rets = pivot.pct_change().dropna(how='all')
    if rets.empty:
        return None, []
    min_obs = max(5, min_obs)
    good_cols = [c for c in rets.columns if rets[c].count() >= min_obs]
    rets = rets[good_cols]
    if rets.shape[0] < min_obs or rets.shape[1] == 0:
        return None, []
    Sigma = rets.cov().values
    return Sigma, list(rets.columns)

In [ ]:
def compute_mpt_weights_for_today(
    tickers,
    historical_data,
    current_date,
    mu,
    window_days=MPT_WINDOW_DAYS,
    ridge_eps=MPT_RIDGE_EPS,
    risk_aversion=MPT_LAMBDA,
    long_only=MPT_LONG_ONLY,
    max_weight=MPT_MAX_WEIGHT,
    use_equal_fallback=MPT_USE_EQUAL_FALLBACK,
):
    if len(tickers) == 0:
        return np.array([]), True

    Sigma, cov_tickers = build_covariance_matrix(
        historical_data,
        tickers,
        current_date,
        window_days=window_days,
        min_obs=20,
    )
    if Sigma is None or set(cov_tickers) != set(tickers):
        w = np.ones(len(tickers)) / len(tickers)
        return w, True

    order = [cov_tickers.index(t) for t in tickers]
    Sigma = Sigma[np.ix_(order, order)]

    w = compute_mpt_weights(
        mu,
        Sigma,
        risk_lambda=risk_aversion,
        long_only=long_only,
        ridge_eps=ridge_eps,
        max_weight=max_weight,
        use_equal_fallback=use_equal_fallback,
    )
    if not np.isfinite(w).all() or w.sum() <= 0:
        w = np.ones(len(tickers)) / len(tickers)
        return w, True
    return w, False


def apply_allocation_mode(
    investment_df,
    historical_data,
    current_date,
    capital,
    open_positions,
    allocation_mode=ALLOCATION_MODE,
):
    meta = {
        'allocation_mode': allocation_mode,
        'budget_pre_caps': 0.0,
        'mpt_used': False,
        'mpt_fallback_used': False,
        'weights': None,
    }

    if investment_df is None or investment_df.empty:
        return investment_df, meta

    mode = str(allocation_mode).upper().strip()
    if mode not in {"KELLY_ONLY", "HYBRID_KELLY_MPT", "MPT_ONLY"}:
        mode = "KELLY_ONLY"
        meta['allocation_mode'] = mode

    budget_pre_caps = float(investment_df['investment_amount'].sum())
    tickers = investment_df['ticker'].tolist()

    if mode == "KELLY_ONLY":
        meta['budget_pre_caps'] = budget_pre_caps
        return investment_df, meta

    if mode == "MPT_ONLY":
        equity = float(capital + sum(p['invest'] for p in open_positions))
        budget_pre_caps = float(MPT_ONLY_BUDGET_FRACTION * equity)

    meta['budget_pre_caps'] = budget_pre_caps

    if len(tickers) == 1:
        if mode == "MPT_ONLY":
            meta['mpt_used'] = True
            meta['weights'] = {tickers[0]: 1.0}
            investment_df = investment_df.copy()
            investment_df['investment_amount'] = budget_pre_caps
        return investment_df, meta

    mu = investment_df['expected_rise'].astype(float).values
    w, fallback = compute_mpt_weights_for_today(
        tickers,
        historical_data,
        current_date,
        mu,
    )
    meta['mpt_used'] = True
    meta['mpt_fallback_used'] = bool(fallback)

    if np.isfinite(w).all() and w.sum() > 0:
        w = w / w.sum()
        meta['weights'] = {t: float(w[i]) for i, t in enumerate(tickers)}
        investment_df = investment_df.copy()
        investment_df['investment_amount'] = budget_pre_caps * w
        return investment_df, meta

    return investment_df, meta

In [30]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # precompute realized returns for settlement only (not used for training)
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker', 'date'])[ret_col].to_dict()
    close_lookup = master_df.set_index(['ticker', 'date'])['close'].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    early_exit_lookup = None
    early_exit_threshold = 0.4  # exit when p_up_1d < threshold (downside signal)
    if H > 1:
        early_exit_path = 'stocknet-dataset/h1_early_exit_df.parquet'
        if not os.path.exists(early_exit_path):
            early_exit_path = 'stocknet-dataset/h1_exit_df.parquet'
        if os.path.exists(early_exit_path):
            try:
                h1_exit_df = pd.read_parquet(early_exit_path)
                h1_exit_df['date'] = pd.to_datetime(h1_exit_df['date'])
                h1_exit_df = h1_exit_df.drop_duplicates(subset=['date', 'ticker'])
                early_exit_lookup = h1_exit_df.set_index(['date', 'ticker'])['p_up_1d'].to_dict()
                print(f"[EARLY EXIT] Loaded {len(h1_exit_df)} signals from {early_exit_path}")
            except Exception as exc:
                print(f"[EARLY EXIT] Failed to load signals: {exc}")
                early_exit_lookup = None
        else:
            print("[EARLY EXIT] No 1d exit signal file found; early exit disabled.")

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    # overlapping book
    open_positions = []  # each: {'ticker','invest','entry_date','exit_date'}
    prev_equity_end = capital
    total_early_exits = 0
    early_exit_pnl_total = 0.0
    early_exit_counterfactual_total = 0.0
    early_exit_counterfactual_count = 0

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = pd.to_datetime(unique_dates[i])
        prev_date = pd.to_datetime(unique_dates[i-1]) if i > 0 else None
        early_exits_today = 0

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                if pd.notna(rH):
                    pnl = pos['invest'] * rH
                    total_pnl_today += pnl
                    print(f"[EXIT] {current_date}: {pos['ticker']} r={rH:.4f}, PnL=${pnl:.2f}")
                    capital += pos['invest'] + pnl  # release capital
            else:
                still_open.append(pos)
        open_positions = still_open

        # early-exit check (signal at current_date predicts tomorrow)
        if H > 1 and early_exit_lookup:
            remaining = []
            for pos in open_positions:
                p_up_1d = early_exit_lookup.get((current_date, pos['ticker']))
                if p_up_1d is None or not np.isfinite(p_up_1d):
                    remaining.append(pos)
                    continue
                if float(p_up_1d) < early_exit_threshold:
                    entry_close = close_lookup.get((pos['ticker'], pos['entry_date']))
                    exit_close = close_lookup.get((pos['ticker'], current_date))
                    if entry_close is None or exit_close is None:
                        remaining.append(pos)
                        continue
                    if not np.isfinite(entry_close) or not np.isfinite(exit_close):
                        remaining.append(pos)
                        continue
                    r_exit = (exit_close / entry_close) - 1.0
                    pnl = pos['invest'] * r_exit
                    total_pnl_today += pnl
                    capital += pos['invest'] + pnl
                    early_exits_today += 1
                    total_early_exits += 1
                    early_exit_pnl_total += pnl

                    planned_rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                    if pd.notna(planned_rH):
                        early_exit_counterfactual_total += pos['invest'] * planned_rH
                        early_exit_counterfactual_count += 1

                    print(
                        f"[EARLY EXIT] {current_date}: {pos['ticker']} p_up_1d={p_up_1d:.3f} -> exit; "
                        f"r={r_exit:.4f}, PnL=${pnl:.2f}"
                    )
                else:
                    remaining.append(pos)
            open_positions = remaining

        # equity at START (after settlements, before new entries)
        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # build prediction universe using info strictly before current_date
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        cutoff = current_date - pd.Timedelta(days=H)
        historical_data = historical_data[historical_data['date'] < cutoff]
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if prev_date is None:
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == prev_date]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                print("Retraining model for ticker:", ticker)
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)
        print(f"[SIM] {current_date}: built {len(daily_predictions_df)} predictions")
        if (not daily_predictions_df.empty and
            'predicted_prob' not in daily_predictions_df.columns and
            'calibrated_prediction' not in daily_predictions_df.columns):
            print("[WARN] predicted_prob missing from daily_predictions_df columns:",
                  sorted(daily_predictions_df.columns))


        # size raw trades via Kelly
        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df,
            payout_map_day,
            capital,
            sector_threshold=SECTOR_CONFIDENCE_THRESHOLD,
            kelly_fraction=KELLY_FRACTION,
        )
        if investment_decision_df.empty:
            print(f"[SIM] {current_date}: no trades proposed today.")
        else:
            print(f"[SIM] {current_date}: {len(investment_decision_df)} trades proposed.")

        investment_decision_df, alloc_meta = apply_allocation_mode(
            investment_decision_df,
            historical_data,
            current_date,
            capital,
            open_positions,
            allocation_mode=ALLOCATION_MODE,
        )

        # entry logic (allow_overlap controls laddering)
        exit_idx = i + H
        if exit_idx < len(unique_dates):
            exit_date = pd.to_datetime(unique_dates[exit_idx])
        else:
            exit_date = None  # can't open new trades that we cannot exit within data

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            # ensure the column exists even if future changes rename it
            if 'predicted_prob' not in investment_decision_df.columns:
                if 'calibrated_prediction' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'calibrated_prediction': 'predicted_prob'}
                    )
                elif 'score' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'score': 'predicted_prob'}
                    )
                else:
                    # nothing to sort by
                    investment_decision_df = pd.DataFrame()

            if not investment_decision_df.empty:
                investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)


            # current exposures (post-settlement)
            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0
            budget_post_caps = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                # per-ticker ladder depth
                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue  # no overlapping allowed

                # base size from Kelly (already scaled by KELLY_FRACTION)
                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))  # vs equity

                # clamp by remaining budgets
                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                # lock capital and record position
                capital -= amt
                total_open += amt
                new_today_open += amt
                budget_post_caps += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})
                print(f"[TRADE] {current_date}: allocated ${amt:.2f} to {tkr} exiting on {exit_date}")

        # equity at END (after entries)
        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        # log the day
        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,  # cash only
            'capital_end': capital,                               # cash only
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,                # realized PnL today
            'daily_return': daily_return,
            'early_exits_today': early_exits_today,
            'allocation_mode': alloc_meta['allocation_mode'],
            'budget_pre_caps': float(alloc_meta['budget_pre_caps']),
            'budget_post_caps': float(budget_post_caps) if 'budget_post_caps' in locals() else 0.0,
            'mpt_used': bool(alloc_meta['mpt_used']),
            'mpt_fallback_used': bool(alloc_meta['mpt_fallback_used']),
            'mpt_weights': alloc_meta.get('weights'),
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    print(f"[EARLY EXIT] Total early exits: {total_early_exits}")
    if total_early_exits > 0:
        print(f"[EARLY EXIT] PnL realized from early exits: ${early_exit_pnl_total:,.2f}")
        if early_exit_counterfactual_count > 0:
            print(
                f"[EARLY EXIT] PnL if held to horizon: ${early_exit_counterfactual_total:,.2f} "
                f"(n={early_exit_counterfactual_count})"
            )
            print(
                f"[EARLY EXIT] Delta vs hold-to-horizon: "
                f"${early_exit_pnl_total - early_exit_counterfactual_total:,.2f}"
            )
        else:
            print("[EARLY EXIT] Counterfactual PnL unavailable for early exits.")
    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [31]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [32]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_and_bimeta_features.parquet')

In [33]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)
# Exclude ticker with missing meta-features across all rows
master_df = master_df[master_df['ticker'] != 'GMRE']

columns_to_check = ['EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    'lstm_prob_up_1d', 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [34]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    # 'lstm_prob_up_1d', 
    # 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 
    'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
    
    
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength', 'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20']
Total number of features: 33

In [35]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

# Execute Pipeline

In [ ]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=5,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))

calculate_final_results(simulation_results, initial_capital)

# for mode in ["KELLY_ONLY", "HYBRID_KELLY_MPT", "MPT_ONLY"]:
#     ALLOCATION_MODE = mode
#     set_global_seeds(42)
#     print("=" * 80)
#     print(f"Running allocation mode: {mode}")
#     simulation_results = run_simulation(
#         master_df,
#         feature_columns,
#         initial_capital,
#         initial_training_days=INITIAL_TRAINING_DAYS,
#         H=5,
#         allow_overlap=True
#     )
#     calculate_final_results(simulation_results, initial_capital)

Starting simulation with 783 initial training days... (H=5)
[EARLY EXIT] Loaded 8613 signals from stocknet-dataset/h1_exit_df.parquet
Starting predictions from day 783 (after 783 training days)

Simulating Trading Days:   0%|          | 0/100 [00:00<?, ?it/s]

[CAL] AAPL: loaded taus [0.5  0.44 0.5  0.42 0.4 ]
[CAL] AAPL: temperature scaling 1.686
[CAL] ABB: loaded taus [0.78 0.78 0.7  0.46 0.44]
[CAL] ABB: temperature scaling 1.007
[CAL] ABBV: loaded taus [0.28 0.36 0.38 0.24 0.26]
[CAL] ABBV: temperature scaling 0.600
[CAL] AEP: loaded taus [0.52 0.46 0.34 0.28 0.24]
[CAL] AEP: temperature scaling 1.414
[CAL] AGFS: loaded taus [0.2  0.8  0.72 0.78 0.7 ]
[CAL] AGFS: temperature scaling 1.143
[CAL] AMGN: loaded taus [0.68 0.4  0.4  0.34 0.28]
[CAL] AMGN: temperature scaling 1.550
[CAL] AMZN: loaded taus [0.74 0.54 0.52 0.42 0.2 ]
[CAL] AMZN: temperature scaling 1.007
[CAL] BA: loaded taus [0.8  0.78 0.68 0.54 0.46]
[CAL] BA: temperature scaling 1.143
[CAL] BABA: loaded taus [0.8  0.74 0.68 0.48 0.34]
[CAL] BABA: temperature scaling 1.414
[CAL] BAC: loaded taus [0.72 0.6  0.48 0.5  0.48]
[CAL] BAC: temperature scaling 2.364
[CAL] BBL: loaded taus [0.8  0.58 0.5  0.38 0.26]
[CAL] BBL: temperature scaling 1.143
[CAL] BCH: loaded taus [0.76 0.46 0.48 0.5  0.44]
[CAL] BCH: temperature scaling 1.007
[CAL] BHP: loaded taus [0.8  0.78 0.6  0.42 0.32]
[CAL] BHP: temperature scaling 0.871
[CAL] BP: loaded taus [0.68 0.56 0.44 0.34 0.32]
[CAL] BP: temperature scaling 1.007
[CAL] BRK-A: loaded taus [0.8  0.72 0.66 0.46 0.56]
[CAL] BRK-A: temperature scaling 0.600
[CAL] BSAC: loaded taus [0.74 0.54 0.66 0.78 0.56]
[CAL] BSAC: temperature scaling 1.279
[CAL] BUD: loaded taus [0.76 0.68 0.54 0.56 0.5 ]
[CAL] BUD: temperature scaling 2.229
[CAL] C: loaded taus [0.72 0.76 0.8  0.52 0.48]
[CAL] C: temperature scaling 0.736
[CAL] CAT: loaded taus [0.78 0.6  0.5  0.34 0.24]
[CAL] CAT: temperature scaling 1.007
[CAL] CELG: loaded taus [0.52 0.68 0.58 0.36 0.6 ]
[CAL] CELG: temperature scaling 0.600
[CAL] CHL: loaded taus [0.78 0.46 0.44 0.26 0.2 ]
[CAL] CHL: temperature scaling 0.736
[CAL] CHTR: loaded taus [0.74 0.68 0.58 0.48 0.38]
[CAL] CHTR: temperature scaling 1.686
[CAL] CMCSA: loaded taus [0.78 0.66 0.48 0.22 0.34]
[CAL] CMCSA: temperature scaling 0.600
[CAL] CODI: loaded taus [0.6  0.68 0.6  0.42 0.7 ]
[CAL] CODI: temperature scaling 0.736
[CAL] CSCO: loaded taus [0.52 0.4  0.36 0.28 0.28]
[CAL] CSCO: temperature scaling 2.229
[CAL] CVX: loaded taus [0.46 0.78 0.52 0.4  0.66]
[CAL] CVX: temperature scaling 0.600
[CAL] D: loaded taus [0.78 0.54 0.46 0.36 0.4 ]
[CAL] D: temperature scaling 0.736
[CAL] DHR: loaded taus [0.78 0.66 0.2  0.38 0.26]
[CAL] DHR: temperature scaling 1.143
[CAL] DIS: loaded taus [0.7  0.4  0.46 0.32 0.34]
[CAL] DIS: temperature scaling 1.007
[CAL] DUK: loaded taus [0.8  0.52 0.44 0.28 0.22]
[CAL] DUK: temperature scaling 0.736
[CAL] EXC: loaded taus [0.78 0.78 0.52 0.48 0.54]
[CAL] EXC: temperature scaling 0.871
[CAL] FB: loaded taus [0.54 0.5  0.44 0.36 0.3 ]
[CAL] FB: temperature scaling 1.957
[CAL] GD: loaded taus [0.2  0.2  0.42 0.52 0.48]
[CAL] GD: temperature scaling 0.600
[CAL] GE: loaded taus [0.8  0.42 0.5  0.46 0.34]
[CAL] GE: temperature scaling 0.736
[CAL] GOOG: loaded taus [0.8  0.66 0.52 0.36 0.3 ]
[CAL] GOOG: temperature scaling 0.736
[CAL] HD: loaded taus [0.5  0.44 0.42 0.22 0.24]
[CAL] HD: temperature scaling 0.871
[CAL] HON: loaded taus [0.78 0.76 0.5  0.66 0.52]
[CAL] HON: temperature scaling 2.093
[CAL] HRG: loaded taus [0.68 0.56 0.48 0.4  0.34]
[CAL] HRG: temperature scaling 1.550
[CAL] HSBC: loaded taus [0.68 0.62 0.56 0.48 0.46]
[CAL] HSBC: temperature scaling 2.229
[CAL] IEP: loaded taus [0.68 0.6  0.52 0.48 0.44]
[CAL] IEP: temperature scaling 2.500
[CAL] INTC: loaded taus [0.6  0.68 0.5  0.52 0.42]
[CAL] INTC: temperature scaling 2.364
[CAL] JNJ: loaded taus [0.52 0.56 0.4  0.34 0.32]
[CAL] JNJ: temperature scaling 0.736
[CAL] JPM: loaded taus [0.7  0.6  0.48 0.48 0.5 ]
[CAL] JPM: temperature scaling 1.957
[CAL] KO: loaded taus [0.66 0.5  0.34 0.26 0.3 ]
[CAL] KO: temperature scaling 0.600
[CAL] LMT: loaded taus [0.54 0.5  0.46 0.44 0.4 ]
[CAL] LMT: temperature scaling 2.500
[CAL] MA: loaded taus [0.78 0.64 0.44 0.5  0.46]
[CAL] MA: temperature scaling 1.414
[CAL] MCD: loaded taus [0.68 0.52 0.52 0.5  0.64]
[CAL] MCD: temperature scaling 2.364
[CAL] MDT: loaded taus [0.78 0.56 0.6  0.48 0.44]
[CAL] MDT: temperature scaling 1.007
[CAL] MMM: loaded taus [0.62 0.2  0.52 0.44 0.38]
[CAL] MMM: temperature scaling 1.957
[CAL] MO: loaded taus [0.72 0.8  0.74 0.4  0.56]
[CAL] MO: temperature scaling 0.871
[CAL] MRK: loaded taus [0.7  0.6  0.48 0.46 0.44]
[CAL] MRK: temperature scaling 1.821
[CAL] MSFT: loaded taus [0.62 0.52 0.46 0.36 0.3 ]
[CAL] MSFT: temperature scaling 1.821
[CAL] NEE: loaded taus [0.78 0.74 0.56 0.5  0.42]
[CAL] NEE: temperature scaling 1.007
[CAL] NGG: loaded taus [0.52 0.74 0.7  0.78 0.52]
[CAL] NGG: temperature scaling 0.600
[CAL] NVS: loaded taus [0.8  0.5  0.58 0.44 0.42]
[CAL] NVS: temperature scaling 1.007
[CAL] ORCL: loaded taus [0.74 0.6  0.5  0.5  0.48]
[CAL] ORCL: temperature scaling 2.093
[CAL] PCG: loaded taus [0.68 0.52 0.5  0.46 0.42]
[CAL] PCG: temperature scaling 2.093
[CAL] PCLN: loaded taus [0.76 0.66 0.48 0.4  0.36]
[CAL] PCLN: temperature scaling 1.279
[CAL] PEP: loaded taus [0.54 0.52 0.66 0.74 0.46]
[CAL] PEP: temperature scaling 1.414
[CAL] PFE: loaded taus [0.54 0.48 0.46 0.34 0.32]
[CAL] PFE: temperature scaling 0.600
[CAL] PG: loaded taus [0.46 0.52 0.46 0.34 0.44]
[CAL] PG: temperature scaling 1.143
[CAL] PICO: loaded taus [0.54 0.44 0.42 0.32 0.5 ]
[CAL] PICO: temperature scaling 1.279
[CAL] PM: loaded taus [0.74 0.5  0.4  0.34 0.3 ]
[CAL] PM: temperature scaling 0.871
[CAL] PPL: loaded taus [0.56 0.42 0.34 0.26 0.38]
[CAL] PPL: temperature scaling 0.871
[CAL] PTR: loaded taus [0.64 0.5  0.52 0.42 0.32]
[CAL] PTR: temperature scaling 1.550
[CAL] RDS-B: loaded taus [0.72 0.52 0.5  0.38 0.34]
[CAL] RDS-B: temperature scaling 1.143
[CAL] REX: loaded taus [0.8  0.28 0.48 0.58 0.58]
[CAL] REX: temperature scaling 0.871
[CAL] SLB: loaded taus [0.66 0.48 0.54 0.38 0.3 ]
[CAL] SLB: temperature scaling 1.686
[CAL] SNP: loaded taus [0.8  0.78 0.56 0.5  0.4 ]
[CAL] SNP: temperature scaling 0.871
[CAL] SNY: loaded taus [0.66 0.8  0.8  0.56 0.54]
[CAL] SNY: temperature scaling 0.736
[CAL] SO: loaded taus [0.5  0.44 0.34 0.26 0.28]
[CAL] SO: temperature scaling 0.736
[CAL] SPLP: loaded taus [0.44 0.76 0.6  0.5  0.4 ]
[CAL] SPLP: temperature scaling 0.600
[CAL] SRE: loaded taus [0.8  0.58 0.5  0.4  0.34]
[CAL] SRE: temperature scaling 0.871
[CAL] T: loaded taus [0.66 0.56 0.46 0.38 0.46]
[CAL] T: temperature scaling 0.600
[CAL] TM: loaded taus [0.44 0.48 0.54 0.26 0.4 ]
[CAL] TM: temperature scaling 1.007
[CAL] TOT: loaded taus [0.68 0.7  0.5  0.34 0.32]
[CAL] TOT: temperature scaling 1.143
[CAL] TSM: loaded taus [0.54 0.48 0.4  0.3  0.22]
[CAL] TSM: temperature scaling 1.686

Simulating Trading Days:   1%|          | 1/100 [00:01<02:06,  1.28s/it]

[CAL] UL: loaded taus [0.74 0.46 0.62 0.52 0.7 ]
[CAL] UL: temperature scaling 1.143
[CAL] UN: loaded taus [0.68 0.6  0.5  0.5  0.5 ]
[CAL] UN: temperature scaling 2.093
[CAL] UNH: loaded taus [0.34 0.34 0.42 0.34 0.46]
[CAL] UNH: temperature scaling 0.736
[CAL] UPS: loaded taus [0.7  0.54 0.5  0.42 0.34]
[CAL] UPS: temperature scaling 1.686
[CAL] UTX: loaded taus [0.6  0.5  0.38 0.34 0.48]
[CAL] UTX: temperature scaling 1.007
[CAL] V: loaded taus [0.72 0.5  0.54 0.54 0.52]
[CAL] V: temperature scaling 1.821
[CAL] VZ: loaded taus [0.7  0.78 0.54 0.48 0.42]
[CAL] VZ: temperature scaling 0.736
[CAL] WFC: loaded taus [0.74 0.48 0.48 0.38 0.3 ]
[CAL] WFC: temperature scaling 1.821
[CAL] WMT: loaded taus [0.7  0.66 0.54 0.5  0.5 ]
[CAL] WMT: temperature scaling 2.500
[CAL] XOM: loaded taus [0.72 0.68 0.44 0.48 0.42]
[CAL] XOM: temperature scaling 1.550
[SIM] 2017-04-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.943)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0022, p_up=0.709)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0012, p_up=0.615)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.542)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0090, p_up=0.846)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0050, p_up=0.901)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0026, p_up=0.614)
[SIM] 2017-04-11 00:00:00: 7 trades proposed.
[TRADE] 2017-04-11 00:00:00: allocated $8594.46 to AAPL exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $8594.46 to VZ exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $8594.46 to BABA exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $4216.61 to LMT exiting on 2017-04-19 00:00:00

Simulating Trading Days:   2%|▏         | 2/100 [00:02<01:57,  1.20s/it]

[SIM] 2017-04-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0004, p_up=0.549)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0049, p_up=0.586)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0022, p_up=0.712)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0033, p_up=0.720)
[PORT] Sector Industrial Goods: sampled MMM from top-3 (expected=0.0038, p_up=0.678)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0016, p_up=0.572)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0051, p_up=0.906)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0020, p_up=0.491)
[SIM] 2017-04-12 00:00:00: 8 trades proposed.
[TRADE] 2017-04-12 00:00:00: allocated $4562.83 to VZ exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $4562.83 to ABBV exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $4562.83 to MMM exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $4562.83 to MO exiting on 2017-04-20 00:00:00
[EARLY EXIT] 2017-04-13 00:00:00: ABBV p_up_1d=0.317 -> exit; r=-0.0037, PnL=$-17.01

Simulating Trading Days:   3%|▎         | 3/100 [00:03<01:57,  1.21s/it]

[SIM] 2017-04-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-1 (expected=0.0009, p_up=0.697)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0013, p_up=0.660)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0052, p_up=0.616)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0023, p_up=0.977)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0044, p_up=0.817)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.548)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0090, p_up=0.849)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0050, p_up=0.903)
[PORT] Sector Utilities: sampled NGG from top-1 (expected=0.0007, p_up=0.934)
[SIM] 2017-04-13 00:00:00: 9 trades proposed.
[TRADE] 2017-04-13 00:00:00: allocated $6162.34 to VZ exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $7246.06 to BABA exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $4830.08 to ABBV exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $6584.97 to MO exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $1476.15 to LMT exiting on 2017-04-21 00:00:00
[EARLY EXIT] 2017-04-17 00:00:00: ABBV p_up_1d=0.322 -> exit; r=0.0028, PnL=$13.56

Simulating Trading Days:   4%|▍         | 4/100 [00:04<01:52,  1.18s/it]

[SIM] 2017-04-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-1 (expected=0.0015, p_up=0.807)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0019, p_up=0.741)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.944)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.723)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0022, p_up=0.829)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0067, p_up=0.906)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.549)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0050, p_up=0.901)
[PORT] Sector Utilities: sampled NGG from top-1 (expected=0.0007, p_up=0.938)
[SIM] 2017-04-17 00:00:00: 9 trades proposed.
[TRADE] 2017-04-17 00:00:00: allocated $4839.57 to AAPL exiting on 2017-04-24 00:00:00

Simulating Trading Days:   5%|▌         | 5/100 [00:05<01:49,  1.15s/it]

[SIM] 2017-04-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-1 (expected=0.0019, p_up=0.882)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0021, p_up=0.762)
[PORT] Sector Consumer Goods: sampled BUD from top-3 (expected=0.0022, p_up=0.548)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0041, p_up=0.532)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0059, p_up=0.882)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.545)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.556)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0049, p_up=0.899)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0019, p_up=0.518)
[SIM] 2017-04-18 00:00:00: 9 trades proposed.
[EXIT] 2017-04-19 00:00:00: AAPL r=-0.0067, PnL=$-57.65
[EXIT] 2017-04-19 00:00:00: VZ r=0.0049, PnL=$42.35
[EXIT] 2017-04-19 00:00:00: BABA r=0.0029, PnL=$24.90
[EXIT] 2017-04-19 00:00:00: LMT r=-0.0024, PnL=$-9.98

Simulating Trading Days:   6%|▌         | 6/100 [00:06<01:47,  1.14s/it]

[SIM] 2017-04-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-1 (expected=0.0020, p_up=0.926)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0022, p_up=0.781)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.945)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.727)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0054, p_up=0.863)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.541)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.562)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0049, p_up=0.895)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.946)
[SIM] 2017-04-19 00:00:00: 9 trades proposed.
[TRADE] 2017-04-19 00:00:00: allocated $8328.41 to AAPL exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $6933.54 to VZ exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $8328.41 to ABBV exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $6408.50 to CHTR exiting on 2017-04-26 00:00:00
[EXIT] 2017-04-20 00:00:00: VZ r=-0.0104, PnL=$-47.57
[EXIT] 2017-04-20 00:00:00: MMM r=0.0077, PnL=$35.12
[EXIT] 2017-04-20 00:00:00: MO r=-0.0104, PnL=$-47.42
[EARLY EXIT] 2017-04-20 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0052, PnL=$43.32

Simulating Trading Days:   7%|▋         | 7/100 [00:08<01:46,  1.14s/it]

[SIM] 2017-04-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0000, p_up=0.633)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0022, p_up=0.777)
[PORT] Sector Consumer Goods: sampled BUD from top-3 (expected=0.0022, p_up=0.543)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.731)
[PORT] Sector Healthcare: sampled NVS from top-3 (expected=0.0013, p_up=0.727)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0068, p_up=0.915)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.803)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0048, p_up=0.617)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0022, p_up=0.543)
[SIM] 2017-04-20 00:00:00: 9 trades proposed.
[TRADE] 2017-04-20 00:00:00: allocated $4770.19 to GD exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $4770.19 to BABA exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $1109.97 to SPLP exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $1308.36 to MA exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $4770.19 to CHL exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $1133.11 to BUD exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $1218.75 to EXC exiting on 2017-04-27 00:00:00
[EXIT] 2017-04-21 00:00:00: VZ r=-0.0282, PnL=$-173.64
[EXIT] 2017-04-21 00:00:00: BABA r=0.0263, PnL=$190.67
[EXIT] 2017-04-21 00:00:00: MO r=0.0024, PnL=$15.70
[EXIT] 2017-04-21 00:00:00: LMT r=0.0190, PnL=$28.04
[EARLY EXIT] 2017-04-21 00:00:00: SPLP p_up_1d=0.390 -> exit; r=0.0000, PnL=$0.00
[EARLY EXIT] 2017-04-21 00:00:00: MA p_up_1d=0.381 -> exit; r=-0.0028, PnL=$-3.65
[EARLY EXIT] 2017-04-21 00:00:00: CHL p_up_1d=0.394 -> exit; r=-0.0007, PnL=$-3.54

Simulating Trading Days:   8%|▊         | 8/100 [00:09<01:44,  1.14s/it]

[SIM] 2017-04-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0020, p_up=0.966)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0020, p_up=0.753)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0022, p_up=0.837)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0040, p_up=0.525)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0038, p_up=0.772)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0040, p_up=0.536)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.790)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0023, p_up=0.923)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0022, p_up=0.540)
[SIM] 2017-04-21 00:00:00: 9 trades proposed.
[TRADE] 2017-04-21 00:00:00: allocated $6902.64 to BABA exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $6902.64 to ABBV exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $6902.64 to LMT exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $6902.64 to V exiting on 2017-04-28 00:00:00
[EXIT] 2017-04-24 00:00:00: AAPL r=0.0128, PnL=$61.76
[EARLY EXIT] 2017-04-24 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0132, PnL=$90.85

Simulating Trading Days:   9%|▉         | 9/100 [00:10<01:43,  1.13s/it]

[SIM] 2017-04-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0006, p_up=0.704)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0017, p_up=0.722)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.947)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0040, p_up=0.519)
[PORT] Sector Healthcare: sampled NVS from top-3 (expected=0.0014, p_up=0.762)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0040, p_up=0.538)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.568)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0023, p_up=0.932)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0021, p_up=0.530)
[SIM] 2017-04-24 00:00:00: 9 trades proposed.
[TRADE] 2017-04-24 00:00:00: allocated $4234.73 to AAPL exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $4234.73 to CHTR exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $4234.73 to LMT exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $3155.26 to V exiting on 2017-05-01 00:00:00

Simulating Trading Days:  10%|█         | 10/100 [00:11<01:52,  1.25s/it]

[SIM] 2017-04-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0020, p_up=0.959)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0016, p_up=0.708)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0022, p_up=0.826)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.745)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0073, p_up=0.606)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0070, p_up=0.933)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0088, p_up=0.766)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.645)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0005, p_up=0.959)
[SIM] 2017-04-25 00:00:00: 9 trades proposed.
[EXIT] 2017-04-26 00:00:00: AAPL r=0.0213, PnL=$177.60
[EXIT] 2017-04-26 00:00:00: VZ r=-0.0323, PnL=$-223.85
[EXIT] 2017-04-26 00:00:00: CHTR r=0.0353, PnL=$226.48

Simulating Trading Days:  11%|█         | 11/100 [00:13<02:00,  1.35s/it]

[SIM] 2017-04-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0008, p_up=0.727)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0015, p_up=0.687)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0058, p_up=0.676)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.514)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0032, p_up=0.707)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0038, p_up=0.862)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0071, p_up=0.670)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0024, p_up=0.934)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0020, p_up=0.525)
[SIM] 2017-04-26 00:00:00: 9 trades proposed.
[TRADE] 2017-04-26 00:00:00: allocated $3583.10 to ABB exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $2021.61 to ABBV exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $4845.56 to MO exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $4845.56 to AMZN exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $4086.42 to V exiting on 2017-05-03 00:00:00
[EXIT] 2017-04-27 00:00:00: GD r=0.0367, PnL=$174.96
[EXIT] 2017-04-27 00:00:00: BABA r=0.0219, PnL=$104.31
[EXIT] 2017-04-27 00:00:00: BUD r=0.0288, PnL=$32.61
[EXIT] 2017-04-27 00:00:00: EXC r=-0.0060, PnL=$-7.30
[EARLY EXIT] 2017-04-27 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0158, PnL=$32.01

Simulating Trading Days:  12%|█▏        | 12/100 [00:14<01:55,  1.31s/it]

[SIM] 2017-04-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0008, p_up=0.610)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0014, p_up=0.677)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.946)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.507)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.910)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.540)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0087, p_up=0.755)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0029, p_up=0.777)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0004, p_up=0.966)
[SIM] 2017-04-27 00:00:00: 9 trades proposed.
[TRADE] 2017-04-27 00:00:00: allocated $5367.89 to AAPL exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $5367.89 to CELG exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $1139.52 to VZ exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $4688.53 to BABA exiting on 2017-05-04 00:00:00
[EXIT] 2017-04-28 00:00:00: BABA r=0.0211, PnL=$145.85
[EXIT] 2017-04-28 00:00:00: LMT r=-0.0133, PnL=$-92.00
[EXIT] 2017-04-28 00:00:00: V r=0.0008, PnL=$5.30

Simulating Trading Days:  13%|█▎        | 13/100 [00:15<01:49,  1.26s/it]

[SIM] 2017-04-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0012, p_up=0.756)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0011, p_up=0.647)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0064, p_up=0.733)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.505)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.944)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0073, p_up=0.949)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0087, p_up=0.749)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0024, p_up=0.936)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0004, p_up=0.968)
[SIM] 2017-04-28 00:00:00: 9 trades proposed.
[TRADE] 2017-04-28 00:00:00: allocated $7059.31 to GD exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $7059.31 to CELG exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $6630.69 to BABA exiting on 2017-05-05 00:00:00
[EXIT] 2017-05-01 00:00:00: AAPL r=0.0205, PnL=$86.68
[EXIT] 2017-05-01 00:00:00: CHTR r=0.0111, PnL=$47.03
[EXIT] 2017-05-01 00:00:00: LMT r=-0.0282, PnL=$-119.28
[EXIT] 2017-05-01 00:00:00: V r=-0.0064, PnL=$-20.27

Simulating Trading Days:  14%|█▍        | 14/100 [00:16<01:44,  1.21s/it]

[SIM] 2017-05-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0012, p_up=0.748)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0009, p_up=0.615)
[PORT] Sector Consumer Goods: sampled BUD from top-3 (expected=0.0022, p_up=0.541)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.513)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0019, p_up=0.769)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0040, p_up=0.529)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.543)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0024, p_up=0.934)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0023, p_up=0.515)
[SIM] 2017-05-01 00:00:00: 9 trades proposed.
[TRADE] 2017-05-01 00:00:00: allocated $1000.74 to T exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $371.23 to SNY exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $3044.13 to CHTR exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $711.70 to BUD exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $3044.13 to LMT exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $960.47 to PCG exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $3044.13 to V exiting on 2017-05-08 00:00:00

Simulating Trading Days:  15%|█▌        | 15/100 [00:18<01:40,  1.18s/it]

[SIM] 2017-05-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0017, p_up=0.686)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0005, p_up=0.565)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0071, p_up=0.792)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.997)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0018, p_up=0.757)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0076, p_up=0.960)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0061, p_up=0.608)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0046, p_up=0.881)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0024, p_up=0.523)
[SIM] 2017-05-02 00:00:00: 9 trades proposed.
[TRADE] 2017-05-02 00:00:00: allocated $3678.83 to GD exiting on 2017-05-09 00:00:00
[EXIT] 2017-05-03 00:00:00: ABB r=0.0157, PnL=$56.19
[EXIT] 2017-05-03 00:00:00: MO r=-0.0180, PnL=$-87.41
[EXIT] 2017-05-03 00:00:00: AMZN r=0.0349, PnL=$169.14
[EXIT] 2017-05-03 00:00:00: V r=0.0068, PnL=$27.59

Simulating Trading Days:  16%|█▌        | 16/100 [00:19<01:37,  1.17s/it]

[SIM] 2017-05-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0017, p_up=0.688)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0001, p_up=0.520)
[PORT] Sector Consumer Goods: sampled BUD from top-3 (expected=0.0022, p_up=0.541)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0042, p_up=0.541)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0030, p_up=0.505)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0038, p_up=0.517)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0087, p_up=0.747)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0024, p_up=0.938)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0004, p_up=0.969)
[SIM] 2017-05-03 00:00:00: 9 trades proposed.
[TRADE] 2017-05-03 00:00:00: allocated $1021.70 to T exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $3755.99 to BABA exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $560.14 to BUD exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $3755.99 to V exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $3755.99 to LMT exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $2174.15 to MDT exiting on 2017-05-10 00:00:00
[EXIT] 2017-05-04 00:00:00: AAPL r=0.0191, PnL=$102.29
[EXIT] 2017-05-04 00:00:00: CELG r=0.0040, PnL=$21.22
[EXIT] 2017-05-04 00:00:00: VZ r=-0.0169, PnL=$-19.29
[EXIT] 2017-05-04 00:00:00: BABA r=0.0037, PnL=$17.47

Simulating Trading Days:  17%|█▋        | 17/100 [00:20<01:35,  1.15s/it]

[SIM] 2017-05-04 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0016, p_up=0.677)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0073, p_up=0.809)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0044, p_up=0.561)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.786)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0078, p_up=0.970)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0054, p_up=0.557)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0028, p_up=0.649)
[SIM] 2017-05-04 00:00:00: 8 trades proposed.
[TRADE] 2017-05-04 00:00:00: allocated $4363.12 to GD exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $4363.12 to MO exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $4363.12 to CELG exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $1464.47 to CHL exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $853.12 to V exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $2045.52 to AMZN exiting on 2017-05-11 00:00:00
[EXIT] 2017-05-05 00:00:00: GD r=0.0112, PnL=$79.41
[EXIT] 2017-05-05 00:00:00: CELG r=-0.0132, PnL=$-93.33
[EXIT] 2017-05-05 00:00:00: BABA r=0.0047, PnL=$31.00
[EARLY EXIT] 2017-05-05 00:00:00: CHL p_up_1d=0.394 -> exit; r=0.0196, PnL=$28.73

Simulating Trading Days:  18%|█▊        | 18/100 [00:21<01:33,  1.14s/it]

[SIM] 2017-05-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0014, p_up=0.658)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0025, p_up=0.783)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0046, p_up=0.578)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0072, p_up=0.592)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0038, p_up=0.514)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0049, p_up=0.525)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0065, p_up=0.960)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0026, p_up=0.536)
[SIM] 2017-05-05 00:00:00: 8 trades proposed.
[TRADE] 2017-05-05 00:00:00: allocated $3490.71 to VZ exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $3490.71 to CELG exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $3490.71 to AMZN exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $858.35 to LMT exiting on 2017-05-12 00:00:00
[EXIT] 2017-05-08 00:00:00: T r=-0.0136, PnL=$-13.56
[EXIT] 2017-05-08 00:00:00: SNY r=0.0290, PnL=$10.76
[EXIT] 2017-05-08 00:00:00: CHTR r=-0.0591, PnL=$-179.83
[EXIT] 2017-05-08 00:00:00: BUD r=0.0692, PnL=$49.26
[EXIT] 2017-05-08 00:00:00: LMT r=0.0152, PnL=$46.16
[EXIT] 2017-05-08 00:00:00: PCG r=0.0077, PnL=$7.37
[EXIT] 2017-05-08 00:00:00: V r=0.0072, PnL=$22.02

Simulating Trading Days:  19%|█▉        | 19/100 [00:22<01:31,  1.13s/it]

[SIM] 2017-05-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0012, p_up=0.642)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.938)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0021, p_up=0.669)
[PORT] Sector Healthcare: sampled MDT from top-2 (expected=0.0034, p_up=0.659)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0038, p_up=0.512)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.544)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.678)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0034, p_up=0.724)
[SIM] 2017-05-08 00:00:00: 8 trades proposed.
[TRADE] 2017-05-08 00:00:00: allocated $4080.82 to AAPL exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1132.86 to PPL exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $4080.82 to CHL exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1084.04 to MDT exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $4080.82 to CHTR exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1863.93 to LMT exiting on 2017-05-15 00:00:00
[EXIT] 2017-05-09 00:00:00: GD r=0.0130, PnL=$47.77
[EARLY EXIT] 2017-05-09 00:00:00: CHL p_up_1d=0.394 -> exit; r=0.0081, PnL=$33.07

Simulating Trading Days:  20%|██        | 20/100 [00:23<01:31,  1.14s/it]

[SIM] 2017-05-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0010, p_up=0.624)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0075, p_up=0.831)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0047, p_up=0.597)
[PORT] Sector Healthcare: sampled MDT from top-2 (expected=0.0035, p_up=0.699)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0039, p_up=0.870)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.545)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0069, p_up=0.974)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0026, p_up=0.538)
[SIM] 2017-05-09 00:00:00: 8 trades proposed.
[TRADE] 2017-05-09 00:00:00: allocated $4139.15 to VZ exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $710.89 to BA exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $4139.15 to MO exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $3428.26 to V exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $3776.03 to CHTR exiting on 2017-05-16 00:00:00
[EXIT] 2017-05-10 00:00:00: T r=0.0013, PnL=$1.33
[EXIT] 2017-05-10 00:00:00: BABA r=0.0293, PnL=$109.87
[EXIT] 2017-05-10 00:00:00: BUD r=0.0526, PnL=$29.48
[EXIT] 2017-05-10 00:00:00: V r=-0.0021, PnL=$-7.72
[EXIT] 2017-05-10 00:00:00: LMT r=0.0079, PnL=$29.81
[EXIT] 2017-05-10 00:00:00: MDT r=-0.0143, PnL=$-31.03

Simulating Trading Days:  21%|██        | 21/100 [00:24<01:29,  1.13s/it]

[SIM] 2017-05-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0009, p_up=0.613)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.938)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0047, p_up=0.596)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0037, p_up=0.749)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0080, p_up=0.980)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0035, p_up=0.749)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0070, p_up=0.977)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0036, p_up=0.753)
[SIM] 2017-05-10 00:00:00: 8 trades proposed.
[TRADE] 2017-05-10 00:00:00: allocated $5444.33 to GD exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $5444.33 to VZ exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $4227.52 to AAPL exiting on 2017-05-17 00:00:00
[EXIT] 2017-05-11 00:00:00: GD r=0.0022, PnL=$9.64
[EXIT] 2017-05-11 00:00:00: MO r=0.0024, PnL=$10.55
[EXIT] 2017-05-11 00:00:00: CELG r=-0.0397, PnL=$-173.18
[EXIT] 2017-05-11 00:00:00: V r=-0.0056, PnL=$-4.79
[EXIT] 2017-05-11 00:00:00: AMZN r=0.0108, PnL=$22.01

Simulating Trading Days:  22%|██▏       | 22/100 [00:25<01:28,  1.14s/it]

[SIM] 2017-05-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0008, p_up=0.612)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0023, p_up=0.604)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.717)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0080, p_up=0.676)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.887)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0034, p_up=0.746)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0050, p_up=0.692)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0026, p_up=0.632)
[SIM] 2017-05-11 00:00:00: 8 trades proposed.
[TRADE] 2017-05-11 00:00:00: allocated $3774.19 to BA exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $2790.62 to PCLN exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $3774.19 to CHL exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $3774.19 to CELG exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $983.57 to SO exiting on 2017-05-18 00:00:00
[EXIT] 2017-05-12 00:00:00: VZ r=-0.0182, PnL=$-63.55
[EXIT] 2017-05-12 00:00:00: CELG r=-0.0252, PnL=$-88.12
[EXIT] 2017-05-12 00:00:00: AMZN r=0.0291, PnL=$101.64
[EXIT] 2017-05-12 00:00:00: LMT r=-0.0065, PnL=$-5.56
[EARLY EXIT] 2017-05-12 00:00:00: CHL p_up_1d=0.394 -> exit; r=-0.0002, PnL=$-0.69

Simulating Trading Days:  23%|██▎       | 23/100 [00:27<01:27,  1.14s/it]

[SIM] 2017-05-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0010, p_up=0.621)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0076, p_up=0.837)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.728)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0012, p_up=0.613)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.891)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0091, p_up=0.885)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0071, p_up=0.979)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0024, p_up=0.518)
[SIM] 2017-05-12 00:00:00: 8 trades proposed.
[TRADE] 2017-05-12 00:00:00: allocated $4890.82 to VZ exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $4890.82 to BA exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $4890.82 to BABA exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $1188.98 to MO exiting on 2017-05-19 00:00:00
[EXIT] 2017-05-15 00:00:00: AAPL r=0.0176, PnL=$71.74
[EXIT] 2017-05-15 00:00:00: PPL r=0.0036, PnL=$4.10
[EXIT] 2017-05-15 00:00:00: MDT r=0.0101, PnL=$10.93
[EXIT] 2017-05-15 00:00:00: CHTR r=-0.0085, PnL=$-34.53
[EXIT] 2017-05-15 00:00:00: LMT r=-0.0006, PnL=$-1.03

Simulating Trading Days:  24%|██▍       | 24/100 [00:28<01:26,  1.14s/it]

[SIM] 2017-05-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0014, p_up=0.656)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0024, p_up=0.615)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.740)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0041, p_up=0.858)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0082, p_up=0.986)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.897)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0026, p_up=0.983)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0023, p_up=0.590)
[SIM] 2017-05-15 00:00:00: 8 trades proposed.
[TRADE] 2017-05-15 00:00:00: allocated $4983.37 to GD exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $1725.75 to T exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $4983.37 to BABA exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $585.83 to MDT exiting on 2017-05-22 00:00:00
[EXIT] 2017-05-16 00:00:00: VZ r=-0.0239, PnL=$-98.98
[EXIT] 2017-05-16 00:00:00: BA r=-0.0225, PnL=$-16.01
[EXIT] 2017-05-16 00:00:00: MO r=0.0094, PnL=$38.87
[EXIT] 2017-05-16 00:00:00: V r=0.0125, PnL=$42.85
[EXIT] 2017-05-16 00:00:00: CHTR r=-0.0169, PnL=$-63.92

Simulating Trading Days:  25%|██▌       | 25/100 [00:29<01:26,  1.15s/it]

[SIM] 2017-05-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0018, p_up=0.693)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.939)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.807)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.934)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0082, p_up=0.987)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0054, p_up=0.559)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.673)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0022, p_up=0.570)
[SIM] 2017-05-16 00:00:00: 8 trades proposed.
[TRADE] 2017-05-16 00:00:00: allocated $5114.32 to GD exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $5114.32 to AAPL exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $5114.32 to CELG exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $782.49 to CHL exiting on 2017-05-23 00:00:00
[EXIT] 2017-05-17 00:00:00: GD r=-0.0122, PnL=$-66.66
[EXIT] 2017-05-17 00:00:00: VZ r=-0.0410, PnL=$-223.03
[EXIT] 2017-05-17 00:00:00: AAPL r=-0.0196, PnL=$-83.03
[EARLY EXIT] 2017-05-17 00:00:00: CHL p_up_1d=0.394 -> exit; r=-0.0098, PnL=$-7.65

Simulating Trading Days:  26%|██▌       | 26/100 [00:30<01:24,  1.14s/it]

[SIM] 2017-05-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0021, p_up=0.717)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0063, p_up=0.717)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0046, p_up=0.584)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0091, p_up=0.965)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0036, p_up=0.495)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0059, p_up=0.595)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0027, p_up=0.991)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0024, p_up=0.588)
[SIM] 2017-05-17 00:00:00: 8 trades proposed.
[TRADE] 2017-05-17 00:00:00: allocated $3949.45 to CELG exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $3949.45 to MO exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $3949.45 to AMZN exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $2645.85 to V exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $1138.23 to LMT exiting on 2017-05-24 00:00:00
[EXIT] 2017-05-18 00:00:00: BA r=-0.0356, PnL=$-134.19
[EXIT] 2017-05-18 00:00:00: PCLN r=-0.0097, PnL=$-26.97
[EXIT] 2017-05-18 00:00:00: CELG r=-0.0177, PnL=$-66.94
[EXIT] 2017-05-18 00:00:00: SO r=0.0000, PnL=$0.00

Simulating Trading Days:  27%|██▋       | 27/100 [00:31<01:23,  1.14s/it]

[SIM] 2017-05-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0002, p_up=0.594)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.940)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0045, p_up=0.574)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.975)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0083, p_up=0.990)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.600)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.629)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0022, p_up=0.503)
[SIM] 2017-05-18 00:00:00: 8 trades proposed.
[TRADE] 2017-05-18 00:00:00: allocated $4001.26 to GD exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $4001.26 to CELG exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $3160.38 to AAPL exiting on 2017-05-25 00:00:00
[EXIT] 2017-05-19 00:00:00: VZ r=-0.0092, PnL=$-44.81
[EXIT] 2017-05-19 00:00:00: BA r=-0.0136, PnL=$-66.46
[EXIT] 2017-05-19 00:00:00: BABA r=0.0239, PnL=$117.05
[EXIT] 2017-05-19 00:00:00: MO r=0.0035, PnL=$4.21

Simulating Trading Days:  28%|██▊       | 28/100 [00:32<01:22,  1.15s/it]

[SIM] 2017-05-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0006, p_up=0.647)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0024, p_up=0.619)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.799)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0044, p_up=0.914)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.887)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.921)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0048, p_up=0.603)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0030, p_up=0.675)
[SIM] 2017-05-19 00:00:00: 8 trades proposed.
[TRADE] 2017-05-19 00:00:00: allocated $4868.76 to BABA exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $4868.76 to MDT exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $4868.76 to BA exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $1262.15 to CHL exiting on 2017-05-26 00:00:00
[EXIT] 2017-05-22 00:00:00: GD r=0.0132, PnL=$65.62
[EXIT] 2017-05-22 00:00:00: T r=-0.0088, PnL=$-15.20
[EXIT] 2017-05-22 00:00:00: BABA r=0.0276, PnL=$137.51
[EXIT] 2017-05-22 00:00:00: MDT r=-0.0018, PnL=$-1.04
[EARLY EXIT] 2017-05-22 00:00:00: CHL p_up_1d=0.394 -> exit; r=0.0049, PnL=$6.15

Simulating Trading Days:  29%|██▉       | 29/100 [00:33<01:21,  1.14s/it]

[SIM] 2017-05-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0019, p_up=0.704)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0051, p_up=0.611)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0043, p_up=0.553)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0021, p_up=0.827)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0037, p_up=0.498)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.617)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0048, p_up=0.580)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0031, p_up=0.694)
[SIM] 2017-05-22 00:00:00: 8 trades proposed.
[TRADE] 2017-05-22 00:00:00: allocated $2666.03 to CHTR exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $2666.03 to MO exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $2666.03 to CHL exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $1892.20 to V exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $773.83 to LMT exiting on 2017-05-30 00:00:00
[EXIT] 2017-05-23 00:00:00: GD r=0.0206, PnL=$105.54
[EXIT] 2017-05-23 00:00:00: AAPL r=-0.0107, PnL=$-54.94
[EXIT] 2017-05-23 00:00:00: CELG r=-0.0172, PnL=$-87.84
[EARLY EXIT] 2017-05-23 00:00:00: CHL p_up_1d=0.394 -> exit; r=0.0011, PnL=$2.87

Simulating Trading Days:  30%|███       | 30/100 [00:35<01:19,  1.14s/it]

[SIM] 2017-05-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0012, p_up=0.754)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0048, p_up=0.581)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.806)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0022, p_up=0.857)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0037, p_up=0.857)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.920)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0052, p_up=0.621)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0020, p_up=0.493)
[SIM] 2017-05-23 00:00:00: 8 trades proposed.
[TRADE] 2017-05-23 00:00:00: allocated $4882.62 to BABA exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $4882.62 to ABB exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $4882.62 to INTC exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $4882.62 to MO exiting on 2017-05-31 00:00:00
[EXIT] 2017-05-24 00:00:00: CELG r=0.0056, PnL=$21.92
[EXIT] 2017-05-24 00:00:00: MO r=0.0326, PnL=$128.76
[EXIT] 2017-05-24 00:00:00: AMZN r=0.0377, PnL=$148.78
[EXIT] 2017-05-24 00:00:00: V r=0.0332, PnL=$87.94
[EXIT] 2017-05-24 00:00:00: LMT r=0.0402, PnL=$45.70

Simulating Trading Days:  31%|███       | 31/100 [00:36<01:18,  1.14s/it]

[SIM] 2017-05-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0015, p_up=0.808)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.945)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.822)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0023, p_up=0.867)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.891)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0069, p_up=0.661)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0066, p_up=0.681)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0032, p_up=0.697)
[SIM] 2017-05-24 00:00:00: 8 trades proposed.
[TRADE] 2017-05-24 00:00:00: allocated $5660.92 to AAPL exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $3821.19 to BA exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $1839.73 to PPL exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $5660.92 to INTC exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $418.79 to AMZN exiting on 2017-06-01 00:00:00
[EXIT] 2017-05-25 00:00:00: GD r=0.0439, PnL=$175.51
[EXIT] 2017-05-25 00:00:00: CELG r=-0.0056, PnL=$-22.49
[EXIT] 2017-05-25 00:00:00: AAPL r=0.0087, PnL=$27.56

Simulating Trading Days:  32%|███▏      | 32/100 [00:37<01:16,  1.13s/it]

[SIM] 2017-05-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0008, p_up=0.611)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.947)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.818)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0023, p_up=0.869)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0039, p_up=0.867)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0069, p_up=0.661)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0068, p_up=0.972)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0033, p_up=0.704)
[SIM] 2017-05-25 00:00:00: 8 trades proposed.
[TRADE] 2017-05-25 00:00:00: allocated $5084.87 to VZ exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $5084.87 to AAPL exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $1119.56 to ABB exiting on 2017-06-02 00:00:00
[EXIT] 2017-05-26 00:00:00: BABA r=0.0062, PnL=$30.42
[EXIT] 2017-05-26 00:00:00: MDT r=0.0223, PnL=$108.81
[EXIT] 2017-05-26 00:00:00: BA r=0.0323, PnL=$157.03

Simulating Trading Days:  33%|███▎      | 33/100 [00:38<01:15,  1.13s/it]

[SIM] 2017-05-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0018, p_up=0.853)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0025, p_up=0.630)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.802)
[PORT] Sector Healthcare: sampled AMGN from top-3 (expected=0.0025, p_up=0.528)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0039, p_up=0.879)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0070, p_up=0.663)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0071, p_up=0.982)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0021, p_up=0.498)
[SIM] 2017-05-26 00:00:00: 8 trades proposed.
[TRADE] 2017-05-26 00:00:00: allocated $4288.73 to VZ exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4288.73 to BA exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $945.30 to C exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4288.73 to AMZN exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $1002.18 to UN exiting on 2017-06-05 00:00:00
[EXIT] 2017-05-30 00:00:00: CHTR r=0.0711, PnL=$189.58
[EXIT] 2017-05-30 00:00:00: MO r=0.0421, PnL=$112.13
[EXIT] 2017-05-30 00:00:00: V r=0.0151, PnL=$28.59
[EXIT] 2017-05-30 00:00:00: LMT r=0.0110, PnL=$8.55

Simulating Trading Days:  34%|███▍      | 34/100 [00:39<01:14,  1.13s/it]

[SIM] 2017-05-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0004, p_up=0.576)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0053, p_up=0.627)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.810)
[PORT] Sector Healthcare: sampled AMGN from top-3 (expected=0.0027, p_up=0.538)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.995)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.901)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0091, p_up=0.794)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0027, p_up=0.637)
[SIM] 2017-05-30 00:00:00: 8 trades proposed.
[TRADE] 2017-05-30 00:00:00: allocated $3666.14 to GD exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $3666.14 to BABA exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $902.99 to INTC exiting on 2017-06-06 00:00:00
[EXIT] 2017-05-31 00:00:00: BABA r=-0.0038, PnL=$-18.67
[EXIT] 2017-05-31 00:00:00: ABB r=0.0113, PnL=$55.02
[EXIT] 2017-05-31 00:00:00: INTC r=0.0070, PnL=$34.04
[EXIT] 2017-05-31 00:00:00: MO r=0.0459, PnL=$224.06

Simulating Trading Days:  35%|███▌      | 35/100 [00:40<01:13,  1.13s/it]

[SIM] 2017-05-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0014, p_up=0.776)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0054, p_up=0.634)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.805)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.862)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0043, p_up=0.894)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.896)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0090, p_up=0.788)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0021, p_up=0.495)
[SIM] 2017-05-31 00:00:00: 8 trades proposed.
[TRADE] 2017-05-31 00:00:00: allocated $5540.02 to BABA exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $2105.35 to ABB exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $5540.02 to CELG exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $5540.02 to INTC exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $1011.17 to MO exiting on 2017-06-07 00:00:00
[EXIT] 2017-06-01 00:00:00: AAPL r=-0.0010, PnL=$-5.91
[EXIT] 2017-06-01 00:00:00: BA r=0.0112, PnL=$42.70
[EXIT] 2017-06-01 00:00:00: PPL r=0.0099, PnL=$18.13
[EXIT] 2017-06-01 00:00:00: INTC r=0.0000, PnL=$0.00
[EXIT] 2017-06-01 00:00:00: AMZN r=0.0159, PnL=$6.66

Simulating Trading Days:  36%|███▌      | 36/100 [00:41<01:12,  1.13s/it]

[SIM] 2017-06-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0004, p_up=0.681)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.954)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.796)
[PORT] Sector Healthcare: sampled AMGN from top-3 (expected=0.0028, p_up=0.547)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.995)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0065, p_up=0.636)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0084, p_up=0.763)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0034, p_up=0.726)
[SIM] 2017-06-01 00:00:00: 8 trades proposed.
[TRADE] 2017-06-01 00:00:00: allocated $5132.71 to GD exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5132.71 to AAPL exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5132.71 to INTC exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $2046.52 to AMZN exiting on 2017-06-08 00:00:00
[EXIT] 2017-06-02 00:00:00: VZ r=0.0249, PnL=$126.81
[EXIT] 2017-06-02 00:00:00: AAPL r=0.0103, PnL=$52.21
[EXIT] 2017-06-02 00:00:00: ABB r=0.0291, PnL=$32.60

Simulating Trading Days:  37%|███▋      | 37/100 [00:43<01:11,  1.13s/it]

[SIM] 2017-06-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0007, p_up=0.713)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0056, p_up=0.656)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.784)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0057, p_up=0.876)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0037, p_up=0.504)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0062, p_up=0.616)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0074, p_up=0.989)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0020, p_up=0.694)
[SIM] 2017-06-02 00:00:00: 8 trades proposed.
[TRADE] 2017-06-02 00:00:00: allocated $3979.89 to VZ exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $3979.89 to ABBV exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $3477.65 to MO exiting on 2017-06-09 00:00:00
[EXIT] 2017-06-05 00:00:00: VZ r=0.0232, PnL=$99.36
[EXIT] 2017-06-05 00:00:00: BA r=0.0126, PnL=$54.24
[EXIT] 2017-06-05 00:00:00: C r=-0.0132, PnL=$-12.49
[EXIT] 2017-06-05 00:00:00: AMZN r=0.0156, PnL=$67.02
[EXIT] 2017-06-05 00:00:00: UN r=0.0204, PnL=$20.42
[EARLY EXIT] 2017-06-05 00:00:00: ABBV p_up_1d=0.385 -> exit; r=0.0039, PnL=$15.39

Simulating Trading Days:  38%|███▊      | 38/100 [00:44<01:10,  1.14s/it]

[SIM] 2017-06-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0008, p_up=0.727)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0057, p_up=0.666)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0037, p_up=0.489)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0087, p_up=0.748)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0038, p_up=0.509)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.625)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0070, p_up=0.518)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0030, p_up=0.825)
[SIM] 2017-06-05 00:00:00: 8 trades proposed.
[TRADE] 2017-06-05 00:00:00: allocated $3166.23 to CELG exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $3166.23 to MO exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $3166.23 to CHTR exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $3166.23 to FB exiting on 2017-06-12 00:00:00
[EXIT] 2017-06-06 00:00:00: GD r=-0.0177, PnL=$-64.79
[EXIT] 2017-06-06 00:00:00: BABA r=0.0057, PnL=$21.01
[EXIT] 2017-06-06 00:00:00: INTC r=-0.0014, PnL=$-1.25

Simulating Trading Days:  39%|███▉      | 39/100 [00:45<01:09,  1.14s/it]

[SIM] 2017-06-06 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0007, p_up=0.720)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.955)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0038, p_up=0.496)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0078, p_up=0.653)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0049, p_up=0.929)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0056, p_up=0.572)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0073, p_up=0.986)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0023, p_up=0.515)
[SIM] 2017-06-06 00:00:00: 8 trades proposed.
[TRADE] 2017-06-06 00:00:00: allocated $4372.13 to VZ exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $4372.13 to AAPL exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $1690.35 to ABB exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $4068.54 to CELG exiting on 2017-06-13 00:00:00
[EXIT] 2017-06-07 00:00:00: BABA r=0.0260, PnL=$143.86
[EXIT] 2017-06-07 00:00:00: ABB r=0.0068, PnL=$14.24
[EXIT] 2017-06-07 00:00:00: CELG r=0.0276, PnL=$153.02
[EXIT] 2017-06-07 00:00:00: INTC r=0.0042, PnL=$23.01
[EXIT] 2017-06-07 00:00:00: MO r=0.0023, PnL=$2.28

Simulating Trading Days:  40%|████      | 40/100 [00:46<01:08,  1.14s/it]

[SIM] 2017-06-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0002, p_up=0.553)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0063, p_up=0.724)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.744)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0075, p_up=0.621)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0091, p_up=0.857)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0048, p_up=0.572)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0042, p_up=0.954)
[SIM] 2017-06-07 00:00:00: 8 trades proposed.
[TRADE] 2017-06-07 00:00:00: allocated $5355.31 to GD exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $5355.31 to BABA exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $5355.31 to MO exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $3906.14 to CELG exiting on 2017-06-14 00:00:00
[EXIT] 2017-06-08 00:00:00: GD r=-0.0142, PnL=$-72.99
[EXIT] 2017-06-08 00:00:00: AAPL r=0.0118, PnL=$60.65
[EXIT] 2017-06-08 00:00:00: INTC r=0.0100, PnL=$51.16
[EXIT] 2017-06-08 00:00:00: AMZN r=0.0144, PnL=$29.43

Simulating Trading Days:  41%|████      | 41/100 [00:47<01:07,  1.14s/it]

[SIM] 2017-06-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0005, p_up=0.636)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.505)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0022, p_up=0.845)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0051, p_up=0.938)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0054, p_up=0.557)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.506)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0043, p_up=0.835)
[SIM] 2017-06-08 00:00:00: 8 trades proposed.
[TRADE] 2017-06-08 00:00:00: allocated $4479.42 to AAPL exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $3477.26 to ABB exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $1234.40 to SO exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $4247.19 to AMZN exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $4054.15 to FB exiting on 2017-06-15 00:00:00
[EXIT] 2017-06-09 00:00:00: VZ r=0.0060, PnL=$24.00
[EXIT] 2017-06-09 00:00:00: MO r=0.0045, PnL=$15.74

Simulating Trading Days:  42%|████▏     | 42/100 [00:48<01:06,  1.14s/it]

[SIM] 2017-06-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0004, p_up=0.571)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.955)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.733)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0089, p_up=0.782)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0051, p_up=0.940)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0055, p_up=0.565)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.503)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0043, p_up=0.960)
[SIM] 2017-06-09 00:00:00: 8 trades proposed.
[TRADE] 2017-06-09 00:00:00: allocated $489.85 to D exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $3985.99 to AAPL exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $1517.69 to ABB exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $1491.83 to AMZN exiting on 2017-06-16 00:00:00
[EXIT] 2017-06-12 00:00:00: CELG r=0.0106, PnL=$33.51
[EXIT] 2017-06-12 00:00:00: MO r=0.0045, PnL=$14.34
[EXIT] 2017-06-12 00:00:00: CHTR r=-0.0168, PnL=$-53.13
[EXIT] 2017-06-12 00:00:00: FB r=-0.0338, PnL=$-106.96

Simulating Trading Days:  43%|████▎     | 43/100 [00:49<01:04,  1.14s/it]

[SIM] 2017-06-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0004, p_up=0.574)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0074, p_up=0.817)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.998)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0066, p_up=0.904)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.812)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0059, p_up=0.941)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0043, p_up=0.840)
[SIM] 2017-06-12 00:00:00: 8 trades proposed.
[TRADE] 2017-06-12 00:00:00: allocated $6308.91 to GD exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $2131.54 to VZ exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $4145.91 to ABBV exiting on 2017-06-19 00:00:00
[EXIT] 2017-06-13 00:00:00: VZ r=0.0004, PnL=$1.88
[EXIT] 2017-06-13 00:00:00: AAPL r=-0.0509, PnL=$-222.50
[EXIT] 2017-06-13 00:00:00: ABB r=-0.0078, PnL=$-13.24
[EXIT] 2017-06-13 00:00:00: CELG r=0.0234, PnL=$95.38

Simulating Trading Days:  44%|████▍     | 44/100 [00:50<01:03,  1.14s/it]

[SIM] 2017-06-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0004, p_up=0.570)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0032, p_up=0.703)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.744)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.867)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0050, p_up=0.934)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0061, p_up=0.607)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0056, p_up=0.927)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0034, p_up=0.607)
[SIM] 2017-06-13 00:00:00: 8 trades proposed.
[TRADE] 2017-06-13 00:00:00: allocated $4526.06 to ABB exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $4526.06 to VZ exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $4526.06 to CELG exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $828.03 to AMZN exiting on 2017-06-20 00:00:00
[EXIT] 2017-06-14 00:00:00: GD r=0.0121, PnL=$64.90
[EXIT] 2017-06-14 00:00:00: BABA r=0.0878, PnL=$470.15
[EXIT] 2017-06-14 00:00:00: MO r=0.0019, PnL=$9.92
[EXIT] 2017-06-14 00:00:00: CELG r=0.0295, PnL=$115.29

Simulating Trading Days:  45%|████▌     | 45/100 [00:52<01:02,  1.14s/it]

[SIM] 2017-06-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0003, p_up=0.709)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0035, p_up=0.892)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0021, p_up=0.727)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.895)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.803)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0072, p_up=0.492)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0042, p_up=0.825)
[SIM] 2017-06-14 00:00:00: 8 trades proposed.
[TRADE] 2017-06-14 00:00:00: allocated $6164.28 to GD exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $6164.28 to CELG exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $6164.28 to BABA exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $1941.40 to FB exiting on 2017-06-21 00:00:00
[EXIT] 2017-06-15 00:00:00: AAPL r=-0.0690, PnL=$-309.24
[EXIT] 2017-06-15 00:00:00: ABB r=-0.0170, PnL=$-59.01
[EXIT] 2017-06-15 00:00:00: SO r=0.0191, PnL=$23.60
[EXIT] 2017-06-15 00:00:00: AMZN r=-0.0456, PnL=$-193.81
[EXIT] 2017-06-15 00:00:00: FB r=-0.0317, PnL=$-128.67

Simulating Trading Days:  46%|████▌     | 46/100 [00:53<01:01,  1.14s/it]

[SIM] 2017-06-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0004, p_up=0.575)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0077, p_up=0.848)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0043, p_up=0.551)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0036, p_up=0.714)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.541)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0072, p_up=0.489)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0040, p_up=0.809)
[SIM] 2017-06-15 00:00:00: 8 trades proposed.
[TRADE] 2017-06-15 00:00:00: allocated $3949.28 to GD exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $3949.28 to MO exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $742.61 to SO exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $1080.59 to V exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $2126.08 to CHTR exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $3949.28 to FB exiting on 2017-06-22 00:00:00
[EXIT] 2017-06-16 00:00:00: D r=0.0180, PnL=$8.84
[EXIT] 2017-06-16 00:00:00: AAPL r=-0.0450, PnL=$-179.53
[EXIT] 2017-06-16 00:00:00: ABB r=0.0004, PnL=$0.60
[EXIT] 2017-06-16 00:00:00: AMZN r=0.0096, PnL=$14.33

Simulating Trading Days:  47%|████▋     | 47/100 [00:54<01:00,  1.14s/it]

[SIM] 2017-06-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0002, p_up=0.700)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.998)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0044, p_up=0.815)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0041, p_up=0.893)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.791)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0072, p_up=0.487)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0034, p_up=0.720)
[SIM] 2017-06-16 00:00:00: 8 trades proposed.
[TRADE] 2017-06-16 00:00:00: allocated $4745.04 to AAPL exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $1667.58 to BA exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $2043.70 to ABBV exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $148.30 to BABA exiting on 2017-06-23 00:00:00
[EXIT] 2017-06-19 00:00:00: GD r=0.0308, PnL=$194.61
[EXIT] 2017-06-19 00:00:00: VZ r=-0.0131, PnL=$-28.00
[EXIT] 2017-06-19 00:00:00: ABBV r=0.0260, PnL=$107.93

Simulating Trading Days:  48%|████▊     | 48/100 [00:55<00:59,  1.14s/it]

[SIM] 2017-06-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-1 (expected=0.0007, p_up=0.590)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0040, p_up=0.941)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.777)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.969)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0041, p_up=0.899)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0088, p_up=0.777)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0052, p_up=0.909)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0034, p_up=0.717)
[SIM] 2017-06-19 00:00:00: 8 trades proposed.
[TRADE] 2017-06-19 00:00:00: allocated $5673.18 to CELG exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $2470.75 to PG exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $4634.61 to VZ exiting on 2017-06-26 00:00:00
[EXIT] 2017-06-20 00:00:00: ABB r=-0.0114, PnL=$-51.80
[EXIT] 2017-06-20 00:00:00: VZ r=-0.0112, PnL=$-50.66
[EXIT] 2017-06-20 00:00:00: CELG r=0.0552, PnL=$249.72
[EXIT] 2017-06-20 00:00:00: AMZN r=0.0120, PnL=$9.96

Simulating Trading Days:  49%|████▉     | 49/100 [00:56<00:58,  1.15s/it]

[SIM] 2017-06-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-2 (expected=0.0008, p_up=0.595)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0041, p_up=0.948)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.998)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.975)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0041, p_up=0.901)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0087, p_up=0.757)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0052, p_up=0.909)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0042, p_up=0.670)
[SIM] 2017-06-20 00:00:00: 8 trades proposed.
[TRADE] 2017-06-20 00:00:00: allocated $6378.25 to CELG exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $2802.52 to PG exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $4279.01 to VZ exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $1056.50 to BA exiting on 2017-06-27 00:00:00
[EXIT] 2017-06-21 00:00:00: GD r=0.0130, PnL=$79.93
[EXIT] 2017-06-21 00:00:00: CELG r=0.0974, PnL=$600.44
[EXIT] 2017-06-21 00:00:00: BABA r=0.0484, PnL=$298.58
[EXIT] 2017-06-21 00:00:00: FB r=0.0244, PnL=$47.29

Simulating Trading Days:  50%|█████     | 50/100 [00:57<00:57,  1.15s/it]

[SIM] 2017-06-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0004, p_up=0.573)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.514)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0032, p_up=0.761)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.994)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0096, p_up=0.821)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0053, p_up=0.788)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0022, p_up=0.582)
[SIM] 2017-06-21 00:00:00: 8 trades proposed.
[TRADE] 2017-06-21 00:00:00: allocated $5366.39 to GD exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $5366.39 to AAPL exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $5366.39 to AMZN exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $5053.46 to CHL exiting on 2017-06-28 00:00:00
[EXIT] 2017-06-22 00:00:00: GD r=-0.0038, PnL=$-15.05
[EXIT] 2017-06-22 00:00:00: MO r=0.0009, PnL=$3.62
[EXIT] 2017-06-22 00:00:00: SO r=-0.0257, PnL=$-19.10
[EXIT] 2017-06-22 00:00:00: V r=-0.0023, PnL=$-2.52
[EXIT] 2017-06-22 00:00:00: CHTR r=-0.0124, PnL=$-26.46
[EXIT] 2017-06-22 00:00:00: FB r=0.0240, PnL=$94.91
[EARLY EXIT] 2017-06-22 00:00:00: CHL p_up_1d=0.394 -> exit; r=0.0007, PnL=$3.78

Simulating Trading Days:  51%|█████     | 51/100 [00:59<00:56,  1.15s/it]

[SIM] 2017-06-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0007, p_up=0.600)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.777)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.972)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.993)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0085, p_up=0.694)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0054, p_up=0.794)
[PORT] Sector Utilities: sampled SRE from top-3 (expected=0.0016, p_up=0.584)
[SIM] 2017-06-22 00:00:00: 8 trades proposed.
[TRADE] 2017-06-22 00:00:00: allocated $6299.27 to GD exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $6299.27 to CELG exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $6299.27 to AAPL exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $1980.21 to BABA exiting on 2017-06-29 00:00:00
[EXIT] 2017-06-23 00:00:00: AAPL r=0.0282, PnL=$133.74
[EXIT] 2017-06-23 00:00:00: BA r=0.0295, PnL=$49.15
[EXIT] 2017-06-23 00:00:00: ABBV r=0.0224, PnL=$45.74
[EXIT] 2017-06-23 00:00:00: BABA r=0.0604, PnL=$8.95

Simulating Trading Days:  52%|█████▏    | 52/100 [01:00<00:55,  1.15s/it]

[SIM] 2017-06-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0005, p_up=0.637)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.778)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0091, p_up=0.968)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0053, p_up=0.945)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0083, p_up=0.650)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0054, p_up=0.793)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0038, p_up=0.641)
[SIM] 2017-06-23 00:00:00: 8 trades proposed.
[TRADE] 2017-06-23 00:00:00: allocated $4918.58 to AAPL exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $2337.56 to ABB exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $1514.79 to CHL exiting on 2017-06-30 00:00:00
[EXIT] 2017-06-26 00:00:00: CELG r=0.0694, PnL=$393.90
[EXIT] 2017-06-26 00:00:00: PG r=-0.0056, PnL=$-13.75
[EXIT] 2017-06-26 00:00:00: VZ r=-0.0176, PnL=$-81.61
[EARLY EXIT] 2017-06-26 00:00:00: CHL p_up_1d=0.394 -> exit; r=-0.0041, PnL=$-6.22

Simulating Trading Days:  53%|█████▎    | 53/100 [01:01<00:54,  1.15s/it]

[SIM] 2017-06-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0016, p_up=0.679)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.955)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.785)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0038, p_up=0.782)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0096, p_up=0.818)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0068, p_up=0.569)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0037, p_up=0.628)
[SIM] 2017-06-26 00:00:00: 8 trades proposed.
[TRADE] 2017-06-26 00:00:00: allocated $5202.19 to GD exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $5202.19 to AMZN exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $4093.58 to FB exiting on 2017-07-03 00:00:00
[EXIT] 2017-06-27 00:00:00: CELG r=0.0367, PnL=$233.97
[EXIT] 2017-06-27 00:00:00: PG r=-0.0114, PnL=$-31.89
[EXIT] 2017-06-27 00:00:00: VZ r=-0.0239, PnL=$-102.46
[EXIT] 2017-06-27 00:00:00: BA r=0.0028, PnL=$2.98

Simulating Trading Days:  54%|█████▍    | 54/100 [01:02<00:53,  1.16s/it]

[SIM] 2017-06-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0007, p_up=0.591)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0064, p_up=0.729)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0036, p_up=0.483)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.943)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0041, p_up=0.896)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0092, p_up=0.797)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0114, p_up=0.895)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0005, p_up=0.628)
[SIM] 2017-06-27 00:00:00: 8 trades proposed.
[TRADE] 2017-06-27 00:00:00: allocated $4579.88 to CELG exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $4579.88 to INTC exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $4579.88 to AMZN exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $848.47 to MO exiting on 2017-07-05 00:00:00
[EXIT] 2017-06-28 00:00:00: GD r=-0.0150, PnL=$-80.54
[EXIT] 2017-06-28 00:00:00: AAPL r=-0.0003, PnL=$-1.47
[EXIT] 2017-06-28 00:00:00: AMZN r=-0.0119, PnL=$-63.72

Simulating Trading Days:  55%|█████▌    | 55/100 [01:03<00:52,  1.16s/it]

[SIM] 2017-06-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0009, p_up=0.763)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0042, p_up=0.803)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.995)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.891)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0083, p_up=0.992)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.569)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0068, p_up=0.575)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0010, p_up=0.532)
[SIM] 2017-06-28 00:00:00: 8 trades proposed.
[TRADE] 2017-06-28 00:00:00: allocated $5195.01 to GD exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $5195.01 to CELG exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $2058.51 to UN exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $3548.62 to FB exiting on 2017-07-06 00:00:00
[EXIT] 2017-06-29 00:00:00: GD r=-0.0214, PnL=$-134.59
[EXIT] 2017-06-29 00:00:00: CELG r=-0.0148, PnL=$-93.30
[EXIT] 2017-06-29 00:00:00: AAPL r=-0.0134, PnL=$-84.35
[EXIT] 2017-06-29 00:00:00: BABA r=-0.0103, PnL=$-20.32

Simulating Trading Days:  56%|█████▌    | 56/100 [01:04<00:50,  1.16s/it]

[SIM] 2017-06-29 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0011, p_up=0.779)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.516)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0050, p_up=0.598)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.875)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0040, p_up=0.823)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0083, p_up=0.992)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0079, p_up=0.723)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0114, p_up=0.894)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0010, p_up=0.524)
[SIM] 2017-06-29 00:00:00: 9 trades proposed.
[TRADE] 2017-06-29 00:00:00: allocated $5793.44 to GD exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $5793.44 to INTC exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $5793.44 to AMZN exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $3264.90 to MO exiting on 2017-07-07 00:00:00
[EXIT] 2017-06-30 00:00:00: AAPL r=-0.0154, PnL=$-75.99
[EXIT] 2017-06-30 00:00:00: ABB r=-0.0197, PnL=$-46.02

Simulating Trading Days:  57%|█████▋    | 57/100 [01:05<00:49,  1.16s/it]

[SIM] 2017-06-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0012, p_up=0.783)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.522)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.809)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0073, p_up=0.598)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0042, p_up=0.907)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0071, p_up=0.672)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0065, p_up=0.962)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0031, p_up=0.583)
[SIM] 2017-06-30 00:00:00: 9 trades proposed.
[TRADE] 2017-06-30 00:00:00: allocated $4219.04 to VZ exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $2039.87 to BA exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $911.82 to UN exiting on 2017-07-10 00:00:00
[EXIT] 2017-07-03 00:00:00: GD r=-0.0027, PnL=$-14.03
[EXIT] 2017-07-03 00:00:00: AMZN r=-0.0406, PnL=$-211.02
[EXIT] 2017-07-03 00:00:00: FB r=-0.0336, PnL=$-137.53

Simulating Trading Days:  58%|█████▊    | 58/100 [01:07<00:48,  1.16s/it]

[SIM] 2017-07-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0010, p_up=0.772)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.530)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.811)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.797)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0022, p_up=0.510)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0065, p_up=0.633)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0067, p_up=0.582)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0031, p_up=0.577)
[SIM] 2017-07-03 00:00:00: 9 trades proposed.
[TRADE] 2017-07-03 00:00:00: allocated $4013.19 to GD exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $4013.19 to UN exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $4013.19 to AMZN exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $2204.58 to FB exiting on 2017-07-11 00:00:00
[EXIT] 2017-07-05 00:00:00: CELG r=0.0180, PnL=$82.25
[EXIT] 2017-07-05 00:00:00: INTC r=0.0205, PnL=$93.91
[EXIT] 2017-07-05 00:00:00: AMZN r=-0.0055, PnL=$-25.23
[EXIT] 2017-07-05 00:00:00: MO r=-0.0102, PnL=$-8.67

Simulating Trading Days:  59%|█████▉    | 59/100 [01:08<00:47,  1.16s/it]

[SIM] 2017-07-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0016, p_up=0.827)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.532)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.812)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.797)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0029, p_up=0.928)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0043, p_up=0.917)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0064, p_up=0.625)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0102, p_up=0.843)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.638)
[SIM] 2017-07-05 00:00:00: 9 trades proposed.
[TRADE] 2017-07-05 00:00:00: allocated $5523.85 to BA exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $5523.85 to INTC exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $3639.98 to AMZN exiting on 2017-07-12 00:00:00
[EXIT] 2017-07-06 00:00:00: GD r=-0.0090, PnL=$-46.82
[EXIT] 2017-07-06 00:00:00: CELG r=-0.0170, PnL=$-88.24
[EXIT] 2017-07-06 00:00:00: UN r=-0.0312, PnL=$-64.21
[EXIT] 2017-07-06 00:00:00: FB r=-0.0288, PnL=$-102.36

Simulating Trading Days:  60%|██████    | 60/100 [01:09<00:46,  1.16s/it]

[SIM] 2017-07-06 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0005, p_up=0.583)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.536)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.811)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.797)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0040, p_up=0.830)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0051, p_up=0.935)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0064, p_up=0.625)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0072, p_up=0.985)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0029, p_up=0.565)
[SIM] 2017-07-06 00:00:00: 9 trades proposed.
[TRADE] 2017-07-06 00:00:00: allocated $5187.06 to VZ exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $4845.35 to ABB exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $2466.46 to MDT exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $3062.29 to UN exiting on 2017-07-13 00:00:00
[EXIT] 2017-07-07 00:00:00: GD r=0.0218, PnL=$126.48
[EXIT] 2017-07-07 00:00:00: INTC r=0.0101, PnL=$58.73
[EXIT] 2017-07-07 00:00:00: AMZN r=0.0029, PnL=$16.80
[EXIT] 2017-07-07 00:00:00: MO r=-0.0020, PnL=$-6.58

Simulating Trading Days:  61%|██████    | 61/100 [01:10<00:45,  1.16s/it]

[SIM] 2017-07-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0005, p_up=0.579)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.538)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0042, p_up=0.807)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.793)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0040, p_up=0.818)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0044, p_up=0.928)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.609)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0106, p_up=0.857)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.645)
[SIM] 2017-07-07 00:00:00: 9 trades proposed.
[TRADE] 2017-07-07 00:00:00: allocated $4161.50 to BA exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $5474.92 to INTC exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $3051.36 to MDT exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $5474.92 to CHTR exiting on 2017-07-14 00:00:00
[EXIT] 2017-07-10 00:00:00: VZ r=-0.0327, PnL=$-137.93
[EXIT] 2017-07-10 00:00:00: BA r=0.0314, PnL=$64.06
[EXIT] 2017-07-10 00:00:00: UN r=-0.0014, PnL=$-1.32

Simulating Trading Days:  62%|██████▏   | 62/100 [01:11<00:44,  1.16s/it]

[SIM] 2017-07-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0003, p_up=0.571)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.538)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0038, p_up=0.917)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.831)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0030, p_up=0.920)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0045, p_up=0.931)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0030, p_up=0.710)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0106, p_up=0.861)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0028, p_up=0.557)
[SIM] 2017-07-10 00:00:00: 9 trades proposed.
[TRADE] 2017-07-10 00:00:00: allocated $4890.86 to BA exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $1683.41 to PFE exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $3388.00 to PG exiting on 2017-07-17 00:00:00
[EXIT] 2017-07-11 00:00:00: GD r=0.0013, PnL=$5.03
[EXIT] 2017-07-11 00:00:00: UN r=0.0096, PnL=$38.69
[EXIT] 2017-07-11 00:00:00: AMZN r=0.0424, PnL=$170.31
[EXIT] 2017-07-11 00:00:00: FB r=0.0461, PnL=$101.59

Simulating Trading Days:  63%|██████▎   | 63/100 [01:12<00:43,  1.16s/it]

[SIM] 2017-07-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.982)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.536)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0037, p_up=0.909)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.771)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0031, p_up=0.893)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.993)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0030, p_up=0.708)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0067, p_up=0.588)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.666)
[SIM] 2017-07-11 00:00:00: 9 trades proposed.
[TRADE] 2017-07-11 00:00:00: allocated $5835.23 to GD exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $5835.23 to PG exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $2794.61 to PFE exiting on 2017-07-18 00:00:00
[EXIT] 2017-07-12 00:00:00: BA r=0.0229, PnL=$126.73
[EXIT] 2017-07-12 00:00:00: INTC r=-0.0026, PnL=$-14.48
[EXIT] 2017-07-12 00:00:00: AMZN r=0.0361, PnL=$131.56

Simulating Trading Days:  64%|██████▍   | 64/100 [01:14<00:41,  1.16s/it]

[SIM] 2017-07-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0018, p_up=0.988)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.531)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0074, p_up=0.928)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.765)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0026, p_up=0.602)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0045, p_up=0.933)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0030, p_up=0.705)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0067, p_up=0.593)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0007, p_up=0.682)
[SIM] 2017-07-12 00:00:00: 9 trades proposed.
[TRADE] 2017-07-12 00:00:00: allocated $5176.41 to BA exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $5176.41 to AAPL exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $716.86 to MA exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $1880.75 to PCLN exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $1165.90 to ABBV exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $742.03 to FB exiting on 2017-07-19 00:00:00
[EXIT] 2017-07-13 00:00:00: VZ r=-0.0007, PnL=$-3.58
[EXIT] 2017-07-13 00:00:00: ABB r=0.0069, PnL=$33.20
[EXIT] 2017-07-13 00:00:00: MDT r=0.0063, PnL=$15.55
[EXIT] 2017-07-13 00:00:00: UN r=0.0280, PnL=$85.72
[EARLY EXIT] 2017-07-13 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0104, PnL=$12.17

Simulating Trading Days:  65%|██████▌   | 65/100 [01:15<00:40,  1.16s/it]

[SIM] 2017-07-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0002, p_up=0.654)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.526)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0031, p_up=0.852)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.764)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0032, p_up=0.797)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0029, p_up=0.702)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0075, p_up=0.993)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0027, p_up=0.547)
[SIM] 2017-07-13 00:00:00: 9 trades proposed.
[TRADE] 2017-07-13 00:00:00: allocated $5698.55 to VZ exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $5698.55 to GD exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $2159.21 to PG exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $2197.26 to PFE exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $1073.63 to MA exiting on 2017-07-20 00:00:00
[EXIT] 2017-07-14 00:00:00: BA r=0.0303, PnL=$126.26
[EXIT] 2017-07-14 00:00:00: INTC r=0.0236, PnL=$129.28
[EXIT] 2017-07-14 00:00:00: MDT r=0.0069, PnL=$21.16
[EXIT] 2017-07-14 00:00:00: CHTR r=0.0312, PnL=$170.79

Simulating Trading Days:  66%|██████▌   | 66/100 [01:16<00:39,  1.16s/it]

[SIM] 2017-07-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.972)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.525)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0073, p_up=0.922)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.766)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0028, p_up=0.661)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0049, p_up=0.927)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0029, p_up=0.701)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0075, p_up=0.993)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0008, p_up=0.743)
[SIM] 2017-07-14 00:00:00: 9 trades proposed.
[TRADE] 2017-07-14 00:00:00: allocated $6750.06 to VZ exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $6750.06 to ABB exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $4975.82 to AAPL exiting on 2017-07-21 00:00:00
[EXIT] 2017-07-17 00:00:00: BA r=0.0247, PnL=$120.86
[EXIT] 2017-07-17 00:00:00: PFE r=-0.0048, PnL=$-8.06
[EXIT] 2017-07-17 00:00:00: PG r=0.0053, PnL=$17.90
[EARLY EXIT] 2017-07-17 00:00:00: MA p_up_1d=0.333 -> exit; r=0.0172, PnL=$12.30
[EARLY EXIT] 2017-07-17 00:00:00: MA p_up_1d=0.333 -> exit; r=0.0156, PnL=$16.77

Simulating Trading Days:  67%|██████▋   | 67/100 [01:17<00:38,  1.17s/it]

[SIM] 2017-07-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0020, p_up=0.953)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.526)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0023, p_up=0.961)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0023, p_up=0.970)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0032, p_up=0.719)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0029, p_up=0.702)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0076, p_up=0.994)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0008, p_up=0.762)
[SIM] 2017-07-17 00:00:00: 9 trades proposed.
[TRADE] 2017-07-17 00:00:00: allocated $6672.60 to VZ exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $5191.99 to GD exiting on 2017-07-24 00:00:00
[EXIT] 2017-07-18 00:00:00: GD r=0.0076, PnL=$44.08
[EXIT] 2017-07-18 00:00:00: PG r=0.0216, PnL=$125.76
[EXIT] 2017-07-18 00:00:00: PFE r=0.0057, PnL=$16.01

Simulating Trading Days:  68%|██████▊   | 68/100 [01:18<00:37,  1.17s/it]

[SIM] 2017-07-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0031, p_up=0.791)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.530)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0072, p_up=0.913)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.793)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0028, p_up=0.622)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.624)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0060, p_up=0.654)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0026, p_up=0.540)
[SIM] 2017-07-18 00:00:00: 9 trades proposed.
[TRADE] 2017-07-18 00:00:00: allocated $4703.33 to GD exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $4703.33 to AAPL exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $4703.33 to INTC exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $485.18 to CHTR exiting on 2017-07-25 00:00:00
[EXIT] 2017-07-19 00:00:00: BA r=0.0215, PnL=$111.33
[EXIT] 2017-07-19 00:00:00: AAPL r=0.0362, PnL=$187.54
[EXIT] 2017-07-19 00:00:00: PCLN r=0.0236, PnL=$44.38
[EXIT] 2017-07-19 00:00:00: FB r=0.0330, PnL=$24.47

Simulating Trading Days:  69%|██████▉   | 69/100 [01:19<00:36,  1.17s/it]

[SIM] 2017-07-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0032, p_up=0.797)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.534)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0071, p_up=0.907)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.762)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0018, p_up=0.750)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0042, p_up=0.902)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0067, p_up=0.649)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0053, p_up=0.789)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0027, p_up=0.542)
[SIM] 2017-07-19 00:00:00: 9 trades proposed.
[TRADE] 2017-07-19 00:00:00: allocated $4892.65 to AAPL exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $4892.65 to BA exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $3447.70 to CHL exiting on 2017-07-26 00:00:00
[EXIT] 2017-07-20 00:00:00: VZ r=0.0168, PnL=$95.65
[EXIT] 2017-07-20 00:00:00: GD r=0.0112, PnL=$64.06
[EXIT] 2017-07-20 00:00:00: PG r=0.0219, PnL=$47.32
[EXIT] 2017-07-20 00:00:00: PFE r=0.0078, PnL=$17.17
[EARLY EXIT] 2017-07-20 00:00:00: CHL p_up_1d=0.333 -> exit; r=-0.0109, PnL=$-37.52

Simulating Trading Days:  70%|███████   | 70/100 [01:21<00:35,  1.17s/it]

[SIM] 2017-07-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0031, p_up=0.791)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.535)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0023, p_up=0.956)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.754)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0043, p_up=0.806)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0049, p_up=0.926)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0062, p_up=0.612)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0077, p_up=0.996)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0027, p_up=0.550)
[SIM] 2017-07-20 00:00:00: 9 trades proposed.
[TRADE] 2017-07-20 00:00:00: allocated $6293.08 to VZ exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $6293.08 to ABB exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $6293.08 to ABBV exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $452.71 to AMZN exiting on 2017-07-27 00:00:00
[EXIT] 2017-07-21 00:00:00: VZ r=0.0154, PnL=$103.82
[EXIT] 2017-07-21 00:00:00: ABB r=-0.0541, PnL=$-364.87
[EXIT] 2017-07-21 00:00:00: AAPL r=0.0083, PnL=$41.06
[EARLY EXIT] 2017-07-21 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0084, PnL=$52.72

Simulating Trading Days:  71%|███████   | 71/100 [01:22<00:33,  1.17s/it]

[SIM] 2017-07-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0028, p_up=0.772)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.536)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0070, p_up=0.894)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.745)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0050, p_up=0.848)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.993)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0028, p_up=0.690)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0068, p_up=0.567)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0009, p_up=0.523)
[SIM] 2017-07-21 00:00:00: 9 trades proposed.
[TRADE] 2017-07-21 00:00:00: allocated $5928.90 to GD exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $5928.90 to AAPL exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $5928.90 to ABBV exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $5928.90 to FB exiting on 2017-07-28 00:00:00
[EXIT] 2017-07-24 00:00:00: VZ r=0.0011, PnL=$7.64
[EXIT] 2017-07-24 00:00:00: GD r=0.0239, PnL=$124.26
[EARLY EXIT] 2017-07-24 00:00:00: ABBV p_up_1d=0.364 -> exit; r=-0.0096, PnL=$-57.20

Simulating Trading Days:  72%|███████▏  | 72/100 [01:23<00:32,  1.17s/it]

[SIM] 2017-07-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0025, p_up=0.748)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.531)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0070, p_up=0.893)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0036, p_up=0.480)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0054, p_up=0.862)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.993)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0055, p_up=0.567)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0076, p_up=0.996)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0014, p_up=0.598)
[SIM] 2017-07-24 00:00:00: 9 trades proposed.
[TRADE] 2017-07-24 00:00:00: allocated $5596.79 to VZ exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $5596.79 to GD exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $2704.15 to ABBV exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $2892.64 to AMZN exiting on 2017-07-31 00:00:00
[EXIT] 2017-07-25 00:00:00: GD r=0.0106, PnL=$49.97
[EXIT] 2017-07-25 00:00:00: AAPL r=0.0177, PnL=$83.36
[EXIT] 2017-07-25 00:00:00: INTC r=0.0041, PnL=$19.07
[EXIT] 2017-07-25 00:00:00: CHTR r=0.0098, PnL=$4.74
[EARLY EXIT] 2017-07-25 00:00:00: ABBV p_up_1d=0.364 -> exit; r=-0.0188, PnL=$-50.86

Simulating Trading Days:  73%|███████▎  | 73/100 [01:24<00:31,  1.17s/it]

[SIM] 2017-07-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0022, p_up=0.727)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.520)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0040, p_up=0.779)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.727)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0053, p_up=0.857)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.890)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.597)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0076, p_up=0.996)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0009, p_up=0.816)
[SIM] 2017-07-25 00:00:00: 9 trades proposed.
[TRADE] 2017-07-25 00:00:00: allocated $6233.90 to VZ exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $3206.36 to BA exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $6233.90 to ABBV exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $3027.54 to UN exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $663.77 to CHTR exiting on 2017-08-01 00:00:00
[EXIT] 2017-07-26 00:00:00: AAPL r=0.0162, PnL=$79.05
[EXIT] 2017-07-26 00:00:00: BA r=0.1070, PnL=$523.65
[EARLY EXIT] 2017-07-26 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0010, PnL=$6.02

Simulating Trading Days:  74%|███████▍  | 74/100 [01:25<00:30,  1.18s/it]

[SIM] 2017-07-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0005, p_up=0.691)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.512)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0071, p_up=0.899)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.727)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0009, p_up=0.604)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.994)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0056, p_up=0.573)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0070, p_up=0.530)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0031, p_up=0.837)
[SIM] 2017-07-26 00:00:00: 9 trades proposed.
[TRADE] 2017-07-26 00:00:00: allocated $4578.82 to GD exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $4578.82 to AAPL exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $4578.82 to AMZN exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $2708.82 to FB exiting on 2017-08-02 00:00:00
[EXIT] 2017-07-27 00:00:00: VZ r=0.0812, PnL=$510.90
[EXIT] 2017-07-27 00:00:00: ABB r=-0.0426, PnL=$-268.34
[EXIT] 2017-07-27 00:00:00: AMZN r=0.0168, PnL=$7.61

Simulating Trading Days:  75%|███████▌  | 75/100 [01:27<00:30,  1.22s/it]

[SIM] 2017-07-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.875)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.513)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0038, p_up=0.765)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.727)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0051, p_up=0.849)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.994)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0052, p_up=0.583)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0051, p_up=0.736)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0037, p_up=0.631)
[SIM] 2017-07-27 00:00:00: 9 trades proposed.
[TRADE] 2017-07-27 00:00:00: allocated $5113.59 to ABBV exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $5113.59 to CHL exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $2986.82 to CHTR exiting on 2017-08-03 00:00:00
[EXIT] 2017-07-28 00:00:00: GD r=-0.0323, PnL=$-191.59
[EXIT] 2017-07-28 00:00:00: AAPL r=-0.0051, PnL=$-30.38
[EXIT] 2017-07-28 00:00:00: FB r=0.0488, PnL=$289.18
[EARLY EXIT] 2017-07-28 00:00:00: ABBV p_up_1d=0.364 -> exit; r=-0.0180, PnL=$-91.96
[EARLY EXIT] 2017-07-28 00:00:00: CHL p_up_1d=0.333 -> exit; r=0.0074, PnL=$37.61

Simulating Trading Days:  76%|███████▌  | 76/100 [01:28<00:29,  1.22s/it]

[SIM] 2017-07-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0016, p_up=0.827)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.515)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0038, p_up=0.760)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.855)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0055, p_up=0.868)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.994)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0052, p_up=0.576)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0075, p_up=0.993)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0043, p_up=0.959)
[SIM] 2017-07-28 00:00:00: 9 trades proposed.
[TRADE] 2017-07-28 00:00:00: allocated $8693.33 to GD exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $8693.33 to VZ exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $2314.04 to D exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $8322.18 to ABBV exiting on 2017-08-04 00:00:00
[EXIT] 2017-07-31 00:00:00: VZ r=0.1073, PnL=$600.53
[EXIT] 2017-07-31 00:00:00: GD r=-0.0420, PnL=$-234.87
[EXIT] 2017-07-31 00:00:00: AMZN r=-0.0493, PnL=$-142.47
[EARLY EXIT] 2017-07-31 00:00:00: ABBV p_up_1d=0.364 -> exit; r=-0.0075, PnL=$-62.62

Simulating Trading Days:  77%|███████▋  | 77/100 [01:29<00:27,  1.20s/it]

[SIM] 2017-07-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0019, p_up=0.700)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.516)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0072, p_up=0.916)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.737)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0019, p_up=0.715)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0042, p_up=0.904)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.568)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.510)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0044, p_up=0.969)
[SIM] 2017-07-31 00:00:00: 9 trades proposed.
[TRADE] 2017-07-31 00:00:00: allocated $3651.48 to D exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $5814.66 to AAPL exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $3036.84 to BA exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $4941.00 to CHTR exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $5076.80 to FB exiting on 2017-08-07 00:00:00
[EXIT] 2017-08-01 00:00:00: VZ r=0.1116, PnL=$695.96
[EXIT] 2017-08-01 00:00:00: BA r=0.1270, PnL=$407.17
[EXIT] 2017-08-01 00:00:00: UN r=0.0059, PnL=$17.82
[EXIT] 2017-08-01 00:00:00: CHTR r=0.1133, PnL=$75.19

Simulating Trading Days:  78%|███████▊  | 78/100 [01:30<00:26,  1.20s/it]

[SIM] 2017-08-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0013, p_up=0.759)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.521)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0023, p_up=0.956)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.845)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0082, p_up=0.942)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.995)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0068, p_up=0.653)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.504)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0042, p_up=0.674)
[SIM] 2017-08-01 00:00:00: 9 trades proposed.
[TRADE] 2017-08-01 00:00:00: allocated $5602.12 to GD exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $5602.12 to ABBV exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $2764.63 to AMZN exiting on 2017-08-08 00:00:00
[EXIT] 2017-08-02 00:00:00: GD r=0.0174, PnL=$79.50
[EXIT] 2017-08-02 00:00:00: AAPL r=0.0240, PnL=$109.80
[EXIT] 2017-08-02 00:00:00: AMZN r=-0.0541, PnL=$-247.51
[EXIT] 2017-08-02 00:00:00: FB r=0.0223, PnL=$60.36
[EARLY EXIT] 2017-08-02 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0047, PnL=$26.27

Simulating Trading Days:  79%|███████▉  | 79/100 [01:31<00:25,  1.20s/it]

[SIM] 2017-08-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0014, p_up=0.777)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.523)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0038, p_up=0.757)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0047, p_up=0.589)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0088, p_up=0.952)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.995)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0074, p_up=0.522)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0073, p_up=0.987)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0043, p_up=0.682)
[SIM] 2017-08-02 00:00:00: 9 trades proposed.
[TRADE] 2017-08-02 00:00:00: allocated $6513.63 to GD exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $6513.63 to VZ exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $6513.63 to ABBV exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $2526.41 to BABA exiting on 2017-08-09 00:00:00
[EXIT] 2017-08-03 00:00:00: CHTR r=0.0474, PnL=$141.65
[EARLY EXIT] 2017-08-03 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0040, PnL=$25.79
[EARLY EXIT] 2017-08-03 00:00:00: BABA p_up_1d=0.334 -> exit; r=0.0093, PnL=$23.45

Simulating Trading Days:  80%|████████  | 80/100 [01:33<00:24,  1.22s/it]

[SIM] 2017-08-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0020, p_up=0.708)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.524)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0023, p_up=0.961)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0048, p_up=0.599)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0095, p_up=0.963)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.995)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.557)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0072, p_up=0.984)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0041, p_up=0.943)
[SIM] 2017-08-03 00:00:00: 9 trades proposed.
[TRADE] 2017-08-03 00:00:00: allocated $6268.20 to VZ exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $5892.29 to ABBV exiting on 2017-08-10 00:00:00
[EXIT] 2017-08-04 00:00:00: GD r=0.0108, PnL=$93.55
[EXIT] 2017-08-04 00:00:00: VZ r=0.0202, PnL=$175.90
[EXIT] 2017-08-04 00:00:00: D r=0.0142, PnL=$32.76
[EARLY EXIT] 2017-08-04 00:00:00: ABBV p_up_1d=0.328 -> exit; r=0.0000, PnL=$0.00

Simulating Trading Days:  81%|████████  | 81/100 [01:34<00:22,  1.21s/it]

[SIM] 2017-08-04 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0004, p_up=0.616)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.533)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0038, p_up=0.760)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0049, p_up=0.609)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0104, p_up=0.975)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0050, p_up=0.931)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.565)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.513)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0037, p_up=0.907)
[SIM] 2017-08-04 00:00:00: 9 trades proposed.
[TRADE] 2017-08-04 00:00:00: allocated $5895.75 to ABBV exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $3951.84 to ABB exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $3610.85 to V exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $4228.81 to CHTR exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $5895.75 to FB exiting on 2017-08-11 00:00:00
[EXIT] 2017-08-07 00:00:00: D r=0.0096, PnL=$35.01
[EXIT] 2017-08-07 00:00:00: AAPL r=0.0678, PnL=$394.08
[EXIT] 2017-08-07 00:00:00: BA r=-0.0092, PnL=$-27.93
[EXIT] 2017-08-07 00:00:00: CHTR r=-0.0279, PnL=$-138.03
[EXIT] 2017-08-07 00:00:00: FB r=0.0161, PnL=$81.89
[EARLY EXIT] 2017-08-07 00:00:00: ABBV p_up_1d=0.317 -> exit; r=0.0032, PnL=$19.10

Simulating Trading Days:  82%|████████▏ | 82/100 [01:35<00:21,  1.22s/it]

[SIM] 2017-08-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0021, p_up=0.713)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.542)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.940)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0049, p_up=0.611)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0108, p_up=0.980)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0050, p_up=0.933)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0081, p_up=0.734)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.512)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0037, p_up=0.764)
[SIM] 2017-08-07 00:00:00: 9 trades proposed.
[TRADE] 2017-08-07 00:00:00: allocated $7288.39 to ABBV exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $7288.39 to AAPL exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $7288.39 to AMZN exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $7288.39 to FB exiting on 2017-08-14 00:00:00
[EXIT] 2017-08-08 00:00:00: GD r=0.0116, PnL=$64.71
[EXIT] 2017-08-08 00:00:00: AMZN r=-0.0064, PnL=$-17.62
[EARLY EXIT] 2017-08-08 00:00:00: ABBV p_up_1d=0.317 -> exit; r=0.0035, PnL=$25.58

Simulating Trading Days:  83%|████████▎ | 83/100 [01:36<00:20,  1.20s/it]

[SIM] 2017-08-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0020, p_up=0.712)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0029, p_up=0.559)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.943)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.783)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.872)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0087, p_up=0.771)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.512)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0044, p_up=0.692)
[SIM] 2017-08-08 00:00:00: 9 trades proposed.
[TRADE] 2017-08-08 00:00:00: allocated $6055.51 to GD exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $3563.75 to AAPL exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $6055.51 to CELG exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $1770.62 to AMZN exiting on 2017-08-15 00:00:00
[EXIT] 2017-08-09 00:00:00: GD r=0.0149, PnL=$97.36
[EXIT] 2017-08-09 00:00:00: VZ r=0.0002, PnL=$1.35

Simulating Trading Days:  84%|████████▍ | 84/100 [01:37<00:19,  1.20s/it]

[SIM] 2017-08-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0009, p_up=0.743)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0031, p_up=0.581)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0039, p_up=0.774)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0049, p_up=0.608)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.937)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0044, p_up=0.926)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0076, p_up=0.548)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0062, p_up=0.951)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0033, p_up=0.708)
[SIM] 2017-08-09 00:00:00: 9 trades proposed.
[TRADE] 2017-08-09 00:00:00: allocated $5395.55 to VZ exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $5395.55 to CELG exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $1699.60 to BA exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $605.66 to UN exiting on 2017-08-16 00:00:00
[EXIT] 2017-08-10 00:00:00: VZ r=-0.0121, PnL=$-76.08

Simulating Trading Days:  85%|████████▌ | 85/100 [01:39<00:17,  1.19s/it]

[SIM] 2017-08-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0019, p_up=0.704)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0032, p_up=0.594)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0040, p_up=0.781)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.771)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0117, p_up=0.991)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0045, p_up=0.931)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.605)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.512)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0043, p_up=0.678)
[SIM] 2017-08-10 00:00:00: 9 trades proposed.
[TRADE] 2017-08-10 00:00:00: allocated $4214.81 to ABBV exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $1912.94 to BA exiting on 2017-08-17 00:00:00
[EXIT] 2017-08-11 00:00:00: ABB r=-0.0239, PnL=$-94.61
[EXIT] 2017-08-11 00:00:00: V r=-0.0079, PnL=$-28.63
[EXIT] 2017-08-11 00:00:00: CHTR r=0.0256, PnL=$108.41
[EXIT] 2017-08-11 00:00:00: FB r=-0.0091, PnL=$-53.53
[EARLY EXIT] 2017-08-11 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0027, PnL=$11.37

Simulating Trading Days:  86%|████████▌ | 86/100 [01:40<00:16,  1.19s/it]

[SIM] 2017-08-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0009, p_up=0.750)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0032, p_up=0.603)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0041, p_up=0.788)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0047, p_up=0.597)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0092, p_up=0.948)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0094, p_up=0.809)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.512)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0025, p_up=0.600)
[SIM] 2017-08-11 00:00:00: 9 trades proposed.
[TRADE] 2017-08-11 00:00:00: allocated $5906.24 to GD exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $5906.24 to CELG exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $5906.24 to AMZN exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $4230.63 to FB exiting on 2017-08-18 00:00:00
[EXIT] 2017-08-14 00:00:00: AAPL r=0.0065, PnL=$47.73
[EXIT] 2017-08-14 00:00:00: AMZN r=-0.0090, PnL=$-65.89
[EXIT] 2017-08-14 00:00:00: FB r=-0.0072, PnL=$-52.13

Simulating Trading Days:  87%|████████▋ | 87/100 [01:41<00:15,  1.19s/it]

[SIM] 2017-08-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0018, p_up=0.690)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0033, p_up=0.610)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0088, p_up=0.937)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.830)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0123, p_up=0.997)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0046, p_up=0.940)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0070, p_up=0.472)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0057, p_up=0.930)
[PORT] Sector Utilities: sampled EXC from top-3 (expected=0.0031, p_up=0.626)
[SIM] 2017-08-14 00:00:00: 9 trades proposed.
[TRADE] 2017-08-14 00:00:00: allocated $7108.26 to ABBV exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $2405.92 to BA exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $7108.26 to MO exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $4702.35 to VZ exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $491.20 to BABA exiting on 2017-08-21 00:00:00
[EXIT] 2017-08-15 00:00:00: GD r=0.0035, PnL=$21.02
[EXIT] 2017-08-15 00:00:00: AAPL r=0.0095, PnL=$33.84
[EXIT] 2017-08-15 00:00:00: CELG r=-0.0288, PnL=$-174.59
[EXIT] 2017-08-15 00:00:00: AMZN r=-0.0072, PnL=$-12.70
[EARLY EXIT] 2017-08-15 00:00:00: ABBV p_up_1d=0.364 -> exit; r=-0.0068, PnL=$-48.18

Simulating Trading Days:  88%|████████▊ | 88/100 [01:42<00:14,  1.21s/it]

[SIM] 2017-08-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.901)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0033, p_up=0.616)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.951)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0046, p_up=0.581)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0011, p_up=0.613)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.997)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0068, p_up=0.459)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0053, p_up=0.790)
[PORT] Sector Utilities: sampled EXC from top-3 (expected=0.0032, p_up=0.638)
[SIM] 2017-08-15 00:00:00: 9 trades proposed.
[TRADE] 2017-08-15 00:00:00: allocated $6235.99 to GD exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $6235.99 to AAPL exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $3848.40 to CHL exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $2387.59 to V exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $5719.25 to BABA exiting on 2017-08-22 00:00:00
[EXIT] 2017-08-16 00:00:00: VZ r=0.0039, PnL=$21.26
[EXIT] 2017-08-16 00:00:00: CELG r=-0.0318, PnL=$-171.53
[EXIT] 2017-08-16 00:00:00: BA r=0.0140, PnL=$23.79
[EXIT] 2017-08-16 00:00:00: UN r=0.0019, PnL=$1.13
[EARLY EXIT] 2017-08-16 00:00:00: CHL p_up_1d=0.333 -> exit; r=0.0068, PnL=$26.26

Simulating Trading Days:  89%|████████▉ | 89/100 [01:43<00:13,  1.21s/it]

[SIM] 2017-08-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0020, p_up=0.905)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0033, p_up=0.619)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.951)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0045, p_up=0.576)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0125, p_up=0.999)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0046, p_up=0.943)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0067, p_up=0.446)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0056, p_up=0.929)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0025, p_up=0.615)
[SIM] 2017-08-16 00:00:00: 9 trades proposed.
[TRADE] 2017-08-16 00:00:00: allocated $6375.83 to ABBV exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $6375.83 to AAPL exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $4123.74 to VZ exiting on 2017-08-23 00:00:00
[EXIT] 2017-08-17 00:00:00: BA r=0.0116, PnL=$22.26
[EARLY EXIT] 2017-08-17 00:00:00: BABA p_up_1d=0.334 -> exit; r=0.0602, PnL=$29.58
[EARLY EXIT] 2017-08-17 00:00:00: BABA p_up_1d=0.334 -> exit; r=0.0391, PnL=$223.69
[EARLY EXIT] 2017-08-17 00:00:00: ABBV p_up_1d=0.364 -> exit; r=-0.0081, PnL=$-51.61

Simulating Trading Days:  90%|█████████ | 90/100 [01:45<00:12,  1.20s/it]

[SIM] 2017-08-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0007, p_up=0.712)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.620)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0086, p_up=0.924)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0045, p_up=0.574)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0071, p_up=0.583)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled HD from top-3 (expected=0.0054, p_up=0.659)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0054, p_up=0.803)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0026, p_up=0.618)
[SIM] 2017-08-17 00:00:00: 9 trades proposed.
[TRADE] 2017-08-17 00:00:00: allocated $4923.07 to GD exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $4923.07 to MO exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $2197.49 to CHL exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $2108.84 to HD exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $503.48 to CELG exiting on 2017-08-24 00:00:00
[EXIT] 2017-08-18 00:00:00: GD r=0.0042, PnL=$25.07
[EXIT] 2017-08-18 00:00:00: CELG r=-0.0227, PnL=$-133.85
[EXIT] 2017-08-18 00:00:00: AMZN r=-0.0098, PnL=$-58.09
[EXIT] 2017-08-18 00:00:00: FB r=-0.0040, PnL=$-16.86
[EARLY EXIT] 2017-08-18 00:00:00: CHL p_up_1d=0.333 -> exit; r=0.0051, PnL=$11.17

Simulating Trading Days:  91%|█████████ | 91/100 [01:46<00:10,  1.20s/it]

[SIM] 2017-08-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0020, p_up=0.918)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.622)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0087, p_up=0.929)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.900)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0126, p_up=1.000)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.621)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0070, p_up=0.533)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0038, p_up=0.640)
[SIM] 2017-08-18 00:00:00: 9 trades proposed.
[TRADE] 2017-08-18 00:00:00: allocated $7796.20 to ABBV exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $7796.20 to GD exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $7796.20 to MO exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $637.47 to FB exiting on 2017-08-25 00:00:00
[EXIT] 2017-08-21 00:00:00: BA r=-0.0062, PnL=$-14.91
[EXIT] 2017-08-21 00:00:00: MO r=-0.0069, PnL=$-49.33
[EXIT] 2017-08-21 00:00:00: VZ r=-0.0131, PnL=$-61.70
[EARLY EXIT] 2017-08-21 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0106, PnL=$82.46

Simulating Trading Days:  92%|█████████▏| 92/100 [01:47<00:09,  1.20s/it]

[SIM] 2017-08-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0011, p_up=0.778)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.621)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.951)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.907)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0088, p_up=0.766)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0079, p_up=0.724)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0069, p_up=0.544)
[PORT] Sector Utilities: sampled EXC from top-3 (expected=0.0026, p_up=0.582)
[SIM] 2017-08-21 00:00:00: 9 trades proposed.
[TRADE] 2017-08-21 00:00:00: allocated $4670.13 to AAPL exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $6666.57 to CELG exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $5384.36 to AMZN exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $3278.65 to FB exiting on 2017-08-28 00:00:00
[EXIT] 2017-08-22 00:00:00: GD r=0.0087, PnL=$54.39
[EXIT] 2017-08-22 00:00:00: AAPL r=-0.0113, PnL=$-70.23
[EXIT] 2017-08-22 00:00:00: V r=0.0140, PnL=$33.50

Simulating Trading Days:  93%|█████████▎| 93/100 [01:48<00:08,  1.20s/it]

[SIM] 2017-08-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0017, p_up=0.843)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0033, p_up=0.619)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.952)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.910)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0126, p_up=1.000)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0046, p_up=0.941)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.621)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0069, p_up=0.552)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0037, p_up=0.634)
[SIM] 2017-08-22 00:00:00: 9 trades proposed.
[TRADE] 2017-08-22 00:00:00: allocated $6606.41 to ABBV exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $6606.41 to AAPL exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $2157.76 to BA exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $1483.93 to CHTR exiting on 2017-08-29 00:00:00
[EXIT] 2017-08-23 00:00:00: AAPL r=-0.0060, PnL=$-38.43
[EXIT] 2017-08-23 00:00:00: VZ r=-0.0027, PnL=$-11.07
[EARLY EXIT] 2017-08-23 00:00:00: ABBV p_up_1d=0.364 -> exit; r=-0.0032, PnL=$-21.18

Simulating Trading Days:  94%|█████████▍| 94/100 [01:50<00:07,  1.22s/it]

[SIM] 2017-08-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0013, p_up=0.793)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.621)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.953)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.914)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0027, p_up=0.586)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0045, p_up=0.936)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0070, p_up=0.668)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0068, p_up=0.559)
[PORT] Sector Utilities: sampled EXC from top-3 (expected=0.0021, p_up=0.533)
[SIM] 2017-08-23 00:00:00: 9 trades proposed.
[TRADE] 2017-08-23 00:00:00: allocated $5300.56 to AAPL exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $3953.83 to BA exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $5300.56 to AMZN exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $1346.73 to HRG exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $1154.83 to FB exiting on 2017-08-30 00:00:00
[EXIT] 2017-08-24 00:00:00: GD r=0.0075, PnL=$36.80
[EXIT] 2017-08-24 00:00:00: MO r=-0.0109, PnL=$-53.60
[EXIT] 2017-08-24 00:00:00: HD r=-0.0095, PnL=$-20.01
[EXIT] 2017-08-24 00:00:00: CELG r=0.0194, PnL=$9.75

Simulating Trading Days:  95%|█████████▌| 95/100 [01:51<00:06,  1.21s/it]

[SIM] 2017-08-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0014, p_up=0.778)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.627)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.817)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.912)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0126, p_up=1.000)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled HD from top-3 (expected=0.0051, p_up=0.615)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0065, p_up=0.677)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0037, p_up=0.628)
[SIM] 2017-08-24 00:00:00: 9 trades proposed.
[TRADE] 2017-08-24 00:00:00: allocated $5855.61 to ABBV exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $5855.61 to GD exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $728.30 to UN exiting on 2017-08-31 00:00:00
[EXIT] 2017-08-25 00:00:00: GD r=0.0016, PnL=$12.55
[EXIT] 2017-08-25 00:00:00: MO r=0.0061, PnL=$47.74
[EXIT] 2017-08-25 00:00:00: FB r=-0.0065, PnL=$-4.15
[EARLY EXIT] 2017-08-25 00:00:00: ABBV p_up_1d=0.364 -> exit; r=0.0051, PnL=$30.05

Simulating Trading Days:  96%|█████████▌| 96/100 [01:52<00:04,  1.21s/it]

[SIM] 2017-08-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0014, p_up=0.819)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.630)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.954)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.796)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0126, p_up=1.000)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0065, p_up=0.630)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0068, p_up=0.572)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0037, p_up=0.628)
[SIM] 2017-08-25 00:00:00: 9 trades proposed.
[EXIT] 2017-08-28 00:00:00: AAPL r=0.0271, PnL=$126.55
[EXIT] 2017-08-28 00:00:00: CELG r=0.0331, PnL=$220.77
[EXIT] 2017-08-28 00:00:00: AMZN r=-0.0076, PnL=$-41.06
[EXIT] 2017-08-28 00:00:00: FB r=-0.0032, PnL=$-10.55

Simulating Trading Days:  97%|█████████▋| 97/100 [01:53<00:03,  1.22s/it]

[SIM] 2017-08-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0026, p_up=0.758)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.630)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.955)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.788)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0126, p_up=1.000)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled HD from top-3 (expected=0.0043, p_up=0.502)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0077, p_up=0.997)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0037, p_up=0.626)
[SIM] 2017-08-28 00:00:00: 9 trades proposed.
[EXIT] 2017-08-29 00:00:00: AAPL r=0.0196, PnL=$129.42
[EXIT] 2017-08-29 00:00:00: BA r=0.0031, PnL=$6.66
[EXIT] 2017-08-29 00:00:00: CHTR r=-0.0207, PnL=$-30.76

Simulating Trading Days:  98%|█████████▊| 98/100 [01:54<00:02,  1.21s/it]

[SIM] 2017-08-29 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.975)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.630)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0081, p_up=0.882)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.910)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0125, p_up=0.999)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0040, p_up=0.874)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0062, p_up=0.613)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0077, p_up=0.998)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.948)
[SIM] 2017-08-29 00:00:00: 9 trades proposed.
[EXIT] 2017-08-30 00:00:00: AAPL r=0.0211, PnL=$111.66
[EXIT] 2017-08-30 00:00:00: BA r=0.0100, PnL=$39.36
[EXIT] 2017-08-30 00:00:00: AMZN r=0.0100, PnL=$53.06
[EXIT] 2017-08-30 00:00:00: HRG r=0.0144, PnL=$19.42
[EXIT] 2017-08-30 00:00:00: FB r=0.0072, PnL=$8.28

Simulating Trading Days:  99%|█████████▉| 99/100 [01:56<00:01,  1.22s/it]

[SIM] 2017-08-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0029, p_up=0.775)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.632)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0082, p_up=0.887)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.775)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0125, p_up=0.999)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0061, p_up=0.609)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0067, p_up=0.590)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0035, p_up=0.615)
[SIM] 2017-08-30 00:00:00: 9 trades proposed.
[EXIT] 2017-08-31 00:00:00: GD r=0.0094, PnL=$55.19
[EXIT] 2017-08-31 00:00:00: UN r=0.0114, PnL=$8.29

Simulating Trading Days: 100%|██████████| 100/100 [01:57<00:00,  1.17s/it]

[SIM] 2017-08-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0018, p_up=0.986)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0035, p_up=0.638)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0044, p_up=0.820)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0047, p_up=0.591)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0028, p_up=0.618)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0061, p_up=0.606)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0121, p_up=0.921)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0011, p_up=0.541)
[SIM] 2017-08-31 00:00:00: 9 trades proposed.
[EARLY EXIT] Total early exits: 44
[EARLY EXIT] PnL realized from early exits: $482.20
[EARLY EXIT] PnL if held to horizon: $1,637.40 (n=44)
[EARLY EXIT] Delta vs hold-to-horizon: $-1,155.20

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,early_exits_today,use_mpt,mpt_fallback_used,mpt_weights,budget_pre_mpt,budget_post_caps,mpt_hhi,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'AAPL': 0.24999999999999986, 'MA': 3.66643318...",34377.859777,30000.000000,0.250000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
1,2017-04-12,70000.000000,51748.680716,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'SPLP': 0.0, 'MO': 0.2499999999999999, 'MA': ...",18251.319284,18251.319284,0.250000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
2,2017-04-13,56294.497853,29994.896195,99982.987316,99982.987316,-17.012684,-0.000170,1,True,False,"{'CVX': 0.0, 'SPLP': 4.124043722053427e-17, 'M...",28984.230826,26299.601658,0.207697,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
3,2017-04-17,34838.535952,29998.963338,99996.544461,99996.544461,13.557145,0.000136,1,True,False,"{'CVX': 5.871342790985325e-17, 'SPLP': 1.56154...",20133.940102,4839.572613,0.250000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
4,2017-04-18,29998.963338,29998.963338,99996.544461,99996.544461,0.000000,0.000000,0,True,False,"{'CVX': 0.0, 'SPLP': 0.0, 'BUD': 0.0, 'V': 0.1...",10350.448742,0.000000,0.208379,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2017-08-25,54731.821120,54731.821120,108620.042571,108620.042571,86.188700,0.000794,1,True,False,"{'SLB': 0.0, 'HRG': 0.0, 'AAPL': 0.20184810896...",28385.900502,12439.527127,0.210347,[]
96,2017-08-28,75027.233851,75027.233851,108915.748159,108915.748159,295.705588,0.002722,0,True,False,"{'SNP': 1.749032855699662e-17, 'HRG': 1.487210...",42187.662330,12439.527127,0.250000,[]
97,2017-08-29,85380.646071,85380.646071,109021.065820,109021.065820,105.317661,0.000967,0,True,False,"{'CVX': 1.630752028663476e-16, 'HRG': 1.890389...",57006.877270,12439.527127,0.250000,[]
98,2017-08-30,102668.927466,102668.927466,109252.839616,109252.839616,231.773796,0.002126,0,True,False,"{'SNP': 8.65159692900389e-17, 'HRG': 0.0, 'MO'...",50194.469847,12439.527127,0.219643,[]
99,2017-08-31,109316.323162,109316.323162,109316.323162,109316.323162,63.483546,0.000581,0,True,False,"{'CVX': 0.0, 'HRG': 0.02080435682471662, 'UN':...",49390.451038,12439.527127,0.214540,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,early_exits_today,use_mpt,mpt_fallback_used,mpt_weights,budget_pre_mpt,budget_post_caps,mpt_hhi,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'AAPL': 0.24999999999999986, 'MA': 3.66643318...",34377.859777,30000.000000,0.250000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
1,2017-04-12,70000.000000,51748.680716,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'SPLP': 0.0, 'MO': 0.2499999999999999, 'MA': ...",18251.319284,18251.319284,0.250000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
2,2017-04-13,56294.497853,29994.896195,99982.987316,99982.987316,-17.012684,-0.000170,1,True,False,"{'CVX': 0.0, 'SPLP': 4.124043722053427e-17, 'M...",28984.230826,26299.601658,0.207697,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
3,2017-04-17,34838.535952,29998.963338,99996.544461,99996.544461,13.557145,0.000136,1,True,False,"{'CVX': 5.871342790985325e-17, 'SPLP': 1.56154...",20133.940102,4839.572613,0.250000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
4,2017-04-18,29998.963338,29998.963338,99996.544461,99996.544461,0.000000,0.000000,0,True,False,"{'CVX': 0.0, 'SPLP': 0.0, 'BUD': 0.0, 'V': 0.1...",10350.448742,0.000000,0.208379,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2017-08-25,54731.821120,54731.821120,108620.042571,108620.042571,86.188700,0.000794,1,True,False,"{'SLB': 0.0, 'HRG': 0.0, 'AAPL': 0.20184810896...",28385.900502,12439.527127,0.210347,[]
96,2017-08-28,75027.233851,75027.233851,108915.748159,108915.748159,295.705588,0.002722,0,True,False,"{'SNP': 1.749032855699662e-17, 'HRG': 1.487210...",42187.662330,12439.527127,0.250000,[]
97,2017-08-29,85380.646071,85380.646071,109021.065820,109021.065820,105.317661,0.000967,0,True,False,"{'CVX': 1.630752028663476e-16, 'HRG': 1.890389...",57006.877270,12439.527127,0.250000,[]
98,2017-08-30,102668.927466,102668.927466,109252.839616,109252.839616,231.773796,0.002126,0,True,False,"{'SNP': 8.65159692900389e-17, 'HRG': 0.0, 'MO'...",50194.469847,12439.527127,0.219643,[]
99,2017-08-31,109316.323162,109316.323162,109316.323162,109316.323162,63.483546,0.000581,0,True,False,"{'CVX': 0.0, 'HRG': 0.02080435682471662, 'UN':...",49390.451038,12439.527127,0.214540,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $109,316.32
Total Return on Investment (ROI): 9.32%
Annualized Sharpe Ratio: 5.92
--------------------------

In [37]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
display(simulation_results)

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,early_exits_today,use_mpt,mpt_fallback_used,mpt_weights,budget_pre_mpt,budget_post_caps,mpt_hhi,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'AAPL': 0.24999999999999986, 'MA': 3.66643318...",34377.859777,30000.000000,0.250000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
1,2017-04-12,70000.000000,51748.680716,100000.000000,100000.000000,0.000000,0.000000,0,True,False,"{'SPLP': 0.0, 'MO': 0.2499999999999999, 'MA': ...",18251.319284,18251.319284,0.250000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
2,2017-04-13,56294.497853,29994.896195,99982.987316,99982.987316,-17.012684,-0.000170,1,True,False,"{'CVX': 0.0, 'SPLP': 4.124043722053427e-17, 'M...",28984.230826,26299.601658,0.207697,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
3,2017-04-17,34838.535952,29998.963338,99996.544461,99996.544461,13.557145,0.000136,1,True,False,"{'CVX': 5.871342790985325e-17, 'SPLP': 1.56154...",20133.940102,4839.572613,0.250000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
4,2017-04-18,29998.963338,29998.963338,99996.544461,99996.544461,0.000000,0.000000,0,True,False,"{'CVX': 0.0, 'SPLP': 0.0, 'BUD': 0.0, 'V': 0.1...",10350.448742,0.000000,0.208379,[]
5,2017-04-19,59998.586307,29999.736078,99996.167430,99996.167430,-0.377031,-0.000004,0,True,False,"{'CVX': 0.0, 'SPLP': 2.969249508414828e-17, 'A...",33313.627164,29998.850229,0.232571,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
6,2017-04-20,52000.072779,32919.294527,99979.607876,99979.607876,-16.559554,-0.000166,1,True,False,"{'SLB': 8.31501355068583e-17, 'SPLP': 0.058172...",19080.778252,19080.778252,0.203192,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
7,2017-04-21,61630.915287,34020.365890,100033.178854,100033.178854,53.570977,0.000536,3,True,False,"{'CVX': 2.8180580089291736e-17, 'SPLP': 0.0, '...",27610.549397,27610.549397,0.250000,"[{'ticker': 'BABA', 'sector': 'Services', 'pro..."
8,2017-04-24,45915.190270,30055.737981,100185.793271,100185.793271,152.614417,0.001526,1,True,False,"{'SLB': 0.0, 'SPLP': 1.0046442494729368e-16, '...",16938.923737,15859.452289,0.250000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
9,2017-04-25,30055.737981,30055.737981,100185.793271,100185.793271,0.000000,0.000000,0,True,False,"{'CVX': 0.0, 'SPLP': 0.0, 'UL': 0.0, 'MA': 6.9...",16540.961115,0.000000,0.250000,[]
10,2017-04-26,51906.420468,32524.178735,100366.032320,100366.032320,180.239049,0.001799,0,True,False,"{'SLB': 6.699602736187286e-17, 'SPLP': 4.13971...",19382.241733,19382.241733,0.214505,"[{'ticker': 'ABB', 'sector': 'Industrial Goods..."
11,2017-04-27,46774.623680,30210.786369,100702.621231,100702.621231,336.588911,0.003354,1,True,False,"{'SNP': 1.1801444818972813e-17, 'SPLP': 9.8676...",21471.573102,16563.837310,0.209744,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
12,2017-04-28,50977.846687,30228.530850,100761.769500,100761.769500,59.148269,0.000587,0,True,False,"{'CVX': 0.0, 'SPLP': 0.0, 'MO': 0.249999999999...",28237.257526,20749.315836,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
13,2017-05-01,46082.142574,33905.607794,100755.928935,100755.928935,-5.840565,-0.000058,0,True,False,"{'CVX': 1.628753431344066e-16, 'SPLP': 8.77125...",12176.534780,12176.534780,0.204822,"[{'ticker': 'T', 'sector': 'Technology', 'prob..."
14,2017-05-02,33905.607794,30226.778681,100755.928935,100755.928935,0.000000,0.000000,0,True,False,"{'SNP': 0.0, 'SPLP': 0.0, 'MO': 0.25, 'BRK-A':...",15692.204595,3678.829113,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
15,2017-05-03,47752.928735,32728.964905,100921.445775,100921.445775,165.516840,0.001643,0,True,False,"{'SNP': 3.990343249459558e-17, 'SPLP': 0.0, 'B...",15023.963830,15023.963830,0.214456,"[{'ticker': 'T', 'sector': 'Technology', 'prob..."
16,2017-05-04,49414.484326,31962.020561,101043.127885,101043.127885,121.682110,0.001206,0,True,False,"{'SNP': 0.0, 'MO': 0.24999999999999992, 'V': 0...",17452.463765,17452.463765,0.210668,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
17,2017-05-05,54221.621930,42891.159004,101088.939678,101088.939678,45.811793,0.000453,1,True,False,"{'SNP': 0.0, 'PG': 0.0, 'V': 0.188526187422162...",13962.820180,11330.462926,0.226821,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
18,2017-05-08,55009.857089,38686.565143,101031.102983,101031.102983,-57.836695,-0.000572,0,True,False,"{'SNP': 3.144109259147088e-15, 'AAPL': 0.25000...",16323.291946,16323.291946,0.209766,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
19,2017-05-09,46527.060106,30333.583754,101111.945846,101111.945846,80.842863,0.000800,1,True,False,"{'SNP': 0.0, 'MO': 0.25, 'V': 0.20706304857440...",16556.594794,16193.476352,0.232219,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
20,2017-05-10,45489.302403,30373.110200,101243.700666,101243.700666,131.754819,0.001303,0,True,False,"{'SNP': 0.0, 'AAPL': 0.24999999999999997, 'V':...",21777.335179,15116.192204,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
21,2017-05-11,46225.339429,31128.579423,101107.939869,101107.939869,-135.760796,-0.001341,0,True,False,"{'SNP': 0.0, 'UN': 7.108553359768366e-17, 'MA'...",15096.760005,15096.760005,0.225914,"[{'ticker': 'BA', 'sector': 'Industrial Goods'..."
22,2017-05-12,46176.951826,30315.497803,101051.659345,101051.659345,-56.280524,-0.000557,1,True,False,"{'SNP': 1.9316862456405503e-17, 'MO': 0.25, 'M...",19563.296131,15861.454023,0.250000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
23,2017-05-15,42609.183919,30330.862950,101102.876501,101102.876501,51.217156,0.000507,0,True,False,"{'SNP': 1.3682922661735575e-16, 'UN': 0.056014...",19933.490500,12278.320969,0.203901,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
24,2017-05-16,46427.154137,30301.707401,101005.691336,101005.691336,-97.185165,-0.000961,0,True,False,"{'SNP': 0.0, 'AAPL': 0.25, 'C': 0.0, 'CELG': 0...",20457.269946,16125.446736,0.219126,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
25,2017-05-17,45820.021561,30187.595705,100625.319016,100625.319016,-380.372321,-0.003766,1,True,False,"{'SNP': 0.0, 'MO': 0.24999999999999978, 'V': 0...",15797.801897,15632.425856,0.222359,"[{'ticker': 'CELG', 'sector': 'Healthcare', 'p..."
26,2017-05-18,41282.054615,30119.162377,100397.207922,100397.207922,-228.111094,-0.002267,0,True,False,"{'CVX': 1.6551483114629878e-16, 'AAPL': 0.25, ...",16005.024253,11162.892238,0.209472,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
27,2017-05-19,45990.603991,30122.158654,100407.195514,100407.195514,9.987592,0.000099,0,True,False,"{'CVX': 1.8812883656987476e-16, 'UN': 1.300147...",19475.059712,15868.445337,0.250000,"[{'ticker': 'BABA', 'sector': 'Services', 'pro..."
28,2017-05-22,43855.662684,33191.555909,100600.228022,100600.228022,193.032508,0.001922,1,True,False,"{'SNP': 0.0, 'MO': 0.25, 'V': 0.17743636790476...",10664.106775,10664.106775,0.224249,"[{'ticker': 'CHTR', 'sector': 'Services', 'pro..."
29,2017-05-23,51166.172590,31635.698678,100565.865550,100565.865550,-34.362472,-0.000342,1,True,False,"{'CVX': 0.0, 'MO': 0.25, 'C': 0.0, 'SNY': 0.0,...",19530.473912,19530.473912,0.250000,"[{'ticker': 'BABA', 'sector': 'Services', 'pro..."
30,2017-05-24,47701.227127,30299.690443,100998.968143,100998.968143,433.102594,0.004307,0,True,False,"{'CVX': 0.0, 'AAPL': 0.25, 'MA': 0.0, 'SNY': 4...",22643.661062,17401.536684,0.222579,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
31,2017-05-25,41643.155581,30353.862313,101179.541043,101179.541043,180.572899,0.001788,0,True,False,"{'SNP': 3.74082372296325e-16, 'AAPL': 0.249999...",20339.471059,11289.293268,0.220970,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
32,2017-05-26,45256.418057,30442.740601,101475.802003,101475.802003,296.260960,0.002928,0,True,False,"{'CVX': 8.935386545246349e-17, 'UN': 0.0834791...",17154.934470,14813.677456,0.204806,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
33,2017-05-30,38779.669935,30544.395377,101814.651256,101814.651256,338.849253,0.003339,0,True,False,"{'SNP': 1.1497270256076436e-16, 'MO': 0.25, 'C...",14664.575945,8235.274558,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
34,2017-05-31,50369.316752,30632.729616,102109.098719,102109.098719,294.447463,0.002892,0,True,False,"{'CVX': 0.0, 'MO': 0.1549936809842526, 'MA': 3...",22160.090900,19736.587137,0.220549,"[{'ticker': 'BABA', 'sector': 'Services', 'pro..."
35,2017-06-01,48095.854165,30651.205975,102170.686584,102170.686584,61.587865,0.000603,0,True,False,"{'SLB': 7.018508811165882e-17, 'AAPL': 0.24999...",20530.832798,17444.648190,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
36,2017-06-02,42152.125422,30714.693829,102382.312763,102382.312763,211.626179,0.002071,0,True,False,"{'SLB': 7.738730312893797e-17, 'MO': 0.2499999...",15919.567175,11437.431593,0.250000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
37,2017-06-05,49752.201726,37087.268638,102626.251410,102626.251410,243.938647,0.002383,1,True,False,"{'SLB': 2.7350093202039313e-17, 'MO': 0.25, 'V...",12664.933088,12664.933088,0.250000,"[{'ticker': 'CELG', 'sector': 'Healthcare', 'p..."
38,2017-06-06,45277.512750,30774.366289,102581.220964,102581.220964,-45.030446,-0.000439,0,True,False,"{'SLB': 1.8383976607981814e-17, 'AAPL': 0.25, ...",17488.519979,14503.146461,0.220357,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
39,2017-06-07,50847.363460,30875.289300,102917.630999,102917.630999,336.410034,0.003279,0,True,False,"{'SNP': 0.0, 'MO': 0.25, 'MA': 2.9923010187937...",21421.248943,19972.074161,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
40,2017-06-08,48388.177493,30895.761301,102985.871003,102985.871003,68.240004,0.000663,0,True,False,"{'CVX': 0.0, 'AAPL': 0.24999999999999994, 'V':...",17917.692751,17492.416192,0.223596,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
41,2017-06-09,38393.037142,30907.682113,103025.607045,103025.607045,39.736042,0.000386,0,True,False,"{'SNP': 1.0509117399917581e-16, 'AAPL': 0.25, ...",15943.946377,7485.355029,0.212903,"[{'ticker': 'D', 'sector': 'Utilities', 'prob_..."
42,2017-06-12,43460.372817,30874.009398,102913.364660,102913.364660,-112.242385,-0.001089,0,True,False,"{'SNP': 0.0, 'MO': 0.24999999999999994, 'BRK-A...",25235.631337,12586.363419,0.222036,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
43,2017-06-13,45238.681409,30832.467063,102774.890210,102774.890210,-138.474450,-0.001346,0,True,False,"{'SNP': 1.490981304296185e-17, 'UN': 0.0, 'MA'...",18104.250921,14406.214346,0.250000,"[{'ticker': 'ABB', 'sector': 'Industrial Goods..."
44,2017-06-14,51464.788020,31030.541102,103435.137007,103435.137007,660.246797,0.006424,0,True,False,"{'BBL': 0.0, 'PG': 0.0, 'C': 0.0, 'CELG': 0.25...",24657.129263,20434.246918,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
45,2017-06-15,47855.833096,32058.704975,102768.012809,102768.012809,-667.124198,-0.006450,0,True,False,"{'PTR': 1.6155242046510498e-16, 'MO': 0.25, 'V...",15797.128122,15797.128122,0.212503,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
46,2017-06-16,39388.301462,30783.676280,102612.254267,102612.254267,-155.758542,-0.001516,0,True,False,"{'BBL': 9.912457863897327e-17, 'AAPL': 0.24999...",18980.153849,8604.625182,0.209780,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
47,2017-06-19,43644.570440,30866.035502,102886.785008,102886.785008,274.530741,0.002675,0,True,False,"{'PTR': 0.0, 'PG': 0.10887833602848498, 'MA': ...",22692.730453,12778.534938,0.213307,"[{'ticker': 'CELG', 'sector': 'Healthcare', 'p..."
48,2017-06-20,45429.480465,30913.204687,103044.015624,103044.015624,157.230616,0.001528,0,True,False,"{'PTR': 0.0, 'PG': 0.10984658892205591, 'BRK-A...",25513.007225,14516.275777,0.189943,"[{'ticker': 'CELG', 'sector': 'Healthcare', 'p..."
49,2017-06-21,52373.696630,31221.078194,104070.260648,104070.260648,1026.245024,0.009959,0,True,False,"{'SNP': 0.0, 'AAPL': 0.25000000000000006, 'V':...",21465.544394,21152.618435,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
50,2017-06-22,52110.837347,31232.829462,104109.431539,104109.431539,39.170891,0.000376,1,True,False,"{'SNP': 0.0, 'AAPL': 0.25, 'MA': 0.0, 'CELG': ...",25197.066803,20878.007885,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
51,2017-06-23,40075.034509,31304.103421,104347.011404,104347.011404,237.579865,0.002282,0,True,False,"{'CVX': 9.158603976910655e-17, 'AAPL': 0.24999...",19674.311484,8770.931087,0.218827,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
52,2017-06-26,45889.754064,31391.801159,104639.337196,104639.337196,292.325792,0.002801,1,True,False,"{'SNP': 0.0, 'AAPL': 0.25, 'C': 0.0, 'MDT': 0....",20808.751278,14497.952905,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
53,2017-06-27,46010.676627,31422.581066,104741.936886,104741.936886,102.599690,0.000981,0,True,False,"{'PTR': 1.9644526568138878e-17, 'MO': 0.249999...",18319.503132,14588.095561,0.250000,"[{'ticker': 'CELG', 'sector': 'Healthcare', 'p..."
54,2017-06-28,47376.011218,31378.862623,104596.208743,104596.208743,-145.728143,-0.001391,0,True,False,"{'BBL': 4.8078614440872955e-17, 'UN': 0.099061...",20780.030529,15997.148595,0.220096,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
55,2017-06-29,51924.313554,31279.095537,104263.651789,104263.651789,-332.556953,-0.003179,0,True,False,"{'BBL': 0.0, 'HRG': 1.4392550166935454e-16, 'M...",23173.762886,20645.218017,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
56,2017-06-30,38413.230699,31242.493733,104141.645778,104141.645778,-122.006012,-0.001170,0,True,False,"{'BBL': 0.0, 'HRG': 8.832979222957402e-17, 'UN...",16876.174889,7170.736966,0.218784,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
57,2017-07-03,45377.864687,31133.719148,103779.063826,103779.063826,-362.581952,-0.003482,0,True,False,"{'BBL': 0.0, 'HRG': 0.0, 'UN': 0.25, 'MA': 0.0...",16052.749771,14244.145539,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
58,2017-07-05,45864.085170,31176.400286,103921.334288,103921.334288,142.270462,0.001371,0,True,False,"{'CVX': 0.0, 'HRG': 5.075748698173035e-16, 'UN...",22095.405472,14687.684884,0.250000,"[{'ticker': 'BA', 'sector': 'Industrial Goods'..."
59,2017-07-06,46871.917723,31310.750988,103619.703129,103619.703129,-301.631159,-0.002902,0,True,False,"{'PTR': 0.0, 'HRG': 1.0964516405003477e-17, 'U...",20748.222313,15561.166735,0.215452,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
60,2017-07-07,52151.396487,33988.696772,103815.130610,103815.130610,195.427481,0.001886,0,True,False,"{'PTR': 1.4456533041878577e-16, 'HRG': 0.0, 'U...",21899.694686,18162.699715,0.209642,"[{'ticker': 'BA', 'sector': 'Industrial Goods'..."
61,2017-07-10,41084.246050,31121.982877,103739.942923,103739.942923,-75.187688,-0.000724,0,True,False,"{'PTR': 1.1849555191120641e-16, 'HRG': 0.03041...",19563.444261,9962.263173,0.205130,"[{'ticker': 'BA', 'sector': 'Industrial Goods'..."
62,2017-07-11,45681.738193,31216.665810,104055.552700,104055.552700,315.609777,0.003042,0,True,False,"{'CVX': 6.115221736196768e-17, 'HRG': 0.037793...",23340.914958,14465.072383,0.212059,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
63,2017-07-12,46148.166271,31289.810483,104299.368278,104299.368278,243.815577,0.002343,0,True,False,"{'CVX': 6.038517294298603e-18, 'HRG': 0.068237...",20705.631923,14858.355788,0.204776,"[{'ticker': 'BA', 'sector': 'Industrial Goods'..."
64,2017-07-13,48159.933618,31332.726664,104442.422215,104442.422215,143.053937,0.001372,1,True,False,"{'SLB': 3.7706126145738567e-17, 'HRG': 0.07643...",22794.217068,16827.206953,0.167319,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
65,2017-07-14,49942.914693,31466.973159,104889.910529,104889.910529,447.488314,0.004285,0,True,False,"{'CVX': 0.0, 'HRG': 0.05888771103569712, 'AAPL...",27000.251228,18475.941535,0.204384,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
66,2017-07-17,43379.489839,31514.902340,105049.674466,105049.674466,159.763937,0.001523,2,True,False,"{'CVX': 3.3584869655342517e-17, 'HRG': 0.08725...",26690.383768,11864.587499,0.221501,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
67,2017-07-18,46165.814835,31570.654373,105235.514578,105235.514578,185.840112,0.001769,0,True,False,"{'SNP': 4.683753385137378e-16, 'HRG': 0.0, 'AA...",18813.306427,14595.160462,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
68,2017-07-19,44913.964329,31680.968229,105603.227430,105603.227430,367.712852,0.003494,0,True,False,"{'SNP': 0.0, 'HRG': 1.0927516124595406e-16, 'A...",19570.591413,13232.996100,0.250000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
69,2017-07-20,51068.923128,31736.972499,105789.908330,105789.908330,186.680899,0.001768,1,True,False,"{'SNP': 0.0, 'HRG': 1.4814238569118256e-16, 'U...",25172.326000,19331.950629,0.250000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
70,2017-07-21,56338.733268,32623.123001,105622.646064,105622.646064,-167.262266,-0.001581,1,True,False,"{'SNP': 0.0, 'HRG': 0.0, 'AAPL': 0.25, 'MA': 2...",23715.610267,23715.610267,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
71,2017-07-24,50491.316422,33700.955448,105697.349419,105697.349419,74.703355,0.000707,1,True,False,"{'SNP': 0.0, 'HRG': 4.664140971421672e-17, 'AA...",22387.147965,16790.360974,0.218785,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
72,2017-07-25,51106.554257,31741.091666,105803.638888,105803.638888,106.289469,0.001006,1,True,False,"{'SNP': 7.561865181577689e-18, 'HRG': 4.037620...",24935.586438,19365.462591,0.218776,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
73,2017-07-26,48368.999418,31923.706297,106412.354324,106412.354324,608.715436,0.005753,1,True,False,"{'SLB': 0.0, 'HRG': 0.0, 'AAPL': 0.25, 'MA': 0...",18315.296671,16445.293121,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
74,2017-07-27,45212.753041,31998.759581,106662.531938,106662.531938,250.177615,0.002351,0,True,False,"{'CVX': 2.475080791039057e-18, 'HRG': 4.923561...",20454.344370,13213.993459,0.250000,"[{'ticker': 'ABBV', 'sector': 'Healthcare', 'p..."
75,2017-07-28,60025.490696,32002.614950,106675.383167,106675.383167,12.851229,0.000120,2,True,False,"{'CVX': 0.0, 'HRG': 0.0, 'UN': 1.3470283517148...",34773.302577,28022.875745,0.225572,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
76,2017-07-31,54571.578812,32050.785664,106835.952215,106835.952215,160.569048,0.001505,1,True,False,"{'SNP': 3.135595396071115e-17, 'HRG': 1.023486...",23258.654651,22520.793147,0.211825,"[{'ticker': 'D', 'sector': 'Utilities', 'prob_..."
77,2017-08-01,46378.492967,32409.628061,108032.093536,108032.093536,1196.141321,0.011196,0,True,False,"{'CVX': 0.0, 'HRG': 0.0, 'UL': 5.8911459761363...",22408.466919,13968.864906,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
78,2017-08-02,54485.454540,32418.153049,108060.510165,108060.510165,28.416629,0.000263,1,True,False,"{'CVX': 0.0, 'HRG': 0.0, 'UN': 0.0, 'V': 0.0, ...",26054.519755,22067.301491,0.250000,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."
79,2017-08-03,44635.906538,32475.420230,108251.400765,108251.400765,190.890600,0.001767,2,True,False,"{'SNP': 5.4674990399589077e-17, 'HRG': 4.10140...",25072.803388,12160.486308,0.210262,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
80,2017-08-04,58370.605662,34787.607130,108553.607710,108553.607710,302.206945,0.002792,1,True,False,"{'CVX': 0.0, 'HRG': 6.807950849386318e-17, 'UN...",23582.998532,23582.998532,0.208678,"[{'ticker': 'ABBV', 'sector': 'Healthcare', 'p..."
81,2017-08-07,63568.270444,34414.698793,108917.728244,108917.728244,364.120534,0.003354,1,True,False,"{'SNP': 0.0, 'HRG': 0.0, 'AAPL': 0.24999999999...",29153.571652,29153.571652,0.250000,"[{'ticker': 'ABBV', 'sector': 'Healthcare', 'p..."
82,2017-08-08,50142.508280,32697.118993,108990.396643,108990.396643,72.668398,0.000667,1,True,False,"{'SNP': 0.0, 'HRG': 0.0, 'AAPL': 0.14712835062...",24222.045671,17445.389288,0.219729,"[{'ticker': 'GD', 'sector': 'Industrial Goods'..."

In [38]:
master_df_with_target = add_horizon_targets(master_df.copy(), H=5, price_col="close")
import numpy as np
import pandas as pd

ret_col = f"ret_{5}d"

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
        # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 374
Total capital allocated: $1,527,498.09
Average position size:  $4,084.22
Completed trades with returns: 374
Winning trades: 232 (62.0%)
Losing trades:  140 (37.4%)
Total PnL: $10,471.53
Average PnL per trade: $28.00
Average return: 0.74%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Services,63,242938.835823,3856.171997,2861.562127,45.421621,0.013453
Healthcare,60,280147.652861,4669.127548,1970.224899,32.837082,0.006478
Industrial Goods,81,347020.486631,4284.203539,1908.186390,23.557857,0.006678
Technology,74,312821.172782,4227.313146,1712.244941,23.138445,0.004085
Consumer Goods,68,286658.438125,4215.565267,1642.789122,24.158664,0.007006
Financial,16,40887.045005,2555.440313,241.500304,15.093769,0.007494
Utilities,10,14567.763798,1456.776380,103.405380,10.340538,0.005034
Conglomerates,2,2456.699384,1228.349692,31.612901,15.806450,0.012703

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
283,2017-07-25,2017-08-01,VZ,Technology,6233.896610,0.995663,0.007623,0.111642,695.962395
345,2017-08-15,2017-08-22,BABA,Services,5719.252029,0.458822,0.006817,0.105927,605.824034
279,2017-07-24,2017-07-31,VZ,Technology,5596.786991,0.996357,0.007649,0.107298,600.525014
178,2017-06-14,2017-06-21,CELG,Healthcare,6164.282316,0.894899,0.009391,0.097406,600.436997
269,2017-07-19,2017-07-26,BA,Industrial Goods,4892.647853,0.901949,0.004151,0.107028,523.648617
271,2017-07-20,2017-07-27,VZ,Technology,6293.081500,0.996462,0.007653,0.081185,510.903710
158,2017-06-07,2017-06-14,BABA,Services,5355.312236,0.857040,0.009060,0.087791,470.145567
284,2017-07-25,2017-08-01,BA,Industrial Goods,3206.360173,0.889525,0.004033,0.126989,407.171131
300,2017-07-31,2017-08-07,AAPL,Consumer Goods,5814.663663,0.915849,0.007236,0.067774,394.082048
191,2017-06-19,2017-06-26,CELG,Healthcare,5673.182613,0.969172,0.009047,0.069431,393.895547

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
260,2017-07-14,2017-07-21,ABB,Industrial Goods,6750.062807,0.926864,0.004901,-0.054054,-364.868528
277,2017-07-21,2017-07-28,ABBV,Healthcare,5928.902567,0.847622,0.005037,-0.056144,-332.869799
161,2017-06-08,2017-06-15,AAPL,Consumer Goods,4479.423188,0.955613,0.007633,-0.069037,-309.244986
272,2017-07-20,2017-07-27,ABB,Industrial Goods,6293.081500,0.926079,0.004886,-0.042640,-268.339432
290,2017-07-26,2017-08-02,AMZN,Services,4578.824168,0.572986,0.005613,-0.054056,-247.512374
280,2017-07-24,2017-07-31,GD,Industrial Goods,5596.786991,0.993415,0.008405,-0.041966,-234.872002
15,2017-04-19,2017-04-26,VZ,Technology,6933.537021,0.894780,0.004854,-0.032284,-223.845011
81,2017-05-10,2017-05-17,VZ,Technology,5444.333795,0.976858,0.006974,-0.040966,-223.032329
154,2017-06-06,2017-06-13,AAPL,Consumer Goods,4372.129995,0.955398,0.007631,-0.050890,-222.498846
210,2017-06-26,2017-07-03,AMZN,Services,5202.187819,0.817505,0.009578,-0.040564,-211.022610

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Services          2861.562127
Healthcare        1970.224899
Industrial Goods  1908.186390
Technology        1712.244941
Consumer Goods    1642.789122
Financial          241.500304
Utilities          103.405380
Conglomerates       31.612901

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Services          2861.562127
Healthcare        1970.224899
Industrial Goods  1908.186390
Technology        1712.244941
Consumer Goods    1642.789122
Financial          241.500304
Utilities          103.405380
Conglomerates       31.612901

Top 10 Most Invested Tickers:

ticker
GD      36
AAPL    33
VZ      31
ABBV    26
AMZN    25
CELG    24
BA      21
BABA    20
MO      19
FB      17
Name: count, dtype: int64

Tickers Never Invested In (52):
{'SRE', 'TM', 'UNH', 'AEP', 'NVS', 'SLB', 'BBL', 'AMGN', 'MRK', 'BHP', 'BSAC', 'KO', 'UL', 'DUK', 'BAC', 'JNJ', 'UPS', 'WFC', 'MCD', 'SNP', 'BCH', 'TSM', 'MSFT', 'GE', 'AGFS', 'PICO', 'RDS-B', 'CVX', 'DIS', 'CSCO', 'CAT', 'NGG', 'GOOG', 'ORCL', 'BRK-A', 'HON', 'WMT', 'PM', 'IEP', 'CMCSA', 'PTR', 'PEP', 'NEE', 'XOM', 'HSBC', 'JPM', 'CODI', 'BP', 'REX', 'UTX', 'DHR', 'TOT'}

In [39]:
# folder_path = 'trained_models/'
# if os.path.exists(folder_path):
#     for filename in os.listdir(folder_path):
#         file_path = os.path.join(folder_path, filename)
#         try:
#             if os.path.isfile(file_path) or os.path.islink(file_path):
#                 os.unlink(file_path)
#             elif os.path.isdir(file_path):
#                 shutil.rmtree(file_path)
#         except Exception as e:
#             print(f'Failed to delete {file_path}. Reason: {e}')
# else:
#     print(f"Folder not found: {folder_path}")

# print(f"Contents of {folder_path} after deletion attempt:")
# if os.path.exists(folder_path):
#     print(os.listdir(folder_path))
# else:
#     print("Folder does not exist.")