# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as Fnn
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [7]:
pandas_ta_classic_path = None
for sp in site.getsitepackages():
    pandas_ta_classic_path = os.path.join(sp, 'pandas_ta_classic')
    if os.path.exists(pandas_ta_classic_path):
        break

if pandas_ta_classic_path:
    squeeze_pro_path = os.path.join(pandas_ta_classic_path, 'momentum', 'squeeze_pro.py')
    if os.path.exists(squeeze_pro_path):
        try:
            with open(squeeze_pro_path, 'r') as f:
                lines = f.readlines()

            new_lines = []
            fixed = False
            for line in lines:
                if "from numpy import NaN as npNaN" in line:
                    new_lines.append(line.replace("from numpy import NaN as npNaN", "# from numpy import NaN as npNaN\nimport numpy as np\n"))
                    fixed = True
                    print("Modified import statement in squeeze_pro.py")
                else:
                    new_lines.append(line)

            if fixed:
                with open(squeeze_pro_path, 'w') as f:
                    f.writelines(new_lines)
                print("Successfully patched pandas_ta_classic/momentum/squeeze_pro.py")
            else:
                print("Could not find the problematic import line in squeeze_pro.py")

        except Exception as e:
            print(f"Error modifying squeeze_pro.py: {e}")
    else:
        print(f"Could not find squeeze_pro.py at {squeeze_pro_path}")
else:
    print("Could not find the pandas_ta_classic library installation path.")

import pandas_ta_classic as ta

Could not find the problematic import line in squeeze_pro.py

### Configurations

In [8]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 1100  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [9]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [10]:
BUCKET_BINS   = [-np.inf, -0.02, -0.005, 0.0, 0.005, 0.02, np.inf]
K = len(BUCKET_BINS) - 1

In [11]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

In [12]:
CALIBRATION_LOGGED = set()

In [13]:
def bucketize_with_edges(x, edges):
    # x: 1D np array of returns; edges: len K+1
    return np.clip(np.digitize(x, edges[1:-1], right=True), 0, len(edges)-2).astype(np.int64)

def make_cumulative_targets(y_idx, K):
    # y_idx in [0..K-1] -> T: [N,K-1] with T[:,k]=1(y>k)
    y = y_idx.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def ordinal_to_class_probs(P_rep):
    # P_rep: [N,K-1] with P(y>k) (after sigmoid), repaired monotone
    N, K1 = P_rep.shape; K = K1+1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:,0] = 1.0 - P_rep[:,0]
    for c in range(1, K-1):
        Pc[:,c] = np.clip(P_rep[:,c-1] - P_rep[:,c], 0., 1.)
    Pc[:,K-1] = P_rep[:,K1-1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)

def monotone_repair_numpy(P):
    P = np.asarray(P, dtype=np.float32).copy()
    for k in range(P.shape[1]-2, -1, -1):
        P[:,k] = np.maximum(P[:,k], P[:,k+1])
    return P

In [14]:


def _temperature_objective(logits: np.ndarray, y: np.ndarray, temperature: float) -> float:
    if temperature <= 0 or not np.isfinite(temperature):
        return np.inf
    P_cum = 1.0 / (1.0 + np.exp(-logits / temperature))
    P_cum = monotone_repair_numpy(P_cum)
    Pc = ordinal_to_class_probs(P_cum)
    idx = np.arange(len(y))
    eps = 1e-9
    return -np.log(np.clip(Pc[idx, y], eps, 1.0)).mean()


# multiclass calibration tuned for macro-F1 balance
def _class_dist(y_hat, K):
    hist = np.bincount(y_hat, minlength=K).astype(np.float32)
    return hist / max(1, y_hat.size)

def _balance_penalty(p_hat, p_target, norm="l1"):
    if norm == "l1":
        return float(np.abs(p_hat - p_target).sum())
    elif norm == "l2":
        return float(np.sqrt(((p_hat - p_target) ** 2).sum()))
    else:
        return float(np.abs(p_hat - p_target).sum())

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    # decode ordinal cumulative probs to class indices using per-head taus.
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def tune_temperature_and_taus(
    Z_val,
    y_val_idx,
    K,
    T_grid=np.linspace(0.6, 2.5, 15),
    tau_grid=np.linspace(0.2, 0.8, 31),
    lambda_balance=0.05,
    target_priors="uniform",
    coord_rounds=3,
):
    """Learn a temperature T and per-head taus by maximizing macro-F1 with a balance penalty."""
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.detach().cpu().numpy()

    N, K_1 = Z_val.shape
    assert K_1 == K - 1

    if isinstance(target_priors, str) and target_priors == "uniform":
        p_target = np.ones(K, dtype=np.float32) / K
    else:
        p_target = np.asarray(target_priors, dtype=np.float32)
        p_target = p_target / p_target.sum()

    best = {"score": -1e9, "T": 1.0, "taus": np.full(K_1, 0.5, np.float32)}

    for T in T_grid:
        P_cum = 1.0 / (1.0 + np.exp(-(Z_val / T)))
        P_rep = monotone_repair_numpy(P_cum)

        taus = np.full(K_1, 0.5, dtype=np.float32)
        for _ in range(coord_rounds):
            for k in range(K_1):
                best_k = (taus[k], -1e9)
                for tau in tau_grid:
                    taus_try = taus.copy()
                    taus_try[k] = tau
                    y_hat = decode_ordinal_with_taus(P_rep, taus_try)
                    f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
                    p_hat = _class_dist(y_hat, K)
                    score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")
                    if score > best_k[1]:
                        best_k = (tau, score)
                taus[k] = best_k[0]

        y_hat = decode_ordinal_with_taus(P_rep, taus)
        f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
        p_hat = _class_dist(y_hat, K)
        score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")

        if score > best["score"]:
            best.update({"score": score, "T": float(T), "taus": taus.astype(np.float32)})

    return best["T"], best["taus"]

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [15]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [16]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # end current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [17]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [18]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [19]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [20]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [21]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [22]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [23]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [24]:
class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):  # T: float32 matrix [N, K-1] with 0/1
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)
    def __len__(self): return len(self.X)
    def __getitem__(self, i): return self.X[i], self.T[i]
    
class LSTMOrdinal(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, head='CORAL', K=6):
        super().__init__()
        self.K = K
        self.lstm1 = nn.LSTM(n_features, hidden1, num_layers=1, batch_first=True, dropout=0.1)
        self.inter_drop = nn.Dropout(inter_dropout)
        self.lstm2 = nn.LSTM(hidden1, hidden2, num_layers=1, batch_first=True, dropout=0.1)

        self.norm = nn.BatchNorm1d(hidden2)
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(dropout)

        if head.upper() == 'CORAL':
            self.w = nn.Linear(fc, 1, bias=False)
            self._beta = nn.Parameter(torch.zeros(K-1))
            self.softplus = nn.Softplus()
            self.head_type = 'CORAL'
        else:
            self.fc_out = nn.Linear(fc, K-1)
            self.head_type = 'CORN'

    def forward(self, x):
        out1,_ = self.lstm1(x)
        out1 = self.inter_drop(out1)
        out2,_ = self.lstm2(out1)
        last = out2[:, -1, :]
        last = self.norm(last)
        z = self.relu(self.fc1(last))
        z = self.drop(z)
        if self.head_type == 'CORAL':
            base = self.w(z)                              # [B,1]
            deltas = self.softplus(self._beta)            # ≥0
            b = torch.cumsum(deltas, dim=0)               # [K-1]
            logits = base - b                              # broadcast -> [B,K-1]
        else:
            logits = self.fc_out(z)                        # [B,K-1]
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [25]:
def train_company_models(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 sequence_length: int = None,
                                 H: int = 1,
                                 K: int = K,        # global K
                                 head_type: str = 'CORAL'):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"[TRAIN] {ticker}: preparing data (H={H}) with {len(company_data_df)} rows")

    ret_col = f"ret_{H}d"
    if ret_col not in company_data_df.columns:
        company_data_df = add_horizon_targets(company_data_df, H=H, price_col='close')

    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)
    if len(company_data_df) < sequence_length + H + 10:
        print(f"[TRAIN] {ticker}: insufficient history for sequence length {sequence_length}")
        return False, sequence_length

    contigs = identify_contiguous_periods(company_data_df)
    if not contigs:
        print(f"[TRAIN] {ticker}: no contiguous periods found")
        return False, sequence_length

    rets = company_data_df[ret_col].values
    y_idx_all = bucketize_with_edges(rets, BUCKET_BINS)
    X_all = company_data_df[feature_cols].values

    X_seq, y_seq = create_contiguous_sequences(
        X_all, y_idx_all, contigs, sequence_length, H
    )
    if len(X_seq) < 40:
        print(f"[TRAIN] {ticker}: too few sequences ({len(X_seq)})")
        return False, sequence_length
    print(f"[TRAIN] {ticker}: built {len(X_seq)} sequences (seq_len={sequence_length})")

    X_tr, X_val, y_tr, y_val = train_test_split(X_seq, y_seq, test_size=0.2, shuffle=False)

    scaler = MinMaxScaler()
    F = X_tr.shape[-1]
    X_tr = scaler.fit_transform(X_tr.reshape(-1, F)).reshape(X_tr.shape)
    X_val = scaler.transform(X_val.reshape(-1, F)).reshape(X_val.shape)
    print(f"[TRAIN] {ticker}: scaler fitted on {X_tr.shape[0]} training sequences")
    # Sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_tr has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    sector_feature_indices = [feature_cols.index('sector_ret_1d'),
                          feature_cols.index('sector_ret_5d'),
                          feature_cols.index('sector_vol_20d')]

    print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")


    T_tr  = make_cumulative_targets(y_tr, K)
    T_val = make_cumulative_targets(y_val, K)

    train_ds = OrdinalSequenceDataset(X_tr, T_tr)
    val_ds   = OrdinalSequenceDataset(X_val, T_val)
    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_tr.shape[-1]
    model = LSTMOrdinal(n_features=n_features, head=head_type, K=K).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    pos_rate = T_tr.mean(axis=0)
    pos_w = ((1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)).astype(np.float32)
    pos_w = torch.tensor(pos_w, dtype=torch.float32, device=device) 
    print(f"[TRAIN] {ticker}: model n_features = {n_features}")

    
    def loss_fn(logits, T):
        losses = []
        for k in range(logits.shape[1]):
            losses.append(Fnn.binary_cross_entropy_with_logits(logits[:,k], T[:,k], pos_weight=pos_w[k]))
        return torch.stack(losses).mean()

    early = EarlyStopper(patience=15, mode='min')
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)

    for epoch in range(100):
        model.train()
        tot = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            l = loss_fn(logits, yb)
            l.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tot += l.item() * xb.size(0)

        model.eval()
        with torch.no_grad():
            vtot = 0.0
            for xb, yb in val_loader:
                xb, yb = xb.to(device), yb.to(device)
                logits = model(xb)
                l = loss_fn(logits, yb)
                vtot += l.item() * xb.size(0)
            val_loss = vtot / len(val_loader.dataset)

        scheduler.step(val_loss)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:
            break

    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    ret_seq_full = company_data_df[ret_col].values[sequence_length:]
    ret_train = ret_seq_full[:len(y_tr)]
    mu_c = np.array([ret_train[y_tr==c].mean() if np.any(y_tr==c) else 0.0 for c in range(K)], dtype=np.float32)


    taus = None
    temperature = 1.0
    try:
        model.eval()
        batch = 256
        logits_list = []
        for start in range(0, len(X_val), batch):
            xb = torch.from_numpy(X_val[start:start+batch].astype(np.float32)).to(device)
            with torch.no_grad():
                logits = model(xb)
            logits_list.append(logits.cpu().numpy())
        if logits_list:
            val_logits = np.vstack(logits_list)
            T_star, taus = tune_temperature_and_taus(
                Z_val=val_logits,
                y_val_idx=y_val,
                K=K,
                T_grid=np.linspace(0.6, 2.5, 15),
                tau_grid=np.linspace(0.2, 0.8, 31),
                lambda_balance=0.05,
                target_priors="uniform",
                coord_rounds=3,
            )
            temperature = float(T_star)
            print(f"[CAL] {ticker}: taus={np.round(taus, 3)} | temperature={temperature:.3f}")
        else:
            print(f"[CAL] {ticker}: no validation logits -> skipping calibration")
    except Exception as exc:
        print(f"[CAL] {ticker}: calibration failed ({exc})")
        taus = None
        temperature = 1.0

    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt"))
    joblib.dump(scaler, os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
    joblib.dump(BUCKET_BINS, os.path.join(model_save_path, f"{ticker}_edges_H{H}.pkl"))
    joblib.dump(mu_c, os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))
    if taus is not None and len(taus) == (K - 1) and np.all(np.isfinite(taus)):
        joblib.dump(taus, os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored taus")
    if temperature is not None and np.isfinite(temperature):
        joblib.dump(float(temperature), os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored temperature scale {temperature:.3f}")
    print(f"[SAVE] {ticker}: artifacts persisted (H={H})")

    del model, scaler, train_loader, val_loader, train_ds, val_ds
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [26]:

def predict_next_horizon(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         H: int,
                         K: int = 6,
                         head: str = "CORAL") -> dict | None:
    """
    Ordinal inference with optional calibration artifacts. Returns class probs plus
    summary stats so the simulator can log decisions.
    """
    try:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt")
        if not os.path.isfile(state_dict_path):
            return None

        scaler   = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        seq_len  = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
        mu_c     = joblib.load(os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))

        taus_path = os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl")
        T_path    = os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl")
        taus = joblib.load(taus_path) if os.path.isfile(taus_path) else None
        temperature = float(joblib.load(T_path)) if os.path.isfile(T_path) else 1.0

        n_features = len(feature_cols)
        model = LSTMOrdinal(n_features=n_features, head=head.upper(), K=K).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    if 'CALIBRATION_LOGGED' not in globals():
        globals()['CALIBRATION_LOGGED'] = set()
    if ticker not in CALIBRATION_LOGGED:
        if taus is not None:
            print(f"[CAL] {ticker}: loaded taus {np.round(taus,3)}")
        else:
            print(f"[CAL] {ticker}: no taus artifact found")
        print(f"[CAL] {ticker}: temperature scaling {temperature:.3f}")
        CALIBRATION_LOGGED.add(ticker)

    contiguous = identify_contiguous_periods(company_data_df)
    if not contiguous:
        return None
    start, end = contiguous[-1]
    period = company_data_df.iloc[start:end+1]
    if len(period) < seq_len:
        return None

    try:
        last_seq = period.tail(seq_len)
        X_scaled = scaler.transform(last_seq[feature_cols])
    except Exception:
        return None

    x = torch.from_numpy(np.asarray([X_scaled], dtype=np.float32)).to(device)

    with torch.no_grad():
        z = model(x)
        if temperature and temperature > 0 and temperature != 1.0:
            z = z / temperature
        P_cum = torch.sigmoid(z).cpu().numpy()
        P_cum = monotone_repair_numpy(P_cum)
        Pc    = ordinal_to_class_probs(P_cum)

    mu_c = np.asarray(mu_c, dtype=np.float32).reshape(-1)
    if mu_c.shape[0] != K:
        return None
    expected_rise = float((Pc[0] * mu_c).sum())

    top_bucket_idx = K - 1
    prob_top_bucket = float(Pc[0, top_bucket_idx])
    bucket_idx = int(np.argmax(Pc[0]))

    class_idx = None
    if taus is not None:
        taus = np.asarray(taus, dtype=np.float32).reshape(-1)
        if taus.shape[0] == (K - 1):
            class_idx = int(decode_ordinal_with_taus(P_cum, taus=taus)[0])

    positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
    prob_up = float(Pc[0, positive_buckets].sum()) if positive_buckets else prob_top_bucket

    return {
        'ticker': ticker,
        'expected_rise': expected_rise,
        'predicted_prob': prob_up,  # probability of positive move
        'prob_up': prob_up,
        'prob_bucket_top': prob_top_bucket,
        'bucket_idx': bucket_idx,
        'class_idx': class_idx,
        'class_probs': Pc[0].tolist(),
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [27]:

def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                              total_capital: float, sector_threshold: float,
                              kelly_fraction: float) -> pd.DataFrame:
    """Pick strongest candidates per sector and size using Kelly on prob_up and horizon payoffs."""
    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")
    df = daily_predictions_df.copy()

    if 'prob_up' not in df.columns and 'class_probs' in df.columns:
        positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
        def _sum_up(probs):
            if isinstance(probs, (list, tuple)) and len(probs) == K and positive_buckets:
                return float(sum(probs[i] for i in positive_buckets))
            return np.nan
        df['prob_up'] = df['class_probs'].apply(_sum_up)

    if 'prob_up' not in df.columns and 'predicted_prob' in df.columns:
        df['prob_up'] = df['predicted_prob']

    if 'expected_rise' not in df.columns:
        print("[PORT] Missing expected_rise; cannot size portfolio.")
        return pd.DataFrame()

    df = df[(df['prob_up'] >= sector_threshold) & (df['expected_rise'] > 0)]
    print(f"[PORT] {len(df)} tickers cleared prob_up ≥ {sector_threshold:.3f} and positive expected return.")
    if df.empty:
        return pd.DataFrame()

    winners = (df.sort_values(['sector', 'expected_rise'], ascending=[True, False])
                 .groupby('sector', as_index=False)
                 .head(1))
    if winners.empty:
        print("[PORT] No sector winners after grouping.")
        return pd.DataFrame()

    rows = []
    for _, row in winners.iterrows():
        ticker = row['ticker']
        sector = row['sector']
        p_up = float(row['prob_up'])
        payout = payout_map.get(ticker, {})
        b = payout.get('b') if isinstance(payout, dict) else float(payout)
        if not np.isfinite(b) or b <= 0:
            print(f"[PORT] Sector {sector}: skipping {ticker} due to invalid payout ratio {b}.")
            continue
        kelly_pct = p_up - (1.0 - p_up) / b
        if kelly_pct <= 0:
            print(f"[PORT] Sector {sector}: Kelly <= 0 for {ticker} (p_up={p_up:.3f}, b={b:.3f}).")
            continue
        investment_fraction = min(MAX_POSITION_SIZE, kelly_pct * kelly_fraction)
        investment_fraction = max(0.0, investment_fraction)
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            print(f"[PORT] Sector {sector}: allocation ${investment_amount:.2f} below minimum; skipping {ticker}.")
            continue
        print(f"[PORT] Sector {sector}: selecting {ticker} (p_up={p_up:.3f}, kelly={kelly_pct:.3f}) "
              f"with ${investment_amount:.2f} allocation")
        rows.append({
            'ticker': ticker,
            'sector': sector,
            'prob_up': p_up,
            'predicted_prob': p_up,
            'expected_rise': row['expected_rise'],
            'bucket_idx': row.get('bucket_idx', np.nan),
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount
        })

    if not rows:
        print("[PORT] All sector winners rejected after Kelly sizing.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [28]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    """Check the minimal set of artifacts needed for ordinal inference."""
    required = [
        f"{ticker}_lstmORD_H{H}.pt",      # model weights (ordinal head)
        f"{ticker}_scaler_H{H}.pkl",      # feature scaler
        f"{ticker}_seq_length_H{H}.pkl",  # sequence length
        f"{ticker}_mu_c_H{H}.pkl",        # per-class train means μ_c for expected return
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in required)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [29]:
def run_simulation(master_df: pd.DataFrame, payout_map: dict, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"\nStarting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    # precompute horizon returns if not already present
    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"
    if ret_col not in master_df.columns or tgt_col not in master_df.columns:
        print("Adding horizon targets to master_df...")
        master_df = add_horizon_targets(master_df, H=H, price_col='close')

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    # overlapping book
    open_positions = []  # each: {'ticker','invest','entry_date','exit_date'}
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                # realize H-day return measured from entry date
                row = master_df[(master_df['date'] == pos['entry_date']) & (master_df['ticker'] == pos['ticker'])]
                if not row.empty:
                    rH = row.iloc[0][ret_col]
                    if pd.notna(rH):
                        pnl = pos['invest'] * rH
                        total_pnl_today += pnl
                        print(f"[EXIT] {current_date}: {pos['ticker']} r={rH:.4f}, PnL=${pnl:.2f}")
                        capital += pos['invest'] + pnl  # release capital
                # else silently drop if missing
            else:
                still_open.append(pos)
        open_positions = still_open

        # equity at START (after settlements, before new entries)
        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # build prediction universe using info strictly before current_date
        historical_data = master_df[master_df['date'] < current_date]
        if i == 0:  # no yesterday slice for display
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                print("Retraining model for ticker:", ticker)
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)
        print(f"[SIM] {current_date}: built {len(daily_predictions_df)} predictions")
        if (not daily_predictions_df.empty and
            'predicted_prob' not in daily_predictions_df.columns and
            'calibrated_prediction' not in daily_predictions_df.columns):
            print("[WARN] predicted_prob missing from daily_predictions_df columns:",
                  sorted(daily_predictions_df.columns))


        # size raw trades via Kelly
        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df,
            payout_map,
            capital,
            sector_threshold=SECTOR_CONFIDENCE_THRESHOLD,
            kelly_fraction=KELLY_FRACTION,
        )
        if investment_decision_df.empty:
            print(f"[SIM] {current_date}: no trades proposed today.")
        else:
            print(f"[SIM] {current_date}: {len(investment_decision_df)} trades proposed.")

        # entry logic (allow_overlap controls laddering)
        exit_idx = i + H
        if exit_idx < len(unique_dates):
            exit_date = unique_dates[exit_idx]
        else:
            exit_date = None  # can't open new trades that we cannot exit within data

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            # ensure the column exists even if future changes rename it
            if 'predicted_prob' not in investment_decision_df.columns:
                if 'calibrated_prediction' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'calibrated_prediction': 'predicted_prob'}
                    )
                elif 'score' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'score': 'predicted_prob'}
                    )
                else:
                    # nothing to sort by
                    investment_decision_df = pd.DataFrame()

            if not investment_decision_df.empty:
                investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)


            # current exposures (post-settlement)
            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                # per-ticker ladder depth
                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue  # no overlapping allowed

                # base size from Kelly (already scaled by KELLY_FRACTION)
                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))  # vs equity

                # clamp by remaining budgets
                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                # lock capital and record position
                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})
                print(f"[TRADE] {current_date}: allocated ${amt:.2f} to {tkr} exiting on {exit_date}")

        # equity at END (after entries)
        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        # log the day
        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,  # cash only
            'capital_end': capital,                               # cash only
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,                # realized PnL today
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [30]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [31]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_features.parquet')

In [32]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)

columns_to_check = ['EMA_12', 'EMA_26','EMA_50','MACD_12_26_9','MACDh_12_26_9','MACDs_12_26_9','RSI_14','ATRr_14',
                    'STOCHRSIk_14_14_3_3','STOCHRSId_14_14_3_3','ATRr_14','BB_upper','BB_middle','BB_lower','OBV',
                    
                    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d',
                    'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
                    'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,EMA_12_sector,EMA_26_sector,EMA_50_sector,MACD_12_26_9_sector,MACDh_12_26_9_sector,MACDs_12_26_9_sector,RSI_14_sector,sector_BB_upper,sector_BB_middle,sector_BB_lower
0,2013-01-28,62.547142,64.744286,62.265713,64.261429,196379400.0,AAPL,0.0,0.0,Consumer Goods,...,63.469842,63.131514,62.677060,0.338328,0.026511,0.311817,58.013322,64.478154,63.186407,61.894660
1,2013-01-29,65.500000,65.742859,64.588570,65.467140,142789500.0,AAPL,0.0,0.0,Consumer Goods,...,63.598899,63.218714,62.741046,0.380185,0.054694,0.325491,63.235273,64.385112,63.338200,62.291288
2,2013-01-30,65.285713,66.085716,64.928574,65.261429,104288800.0,AAPL,0.0,0.0,Consumer Goods,...,63.708321,63.299561,62.802580,0.408761,0.066616,0.342145,63.247349,64.420760,63.446936,62.473111
3,2013-01-31,65.282860,65.611427,64.997147,65.070000,79833600.0,AAPL,0.0,0.0,Consumer Goods,...,63.711657,63.331445,62.838949,0.380212,0.030453,0.349758,55.305822,64.427675,63.450371,62.473067
4,2013-02-01,65.587143,65.639999,64.050003,64.802856,134871100.0,AAPL,0.0,0.0,Consumer Goods,...,63.838369,63.420618,62.905472,0.417750,0.054394,0.363357,62.369091,64.592130,63.522521,62.452912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100099,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,60.623603,60.734795,60.870774,-0.111192,0.016355,-0.127548,53.634155,62.998418,61.014300,59.030182
100100,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,60.692895,60.759922,60.878744,-0.067027,0.048417,-0.115443,54.205103,62.813547,60.944450,59.075353
100101,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,60.739988,60.777631,60.883460,-0.037643,0.062240,-0.099883,53.126723,62.594765,60.868750,59.142735
100102,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,60.833067,60.819658,60.901560,0.013408,0.090633,-0.077225,57.342961,62.482556,60.831900,59.181244
100103,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,60.979826,60.891313,60.936283,0.088512,0.132590,-0.044078,62.040301,62.385381,60.807600,59.229819

In [33]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d',
    'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle', 'sector_BB_lower']
Total number of features: 37

In [34]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,EMA_12_sector,EMA_26_sector,EMA_50_sector,MACD_12_26_9_sector,MACDh_12_26_9_sector,MACDs_12_26_9_sector,RSI_14_sector,sector_BB_upper,sector_BB_middle,sector_BB_lower
0,2013-01-28,62.547142,64.744286,62.265713,64.261429,196379400.0,AAPL,0.0,0.0,Consumer Goods,...,63.469842,63.131514,62.677060,0.338328,0.026511,0.311817,58.013322,64.478154,63.186407,61.894660
1,2013-01-29,65.500000,65.742859,64.588570,65.467140,142789500.0,AAPL,0.0,0.0,Consumer Goods,...,63.598899,63.218714,62.741046,0.380185,0.054694,0.325491,63.235273,64.385112,63.338200,62.291288
2,2013-01-30,65.285713,66.085716,64.928574,65.261429,104288800.0,AAPL,0.0,0.0,Consumer Goods,...,63.708321,63.299561,62.802580,0.408761,0.066616,0.342145,63.247349,64.420760,63.446936,62.473111
3,2013-01-31,65.282860,65.611427,64.997147,65.070000,79833600.0,AAPL,0.0,0.0,Consumer Goods,...,63.711657,63.331445,62.838949,0.380212,0.030453,0.349758,55.305822,64.427675,63.450371,62.473067
4,2013-02-01,65.587143,65.639999,64.050003,64.802856,134871100.0,AAPL,0.0,0.0,Consumer Goods,...,63.838369,63.420618,62.905472,0.417750,0.054394,0.363357,62.369091,64.592130,63.522521,62.452912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100099,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,60.623603,60.734795,60.870774,-0.111192,0.016355,-0.127548,53.634155,62.998418,61.014300,59.030182
100100,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,60.692895,60.759922,60.878744,-0.067027,0.048417,-0.115443,54.205103,62.813547,60.944450,59.075353
100101,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,60.739988,60.777631,60.883460,-0.037643,0.062240,-0.099883,53.126723,62.594765,60.868750,59.142735
100102,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,60.833067,60.819658,60.901560,0.013408,0.090633,-0.077225,57.342961,62.482556,60.831900,59.181244
100103,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,60.979826,60.891313,60.936283,0.088512,0.132590,-0.044078,62.040301,62.385381,60.807600,59.229819

# Execute Pipeline

In [35]:

master_df_with_target = create_target_variable(master_df)
master_df_with_target = add_horizon_targets(master_df_with_target, H=1)
payout_map = calculate_historical_payouts(master_df_with_target)

initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df_with_target,
    payout_map,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=1,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Creating target variable...
Target variable created.

Starting simulation with 1100 initial training days... (H=1)
Starting predictions from day 1100 (after 1100 training days)

Simulating Trading Days:   0%|          | 0/59 [00:00<?, ?it/s]

Retraining model for ticker: AAPL
[TRAIN] AAPL: preparing data (H=1) with 1100 rows
[TRAIN] AAPL: built 1088 sequences (seq_len=12)
[TRAIN] AAPL: scaler fitted on 870 training sequences
[TRAIN] AAPL: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] AAPL: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] AAPL: sector feature maxs = [0.03194691 0.05042416 0.01893123]
[TRAIN] AAPL: model n_features = 37
[CAL] AAPL: taus=[0.7  0.58 0.56 0.36 0.3 ] | temperature=0.600
[SAVE] AAPL: stored taus
[SAVE] AAPL: stored temperature scale 0.600
[SAVE] AAPL: artifacts persisted (H=1)
[CAL] AAPL: loaded taus [0.7  0.58 0.56 0.36 0.3 ]
[CAL] AAPL: temperature scaling 0.600
Retraining model for ticker: ABB
[TRAIN] ABB: preparing data (H=1) with 1100 rows
[TRAIN] ABB: built 1088 sequences (seq_len=12)
[TRAIN] ABB: scaler fitted on 870 training sequences
[TRAIN] ABB: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] ABB: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] ABB: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
[TRAIN] ABB: model n_features = 37
[CAL] ABB: taus=[0.8  0.58 0.46 0.5  0.42] | temperature=1.143
[SAVE] ABB: stored taus
[SAVE] ABB: stored temperature scale 1.143
[SAVE] ABB: artifacts persisted (H=1)
[CAL] ABB: loaded taus [0.8  0.58 0.46 0.5  0.42]
[CAL] ABB: temperature scaling 1.143
Retraining model for ticker: ABBV
[TRAIN] ABBV: preparing data (H=1) with 1068 rows
[TRAIN] ABBV: built 1056 sequences (seq_len=12)
[TRAIN] ABBV: scaler fitted on 844 training sequences
[TRAIN] ABBV: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] ABBV: sector feature mins = [-0.0410257  -0.11491243  0.00410269]
[TRAIN] ABBV: sector feature maxs = [0.04369867 0.0870226  0.02237914]
[TRAIN] ABBV: model n_features = 37
[CAL] ABBV: taus=[0.68 0.54 0.48 0.42 0.28] | temperature=1.279
[SAVE] ABBV: stored taus
[SAVE] ABBV: stored temperature scale 1.279
[SAVE] ABBV: artifacts persisted (H=1)
[CAL] ABBV: loaded taus [0.68 0.54 0.48 0.42 0.28]
[CAL] ABBV: temperature scaling 1.279
Retraining model for ticker: AEP
[TRAIN] AEP: preparing data (H=1) with 1100 rows
[TRAIN] AEP: built 1088 sequences (seq_len=12)
[TRAIN] AEP: scaler fitted on 870 training sequences
[TRAIN] AEP: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] AEP: sector feature mins = [-0.04000807 -0.08164836  0.00362283]
[TRAIN] AEP: sector feature maxs = [0.03053178 0.06078573 0.01557388]
[TRAIN] AEP: model n_features = 37
[CAL] AEP: taus=[0.62 0.52 0.48 0.42 0.46] | temperature=2.093
[SAVE] AEP: stored taus
[SAVE] AEP: stored temperature scale 2.093
[SAVE] AEP: artifacts persisted (H=1)
[CAL] AEP: loaded taus [0.62 0.52 0.48 0.42 0.46]
[CAL] AEP: temperature scaling 2.093
Retraining model for ticker: AGFS
[TRAIN] AGFS: preparing data (H=1) with 592 rows
[TRAIN] AGFS: built 580 sequences (seq_len=12)
[TRAIN] AGFS: scaler fitted on 464 training sequences
[TRAIN] AGFS: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] AGFS: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] AGFS: sector feature maxs = [0.35098106 0.39009354 0.07892018]
[TRAIN] AGFS: model n_features = 37
[CAL] AGFS: taus=[0.72 0.66 0.6  0.52 0.44] | temperature=2.093
[SAVE] AGFS: stored taus
[SAVE] AGFS: stored temperature scale 2.093
[SAVE] AGFS: artifacts persisted (H=1)
[CAL] AGFS: loaded taus [0.72 0.66 0.6  0.52 0.44]
[CAL] AGFS: temperature scaling 2.093
Retraining model for ticker: AMGN
[TRAIN] AMGN: preparing data (H=1) with 1100 rows
[TRAIN] AMGN: built 1088 sequences (seq_len=12)
[TRAIN] AMGN: scaler fitted on 870 training sequences
[TRAIN] AMGN: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] AMGN: sector feature mins = [-0.0410257  -0.11491243  0.00426767]
[TRAIN] AMGN: sector feature maxs = [0.04369867 0.0870226  0.02237914]
[TRAIN] AMGN: model n_features = 37
[CAL] AMGN: taus=[0.6  0.54 0.36 0.34 0.34] | temperature=0.600
[SAVE] AMGN: stored taus
[SAVE] AMGN: stored temperature scale 0.600
[SAVE] AMGN: artifacts persisted (H=1)
[CAL] AMGN: loaded taus [0.6  0.54 0.36 0.34 0.34]
[CAL] AMGN: temperature scaling 0.600
Retraining model for ticker: AMZN
[TRAIN] AMZN: preparing data (H=1) with 1100 rows
[TRAIN] AMZN: built 1088 sequences (seq_len=12)
[TRAIN] AMZN: scaler fitted on 870 training sequences
[TRAIN] AMZN: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] AMZN: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] AMZN: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] AMZN: model n_features = 37
[CAL] AMZN: taus=[0.68 0.56 0.48 0.46 0.32] | temperature=1.279
[SAVE] AMZN: stored taus
[SAVE] AMZN: stored temperature scale 1.279
[SAVE] AMZN: artifacts persisted (H=1)
[CAL] AMZN: loaded taus [0.68 0.56 0.48 0.46 0.32]
[CAL] AMZN: temperature scaling 1.279
Retraining model for ticker: BA
[TRAIN] BA: preparing data (H=1) with 1100 rows
[TRAIN] BA: built 1088 sequences (seq_len=12)
[TRAIN] BA: scaler fitted on 870 training sequences
[TRAIN] BA: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BA: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] BA: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
[TRAIN] BA: model n_features = 37
[CAL] BA: taus=[0.72 0.2  0.5  0.42 0.34] | temperature=1.007
[SAVE] BA: stored taus
[SAVE] BA: stored temperature scale 1.007
[SAVE] BA: artifacts persisted (H=1)
[CAL] BA: loaded taus [0.72 0.2  0.5  0.42 0.34]
[CAL] BA: temperature scaling 1.007
Retraining model for ticker: BABA
[TRAIN] BABA: preparing data (H=1) with 636 rows
[TRAIN] BABA: built 624 sequences (seq_len=12)
[TRAIN] BABA: scaler fitted on 499 training sequences
[TRAIN] BABA: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BABA: sector feature mins = [-0.06810713 -0.10466671  0.00432136]
[TRAIN] BABA: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] BABA: model n_features = 37
[CAL] BABA: taus=[0.8  0.78 0.6  0.5  0.4 ] | temperature=0.871
[SAVE] BABA: stored taus
[SAVE] BABA: stored temperature scale 0.871
[SAVE] BABA: artifacts persisted (H=1)
[CAL] BABA: loaded taus [0.8  0.78 0.6  0.5  0.4 ]
[CAL] BABA: temperature scaling 0.871
Retraining model for ticker: BAC
[TRAIN] BAC: preparing data (H=1) with 1100 rows
[TRAIN] BAC: built 1088 sequences (seq_len=12)
[TRAIN] BAC: scaler fitted on 870 training sequences
[TRAIN] BAC: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BAC: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BAC: sector feature maxs = [0.03246263 0.0680742  0.01782321]
[TRAIN] BAC: model n_features = 37
[CAL] BAC: taus=[0.76 0.44 0.46 0.44 0.24] | temperature=1.007
[SAVE] BAC: stored taus
[SAVE] BAC: stored temperature scale 1.007
[SAVE] BAC: artifacts persisted (H=1)
[CAL] BAC: loaded taus [0.76 0.44 0.46 0.44 0.24]
[CAL] BAC: temperature scaling 1.007
Retraining model for ticker: BBL
[TRAIN] BBL: preparing data (H=1) with 1100 rows
[TRAIN] BBL: built 1088 sequences (seq_len=12)
[TRAIN] BBL: scaler fitted on 870 training sequences
[TRAIN] BBL: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BBL: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BBL: sector feature maxs = [0.05341933 0.13994116 0.03044324]
[TRAIN] BBL: model n_features = 37
[CAL] BBL: taus=[0.8  0.74 0.62 0.42 0.34] | temperature=1.007
[SAVE] BBL: stored taus
[SAVE] BBL: stored temperature scale 1.007
[SAVE] BBL: artifacts persisted (H=1)
[CAL] BBL: loaded taus [0.8  0.74 0.62 0.42 0.34]
[CAL] BBL: temperature scaling 1.007
Retraining model for ticker: BCH
[TRAIN] BCH: preparing data (H=1) with 1100 rows
[TRAIN] BCH: built 1088 sequences (seq_len=12)
[TRAIN] BCH: scaler fitted on 870 training sequences
[TRAIN] BCH: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BCH: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BCH: sector feature maxs = [0.03246263 0.0680742  0.01782321]
[TRAIN] BCH: model n_features = 37
[CAL] BCH: taus=[0.74 0.64 0.54 0.5  0.48] | temperature=1.957
[SAVE] BCH: stored taus
[SAVE] BCH: stored temperature scale 1.957
[SAVE] BCH: artifacts persisted (H=1)
[CAL] BCH: loaded taus [0.74 0.64 0.54 0.5  0.48]
[CAL] BCH: temperature scaling 1.957
Retraining model for ticker: BHP
[TRAIN] BHP: preparing data (H=1) with 1100 rows
[TRAIN] BHP: built 1088 sequences (seq_len=12)
[TRAIN] BHP: scaler fitted on 870 training sequences
[TRAIN] BHP: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BHP: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BHP: sector feature maxs = [0.05341933 0.13994116 0.03044324]
[TRAIN] BHP: model n_features = 37
[CAL] BHP: taus=[0.74 0.52 0.48 0.32 0.28] | temperature=1.686
[SAVE] BHP: stored taus
[SAVE] BHP: stored temperature scale 1.686
[SAVE] BHP: artifacts persisted (H=1)
[CAL] BHP: loaded taus [0.74 0.52 0.48 0.32 0.28]
[CAL] BHP: temperature scaling 1.686
Retraining model for ticker: BP
[TRAIN] BP: preparing data (H=1) with 1100 rows
[TRAIN] BP: built 1088 sequences (seq_len=12)
[TRAIN] BP: scaler fitted on 870 training sequences
[TRAIN] BP: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BP: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BP: sector feature maxs = [0.05341933 0.13994116 0.03044324]
[TRAIN] BP: model n_features = 37
[CAL] BP: taus=[0.78 0.2  0.66 0.3  0.2 ] | temperature=0.736
[SAVE] BP: stored taus
[SAVE] BP: stored temperature scale 0.736
[SAVE] BP: artifacts persisted (H=1)
[CAL] BP: loaded taus [0.78 0.2  0.66 0.3  0.2 ]
[CAL] BP: temperature scaling 0.736
Retraining model for ticker: BRK-A
[TRAIN] BRK-A: preparing data (H=1) with 1100 rows
[TRAIN] BRK-A: built 1088 sequences (seq_len=12)
[TRAIN] BRK-A: scaler fitted on 870 training sequences
[TRAIN] BRK-A: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BRK-A: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BRK-A: sector feature maxs = [0.03246263 0.0680742  0.01782321]
[TRAIN] BRK-A: model n_features = 37
[CAL] BRK-A: taus=[0.2  0.76 0.52 0.44 0.28] | temperature=0.871
[SAVE] BRK-A: stored taus
[SAVE] BRK-A: stored temperature scale 0.871
[SAVE] BRK-A: artifacts persisted (H=1)
[CAL] BRK-A: loaded taus [0.2  0.76 0.52 0.44 0.28]
[CAL] BRK-A: temperature scaling 0.871
Retraining model for ticker: BSAC
[TRAIN] BSAC: preparing data (H=1) with 1100 rows
[TRAIN] BSAC: built 1088 sequences (seq_len=12)
[TRAIN] BSAC: scaler fitted on 870 training sequences
[TRAIN] BSAC: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BSAC: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] BSAC: sector feature maxs = [0.03246263 0.0680742  0.01782321]
[TRAIN] BSAC: model n_features = 37
[CAL] BSAC: taus=[0.78 0.54 0.5  0.38 0.26] | temperature=0.871
[SAVE] BSAC: stored taus
[SAVE] BSAC: stored temperature scale 0.871
[SAVE] BSAC: artifacts persisted (H=1)
[CAL] BSAC: loaded taus [0.78 0.54 0.5  0.38 0.26]
[CAL] BSAC: temperature scaling 0.871
Retraining model for ticker: BUD
[TRAIN] BUD: preparing data (H=1) with 1100 rows
[TRAIN] BUD: built 1088 sequences (seq_len=12)
[TRAIN] BUD: scaler fitted on 870 training sequences
[TRAIN] BUD: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] BUD: sector feature mins = [-0.03740183 -0.09440794  0.00364845]
[TRAIN] BUD: sector feature maxs = [0.03194691 0.05042416 0.01893123]
[TRAIN] BUD: model n_features = 37
[CAL] BUD: taus=[0.2  0.78 0.72 0.5  0.6 ] | temperature=1.279
[SAVE] BUD: stored taus
[SAVE] BUD: stored temperature scale 1.279
[SAVE] BUD: artifacts persisted (H=1)
[CAL] BUD: loaded taus [0.2  0.78 0.72 0.5  0.6 ]
[CAL] BUD: temperature scaling 1.279
Retraining model for ticker: C
[TRAIN] C: preparing data (H=1) with 1100 rows
[TRAIN] C: built 1088 sequences (seq_len=12)
[TRAIN] C: scaler fitted on 870 training sequences
[TRAIN] C: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] C: sector feature mins = [-0.04114202 -0.0844463   0.00394133]
[TRAIN] C: sector feature maxs = [0.03246263 0.0680742  0.01782321]
[TRAIN] C: model n_features = 37
[CAL] C: taus=[0.74 0.74 0.56 0.5  0.48] | temperature=1.143
[SAVE] C: stored taus
[SAVE] C: stored temperature scale 1.143
[SAVE] C: artifacts persisted (H=1)
[CAL] C: loaded taus [0.74 0.74 0.56 0.5  0.48]
[CAL] C: temperature scaling 1.143
Retraining model for ticker: CAT
[TRAIN] CAT: preparing data (H=1) with 1100 rows
[TRAIN] CAT: built 1088 sequences (seq_len=12)
[TRAIN] CAT: scaler fitted on 870 training sequences
[TRAIN] CAT: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] CAT: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] CAT: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
[TRAIN] CAT: model n_features = 37
[CAL] CAT: taus=[0.76 0.66 0.48 0.46 0.44] | temperature=1.279
[SAVE] CAT: stored taus
[SAVE] CAT: stored temperature scale 1.279
[SAVE] CAT: artifacts persisted (H=1)
[CAL] CAT: loaded taus [0.76 0.66 0.48 0.46 0.44]
[CAL] CAT: temperature scaling 1.279
Retraining model for ticker: CELG
[TRAIN] CELG: preparing data (H=1) with 1100 rows
[TRAIN] CELG: built 1088 sequences (seq_len=12)
[TRAIN] CELG: scaler fitted on 870 training sequences
[TRAIN] CELG: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] CELG: sector feature mins = [-0.0410257  -0.11491243  0.00426767]
[TRAIN] CELG: sector feature maxs = [0.04369867 0.0870226  0.02237914]
[TRAIN] CELG: model n_features = 37
[CAL] CELG: taus=[0.62 0.52 0.46 0.42 0.38] | temperature=2.093
[SAVE] CELG: stored taus
[SAVE] CELG: stored temperature scale 2.093
[SAVE] CELG: artifacts persisted (H=1)
[CAL] CELG: loaded taus [0.62 0.52 0.46 0.42 0.38]
[CAL] CELG: temperature scaling 2.093
Retraining model for ticker: CHL
[TRAIN] CHL: preparing data (H=1) with 1100 rows
[TRAIN] CHL: built 1088 sequences (seq_len=12)
[TRAIN] CHL: scaler fitted on 870 training sequences
[TRAIN] CHL: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] CHL: sector feature mins = [-0.0442555  -0.11070618  0.00543296]
[TRAIN] CHL: sector feature maxs = [0.09751891 0.16866831 0.02562898]
[TRAIN] CHL: model n_features = 37
[CAL] CHL: taus=[0.8  0.66 0.5  0.2  0.2 ] | temperature=0.736
[SAVE] CHL: stored taus
[SAVE] CHL: stored temperature scale 0.736
[SAVE] CHL: artifacts persisted (H=1)
[CAL] CHL: loaded taus [0.8  0.66 0.5  0.2  0.2 ]
[CAL] CHL: temperature scaling 0.736
Retraining model for ticker: CHTR
[TRAIN] CHTR: preparing data (H=1) with 1100 rows
[TRAIN] CHTR: built 1088 sequences (seq_len=12)
[TRAIN] CHTR: scaler fitted on 870 training sequences
[TRAIN] CHTR: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] CHTR: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] CHTR: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] CHTR: model n_features = 37
[CAL] CHTR: taus=[0.8  0.74 0.54 0.46 0.4 ] | temperature=1.143
[SAVE] CHTR: stored taus
[SAVE] CHTR: stored temperature scale 1.143
[SAVE] CHTR: artifacts persisted (H=1)
[CAL] CHTR: loaded taus [0.8  0.74 0.54 0.46 0.4 ]
[CAL] CHTR: temperature scaling 1.143
Retraining model for ticker: CMCSA
[TRAIN] CMCSA: preparing data (H=1) with 1100 rows
[TRAIN] CMCSA: built 1088 sequences (seq_len=12)
[TRAIN] CMCSA: scaler fitted on 870 training sequences
[TRAIN] CMCSA: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] CMCSA: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] CMCSA: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] CMCSA: model n_features = 37
[CAL] CMCSA: taus=[0.76 0.64 0.2  0.5  0.46] | temperature=1.821
[SAVE] CMCSA: stored taus
[SAVE] CMCSA: stored temperature scale 1.821
[SAVE] CMCSA: artifacts persisted (H=1)
[CAL] CMCSA: loaded taus [0.76 0.64 0.2  0.5  0.46]
[CAL] CMCSA: temperature scaling 1.821
Retraining model for ticker: CODI
[TRAIN] CODI: preparing data (H=1) with 1100 rows
[TRAIN] CODI: built 1088 sequences (seq_len=12)
[TRAIN] CODI: scaler fitted on 870 training sequences
[TRAIN] CODI: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] CODI: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] CODI: sector feature maxs = [0.07760173 0.18492148 0.05036315]
[TRAIN] CODI: model n_features = 37
[CAL] CODI: taus=[0.2  0.8  0.66 0.48 0.32] | temperature=0.600
[SAVE] CODI: stored taus
[SAVE] CODI: stored temperature scale 0.600
[SAVE] CODI: artifacts persisted (H=1)
[CAL] CODI: loaded taus [0.2  0.8  0.66 0.48 0.32]
[CAL] CODI: temperature scaling 0.600
Retraining model for ticker: CSCO
[TRAIN] CSCO: preparing data (H=1) with 1100 rows
[TRAIN] CSCO: built 1088 sequences (seq_len=12)
[TRAIN] CSCO: scaler fitted on 870 training sequences
[TRAIN] CSCO: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] CSCO: sector feature mins = [-0.0442555  -0.11070618  0.00543296]
[TRAIN] CSCO: sector feature maxs = [0.09751891 0.16866831 0.02562898]
[TRAIN] CSCO: model n_features = 37
[CAL] CSCO: taus=[0.64 0.62 0.48 0.5  0.44] | temperature=1.550
[SAVE] CSCO: stored taus
[SAVE] CSCO: stored temperature scale 1.550
[SAVE] CSCO: artifacts persisted (H=1)
[CAL] CSCO: loaded taus [0.64 0.62 0.48 0.5  0.44]
[CAL] CSCO: temperature scaling 1.550
Retraining model for ticker: CVX
[TRAIN] CVX: preparing data (H=1) with 1100 rows
[TRAIN] CVX: built 1088 sequences (seq_len=12)
[TRAIN] CVX: scaler fitted on 870 training sequences
[TRAIN] CVX: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] CVX: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] CVX: sector feature maxs = [0.05341933 0.13994116 0.03044324]
[TRAIN] CVX: model n_features = 37
[CAL] CVX: taus=[0.62 0.42 0.46 0.4  0.38] | temperature=1.686
[SAVE] CVX: stored taus
[SAVE] CVX: stored temperature scale 1.686
[SAVE] CVX: artifacts persisted (H=1)
[CAL] CVX: loaded taus [0.62 0.42 0.46 0.4  0.38]
[CAL] CVX: temperature scaling 1.686
Retraining model for ticker: D
[TRAIN] D: preparing data (H=1) with 1100 rows
[TRAIN] D: built 1088 sequences (seq_len=12)
[TRAIN] D: scaler fitted on 870 training sequences
[TRAIN] D: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] D: sector feature mins = [-0.04000807 -0.08164836  0.00362283]
[TRAIN] D: sector feature maxs = [0.03053178 0.06078573 0.01557388]
[TRAIN] D: model n_features = 37
[CAL] D: taus=[0.64 0.2  0.5  0.46 0.42] | temperature=2.500
[SAVE] D: stored taus
[SAVE] D: stored temperature scale 2.500
[SAVE] D: artifacts persisted (H=1)
[CAL] D: loaded taus [0.64 0.2  0.5  0.46 0.42]
[CAL] D: temperature scaling 2.500
Retraining model for ticker: DHR
[TRAIN] DHR: preparing data (H=1) with 1100 rows
[TRAIN] DHR: built 1088 sequences (seq_len=12)
[TRAIN] DHR: scaler fitted on 870 training sequences
[TRAIN] DHR: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] DHR: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] DHR: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
[TRAIN] DHR: model n_features = 37
[CAL] DHR: taus=[0.8  0.78 0.46 0.28 0.2 ] | temperature=0.600
[SAVE] DHR: stored taus
[SAVE] DHR: stored temperature scale 0.600
[SAVE] DHR: artifacts persisted (H=1)
[CAL] DHR: loaded taus [0.8  0.78 0.46 0.28 0.2 ]
[CAL] DHR: temperature scaling 0.600
Retraining model for ticker: DIS
[TRAIN] DIS: preparing data (H=1) with 1100 rows
[TRAIN] DIS: built 1088 sequences (seq_len=12)
[TRAIN] DIS: scaler fitted on 870 training sequences
[TRAIN] DIS: scaler.n_features_in_ = 37, len(feature_cols) = 37
[TRAIN] DIS: sector feature mins = [-0.06810713 -0.10466671  0.00567241]
[TRAIN] DIS: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] DIS: model n_features = 37
[CAL] DIS: taus=[0.68 0.52 0.52 0.36 0.34] | temperature=1.279
[SAVE] DIS: stored taus
[SAVE] DIS: stored temperature scale 1.279
[SAVE] DIS: artifacts persisted (H=1)
[CAL] DIS: loaded taus [0.68 0.52 0.52 0.36 0.34]
[CAL] DIS: temperature scaling 1.279
Retraining model for ticker: DUK
[TRAIN] DUK: preparing data (H=1) with 1100 rows
[TRAIN] DUK: built 1088 sequences (seq_len=12)
[TRAIN] DUK: scaler fitted on 870 training sequences

Simulating Trading Days:   2%|▏         | 1/59 [14:59<14:29:20, 899.32s/it]

[CAL] XOM: taus=[0.72 0.54 0.5  0.48 0.4 ] | temperature=1.143
[SAVE] XOM: stored taus
[SAVE] XOM: stored temperature scale 1.143
[SAVE] XOM: artifacts persisted (H=1)
[CAL] XOM: loaded taus [0.72 0.54 0.5  0.48 0.4 ]
[CAL] XOM: temperature scaling 1.143
[SIM] 2017-06-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.669, kelly=0.360) with $3604.12 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.602, kelly=0.256) with $2556.23 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.830, kelly=0.658) with $6583.52 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.681, kelly=0.373) with $3734.27 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.619, kelly=0.229) with $2290.15 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.854, kelly=0.710) with $7103.44 allocation
[PORT] Sector Services: selecting WMT (p_up=0.676, kelly=0.341) with $3413.72 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.894, kelly=0.788) with $7881.54 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.755, kelly=0.504) with $5037.07 allocation
[SIM] 2017-06-09 00:00:00: 9 trades proposed.
[TRADE] 2017-06-09 00:00:00: allocated $7881.54 to VZ exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $7103.44 to UTX exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $6583.52 to UL exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $5037.07 to NGG exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $3394.43 to WFC exiting on 2017-06-12 00:00:00
[EXIT] 2017-06-12 00:00:00: VZ r=0.0101, PnL=$79.29
[EXIT] 2017-06-12 00:00:00: UTX r=-0.0063, PnL=$-44.75
[EXIT] 2017-06-12 00:00:00: UL r=-0.0097, PnL=$-63.56
[EXIT] 2017-06-12 00:00:00: NGG r=-0.0071, PnL=$-35.55
[EXIT] 2017-06-12 00:00:00: WFC r=0.0054, PnL=$18.30

Simulating Trading Days:   3%|▎         | 2/59 [15:01<5:52:46, 371.34s/it]

[SIM] 2017-06-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.673, kelly=0.368) with $3678.05 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.593, kelly=0.197) with $1971.00 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.854, kelly=0.706) with $7060.46 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.662, kelly=0.336) with $3363.28 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.625, kelly=0.241) with $2409.43 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.857, kelly=0.717) with $7168.81 allocation
[PORT] Sector Services: selecting WMT (p_up=0.698, kelly=0.385) with $3852.37 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.901, kelly=0.803) with $8027.90 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.765, kelly=0.523) with $5228.46 allocation
[SIM] 2017-06-12 00:00:00: 9 trades proposed.
[TRADE] 2017-06-12 00:00:00: allocated $8027.90 to VZ exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $7168.81 to UTX exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $7060.46 to UL exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $5228.46 to NGG exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $2500.49 to WMT exiting on 2017-06-13 00:00:00
[EXIT] 2017-06-13 00:00:00: VZ r=-0.0155, PnL=$-124.19
[EXIT] 2017-06-13 00:00:00: UTX r=0.0015, PnL=$10.76
[EXIT] 2017-06-13 00:00:00: UL r=-0.0026, PnL=$-18.18
[EXIT] 2017-06-13 00:00:00: NGG r=0.0127, PnL=$66.24
[EXIT] 2017-06-13 00:00:00: WMT r=0.0035, PnL=$8.84

Simulating Trading Days:   5%|▌         | 3/59 [15:02<3:08:56, 202.45s/it]

[SIM] 2017-06-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.674, kelly=0.369) with $3686.04 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.585, kelly=0.182) with $1820.53 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.878, kelly=0.755) with $7538.96 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.635, kelly=0.283) with $2826.56 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.632, kelly=0.257) with $2564.56 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.860, kelly=0.722) with $7215.91 allocation
[PORT] Sector Services: selecting WMT (p_up=0.694, kelly=0.379) with $3783.03 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.906, kelly=0.813) with $8117.13 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.772, kelly=0.538) with $5372.89 allocation
[SIM] 2017-06-13 00:00:00: 9 trades proposed.
[TRADE] 2017-06-13 00:00:00: allocated $8117.13 to VZ exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $7538.96 to UL exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $7215.91 to UTX exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $5372.89 to NGG exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $1724.26 to WMT exiting on 2017-06-14 00:00:00
[EXIT] 2017-06-14 00:00:00: VZ r=0.0050, PnL=$40.18
[EXIT] 2017-06-14 00:00:00: UL r=-0.0035, PnL=$-26.41
[EXIT] 2017-06-14 00:00:00: UTX r=-0.0004, PnL=$-3.00
[EXIT] 2017-06-14 00:00:00: NGG r=0.0011, PnL=$5.74
[EXIT] 2017-06-14 00:00:00: WMT r=0.0048, PnL=$8.24

Simulating Trading Days:   7%|▋         | 4/59 [15:04<1:52:51, 123.11s/it]

[SIM] 2017-06-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.665, kelly=0.352) with $3516.14 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.543, kelly=0.096) with $963.39 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.897, kelly=0.793) with $7921.40 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.591, kelly=0.204) with $2039.30 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.639, kelly=0.271) with $2704.46 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.850, kelly=0.703) with $7025.38 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.671, kelly=0.394) with $3938.12 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.907, kelly=0.816) with $8148.92 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.788, kelly=0.561) with $5607.30 allocation
[SIM] 2017-06-14 00:00:00: 9 trades proposed.
[TRADE] 2017-06-14 00:00:00: allocated $8148.92 to VZ exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $7921.40 to UL exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $7025.38 to UTX exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $5607.30 to NEE exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $1273.58 to CHTR exiting on 2017-06-15 00:00:00
[EXIT] 2017-06-15 00:00:00: VZ r=-0.0011, PnL=$-8.73
[EXIT] 2017-06-15 00:00:00: UL r=0.0024, PnL=$19.06
[EXIT] 2017-06-15 00:00:00: UTX r=0.0062, PnL=$43.32
[EXIT] 2017-06-15 00:00:00: NEE r=0.0051, PnL=$28.60
[EXIT] 2017-06-15 00:00:00: CHTR r=0.0000, PnL=$0.04

Simulating Trading Days:   8%|▊         | 5/59 [15:05<1:11:24, 79.35s/it]

[SIM] 2017-06-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.674, kelly=0.370) with $3699.81 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.543, kelly=0.096) with $956.17 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.912, kelly=0.822) with $8221.85 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.604, kelly=0.230) with $2295.10 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.645, kelly=0.283) with $2828.54 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.840, kelly=0.683) with $6830.90 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.675, kelly=0.402) with $4015.37 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.909, kelly=0.818) with $8183.08 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.802, kelly=0.589) with $5893.23 allocation
[SIM] 2017-06-15 00:00:00: 9 trades proposed.
[TRADE] 2017-06-15 00:00:00: allocated $8221.85 to UL exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $8183.08 to VZ exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $6830.90 to UTX exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $5893.23 to NEE exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $872.21 to CHTR exiting on 2017-06-16 00:00:00
[EXIT] 2017-06-16 00:00:00: UL r=0.0096, PnL=$78.93
[EXIT] 2017-06-16 00:00:00: VZ r=-0.0002, PnL=$-1.75
[EXIT] 2017-06-16 00:00:00: UTX r=-0.0027, PnL=$-18.10
[EXIT] 2017-06-16 00:00:00: NEE r=0.0068, PnL=$40.29
[EXIT] 2017-06-16 00:00:00: CHTR r=0.0056, PnL=$4.85

Simulating Trading Days:  10%|█         | 6/59 [15:07<46:45, 52.94s/it]

[SIM] 2017-06-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.675, kelly=0.371) with $3712.96 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.543, kelly=0.096) with $956.26 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.922, kelly=0.843) with $8442.27 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.621, kelly=0.263) with $2631.99 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.651, kelly=0.295) with $2951.76 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.825, kelly=0.654) with $6545.47 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.678, kelly=0.406) with $4066.39 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.910, kelly=0.820) with $8208.67 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.809, kelly=0.603) with $6038.70 allocation
[SIM] 2017-06-16 00:00:00: 9 trades proposed.
[TRADE] 2017-06-16 00:00:00: allocated $8442.27 to UL exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $8208.67 to VZ exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $6545.47 to UTX exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $6038.70 to NEE exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $797.42 to CHTR exiting on 2017-06-19 00:00:00
[EXIT] 2017-06-19 00:00:00: UL r=0.0033, PnL=$27.79
[EXIT] 2017-06-19 00:00:00: VZ r=-0.0013, PnL=$-10.56
[EXIT] 2017-06-19 00:00:00: UTX r=0.0118, PnL=$77.18
[EXIT] 2017-06-19 00:00:00: NEE r=-0.0032, PnL=$-19.02
[EXIT] 2017-06-19 00:00:00: CHTR r=0.0001, PnL=$0.09

Simulating Trading Days:  12%|█▏        | 7/59 [15:09<31:19, 36.14s/it]

[SIM] 2017-06-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.679, kelly=0.380) with $3806.71 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.535, kelly=0.073) with $730.39 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.929, kelly=0.857) with $8580.95 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.640, kelly=0.300) with $3004.22 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.656, kelly=0.305) with $3055.92 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.810, kelly=0.623) with $6237.76 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.689, kelly=0.427) with $4275.78 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.909, kelly=0.819) with $8205.40 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.805, kelly=0.595) with $5960.01 allocation
[SIM] 2017-06-19 00:00:00: 9 trades proposed.
[TRADE] 2017-06-19 00:00:00: allocated $8580.95 to UL exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $8205.40 to VZ exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $6237.76 to UTX exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $5960.01 to NEE exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $1071.05 to CHTR exiting on 2017-06-20 00:00:00
[EXIT] 2017-06-20 00:00:00: UL r=-0.0093, PnL=$-79.76
[EXIT] 2017-06-20 00:00:00: VZ r=-0.0135, PnL=$-111.00
[EXIT] 2017-06-20 00:00:00: UTX r=-0.0028, PnL=$-17.41
[EXIT] 2017-06-20 00:00:00: NEE r=-0.0030, PnL=$-18.00
[EXIT] 2017-06-20 00:00:00: CHTR r=-0.0195, PnL=$-20.93

Simulating Trading Days:  14%|█▎        | 8/59 [15:10<21:23, 25.17s/it]

[SIM] 2017-06-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.674, kelly=0.370) with $3696.02 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.543, kelly=0.096) with $963.79 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.932, kelly=0.862) with $8616.03 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.653, kelly=0.326) with $3256.30 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.657, kelly=0.306) with $3061.01 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.788, kelly=0.580) with $5800.11 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.686, kelly=0.421) with $4208.29 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.908, kelly=0.816) with $8154.30 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.794, kelly=0.573) with $5730.72 allocation
[SIM] 2017-06-20 00:00:00: 9 trades proposed.
[TRADE] 2017-06-20 00:00:00: allocated $8616.03 to UL exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $8154.30 to VZ exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5730.72 to NEE exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5800.11 to UTX exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $1679.88 to CHTR exiting on 2017-06-21 00:00:00
[EXIT] 2017-06-21 00:00:00: UL r=0.0028, PnL=$23.77
[EXIT] 2017-06-21 00:00:00: VZ r=-0.0115, PnL=$-94.07
[EXIT] 2017-06-21 00:00:00: NEE r=-0.0063, PnL=$-36.33
[EXIT] 2017-06-21 00:00:00: UTX r=0.0020, PnL=$11.46
[EXIT] 2017-06-21 00:00:00: CHTR r=0.0008, PnL=$1.36

Simulating Trading Days:  15%|█▌        | 9/59 [15:12<14:51, 17.83s/it]

[SIM] 2017-06-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.677, kelly=0.375) with $3742.51 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.543, kelly=0.096) with $960.04 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.934, kelly=0.867) with $8660.59 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.665, kelly=0.348) with $3477.18 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.655, kelly=0.303) with $3025.28 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.783, kelly=0.569) with $5681.44 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.688, kelly=0.426) with $4249.19 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.908, kelly=0.816) with $8149.13 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.783, kelly=0.549) with $5485.13 allocation
[SIM] 2017-06-21 00:00:00: 9 trades proposed.
[TRADE] 2017-06-21 00:00:00: allocated $8660.59 to UL exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $8149.13 to VZ exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $5485.13 to NEE exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $5681.44 to UTX exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $1976.60 to CHTR exiting on 2017-06-22 00:00:00
[EXIT] 2017-06-22 00:00:00: UL r=-0.0035, PnL=$-30.19
[EXIT] 2017-06-22 00:00:00: VZ r=0.0002, PnL=$1.79
[EXIT] 2017-06-22 00:00:00: NEE r=0.0038, PnL=$20.61
[EXIT] 2017-06-22 00:00:00: UTX r=0.0034, PnL=$19.60
[EXIT] 2017-06-22 00:00:00: CHTR r=0.0007, PnL=$1.48

Simulating Trading Days:  17%|█▋        | 10/59 [15:13<10:27, 12.81s/it]

[SIM] 2017-06-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.691, kelly=0.403) with $4025.53 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.534, kelly=0.081) with $807.61 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.936, kelly=0.871) with $8696.25 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.674, kelly=0.365) with $3646.68 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.650, kelly=0.292) with $2915.88 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.787, kelly=0.577) with $5762.85 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.690, kelly=0.430) with $4292.72 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.908, kelly=0.817) with $8155.72 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.790, kelly=0.565) with $5643.22 allocation
[SIM] 2017-06-22 00:00:00: 9 trades proposed.
[TRADE] 2017-06-22 00:00:00: allocated $8696.25 to UL exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $8155.72 to VZ exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $5643.22 to NEE exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $5762.85 to UTX exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $1698.85 to SLB exiting on 2017-06-23 00:00:00
[EXIT] 2017-06-23 00:00:00: UL r=0.0006, PnL=$4.80
[EXIT] 2017-06-23 00:00:00: VZ r=-0.0007, PnL=$-5.39
[EXIT] 2017-06-23 00:00:00: NEE r=0.0109, PnL=$61.78
[EXIT] 2017-06-23 00:00:00: UTX r=0.0004, PnL=$2.36
[EXIT] 2017-06-23 00:00:00: SLB r=0.0086, PnL=$14.55

Simulating Trading Days:  19%|█▊        | 11/59 [15:15<07:27,  9.33s/it]

[SIM] 2017-06-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.697, kelly=0.413) with $4131.81 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.538, kelly=0.089) with $887.47 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.938, kelly=0.875) with $8740.85 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.678, kelly=0.375) with $3742.97 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.642, kelly=0.277) with $2767.79 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.800, kelly=0.603) with $6023.81 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.692, kelly=0.433) with $4329.19 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.909, kelly=0.818) with $8175.81 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.798, kelly=0.581) with $5805.48 allocation
[SIM] 2017-06-23 00:00:00: 9 trades proposed.
[TRADE] 2017-06-23 00:00:00: allocated $8740.85 to UL exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $8175.81 to VZ exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $6023.81 to UTX exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $5805.48 to NEE exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $1234.37 to SLB exiting on 2017-06-26 00:00:00
[EXIT] 2017-06-26 00:00:00: UL r=0.0088, PnL=$77.20
[EXIT] 2017-06-26 00:00:00: VZ r=0.0079, PnL=$64.84
[EXIT] 2017-06-26 00:00:00: UTX r=-0.0029, PnL=$-17.25
[EXIT] 2017-06-26 00:00:00: NEE r=0.0076, PnL=$44.21
[EXIT] 2017-06-26 00:00:00: SLB r=-0.0006, PnL=$-0.75

Simulating Trading Days:  20%|██        | 12/59 [15:16<05:26,  6.94s/it]

[SIM] 2017-06-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.697, kelly=0.413) with $4137.34 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.542, kelly=0.096) with $965.92 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.939, kelly=0.878) with $8786.11 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.681, kelly=0.379) with $3793.60 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.632, kelly=0.256) with $2560.52 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.806, kelly=0.615) with $6153.93 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.701, kelly=0.450) with $4505.74 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.910, kelly=0.820) with $8207.22 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.815, kelly=0.616) with $6169.28 allocation
[SIM] 2017-06-26 00:00:00: 9 trades proposed.
[TRADE] 2017-06-26 00:00:00: allocated $8786.11 to UL exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $8207.22 to VZ exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $6169.28 to NEE exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $6153.93 to UTX exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $714.26 to CHTR exiting on 2017-06-27 00:00:00
[EXIT] 2017-06-27 00:00:00: UL r=-0.0013, PnL=$-11.22
[EXIT] 2017-06-27 00:00:00: VZ r=-0.0199, PnL=$-163.25
[EXIT] 2017-06-27 00:00:00: NEE r=-0.0136, PnL=$-83.84
[EXIT] 2017-06-27 00:00:00: UTX r=-0.0023, PnL=$-14.14
[EXIT] 2017-06-27 00:00:00: CHTR r=-0.0084, PnL=$-5.97

Simulating Trading Days:  22%|██▏       | 13/59 [15:18<04:04,  5.31s/it]

[SIM] 2017-06-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.695, kelly=0.411) with $4100.12 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.545, kelly=0.101) with $1013.19 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.940, kelly=0.879) with $8775.38 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.675, kelly=0.368) with $3668.93 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.616, kelly=0.223) with $2230.17 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.819, kelly=0.642) with $6409.26 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.699, kelly=0.446) with $4455.69 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.912, kelly=0.825) with $8238.96 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.816, kelly=0.618) with $6172.78 allocation
[SIM] 2017-06-27 00:00:00: 9 trades proposed.
[TRADE] 2017-06-27 00:00:00: allocated $8775.38 to UL exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $8238.96 to VZ exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $6409.26 to UTX exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $6172.78 to NEE exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $350.89 to CHTR exiting on 2017-06-28 00:00:00
[EXIT] 2017-06-28 00:00:00: UL r=0.0068, PnL=$59.29
[EXIT] 2017-06-28 00:00:00: VZ r=0.0000, PnL=$0.00
[EXIT] 2017-06-28 00:00:00: UTX r=0.0075, PnL=$47.97
[EXIT] 2017-06-28 00:00:00: NEE r=-0.0088, PnL=$-54.23
[EXIT] 2017-06-28 00:00:00: CHTR r=0.0316, PnL=$11.09

Simulating Trading Days:  24%|██▎       | 14/59 [15:19<03:06,  4.15s/it]

[SIM] 2017-06-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.696, kelly=0.412) with $4111.71 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.562, kelly=0.182) with $1815.44 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.940, kelly=0.879) with $8780.75 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.663, kelly=0.344) with $3435.13 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.600, kelly=0.192) with $1914.53 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.839, kelly=0.682) with $6809.84 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.702, kelly=0.451) with $4500.59 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.918, kelly=0.837) with $8356.97 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.822, kelly=0.631) with $6298.44 allocation
[SIM] 2017-06-28 00:00:00: 9 trades proposed.
[TRADE] 2017-06-28 00:00:00: allocated $8780.75 to UL exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $8356.97 to VZ exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $6809.84 to UTX exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $6018.94 to NEE exiting on 2017-06-29 00:00:00
[EXIT] 2017-06-29 00:00:00: UL r=-0.0281, PnL=$-246.87
[EXIT] 2017-06-29 00:00:00: VZ r=-0.0096, PnL=$-80.14
[EXIT] 2017-06-29 00:00:00: UTX r=-0.0069, PnL=$-47.25
[EXIT] 2017-06-29 00:00:00: NEE r=-0.0074, PnL=$-44.82

Simulating Trading Days:  25%|██▌       | 15/59 [15:21<02:32,  3.46s/it]

[SIM] 2017-06-29 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.695, kelly=0.410) with $4082.43 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.571, kelly=0.198) with $1973.90 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.936, kelly=0.872) with $8671.90 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.646, kelly=0.311) with $3089.05 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.582, kelly=0.156) with $1552.11 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.842, kelly=0.687) with $6836.82 allocation
[PORT] Sector Services: selecting WMT (p_up=0.718, kelly=0.427) with $4244.91 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.924, kelly=0.848) with $8439.60 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.832, kelly=0.652) with $6483.97 allocation
[SIM] 2017-06-29 00:00:00: 9 trades proposed.
[TRADE] 2017-06-29 00:00:00: allocated $8671.90 to UL exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $8439.60 to VZ exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $6836.82 to UTX exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $5892.47 to NEE exiting on 2017-06-30 00:00:00
[EXIT] 2017-06-30 00:00:00: UL r=0.0101, PnL=$87.40
[EXIT] 2017-06-30 00:00:00: VZ r=0.0056, PnL=$47.51
[EXIT] 2017-06-30 00:00:00: UTX r=0.0038, PnL=$25.85
[EXIT] 2017-06-30 00:00:00: NEE r=0.0011, PnL=$6.74

Simulating Trading Days:  27%|██▋       | 16/59 [15:23<02:05,  2.93s/it]

[SIM] 2017-06-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.701, kelly=0.423) with $4210.77 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.565, kelly=0.187) with $1859.74 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.936, kelly=0.870) with $8672.16 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.631, kelly=0.281) with $2804.48 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.573, kelly=0.136) with $1354.25 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.865, kelly=0.732) with $7298.02 allocation
[PORT] Sector Services: selecting WMT (p_up=0.733, kelly=0.457) with $4549.07 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.930, kelly=0.861) with $8578.18 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.851, kelly=0.691) with $6881.24 allocation
[SIM] 2017-06-30 00:00:00: 9 trades proposed.
[TRADE] 2017-06-30 00:00:00: allocated $8672.16 to UL exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $8578.18 to VZ exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $7298.02 to UTX exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $5342.67 to NEE exiting on 2017-07-03 00:00:00
[EXIT] 2017-07-03 00:00:00: UL r=-0.0054, PnL=$-46.47
[EXIT] 2017-07-03 00:00:00: VZ r=0.0076, PnL=$65.31
[EXIT] 2017-07-03 00:00:00: UTX r=-0.0002, PnL=$-1.79
[EXIT] 2017-07-03 00:00:00: NEE r=-0.0036, PnL=$-19.44

Simulating Trading Days:  29%|██▉       | 17/59 [15:25<01:46,  2.53s/it]

[SIM] 2017-07-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.701, kelly=0.421) with $4196.92 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.554, kelly=0.119) with $1188.24 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.934, kelly=0.866) with $8632.90 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.612, kelly=0.245) with $2440.85 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.598, kelly=0.218) with $2169.61 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.869, kelly=0.740) with $7377.71 allocation
[PORT] Sector Services: selecting WMT (p_up=0.742, kelly=0.475) with $4727.69 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.935, kelly=0.870) with $8668.42 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.862, kelly=0.714) with $7114.00 allocation
[SIM] 2017-07-03 00:00:00: 9 trades proposed.
[TRADE] 2017-07-03 00:00:00: allocated $8668.42 to VZ exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $8632.90 to UL exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $7377.71 to UTX exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $5211.29 to NEE exiting on 2017-07-05 00:00:00
[EXIT] 2017-07-05 00:00:00: VZ r=-0.0078, PnL=$-67.42
[EXIT] 2017-07-05 00:00:00: UL r=-0.0017, PnL=$-14.43
[EXIT] 2017-07-05 00:00:00: UTX r=0.0058, PnL=$42.91
[EXIT] 2017-07-05 00:00:00: NEE r=-0.0057, PnL=$-29.86

Simulating Trading Days:  31%|███       | 18/59 [15:26<01:31,  2.23s/it]

[SIM] 2017-07-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.697, kelly=0.415) with $4128.63 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.653, kelly=0.308) with $3071.55 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.934, kelly=0.867) with $8634.41 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.598, kelly=0.218) with $2168.53 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.610, kelly=0.242) with $2405.20 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.867, kelly=0.736) with $7323.80 allocation
[PORT] Sector Services: selecting WMT (p_up=0.769, kelly=0.531) with $5287.28 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.938, kelly=0.876) with $8723.24 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.867, kelly=0.724) with $7207.61 allocation
[SIM] 2017-07-05 00:00:00: 9 trades proposed.
[TRADE] 2017-07-05 00:00:00: allocated $8723.24 to VZ exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $8634.41 to UL exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $7207.61 to NEE exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $5304.41 to UTX exiting on 2017-07-06 00:00:00
[EXIT] 2017-07-06 00:00:00: VZ r=-0.0253, PnL=$-220.77
[EXIT] 2017-07-06 00:00:00: UL r=-0.0050, PnL=$-43.38
[EXIT] 2017-07-06 00:00:00: NEE r=0.0054, PnL=$38.94
[EXIT] 2017-07-06 00:00:00: UTX r=-0.0073, PnL=$-38.88

Simulating Trading Days:  32%|███▏      | 19/59 [15:28<01:20,  2.02s/it]

[SIM] 2017-07-06 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.700, kelly=0.420) with $4169.75 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.736, kelly=0.473) with $4698.22 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.935, kelly=0.868) with $8623.46 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.589, kelly=0.200) with $1989.00 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.617, kelly=0.256) with $2540.65 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.854, kelly=0.710) with $7052.45 allocation
[PORT] Sector Services: selecting WMT (p_up=0.770, kelly=0.533) with $5289.92 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.939, kelly=0.878) with $8716.90 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.873, kelly=0.737) with $7314.12 allocation
[SIM] 2017-07-06 00:00:00: 9 trades proposed.
[TRADE] 2017-07-06 00:00:00: allocated $8716.90 to VZ exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $8623.46 to UL exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $7314.12 to NEE exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $5135.97 to UTX exiting on 2017-07-07 00:00:00
[EXIT] 2017-07-07 00:00:00: VZ r=-0.0009, PnL=$-8.01
[EXIT] 2017-07-07 00:00:00: UL r=0.0047, PnL=$40.32
[EXIT] 2017-07-07 00:00:00: NEE r=0.0065, PnL=$47.69
[EXIT] 2017-07-07 00:00:00: UTX r=0.0059, PnL=$30.34

Simulating Trading Days:  34%|███▍      | 20/59 [15:29<01:13,  1.88s/it]

[SIM] 2017-07-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.701, kelly=0.421) with $4187.89 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.785, kelly=0.572) with $5683.65 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.937, kelly=0.873) with $8676.55 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.586, kelly=0.194) with $1933.25 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.593, kelly=0.187) with $1856.31 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.855, kelly=0.713) with $7089.12 allocation
[PORT] Sector Services: selecting WMT (p_up=0.773, kelly=0.539) with $5362.57 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.940, kelly=0.881) with $8761.96 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.874, kelly=0.740) with $7352.31 allocation
[SIM] 2017-07-07 00:00:00: 9 trades proposed.
[TRADE] 2017-07-07 00:00:00: allocated $8761.96 to VZ exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $8676.55 to UL exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $7352.31 to NEE exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $5032.72 to UTX exiting on 2017-07-10 00:00:00
[EXIT] 2017-07-10 00:00:00: VZ r=-0.0064, PnL=$-56.42
[EXIT] 2017-07-10 00:00:00: UL r=0.0056, PnL=$48.45
[EXIT] 2017-07-10 00:00:00: NEE r=0.0039, PnL=$28.79
[EXIT] 2017-07-10 00:00:00: UTX r=0.0037, PnL=$18.47

Simulating Trading Days:  36%|███▌      | 21/59 [15:31<01:07,  1.76s/it]

[SIM] 2017-07-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.698, kelly=0.416) with $4134.42 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.806, kelly=0.613) with $6098.14 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.938, kelly=0.875) with $8700.50 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.580, kelly=0.183) with $1818.09 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.606, kelly=0.212) with $2110.17 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.845, kelly=0.692) with $6881.23 allocation
[PORT] Sector Services: selecting WMT (p_up=0.768, kelly=0.527) with $5243.68 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.942, kelly=0.884) with $8791.75 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.869, kelly=0.728) with $7243.54 allocation
[SIM] 2017-07-10 00:00:00: 9 trades proposed.
[TRADE] 2017-07-10 00:00:00: allocated $8791.75 to VZ exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $8700.50 to UL exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $7243.54 to NEE exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $5099.54 to UTX exiting on 2017-07-11 00:00:00
[EXIT] 2017-07-11 00:00:00: VZ r=-0.0072, PnL=$-63.09
[EXIT] 2017-07-11 00:00:00: UL r=0.0057, PnL=$49.93
[EXIT] 2017-07-11 00:00:00: NEE r=-0.0020, PnL=$-14.38
[EXIT] 2017-07-11 00:00:00: UTX r=0.0039, PnL=$19.89

Simulating Trading Days:  37%|███▋      | 22/59 [15:32<01:03,  1.72s/it]

[SIM] 2017-07-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.694, kelly=0.408) with $4055.86 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.811, kelly=0.623) with $6190.50 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.939, kelly=0.876) with $8714.06 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.577, kelly=0.178) with $1769.31 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.617, kelly=0.234) with $2326.76 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.836, kelly=0.674) with $6702.72 allocation
[PORT] Sector Services: selecting WMT (p_up=0.756, kelly=0.504) with $5008.46 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.942, kelly=0.885) with $8804.08 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.862, kelly=0.714) with $7099.81 allocation
[SIM] 2017-07-11 00:00:00: 9 trades proposed.
[TRADE] 2017-07-11 00:00:00: allocated $8804.08 to VZ exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $8714.06 to UL exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $7099.81 to NEE exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $5215.08 to UTX exiting on 2017-07-12 00:00:00
[EXIT] 2017-07-12 00:00:00: VZ r=0.0077, PnL=$67.74
[EXIT] 2017-07-12 00:00:00: UL r=0.0087, PnL=$75.38
[EXIT] 2017-07-12 00:00:00: NEE r=0.0002, PnL=$1.51
[EXIT] 2017-07-12 00:00:00: UTX r=0.0014, PnL=$7.18

Simulating Trading Days:  39%|███▉      | 23/59 [15:34<01:01,  1.71s/it]

[SIM] 2017-07-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.689, kelly=0.398) with $3966.90 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.806, kelly=0.613) with $6108.52 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.938, kelly=0.874) with $8707.91 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.578, kelly=0.178) with $1776.36 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.626, kelly=0.251) with $2498.99 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.825, kelly=0.654) with $6510.03 allocation
[PORT] Sector Services: selecting WMT (p_up=0.748, kelly=0.487) with $4848.59 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.943, kelly=0.887) with $8831.73 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.855, kelly=0.700) with $6967.89 allocation
[SIM] 2017-07-12 00:00:00: 9 trades proposed.
[TRADE] 2017-07-12 00:00:00: allocated $8831.73 to VZ exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $8707.91 to UL exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $6967.89 to NEE exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $5371.05 to UTX exiting on 2017-07-13 00:00:00
[EXIT] 2017-07-13 00:00:00: VZ r=0.0062, PnL=$55.17
[EXIT] 2017-07-13 00:00:00: UL r=0.0089, PnL=$77.86
[EXIT] 2017-07-13 00:00:00: NEE r=-0.0014, PnL=$-9.90
[EXIT] 2017-07-13 00:00:00: UTX r=-0.0052, PnL=$-27.79

Simulating Trading Days:  41%|████      | 24/59 [15:36<00:58,  1.68s/it]

[SIM] 2017-07-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.684, kelly=0.388) with $3869.29 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.795, kelly=0.590) with $5885.29 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.934, kelly=0.866) with $8634.41 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.639, kelly=0.324) with $3227.30 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.627, kelly=0.254) with $2536.39 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.812, kelly=0.627) with $6250.93 allocation
[PORT] Sector Services: selecting WMT (p_up=0.731, kelly=0.453) with $4520.16 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.944, kelly=0.888) with $8854.63 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.845, kelly=0.678) with $6755.96 allocation
[SIM] 2017-07-13 00:00:00: 9 trades proposed.
[TRADE] 2017-07-13 00:00:00: allocated $8854.63 to VZ exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $8634.41 to UL exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $6755.96 to NEE exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $5662.18 to UTX exiting on 2017-07-14 00:00:00
[EXIT] 2017-07-14 00:00:00: VZ r=0.0016, PnL=$14.25
[EXIT] 2017-07-14 00:00:00: UL r=0.0114, PnL=$98.38
[EXIT] 2017-07-14 00:00:00: NEE r=0.0077, PnL=$51.90
[EXIT] 2017-07-14 00:00:00: UTX r=0.0028, PnL=$15.64

Simulating Trading Days:  42%|████▏     | 25/59 [15:37<00:57,  1.69s/it]

[SIM] 2017-07-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.674, kelly=0.369) with $3688.78 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.761, kelly=0.524) with $5231.03 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.927, kelly=0.853) with $8515.67 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.637, kelly=0.320) with $3196.97 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.630, kelly=0.260) with $2592.52 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.805, kelly=0.614) with $6128.64 allocation
[PORT] Sector Services: selecting WMT (p_up=0.725, kelly=0.440) with $4398.83 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.944, kelly=0.888) with $8868.06 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.838, kelly=0.665) with $6636.81 allocation
[SIM] 2017-07-14 00:00:00: 9 trades proposed.
[TRADE] 2017-07-14 00:00:00: allocated $8868.06 to VZ exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $8515.67 to UL exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $6636.81 to NEE exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $5940.71 to UTX exiting on 2017-07-17 00:00:00
[EXIT] 2017-07-17 00:00:00: VZ r=0.0023, PnL=$20.36
[EXIT] 2017-07-17 00:00:00: UL r=-0.0014, PnL=$-12.18
[EXIT] 2017-07-17 00:00:00: NEE r=-0.0049, PnL=$-32.33
[EXIT] 2017-07-17 00:00:00: UTX r=-0.0024, PnL=$-14.44

Simulating Trading Days:  44%|████▍     | 26/59 [15:40<01:05,  1.99s/it]

[SIM] 2017-07-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.663, kelly=0.348) with $3476.96 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.706, kelly=0.414) with $4129.04 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.917, kelly=0.833) with $8313.02 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.638, kelly=0.321) with $3205.70 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.626, kelly=0.251) with $2510.49 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.798, kelly=0.600) with $5994.63 allocation
[PORT] Sector Services: selecting WMT (p_up=0.723, kelly=0.436) with $4351.57 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.942, kelly=0.885) with $8836.89 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.826, kelly=0.640) with $6387.24 allocation
[SIM] 2017-07-17 00:00:00: 9 trades proposed.
[TRADE] 2017-07-17 00:00:00: allocated $8836.89 to VZ exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $8313.02 to UL exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $6387.24 to NEE exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $5994.63 to UTX exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $417.88 to WMT exiting on 2017-07-18 00:00:00
[EXIT] 2017-07-18 00:00:00: VZ r=-0.0069, PnL=$-60.72
[EXIT] 2017-07-18 00:00:00: UL r=0.0000, PnL=$0.00
[EXIT] 2017-07-18 00:00:00: NEE r=0.0037, PnL=$23.56
[EXIT] 2017-07-18 00:00:00: UTX r=-0.0039, PnL=$-23.37
[EXIT] 2017-07-18 00:00:00: WMT r=-0.0022, PnL=$-0.93

Simulating Trading Days:  46%|████▌     | 27/59 [15:42<00:59,  1.85s/it]

[SIM] 2017-07-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.655, kelly=0.333) with $3320.04 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.636, kelly=0.275) with $2740.69 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.906, kelly=0.811) with $8094.87 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.636, kelly=0.319) with $3178.23 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.624, kelly=0.248) with $2477.77 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.803, kelly=0.609) with $6076.51 allocation
[PORT] Sector Services: selecting WMT (p_up=0.734, kelly=0.459) with $4579.41 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.941, kelly=0.883) with $8813.35 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.821, kelly=0.629) with $6275.08 allocation
[SIM] 2017-07-18 00:00:00: 9 trades proposed.
[TRADE] 2017-07-18 00:00:00: allocated $8813.35 to VZ exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $8094.87 to UL exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $6275.08 to NEE exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $6076.51 to UTX exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $671.41 to WMT exiting on 2017-07-19 00:00:00
[EXIT] 2017-07-19 00:00:00: VZ r=0.0021, PnL=$18.29
[EXIT] 2017-07-19 00:00:00: UL r=0.0013, PnL=$10.15
[EXIT] 2017-07-19 00:00:00: NEE r=0.0022, PnL=$13.75
[EXIT] 2017-07-19 00:00:00: UTX r=0.0037, PnL=$22.30
[EXIT] 2017-07-19 00:00:00: WMT r=-0.0043, PnL=$-2.91

Simulating Trading Days:  47%|████▋     | 28/59 [15:43<00:54,  1.75s/it]

[SIM] 2017-07-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.650, kelly=0.323) with $3229.10 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.545, kelly=0.092) with $921.10 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.895, kelly=0.789) with $7876.13 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.635, kelly=0.316) with $3153.12 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.619, kelly=0.237) with $2370.98 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.820, kelly=0.643) with $6417.10 allocation
[PORT] Sector Services: selecting WMT (p_up=0.750, kelly=0.493) with $4916.97 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.941, kelly=0.883) with $8818.92 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.799, kelly=0.584) with $5829.75 allocation
[SIM] 2017-07-19 00:00:00: 9 trades proposed.
[TRADE] 2017-07-19 00:00:00: allocated $8818.92 to VZ exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $7876.13 to UL exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $6417.10 to UTX exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $5829.75 to NEE exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $1007.80 to WMT exiting on 2017-07-20 00:00:00
[EXIT] 2017-07-20 00:00:00: VZ r=0.0177, PnL=$156.28
[EXIT] 2017-07-20 00:00:00: UL r=0.0170, PnL=$133.83
[EXIT] 2017-07-20 00:00:00: UTX r=-0.0051, PnL=$-32.85
[EXIT] 2017-07-20 00:00:00: NEE r=0.0118, PnL=$69.07
[EXIT] 2017-07-20 00:00:00: WMT r=0.0020, PnL=$1.99

Simulating Trading Days:  49%|████▉     | 29/59 [15:45<00:50,  1.67s/it]

[SIM] 2017-07-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.647, kelly=0.317) with $3170.27 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.584, kelly=0.180) with $1804.67 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.886, kelly=0.770) with $7708.48 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.629, kelly=0.306) with $3062.20 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.606, kelly=0.211) with $2117.57 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.825, kelly=0.652) with $6534.06 allocation
[PORT] Sector Services: selecting WMT (p_up=0.758, kelly=0.508) with $5084.56 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.941, kelly=0.883) with $8840.49 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.767, kelly=0.516) with $5168.97 allocation
[SIM] 2017-07-20 00:00:00: 9 trades proposed.
[TRADE] 2017-07-20 00:00:00: allocated $8840.49 to VZ exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $7708.48 to UL exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $6534.06 to UTX exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $5168.97 to NEE exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $1796.20 to WMT exiting on 2017-07-21 00:00:00
[EXIT] 2017-07-21 00:00:00: VZ r=0.0002, PnL=$2.00
[EXIT] 2017-07-21 00:00:00: UL r=0.0040, PnL=$31.18
[EXIT] 2017-07-21 00:00:00: UTX r=0.0085, PnL=$55.50
[EXIT] 2017-07-21 00:00:00: NEE r=0.0062, PnL=$32.06
[EXIT] 2017-07-21 00:00:00: WMT r=0.0017, PnL=$3.07

Simulating Trading Days:  51%|█████     | 30/59 [15:46<00:47,  1.62s/it]

[SIM] 2017-07-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.647, kelly=0.318) with $3189.81 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.617, kelly=0.246) with $2466.57 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.877, kelly=0.752) with $7541.34 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.616, kelly=0.246) with $2462.12 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.609, kelly=0.209) with $2100.25 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.841, kelly=0.684) with $6860.26 allocation
[PORT] Sector Services: selecting WMT (p_up=0.764, kelly=0.519) with $5206.96 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.941, kelly=0.882) with $8841.07 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.736, kelly=0.451) with $4527.81 allocation
[SIM] 2017-07-21 00:00:00: 9 trades proposed.
[TRADE] 2017-07-21 00:00:00: allocated $8841.07 to VZ exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $7541.34 to UL exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $6860.26 to UTX exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $5206.96 to WMT exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $1635.71 to NEE exiting on 2017-07-24 00:00:00
[EXIT] 2017-07-24 00:00:00: VZ r=-0.0118, PnL=$-103.94
[EXIT] 2017-07-24 00:00:00: UL r=-0.0103, PnL=$-77.94
[EXIT] 2017-07-24 00:00:00: UTX r=-0.0029, PnL=$-20.00
[EXIT] 2017-07-24 00:00:00: WMT r=0.0097, PnL=$50.60
[EXIT] 2017-07-24 00:00:00: NEE r=-0.0085, PnL=$-13.82

Simulating Trading Days:  53%|█████▎    | 31/59 [15:48<00:44,  1.60s/it]

[SIM] 2017-07-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.658, kelly=0.339) with $3393.71 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.651, kelly=0.312) with $3123.87 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.869, kelly=0.737) with $7376.18 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.641, kelly=0.295) with $2951.24 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.612, kelly=0.215) with $2149.69 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.849, kelly=0.702) with $7024.40 allocation
[PORT] Sector Services: selecting WMT (p_up=0.766, kelly=0.524) with $5243.88 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.939, kelly=0.879) with $8799.25 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.705, kelly=0.388) with $3881.72 allocation
[SIM] 2017-07-24 00:00:00: 9 trades proposed.
[TRADE] 2017-07-24 00:00:00: allocated $8799.25 to VZ exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $7376.18 to UL exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $7024.40 to UTX exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $5243.88 to WMT exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $1592.10 to NEE exiting on 2017-07-25 00:00:00
[EXIT] 2017-07-25 00:00:00: VZ r=0.0062, PnL=$54.35
[EXIT] 2017-07-25 00:00:00: UL r=0.0027, PnL=$19.58
[EXIT] 2017-07-25 00:00:00: UTX r=-0.0220, PnL=$-154.60
[EXIT] 2017-07-25 00:00:00: WMT r=0.0212, PnL=$111.17
[EXIT] 2017-07-25 00:00:00: NEE r=-0.0003, PnL=$-0.44

Simulating Trading Days:  54%|█████▍    | 32/59 [15:49<00:42,  1.58s/it]

[SIM] 2017-07-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.660, kelly=0.343) with $3437.08 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.676, kelly=0.361) with $3613.79 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.866, kelly=0.729) with $7303.12 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.661, kelly=0.334) with $3348.76 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.613, kelly=0.217) with $2171.41 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.852, kelly=0.707) with $7076.53 allocation
[PORT] Sector Services: selecting WMT (p_up=0.762, kelly=0.517) with $5177.06 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.938, kelly=0.877) with $8778.50 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.696, kelly=0.370) with $3701.55 allocation
[SIM] 2017-07-25 00:00:00: 9 trades proposed.
[TRADE] 2017-07-25 00:00:00: allocated $8778.50 to VZ exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $7303.12 to UL exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $7076.53 to UTX exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $5177.06 to WMT exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $1709.61 to NEE exiting on 2017-07-26 00:00:00
[EXIT] 2017-07-26 00:00:00: VZ r=0.0095, PnL=$83.83
[EXIT] 2017-07-26 00:00:00: UL r=0.0076, PnL=$55.43
[EXIT] 2017-07-26 00:00:00: UTX r=-0.0073, PnL=$-51.71
[EXIT] 2017-07-26 00:00:00: WMT r=0.0048, PnL=$25.05
[EXIT] 2017-07-26 00:00:00: NEE r=0.0166, PnL=$28.43

Simulating Trading Days:  56%|█████▌    | 33/59 [15:51<00:40,  1.55s/it]

[SIM] 2017-07-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.659, kelly=0.341) with $3423.75 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.689, kelly=0.388) with $3892.78 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.864, kelly=0.727) with $7291.28 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.672, kelly=0.356) with $3565.60 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.613, kelly=0.218) with $2187.38 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.868, kelly=0.737) with $7395.38 allocation
[PORT] Sector Services: selecting WMT (p_up=0.751, kelly=0.493) with $4945.91 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.938, kelly=0.876) with $8789.33 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.693, kelly=0.362) with $3635.01 allocation
[SIM] 2017-07-26 00:00:00: 9 trades proposed.
[TRADE] 2017-07-26 00:00:00: allocated $8789.33 to VZ exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $7395.38 to UTX exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $7291.28 to UL exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $4945.91 to WMT exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $1665.24 to NEE exiting on 2017-07-27 00:00:00
[EXIT] 2017-07-27 00:00:00: VZ r=0.0768, PnL=$675.04
[EXIT] 2017-07-27 00:00:00: UTX r=-0.0071, PnL=$-52.59
[EXIT] 2017-07-27 00:00:00: UL r=0.0000, PnL=$0.00
[EXIT] 2017-07-27 00:00:00: WMT r=0.0112, PnL=$55.16
[EXIT] 2017-07-27 00:00:00: NEE r=-0.0058, PnL=$-9.61

Simulating Trading Days:  58%|█████▊    | 34/59 [15:52<00:38,  1.53s/it]

[SIM] 2017-07-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.661, kelly=0.345) with $3479.16 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.692, kelly=0.394) with $3974.64 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.865, kelly=0.728) with $7347.71 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.675, kelly=0.363) with $3666.56 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.612, kelly=0.216) with $2177.83 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.872, kelly=0.746) with $7526.52 allocation
[PORT] Sector Services: selecting WMT (p_up=0.737, kelly=0.464) with $4688.51 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.937, kelly=0.875) with $8836.83 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.696, kelly=0.370) with $3733.29 allocation
[SIM] 2017-07-27 00:00:00: 9 trades proposed.
[TRADE] 2017-07-27 00:00:00: allocated $8836.83 to VZ exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $7526.52 to UTX exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $7347.71 to UL exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $4688.51 to WMT exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $1887.97 to NEE exiting on 2017-07-28 00:00:00
[EXIT] 2017-07-28 00:00:00: VZ r=0.0027, PnL=$24.03
[EXIT] 2017-07-28 00:00:00: UTX r=0.0015, PnL=$11.41
[EXIT] 2017-07-28 00:00:00: UL r=-0.0049, PnL=$-36.04
[EXIT] 2017-07-28 00:00:00: WMT r=0.0004, PnL=$1.76
[EXIT] 2017-07-28 00:00:00: NEE r=0.0032, PnL=$6.13

Simulating Trading Days:  59%|█████▉    | 35/59 [15:54<00:36,  1.52s/it]

[SIM] 2017-07-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.664, kelly=0.351) with $3545.24 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.686, kelly=0.382) with $3855.01 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.866, kelly=0.730) with $7365.71 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.674, kelly=0.359) with $3629.58 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.627, kelly=0.282) with $2846.15 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.872, kelly=0.746) with $7531.15 allocation
[PORT] Sector Services: selecting WMT (p_up=0.732, kelly=0.455) with $4596.59 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.937, kelly=0.874) with $8825.06 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.698, kelly=0.373) with $3769.20 allocation
[SIM] 2017-07-28 00:00:00: 9 trades proposed.
[TRADE] 2017-07-28 00:00:00: allocated $8825.06 to VZ exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $7531.15 to UTX exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $7365.71 to UL exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $4596.59 to WMT exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $1971.21 to NEE exiting on 2017-07-31 00:00:00
[EXIT] 2017-07-31 00:00:00: VZ r=0.0096, PnL=$84.68
[EXIT] 2017-07-31 00:00:00: UTX r=-0.0025, PnL=$-19.01
[EXIT] 2017-07-31 00:00:00: UL r=0.0033, PnL=$24.64
[EXIT] 2017-07-31 00:00:00: WMT r=0.0023, PnL=$10.37
[EXIT] 2017-07-31 00:00:00: NEE r=0.0067, PnL=$13.18

Simulating Trading Days:  61%|██████    | 36/59 [15:55<00:35,  1.56s/it]

[SIM] 2017-07-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.671, kelly=0.363) with $3673.85 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.678, kelly=0.366) with $3702.63 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.872, kelly=0.742) with $7495.95 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.686, kelly=0.384) with $3879.28 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.635, kelly=0.296) with $2996.05 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.865, kelly=0.732) with $7398.59 allocation
[PORT] Sector Services: selecting WMT (p_up=0.726, kelly=0.444) with $4485.29 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.932, kelly=0.864) with $8735.76 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.692, kelly=0.362) with $3657.81 allocation
[SIM] 2017-07-31 00:00:00: 9 trades proposed.
[TRADE] 2017-07-31 00:00:00: allocated $8735.76 to VZ exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $7495.95 to UL exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $7398.59 to UTX exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $4485.29 to WMT exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $2208.30 to NEE exiting on 2017-08-01 00:00:00
[EXIT] 2017-08-01 00:00:00: VZ r=0.0101, PnL=$88.44
[EXIT] 2017-08-01 00:00:00: UL r=-0.0030, PnL=$-22.36
[EXIT] 2017-08-01 00:00:00: UTX r=0.0026, PnL=$19.34
[EXIT] 2017-08-01 00:00:00: WMT r=0.0064, PnL=$28.60
[EXIT] 2017-08-01 00:00:00: NEE r=0.0033, PnL=$7.26

Simulating Trading Days:  63%|██████▎   | 37/59 [15:57<00:34,  1.58s/it]

[SIM] 2017-08-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.668, kelly=0.357) with $3615.86 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.667, kelly=0.345) with $3486.97 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.877, kelly=0.752) with $7610.81 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.691, kelly=0.394) with $3988.17 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.668, kelly=0.354) with $3582.85 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.858, kelly=0.719) with $7280.27 allocation
[PORT] Sector Services: selecting WMT (p_up=0.722, kelly=0.435) with $4406.70 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.926, kelly=0.854) with $8638.13 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.688, kelly=0.354) with $3581.62 allocation
[SIM] 2017-08-01 00:00:00: 9 trades proposed.
[TRADE] 2017-08-01 00:00:00: allocated $8638.13 to VZ exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $7610.81 to UL exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $7280.27 to UTX exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $4406.70 to WMT exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $2424.35 to WFC exiting on 2017-08-02 00:00:00
[EXIT] 2017-08-02 00:00:00: VZ r=-0.0139, PnL=$-120.15
[EXIT] 2017-08-02 00:00:00: UL r=-0.0037, PnL=$-28.13
[EXIT] 2017-08-02 00:00:00: UTX r=0.0124, PnL=$90.02
[EXIT] 2017-08-02 00:00:00: WMT r=0.0004, PnL=$1.64
[EXIT] 2017-08-02 00:00:00: WFC r=-0.0085, PnL=$-20.62

Simulating Trading Days:  64%|██████▍   | 38/59 [15:58<00:32,  1.57s/it]

[SIM] 2017-08-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.661, kelly=0.344) with $3475.60 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.592, kelly=0.195) with $1968.78 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.884, kelly=0.767) with $7758.46 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.694, kelly=0.400) with $4043.39 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.668, kelly=0.355) with $3588.60 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.853, kelly=0.709) with $7170.17 allocation
[PORT] Sector Services: selecting WMT (p_up=0.717, kelly=0.425) with $4294.11 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.922, kelly=0.844) with $8535.51 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.678, kelly=0.332) with $3353.62 allocation
[SIM] 2017-08-02 00:00:00: 9 trades proposed.
[TRADE] 2017-08-02 00:00:00: allocated $8535.51 to VZ exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $7758.46 to UL exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $7170.17 to UTX exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $4294.11 to WMT exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $2578.85 to WFC exiting on 2017-08-03 00:00:00
[EXIT] 2017-08-03 00:00:00: VZ r=0.0083, PnL=$70.82
[EXIT] 2017-08-03 00:00:00: UL r=0.0019, PnL=$15.08
[EXIT] 2017-08-03 00:00:00: UTX r=0.0062, PnL=$44.68
[EXIT] 2017-08-03 00:00:00: WMT r=0.0042, PnL=$18.13
[EXIT] 2017-08-03 00:00:00: WFC r=-0.0041, PnL=$-10.58

Simulating Trading Days:  66%|██████▌   | 39/59 [16:00<00:31,  1.58s/it]

[SIM] 2017-08-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.652, kelly=0.327) with $3314.50 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.645, kelly=0.292) with $2956.99 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.894, kelly=0.786) with $7964.22 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.697, kelly=0.406) with $4109.70 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.668, kelly=0.355) with $3590.68 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.844, kelly=0.690) with $6985.17 allocation
[PORT] Sector Services: selecting WMT (p_up=0.718, kelly=0.427) with $4328.21 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.918, kelly=0.836) with $8463.56 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.670, kelly=0.315) with $3191.93 allocation
[SIM] 2017-08-03 00:00:00: 9 trades proposed.
[TRADE] 2017-08-03 00:00:00: allocated $8463.56 to VZ exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $7964.22 to UL exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $6985.17 to UTX exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $4328.21 to WMT exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $2637.38 to WFC exiting on 2017-08-04 00:00:00
[EXIT] 2017-08-04 00:00:00: VZ r=0.0062, PnL=$52.23
[EXIT] 2017-08-04 00:00:00: UL r=0.0028, PnL=$22.47
[EXIT] 2017-08-04 00:00:00: UTX r=0.0032, PnL=$22.50
[EXIT] 2017-08-04 00:00:00: WMT r=-0.0048, PnL=$-20.87
[EXIT] 2017-08-04 00:00:00: WFC r=-0.0105, PnL=$-27.66

Simulating Trading Days:  68%|██████▊   | 40/59 [16:02<00:29,  1.57s/it]

[SIM] 2017-08-04 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.647, kelly=0.317) with $3209.29 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.736, kelly=0.473) with $4795.07 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.905, kelly=0.808) with $8188.76 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.701, kelly=0.414) with $4195.03 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.665, kelly=0.349) with $3538.09 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.831, kelly=0.664) with $6729.94 allocation
[PORT] Sector Services: selecting WMT (p_up=0.717, kelly=0.425) with $4301.31 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.913, kelly=0.827) with $8373.92 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.651, kelly=0.277) with $2804.22 allocation
[SIM] 2017-08-04 00:00:00: 9 trades proposed.
[TRADE] 2017-08-04 00:00:00: allocated $8373.92 to VZ exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $8188.76 to UL exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $6729.94 to UTX exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $4795.07 to GMRE exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $2305.45 to WMT exiting on 2017-08-07 00:00:00
[EXIT] 2017-08-07 00:00:00: VZ r=-0.0010, PnL=$-8.56
[EXIT] 2017-08-07 00:00:00: UL r=0.0070, PnL=$57.59
[EXIT] 2017-08-07 00:00:00: UTX r=-0.0244, PnL=$-164.52
[EXIT] 2017-08-07 00:00:00: GMRE r=0.0044, PnL=$21.29
[EXIT] 2017-08-07 00:00:00: WMT r=0.0099, PnL=$22.92

Simulating Trading Days:  69%|██████▉   | 41/59 [16:03<00:28,  1.57s/it]

[SIM] 2017-08-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.639, kelly=0.302) with $3061.51 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.808, kelly=0.617) with $6246.19 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.914, kelly=0.826) with $8363.51 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.721, kelly=0.452) with $4580.21 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.662, kelly=0.343) with $3470.88 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.820, kelly=0.643) with $6514.73 allocation
[PORT] Sector Services: selecting WMT (p_up=0.718, kelly=0.427) with $4318.39 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.908, kelly=0.816) with $8262.37 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.642, kelly=0.258) with $2612.66 allocation
[SIM] 2017-08-07 00:00:00: 9 trades proposed.
[TRADE] 2017-08-07 00:00:00: allocated $8363.51 to UL exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $8262.37 to VZ exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $6514.73 to UTX exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $6246.19 to GMRE exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $984.94 to WFC exiting on 2017-08-08 00:00:00
[EXIT] 2017-08-08 00:00:00: UL r=-0.0010, PnL=$-8.76
[EXIT] 2017-08-08 00:00:00: VZ r=-0.0053, PnL=$-43.97
[EXIT] 2017-08-08 00:00:00: UTX r=-0.0028, PnL=$-18.14
[EXIT] 2017-08-08 00:00:00: GMRE r=-0.0122, PnL=$-75.92
[EXIT] 2017-08-08 00:00:00: WFC r=0.0032, PnL=$3.19

Simulating Trading Days:  71%|███████   | 42/59 [16:05<00:27,  1.60s/it]

[SIM] 2017-08-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.634, kelly=0.293) with $2963.72 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.847, kelly=0.694) with $7015.67 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.919, kelly=0.837) with $8458.24 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.737, kelly=0.485) with $4899.57 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.658, kelly=0.335) with $3391.44 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.821, kelly=0.645) with $6519.64 allocation
[PORT] Sector Services: selecting WMT (p_up=0.719, kelly=0.429) with $4335.23 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.902, kelly=0.805) with $8135.02 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.632, kelly=0.236) with $2388.30 allocation
[SIM] 2017-08-08 00:00:00: 9 trades proposed.
[TRADE] 2017-08-08 00:00:00: allocated $8458.24 to UL exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $8135.02 to VZ exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $7015.67 to GMRE exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $6519.64 to UTX exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $200.10 to WFC exiting on 2017-08-09 00:00:00
[EXIT] 2017-08-09 00:00:00: UL r=0.0075, PnL=$63.56
[EXIT] 2017-08-09 00:00:00: VZ r=-0.0078, PnL=$-63.61
[EXIT] 2017-08-09 00:00:00: GMRE r=-0.0011, PnL=$-7.85
[EXIT] 2017-08-09 00:00:00: UTX r=-0.0084, PnL=$-54.61
[EXIT] 2017-08-09 00:00:00: WFC r=0.0015, PnL=$0.30

Simulating Trading Days:  73%|███████▎  | 43/59 [16:06<00:25,  1.60s/it]

[SIM] 2017-08-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.638, kelly=0.300) with $3035.12 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.858, kelly=0.716) with $7238.22 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.922, kelly=0.843) with $8518.62 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.755, kelly=0.520) with $5250.14 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.606, kelly=0.212) with $2139.25 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.829, kelly=0.661) with $6680.76 allocation
[PORT] Sector Services: selecting WMT (p_up=0.720, kelly=0.430) with $4342.19 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.898, kelly=0.796) with $8041.38 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.630, kelly=0.233) with $2350.94 allocation
[SIM] 2017-08-09 00:00:00: 9 trades proposed.
[TRADE] 2017-08-09 00:00:00: allocated $8518.62 to UL exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $8041.38 to VZ exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $7238.22 to GMRE exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $6511.78 to UTX exiting on 2017-08-10 00:00:00
[EXIT] 2017-08-10 00:00:00: UL r=-0.0167, PnL=$-141.85
[EXIT] 2017-08-10 00:00:00: VZ r=-0.0041, PnL=$-33.35
[EXIT] 2017-08-10 00:00:00: GMRE r=-0.0168, PnL=$-121.58
[EXIT] 2017-08-10 00:00:00: UTX r=-0.0038, PnL=$-24.45

Simulating Trading Days:  75%|███████▍  | 44/59 [16:08<00:24,  1.61s/it]

[SIM] 2017-08-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.643, kelly=0.309) with $3113.05 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.857, kelly=0.715) with $7205.33 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.922, kelly=0.844) with $8496.96 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.763, kelly=0.534) with $5380.65 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.615, kelly=0.231) with $2323.90 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.841, kelly=0.685) with $6898.37 allocation
[PORT] Sector Services: selecting WMT (p_up=0.759, kelly=0.509) with $5127.69 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.894, kelly=0.789) with $7945.87 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.654, kelly=0.282) with $2835.63 allocation
[SIM] 2017-08-10 00:00:00: 9 trades proposed.
[TRADE] 2017-08-10 00:00:00: allocated $8496.96 to UL exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $7945.87 to VZ exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $7205.33 to GMRE exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $6565.47 to UTX exiting on 2017-08-11 00:00:00
[EXIT] 2017-08-11 00:00:00: UL r=0.0009, PnL=$7.49
[EXIT] 2017-08-11 00:00:00: VZ r=0.0008, PnL=$6.62
[EXIT] 2017-08-11 00:00:00: GMRE r=0.0239, PnL=$172.34
[EXIT] 2017-08-11 00:00:00: UTX r=0.0011, PnL=$7.31

Simulating Trading Days:  76%|███████▋  | 45/59 [16:09<00:21,  1.57s/it]

[SIM] 2017-08-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.661, kelly=0.345) with $3481.12 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.862, kelly=0.724) with $7303.69 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.926, kelly=0.850) with $8578.24 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.772, kelly=0.553) with $5579.18 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.633, kelly=0.265) with $2675.36 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.864, kelly=0.731) with $7377.66 allocation
[PORT] Sector Services: selecting WMT (p_up=0.796, kelly=0.586) with $5908.29 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.893, kelly=0.787) with $7944.41 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.662, kelly=0.299) with $3016.32 allocation
[SIM] 2017-08-11 00:00:00: 9 trades proposed.
[TRADE] 2017-08-11 00:00:00: allocated $8578.24 to UL exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $7944.41 to VZ exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $7377.66 to UTX exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $6371.46 to GMRE exiting on 2017-08-14 00:00:00
[EXIT] 2017-08-14 00:00:00: UL r=0.0092, PnL=$78.62
[EXIT] 2017-08-14 00:00:00: VZ r=0.0150, PnL=$119.02
[EXIT] 2017-08-14 00:00:00: UTX r=0.0022, PnL=$16.41
[EXIT] 2017-08-14 00:00:00: GMRE r=0.0289, PnL=$184.27

Simulating Trading Days:  78%|███████▊  | 46/59 [16:11<00:20,  1.55s/it]

[SIM] 2017-08-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.675, kelly=0.372) with $3765.18 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.855, kelly=0.710) with $7190.81 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.929, kelly=0.857) with $8676.84 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.779, kelly=0.566) with $5735.70 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.641, kelly=0.282) with $2856.86 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.877, kelly=0.757) with $7664.35 allocation
[PORT] Sector Services: selecting WMT (p_up=0.802, kelly=0.596) with $6041.69 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.892, kelly=0.785) with $7947.47 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.675, kelly=0.326) with $3305.77 allocation
[SIM] 2017-08-14 00:00:00: 9 trades proposed.
[TRADE] 2017-08-14 00:00:00: allocated $8676.84 to UL exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $7947.47 to VZ exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $7664.35 to UTX exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $6102.60 to GMRE exiting on 2017-08-15 00:00:00
[EXIT] 2017-08-15 00:00:00: UL r=0.0056, PnL=$48.49
[EXIT] 2017-08-15 00:00:00: VZ r=-0.0062, PnL=$-48.88
[EXIT] 2017-08-15 00:00:00: UTX r=-0.0102, PnL=$-77.85
[EXIT] 2017-08-15 00:00:00: GMRE r=-0.0076, PnL=$-46.18

Simulating Trading Days:  80%|███████▉  | 47/59 [16:12<00:18,  1.54s/it]

[SIM] 2017-08-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.684, kelly=0.388) with $3927.23 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.805, kelly=0.612) with $6192.31 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.932, kelly=0.863) with $8730.17 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.772, kelly=0.553) with $5599.77 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.640, kelly=0.280) with $2834.84 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.876, kelly=0.754) with $7627.73 allocation
[PORT] Sector Services: selecting WMT (p_up=0.783, kelly=0.560) with $5662.54 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.889, kelly=0.779) with $7878.42 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.676, kelly=0.327) with $3313.44 allocation
[SIM] 2017-08-15 00:00:00: 9 trades proposed.
[TRADE] 2017-08-15 00:00:00: allocated $8730.17 to UL exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $7878.42 to VZ exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $7627.73 to UTX exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $6117.61 to GMRE exiting on 2017-08-16 00:00:00
[EXIT] 2017-08-16 00:00:00: UL r=-0.0007, PnL=$-6.06
[EXIT] 2017-08-16 00:00:00: VZ r=-0.0014, PnL=$-11.38
[EXIT] 2017-08-16 00:00:00: UTX r=0.0176, PnL=$134.19
[EXIT] 2017-08-16 00:00:00: GMRE r=0.0109, PnL=$66.64

Simulating Trading Days:  81%|████████▏ | 48/59 [16:14<00:16,  1.52s/it]

[SIM] 2017-08-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.725, kelly=0.459) with $4655.95 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.706, kelly=0.414) with $4191.75 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.933, kelly=0.865) with $8770.69 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.760, kelly=0.529) with $5357.65 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.638, kelly=0.275) with $2792.37 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.878, kelly=0.758) with $7685.10 allocation
[PORT] Sector Services: selecting WMT (p_up=0.771, kelly=0.535) with $5425.15 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.886, kelly=0.774) with $7842.88 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.678, kelly=0.333) with $3376.97 allocation
[SIM] 2017-08-16 00:00:00: 9 trades proposed.
[TRADE] 2017-08-16 00:00:00: allocated $8770.69 to UL exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $7842.88 to VZ exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $7685.10 to UTX exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $5425.15 to WMT exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $685.13 to WFC exiting on 2017-08-17 00:00:00
[EXIT] 2017-08-17 00:00:00: UL r=-0.0085, PnL=$-74.69
[EXIT] 2017-08-17 00:00:00: VZ r=-0.0107, PnL=$-84.25
[EXIT] 2017-08-17 00:00:00: UTX r=-0.0161, PnL=$-123.74
[EXIT] 2017-08-17 00:00:00: WMT r=-0.0158, PnL=$-85.75
[EXIT] 2017-08-17 00:00:00: WFC r=-0.0169, PnL=$-11.57

Simulating Trading Days:  83%|████████▎ | 49/59 [16:15<00:15,  1.51s/it]

[SIM] 2017-08-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.760, kelly=0.527) with $5323.11 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.760, kelly=0.528) with $5329.52 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.933, kelly=0.865) with $8732.40 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.745, kelly=0.499) with $5036.19 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.630, kelly=0.260) with $2628.39 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.874, kelly=0.750) with $7575.89 allocation
[PORT] Sector Services: selecting WMT (p_up=0.754, kelly=0.499) with $5037.89 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.884, kelly=0.770) with $7773.84 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.666, kelly=0.306) with $3094.54 allocation
[SIM] 2017-08-17 00:00:00: 9 trades proposed.
[TRADE] 2017-08-17 00:00:00: allocated $8732.40 to UL exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $7773.84 to VZ exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $7575.89 to UTX exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $5329.52 to CODI exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $883.29 to XOM exiting on 2017-08-18 00:00:00
[EXIT] 2017-08-18 00:00:00: UL r=0.0025, PnL=$21.43
[EXIT] 2017-08-18 00:00:00: VZ r=-0.0042, PnL=$-32.47
[EXIT] 2017-08-18 00:00:00: UTX r=-0.0053, PnL=$-40.46
[EXIT] 2017-08-18 00:00:00: CODI r=-0.0029, PnL=$-15.54
[EXIT] 2017-08-18 00:00:00: XOM r=0.0050, PnL=$4.40

Simulating Trading Days:  85%|████████▍ | 50/59 [16:17<00:13,  1.50s/it]

[SIM] 2017-08-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.798, kelly=0.602) with $6075.50 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.773, kelly=0.553) with $5578.93 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.934, kelly=0.867) with $8746.30 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.736, kelly=0.482) with $4866.33 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.634, kelly=0.268) with $2700.58 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.885, kelly=0.772) with $7787.35 allocation
[PORT] Sector Services: selecting WMT (p_up=0.753, kelly=0.497) with $5014.90 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.885, kelly=0.771) with $7782.90 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.674, kelly=0.324) with $3270.14 allocation
[SIM] 2017-08-18 00:00:00: 9 trades proposed.
[TRADE] 2017-08-18 00:00:00: allocated $8746.30 to UL exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $7782.90 to VZ exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $7787.35 to UTX exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $5959.60 to XOM exiting on 2017-08-21 00:00:00
[EXIT] 2017-08-21 00:00:00: UL r=0.0070, PnL=$61.17
[EXIT] 2017-08-21 00:00:00: VZ r=0.0094, PnL=$73.44
[EXIT] 2017-08-21 00:00:00: UTX r=-0.0017, PnL=$-13.49
[EXIT] 2017-08-21 00:00:00: XOM r=-0.0034, PnL=$-20.22

Simulating Trading Days:  86%|████████▋ | 51/59 [16:18<00:12,  1.51s/it]

[SIM] 2017-08-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.814, kelly=0.633) with $6397.72 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.789, kelly=0.585) with $5909.57 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.935, kelly=0.869) with $8778.48 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.734, kelly=0.477) with $4822.79 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.640, kelly=0.280) with $2825.56 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.891, kelly=0.783) with $7913.21 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.726, kelly=0.496) with $5009.73 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.885, kelly=0.771) with $7787.30 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.693, kelly=0.363) with $3664.48 allocation
[SIM] 2017-08-21 00:00:00: 9 trades proposed.
[TRADE] 2017-08-21 00:00:00: allocated $8778.48 to UL exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $7913.21 to UTX exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $7787.30 to VZ exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $5827.44 to XOM exiting on 2017-08-22 00:00:00
[EXIT] 2017-08-22 00:00:00: UL r=0.0057, PnL=$50.30
[EXIT] 2017-08-22 00:00:00: UTX r=0.0036, PnL=$28.14
[EXIT] 2017-08-22 00:00:00: VZ r=0.0044, PnL=$33.97
[EXIT] 2017-08-22 00:00:00: XOM r=0.0047, PnL=$27.47

Simulating Trading Days:  88%|████████▊ | 52/59 [16:20<00:10,  1.50s/it]

[SIM] 2017-08-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.808, kelly=0.623) with $6303.57 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.802, kelly=0.611) with $6178.96 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.936, kelly=0.871) with $8810.58 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.732, kelly=0.475) with $4805.35 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.644, kelly=0.289) with $2920.11 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.892, kelly=0.786) with $7953.24 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.729, kelly=0.501) with $5068.88 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.885, kelly=0.770) with $7789.17 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.704, kelly=0.387) with $3911.34 allocation
[SIM] 2017-08-22 00:00:00: 9 trades proposed.
[TRADE] 2017-08-22 00:00:00: allocated $8810.58 to UL exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $7953.24 to UTX exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $7789.17 to VZ exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $5795.42 to XOM exiting on 2017-08-23 00:00:00
[EXIT] 2017-08-23 00:00:00: UL r=-0.0014, PnL=$-12.17
[EXIT] 2017-08-23 00:00:00: UTX r=0.0116, PnL=$92.12
[EXIT] 2017-08-23 00:00:00: VZ r=-0.0014, PnL=$-11.28
[EXIT] 2017-08-23 00:00:00: XOM r=-0.0017, PnL=$-9.82

Simulating Trading Days:  90%|████████▉ | 53/59 [16:21<00:08,  1.49s/it]

[SIM] 2017-08-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.783, kelly=0.574) with $5807.92 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.806, kelly=0.617) with $6247.96 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.936, kelly=0.871) with $8812.91 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.727, kelly=0.464) with $4697.22 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.643, kelly=0.286) with $2898.85 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.882, kelly=0.767) with $7759.63 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.723, kelly=0.491) with $4967.12 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.883, kelly=0.766) with $7754.45 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.706, kelly=0.390) with $3948.09 allocation
[SIM] 2017-08-23 00:00:00: 9 trades proposed.
[TRADE] 2017-08-23 00:00:00: allocated $8812.91 to UL exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $7754.45 to VZ exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $7759.63 to UTX exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $6039.06 to CODI exiting on 2017-08-24 00:00:00
[EXIT] 2017-08-24 00:00:00: UL r=-0.0031, PnL=$-27.43
[EXIT] 2017-08-24 00:00:00: VZ r=0.0006, PnL=$4.82
[EXIT] 2017-08-24 00:00:00: UTX r=-0.0148, PnL=$-114.71
[EXIT] 2017-08-24 00:00:00: CODI r=-0.0145, PnL=$-87.52

Simulating Trading Days:  92%|█████████▏| 54/59 [16:23<00:07,  1.49s/it]

[SIM] 2017-08-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.753, kelly=0.513) with $5182.03 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.799, kelly=0.604) with $6101.64 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.935, kelly=0.869) with $8772.41 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.718, kelly=0.446) with $4503.24 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.643, kelly=0.285) with $2881.37 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.882, kelly=0.765) with $7729.08 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.725, kelly=0.494) with $4990.06 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.880, kelly=0.762) with $7692.40 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.717, kelly=0.413) with $4169.93 allocation
[SIM] 2017-08-24 00:00:00: 9 trades proposed.
[TRADE] 2017-08-24 00:00:00: allocated $8772.41 to UL exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $7729.08 to UTX exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $7692.40 to VZ exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $6101.64 to CODI exiting on 2017-08-25 00:00:00
[EXIT] 2017-08-25 00:00:00: UL r=0.0064, PnL=$56.29
[EXIT] 2017-08-25 00:00:00: UTX r=-0.0020, PnL=$-15.42
[EXIT] 2017-08-25 00:00:00: VZ r=0.0077, PnL=$58.91
[EXIT] 2017-08-25 00:00:00: CODI r=0.0206, PnL=$125.62

Simulating Trading Days:  93%|█████████▎| 55/59 [16:24<00:05,  1.50s/it]

[SIM] 2017-08-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.728, kelly=0.465) with $4711.19 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.746, kelly=0.492) with $4985.09 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.934, kelly=0.866) with $8770.64 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.706, kelly=0.422) with $4274.19 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.636, kelly=0.271) with $2745.51 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.878, kelly=0.759) with $7679.20 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.732, kelly=0.506) with $5122.68 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.879, kelly=0.758) with $7676.39 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.726, kelly=0.433) with $4380.02 allocation
[SIM] 2017-08-25 00:00:00: 9 trades proposed.
[TRADE] 2017-08-25 00:00:00: allocated $8770.64 to UL exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $7676.39 to VZ exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $7679.20 to UTX exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $4985.09 to GMRE exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $1254.89 to CHTR exiting on 2017-08-28 00:00:00
[EXIT] 2017-08-28 00:00:00: UL r=0.0016, PnL=$13.60
[EXIT] 2017-08-28 00:00:00: VZ r=-0.0014, PnL=$-11.04
[EXIT] 2017-08-28 00:00:00: UTX r=0.0023, PnL=$17.35
[EXIT] 2017-08-28 00:00:00: GMRE r=-0.0410, PnL=$-204.17
[EXIT] 2017-08-28 00:00:00: CHTR r=0.0011, PnL=$1.42

Simulating Trading Days:  95%|█████████▍| 56/59 [16:26<00:04,  1.49s/it]

[SIM] 2017-08-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.707, kelly=0.434) with $4386.85 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.787, kelly=0.574) with $5802.51 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.932, kelly=0.863) with $8721.54 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.694, kelly=0.399) with $4029.66 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.630, kelly=0.260) with $2626.86 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.874, kelly=0.751) with $7584.03 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.737, kelly=0.515) with $5202.00 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.876, kelly=0.754) with $7616.82 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.740, kelly=0.462) with $4664.22 allocation
[SIM] 2017-08-28 00:00:00: 9 trades proposed.
[TRADE] 2017-08-28 00:00:00: allocated $8721.54 to UL exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $7616.82 to VZ exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $7584.03 to UTX exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $5802.51 to GMRE exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $586.47 to NEE exiting on 2017-08-29 00:00:00
[EXIT] 2017-08-29 00:00:00: UL r=0.0000, PnL=$0.00
[EXIT] 2017-08-29 00:00:00: VZ r=-0.0021, PnL=$-15.67
[EXIT] 2017-08-29 00:00:00: UTX r=0.0292, PnL=$221.61
[EXIT] 2017-08-29 00:00:00: GMRE r=0.0130, PnL=$75.71
[EXIT] 2017-08-29 00:00:00: NEE r=-0.0011, PnL=$-0.62

Simulating Trading Days:  97%|█████████▋| 57/59 [16:27<00:02,  1.49s/it]

[SIM] 2017-08-29 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.701, kelly=0.422) with $4280.23 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.795, kelly=0.591) with $5983.43 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.930, kelly=0.860) with $8710.43 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.690, kelly=0.391) with $3958.18 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.623, kelly=0.246) with $2496.82 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.869, kelly=0.741) with $7503.00 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.736, kelly=0.514) with $5204.09 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.873, kelly=0.747) with $7571.48 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.743, kelly=0.467) with $4731.92 allocation
[SIM] 2017-08-29 00:00:00: 9 trades proposed.
[TRADE] 2017-08-29 00:00:00: allocated $8710.43 to UL exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $7571.48 to VZ exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $7503.00 to UTX exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $5983.43 to GMRE exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $627.33 to NEE exiting on 2017-08-30 00:00:00
[EXIT] 2017-08-30 00:00:00: UL r=-0.0083, PnL=$-71.94
[EXIT] 2017-08-30 00:00:00: VZ r=-0.0080, PnL=$-60.87
[EXIT] 2017-08-30 00:00:00: UTX r=0.0076, PnL=$56.89
[EXIT] 2017-08-30 00:00:00: GMRE r=-0.0082, PnL=$-49.04
[EXIT] 2017-08-30 00:00:00: NEE r=-0.0007, PnL=$-0.42

Simulating Trading Days:  98%|█████████▊| 58/59 [16:29<00:01,  1.51s/it]

[SIM] 2017-08-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.695, kelly=0.410) with $4146.93 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.777, kelly=0.556) with $5622.01 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.927, kelly=0.853) with $8636.52 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.692, kelly=0.395) with $4001.41 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.687, kelly=0.391) with $3952.63 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.857, kelly=0.717) with $7254.96 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.736, kelly=0.514) with $5199.17 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.871, kelly=0.744) with $7526.56 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.743, kelly=0.467) with $4725.70 allocation
[SIM] 2017-08-30 00:00:00: 9 trades proposed.
[TRADE] 2017-08-30 00:00:00: allocated $8636.52 to UL exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $7526.56 to VZ exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $7254.96 to UTX exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $5622.01 to GMRE exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $1318.03 to NEE exiting on 2017-08-31 00:00:00
[EXIT] 2017-08-31 00:00:00: UL r=0.0099, PnL=$85.41
[EXIT] 2017-08-31 00:00:00: VZ r=-0.0031, PnL=$-23.46
[EXIT] 2017-08-31 00:00:00: UTX r=0.0010, PnL=$7.28
[EXIT] 2017-08-31 00:00:00: GMRE r=-0.0024, PnL=$-13.28
[EXIT] 2017-08-31 00:00:00: NEE r=-0.0007, PnL=$-0.96

Simulating Trading Days: 100%|██████████| 59/59 [16:30<00:00, 16.80s/it]

[SIM] 2017-08-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.686, kelly=0.392) with $3968.10 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.748, kelly=0.498) with $5037.19 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.926, kelly=0.851) with $8617.50 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.699, kelly=0.409) with $4146.05 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.689, kelly=0.396) with $4009.03 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.842, kelly=0.687) with $6958.14 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.726, kelly=0.495) with $5012.74 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.870, kelly=0.740) with $7495.15 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.742, kelly=0.464) with $4700.33 allocation
[SIM] 2017-08-31 00:00:00: 9 trades proposed.

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-06-09,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
1,2017-06-12,99953.729076,69967.610353,99953.729076,99953.729076,-46.270924,-0.000463,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
2,2017-06-13,99897.206284,69928.044398,99897.206284,99897.206284,-56.522793,-0.000565,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
3,2017-06-14,99921.950191,69945.365134,99921.950191,99921.950191,24.743907,0.000248,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
4,2017-06-15,100004.238818,70002.967173,100004.238818,100004.238818,82.288627,0.000824,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
5,2017-06-16,100108.447086,70075.912960,100108.447086,100108.447086,104.208268,0.001042,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
6,2017-06-19,100183.918284,70128.742799,100183.918284,100183.918284,75.471198,0.000754,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
7,2017-06-20,99936.822408,69955.775686,99936.822408,99936.822408,-247.095876,-0.002466,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
8,2017-06-21,99843.006151,69890.104305,99843.006151,99843.006151,-93.816257,-0.000939,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
9,2017-06-22,99856.301504,69899.411052,99856.301504,99856.301504,13.295353,0.000133,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
10,2017-06-23,99934.406333,69954.084433,99934.406333,99934.406333,78.104829,0.000782,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
11,2017-06-26,100102.656780,70071.859746,100102.656780,100102.656780,168.250447,0.001684,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
12,2017-06-27,99824.246899,69876.972829,99824.246899,99824.246899,-278.409881,-0.002781,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
13,2017-06-28,99888.368497,69921.857948,99888.368497,99888.368497,64.121599,0.000642,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
14,2017-06-29,99469.286572,69628.500600,99469.286572,99469.286572,-419.081925,-0.004196,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
15,2017-06-30,99636.782516,69745.747761,99636.782516,99636.782516,167.495944,0.001684,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
16,2017-07-03,99634.382076,69744.067453,99634.382076,99634.382076,-2.400440,-0.000024,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
17,2017-07-05,99565.576101,69695.903271,99565.576101,99565.576101,-68.805975,-0.000691,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
18,2017-07-06,99301.488562,69511.041994,99301.488562,99301.488562,-264.087539,-0.002652,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
19,2017-07-07,99411.821592,69588.275114,99411.821592,99411.821592,110.333030,0.001111,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
20,2017-07-10,99451.107539,69615.775277,99451.107539,99451.107539,39.285947,0.000395,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
21,2017-07-11,99443.457197,69610.420038,99443.457197,99443.457197,-7.650342,-0.000077,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
22,2017-07-12,99595.270034,69716.689024,99595.270034,99595.270034,151.812837,0.001527,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
23,2017-07-13,99690.620763,69783.434534,99690.620763,99690.620763,95.350729,0.000957,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
24,2017-07-14,99870.802042,69909.561429,99870.802042,99870.802042,180.181279,0.001807,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
25,2017-07-17,99832.209386,69882.546570,99832.209386,99832.209386,-38.592656,-0.000386,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
26,2017-07-18,99770.746635,69839.522645,99770.746635,99770.746635,-61.462751,-0.000616,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
27,2017-07-19,99832.326824,69882.628777,99832.326824,99832.326824,61.580189,0.000617,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
28,2017-07-20,100160.653765,70112.457635,100160.653765,100160.653765,328.326941,0.003289,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
29,2017-07-21,100284.463784,70199.124649,100284.463784,100284.463784,123.810019,0.001236,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
30,2017-07-24,100119.362549,70083.553784,100119.362549,100119.362549,-165.101236,-0.001646,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
31,2017-07-25,100149.418406,70104.592885,100149.418406,100149.418406,30.055858,0.000300,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
32,2017-07-26,100290.459086,70203.321360,100290.459086,100290.459086,141.040680,0.001408,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
33,2017-07-27,100958.458300,70670.920810,100958.458300,100958.458300,667.999214,0.006661,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
34,2017-07-28,100965.754186,70676.027930,100965.754186,100965.754186,7.295886,0.000072,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
35,2017-07-31,101079.609015,70755.726311,101079.609015,101079.609015,113.854829,0.001128,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
36,2017-08-01,101200.885061,70840.619543,101200.885061,101200.885061,121.276046,0.001200,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
37,2017-08-02,101123.655042,70786.558529,101123.655042,101123.655042,-77.230019,-0.000763,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
38,2017-08-03,101261.782962,70883.248074,101261.782962,101261.782962,138.127920,0.001366,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
39,2017-08-04,101310.446847,70917.312793,101310.446847,101310.446847,48.663885,0.000481,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
40,2017-08-07,101239.153823,70867.407676,101239.153823,101239.153823,-71.293024,-0.000704,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
41,2017-08-08,101095.553547,70766.887483,101095.553547,101095.553547,-143.600276,-0.001418,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
42,2017-08-09,101033.354704,70723.348293,101033.354704,101033.354704,-62.198843,-0.000615,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
43,2017-08-10,100712.117946,70498.482562,100712.117946,100712.117946,-321.236759,-0.003180,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
44,2017-08-11,100905.878432,70634.114903,100905.878432,100905.878432,193.760487,0.001924,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
45,2017-08-14,101304.190580,70912.933406,101304.190580,101304.190580,398.312148,0.003947,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
46,2017-08-15,101179.768921,70825.838245,101179.768921,101179.768921,-124.421659,-0.001228,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
47,2017-08-16,101363.158179,70954.210725,101363.158179,101363.158179,183.389258,0.001813,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
48,2017-08-17,100983.154898,70688.208428,100983.154898,100983.154898,-380.003281,-0.003749,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
49,2017-08-18,100920.525442,70644.367810,100920.525442,100920.525442,-62.629455,-0.000620,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
50,2017-08-21,101021.432983,70715.003088,101021.432983,101021.432983,100.907541,0.001000,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
51,2017-08-22,101161.315379,70812.920765,101161.315379,101161.315379,139.882395,0.001385,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
52,2017-08-23,101220.171741,70854.120219,101220.171741,101220.171741,58.856362,0.000582,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
53,2017-08-24,100995.335062,70699.816162,100995.335062,100995.335062,-224.836680,-0.002221,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
54,2017-08-25,101220.745521,70854.521864,101220.745521,101220.745521,225.410459,0.002232,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
55,2017-08-28,101037.913727,70726.539609,101037.913727,101037.913727,-182.831793,-0.001806,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
56,2017-08-29,101318.945750,70923.262025,101318.945750,101318.945750,281.032022,0.002781,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
57,2017-08-30,101193.564906,70835.495434,101193.564906,101193.564906,-125.380844,-0.001237,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
58,2017-08-31,101248.551333,101248.551333,101248.551333,101248.551333,54.986427,0.000543,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-06-09,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
1,2017-06-12,99953.729076,69967.610353,99953.729076,99953.729076,-46.270924,-0.000463,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
2,2017-06-13,99897.206284,69928.044398,99897.206284,99897.206284,-56.522793,-0.000565,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
3,2017-06-14,99921.950191,69945.365134,99921.950191,99921.950191,24.743907,0.000248,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
4,2017-06-15,100004.238818,70002.967173,100004.238818,100004.238818,82.288627,0.000824,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
5,2017-06-16,100108.447086,70075.912960,100108.447086,100108.447086,104.208268,0.001042,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
6,2017-06-19,100183.918284,70128.742799,100183.918284,100183.918284,75.471198,0.000754,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
7,2017-06-20,99936.822408,69955.775686,99936.822408,99936.822408,-247.095876,-0.002466,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
8,2017-06-21,99843.006151,69890.104305,99843.006151,99843.006151,-93.816257,-0.000939,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
9,2017-06-22,99856.301504,69899.411052,99856.301504,99856.301504,13.295353,0.000133,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
10,2017-06-23,99934.406333,69954.084433,99934.406333,99934.406333,78.104829,0.000782,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
11,2017-06-26,100102.656780,70071.859746,100102.656780,100102.656780,168.250447,0.001684,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
12,2017-06-27,99824.246899,69876.972829,99824.246899,99824.246899,-278.409881,-0.002781,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
13,2017-06-28,99888.368497,69921.857948,99888.368497,99888.368497,64.121599,0.000642,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
14,2017-06-29,99469.286572,69628.500600,99469.286572,99469.286572,-419.081925,-0.004196,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
15,2017-06-30,99636.782516,69745.747761,99636.782516,99636.782516,167.495944,0.001684,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
16,2017-07-03,99634.382076,69744.067453,99634.382076,99634.382076,-2.400440,-0.000024,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
17,2017-07-05,99565.576101,69695.903271,99565.576101,99565.576101,-68.805975,-0.000691,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
18,2017-07-06,99301.488562,69511.041994,99301.488562,99301.488562,-264.087539,-0.002652,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
19,2017-07-07,99411.821592,69588.275114,99411.821592,99411.821592,110.333030,0.001111,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
20,2017-07-10,99451.107539,69615.775277,99451.107539,99451.107539,39.285947,0.000395,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
21,2017-07-11,99443.457197,69610.420038,99443.457197,99443.457197,-7.650342,-0.000077,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
22,2017-07-12,99595.270034,69716.689024,99595.270034,99595.270034,151.812837,0.001527,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
23,2017-07-13,99690.620763,69783.434534,99690.620763,99690.620763,95.350729,0.000957,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
24,2017-07-14,99870.802042,69909.561429,99870.802042,99870.802042,180.181279,0.001807,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
25,2017-07-17,99832.209386,69882.546570,99832.209386,99832.209386,-38.592656,-0.000386,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
26,2017-07-18,99770.746635,69839.522645,99770.746635,99770.746635,-61.462751,-0.000616,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
27,2017-07-19,99832.326824,69882.628777,99832.326824,99832.326824,61.580189,0.000617,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
28,2017-07-20,100160.653765,70112.457635,100160.653765,100160.653765,328.326941,0.003289,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
29,2017-07-21,100284.463784,70199.124649,100284.463784,100284.463784,123.810019,0.001236,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
30,2017-07-24,100119.362549,70083.553784,100119.362549,100119.362549,-165.101236,-0.001646,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
31,2017-07-25,100149.418406,70104.592885,100149.418406,100149.418406,30.055858,0.000300,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
32,2017-07-26,100290.459086,70203.321360,100290.459086,100290.459086,141.040680,0.001408,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
33,2017-07-27,100958.458300,70670.920810,100958.458300,100958.458300,667.999214,0.006661,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
34,2017-07-28,100965.754186,70676.027930,100965.754186,100965.754186,7.295886,0.000072,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
35,2017-07-31,101079.609015,70755.726311,101079.609015,101079.609015,113.854829,0.001128,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
36,2017-08-01,101200.885061,70840.619543,101200.885061,101200.885061,121.276046,0.001200,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
37,2017-08-02,101123.655042,70786.558529,101123.655042,101123.655042,-77.230019,-0.000763,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
38,2017-08-03,101261.782962,70883.248074,101261.782962,101261.782962,138.127920,0.001366,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
39,2017-08-04,101310.446847,70917.312793,101310.446847,101310.446847,48.663885,0.000481,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
40,2017-08-07,101239.153823,70867.407676,101239.153823,101239.153823,-71.293024,-0.000704,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
41,2017-08-08,101095.553547,70766.887483,101095.553547,101095.553547,-143.600276,-0.001418,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
42,2017-08-09,101033.354704,70723.348293,101033.354704,101033.354704,-62.198843,-0.000615,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
43,2017-08-10,100712.117946,70498.482562,100712.117946,100712.117946,-321.236759,-0.003180,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
44,2017-08-11,100905.878432,70634.114903,100905.878432,100905.878432,193.760487,0.001924,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
45,2017-08-14,101304.190580,70912.933406,101304.190580,101304.190580,398.312148,0.003947,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
46,2017-08-15,101179.768921,70825.838245,101179.768921,101179.768921,-124.421659,-0.001228,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
47,2017-08-16,101363.158179,70954.210725,101363.158179,101363.158179,183.389258,0.001813,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
48,2017-08-17,100983.154898,70688.208428,100983.154898,100983.154898,-380.003281,-0.003749,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
49,2017-08-18,100920.525442,70644.367810,100920.525442,100920.525442,-62.629455,-0.000620,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
50,2017-08-21,101021.432983,70715.003088,101021.432983,101021.432983,100.907541,0.001000,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
51,2017-08-22,101161.315379,70812.920765,101161.315379,101161.315379,139.882395,0.001385,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
52,2017-08-23,101220.171741,70854.120219,101220.171741,101220.171741,58.856362,0.000582,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
53,2017-08-24,100995.335062,70699.816162,100995.335062,100995.335062,-224.836680,-0.002221,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
54,2017-08-25,101220.745521,70854.521864,101220.745521,101220.745521,225.410459,0.002232,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
55,2017-08-28,101037.913727,70726.539609,101037.913727,101037.913727,-182.831793,-0.001806,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
56,2017-08-29,101318.945750,70923.262025,101318.945750,101318.945750,281.032022,0.002781,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
57,2017-08-30,101193.564906,70835.495434,101193.564906,101193.564906,-125.380844,-0.001237,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
58,2017-08-31,101248.551333,101248.551333,101248.551333,101248.551333,54.986427,0.000543,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $101,248.55
Total Return on Investment (ROI): 1.25%
Annualized Sharpe Ratio: 1.81
--------------------------

In [36]:
import numpy as np
import pandas as pd

ret_col = f"ret_{5}d"
if ret_col not in master_df_with_target.columns:
    master_df_with_target = add_horizon_targets(master_df_with_target, H=5, price_col='close')

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 268
Total capital allocated: $1,746,828.64
Average position size:  $6,518.02
Completed trades with returns: 248
Winning trades: 141 (56.9%)
Losing trades:  107 (43.1%)
Total PnL: $5,824.54
Average PnL per trade: $23.49
Average return: 0.29%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Consumer Goods,58,481910.829322,8308.807402,2811.488139,52.064595,0.006175
Technology,58,482144.997757,8312.844789,1950.703641,36.124141,0.003710
Services,27,73212.641613,2711.579319,795.401931,30.592382,0.005727
Utilities,39,192050.738226,4924.377903,794.328094,22.064669,0.005361
Conglomerates,15,90955.401690,6063.693446,253.292578,23.026598,0.001692
Basic Matierials,6,21398.973357,3566.495560,-9.427590,-1.571265,-0.000309
Financial,7,12905.180886,1843.597269,-169.697025,-24.242432,-0.010065
Industrial Goods,58,392249.877537,6762.928923,-601.550087,-11.139816,-0.001886

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
143,2017-07-25,2017-07-26,VZ,Technology,8778.502492,0.938009,0.018261,0.111642,980.046350
138,2017-07-24,2017-07-25,VZ,Technology,8799.247782,0.939181,0.018373,0.107298,944.143204
148,2017-07-26,2017-07-27,VZ,Technology,8789.325947,0.937932,0.018254,0.085811,754.218558
133,2017-07-21,2017-07-24,VZ,Technology,8841.069234,0.940549,0.018505,0.083880,741.586209
128,2017-07-20,2017-07-21,VZ,Technology,8840.486318,0.941067,0.018555,0.081185,717.714726
90,2017-07-07,2017-07-10,UL,Consumer Goods,8676.549196,0.936837,0.021176,0.040953,355.331010
204,2017-08-10,2017-08-11,GMRE,Conglomerates,7205.329636,0.857341,0.022985,0.048975,352.880609
245,2017-08-24,2017-08-25,UTX,Industrial Goods,7729.077107,0.881616,0.016524,0.038335,296.292320
86,2017-07-06,2017-07-07,UL,Consumer Goods,8623.455680,0.934664,0.021004,0.034038,293.523266
94,2017-07-10,2017-07-11,UL,Consumer Goods,8700.501644,0.937862,0.021257,0.033691,293.130563

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
217,2017-08-15,2017-08-16,GMRE,Conglomerates,6117.609420,0.805490,0.018809,-0.089325,-546.453129
77,2017-07-03,2017-07-05,VZ,Technology,8668.416436,0.934736,0.017955,-0.046889,-406.452608
74,2017-06-30,2017-07-03,VZ,Technology,8578.182527,0.930178,0.017542,-0.032691,-280.433003
81,2017-07-05,2017-07-06,VZ,Technology,8723.238129,0.937803,0.018242,-0.032027,-279.378246
65,2017-06-28,2017-06-29,UL,Consumer Goods,8780.754247,0.939949,0.021425,-0.030111,-264.394192
140,2017-07-24,2017-07-25,UTX,Industrial Goods,7024.396839,0.849493,0.014569,-0.037034,-260.141552
135,2017-07-21,2017-07-24,UTX,Industrial Goods,6860.261788,0.840655,0.014068,-0.037412,-256.655403
185,2017-08-04,2017-08-07,UTX,Industrial Goods,6729.937169,0.830673,0.013519,-0.037863,-254.816897
180,2017-08-03,2017-08-04,UTX,Industrial Goods,6985.167414,0.843547,0.014231,-0.035838,-250.335253
66,2017-06-28,2017-06-29,VZ,Technology,8356.972440,0.917970,0.016506,-0.029438,-246.012570

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Consumer Goods    2811.488139
Technology        1950.703641
Services           795.401931
Utilities          794.328094
Conglomerates      253.292578
Basic Matierials    -9.427590
Financial         -169.697025
Industrial Goods  -601.550087

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Consumer Goods    2811.488139
Technology        1950.703641
Services           795.401931
Utilities          794.328094
Conglomerates      253.292578
Basic Matierials    -9.427590
Financial         -169.697025
Industrial Goods  -601.550087

In [37]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]