# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as Fnn
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [7]:
pandas_ta_classic_path = None
for sp in site.getsitepackages():
    pandas_ta_classic_path = os.path.join(sp, 'pandas_ta_classic')
    if os.path.exists(pandas_ta_classic_path):
        break

if pandas_ta_classic_path:
    squeeze_pro_path = os.path.join(pandas_ta_classic_path, 'momentum', 'squeeze_pro.py')
    if os.path.exists(squeeze_pro_path):
        try:
            with open(squeeze_pro_path, 'r') as f:
                lines = f.readlines()

            new_lines = []
            fixed = False
            for line in lines:
                if "from numpy import NaN as npNaN" in line:
                    new_lines.append(line.replace("from numpy import NaN as npNaN", "# from numpy import NaN as npNaN\nimport numpy as np\n"))
                    fixed = True
                    print("Modified import statement in squeeze_pro.py")
                else:
                    new_lines.append(line)

            if fixed:
                with open(squeeze_pro_path, 'w') as f:
                    f.writelines(new_lines)
                print("Successfully patched pandas_ta_classic/momentum/squeeze_pro.py")
            else:
                print("Could not find the problematic import line in squeeze_pro.py")

        except Exception as e:
            print(f"Error modifying squeeze_pro.py: {e}")
    else:
        print(f"Could not find squeeze_pro.py at {squeeze_pro_path}")
else:
    print("Could not find the pandas_ta_classic library installation path.")

import pandas_ta_classic as ta

Could not find the problematic import line in squeeze_pro.py

### Configurations

In [8]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 1100  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [9]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [10]:
BUCKET_BINS   = [-np.inf, -0.02, -0.005, 0.0, 0.005, 0.02, np.inf]
K = len(BUCKET_BINS) - 1

In [11]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

In [12]:
CALIBRATION_LOGGED = set()

In [13]:
def bucketize_with_edges(x, edges):
    # x: 1D np array of returns; edges: len K+1
    return np.clip(np.digitize(x, edges[1:-1], right=True), 0, len(edges)-2).astype(np.int64)

def make_cumulative_targets(y_idx, K):
    # y_idx in [0..K-1] -> T: [N,K-1] with T[:,k]=1(y>k)
    y = y_idx.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def ordinal_to_class_probs(P_rep):
    # P_rep: [N,K-1] with P(y>k) (after sigmoid), repaired monotone
    N, K1 = P_rep.shape; K = K1+1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:,0] = 1.0 - P_rep[:,0]
    for c in range(1, K-1):
        Pc[:,c] = np.clip(P_rep[:,c-1] - P_rep[:,c], 0., 1.)
    Pc[:,K-1] = P_rep[:,K1-1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)

def monotone_repair_numpy(P):
    P = np.asarray(P, dtype=np.float32).copy()
    for k in range(P.shape[1]-2, -1, -1):
        P[:,k] = np.maximum(P[:,k], P[:,k+1])
    return P

In [ ]:


def _temperature_objective(logits: np.ndarray, y: np.ndarray, temperature: float) -> float:
    if temperature <= 0 or not np.isfinite(temperature):
        return np.inf
    P_cum = 1.0 / (1.0 + np.exp(-logits / temperature))
    P_cum = monotone_repair_numpy(P_cum)
    Pc = ordinal_to_class_probs(P_cum)
    idx = np.arange(len(y))
    eps = 1e-9
    return -np.log(np.clip(Pc[idx, y], eps, 1.0)).mean()


# multiclass calibration tuned for macro-F1 balance
def _class_dist(y_hat, K):
    hist = np.bincount(y_hat, minlength=K).astype(np.float32)
    return hist / max(1, y_hat.size)

def _balance_penalty(p_hat, p_target, norm="l1"):
    if norm == "l1":
        return float(np.abs(p_hat - p_target).sum())
    elif norm == "l2":
        return float(np.sqrt(((p_hat - p_target) ** 2).sum()))
    else:
        return float(np.abs(p_hat - p_target).sum())

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    # decode ordinal cumulative probs to class indices using per-head taus.
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def tune_temperature_and_taus(
    Z_val,
    y_val_idx,
    K,
    T_grid=np.linspace(0.6, 2.5, 15),
    tau_grid=np.linspace(0.2, 0.8, 31),
    lambda_balance=0.05,
    target_priors="uniform",
    coord_rounds=3,
):
    """Learn a temperature T and per-head taus by maximizing macro-F1 with a balance penalty."""
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.detach().cpu().numpy()

    N, K_1 = Z_val.shape
    assert K_1 == K - 1

    if isinstance(target_priors, str) and target_priors == "uniform":
        p_target = np.ones(K, dtype=np.float32) / K
    else:
        p_target = np.asarray(target_priors, dtype=np.float32)
        p_target = p_target / p_target.sum()

    best = {"score": -1e9, "T": 1.0, "taus": np.full(K_1, 0.5, np.float32)}

    for T in T_grid:
        P_cum = 1.0 / (1.0 + np.exp(-(Z_val / T)))
        P_rep = monotone_repair_numpy(P_cum)

        taus = np.full(K_1, 0.5, dtype=np.float32)
        for _ in range(coord_rounds):
            for k in range(K_1):
                best_k = (taus[k], -1e9)
                for tau in tau_grid:
                    taus_try = taus.copy()
                    taus_try[k] = tau
                    y_hat = decode_ordinal_with_taus(P_rep, taus_try)
                    f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
                    p_hat = _class_dist(y_hat, K)
                    score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")
                    if score > best_k[1]:
                        best_k = (tau, score)
                taus[k] = best_k[0]

        y_hat = decode_ordinal_with_taus(P_rep, taus)
        f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
        p_hat = _class_dist(y_hat, K)
        score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")

        if score > best["score"]:
            best.update({"score": score, "T": float(T), "taus": taus.astype(np.float32)})

    return best["T"], best["taus"]

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [15]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close_price') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [ ]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # end current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [17]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [18]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [19]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close_price'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close_price']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [20]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [21]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [22]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [23]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [24]:
class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):  # T: float32 matrix [N, K-1] with 0/1
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)
    def __len__(self): return len(self.X)
    def __getitem__(self, i): return self.X[i], self.T[i]
    
class LSTMOrdinal(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, head='CORAL', K=6):
        super().__init__()
        self.K = K
        self.lstm1 = nn.LSTM(n_features, hidden1, num_layers=1, batch_first=True, dropout=0.1)
        self.inter_drop = nn.Dropout(inter_dropout)
        self.lstm2 = nn.LSTM(hidden1, hidden2, num_layers=1, batch_first=True, dropout=0.1)

        self.norm = nn.BatchNorm1d(hidden2)
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(dropout)

        if head.upper() == 'CORAL':
            self.w = nn.Linear(fc, 1, bias=False)
            self._beta = nn.Parameter(torch.zeros(K-1))
            self.softplus = nn.Softplus()
            self.head_type = 'CORAL'
        else:
            self.fc_out = nn.Linear(fc, K-1)
            self.head_type = 'CORN'

    def forward(self, x):
        out1,_ = self.lstm1(x)
        out1 = self.inter_drop(out1)
        out2,_ = self.lstm2(out1)
        last = out2[:, -1, :]
        last = self.norm(last)
        z = self.relu(self.fc1(last))
        z = self.drop(z)
        if self.head_type == 'CORAL':
            base = self.w(z)                              # [B,1]
            deltas = self.softplus(self._beta)            # ≥0
            b = torch.cumsum(deltas, dim=0)               # [K-1]
            logits = base - b                              # broadcast -> [B,K-1]
        else:
            logits = self.fc_out(z)                        # [B,K-1]
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [25]:

def train_company_models(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 sequence_length: int = None,
                                 H: int = 1,
                                 K: int = K,        # global K
                                 head_type: str = 'CORAL'):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"[TRAIN] {ticker}: preparing data (H={H}) with {len(company_data_df)} rows")

    ret_col = f"ret_{H}d"
    if ret_col not in company_data_df.columns:
        company_data_df = add_horizon_targets(company_data_df, H=H, price_col='close_price')

    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)
    if len(company_data_df) < sequence_length + H + 10:
        print(f"[TRAIN] {ticker}: insufficient history for sequence length {sequence_length}")
        return False, sequence_length

    contigs = identify_contiguous_periods(company_data_df)
    if not contigs:
        print(f"[TRAIN] {ticker}: no contiguous periods found")
        return False, sequence_length

    rets = company_data_df[ret_col].values
    y_idx_all = bucketize_with_edges(rets, BUCKET_BINS)
    X_all = company_data_df[feature_cols].values

    X_seq, y_seq = create_contiguous_sequences(
        X_all, y_idx_all, contigs, sequence_length, H
    )
    if len(X_seq) < 40:
        print(f"[TRAIN] {ticker}: too few sequences ({len(X_seq)})")
        return False, sequence_length
    print(f"[TRAIN] {ticker}: built {len(X_seq)} sequences (seq_len={sequence_length})")

    X_tr, X_val, y_tr, y_val = train_test_split(X_seq, y_seq, test_size=0.2, shuffle=False)

    scaler = MinMaxScaler()
    F = X_tr.shape[-1]
    X_tr = scaler.fit_transform(X_tr.reshape(-1, F)).reshape(X_tr.shape)
    X_val = scaler.transform(X_val.reshape(-1, F)).reshape(X_val.shape)
    print(f"[TRAIN] {ticker}: scaler fitted on {X_tr.shape[0]} training sequences")

    T_tr  = make_cumulative_targets(y_tr, K)
    T_val = make_cumulative_targets(y_val, K)

    train_ds = OrdinalSequenceDataset(X_tr, T_tr)
    val_ds   = OrdinalSequenceDataset(X_val, T_val)
    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_tr.shape[-1]
    model = LSTMOrdinal(n_features=n_features, head=head_type, K=K).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    pos_rate = T_tr.mean(axis=0)
    pos_w = ((1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)).astype(np.float32)
    pos_w = torch.tensor(pos_w, dtype=torch.float32, device=device)

    def loss_fn(logits, T):
        losses = []
        for k in range(logits.shape[1]):
            losses.append(Fnn.binary_cross_entropy_with_logits(logits[:,k], T[:,k], pos_weight=pos_w[k]))
        return torch.stack(losses).mean()

    early = EarlyStopper(patience=15, mode='min')
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)

    for epoch in range(100):
        model.train()
        tot = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            l = loss_fn(logits, yb)
            l.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tot += l.item() * xb.size(0)

        model.eval()
        with torch.no_grad():
            vtot = 0.0
            for xb, yb in val_loader:
                xb, yb = xb.to(device), yb.to(device)
                logits = model(xb)
                l = loss_fn(logits, yb)
                vtot += l.item() * xb.size(0)
            val_loss = vtot / len(val_loader.dataset)

        scheduler.step(val_loss)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:
            break

    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    ret_seq_full = company_data_df[ret_col].values[sequence_length:]
    ret_train = ret_seq_full[:len(y_tr)]
    mu_c = np.array([ret_train[y_tr==c].mean() if np.any(y_tr==c) else 0.0 for c in range(K)], dtype=np.float32)


    taus = None
    temperature = 1.0
    try:
        model.eval()
        batch = 256
        logits_list = []
        for start in range(0, len(X_val), batch):
            xb = torch.from_numpy(X_val[start:start+batch].astype(np.float32)).to(device)
            with torch.no_grad():
                logits = model(xb)
            logits_list.append(logits.cpu().numpy())
        if logits_list:
            val_logits = np.vstack(logits_list)
            T_star, taus = tune_temperature_and_taus(
                Z_val=val_logits,
                y_val_idx=y_val,
                K=K,
                T_grid=np.linspace(0.6, 2.5, 15),
                tau_grid=np.linspace(0.2, 0.8, 31),
                lambda_balance=0.05,
                target_priors="uniform",
                coord_rounds=3,
            )
            temperature = float(T_star)
            print(f"[CAL] {ticker}: taus={np.round(taus, 3)} | temperature={temperature:.3f}")
        else:
            print(f"[CAL] {ticker}: no validation logits -> skipping calibration")
    except Exception as exc:
        print(f"[CAL] {ticker}: calibration failed ({exc})")
        taus = None
        temperature = 1.0

    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt"))
    joblib.dump(scaler, os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
    joblib.dump(BUCKET_BINS, os.path.join(model_save_path, f"{ticker}_edges_H{H}.pkl"))
    joblib.dump(mu_c, os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))
    if taus is not None and len(taus) == (K - 1) and np.all(np.isfinite(taus)):
        joblib.dump(taus, os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored taus")
    if temperature is not None and np.isfinite(temperature):
        joblib.dump(float(temperature), os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored temperature scale {temperature:.3f}")
    print(f"[SAVE] {ticker}: artifacts persisted (H={H})")

    del model, scaler, train_loader, val_loader, train_ds, val_ds
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [26]:

def predict_next_horizon(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         H: int,
                         K: int = 6,
                         head: str = "CORAL") -> dict | None:
    """
    Ordinal inference with optional calibration artifacts. Returns class probs plus
    summary stats so the simulator can log decisions.
    """
    try:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt")
        if not os.path.isfile(state_dict_path):
            return None

        scaler   = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        seq_len  = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
        mu_c     = joblib.load(os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))

        taus_path = os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl")
        T_path    = os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl")
        taus = joblib.load(taus_path) if os.path.isfile(taus_path) else None
        temperature = float(joblib.load(T_path)) if os.path.isfile(T_path) else 1.0

        n_features = len(feature_cols)
        model = LSTMOrdinal(n_features=n_features, head=head.upper(), K=K).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    if 'CALIBRATION_LOGGED' not in globals():
        globals()['CALIBRATION_LOGGED'] = set()
    if ticker not in CALIBRATION_LOGGED:
        if taus is not None:
            print(f"[CAL] {ticker}: loaded taus {np.round(taus,3)}")
        else:
            print(f"[CAL] {ticker}: no taus artifact found")
        print(f"[CAL] {ticker}: temperature scaling {temperature:.3f}")
        CALIBRATION_LOGGED.add(ticker)

    contiguous = identify_contiguous_periods(company_data_df)
    if not contiguous:
        return None
    start, end = contiguous[-1]
    period = company_data_df.iloc[start:end+1]
    if len(period) < seq_len:
        return None

    try:
        last_seq = period.tail(seq_len)
        X_scaled = scaler.transform(last_seq[feature_cols])
    except Exception:
        return None

    x = torch.from_numpy(np.asarray([X_scaled], dtype=np.float32)).to(device)

    with torch.no_grad():
        z = model(x)
        if temperature and temperature > 0 and temperature != 1.0:
            z = z / temperature
        P_cum = torch.sigmoid(z).cpu().numpy()
        P_cum = monotone_repair_numpy(P_cum)
        Pc    = ordinal_to_class_probs(P_cum)

    mu_c = np.asarray(mu_c, dtype=np.float32).reshape(-1)
    if mu_c.shape[0] != K:
        return None
    expected_rise = float((Pc[0] * mu_c).sum())

    top_bucket_idx = K - 1
    prob_top_bucket = float(Pc[0, top_bucket_idx])
    bucket_idx = int(np.argmax(Pc[0]))

    class_idx = None
    if taus is not None:
        taus = np.asarray(taus, dtype=np.float32).reshape(-1)
        if taus.shape[0] == (K - 1):
            class_idx = int(decode_ordinal_with_taus(P_cum, taus=taus)[0])

    positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
    prob_up = float(Pc[0, positive_buckets].sum()) if positive_buckets else prob_top_bucket

    return {
        'ticker': ticker,
        'expected_rise': expected_rise,
        'predicted_prob': prob_up,  # probability of positive move
        'prob_up': prob_up,
        'prob_bucket_top': prob_top_bucket,
        'bucket_idx': bucket_idx,
        'class_idx': class_idx,
        'class_probs': Pc[0].tolist(),
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [27]:

def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                              total_capital: float, sector_threshold: float,
                              kelly_fraction: float) -> pd.DataFrame:
    """Pick strongest candidates per sector and size using Kelly on prob_up and horizon payoffs."""
    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")
    df = daily_predictions_df.copy()

    if 'prob_up' not in df.columns and 'class_probs' in df.columns:
        positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
        def _sum_up(probs):
            if isinstance(probs, (list, tuple)) and len(probs) == K and positive_buckets:
                return float(sum(probs[i] for i in positive_buckets))
            return np.nan
        df['prob_up'] = df['class_probs'].apply(_sum_up)

    if 'prob_up' not in df.columns and 'predicted_prob' in df.columns:
        df['prob_up'] = df['predicted_prob']

    if 'expected_rise' not in df.columns:
        print("[PORT] Missing expected_rise; cannot size portfolio.")
        return pd.DataFrame()

    df = df[(df['prob_up'] >= sector_threshold) & (df['expected_rise'] > 0)]
    print(f"[PORT] {len(df)} tickers cleared prob_up ≥ {sector_threshold:.3f} and positive expected return.")
    if df.empty:
        return pd.DataFrame()

    winners = (df.sort_values(['sector', 'expected_rise'], ascending=[True, False])
                 .groupby('sector', as_index=False)
                 .head(1))
    if winners.empty:
        print("[PORT] No sector winners after grouping.")
        return pd.DataFrame()

    rows = []
    for _, row in winners.iterrows():
        ticker = row['ticker']
        sector = row['sector']
        p_up = float(row['prob_up'])
        payout = payout_map.get(ticker, {})
        b = payout.get('b') if isinstance(payout, dict) else float(payout)
        if not np.isfinite(b) or b <= 0:
            print(f"[PORT] Sector {sector}: skipping {ticker} due to invalid payout ratio {b}.")
            continue
        kelly_pct = p_up - (1.0 - p_up) / b
        if kelly_pct <= 0:
            print(f"[PORT] Sector {sector}: Kelly <= 0 for {ticker} (p_up={p_up:.3f}, b={b:.3f}).")
            continue
        investment_fraction = min(MAX_POSITION_SIZE, kelly_pct * kelly_fraction)
        investment_fraction = max(0.0, investment_fraction)
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            print(f"[PORT] Sector {sector}: allocation ${investment_amount:.2f} below minimum; skipping {ticker}.")
            continue
        print(f"[PORT] Sector {sector}: selecting {ticker} (p_up={p_up:.3f}, kelly={kelly_pct:.3f}) "
              f"with ${investment_amount:.2f} allocation")
        rows.append({
            'ticker': ticker,
            'sector': sector,
            'prob_up': p_up,
            'predicted_prob': p_up,
            'expected_rise': row['expected_rise'],
            'bucket_idx': row.get('bucket_idx', np.nan),
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount
        })

    if not rows:
        print("[PORT] All sector winners rejected after Kelly sizing.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [28]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    """Check the minimal set of artifacts needed for ordinal inference."""
    required = [
        f"{ticker}_lstmORD_H{H}.pt",      # model weights (ordinal head)
        f"{ticker}_scaler_H{H}.pkl",      # feature scaler
        f"{ticker}_seq_length_H{H}.pkl",  # sequence length
        f"{ticker}_mu_c_H{H}.pkl",        # per-class train means μ_c for expected return
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in required)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [ ]:
def run_simulation(master_df: pd.DataFrame, payout_map: dict, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"\nStarting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    # precompute horizon returns if not already present
    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"
    if ret_col not in master_df.columns or tgt_col not in master_df.columns:
        print("Adding horizon targets to master_df...")
        master_df = add_horizon_targets(master_df, H=H, price_col='close_price')

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    # overlapping book
    open_positions = []  # each: {'ticker','invest','entry_date','exit_date'}
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                # realize H-day return measured from entry date
                row = master_df[(master_df['date'] == pos['entry_date']) & (master_df['ticker'] == pos['ticker'])]
                if not row.empty:
                    rH = row.iloc[0][ret_col]
                    if pd.notna(rH):
                        pnl = pos['invest'] * rH
                        total_pnl_today += pnl
                        print(f"[EXIT] {current_date}: {pos['ticker']} r={rH:.4f}, PnL=${pnl:.2f}")
                        capital += pos['invest'] + pnl  # release capital
                # else silently drop if missing
            else:
                still_open.append(pos)
        open_positions = still_open

        # equity at START (after settlements, before new entries)
        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # build prediction universe using info strictly before current_date
        historical_data = master_df[master_df['date'] < current_date]
        if i == 0:  # no yesterday slice for display
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                print("Retraining model for ticker:", ticker)
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)
        print(f"[SIM] {current_date}: built {len(daily_predictions_df)} predictions")
        if (not daily_predictions_df.empty and
            'predicted_prob' not in daily_predictions_df.columns and
            'calibrated_prediction' not in daily_predictions_df.columns):
            print("[WARN] predicted_prob missing from daily_predictions_df columns:",
                  sorted(daily_predictions_df.columns))


        # size raw trades via Kelly
        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df,
            payout_map,
            capital,
            sector_threshold=SECTOR_CONFIDENCE_THRESHOLD,
            kelly_fraction=KELLY_FRACTION,
        )
        if investment_decision_df.empty:
            print(f"[SIM] {current_date}: no trades proposed today.")
        else:
            print(f"[SIM] {current_date}: {len(investment_decision_df)} trades proposed.")

        # entry logic (allow_overlap controls laddering)
        exit_idx = i + H
        if exit_idx < len(unique_dates):
            exit_date = unique_dates[exit_idx]
        else:
            exit_date = None  # can't open new trades that we cannot exit within data

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            # ensure the column exists even if future changes rename it
            if 'predicted_prob' not in investment_decision_df.columns:
                if 'calibrated_prediction' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'calibrated_prediction': 'predicted_prob'}
                    )
                elif 'score' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'score': 'predicted_prob'}
                    )
                else:
                    # nothing to sort by
                    investment_decision_df = pd.DataFrame()

            if not investment_decision_df.empty:
                investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)


            # current exposures (post-settlement)
            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                # per-ticker ladder depth
                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue  # no overlapping allowed

                # base size from Kelly (already scaled by KELLY_FRACTION)
                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))  # vs equity

                # clamp by remaining budgets
                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                # lock capital and record position
                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})
                print(f"[TRADE] {current_date}: allocated ${amt:.2f} to {tkr} exiting on {exit_date}")

        # equity at END (after entries)
        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        # log the day
        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,  # cash only
            'capital_end': capital,                               # cash only
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,                # realized PnL today
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [30]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

In [31]:
companies = pd.read_parquet('stocknet-dataset/stock_table.parquet')
tweets = pd.read_parquet('stocknet-dataset/stock_tweets_withsentiment_withemotion_withstance_nomerge.parquet')
stocks = pd.read_parquet('stocknet-dataset/stock_prices.parquet')

companies = companies.rename(columns={'symbol': 'ticker'})

companies.columns = [x.lower() for x in companies.columns]
tweets.columns = [x.lower() for x in tweets.columns]
stocks.columns = [x.lower() for x in stocks.columns]

tweets['stance_positive'] = (tweets['stance_label'] == 'Positive').astype(int)
tweets['stance_negative'] = (tweets['stance_label'] == 'Negative').astype(int)

tweets_merged = tweets.groupby(['date', 'ticker'], as_index=False).agg({
    'text': lambda x: ' '.join(x),
    'sentiment': lambda x: x.mean(),
    'emotion_anger': 'sum',
    'emotion_disgust': 'sum',
    'emotion_fear': 'sum',
    'emotion_joy': 'sum',
    'emotion_neutral': 'sum',
    'emotion_sadness': 'sum',
    'emotion_surprize': 'sum',
    'stance_positive': 'sum',
    'stance_negative': 'sum'
})




tweets_merged['date'] = pd.to_datetime(tweets_merged['date'])
stocks['date'] = pd.to_datetime(stocks['date'])

"""
master_df = stocks.merge(
    tweets_merged,
    on=["date", "ticker"]
)
"""


master_df = pd.merge(
    stocks,
    tweets_merged,
    on=["date", "ticker"],
    how='left'
)

tweet_feature_cols = ['sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'stance_positive', 'stance_negative']
for col in tweet_feature_cols:
    if col in master_df.columns:
        master_df[col].fillna(0, inplace=True)



companies = companies.rename(columns={'symbol': 'ticker'})

master_df = pd.merge(master_df, companies[['ticker', 'sector', 'company']], on='ticker', how='left')


feature_cols = ['open','high','low','volume']

master_df = master_df.rename(columns={'close': 'close_price', 'company': 'company_name'})


print(f"Shape of master_df before dropping NaNs: {master_df.shape}")
#master_df.dropna(inplace=True)
print(f"Shape of master_df after dropping NaNs: {master_df.shape}")

master_df.rename(columns={'close_price': 'close'}, inplace=True)





master_df.sort_values(by=['ticker', 'date'], inplace=True)


def apply_ta_indicators(df_group):
    df_group.set_index(pd.DatetimeIndex(df_group['date']), inplace=True)
    #Trend
    df_group.ta.ema(length=12, append=True)
    df_group.ta.ema(length=26, append=True)
    df_group.ta.ema(length=50, append=True)

    df_group.ta.macd(fast=12, slow=26, signal=9, append=True)



    df_group.ta.rsi(length=14, append=True)
    df_group.ta.stochrsi(length=14, append=True)


    df_group.ta.atr(length=14, append=True)

    bb = ta.bbands(df_group['close'], length=20, std=2)
    df_group['BB_upper'] = bb['BBU_20_2.0']
    df_group['BB_middle'] = bb['BBM_20_2.0']
    df_group['BB_lower'] = bb['BBL_20_2.0']


    df_group.ta.obv(append=True)
    return df_group.reset_index(drop=True)

master_df = master_df.groupby('ticker').apply(apply_ta_indicators)

Shape of master_df before dropping NaNs: (108592, 21)
Shape of master_df after dropping NaNs: (108592, 21)

In [32]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)

In [33]:
master_df

                  date       open       high        low      close  \
ticker
AAPL   0    2012-09-04  95.108574  96.448570  94.928574  96.424286
       1    2012-09-05  96.510002  96.621429  95.657143  95.747147
       2    2012-09-06  96.167145  96.898575  95.828575  96.610001
       3    2012-09-07  96.864288  97.497147  96.538574  97.205711
       4    2012-09-10  97.207146  97.612854  94.585716  94.677139
...                ...        ...        ...        ...        ...
XOM    1253 2017-08-28  76.900002  76.940002  76.260002  76.470001
       1254 2017-08-29  76.209999  76.489998  76.080002  76.449997
       1255 2017-08-30  76.239998  76.449997  76.059998  76.099998
       1256 2017-08-31  76.269997  76.489998  76.050003  76.330002
       1257 2017-09-01  76.370003  76.849998  76.320000  76.570000

                  volume ticker  stance_positive  stance_negative  \
ticker
AAPL   0      91973000.0   AAPL              0.0              0.0
       1      84093800.0   AAPL              0.0              0.0
       2      97799100.0   AAPL              0.0              0.0
       3      82416600.0   AAPL              0.0              0.0
       4     121999500.0   AAPL              0.0              0.0
...                  ...    ...              ...              ...
XOM    1253    8229700.0    XOM              0.0              0.0
       1254    7060400.0    XOM              0.0              0.0
       1255    8218000.0    XOM              0.0              0.0
       1256   15641700.0    XOM              0.0              0.0
       1257    7340800.0    XOM              0.0              0.0

                       sector  ... MACDh_12_26_9  MACDs_12_26_9     RSI_14  \
ticker                         ...
AAPL   0       Consumer Goods  ...           NaN            NaN        NaN
       1       Consumer Goods  ...           NaN            NaN        NaN
       2       Consumer Goods  ...           NaN            NaN        NaN
       3       Consumer Goods  ...           NaN            NaN        NaN
       4       Consumer Goods  ...           NaN            NaN        NaN
...                       ...  ...           ...            ...        ...
XOM    1253  Basic Matierials  ...     -0.107548      -0.972858  31.975492
       1254  Basic Matierials  ...     -0.069077      -0.990127  31.851847
       1255  Basic Matierials  ...     -0.054652      -1.003790  29.688704
       1256  Basic Matierials  ...     -0.018917      -1.008519  32.913052
       1257  Basic Matierials  ...      0.028984      -1.001273  36.200731

             STOCHRSIk_14_14_3_3  STOCHRSId_14_14_3_3   ATRr_14   BB_upper  \
ticker
AAPL   0                     NaN                  NaN       NaN        NaN
       1                     NaN                  NaN       NaN        NaN
       2                     NaN                  NaN       NaN        NaN
       3                     NaN                  NaN       NaN        NaN
       4                     NaN                  NaN       NaN        NaN
...                          ...                  ...       ...        ...
XOM    1253            35.117121            31.775404  0.786087  81.525829
       1254            48.597552            38.712818  0.759224  81.303475
       1255            55.025431            46.246701  0.732850  80.964170
       1256            73.940933            59.187972  0.711932  80.569554
       1257            85.986580            71.650981  0.698937  80.167620

             BB_middle   BB_lower          OBV
ticker
AAPL   0           NaN        NaN   91973000.0
       1           NaN        NaN    7879200.0
       2           NaN        NaN  105678300.0
       3           NaN        NaN  188094900.0
       4           NaN        NaN   66095400.0
...                ...        ...          ...
XOM    1253    78.2435  74.961171 -268825100.0
       1254    78.0575  74.811525 -275885500.0
       1255    77.8325  74.700830 -284103500.0
       1256    77.6245  74.679446 -268461800.0
       1257    77.4425  74.717380 -261121000.0

[108592 rows x 25 columns]

In [34]:
columns_to_check = ['EMA_12', 'EMA_26','EMA_50','MACD_12_26_9','MACDh_12_26_9','MACDs_12_26_9','RSI_14','ATRr_14','STOCHRSIk_14_14_3_3','STOCHRSId_14_14_3_3','ATRr_14','BB_upper','BB_middle','BB_lower','OBV']
master_df = master_df.dropna(subset=columns_to_check)

In [35]:
feature_cols = ['open','high','low','volume',
                # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV'
]
feature_cols.extend(new_indicator_columns)
print(f"Final feature columns: {feature_cols}")

Final feature columns: ['open', 'high', 'low', 'volume', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV']

In [36]:
master_df = master_df.rename(columns={'close': 'close_price', 'company': 'company_name'})

In [37]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close_price,volume,ticker,stance_positive,stance_negative,sector,...,MACDh_12_26_9,MACDs_12_26_9,RSI_14,STOCHRSIk_14_14_3_3,STOCHRSId_14_14_3_3,ATRr_14,BB_upper,BB_middle,BB_lower,OBV
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,119292600.0,AAPL,0.0,0.0,Consumer Goods,...,-0.538077,-3.703588,25.771012,21.054629,19.582354,2.377852,94.648550,84.401357,74.154164,-1.014356e+09
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,197477700.0,AAPL,0.0,0.0,Consumer Goods,...,-0.537725,-3.838019,23.573491,15.792949,19.993462,2.380310,93.761634,83.514428,73.267223,-1.211834e+09
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,316723400.0,AAPL,0.0,0.0,Consumer Goods,...,-0.455544,-3.951905,24.836267,12.243346,16.363641,2.459547,92.716200,82.679214,72.642228,-8.951103e+08
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,205829400.0,AAPL,0.0,0.0,Consumer Goods,...,0.002769,-3.951213,43.429047,39.692073,22.576123,2.695187,91.617665,82.201285,72.784906,-6.892809e+08
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,160688500.0,AAPL,0.0,0.0,Consumer Goods,...,0.281964,-3.880722,42.011353,69.373201,40.436207,2.679612,91.027780,81.851785,72.675790,-8.499694e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104215,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,-0.107548,-0.972858,31.975492,35.117121,31.775404,0.786087,81.525829,78.243500,74.961171,-2.688251e+08
104216,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,-0.069077,-0.990127,31.851847,48.597552,38.712818,0.759224,81.303475,78.057500,74.811525,-2.758855e+08
104217,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,-0.054652,-1.003790,29.688704,55.025431,46.246701,0.732850,80.964170,77.832500,74.700830,-2.841035e+08
104218,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,-0.018917,-1.008519,32.913052,73.940933,59.187972,0.711932,80.569554,77.624500,74.679446,-2.684618e+08
104219,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,0.028984,-1.001273,36.200731,85.986580,71.650981,0.698937,80.167620,77.442500,74.717380,-2.611210e+08

In [38]:

master_df_with_target = create_target_variable(master_df)
master_df_with_target = add_horizon_targets(master_df_with_target, H=5)
payout_map = calculate_historical_payouts(master_df_with_target)

initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df_with_target,
    payout_map,
    feature_cols,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=5,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Creating target variable...
Target variable created.

Starting simulation with 1100 initial training days... (H=5)
Starting predictions from day 1100 (after 1100 training days)

Simulating Trading Days:   0%|          | 0/108 [00:00<?, ?it/s]

Retraining model for ticker: AAPL
[TRAIN] AAPL: preparing data (H=5) with 1100 rows
[TRAIN] AAPL: built 1084 sequences (seq_len=12)
[TRAIN] AAPL: scaler fitted on 867 training sequences
[CAL] AAPL: taus=[0.78 0.62 0.56 0.42 0.38] | temperature=1.007
[SAVE] AAPL: stored taus
[SAVE] AAPL: stored temperature scale 1.007
[SAVE] AAPL: artifacts persisted (H=5)
[CAL] AAPL: loaded taus [0.78 0.62 0.56 0.42 0.38]
[CAL] AAPL: temperature scaling 1.007
Retraining model for ticker: ABB
[TRAIN] ABB: preparing data (H=5) with 1100 rows
[TRAIN] ABB: built 1084 sequences (seq_len=12)
[TRAIN] ABB: scaler fitted on 867 training sequences
[CAL] ABB: taus=[0.8  0.52 0.52 0.42 0.32] | temperature=0.736
[SAVE] ABB: stored taus
[SAVE] ABB: stored temperature scale 0.736
[SAVE] ABB: artifacts persisted (H=5)
[CAL] ABB: loaded taus [0.8  0.52 0.52 0.42 0.32]
[CAL] ABB: temperature scaling 0.736
Retraining model for ticker: ABBV
[TRAIN] ABBV: preparing data (H=5) with 1019 rows
[TRAIN] ABBV: built 1003 sequences (seq_len=12)
[TRAIN] ABBV: scaler fitted on 802 training sequences
[CAL] ABBV: taus=[0.5  0.44 0.42 0.48 0.3 ] | temperature=1.686
[SAVE] ABBV: stored taus
[SAVE] ABBV: stored temperature scale 1.686
[SAVE] ABBV: artifacts persisted (H=5)
[CAL] ABBV: loaded taus [0.5  0.44 0.42 0.48 0.3 ]
[CAL] ABBV: temperature scaling 1.686
Retraining model for ticker: AEP
[TRAIN] AEP: preparing data (H=5) with 1100 rows
[TRAIN] AEP: built 1084 sequences (seq_len=12)
[TRAIN] AEP: scaler fitted on 867 training sequences
[CAL] AEP: taus=[0.7  0.62 0.52 0.44 0.34] | temperature=1.686
[SAVE] AEP: stored taus
[SAVE] AEP: stored temperature scale 1.686
[SAVE] AEP: artifacts persisted (H=5)
[CAL] AEP: loaded taus [0.7  0.62 0.52 0.44 0.34]
[CAL] AEP: temperature scaling 1.686
Retraining model for ticker: AGFS
[TRAIN] AGFS: preparing data (H=5) with 543 rows
[TRAIN] AGFS: built 527 sequences (seq_len=12)
[TRAIN] AGFS: scaler fitted on 421 training sequences
[CAL] AGFS: taus=[0.72 0.66 0.54 0.44 0.32] | temperature=1.414
[SAVE] AGFS: stored taus
[SAVE] AGFS: stored temperature scale 1.414
[SAVE] AGFS: artifacts persisted (H=5)
[CAL] AGFS: loaded taus [0.72 0.66 0.54 0.44 0.32]
[CAL] AGFS: temperature scaling 1.414
Retraining model for ticker: AMGN
[TRAIN] AMGN: preparing data (H=5) with 1100 rows
[TRAIN] AMGN: built 1084 sequences (seq_len=12)
[TRAIN] AMGN: scaler fitted on 867 training sequences
[CAL] AMGN: taus=[0.54 0.52 0.44 0.36 0.36] | temperature=1.414
[SAVE] AMGN: stored taus
[SAVE] AMGN: stored temperature scale 1.414
[SAVE] AMGN: artifacts persisted (H=5)
[CAL] AMGN: loaded taus [0.54 0.52 0.44 0.36 0.36]
[CAL] AMGN: temperature scaling 1.414
Retraining model for ticker: AMZN
[TRAIN] AMZN: preparing data (H=5) with 1100 rows
[TRAIN] AMZN: built 1084 sequences (seq_len=12)
[TRAIN] AMZN: scaler fitted on 867 training sequences
[CAL] AMZN: taus=[0.8  0.74 0.5  0.44 0.32] | temperature=0.736
[SAVE] AMZN: stored taus
[SAVE] AMZN: stored temperature scale 0.736
[SAVE] AMZN: artifacts persisted (H=5)
[CAL] AMZN: loaded taus [0.8  0.74 0.5  0.44 0.32]
[CAL] AMZN: temperature scaling 0.736
Retraining model for ticker: BA
[TRAIN] BA: preparing data (H=5) with 1100 rows
[TRAIN] BA: built 1084 sequences (seq_len=12)
[TRAIN] BA: scaler fitted on 867 training sequences
[CAL] BA: taus=[0.76 0.5  0.48 0.52 0.3 ] | temperature=1.143
[SAVE] BA: stored taus
[SAVE] BA: stored temperature scale 1.143
[SAVE] BA: artifacts persisted (H=5)
[CAL] BA: loaded taus [0.76 0.5  0.48 0.52 0.3 ]
[CAL] BA: temperature scaling 1.143
Retraining model for ticker: BABA
[TRAIN] BABA: preparing data (H=5) with 587 rows
[TRAIN] BABA: built 571 sequences (seq_len=12)
[TRAIN] BABA: scaler fitted on 456 training sequences
[CAL] BABA: taus=[0.7  0.54 0.5  0.46 0.42] | temperature=1.821
[SAVE] BABA: stored taus
[SAVE] BABA: stored temperature scale 1.821
[SAVE] BABA: artifacts persisted (H=5)
[CAL] BABA: loaded taus [0.7  0.54 0.5  0.46 0.42]
[CAL] BABA: temperature scaling 1.821
Retraining model for ticker: BAC
[TRAIN] BAC: preparing data (H=5) with 1100 rows
[TRAIN] BAC: built 1084 sequences (seq_len=12)
[TRAIN] BAC: scaler fitted on 867 training sequences
[CAL] BAC: taus=[0.64 0.54 0.62 0.48 0.34] | temperature=0.871
[SAVE] BAC: stored taus
[SAVE] BAC: stored temperature scale 0.871
[SAVE] BAC: artifacts persisted (H=5)
[CAL] BAC: loaded taus [0.64 0.54 0.62 0.48 0.34]
[CAL] BAC: temperature scaling 0.871
Retraining model for ticker: BBL
[TRAIN] BBL: preparing data (H=5) with 1100 rows
[TRAIN] BBL: built 1084 sequences (seq_len=12)
[TRAIN] BBL: scaler fitted on 867 training sequences
[CAL] BBL: taus=[0.7  0.6  0.48 0.38 0.26] | temperature=1.279
[SAVE] BBL: stored taus
[SAVE] BBL: stored temperature scale 1.279
[SAVE] BBL: artifacts persisted (H=5)
[CAL] BBL: loaded taus [0.7  0.6  0.48 0.38 0.26]
[CAL] BBL: temperature scaling 1.279
Retraining model for ticker: BCH
[TRAIN] BCH: preparing data (H=5) with 1100 rows
[TRAIN] BCH: built 1084 sequences (seq_len=12)
[TRAIN] BCH: scaler fitted on 867 training sequences
[CAL] BCH: taus=[0.72 0.2  0.52 0.44 0.36] | temperature=1.143
[SAVE] BCH: stored taus
[SAVE] BCH: stored temperature scale 1.143
[SAVE] BCH: artifacts persisted (H=5)
[CAL] BCH: loaded taus [0.72 0.2  0.52 0.44 0.36]
[CAL] BCH: temperature scaling 1.143
Retraining model for ticker: BHP
[TRAIN] BHP: preparing data (H=5) with 1100 rows
[TRAIN] BHP: built 1084 sequences (seq_len=12)
[TRAIN] BHP: scaler fitted on 867 training sequences
[CAL] BHP: taus=[0.66 0.56 0.5  0.34 0.28] | temperature=1.821
[SAVE] BHP: stored taus
[SAVE] BHP: stored temperature scale 1.821
[SAVE] BHP: artifacts persisted (H=5)
[CAL] BHP: loaded taus [0.66 0.56 0.5  0.34 0.28]
[CAL] BHP: temperature scaling 1.821
Retraining model for ticker: BP
[TRAIN] BP: preparing data (H=5) with 1100 rows
[TRAIN] BP: built 1084 sequences (seq_len=12)
[TRAIN] BP: scaler fitted on 867 training sequences
[CAL] BP: taus=[0.72 0.7  0.54 0.48 0.44] | temperature=1.007
[SAVE] BP: stored taus
[SAVE] BP: stored temperature scale 1.007
[SAVE] BP: artifacts persisted (H=5)
[CAL] BP: loaded taus [0.72 0.7  0.54 0.48 0.44]
[CAL] BP: temperature scaling 1.007
Retraining model for ticker: BRK-A
[TRAIN] BRK-A: preparing data (H=5) with 1100 rows
[TRAIN] BRK-A: built 1084 sequences (seq_len=12)
[TRAIN] BRK-A: scaler fitted on 867 training sequences
[CAL] BRK-A: taus=[0.2  0.76 0.62 0.4  0.34] | temperature=0.600
[SAVE] BRK-A: stored taus
[SAVE] BRK-A: stored temperature scale 0.600
[SAVE] BRK-A: artifacts persisted (H=5)
[CAL] BRK-A: loaded taus [0.2  0.76 0.62 0.4  0.34]
[CAL] BRK-A: temperature scaling 0.600
Retraining model for ticker: BSAC
[TRAIN] BSAC: preparing data (H=5) with 1100 rows
[TRAIN] BSAC: built 1084 sequences (seq_len=12)
[TRAIN] BSAC: scaler fitted on 867 training sequences
[CAL] BSAC: taus=[0.8  0.74 0.62 0.46 0.4 ] | temperature=0.871
[SAVE] BSAC: stored taus
[SAVE] BSAC: stored temperature scale 0.871
[SAVE] BSAC: artifacts persisted (H=5)
[CAL] BSAC: loaded taus [0.8  0.74 0.62 0.46 0.4 ]
[CAL] BSAC: temperature scaling 0.871
Retraining model for ticker: BUD
[TRAIN] BUD: preparing data (H=5) with 1100 rows
[TRAIN] BUD: built 1084 sequences (seq_len=12)
[TRAIN] BUD: scaler fitted on 867 training sequences
[CAL] BUD: taus=[0.78 0.8  0.62 0.38 0.2 ] | temperature=0.600
[SAVE] BUD: stored taus
[SAVE] BUD: stored temperature scale 0.600
[SAVE] BUD: artifacts persisted (H=5)
[CAL] BUD: loaded taus [0.78 0.8  0.62 0.38 0.2 ]
[CAL] BUD: temperature scaling 0.600
Retraining model for ticker: C
[TRAIN] C: preparing data (H=5) with 1100 rows
[TRAIN] C: built 1084 sequences (seq_len=12)
[TRAIN] C: scaler fitted on 867 training sequences
[CAL] C: taus=[0.78 0.54 0.5  0.48 0.48] | temperature=0.871
[SAVE] C: stored taus
[SAVE] C: stored temperature scale 0.871
[SAVE] C: artifacts persisted (H=5)
[CAL] C: loaded taus [0.78 0.54 0.5  0.48 0.48]
[CAL] C: temperature scaling 0.871
Retraining model for ticker: CAT
[TRAIN] CAT: preparing data (H=5) with 1100 rows
[TRAIN] CAT: built 1084 sequences (seq_len=12)
[TRAIN] CAT: scaler fitted on 867 training sequences
[CAL] CAT: taus=[0.68 0.7  0.42 0.28 0.26] | temperature=0.600
[SAVE] CAT: stored taus
[SAVE] CAT: stored temperature scale 0.600
[SAVE] CAT: artifacts persisted (H=5)
[CAL] CAT: loaded taus [0.68 0.7  0.42 0.28 0.26]
[CAL] CAT: temperature scaling 0.600
Retraining model for ticker: CELG
[TRAIN] CELG: preparing data (H=5) with 1100 rows
[TRAIN] CELG: built 1084 sequences (seq_len=12)
[TRAIN] CELG: scaler fitted on 867 training sequences
[CAL] CELG: taus=[0.78 0.74 0.54 0.4  0.3 ] | temperature=0.736
[SAVE] CELG: stored taus
[SAVE] CELG: stored temperature scale 0.736
[SAVE] CELG: artifacts persisted (H=5)
[CAL] CELG: loaded taus [0.78 0.74 0.54 0.4  0.3 ]
[CAL] CELG: temperature scaling 0.736
Retraining model for ticker: CHL
[TRAIN] CHL: preparing data (H=5) with 1100 rows
[TRAIN] CHL: built 1084 sequences (seq_len=12)
[TRAIN] CHL: scaler fitted on 867 training sequences
[CAL] CHL: taus=[0.56 0.5  0.5  0.36 0.32] | temperature=1.143
[SAVE] CHL: stored taus
[SAVE] CHL: stored temperature scale 1.143
[SAVE] CHL: artifacts persisted (H=5)
[CAL] CHL: loaded taus [0.56 0.5  0.5  0.36 0.32]
[CAL] CHL: temperature scaling 1.143
Retraining model for ticker: CHTR
[TRAIN] CHTR: preparing data (H=5) with 1100 rows
[TRAIN] CHTR: built 1084 sequences (seq_len=12)
[TRAIN] CHTR: scaler fitted on 867 training sequences
[CAL] CHTR: taus=[0.72 0.64 0.52 0.44 0.38] | temperature=1.686
[SAVE] CHTR: stored taus
[SAVE] CHTR: stored temperature scale 1.686
[SAVE] CHTR: artifacts persisted (H=5)
[CAL] CHTR: loaded taus [0.72 0.64 0.52 0.44 0.38]
[CAL] CHTR: temperature scaling 1.686
Retraining model for ticker: CMCSA
[TRAIN] CMCSA: preparing data (H=5) with 1100 rows
[TRAIN] CMCSA: built 1084 sequences (seq_len=12)
[TRAIN] CMCSA: scaler fitted on 867 training sequences
[CAL] CMCSA: taus=[0.78 0.7  0.44 0.36 0.42] | temperature=1.143
[SAVE] CMCSA: stored taus
[SAVE] CMCSA: stored temperature scale 1.143
[SAVE] CMCSA: artifacts persisted (H=5)
[CAL] CMCSA: loaded taus [0.78 0.7  0.44 0.36 0.42]
[CAL] CMCSA: temperature scaling 1.143
Retraining model for ticker: CODI
[TRAIN] CODI: preparing data (H=5) with 1100 rows
[TRAIN] CODI: built 1084 sequences (seq_len=12)
[TRAIN] CODI: scaler fitted on 867 training sequences
[CAL] CODI: taus=[0.8  0.74 0.52 0.46 0.5 ] | temperature=0.871
[SAVE] CODI: stored taus
[SAVE] CODI: stored temperature scale 0.871
[SAVE] CODI: artifacts persisted (H=5)
[CAL] CODI: loaded taus [0.8  0.74 0.52 0.46 0.5 ]
[CAL] CODI: temperature scaling 0.871
Retraining model for ticker: CSCO
[TRAIN] CSCO: preparing data (H=5) with 1100 rows
[TRAIN] CSCO: built 1084 sequences (seq_len=12)
[TRAIN] CSCO: scaler fitted on 867 training sequences
[CAL] CSCO: taus=[0.78 0.5  0.58 0.56 0.24] | temperature=0.871
[SAVE] CSCO: stored taus
[SAVE] CSCO: stored temperature scale 0.871
[SAVE] CSCO: artifacts persisted (H=5)
[CAL] CSCO: loaded taus [0.78 0.5  0.58 0.56 0.24]
[CAL] CSCO: temperature scaling 0.871
Retraining model for ticker: CVX
[TRAIN] CVX: preparing data (H=5) with 1100 rows
[TRAIN] CVX: built 1084 sequences (seq_len=12)
[TRAIN] CVX: scaler fitted on 867 training sequences
[CAL] CVX: taus=[0.8  0.76 0.56 0.42 0.34] | temperature=0.736
[SAVE] CVX: stored taus
[SAVE] CVX: stored temperature scale 0.736
[SAVE] CVX: artifacts persisted (H=5)
[CAL] CVX: loaded taus [0.8  0.76 0.56 0.42 0.34]
[CAL] CVX: temperature scaling 0.736
Retraining model for ticker: D
[TRAIN] D: preparing data (H=5) with 1100 rows
[TRAIN] D: built 1084 sequences (seq_len=12)
[TRAIN] D: scaler fitted on 867 training sequences
[CAL] D: taus=[0.8  0.74 0.54 0.5  0.54] | temperature=1.550
[SAVE] D: stored taus
[SAVE] D: stored temperature scale 1.550
[SAVE] D: artifacts persisted (H=5)
[CAL] D: loaded taus [0.8  0.74 0.54 0.5  0.54]
[CAL] D: temperature scaling 1.550
Retraining model for ticker: DHR
[TRAIN] DHR: preparing data (H=5) with 1100 rows
[TRAIN] DHR: built 1084 sequences (seq_len=12)
[TRAIN] DHR: scaler fitted on 867 training sequences
[CAL] DHR: taus=[0.72 0.52 0.5  0.42 0.32] | temperature=1.007
[SAVE] DHR: stored taus
[SAVE] DHR: stored temperature scale 1.007
[SAVE] DHR: artifacts persisted (H=5)
[CAL] DHR: loaded taus [0.72 0.52 0.5  0.42 0.32]
[CAL] DHR: temperature scaling 1.007
Retraining model for ticker: DIS
[TRAIN] DIS: preparing data (H=5) with 1100 rows
[TRAIN] DIS: built 1084 sequences (seq_len=12)
[TRAIN] DIS: scaler fitted on 867 training sequences
[CAL] DIS: taus=[0.7  0.2  0.44 0.34 0.26] | temperature=1.279
[SAVE] DIS: stored taus
[SAVE] DIS: stored temperature scale 1.279
[SAVE] DIS: artifacts persisted (H=5)
[CAL] DIS: loaded taus [0.7  0.2  0.44 0.34 0.26]
[CAL] DIS: temperature scaling 1.279
Retraining model for ticker: DUK
[TRAIN] DUK: preparing data (H=5) with 1100 rows
[TRAIN] DUK: built 1084 sequences (seq_len=12)
[TRAIN] DUK: scaler fitted on 867 training sequences
[CAL] DUK: taus=[0.38 0.52 0.44 0.42 0.42] | temperature=1.007
[SAVE] DUK: stored taus
[SAVE] DUK: stored temperature scale 1.007
[SAVE] DUK: artifacts persisted (H=5)
[CAL] DUK: loaded taus [0.38 0.52 0.44 0.42 0.42]
[CAL] DUK: temperature scaling 1.007
Retraining model for ticker: EXC
[TRAIN] EXC: preparing data (H=5) with 1100 rows
[TRAIN] EXC: built 1084 sequences (seq_len=12)
[TRAIN] EXC: scaler fitted on 867 training sequences
[CAL] EXC: taus=[0.78 0.8  0.8  0.6  0.4 ] | temperature=0.600
[SAVE] EXC: stored taus
[SAVE] EXC: stored temperature scale 0.600
[SAVE] EXC: artifacts persisted (H=5)
[CAL] EXC: loaded taus [0.78 0.8  0.8  0.6  0.4 ]
[CAL] EXC: temperature scaling 0.600
Retraining model for ticker: FB
[TRAIN] FB: preparing data (H=5) with 1100 rows
[TRAIN] FB: built 1084 sequences (seq_len=12)
[TRAIN] FB: scaler fitted on 867 training sequences
[CAL] FB: taus=[0.78 0.68 0.56 0.46 0.38] | temperature=1.414
[SAVE] FB: stored taus
[SAVE] FB: stored temperature scale 1.414
[SAVE] FB: artifacts persisted (H=5)
[CAL] FB: loaded taus [0.78 0.68 0.56 0.46 0.38]
[CAL] FB: temperature scaling 1.414
Retraining model for ticker: GD
[TRAIN] GD: preparing data (H=5) with 1100 rows
[TRAIN] GD: built 1084 sequences (seq_len=12)
[TRAIN] GD: scaler fitted on 867 training sequences
[CAL] GD: taus=[0.76 0.2  0.58 0.52 0.48] | temperature=1.007
[SAVE] GD: stored taus
[SAVE] GD: stored temperature scale 1.007
[SAVE] GD: artifacts persisted (H=5)
[CAL] GD: loaded taus [0.76 0.2  0.58 0.52 0.48]
[CAL] GD: temperature scaling 1.007
Retraining model for ticker: GE
[TRAIN] GE: preparing data (H=5) with 1100 rows
[TRAIN] GE: built 1084 sequences (seq_len=12)
[TRAIN] GE: scaler fitted on 867 training sequences
[CAL] GE: taus=[0.78 0.46 0.58 0.44 0.42] | temperature=0.871
[SAVE] GE: stored taus
[SAVE] GE: stored temperature scale 0.871
[SAVE] GE: artifacts persisted (H=5)
[CAL] GE: loaded taus [0.78 0.46 0.58 0.44 0.42]
[CAL] GE: temperature scaling 0.871
Retraining model for ticker: GMRE
[TRAIN] GMRE: preparing data (H=5) with 139 rows
[TRAIN] GMRE: built 123 sequences (seq_len=12)
[TRAIN] GMRE: scaler fitted on 98 training sequences
[CAL] GMRE: taus=[0.5  0.4  0.48 0.4  0.3 ] | temperature=1.550
[SAVE] GMRE: stored taus
[SAVE] GMRE: stored temperature scale 1.550
[SAVE] GMRE: artifacts persisted (H=5)
[CAL] GMRE: loaded taus [0.5  0.4  0.48 0.4  0.3 ]
[CAL] GMRE: temperature scaling 1.550
Retraining model for ticker: GOOG
[TRAIN] GOOG: preparing data (H=5) with 1100 rows
[TRAIN] GOOG: built 1084 sequences (seq_len=12)
[TRAIN] GOOG: scaler fitted on 867 training sequences
[CAL] GOOG: taus=[0.7  0.44 0.48 0.5  0.44] | temperature=1.821
[SAVE] GOOG: stored taus
[SAVE] GOOG: stored temperature scale 1.821
[SAVE] GOOG: artifacts persisted (H=5)
[CAL] GOOG: loaded taus [0.7  0.44 0.48 0.5  0.44]
[CAL] GOOG: temperature scaling 1.821
Retraining model for ticker: HD
[TRAIN] HD: preparing data (H=5) with 1100 rows
[TRAIN] HD: built 1084 sequences (seq_len=12)
[TRAIN] HD: scaler fitted on 867 training sequences
[CAL] HD: taus=[0.58 0.52 0.42 0.28 0.36] | temperature=0.871
[SAVE] HD: stored taus
[SAVE] HD: stored temperature scale 0.871
[SAVE] HD: artifacts persisted (H=5)
[CAL] HD: loaded taus [0.58 0.52 0.42 0.28 0.36]
[CAL] HD: temperature scaling 0.871
Retraining model for ticker: HON
[TRAIN] HON: preparing data (H=5) with 1100 rows
[TRAIN] HON: built 1084 sequences (seq_len=12)
[TRAIN] HON: scaler fitted on 867 training sequences
[CAL] HON: taus=[0.8  0.68 0.52 0.5  0.42] | temperature=1.279
[SAVE] HON: stored taus
[SAVE] HON: stored temperature scale 1.279
[SAVE] HON: artifacts persisted (H=5)
[CAL] HON: loaded taus [0.8  0.68 0.52 0.5  0.42]
[CAL] HON: temperature scaling 1.279
Retraining model for ticker: HRG
[TRAIN] HRG: preparing data (H=5) with 1100 rows
[TRAIN] HRG: built 1084 sequences (seq_len=12)
[TRAIN] HRG: scaler fitted on 867 training sequences
[CAL] HRG: taus=[0.76 0.68 0.52 0.48 0.34] | temperature=1.414
[SAVE] HRG: stored taus
[SAVE] HRG: stored temperature scale 1.414
[SAVE] HRG: artifacts persisted (H=5)
[CAL] HRG: loaded taus [0.76 0.68 0.52 0.48 0.34]
[CAL] HRG: temperature scaling 1.414
Retraining model for ticker: HSBC
[TRAIN] HSBC: preparing data (H=5) with 1100 rows
[TRAIN] HSBC: built 1084 sequences (seq_len=12)
[TRAIN] HSBC: scaler fitted on 867 training sequences
[CAL] HSBC: taus=[0.66 0.56 0.52 0.46 0.34] | temperature=1.957
[SAVE] HSBC: stored taus
[SAVE] HSBC: stored temperature scale 1.957
[SAVE] HSBC: artifacts persisted (H=5)
[CAL] HSBC: loaded taus [0.66 0.56 0.52 0.46 0.34]
[CAL] HSBC: temperature scaling 1.957
Retraining model for ticker: IEP
[TRAIN] IEP: preparing data (H=5) with 1100 rows
[TRAIN] IEP: built 1084 sequences (seq_len=12)
[TRAIN] IEP: scaler fitted on 867 training sequences
[CAL] IEP: taus=[0.7  0.6  0.52 0.38 0.28] | temperature=1.414
[SAVE] IEP: stored taus
[SAVE] IEP: stored temperature scale 1.414
[SAVE] IEP: artifacts persisted (H=5)
[CAL] IEP: loaded taus [0.7  0.6  0.52 0.38 0.28]
[CAL] IEP: temperature scaling 1.414
Retraining model for ticker: INTC
[TRAIN] INTC: preparing data (H=5) with 1100 rows
[TRAIN] INTC: built 1084 sequences (seq_len=12)
[TRAIN] INTC: scaler fitted on 867 training sequences
[CAL] INTC: taus=[0.78 0.46 0.52 0.48 0.42] | temperature=1.143
[SAVE] INTC: stored taus
[SAVE] INTC: stored temperature scale 1.143
[SAVE] INTC: artifacts persisted (H=5)
[CAL] INTC: loaded taus [0.78 0.46 0.52 0.48 0.42]
[CAL] INTC: temperature scaling 1.143
Retraining model for ticker: JNJ
[TRAIN] JNJ: preparing data (H=5) with 1100 rows
[TRAIN] JNJ: built 1084 sequences (seq_len=12)
[TRAIN] JNJ: scaler fitted on 867 training sequences
[CAL] JNJ: taus=[0.62 0.48 0.46 0.38 0.3 ] | temperature=2.500
[SAVE] JNJ: stored taus
[SAVE] JNJ: stored temperature scale 2.500
[SAVE] JNJ: artifacts persisted (H=5)
[CAL] JNJ: loaded taus [0.62 0.48 0.46 0.38 0.3 ]
[CAL] JNJ: temperature scaling 2.500
Retraining model for ticker: JPM
[TRAIN] JPM: preparing data (H=5) with 1100 rows
[TRAIN] JPM: built 1084 sequences (seq_len=12)
[TRAIN] JPM: scaler fitted on 867 training sequences
[CAL] JPM: taus=[0.76 0.66 0.44 0.34 0.34] | temperature=0.600
[SAVE] JPM: stored taus
[SAVE] JPM: stored temperature scale 0.600
[SAVE] JPM: artifacts persisted (H=5)
[CAL] JPM: loaded taus [0.76 0.66 0.44 0.34 0.34]
[CAL] JPM: temperature scaling 0.600
Retraining model for ticker: KO
[TRAIN] KO: preparing data (H=5) with 1100 rows
[TRAIN] KO: built 1084 sequences (seq_len=12)
[TRAIN] KO: scaler fitted on 867 training sequences
[CAL] KO: taus=[0.56 0.48 0.42 0.36 0.6 ] | temperature=1.007
[SAVE] KO: stored taus
[SAVE] KO: stored temperature scale 1.007
[SAVE] KO: artifacts persisted (H=5)
[CAL] KO: loaded taus [0.56 0.48 0.42 0.36 0.6 ]
[CAL] KO: temperature scaling 1.007
Retraining model for ticker: LMT
[TRAIN] LMT: preparing data (H=5) with 1100 rows
[TRAIN] LMT: built 1084 sequences (seq_len=12)
[TRAIN] LMT: scaler fitted on 867 training sequences
[CAL] LMT: taus=[0.66 0.58 0.52 0.42 0.38] | temperature=1.957

Simulating Trading Days:   1%|          | 1/108 [14:26<25:44:40, 866.17s/it]

[CAL] XOM: taus=[0.68 0.48 0.52 0.48 0.48] | temperature=1.143
[SAVE] XOM: stored taus
[SAVE] XOM: stored temperature scale 1.143
[SAVE] XOM: artifacts persisted (H=5)
[CAL] XOM: loaded taus [0.68 0.48 0.52 0.48 0.48]
[CAL] XOM: temperature scaling 1.143
[SIM] 2017-03-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.777, kelly=0.535) with $5346.92 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.640, kelly=0.328) with $3282.73 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.718, kelly=0.418) with $4177.65 allocation
[PORT] Sector Financial: selecting V (p_up=0.547, kelly=0.165) with $1651.63 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.544, kelly=0.183) with $1830.28 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.674, kelly=0.398) with $3983.69 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.566, kelly=0.246) with $2455.97 allocation
[PORT] Sector Technology: selecting FB (p_up=0.544, kelly=0.212) with $2118.55 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.623, kelly=0.260) with $2597.78 allocation
[SIM] 2017-03-30 00:00:00: 9 trades proposed.
[TRADE] 2017-03-30 00:00:00: allocated $5346.92 to TOT exiting on 2017-04-06 00:00:00
[TRADE] 2017-03-30 00:00:00: allocated $4177.65 to PM exiting on 2017-04-06 00:00:00
[TRADE] 2017-03-30 00:00:00: allocated $3983.69 to GD exiting on 2017-04-06 00:00:00
[TRADE] 2017-03-30 00:00:00: allocated $3282.73 to REX exiting on 2017-04-06 00:00:00
[TRADE] 2017-03-30 00:00:00: allocated $2597.78 to NEE exiting on 2017-04-06 00:00:00
[TRADE] 2017-03-30 00:00:00: allocated $2455.97 to CHTR exiting on 2017-04-06 00:00:00
[TRADE] 2017-03-30 00:00:00: allocated $1651.63 to V exiting on 2017-04-06 00:00:00
[TRADE] 2017-03-30 00:00:00: allocated $2118.55 to FB exiting on 2017-04-06 00:00:00
[TRADE] 2017-03-30 00:00:00: allocated $1830.28 to CELG exiting on 2017-04-06 00:00:00

Simulating Trading Days:   2%|▏         | 2/108 [14:27<10:31:43, 357.58s/it]

[SIM] 2017-03-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.790, kelly=0.561) with $4069.94 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.600, kelly=0.255) with $1851.97 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.714, kelly=0.410) with $2976.09 allocation
[PORT] Sector Financial: selecting V (p_up=0.547, kelly=0.166) with $1200.78 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.573, kelly=0.235) with $1705.90 allocation
[PORT] Sector Industrial Goods: selecting LMT (p_up=0.532, kelly=0.147) with $1067.10 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.569, kelly=0.252) with $1830.15 allocation
[PORT] Sector Technology: selecting FB (p_up=0.535, kelly=0.196) with $1420.31 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.680, kelly=0.372) with $2700.17 allocation
[SIM] 2017-03-31 00:00:00: 9 trades proposed.
[TRADE] 2017-03-31 00:00:00: allocated $4069.94 to TOT exiting on 2017-04-07 00:00:00
[TRADE] 2017-03-31 00:00:00: allocated $2976.09 to PM exiting on 2017-04-07 00:00:00
[TRADE] 2017-03-31 00:00:00: allocated $2700.17 to NEE exiting on 2017-04-07 00:00:00
[TRADE] 2017-03-31 00:00:00: allocated $1851.97 to REX exiting on 2017-04-07 00:00:00
[TRADE] 2017-03-31 00:00:00: allocated $1705.90 to CELG exiting on 2017-04-07 00:00:00
[TRADE] 2017-03-31 00:00:00: allocated $1830.15 to CHTR exiting on 2017-04-07 00:00:00
[TRADE] 2017-03-31 00:00:00: allocated $1200.78 to V exiting on 2017-04-07 00:00:00
[TRADE] 2017-03-31 00:00:00: allocated $1420.31 to FB exiting on 2017-04-07 00:00:00
[TRADE] 2017-03-31 00:00:00: allocated $1067.10 to LMT exiting on 2017-04-07 00:00:00

Simulating Trading Days:   3%|▎         | 3/108 [14:29<5:41:08, 194.94s/it]

[SIM] 2017-04-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.796, kelly=0.574) with $3083.56 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.567, kelly=0.193) with $1035.04 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.709, kelly=0.401) with $2152.71 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.825, kelly=0.660) with $3548.59 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.613, kelly=0.308) with $1654.89 allocation
[PORT] Sector Industrial Goods: selecting LMT (p_up=0.530, kelly=0.144) with $773.42 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.706, kelly=0.437) with $2345.85 allocation
[PORT] Sector Technology: selecting FB (p_up=0.530, kelly=0.187) with $1004.50 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.705, kelly=0.421) with $2263.62 allocation
[SIM] 2017-04-03 00:00:00: 9 trades proposed.
[TRADE] 2017-04-03 00:00:00: allocated $3548.59 to JPM exiting on 2017-04-10 00:00:00
[TRADE] 2017-04-03 00:00:00: allocated $3083.56 to TOT exiting on 2017-04-10 00:00:00
[TRADE] 2017-04-03 00:00:00: allocated $2152.71 to PM exiting on 2017-04-10 00:00:00
[TRADE] 2017-04-03 00:00:00: allocated $2345.85 to PCLN exiting on 2017-04-10 00:00:00
[TRADE] 2017-04-03 00:00:00: allocated $2263.62 to NEE exiting on 2017-04-10 00:00:00
[TRADE] 2017-04-03 00:00:00: allocated $1654.89 to CELG exiting on 2017-04-10 00:00:00
[TRADE] 2017-04-03 00:00:00: allocated $1035.04 to REX exiting on 2017-04-10 00:00:00
[TRADE] 2017-04-03 00:00:00: allocated $1004.50 to FB exiting on 2017-04-10 00:00:00
[TRADE] 2017-04-03 00:00:00: allocated $773.42 to LMT exiting on 2017-04-10 00:00:00

Simulating Trading Days:   4%|▎         | 4/108 [14:30<3:25:25, 118.51s/it]

[SIM] 2017-04-04 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.796, kelly=0.573) with $2056.00 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.541, kelly=0.144) with $517.09 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.702, kelly=0.386) with $1382.89 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.877, kelly=0.761) with $2731.26 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.658, kelly=0.388) with $1393.10 allocation
[PORT] Sector Industrial Goods: selecting LMT (p_up=0.529, kelly=0.143) with $512.93 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.727, kelly=0.477) with $1710.39 allocation
[PORT] Sector Technology: selecting FB (p_up=0.529, kelly=0.185) with $663.52 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.837, kelly=0.666) with $2388.33 allocation
[SIM] 2017-04-04 00:00:00: 9 trades proposed.
[TRADE] 2017-04-04 00:00:00: allocated $2731.26 to JPM exiting on 2017-04-11 00:00:00
[TRADE] 2017-04-04 00:00:00: allocated $2388.33 to PPL exiting on 2017-04-11 00:00:00
[TRADE] 2017-04-04 00:00:00: allocated $750.62 to PCLN exiting on 2017-04-11 00:00:00

Simulating Trading Days:   5%|▍         | 5/108 [14:31<2:10:59, 76.30s/it]

[SIM] 2017-04-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.794, kelly=0.570) with $1711.33 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.525, kelly=0.114) with $343.44 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.777, kelly=0.584) with $1752.73 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.892, kelly=0.790) with $2369.43 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.672, kelly=0.414) with $1240.65 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.669, kelly=0.389) with $1165.78 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.746, kelly=0.514) with $1541.35 allocation
[PORT] Sector Technology: selecting FB (p_up=0.533, kelly=0.191) with $573.80 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.854, kelly=0.701) with $2103.40 allocation
[SIM] 2017-04-05 00:00:00: 9 trades proposed.
[EXIT] 2017-04-06 00:00:00: TOT r=0.0362, PnL=$193.33
[EXIT] 2017-04-06 00:00:00: PM r=-0.0082, PnL=$-34.22
[EXIT] 2017-04-06 00:00:00: GD r=-0.0131, PnL=$-52.33
[EXIT] 2017-04-06 00:00:00: REX r=0.0165, PnL=$54.24
[EXIT] 2017-04-06 00:00:00: NEE r=0.0127, PnL=$33.05
[EXIT] 2017-04-06 00:00:00: CHTR r=0.0265, PnL=$64.97
[EXIT] 2017-04-06 00:00:00: V r=0.0009, PnL=$1.48
[EXIT] 2017-04-06 00:00:00: FB r=-0.0087, PnL=$-18.45
[EXIT] 2017-04-06 00:00:00: CELG r=-0.0003, PnL=$-0.59

Simulating Trading Days:   6%|▌         | 6/108 [14:33<1:26:25, 50.83s/it]

[SIM] 2017-04-06 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.805, kelly=0.592) with $3416.08 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.509, kelly=0.085) with $491.30 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.838, kelly=0.698) with $4025.63 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.883, kelly=0.773) with $4456.49 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.700, kelly=0.463) with $2671.54 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.685, kelly=0.419) with $2415.77 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.710, kelly=0.455) with $2624.35 allocation
[PORT] Sector Technology: selecting FB (p_up=0.538, kelly=0.200) with $1155.51 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.866, kelly=0.726) with $4187.83 allocation
[SIM] 2017-04-06 00:00:00: 9 trades proposed.
[TRADE] 2017-04-06 00:00:00: allocated $4456.49 to JPM exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-06 00:00:00: allocated $4187.83 to PPL exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-06 00:00:00: allocated $4025.63 to TM exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-06 00:00:00: allocated $3416.08 to TOT exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-06 00:00:00: allocated $2624.35 to AMZN exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-06 00:00:00: allocated $2671.54 to CELG exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-06 00:00:00: allocated $2415.77 to GD exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-06 00:00:00: allocated $1155.51 to FB exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-06 00:00:00: allocated $491.30 to REX exiting on 2017-04-13 00:00:00
[EXIT] 2017-04-07 00:00:00: TOT r=0.0290, PnL=$117.85
[EXIT] 2017-04-07 00:00:00: PM r=0.0062, PnL=$18.45
[EXIT] 2017-04-07 00:00:00: NEE r=0.0044, PnL=$11.78
[EXIT] 2017-04-07 00:00:00: REX r=-0.0251, PnL=$-46.46
[EXIT] 2017-04-07 00:00:00: CELG r=0.0092, PnL=$15.77
[EXIT] 2017-04-07 00:00:00: CHTR r=0.0102, PnL=$18.62
[EXIT] 2017-04-07 00:00:00: V r=-0.0015, PnL=$-1.76
[EXIT] 2017-04-07 00:00:00: FB r=-0.0089, PnL=$-12.70
[EXIT] 2017-04-07 00:00:00: LMT r=0.0098, PnL=$10.49

Simulating Trading Days:   6%|▋         | 7/108 [14:34<58:23, 34.69s/it]

[SIM] 2017-04-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.800, kelly=0.582) with $2977.17 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.505, kelly=0.078) with $400.43 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.890, kelly=0.796) with $4073.03 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.878, kelly=0.763) with $3904.48 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.709, kelly=0.480) with $2455.62 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.701, kelly=0.448) with $2291.06 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.735, kelly=0.501) with $2567.20 allocation
[PORT] Sector Technology: selecting FB (p_up=0.547, kelly=0.216) with $1106.17 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.844, kelly=0.680) with $3480.77 allocation
[SIM] 2017-04-07 00:00:00: 9 trades proposed.
[TRADE] 2017-04-07 00:00:00: allocated $4073.03 to TM exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-07 00:00:00: allocated $3480.77 to PPL exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-07 00:00:00: allocated $2977.17 to TOT exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-07 00:00:00: allocated $2567.20 to AMZN exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-07 00:00:00: allocated $2455.62 to CELG exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-07 00:00:00: allocated $2291.06 to GD exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-07 00:00:00: allocated $1106.17 to FB exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-07 00:00:00: allocated $400.43 to REX exiting on 2017-04-17 00:00:00
[EXIT] 2017-04-10 00:00:00: JPM r=-0.0187, PnL=$-66.50
[EXIT] 2017-04-10 00:00:00: TOT r=0.0218, PnL=$67.18
[EXIT] 2017-04-10 00:00:00: PM r=0.0012, PnL=$2.67
[EXIT] 2017-04-10 00:00:00: PCLN r=0.0011, PnL=$2.62
[EXIT] 2017-04-10 00:00:00: NEE r=0.0055, PnL=$12.49
[EXIT] 2017-04-10 00:00:00: CELG r=0.0151, PnL=$24.95
[EXIT] 2017-04-10 00:00:00: REX r=-0.0289, PnL=$-29.88
[EXIT] 2017-04-10 00:00:00: FB r=-0.0087, PnL=$-8.75
[EXIT] 2017-04-10 00:00:00: LMT r=0.0013, PnL=$1.01

Simulating Trading Days:   7%|▋         | 8/108 [14:36<40:09, 24.10s/it]

[SIM] 2017-04-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.783, kelly=0.548) with $2722.97 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.504, kelly=0.075) with $374.56 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.921, kelly=0.852) with $4236.14 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.869, kelly=0.746) with $3710.61 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.659, kelly=0.390) with $1937.56 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.705, kelly=0.454) with $2257.35 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.746, kelly=0.524) with $2603.52 allocation
[PORT] Sector Technology: selecting FB (p_up=0.557, kelly=0.234) with $1161.82 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.841, kelly=0.674) with $3351.25 allocation
[SIM] 2017-04-10 00:00:00: 9 trades proposed.
[TRADE] 2017-04-10 00:00:00: allocated $4236.14 to TM exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-10 00:00:00: allocated $3710.61 to JPM exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-10 00:00:00: allocated $2722.97 to TOT exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-10 00:00:00: allocated $2603.52 to AMZN exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-10 00:00:00: allocated $2257.35 to GD exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-10 00:00:00: allocated $1937.56 to CELG exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-10 00:00:00: allocated $1161.82 to FB exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-10 00:00:00: allocated $374.56 to REX exiting on 2017-04-18 00:00:00
[EXIT] 2017-04-11 00:00:00: JPM r=-0.0181, PnL=$-49.43
[EXIT] 2017-04-11 00:00:00: PPL r=-0.0005, PnL=$-1.28
[EXIT] 2017-04-11 00:00:00: PCLN r=0.0006, PnL=$0.43

Simulating Trading Days:   8%|▊         | 9/108 [14:37<28:04, 17.01s/it]

[SIM] 2017-04-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.767, kelly=0.514) with $1877.28 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.499, kelly=0.067) with $244.53 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.936, kelly=0.881) with $3216.36 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.874, kelly=0.757) with $2763.46 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.586, kelly=0.260) with $948.99 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.696, kelly=0.439) with $1602.54 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.751, kelly=0.532) with $1943.40 allocation
[PORT] Sector Technology: selecting FB (p_up=0.568, kelly=0.252) with $920.42 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.869, kelly=0.731) with $2669.22 allocation
[SIM] 2017-04-11 00:00:00: 9 trades proposed.
[TRADE] 2017-04-11 00:00:00: allocated $2763.46 to JPM exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $2669.22 to PPL exiting on 2017-04-19 00:00:00

Simulating Trading Days:   9%|▉         | 10/108 [14:39<19:55, 12.20s/it]

[SIM] 2017-04-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.755, kelly=0.488) with $1516.80 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.488, kelly=0.047) with $145.04 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.940, kelly=0.888) with $2761.71 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.888, kelly=0.783) with $2434.23 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.579, kelly=0.247) with $767.89 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.676, kelly=0.401) with $1248.16 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.747, kelly=0.525) with $1633.60 allocation
[PORT] Sector Technology: selecting FB (p_up=0.577, kelly=0.269) with $836.75 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.899, kelly=0.793) with $2465.76 allocation
[SIM] 2017-04-12 00:00:00: 9 trades proposed.
[EXIT] 2017-04-13 00:00:00: JPM r=-0.0241, PnL=$-107.19
[EXIT] 2017-04-13 00:00:00: PPL r=0.0045, PnL=$19.03
[EXIT] 2017-04-13 00:00:00: TM r=-0.0125, PnL=$-50.37
[EXIT] 2017-04-13 00:00:00: TOT r=-0.0258, PnL=$-88.25
[EXIT] 2017-04-13 00:00:00: AMZN r=-0.0152, PnL=$-39.76
[EXIT] 2017-04-13 00:00:00: CELG r=0.0012, PnL=$3.22
[EXIT] 2017-04-13 00:00:00: GD r=0.0023, PnL=$5.58
[EXIT] 2017-04-13 00:00:00: FB r=-0.0126, PnL=$-14.57
[EXIT] 2017-04-13 00:00:00: REX r=-0.0120, PnL=$-5.88

Simulating Trading Days:  10%|█         | 11/108 [14:40<14:27,  8.94s/it]

[SIM] 2017-04-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.756, kelly=0.490) with $2754.05 allocation
[PORT] Sector Conglomerates: selecting REX (p_up=0.478, kelly=0.026) with $148.45 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.941, kelly=0.891) with $5011.70 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.906, kelly=0.817) with $4597.99 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.640, kelly=0.356) with $2004.14 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.678, kelly=0.405) with $2279.56 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.736, kelly=0.505) with $2840.21 allocation
[PORT] Sector Technology: selecting FB (p_up=0.584, kelly=0.281) with $1581.83 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.891, kelly=0.777) with $4369.35 allocation
[SIM] 2017-04-13 00:00:00: 9 trades proposed.
[TRADE] 2017-04-13 00:00:00: allocated $5011.70 to TM exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $4597.99 to JPM exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $4369.35 to PPL exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $2754.05 to TOT exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $2840.21 to AMZN exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $2279.56 to GD exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $2004.14 to CELG exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $1581.83 to FB exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $148.45 to REX exiting on 2017-04-21 00:00:00
[EXIT] 2017-04-17 00:00:00: TM r=0.0020, PnL=$8.08
[EXIT] 2017-04-17 00:00:00: PPL r=0.0177, PnL=$61.64
[EXIT] 2017-04-17 00:00:00: TOT r=-0.0200, PnL=$-59.68
[EXIT] 2017-04-17 00:00:00: AMZN r=0.0079, PnL=$20.40
[EXIT] 2017-04-17 00:00:00: CELG r=-0.0041, PnL=$-9.97
[EXIT] 2017-04-17 00:00:00: GD r=0.0045, PnL=$10.36
[EXIT] 2017-04-17 00:00:00: FB r=0.0045, PnL=$5.03
[EXIT] 2017-04-17 00:00:00: REX r=-0.0092, PnL=$-3.68

Simulating Trading Days:  11%|█         | 12/108 [14:42<10:38,  6.65s/it]

[SIM] 2017-04-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.751, kelly=0.480) with $2401.90 allocation
[PORT] Sector Conglomerates: Kelly <= 0 for REX (p_up=0.456, b=1.158).
[PORT] Sector Consumer Goods: selecting TM (p_up=0.945, kelly=0.897) with $4488.50 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.921, kelly=0.847) with $4238.26 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.770, kelly=0.588) with $2945.12 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.693, kelly=0.433) with $2167.90 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.786, kelly=0.590) with $2954.24 allocation
[PORT] Sector Technology: selecting FB (p_up=0.589, kelly=0.289) with $1444.84 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.869, kelly=0.732) with $3666.17 allocation
[SIM] 2017-04-17 00:00:00: 8 trades proposed.
[TRADE] 2017-04-17 00:00:00: allocated $4488.50 to TM exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $3666.17 to PPL exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $2954.24 to PCLN exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $2945.12 to CELG exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $2401.90 to TOT exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $2167.90 to GD exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $1409.79 to FB exiting on 2017-04-24 00:00:00
[EXIT] 2017-04-18 00:00:00: TM r=-0.0062, PnL=$-26.38
[EXIT] 2017-04-18 00:00:00: JPM r=-0.0084, PnL=$-31.11
[EXIT] 2017-04-18 00:00:00: TOT r=-0.0236, PnL=$-64.39
[EXIT] 2017-04-18 00:00:00: AMZN r=-0.0036, PnL=$-9.36
[EXIT] 2017-04-18 00:00:00: GD r=-0.0015, PnL=$-3.37
[EXIT] 2017-04-18 00:00:00: CELG r=-0.0231, PnL=$-44.78
[EXIT] 2017-04-18 00:00:00: FB r=-0.0006, PnL=$-0.66
[EXIT] 2017-04-18 00:00:00: REX r=0.0082, PnL=$3.06

Simulating Trading Days:  12%|█▏        | 13/108 [14:43<08:04,  5.10s/it]

[SIM] 2017-04-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.722, kelly=0.419) with $2046.13 allocation
[PORT] Sector Conglomerates: Kelly <= 0 for REX (p_up=0.431, b=1.158).
[PORT] Sector Consumer Goods: selecting TM (p_up=0.938, kelly=0.885) with $4322.50 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.944, kelly=0.891) with $4352.95 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.830, kelly=0.695) with $3395.43 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.709, kelly=0.462) with $2256.66 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.795, kelly=0.607) with $2964.37 allocation
[PORT] Sector Technology: selecting FB (p_up=0.586, kelly=0.284) with $1388.34 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.856, kelly=0.716) with $3496.01 allocation
[SIM] 2017-04-18 00:00:00: 8 trades proposed.
[TRADE] 2017-04-18 00:00:00: allocated $4352.95 to JPM exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $4322.50 to TM exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $3496.01 to EXC exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $3395.43 to CELG exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $2964.37 to PCLN exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $349.38 to TOT exiting on 2017-04-25 00:00:00
[EXIT] 2017-04-19 00:00:00: JPM r=-0.0148, PnL=$-40.94
[EXIT] 2017-04-19 00:00:00: PPL r=0.0112, PnL=$30.02

Simulating Trading Days:  13%|█▎        | 14/108 [14:44<06:15,  3.99s/it]

[SIM] 2017-04-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.856, kelly=0.710) with $2514.27 allocation
[PORT] Sector Conglomerates: Kelly <= 0 for REX (p_up=0.412, b=1.158).
[PORT] Sector Consumer Goods: selecting TM (p_up=0.923, kelly=0.857) with $3033.55 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.966, kelly=0.934) with $3304.90 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.866, kelly=0.760) with $2690.07 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.724, kelly=0.490) with $1733.10 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.802, kelly=0.620) with $2195.24 allocation
[PORT] Sector Technology: selecting FB (p_up=0.581, kelly=0.274) with $971.48 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.850, kelly=0.692) with $2449.96 allocation
[SIM] 2017-04-19 00:00:00: 8 trades proposed.
[TRADE] 2017-04-19 00:00:00: allocated $3304.90 to JPM exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $2120.13 to CVX exiting on 2017-04-26 00:00:00

Simulating Trading Days:  14%|█▍        | 15/108 [14:46<04:59,  3.22s/it]

[SIM] 2017-04-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.871, kelly=0.740) with $2216.23 allocation
[PORT] Sector Conglomerates: Kelly <= 0 for REX (p_up=0.386, b=1.158).
[PORT] Sector Consumer Goods: selecting TM (p_up=0.895, kelly=0.804) with $2408.88 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.980, kelly=0.962) with $2883.30 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.857, kelly=0.745) with $2231.98 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.736, kelly=0.512) with $1534.26 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.804, kelly=0.625) with $1872.30 allocation
[PORT] Sector Technology: selecting FB (p_up=0.571, kelly=0.257) with $771.13 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.846, kelly=0.685) with $2052.99 allocation
[SIM] 2017-04-20 00:00:00: 8 trades proposed.
[EXIT] 2017-04-21 00:00:00: TM r=0.0230, PnL=$115.45
[EXIT] 2017-04-21 00:00:00: JPM r=0.0014, PnL=$6.54
[EXIT] 2017-04-21 00:00:00: PPL r=0.0093, PnL=$40.69
[EXIT] 2017-04-21 00:00:00: TOT r=-0.0117, PnL=$-32.16
[EXIT] 2017-04-21 00:00:00: AMZN r=0.0157, PnL=$44.50
[EXIT] 2017-04-21 00:00:00: GD r=0.0118, PnL=$26.98
[EXIT] 2017-04-21 00:00:00: CELG r=-0.0176, PnL=$-35.27
[EXIT] 2017-04-21 00:00:00: FB r=0.0308, PnL=$48.68
[EXIT] 2017-04-21 00:00:00: REX r=0.0006, PnL=$0.08

Simulating Trading Days:  15%|█▍        | 16/108 [14:47<04:07,  2.69s/it]

[SIM] 2017-04-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.868, kelly=0.734) with $4095.94 allocation
[PORT] Sector Conglomerates: Kelly <= 0 for REX (p_up=0.355, b=1.158).
[PORT] Sector Consumer Goods: selecting TM (p_up=0.853, kelly=0.726) with $4051.34 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.990, kelly=0.980) with $5463.64 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.824, kelly=0.685) with $3820.78 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.750, kelly=0.538) with $3002.62 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.803, kelly=0.621) with $3465.88 allocation
[PORT] Sector Technology: selecting FB (p_up=0.558, kelly=0.236) with $1314.39 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.867, kelly=0.727) with $4057.27 allocation
[SIM] 2017-04-21 00:00:00: 8 trades proposed.
[TRADE] 2017-04-21 00:00:00: allocated $5463.64 to JPM exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $4095.94 to CVX exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $4057.27 to PPL exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $4051.34 to TM exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $3820.78 to CELG exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $3465.88 to PCLN exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $783.28 to GD exiting on 2017-04-28 00:00:00
[EXIT] 2017-04-24 00:00:00: TM r=0.0082, PnL=$36.80
[EXIT] 2017-04-24 00:00:00: PPL r=0.0018, PnL=$6.77
[EXIT] 2017-04-24 00:00:00: PCLN r=0.0158, PnL=$46.73
[EXIT] 2017-04-24 00:00:00: CELG r=-0.0154, PnL=$-45.21
[EXIT] 2017-04-24 00:00:00: TOT r=0.0191, PnL=$45.83
[EXIT] 2017-04-24 00:00:00: GD r=0.0160, PnL=$34.66
[EXIT] 2017-04-24 00:00:00: FB r=0.0286, PnL=$40.37

Simulating Trading Days:  16%|█▌        | 17/108 [14:49<03:30,  2.31s/it]

[SIM] 2017-04-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.838, kelly=0.675) with $3388.21 allocation
[PORT] Sector Conglomerates: Kelly <= 0 for REX (p_up=0.324, b=1.158).
[PORT] Sector Consumer Goods: selecting TM (p_up=0.811, kelly=0.647) with $3249.76 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.994, kelly=0.988) with $4962.88 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.795, kelly=0.634) with $3182.95 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.757, kelly=0.550) with $2763.82 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.798, kelly=0.612) with $3074.94 allocation
[PORT] Sector Technology: selecting FB (p_up=0.545, kelly=0.213) with $1072.46 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.880, kelly=0.754) with $3788.49 allocation
[SIM] 2017-04-24 00:00:00: 8 trades proposed.
[TRADE] 2017-04-24 00:00:00: allocated $3788.49 to PPL exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $3388.21 to CVX exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $3249.76 to TM exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $3074.94 to PCLN exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $3182.95 to CELG exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $2763.82 to GD exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $701.62 to FB exiting on 2017-05-01 00:00:00
[EXIT] 2017-04-25 00:00:00: JPM r=0.0364, PnL=$158.46
[EXIT] 2017-04-25 00:00:00: TM r=0.0323, PnL=$139.54
[EXIT] 2017-04-25 00:00:00: EXC r=-0.0196, PnL=$-68.40
[EXIT] 2017-04-25 00:00:00: CELG r=0.0204, PnL=$69.28
[EXIT] 2017-04-25 00:00:00: PCLN r=0.0203, PnL=$60.15
[EXIT] 2017-04-25 00:00:00: TOT r=0.0369, PnL=$12.90

Simulating Trading Days:  17%|█▋        | 18/108 [14:50<03:05,  2.06s/it]

[SIM] 2017-04-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.764, kelly=0.525) with $2589.56 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.764, kelly=0.567) with $2795.34 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.748, kelly=0.481) with $2371.98 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.997, kelly=0.994) with $4904.31 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.745, kelly=0.543) with $2679.03 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.759, kelly=0.555) with $2738.89 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.789, kelly=0.596) with $2938.26 allocation
[PORT] Sector Technology: selecting FB (p_up=0.533, kelly=0.192) with $948.39 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.858, kelly=0.708) with $3494.77 allocation
[SIM] 2017-04-25 00:00:00: 9 trades proposed.
[TRADE] 2017-04-25 00:00:00: allocated $4904.31 to JPM exiting on 2017-05-02 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $3494.77 to PPL exiting on 2017-05-02 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $2938.26 to PCLN exiting on 2017-05-02 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $2795.34 to GMRE exiting on 2017-05-02 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $2738.89 to GD exiting on 2017-05-02 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $2269.43 to PM exiting on 2017-05-02 00:00:00
[EXIT] 2017-04-26 00:00:00: JPM r=0.0470, PnL=$155.35
[EXIT] 2017-04-26 00:00:00: CVX r=0.0177, PnL=$37.63

Simulating Trading Days:  18%|█▊        | 19/108 [14:52<02:44,  1.85s/it]

[SIM] 2017-04-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.535, kelly=0.029) with $103.75 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.839, kelly=0.705) with $2524.23 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.746, kelly=0.475) with $1702.45 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.998, kelly=0.997) with $3568.99 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.631, kelly=0.339) with $1214.31 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.763, kelly=0.562) with $2013.30 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.775, kelly=0.569) with $2036.31 allocation
[PORT] Sector Technology: selecting FB (p_up=0.525, kelly=0.179) with $641.10 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.809, kelly=0.609) with $2179.90 allocation
[SIM] 2017-04-26 00:00:00: 9 trades proposed.
[TRADE] 2017-04-26 00:00:00: allocated $3568.99 to JPM exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $1991.12 to GMRE exiting on 2017-05-03 00:00:00

Simulating Trading Days:  19%|█▊        | 20/108 [14:53<02:35,  1.77s/it]

[SIM] 2017-04-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.557, kelly=0.075) with $226.03 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.893, kelly=0.804) with $2432.32 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.742, kelly=0.469) with $1417.76 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.999, kelly=0.997) with $3017.59 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.559, kelly=0.210) with $635.24 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.771, kelly=0.576) with $1743.95 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.759, kelly=0.538) with $1626.94 allocation
[PORT] Sector Technology: selecting FB (p_up=0.521, kelly=0.171) with $516.03 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.802, kelly=0.595) with $1800.14 allocation
[SIM] 2017-04-27 00:00:00: 9 trades proposed.
[EXIT] 2017-04-28 00:00:00: JPM r=0.0293, PnL=$160.32
[EXIT] 2017-04-28 00:00:00: CVX r=0.0173, PnL=$70.68
[EXIT] 2017-04-28 00:00:00: PPL r=0.0047, PnL=$19.25
[EXIT] 2017-04-28 00:00:00: TM r=0.0146, PnL=$59.30
[EXIT] 2017-04-28 00:00:00: CELG r=0.0146, PnL=$55.94
[EXIT] 2017-04-28 00:00:00: PCLN r=0.0541, PnL=$187.56
[EXIT] 2017-04-28 00:00:00: GD r=0.0257, PnL=$20.11

Simulating Trading Days:  19%|█▉        | 21/108 [14:55<02:26,  1.69s/it]

[SIM] 2017-04-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.564, kelly=0.089) with $505.68 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.922, kelly=0.856) with $4843.79 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.738, kelly=0.459) with $2599.06 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.999, kelly=0.998) with $5642.24 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.573, kelly=0.235) with $1329.56 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.778, kelly=0.589) with $3332.34 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.750, kelly=0.521) with $2944.34 allocation
[PORT] Sector Technology: selecting FB (p_up=0.518, kelly=0.167) with $943.25 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.804, kelly=0.599) with $3387.23 allocation
[SIM] 2017-04-28 00:00:00: 9 trades proposed.
[TRADE] 2017-04-28 00:00:00: allocated $5642.24 to JPM exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $4843.79 to GMRE exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $3387.23 to PPL exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $3332.34 to GD exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $2944.34 to PCLN exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $2599.06 to PM exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $1329.56 to CELG exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $505.68 to TOT exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $943.25 to FB exiting on 2017-05-05 00:00:00
[EXIT] 2017-05-01 00:00:00: PPL r=-0.0005, PnL=$-1.99
[EXIT] 2017-05-01 00:00:00: CVX r=-0.0001, PnL=$-0.32
[EXIT] 2017-05-01 00:00:00: TM r=0.0122, PnL=$39.79
[EXIT] 2017-05-01 00:00:00: PCLN r=0.0396, PnL=$121.90
[EXIT] 2017-05-01 00:00:00: CELG r=0.0074, PnL=$23.52
[EXIT] 2017-05-01 00:00:00: GD r=0.0065, PnL=$17.86
[EXIT] 2017-05-01 00:00:00: FB r=0.0481, PnL=$33.71

Simulating Trading Days:  20%|██        | 22/108 [14:56<02:18,  1.61s/it]

[SIM] 2017-05-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.591, kelly=0.146) with $750.81 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.925, kelly=0.862) with $4432.73 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.727, kelly=0.437) with $2245.81 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.998, kelly=0.997) with $5125.18 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.672, kelly=0.413) with $2121.69 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.788, kelly=0.608) with $3127.87 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.735, kelly=0.492) with $2530.69 allocation
[PORT] Sector Technology: selecting FB (p_up=0.517, kelly=0.164) with $844.02 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.815, kelly=0.621) with $3190.79 allocation
[SIM] 2017-05-01 00:00:00: 9 trades proposed.
[TRADE] 2017-05-01 00:00:00: allocated $3190.79 to PPL exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $3127.87 to GD exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $2530.69 to PCLN exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $2245.81 to PM exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $2121.69 to CELG exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $750.81 to TOT exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $844.02 to FB exiting on 2017-05-08 00:00:00
[EXIT] 2017-05-02 00:00:00: JPM r=-0.0199, PnL=$-97.80
[EXIT] 2017-05-02 00:00:00: PPL r=-0.0031, PnL=$-10.99
[EXIT] 2017-05-02 00:00:00: PCLN r=0.0453, PnL=$132.99
[EXIT] 2017-05-02 00:00:00: GMRE r=-0.0592, PnL=$-165.61
[EXIT] 2017-05-02 00:00:00: GD r=0.0043, PnL=$11.76
[EXIT] 2017-05-02 00:00:00: PM r=-0.0232, PnL=$-52.58

Simulating Trading Days:  21%|██▏       | 23/108 [14:58<02:13,  1.57s/it]

[SIM] 2017-05-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.613, kelly=0.192) with $1064.12 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.906, kelly=0.827) with $4597.84 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.708, kelly=0.398) with $2209.94 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.997, kelly=0.995) with $5528.50 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.759, kelly=0.568) with $3157.56 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.800, kelly=0.631) with $3507.18 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.715, kelly=0.453) with $2518.33 allocation
[PORT] Sector Technology: selecting FB (p_up=0.516, kelly=0.162) with $902.70 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.794, kelly=0.578) with $3209.85 allocation
[SIM] 2017-05-02 00:00:00: 9 trades proposed.
[TRADE] 2017-05-02 00:00:00: allocated $5528.50 to JPM exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $4597.84 to GMRE exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $3507.18 to GD exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $3209.85 to PPL exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $3157.56 to CELG exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $2518.33 to PCLN exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $2209.94 to PM exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $398.32 to TOT exiting on 2017-05-09 00:00:00
[EXIT] 2017-05-03 00:00:00: JPM r=-0.0162, PnL=$-57.71
[EXIT] 2017-05-03 00:00:00: GMRE r=-0.0637, PnL=$-126.88

Simulating Trading Days:  22%|██▏       | 24/108 [14:59<02:08,  1.53s/it]

[SIM] 2017-05-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.637, kelly=0.243) with $868.75 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.851, kelly=0.726) with $2600.43 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.728, kelly=0.447) with $1600.65 allocation
[PORT] Sector Financial: selecting V (p_up=0.658, kelly=0.370) with $1325.09 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.814, kelly=0.667) with $2389.06 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.810, kelly=0.649) with $2326.20 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.590, kelly=0.287) with $1029.56 allocation
[PORT] Sector Technology: selecting FB (p_up=0.516, kelly=0.162) with $580.04 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.806, kelly=0.603) with $2158.61 allocation
[SIM] 2017-05-03 00:00:00: 9 trades proposed.
[TRADE] 2017-05-03 00:00:00: allocated $2600.43 to GMRE exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $1600.65 to UL exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $1229.83 to V exiting on 2017-05-10 00:00:00

Simulating Trading Days:  23%|██▎       | 25/108 [15:01<02:04,  1.50s/it]

[SIM] 2017-05-04 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.653, kelly=0.276) with $838.56 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.575, kelly=0.253) with $770.12 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.729, kelly=0.448) with $1360.77 allocation
[PORT] Sector Financial: selecting V (p_up=0.664, kelly=0.380) with $1154.38 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.844, kelly=0.722) with $2192.56 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.814, kelly=0.657) with $1994.87 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.611, kelly=0.269) with $816.58 allocation
[PORT] Sector Technology: selecting FB (p_up=0.517, kelly=0.165) with $500.79 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.842, kelly=0.676) with $2052.69 allocation
[SIM] 2017-05-04 00:00:00: 9 trades proposed.
[EXIT] 2017-05-05 00:00:00: JPM r=0.0000, PnL=$0.00
[EXIT] 2017-05-05 00:00:00: GMRE r=0.0151, PnL=$73.15
[EXIT] 2017-05-05 00:00:00: PPL r=0.0110, PnL=$37.33
[EXIT] 2017-05-05 00:00:00: GD r=0.0112, PnL=$37.49
[EXIT] 2017-05-05 00:00:00: PCLN r=0.0308, PnL=$90.60
[EXIT] 2017-05-05 00:00:00: PM r=0.0127, PnL=$33.06
[EXIT] 2017-05-05 00:00:00: CELG r=-0.0132, PnL=$-17.58
[EXIT] 2017-05-05 00:00:00: TOT r=0.0324, PnL=$16.40
[EXIT] 2017-05-05 00:00:00: FB r=-0.0001, PnL=$-0.06

Simulating Trading Days:  24%|██▍       | 26/108 [15:02<02:01,  1.49s/it]

[SIM] 2017-05-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.658, kelly=0.286) with $1607.61 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.563, kelly=0.232) with $1304.85 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.730, kelly=0.451) with $2532.93 allocation
[PORT] Sector Financial: selecting V (p_up=0.665, kelly=0.383) with $2153.73 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.828, kelly=0.692) with $3890.52 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.811, kelly=0.652) with $3660.42 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.638, kelly=0.320) with $1798.50 allocation
[PORT] Sector Technology: selecting FB (p_up=0.522, kelly=0.173) with $971.87 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.807, kelly=0.604) with $3392.00 allocation
[SIM] 2017-05-05 00:00:00: 9 trades proposed.
[TRADE] 2017-05-05 00:00:00: allocated $3890.52 to CELG exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $3660.42 to GD exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $3392.00 to PPL exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $2532.93 to UL exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $2153.73 to V exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $1607.61 to TOT exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $1798.50 to AMZN exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $1304.85 to IEP exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $971.87 to FB exiting on 2017-05-12 00:00:00
[EXIT] 2017-05-08 00:00:00: PPL r=0.0187, PnL=$59.65
[EXIT] 2017-05-08 00:00:00: GD r=0.0165, PnL=$51.50
[EXIT] 2017-05-08 00:00:00: PCLN r=0.0182, PnL=$46.00
[EXIT] 2017-05-08 00:00:00: PM r=0.0188, PnL=$42.25
[EXIT] 2017-05-08 00:00:00: CELG r=-0.0459, PnL=$-97.48
[EXIT] 2017-05-08 00:00:00: TOT r=0.0260, PnL=$19.54
[EXIT] 2017-05-08 00:00:00: FB r=-0.0092, PnL=$-7.75

Simulating Trading Days:  25%|██▌       | 27/108 [15:03<02:00,  1.49s/it]

[SIM] 2017-05-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.633, kelly=0.234) with $1165.08 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.553, kelly=0.213) with $1062.36 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.729, kelly=0.448) with $2229.99 allocation
[PORT] Sector Financial: selecting V (p_up=0.663, kelly=0.379) with $1885.34 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.836, kelly=0.706) with $3517.75 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.801, kelly=0.632) with $3146.23 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.649, kelly=0.341) with $1697.30 allocation
[PORT] Sector Technology: selecting FB (p_up=0.529, kelly=0.186) with $924.00 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.924, kelly=0.847) with $4219.71 allocation
[SIM] 2017-05-08 00:00:00: 9 trades proposed.
[TRADE] 2017-05-08 00:00:00: allocated $4219.71 to SRE exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $3517.75 to CELG exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $3146.23 to GD exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $2229.99 to UL exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1885.34 to V exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1697.30 to AMZN exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1165.08 to TOT exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1062.36 to IEP exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $371.85 to FB exiting on 2017-05-15 00:00:00
[EXIT] 2017-05-09 00:00:00: JPM r=0.0029, PnL=$15.98
[EXIT] 2017-05-09 00:00:00: GMRE r=0.0358, PnL=$164.74
[EXIT] 2017-05-09 00:00:00: GD r=0.0130, PnL=$45.54
[EXIT] 2017-05-09 00:00:00: PPL r=0.0087, PnL=$27.85
[EXIT] 2017-05-09 00:00:00: CELG r=-0.0300, PnL=$-94.86
[EXIT] 2017-05-09 00:00:00: PCLN r=0.0163, PnL=$40.99
[EXIT] 2017-05-09 00:00:00: PM r=0.0132, PnL=$29.21
[EXIT] 2017-05-09 00:00:00: TOT r=0.0175, PnL=$6.96

Simulating Trading Days:  26%|██▌       | 28/108 [15:05<01:59,  1.49s/it]

[SIM] 2017-05-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.576, kelly=0.114) with $637.43 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.546, kelly=0.201) with $1123.91 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.736, kelly=0.462) with $2580.08 allocation
[PORT] Sector Financial: selecting V (p_up=0.656, kelly=0.367) with $2047.85 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.865, kelly=0.759) with $4241.34 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.786, kelly=0.605) with $3378.10 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.653, kelly=0.348) with $1945.37 allocation
[PORT] Sector Technology: selecting FB (p_up=0.536, kelly=0.198) with $1106.86 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.840, kelly=0.680) with $3798.85 allocation
[SIM] 2017-05-09 00:00:00: 9 trades proposed.
[TRADE] 2017-05-09 00:00:00: allocated $4241.34 to CELG exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $3798.85 to SRE exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $3378.10 to GD exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $1945.37 to AMZN exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $637.43 to TOT exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $1123.91 to IEP exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $1106.86 to FB exiting on 2017-05-16 00:00:00
[EXIT] 2017-05-10 00:00:00: GMRE r=0.0395, PnL=$102.76
[EXIT] 2017-05-10 00:00:00: UL r=0.0245, PnL=$39.22
[EXIT] 2017-05-10 00:00:00: V r=-0.0021, PnL=$-2.53

Simulating Trading Days:  27%|██▋       | 29/108 [15:06<01:56,  1.48s/it]

[SIM] 2017-05-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.595, kelly=0.197) with $889.41 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.537, kelly=0.185) with $838.25 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.742, kelly=0.476) with $2149.82 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.990, kelly=0.980) with $4431.60 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.869, kelly=0.766) with $3462.69 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.768, kelly=0.572) with $2583.82 allocation
[PORT] Sector Services: selecting BABA (p_up=0.738, kelly=0.495) with $2237.93 allocation
[PORT] Sector Technology: selecting FB (p_up=0.544, kelly=0.211) with $953.59 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.725, kelly=0.449) with $2031.73 allocation
[SIM] 2017-05-10 00:00:00: 9 trades proposed.
[TRADE] 2017-05-10 00:00:00: allocated $4431.60 to JPM exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $2149.82 to UL exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $2237.93 to BABA exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $2031.73 to SRE exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $889.41 to SLB exiting on 2017-05-17 00:00:00

Simulating Trading Days:  28%|██▊       | 30/108 [15:08<01:52,  1.45s/it]

[SIM] 2017-05-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.557, kelly=0.123) with $410.60 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.530, kelly=0.174) with $580.88 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.749, kelly=0.489) with $1636.07 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.990, kelly=0.981) with $3281.32 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.853, kelly=0.737) with $2465.14 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.767, kelly=0.569) with $1904.66 allocation
[PORT] Sector Services: selecting BABA (p_up=0.766, kelly=0.550) with $1840.31 allocation
[PORT] Sector Technology: selecting FB (p_up=0.551, kelly=0.223) with $745.25 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.578, kelly=0.172) with $575.00 allocation
[SIM] 2017-05-11 00:00:00: 9 trades proposed.
[TRADE] 2017-05-11 00:00:00: allocated $2849.17 to JPM exiting on 2017-05-18 00:00:00
[EXIT] 2017-05-12 00:00:00: CELG r=-0.0252, PnL=$-98.21
[EXIT] 2017-05-12 00:00:00: GD r=-0.0019, PnL=$-7.10
[EXIT] 2017-05-12 00:00:00: PPL r=0.0060, PnL=$20.25
[EXIT] 2017-05-12 00:00:00: UL r=0.0205, PnL=$51.92
[EXIT] 2017-05-12 00:00:00: V r=0.0069, PnL=$14.97
[EXIT] 2017-05-12 00:00:00: TOT r=-0.0115, PnL=$-18.56
[EXIT] 2017-05-12 00:00:00: AMZN r=0.0291, PnL=$52.37
[EXIT] 2017-05-12 00:00:00: IEP r=-0.0563, PnL=$-73.45
[EXIT] 2017-05-12 00:00:00: FB r=0.0006, PnL=$0.58

Simulating Trading Days:  29%|██▊       | 31/108 [15:09<01:51,  1.45s/it]

[SIM] 2017-05-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.652, kelly=0.300) with $1555.53 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.521, kelly=0.158) with $817.69 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.753, kelly=0.498) with $2581.78 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.989, kelly=0.979) with $5080.31 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.831, kelly=0.698) with $3620.74 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.777, kelly=0.587) with $3047.08 allocation
[PORT] Sector Services: selecting BABA (p_up=0.783, kelly=0.583) with $3021.92 allocation
[PORT] Sector Technology: selecting FB (p_up=0.556, kelly=0.233) with $1206.62 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.589, kelly=0.192) with $993.90 allocation
[SIM] 2017-05-12 00:00:00: 9 trades proposed.
[TRADE] 2017-05-12 00:00:00: allocated $5080.31 to JPM exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $3620.74 to CELG exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $3021.92 to BABA exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $3047.08 to GD exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $2581.78 to UL exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $1555.53 to CVX exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $993.90 to NEE exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $1206.62 to FB exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $164.49 to IEP exiting on 2017-05-19 00:00:00
[EXIT] 2017-05-15 00:00:00: SRE r=0.0002, PnL=$0.75
[EXIT] 2017-05-15 00:00:00: CELG r=0.0057, PnL=$20.21
[EXIT] 2017-05-15 00:00:00: GD r=-0.0059, PnL=$-18.43
[EXIT] 2017-05-15 00:00:00: UL r=0.0178, PnL=$39.69
[EXIT] 2017-05-15 00:00:00: V r=0.0143, PnL=$26.87
[EXIT] 2017-05-15 00:00:00: AMZN r=0.0094, PnL=$15.97
[EXIT] 2017-05-15 00:00:00: TOT r=0.0069, PnL=$8.00
[EXIT] 2017-05-15 00:00:00: IEP r=-0.0286, PnL=$-30.39
[EXIT] 2017-05-15 00:00:00: FB r=-0.0058, PnL=$-2.14

Simulating Trading Days:  30%|██▉       | 32/108 [15:11<01:49,  1.43s/it]

[SIM] 2017-05-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.683, kelly=0.362) with $1810.39 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.514, kelly=0.145) with $723.13 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.754, kelly=0.499) with $2491.36 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.987, kelly=0.975) with $4872.01 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.824, kelly=0.685) with $3420.45 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.791, kelly=0.614) with $3065.95 allocation
[PORT] Sector Services: selecting BABA (p_up=0.786, kelly=0.587) with $2932.71 allocation
[PORT] Sector Technology: selecting FB (p_up=0.559, kelly=0.238) with $1187.30 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.594, kelly=0.202) with $1007.25 allocation
[SIM] 2017-05-15 00:00:00: 9 trades proposed.
[TRADE] 2017-05-15 00:00:00: allocated $3420.45 to CELG exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $3065.95 to GD exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $2932.71 to BABA exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $2491.36 to UL exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $1810.39 to CVX exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $1007.25 to NEE exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $1187.30 to FB exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $723.13 to IEP exiting on 2017-05-22 00:00:00
[EXIT] 2017-05-16 00:00:00: CELG r=-0.0062, PnL=$-26.13
[EXIT] 2017-05-16 00:00:00: SRE r=-0.0082, PnL=$-31.00
[EXIT] 2017-05-16 00:00:00: GD r=-0.0066, PnL=$-22.34
[EXIT] 2017-05-16 00:00:00: AMZN r=0.0139, PnL=$27.05
[EXIT] 2017-05-16 00:00:00: TOT r=0.0411, PnL=$26.20
[EXIT] 2017-05-16 00:00:00: IEP r=-0.0049, PnL=$-5.53
[EXIT] 2017-05-16 00:00:00: FB r=-0.0047, PnL=$-5.15

Simulating Trading Days:  31%|███       | 33/108 [15:12<01:46,  1.42s/it]

[SIM] 2017-05-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.710, kelly=0.416) with $2058.70 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.513, kelly=0.143) with $708.17 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.736, kelly=0.456) with $2258.26 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.984, kelly=0.968) with $4793.01 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.829, kelly=0.694) with $3437.25 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.801, kelly=0.633) with $3134.25 allocation
[PORT] Sector Services: selecting BABA (p_up=0.780, kelly=0.576) with $2849.69 allocation
[PORT] Sector Technology: selecting FB (p_up=0.562, kelly=0.242) with $1198.67 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.590, kelly=0.195) with $966.41 allocation
[SIM] 2017-05-16 00:00:00: 9 trades proposed.
[TRADE] 2017-05-16 00:00:00: allocated $3437.25 to CELG exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $3134.25 to GD exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $2258.26 to PM exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $2058.70 to CVX exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $966.41 to NEE exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $1198.67 to FB exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $708.17 to IEP exiting on 2017-05-23 00:00:00
[EXIT] 2017-05-17 00:00:00: JPM r=-0.0361, PnL=$-160.17
[EXIT] 2017-05-17 00:00:00: UL r=0.0165, PnL=$35.50
[EXIT] 2017-05-17 00:00:00: BABA r=0.0062, PnL=$13.80
[EXIT] 2017-05-17 00:00:00: SRE r=-0.0098, PnL=$-19.84
[EXIT] 2017-05-17 00:00:00: SLB r=-0.0231, PnL=$-20.56

Simulating Trading Days:  31%|███▏      | 34/108 [15:13<01:45,  1.42s/it]

[SIM] 2017-05-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.733, kelly=0.463) with $2190.82 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.517, kelly=0.150) with $712.13 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.763, kelly=0.511) with $2419.62 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.981, kelly=0.964) with $4563.29 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.832, kelly=0.699) with $3307.48 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.803, kelly=0.636) with $3008.72 allocation
[PORT] Sector Services: selecting BABA (p_up=0.774, kelly=0.565) with $2676.08 allocation
[PORT] Sector Technology: selecting FB (p_up=0.562, kelly=0.243) with $1150.14 allocation
[PORT] Sector Utilities: selecting D (p_up=0.679, kelly=0.361) with $1707.78 allocation
[SIM] 2017-05-17 00:00:00: 9 trades proposed.
[TRADE] 2017-05-17 00:00:00: allocated $4563.29 to JPM exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $2676.08 to BABA exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $2419.62 to PM exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $1707.78 to D exiting on 2017-05-24 00:00:00
[EXIT] 2017-05-18 00:00:00: JPM r=-0.0367, PnL=$-104.60

Simulating Trading Days:  32%|███▏      | 35/108 [15:15<01:45,  1.44s/it]

[SIM] 2017-05-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.750, kelly=0.496) with $1921.28 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.523, kelly=0.161) with $623.94 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.793, kelly=0.574) with $2220.71 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.979, kelly=0.959) with $3712.06 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.853, kelly=0.736) with $2850.44 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.806, kelly=0.642) with $2486.09 allocation
[PORT] Sector Services: selecting BABA (p_up=0.772, kelly=0.561) with $2173.49 allocation
[PORT] Sector Technology: selecting FB (p_up=0.567, kelly=0.250) with $969.05 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.719, kelly=0.424) with $1642.12 allocation
[SIM] 2017-05-18 00:00:00: 9 trades proposed.
[TRADE] 2017-05-18 00:00:00: allocated $3712.06 to JPM exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $2220.71 to PM exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $1642.12 to PPL exiting on 2017-05-25 00:00:00
[EXIT] 2017-05-19 00:00:00: JPM r=-0.0246, PnL=$-125.08
[EXIT] 2017-05-19 00:00:00: CELG r=-0.0200, PnL=$-72.52
[EXIT] 2017-05-19 00:00:00: BABA r=0.0239, PnL=$72.32
[EXIT] 2017-05-19 00:00:00: GD r=0.0014, PnL=$4.36
[EXIT] 2017-05-19 00:00:00: UL r=0.0208, PnL=$53.82
[EXIT] 2017-05-19 00:00:00: CVX r=0.0053, PnL=$8.22
[EXIT] 2017-05-19 00:00:00: NEE r=0.0128, PnL=$12.76
[EXIT] 2017-05-19 00:00:00: FB r=-0.0151, PnL=$-18.22
[EXIT] 2017-05-19 00:00:00: IEP r=-0.0137, PnL=$-2.25

Simulating Trading Days:  33%|███▎      | 36/108 [15:16<01:45,  1.47s/it]

[SIM] 2017-05-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.765, kelly=0.527) with $2760.32 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.531, kelly=0.175) with $917.01 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.822, kelly=0.634) with $3317.55 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.973, kelly=0.948) with $4964.48 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.866, kelly=0.760) with $3978.95 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.804, kelly=0.637) with $3336.47 allocation
[PORT] Sector Services: selecting BABA (p_up=0.784, kelly=0.585) with $3061.25 allocation
[PORT] Sector Technology: selecting FB (p_up=0.567, kelly=0.252) with $1317.21 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.857, kelly=0.718) with $3757.97 allocation
[SIM] 2017-05-19 00:00:00: 9 trades proposed.
[TRADE] 2017-05-19 00:00:00: allocated $4964.48 to JPM exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $3978.95 to CELG exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $3757.97 to EXC exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $3336.47 to GD exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $3061.25 to BABA exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $2739.30 to CVX exiting on 2017-05-26 00:00:00
[EXIT] 2017-05-22 00:00:00: CELG r=-0.0280, PnL=$-95.68
[EXIT] 2017-05-22 00:00:00: GD r=0.0132, PnL=$40.37
[EXIT] 2017-05-22 00:00:00: BABA r=0.0276, PnL=$80.93
[EXIT] 2017-05-22 00:00:00: UL r=0.0244, PnL=$60.90
[EXIT] 2017-05-22 00:00:00: CVX r=-0.0068, PnL=$-12.37
[EXIT] 2017-05-22 00:00:00: NEE r=0.0163, PnL=$16.43
[EXIT] 2017-05-22 00:00:00: FB r=-0.0130, PnL=$-15.42
[EXIT] 2017-05-22 00:00:00: IEP r=-0.0364, PnL=$-26.34

Simulating Trading Days:  34%|███▍      | 37/108 [15:18<01:43,  1.46s/it]

[SIM] 2017-05-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.776, kelly=0.549) with $2592.90 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.539, kelly=0.190) with $894.58 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.849, kelly=0.689) with $3249.40 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.961, kelly=0.924) with $4361.92 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.880, kelly=0.786) with $3708.83 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.789, kelly=0.609) with $2875.79 allocation
[PORT] Sector Services: selecting BABA (p_up=0.777, kelly=0.571) with $2696.37 allocation
[PORT] Sector Technology: selecting FB (p_up=0.565, kelly=0.248) with $1169.93 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.900, kelly=0.802) with $3785.90 allocation
[SIM] 2017-05-22 00:00:00: 9 trades proposed.
[TRADE] 2017-05-22 00:00:00: allocated $3785.90 to EXC exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $3708.83 to CELG exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $2875.79 to GD exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $2696.37 to BABA exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $2592.90 to CVX exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $1012.93 to FB exiting on 2017-05-30 00:00:00
[EXIT] 2017-05-23 00:00:00: CELG r=-0.0172, PnL=$-59.03
[EXIT] 2017-05-23 00:00:00: GD r=0.0206, PnL=$64.68
[EXIT] 2017-05-23 00:00:00: PM r=0.0259, PnL=$58.49
[EXIT] 2017-05-23 00:00:00: CVX r=-0.0091, PnL=$-18.81
[EXIT] 2017-05-23 00:00:00: NEE r=0.0225, PnL=$21.76
[EXIT] 2017-05-23 00:00:00: FB r=-0.0114, PnL=$-13.68
[EXIT] 2017-05-23 00:00:00: IEP r=-0.0305, PnL=$-21.57

Simulating Trading Days:  35%|███▌      | 38/108 [15:19<01:42,  1.47s/it]

[SIM] 2017-05-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.791, kelly=0.579) with $2567.70 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.548, kelly=0.206) with $913.21 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.871, kelly=0.733) with $3249.63 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.944, kelly=0.891) with $3948.62 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.886, kelly=0.797) with $3529.95 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.760, kelly=0.556) with $2463.99 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.823, kelly=0.660) with $2924.32 allocation
[PORT] Sector Technology: selecting FB (p_up=0.561, kelly=0.241) with $1066.33 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.922, kelly=0.846) with $3749.01 allocation
[SIM] 2017-05-23 00:00:00: 9 trades proposed.
[TRADE] 2017-05-23 00:00:00: allocated $3749.01 to EXC exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $3529.95 to CELG exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $3249.63 to PM exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $2924.32 to PCLN exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $331.06 to CVX exiting on 2017-05-31 00:00:00
[EXIT] 2017-05-24 00:00:00: JPM r=0.0171, PnL=$77.98
[EXIT] 2017-05-24 00:00:00: BABA r=0.0173, PnL=$46.33
[EXIT] 2017-05-24 00:00:00: PM r=0.0324, PnL=$78.28
[EXIT] 2017-05-24 00:00:00: D r=0.0363, PnL=$61.94

Simulating Trading Days:  36%|███▌      | 39/108 [15:21<01:40,  1.46s/it]

[SIM] 2017-05-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.797, kelly=0.592) with $2495.24 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.828, kelly=0.685) with $2887.49 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.887, kelly=0.767) with $3233.46 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.938, kelly=0.880) with $3709.36 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.862, kelly=0.754) with $3178.55 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.719, kelly=0.481) with $2028.18 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.839, kelly=0.691) with $2914.27 allocation
[PORT] Sector Technology: selecting FB (p_up=0.557, kelly=0.234) with $985.59 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.933, kelly=0.867) with $3657.45 allocation
[SIM] 2017-05-24 00:00:00: 9 trades proposed.
[TRADE] 2017-05-24 00:00:00: allocated $3709.36 to JPM exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $3233.46 to PM exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $2914.27 to PCLN exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $1694.85 to GMRE exiting on 2017-06-01 00:00:00
[EXIT] 2017-05-25 00:00:00: JPM r=0.0166, PnL=$61.45
[EXIT] 2017-05-25 00:00:00: PM r=0.0519, PnL=$115.36
[EXIT] 2017-05-25 00:00:00: PPL r=0.0284, PnL=$46.56

Simulating Trading Days:  37%|███▋      | 40/108 [15:22<01:39,  1.46s/it]

[SIM] 2017-05-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.795, kelly=0.588) with $2259.64 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.888, kelly=0.794) with $3048.59 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.898, kelly=0.789) with $3030.92 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.950, kelly=0.903) with $3467.31 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.822, kelly=0.682) with $2617.82 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.678, kelly=0.405) with $1554.25 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.849, kelly=0.711) with $2730.14 allocation
[PORT] Sector Technology: selecting FB (p_up=0.551, kelly=0.224) with $859.67 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.940, kelly=0.881) with $3385.50 allocation
[SIM] 2017-05-25 00:00:00: 9 trades proposed.
[TRADE] 2017-05-25 00:00:00: allocated $3467.31 to JPM exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $3030.92 to PM exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $1233.01 to GMRE exiting on 2017-06-02 00:00:00
[EXIT] 2017-05-26 00:00:00: JPM r=0.0068, PnL=$33.96
[EXIT] 2017-05-26 00:00:00: CELG r=-0.0013, PnL=$-5.10
[EXIT] 2017-05-26 00:00:00: EXC r=0.0217, PnL=$81.46
[EXIT] 2017-05-26 00:00:00: GD r=0.0325, PnL=$108.51
[EXIT] 2017-05-26 00:00:00: BABA r=0.0062, PnL=$19.13
[EXIT] 2017-05-26 00:00:00: CVX r=-0.0169, PnL=$-46.29

Simulating Trading Days:  38%|███▊      | 41/108 [15:24<01:36,  1.44s/it]

[SIM] 2017-05-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.785, kelly=0.567) with $2990.27 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.923, kelly=0.858) with $4522.56 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.906, kelly=0.805) with $4244.79 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.971, kelly=0.943) with $4972.69 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.796, kelly=0.636) with $3350.28 allocation
[PORT] Sector Industrial Goods: selecting LMT (p_up=0.520, kelly=0.126) with $663.42 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.854, kelly=0.721) with $3799.95 allocation
[PORT] Sector Technology: selecting FB (p_up=0.543, kelly=0.210) with $1107.75 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.943, kelly=0.888) with $4682.43 allocation
[SIM] 2017-05-26 00:00:00: 9 trades proposed.
[TRADE] 2017-05-26 00:00:00: allocated $4972.69 to JPM exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4682.43 to EXC exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4522.56 to GMRE exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $3799.95 to PCLN exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $3350.28 to CELG exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $644.67 to CVX exiting on 2017-06-05 00:00:00
[EXIT] 2017-05-30 00:00:00: EXC r=0.0149, PnL=$56.47
[EXIT] 2017-05-30 00:00:00: CELG r=-0.0050, PnL=$-18.59
[EXIT] 2017-05-30 00:00:00: GD r=0.0215, PnL=$61.95
[EXIT] 2017-05-30 00:00:00: BABA r=-0.0067, PnL=$-18.16
[EXIT] 2017-05-30 00:00:00: CVX r=-0.0194, PnL=$-50.33
[EXIT] 2017-05-30 00:00:00: FB r=0.0279, PnL=$28.29

Simulating Trading Days:  39%|███▉      | 42/108 [15:25<01:34,  1.44s/it]

[SIM] 2017-05-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.763, kelly=0.523) with $2480.94 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.945, kelly=0.900) with $4271.45 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.911, kelly=0.816) with $3872.70 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.981, kelly=0.964) with $4573.51 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.795, kelly=0.632) with $3001.14 allocation
[PORT] Sector Industrial Goods: selecting LMT (p_up=0.521, kelly=0.128) with $608.10 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.852, kelly=0.717) with $3403.14 allocation
[PORT] Sector Technology: selecting FB (p_up=0.534, kelly=0.195) with $923.65 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.944, kelly=0.890) with $4224.33 allocation
[SIM] 2017-05-30 00:00:00: 9 trades proposed.
[TRADE] 2017-05-30 00:00:00: allocated $4224.33 to EXC exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $3001.14 to CELG exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $2480.94 to CVX exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $923.65 to FB exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $608.10 to LMT exiting on 2017-06-06 00:00:00
[EXIT] 2017-05-31 00:00:00: EXC r=0.0266, PnL=$99.63
[EXIT] 2017-05-31 00:00:00: CELG r=-0.0247, PnL=$-87.26
[EXIT] 2017-05-31 00:00:00: PM r=0.0287, PnL=$93.20
[EXIT] 2017-05-31 00:00:00: PCLN r=0.0269, PnL=$78.63
[EXIT] 2017-05-31 00:00:00: CVX r=-0.0263, PnL=$-8.69

Simulating Trading Days:  40%|███▉      | 43/108 [15:26<01:32,  1.42s/it]

[SIM] 2017-05-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting CVX (p_up=0.729, kelly=0.455) with $2285.58 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.957, kelly=0.921) with $4621.34 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.914, kelly=0.824) with $4133.28 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.983, kelly=0.967) with $4854.27 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.836, kelly=0.706) with $3545.24 allocation
[PORT] Sector Industrial Goods: selecting LMT (p_up=0.525, kelly=0.135) with $675.10 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.846, kelly=0.704) with $3534.95 allocation
[PORT] Sector Technology: selecting FB (p_up=0.527, kelly=0.182) with $912.47 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.944, kelly=0.889) with $4460.80 allocation
[SIM] 2017-05-31 00:00:00: 9 trades proposed.
[TRADE] 2017-05-31 00:00:00: allocated $4460.80 to EXC exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $4133.28 to PM exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $3534.95 to PCLN exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $3545.24 to CELG exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $2285.58 to CVX exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $912.47 to FB exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $510.82 to LMT exiting on 2017-06-07 00:00:00
[EXIT] 2017-06-01 00:00:00: JPM r=-0.0309, PnL=$-114.69
[EXIT] 2017-06-01 00:00:00: PM r=0.0295, PnL=$95.55
[EXIT] 2017-06-01 00:00:00: PCLN r=0.0228, PnL=$66.33
[EXIT] 2017-06-01 00:00:00: GMRE r=-0.0166, PnL=$-28.07

Simulating Trading Days:  41%|████      | 44/108 [15:28<01:30,  1.42s/it]

[SIM] 2017-06-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.597, kelly=0.202) with $853.93 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.957, kelly=0.920) with $3899.30 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.917, kelly=0.829) with $3514.88 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.977, kelly=0.956) with $4051.85 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.886, kelly=0.796) with $3374.84 allocation
[PORT] Sector Industrial Goods: selecting LMT (p_up=0.528, kelly=0.140) with $594.95 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.833, kelly=0.679) with $2878.19 allocation
[PORT] Sector Technology: selecting FB (p_up=0.525, kelly=0.178) with $754.00 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.941, kelly=0.885) with $3748.71 allocation
[SIM] 2017-06-01 00:00:00: 9 trades proposed.
[TRADE] 2017-06-01 00:00:00: allocated $4051.85 to JPM exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $3899.30 to GMRE exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $3514.88 to PM exiting on 2017-06-08 00:00:00
[EXIT] 2017-06-02 00:00:00: JPM r=-0.0318, PnL=$-110.09
[EXIT] 2017-06-02 00:00:00: PM r=0.0193, PnL=$58.60
[EXIT] 2017-06-02 00:00:00: GMRE r=-0.0063, PnL=$-7.73

Simulating Trading Days:  42%|████▏     | 45/108 [15:29<01:29,  1.43s/it]

[SIM] 2017-06-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.615, kelly=0.237) with $914.13 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.946, kelly=0.902) with $3479.25 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.918, kelly=0.832) with $3208.71 allocation
[PORT] Sector Financial: selecting V (p_up=0.631, kelly=0.321) with $1237.68 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.892, kelly=0.806) with $3110.32 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.683, kelly=0.414) with $1596.27 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.825, kelly=0.665) with $2565.17 allocation
[PORT] Sector Technology: selecting FB (p_up=0.525, kelly=0.179) with $691.12 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.939, kelly=0.879) with $3392.14 allocation
[SIM] 2017-06-02 00:00:00: 9 trades proposed.
[TRADE] 2017-06-02 00:00:00: allocated $3479.25 to GMRE exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $3208.71 to PM exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $1101.12 to PCLN exiting on 2017-06-09 00:00:00
[EXIT] 2017-06-05 00:00:00: JPM r=-0.0301, PnL=$-149.72
[EXIT] 2017-06-05 00:00:00: EXC r=0.0226, PnL=$105.88
[EXIT] 2017-06-05 00:00:00: GMRE r=0.0052, PnL=$23.46
[EXIT] 2017-06-05 00:00:00: PCLN r=0.0149, PnL=$56.43
[EXIT] 2017-06-05 00:00:00: CELG r=0.0113, PnL=$37.87
[EXIT] 2017-06-05 00:00:00: CVX r=-0.0146, PnL=$-9.42

Simulating Trading Days:  43%|████▎     | 46/108 [15:31<01:29,  1.45s/it]

[SIM] 2017-06-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.634, kelly=0.275) with $1450.23 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.928, kelly=0.868) with $4585.56 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.918, kelly=0.830) with $4387.15 allocation
[PORT] Sector Financial: selecting V (p_up=0.641, kelly=0.338) with $1787.34 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.841, kelly=0.716) with $3781.09 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.700, kelly=0.446) with $2358.29 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.815, kelly=0.646) with $3410.21 allocation
[PORT] Sector Technology: selecting FB (p_up=0.526, kelly=0.180) with $953.56 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.935, kelly=0.872) with $4606.51 allocation
[SIM] 2017-06-05 00:00:00: 9 trades proposed.
[TRADE] 2017-06-05 00:00:00: allocated $4606.51 to EXC exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $4585.56 to GMRE exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $3781.09 to CELG exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $3410.21 to PCLN exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $2358.29 to GD exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $1787.34 to V exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $1450.23 to SLB exiting on 2017-06-12 00:00:00
[EXIT] 2017-06-06 00:00:00: EXC r=0.0175, PnL=$73.80
[EXIT] 2017-06-06 00:00:00: CELG r=0.0152, PnL=$45.62
[EXIT] 2017-06-06 00:00:00: CVX r=0.0011, PnL=$2.62
[EXIT] 2017-06-06 00:00:00: FB r=0.0028, PnL=$2.61
[EXIT] 2017-06-06 00:00:00: LMT r=-0.0115, PnL=$-6.97

Simulating Trading Days:  44%|████▎     | 47/108 [15:32<01:27,  1.43s/it]

[SIM] 2017-06-06 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.644, kelly=0.295) with $1243.46 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.915, kelly=0.845) with $3564.47 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.916, kelly=0.826) with $3486.52 allocation
[PORT] Sector Financial: selecting V (p_up=0.652, kelly=0.359) with $1516.78 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.773, kelly=0.594) with $2506.02 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.722, kelly=0.485) with $2048.90 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.801, kelly=0.618) with $2607.56 allocation
[PORT] Sector Technology: selecting FB (p_up=0.527, kelly=0.181) with $764.77 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.930, kelly=0.863) with $3643.00 allocation
[SIM] 2017-06-06 00:00:00: 9 trades proposed.
[TRADE] 2017-06-06 00:00:00: allocated $3643.00 to EXC exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $2506.02 to CELG exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $2048.90 to GD exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $1516.78 to V exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $1243.46 to SLB exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $400.89 to FB exiting on 2017-06-13 00:00:00
[EXIT] 2017-06-07 00:00:00: EXC r=0.0083, PnL=$36.86
[EXIT] 2017-06-07 00:00:00: PM r=0.0209, PnL=$86.25
[EXIT] 2017-06-07 00:00:00: PCLN r=0.0071, PnL=$25.01
[EXIT] 2017-06-07 00:00:00: CELG r=0.0276, PnL=$97.92
[EXIT] 2017-06-07 00:00:00: CVX r=0.0028, PnL=$6.41
[EXIT] 2017-06-07 00:00:00: FB r=0.0110, PnL=$10.00
[EXIT] 2017-06-07 00:00:00: LMT r=-0.0133, PnL=$-6.81

Simulating Trading Days:  44%|████▍     | 48/108 [15:34<01:26,  1.44s/it]

[SIM] 2017-06-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.657, kelly=0.283) with $1430.39 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.902, kelly=0.820) with $4141.55 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.913, kelly=0.821) with $4142.49 allocation
[PORT] Sector Financial: selecting V (p_up=0.665, kelly=0.382) with $1928.62 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.746, kelly=0.546) with $2754.04 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.747, kelly=0.532) with $2687.18 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.783, kelly=0.584) with $2949.64 allocation
[PORT] Sector Technology: selecting FB (p_up=0.528, kelly=0.184) with $926.43 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.925, kelly=0.852) with $4300.62 allocation
[SIM] 2017-06-07 00:00:00: 9 trades proposed.
[TRADE] 2017-06-07 00:00:00: allocated $4300.62 to EXC exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $4142.49 to PM exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $2949.64 to PCLN exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $2687.18 to GD exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $2754.04 to CELG exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $1928.62 to V exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $799.49 to TOT exiting on 2017-06-14 00:00:00
[EXIT] 2017-06-08 00:00:00: JPM r=0.0228, PnL=$92.20
[EXIT] 2017-06-08 00:00:00: GMRE r=-0.0011, PnL=$-4.10
[EXIT] 2017-06-08 00:00:00: PM r=0.0017, PnL=$6.11

Simulating Trading Days:  45%|████▌     | 49/108 [15:35<01:25,  1.45s/it]

[SIM] 2017-06-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.701, kelly=0.375) with $1593.06 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.885, kelly=0.789) with $3351.78 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.911, kelly=0.816) with $3465.55 allocation
[PORT] Sector Financial: selecting V (p_up=0.678, kelly=0.407) with $1730.18 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.741, kelly=0.536) with $2276.04 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.771, kelly=0.576) with $2447.77 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.711, kelly=0.458) with $1944.77 allocation
[PORT] Sector Technology: selecting FB (p_up=0.531, kelly=0.188) with $798.43 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.918, kelly=0.838) with $3560.30 allocation
[SIM] 2017-06-08 00:00:00: 9 trades proposed.
[TRADE] 2017-06-08 00:00:00: allocated $3465.55 to PM exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $3351.78 to GMRE exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $1944.77 to AMZN exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $1593.06 to TOT exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $798.43 to FB exiting on 2017-06-15 00:00:00
[EXIT] 2017-06-09 00:00:00: GMRE r=-0.0011, PnL=$-3.66
[EXIT] 2017-06-09 00:00:00: PM r=-0.0137, PnL=$-44.00
[EXIT] 2017-06-09 00:00:00: PCLN r=-0.0284, PnL=$-31.27

Simulating Trading Days:  46%|████▋     | 50/108 [15:37<01:32,  1.60s/it]

[SIM] 2017-06-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.728, kelly=0.431) with $1684.30 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.850, kelly=0.725) with $2832.00 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.908, kelly=0.810) with $3161.85 allocation
[PORT] Sector Financial: selecting V (p_up=0.686, kelly=0.422) with $1647.83 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.743, kelly=0.539) with $2104.88 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.786, kelly=0.605) with $2362.07 allocation
[PORT] Sector Services: selecting BABA (p_up=0.764, kelly=0.545) with $2127.26 allocation
[PORT] Sector Technology: selecting FB (p_up=0.532, kelly=0.191) with $745.21 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.909, kelly=0.821) with $3206.74 allocation
[SIM] 2017-06-09 00:00:00: 9 trades proposed.
[TRADE] 2017-06-09 00:00:00: allocated $3161.85 to PM exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $2832.00 to GMRE exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $2118.36 to BABA exiting on 2017-06-16 00:00:00
[EXIT] 2017-06-12 00:00:00: EXC r=-0.0041, PnL=$-18.86
[EXIT] 2017-06-12 00:00:00: GMRE r=-0.0248, PnL=$-113.57
[EXIT] 2017-06-12 00:00:00: CELG r=0.0106, PnL=$40.02
[EXIT] 2017-06-12 00:00:00: PCLN r=-0.0415, PnL=$-141.68
[EXIT] 2017-06-12 00:00:00: GD r=-0.0152, PnL=$-35.94
[EXIT] 2017-06-12 00:00:00: V r=-0.0316, PnL=$-56.46
[EXIT] 2017-06-12 00:00:00: SLB r=0.0006, PnL=$0.84

Simulating Trading Days:  47%|████▋     | 51/108 [15:39<01:31,  1.60s/it]

[SIM] 2017-06-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.746, kelly=0.470) with $2471.34 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.807, kelly=0.646) with $3395.93 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.837, kelly=0.673) with $3538.81 allocation
[PORT] Sector Financial: selecting V (p_up=0.687, kelly=0.422) with $2220.97 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.714, kelly=0.489) with $2569.10 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.791, kelly=0.615) with $3231.43 allocation
[PORT] Sector Services: selecting BABA (p_up=0.815, kelly=0.643) with $3381.16 allocation
[PORT] Sector Technology: selecting FB (p_up=0.541, kelly=0.206) with $1084.94 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.898, kelly=0.800) with $4206.75 allocation
[SIM] 2017-06-12 00:00:00: 9 trades proposed.
[TRADE] 2017-06-12 00:00:00: allocated $4206.75 to EXC exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $3538.81 to PG exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $3381.16 to BABA exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $3395.93 to GMRE exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $3231.43 to GD exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $2471.34 to TOT exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $1525.86 to CELG exiting on 2017-06-19 00:00:00
[EXIT] 2017-06-13 00:00:00: EXC r=-0.0038, PnL=$-13.90
[EXIT] 2017-06-13 00:00:00: CELG r=0.0234, PnL=$58.75
[EXIT] 2017-06-13 00:00:00: GD r=0.0106, PnL=$21.79
[EXIT] 2017-06-13 00:00:00: V r=-0.0074, PnL=$-11.24
[EXIT] 2017-06-13 00:00:00: SLB r=-0.0089, PnL=$-11.02
[EXIT] 2017-06-13 00:00:00: FB r=-0.0139, PnL=$-5.59

Simulating Trading Days:  48%|████▊     | 52/108 [15:40<01:28,  1.58s/it]

[SIM] 2017-06-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.756, kelly=0.490) with $2067.50 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.605, kelly=0.305) with $1288.75 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.854, kelly=0.707) with $2984.17 allocation
[PORT] Sector Financial: selecting V (p_up=0.681, kelly=0.411) with $1737.26 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.665, kelly=0.401) with $1692.27 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.793, kelly=0.617) with $2606.11 allocation
[PORT] Sector Services: selecting BABA (p_up=0.805, kelly=0.625) with $2640.90 allocation
[PORT] Sector Technology: selecting FB (p_up=0.554, kelly=0.229) with $967.83 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.879, kelly=0.762) with $3218.91 allocation
[SIM] 2017-06-13 00:00:00: 9 trades proposed.
[TRADE] 2017-06-13 00:00:00: allocated $3218.91 to EXC exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $2984.17 to PG exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $2640.90 to BABA exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $2542.22 to GD exiting on 2017-06-20 00:00:00
[EXIT] 2017-06-14 00:00:00: EXC r=0.0022, PnL=$9.40
[EXIT] 2017-06-14 00:00:00: PM r=-0.0209, PnL=$-86.37
[EXIT] 2017-06-14 00:00:00: PCLN r=-0.0311, PnL=$-91.69
[EXIT] 2017-06-14 00:00:00: GD r=0.0121, PnL=$32.56
[EXIT] 2017-06-14 00:00:00: CELG r=0.0295, PnL=$81.28
[EXIT] 2017-06-14 00:00:00: V r=-0.0080, PnL=$-15.45
[EXIT] 2017-06-14 00:00:00: TOT r=-0.0149, PnL=$-11.87

Simulating Trading Days:  49%|████▉     | 53/108 [15:42<01:23,  1.53s/it]

[SIM] 2017-06-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.762, kelly=0.503) with $2530.14 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.613, kelly=0.320) with $1607.83 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.866, kelly=0.731) with $3678.47 allocation
[PORT] Sector Financial: selecting V (p_up=0.672, kelly=0.396) with $1994.77 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.608, kelly=0.298) with $1501.13 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.783, kelly=0.599) with $3012.94 allocation
[PORT] Sector Services: selecting BABA (p_up=0.777, kelly=0.570) with $2868.21 allocation
[PORT] Sector Technology: selecting FB (p_up=0.567, kelly=0.252) with $1266.20 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.846, kelly=0.697) with $3506.00 allocation
[SIM] 2017-06-14 00:00:00: 9 trades proposed.
[TRADE] 2017-06-14 00:00:00: allocated $3678.47 to PG exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $3506.00 to EXC exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $3012.94 to GD exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $2530.14 to TOT exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $1994.77 to V exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $1607.83 to IEP exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $1501.13 to CELG exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $1266.20 to FB exiting on 2017-06-21 00:00:00
[EXIT] 2017-06-15 00:00:00: PM r=-0.0050, PnL=$-17.17
[EXIT] 2017-06-15 00:00:00: GMRE r=-0.0032, PnL=$-10.60
[EXIT] 2017-06-15 00:00:00: AMZN r=-0.0456, PnL=$-88.74
[EXIT] 2017-06-15 00:00:00: TOT r=-0.0307, PnL=$-48.93
[EXIT] 2017-06-15 00:00:00: FB r=-0.0317, PnL=$-25.34

Simulating Trading Days:  50%|█████     | 54/108 [15:43<01:23,  1.55s/it]

[SIM] 2017-06-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.770, kelly=0.520) with $2193.42 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.619, kelly=0.330) with $1393.04 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.869, kelly=0.737) with $3108.22 allocation
[PORT] Sector Financial: selecting V (p_up=0.663, kelly=0.379) with $1600.41 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.548, kelly=0.190) with $802.28 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.764, kelly=0.564) with $2380.72 allocation
[PORT] Sector Services: selecting BABA (p_up=0.726, kelly=0.471) with $1988.80 allocation
[PORT] Sector Technology: selecting FB (p_up=0.576, kelly=0.266) with $1122.81 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.745, kelly=0.498) with $2102.69 allocation
[SIM] 2017-06-15 00:00:00: 9 trades proposed.
[TRADE] 2017-06-15 00:00:00: allocated $2193.42 to TOT exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $2102.69 to NEE exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $1600.41 to V exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $1393.04 to IEP exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $1122.81 to FB exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $802.28 to CELG exiting on 2017-06-22 00:00:00
[EXIT] 2017-06-16 00:00:00: PM r=0.0143, PnL=$45.27
[EXIT] 2017-06-16 00:00:00: GMRE r=-0.0179, PnL=$-50.68
[EXIT] 2017-06-16 00:00:00: BABA r=-0.0328, PnL=$-69.43

Simulating Trading Days:  51%|█████     | 55/108 [15:45<01:21,  1.53s/it]

[SIM] 2017-06-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.776, kelly=0.532) with $2182.39 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.621, kelly=0.334) with $1369.04 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.859, kelly=0.718) with $2945.04 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.998, kelly=0.996) with $4085.43 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.521, kelly=0.143) with $585.02 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.777, kelly=0.575) with $2359.51 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.612, kelly=0.326) with $1335.35 allocation
[PORT] Sector Technology: selecting FB (p_up=0.580, kelly=0.274) with $1122.69 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.749, kelly=0.507) with $2079.35 allocation
[SIM] 2017-06-16 00:00:00: 9 trades proposed.
[TRADE] 2017-06-16 00:00:00: allocated $4085.43 to JPM exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $2359.51 to MMM exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $2079.35 to NEE exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $1369.04 to IEP exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $379.00 to CHTR exiting on 2017-06-23 00:00:00
[EXIT] 2017-06-19 00:00:00: EXC r=0.0099, PnL=$41.51
[EXIT] 2017-06-19 00:00:00: PG r=0.0184, PnL=$64.97
[EXIT] 2017-06-19 00:00:00: BABA r=0.0028, PnL=$9.48
[EXIT] 2017-06-19 00:00:00: GMRE r=0.0222, PnL=$75.47
[EXIT] 2017-06-19 00:00:00: GD r=0.0308, PnL=$99.68
[EXIT] 2017-06-19 00:00:00: TOT r=-0.0170, PnL=$-42.04
[EXIT] 2017-06-19 00:00:00: CELG r=0.0487, PnL=$74.28

Simulating Trading Days:  52%|█████▏    | 56/108 [15:46<01:19,  1.52s/it]

[SIM] 2017-06-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.773, kelly=0.525) with $2772.47 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.621, kelly=0.333) with $1758.04 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.835, kelly=0.671) with $3541.41 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.997, kelly=0.994) with $5247.58 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.474, kelly=0.058) with $306.82 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.784, kelly=0.588) with $3103.01 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.709, kelly=0.442) with $2333.71 allocation
[PORT] Sector Technology: selecting FB (p_up=0.581, kelly=0.276) with $1457.71 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.745, kelly=0.499) with $2632.84 allocation
[SIM] 2017-06-19 00:00:00: 9 trades proposed.
[TRADE] 2017-06-19 00:00:00: allocated $5247.58 to JPM exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $3541.41 to PG exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $3103.01 to MMM exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $2772.47 to TOT exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $2632.84 to NEE exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $2333.71 to PCLN exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $1457.71 to FB exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $306.82 to CELG exiting on 2017-06-26 00:00:00
[EXIT] 2017-06-20 00:00:00: EXC r=0.0093, PnL=$29.94
[EXIT] 2017-06-20 00:00:00: PG r=0.0178, PnL=$53.20
[EXIT] 2017-06-20 00:00:00: BABA r=0.0130, PnL=$34.41
[EXIT] 2017-06-20 00:00:00: GD r=0.0165, PnL=$41.96

Simulating Trading Days:  53%|█████▎    | 57/108 [15:48<01:18,  1.53s/it]

[SIM] 2017-06-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.756, kelly=0.489) with $2103.02 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.614, kelly=0.322) with $1383.88 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.803, kelly=0.606) with $2603.81 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.995, kelly=0.990) with $4251.34 allocation
[PORT] Sector Healthcare: Kelly <= 0 for CELG (p_up=0.412, b=1.266).
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.789, kelly=0.598) with $2569.98 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.744, kelly=0.510) with $2189.43 allocation
[PORT] Sector Technology: selecting FB (p_up=0.578, kelly=0.271) with $1163.22 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.737, kelly=0.483) with $2073.61 allocation
[SIM] 2017-06-20 00:00:00: 8 trades proposed.
[TRADE] 2017-06-20 00:00:00: allocated $4251.34 to JPM exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $2603.81 to PG exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $2569.98 to MMM exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $2189.43 to PCLN exiting on 2017-06-27 00:00:00
[EXIT] 2017-06-21 00:00:00: PG r=0.0109, PnL=$39.93
[EXIT] 2017-06-21 00:00:00: EXC r=-0.0005, PnL=$-1.91
[EXIT] 2017-06-21 00:00:00: GD r=0.0130, PnL=$39.07
[EXIT] 2017-06-21 00:00:00: TOT r=-0.0188, PnL=$-47.68
[EXIT] 2017-06-21 00:00:00: V r=-0.0082, PnL=$-16.32
[EXIT] 2017-06-21 00:00:00: IEP r=0.0137, PnL=$22.00
[EXIT] 2017-06-21 00:00:00: CELG r=0.0974, PnL=$146.22
[EXIT] 2017-06-21 00:00:00: FB r=0.0244, PnL=$30.84

Simulating Trading Days:  54%|█████▎    | 58/108 [15:49<01:15,  1.52s/it]

[SIM] 2017-06-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 67 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.734, kelly=0.445) with $2252.94 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.604, kelly=0.304) with $1540.92 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.893, kelly=0.799) with $4049.93 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.993, kelly=0.986) with $4992.63 allocation
[PORT] Sector Healthcare: Kelly <= 0 for CELG (p_up=0.359, b=1.266).
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.796, kelly=0.611) with $3095.09 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.774, kelly=0.566) with $2866.97 allocation
[PORT] Sector Technology: selecting FB (p_up=0.573, kelly=0.261) with $1324.01 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.730, kelly=0.470) with $2380.75 allocation
[SIM] 2017-06-21 00:00:00: 8 trades proposed.
[TRADE] 2017-06-21 00:00:00: allocated $4049.93 to TM exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $2866.97 to PCLN exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $2252.94 to TOT exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $1540.92 to IEP exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $1324.01 to FB exiting on 2017-06-28 00:00:00
[EXIT] 2017-06-22 00:00:00: TOT r=-0.0044, PnL=$-9.74
[EXIT] 2017-06-22 00:00:00: NEE r=-0.0020, PnL=$-4.15
[EXIT] 2017-06-22 00:00:00: V r=-0.0023, PnL=$-3.74
[EXIT] 2017-06-22 00:00:00: IEP r=0.0072, PnL=$10.05
[EXIT] 2017-06-22 00:00:00: FB r=0.0240, PnL=$26.98
[EXIT] 2017-06-22 00:00:00: CELG r=0.1084, PnL=$86.94

Simulating Trading Days:  55%|█████▍    | 59/108 [15:51<01:13,  1.50s/it]

[SIM] 2017-06-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.737, kelly=0.452) with $2164.88 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.592, kelly=0.283) with $1357.89 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.918, kelly=0.848) with $4064.40 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.991, kelly=0.982) with $4707.05 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.575, kelly=0.196) with $938.14 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.805, kelly=0.629) with $3014.91 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.794, kelly=0.606) with $2905.71 allocation
[PORT] Sector Technology: selecting FB (p_up=0.565, kelly=0.248) with $1186.65 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.725, kelly=0.461) with $2208.15 allocation
[SIM] 2017-06-22 00:00:00: 9 trades proposed.
[TRADE] 2017-06-22 00:00:00: allocated $4064.40 to TM exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $2164.88 to TOT exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $2208.15 to NEE exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $1357.89 to IEP exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $938.14 to AMGN exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $1186.65 to FB exiting on 2017-06-29 00:00:00
[EXIT] 2017-06-23 00:00:00: JPM r=0.0079, PnL=$32.24
[EXIT] 2017-06-23 00:00:00: MMM r=-0.0016, PnL=$-3.76
[EXIT] 2017-06-23 00:00:00: NEE r=0.0021, PnL=$4.37
[EXIT] 2017-06-23 00:00:00: IEP r=-0.0148, PnL=$-20.20
[EXIT] 2017-06-23 00:00:00: CHTR r=-0.0277, PnL=$-10.49

Simulating Trading Days:  56%|█████▌    | 60/108 [15:52<01:11,  1.49s/it]

[SIM] 2017-06-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.761, kelly=0.501) with $2320.57 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.581, kelly=0.263) with $1216.17 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.923, kelly=0.857) with $3966.12 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.988, kelly=0.977) with $4524.88 allocation
[PORT] Sector Healthcare: selecting ABBV (p_up=0.547, kelly=0.114) with $526.91 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.815, kelly=0.648) with $3001.81 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.807, kelly=0.630) with $2916.96 allocation
[PORT] Sector Technology: selecting FB (p_up=0.559, kelly=0.237) with $1096.30 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.726, kelly=0.462) with $2139.39 allocation
[SIM] 2017-06-23 00:00:00: 9 trades proposed.
[TRADE] 2017-06-23 00:00:00: allocated $4524.88 to JPM exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $3966.12 to TM exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $3001.81 to MMM exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $2139.39 to NEE exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $1216.17 to IEP exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $471.00 to ABBV exiting on 2017-06-30 00:00:00
[EXIT] 2017-06-26 00:00:00: JPM r=-0.0094, PnL=$-49.46
[EXIT] 2017-06-26 00:00:00: PG r=-0.0056, PnL=$-19.71
[EXIT] 2017-06-26 00:00:00: MMM r=-0.0035, PnL=$-10.91
[EXIT] 2017-06-26 00:00:00: TOT r=-0.0221, PnL=$-61.22
[EXIT] 2017-06-26 00:00:00: NEE r=0.0129, PnL=$34.02
[EXIT] 2017-06-26 00:00:00: PCLN r=0.0134, PnL=$31.18
[EXIT] 2017-06-26 00:00:00: FB r=0.0047, PnL=$6.87
[EXIT] 2017-06-26 00:00:00: CELG r=0.0694, PnL=$21.30

Simulating Trading Days:  56%|█████▋    | 61/108 [15:54<01:08,  1.47s/it]

[SIM] 2017-06-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 67 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.790, kelly=0.562) with $2938.93 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.572, kelly=0.248) with $1297.81 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.911, kelly=0.834) with $4363.56 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.985, kelly=0.972) with $5083.82 allocation
[PORT] Sector Healthcare: selecting ABBV (p_up=0.537, kelly=0.095) with $497.53 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.823, kelly=0.663) with $3470.45 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.813, kelly=0.641) with $3355.05 allocation
[PORT] Sector Technology: selecting FB (p_up=0.552, kelly=0.225) with $1179.41 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.805, kelly=0.600) with $3137.30 allocation
[SIM] 2017-06-26 00:00:00: 9 trades proposed.
[TRADE] 2017-06-26 00:00:00: allocated $5083.82 to JPM exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $3470.45 to MMM exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $3355.05 to PCLN exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $3137.30 to PPL exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $2938.93 to TOT exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $1179.41 to FB exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $497.53 to ABBV exiting on 2017-07-03 00:00:00
[EXIT] 2017-06-27 00:00:00: JPM r=0.0061, PnL=$25.75
[EXIT] 2017-06-27 00:00:00: PG r=-0.0114, PnL=$-29.63
[EXIT] 2017-06-27 00:00:00: MMM r=-0.0168, PnL=$-43.12
[EXIT] 2017-06-27 00:00:00: PCLN r=0.0041, PnL=$9.00

Simulating Trading Days:  57%|█████▋    | 62/108 [15:55<01:06,  1.45s/it]

[SIM] 2017-06-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.810, kelly=0.603) with $2666.87 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.822, kelly=0.672) with $2975.00 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.881, kelly=0.777) with $3438.31 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.981, kelly=0.963) with $4262.29 allocation
[PORT] Sector Healthcare: selecting MDT (p_up=0.544, kelly=0.118) with $520.25 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.827, kelly=0.671) with $2968.94 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.816, kelly=0.648) with $2865.86 allocation
[PORT] Sector Technology: selecting FB (p_up=0.549, kelly=0.219) with $970.49 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.839, kelly=0.670) with $2963.43 allocation
[SIM] 2017-06-27 00:00:00: 9 trades proposed.
[TRADE] 2017-06-27 00:00:00: allocated $4262.29 to JPM exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $2963.43 to PPL exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $2968.94 to MMM exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $2975.00 to GMRE exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $117.83 to PCLN exiting on 2017-07-05 00:00:00
[EXIT] 2017-06-28 00:00:00: TM r=0.0072, PnL=$29.05
[EXIT] 2017-06-28 00:00:00: PCLN r=0.0120, PnL=$34.43
[EXIT] 2017-06-28 00:00:00: TOT r=0.0186, PnL=$41.91
[EXIT] 2017-06-28 00:00:00: IEP r=0.0143, PnL=$22.02
[EXIT] 2017-06-28 00:00:00: FB r=-0.0044, PnL=$-5.76

Simulating Trading Days:  58%|█████▊    | 63/108 [15:57<01:05,  1.45s/it]

[SIM] 2017-06-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 68 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.811, kelly=0.604) with $2605.63 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.852, kelly=0.728) with $3136.41 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.773, kelly=0.546) with $2353.82 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.978, kelly=0.957) with $4124.74 allocation
[PORT] Sector Healthcare: Kelly <= 0 for CELG (p_up=0.384, b=1.266).
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.833, kelly=0.682) with $2942.02 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.820, kelly=0.655) with $2824.66 allocation
[PORT] Sector Technology: selecting FB (p_up=0.551, kelly=0.224) with $964.34 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.844, kelly=0.680) with $2930.41 allocation
[SIM] 2017-06-28 00:00:00: 8 trades proposed.
[TRADE] 2017-06-28 00:00:00: allocated $3136.41 to GMRE exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $2930.41 to PPL exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $2824.66 to PCLN exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $2605.63 to TOT exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $622.81 to PG exiting on 2017-07-06 00:00:00
[EXIT] 2017-06-29 00:00:00: TM r=-0.0109, PnL=$-44.31
[EXIT] 2017-06-29 00:00:00: TOT r=0.0107, PnL=$23.26
[EXIT] 2017-06-29 00:00:00: NEE r=-0.0114, PnL=$-25.26
[EXIT] 2017-06-29 00:00:00: IEP r=0.0163, PnL=$22.15
[EXIT] 2017-06-29 00:00:00: AMGN r=-0.0071, PnL=$-6.64
[EXIT] 2017-06-29 00:00:00: FB r=-0.0154, PnL=$-18.26

Simulating Trading Days:  59%|█████▉    | 64/108 [15:58<01:04,  1.47s/it]

[SIM] 2017-06-29 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.798, kelly=0.579) with $2479.54 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.842, kelly=0.710) with $3044.22 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.777, kelly=0.554) with $2376.16 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.977, kelly=0.956) with $4096.67 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.477, kelly=0.063) with $270.84 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.833, kelly=0.682) with $2921.80 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.818, kelly=0.650) with $2786.82 allocation
[PORT] Sector Technology: selecting FB (p_up=0.555, kelly=0.230) with $986.45 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.849, kelly=0.691) with $2959.99 allocation
[SIM] 2017-06-29 00:00:00: 9 trades proposed.
[TRADE] 2017-06-29 00:00:00: allocated $3044.22 to GMRE exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $2479.54 to TOT exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $2376.16 to PG exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $986.45 to FB exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $270.84 to CELG exiting on 2017-07-07 00:00:00
[EXIT] 2017-06-30 00:00:00: JPM r=0.0523, PnL=$236.51
[EXIT] 2017-06-30 00:00:00: TM r=-0.0021, PnL=$-8.29
[EXIT] 2017-06-30 00:00:00: MMM r=-0.0221, PnL=$-66.41
[EXIT] 2017-06-30 00:00:00: NEE r=-0.0210, PnL=$-44.99
[EXIT] 2017-06-30 00:00:00: IEP r=0.0181, PnL=$22.05
[EXIT] 2017-06-30 00:00:00: ABBV r=-0.0018, PnL=$-0.84

Simulating Trading Days:  60%|██████    | 65/108 [15:59<01:03,  1.47s/it]

[SIM] 2017-06-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 66 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.792, kelly=0.566) with $2783.81 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.802, kelly=0.636) with $3128.09 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.784, kelly=0.568) with $2793.42 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.980, kelly=0.961) with $4723.79 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.581, kelly=0.250) with $1229.22 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.832, kelly=0.680) with $3342.76 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.811, kelly=0.637) with $3131.79 allocation
[PORT] Sector Technology: selecting FB (p_up=0.561, kelly=0.241) with $1183.82 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.880, kelly=0.755) with $3712.38 allocation
[SIM] 2017-06-30 00:00:00: 9 trades proposed.
[TRADE] 2017-06-30 00:00:00: allocated $4723.79 to JPM exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $3342.76 to MMM exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $2793.42 to PG exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $1229.22 to CELG exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $1183.82 to FB exiting on 2017-07-10 00:00:00
[EXIT] 2017-07-03 00:00:00: JPM r=0.0632, PnL=$321.09
[EXIT] 2017-07-03 00:00:00: MMM r=-0.0131, PnL=$-45.38
[EXIT] 2017-07-03 00:00:00: PCLN r=-0.0177, PnL=$-59.38
[EXIT] 2017-07-03 00:00:00: PPL r=-0.0257, PnL=$-80.65
[EXIT] 2017-07-03 00:00:00: TOT r=0.0191, PnL=$56.20
[EXIT] 2017-07-03 00:00:00: FB r=-0.0336, PnL=$-39.62
[EXIT] 2017-07-03 00:00:00: ABBV r=-0.0044, PnL=$-2.19

Simulating Trading Days:  61%|██████    | 66/108 [16:01<01:03,  1.51s/it]

[SIM] 2017-07-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.817, kelly=0.617) with $3437.27 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.569, kelly=0.243) with $1352.91 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.789, kelly=0.578) with $3220.57 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.982, kelly=0.965) with $5375.51 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.680, kelly=0.427) with $2375.82 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.824, kelly=0.665) with $3701.43 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.801, kelly=0.619) with $3447.36 allocation
[PORT] Sector Technology: selecting FB (p_up=0.567, kelly=0.251) with $1397.11 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.892, kelly=0.778) with $4332.46 allocation
[SIM] 2017-07-03 00:00:00: 9 trades proposed.
[TRADE] 2017-07-03 00:00:00: allocated $5375.51 to JPM exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $4332.46 to PPL exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $3701.43 to MMM exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $3437.27 to TOT exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $3447.36 to PCLN exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $2375.82 to CELG exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $1352.91 to IEP exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $616.33 to FB exiting on 2017-07-11 00:00:00
[EXIT] 2017-07-05 00:00:00: JPM r=0.0639, PnL=$272.53
[EXIT] 2017-07-05 00:00:00: PPL r=-0.0187, PnL=$-55.44
[EXIT] 2017-07-05 00:00:00: MMM r=-0.0001, PnL=$-0.28
[EXIT] 2017-07-05 00:00:00: GMRE r=-0.1099, PnL=$-326.86
[EXIT] 2017-07-05 00:00:00: PCLN r=0.0042, PnL=$0.49

Simulating Trading Days:  62%|██████▏   | 67/108 [16:02<01:00,  1.47s/it]

[SIM] 2017-07-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.843, kelly=0.671) with $2970.46 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.569, kelly=0.242) with $1072.05 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.770, kelly=0.540) with $2387.87 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.983, kelly=0.967) with $4275.88 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.748, kelly=0.549) with $2429.22 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.810, kelly=0.637) with $2819.91 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.790, kelly=0.597) with $2640.62 allocation
[PORT] Sector Technology: selecting FB (p_up=0.575, kelly=0.265) with $1174.27 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.891, kelly=0.777) with $3435.34 allocation
[SIM] 2017-07-05 00:00:00: 9 trades proposed.
[TRADE] 2017-07-05 00:00:00: allocated $4275.88 to JPM exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $3435.34 to PPL exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $2819.91 to MMM exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $2640.62 to PCLN exiting on 2017-07-12 00:00:00
[EXIT] 2017-07-06 00:00:00: GMRE r=-0.0090, PnL=$-28.35
[EXIT] 2017-07-06 00:00:00: PPL r=-0.0209, PnL=$-61.11
[EXIT] 2017-07-06 00:00:00: PCLN r=-0.0095, PnL=$-26.76
[EXIT] 2017-07-06 00:00:00: TOT r=-0.0298, PnL=$-77.58
[EXIT] 2017-07-06 00:00:00: PG r=-0.0113, PnL=$-7.05

Simulating Trading Days:  63%|██████▎   | 68/108 [16:04<00:58,  1.47s/it]

[SIM] 2017-07-06 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.872, kelly=0.733) with $3153.00 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.568, kelly=0.240) with $1031.81 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.777, kelly=0.547) with $2349.79 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.982, kelly=0.966) with $4151.38 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.712, kelly=0.485) with $2083.56 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.794, kelly=0.608) with $2611.71 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.776, kelly=0.570) with $2449.93 allocation
[PORT] Sector Technology: selecting FB (p_up=0.583, kelly=0.278) with $1195.89 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.886, kelly=0.766) with $3294.12 allocation
[SIM] 2017-07-06 00:00:00: 9 trades proposed.
[TRADE] 2017-07-06 00:00:00: allocated $3294.12 to PPL exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $3153.00 to TOT exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $2349.79 to UL exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $2449.93 to PCLN exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $771.52 to IEP exiting on 2017-07-13 00:00:00
[EXIT] 2017-07-07 00:00:00: GMRE r=-0.0156, PnL=$-47.41
[EXIT] 2017-07-07 00:00:00: TOT r=-0.0283, PnL=$-70.12
[EXIT] 2017-07-07 00:00:00: PG r=0.0076, PnL=$18.03
[EXIT] 2017-07-07 00:00:00: FB r=0.0026, PnL=$2.61
[EXIT] 2017-07-07 00:00:00: CELG r=0.0065, PnL=$1.77

Simulating Trading Days:  64%|██████▍   | 69/108 [16:05<00:56,  1.46s/it]

[SIM] 2017-07-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.893, kelly=0.776) with $3107.08 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.566, kelly=0.237) with $947.64 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.764, kelly=0.519) with $2077.34 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.979, kelly=0.959) with $3839.24 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.649, kelly=0.372) with $1488.87 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.782, kelly=0.584) with $2339.70 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.761, kelly=0.542) with $2170.66 allocation
[PORT] Sector Technology: selecting FB (p_up=0.588, kelly=0.288) with $1153.35 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.871, kelly=0.735) with $2943.47 allocation
[SIM] 2017-07-07 00:00:00: 9 trades proposed.
[TRADE] 2017-07-07 00:00:00: allocated $3107.08 to TOT exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $2077.34 to UL exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $1488.87 to CELG exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $1153.35 to FB exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $947.64 to IEP exiting on 2017-07-14 00:00:00
[EXIT] 2017-07-10 00:00:00: JPM r=0.0196, PnL=$92.51
[EXIT] 2017-07-10 00:00:00: MMM r=0.0110, PnL=$36.93
[EXIT] 2017-07-10 00:00:00: PG r=-0.0007, PnL=$-1.92
[EXIT] 2017-07-10 00:00:00: CELG r=0.0159, PnL=$19.50
[EXIT] 2017-07-10 00:00:00: FB r=0.0167, PnL=$19.76

Simulating Trading Days:  65%|██████▍   | 70/108 [16:07<00:55,  1.47s/it]

[SIM] 2017-07-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.912, kelly=0.816) with $3644.97 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.567, kelly=0.238) with $1064.55 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.754, kelly=0.499) with $2231.38 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.972, kelly=0.945) with $4225.46 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.569, kelly=0.229) with $1023.13 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.771, kelly=0.563) with $2516.87 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.750, kelly=0.521) with $2327.88 allocation
[PORT] Sector Technology: selecting FB (p_up=0.588, kelly=0.288) with $1287.32 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.856, kelly=0.706) with $3154.11 allocation
[SIM] 2017-07-10 00:00:00: 9 trades proposed.
[TRADE] 2017-07-10 00:00:00: allocated $4225.46 to JPM exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $2516.87 to MMM exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $2231.38 to UL exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $1287.32 to FB exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $1023.13 to CELG exiting on 2017-07-17 00:00:00
[EXIT] 2017-07-11 00:00:00: JPM r=0.0009, PnL=$4.64
[EXIT] 2017-07-11 00:00:00: PPL r=-0.0136, PnL=$-58.85
[EXIT] 2017-07-11 00:00:00: MMM r=-0.0008, PnL=$-3.00
[EXIT] 2017-07-11 00:00:00: TOT r=-0.0216, PnL=$-74.10
[EXIT] 2017-07-11 00:00:00: PCLN r=0.0467, PnL=$160.89
[EXIT] 2017-07-11 00:00:00: CELG r=0.0159, PnL=$37.78
[EXIT] 2017-07-11 00:00:00: IEP r=0.0031, PnL=$4.24
[EXIT] 2017-07-11 00:00:00: FB r=0.0461, PnL=$28.40

Simulating Trading Days:  66%|██████▌   | 71/108 [16:08<00:54,  1.47s/it]

[SIM] 2017-07-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.915, kelly=0.823) with $4787.65 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.570, kelly=0.244) with $1417.58 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.751, kelly=0.493) with $2869.62 allocation
[PORT] Sector Financial: selecting V (p_up=0.629, kelly=0.317) with $1842.14 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.525, kelly=0.150) with $871.28 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.761, kelly=0.544) with $3164.28 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.744, kelly=0.509) with $2959.85 allocation
[PORT] Sector Technology: selecting FB (p_up=0.583, kelly=0.279) with $1622.50 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.847, kelly=0.686) with $3987.03 allocation
[SIM] 2017-07-11 00:00:00: 9 trades proposed.
[TRADE] 2017-07-11 00:00:00: allocated $4787.65 to TOT exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $3987.03 to PPL exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $3164.28 to MMM exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $2959.85 to PCLN exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $1842.14 to V exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $1622.50 to FB exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $1417.58 to IEP exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $871.28 to CELG exiting on 2017-07-18 00:00:00
[EXIT] 2017-07-12 00:00:00: JPM r=-0.0125, PnL=$-53.40
[EXIT] 2017-07-12 00:00:00: PPL r=-0.0128, PnL=$-43.96
[EXIT] 2017-07-12 00:00:00: MMM r=0.0073, PnL=$20.70
[EXIT] 2017-07-12 00:00:00: PCLN r=0.0430, PnL=$113.45

Simulating Trading Days:  67%|██████▋   | 72/108 [16:10<00:53,  1.48s/it]

[SIM] 2017-07-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.907, kelly=0.806) with $4085.86 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.576, kelly=0.254) with $1287.66 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.752, kelly=0.495) with $2508.63 allocation
[PORT] Sector Financial: selecting V (p_up=0.631, kelly=0.320) with $1623.31 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.505, kelly=0.115) with $582.81 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.754, kelly=0.531) with $2691.04 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.740, kelly=0.502) with $2543.82 allocation
[PORT] Sector Technology: selecting FB (p_up=0.572, kelly=0.260) with $1320.23 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.853, kelly=0.699) with $3544.35 allocation
[SIM] 2017-07-12 00:00:00: 9 trades proposed.
[TRADE] 2017-07-12 00:00:00: allocated $3544.35 to PPL exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $2691.04 to MMM exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $2543.82 to PCLN exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $1623.31 to V exiting on 2017-07-19 00:00:00
[EXIT] 2017-07-13 00:00:00: PPL r=-0.0155, PnL=$-51.11
[EXIT] 2017-07-13 00:00:00: TOT r=0.0072, PnL=$22.58
[EXIT] 2017-07-13 00:00:00: UL r=0.0340, PnL=$79.98
[EXIT] 2017-07-13 00:00:00: PCLN r=0.0365, PnL=$89.50
[EXIT] 2017-07-13 00:00:00: IEP r=0.0221, PnL=$17.02

Simulating Trading Days:  68%|██████▊   | 73/108 [16:11<00:52,  1.49s/it]

[SIM] 2017-07-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.891, kelly=0.771) with $4048.30 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.583, kelly=0.266) with $1397.06 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.757, kelly=0.506) with $2656.11 allocation
[PORT] Sector Financial: selecting V (p_up=0.630, kelly=0.319) with $1672.02 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.488, kelly=0.083) with $438.15 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.747, kelly=0.518) with $2718.44 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.739, kelly=0.500) with $2625.09 allocation
[PORT] Sector Technology: selecting FB (p_up=0.559, kelly=0.237) with $1243.66 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.861, kelly=0.715) with $3750.38 allocation
[SIM] 2017-07-13 00:00:00: 9 trades proposed.
[TRADE] 2017-07-13 00:00:00: allocated $4048.30 to TOT exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $3750.38 to PPL exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $2656.11 to UL exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $2625.09 to PCLN exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $1672.02 to V exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $1397.06 to IEP exiting on 2017-07-20 00:00:00
[EXIT] 2017-07-14 00:00:00: TOT r=0.0250, PnL=$77.60
[EXIT] 2017-07-14 00:00:00: UL r=0.0410, PnL=$85.07
[EXIT] 2017-07-14 00:00:00: CELG r=0.0152, PnL=$22.58
[EXIT] 2017-07-14 00:00:00: FB r=0.0563, PnL=$64.96
[EXIT] 2017-07-14 00:00:00: IEP r=0.0127, PnL=$11.99

Simulating Trading Days:  69%|██████▊   | 74/108 [16:13<00:49,  1.47s/it]

[SIM] 2017-07-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.868, kelly=0.725) with $3289.65 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.592, kelly=0.283) with $1281.78 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.765, kelly=0.521) with $2365.21 allocation
[PORT] Sector Financial: selecting V (p_up=0.627, kelly=0.313) with $1419.87 allocation
[PORT] Sector Healthcare: allocation $96.72 below minimum; skipping CELG.
[PORT] Sector Industrial Goods: selecting GD (p_up=0.693, kelly=0.433) with $1963.21 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.738, kelly=0.498) with $2260.61 allocation
[PORT] Sector Technology: selecting FB (p_up=0.547, kelly=0.216) with $978.88 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.822, kelly=0.636) with $2884.42 allocation
[SIM] 2017-07-14 00:00:00: 8 trades proposed.
[TRADE] 2017-07-14 00:00:00: allocated $3289.65 to TOT exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $2365.21 to UL exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $1963.21 to GD exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $1281.78 to IEP exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $978.88 to FB exiting on 2017-07-21 00:00:00
[EXIT] 2017-07-17 00:00:00: JPM r=-0.0193, PnL=$-81.62
[EXIT] 2017-07-17 00:00:00: MMM r=0.0057, PnL=$14.23
[EXIT] 2017-07-17 00:00:00: UL r=0.0337, PnL=$75.18
[EXIT] 2017-07-17 00:00:00: FB r=0.0406, PnL=$52.25
[EXIT] 2017-07-17 00:00:00: CELG r=0.0223, PnL=$22.80

Simulating Trading Days:  69%|██████▉   | 75/108 [16:14<00:48,  1.47s/it]

[SIM] 2017-07-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.849, kelly=0.685) with $3208.96 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.603, kelly=0.301) with $1412.09 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.773, kelly=0.537) with $2515.86 allocation
[PORT] Sector Financial: selecting V (p_up=0.623, kelly=0.305) with $1428.60 allocation
[PORT] Sector Healthcare: Kelly <= 0 for CELG (p_up=0.436, b=1.266).
[PORT] Sector Industrial Goods: selecting GD (p_up=0.687, kelly=0.421) with $1972.65 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.736, kelly=0.494) with $2316.13 allocation
[PORT] Sector Technology: selecting FB (p_up=0.536, kelly=0.198) with $927.75 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.817, kelly=0.626) with $2931.66 allocation
[SIM] 2017-07-17 00:00:00: 8 trades proposed.
[TRADE] 2017-07-17 00:00:00: allocated $2515.86 to UL exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $1972.65 to GD exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $927.75 to FB exiting on 2017-07-24 00:00:00
[EXIT] 2017-07-18 00:00:00: TOT r=0.0135, PnL=$64.46
[EXIT] 2017-07-18 00:00:00: PPL r=-0.0019, PnL=$-7.39
[EXIT] 2017-07-18 00:00:00: MMM r=0.0079, PnL=$24.90
[EXIT] 2017-07-18 00:00:00: PCLN r=0.0244, PnL=$72.25
[EXIT] 2017-07-18 00:00:00: V r=0.0227, PnL=$41.90
[EXIT] 2017-07-18 00:00:00: FB r=0.0489, PnL=$79.31
[EXIT] 2017-07-18 00:00:00: IEP r=0.0194, PnL=$27.43
[EXIT] 2017-07-18 00:00:00: CELG r=0.0153, PnL=$13.31

Simulating Trading Days:  70%|███████   | 76/108 [16:16<00:48,  1.50s/it]

[SIM] 2017-07-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.845, kelly=0.677) with $4225.01 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.614, kelly=0.321) with $2005.19 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.778, kelly=0.548) with $3420.09 allocation
[PORT] Sector Financial: selecting V (p_up=0.622, kelly=0.304) with $1899.04 allocation
[PORT] Sector Healthcare: Kelly <= 0 for CELG (p_up=0.435, b=1.266).
[PORT] Sector Industrial Goods: selecting GD (p_up=0.693, kelly=0.432) with $2698.35 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.665, kelly=0.370) with $2310.02 allocation
[PORT] Sector Technology: selecting FB (p_up=0.530, kelly=0.187) with $1164.72 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.773, kelly=0.536) with $3343.37 allocation
[SIM] 2017-07-18 00:00:00: 8 trades proposed.
[TRADE] 2017-07-18 00:00:00: allocated $4225.01 to TOT exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $3343.37 to PPL exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $2698.35 to GD exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $2310.02 to AMZN exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $1899.04 to V exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $2005.19 to IEP exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $1164.72 to FB exiting on 2017-07-25 00:00:00
[EXIT] 2017-07-19 00:00:00: PPL r=0.0085, PnL=$30.01
[EXIT] 2017-07-19 00:00:00: MMM r=0.0038, PnL=$10.19
[EXIT] 2017-07-19 00:00:00: PCLN r=0.0236, PnL=$60.02
[EXIT] 2017-07-19 00:00:00: V r=0.0215, PnL=$34.94

Simulating Trading Days:  71%|███████▏  | 77/108 [16:17<00:45,  1.48s/it]

[SIM] 2017-07-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.855, kelly=0.697) with $3854.76 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.788, kelly=0.611) with $3378.71 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.780, kelly=0.552) with $3053.75 allocation
[PORT] Sector Financial: selecting V (p_up=0.628, kelly=0.314) with $1735.08 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.482, kelly=0.072) with $399.74 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.698, kelly=0.442) with $2445.82 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.700, kelly=0.437) with $2417.04 allocation
[PORT] Sector Technology: selecting FB (p_up=0.525, kelly=0.178) with $986.79 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.746, kelly=0.480) with $2652.30 allocation
[SIM] 2017-07-19 00:00:00: 9 trades proposed.
[TRADE] 2017-07-19 00:00:00: allocated $3378.71 to GMRE exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $2652.30 to PPL exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $2417.04 to AMZN exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $1735.08 to V exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $399.74 to CELG exiting on 2017-07-26 00:00:00
[EXIT] 2017-07-20 00:00:00: TOT r=0.0228, PnL=$92.10
[EXIT] 2017-07-20 00:00:00: PPL r=0.0214, PnL=$80.14
[EXIT] 2017-07-20 00:00:00: UL r=0.0284, PnL=$75.42
[EXIT] 2017-07-20 00:00:00: PCLN r=0.0302, PnL=$79.16
[EXIT] 2017-07-20 00:00:00: V r=0.0226, PnL=$37.82
[EXIT] 2017-07-20 00:00:00: IEP r=0.0212, PnL=$29.61

Simulating Trading Days:  72%|███████▏  | 78/108 [16:19<00:43,  1.46s/it]

[SIM] 2017-07-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.868, kelly=0.725) with $4440.15 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.628, kelly=0.347) with $2124.37 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.786, kelly=0.559) with $3426.36 allocation
[PORT] Sector Financial: selecting V (p_up=0.643, kelly=0.342) with $2097.85 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.505, kelly=0.115) with $703.18 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.705, kelly=0.456) with $2791.84 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.730, kelly=0.494) with $3023.65 allocation
[PORT] Sector Technology: selecting FB (p_up=0.522, kelly=0.172) with $1056.60 allocation
[PORT] Sector Utilities: selecting PPL (p_up=0.704, kelly=0.393) with $2409.75 allocation
[SIM] 2017-07-20 00:00:00: 9 trades proposed.
[TRADE] 2017-07-20 00:00:00: allocated $4440.15 to TOT exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $3426.36 to PM exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $3023.65 to AMZN exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $2409.75 to PPL exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $2097.85 to V exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $2124.37 to IEP exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $703.18 to CELG exiting on 2017-07-27 00:00:00
[EXIT] 2017-07-21 00:00:00: TOT r=-0.0008, PnL=$-2.65
[EXIT] 2017-07-21 00:00:00: UL r=0.0209, PnL=$49.49
[EXIT] 2017-07-21 00:00:00: GD r=0.0169, PnL=$33.18
[EXIT] 2017-07-21 00:00:00: IEP r=0.0234, PnL=$30.06
[EXIT] 2017-07-21 00:00:00: FB r=0.0279, PnL=$27.29

Simulating Trading Days:  73%|███████▎  | 79/108 [16:20<00:41,  1.44s/it]

[SIM] 2017-07-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.883, kelly=0.755) with $4005.21 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.630, kelly=0.350) with $1856.50 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.822, kelly=0.633) with $3358.47 allocation
[PORT] Sector Financial: selecting V (p_up=0.662, kelly=0.377) with $2002.28 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.506, kelly=0.117) with $618.82 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.711, kelly=0.466) with $2470.59 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.755, kelly=0.540) with $2865.52 allocation
[PORT] Sector Technology: selecting FB (p_up=0.520, kelly=0.169) with $895.54 allocation
[PORT] Sector Utilities: selecting D (p_up=0.736, kelly=0.474) with $2512.74 allocation
[SIM] 2017-07-21 00:00:00: 9 trades proposed.
[TRADE] 2017-07-21 00:00:00: allocated $4005.21 to TOT exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $3358.47 to PM exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $2512.74 to D exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $2470.59 to GD exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $1856.50 to IEP exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $895.54 to FB exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $618.82 to CELG exiting on 2017-07-28 00:00:00
[EXIT] 2017-07-24 00:00:00: UL r=0.0118, PnL=$29.74
[EXIT] 2017-07-24 00:00:00: GD r=0.0239, PnL=$47.21
[EXIT] 2017-07-24 00:00:00: FB r=0.0393, PnL=$36.42

Simulating Trading Days:  74%|███████▍  | 80/108 [16:22<00:40,  1.45s/it]

[SIM] 2017-07-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.897, kelly=0.785) with $3366.04 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.628, kelly=0.346) with $1484.67 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.848, kelly=0.686) with $2939.09 allocation
[PORT] Sector Financial: selecting V (p_up=0.681, kelly=0.412) with $1767.38 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.481, kelly=0.072) with $307.75 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.719, kelly=0.480) with $2056.85 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.772, kelly=0.572) with $2452.27 allocation
[PORT] Sector Technology: selecting FB (p_up=0.518, kelly=0.167) with $715.86 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.856, kelly=0.717) with $3072.37 allocation
[SIM] 2017-07-24 00:00:00: 9 trades proposed.
[TRADE] 2017-07-24 00:00:00: allocated $3072.37 to EXC exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $2939.09 to PM exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $2056.85 to GD exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $715.86 to FB exiting on 2017-07-31 00:00:00
[EXIT] 2017-07-25 00:00:00: TOT r=0.0028, PnL=$11.91
[EXIT] 2017-07-25 00:00:00: PPL r=0.0074, PnL=$24.84
[EXIT] 2017-07-25 00:00:00: GD r=0.0106, PnL=$28.67
[EXIT] 2017-07-25 00:00:00: AMZN r=0.0151, PnL=$34.77
[EXIT] 2017-07-25 00:00:00: V r=0.0247, PnL=$46.90
[EXIT] 2017-07-25 00:00:00: IEP r=0.0228, PnL=$45.76
[EXIT] 2017-07-25 00:00:00: FB r=0.0149, PnL=$17.31

Simulating Trading Days:  75%|███████▌  | 81/108 [16:23<00:39,  1.47s/it]

[SIM] 2017-07-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.908, kelly=0.808) with $4195.68 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.620, kelly=0.332) with $1726.39 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.861, kelly=0.714) with $3707.93 allocation
[PORT] Sector Financial: selecting V (p_up=0.700, kelly=0.446) with $2318.69 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.485, kelly=0.079) with $409.94 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.729, kelly=0.500) with $2595.61 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.785, kelly=0.596) with $3094.01 allocation
[PORT] Sector Technology: selecting FB (p_up=0.517, kelly=0.165) with $858.06 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.904, kelly=0.811) with $4211.08 allocation
[SIM] 2017-07-25 00:00:00: 9 trades proposed.
[TRADE] 2017-07-25 00:00:00: allocated $4195.68 to TOT exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $4211.08 to EXC exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $3094.01 to AMZN exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $2595.61 to GD exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $2318.69 to V exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $1726.39 to IEP exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $858.06 to FB exiting on 2017-08-01 00:00:00
[EXIT] 2017-07-26 00:00:00: GMRE r=-0.0053, PnL=$-18.07
[EXIT] 2017-07-26 00:00:00: PPL r=-0.0008, PnL=$-2.09
[EXIT] 2017-07-26 00:00:00: AMZN r=0.0253, PnL=$61.03
[EXIT] 2017-07-26 00:00:00: V r=0.0265, PnL=$45.92
[EXIT] 2017-07-26 00:00:00: CELG r=0.0204, PnL=$8.14

Simulating Trading Days:  76%|███████▌  | 82/108 [16:24<00:38,  1.46s/it]

[SIM] 2017-07-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.913, kelly=0.819) with $3570.15 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.610, kelly=0.314) with $1370.30 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.866, kelly=0.723) with $3154.74 allocation
[PORT] Sector Financial: selecting V (p_up=0.715, kelly=0.475) with $2070.57 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.583, kelly=0.254) with $1105.74 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.749, kelly=0.536) with $2338.32 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.792, kelly=0.610) with $2658.51 allocation
[PORT] Sector Technology: selecting FB (p_up=0.517, kelly=0.165) with $719.94 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.923, kelly=0.848) with $3699.04 allocation
[SIM] 2017-07-26 00:00:00: 9 trades proposed.
[TRADE] 2017-07-26 00:00:00: allocated $3699.04 to EXC exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $2658.51 to AMZN exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $2070.57 to V exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $1105.74 to CELG exiting on 2017-08-02 00:00:00
[EXIT] 2017-07-27 00:00:00: TOT r=0.0018, PnL=$7.94
[EXIT] 2017-07-27 00:00:00: PM r=-0.0139, PnL=$-47.74
[EXIT] 2017-07-27 00:00:00: AMZN r=0.0168, PnL=$50.85
[EXIT] 2017-07-27 00:00:00: PPL r=-0.0031, PnL=$-7.56
[EXIT] 2017-07-27 00:00:00: V r=0.0149, PnL=$31.22
[EXIT] 2017-07-27 00:00:00: IEP r=0.0023, PnL=$4.81
[EXIT] 2017-07-27 00:00:00: CELG r=-0.0158, PnL=$-11.14

Simulating Trading Days:  77%|███████▋  | 83/108 [16:26<00:37,  1.49s/it]

[SIM] 2017-07-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.908, kelly=0.807) with $4225.38 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.600, kelly=0.296) with $1550.13 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.863, kelly=0.717) with $3750.96 allocation
[PORT] Sector Financial: selecting V (p_up=0.730, kelly=0.502) with $2626.04 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.668, kelly=0.407) with $2127.65 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.792, kelly=0.616) with $3222.56 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.797, kelly=0.618) with $3234.86 allocation
[PORT] Sector Technology: selecting FB (p_up=0.517, kelly=0.165) with $862.15 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.928, kelly=0.859) with $4495.88 allocation
[SIM] 2017-07-27 00:00:00: 9 trades proposed.
[TRADE] 2017-07-27 00:00:00: allocated $4225.38 to TOT exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $3750.96 to PM exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $3234.86 to AMZN exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $2626.04 to V exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $2127.65 to CELG exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $1550.13 to IEP exiting on 2017-08-03 00:00:00
[EXIT] 2017-07-28 00:00:00: TOT r=0.0200, PnL=$79.91
[EXIT] 2017-07-28 00:00:00: PM r=-0.0089, PnL=$-30.05
[EXIT] 2017-07-28 00:00:00: D r=-0.0075, PnL=$-18.79
[EXIT] 2017-07-28 00:00:00: GD r=-0.0323, PnL=$-79.84
[EXIT] 2017-07-28 00:00:00: IEP r=-0.0227, PnL=$-42.19
[EXIT] 2017-07-28 00:00:00: FB r=0.0488, PnL=$43.68
[EXIT] 2017-07-28 00:00:00: CELG r=-0.0264, PnL=$-16.35

Simulating Trading Days:  78%|███████▊  | 84/108 [16:27<00:35,  1.47s/it]

[SIM] 2017-07-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.899, kelly=0.790) with $3987.32 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.587, kelly=0.275) with $1386.89 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.854, kelly=0.698) with $3523.95 allocation
[PORT] Sector Financial: selecting V (p_up=0.739, kelly=0.518) with $2615.35 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.797, kelly=0.636) with $3211.73 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.829, kelly=0.685) with $3455.16 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.798, kelly=0.621) with $3133.07 allocation
[PORT] Sector Technology: selecting FB (p_up=0.514, kelly=0.160) with $805.21 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.927, kelly=0.857) with $4324.68 allocation
[SIM] 2017-07-28 00:00:00: 9 trades proposed.
[TRADE] 2017-07-28 00:00:00: allocated $3987.32 to TOT exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $3523.95 to PM exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $3455.16 to GD exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $3211.73 to CELG exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $1386.89 to IEP exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $805.21 to FB exiting on 2017-08-04 00:00:00
[EXIT] 2017-07-31 00:00:00: EXC r=0.0306, PnL=$94.15
[EXIT] 2017-07-31 00:00:00: PM r=-0.0183, PnL=$-53.89
[EXIT] 2017-07-31 00:00:00: GD r=-0.0420, PnL=$-86.32
[EXIT] 2017-07-31 00:00:00: FB r=0.0196, PnL=$14.02

Simulating Trading Days:  79%|███████▊  | 85/108 [16:29<00:33,  1.45s/it]

[SIM] 2017-07-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.892, kelly=0.774) with $3315.73 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.570, kelly=0.245) with $1049.62 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.842, kelly=0.674) with $2888.40 allocation
[PORT] Sector Financial: selecting V (p_up=0.741, kelly=0.522) with $2238.60 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.847, kelly=0.726) with $3110.69 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.848, kelly=0.719) with $3080.60 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.786, kelly=0.599) with $2566.47 allocation
[PORT] Sector Technology: selecting FB (p_up=0.510, kelly=0.153) with $654.96 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.924, kelly=0.850) with $3641.52 allocation
[SIM] 2017-07-31 00:00:00: 9 trades proposed.
[TRADE] 2017-07-31 00:00:00: allocated $3641.52 to EXC exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $3080.60 to GD exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $2888.40 to PM exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $654.96 to FB exiting on 2017-08-07 00:00:00
[EXIT] 2017-08-01 00:00:00: TOT r=0.0281, PnL=$117.90
[EXIT] 2017-08-01 00:00:00: EXC r=0.0413, PnL=$174.04
[EXIT] 2017-08-01 00:00:00: AMZN r=-0.0420, PnL=$-129.96
[EXIT] 2017-08-01 00:00:00: GD r=-0.0345, PnL=$-89.64
[EXIT] 2017-08-01 00:00:00: V r=0.0088, PnL=$20.41
[EXIT] 2017-08-01 00:00:00: IEP r=-0.0082, PnL=$-14.24
[EXIT] 2017-08-01 00:00:00: FB r=0.0277, PnL=$23.78

Simulating Trading Days:  80%|███████▉  | 86/108 [16:30<00:31,  1.44s/it]

[SIM] 2017-08-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.886, kelly=0.763) with $3943.31 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.555, kelly=0.217) with $1123.85 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.824, kelly=0.637) with $3290.27 allocation
[PORT] Sector Financial: selecting V (p_up=0.738, kelly=0.517) with $2671.87 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.836, kelly=0.706) with $3650.29 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.849, kelly=0.720) with $3722.00 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.759, kelly=0.547) with $2825.67 allocation
[PORT] Sector Technology: selecting FB (p_up=0.510, kelly=0.153) with $790.64 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.921, kelly=0.845) with $4369.73 allocation
[SIM] 2017-08-01 00:00:00: 9 trades proposed.
[TRADE] 2017-08-01 00:00:00: allocated $4369.73 to EXC exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $3943.31 to TOT exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $3722.00 to GD exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $2825.67 to AMZN exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $2671.87 to V exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $1123.85 to IEP exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $790.64 to FB exiting on 2017-08-08 00:00:00
[EXIT] 2017-08-02 00:00:00: EXC r=0.0196, PnL=$72.65
[EXIT] 2017-08-02 00:00:00: AMZN r=-0.0541, PnL=$-143.71
[EXIT] 2017-08-02 00:00:00: V r=0.0043, PnL=$8.83
[EXIT] 2017-08-02 00:00:00: CELG r=-0.0211, PnL=$-23.28

Simulating Trading Days:  81%|████████  | 87/108 [16:32<00:30,  1.45s/it]

[SIM] 2017-08-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.884, kelly=0.757) with $3155.31 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.542, kelly=0.196) with $815.43 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.794, kelly=0.575) with $2397.37 allocation
[PORT] Sector Financial: selecting V (p_up=0.734, kelly=0.509) with $2124.12 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.778, kelly=0.603) with $2513.49 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.835, kelly=0.695) with $2896.00 allocation
[PORT] Sector Services: selecting AMZN (p_up=0.717, kelly=0.468) with $1951.95 allocation
[PORT] Sector Technology: selecting FB (p_up=0.513, kelly=0.158) with $659.25 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.921, kelly=0.844) with $3518.28 allocation
[SIM] 2017-08-02 00:00:00: 9 trades proposed.
[TRADE] 2017-08-02 00:00:00: allocated $3518.28 to EXC exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $2513.49 to CELG exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $2124.12 to V exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $1949.31 to AMZN exiting on 2017-08-09 00:00:00
[EXIT] 2017-08-03 00:00:00: TOT r=0.0200, PnL=$84.61
[EXIT] 2017-08-03 00:00:00: PM r=-0.0313, PnL=$-117.43
[EXIT] 2017-08-03 00:00:00: AMZN r=-0.0565, PnL=$-182.71
[EXIT] 2017-08-03 00:00:00: V r=0.0102, PnL=$26.90
[EXIT] 2017-08-03 00:00:00: CELG r=0.0130, PnL=$27.76
[EXIT] 2017-08-03 00:00:00: IEP r=-0.0218, PnL=$-33.85

Simulating Trading Days:  81%|████████▏ | 88/108 [16:33<00:29,  1.45s/it]

[SIM] 2017-08-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.883, kelly=0.755) with $3691.99 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.534, kelly=0.181) with $886.55 allocation
[PORT] Sector Consumer Goods: selecting PG (p_up=0.786, kelly=0.571) with $2790.43 allocation
[PORT] Sector Financial: selecting V (p_up=0.731, kelly=0.504) with $2462.73 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.705, kelly=0.472) with $2307.82 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.813, kelly=0.654) with $3198.73 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.748, kelly=0.518) with $2532.97 allocation
[PORT] Sector Technology: selecting FB (p_up=0.520, kelly=0.169) with $825.64 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.922, kelly=0.846) with $4135.22 allocation
[SIM] 2017-08-03 00:00:00: 9 trades proposed.
[TRADE] 2017-08-03 00:00:00: allocated $3691.99 to TOT exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $2790.43 to PG exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $2532.97 to PCLN exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $2462.73 to V exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $2307.82 to CELG exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $886.55 to IEP exiting on 2017-08-10 00:00:00
[EXIT] 2017-08-04 00:00:00: TOT r=0.0259, PnL=$103.21
[EXIT] 2017-08-04 00:00:00: PM r=-0.0316, PnL=$-111.51
[EXIT] 2017-08-04 00:00:00: GD r=0.0108, PnL=$37.18
[EXIT] 2017-08-04 00:00:00: CELG r=0.0194, PnL=$62.27
[EXIT] 2017-08-04 00:00:00: IEP r=0.0215, PnL=$29.85
[EXIT] 2017-08-04 00:00:00: FB r=-0.0164, PnL=$-13.21

Simulating Trading Days:  82%|████████▏ | 89/108 [16:35<00:27,  1.44s/it]

[SIM] 2017-08-04 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.883, kelly=0.755) with $3831.14 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.532, kelly=0.176) with $895.00 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.799, kelly=0.594) with $3013.31 allocation
[PORT] Sector Financial: selecting V (p_up=0.726, kelly=0.494) with $2506.99 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.631, kelly=0.340) with $1722.73 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.786, kelly=0.604) with $3062.94 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.755, kelly=0.531) with $2694.01 allocation
[PORT] Sector Technology: selecting FB (p_up=0.526, kelly=0.180) with $911.24 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.922, kelly=0.846) with $4292.60 allocation
[SIM] 2017-08-04 00:00:00: 9 trades proposed.
[TRADE] 2017-08-04 00:00:00: allocated $3831.14 to TOT exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $3013.31 to MO exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $3062.94 to GD exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $2694.01 to PCLN exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $1722.73 to CELG exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $895.00 to IEP exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $911.24 to FB exiting on 2017-08-11 00:00:00
[EXIT] 2017-08-07 00:00:00: EXC r=-0.0031, PnL=$-11.40
[EXIT] 2017-08-07 00:00:00: GD r=0.0245, PnL=$75.47
[EXIT] 2017-08-07 00:00:00: PM r=-0.0073, PnL=$-21.04
[EXIT] 2017-08-07 00:00:00: FB r=0.0161, PnL=$10.56

Simulating Trading Days:  83%|████████▎ | 90/108 [16:36<00:25,  1.44s/it]

[SIM] 2017-08-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.882, kelly=0.753) with $3380.76 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.536, kelly=0.184) with $825.88 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.913, kelly=0.824) with $3701.37 allocation
[PORT] Sector Financial: selecting V (p_up=0.719, kelly=0.482) with $2165.23 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.583, kelly=0.253) with $1135.60 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.759, kelly=0.554) with $2487.91 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.765, kelly=0.549) with $2465.23 allocation
[PORT] Sector Technology: selecting FB (p_up=0.530, kelly=0.187) with $839.78 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.920, kelly=0.843) with $3787.19 allocation
[SIM] 2017-08-07 00:00:00: 9 trades proposed.
[TRADE] 2017-08-07 00:00:00: allocated $3787.19 to EXC exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $3701.37 to MO exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $2465.23 to PCLN exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $2487.91 to GD exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $839.78 to FB exiting on 2017-08-14 00:00:00
[EXIT] 2017-08-08 00:00:00: EXC r=-0.0088, PnL=$-38.54
[EXIT] 2017-08-08 00:00:00: TOT r=-0.0006, PnL=$-2.31
[EXIT] 2017-08-08 00:00:00: GD r=0.0116, PnL=$42.99
[EXIT] 2017-08-08 00:00:00: AMZN r=-0.0064, PnL=$-18.01
[EXIT] 2017-08-08 00:00:00: V r=0.0041, PnL=$10.86
[EXIT] 2017-08-08 00:00:00: IEP r=0.0548, PnL=$61.61
[EXIT] 2017-08-08 00:00:00: FB r=0.0081, PnL=$6.38

Simulating Trading Days:  84%|████████▍ | 91/108 [16:38<00:24,  1.45s/it]

[SIM] 2017-08-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.883, kelly=0.755) with $3862.35 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.546, kelly=0.202) with $1034.68 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.963, kelly=0.926) with $4732.55 allocation
[PORT] Sector Financial: selecting V (p_up=0.711, kelly=0.468) with $2393.63 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.558, kelly=0.209) with $1067.51 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.735, kelly=0.511) with $2611.15 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.779, kelly=0.577) with $2951.51 allocation
[PORT] Sector Technology: selecting FB (p_up=0.530, kelly=0.186) with $952.38 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.915, kelly=0.833) with $4257.35 allocation
[SIM] 2017-08-08 00:00:00: 9 trades proposed.
[TRADE] 2017-08-08 00:00:00: allocated $4732.55 to MO exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $4257.35 to EXC exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $3862.35 to TOT exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $2611.15 to GD exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $2393.63 to V exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $1034.68 to IEP exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $642.56 to FB exiting on 2017-08-15 00:00:00
[EXIT] 2017-08-09 00:00:00: EXC r=-0.0187, PnL=$-65.93
[EXIT] 2017-08-09 00:00:00: CELG r=0.0053, PnL=$13.42
[EXIT] 2017-08-09 00:00:00: V r=-0.0031, PnL=$-6.50
[EXIT] 2017-08-09 00:00:00: AMZN r=-0.0139, PnL=$-27.17

Simulating Trading Days:  85%|████████▌ | 92/108 [16:39<00:23,  1.48s/it]

[SIM] 2017-08-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.885, kelly=0.760) with $3164.69 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.563, kelly=0.233) with $967.58 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.983, kelly=0.965) with $4017.85 allocation
[PORT] Sector Financial: selecting V (p_up=0.703, kelly=0.453) with $1883.73 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.621, kelly=0.322) with $1339.00 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.725, kelly=0.491) with $2044.14 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.794, kelly=0.605) with $2516.87 allocation
[PORT] Sector Technology: selecting FB (p_up=0.526, kelly=0.181) with $752.55 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.905, kelly=0.813) with $3382.18 allocation
[SIM] 2017-08-09 00:00:00: 9 trades proposed.
[TRADE] 2017-08-09 00:00:00: allocated $3382.18 to EXC exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $1883.73 to V exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $1339.00 to CELG exiting on 2017-08-16 00:00:00
[EXIT] 2017-08-10 00:00:00: TOT r=-0.0113, PnL=$-41.62
[EXIT] 2017-08-10 00:00:00: PG r=0.0097, PnL=$27.03
[EXIT] 2017-08-10 00:00:00: PCLN r=-0.0879, PnL=$-222.77
[EXIT] 2017-08-10 00:00:00: V r=-0.0109, PnL=$-26.93
[EXIT] 2017-08-10 00:00:00: CELG r=-0.0407, PnL=$-93.91
[EXIT] 2017-08-10 00:00:00: IEP r=0.0425, PnL=$37.71

Simulating Trading Days:  86%|████████▌ | 93/108 [16:41<00:22,  1.48s/it]

[SIM] 2017-08-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.880, kelly=0.750) with $3701.63 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.581, kelly=0.264) with $1300.94 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.991, kelly=0.982) with $4846.17 allocation
[PORT] Sector Financial: selecting V (p_up=0.693, kelly=0.435) with $2147.20 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.696, kelly=0.456) with $2248.88 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.721, kelly=0.484) with $2389.28 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.812, kelly=0.640) with $3156.78 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.955, kelly=0.912) with $4502.47 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.886, kelly=0.775) with $3825.68 allocation
[SIM] 2017-08-10 00:00:00: 9 trades proposed.
[TRADE] 2017-08-10 00:00:00: allocated $4502.47 to INTC exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $3701.63 to TOT exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $3156.78 to PCLN exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $2248.88 to CELG exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $2147.20 to V exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $1300.94 to IEP exiting on 2017-08-17 00:00:00
[EXIT] 2017-08-11 00:00:00: TOT r=-0.0293, PnL=$-112.16
[EXIT] 2017-08-11 00:00:00: MO r=-0.0185, PnL=$-55.65
[EXIT] 2017-08-11 00:00:00: GD r=-0.0109, PnL=$-33.37
[EXIT] 2017-08-11 00:00:00: PCLN r=-0.0879, PnL=$-236.70
[EXIT] 2017-08-11 00:00:00: CELG r=-0.0446, PnL=$-76.75
[EXIT] 2017-08-11 00:00:00: IEP r=-0.0011, PnL=$-1.01
[EXIT] 2017-08-11 00:00:00: FB r=-0.0091, PnL=$-8.27

Simulating Trading Days:  87%|████████▋ | 94/108 [16:43<00:22,  1.61s/it]

[SIM] 2017-08-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.866, kelly=0.719) with $3445.89 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.592, kelly=0.283) with $1354.73 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.995, kelly=0.990) with $4740.91 allocation
[PORT] Sector Financial: selecting V (p_up=0.682, kelly=0.414) with $1985.52 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.807, kelly=0.654) with $3133.22 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.729, kelly=0.500) with $2393.16 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.829, kelly=0.673) with $3222.49 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.963, kelly=0.927) with $4442.09 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.849, kelly=0.703) with $3369.79 allocation
[SIM] 2017-08-11 00:00:00: 9 trades proposed.
[TRADE] 2017-08-11 00:00:00: allocated $4740.91 to MO exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $4442.09 to INTC exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $3445.89 to TOT exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $3222.49 to PCLN exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $742.47 to CELG exiting on 2017-08-18 00:00:00
[EXIT] 2017-08-14 00:00:00: EXC r=-0.0162, PnL=$-61.44
[EXIT] 2017-08-14 00:00:00: MO r=-0.0174, PnL=$-64.50
[EXIT] 2017-08-14 00:00:00: PCLN r=-0.0826, PnL=$-203.59
[EXIT] 2017-08-14 00:00:00: GD r=-0.0042, PnL=$-10.39
[EXIT] 2017-08-14 00:00:00: FB r=-0.0072, PnL=$-6.01

Simulating Trading Days:  88%|████████▊ | 95/108 [16:44<00:20,  1.58s/it]

[SIM] 2017-08-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.830, kelly=0.645) with $2853.56 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.593, kelly=0.284) with $1257.87 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.997, kelly=0.994) with $4397.13 allocation
[PORT] Sector Financial: selecting V (p_up=0.670, kelly=0.391) with $1731.48 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.857, kelly=0.745) with $3294.86 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.741, kelly=0.522) with $2310.68 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.844, kelly=0.701) with $3101.45 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.967, kelly=0.935) with $4137.35 allocation
[PORT] Sector Utilities: selecting D (p_up=0.812, kelly=0.625) with $2766.60 allocation
[SIM] 2017-08-14 00:00:00: 9 trades proposed.
[TRADE] 2017-08-14 00:00:00: allocated $4397.13 to MO exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $4137.35 to INTC exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $3101.45 to PCLN exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $1403.40 to D exiting on 2017-08-21 00:00:00
[EXIT] 2017-08-15 00:00:00: MO r=-0.0012, PnL=$-5.79
[EXIT] 2017-08-15 00:00:00: EXC r=-0.0097, PnL=$-41.23
[EXIT] 2017-08-15 00:00:00: TOT r=-0.0182, PnL=$-70.17
[EXIT] 2017-08-15 00:00:00: GD r=0.0035, PnL=$9.06
[EXIT] 2017-08-15 00:00:00: V r=0.0133, PnL=$31.91
[EXIT] 2017-08-15 00:00:00: IEP r=-0.0706, PnL=$-73.06
[EXIT] 2017-08-15 00:00:00: FB r=-0.0013, PnL=$-0.86

Simulating Trading Days:  89%|████████▉ | 96/108 [16:46<00:19,  1.60s/it]

[SIM] 2017-08-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.764, kelly=0.508) with $2570.57 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.584, kelly=0.269) with $1360.05 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.998, kelly=0.996) with $5037.54 allocation
[PORT] Sector Financial: selecting V (p_up=0.661, kelly=0.374) with $1894.66 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.839, kelly=0.712) with $3601.67 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.748, kelly=0.534) with $2703.32 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.855, kelly=0.721) with $3650.22 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.962, kelly=0.925) with $4681.20 allocation
[PORT] Sector Utilities: selecting D (p_up=0.805, kelly=0.611) with $3090.72 allocation
[SIM] 2017-08-15 00:00:00: 9 trades proposed.
[TRADE] 2017-08-15 00:00:00: allocated $5037.54 to MO exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $3090.72 to D exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $2570.57 to TOT exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $2703.32 to GD exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $1894.66 to V exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $1360.05 to IEP exiting on 2017-08-22 00:00:00
[EXIT] 2017-08-16 00:00:00: EXC r=0.0114, PnL=$38.58
[EXIT] 2017-08-16 00:00:00: V r=0.0233, PnL=$43.84
[EXIT] 2017-08-16 00:00:00: CELG r=-0.0318, PnL=$-42.57

Simulating Trading Days:  90%|████████▉ | 97/108 [16:47<00:17,  1.58s/it]

[SIM] 2017-08-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.755, kelly=0.522) with $2118.54 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.570, kelly=0.244) with $989.52 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.998, kelly=0.995) with $4038.32 allocation
[PORT] Sector Financial: selecting V (p_up=0.656, kelly=0.367) with $1488.97 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.815, kelly=0.669) with $2714.60 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.748, kelly=0.533) with $2164.91 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.866, kelly=0.744) with $3018.06 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.947, kelly=0.896) with $3638.31 allocation
[PORT] Sector Utilities: selecting D (p_up=0.795, kelly=0.591) with $2397.16 allocation
[SIM] 2017-08-16 00:00:00: 9 trades proposed.
[TRADE] 2017-08-16 00:00:00: allocated $2714.60 to CELG exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $2397.16 to D exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $2118.54 to SNP exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $2164.91 to GD exiting on 2017-08-23 00:00:00
[EXIT] 2017-08-17 00:00:00: INTC r=-0.0268, PnL=$-120.85
[EXIT] 2017-08-17 00:00:00: TOT r=-0.0195, PnL=$-72.04
[EXIT] 2017-08-17 00:00:00: PCLN r=-0.0198, PnL=$-62.55
[EXIT] 2017-08-17 00:00:00: CELG r=-0.0214, PnL=$-48.13
[EXIT] 2017-08-17 00:00:00: V r=0.0268, PnL=$57.62
[EXIT] 2017-08-17 00:00:00: IEP r=-0.0733, PnL=$-95.34

Simulating Trading Days:  91%|█████████ | 98/108 [16:49<00:15,  1.57s/it]

[SIM] 2017-08-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.747, kelly=0.506) with $2423.59 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.554, kelly=0.216) with $1035.54 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.997, kelly=0.994) with $4762.71 allocation
[PORT] Sector Financial: selecting V (p_up=0.658, kelly=0.369) with $1769.21 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.798, kelly=0.638) with $3058.40 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.739, kelly=0.519) with $2484.10 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.877, kelly=0.765) with $3664.58 allocation
[PORT] Sector Technology: selecting FB (p_up=0.522, kelly=0.173) with $829.75 allocation
[PORT] Sector Utilities: selecting D (p_up=0.781, kelly=0.563) with $2698.50 allocation
[SIM] 2017-08-17 00:00:00: 9 trades proposed.
[TRADE] 2017-08-17 00:00:00: allocated $3664.58 to PCLN exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $3058.40 to CELG exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $2423.59 to SNP exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $2484.10 to GD exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $1769.21 to V exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $1035.54 to IEP exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $829.75 to FB exiting on 2017-08-24 00:00:00
[EXIT] 2017-08-18 00:00:00: MO r=-0.0096, PnL=$-45.71
[EXIT] 2017-08-18 00:00:00: INTC r=-0.0240, PnL=$-106.50
[EXIT] 2017-08-18 00:00:00: TOT r=0.0018, PnL=$6.15
[EXIT] 2017-08-18 00:00:00: PCLN r=-0.0238, PnL=$-76.77
[EXIT] 2017-08-18 00:00:00: CELG r=-0.0227, PnL=$-16.83

Simulating Trading Days:  92%|█████████▏| 99/108 [16:50<00:13,  1.54s/it]

[SIM] 2017-08-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.741, kelly=0.494) with $2420.06 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.542, kelly=0.194) with $951.69 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.997, kelly=0.993) with $4865.30 allocation
[PORT] Sector Financial: selecting V (p_up=0.661, kelly=0.375) with $1837.02 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.826, kelly=0.688) with $3371.99 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.745, kelly=0.530) with $2595.34 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.885, kelly=0.779) with $3818.55 allocation
[PORT] Sector Technology: selecting FB (p_up=0.525, kelly=0.178) with $870.11 allocation
[PORT] Sector Utilities: selecting D (p_up=0.766, kelly=0.532) with $2608.82 allocation
[SIM] 2017-08-18 00:00:00: 9 trades proposed.
[TRADE] 2017-08-18 00:00:00: allocated $4865.30 to MO exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $3818.55 to PCLN exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $3371.99 to CELG exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $2420.06 to SNP exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $1837.02 to V exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $951.69 to IEP exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $725.19 to FB exiting on 2017-08-25 00:00:00
[EXIT] 2017-08-21 00:00:00: MO r=-0.0069, PnL=$-30.52
[EXIT] 2017-08-21 00:00:00: INTC r=-0.0391, PnL=$-161.67
[EXIT] 2017-08-21 00:00:00: PCLN r=-0.0386, PnL=$-119.84
[EXIT] 2017-08-21 00:00:00: D r=0.0136, PnL=$19.15

Simulating Trading Days:  93%|█████████▎| 100/108 [16:52<00:12,  1.54s/it]

[SIM] 2017-08-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.743, kelly=0.499) with $2182.33 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.534, kelly=0.181) with $793.12 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.996, kelly=0.992) with $4339.55 allocation
[PORT] Sector Financial: selecting V (p_up=0.664, kelly=0.381) with $1667.27 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.852, kelly=0.736) with $3218.48 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.759, kelly=0.556) with $2430.71 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.889, kelly=0.788) with $3448.38 allocation
[PORT] Sector Technology: selecting FB (p_up=0.530, kelly=0.187) with $818.00 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.885, kelly=0.770) with $3369.58 allocation
[SIM] 2017-08-21 00:00:00: 9 trades proposed.
[TRADE] 2017-08-21 00:00:00: allocated $4339.55 to MO exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $3448.38 to PCLN exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $3369.58 to SRE exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $818.00 to FB exiting on 2017-08-28 00:00:00
[EXIT] 2017-08-22 00:00:00: MO r=-0.0190, PnL=$-95.66
[EXIT] 2017-08-22 00:00:00: D r=0.0137, PnL=$42.45
[EXIT] 2017-08-22 00:00:00: TOT r=0.0159, PnL=$40.92
[EXIT] 2017-08-22 00:00:00: GD r=0.0087, PnL=$23.58
[EXIT] 2017-08-22 00:00:00: V r=0.0140, PnL=$26.58
[EXIT] 2017-08-22 00:00:00: IEP r=-0.0341, PnL=$-46.42

Simulating Trading Days:  94%|█████████▎| 101/108 [16:53<00:10,  1.55s/it]

[SIM] 2017-08-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.745, kelly=0.502) with $2429.88 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.531, kelly=0.175) with $846.23 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.996, kelly=0.991) with $4799.08 allocation
[PORT] Sector Financial: selecting V (p_up=0.669, kelly=0.390) with $1887.35 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.874, kelly=0.774) with $3747.53 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.781, kelly=0.595) with $2879.53 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.892, kelly=0.793) with $3841.39 allocation
[PORT] Sector Technology: selecting FB (p_up=0.536, kelly=0.197) with $955.87 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.869, kelly=0.738) with $3571.85 allocation
[SIM] 2017-08-22 00:00:00: 9 trades proposed.
[TRADE] 2017-08-22 00:00:00: allocated $4799.08 to MO exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $3571.85 to SRE exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $2879.53 to GD exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $1887.35 to V exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $846.23 to IEP exiting on 2017-08-29 00:00:00
[EXIT] 2017-08-23 00:00:00: CELG r=-0.0158, PnL=$-42.81
[EXIT] 2017-08-23 00:00:00: D r=0.0125, PnL=$30.03
[EXIT] 2017-08-23 00:00:00: SNP r=0.0165, PnL=$34.86
[EXIT] 2017-08-23 00:00:00: GD r=-0.0043, PnL=$-9.28

Simulating Trading Days:  94%|█████████▍| 102/108 [16:55<00:09,  1.53s/it]

[SIM] 2017-08-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.745, kelly=0.503) with $2204.74 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.531, kelly=0.176) with $772.25 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.995, kelly=0.990) with $4341.78 allocation
[PORT] Sector Financial: selecting V (p_up=0.676, kelly=0.403) with $1766.57 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.854, kelly=0.739) with $3241.28 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.784, kelly=0.600) with $2632.60 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.893, kelly=0.795) with $3486.52 allocation
[PORT] Sector Technology: selecting FB (p_up=0.539, kelly=0.202) with $885.79 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.651, kelly=0.315) with $1382.45 allocation
[SIM] 2017-08-23 00:00:00: 9 trades proposed.
[TRADE] 2017-08-23 00:00:00: allocated $3241.28 to CELG exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $2632.60 to GD exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $2204.74 to SNP exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $1382.45 to NEE exiting on 2017-08-30 00:00:00
[EXIT] 2017-08-24 00:00:00: PCLN r=0.0014, PnL=$5.13
[EXIT] 2017-08-24 00:00:00: CELG r=0.0194, PnL=$59.21
[EXIT] 2017-08-24 00:00:00: SNP r=0.0400, PnL=$96.88
[EXIT] 2017-08-24 00:00:00: GD r=0.0075, PnL=$18.57
[EXIT] 2017-08-24 00:00:00: V r=0.0104, PnL=$18.36
[EXIT] 2017-08-24 00:00:00: IEP r=0.0098, PnL=$10.11
[EXIT] 2017-08-24 00:00:00: FB r=0.0050, PnL=$4.13

Simulating Trading Days:  95%|█████████▌| 103/108 [16:56<00:07,  1.54s/it]

[SIM] 2017-08-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.697, kelly=0.368) with $1833.09 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.537, kelly=0.186) with $925.28 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.995, kelly=0.989) with $4931.19 allocation
[PORT] Sector Financial: selecting V (p_up=0.684, kelly=0.417) with $2081.25 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.841, kelly=0.716) with $3571.11 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.783, kelly=0.598) with $2983.27 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.893, kelly=0.794) with $3960.88 allocation
[PORT] Sector Technology: selecting FB (p_up=0.540, kelly=0.205) with $1020.00 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.666, kelly=0.344) with $1713.69 allocation
[SIM] 2017-08-24 00:00:00: 9 trades proposed.
[TRADE] 2017-08-24 00:00:00: allocated $3960.88 to PCLN exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $3571.11 to CELG exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $2983.27 to GD exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $1833.09 to TOT exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $2081.25 to V exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $1713.69 to NEE exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $1020.00 to FB exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $925.28 to IEP exiting on 2017-08-31 00:00:00
[EXIT] 2017-08-25 00:00:00: MO r=0.0061, PnL=$29.79
[EXIT] 2017-08-25 00:00:00: PCLN r=-0.0091, PnL=$-34.85
[EXIT] 2017-08-25 00:00:00: CELG r=0.0159, PnL=$53.62
[EXIT] 2017-08-25 00:00:00: SNP r=0.0308, PnL=$74.50
[EXIT] 2017-08-25 00:00:00: V r=0.0082, PnL=$15.05
[EXIT] 2017-08-25 00:00:00: IEP r=0.0298, PnL=$28.36
[EXIT] 2017-08-25 00:00:00: FB r=-0.0065, PnL=$-4.72

Simulating Trading Days:  96%|█████████▋| 104/108 [16:58<00:06,  1.55s/it]

[SIM] 2017-08-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.771, kelly=0.552) with $2758.00 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.545, kelly=0.201) with $1002.49 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.994, kelly=0.988) with $4931.56 allocation
[PORT] Sector Financial: selecting V (p_up=0.691, kelly=0.431) with $2151.77 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.824, kelly=0.685) with $3421.00 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.776, kelly=0.586) with $2927.63 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.891, kelly=0.791) with $3948.64 allocation
[PORT] Sector Technology: selecting FB (p_up=0.542, kelly=0.208) with $1038.75 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.684, kelly=0.378) with $1889.21 allocation
[SIM] 2017-08-25 00:00:00: 9 trades proposed.
[EXIT] 2017-08-28 00:00:00: MO r=-0.0071, PnL=$-31.00
[EXIT] 2017-08-28 00:00:00: PCLN r=-0.0065, PnL=$-22.26
[EXIT] 2017-08-28 00:00:00: SRE r=0.0068, PnL=$23.05
[EXIT] 2017-08-28 00:00:00: FB r=-0.0032, PnL=$-2.63

Simulating Trading Days:  97%|█████████▋| 105/108 [17:00<00:04,  1.56s/it]

[SIM] 2017-08-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.775, kelly=0.561) with $3469.73 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.557, kelly=0.222) with $1372.52 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.993, kelly=0.986) with $6101.74 allocation
[PORT] Sector Financial: selecting V (p_up=0.698, kelly=0.444) with $2747.84 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.822, kelly=0.682) with $4219.21 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.781, kelly=0.595) with $3682.63 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.886, kelly=0.782) with $4840.11 allocation
[PORT] Sector Technology: selecting FB (p_up=0.547, kelly=0.217) with $1339.70 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.701, kelly=0.413) with $2554.52 allocation
[SIM] 2017-08-28 00:00:00: 9 trades proposed.
[EXIT] 2017-08-29 00:00:00: MO r=-0.0039, PnL=$-18.73
[EXIT] 2017-08-29 00:00:00: SRE r=0.0042, PnL=$15.10
[EXIT] 2017-08-29 00:00:00: GD r=-0.0014, PnL=$-4.01
[EXIT] 2017-08-29 00:00:00: V r=-0.0029, PnL=$-5.44
[EXIT] 2017-08-29 00:00:00: IEP r=0.0184, PnL=$15.54

Simulating Trading Days:  98%|█████████▊| 106/108 [17:01<00:03,  1.55s/it]

[SIM] 2017-08-29 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.772, kelly=0.556) with $4215.07 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.569, kelly=0.241) with $1831.89 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.992, kelly=0.984) with $7464.77 allocation
[PORT] Sector Financial: selecting V (p_up=0.707, kelly=0.460) with $3487.85 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.804, kelly=0.649) with $4922.90 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.794, kelly=0.620) with $4701.41 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.881, kelly=0.772) with $5855.03 allocation
[PORT] Sector Technology: selecting FB (p_up=0.552, kelly=0.225) with $1707.16 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.703, kelly=0.417) with $3164.12 allocation
[SIM] 2017-08-29 00:00:00: 9 trades proposed.
[EXIT] 2017-08-30 00:00:00: CELG r=0.0399, PnL=$129.21
[EXIT] 2017-08-30 00:00:00: GD r=0.0074, PnL=$19.37
[EXIT] 2017-08-30 00:00:00: SNP r=0.0239, PnL=$52.64
[EXIT] 2017-08-30 00:00:00: NEE r=0.0065, PnL=$9.05

Simulating Trading Days:  99%|█████████▉| 107/108 [17:03<00:01,  1.56s/it]

[SIM] 2017-08-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 64 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.804, kelly=0.617) with $5273.91 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.577, kelly=0.256) with $2189.52 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.990, kelly=0.980) with $8384.39 allocation
[PORT] Sector Financial: selecting V (p_up=0.715, kelly=0.475) with $4061.58 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.783, kelly=0.611) with $5226.84 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.796, kelly=0.624) with $5333.53 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.873, kelly=0.756) with $6469.16 allocation
[PORT] Sector Technology: selecting FB (p_up=0.555, kelly=0.230) with $1963.88 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.707, kelly=0.424) with $3630.01 allocation
[SIM] 2017-08-30 00:00:00: 9 trades proposed.
[EXIT] 2017-08-31 00:00:00: PCLN r=0.0201, PnL=$79.78
[EXIT] 2017-08-31 00:00:00: CELG r=0.0683, PnL=$243.84
[EXIT] 2017-08-31 00:00:00: GD r=0.0094, PnL=$28.12
[EXIT] 2017-08-31 00:00:00: TOT r=0.0130, PnL=$23.91
[EXIT] 2017-08-31 00:00:00: V r=0.0029, PnL=$6.05
[EXIT] 2017-08-31 00:00:00: NEE r=0.0080, PnL=$13.77
[EXIT] 2017-08-31 00:00:00: FB r=0.0252, PnL=$25.72
[EXIT] 2017-08-31 00:00:00: IEP r=0.0097, PnL=$8.94

Simulating Trading Days: 100%|██████████| 108/108 [17:04<00:00,  9.49s/it]

[SIM] 2017-08-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 63 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.829, kelly=0.666) with $6931.42 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.582, kelly=0.266) with $2764.98 allocation
[PORT] Sector Consumer Goods: selecting MO (p_up=0.988, kelly=0.975) with $10143.66 allocation
[PORT] Sector Financial: selecting V (p_up=0.721, kelly=0.486) with $5053.80 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.749, kelly=0.551) with $5728.37 allocation
[PORT] Sector Industrial Goods: selecting GD (p_up=0.785, kelly=0.602) with $6266.85 allocation
[PORT] Sector Services: selecting PCLN (p_up=0.861, kelly=0.733) with $7627.81 allocation
[PORT] Sector Technology: selecting FB (p_up=0.552, kelly=0.225) with $2337.74 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.841, kelly=0.687) with $7145.22 allocation
[SIM] 2017-08-31 00:00:00: 9 trades proposed.

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-03-30,100000.000000,72554.805300,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'TOT', 'sector': 'Basic Matierials..."
1,2017-03-31,72554.805300,53732.394155,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'TOT', 'sector': 'Basic Matierials..."
2,2017-04-03,53732.394155,35870.213560,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'JPM', 'sector': 'Financial', 'pro..."
3,2017-04-04,35870.213560,30000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'JPM', 'sector': 'Financial', 'pro..."
4,2017-04-05,30000.000000,30000.000000,100000.000000,100000.000000,0.000000,0.000000,[]
...,...,...,...,...,...,...,...,...
95,2017-08-15,50597.078067,33940.215982,103893.044301,103893.044301,-150.138110,-0.001443,"[{'ticker': 'MO', 'sector': 'Consumer Goods', ..."
96,2017-08-16,40584.973372,31189.750913,103932.893918,103932.893918,39.849617,0.000384,"[{'ticker': 'CELG', 'sector': 'Healthcare', 'p..."
97,2017-08-17,47906.368353,32641.198479,103591.611135,103591.611135,-341.282783,-0.003284,"[{'ticker': 'PCLN', 'sector': 'Services', 'pro..."
98,2017-08-18,48995.388364,31005.589404,103351.964681,103351.964681,-239.646454,-0.002313,"[{'ticker': 'MO', 'sector': 'Consumer Goods', ..."
99,2017-08-21,43752.035568,31776.521712,103059.088946,103059.088946,-292.875736,-0.002834,"[{'ticker': 'MO', 'sector': 'Consumer Goods', ..."

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
8,2017-04-11,36528.550113,31095.872630,100329.022049,100329.022049,-50.271046,-0.000501,"[{'ticker': 'JPM', 'sector': 'Financial', 'pro..."
9,2017-04-12,31095.872630,31095.872630,100329.022049,100329.022049,0.000000,0.000000,[]
10,2017-04-13,56262.179213,30674.906091,100050.836882,100050.836882,-278.185167,-0.002773,"[{'ticker': 'TM', 'sector': 'Consumer Goods', ..."
11,2017-04-17,50058.526525,30024.901247,100083.004158,100083.004158,32.167276,0.000322,"[{'ticker': 'TM', 'sector': 'Consumer Goods', ..."
12,2017-04-18,48852.444860,29971.806222,99906.020742,99906.020742,-176.983417,-0.001768,"[{'ticker': 'JPM', 'sector': 'Financial', 'pro..."
...,...,...,...,...,...,...,...,...
103,2017-08-25,49928.271534,49928.271534,103437.478850,103437.478850,161.760385,0.001566,[]
104,2017-08-28,61870.941788,61870.941788,103404.635248,103404.635248,-32.843602,-0.000318,[]
105,2017-08-29,75857.450043,75857.450043,103407.100992,103407.100992,2.465744,0.000024,[]
106,2017-08-30,85528.808030,85528.808030,103617.380839,103617.380839,210.279847,0.002034,[]
107,2017-08-31,104047.519330,104047.519330,104047.519330,104047.519330,430.138491,0.004151,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $104,047.52
Total Return on Investment (ROI): 4.05%
Annualized Sharpe Ratio: 3.39
--------------------------

In [39]:
import numpy as np
import pandas as pd

ret_col = f"ret_{5}d"
if ret_col not in master_df_with_target.columns:
    master_df_with_target = add_horizon_targets(master_df_with_target, H=5, price_col='close_price')

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 563
Total capital allocated: $1,455,099.60
Average position size:  $2,584.55
Completed trades with returns: 563
Winning trades: 322 (57.2%)
Losing trades:  240 (42.6%)
Total PnL: $4,047.52
Average PnL per trade: $7.19
Average return: 0.31%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Consumer Goods,66,214434.749078,3249.011350,948.434937,14.370226,0.006281
Utilities,71,225172.598720,3171.445052,932.283371,13.130752,0.004577
Financial,63,200418.748653,3181.249979,750.036928,11.905348,0.003902
Industrial Goods,60,159868.114782,2664.468580,619.617082,10.326951,0.003484
Basic Matierials,65,169623.795078,2609.596847,568.929564,8.752763,0.002825
Healthcare,59,134797.203095,2284.698358,428.574514,7.263975,0.004697
Services,67,178507.703365,2664.294080,290.987109,4.343091,0.000763
Technology,53,64585.517396,1218.594668,53.695266,1.013118,0.006033
Conglomerates,59,107691.172413,1825.274109,-545.039440,-9.237957,-0.005078

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
327,2017-06-26,2017-07-03,JPM,Financial,5083.815368,0.985335,0.005976,0.063159,321.089334
334,2017-06-27,2017-07-05,JPM,Financial,4262.291415,0.981148,0.005941,0.063941,272.534776
556,2017-08-24,2017-08-31,CELG,Healthcare,3571.113956,0.841408,0.010784,0.068281,243.840488
321,2017-06-23,2017-06-30,JPM,Financial,4524.879447,0.988313,0.006001,0.052268,236.506528
0,2017-03-30,2017-04-06,TOT,Basic Matierials,5346.923444,0.777171,0.002975,0.036157,193.326419
86,2017-04-21,2017-04-28,PCLN,Services,3465.878719,0.802504,0.007844,0.054115,187.555857
438,2017-07-25,2017-08-01,EXC,Utilities,4211.077661,0.903921,0.005914,0.041329,174.039563
120,2017-05-02,2017-05-09,GMRE,Conglomerates,4597.840184,0.905988,0.012398,0.035831,164.743459
358,2017-07-03,2017-07-11,PCLN,Services,3447.359682,0.801181,0.007821,0.046671,160.890412
81,2017-04-21,2017-04-28,JPM,Financial,5463.642141,0.989510,0.006012,0.029342,160.315303

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
337,2017-06-27,2017-07-05,GMRE,Conglomerates,2974.995541,0.821559,0.007536,-0.109868,-326.856072
484,2017-08-04,2017-08-11,PCLN,Services,2694.005888,0.755436,0.007047,-0.087860,-236.696420
477,2017-08-03,2017-08-10,PCLN,Services,2532.965230,0.748489,0.006933,-0.087950,-222.773225
490,2017-08-07,2017-08-14,PCLN,Services,2465.227290,0.764724,0.007201,-0.082584,-203.589152
450,2017-07-27,2017-08-03,AMZN,Services,3234.859826,0.796669,0.008074,-0.056482,-182.710873
98,2017-04-25,2017-05-02,GMRE,Conglomerates,2795.342356,0.763889,0.004680,-0.059244,-165.607617
515,2017-08-14,2017-08-21,INTC,Technology,4137.346302,0.966997,0.010050,-0.039075,-161.668685
155,2017-05-10,2017-05-17,JPM,Financial,4431.599094,0.989892,0.006015,-0.036143,-160.172326
216,2017-05-26,2017-06-05,JPM,Financial,4972.693592,0.970857,0.005861,-0.030108,-149.716757
445,2017-07-26,2017-08-02,AMZN,Services,2658.508931,0.792108,0.008022,-0.054056,-143.708042

TOP 10 SECTORS BY TOTAL PnL

                   total_pnl
sector
Consumer Goods    948.434937
Utilities         932.283371
Financial         750.036928
Industrial Goods  619.617082
Basic Matierials  568.929564
Healthcare        428.574514
Services          290.987109
Technology         53.695266
Conglomerates    -545.039440

BOTTOM 10 SECTORS BY TOTAL PnL

                   total_pnl
sector
Consumer Goods    948.434937
Utilities         932.283371
Financial         750.036928
Industrial Goods  619.617082
Basic Matierials  568.929564
Healthcare        428.574514
Services          290.987109
Technology         53.695266
Conglomerates    -545.039440

In [40]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]