# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as Fnn
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [7]:
pandas_ta_classic_path = None
for sp in site.getsitepackages():
    pandas_ta_classic_path = os.path.join(sp, 'pandas_ta_classic')
    if os.path.exists(pandas_ta_classic_path):
        break

if pandas_ta_classic_path:
    squeeze_pro_path = os.path.join(pandas_ta_classic_path, 'momentum', 'squeeze_pro.py')
    if os.path.exists(squeeze_pro_path):
        try:
            with open(squeeze_pro_path, 'r') as f:
                lines = f.readlines()

            new_lines = []
            fixed = False
            for line in lines:
                if "from numpy import NaN as npNaN" in line:
                    new_lines.append(line.replace("from numpy import NaN as npNaN", "# from numpy import NaN as npNaN\nimport numpy as np\n"))
                    fixed = True
                    print("Modified import statement in squeeze_pro.py")
                else:
                    new_lines.append(line)

            if fixed:
                with open(squeeze_pro_path, 'w') as f:
                    f.writelines(new_lines)
                print("Successfully patched pandas_ta_classic/momentum/squeeze_pro.py")
            else:
                print("Could not find the problematic import line in squeeze_pro.py")

        except Exception as e:
            print(f"Error modifying squeeze_pro.py: {e}")
    else:
        print(f"Could not find squeeze_pro.py at {squeeze_pro_path}")
else:
    print("Could not find the pandas_ta_classic library installation path.")

import pandas_ta_classic as ta

Could not find the problematic import line in squeeze_pro.py

### Configurations

In [8]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 1100  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [9]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [10]:
BUCKET_BINS   = [-np.inf, -0.02, -0.005, 0.0, 0.005, 0.02, np.inf]
K = len(BUCKET_BINS) - 1

In [11]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

In [12]:
CALIBRATION_LOGGED = set()

In [13]:
def bucketize_with_edges(x, edges):
    # x: 1D np array of returns; edges: len K+1
    return np.clip(np.digitize(x, edges[1:-1], right=True), 0, len(edges)-2).astype(np.int64)

def make_cumulative_targets(y_idx, K):
    # y_idx in [0..K-1] -> T: [N,K-1] with T[:,k]=1(y>k)
    y = y_idx.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def ordinal_to_class_probs(P_rep):
    # P_rep: [N,K-1] with P(y>k) (after sigmoid), repaired monotone
    N, K1 = P_rep.shape; K = K1+1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:,0] = 1.0 - P_rep[:,0]
    for c in range(1, K-1):
        Pc[:,c] = np.clip(P_rep[:,c-1] - P_rep[:,c], 0., 1.)
    Pc[:,K-1] = P_rep[:,K1-1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)

def monotone_repair_numpy(P):
    P = np.asarray(P, dtype=np.float32).copy()
    for k in range(P.shape[1]-2, -1, -1):
        P[:,k] = np.maximum(P[:,k], P[:,k+1])
    return P

In [14]:
# multiclass calibration tuned for macro-F1 balance
def _class_dist(y_hat, K):
    hist = np.bincount(y_hat, minlength=K).astype(np.float32)
    return hist / max(1, y_hat.size)

def _balance_penalty(p_hat, p_target, norm="l1"):
    if norm == "l1":
        return float(np.abs(p_hat - p_target).sum())
    elif norm == "l2":
        return float(np.sqrt(((p_hat - p_target) ** 2).sum()))
    else:
        return float(np.abs(p_hat - p_target).sum())

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    # decode ordinal cumulative probs to class indices using per-head taus.
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def tune_temperature_and_taus(
    Z_val,
    y_val_idx,
    K,
    T_grid=np.linspace(0.6, 2.5, 15),
    tau_grid=np.linspace(0.2, 0.8, 31),
    lambda_balance=0.05,
    target_priors="uniform",
    coord_rounds=3,
):
    """Learn a temperature T and per-head taus by maximizing macro-F1 with a balance penalty."""
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.detach().cpu().numpy()

    N, K_1 = Z_val.shape
    assert K_1 == K - 1

    if isinstance(target_priors, str) and target_priors == "uniform":
        p_target = np.ones(K, dtype=np.float32) / K
    else:
        p_target = np.asarray(target_priors, dtype=np.float32)
        p_target = p_target / p_target.sum()

    best = {"score": -1e9, "T": 1.0, "taus": np.full(K_1, 0.5, np.float32)}

    for T in T_grid:
        P_cum = 1.0 / (1.0 + np.exp(-(Z_val / T)))
        P_rep = monotone_repair_numpy(P_cum)

        taus = np.full(K_1, 0.5, dtype=np.float32)
        for _ in range(coord_rounds):
            for k in range(K_1):
                best_k = (taus[k], -1e9)
                for tau in tau_grid:
                    taus_try = taus.copy()
                    taus_try[k] = tau
                    y_hat = decode_ordinal_with_taus(P_rep, taus_try)
                    f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
                    p_hat = _class_dist(y_hat, K)
                    score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")
                    if score > best_k[1]:
                        best_k = (tau, score)
                taus[k] = best_k[0]

        y_hat = decode_ordinal_with_taus(P_rep, taus)
        f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
        p_hat = _class_dist(y_hat, K)
        score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")

        if score > best["score"]:
            best.update({"score": score, "T": float(T), "taus": taus.astype(np.float32)})

    return best["T"], best["taus"]

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [15]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [16]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # end current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [17]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [18]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [19]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [20]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [21]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [22]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [23]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [24]:
class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):  # T: float32 matrix [N, K-1] with 0/1
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)
    def __len__(self): return len(self.X)
    def __getitem__(self, i): return self.X[i], self.T[i]
    
class LSTMOrdinal(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, head='CORAL', K=6):
        super().__init__()
        self.K = K
        self.lstm1 = nn.LSTM(n_features, hidden1, num_layers=1, batch_first=True, dropout=0.1)
        self.inter_drop = nn.Dropout(inter_dropout)
        self.lstm2 = nn.LSTM(hidden1, hidden2, num_layers=1, batch_first=True, dropout=0.1)

        self.norm = nn.BatchNorm1d(hidden2)
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(dropout)

        if head.upper() == 'CORAL':
            self.w = nn.Linear(fc, 1, bias=False)
            self._beta = nn.Parameter(torch.zeros(K-1))
            self.softplus = nn.Softplus()
            self.head_type = 'CORAL'
        else:
            self.fc_out = nn.Linear(fc, K-1)
            self.head_type = 'CORN'

    def forward(self, x):
        out1,_ = self.lstm1(x)
        out1 = self.inter_drop(out1)
        out2,_ = self.lstm2(out1)
        last = out2[:, -1, :]
        last = self.norm(last)
        z = self.relu(self.fc1(last))
        z = self.drop(z)
        if self.head_type == 'CORAL':
            base = self.w(z)                              # [B,1]
            deltas = self.softplus(self._beta)            # ≥0
            b = torch.cumsum(deltas, dim=0)               # [K-1]
            logits = base - b                              # broadcast -> [B,K-1]
        else:
            logits = self.fc_out(z)                        # [B,K-1]
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [25]:
def train_company_models(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 sequence_length: int = None,
                                 H: int = 1,
                                 K: int = K,        # global K
                                 head_type: str = 'CORAL'):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"[TRAIN] {ticker}: preparing data (H={H}) with {len(company_data_df)} rows")

    ret_col = f"ret_{H}d"
    if ret_col not in company_data_df.columns:
        company_data_df = add_horizon_targets(company_data_df, H=H, price_col='close')

    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)
    if len(company_data_df) < sequence_length + H + 10:
        print(f"[TRAIN] {ticker}: insufficient history for sequence length {sequence_length}")
        return False, sequence_length

    contigs = identify_contiguous_periods(company_data_df)
    if not contigs:
        print(f"[TRAIN] {ticker}: no contiguous periods found")
        return False, sequence_length

    rets = company_data_df[ret_col].values
    y_idx_all = bucketize_with_edges(rets, BUCKET_BINS)
    X_all = company_data_df[feature_cols].values

    X_seq, y_seq = create_contiguous_sequences(
        X_all, y_idx_all, contigs, sequence_length, H
    )
    if len(X_seq) < 40:
        print(f"[TRAIN] {ticker}: too few sequences ({len(X_seq)})")
        return False, sequence_length
    print(f"[TRAIN] {ticker}: built {len(X_seq)} sequences (seq_len={sequence_length})")

    X_tr, X_val, y_tr, y_val = train_test_split(X_seq, y_seq, test_size=0.2, shuffle=False)

    scaler = MinMaxScaler()
    F = X_tr.shape[-1]
    X_tr = scaler.fit_transform(X_tr.reshape(-1, F)).reshape(X_tr.shape)
    X_val = scaler.transform(X_val.reshape(-1, F)).reshape(X_val.shape)
    print(f"[TRAIN] {ticker}: scaler fitted on {X_tr.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_tr has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    # sector_feature_indices = [feature_cols.index('sector_ret_1d'),
    #                       feature_cols.index('sector_ret_5d'),
    #                       feature_cols.index('sector_vol_20d')]

    # print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    # print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")


    T_tr  = make_cumulative_targets(y_tr, K)
    T_val = make_cumulative_targets(y_val, K)

    train_ds = OrdinalSequenceDataset(X_tr, T_tr)
    val_ds   = OrdinalSequenceDataset(X_val, T_val)
    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_tr.shape[-1]
    model = LSTMOrdinal(n_features=n_features, head=head_type, K=K).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    pos_rate = T_tr.mean(axis=0)
    pos_w = ((1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)).astype(np.float32)
    pos_w = torch.tensor(pos_w, dtype=torch.float32, device=device) 
    print(f"[TRAIN] {ticker}: model n_features = {n_features}")

    
    def loss_fn(logits, T):
        losses = []
        for k in range(logits.shape[1]):
            losses.append(Fnn.binary_cross_entropy_with_logits(logits[:,k], T[:,k], pos_weight=pos_w[k]))
        return torch.stack(losses).mean()

    early = EarlyStopper(patience=15, mode='min')
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)

    for epoch in range(100):
        model.train()
        tot = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            l = loss_fn(logits, yb)
            l.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tot += l.item() * xb.size(0)

        model.eval()
        with torch.no_grad():
            vtot = 0.0
            for xb, yb in val_loader:
                xb, yb = xb.to(device), yb.to(device)
                logits = model(xb)
                l = loss_fn(logits, yb)
                vtot += l.item() * xb.size(0)
            val_loss = vtot / len(val_loader.dataset)

        scheduler.step(val_loss)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:
            break

    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    ret_seq_full = company_data_df[ret_col].values[sequence_length:]
    ret_train = ret_seq_full[:len(y_tr)]
    mu_c = np.array([ret_train[y_tr==c].mean() if np.any(y_tr==c) else 0.0 for c in range(K)], dtype=np.float32)


    taus = None
    temperature = 1.0
    try:
        model.eval()
        batch = 256
        logits_list = []
        for start in range(0, len(X_val), batch):
            xb = torch.from_numpy(X_val[start:start+batch].astype(np.float32)).to(device)
            with torch.no_grad():
                logits = model(xb)
            logits_list.append(logits.cpu().numpy())
        if logits_list:
            val_logits = np.vstack(logits_list)
            T_star, taus = tune_temperature_and_taus(
                Z_val=val_logits,
                y_val_idx=y_val,
                K=K,
                T_grid=np.linspace(0.6, 2.5, 15),
                tau_grid=np.linspace(0.2, 0.8, 31),
                lambda_balance=0.05,
                target_priors="uniform",
                coord_rounds=3,
            )
            temperature = float(T_star)
            print(f"[CAL] {ticker}: taus={np.round(taus, 3)} | temperature={temperature:.3f}")
        else:
            print(f"[CAL] {ticker}: no validation logits -> skipping calibration")
    except Exception as exc:
        print(f"[CAL] {ticker}: calibration failed ({exc})")
        taus = None
        temperature = 1.0

    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt"))
    joblib.dump(scaler, os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
    joblib.dump(BUCKET_BINS, os.path.join(model_save_path, f"{ticker}_edges_H{H}.pkl"))
    joblib.dump(mu_c, os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))
    if taus is not None and len(taus) == (K - 1) and np.all(np.isfinite(taus)):
        joblib.dump(taus, os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored taus")
    if temperature is not None and np.isfinite(temperature):
        joblib.dump(float(temperature), os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored temperature scale {temperature:.3f}")
    print(f"[SAVE] {ticker}: artifacts persisted (H={H})")

    del model, scaler, train_loader, val_loader, train_ds, val_ds
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [26]:

def predict_next_horizon(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         H: int,
                         K: int = 6,
                         head: str = "CORAL") -> dict | None:
    """
    Ordinal inference with optional calibration artifacts. Returns class probs plus
    summary stats so the simulator can log decisions.
    """
    try:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt")
        if not os.path.isfile(state_dict_path):
            return None

        scaler   = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        seq_len  = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
        mu_c     = joblib.load(os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))

        taus_path = os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl")
        T_path    = os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl")
        taus = joblib.load(taus_path) if os.path.isfile(taus_path) else None
        temperature = float(joblib.load(T_path)) if os.path.isfile(T_path) else 1.0

        n_features = len(feature_cols)
        model = LSTMOrdinal(n_features=n_features, head=head.upper(), K=K).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    if 'CALIBRATION_LOGGED' not in globals():
        globals()['CALIBRATION_LOGGED'] = set()
    if ticker not in CALIBRATION_LOGGED:
        if taus is not None:
            print(f"[CAL] {ticker}: loaded taus {np.round(taus,3)}")
        else:
            print(f"[CAL] {ticker}: no taus artifact found")
        print(f"[CAL] {ticker}: temperature scaling {temperature:.3f}")
        CALIBRATION_LOGGED.add(ticker)

    contiguous = identify_contiguous_periods(company_data_df)
    if not contiguous:
        return None
    start, end = contiguous[-1]
    period = company_data_df.iloc[start:end+1]
    if len(period) < seq_len:
        return None

    try:
        last_seq = period.tail(seq_len)
        X_scaled = scaler.transform(last_seq[feature_cols])
    except Exception:
        return None

    x = torch.from_numpy(np.asarray([X_scaled], dtype=np.float32)).to(device)

    with torch.no_grad():
        z = model(x)
        if temperature and temperature > 0 and temperature != 1.0:
            z = z / temperature
        P_cum = torch.sigmoid(z).cpu().numpy()
        P_cum = monotone_repair_numpy(P_cum)
        Pc    = ordinal_to_class_probs(P_cum)

    mu_c = np.asarray(mu_c, dtype=np.float32).reshape(-1)
    if mu_c.shape[0] != K:
        return None
    expected_rise = float((Pc[0] * mu_c).sum())

    top_bucket_idx = K - 1
    prob_top_bucket = float(Pc[0, top_bucket_idx])
    bucket_idx = int(np.argmax(Pc[0]))

    class_idx = None
    if taus is not None:
        taus = np.asarray(taus, dtype=np.float32).reshape(-1)
        if taus.shape[0] == (K - 1):
            class_idx = int(decode_ordinal_with_taus(P_cum, taus=taus)[0])

    positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
    prob_up = float(Pc[0, positive_buckets].sum()) if positive_buckets else prob_top_bucket

    return {
        'ticker': ticker,
        'expected_rise': expected_rise,
        'predicted_prob': prob_up,  # probability of positive move
        'prob_up': prob_up,
        'prob_bucket_top': prob_top_bucket,
        'bucket_idx': bucket_idx,
        'class_idx': class_idx,
        'class_probs': Pc[0].tolist(),
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [27]:

def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                              total_capital: float, sector_threshold: float,
                              kelly_fraction: float) -> pd.DataFrame:
    """Pick strongest candidates per sector and size using Kelly on prob_up and horizon payoffs."""
    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")
    df = daily_predictions_df.copy()

    if 'prob_up' not in df.columns and 'class_probs' in df.columns:
        positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
        def _sum_up(probs):
            if isinstance(probs, (list, tuple)) and len(probs) == K and positive_buckets:
                return float(sum(probs[i] for i in positive_buckets))
            return np.nan
        df['prob_up'] = df['class_probs'].apply(_sum_up)

    if 'prob_up' not in df.columns and 'predicted_prob' in df.columns:
        df['prob_up'] = df['predicted_prob']

    if 'expected_rise' not in df.columns:
        print("[PORT] Missing expected_rise; cannot size portfolio.")
        return pd.DataFrame()

    df = df[(df['prob_up'] >= sector_threshold) & (df['expected_rise'] > 0)]
    print(f"[PORT] {len(df)} tickers cleared prob_up ≥ {sector_threshold:.3f} and positive expected return.")
    if df.empty:
        return pd.DataFrame()

    winners = (df.sort_values(['sector', 'expected_rise'], ascending=[True, False])
                 .groupby('sector', as_index=False)
                 .head(1))
    if winners.empty:
        print("[PORT] No sector winners after grouping.")
        return pd.DataFrame()

    rows = []
    for _, row in winners.iterrows():
        ticker = row['ticker']
        sector = row['sector']
        p_up = float(row['prob_up'])
        payout = payout_map.get(ticker, {})
        b = payout.get('b') if isinstance(payout, dict) else float(payout)
        if not np.isfinite(b) or b <= 0:
            print(f"[PORT] Sector {sector}: skipping {ticker} due to invalid payout ratio {b}.")
            continue
        kelly_pct = p_up - (1.0 - p_up) / b
        if kelly_pct <= 0:
            print(f"[PORT] Sector {sector}: Kelly <= 0 for {ticker} (p_up={p_up:.3f}, b={b:.3f}).")
            continue
        investment_fraction = min(MAX_POSITION_SIZE, kelly_pct * kelly_fraction)
        investment_fraction = max(0.0, investment_fraction)
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            print(f"[PORT] Sector {sector}: allocation ${investment_amount:.2f} below minimum; skipping {ticker}.")
            continue
        print(f"[PORT] Sector {sector}: selecting {ticker} (p_up={p_up:.3f}, kelly={kelly_pct:.3f}) "
              f"with ${investment_amount:.2f} allocation")
        rows.append({
            'ticker': ticker,
            'sector': sector,
            'prob_up': p_up,
            'predicted_prob': p_up,
            'expected_rise': row['expected_rise'],
            'bucket_idx': row.get('bucket_idx', np.nan),
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount
        })

    if not rows:
        print("[PORT] All sector winners rejected after Kelly sizing.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [28]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    """Check the minimal set of artifacts needed for ordinal inference."""
    required = [
        f"{ticker}_lstmORD_H{H}.pt",      # model weights (ordinal head)
        f"{ticker}_scaler_H{H}.pkl",      # feature scaler
        f"{ticker}_seq_length_H{H}.pkl",  # sequence length
        f"{ticker}_mu_c_H{H}.pkl",        # per-class train means μ_c for expected return
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in required)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [29]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # precompute realized returns for settlement only (not used for training)
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker', 'date'])[ret_col].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    # overlapping book
    open_positions = []  # each: {'ticker','invest','entry_date','exit_date'}
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                if pd.notna(rH):
                    pnl = pos['invest'] * rH
                    total_pnl_today += pnl
                    print(f"[EXIT] {current_date}: {pos['ticker']} r={rH:.4f}, PnL=${pnl:.2f}")
                    capital += pos['invest'] + pnl  # release capital
            else:
                still_open.append(pos)
        open_positions = still_open

        # equity at START (after settlements, before new entries)
        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # build prediction universe using info strictly before current_date
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if i == 0:  # no yesterday slice for display
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                print("Retraining model for ticker:", ticker)
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)
        print(f"[SIM] {current_date}: built {len(daily_predictions_df)} predictions")
        if (not daily_predictions_df.empty and
            'predicted_prob' not in daily_predictions_df.columns and
            'calibrated_prediction' not in daily_predictions_df.columns):
            print("[WARN] predicted_prob missing from daily_predictions_df columns:",
                  sorted(daily_predictions_df.columns))


        # size raw trades via Kelly
        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df,
            payout_map_day,
            capital,
            sector_threshold=SECTOR_CONFIDENCE_THRESHOLD,
            kelly_fraction=KELLY_FRACTION,
        )
        if investment_decision_df.empty:
            print(f"[SIM] {current_date}: no trades proposed today.")
        else:
            print(f"[SIM] {current_date}: {len(investment_decision_df)} trades proposed.")

        # entry logic (allow_overlap controls laddering)
        exit_idx = i + H
        if exit_idx < len(unique_dates):
            exit_date = unique_dates[exit_idx]
        else:
            exit_date = None  # can't open new trades that we cannot exit within data

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            # ensure the column exists even if future changes rename it
            if 'predicted_prob' not in investment_decision_df.columns:
                if 'calibrated_prediction' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'calibrated_prediction': 'predicted_prob'}
                    )
                elif 'score' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'score': 'predicted_prob'}
                    )
                else:
                    # nothing to sort by
                    investment_decision_df = pd.DataFrame()

            if not investment_decision_df.empty:
                investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)


            # current exposures (post-settlement)
            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                # per-ticker ladder depth
                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue  # no overlapping allowed

                # base size from Kelly (already scaled by KELLY_FRACTION)
                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))  # vs equity

                # clamp by remaining budgets
                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                # lock capital and record position
                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})
                print(f"[TRADE] {current_date}: allocated ${amt:.2f} to {tkr} exiting on {exit_date}")

        # equity at END (after entries)
        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        # log the day
        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,  # cash only
            'capital_end': capital,                               # cash only
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,                # realized PnL today
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [30]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [31]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_features.parquet')

In [32]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)

columns_to_check = ['EMA_12', 'EMA_26','EMA_50','MACD_12_26_9','MACDh_12_26_9','MACDs_12_26_9','RSI_14','ATRr_14',
                    'STOCHRSIk_14_14_3_3','STOCHRSId_14_14_3_3','ATRr_14','BB_upper','BB_middle','BB_lower','OBV',
                    
                    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
                    # 'sector_ret_60d', 
                    'sector_vol_20d', 'sector_dispersion_1d',
                    # 'sector_rel_strength',
                    
                    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
                    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,sector_close_mean,sector_volume_mean,sector_ret_1d,sector_ret_5d,sector_ret_20d,sector_range,sector_vol_20d,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-12-13,75.878571,76.805717,75.114288,75.669998,156314900.0,AAPL,0.0,0.0,Consumer Goods,...,62.547998,19829560.0,-0.006623,-0.002006,0.056416,0.698142,0.008085,1554.712849,0.002853,0.005430
1,2012-12-14,73.535713,74.018570,72.225716,72.827141,252394800.0,AAPL,0.0,0.0,Consumer Goods,...,62.332714,29416920.0,-0.003442,-0.007518,0.045959,0.581286,0.008149,1550.069802,-0.007258,0.013233
2,2012-12-17,72.704285,74.285713,71.604286,74.118568,189401800.0,AAPL,0.0,0.0,Consumer Goods,...,62.372857,24089840.0,0.000644,-0.005215,0.039231,0.782143,0.008074,1562.391712,-0.017465,0.008229
3,2012-12-18,75.000000,76.414284,74.321426,76.271431,156421300.0,AAPL,0.0,0.0,Consumer Goods,...,62.862143,22884370.0,0.007845,-0.001921,0.021354,1.029286,0.006088,1572.637095,-0.030002,0.014815
4,2012-12-19,75.924286,76.242859,75.071426,75.187141,112342300.0,AAPL,0.0,0.0,Consumer Goods,...,62.554713,17363510.0,-0.004891,-0.006516,0.012048,0.846144,0.006179,1566.784191,-0.032355,0.010914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102535,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,61.025001,2428780.0,-0.001767,0.021766,-0.016313,0.593999,0.006240,3101.328695,-0.007883,0.005228
102536,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,61.073999,2215970.0,0.000803,0.015446,-0.022362,0.690000,0.005981,3102.507723,-0.016661,0.002030
102537,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,60.999000,2459030.0,-0.001228,0.010118,-0.024219,0.485999,0.005966,3128.753695,-0.017629,0.004873
102538,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,61.345000,4155760.0,0.005672,0.012494,-0.011871,0.461999,0.005997,3141.201722,-0.008376,0.006185
102539,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,61.787000,2870660.0,0.007205,0.010698,-0.007804,0.636000,0.006197,3136.813139,-0.001766,0.007085

In [33]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength']
Total number of features: 28

In [34]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,sector_close_mean,sector_volume_mean,sector_ret_1d,sector_ret_5d,sector_ret_20d,sector_range,sector_vol_20d,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-12-13,75.878571,76.805717,75.114288,75.669998,156314900.0,AAPL,0.0,0.0,Consumer Goods,...,62.547998,19829560.0,-0.006623,-0.002006,0.056416,0.698142,0.008085,1554.712849,0.002853,0.005430
1,2012-12-14,73.535713,74.018570,72.225716,72.827141,252394800.0,AAPL,0.0,0.0,Consumer Goods,...,62.332714,29416920.0,-0.003442,-0.007518,0.045959,0.581286,0.008149,1550.069802,-0.007258,0.013233
2,2012-12-17,72.704285,74.285713,71.604286,74.118568,189401800.0,AAPL,0.0,0.0,Consumer Goods,...,62.372857,24089840.0,0.000644,-0.005215,0.039231,0.782143,0.008074,1562.391712,-0.017465,0.008229
3,2012-12-18,75.000000,76.414284,74.321426,76.271431,156421300.0,AAPL,0.0,0.0,Consumer Goods,...,62.862143,22884370.0,0.007845,-0.001921,0.021354,1.029286,0.006088,1572.637095,-0.030002,0.014815
4,2012-12-19,75.924286,76.242859,75.071426,75.187141,112342300.0,AAPL,0.0,0.0,Consumer Goods,...,62.554713,17363510.0,-0.004891,-0.006516,0.012048,0.846144,0.006179,1566.784191,-0.032355,0.010914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102535,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,61.025001,2428780.0,-0.001767,0.021766,-0.016313,0.593999,0.006240,3101.328695,-0.007883,0.005228
102536,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,61.073999,2215970.0,0.000803,0.015446,-0.022362,0.690000,0.005981,3102.507723,-0.016661,0.002030
102537,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,60.999000,2459030.0,-0.001228,0.010118,-0.024219,0.485999,0.005966,3128.753695,-0.017629,0.004873
102538,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,61.345000,4155760.0,0.005672,0.012494,-0.011871,0.461999,0.005997,3141.201722,-0.008376,0.006185
102539,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,61.787000,2870660.0,0.007205,0.010698,-0.007804,0.636000,0.006197,3136.813139,-0.001766,0.007085

# Execute Pipeline

In [35]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=1,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Starting simulation with 1100 initial training days... (H=1)
Starting predictions from day 1100 (after 1100 training days)

Simulating Trading Days:   0%|          | 0/89 [00:00<?, ?it/s]

Retraining model for ticker: AAPL
[TRAIN] AAPL: preparing data (H=1) with 1099 rows
[TRAIN] AAPL: built 1087 sequences (seq_len=12)
[TRAIN] AAPL: scaler fitted on 869 training sequences
[TRAIN] AAPL: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AAPL: model n_features = 28
[CAL] AAPL: taus=[0.8  0.72 0.52 0.4  0.28] | temperature=0.871
[SAVE] AAPL: stored taus
[SAVE] AAPL: stored temperature scale 0.871
[SAVE] AAPL: artifacts persisted (H=1)
[CAL] AAPL: loaded taus [0.8  0.72 0.52 0.4  0.28]
[CAL] AAPL: temperature scaling 0.871
Retraining model for ticker: ABB
[TRAIN] ABB: preparing data (H=1) with 1099 rows
[TRAIN] ABB: built 1087 sequences (seq_len=12)
[TRAIN] ABB: scaler fitted on 869 training sequences
[TRAIN] ABB: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] ABB: model n_features = 28
[CAL] ABB: taus=[0.74 0.52 0.56 0.54 0.48] | temperature=0.871
[SAVE] ABB: stored taus
[SAVE] ABB: stored temperature scale 0.871
[SAVE] ABB: artifacts persisted (H=1)
[CAL] ABB: loaded taus [0.74 0.52 0.56 0.54 0.48]
[CAL] ABB: temperature scaling 0.871
Retraining model for ticker: ABBV
[TRAIN] ABBV: preparing data (H=1) with 1038 rows
[TRAIN] ABBV: built 1026 sequences (seq_len=12)
[TRAIN] ABBV: scaler fitted on 820 training sequences
[TRAIN] ABBV: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] ABBV: model n_features = 28
[CAL] ABBV: taus=[0.78 0.72 0.56 0.48 0.4 ] | temperature=1.007
[SAVE] ABBV: stored taus
[SAVE] ABBV: stored temperature scale 1.007
[SAVE] ABBV: artifacts persisted (H=1)
[CAL] ABBV: loaded taus [0.78 0.72 0.56 0.48 0.4 ]
[CAL] ABBV: temperature scaling 1.007
Retraining model for ticker: AEP
[TRAIN] AEP: preparing data (H=1) with 1099 rows
[TRAIN] AEP: built 1087 sequences (seq_len=12)
[TRAIN] AEP: scaler fitted on 869 training sequences
[TRAIN] AEP: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AEP: model n_features = 28
[CAL] AEP: taus=[0.64 0.48 0.48 0.36 0.42] | temperature=1.414
[SAVE] AEP: stored taus
[SAVE] AEP: stored temperature scale 1.414
[SAVE] AEP: artifacts persisted (H=1)
[CAL] AEP: loaded taus [0.64 0.48 0.48 0.36 0.42]
[CAL] AEP: temperature scaling 1.414
Retraining model for ticker: AGFS
[TRAIN] AGFS: preparing data (H=1) with 562 rows
[TRAIN] AGFS: built 550 sequences (seq_len=12)
[TRAIN] AGFS: scaler fitted on 440 training sequences
[TRAIN] AGFS: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AGFS: model n_features = 28
[CAL] AGFS: taus=[0.8  0.72 0.5  0.46 0.38] | temperature=1.279
[SAVE] AGFS: stored taus
[SAVE] AGFS: stored temperature scale 1.279
[SAVE] AGFS: artifacts persisted (H=1)
[CAL] AGFS: loaded taus [0.8  0.72 0.5  0.46 0.38]
[CAL] AGFS: temperature scaling 1.279
Retraining model for ticker: AMGN
[TRAIN] AMGN: preparing data (H=1) with 1099 rows
[TRAIN] AMGN: built 1087 sequences (seq_len=12)
[TRAIN] AMGN: scaler fitted on 869 training sequences
[TRAIN] AMGN: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AMGN: model n_features = 28
[CAL] AMGN: taus=[0.78 0.68 0.52 0.5  0.62] | temperature=0.600
[SAVE] AMGN: stored taus
[SAVE] AMGN: stored temperature scale 0.600
[SAVE] AMGN: artifacts persisted (H=1)
[CAL] AMGN: loaded taus [0.78 0.68 0.52 0.5  0.62]
[CAL] AMGN: temperature scaling 0.600
Retraining model for ticker: AMZN
[TRAIN] AMZN: preparing data (H=1) with 1099 rows
[TRAIN] AMZN: built 1087 sequences (seq_len=12)
[TRAIN] AMZN: scaler fitted on 869 training sequences
[TRAIN] AMZN: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AMZN: model n_features = 28
[CAL] AMZN: taus=[0.2  0.74 0.52 0.44 0.22] | temperature=0.871
[SAVE] AMZN: stored taus
[SAVE] AMZN: stored temperature scale 0.871
[SAVE] AMZN: artifacts persisted (H=1)
[CAL] AMZN: loaded taus [0.2  0.74 0.52 0.44 0.22]
[CAL] AMZN: temperature scaling 0.871
Retraining model for ticker: BA
[TRAIN] BA: preparing data (H=1) with 1099 rows
[TRAIN] BA: built 1087 sequences (seq_len=12)
[TRAIN] BA: scaler fitted on 869 training sequences
[TRAIN] BA: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BA: model n_features = 28
[CAL] BA: taus=[0.8  0.78 0.5  0.4  0.24] | temperature=0.600
[SAVE] BA: stored taus
[SAVE] BA: stored temperature scale 0.600
[SAVE] BA: artifacts persisted (H=1)
[CAL] BA: loaded taus [0.8  0.78 0.5  0.4  0.24]
[CAL] BA: temperature scaling 0.600
Retraining model for ticker: BABA
[TRAIN] BABA: preparing data (H=1) with 606 rows
[TRAIN] BABA: built 594 sequences (seq_len=12)
[TRAIN] BABA: scaler fitted on 475 training sequences
[TRAIN] BABA: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BABA: model n_features = 28
[CAL] BABA: taus=[0.64 0.8  0.42 0.56 0.42] | temperature=0.736
[SAVE] BABA: stored taus
[SAVE] BABA: stored temperature scale 0.736
[SAVE] BABA: artifacts persisted (H=1)
[CAL] BABA: loaded taus [0.64 0.8  0.42 0.56 0.42]
[CAL] BABA: temperature scaling 0.736
Retraining model for ticker: BAC
[TRAIN] BAC: preparing data (H=1) with 1099 rows
[TRAIN] BAC: built 1087 sequences (seq_len=12)
[TRAIN] BAC: scaler fitted on 869 training sequences
[TRAIN] BAC: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BAC: model n_features = 28
[CAL] BAC: taus=[0.8  0.74 0.58 0.46 0.72] | temperature=1.007
[SAVE] BAC: stored taus
[SAVE] BAC: stored temperature scale 1.007
[SAVE] BAC: artifacts persisted (H=1)
[CAL] BAC: loaded taus [0.8  0.74 0.58 0.46 0.72]
[CAL] BAC: temperature scaling 1.007
Retraining model for ticker: BBL
[TRAIN] BBL: preparing data (H=1) with 1099 rows
[TRAIN] BBL: built 1087 sequences (seq_len=12)
[TRAIN] BBL: scaler fitted on 869 training sequences
[TRAIN] BBL: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BBL: model n_features = 28
[CAL] BBL: taus=[0.78 0.66 0.5  0.44 0.4 ] | temperature=1.143
[SAVE] BBL: stored taus
[SAVE] BBL: stored temperature scale 1.143
[SAVE] BBL: artifacts persisted (H=1)
[CAL] BBL: loaded taus [0.78 0.66 0.5  0.44 0.4 ]
[CAL] BBL: temperature scaling 1.143
Retraining model for ticker: BCH
[TRAIN] BCH: preparing data (H=1) with 1099 rows
[TRAIN] BCH: built 1087 sequences (seq_len=12)
[TRAIN] BCH: scaler fitted on 869 training sequences
[TRAIN] BCH: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BCH: model n_features = 28
[CAL] BCH: taus=[0.8  0.52 0.56 0.3  0.42] | temperature=0.736
[SAVE] BCH: stored taus
[SAVE] BCH: stored temperature scale 0.736
[SAVE] BCH: artifacts persisted (H=1)
[CAL] BCH: loaded taus [0.8  0.52 0.56 0.3  0.42]
[CAL] BCH: temperature scaling 0.736
Retraining model for ticker: BHP
[TRAIN] BHP: preparing data (H=1) with 1099 rows
[TRAIN] BHP: built 1087 sequences (seq_len=12)
[TRAIN] BHP: scaler fitted on 869 training sequences
[TRAIN] BHP: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BHP: model n_features = 28
[CAL] BHP: taus=[0.7  0.2  0.54 0.46 0.42] | temperature=1.279
[SAVE] BHP: stored taus
[SAVE] BHP: stored temperature scale 1.279
[SAVE] BHP: artifacts persisted (H=1)
[CAL] BHP: loaded taus [0.7  0.2  0.54 0.46 0.42]
[CAL] BHP: temperature scaling 1.279
Retraining model for ticker: BP
[TRAIN] BP: preparing data (H=1) with 1099 rows
[TRAIN] BP: built 1087 sequences (seq_len=12)
[TRAIN] BP: scaler fitted on 869 training sequences
[TRAIN] BP: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BP: model n_features = 28
[CAL] BP: taus=[0.2  0.8  0.54 0.46 0.34] | temperature=0.600
[SAVE] BP: stored taus
[SAVE] BP: stored temperature scale 0.600
[SAVE] BP: artifacts persisted (H=1)
[CAL] BP: loaded taus [0.2  0.8  0.54 0.46 0.34]
[CAL] BP: temperature scaling 0.600
Retraining model for ticker: BRK-A
[TRAIN] BRK-A: preparing data (H=1) with 1099 rows
[TRAIN] BRK-A: built 1087 sequences (seq_len=12)
[TRAIN] BRK-A: scaler fitted on 869 training sequences
[TRAIN] BRK-A: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BRK-A: model n_features = 28
[CAL] BRK-A: taus=[0.8  0.78 0.44 0.54 0.42] | temperature=0.871
[SAVE] BRK-A: stored taus
[SAVE] BRK-A: stored temperature scale 0.871
[SAVE] BRK-A: artifacts persisted (H=1)
[CAL] BRK-A: loaded taus [0.8  0.78 0.44 0.54 0.42]
[CAL] BRK-A: temperature scaling 0.871
Retraining model for ticker: BSAC
[TRAIN] BSAC: preparing data (H=1) with 1099 rows
[TRAIN] BSAC: built 1087 sequences (seq_len=12)
[TRAIN] BSAC: scaler fitted on 869 training sequences
[TRAIN] BSAC: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BSAC: model n_features = 28
[CAL] BSAC: taus=[0.78 0.5  0.48 0.24 0.22] | temperature=0.736
[SAVE] BSAC: stored taus
[SAVE] BSAC: stored temperature scale 0.736
[SAVE] BSAC: artifacts persisted (H=1)
[CAL] BSAC: loaded taus [0.78 0.5  0.48 0.24 0.22]
[CAL] BSAC: temperature scaling 0.736
Retraining model for ticker: BUD
[TRAIN] BUD: preparing data (H=1) with 1099 rows
[TRAIN] BUD: built 1087 sequences (seq_len=12)
[TRAIN] BUD: scaler fitted on 869 training sequences
[TRAIN] BUD: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BUD: model n_features = 28
[CAL] BUD: taus=[0.74 0.68 0.52 0.5  0.5 ] | temperature=1.550
[SAVE] BUD: stored taus
[SAVE] BUD: stored temperature scale 1.550
[SAVE] BUD: artifacts persisted (H=1)
[CAL] BUD: loaded taus [0.74 0.68 0.52 0.5  0.5 ]
[CAL] BUD: temperature scaling 1.550
Retraining model for ticker: C
[TRAIN] C: preparing data (H=1) with 1099 rows
[TRAIN] C: built 1087 sequences (seq_len=12)
[TRAIN] C: scaler fitted on 869 training sequences
[TRAIN] C: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] C: model n_features = 28
[CAL] C: taus=[0.8  0.72 0.38 0.38 0.36] | temperature=1.007
[SAVE] C: stored taus
[SAVE] C: stored temperature scale 1.007
[SAVE] C: artifacts persisted (H=1)
[CAL] C: loaded taus [0.8  0.72 0.38 0.38 0.36]
[CAL] C: temperature scaling 1.007
Retraining model for ticker: CAT
[TRAIN] CAT: preparing data (H=1) with 1099 rows
[TRAIN] CAT: built 1087 sequences (seq_len=12)
[TRAIN] CAT: scaler fitted on 869 training sequences
[TRAIN] CAT: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CAT: model n_features = 28
[CAL] CAT: taus=[0.78 0.54 0.52 0.5  0.58] | temperature=1.686
[SAVE] CAT: stored taus
[SAVE] CAT: stored temperature scale 1.686
[SAVE] CAT: artifacts persisted (H=1)
[CAL] CAT: loaded taus [0.78 0.54 0.52 0.5  0.58]
[CAL] CAT: temperature scaling 1.686
Retraining model for ticker: CELG
[TRAIN] CELG: preparing data (H=1) with 1099 rows
[TRAIN] CELG: built 1087 sequences (seq_len=12)
[TRAIN] CELG: scaler fitted on 869 training sequences
[TRAIN] CELG: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CELG: model n_features = 28
[CAL] CELG: taus=[0.72 0.72 0.46 0.46 0.38] | temperature=0.871
[SAVE] CELG: stored taus
[SAVE] CELG: stored temperature scale 0.871
[SAVE] CELG: artifacts persisted (H=1)
[CAL] CELG: loaded taus [0.72 0.72 0.46 0.46 0.38]
[CAL] CELG: temperature scaling 0.871
Retraining model for ticker: CHL
[TRAIN] CHL: preparing data (H=1) with 1099 rows
[TRAIN] CHL: built 1087 sequences (seq_len=12)
[TRAIN] CHL: scaler fitted on 869 training sequences
[TRAIN] CHL: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CHL: model n_features = 28
[CAL] CHL: taus=[0.78 0.48 0.52 0.4  0.28] | temperature=0.736
[SAVE] CHL: stored taus
[SAVE] CHL: stored temperature scale 0.736
[SAVE] CHL: artifacts persisted (H=1)
[CAL] CHL: loaded taus [0.78 0.48 0.52 0.4  0.28]
[CAL] CHL: temperature scaling 0.736
Retraining model for ticker: CHTR
[TRAIN] CHTR: preparing data (H=1) with 1099 rows
[TRAIN] CHTR: built 1087 sequences (seq_len=12)
[TRAIN] CHTR: scaler fitted on 869 training sequences
[TRAIN] CHTR: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CHTR: model n_features = 28
[CAL] CHTR: taus=[0.8  0.7  0.44 0.46 0.38] | temperature=1.007
[SAVE] CHTR: stored taus
[SAVE] CHTR: stored temperature scale 1.007
[SAVE] CHTR: artifacts persisted (H=1)
[CAL] CHTR: loaded taus [0.8  0.7  0.44 0.46 0.38]
[CAL] CHTR: temperature scaling 1.007
Retraining model for ticker: CMCSA
[TRAIN] CMCSA: preparing data (H=1) with 1099 rows
[TRAIN] CMCSA: built 1087 sequences (seq_len=12)
[TRAIN] CMCSA: scaler fitted on 869 training sequences
[TRAIN] CMCSA: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CMCSA: model n_features = 28
[CAL] CMCSA: taus=[0.74 0.64 0.52 0.46 0.42] | temperature=1.550
[SAVE] CMCSA: stored taus
[SAVE] CMCSA: stored temperature scale 1.550
[SAVE] CMCSA: artifacts persisted (H=1)
[CAL] CMCSA: loaded taus [0.74 0.64 0.52 0.46 0.42]
[CAL] CMCSA: temperature scaling 1.550
Retraining model for ticker: CODI
[TRAIN] CODI: preparing data (H=1) with 1099 rows
[TRAIN] CODI: built 1087 sequences (seq_len=12)
[TRAIN] CODI: scaler fitted on 869 training sequences
[TRAIN] CODI: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CODI: model n_features = 28
[CAL] CODI: taus=[0.74 0.6  0.58 0.5  0.44] | temperature=1.279
[SAVE] CODI: stored taus
[SAVE] CODI: stored temperature scale 1.279
[SAVE] CODI: artifacts persisted (H=1)
[CAL] CODI: loaded taus [0.74 0.6  0.58 0.5  0.44]
[CAL] CODI: temperature scaling 1.279
Retraining model for ticker: CSCO
[TRAIN] CSCO: preparing data (H=1) with 1099 rows
[TRAIN] CSCO: built 1087 sequences (seq_len=12)
[TRAIN] CSCO: scaler fitted on 869 training sequences
[TRAIN] CSCO: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CSCO: model n_features = 28
[CAL] CSCO: taus=[0.8  0.72 0.7  0.48 0.48] | temperature=0.871
[SAVE] CSCO: stored taus
[SAVE] CSCO: stored temperature scale 0.871
[SAVE] CSCO: artifacts persisted (H=1)
[CAL] CSCO: loaded taus [0.8  0.72 0.7  0.48 0.48]
[CAL] CSCO: temperature scaling 0.871
Retraining model for ticker: CVX
[TRAIN] CVX: preparing data (H=1) with 1099 rows
[TRAIN] CVX: built 1087 sequences (seq_len=12)
[TRAIN] CVX: scaler fitted on 869 training sequences
[TRAIN] CVX: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CVX: model n_features = 28
[CAL] CVX: taus=[0.74 0.78 0.46 0.46 0.32] | temperature=0.871
[SAVE] CVX: stored taus
[SAVE] CVX: stored temperature scale 0.871
[SAVE] CVX: artifacts persisted (H=1)
[CAL] CVX: loaded taus [0.74 0.78 0.46 0.46 0.32]
[CAL] CVX: temperature scaling 0.871
Retraining model for ticker: D
[TRAIN] D: preparing data (H=1) with 1099 rows
[TRAIN] D: built 1087 sequences (seq_len=12)
[TRAIN] D: scaler fitted on 869 training sequences
[TRAIN] D: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] D: model n_features = 28
[CAL] D: taus=[0.8  0.7  0.46 0.38 0.38] | temperature=0.736
[SAVE] D: stored taus
[SAVE] D: stored temperature scale 0.736
[SAVE] D: artifacts persisted (H=1)
[CAL] D: loaded taus [0.8  0.7  0.46 0.38 0.38]
[CAL] D: temperature scaling 0.736
Retraining model for ticker: DHR
[TRAIN] DHR: preparing data (H=1) with 1099 rows
[TRAIN] DHR: built 1087 sequences (seq_len=12)
[TRAIN] DHR: scaler fitted on 869 training sequences
[TRAIN] DHR: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] DHR: model n_features = 28
[CAL] DHR: taus=[0.72 0.58 0.5  0.44 0.4 ] | temperature=1.414
[SAVE] DHR: stored taus
[SAVE] DHR: stored temperature scale 1.414
[SAVE] DHR: artifacts persisted (H=1)
[CAL] DHR: loaded taus [0.72 0.58 0.5  0.44 0.4 ]
[CAL] DHR: temperature scaling 1.414
Retraining model for ticker: DIS
[TRAIN] DIS: preparing data (H=1) with 1099 rows
[TRAIN] DIS: built 1087 sequences (seq_len=12)
[TRAIN] DIS: scaler fitted on 869 training sequences
[TRAIN] DIS: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] DIS: model n_features = 28
[CAL] DIS: taus=[0.76 0.54 0.48 0.34 0.24] | temperature=0.871
[SAVE] DIS: stored taus
[SAVE] DIS: stored temperature scale 0.871
[SAVE] DIS: artifacts persisted (H=1)
[CAL] DIS: loaded taus [0.76 0.54 0.48 0.34 0.24]
[CAL] DIS: temperature scaling 0.871
Retraining model for ticker: DUK
[TRAIN] DUK: preparing data (H=1) with 1099 rows
[TRAIN] DUK: built 1087 sequences (seq_len=12)
[TRAIN] DUK: scaler fitted on 869 training sequences
[TRAIN] DUK: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] DUK: model n_features = 28
[CAL] DUK: taus=[0.8  0.74 0.6  0.5  0.4 ] | temperature=1.143
[SAVE] DUK: stored taus
[SAVE] DUK: stored temperature scale 1.143
[SAVE] DUK: artifacts persisted (H=1)
[CAL] DUK: loaded taus [0.8  0.74 0.6  0.5  0.4 ]
[CAL] DUK: temperature scaling 1.143
Retraining model for ticker: EXC
[TRAIN] EXC: preparing data (H=1) with 1099 rows
[TRAIN] EXC: built 1087 sequences (seq_len=12)
[TRAIN] EXC: scaler fitted on 869 training sequences
[TRAIN] EXC: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] EXC: model n_features = 28
[CAL] EXC: taus=[0.66 0.54 0.5  0.46 0.46] | temperature=2.093
[SAVE] EXC: stored taus
[SAVE] EXC: stored temperature scale 2.093
[SAVE] EXC: artifacts persisted (H=1)
[CAL] EXC: loaded taus [0.66 0.54 0.5  0.46 0.46]
[CAL] EXC: temperature scaling 2.093
Retraining model for ticker: FB
[TRAIN] FB: preparing data (H=1) with 1099 rows
[TRAIN] FB: built 1087 sequences (seq_len=12)
[TRAIN] FB: scaler fitted on 869 training sequences
[TRAIN] FB: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] FB: model n_features = 28
[CAL] FB: taus=[0.76 0.64 0.52 0.2  0.28] | temperature=1.143
[SAVE] FB: stored taus
[SAVE] FB: stored temperature scale 1.143
[SAVE] FB: artifacts persisted (H=1)
[CAL] FB: loaded taus [0.76 0.64 0.52 0.2  0.28]
[CAL] FB: temperature scaling 1.143
Retraining model for ticker: GD
[TRAIN] GD: preparing data (H=1) with 1099 rows
[TRAIN] GD: built 1087 sequences (seq_len=12)
[TRAIN] GD: scaler fitted on 869 training sequences
[TRAIN] GD: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] GD: model n_features = 28
[CAL] GD: taus=[0.78 0.72 0.54 0.38 0.48] | temperature=0.600
[SAVE] GD: stored taus
[SAVE] GD: stored temperature scale 0.600
[SAVE] GD: artifacts persisted (H=1)
[CAL] GD: loaded taus [0.78 0.72 0.54 0.38 0.48]
[CAL] GD: temperature scaling 0.600
Retraining model for ticker: GE
[TRAIN] GE: preparing data (H=1) with 1099 rows
[TRAIN] GE: built 1087 sequences (seq_len=12)
[TRAIN] GE: scaler fitted on 869 training sequences
[TRAIN] GE: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] GE: model n_features = 28
[CAL] GE: taus=[0.8  0.72 0.38 0.46 0.38] | temperature=1.007
[SAVE] GE: stored taus
[SAVE] GE: stored temperature scale 1.007
[SAVE] GE: artifacts persisted (H=1)
[CAL] GE: loaded taus [0.8  0.72 0.38 0.46 0.38]
[CAL] GE: temperature scaling 1.007
Retraining model for ticker: GMRE
[TRAIN] GMRE: preparing data (H=1) with 158 rows
[TRAIN] GMRE: built 146 sequences (seq_len=12)
[TRAIN] GMRE: scaler fitted on 116 training sequences
[TRAIN] GMRE: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] GMRE: model n_features = 28
[CAL] GMRE: taus=[0.52 0.48 0.36 0.3  0.24] | temperature=1.686
[SAVE] GMRE: stored taus
[SAVE] GMRE: stored temperature scale 1.686
[SAVE] GMRE: artifacts persisted (H=1)
[CAL] GMRE: loaded taus [0.52 0.48 0.36 0.3  0.24]
[CAL] GMRE: temperature scaling 1.686
Retraining model for ticker: GOOG
[TRAIN] GOOG: preparing data (H=1) with 1099 rows
[TRAIN] GOOG: built 1087 sequences (seq_len=12)
[TRAIN] GOOG: scaler fitted on 869 training sequences
[TRAIN] GOOG: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] GOOG: model n_features = 28
[CAL] GOOG: taus=[0.74 0.52 0.52 0.48 0.44] | temperature=1.007
[SAVE] GOOG: stored taus
[SAVE] GOOG: stored temperature scale 1.007
[SAVE] GOOG: artifacts persisted (H=1)
[CAL] GOOG: loaded taus [0.74 0.52 0.52 0.48 0.44]
[CAL] GOOG: temperature scaling 1.007
Retraining model for ticker: HD
[TRAIN] HD: preparing data (H=1) with 1099 rows
[TRAIN] HD: built 1087 sequences (seq_len=12)
[TRAIN] HD: scaler fitted on 869 training sequences
[TRAIN] HD: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] HD: model n_features = 28
[CAL] HD: taus=[0.62 0.54 0.48 0.42 0.34] | temperature=2.229
[SAVE] HD: stored taus
[SAVE] HD: stored temperature scale 2.229
[SAVE] HD: artifacts persisted (H=1)
[CAL] HD: loaded taus [0.62 0.54 0.48 0.42 0.34]
[CAL] HD: temperature scaling 2.229
Retraining model for ticker: HON
[TRAIN] HON: preparing data (H=1) with 1099 rows

Simulating Trading Days:   1%|          | 1/89 [38:37<56:38:20, 2317.05s/it]

[CAL] XOM: taus=[0.78 0.66 0.48 0.36 0.26] | temperature=0.600
[SAVE] XOM: stored taus
[SAVE] XOM: stored temperature scale 0.600
[SAVE] XOM: artifacts persisted (H=1)
[CAL] XOM: loaded taus [0.78 0.66 0.48 0.36 0.26]
[CAL] XOM: temperature scaling 0.600
[SIM] 2017-04-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.831, kelly=0.639) with $6392.41 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.634, kelly=0.283) with $2830.73 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.838, kelly=0.678) with $6778.09 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.770, kelly=0.542) with $5416.16 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.748, kelly=0.495) with $4946.88 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.834, kelly=0.660) with $6595.63 allocation
[PORT] Sector Services: selecting WMT (p_up=0.740, kelly=0.475) with $4754.22 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.688, kelly=0.372) with $3719.92 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.613, kelly=0.206) with $2060.29 allocation
[SIM] 2017-04-28 00:00:00: 9 trades proposed.
[TRADE] 2017-04-28 00:00:00: allocated $6778.09 to PM exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $6595.63 to ABB exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $6392.41 to RDS-B exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $5416.16 to HSBC exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $4817.70 to NVS exiting on 2017-05-01 00:00:00
[EXIT] 2017-05-01 00:00:00: PM r=-0.0026, PnL=$-17.73
[EXIT] 2017-05-01 00:00:00: ABB r=-0.0012, PnL=$-8.04
[EXIT] 2017-05-01 00:00:00: RDS-B r=-0.0017, PnL=$-10.63
[EXIT] 2017-05-01 00:00:00: HSBC r=0.0027, PnL=$14.47
[EXIT] 2017-05-01 00:00:00: NVS r=-0.0004, PnL=$-1.88

Simulating Trading Days:   2%|▏         | 2/89 [38:39<23:05:24, 955.46s/it]

[SIM] 2017-05-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.834, kelly=0.646) with $6461.69 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.630, kelly=0.277) with $2769.51 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.845, kelly=0.690) with $6902.32 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.806, kelly=0.639) with $6391.77 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.690, kelly=0.379) with $3787.09 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.799, kelly=0.588) with $5880.89 allocation
[PORT] Sector Services: selecting WMT (p_up=0.738, kelly=0.471) with $4712.80 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.667, kelly=0.365) with $3644.63 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.613, kelly=0.208) with $2075.53 allocation
[SIM] 2017-05-01 00:00:00: 9 trades proposed.
[TRADE] 2017-05-01 00:00:00: allocated $6902.32 to PM exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $6461.69 to RDS-B exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $6391.77 to BRK-A exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $5880.89 to ABB exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $4356.19 to WMT exiting on 2017-05-02 00:00:00
[EXIT] 2017-05-02 00:00:00: PM r=-0.0007, PnL=$-5.00
[EXIT] 2017-05-02 00:00:00: RDS-B r=-0.0054, PnL=$-34.68
[EXIT] 2017-05-02 00:00:00: BRK-A r=0.0030, PnL=$19.05
[EXIT] 2017-05-02 00:00:00: ABB r=0.0053, PnL=$31.12
[EXIT] 2017-05-02 00:00:00: WMT r=0.0039, PnL=$16.79

Simulating Trading Days:   3%|▎         | 3/89 [38:41<12:25:35, 520.18s/it]

[SIM] 2017-05-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.838, kelly=0.655) with $6550.39 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.633, kelly=0.281) with $2811.11 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.849, kelly=0.698) with $6984.48 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.810, kelly=0.647) with $6465.55 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.621, kelly=0.242) with $2415.26 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.751, kelly=0.490) with $4904.33 allocation
[PORT] Sector Services: selecting UPS (p_up=0.797, kelly=0.590) with $5903.16 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.697, kelly=0.421) with $4207.48 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.618, kelly=0.217) with $2169.15 allocation
[SIM] 2017-05-02 00:00:00: 9 trades proposed.
[TRADE] 2017-05-02 00:00:00: allocated $6984.48 to PM exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $6550.39 to RDS-B exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $6465.55 to BRK-A exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $5903.16 to UPS exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $4097.47 to ABB exiting on 2017-05-03 00:00:00
[EXIT] 2017-05-03 00:00:00: PM r=0.0013, PnL=$8.85
[EXIT] 2017-05-03 00:00:00: RDS-B r=0.0095, PnL=$62.16
[EXIT] 2017-05-03 00:00:00: BRK-A r=0.0040, PnL=$25.71
[EXIT] 2017-05-03 00:00:00: UPS r=0.0040, PnL=$23.74
[EXIT] 2017-05-03 00:00:00: ABB r=-0.0036, PnL=$-14.93

Simulating Trading Days:   4%|▍         | 4/89 [38:43<7:27:13, 315.68s/it]

[SIM] 2017-05-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.841, kelly=0.662) with $6625.73 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.633, kelly=0.277) with $2775.00 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.851, kelly=0.704) with $7047.12 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.805, kelly=0.639) with $6395.41 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.607, kelly=0.201) with $2011.46 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.690, kelly=0.365) with $3652.91 allocation
[PORT] Sector Services: selecting UPS (p_up=0.840, kelly=0.678) with $6786.04 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.722, kelly=0.469) with $4692.56 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.622, kelly=0.226) with $2261.24 allocation
[SIM] 2017-05-03 00:00:00: 9 trades proposed.
[TRADE] 2017-05-03 00:00:00: allocated $7047.12 to PM exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $6625.73 to RDS-B exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $6786.04 to UPS exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $6395.41 to BRK-A exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $3178.41 to CSCO exiting on 2017-05-04 00:00:00
[EXIT] 2017-05-04 00:00:00: PM r=0.0053, PnL=$37.59
[EXIT] 2017-05-04 00:00:00: RDS-B r=-0.0011, PnL=$-7.33
[EXIT] 2017-05-04 00:00:00: UPS r=-0.0028, PnL=$-18.96
[EXIT] 2017-05-04 00:00:00: BRK-A r=-0.0018, PnL=$-11.77
[EXIT] 2017-05-04 00:00:00: CSCO r=-0.0020, PnL=$-6.50

Simulating Trading Days:   6%|▌         | 5/89 [38:45<4:43:41, 202.63s/it]

[SIM] 2017-05-04 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.848, kelly=0.676) with $6767.71 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.651, kelly=0.312) with $3127.36 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.852, kelly=0.704) with $7050.86 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.798, kelly=0.625) with $6259.62 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.589, kelly=0.200) with $2005.18 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.687, kelly=0.385) with $3854.76 allocation
[PORT] Sector Services: selecting UPS (p_up=0.846, kelly=0.689) with $6900.29 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.743, kelly=0.508) with $5085.14 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.625, kelly=0.230) with $2302.57 allocation
[SIM] 2017-05-04 00:00:00: 9 trades proposed.
[TRADE] 2017-05-04 00:00:00: allocated $7050.86 to PM exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $6767.71 to RDS-B exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $6900.29 to UPS exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $6259.62 to BRK-A exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $3052.14 to CSCO exiting on 2017-05-05 00:00:00
[EXIT] 2017-05-05 00:00:00: PM r=0.0094, PnL=$66.58
[EXIT] 2017-05-05 00:00:00: RDS-B r=0.0349, PnL=$236.04
[EXIT] 2017-05-05 00:00:00: UPS r=0.0035, PnL=$24.49
[EXIT] 2017-05-05 00:00:00: BRK-A r=0.0018, PnL=$11.54
[EXIT] 2017-05-05 00:00:00: CSCO r=0.0061, PnL=$18.75

Simulating Trading Days:   7%|▋         | 6/89 [38:48<3:06:02, 134.49s/it]

[SIM] 2017-05-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.849, kelly=0.678) with $6815.13 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.672, kelly=0.355) with $3562.80 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.851, kelly=0.704) with $7072.59 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.794, kelly=0.617) with $6201.89 allocation
[PORT] Sector Healthcare: selecting JNJ (p_up=0.592, kelly=0.206) with $2071.73 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.723, kelly=0.457) with $4589.71 allocation
[PORT] Sector Services: selecting BABA (p_up=0.800, kelly=0.615) with $6181.52 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.757, kelly=0.536) with $5384.47 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.661, kelly=0.305) with $3061.43 allocation
[SIM] 2017-05-05 00:00:00: 9 trades proposed.
[TRADE] 2017-05-05 00:00:00: allocated $7072.59 to PM exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $6815.13 to RDS-B exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $6181.52 to BABA exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $6201.89 to BRK-A exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $3866.70 to CSCO exiting on 2017-05-08 00:00:00
[EXIT] 2017-05-08 00:00:00: PM r=0.0034, PnL=$23.94
[EXIT] 2017-05-08 00:00:00: RDS-B r=0.0057, PnL=$38.89
[EXIT] 2017-05-08 00:00:00: BABA r=0.0071, PnL=$43.68
[EXIT] 2017-05-08 00:00:00: BRK-A r=-0.0114, PnL=$-70.45
[EXIT] 2017-05-08 00:00:00: CSCO r=-0.0029, PnL=$-11.24

Simulating Trading Days:   8%|▊         | 7/89 [38:50<2:04:41, 91.24s/it]

[SIM] 2017-05-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.842, kelly=0.664) with $6668.72 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.699, kelly=0.407) with $4090.20 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.845, kelly=0.691) with $6946.83 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.794, kelly=0.617) with $6199.81 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.630, kelly=0.249) with $2500.10 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.749, kelly=0.507) with $5096.94 allocation
[PORT] Sector Services: selecting BABA (p_up=0.813, kelly=0.639) with $6423.40 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.768, kelly=0.556) with $5585.36 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.690, kelly=0.364) with $3656.17 allocation
[SIM] 2017-05-08 00:00:00: 9 trades proposed.
[TRADE] 2017-05-08 00:00:00: allocated $6946.83 to PM exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $6668.72 to RDS-B exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $6423.40 to BABA exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $6199.81 to BRK-A exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $3906.51 to CSCO exiting on 2017-05-09 00:00:00
[EXIT] 2017-05-09 00:00:00: PM r=-0.0062, PnL=$-43.17
[EXIT] 2017-05-09 00:00:00: RDS-B r=-0.0027, PnL=$-17.74
[EXIT] 2017-05-09 00:00:00: BABA r=0.0269, PnL=$172.60
[EXIT] 2017-05-09 00:00:00: BRK-A r=-0.0047, PnL=$-29.10
[EXIT] 2017-05-09 00:00:00: CSCO r=-0.0114, PnL=$-44.43

Simulating Trading Days:   9%|▉         | 8/89 [38:52<1:24:54, 62.90s/it]

[SIM] 2017-05-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.803, kelly=0.582) with $5846.20 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.712, kelly=0.432) with $4338.67 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.839, kelly=0.680) with $6834.39 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.792, kelly=0.614) with $6172.53 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.679, kelly=0.349) with $3510.98 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.772, kelly=0.553) with $5560.31 allocation
[PORT] Sector Services: selecting BABA (p_up=0.829, kelly=0.671) with $6740.59 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.776, kelly=0.572) with $5751.01 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.693, kelly=0.371) with $3733.24 allocation
[SIM] 2017-05-09 00:00:00: 9 trades proposed.
[TRADE] 2017-05-09 00:00:00: allocated $6834.39 to PM exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $6740.59 to BABA exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $5846.20 to RDS-B exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $6172.53 to BRK-A exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $4563.02 to CSCO exiting on 2017-05-10 00:00:00
[EXIT] 2017-05-10 00:00:00: PM r=-0.0098, PnL=$-67.17
[EXIT] 2017-05-10 00:00:00: BABA r=-0.0002, PnL=$-1.12
[EXIT] 2017-05-10 00:00:00: RDS-B r=0.0116, PnL=$67.56
[EXIT] 2017-05-10 00:00:00: BRK-A r=-0.0006, PnL=$-3.76
[EXIT] 2017-05-10 00:00:00: CSCO r=-0.0047, PnL=$-21.54

Simulating Trading Days:  10%|█         | 9/89 [38:54<58:33, 43.92s/it]

[SIM] 2017-05-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.648, kelly=0.285) with $2867.71 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.721, kelly=0.450) with $4524.37 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.832, kelly=0.665) with $6684.53 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.789, kelly=0.607) with $6100.71 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.730, kelly=0.451) with $4534.63 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.789, kelly=0.586) with $5890.78 allocation
[PORT] Sector Services: selecting BABA (p_up=0.844, kelly=0.698) with $7018.31 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.780, kelly=0.580) with $5830.03 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.684, kelly=0.353) with $3542.98 allocation
[SIM] 2017-05-10 00:00:00: 9 trades proposed.
[TRADE] 2017-05-10 00:00:00: allocated $7018.31 to BABA exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $6684.53 to PM exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $5890.78 to UTX exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $6100.71 to BRK-A exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $4454.59 to CSCO exiting on 2017-05-11 00:00:00
[EXIT] 2017-05-11 00:00:00: BABA r=0.0015, PnL=$10.53
[EXIT] 2017-05-11 00:00:00: PM r=0.0032, PnL=$21.71
[EXIT] 2017-05-11 00:00:00: UTX r=0.0021, PnL=$12.66
[EXIT] 2017-05-11 00:00:00: BRK-A r=-0.0025, PnL=$-15.14
[EXIT] 2017-05-11 00:00:00: CSCO r=-0.0033, PnL=$-14.52

Simulating Trading Days:  11%|█         | 10/89 [38:56<40:52, 31.04s/it]

[SIM] 2017-05-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.645, kelly=0.279) with $2808.72 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.730, kelly=0.467) with $4696.75 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.828, kelly=0.657) with $6603.98 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.774, kelly=0.581) with $5835.09 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.771, kelly=0.535) with $5379.53 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.801, kelly=0.609) with $6118.55 allocation
[PORT] Sector Services: selecting BABA (p_up=0.849, kelly=0.709) with $7130.29 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.781, kelly=0.581) with $5843.96 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.681, kelly=0.346) with $3480.34 allocation
[SIM] 2017-05-11 00:00:00: 9 trades proposed.
[TRADE] 2017-05-11 00:00:00: allocated $7130.29 to BABA exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $6603.98 to PM exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $6118.55 to UTX exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $5843.96 to CSCO exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $4456.70 to BRK-A exiting on 2017-05-12 00:00:00
[EXIT] 2017-05-12 00:00:00: BABA r=0.0015, PnL=$10.68
[EXIT] 2017-05-12 00:00:00: PM r=0.0047, PnL=$30.88
[EXIT] 2017-05-12 00:00:00: UTX r=-0.0037, PnL=$-22.70
[EXIT] 2017-05-12 00:00:00: CSCO r=-0.0054, PnL=$-31.28
[EXIT] 2017-05-12 00:00:00: BRK-A r=-0.0001, PnL=$-0.36

Simulating Trading Days:  12%|█▏        | 11/89 [38:59<28:52, 22.21s/it]

[SIM] 2017-05-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.635, kelly=0.258) with $2589.16 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.731, kelly=0.470) with $4723.25 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.827, kelly=0.654) with $6573.93 allocation
[PORT] Sector Financial: selecting MA (p_up=0.715, kelly=0.430) with $4325.21 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.809, kelly=0.611) with $6142.06 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.810, kelly=0.628) with $6309.21 allocation
[PORT] Sector Services: selecting BABA (p_up=0.846, kelly=0.703) with $7061.58 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.774, kelly=0.568) with $5709.85 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.675, kelly=0.336) with $3374.05 allocation
[SIM] 2017-05-12 00:00:00: 9 trades proposed.
[TRADE] 2017-05-12 00:00:00: allocated $7061.58 to BABA exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $6573.93 to PM exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $6309.21 to UTX exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $6142.06 to SNY exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $4062.88 to CSCO exiting on 2017-05-15 00:00:00
[EXIT] 2017-05-15 00:00:00: BABA r=0.0088, PnL=$62.20
[EXIT] 2017-05-15 00:00:00: PM r=0.0058, PnL=$38.25
[EXIT] 2017-05-15 00:00:00: UTX r=0.0007, PnL=$4.70
[EXIT] 2017-05-15 00:00:00: SNY r=0.0041, PnL=$24.96
[EXIT] 2017-05-15 00:00:00: CSCO r=0.0233, PnL=$94.74

Simulating Trading Days:  13%|█▎        | 12/89 [39:01<20:41, 16.13s/it]

[SIM] 2017-05-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.671, kelly=0.368) with $3708.31 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.731, kelly=0.470) with $4734.16 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.827, kelly=0.656) with $6606.68 allocation
[PORT] Sector Financial: selecting MA (p_up=0.720, kelly=0.440) with $4434.54 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.837, kelly=0.668) with $6732.49 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.815, kelly=0.636) with $6405.06 allocation
[PORT] Sector Services: selecting BABA (p_up=0.833, kelly=0.677) with $6822.39 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.755, kelly=0.532) with $5359.72 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.673, kelly=0.331) with $3335.93 allocation
[SIM] 2017-05-15 00:00:00: 9 trades proposed.
[TRADE] 2017-05-15 00:00:00: allocated $6732.49 to SNY exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $6822.39 to BABA exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $6606.68 to PM exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $6405.06 to UTX exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $3650.49 to CSCO exiting on 2017-05-16 00:00:00
[EXIT] 2017-05-16 00:00:00: SNY r=0.0162, PnL=$109.01
[EXIT] 2017-05-16 00:00:00: BABA r=0.0216, PnL=$147.24
[EXIT] 2017-05-16 00:00:00: PM r=0.0103, PnL=$68.21
[EXIT] 2017-05-16 00:00:00: UTX r=0.0040, PnL=$25.43
[EXIT] 2017-05-16 00:00:00: CSCO r=0.0020, PnL=$7.47

Simulating Trading Days:  15%|█▍        | 13/89 [39:03<15:06, 11.92s/it]

[SIM] 2017-05-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.650, kelly=0.328) with $3315.33 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.734, kelly=0.476) with $4810.55 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.827, kelly=0.655) with $6624.55 allocation
[PORT] Sector Financial: selecting MA (p_up=0.699, kelly=0.400) with $4041.89 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.846, kelly=0.686) with $6935.19 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.821, kelly=0.648) with $6547.22 allocation
[PORT] Sector Services: selecting BABA (p_up=0.821, kelly=0.654) with $6610.52 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.724, kelly=0.474) with $4788.98 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.670, kelly=0.323) with $3264.20 allocation
[SIM] 2017-05-16 00:00:00: 9 trades proposed.
[TRADE] 2017-05-16 00:00:00: allocated $6935.19 to SNY exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $6624.55 to PM exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $6610.52 to BABA exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $6547.22 to UTX exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $3606.83 to HRG exiting on 2017-05-17 00:00:00
[EXIT] 2017-05-17 00:00:00: SNY r=-0.0161, PnL=$-111.88
[EXIT] 2017-05-17 00:00:00: PM r=0.0020, PnL=$13.42
[EXIT] 2017-05-17 00:00:00: BABA r=-0.0266, PnL=$-175.90
[EXIT] 2017-05-17 00:00:00: UTX r=-0.0150, PnL=$-98.15
[EXIT] 2017-05-17 00:00:00: HRG r=-0.0203, PnL=$-73.11

Simulating Trading Days:  16%|█▌        | 14/89 [39:05<11:13,  8.97s/it]

[SIM] 2017-05-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.624, kelly=0.278) with $2796.87 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.735, kelly=0.477) with $4803.29 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.826, kelly=0.654) with $6581.47 allocation
[PORT] Sector Financial: selecting MA (p_up=0.651, kelly=0.302) with $3039.84 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.846, kelly=0.686) with $6906.31 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.822, kelly=0.649) with $6533.28 allocation
[PORT] Sector Services: selecting BABA (p_up=0.810, kelly=0.632) with $6361.79 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.684, kelly=0.398) with $4009.83 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.667, kelly=0.317) with $3188.02 allocation
[SIM] 2017-05-17 00:00:00: 9 trades proposed.
[TRADE] 2017-05-17 00:00:00: allocated $6906.31 to SNY exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $6581.47 to PM exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $6533.28 to UTX exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $6361.79 to BABA exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $3807.78 to HRG exiting on 2017-05-18 00:00:00
[EXIT] 2017-05-18 00:00:00: SNY r=-0.0051, PnL=$-34.95
[EXIT] 2017-05-18 00:00:00: PM r=-0.0015, PnL=$-9.84
[EXIT] 2017-05-18 00:00:00: UTX r=-0.0018, PnL=$-11.47
[EXIT] 2017-05-18 00:00:00: BABA r=0.0046, PnL=$28.98
[EXIT] 2017-05-18 00:00:00: HRG r=0.0063, PnL=$24.07

Simulating Trading Days:  17%|█▋        | 15/89 [39:15<11:11,  9.08s/it]

[SIM] 2017-05-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.615, kelly=0.261) with $2626.67 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.739, kelly=0.485) with $4880.91 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.827, kelly=0.654) with $6584.63 allocation
[PORT] Sector Financial: selecting MA (p_up=0.615, kelly=0.230) with $2311.93 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.843, kelly=0.682) with $6861.65 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.820, kelly=0.645) with $6492.58 allocation
[PORT] Sector Services: selecting BABA (p_up=0.796, kelly=0.606) with $6101.50 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.708, kelly=0.413) with $4157.26 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.667, kelly=0.318) with $3201.14 allocation
[SIM] 2017-05-18 00:00:00: 9 trades proposed.
[TRADE] 2017-05-18 00:00:00: allocated $6861.65 to SNY exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $6584.63 to PM exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $6492.58 to UTX exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $6101.50 to BABA exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $4149.31 to HRG exiting on 2017-05-19 00:00:00
[EXIT] 2017-05-19 00:00:00: SNY r=0.0033, PnL=$22.34
[EXIT] 2017-05-19 00:00:00: PM r=0.0102, PnL=$67.25
[EXIT] 2017-05-19 00:00:00: UTX r=0.0150, PnL=$97.36
[EXIT] 2017-05-19 00:00:00: BABA r=0.0161, PnL=$98.11
[EXIT] 2017-05-19 00:00:00: HRG r=0.0120, PnL=$49.76

Simulating Trading Days:  18%|█▊        | 16/89 [39:17<08:31,  7.00s/it]

[SIM] 2017-05-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.619, kelly=0.270) with $2722.11 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.751, kelly=0.508) with $5124.94 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.828, kelly=0.658) with $6642.36 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.762, kelly=0.537) with $5424.26 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.845, kelly=0.685) with $6919.15 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.823, kelly=0.652) with $6586.36 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.733, kelly=0.511) with $5163.63 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.773, kelly=0.545) with $5502.84 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.670, kelly=0.323) with $3265.08 allocation
[SIM] 2017-05-19 00:00:00: 9 trades proposed.
[TRADE] 2017-05-19 00:00:00: allocated $6919.15 to SNY exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $6642.36 to PM exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $6586.36 to UTX exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $5502.84 to VZ exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $4639.38 to WFC exiting on 2017-05-22 00:00:00
[EXIT] 2017-05-22 00:00:00: SNY r=-0.0030, PnL=$-21.05
[EXIT] 2017-05-22 00:00:00: PM r=0.0129, PnL=$85.68
[EXIT] 2017-05-22 00:00:00: UTX r=0.0041, PnL=$27.18
[EXIT] 2017-05-22 00:00:00: VZ r=0.0013, PnL=$7.27
[EXIT] 2017-05-22 00:00:00: WFC r=-0.0009, PnL=$-4.37

Simulating Trading Days:  19%|█▉        | 17/89 [39:19<06:39,  5.55s/it]

[SIM] 2017-05-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.625, kelly=0.280) with $2833.55 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.757, kelly=0.519) with $5244.73 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.830, kelly=0.661) with $6680.76 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.811, kelly=0.633) with $6393.07 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.849, kelly=0.692) with $6994.52 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.813, kelly=0.634) with $6403.00 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.738, kelly=0.521) with $5269.32 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.798, kelly=0.595) with $6015.92 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.689, kelly=0.378) with $3822.32 allocation
[SIM] 2017-05-22 00:00:00: 9 trades proposed.
[TRADE] 2017-05-22 00:00:00: allocated $6994.52 to SNY exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $6680.76 to PM exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $6403.00 to UTX exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $6393.07 to WFC exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $3847.17 to VZ exiting on 2017-05-23 00:00:00
[EXIT] 2017-05-23 00:00:00: SNY r=-0.0018, PnL=$-12.81
[EXIT] 2017-05-23 00:00:00: PM r=0.0021, PnL=$13.80
[EXIT] 2017-05-23 00:00:00: UTX r=0.0034, PnL=$21.58
[EXIT] 2017-05-23 00:00:00: WFC r=0.0072, PnL=$45.83
[EXIT] 2017-05-23 00:00:00: VZ r=0.0000, PnL=$0.00

Simulating Trading Days:  20%|██        | 18/89 [39:21<05:23,  4.55s/it]

[SIM] 2017-05-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.640, kelly=0.309) with $3120.39 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.752, kelly=0.511) with $5162.75 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.831, kelly=0.664) with $6712.00 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.790, kelly=0.592) with $5986.83 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.846, kelly=0.688) with $6957.51 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.780, kelly=0.567) with $5737.63 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.735, kelly=0.515) with $5211.64 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.773, kelly=0.544) with $5503.80 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.703, kelly=0.400) with $4048.54 allocation
[SIM] 2017-05-23 00:00:00: 9 trades proposed.
[TRADE] 2017-05-23 00:00:00: allocated $6957.51 to SNY exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $6712.00 to PM exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $5986.83 to WFC exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $5737.63 to UTX exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $4945.07 to VZ exiting on 2017-05-24 00:00:00
[EXIT] 2017-05-24 00:00:00: SNY r=0.0016, PnL=$11.34
[EXIT] 2017-05-24 00:00:00: PM r=0.0083, PnL=$55.90
[EXIT] 2017-05-24 00:00:00: WFC r=-0.0056, PnL=$-33.64
[EXIT] 2017-05-24 00:00:00: UTX r=0.0001, PnL=$0.47
[EXIT] 2017-05-24 00:00:00: VZ r=-0.0097, PnL=$-47.84

Simulating Trading Days:  21%|██▏       | 19/89 [39:23<04:28,  3.84s/it]

[SIM] 2017-05-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.654, kelly=0.335) with $3383.64 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.743, kelly=0.493) with $4986.75 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.833, kelly=0.666) with $6738.46 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.766, kelly=0.546) with $5516.95 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.871, kelly=0.745) with $7537.95 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.741, kelly=0.492) with $4970.68 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.722, kelly=0.492) with $4974.16 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.728, kelly=0.455) with $4597.93 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.714, kelly=0.414) with $4190.27 allocation
[SIM] 2017-05-24 00:00:00: 9 trades proposed.
[TRADE] 2017-05-24 00:00:00: allocated $7537.95 to AMGN exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $6738.46 to PM exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $5516.95 to WFC exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $4986.75 to HRG exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $4970.68 to UTX exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $584.13 to VZ exiting on 2017-05-25 00:00:00
[EXIT] 2017-05-25 00:00:00: AMGN r=0.0054, PnL=$40.47
[EXIT] 2017-05-25 00:00:00: PM r=0.0175, PnL=$117.63
[EXIT] 2017-05-25 00:00:00: WFC r=-0.0058, PnL=$-32.21
[EXIT] 2017-05-25 00:00:00: HRG r=0.0005, PnL=$2.69
[EXIT] 2017-05-25 00:00:00: UTX r=0.0014, PnL=$6.92
[EXIT] 2017-05-25 00:00:00: VZ r=0.0060, PnL=$3.50

Simulating Trading Days:  22%|██▏       | 20/89 [39:26<03:50,  3.34s/it]

[SIM] 2017-05-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.659, kelly=0.344) with $3485.63 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.734, kelly=0.477) with $4826.95 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.836, kelly=0.673) with $6817.37 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.767, kelly=0.547) with $5536.44 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.864, kelly=0.731) with $7405.50 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.703, kelly=0.416) with $4215.52 allocation
[PORT] Sector Services: selecting BABA (p_up=0.778, kelly=0.570) with $5772.15 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.696, kelly=0.389) with $3936.44 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.739, kelly=0.473) with $4788.15 allocation
[SIM] 2017-05-25 00:00:00: 9 trades proposed.
[TRADE] 2017-05-25 00:00:00: allocated $7405.50 to AMGN exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $6817.37 to PM exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $5772.15 to BABA exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $5536.44 to WFC exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $4788.15 to NGG exiting on 2017-05-26 00:00:00
[EXIT] 2017-05-26 00:00:00: AMGN r=-0.0027, PnL=$-20.01
[EXIT] 2017-05-26 00:00:00: PM r=0.0029, PnL=$19.97
[EXIT] 2017-05-26 00:00:00: BABA r=0.0029, PnL=$16.81
[EXIT] 2017-05-26 00:00:00: WFC r=-0.0070, PnL=$-38.81
[EXIT] 2017-05-26 00:00:00: NGG r=-0.0098, PnL=$-46.74

Simulating Trading Days:  24%|██▎       | 21/89 [39:28<03:23,  2.99s/it]

[SIM] 2017-05-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.662, kelly=0.350) with $3544.14 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.709, kelly=0.426) with $4312.46 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.839, kelly=0.679) with $6869.58 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.770, kelly=0.553) with $5599.08 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.842, kelly=0.688) with $6964.45 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.665, kelly=0.341) with $3448.26 allocation
[PORT] Sector Services: selecting BABA (p_up=0.787, kelly=0.588) with $5949.96 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.696, kelly=0.390) with $3950.14 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.755, kelly=0.505) with $5113.70 allocation
[SIM] 2017-05-26 00:00:00: 9 trades proposed.
[TRADE] 2017-05-26 00:00:00: allocated $6964.45 to AMGN exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $6869.58 to PM exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $5949.96 to BABA exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $5599.08 to WFC exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4972.91 to NGG exiting on 2017-05-30 00:00:00
[EXIT] 2017-05-30 00:00:00: AMGN r=-0.0075, PnL=$-52.12
[EXIT] 2017-05-30 00:00:00: PM r=0.0010, PnL=$6.88
[EXIT] 2017-05-30 00:00:00: BABA r=-0.0006, PnL=$-3.84
[EXIT] 2017-05-30 00:00:00: WFC r=-0.0048, PnL=$-26.71
[EXIT] 2017-05-30 00:00:00: NGG r=0.0046, PnL=$22.74

Simulating Trading Days:  25%|██▍       | 22/89 [39:30<03:04,  2.75s/it]

[SIM] 2017-05-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.659, kelly=0.344) with $3480.91 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.692, kelly=0.393) with $3970.73 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.841, kelly=0.683) with $6909.84 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.766, kelly=0.546) with $5517.96 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.805, kelly=0.615) with $6218.41 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.692, kelly=0.370) with $3744.05 allocation
[PORT] Sector Services: selecting BABA (p_up=0.795, kelly=0.603) with $6101.15 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.693, kelly=0.383) with $3875.03 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.764, kelly=0.525) with $5304.67 allocation
[SIM] 2017-05-30 00:00:00: 9 trades proposed.
[TRADE] 2017-05-30 00:00:00: allocated $6909.84 to PM exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $6218.41 to AMGN exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $6101.15 to BABA exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $5517.96 to WFC exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $5304.67 to NGG exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $288.04 to VZ exiting on 2017-05-31 00:00:00
[EXIT] 2017-05-31 00:00:00: PM r=-0.0013, PnL=$-8.64
[EXIT] 2017-05-31 00:00:00: AMGN r=0.0090, PnL=$56.18
[EXIT] 2017-05-31 00:00:00: BABA r=-0.0117, PnL=$-71.40
[EXIT] 2017-05-31 00:00:00: WFC r=-0.0196, PnL=$-107.91
[EXIT] 2017-05-31 00:00:00: NGG r=-0.0257, PnL=$-136.56
[EXIT] 2017-05-31 00:00:00: VZ r=0.0095, PnL=$2.74

Simulating Trading Days:  26%|██▌       | 23/89 [39:32<02:50,  2.59s/it]

[SIM] 2017-05-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.626, kelly=0.279) with $2817.31 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.675, kelly=0.359) with $3620.48 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.845, kelly=0.691) with $6965.22 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.771, kelly=0.556) with $5606.06 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.732, kelly=0.456) with $4604.42 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.694, kelly=0.375) with $3780.40 allocation
[PORT] Sector Services: selecting BABA (p_up=0.802, kelly=0.617) with $6221.86 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.695, kelly=0.389) with $3920.38 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.768, kelly=0.532) with $5362.60 allocation
[SIM] 2017-05-31 00:00:00: 9 trades proposed.
[TRADE] 2017-05-31 00:00:00: allocated $6965.22 to PM exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $6221.86 to BABA exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $5606.06 to WFC exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $5362.60 to NGG exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $4604.42 to SNY exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $1500.23 to VZ exiting on 2017-06-01 00:00:00
[EXIT] 2017-06-01 00:00:00: PM r=0.0092, PnL=$63.95
[EXIT] 2017-06-01 00:00:00: BABA r=0.0123, PnL=$76.72
[EXIT] 2017-06-01 00:00:00: WFC r=0.0184, PnL=$103.04
[EXIT] 2017-06-01 00:00:00: NGG r=-0.0026, PnL=$-14.09
[EXIT] 2017-06-01 00:00:00: SNY r=-0.0063, PnL=$-28.78
[EXIT] 2017-06-01 00:00:00: VZ r=-0.0028, PnL=$-4.18

Simulating Trading Days:  27%|██▋       | 24/89 [39:34<02:41,  2.48s/it]

[SIM] 2017-06-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.551, kelly=0.136) with $1371.67 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.661, kelly=0.330) with $3338.89 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.848, kelly=0.697) with $7042.46 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.804, kelly=0.620) with $6263.32 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.705, kelly=0.401) with $4047.82 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.699, kelly=0.386) with $3900.38 allocation
[PORT] Sector Services: selecting BABA (p_up=0.805, kelly=0.623) with $6291.54 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.704, kelly=0.406) with $4103.20 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.771, kelly=0.536) with $5421.04 allocation
[SIM] 2017-06-01 00:00:00: 9 trades proposed.
[TRADE] 2017-06-01 00:00:00: allocated $7042.46 to PM exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $6291.54 to BABA exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $6263.32 to WFC exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5421.04 to NGG exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $4047.82 to SNY exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $1253.21 to VZ exiting on 2017-06-02 00:00:00
[EXIT] 2017-06-02 00:00:00: PM r=0.0074, PnL=$51.84
[EXIT] 2017-06-02 00:00:00: BABA r=0.0013, PnL=$8.12
[EXIT] 2017-06-02 00:00:00: WFC r=-0.0052, PnL=$-32.47
[EXIT] 2017-06-02 00:00:00: NGG r=-0.0105, PnL=$-57.13
[EXIT] 2017-06-02 00:00:00: SNY r=0.0148, PnL=$59.96
[EXIT] 2017-06-02 00:00:00: VZ r=-0.0015, PnL=$-1.89

Simulating Trading Days:  28%|██▊       | 25/89 [39:37<02:32,  2.39s/it]

[SIM] 2017-06-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.599, kelly=0.148) with $1494.36 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.642, kelly=0.294) with $2973.18 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.851, kelly=0.703) with $7102.31 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.851, kelly=0.710) with $7175.32 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.680, kelly=0.352) with $3556.02 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.695, kelly=0.377) with $3813.89 allocation
[PORT] Sector Services: selecting BABA (p_up=0.806, kelly=0.625) with $6323.03 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.742, kelly=0.482) with $4874.87 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.785, kelly=0.565) with $5712.82 allocation
[SIM] 2017-06-02 00:00:00: 9 trades proposed.
[TRADE] 2017-06-02 00:00:00: allocated $7102.31 to PM exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $7175.32 to WFC exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $6323.03 to BABA exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $5712.82 to NGG exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $4014.44 to VZ exiting on 2017-06-05 00:00:00
[EXIT] 2017-06-05 00:00:00: PM r=0.0015, PnL=$10.50
[EXIT] 2017-06-05 00:00:00: WFC r=-0.0017, PnL=$-12.46
[EXIT] 2017-06-05 00:00:00: BABA r=0.0100, PnL=$63.16
[EXIT] 2017-06-05 00:00:00: NGG r=-0.0013, PnL=$-7.61
[EXIT] 2017-06-05 00:00:00: VZ r=-0.0015, PnL=$-6.05

Simulating Trading Days:  29%|██▉       | 26/89 [39:39<02:27,  2.35s/it]

[SIM] 2017-06-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.712, kelly=0.389) with $3929.64 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.621, kelly=0.253) with $2559.50 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.853, kelly=0.707) with $7148.25 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.834, kelly=0.678) with $6859.50 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.661, kelly=0.313) with $3162.65 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.649, kelly=0.308) with $3113.70 allocation
[PORT] Sector Services: selecting BABA (p_up=0.805, kelly=0.623) with $6297.29 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.745, kelly=0.488) with $4939.60 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.793, kelly=0.582) with $5883.66 allocation
[SIM] 2017-06-05 00:00:00: 9 trades proposed.
[TRADE] 2017-06-05 00:00:00: allocated $7148.25 to PM exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $6859.50 to WFC exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $6297.29 to BABA exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $5883.66 to NGG exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $4153.48 to VZ exiting on 2017-06-06 00:00:00
[EXIT] 2017-06-06 00:00:00: PM r=0.0002, PnL=$1.76
[EXIT] 2017-06-06 00:00:00: WFC r=0.0017, PnL=$11.94
[EXIT] 2017-06-06 00:00:00: BABA r=-0.0060, PnL=$-37.67
[EXIT] 2017-06-06 00:00:00: NGG r=-0.0114, PnL=$-67.11
[EXIT] 2017-06-06 00:00:00: VZ r=0.0015, PnL=$6.27

Simulating Trading Days:  30%|███       | 27/89 [39:41<02:22,  2.30s/it]

[SIM] 2017-06-06 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.795, kelly=0.565) with $5713.29 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.637, kelly=0.287) with $2896.19 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.855, kelly=0.710) with $7179.68 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.833, kelly=0.677) with $6839.81 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.634, kelly=0.259) with $2619.66 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.661, kelly=0.331) with $3344.97 allocation
[PORT] Sector Services: selecting UPS (p_up=0.850, kelly=0.697) with $7046.65 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.751, kelly=0.502) with $5069.66 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.791, kelly=0.577) with $5831.91 allocation
[SIM] 2017-06-06 00:00:00: 9 trades proposed.
[TRADE] 2017-06-06 00:00:00: allocated $7179.68 to PM exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $7046.65 to UPS exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $6839.81 to WFC exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $5713.29 to RDS-B exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $3537.31 to NGG exiting on 2017-06-07 00:00:00
[EXIT] 2017-06-07 00:00:00: PM r=0.0025, PnL=$17.66
[EXIT] 2017-06-07 00:00:00: UPS r=-0.0070, PnL=$-49.19
[EXIT] 2017-06-07 00:00:00: WFC r=0.0054, PnL=$36.96
[EXIT] 2017-06-07 00:00:00: RDS-B r=-0.0122, PnL=$-69.95
[EXIT] 2017-06-07 00:00:00: NGG r=0.0018, PnL=$6.36

Simulating Trading Days:  31%|███▏      | 28/89 [39:43<02:19,  2.28s/it]

[SIM] 2017-06-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.843, kelly=0.667) with $6733.01 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.642, kelly=0.296) with $2993.44 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.858, kelly=0.716) with $7236.14 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.807, kelly=0.625) with $6308.99 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.616, kelly=0.221) with $2236.61 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.670, kelly=0.350) with $3534.47 allocation
[PORT] Sector Services: selecting UPS (p_up=0.884, kelly=0.767) with $7743.09 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.743, kelly=0.485) with $4893.37 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.785, kelly=0.565) with $5706.26 allocation
[SIM] 2017-06-07 00:00:00: 9 trades proposed.
[TRADE] 2017-06-07 00:00:00: allocated $7743.09 to UPS exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $7236.14 to PM exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $6733.01 to RDS-B exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $6308.99 to WFC exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $2278.05 to NGG exiting on 2017-06-08 00:00:00
[EXIT] 2017-06-08 00:00:00: UPS r=0.0007, PnL=$5.08
[EXIT] 2017-06-08 00:00:00: PM r=-0.0097, PnL=$-70.41
[EXIT] 2017-06-08 00:00:00: RDS-B r=-0.0061, PnL=$-41.12
[EXIT] 2017-06-08 00:00:00: WFC r=0.0090, PnL=$56.93
[EXIT] 2017-06-08 00:00:00: NGG r=0.0000, PnL=$0.00

Simulating Trading Days:  33%|███▎      | 29/89 [39:45<02:15,  2.25s/it]

[SIM] 2017-06-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.870, kelly=0.723) with $7298.10 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.644, kelly=0.301) with $3040.83 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.861, kelly=0.723) with $7297.40 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.799, kelly=0.609) with $6144.04 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.599, kelly=0.187) with $1892.27 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.682, kelly=0.372) with $3756.86 allocation
[PORT] Sector Services: selecting UPS (p_up=0.893, kelly=0.784) with $7909.46 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.750, kelly=0.498) with $5032.20 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.775, kelly=0.546) with $5506.81 allocation
[SIM] 2017-06-08 00:00:00: 9 trades proposed.
[TRADE] 2017-06-08 00:00:00: allocated $7909.46 to UPS exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $7298.10 to RDS-B exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $7297.40 to PM exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $6144.04 to WFC exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $1635.43 to NGG exiting on 2017-06-09 00:00:00
[EXIT] 2017-06-09 00:00:00: UPS r=0.0026, PnL=$20.75
[EXIT] 2017-06-09 00:00:00: RDS-B r=0.0078, PnL=$56.72
[EXIT] 2017-06-09 00:00:00: PM r=-0.0082, PnL=$-59.65
[EXIT] 2017-06-09 00:00:00: WFC r=0.0236, PnL=$144.95
[EXIT] 2017-06-09 00:00:00: NGG r=-0.0251, PnL=$-41.09

Simulating Trading Days:  34%|███▎      | 30/89 [39:48<02:12,  2.24s/it]

[SIM] 2017-06-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.890, kelly=0.766) with $7738.35 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.640, kelly=0.293) with $2962.80 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.864, kelly=0.728) with $7359.79 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.769, kelly=0.552) with $5580.12 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.589, kelly=0.166) with $1678.07 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.691, kelly=0.390) with $3943.25 allocation
[PORT] Sector Services: selecting UPS (p_up=0.887, kelly=0.771) with $7790.60 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.735, kelly=0.468) with $4734.26 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.763, kelly=0.520) with $5260.46 allocation
[SIM] 2017-06-09 00:00:00: 9 trades proposed.
[TRADE] 2017-06-09 00:00:00: allocated $7738.35 to RDS-B exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $7790.60 to UPS exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $7359.79 to PM exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $5580.12 to WFC exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $1852.07 to NGG exiting on 2017-06-12 00:00:00
[EXIT] 2017-06-12 00:00:00: RDS-B r=0.0079, PnL=$61.06
[EXIT] 2017-06-12 00:00:00: UPS r=0.0178, PnL=$139.03
[EXIT] 2017-06-12 00:00:00: PM r=-0.0079, PnL=$-58.21
[EXIT] 2017-06-12 00:00:00: WFC r=0.0054, PnL=$30.08
[EXIT] 2017-06-12 00:00:00: NGG r=-0.0071, PnL=$-13.07

Simulating Trading Days:  35%|███▍      | 31/89 [39:50<02:09,  2.24s/it]

[SIM] 2017-06-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.907, kelly=0.802) with $8122.78 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.629, kelly=0.273) with $2762.45 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.868, kelly=0.736) with $7448.01 allocation
[PORT] Sector Financial: selecting BRK-A (p_up=0.773, kelly=0.579) with $5862.60 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.589, kelly=0.166) with $1676.47 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.698, kelly=0.405) with $4099.81 allocation
[PORT] Sector Services: selecting UPS (p_up=0.894, kelly=0.785) with $7944.53 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.738, kelly=0.475) with $4806.18 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.754, kelly=0.502) with $5083.92 allocation
[SIM] 2017-06-12 00:00:00: 9 trades proposed.
[TRADE] 2017-06-12 00:00:00: allocated $8122.78 to RDS-B exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $7944.53 to UPS exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $7448.01 to PM exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $5862.60 to BRK-A exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $990.67 to NGG exiting on 2017-06-13 00:00:00
[EXIT] 2017-06-13 00:00:00: RDS-B r=0.0044, PnL=$36.13
[EXIT] 2017-06-13 00:00:00: UPS r=0.0084, PnL=$66.36
[EXIT] 2017-06-13 00:00:00: PM r=-0.0040, PnL=$-30.00
[EXIT] 2017-06-13 00:00:00: BRK-A r=0.0051, PnL=$29.78
[EXIT] 2017-06-13 00:00:00: NGG r=0.0127, PnL=$12.55

Simulating Trading Days:  36%|███▌      | 32/89 [39:52<02:07,  2.24s/it]

[SIM] 2017-06-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.919, kelly=0.828) with $8393.63 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.601, kelly=0.211) with $2134.51 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.870, kelly=0.741) with $7512.75 allocation
[PORT] Sector Financial: selecting MA (p_up=0.735, kelly=0.470) with $4760.46 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.598, kelly=0.184) with $1860.65 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.700, kelly=0.411) with $4169.96 allocation
[PORT] Sector Services: selecting UPS (p_up=0.873, kelly=0.743) with $7530.75 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.805, kelly=0.609) with $6172.18 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.754, kelly=0.501) with $5076.43 allocation
[SIM] 2017-06-13 00:00:00: 9 trades proposed.
[TRADE] 2017-06-13 00:00:00: allocated $8393.63 to RDS-B exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $7530.75 to UPS exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $7512.75 to PM exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $6172.18 to VZ exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $793.74 to NGG exiting on 2017-06-14 00:00:00
[EXIT] 2017-06-14 00:00:00: RDS-B r=-0.0138, PnL=$-115.98
[EXIT] 2017-06-14 00:00:00: UPS r=-0.0042, PnL=$-31.54
[EXIT] 2017-06-14 00:00:00: PM r=0.0089, PnL=$67.09
[EXIT] 2017-06-14 00:00:00: VZ r=0.0050, PnL=$30.56
[EXIT] 2017-06-14 00:00:00: NGG r=0.0011, PnL=$0.85

Simulating Trading Days:  37%|███▋      | 33/89 [39:54<02:05,  2.24s/it]

[SIM] 2017-06-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.916, kelly=0.821) with $8311.99 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.608, kelly=0.226) with $2291.72 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.872, kelly=0.744) with $7541.26 allocation
[PORT] Sector Financial: selecting MA (p_up=0.779, kelly=0.559) with $5666.03 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.612, kelly=0.213) with $2153.01 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.702, kelly=0.413) with $4186.24 allocation
[PORT] Sector Services: selecting UPS (p_up=0.835, kelly=0.667) with $6752.69 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.818, kelly=0.636) with $6438.74 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.758, kelly=0.510) with $5162.12 allocation
[SIM] 2017-06-14 00:00:00: 9 trades proposed.
[TRADE] 2017-06-14 00:00:00: allocated $8311.99 to RDS-B exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $7541.26 to PM exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $6752.69 to UPS exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $6438.74 to VZ exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $1343.67 to MA exiting on 2017-06-15 00:00:00
[EXIT] 2017-06-15 00:00:00: RDS-B r=-0.0113, PnL=$-94.06
[EXIT] 2017-06-15 00:00:00: PM r=0.0063, PnL=$47.86
[EXIT] 2017-06-15 00:00:00: UPS r=0.0080, PnL=$53.71
[EXIT] 2017-06-15 00:00:00: VZ r=-0.0011, PnL=$-6.90
[EXIT] 2017-06-15 00:00:00: MA r=-0.0088, PnL=$-11.85

Simulating Trading Days:  38%|███▊      | 34/89 [39:57<02:02,  2.23s/it]

[SIM] 2017-06-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.890, kelly=0.766) with $7757.65 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.619, kelly=0.248) with $2509.92 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.872, kelly=0.744) with $7537.92 allocation
[PORT] Sector Financial: selecting MA (p_up=0.775, kelly=0.551) with $5581.93 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.634, kelly=0.256) with $2593.48 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.699, kelly=0.408) with $4133.86 allocation
[PORT] Sector Services: selecting UPS (p_up=0.788, kelly=0.572) with $5796.98 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.797, kelly=0.594) with $6011.42 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.770, kelly=0.534) with $5411.72 allocation
[SIM] 2017-06-15 00:00:00: 9 trades proposed.
[TRADE] 2017-06-15 00:00:00: allocated $7757.65 to RDS-B exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $7537.92 to PM exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $6011.42 to VZ exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $5796.98 to UPS exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $3281.00 to MA exiting on 2017-06-16 00:00:00
[EXIT] 2017-06-16 00:00:00: RDS-B r=0.0216, PnL=$167.73
[EXIT] 2017-06-16 00:00:00: PM r=0.0110, PnL=$83.19
[EXIT] 2017-06-16 00:00:00: VZ r=-0.0002, PnL=$-1.29
[EXIT] 2017-06-16 00:00:00: UPS r=0.0030, PnL=$17.35
[EXIT] 2017-06-16 00:00:00: MA r=0.0044, PnL=$14.59

Simulating Trading Days:  39%|███▉      | 35/89 [39:59<01:59,  2.22s/it]

[SIM] 2017-06-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.845, kelly=0.671) with $6814.33 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.631, kelly=0.271) with $2751.69 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.877, kelly=0.754) with $7662.52 allocation
[PORT] Sector Financial: selecting MA (p_up=0.762, kelly=0.525) with $5330.43 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.657, kelly=0.303) with $3073.18 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.698, kelly=0.405) with $4117.31 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.695, kelly=0.442) with $4486.84 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.740, kelly=0.502) with $5103.11 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.775, kelly=0.544) with $5521.96 allocation
[SIM] 2017-06-16 00:00:00: 9 trades proposed.
[TRADE] 2017-06-16 00:00:00: allocated $7662.52 to PM exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $6814.33 to RDS-B exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $5521.96 to NGG exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $5330.43 to MA exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $5103.11 to CSCO exiting on 2017-06-19 00:00:00
[EXIT] 2017-06-19 00:00:00: PM r=0.0087, PnL=$66.66
[EXIT] 2017-06-19 00:00:00: RDS-B r=-0.0028, PnL=$-19.39
[EXIT] 2017-06-19 00:00:00: NGG r=-0.0042, PnL=$-23.44
[EXIT] 2017-06-19 00:00:00: MA r=0.0093, PnL=$49.39
[EXIT] 2017-06-19 00:00:00: CSCO r=0.0114, PnL=$58.08

Simulating Trading Days:  40%|████      | 36/89 [40:01<01:57,  2.22s/it]

[SIM] 2017-06-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.808, kelly=0.592) with $6020.50 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.642, kelly=0.293) with $2977.28 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.880, kelly=0.760) with $7729.91 allocation
[PORT] Sector Financial: selecting MA (p_up=0.764, kelly=0.529) with $5378.77 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.679, kelly=0.349) with $3544.37 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.756, kelly=0.500) with $5086.46 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.697, kelly=0.446) with $4530.85 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.762, kelly=0.544) with $5528.44 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.770, kelly=0.534) with $5426.18 allocation
[SIM] 2017-06-19 00:00:00: 9 trades proposed.
[TRADE] 2017-06-19 00:00:00: allocated $7729.91 to PM exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $6020.50 to RDS-B exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $5426.18 to NGG exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $5378.77 to MA exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $5528.44 to CSCO exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $425.03 to ABB exiting on 2017-06-20 00:00:00
[EXIT] 2017-06-20 00:00:00: PM r=-0.0064, PnL=$-49.69
[EXIT] 2017-06-20 00:00:00: RDS-B r=-0.0257, PnL=$-154.62
[EXIT] 2017-06-20 00:00:00: NGG r=-0.0091, PnL=$-49.56
[EXIT] 2017-06-20 00:00:00: MA r=-0.0013, PnL=$-6.99
[EXIT] 2017-06-20 00:00:00: CSCO r=-0.0044, PnL=$-24.19
[EXIT] 2017-06-20 00:00:00: ABB r=-0.0176, PnL=$-7.50

Simulating Trading Days:  42%|████▏     | 37/89 [57:29<4:33:50, 315.97s/it]

[SIM] 2017-06-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.783, kelly=0.540) with $5476.11 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.650, kelly=0.309) with $3135.34 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.880, kelly=0.760) with $7707.87 allocation
[PORT] Sector Financial: selecting MA (p_up=0.752, kelly=0.503) with $5103.28 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.690, kelly=0.371) with $3766.01 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.768, kelly=0.525) with $5323.51 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.711, kelly=0.471) with $4775.86 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.781, kelly=0.580) with $5885.35 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.719, kelly=0.416) with $4222.11 allocation
[SIM] 2017-06-20 00:00:00: 9 trades proposed.
[TRADE] 2017-06-20 00:00:00: allocated $7707.87 to PM exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5476.11 to RDS-B exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5885.35 to CSCO exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5323.51 to ABB exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5103.28 to MA exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $924.95 to NEE exiting on 2017-06-21 00:00:00
[EXIT] 2017-06-21 00:00:00: PM r=-0.0157, PnL=$-121.19
[EXIT] 2017-06-21 00:00:00: RDS-B r=-0.0146, PnL=$-80.19
[EXIT] 2017-06-21 00:00:00: CSCO r=-0.0003, PnL=$-1.85
[EXIT] 2017-06-21 00:00:00: ABB r=0.0056, PnL=$29.75
[EXIT] 2017-06-21 00:00:00: MA r=0.0014, PnL=$7.06
[EXIT] 2017-06-21 00:00:00: NEE r=-0.0063, PnL=$-5.86

Simulating Trading Days:  43%|████▎     | 38/89 [57:31<3:08:38, 221.93s/it]

[SIM] 2017-06-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.746, kelly=0.460) with $4651.63 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.656, kelly=0.320) with $3239.27 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.878, kelly=0.756) with $7651.03 allocation
[PORT] Sector Financial: selecting MA (p_up=0.737, kelly=0.474) with $4801.38 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.694, kelly=0.380) with $3842.88 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.767, kelly=0.523) with $5296.14 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.707, kelly=0.463) with $4682.22 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.796, kelly=0.609) with $6169.29 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.709, kelly=0.397) with $4022.18 allocation
[SIM] 2017-06-21 00:00:00: 9 trades proposed.
[TRADE] 2017-06-21 00:00:00: allocated $7651.03 to PM exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $6169.29 to CSCO exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $5296.14 to ABB exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $4651.63 to RDS-B exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $4801.38 to MA exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $1799.90 to NEE exiting on 2017-06-22 00:00:00
[EXIT] 2017-06-22 00:00:00: PM r=-0.0040, PnL=$-30.56
[EXIT] 2017-06-22 00:00:00: CSCO r=0.0003, PnL=$1.94
[EXIT] 2017-06-22 00:00:00: ABB r=0.0048, PnL=$25.23
[EXIT] 2017-06-22 00:00:00: RDS-B r=-0.0007, PnL=$-3.46
[EXIT] 2017-06-22 00:00:00: MA r=0.0016, PnL=$7.80
[EXIT] 2017-06-22 00:00:00: NEE r=0.0038, PnL=$6.76

Simulating Trading Days:  44%|████▍     | 39/89 [57:34<2:10:02, 156.05s/it]

[SIM] 2017-06-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.720, kelly=0.404) with $4092.57 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.665, kelly=0.337) with $3411.75 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.878, kelly=0.756) with $7652.65 allocation
[PORT] Sector Financial: selecting MA (p_up=0.739, kelly=0.479) with $4849.44 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.687, kelly=0.365) with $3699.01 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.770, kelly=0.529) with $5356.75 allocation
[PORT] Sector Services: selecting WMT (p_up=0.754, kelly=0.503) with $5088.60 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.811, kelly=0.638) with $6459.74 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.701, kelly=0.382) with $3862.83 allocation
[SIM] 2017-06-22 00:00:00: 9 trades proposed.
[TRADE] 2017-06-22 00:00:00: allocated $7652.65 to PM exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $6459.74 to CSCO exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $5356.75 to ABB exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $5088.60 to WMT exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $4849.44 to MA exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $964.52 to RDS-B exiting on 2017-06-23 00:00:00
[EXIT] 2017-06-23 00:00:00: PM r=-0.0013, PnL=$-9.59
[EXIT] 2017-06-23 00:00:00: CSCO r=0.0075, PnL=$48.68
[EXIT] 2017-06-23 00:00:00: ABB r=0.0036, PnL=$19.05
[EXIT] 2017-06-23 00:00:00: WMT r=-0.0090, PnL=$-45.82
[EXIT] 2017-06-23 00:00:00: MA r=0.0058, PnL=$27.92
[EXIT] 2017-06-23 00:00:00: RDS-B r=0.0043, PnL=$4.12

Simulating Trading Days:  45%|████▍     | 40/89 [57:37<1:29:52, 110.04s/it]

[SIM] 2017-06-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.739, kelly=0.445) with $4505.95 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.674, kelly=0.355) with $3596.40 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.880, kelly=0.761) with $7708.84 allocation
[PORT] Sector Financial: selecting MA (p_up=0.741, kelly=0.482) with $4879.98 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.669, kelly=0.329) with $3331.70 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.782, kelly=0.553) with $5604.65 allocation
[PORT] Sector Services: selecting WMT (p_up=0.767, kelly=0.529) with $5356.14 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.822, kelly=0.659) with $6675.05 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.700, kelly=0.379) with $3839.70 allocation
[SIM] 2017-06-23 00:00:00: 9 trades proposed.
[TRADE] 2017-06-23 00:00:00: allocated $7708.84 to PM exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $6675.05 to CSCO exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $5604.65 to ABB exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $5356.14 to WMT exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $4879.98 to MA exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $160.33 to RDS-B exiting on 2017-06-26 00:00:00
[EXIT] 2017-06-26 00:00:00: PM r=-0.0004, PnL=$-3.22
[EXIT] 2017-06-26 00:00:00: CSCO r=0.0047, PnL=$31.20
[EXIT] 2017-06-26 00:00:00: ABB r=-0.0016, PnL=$-8.83
[EXIT] 2017-06-26 00:00:00: WMT r=0.0088, PnL=$47.24
[EXIT] 2017-06-26 00:00:00: MA r=-0.0040, PnL=$-19.28
[EXIT] 2017-06-26 00:00:00: RDS-B r=0.0019, PnL=$0.30

Simulating Trading Days:  46%|████▌     | 41/89 [57:39<1:02:15, 77.81s/it]

[SIM] 2017-06-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.800, kelly=0.575) with $5830.85 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.685, kelly=0.378) with $3829.70 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.884, kelly=0.768) with $7785.65 allocation
[PORT] Sector Financial: selecting MA (p_up=0.739, kelly=0.479) with $4849.20 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.654, kelly=0.298) with $3018.95 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.784, kelly=0.558) with $5654.99 allocation
[PORT] Sector Services: selecting WMT (p_up=0.780, kelly=0.556) with $5629.43 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.829, kelly=0.673) with $6818.98 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.705, kelly=0.390) with $3947.01 allocation
[SIM] 2017-06-26 00:00:00: 9 trades proposed.
[TRADE] 2017-06-26 00:00:00: allocated $7785.65 to PM exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $6818.98 to CSCO exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $5830.85 to RDS-B exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $5654.99 to ABB exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $4308.75 to WMT exiting on 2017-06-27 00:00:00
[EXIT] 2017-06-27 00:00:00: PM r=-0.0115, PnL=$-89.25
[EXIT] 2017-06-27 00:00:00: CSCO r=-0.0149, PnL=$-101.52
[EXIT] 2017-06-27 00:00:00: RDS-B r=0.0126, PnL=$73.26
[EXIT] 2017-06-27 00:00:00: ABB r=-0.0016, PnL=$-8.92
[EXIT] 2017-06-27 00:00:00: WMT r=0.0068, PnL=$29.11

Simulating Trading Days:  47%|████▋     | 42/89 [57:42<43:13, 55.19s/it]

[SIM] 2017-06-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.862, kelly=0.707) with $7159.65 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.694, kelly=0.395) with $3997.79 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.886, kelly=0.774) with $7830.89 allocation
[PORT] Sector Financial: selecting MA (p_up=0.742, kelly=0.484) with $4894.83 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.652, kelly=0.293) with $2970.10 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.774, kelly=0.537) with $5437.28 allocation
[PORT] Sector Services: selecting WMT (p_up=0.790, kelly=0.576) with $5831.37 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.833, kelly=0.680) with $6879.28 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.719, kelly=0.417) with $4221.48 allocation
[SIM] 2017-06-27 00:00:00: 9 trades proposed.
[TRADE] 2017-06-27 00:00:00: allocated $7830.89 to PM exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $7159.65 to RDS-B exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $6879.28 to CSCO exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $5831.37 to WMT exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $2668.84 to ABB exiting on 2017-06-28 00:00:00
[EXIT] 2017-06-28 00:00:00: PM r=0.0067, PnL=$52.37
[EXIT] 2017-06-28 00:00:00: RDS-B r=0.0113, PnL=$81.00
[EXIT] 2017-06-28 00:00:00: CSCO r=0.0101, PnL=$69.31
[EXIT] 2017-06-28 00:00:00: WMT r=0.0066, PnL=$38.36
[EXIT] 2017-06-28 00:00:00: ABB r=-0.0055, PnL=$-14.76

Simulating Trading Days:  48%|████▊     | 43/89 [57:44<30:08, 39.31s/it]

[SIM] 2017-06-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.902, kelly=0.792) with $8033.04 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.703, kelly=0.412) with $4180.80 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.888, kelly=0.776) with $7872.10 allocation
[PORT] Sector Financial: selecting MA (p_up=0.735, kelly=0.471) with $4775.62 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.668, kelly=0.328) with $3323.66 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.710, kelly=0.427) with $4333.81 allocation
[PORT] Sector Services: selecting WMT (p_up=0.798, kelly=0.592) with $6005.03 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.837, kelly=0.688) with $6978.44 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.716, kelly=0.411) with $4165.23 allocation
[SIM] 2017-06-28 00:00:00: 9 trades proposed.
[TRADE] 2017-06-28 00:00:00: allocated $8033.04 to RDS-B exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $7872.10 to PM exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $6978.44 to CSCO exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $6005.03 to WMT exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $1549.30 to MA exiting on 2017-06-29 00:00:00
[EXIT] 2017-06-29 00:00:00: RDS-B r=-0.0146, PnL=$-117.41
[EXIT] 2017-06-29 00:00:00: PM r=-0.0156, PnL=$-122.45
[EXIT] 2017-06-29 00:00:00: CSCO r=-0.0209, PnL=$-145.75
[EXIT] 2017-06-29 00:00:00: WMT r=-0.0076, PnL=$-45.52
[EXIT] 2017-06-29 00:00:00: MA r=-0.0264, PnL=$-40.96

Simulating Trading Days:  49%|████▉     | 44/89 [57:47<21:16, 28.36s/it]

[SIM] 2017-06-29 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.920, kelly=0.829) with $8375.42 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.714, kelly=0.434) with $4380.99 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.890, kelly=0.782) with $7894.26 allocation
[PORT] Sector Financial: selecting MA (p_up=0.743, kelly=0.487) with $4918.29 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.687, kelly=0.366) with $3695.90 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.749, kelly=0.506) with $5114.18 allocation
[PORT] Sector Services: selecting WMT (p_up=0.804, kelly=0.603) with $6088.18 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.842, kelly=0.697) with $7040.18 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.722, kelly=0.423) with $4272.39 allocation
[SIM] 2017-06-29 00:00:00: 9 trades proposed.
[TRADE] 2017-06-29 00:00:00: allocated $8375.42 to RDS-B exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $7894.26 to PM exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $7040.18 to CSCO exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $6088.18 to WMT exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $898.25 to UTX exiting on 2017-06-30 00:00:00
[EXIT] 2017-06-30 00:00:00: RDS-B r=-0.0033, PnL=$-27.61
[EXIT] 2017-06-30 00:00:00: PM r=0.0032, PnL=$24.95
[EXIT] 2017-06-30 00:00:00: CSCO r=-0.0035, PnL=$-24.66
[EXIT] 2017-06-30 00:00:00: WMT r=-0.0033, PnL=$-20.05
[EXIT] 2017-06-30 00:00:00: UTX r=0.0038, PnL=$3.40

Simulating Trading Days:  51%|█████     | 45/89 [57:49<15:05, 20.57s/it]

[SIM] 2017-06-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.917, kelly=0.824) with $8314.29 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.717, kelly=0.439) with $4435.04 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.891, kelly=0.782) with $7893.24 allocation
[PORT] Sector Financial: selecting MA (p_up=0.712, kelly=0.424) with $4281.56 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.688, kelly=0.367) with $3701.32 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.765, kelly=0.536) with $5414.07 allocation
[PORT] Sector Services: selecting WMT (p_up=0.804, kelly=0.603) with $6084.48 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.844, kelly=0.701) with $7077.25 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.730, kelly=0.440) with $4443.82 allocation
[SIM] 2017-06-30 00:00:00: 9 trades proposed.
[TRADE] 2017-06-30 00:00:00: allocated $8314.29 to RDS-B exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $7893.24 to PM exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $7077.25 to CSCO exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $6084.48 to WMT exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $913.82 to UTX exiting on 2017-07-03 00:00:00
[EXIT] 2017-07-03 00:00:00: RDS-B r=0.0105, PnL=$87.07
[EXIT] 2017-07-03 00:00:00: PM r=-0.0047, PnL=$-36.96
[EXIT] 2017-07-03 00:00:00: CSCO r=0.0010, PnL=$6.78
[EXIT] 2017-07-03 00:00:00: WMT r=-0.0042, PnL=$-25.73
[EXIT] 2017-07-03 00:00:00: UTX r=-0.0002, PnL=$-0.22

Simulating Trading Days:  52%|█████▏    | 46/89 [57:51<10:48, 15.08s/it]

[SIM] 2017-07-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.896, kelly=0.779) with $7861.17 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.722, kelly=0.450) with $4539.78 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.897, kelly=0.793) with $8012.01 allocation
[PORT] Sector Financial: selecting MA (p_up=0.781, kelly=0.561) with $5668.22 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.710, kelly=0.413) with $4165.66 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.779, kelly=0.564) with $5697.75 allocation
[PORT] Sector Services: selecting WMT (p_up=0.806, kelly=0.608) with $6136.41 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.845, kelly=0.702) with $7087.36 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.753, kelly=0.488) with $4929.20 allocation
[SIM] 2017-07-03 00:00:00: 9 trades proposed.
[TRADE] 2017-07-03 00:00:00: allocated $8012.01 to PM exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $7861.17 to RDS-B exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $7087.36 to CSCO exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $6136.41 to WMT exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $1195.42 to MA exiting on 2017-07-05 00:00:00
[EXIT] 2017-07-05 00:00:00: PM r=0.0140, PnL=$112.40
[EXIT] 2017-07-05 00:00:00: RDS-B r=-0.0122, PnL=$-95.76
[EXIT] 2017-07-05 00:00:00: CSCO r=-0.0070, PnL=$-49.77
[EXIT] 2017-07-05 00:00:00: WMT r=-0.0005, PnL=$-3.26
[EXIT] 2017-07-05 00:00:00: MA r=0.0099, PnL=$11.88

Simulating Trading Days:  53%|█████▎    | 47/89 [57:54<07:51, 11.23s/it]

[SIM] 2017-07-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.859, kelly=0.701) with $7076.08 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.724, kelly=0.452) with $4567.77 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.900, kelly=0.799) with $8070.58 allocation
[PORT] Sector Financial: selecting MA (p_up=0.768, kelly=0.537) with $5420.49 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.748, kelly=0.490) with $4943.92 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.784, kelly=0.575) with $5808.32 allocation
[PORT] Sector Services: selecting WMT (p_up=0.808, kelly=0.613) with $6183.93 allocation
[PORT] Sector Technology: selecting CSCO (p_up=0.839, kelly=0.691) with $6977.50 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.769, kelly=0.520) with $5253.80 allocation
[SIM] 2017-07-05 00:00:00: 9 trades proposed.
[TRADE] 2017-07-05 00:00:00: allocated $8070.58 to PM exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $7076.08 to RDS-B exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $6977.50 to CSCO exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $6183.93 to WMT exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $1976.93 to UTX exiting on 2017-07-06 00:00:00
[EXIT] 2017-07-06 00:00:00: PM r=-0.0016, PnL=$-12.94
[EXIT] 2017-07-06 00:00:00: RDS-B r=0.0004, PnL=$2.60
[EXIT] 2017-07-06 00:00:00: CSCO r=-0.0125, PnL=$-87.47
[EXIT] 2017-07-06 00:00:00: WMT r=0.0020, PnL=$12.32
[EXIT] 2017-07-06 00:00:00: UTX r=-0.0073, PnL=$-14.49

Simulating Trading Days:  54%|█████▍    | 48/89 [57:56<05:51,  8.57s/it]

[SIM] 2017-07-06 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.806, kelly=0.587) with $5919.64 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.724, kelly=0.454) with $4581.60 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.902, kelly=0.805) with $8113.75 allocation
[PORT] Sector Financial: selecting MA (p_up=0.754, kelly=0.509) with $5133.42 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.785, kelly=0.563) with $5682.00 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.778, kelly=0.564) with $5683.63 allocation
[PORT] Sector Services: selecting WMT (p_up=0.811, kelly=0.618) with $6232.42 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.882, kelly=0.764) with $7700.06 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.773, kelly=0.529) with $5333.74 allocation
[SIM] 2017-07-06 00:00:00: 9 trades proposed.
[TRADE] 2017-07-06 00:00:00: allocated $8113.75 to PM exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $7700.06 to VZ exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $6232.42 to WMT exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $5919.64 to RDS-B exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $2289.15 to SNY exiting on 2017-07-07 00:00:00
[EXIT] 2017-07-07 00:00:00: PM r=-0.0038, PnL=$-30.85
[EXIT] 2017-07-07 00:00:00: VZ r=-0.0009, PnL=$-7.08
[EXIT] 2017-07-07 00:00:00: WMT r=-0.0019, PnL=$-11.56
[EXIT] 2017-07-07 00:00:00: RDS-B r=-0.0031, PnL=$-18.52
[EXIT] 2017-07-07 00:00:00: SNY r=0.0144, PnL=$32.97

Simulating Trading Days:  55%|█████▌    | 49/89 [57:58<04:27,  6.68s/it]

[SIM] 2017-07-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.735, kelly=0.489) with $4930.60 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.724, kelly=0.453) with $4569.62 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.901, kelly=0.803) with $8093.04 allocation
[PORT] Sector Financial: selecting MA (p_up=0.756, kelly=0.512) with $5164.55 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.821, kelly=0.638) with $6428.24 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.765, kelly=0.538) with $5424.13 allocation
[PORT] Sector Services: selecting WMT (p_up=0.810, kelly=0.616) with $6212.42 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.878, kelly=0.754) with $7601.24 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.778, kelly=0.540) with $5443.40 allocation
[SIM] 2017-07-07 00:00:00: 9 trades proposed.
[TRADE] 2017-07-07 00:00:00: allocated $8093.04 to PM exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $7601.24 to VZ exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $6428.24 to SNY exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $6212.42 to WMT exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $1909.58 to NEE exiting on 2017-07-10 00:00:00
[EXIT] 2017-07-10 00:00:00: PM r=0.0022, PnL=$17.85
[EXIT] 2017-07-10 00:00:00: VZ r=-0.0064, PnL=$-48.95
[EXIT] 2017-07-10 00:00:00: SNY r=-0.0050, PnL=$-32.21
[EXIT] 2017-07-10 00:00:00: WMT r=-0.0279, PnL=$-173.19
[EXIT] 2017-07-10 00:00:00: NEE r=0.0039, PnL=$7.48

Simulating Trading Days:  56%|█████▌    | 50/89 [58:00<03:28,  5.35s/it]

[SIM] 2017-07-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.727, kelly=0.474) with $4771.82 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.727, kelly=0.459) with $4617.10 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.901, kelly=0.802) with $8068.52 allocation
[PORT] Sector Financial: selecting MA (p_up=0.767, kelly=0.534) with $5375.65 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.858, kelly=0.711) with $7155.58 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.786, kelly=0.564) with $5670.72 allocation
[PORT] Sector Services: selecting WMT (p_up=0.810, kelly=0.616) with $6195.63 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.898, kelly=0.795) with $7993.29 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.777, kelly=0.537) with $5403.44 allocation
[SIM] 2017-07-10 00:00:00: 9 trades proposed.
[TRADE] 2017-07-10 00:00:00: allocated $8068.52 to PM exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $7993.29 to VZ exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $7155.58 to SNY exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $6195.63 to WMT exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $762.79 to ABB exiting on 2017-07-11 00:00:00
[EXIT] 2017-07-11 00:00:00: PM r=-0.0080, PnL=$-64.87
[EXIT] 2017-07-11 00:00:00: VZ r=-0.0072, PnL=$-57.36
[EXIT] 2017-07-11 00:00:00: SNY r=0.0029, PnL=$21.02
[EXIT] 2017-07-11 00:00:00: WMT r=0.0033, PnL=$20.31
[EXIT] 2017-07-11 00:00:00: ABB r=0.0044, PnL=$3.39

Simulating Trading Days:  57%|█████▋    | 51/89 [58:03<02:47,  4.41s/it]

[SIM] 2017-07-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.711, kelly=0.442) with $4444.52 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.727, kelly=0.460) with $4626.54 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.897, kelly=0.796) with $7997.38 allocation
[PORT] Sector Financial: selecting MA (p_up=0.727, kelly=0.454) with $4560.80 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.879, kelly=0.755) with $7590.89 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.798, kelly=0.587) with $5899.88 allocation
[PORT] Sector Services: selecting WMT (p_up=0.808, kelly=0.611) with $6142.75 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.900, kelly=0.799) with $8025.99 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.765, kelly=0.513) with $5156.59 allocation
[SIM] 2017-07-11 00:00:00: 9 trades proposed.
[TRADE] 2017-07-11 00:00:00: allocated $8025.99 to VZ exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $7997.38 to PM exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $7590.89 to SNY exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $6142.75 to WMT exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $395.54 to ABB exiting on 2017-07-12 00:00:00
[EXIT] 2017-07-12 00:00:00: VZ r=0.0077, PnL=$61.75
[EXIT] 2017-07-12 00:00:00: PM r=0.0087, PnL=$69.60
[EXIT] 2017-07-12 00:00:00: SNY r=0.0228, PnL=$173.10
[EXIT] 2017-07-12 00:00:00: WMT r=0.0064, PnL=$39.30
[EXIT] 2017-07-12 00:00:00: ABB r=0.0161, PnL=$6.36

Simulating Trading Days:  58%|█████▊    | 52/89 [58:05<02:19,  3.77s/it]

[SIM] 2017-07-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.688, kelly=0.398) with $4016.49 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.729, kelly=0.463) with $4674.41 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.894, kelly=0.789) with $7954.92 allocation
[PORT] Sector Financial: selecting MA (p_up=0.726, kelly=0.453) with $4572.43 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.889, kelly=0.775) with $7818.00 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.802, kelly=0.595) with $6003.34 allocation
[PORT] Sector Services: selecting WMT (p_up=0.809, kelly=0.612) with $6176.36 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.901, kelly=0.801) with $8083.62 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.751, kelly=0.483) with $4875.63 allocation
[SIM] 2017-07-12 00:00:00: 9 trades proposed.
[TRADE] 2017-07-12 00:00:00: allocated $8083.62 to VZ exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $7954.92 to PM exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $7818.00 to SNY exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $6176.36 to WMT exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $224.69 to ABB exiting on 2017-07-13 00:00:00
[EXIT] 2017-07-13 00:00:00: VZ r=0.0062, PnL=$50.50
[EXIT] 2017-07-13 00:00:00: PM r=-0.0061, PnL=$-48.44
[EXIT] 2017-07-13 00:00:00: SNY r=-0.0051, PnL=$-39.98
[EXIT] 2017-07-13 00:00:00: WMT r=0.0150, PnL=$92.72
[EXIT] 2017-07-13 00:00:00: ABB r=-0.0111, PnL=$-2.49

Simulating Trading Days:  60%|█████▉    | 53/89 [58:07<01:59,  3.31s/it]

[SIM] 2017-07-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.709, kelly=0.399) with $4024.00 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.730, kelly=0.466) with $4706.21 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.892, kelly=0.786) with $7929.18 allocation
[PORT] Sector Financial: selecting MA (p_up=0.715, kelly=0.431) with $4350.82 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.884, kelly=0.765) with $7724.57 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.806, kelly=0.604) with $6090.48 allocation
[PORT] Sector Services: selecting WMT (p_up=0.812, kelly=0.618) with $6240.95 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.904, kelly=0.808) with $8154.79 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.736, kelly=0.452) with $4562.86 allocation
[SIM] 2017-07-13 00:00:00: 9 trades proposed.
[TRADE] 2017-07-13 00:00:00: allocated $8154.79 to VZ exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $7929.18 to PM exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $7724.57 to SNY exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $6240.95 to WMT exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $223.80 to ABB exiting on 2017-07-14 00:00:00
[EXIT] 2017-07-14 00:00:00: VZ r=0.0016, PnL=$13.13
[EXIT] 2017-07-14 00:00:00: PM r=0.0138, PnL=$109.31
[EXIT] 2017-07-14 00:00:00: SNY r=-0.0095, PnL=$-73.05
[EXIT] 2017-07-14 00:00:00: WMT r=0.0172, PnL=$107.27
[EXIT] 2017-07-14 00:00:00: ABB r=0.0072, PnL=$1.61

Simulating Trading Days:  61%|██████    | 54/89 [58:09<01:44,  3.00s/it]

[SIM] 2017-07-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.726, kelly=0.434) with $4387.62 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.728, kelly=0.463) with $4677.36 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.888, kelly=0.776) with $7847.83 allocation
[PORT] Sector Financial: selecting MA (p_up=0.702, kelly=0.404) with $4084.03 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.868, kelly=0.733) with $7408.56 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.796, kelly=0.584) with $5903.84 allocation
[PORT] Sector Services: selecting WMT (p_up=0.815, kelly=0.625) with $6320.30 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.899, kelly=0.798) with $8061.01 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.775, kelly=0.545) with $5506.01 allocation
[SIM] 2017-07-14 00:00:00: 9 trades proposed.
[TRADE] 2017-07-14 00:00:00: allocated $8061.01 to VZ exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $7847.83 to PM exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $7408.56 to SNY exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $6320.30 to WMT exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $683.07 to ABB exiting on 2017-07-17 00:00:00
[EXIT] 2017-07-17 00:00:00: VZ r=0.0023, PnL=$18.51
[EXIT] 2017-07-17 00:00:00: PM r=-0.0011, PnL=$-8.56
[EXIT] 2017-07-17 00:00:00: SNY r=0.0000, PnL=$0.00
[EXIT] 2017-07-17 00:00:00: WMT r=0.0004, PnL=$2.48
[EXIT] 2017-07-17 00:00:00: ABB r=-0.0032, PnL=$-2.17

Simulating Trading Days:  62%|██████▏   | 55/89 [58:12<01:34,  2.78s/it]

[SIM] 2017-07-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.721, kelly=0.423) with $4272.82 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.728, kelly=0.461) with $4662.54 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.884, kelly=0.769) with $7769.97 allocation
[PORT] Sector Financial: selecting MA (p_up=0.681, kelly=0.363) with $3667.08 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.841, kelly=0.679) with $6859.29 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.782, kelly=0.554) with $5603.32 allocation
[PORT] Sector Services: selecting WMT (p_up=0.816, kelly=0.628) with $6344.75 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.897, kelly=0.794) with $8021.52 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.757, kelly=0.508) with $5135.51 allocation
[SIM] 2017-07-17 00:00:00: 9 trades proposed.
[TRADE] 2017-07-17 00:00:00: allocated $8021.52 to VZ exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $7769.97 to PM exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $6859.29 to SNY exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $6344.75 to WMT exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $1328.31 to ABB exiting on 2017-07-18 00:00:00
[EXIT] 2017-07-18 00:00:00: VZ r=-0.0069, PnL=$-55.12
[EXIT] 2017-07-18 00:00:00: PM r=0.0054, PnL=$41.79
[EXIT] 2017-07-18 00:00:00: SNY r=-0.0091, PnL=$-62.64
[EXIT] 2017-07-18 00:00:00: WMT r=-0.0022, PnL=$-14.12
[EXIT] 2017-07-18 00:00:00: ABB r=-0.0024, PnL=$-3.18

Simulating Trading Days:  63%|██████▎   | 56/89 [58:14<01:26,  2.63s/it]

[SIM] 2017-07-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.696, kelly=0.373) with $3766.38 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.722, kelly=0.450) with $4542.35 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.878, kelly=0.758) with $7653.77 allocation
[PORT] Sector Financial: selecting MA (p_up=0.693, kelly=0.386) with $3895.02 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.804, kelly=0.602) with $6083.91 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.741, kelly=0.489) with $4941.77 allocation
[PORT] Sector Services: selecting WMT (p_up=0.812, kelly=0.619) with $6254.54 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.891, kelly=0.780) with $7876.42 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.686, kelly=0.349) with $3529.00 allocation
[SIM] 2017-07-18 00:00:00: 9 trades proposed.
[TRADE] 2017-07-18 00:00:00: allocated $7876.42 to VZ exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $7653.77 to PM exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $6254.54 to WMT exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $6083.91 to SNY exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $2427.23 to UTX exiting on 2017-07-19 00:00:00
[EXIT] 2017-07-19 00:00:00: VZ r=0.0021, PnL=$16.35
[EXIT] 2017-07-19 00:00:00: PM r=0.0165, PnL=$126.67
[EXIT] 2017-07-19 00:00:00: WMT r=-0.0043, PnL=$-27.09
[EXIT] 2017-07-19 00:00:00: SNY r=-0.0195, PnL=$-118.52
[EXIT] 2017-07-19 00:00:00: UTX r=0.0037, PnL=$8.91

Simulating Trading Days:  64%|██████▍   | 57/89 [58:16<01:20,  2.51s/it]

[SIM] 2017-07-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.659, kelly=0.343) with $3463.27 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.715, kelly=0.436) with $4401.34 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.875, kelly=0.750) with $7577.15 allocation
[PORT] Sector Financial: selecting MA (p_up=0.690, kelly=0.380) with $3838.61 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.767, kelly=0.527) with $5326.16 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.747, kelly=0.501) with $5059.40 allocation
[PORT] Sector Services: selecting WMT (p_up=0.807, kelly=0.609) with $6149.29 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.892, kelly=0.782) with $7897.21 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.685, kelly=0.348) with $3515.28 allocation
[SIM] 2017-07-19 00:00:00: 9 trades proposed.
[TRADE] 2017-07-19 00:00:00: allocated $7897.21 to VZ exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $7577.15 to PM exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $6149.29 to WMT exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $5326.16 to SNY exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $3347.93 to UTX exiting on 2017-07-20 00:00:00
[EXIT] 2017-07-20 00:00:00: VZ r=0.0177, PnL=$139.95
[EXIT] 2017-07-20 00:00:00: PM r=-0.0145, PnL=$-109.65
[EXIT] 2017-07-20 00:00:00: WMT r=0.0020, PnL=$12.16
[EXIT] 2017-07-20 00:00:00: SNY r=0.0267, PnL=$142.23
[EXIT] 2017-07-20 00:00:00: UTX r=-0.0051, PnL=$-17.14

Simulating Trading Days:  65%|██████▌   | 58/89 [58:18<01:15,  2.42s/it]

[SIM] 2017-07-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.693, kelly=0.409) with $4133.80 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.715, kelly=0.436) with $4409.24 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.869, kelly=0.741) with $7491.51 allocation
[PORT] Sector Financial: selecting MA (p_up=0.706, kelly=0.411) with $4159.01 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.736, kelly=0.464) with $4695.56 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.757, kelly=0.520) with $5260.45 allocation
[PORT] Sector Services: selecting WMT (p_up=0.799, kelly=0.595) with $6013.99 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.898, kelly=0.795) with $8038.56 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.669, kelly=0.313) with $3169.78 allocation
[SIM] 2017-07-20 00:00:00: 9 trades proposed.
[TRADE] 2017-07-20 00:00:00: allocated $8038.56 to VZ exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $7491.51 to PM exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $6013.99 to WMT exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $5260.45 to UTX exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $3543.50 to SNY exiting on 2017-07-21 00:00:00
[EXIT] 2017-07-21 00:00:00: VZ r=0.0002, PnL=$1.82
[EXIT] 2017-07-21 00:00:00: PM r=-0.0023, PnL=$-17.50
[EXIT] 2017-07-21 00:00:00: WMT r=0.0017, PnL=$10.28
[EXIT] 2017-07-21 00:00:00: UTX r=0.0085, PnL=$44.68
[EXIT] 2017-07-21 00:00:00: SNY r=-0.0073, PnL=$-25.81

Simulating Trading Days:  66%|██████▋   | 59/89 [58:21<01:11,  2.38s/it]

[SIM] 2017-07-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.715, kelly=0.452) with $4570.58 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.716, kelly=0.438) with $4427.23 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.865, kelly=0.732) with $7407.34 allocation
[PORT] Sector Financial: selecting MA (p_up=0.696, kelly=0.392) with $3961.22 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.728, kelly=0.449) with $4542.87 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.756, kelly=0.519) with $5252.78 allocation
[PORT] Sector Services: selecting WMT (p_up=0.796, kelly=0.588) with $5952.62 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.905, kelly=0.808) with $8179.74 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.640, kelly=0.254) with $2571.85 allocation
[SIM] 2017-07-21 00:00:00: 9 trades proposed.
[TRADE] 2017-07-21 00:00:00: allocated $8179.74 to VZ exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $7407.34 to PM exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $5952.62 to WMT exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $5252.78 to UTX exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $3559.58 to SNY exiting on 2017-07-24 00:00:00
[EXIT] 2017-07-24 00:00:00: VZ r=-0.0118, PnL=$-96.17
[EXIT] 2017-07-24 00:00:00: PM r=-0.0058, PnL=$-42.74
[EXIT] 2017-07-24 00:00:00: WMT r=0.0097, PnL=$57.85
[EXIT] 2017-07-24 00:00:00: UTX r=-0.0029, PnL=$-15.31
[EXIT] 2017-07-24 00:00:00: SNY r=0.0000, PnL=$0.00

Simulating Trading Days:  67%|██████▋   | 60/89 [58:23<01:07,  2.34s/it]

[SIM] 2017-07-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.724, kelly=0.469) with $4744.56 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.721, kelly=0.447) with $4519.10 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.868, kelly=0.737) with $7446.02 allocation
[PORT] Sector Financial: selecting MA (p_up=0.707, kelly=0.412) with $4167.60 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.748, kelly=0.490) with $4953.64 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.747, kelly=0.502) with $5074.26 allocation
[PORT] Sector Services: selecting WMT (p_up=0.791, kelly=0.577) with $5837.02 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.915, kelly=0.828) with $8371.28 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.614, kelly=0.199) with $2015.64 allocation
[SIM] 2017-07-24 00:00:00: 9 trades proposed.
[TRADE] 2017-07-24 00:00:00: allocated $8371.28 to VZ exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $7446.02 to PM exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $5837.02 to WMT exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $4953.64 to SNY exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $3715.18 to UTX exiting on 2017-07-25 00:00:00
[EXIT] 2017-07-25 00:00:00: VZ r=0.0062, PnL=$51.71
[EXIT] 2017-07-25 00:00:00: PM r=-0.0090, PnL=$-67.01
[EXIT] 2017-07-25 00:00:00: WMT r=0.0212, PnL=$123.74
[EXIT] 2017-07-25 00:00:00: SNY r=0.0075, PnL=$37.38
[EXIT] 2017-07-25 00:00:00: UTX r=-0.0220, PnL=$-81.77

Simulating Trading Days:  69%|██████▊   | 61/89 [58:25<01:05,  2.33s/it]

[SIM] 2017-07-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.725, kelly=0.471) with $4760.52 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.721, kelly=0.448) with $4530.90 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.871, kelly=0.743) with $7516.94 allocation
[PORT] Sector Financial: selecting MA (p_up=0.720, kelly=0.438) with $4424.98 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.782, kelly=0.558) with $5648.10 allocation
[PORT] Sector Industrial Goods: selecting UTX (p_up=0.725, kelly=0.458) with $4633.60 allocation
[PORT] Sector Services: selecting WMT (p_up=0.789, kelly=0.573) with $5793.66 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.917, kelly=0.833) with $8422.15 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.588, kelly=0.146) with $1479.07 allocation
[SIM] 2017-07-25 00:00:00: 9 trades proposed.
[TRADE] 2017-07-25 00:00:00: allocated $8422.15 to VZ exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $7516.94 to PM exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $5793.66 to WMT exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $5648.10 to SNY exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $2961.51 to UTX exiting on 2017-07-26 00:00:00
[EXIT] 2017-07-26 00:00:00: VZ r=0.0095, PnL=$80.43
[EXIT] 2017-07-26 00:00:00: PM r=-0.0014, PnL=$-10.85
[EXIT] 2017-07-26 00:00:00: WMT r=0.0048, PnL=$28.04
[EXIT] 2017-07-26 00:00:00: SNY r=-0.0010, PnL=$-5.87
[EXIT] 2017-07-26 00:00:00: UTX r=-0.0073, PnL=$-21.64

Simulating Trading Days:  70%|██████▉   | 62/89 [58:28<01:02,  2.32s/it]

[SIM] 2017-07-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.725, kelly=0.472) with $4776.52 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.727, kelly=0.460) with $4656.98 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.875, kelly=0.750) with $7595.66 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.760, kelly=0.534) with $5400.31 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.816, kelly=0.627) with $6349.00 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.791, kelly=0.571) with $5783.69 allocation
[PORT] Sector Services: selecting WMT (p_up=0.784, kelly=0.563) with $5700.40 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.916, kelly=0.831) with $8414.65 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.614, kelly=0.217) with $2196.90 allocation
[SIM] 2017-07-26 00:00:00: 9 trades proposed.
[TRADE] 2017-07-26 00:00:00: allocated $8414.65 to VZ exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $7595.66 to PM exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $6349.00 to SNY exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $5783.69 to ABB exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $2220.39 to WMT exiting on 2017-07-27 00:00:00
[EXIT] 2017-07-27 00:00:00: VZ r=0.0768, PnL=$646.26
[EXIT] 2017-07-27 00:00:00: PM r=0.0046, PnL=$34.86
[EXIT] 2017-07-27 00:00:00: SNY r=0.0015, PnL=$9.26
[EXIT] 2017-07-27 00:00:00: ABB r=-0.0017, PnL=$-9.89
[EXIT] 2017-07-27 00:00:00: WMT r=0.0112, PnL=$24.76

Simulating Trading Days:  71%|███████   | 63/89 [58:30<01:00,  2.31s/it]

[SIM] 2017-07-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.714, kelly=0.449) with $4580.83 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.723, kelly=0.452) with $4604.33 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.880, kelly=0.761) with $7754.92 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.764, kelly=0.542) with $5524.53 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.846, kelly=0.689) with $7025.91 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.859, kelly=0.711) with $7246.75 allocation
[PORT] Sector Services: selecting WMT (p_up=0.773, kelly=0.542) with $5524.53 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.930, kelly=0.860) with $8761.19 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.646, kelly=0.282) with $2877.76 allocation
[SIM] 2017-07-27 00:00:00: 9 trades proposed.
[TRADE] 2017-07-27 00:00:00: allocated $8761.19 to VZ exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $7754.92 to PM exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $7246.75 to ABB exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $6812.11 to SNY exiting on 2017-07-28 00:00:00
[EXIT] 2017-07-28 00:00:00: VZ r=0.0027, PnL=$23.82
[EXIT] 2017-07-28 00:00:00: PM r=0.0027, PnL=$21.00
[EXIT] 2017-07-28 00:00:00: ABB r=0.0064, PnL=$46.55
[EXIT] 2017-07-28 00:00:00: SNY r=-0.0110, PnL=$-75.08

Simulating Trading Days:  72%|███████▏  | 64/89 [58:32<00:57,  2.31s/it]

[SIM] 2017-07-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.695, kelly=0.415) with $4226.87 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.721, kelly=0.448) with $4562.02 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.883, kelly=0.768) with $7829.27 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.778, kelly=0.569) with $5803.75 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.866, kelly=0.729) with $7429.36 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.916, kelly=0.828) with $8435.42 allocation
[PORT] Sector Services: selecting WMT (p_up=0.762, kelly=0.518) with $5285.14 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.939, kelly=0.878) with $8946.11 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.675, kelly=0.341) with $3474.18 allocation
[SIM] 2017-07-28 00:00:00: 9 trades proposed.
[TRADE] 2017-07-28 00:00:00: allocated $8946.11 to VZ exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $8435.42 to ABB exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $7829.27 to PM exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $5369.06 to SNY exiting on 2017-07-31 00:00:00
[EXIT] 2017-07-31 00:00:00: VZ r=0.0096, PnL=$85.84
[EXIT] 2017-07-31 00:00:00: ABB r=0.0000, PnL=$0.00
[EXIT] 2017-07-31 00:00:00: PM r=-0.0152, PnL=$-118.92
[EXIT] 2017-07-31 00:00:00: SNY r=-0.0042, PnL=$-22.58

Simulating Trading Days:  73%|███████▎  | 65/89 [58:34<00:54,  2.29s/it]

[SIM] 2017-07-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.683, kelly=0.391) with $3987.80 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.730, kelly=0.464) with $4724.79 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.884, kelly=0.769) with $7830.14 allocation
[PORT] Sector Financial: selecting MA (p_up=0.764, kelly=0.526) with $5356.07 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.879, kelly=0.756) with $7700.92 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.935, kelly=0.867) with $8830.70 allocation
[PORT] Sector Services: selecting WMT (p_up=0.747, kelly=0.488) with $4973.09 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.952, kelly=0.904) with $9205.07 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.697, kelly=0.386) with $3936.07 allocation
[SIM] 2017-07-31 00:00:00: 9 trades proposed.
[TRADE] 2017-07-31 00:00:00: allocated $9205.07 to VZ exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $8830.70 to ABB exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $7830.14 to PM exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $4697.24 to SNY exiting on 2017-08-01 00:00:00
[EXIT] 2017-08-01 00:00:00: VZ r=0.0101, PnL=$93.19
[EXIT] 2017-08-01 00:00:00: ABB r=0.0060, PnL=$52.61
[EXIT] 2017-08-01 00:00:00: PM r=-0.0071, PnL=$-55.69
[EXIT] 2017-08-01 00:00:00: SNY r=-0.0068, PnL=$-31.74

Simulating Trading Days:  74%|███████▍  | 66/89 [58:37<00:52,  2.29s/it]

[SIM] 2017-08-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.686, kelly=0.396) with $4036.32 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.743, kelly=0.490) with $4995.14 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.889, kelly=0.779) with $7945.35 allocation
[PORT] Sector Financial: selecting MA (p_up=0.803, kelly=0.605) with $6164.31 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.886, kelly=0.769) with $7841.32 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.937, kelly=0.872) with $8885.53 allocation
[PORT] Sector Services: selecting WMT (p_up=0.733, kelly=0.459) with $4679.18 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.929, kelly=0.859) with $8755.74 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.711, kelly=0.415) with $4228.43 allocation
[SIM] 2017-08-01 00:00:00: 9 trades proposed.
[TRADE] 2017-08-01 00:00:00: allocated $8885.53 to ABB exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $8755.74 to VZ exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $7945.35 to PM exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $4994.05 to SNY exiting on 2017-08-02 00:00:00
[EXIT] 2017-08-02 00:00:00: ABB r=-0.0013, PnL=$-11.28
[EXIT] 2017-08-02 00:00:00: VZ r=-0.0139, PnL=$-121.78
[EXIT] 2017-08-02 00:00:00: PM r=-0.0123, PnL=$-97.36
[EXIT] 2017-08-02 00:00:00: SNY r=0.0094, PnL=$46.71

Simulating Trading Days:  75%|███████▌  | 67/89 [58:39<00:50,  2.27s/it]

[SIM] 2017-08-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.698, kelly=0.419) with $4259.33 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.754, kelly=0.513) with $5218.78 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.897, kelly=0.795) with $8085.68 allocation
[PORT] Sector Financial: selecting MA (p_up=0.816, kelly=0.632) with $6430.54 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.890, kelly=0.777) with $7910.89 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.931, kelly=0.859) with $8739.37 allocation
[PORT] Sector Services: selecting WMT (p_up=0.717, kelly=0.429) with $4360.73 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.900, kelly=0.800) with $8140.49 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.719, kelly=0.430) with $4374.59 allocation
[SIM] 2017-08-02 00:00:00: 9 trades proposed.
[TRADE] 2017-08-02 00:00:00: allocated $8739.37 to ABB exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $8140.49 to VZ exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $8085.68 to PM exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $5560.01 to SNY exiting on 2017-08-03 00:00:00
[EXIT] 2017-08-03 00:00:00: ABB r=-0.0055, PnL=$-48.12
[EXIT] 2017-08-03 00:00:00: VZ r=0.0083, PnL=$67.54
[EXIT] 2017-08-03 00:00:00: PM r=0.0003, PnL=$2.12
[EXIT] 2017-08-03 00:00:00: SNY r=0.0042, PnL=$23.42

Simulating Trading Days:  76%|███████▋  | 68/89 [58:41<00:47,  2.28s/it]

[SIM] 2017-08-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.720, kelly=0.460) with $4683.48 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.760, kelly=0.524) with $5329.49 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.903, kelly=0.807) with $8211.81 allocation
[PORT] Sector Financial: selecting MA (p_up=0.807, kelly=0.613) with $6239.59 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.894, kelly=0.786) with $7998.47 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.923, kelly=0.843) with $8579.00 allocation
[PORT] Sector Services: selecting WMT (p_up=0.714, kelly=0.420) with $4279.58 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.864, kelly=0.730) with $7429.54 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.721, kelly=0.434) with $4420.12 allocation
[SIM] 2017-08-03 00:00:00: 9 trades proposed.
[TRADE] 2017-08-03 00:00:00: allocated $8579.00 to ABB exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $8211.81 to PM exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $7998.47 to SNY exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $5749.76 to ORCL exiting on 2017-08-04 00:00:00
[EXIT] 2017-08-04 00:00:00: ABB r=-0.0038, PnL=$-32.88
[EXIT] 2017-08-04 00:00:00: PM r=0.0024, PnL=$19.37
[EXIT] 2017-08-04 00:00:00: SNY r=0.0084, PnL=$67.10
[EXIT] 2017-08-04 00:00:00: ORCL r=-0.0054, PnL=$-30.91

Simulating Trading Days:  78%|███████▊  | 69/89 [58:43<00:45,  2.27s/it]

[SIM] 2017-08-04 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.745, kelly=0.508) with $5171.64 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.767, kelly=0.538) with $5478.88 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.907, kelly=0.815) with $8303.26 allocation
[PORT] Sector Financial: selecting MA (p_up=0.780, kelly=0.558) with $5685.91 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.897, kelly=0.791) with $8057.92 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.912, kelly=0.821) with $8357.35 allocation
[PORT] Sector Services: selecting WMT (p_up=0.710, kelly=0.413) with $4207.97 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.897, kelly=0.796) with $8106.86 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.720, kelly=0.432) with $4397.41 allocation
[SIM] 2017-08-04 00:00:00: 9 trades proposed.
[TRADE] 2017-08-04 00:00:00: allocated $8357.35 to ABB exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $8303.26 to PM exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $8106.86 to ORCL exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $5778.39 to SNY exiting on 2017-08-07 00:00:00
[EXIT] 2017-08-07 00:00:00: ABB r=-0.0013, PnL=$-10.72
[EXIT] 2017-08-07 00:00:00: PM r=0.0096, PnL=$79.59
[EXIT] 2017-08-07 00:00:00: ORCL r=-0.0064, PnL=$-51.93
[EXIT] 2017-08-07 00:00:00: SNY r=-0.0023, PnL=$-13.22

Simulating Trading Days:  79%|███████▊  | 70/89 [58:46<00:43,  2.27s/it]

[SIM] 2017-08-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.763, kelly=0.544) with $5540.07 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.770, kelly=0.544) with $5541.31 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.913, kelly=0.826) with $8414.42 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.815, kelly=0.641) with $6523.73 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.900, kelly=0.798) with $8124.72 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.899, kelly=0.793) with $8078.63 allocation
[PORT] Sector Services: selecting WMT (p_up=0.706, kelly=0.404) with $4113.82 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.915, kelly=0.831) with $8457.34 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.716, kelly=0.425) with $4323.36 allocation
[SIM] 2017-08-07 00:00:00: 9 trades proposed.
[TRADE] 2017-08-07 00:00:00: allocated $8457.34 to ORCL exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $8414.42 to PM exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $8124.72 to SNY exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $5550.49 to ABB exiting on 2017-08-08 00:00:00
[EXIT] 2017-08-08 00:00:00: ORCL r=-0.0109, PnL=$-92.00
[EXIT] 2017-08-08 00:00:00: PM r=-0.0103, PnL=$-86.42
[EXIT] 2017-08-08 00:00:00: SNY r=-0.0010, PnL=$-8.47
[EXIT] 2017-08-08 00:00:00: ABB r=-0.0021, PnL=$-11.88

Simulating Trading Days:  80%|███████▉  | 71/89 [58:48<00:40,  2.27s/it]

[SIM] 2017-08-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.768, kelly=0.552) with $5610.80 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.773, kelly=0.551) with $5598.30 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.916, kelly=0.832) with $8454.28 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.855, kelly=0.718) with $7295.95 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.903, kelly=0.805) with $8176.35 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.884, kelly=0.764) with $7760.27 allocation
[PORT] Sector Services: selecting WMT (p_up=0.701, kelly=0.395) with $4014.59 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.926, kelly=0.853) with $8673.18 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.712, kelly=0.416) with $4229.01 allocation
[SIM] 2017-08-08 00:00:00: 9 trades proposed.
[TRADE] 2017-08-08 00:00:00: allocated $8673.18 to ORCL exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $8454.28 to PM exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $8176.35 to SNY exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $5183.52 to ABB exiting on 2017-08-09 00:00:00
[EXIT] 2017-08-09 00:00:00: ORCL r=-0.0008, PnL=$-7.07
[EXIT] 2017-08-09 00:00:00: PM r=0.0065, PnL=$54.56
[EXIT] 2017-08-09 00:00:00: SNY r=-0.0035, PnL=$-29.01
[EXIT] 2017-08-09 00:00:00: ABB r=-0.0021, PnL=$-11.12

Simulating Trading Days:  81%|████████  | 72/89 [58:50<00:38,  2.27s/it]

[SIM] 2017-08-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.742, kelly=0.504) with $5118.21 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.778, kelly=0.560) with $5688.28 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.914, kelly=0.829) with $8429.22 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.901, kelly=0.807) with $8202.31 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.902, kelly=0.802) with $8146.73 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.879, kelly=0.752) with $7647.72 allocation
[PORT] Sector Services: selecting WMT (p_up=0.695, kelly=0.383) with $3894.93 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.937, kelly=0.875) with $8889.12 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.708, kelly=0.407) with $4138.96 allocation
[SIM] 2017-08-09 00:00:00: 9 trades proposed.
[TRADE] 2017-08-09 00:00:00: allocated $8889.12 to ORCL exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $8429.22 to PM exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $8146.73 to SNY exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $5024.47 to WFC exiting on 2017-08-10 00:00:00
[EXIT] 2017-08-10 00:00:00: ORCL r=-0.0196, PnL=$-173.94
[EXIT] 2017-08-10 00:00:00: PM r=-0.0103, PnL=$-86.91
[EXIT] 2017-08-10 00:00:00: SNY r=-0.0071, PnL=$-58.01
[EXIT] 2017-08-10 00:00:00: WFC r=-0.0159, PnL=$-79.95

Simulating Trading Days:  82%|████████▏ | 73/89 [58:53<00:36,  2.28s/it]

[SIM] 2017-08-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.668, kelly=0.360) with $3645.05 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.781, kelly=0.566) with $5725.27 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.914, kelly=0.828) with $8377.28 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.925, kelly=0.855) with $8651.70 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.900, kelly=0.797) with $8072.41 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.872, kelly=0.739) with $7486.15 allocation
[PORT] Sector Services: selecting WMT (p_up=0.689, kelly=0.371) with $3752.91 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.946, kelly=0.893) with $9040.63 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.703, kelly=0.398) with $4024.45 allocation
[SIM] 2017-08-10 00:00:00: 9 trades proposed.
[TRADE] 2017-08-10 00:00:00: allocated $9040.63 to ORCL exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $8651.70 to WFC exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $8377.28 to PM exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $4300.29 to SNY exiting on 2017-08-11 00:00:00
[EXIT] 2017-08-11 00:00:00: ORCL r=0.0029, PnL=$26.31
[EXIT] 2017-08-11 00:00:00: WFC r=-0.0002, PnL=$-1.67
[EXIT] 2017-08-11 00:00:00: PM r=0.0058, PnL=$48.41
[EXIT] 2017-08-11 00:00:00: SNY r=0.0030, PnL=$12.70

Simulating Trading Days:  83%|████████▎ | 74/89 [58:55<00:34,  2.28s/it]

[SIM] 2017-08-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BP (p_up=0.664, kelly=0.331) with $3357.46 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.783, kelly=0.569) with $5768.25 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.911, kelly=0.823) with $8336.80 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.916, kelly=0.837) with $8479.48 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.893, kelly=0.784) with $7945.08 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.873, kelly=0.741) with $7502.82 allocation
[PORT] Sector Services: selecting WMT (p_up=0.680, kelly=0.352) with $3564.83 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.954, kelly=0.908) with $9202.04 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.697, kelly=0.385) with $3897.59 allocation
[SIM] 2017-08-11 00:00:00: 9 trades proposed.
[TRADE] 2017-08-11 00:00:00: allocated $9202.04 to ORCL exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $8479.48 to WFC exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $8336.80 to PM exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $4377.31 to SNY exiting on 2017-08-14 00:00:00
[EXIT] 2017-08-14 00:00:00: ORCL r=0.0126, PnL=$116.36
[EXIT] 2017-08-14 00:00:00: WFC r=0.0173, PnL=$146.93
[EXIT] 2017-08-14 00:00:00: PM r=-0.0010, PnL=$-8.71
[EXIT] 2017-08-14 00:00:00: SNY r=0.0038, PnL=$16.57

Simulating Trading Days:  84%|████████▍ | 75/89 [58:57<00:32,  2.29s/it]

[SIM] 2017-08-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BP (p_up=0.658, kelly=0.318) with $3233.90 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.785, kelly=0.575) with $5839.93 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.912, kelly=0.824) with $8375.04 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.936, kelly=0.876) with $8901.54 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.888, kelly=0.775) with $7869.79 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.871, kelly=0.737) with $7489.71 allocation
[PORT] Sector Services: selecting MCD (p_up=0.671, kelly=0.332) with $3370.03 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.970, kelly=0.940) with $9554.38 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.693, kelly=0.377) with $3833.61 allocation
[SIM] 2017-08-14 00:00:00: 9 trades proposed.
[TRADE] 2017-08-14 00:00:00: allocated $9554.38 to ORCL exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $8901.54 to WFC exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $8375.04 to PM exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $3646.01 to SNY exiting on 2017-08-15 00:00:00
[EXIT] 2017-08-15 00:00:00: ORCL r=-0.0004, PnL=$-3.91
[EXIT] 2017-08-15 00:00:00: WFC r=0.0002, PnL=$1.68
[EXIT] 2017-08-15 00:00:00: PM r=0.0180, PnL=$150.34
[EXIT] 2017-08-15 00:00:00: SNY r=0.0021, PnL=$7.64

Simulating Trading Days:  85%|████████▌ | 76/89 [58:59<00:29,  2.30s/it]

[SIM] 2017-08-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BP (p_up=0.629, kelly=0.262) with $2662.19 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.788, kelly=0.581) with $5906.86 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.910, kelly=0.822) with $8358.42 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.946, kelly=0.895) with $9107.89 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.883, kelly=0.763) with $7763.09 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.868, kelly=0.731) with $7435.49 allocation
[PORT] Sector Services: selecting MCD (p_up=0.677, kelly=0.344) with $3497.35 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.974, kelly=0.947) with $9639.75 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.687, kelly=0.365) with $3718.66 allocation
[SIM] 2017-08-15 00:00:00: 9 trades proposed.
[TRADE] 2017-08-15 00:00:00: allocated $9639.75 to ORCL exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $9107.89 to WFC exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $8358.42 to PM exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $3417.64 to SNY exiting on 2017-08-16 00:00:00
[EXIT] 2017-08-16 00:00:00: ORCL r=0.0086, PnL=$82.91
[EXIT] 2017-08-16 00:00:00: WFC r=-0.0030, PnL=$-27.57
[EXIT] 2017-08-16 00:00:00: PM r=0.0078, PnL=$65.11
[EXIT] 2017-08-16 00:00:00: SNY r=0.0125, PnL=$42.87

Simulating Trading Days:  87%|████████▋ | 77/89 [59:02<00:27,  2.29s/it]

[SIM] 2017-08-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.630, kelly=0.286) with $2919.47 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.789, kelly=0.582) with $5927.85 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.907, kelly=0.815) with $8301.85 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.927, kelly=0.858) with $8748.63 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.874, kelly=0.746) with $7601.07 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.864, kelly=0.722) with $7361.90 allocation
[PORT] Sector Services: selecting MCD (p_up=0.678, kelly=0.346) with $3528.26 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.971, kelly=0.943) with $9606.40 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.680, kelly=0.350) with $3569.24 allocation
[SIM] 2017-08-16 00:00:00: 9 trades proposed.
[TRADE] 2017-08-16 00:00:00: allocated $9606.40 to ORCL exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $8748.63 to WFC exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $8301.85 to PM exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $3915.82 to SNY exiting on 2017-08-17 00:00:00
[EXIT] 2017-08-17 00:00:00: ORCL r=-0.0142, PnL=$-136.54
[EXIT] 2017-08-17 00:00:00: WFC r=-0.0169, PnL=$-147.78
[EXIT] 2017-08-17 00:00:00: PM r=-0.0153, PnL=$-126.93
[EXIT] 2017-08-17 00:00:00: SNY r=-0.0072, PnL=$-28.30

Simulating Trading Days:  88%|████████▊ | 78/89 [59:04<00:25,  2.28s/it]

[SIM] 2017-08-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.710, kelly=0.440) with $4460.67 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.793, kelly=0.589) with $5974.94 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.900, kelly=0.801) with $8130.29 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.912, kelly=0.830) with $8420.82 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.874, kelly=0.744) with $7553.35 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.862, kelly=0.719) with $7292.04 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.664, kelly=0.387) with $3922.04 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.968, kelly=0.937) with $9504.54 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.671, kelly=0.332) with $3371.69 allocation
[SIM] 2017-08-17 00:00:00: 9 trades proposed.
[TRADE] 2017-08-17 00:00:00: allocated $9504.54 to ORCL exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $8420.82 to WFC exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $8130.29 to PM exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $4385.19 to SNY exiting on 2017-08-18 00:00:00
[EXIT] 2017-08-18 00:00:00: ORCL r=0.0014, PnL=$13.70
[EXIT] 2017-08-18 00:00:00: WFC r=-0.0023, PnL=$-19.51
[EXIT] 2017-08-18 00:00:00: PM r=-0.0052, PnL=$-42.08
[EXIT] 2017-08-18 00:00:00: SNY r=0.0023, PnL=$10.03

Simulating Trading Days:  89%|████████▉ | 79/89 [59:06<00:22,  2.29s/it]

[SIM] 2017-08-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.725, kelly=0.470) with $4764.78 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.792, kelly=0.588) with $5959.34 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.896, kelly=0.792) with $8033.74 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.893, kelly=0.793) with $8040.70 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.875, kelly=0.748) with $7588.50 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.858, kelly=0.710) with $7200.05 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.671, kelly=0.399) with $4047.37 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.961, kelly=0.922) with $9349.26 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.657, kelly=0.306) with $3099.12 allocation
[SIM] 2017-08-18 00:00:00: 9 trades proposed.
[TRADE] 2017-08-18 00:00:00: allocated $9349.26 to ORCL exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $8033.74 to PM exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $8040.70 to WFC exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $5005.78 to SNY exiting on 2017-08-21 00:00:00
[EXIT] 2017-08-21 00:00:00: ORCL r=0.0058, PnL=$53.84
[EXIT] 2017-08-21 00:00:00: PM r=0.0080, PnL=$64.09
[EXIT] 2017-08-21 00:00:00: WFC r=0.0027, PnL=$21.78
[EXIT] 2017-08-21 00:00:00: SNY r=0.0006, PnL=$3.12

Simulating Trading Days:  90%|████████▉ | 80/89 [59:09<00:20,  2.29s/it]

[SIM] 2017-08-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.723, kelly=0.465) with $4721.62 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.793, kelly=0.590) with $5991.16 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.895, kelly=0.791) with $8030.43 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.899, kelly=0.805) with $8173.48 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.883, kelly=0.763) with $7755.11 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.843, kelly=0.679) with $6897.80 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.698, kelly=0.449) with $4562.39 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.961, kelly=0.923) with $9375.52 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.645, kelly=0.281) with $2854.08 allocation
[SIM] 2017-08-21 00:00:00: 9 trades proposed.
[TRADE] 2017-08-21 00:00:00: allocated $9375.52 to ORCL exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $8173.48 to WFC exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $8030.43 to PM exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $4892.91 to SNY exiting on 2017-08-22 00:00:00
[EXIT] 2017-08-22 00:00:00: ORCL r=0.0074, PnL=$69.02
[EXIT] 2017-08-22 00:00:00: WFC r=0.0077, PnL=$63.09
[EXIT] 2017-08-22 00:00:00: PM r=-0.0002, PnL=$-1.38
[EXIT] 2017-08-22 00:00:00: SNY r=0.0050, PnL=$24.35

Simulating Trading Days:  91%|█████████ | 81/89 [59:11<00:18,  2.30s/it]

[SIM] 2017-08-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.721, kelly=0.462) with $4701.68 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.796, kelly=0.596) with $6059.85 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.895, kelly=0.790) with $8039.65 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.902, kelly=0.810) with $8244.52 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.888, kelly=0.773) with $7866.90 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.825, kelly=0.643) with $6540.63 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.712, kelly=0.475) with $4831.46 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.956, kelly=0.912) with $9280.01 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.631, kelly=0.252) with $2568.24 allocation
[SIM] 2017-08-22 00:00:00: 9 trades proposed.
[TRADE] 2017-08-22 00:00:00: allocated $9280.01 to ORCL exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $8244.52 to WFC exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $8039.65 to PM exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $4954.67 to SNY exiting on 2017-08-23 00:00:00
[EXIT] 2017-08-23 00:00:00: ORCL r=-0.0039, PnL=$-35.79
[EXIT] 2017-08-23 00:00:00: WFC r=-0.0036, PnL=$-30.00
[EXIT] 2017-08-23 00:00:00: PM r=-0.0066, PnL=$-53.26
[EXIT] 2017-08-23 00:00:00: SNY r=-0.0045, PnL=$-22.49

Simulating Trading Days:  92%|█████████▏| 82/89 [59:13<00:16,  2.29s/it]

[SIM] 2017-08-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.717, kelly=0.454) with $4608.06 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.801, kelly=0.606) with $6158.44 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.894, kelly=0.788) with $8009.99 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.904, kelly=0.814) with $8268.52 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.888, kelly=0.773) with $7853.71 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.776, kelly=0.554) with $5627.60 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.715, kelly=0.480) with $4873.52 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.949, kelly=0.899) with $9128.63 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.606, kelly=0.183) with $1861.29 allocation
[SIM] 2017-08-23 00:00:00: 9 trades proposed.
[TRADE] 2017-08-23 00:00:00: allocated $9128.63 to ORCL exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $8268.52 to WFC exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $8009.99 to PM exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $5069.25 to SNY exiting on 2017-08-24 00:00:00
[EXIT] 2017-08-24 00:00:00: ORCL r=0.0024, PnL=$22.32
[EXIT] 2017-08-24 00:00:00: WFC r=0.0025, PnL=$20.66
[EXIT] 2017-08-24 00:00:00: PM r=-0.0081, PnL=$-65.21
[EXIT] 2017-08-24 00:00:00: SNY r=0.0039, PnL=$19.97

Simulating Trading Days:  93%|█████████▎| 83/89 [59:15<00:13,  2.28s/it]

[SIM] 2017-08-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.828, kelly=0.635) with $6450.04 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.802, kelly=0.609) with $6183.58 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.893, kelly=0.786) with $7986.36 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.879, kelly=0.766) with $7778.87 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.877, kelly=0.751) with $7628.18 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.772, kelly=0.546) with $5543.43 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.713, kelly=0.475) with $4828.23 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.931, kelly=0.862) with $8758.17 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.614, kelly=0.200) with $2032.79 allocation
[SIM] 2017-08-24 00:00:00: 9 trades proposed.
[TRADE] 2017-08-24 00:00:00: allocated $8758.17 to ORCL exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $7986.36 to PM exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $7778.87 to WFC exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $5952.30 to SNY exiting on 2017-08-25 00:00:00
[EXIT] 2017-08-25 00:00:00: ORCL r=0.0010, PnL=$8.90
[EXIT] 2017-08-25 00:00:00: PM r=0.0024, PnL=$19.53
[EXIT] 2017-08-25 00:00:00: WFC r=-0.0075, PnL=$-58.16
[EXIT] 2017-08-25 00:00:00: SNY r=0.0056, PnL=$33.18

Simulating Trading Days:  94%|█████████▍| 84/89 [59:18<00:11,  2.29s/it]

[SIM] 2017-08-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.873, kelly=0.730) with $7416.38 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.802, kelly=0.608) with $6178.43 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.893, kelly=0.786) with $7988.61 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.871, kelly=0.750) with $7621.11 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.867, kelly=0.731) with $7421.20 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.766, kelly=0.534) with $5429.43 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.719, kelly=0.487) with $4943.30 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.917, kelly=0.835) with $8477.76 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.626, kelly=0.225) with $2284.11 allocation
[SIM] 2017-08-25 00:00:00: 9 trades proposed.
[TRADE] 2017-08-25 00:00:00: allocated $8477.76 to ORCL exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $7988.61 to PM exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $7416.38 to RDS-B exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $6594.00 to WFC exiting on 2017-08-28 00:00:00
[EXIT] 2017-08-28 00:00:00: ORCL r=0.0000, PnL=$0.00
[EXIT] 2017-08-28 00:00:00: PM r=0.0064, PnL=$51.49
[EXIT] 2017-08-28 00:00:00: RDS-B r=-0.0019, PnL=$-14.32
[EXIT] 2017-08-28 00:00:00: WFC r=-0.0027, PnL=$-17.83

Simulating Trading Days:  96%|█████████▌| 85/89 [59:20<00:09,  2.29s/it]

[SIM] 2017-08-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.894, kelly=0.776) with $7884.03 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.787, kelly=0.579) with $5886.49 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.894, kelly=0.789) with $8015.05 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.860, kelly=0.728) with $7399.35 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.857, kelly=0.710) with $7211.74 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.753, kelly=0.509) with $5171.22 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.727, kelly=0.501) with $5093.02 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.901, kelly=0.804) with $8169.93 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.639, kelly=0.252) with $2558.15 allocation
[SIM] 2017-08-28 00:00:00: 9 trades proposed.
[TRADE] 2017-08-28 00:00:00: allocated $8169.93 to ORCL exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $7884.03 to RDS-B exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $8015.05 to PM exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $6413.54 to WFC exiting on 2017-08-29 00:00:00
[EXIT] 2017-08-29 00:00:00: ORCL r=0.0043, PnL=$34.84
[EXIT] 2017-08-29 00:00:00: RDS-B r=0.0000, PnL=$0.00
[EXIT] 2017-08-29 00:00:00: PM r=0.0087, PnL=$70.06
[EXIT] 2017-08-29 00:00:00: WFC r=-0.0041, PnL=$-26.09

Simulating Trading Days:  97%|█████████▋| 86/89 [59:22<00:06,  2.29s/it]

[SIM] 2017-08-29 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.897, kelly=0.783) with $7957.54 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.762, kelly=0.530) with $5385.26 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.893, kelly=0.788) with $8010.52 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.838, kelly=0.685) with $6962.10 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.851, kelly=0.698) with $7093.94 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.738, kelly=0.479) with $4868.91 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.733, kelly=0.512) with $5207.62 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.886, kelly=0.774) with $7867.16 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.654, kelly=0.282) with $2869.91 allocation
[SIM] 2017-08-29 00:00:00: 9 trades proposed.
[TRADE] 2017-08-29 00:00:00: allocated $7957.54 to RDS-B exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $8010.52 to PM exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $7867.16 to ORCL exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $6670.97 to SNY exiting on 2017-08-30 00:00:00
[EXIT] 2017-08-30 00:00:00: RDS-B r=-0.0060, PnL=$-47.59
[EXIT] 2017-08-30 00:00:00: PM r=-0.0010, PnL=$-8.25
[EXIT] 2017-08-30 00:00:00: ORCL r=0.0071, PnL=$55.68
[EXIT] 2017-08-30 00:00:00: SNY r=-0.0157, PnL=$-104.92

Simulating Trading Days:  98%|█████████▊| 87/89 [59:25<00:04,  2.29s/it]

[SIM] 2017-08-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.885, kelly=0.756) with $7679.68 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.742, kelly=0.490) with $4975.56 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.892, kelly=0.785) with $7970.19 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.848, kelly=0.705) with $7164.68 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.846, kelly=0.689) with $6998.20 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.715, kelly=0.434) with $4411.01 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.735, kelly=0.516) with $5242.23 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.868, kelly=0.737) with $7485.11 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.659, kelly=0.294) with $2983.72 allocation
[SIM] 2017-08-30 00:00:00: 9 trades proposed.
[TRADE] 2017-08-30 00:00:00: allocated $7970.19 to PM exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $7679.68 to RDS-B exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $7485.11 to ORCL exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $7164.68 to WFC exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $175.01 to SNY exiting on 2017-08-31 00:00:00
[EXIT] 2017-08-31 00:00:00: PM r=0.0043, PnL=$34.23
[EXIT] 2017-08-31 00:00:00: RDS-B r=0.0021, PnL=$16.31
[EXIT] 2017-08-31 00:00:00: ORCL r=0.0106, PnL=$79.66
[EXIT] 2017-08-31 00:00:00: WFC r=-0.0056, PnL=$-40.45
[EXIT] 2017-08-31 00:00:00: SNY r=0.0135, PnL=$2.36

Simulating Trading Days:  99%|█████████▉| 88/89 [59:27<00:02,  2.28s/it]

[SIM] 2017-08-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting RDS-B (p_up=0.855, kelly=0.694) with $7051.21 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.730, kelly=0.466) with $4738.77 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.889, kelly=0.779) with $7917.76 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.858, kelly=0.725) with $7373.06 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.852, kelly=0.701) with $7128.29 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.682, kelly=0.369) with $3749.04 allocation
[PORT] Sector Services: selecting WMT (p_up=0.771, kelly=0.535) with $5441.15 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.859, kelly=0.719) with $7306.26 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.662, kelly=0.301) with $3057.56 allocation
[SIM] 2017-08-31 00:00:00: 9 trades proposed.
[TRADE] 2017-08-31 00:00:00: allocated $7917.76 to PM exiting on 2017-09-01 00:00:00
[TRADE] 2017-08-31 00:00:00: allocated $7306.26 to ORCL exiting on 2017-09-01 00:00:00
[TRADE] 2017-08-31 00:00:00: allocated $7373.06 to WFC exiting on 2017-09-01 00:00:00
[TRADE] 2017-08-31 00:00:00: allocated $7051.21 to RDS-B exiting on 2017-09-01 00:00:00
[TRADE] 2017-08-31 00:00:00: allocated $854.02 to SNY exiting on 2017-09-01 00:00:00
[EXIT] 2017-09-01 00:00:00: PM r=0.0077, PnL=$60.94
[EXIT] 2017-09-01 00:00:00: ORCL r=0.0058, PnL=$42.10
[EXIT] 2017-09-01 00:00:00: WFC r=-0.0020, PnL=$-14.44
[EXIT] 2017-09-01 00:00:00: RDS-B r=0.0014, PnL=$9.96
[EXIT] 2017-09-01 00:00:00: SNY r=0.0096, PnL=$8.22

Simulating Trading Days: 100%|██████████| 89/89 [59:29<00:00, 40.11s/it]

[SIM] 2017-09-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SNP (p_up=0.847, kelly=0.695) with $7070.04 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.724, kelly=0.454) with $4625.61 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.886, kelly=0.772) with $7861.94 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.853, kelly=0.714) with $7270.76 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.861, kelly=0.718) with $7306.61 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.707, kelly=0.405) with $4123.02 allocation
[PORT] Sector Services: selecting WMT (p_up=0.773, kelly=0.539) with $5489.48 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.838, kelly=0.677) with $6892.01 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.661, kelly=0.298) with $3033.16 allocation
[SIM] 2017-09-01 00:00:00: 9 trades proposed.

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-28,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
1,2017-05-01,99976.187557,69983.331290,99976.187557,99976.187557,-23.812443,-0.000238,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
2,2017-05-02,100003.470077,70002.429054,100003.470077,100003.470077,27.282520,0.000273,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
3,2017-05-03,100109.001456,70076.301019,100109.001456,100109.001456,105.531379,0.001055,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
4,2017-05-04,100102.035331,70071.424731,100102.035331,100102.035331,-6.966126,-0.000070,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
...,...,...,...,...,...,...,...,...
84,2017-08-28,101608.489225,71125.942458,101608.489225,101608.489225,19.340057,0.000190,"[{'ticker': 'ORCL', 'sector': 'Technology', 'p..."
85,2017-08-29,101687.309803,71181.116862,101687.309803,101687.309803,78.820577,0.000776,"[{'ticker': 'RDS-B', 'sector': 'Basic Matieria..."
86,2017-08-30,101582.237891,71107.566523,101582.237891,101582.237891,-105.071912,-0.001033,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
87,2017-08-31,101674.340611,71172.038427,101674.340611,101674.340611,92.102720,0.000907,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
88,2017-09-01,101781.123366,101781.123366,101781.123366,101781.123366,106.782756,0.001050,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-28,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
1,2017-05-01,99976.187557,69983.331290,99976.187557,99976.187557,-23.812443,-0.000238,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
2,2017-05-02,100003.470077,70002.429054,100003.470077,100003.470077,27.282520,0.000273,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
3,2017-05-03,100109.001456,70076.301019,100109.001456,100109.001456,105.531379,0.001055,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
4,2017-05-04,100102.035331,70071.424731,100102.035331,100102.035331,-6.966126,-0.000070,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
...,...,...,...,...,...,...,...,...
84,2017-08-28,101608.489225,71125.942458,101608.489225,101608.489225,19.340057,0.000190,"[{'ticker': 'ORCL', 'sector': 'Technology', 'p..."
85,2017-08-29,101687.309803,71181.116862,101687.309803,101687.309803,78.820577,0.000776,"[{'ticker': 'RDS-B', 'sector': 'Basic Matieria..."
86,2017-08-30,101582.237891,71107.566523,101582.237891,101582.237891,-105.071912,-0.001033,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
87,2017-08-31,101674.340611,71172.038427,101674.340611,101674.340611,92.102720,0.000907,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
88,2017-09-01,101781.123366,101781.123366,101781.123366,101781.123366,106.782756,0.001050,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $101,781.12
Total Return on Investment (ROI): 1.78%
Annualized Sharpe Ratio: 1.81
--------------------------

In [36]:
master_df_with_target = add_horizon_targets(master_df.copy(), H=1, price_col="close")
import numpy as np
import pandas as pd

ret_col = f"ret_{1}d"

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
        # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 425
Total capital allocated: $2,670,391.32
Average position size:  $6,283.27
Completed trades with returns: 425
Winning trades: 219 (51.5%)
Losing trades:  199 (46.8%)
Total PnL: $1,781.12
Average PnL per trade: $4.19
Average return: 0.06%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Services,53,331039.254224,6246.023665,996.106538,18.794463,0.003082
Technology,75,512241.556631,6829.887422,792.358911,10.564785,0.001364
Consumer Goods,88,665692.863032,7564.691625,420.409718,4.777383,0.000727
Basic Matierials,35,232843.182475,6652.662356,30.563732,0.873249,0.000240
Healthcare,54,308057.595651,5704.770290,23.096501,0.427713,0.000948
Conglomerates,4,16550.664540,4137.666135,3.411899,0.852975,-0.000354
Industrial Goods,46,220862.352182,4801.355482,-20.663650,-0.449210,-0.000544
Financial,52,318988.163253,6134.387755,-58.630543,-1.127510,-0.000499
Utilities,18,64115.685903,3561.982550,-405.529739,-22.529430,-0.004752

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
314,2017-07-26,2017-07-27,VZ,Technology,8414.648606,0.916278,0.019754,0.076802,646.259956
21,2017-05-04,2017-05-05,RDS-B,Basic Matierials,6767.705002,0.847969,0.015787,0.034877,236.039546
261,2017-07-11,2017-07-12,SNY,Healthcare,7590.891791,0.879294,0.019004,0.022803,173.097745
32,2017-05-08,2017-05-09,BABA,Services,6423.402967,0.813100,0.014932,0.026870,172.595231
169,2017-06-15,2017-06-16,RDS-B,Basic Matierials,7757.649269,0.889923,0.018764,0.021621,167.725194
369,2017-08-14,2017-08-15,PM,Consumer Goods,8375.041586,0.912015,0.023160,0.017950,150.336081
56,2017-05-15,2017-05-16,BABA,Services,6822.394418,0.832970,0.016229,0.021582,147.237553
364,2017-08-11,2017-08-14,WFC,Financial,8479.481197,0.916135,0.020320,0.017328,146.929952
147,2017-06-08,2017-06-09,WFC,Financial,6144.035152,0.798560,0.013280,0.023592,144.950364
292,2017-07-19,2017-07-20,SNY,Healthcare,5326.159366,0.766654,0.012619,0.026704,142.228136

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
62,2017-05-16,2017-05-17,BABA,Services,6610.517700,0.820991,0.015438,-0.026609,-175.896488
355,2017-08-09,2017-08-10,ORCL,Technology,8889.117041,0.936799,0.022575,-0.019568,-173.941681
252,2017-07-07,2017-07-10,WMT,Services,6212.416083,0.810135,0.016133,-0.027877,-173.185546
180,2017-06-19,2017-06-20,RDS-B,Basic Matierials,6020.496947,0.807932,0.013334,-0.025682,-154.619397
376,2017-08-16,2017-08-17,WFC,Financial,8748.625983,0.927166,0.021111,-0.016891,-147.775238
221,2017-06-28,2017-06-29,CSCO,Technology,6978.444529,0.837245,0.017844,-0.020885,-145.747241
110,2017-05-30,2017-05-31,NGG,Utilities,5304.665826,0.764358,0.011268,-0.025743,-136.558595
375,2017-08-16,2017-08-17,ORCL,Technology,9606.400457,0.971074,0.025479,-0.014213,-136.537867
377,2017-08-16,2017-08-17,PM,Consumer Goods,8301.852977,0.906946,0.022828,-0.015289,-126.929074
220,2017-06-28,2017-06-29,PM,Consumer Goods,7872.099632,0.887550,0.021580,-0.015555,-122.453280

TOP 10 SECTORS BY TOTAL PnL

                   total_pnl
sector
Services          996.106538
Technology        792.358911
Consumer Goods    420.409718
Basic Matierials   30.563732
Healthcare         23.096501
Conglomerates       3.411899
Industrial Goods  -20.663650
Financial         -58.630543
Utilities        -405.529739

BOTTOM 10 SECTORS BY TOTAL PnL

                   total_pnl
sector
Services          996.106538
Technology        792.358911
Consumer Goods    420.409718
Basic Matierials   30.563732
Healthcare         23.096501
Conglomerates       3.411899
Industrial Goods  -20.663650
Financial         -58.630543
Utilities        -405.529739

Top 10 Most Invested Tickers:

ticker
PM       88
SNY      49
RDS-B    35
VZ       32
WFC      31
ABB      26
WMT      25
CSCO     22
ORCL     21
UTX      20
Name: count, dtype: int64

Tickers Never Invested In (68):
{'CMCSA', 'BBL', 'TM', 'BA', 'GMRE', 'JNJ', 'HD', 'BP', 'IEP', 'SO', 'LMT', 'BUD', 'HON', 'AAPL', 'PCLN', 'MDT', 'BSAC', 'GE', 'CAT', 'PG', 'PCG', 'AEP', 'CHTR', 'SPLP', 'D', 'UN', 'MMM', 'T', 'MRK', 'MSFT', 'BCH', 'INTC', 'AMZN', 'SRE', 'BAC', 'TSM', 'C', 'PICO', 'FB', 'MCD', 'DUK', 'SLB', 'UL', 'TOT', 'JPM', 'DIS', 'REX', 'SNP', 'GD', 'GOOG', 'CELG', 'CODI', 'MO', 'CVX', 'AGFS', 'ABBV', 'BHP', 'CHL', 'KO', 'PFE', 'XOM', 'V', 'PPL', 'PEP', 'DHR', 'EXC', 'UNH', 'PTR'}

In [37]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]