# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as Fnn
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [7]:
pandas_ta_classic_path = None
for sp in site.getsitepackages():
    pandas_ta_classic_path = os.path.join(sp, 'pandas_ta_classic')
    if os.path.exists(pandas_ta_classic_path):
        break

if pandas_ta_classic_path:
    squeeze_pro_path = os.path.join(pandas_ta_classic_path, 'momentum', 'squeeze_pro.py')
    if os.path.exists(squeeze_pro_path):
        try:
            with open(squeeze_pro_path, 'r') as f:
                lines = f.readlines()

            new_lines = []
            fixed = False
            for line in lines:
                if "from numpy import NaN as npNaN" in line:
                    new_lines.append(line.replace("from numpy import NaN as npNaN", "# from numpy import NaN as npNaN\nimport numpy as np\n"))
                    fixed = True
                    print("Modified import statement in squeeze_pro.py")
                else:
                    new_lines.append(line)

            if fixed:
                with open(squeeze_pro_path, 'w') as f:
                    f.writelines(new_lines)
                print("Successfully patched pandas_ta_classic/momentum/squeeze_pro.py")
            else:
                print("Could not find the problematic import line in squeeze_pro.py")

        except Exception as e:
            print(f"Error modifying squeeze_pro.py: {e}")
    else:
        print(f"Could not find squeeze_pro.py at {squeeze_pro_path}")
else:
    print("Could not find the pandas_ta_classic library installation path.")

import pandas_ta_classic as ta

Could not find the problematic import line in squeeze_pro.py

### Configurations

In [8]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 783  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [9]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [10]:
BUCKET_BINS   = [-np.inf, -0.02, -0.005, 0.0, 0.005, 0.02, np.inf]
K = len(BUCKET_BINS) - 1

In [11]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

In [12]:
CALIBRATION_LOGGED = set()

In [13]:
def bucketize_with_edges(x, edges):
    # x: 1D np array of returns; edges: len K+1
    return np.clip(np.digitize(x, edges[1:-1], right=True), 0, len(edges)-2).astype(np.int64)

def make_cumulative_targets(y_idx, K):
    # y_idx in [0..K-1] -> T: [N,K-1] with T[:,k]=1(y>k)
    y = y_idx.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def ordinal_to_class_probs(P_rep):
    # P_rep: [N,K-1] with P(y>k) (after sigmoid), repaired monotone
    N, K1 = P_rep.shape; K = K1+1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:,0] = 1.0 - P_rep[:,0]
    for c in range(1, K-1):
        Pc[:,c] = np.clip(P_rep[:,c-1] - P_rep[:,c], 0., 1.)
    Pc[:,K-1] = P_rep[:,K1-1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)

def monotone_repair_numpy(P):
    P = np.asarray(P, dtype=np.float32).copy()
    for k in range(P.shape[1]-2, -1, -1):
        P[:,k] = np.maximum(P[:,k], P[:,k+1])
    return P

In [14]:
# multiclass calibration tuned for macro-F1 balance
def _class_dist(y_hat, K):
    hist = np.bincount(y_hat, minlength=K).astype(np.float32)
    return hist / max(1, y_hat.size)

def _balance_penalty(p_hat, p_target, norm="l1"):
    if norm == "l1":
        return float(np.abs(p_hat - p_target).sum())
    elif norm == "l2":
        return float(np.sqrt(((p_hat - p_target) ** 2).sum()))
    else:
        return float(np.abs(p_hat - p_target).sum())

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    # decode ordinal cumulative probs to class indices using per-head taus.
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def tune_temperature_and_taus(
    Z_val,
    y_val_idx,
    K,
    T_grid=np.linspace(0.6, 2.5, 15),
    tau_grid=np.linspace(0.2, 0.8, 31),
    lambda_balance=0.05,
    target_priors="uniform",
    coord_rounds=3,
):
    """Learn a temperature T and per-head taus by maximizing macro-F1 with a balance penalty."""
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.detach().cpu().numpy()

    N, K_1 = Z_val.shape
    assert K_1 == K - 1

    if isinstance(target_priors, str) and target_priors == "uniform":
        p_target = np.ones(K, dtype=np.float32) / K
    else:
        p_target = np.asarray(target_priors, dtype=np.float32)
        p_target = p_target / p_target.sum()

    best = {"score": -1e9, "T": 1.0, "taus": np.full(K_1, 0.5, np.float32)}

    for T in T_grid:
        P_cum = 1.0 / (1.0 + np.exp(-(Z_val / T)))
        P_rep = monotone_repair_numpy(P_cum)

        taus = np.full(K_1, 0.5, dtype=np.float32)
        for _ in range(coord_rounds):
            for k in range(K_1):
                best_k = (taus[k], -1e9)
                for tau in tau_grid:
                    taus_try = taus.copy()
                    taus_try[k] = tau
                    y_hat = decode_ordinal_with_taus(P_rep, taus_try)
                    f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
                    p_hat = _class_dist(y_hat, K)
                    score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")
                    if score > best_k[1]:
                        best_k = (tau, score)
                taus[k] = best_k[0]

        y_hat = decode_ordinal_with_taus(P_rep, taus)
        f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
        p_hat = _class_dist(y_hat, K)
        score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")

        if score > best["score"]:
            best.update({"score": score, "T": float(T), "taus": taus.astype(np.float32)})

    return best["T"], best["taus"]

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [15]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [16]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # end current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [17]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [18]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [19]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [20]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [21]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [22]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [23]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [24]:
class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):  # T: float32 matrix [N, K-1] with 0/1
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)
    def __len__(self): return len(self.X)
    def __getitem__(self, i): return self.X[i], self.T[i]
    
class LSTMOrdinal(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, head='CORAL', K=6):
        super().__init__()
        self.K = K
        self.lstm1 = nn.LSTM(n_features, hidden1, num_layers=1, batch_first=True, dropout=0.1)
        self.inter_drop = nn.Dropout(inter_dropout)
        self.lstm2 = nn.LSTM(hidden1, hidden2, num_layers=1, batch_first=True, dropout=0.1)

        self.norm = nn.BatchNorm1d(hidden2)
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(dropout)

        if head.upper() == 'CORAL':
            self.w = nn.Linear(fc, 1, bias=False)
            self._beta = nn.Parameter(torch.zeros(K-1))
            self.softplus = nn.Softplus()
            self.head_type = 'CORAL'
        else:
            self.fc_out = nn.Linear(fc, K-1)
            self.head_type = 'CORN'

    def forward(self, x):
        out1,_ = self.lstm1(x)
        out1 = self.inter_drop(out1)
        out2,_ = self.lstm2(out1)
        last = out2[:, -1, :]
        last = self.norm(last)
        z = self.relu(self.fc1(last))
        z = self.drop(z)
        if self.head_type == 'CORAL':
            base = self.w(z)                              # [B,1]
            deltas = self.softplus(self._beta)            # ≥0
            b = torch.cumsum(deltas, dim=0)               # [K-1]
            logits = base - b                              # broadcast -> [B,K-1]
        else:
            logits = self.fc_out(z)                        # [B,K-1]
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [25]:
def train_company_models(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 sequence_length: int = None,
                                 H: int = 1,
                                 K: int = K,        # global K
                                 head_type: str = 'CORAL'):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"[TRAIN] {ticker}: preparing data (H={H}) with {len(company_data_df)} rows")

    ret_col = f"ret_{H}d"
    if ret_col not in company_data_df.columns:
        company_data_df = add_horizon_targets(company_data_df, H=H, price_col='close')

    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)
    if len(company_data_df) < sequence_length + H + 10:
        print(f"[TRAIN] {ticker}: insufficient history for sequence length {sequence_length}")
        return False, sequence_length

    contigs = identify_contiguous_periods(company_data_df)
    if not contigs:
        print(f"[TRAIN] {ticker}: no contiguous periods found")
        return False, sequence_length

    rets = company_data_df[ret_col].values
    y_idx_all = bucketize_with_edges(rets, BUCKET_BINS)
    X_all = company_data_df[feature_cols].values

    X_seq, y_seq = create_contiguous_sequences(
        X_all, y_idx_all, contigs, sequence_length, H
    )
    if len(X_seq) < 40:
        print(f"[TRAIN] {ticker}: too few sequences ({len(X_seq)})")
        return False, sequence_length
    print(f"[TRAIN] {ticker}: built {len(X_seq)} sequences (seq_len={sequence_length})")

    X_tr, X_val, y_tr, y_val = train_test_split(X_seq, y_seq, test_size=0.2, shuffle=False)

    scaler = MinMaxScaler()
    F = X_tr.shape[-1]
    X_tr = scaler.fit_transform(X_tr.reshape(-1, F)).reshape(X_tr.shape)
    X_val = scaler.transform(X_val.reshape(-1, F)).reshape(X_val.shape)
    print(f"[TRAIN] {ticker}: scaler fitted on {X_tr.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_tr has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    # sector_feature_indices = [feature_cols.index('sector_ret_1d'),
    #                       feature_cols.index('sector_ret_5d'),
    #                       feature_cols.index('sector_vol_20d')]

    # print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    # print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")


    T_tr  = make_cumulative_targets(y_tr, K)
    T_val = make_cumulative_targets(y_val, K)

    train_ds = OrdinalSequenceDataset(X_tr, T_tr)
    val_ds   = OrdinalSequenceDataset(X_val, T_val)
    train_bs = min(32, len(train_ds))
    if train_bs < 2:
        print(f"[TRAIN] {ticker}: too few samples for BatchNorm (train size={len(train_ds)})")
        return False, sequence_length
    if len(train_ds) % train_bs == 1 and train_bs > 2:
        train_bs -= 1  # avoid batch size 1 for BatchNorm
    val_bs = min(32, len(val_ds))
    train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=True, drop_last=False)
    val_loader   = DataLoader(val_ds,   batch_size=val_bs, shuffle=False, drop_last=False)

    n_features = X_tr.shape[-1]
    model = LSTMOrdinal(n_features=n_features, head=head_type, K=K).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    pos_rate = T_tr.mean(axis=0)
    pos_w = ((1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)).astype(np.float32)
    pos_w = torch.tensor(pos_w, dtype=torch.float32, device=device) 
    print(f"[TRAIN] {ticker}: model n_features = {n_features}")

    
    def loss_fn(logits, T):
        losses = []
        for k in range(logits.shape[1]):
            losses.append(Fnn.binary_cross_entropy_with_logits(logits[:,k], T[:,k], pos_weight=pos_w[k]))
        return torch.stack(losses).mean()

    early = EarlyStopper(patience=15, mode='min')
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)

    for epoch in range(100):
        model.train()
        tot = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            l = loss_fn(logits, yb)
            l.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tot += l.item() * xb.size(0)

        model.eval()
        with torch.no_grad():
            vtot = 0.0
            for xb, yb in val_loader:
                xb, yb = xb.to(device), yb.to(device)
                logits = model(xb)
                l = loss_fn(logits, yb)
                vtot += l.item() * xb.size(0)
            val_loss = vtot / len(val_loader.dataset)

        scheduler.step(val_loss)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:
            break

    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    ret_seq_full = company_data_df[ret_col].values[sequence_length:]
    ret_train = ret_seq_full[:len(y_tr)]
    mu_c = np.array([ret_train[y_tr==c].mean() if np.any(y_tr==c) else 0.0 for c in range(K)], dtype=np.float32)


    taus = None
    temperature = 1.0
    try:
        model.eval()
        batch = 256
        logits_list = []
        for start in range(0, len(X_val), batch):
            xb = torch.from_numpy(X_val[start:start+batch].astype(np.float32)).to(device)
            with torch.no_grad():
                logits = model(xb)
            logits_list.append(logits.cpu().numpy())
        if logits_list:
            val_logits = np.vstack(logits_list)
            T_star, taus = tune_temperature_and_taus(
                Z_val=val_logits,
                y_val_idx=y_val,
                K=K,
                T_grid=np.linspace(0.6, 2.5, 15),
                tau_grid=np.linspace(0.2, 0.8, 31),
                lambda_balance=0.05,
                target_priors="uniform",
                coord_rounds=3,
            )
            temperature = float(T_star)
            print(f"[CAL] {ticker}: taus={np.round(taus, 3)} | temperature={temperature:.3f}")
        else:
            print(f"[CAL] {ticker}: no validation logits -> skipping calibration")
    except Exception as exc:
        print(f"[CAL] {ticker}: calibration failed ({exc})")
        taus = None
        temperature = 1.0

    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt"))
    joblib.dump(scaler, os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
    joblib.dump(BUCKET_BINS, os.path.join(model_save_path, f"{ticker}_edges_H{H}.pkl"))
    joblib.dump(mu_c, os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))
    if taus is not None and len(taus) == (K - 1) and np.all(np.isfinite(taus)):
        joblib.dump(taus, os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored taus")
    if temperature is not None and np.isfinite(temperature):
        joblib.dump(float(temperature), os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored temperature scale {temperature:.3f}")
    print(f"[SAVE] {ticker}: artifacts persisted (H={H})")

    del model, scaler, train_loader, val_loader, train_ds, val_ds
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [26]:

def predict_next_horizon(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         H: int,
                         K: int = 6,
                         head: str = "CORAL") -> dict | None:
    """
    Ordinal inference with optional calibration artifacts. Returns class probs plus
    summary stats so the simulator can log decisions.
    """
    try:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt")
        if not os.path.isfile(state_dict_path):
            return None

        scaler   = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        seq_len  = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
        mu_c     = joblib.load(os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))

        taus_path = os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl")
        T_path    = os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl")
        taus = joblib.load(taus_path) if os.path.isfile(taus_path) else None
        temperature = float(joblib.load(T_path)) if os.path.isfile(T_path) else 1.0

        n_features = len(feature_cols)
        model = LSTMOrdinal(n_features=n_features, head=head.upper(), K=K).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    if 'CALIBRATION_LOGGED' not in globals():
        globals()['CALIBRATION_LOGGED'] = set()
    if ticker not in CALIBRATION_LOGGED:
        if taus is not None:
            print(f"[CAL] {ticker}: loaded taus {np.round(taus,3)}")
        else:
            print(f"[CAL] {ticker}: no taus artifact found")
        print(f"[CAL] {ticker}: temperature scaling {temperature:.3f}")
        CALIBRATION_LOGGED.add(ticker)

    contiguous = identify_contiguous_periods(company_data_df)
    if not contiguous:
        return None
    start, end = contiguous[-1]
    period = company_data_df.iloc[start:end+1]
    if len(period) < seq_len:
        return None

    try:
        last_seq = period.tail(seq_len)
        X_scaled = scaler.transform(last_seq[feature_cols])
    except Exception:
        return None

    x = torch.from_numpy(np.asarray([X_scaled], dtype=np.float32)).to(device)

    with torch.no_grad():
        z = model(x)
        if temperature and temperature > 0 and temperature != 1.0:
            z = z / temperature
        P_cum = torch.sigmoid(z).cpu().numpy()
        P_cum = monotone_repair_numpy(P_cum)
        Pc    = ordinal_to_class_probs(P_cum)

    mu_c = np.asarray(mu_c, dtype=np.float32).reshape(-1)
    if mu_c.shape[0] != K:
        return None
    expected_rise = float((Pc[0] * mu_c).sum())

    top_bucket_idx = K - 1
    prob_top_bucket = float(Pc[0, top_bucket_idx])
    bucket_idx = int(np.argmax(Pc[0]))

    class_idx = None
    if taus is not None:
        taus = np.asarray(taus, dtype=np.float32).reshape(-1)
        if taus.shape[0] == (K - 1):
            class_idx = int(decode_ordinal_with_taus(P_cum, taus=taus)[0])

    positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
    prob_up = float(Pc[0, positive_buckets].sum()) if positive_buckets else prob_top_bucket

    return {
        'ticker': ticker,
        'expected_rise': expected_rise,
        'predicted_prob': prob_up,  # probability of positive move
        'prob_up': prob_up,
        'prob_bucket_top': prob_top_bucket,
        'bucket_idx': bucket_idx,
        'class_idx': class_idx,
        'class_probs': Pc[0].tolist(),
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [27]:
def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                              total_capital: float, sector_threshold: float,
                              kelly_fraction: float, top_k: int = 3, softmax_alpha: float = 1) -> pd.DataFrame:
    """Pick one name per sector via softmax over top-K expected_rise, then size with Kelly."""
    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")
    df = daily_predictions_df.copy()

    if 'prob_up' not in df.columns and 'class_probs' in df.columns:
        positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
        def _sum_up(probs):
            if isinstance(probs, (list, tuple)) and len(probs) == K and positive_buckets:
                return float(sum(probs[i] for i in positive_buckets))
            return np.nan
        df['prob_up'] = df['class_probs'].apply(_sum_up)

    if 'prob_up' not in df.columns and 'predicted_prob' in df.columns:
        df['prob_up'] = df['predicted_prob']

    if 'expected_rise' not in df.columns:
        print("[PORT] Missing expected_rise; cannot size portfolio.")
        return pd.DataFrame()

    # base filters
    df = df[(df['prob_up'] >= sector_threshold) & (df['expected_rise'] > 0)]
    print(f"[PORT] {len(df)} tickers cleared prob_up ≥ {sector_threshold:.3f} and positive expected return.")
    if df.empty:
        return pd.DataFrame()

    candidates = []
    for _, row in df.iterrows():
        ticker = row['ticker']
        p_up = float(row['prob_up'])
        payout = payout_map.get(ticker, {})
        b = payout.get('b') if isinstance(payout, dict) else float(payout)
        if not np.isfinite(b) or b <= 0:
            continue
        kelly_pct = p_up - (1.0 - p_up) / b
        if kelly_pct <= 0:
            continue
        investment_fraction = min(MAX_POSITION_SIZE, kelly_pct * kelly_fraction)
        investment_fraction = max(0.0, investment_fraction)
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            continue
        enriched = row.to_dict()
        enriched.update({
            'kelly_pct': kelly_pct,
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount,
        })
        candidates.append(enriched)

    if not candidates:
        print("[PORT] All candidates rejected after quality filters.")
        return pd.DataFrame()

    cand_df = pd.DataFrame(candidates)

    rows = []
    alpha = max(softmax_alpha, 1e-6)
    for sector, group in cand_df.groupby('sector'):
        if group.empty:
            continue
        top_group = group.sort_values('expected_rise', ascending=False).head(max(1, top_k))
        logits = (top_group['expected_rise'].to_numpy() * 100.0 * alpha)
        logits = logits - logits.max()  # stabilize
        weights = np.exp(logits)
        probs = weights / weights.sum()
        choice_idx = np.random.choice(len(top_group), p=probs)
        choice = top_group.iloc[choice_idx]

        print(f"[PORT] Sector {sector}: sampled {choice['ticker']} from top-{len(top_group)} (expected={choice['expected_rise']:.4f}, p_up={choice['prob_up']:.3f})")

        rows.append({
            'ticker': choice['ticker'],
            'sector': sector,
            'prob_up': float(choice['prob_up']),
            'predicted_prob': float(choice['prob_up']),
            'expected_rise': choice['expected_rise'],
            'bucket_idx': choice.get('bucket_idx', np.nan),
            'investment_fraction': choice['investment_fraction'],
            'investment_amount': choice['investment_amount'],
        })

    if not rows:
        print("[PORT] All sector winners rejected after sizing.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [28]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    """Check the minimal set of artifacts needed for ordinal inference."""
    required = [
        f"{ticker}_lstmORD_H{H}.pt",      # model weights (ordinal head)
        f"{ticker}_scaler_H{H}.pkl",      # feature scaler
        f"{ticker}_seq_length_H{H}.pkl",  # sequence length
        f"{ticker}_mu_c_H{H}.pkl",        # per-class train means μ_c for expected return
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in required)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [29]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # precompute realized returns for settlement only (not used for training)
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker', 'date'])[ret_col].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    # overlapping book
    open_positions = []  # each: {'ticker','invest','entry_date','exit_date'}
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                if pd.notna(rH):
                    pnl = pos['invest'] * rH
                    total_pnl_today += pnl
                    print(f"[EXIT] {current_date}: {pos['ticker']} r={rH:.4f}, PnL=${pnl:.2f}")
                    capital += pos['invest'] + pnl  # release capital
            else:
                still_open.append(pos)
        open_positions = still_open

        # equity at START (after settlements, before new entries)
        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # build prediction universe using info strictly before current_date
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        cutoff = current_date - pd.Timedelta(days=H)
        historical_data = historical_data[historical_data['date'] < cutoff]
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if i == 0:  # no yesterday slice for display
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                print("Retraining model for ticker:", ticker)
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)
        print(f"[SIM] {current_date}: built {len(daily_predictions_df)} predictions")
        if (not daily_predictions_df.empty and
            'predicted_prob' not in daily_predictions_df.columns and
            'calibrated_prediction' not in daily_predictions_df.columns):
            print("[WARN] predicted_prob missing from daily_predictions_df columns:",
                  sorted(daily_predictions_df.columns))


        # size raw trades via Kelly
        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df,
            payout_map_day,
            capital,
            sector_threshold=SECTOR_CONFIDENCE_THRESHOLD,
            kelly_fraction=KELLY_FRACTION,
        )
        if investment_decision_df.empty:
            print(f"[SIM] {current_date}: no trades proposed today.")
        else:
            print(f"[SIM] {current_date}: {len(investment_decision_df)} trades proposed.")

        # entry logic (allow_overlap controls laddering)
        exit_idx = i + H
        if exit_idx < len(unique_dates):
            exit_date = unique_dates[exit_idx]
        else:
            exit_date = None  # can't open new trades that we cannot exit within data

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            # ensure the column exists even if future changes rename it
            if 'predicted_prob' not in investment_decision_df.columns:
                if 'calibrated_prediction' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'calibrated_prediction': 'predicted_prob'}
                    )
                elif 'score' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'score': 'predicted_prob'}
                    )
                else:
                    # nothing to sort by
                    investment_decision_df = pd.DataFrame()

            if not investment_decision_df.empty:
                investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)


            # current exposures (post-settlement)
            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                # per-ticker ladder depth
                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue  # no overlapping allowed

                # base size from Kelly (already scaled by KELLY_FRACTION)
                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))  # vs equity

                # clamp by remaining budgets
                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                # lock capital and record position
                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})
                print(f"[TRADE] {current_date}: allocated ${amt:.2f} to {tkr} exiting on {exit_date}")

        # equity at END (after entries)
        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        # log the day
        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,  # cash only
            'capital_end': capital,                               # cash only
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,                # realized PnL today
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [30]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [31]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_and_bimeta_features.parquet')

In [32]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)
# Exclude ticker with missing meta-features across all rows
master_df = master_df[master_df['ticker'] != 'GMRE']

columns_to_check = ['EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    'lstm_prob_up_1d', 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [33]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    # 'lstm_prob_up_1d', 
    # 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 
    'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength', 'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20']
Total number of features: 33

In [34]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

# Execute Pipeline

In [35]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=5,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Starting simulation with 783 initial training days... (H=5)
Starting predictions from day 783 (after 783 training days)

Simulating Trading Days:   0%|          | 0/100 [00:00<?, ?it/s]

Retraining model for ticker: AAPL
[TRAIN] AAPL: preparing data (H=5) with 778 rows
[TRAIN] AAPL: built 762 sequences (seq_len=12)
[TRAIN] AAPL: scaler fitted on 609 training sequences
[TRAIN] AAPL: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AAPL: model n_features = 33
[CAL] AAPL: taus=[0.5  0.44 0.5  0.42 0.4 ] | temperature=1.686
[SAVE] AAPL: stored taus
[SAVE] AAPL: stored temperature scale 1.686
[SAVE] AAPL: artifacts persisted (H=5)
[CAL] AAPL: loaded taus [0.5  0.44 0.5  0.42 0.4 ]
[CAL] AAPL: temperature scaling 1.686
Retraining model for ticker: ABB
[TRAIN] ABB: preparing data (H=5) with 778 rows
[TRAIN] ABB: built 762 sequences (seq_len=12)
[TRAIN] ABB: scaler fitted on 609 training sequences
[TRAIN] ABB: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] ABB: model n_features = 33
[CAL] ABB: taus=[0.78 0.78 0.7  0.46 0.44] | temperature=1.007
[SAVE] ABB: stored taus
[SAVE] ABB: stored temperature scale 1.007
[SAVE] ABB: artifacts persisted (H=5)
[CAL] ABB: loaded taus [0.78 0.78 0.7  0.46 0.44]
[CAL] ABB: temperature scaling 1.007
Retraining model for ticker: ABBV
[TRAIN] ABBV: preparing data (H=5) with 716 rows
[TRAIN] ABBV: built 700 sequences (seq_len=12)
[TRAIN] ABBV: scaler fitted on 560 training sequences
[TRAIN] ABBV: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] ABBV: model n_features = 33
[CAL] ABBV: taus=[0.28 0.36 0.38 0.24 0.26] | temperature=0.600
[SAVE] ABBV: stored taus
[SAVE] ABBV: stored temperature scale 0.600
[SAVE] ABBV: artifacts persisted (H=5)
[CAL] ABBV: loaded taus [0.28 0.36 0.38 0.24 0.26]
[CAL] ABBV: temperature scaling 0.600
Retraining model for ticker: AEP
[TRAIN] AEP: preparing data (H=5) with 778 rows
[TRAIN] AEP: built 762 sequences (seq_len=12)
[TRAIN] AEP: scaler fitted on 609 training sequences
[TRAIN] AEP: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AEP: model n_features = 33
[CAL] AEP: taus=[0.52 0.46 0.34 0.28 0.24] | temperature=1.414
[SAVE] AEP: stored taus
[SAVE] AEP: stored temperature scale 1.414
[SAVE] AEP: artifacts persisted (H=5)
[CAL] AEP: loaded taus [0.52 0.46 0.34 0.28 0.24]
[CAL] AEP: temperature scaling 1.414
Retraining model for ticker: AGFS
[TRAIN] AGFS: preparing data (H=5) with 240 rows
[TRAIN] AGFS: built 224 sequences (seq_len=12)
[TRAIN] AGFS: scaler fitted on 179 training sequences
[TRAIN] AGFS: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AGFS: model n_features = 33
[CAL] AGFS: taus=[0.2  0.8  0.72 0.78 0.7 ] | temperature=1.143
[SAVE] AGFS: stored taus
[SAVE] AGFS: stored temperature scale 1.143
[SAVE] AGFS: artifacts persisted (H=5)
[CAL] AGFS: loaded taus [0.2  0.8  0.72 0.78 0.7 ]
[CAL] AGFS: temperature scaling 1.143
Retraining model for ticker: AMGN
[TRAIN] AMGN: preparing data (H=5) with 778 rows
[TRAIN] AMGN: built 762 sequences (seq_len=12)
[TRAIN] AMGN: scaler fitted on 609 training sequences
[TRAIN] AMGN: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AMGN: model n_features = 33
[CAL] AMGN: taus=[0.68 0.4  0.4  0.34 0.28] | temperature=1.550
[SAVE] AMGN: stored taus
[SAVE] AMGN: stored temperature scale 1.550
[SAVE] AMGN: artifacts persisted (H=5)
[CAL] AMGN: loaded taus [0.68 0.4  0.4  0.34 0.28]
[CAL] AMGN: temperature scaling 1.550
Retraining model for ticker: AMZN
[TRAIN] AMZN: preparing data (H=5) with 778 rows
[TRAIN] AMZN: built 762 sequences (seq_len=12)
[TRAIN] AMZN: scaler fitted on 609 training sequences
[TRAIN] AMZN: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AMZN: model n_features = 33
[CAL] AMZN: taus=[0.74 0.54 0.52 0.42 0.2 ] | temperature=1.007
[SAVE] AMZN: stored taus
[SAVE] AMZN: stored temperature scale 1.007
[SAVE] AMZN: artifacts persisted (H=5)
[CAL] AMZN: loaded taus [0.74 0.54 0.52 0.42 0.2 ]
[CAL] AMZN: temperature scaling 1.007
Retraining model for ticker: BA
[TRAIN] BA: preparing data (H=5) with 778 rows
[TRAIN] BA: built 762 sequences (seq_len=12)
[TRAIN] BA: scaler fitted on 609 training sequences
[TRAIN] BA: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BA: model n_features = 33
[CAL] BA: taus=[0.8  0.78 0.68 0.54 0.46] | temperature=1.143
[SAVE] BA: stored taus
[SAVE] BA: stored temperature scale 1.143
[SAVE] BA: artifacts persisted (H=5)
[CAL] BA: loaded taus [0.8  0.78 0.68 0.54 0.46]
[CAL] BA: temperature scaling 1.143
Retraining model for ticker: BABA
[TRAIN] BABA: preparing data (H=5) with 284 rows
[TRAIN] BABA: built 268 sequences (seq_len=12)
[TRAIN] BABA: scaler fitted on 214 training sequences
[TRAIN] BABA: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BABA: model n_features = 33
[CAL] BABA: taus=[0.8  0.74 0.68 0.48 0.34] | temperature=1.414
[SAVE] BABA: stored taus
[SAVE] BABA: stored temperature scale 1.414
[SAVE] BABA: artifacts persisted (H=5)
[CAL] BABA: loaded taus [0.8  0.74 0.68 0.48 0.34]
[CAL] BABA: temperature scaling 1.414
Retraining model for ticker: BAC
[TRAIN] BAC: preparing data (H=5) with 778 rows
[TRAIN] BAC: built 762 sequences (seq_len=12)
[TRAIN] BAC: scaler fitted on 609 training sequences
[TRAIN] BAC: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BAC: model n_features = 33
[CAL] BAC: taus=[0.72 0.6  0.48 0.5  0.48] | temperature=2.364
[SAVE] BAC: stored taus
[SAVE] BAC: stored temperature scale 2.364
[SAVE] BAC: artifacts persisted (H=5)
[CAL] BAC: loaded taus [0.72 0.6  0.48 0.5  0.48]
[CAL] BAC: temperature scaling 2.364
Retraining model for ticker: BBL
[TRAIN] BBL: preparing data (H=5) with 778 rows
[TRAIN] BBL: built 762 sequences (seq_len=12)
[TRAIN] BBL: scaler fitted on 609 training sequences
[TRAIN] BBL: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BBL: model n_features = 33
[CAL] BBL: taus=[0.8  0.58 0.5  0.38 0.26] | temperature=1.143
[SAVE] BBL: stored taus
[SAVE] BBL: stored temperature scale 1.143
[SAVE] BBL: artifacts persisted (H=5)
[CAL] BBL: loaded taus [0.8  0.58 0.5  0.38 0.26]
[CAL] BBL: temperature scaling 1.143
Retraining model for ticker: BCH
[TRAIN] BCH: preparing data (H=5) with 778 rows
[TRAIN] BCH: built 762 sequences (seq_len=12)
[TRAIN] BCH: scaler fitted on 609 training sequences
[TRAIN] BCH: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BCH: model n_features = 33
[CAL] BCH: taus=[0.76 0.46 0.48 0.5  0.44] | temperature=1.007
[SAVE] BCH: stored taus
[SAVE] BCH: stored temperature scale 1.007
[SAVE] BCH: artifacts persisted (H=5)
[CAL] BCH: loaded taus [0.76 0.46 0.48 0.5  0.44]
[CAL] BCH: temperature scaling 1.007
Retraining model for ticker: BHP
[TRAIN] BHP: preparing data (H=5) with 778 rows
[TRAIN] BHP: built 762 sequences (seq_len=12)
[TRAIN] BHP: scaler fitted on 609 training sequences
[TRAIN] BHP: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BHP: model n_features = 33
[CAL] BHP: taus=[0.8  0.78 0.6  0.42 0.32] | temperature=0.871
[SAVE] BHP: stored taus
[SAVE] BHP: stored temperature scale 0.871
[SAVE] BHP: artifacts persisted (H=5)
[CAL] BHP: loaded taus [0.8  0.78 0.6  0.42 0.32]
[CAL] BHP: temperature scaling 0.871
Retraining model for ticker: BP
[TRAIN] BP: preparing data (H=5) with 778 rows
[TRAIN] BP: built 762 sequences (seq_len=12)
[TRAIN] BP: scaler fitted on 609 training sequences
[TRAIN] BP: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BP: model n_features = 33
[CAL] BP: taus=[0.68 0.56 0.44 0.34 0.32] | temperature=1.007
[SAVE] BP: stored taus
[SAVE] BP: stored temperature scale 1.007
[SAVE] BP: artifacts persisted (H=5)
[CAL] BP: loaded taus [0.68 0.56 0.44 0.34 0.32]
[CAL] BP: temperature scaling 1.007
Retraining model for ticker: BRK-A
[TRAIN] BRK-A: preparing data (H=5) with 778 rows
[TRAIN] BRK-A: built 762 sequences (seq_len=12)
[TRAIN] BRK-A: scaler fitted on 609 training sequences
[TRAIN] BRK-A: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BRK-A: model n_features = 33
[CAL] BRK-A: taus=[0.8  0.72 0.66 0.46 0.56] | temperature=0.600
[SAVE] BRK-A: stored taus
[SAVE] BRK-A: stored temperature scale 0.600
[SAVE] BRK-A: artifacts persisted (H=5)
[CAL] BRK-A: loaded taus [0.8  0.72 0.66 0.46 0.56]
[CAL] BRK-A: temperature scaling 0.600
Retraining model for ticker: BSAC
[TRAIN] BSAC: preparing data (H=5) with 778 rows
[TRAIN] BSAC: built 762 sequences (seq_len=12)
[TRAIN] BSAC: scaler fitted on 609 training sequences
[TRAIN] BSAC: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BSAC: model n_features = 33
[CAL] BSAC: taus=[0.74 0.54 0.66 0.78 0.56] | temperature=1.279
[SAVE] BSAC: stored taus
[SAVE] BSAC: stored temperature scale 1.279
[SAVE] BSAC: artifacts persisted (H=5)
[CAL] BSAC: loaded taus [0.74 0.54 0.66 0.78 0.56]
[CAL] BSAC: temperature scaling 1.279
Retraining model for ticker: BUD
[TRAIN] BUD: preparing data (H=5) with 778 rows
[TRAIN] BUD: built 762 sequences (seq_len=12)
[TRAIN] BUD: scaler fitted on 609 training sequences
[TRAIN] BUD: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BUD: model n_features = 33
[CAL] BUD: taus=[0.76 0.68 0.54 0.56 0.5 ] | temperature=2.229
[SAVE] BUD: stored taus
[SAVE] BUD: stored temperature scale 2.229
[SAVE] BUD: artifacts persisted (H=5)
[CAL] BUD: loaded taus [0.76 0.68 0.54 0.56 0.5 ]
[CAL] BUD: temperature scaling 2.229
Retraining model for ticker: C
[TRAIN] C: preparing data (H=5) with 778 rows
[TRAIN] C: built 762 sequences (seq_len=12)
[TRAIN] C: scaler fitted on 609 training sequences
[TRAIN] C: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] C: model n_features = 33
[CAL] C: taus=[0.72 0.76 0.8  0.52 0.48] | temperature=0.736
[SAVE] C: stored taus
[SAVE] C: stored temperature scale 0.736
[SAVE] C: artifacts persisted (H=5)
[CAL] C: loaded taus [0.72 0.76 0.8  0.52 0.48]
[CAL] C: temperature scaling 0.736
Retraining model for ticker: CAT
[TRAIN] CAT: preparing data (H=5) with 778 rows
[TRAIN] CAT: built 762 sequences (seq_len=12)
[TRAIN] CAT: scaler fitted on 609 training sequences
[TRAIN] CAT: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CAT: model n_features = 33
[CAL] CAT: taus=[0.78 0.6  0.5  0.34 0.24] | temperature=1.007
[SAVE] CAT: stored taus
[SAVE] CAT: stored temperature scale 1.007
[SAVE] CAT: artifacts persisted (H=5)
[CAL] CAT: loaded taus [0.78 0.6  0.5  0.34 0.24]
[CAL] CAT: temperature scaling 1.007
Retraining model for ticker: CELG
[TRAIN] CELG: preparing data (H=5) with 778 rows
[TRAIN] CELG: built 762 sequences (seq_len=12)
[TRAIN] CELG: scaler fitted on 609 training sequences
[TRAIN] CELG: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CELG: model n_features = 33
[CAL] CELG: taus=[0.52 0.68 0.58 0.36 0.6 ] | temperature=0.600
[SAVE] CELG: stored taus
[SAVE] CELG: stored temperature scale 0.600
[SAVE] CELG: artifacts persisted (H=5)
[CAL] CELG: loaded taus [0.52 0.68 0.58 0.36 0.6 ]
[CAL] CELG: temperature scaling 0.600
Retraining model for ticker: CHL
[TRAIN] CHL: preparing data (H=5) with 778 rows
[TRAIN] CHL: built 762 sequences (seq_len=12)
[TRAIN] CHL: scaler fitted on 609 training sequences
[TRAIN] CHL: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CHL: model n_features = 33
[CAL] CHL: taus=[0.78 0.46 0.44 0.26 0.2 ] | temperature=0.736
[SAVE] CHL: stored taus
[SAVE] CHL: stored temperature scale 0.736
[SAVE] CHL: artifacts persisted (H=5)
[CAL] CHL: loaded taus [0.78 0.46 0.44 0.26 0.2 ]
[CAL] CHL: temperature scaling 0.736
Retraining model for ticker: CHTR
[TRAIN] CHTR: preparing data (H=5) with 778 rows
[TRAIN] CHTR: built 762 sequences (seq_len=12)
[TRAIN] CHTR: scaler fitted on 609 training sequences
[TRAIN] CHTR: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CHTR: model n_features = 33
[CAL] CHTR: taus=[0.74 0.68 0.58 0.48 0.38] | temperature=1.686
[SAVE] CHTR: stored taus
[SAVE] CHTR: stored temperature scale 1.686
[SAVE] CHTR: artifacts persisted (H=5)
[CAL] CHTR: loaded taus [0.74 0.68 0.58 0.48 0.38]
[CAL] CHTR: temperature scaling 1.686
Retraining model for ticker: CMCSA
[TRAIN] CMCSA: preparing data (H=5) with 778 rows
[TRAIN] CMCSA: built 762 sequences (seq_len=12)
[TRAIN] CMCSA: scaler fitted on 609 training sequences
[TRAIN] CMCSA: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CMCSA: model n_features = 33
[CAL] CMCSA: taus=[0.78 0.66 0.48 0.22 0.34] | temperature=0.600
[SAVE] CMCSA: stored taus
[SAVE] CMCSA: stored temperature scale 0.600
[SAVE] CMCSA: artifacts persisted (H=5)
[CAL] CMCSA: loaded taus [0.78 0.66 0.48 0.22 0.34]
[CAL] CMCSA: temperature scaling 0.600
Retraining model for ticker: CODI
[TRAIN] CODI: preparing data (H=5) with 778 rows
[TRAIN] CODI: built 762 sequences (seq_len=12)
[TRAIN] CODI: scaler fitted on 609 training sequences
[TRAIN] CODI: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CODI: model n_features = 33
[CAL] CODI: taus=[0.6  0.68 0.6  0.42 0.7 ] | temperature=0.736
[SAVE] CODI: stored taus
[SAVE] CODI: stored temperature scale 0.736
[SAVE] CODI: artifacts persisted (H=5)
[CAL] CODI: loaded taus [0.6  0.68 0.6  0.42 0.7 ]
[CAL] CODI: temperature scaling 0.736
Retraining model for ticker: CSCO
[TRAIN] CSCO: preparing data (H=5) with 778 rows
[TRAIN] CSCO: built 762 sequences (seq_len=12)
[TRAIN] CSCO: scaler fitted on 609 training sequences
[TRAIN] CSCO: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CSCO: model n_features = 33
[CAL] CSCO: taus=[0.52 0.4  0.36 0.28 0.28] | temperature=2.229
[SAVE] CSCO: stored taus
[SAVE] CSCO: stored temperature scale 2.229
[SAVE] CSCO: artifacts persisted (H=5)
[CAL] CSCO: loaded taus [0.52 0.4  0.36 0.28 0.28]
[CAL] CSCO: temperature scaling 2.229
Retraining model for ticker: CVX
[TRAIN] CVX: preparing data (H=5) with 778 rows
[TRAIN] CVX: built 762 sequences (seq_len=12)
[TRAIN] CVX: scaler fitted on 609 training sequences
[TRAIN] CVX: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CVX: model n_features = 33
[CAL] CVX: taus=[0.46 0.78 0.52 0.4  0.66] | temperature=0.600
[SAVE] CVX: stored taus
[SAVE] CVX: stored temperature scale 0.600
[SAVE] CVX: artifacts persisted (H=5)
[CAL] CVX: loaded taus [0.46 0.78 0.52 0.4  0.66]
[CAL] CVX: temperature scaling 0.600
Retraining model for ticker: D
[TRAIN] D: preparing data (H=5) with 778 rows
[TRAIN] D: built 762 sequences (seq_len=12)
[TRAIN] D: scaler fitted on 609 training sequences
[TRAIN] D: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] D: model n_features = 33
[CAL] D: taus=[0.78 0.54 0.46 0.36 0.4 ] | temperature=0.736
[SAVE] D: stored taus
[SAVE] D: stored temperature scale 0.736
[SAVE] D: artifacts persisted (H=5)
[CAL] D: loaded taus [0.78 0.54 0.46 0.36 0.4 ]
[CAL] D: temperature scaling 0.736
Retraining model for ticker: DHR
[TRAIN] DHR: preparing data (H=5) with 778 rows
[TRAIN] DHR: built 762 sequences (seq_len=12)
[TRAIN] DHR: scaler fitted on 609 training sequences
[TRAIN] DHR: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] DHR: model n_features = 33
[CAL] DHR: taus=[0.78 0.66 0.2  0.38 0.26] | temperature=1.143
[SAVE] DHR: stored taus
[SAVE] DHR: stored temperature scale 1.143
[SAVE] DHR: artifacts persisted (H=5)
[CAL] DHR: loaded taus [0.78 0.66 0.2  0.38 0.26]
[CAL] DHR: temperature scaling 1.143
Retraining model for ticker: DIS
[TRAIN] DIS: preparing data (H=5) with 778 rows
[TRAIN] DIS: built 762 sequences (seq_len=12)
[TRAIN] DIS: scaler fitted on 609 training sequences
[TRAIN] DIS: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] DIS: model n_features = 33
[CAL] DIS: taus=[0.7  0.4  0.46 0.32 0.34] | temperature=1.007
[SAVE] DIS: stored taus
[SAVE] DIS: stored temperature scale 1.007
[SAVE] DIS: artifacts persisted (H=5)
[CAL] DIS: loaded taus [0.7  0.4  0.46 0.32 0.34]
[CAL] DIS: temperature scaling 1.007
Retraining model for ticker: DUK
[TRAIN] DUK: preparing data (H=5) with 778 rows
[TRAIN] DUK: built 762 sequences (seq_len=12)
[TRAIN] DUK: scaler fitted on 609 training sequences
[TRAIN] DUK: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] DUK: model n_features = 33
[CAL] DUK: taus=[0.8  0.52 0.44 0.28 0.22] | temperature=0.736
[SAVE] DUK: stored taus
[SAVE] DUK: stored temperature scale 0.736
[SAVE] DUK: artifacts persisted (H=5)
[CAL] DUK: loaded taus [0.8  0.52 0.44 0.28 0.22]
[CAL] DUK: temperature scaling 0.736
Retraining model for ticker: EXC
[TRAIN] EXC: preparing data (H=5) with 778 rows
[TRAIN] EXC: built 762 sequences (seq_len=12)
[TRAIN] EXC: scaler fitted on 609 training sequences
[TRAIN] EXC: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] EXC: model n_features = 33
[CAL] EXC: taus=[0.78 0.78 0.52 0.48 0.54] | temperature=0.871
[SAVE] EXC: stored taus
[SAVE] EXC: stored temperature scale 0.871
[SAVE] EXC: artifacts persisted (H=5)
[CAL] EXC: loaded taus [0.78 0.78 0.52 0.48 0.54]
[CAL] EXC: temperature scaling 0.871
Retraining model for ticker: FB
[TRAIN] FB: preparing data (H=5) with 778 rows
[TRAIN] FB: built 762 sequences (seq_len=12)
[TRAIN] FB: scaler fitted on 609 training sequences
[TRAIN] FB: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] FB: model n_features = 33
[CAL] FB: taus=[0.54 0.5  0.44 0.36 0.3 ] | temperature=1.957
[SAVE] FB: stored taus
[SAVE] FB: stored temperature scale 1.957
[SAVE] FB: artifacts persisted (H=5)
[CAL] FB: loaded taus [0.54 0.5  0.44 0.36 0.3 ]
[CAL] FB: temperature scaling 1.957
Retraining model for ticker: GD
[TRAIN] GD: preparing data (H=5) with 778 rows
[TRAIN] GD: built 762 sequences (seq_len=12)
[TRAIN] GD: scaler fitted on 609 training sequences
[TRAIN] GD: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] GD: model n_features = 33
[CAL] GD: taus=[0.2  0.2  0.42 0.52 0.48] | temperature=0.600
[SAVE] GD: stored taus
[SAVE] GD: stored temperature scale 0.600
[SAVE] GD: artifacts persisted (H=5)
[CAL] GD: loaded taus [0.2  0.2  0.42 0.52 0.48]
[CAL] GD: temperature scaling 0.600
Retraining model for ticker: GE
[TRAIN] GE: preparing data (H=5) with 778 rows
[TRAIN] GE: built 762 sequences (seq_len=12)
[TRAIN] GE: scaler fitted on 609 training sequences
[TRAIN] GE: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] GE: model n_features = 33
[CAL] GE: taus=[0.8  0.42 0.5  0.46 0.34] | temperature=0.736
[SAVE] GE: stored taus
[SAVE] GE: stored temperature scale 0.736
[SAVE] GE: artifacts persisted (H=5)
[CAL] GE: loaded taus [0.8  0.42 0.5  0.46 0.34]
[CAL] GE: temperature scaling 0.736
Retraining model for ticker: GOOG
[TRAIN] GOOG: preparing data (H=5) with 778 rows
[TRAIN] GOOG: built 762 sequences (seq_len=12)
[TRAIN] GOOG: scaler fitted on 609 training sequences
[TRAIN] GOOG: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] GOOG: model n_features = 33
[CAL] GOOG: taus=[0.8  0.66 0.52 0.36 0.3 ] | temperature=0.736
[SAVE] GOOG: stored taus
[SAVE] GOOG: stored temperature scale 0.736
[SAVE] GOOG: artifacts persisted (H=5)
[CAL] GOOG: loaded taus [0.8  0.66 0.52 0.36 0.3 ]
[CAL] GOOG: temperature scaling 0.736
Retraining model for ticker: HD
[TRAIN] HD: preparing data (H=5) with 778 rows
[TRAIN] HD: built 762 sequences (seq_len=12)
[TRAIN] HD: scaler fitted on 609 training sequences
[TRAIN] HD: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] HD: model n_features = 33
[CAL] HD: taus=[0.5  0.44 0.42 0.22 0.24] | temperature=0.871
[SAVE] HD: stored taus
[SAVE] HD: stored temperature scale 0.871
[SAVE] HD: artifacts persisted (H=5)
[CAL] HD: loaded taus [0.5  0.44 0.42 0.22 0.24]
[CAL] HD: temperature scaling 0.871
Retraining model for ticker: HON
[TRAIN] HON: preparing data (H=5) with 778 rows
[TRAIN] HON: built 762 sequences (seq_len=12)
[TRAIN] HON: scaler fitted on 609 training sequences
[TRAIN] HON: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] HON: model n_features = 33
[CAL] HON: taus=[0.78 0.76 0.5  0.66 0.52] | temperature=2.093
[SAVE] HON: stored taus
[SAVE] HON: stored temperature scale 2.093
[SAVE] HON: artifacts persisted (H=5)
[CAL] HON: loaded taus [0.78 0.76 0.5  0.66 0.52]
[CAL] HON: temperature scaling 2.093
Retraining model for ticker: HRG
[TRAIN] HRG: preparing data (H=5) with 778 rows
[TRAIN] HRG: built 762 sequences (seq_len=12)

Simulating Trading Days:   1%|          | 1/100 [10:19<17:02:19, 619.59s/it]

[CAL] XOM: taus=[0.72 0.68 0.44 0.48 0.42] | temperature=1.550
[SAVE] XOM: stored taus
[SAVE] XOM: stored temperature scale 1.550
[SAVE] XOM: artifacts persisted (H=5)
[CAL] XOM: loaded taus [0.72 0.68 0.44 0.48 0.42]
[CAL] XOM: temperature scaling 1.550
[SIM] 2017-04-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.943)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0022, p_up=0.709)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0012, p_up=0.615)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.542)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0090, p_up=0.846)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0050, p_up=0.901)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0026, p_up=0.614)
[SIM] 2017-04-11 00:00:00: 7 trades proposed.
[TRADE] 2017-04-11 00:00:00: allocated $8922.92 to AAPL exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $7948.69 to VZ exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $7263.25 to BABA exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $4117.19 to MA exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $1747.95 to MRK exiting on 2017-04-19 00:00:00

Simulating Trading Days:   2%|▏         | 2/100 [10:20<6:57:55, 255.87s/it]

[SIM] 2017-04-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0004, p_up=0.549)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0049, p_up=0.586)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0022, p_up=0.712)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0033, p_up=0.720)
[PORT] Sector Industrial Goods: sampled MMM from top-3 (expected=0.0038, p_up=0.678)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0016, p_up=0.572)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0051, p_up=0.906)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0020, p_up=0.491)
[SIM] 2017-04-12 00:00:00: 8 trades proposed.
[TRADE] 2017-04-12 00:00:00: allocated $5643.79 to VZ exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $3122.52 to ABBV exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $2918.13 to MA exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $2737.75 to MMM exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $1275.70 to MO exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $1310.88 to PCLN exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $1053.64 to SPLP exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $188.90 to PCG exiting on 2017-04-20 00:00:00

Simulating Trading Days:   3%|▎         | 3/100 [10:21<3:45:34, 139.53s/it]

[SIM] 2017-04-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-1 (expected=0.0009, p_up=0.697)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0013, p_up=0.660)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0052, p_up=0.616)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0023, p_up=0.977)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0044, p_up=0.817)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.548)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0090, p_up=0.849)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0050, p_up=0.903)
[PORT] Sector Utilities: sampled NGG from top-1 (expected=0.0007, p_up=0.934)
[SIM] 2017-04-13 00:00:00: 9 trades proposed.
[TRADE] 2017-04-13 00:00:00: allocated $4961.22 to BRK-A exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $4448.82 to NGG exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $4137.40 to VZ exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $3785.23 to BABA exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $3300.12 to ABBV exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $1115.89 to CVX exiting on 2017-04-21 00:00:00

Simulating Trading Days:   4%|▍         | 4/100 [10:23<2:15:48, 84.88s/it]

[SIM] 2017-04-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-1 (expected=0.0015, p_up=0.807)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0019, p_up=0.741)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.944)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.723)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0022, p_up=0.829)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0067, p_up=0.906)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.549)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0050, p_up=0.901)
[PORT] Sector Utilities: sampled NGG from top-1 (expected=0.0007, p_up=0.938)
[SIM] 2017-04-17 00:00:00: 9 trades proposed.

Simulating Trading Days:   5%|▌         | 5/100 [10:24<1:26:34, 54.67s/it]

[SIM] 2017-04-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-1 (expected=0.0019, p_up=0.882)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0021, p_up=0.762)
[PORT] Sector Consumer Goods: sampled BUD from top-3 (expected=0.0022, p_up=0.548)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0041, p_up=0.532)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0059, p_up=0.882)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.545)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.556)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0049, p_up=0.899)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0019, p_up=0.518)
[SIM] 2017-04-18 00:00:00: 9 trades proposed.
[EXIT] 2017-04-19 00:00:00: AAPL r=-0.0067, PnL=$-59.85
[EXIT] 2017-04-19 00:00:00: VZ r=0.0049, PnL=$39.17
[EXIT] 2017-04-19 00:00:00: BABA r=0.0029, PnL=$21.05
[EXIT] 2017-04-19 00:00:00: MA r=0.0016, PnL=$6.61
[EXIT] 2017-04-19 00:00:00: MRK r=0.0010, PnL=$1.68

Simulating Trading Days:   6%|▌         | 6/100 [10:25<57:07, 36.46s/it]

[SIM] 2017-04-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-1 (expected=0.0020, p_up=0.926)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0022, p_up=0.781)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.945)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.727)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0054, p_up=0.863)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.541)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.562)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0049, p_up=0.895)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.946)
[SIM] 2017-04-19 00:00:00: 9 trades proposed.
[TRADE] 2017-04-19 00:00:00: allocated $5309.58 to NGG exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $5383.09 to AAPL exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $5123.43 to CVX exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $4694.88 to VZ exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $4375.31 to ABBV exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $3513.91 to SPLP exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $1602.40 to MA exiting on 2017-04-26 00:00:00
[EXIT] 2017-04-20 00:00:00: VZ r=-0.0104, PnL=$-58.84
[EXIT] 2017-04-20 00:00:00: ABBV r=-0.0092, PnL=$-28.62
[EXIT] 2017-04-20 00:00:00: MA r=0.0280, PnL=$81.68
[EXIT] 2017-04-20 00:00:00: MMM r=0.0077, PnL=$21.07
[EXIT] 2017-04-20 00:00:00: MO r=-0.0104, PnL=$-13.26
[EXIT] 2017-04-20 00:00:00: PCLN r=0.0062, PnL=$8.08
[EXIT] 2017-04-20 00:00:00: SPLP r=-0.0319, PnL=$-33.63
[EXIT] 2017-04-20 00:00:00: PCG r=-0.0055, PnL=$-1.04

Simulating Trading Days:   7%|▋         | 7/100 [10:26<38:36, 24.91s/it]

[SIM] 2017-04-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0000, p_up=0.633)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0022, p_up=0.777)
[PORT] Sector Consumer Goods: sampled BUD from top-3 (expected=0.0022, p_up=0.543)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.731)
[PORT] Sector Healthcare: sampled NVS from top-3 (expected=0.0013, p_up=0.727)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0068, p_up=0.915)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.803)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0048, p_up=0.617)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0022, p_up=0.543)
[SIM] 2017-04-20 00:00:00: 9 trades proposed.
[TRADE] 2017-04-20 00:00:00: allocated $4053.93 to GD exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $3137.99 to BABA exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $2790.51 to SPLP exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $2195.58 to MA exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $2122.02 to NVS exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $1308.26 to SLB exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $1464.70 to CHL exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $200.83 to BUD exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $424.61 to EXC exiting on 2017-04-27 00:00:00
[EXIT] 2017-04-21 00:00:00: BRK-A r=0.0022, PnL=$11.14
[EXIT] 2017-04-21 00:00:00: NGG r=-0.0082, PnL=$-36.44
[EXIT] 2017-04-21 00:00:00: VZ r=-0.0282, PnL=$-116.58
[EXIT] 2017-04-21 00:00:00: BABA r=0.0263, PnL=$99.60
[EXIT] 2017-04-21 00:00:00: ABBV r=-0.0048, PnL=$-15.95
[EXIT] 2017-04-21 00:00:00: CVX r=-0.0114, PnL=$-12.73

Simulating Trading Days:   8%|▊         | 8/100 [10:27<26:35, 17.35s/it]

[SIM] 2017-04-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0020, p_up=0.966)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0020, p_up=0.753)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0022, p_up=0.837)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0040, p_up=0.525)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0038, p_up=0.772)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0040, p_up=0.536)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.790)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0023, p_up=0.923)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0022, p_up=0.540)
[SIM] 2017-04-21 00:00:00: 9 trades proposed.
[TRADE] 2017-04-21 00:00:00: allocated $4870.56 to CVX exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $4395.23 to T exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $3497.09 to UL exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $3273.27 to BABA exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $2869.13 to ABBV exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $2771.94 to SPLP exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $424.54 to EXC exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $136.41 to LMT exiting on 2017-04-28 00:00:00

Simulating Trading Days:   9%|▉         | 9/100 [10:28<18:36, 12.27s/it]

[SIM] 2017-04-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0006, p_up=0.704)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0017, p_up=0.722)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.947)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0040, p_up=0.519)
[PORT] Sector Healthcare: sampled NVS from top-3 (expected=0.0014, p_up=0.762)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0040, p_up=0.538)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.568)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0023, p_up=0.932)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0021, p_up=0.530)
[SIM] 2017-04-24 00:00:00: 9 trades proposed.

Simulating Trading Days:  10%|█         | 10/100 [10:29<13:13,  8.82s/it]

[SIM] 2017-04-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0020, p_up=0.959)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0016, p_up=0.708)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0022, p_up=0.826)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.745)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0073, p_up=0.606)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0070, p_up=0.933)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0088, p_up=0.766)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.645)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0005, p_up=0.959)
[SIM] 2017-04-25 00:00:00: 9 trades proposed.
[EXIT] 2017-04-26 00:00:00: NGG r=0.0056, PnL=$29.82
[EXIT] 2017-04-26 00:00:00: AAPL r=0.0213, PnL=$114.79
[EXIT] 2017-04-26 00:00:00: CVX r=0.0177, PnL=$90.94
[EXIT] 2017-04-26 00:00:00: VZ r=-0.0323, PnL=$-151.57
[EXIT] 2017-04-26 00:00:00: ABBV r=0.0251, PnL=$109.64
[EXIT] 2017-04-26 00:00:00: SPLP r=0.0222, PnL=$78.09
[EXIT] 2017-04-26 00:00:00: MA r=0.0346, PnL=$55.37

Simulating Trading Days:  11%|█         | 11/100 [10:30<09:34,  6.45s/it]

[SIM] 2017-04-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0008, p_up=0.727)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0015, p_up=0.687)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0058, p_up=0.676)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.514)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0032, p_up=0.707)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0038, p_up=0.862)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0071, p_up=0.670)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0024, p_up=0.934)
[PORT] Sector Utilities: sampled EXC from top-2 (expected=0.0020, p_up=0.525)
[SIM] 2017-04-26 00:00:00: 9 trades proposed.
[TRADE] 2017-04-26 00:00:00: allocated $5214.09 to T exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $4289.43 to ABB exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $2754.89 to SLB exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $2543.03 to ABBV exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $2451.81 to SPLP exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $2155.77 to MO exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $2276.51 to AMZN exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $316.59 to EXC exiting on 2017-05-03 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $515.70 to V exiting on 2017-05-03 00:00:00
[EXIT] 2017-04-27 00:00:00: GD r=0.0367, PnL=$148.69
[EXIT] 2017-04-27 00:00:00: BABA r=0.0219, PnL=$68.62
[EXIT] 2017-04-27 00:00:00: SPLP r=0.0110, PnL=$30.66
[EXIT] 2017-04-27 00:00:00: MA r=0.0219, PnL=$48.09
[EXIT] 2017-04-27 00:00:00: NVS r=0.0467, PnL=$99.15
[EXIT] 2017-04-27 00:00:00: SLB r=-0.0480, PnL=$-62.75
[EXIT] 2017-04-27 00:00:00: CHL r=-0.0095, PnL=$-13.86
[EXIT] 2017-04-27 00:00:00: BUD r=0.0288, PnL=$5.78
[EXIT] 2017-04-27 00:00:00: EXC r=-0.0060, PnL=$-2.54

Simulating Trading Days:  12%|█▏        | 12/100 [10:31<07:04,  4.83s/it]

[SIM] 2017-04-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0008, p_up=0.610)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0014, p_up=0.677)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.946)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.507)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.910)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0041, p_up=0.540)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0087, p_up=0.755)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0029, p_up=0.777)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0004, p_up=0.966)
[SIM] 2017-04-27 00:00:00: 9 trades proposed.
[TRADE] 2017-04-27 00:00:00: allocated $5172.32 to NGG exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $5018.72 to AAPL exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $4660.80 to CELG exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $2988.66 to VZ exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $3149.81 to BABA exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $2156.78 to SPLP exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $1253.87 to SNP exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $809.26 to LMT exiting on 2017-05-04 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $407.18 to V exiting on 2017-05-04 00:00:00
[EXIT] 2017-04-28 00:00:00: CVX r=0.0173, PnL=$84.05
[EXIT] 2017-04-28 00:00:00: T r=-0.0075, PnL=$-33.02
[EXIT] 2017-04-28 00:00:00: UL r=0.0248, PnL=$86.55
[EXIT] 2017-04-28 00:00:00: BABA r=0.0211, PnL=$69.16
[EXIT] 2017-04-28 00:00:00: ABBV r=0.0332, PnL=$95.31
[EXIT] 2017-04-28 00:00:00: SPLP r=0.0110, PnL=$30.46
[EXIT] 2017-04-28 00:00:00: EXC r=-0.0114, PnL=$-4.85
[EXIT] 2017-04-28 00:00:00: LMT r=-0.0133, PnL=$-1.82

Simulating Trading Days:  13%|█▎        | 13/100 [10:33<05:23,  3.72s/it]

[SIM] 2017-04-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0012, p_up=0.756)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0011, p_up=0.647)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0064, p_up=0.733)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.505)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.944)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0073, p_up=0.949)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0087, p_up=0.749)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0024, p_up=0.936)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0004, p_up=0.968)
[SIM] 2017-04-28 00:00:00: 9 trades proposed.
[TRADE] 2017-04-28 00:00:00: allocated $4912.30 to NGG exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $4767.78 to GD exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $4730.79 to CELG exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $4580.84 to T exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $2719.87 to CVX exiting on 2017-05-05 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $774.74 to BABA exiting on 2017-05-05 00:00:00

Simulating Trading Days:  14%|█▍        | 14/100 [10:34<04:11,  2.93s/it]

[SIM] 2017-05-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0012, p_up=0.748)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0009, p_up=0.615)
[PORT] Sector Consumer Goods: sampled BUD from top-3 (expected=0.0022, p_up=0.541)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.513)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0019, p_up=0.769)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0040, p_up=0.529)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.543)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0024, p_up=0.934)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0023, p_up=0.515)
[SIM] 2017-05-01 00:00:00: 9 trades proposed.

Simulating Trading Days:  15%|█▌        | 15/100 [10:35<03:22,  2.38s/it]

[SIM] 2017-05-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0017, p_up=0.686)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0005, p_up=0.565)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0071, p_up=0.792)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.997)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0018, p_up=0.757)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0076, p_up=0.960)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0061, p_up=0.608)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0046, p_up=0.881)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0024, p_up=0.523)
[SIM] 2017-05-02 00:00:00: 9 trades proposed.
[EXIT] 2017-05-03 00:00:00: T r=-0.0504, PnL=$-263.03
[EXIT] 2017-05-03 00:00:00: ABB r=0.0157, PnL=$67.27
[EXIT] 2017-05-03 00:00:00: SLB r=-0.0348, PnL=$-95.91
[EXIT] 2017-05-03 00:00:00: ABBV r=0.0261, PnL=$66.47
[EXIT] 2017-05-03 00:00:00: SPLP r=-0.0109, PnL=$-26.65
[EXIT] 2017-05-03 00:00:00: MO r=-0.0180, PnL=$-38.89
[EXIT] 2017-05-03 00:00:00: AMZN r=0.0349, PnL=$79.46
[EXIT] 2017-05-03 00:00:00: EXC r=-0.0264, PnL=$-8.35
[EXIT] 2017-05-03 00:00:00: V r=0.0068, PnL=$3.48

Simulating Trading Days:  16%|█▌        | 16/100 [10:36<02:47,  2.00s/it]

[SIM] 2017-05-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0017, p_up=0.688)
[PORT] Sector Conglomerates: sampled SPLP from top-1 (expected=0.0001, p_up=0.520)
[PORT] Sector Consumer Goods: sampled BUD from top-3 (expected=0.0022, p_up=0.541)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0042, p_up=0.541)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0030, p_up=0.505)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0038, p_up=0.517)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0087, p_up=0.747)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0024, p_up=0.938)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0004, p_up=0.969)
[SIM] 2017-05-03 00:00:00: 9 trades proposed.
[TRADE] 2017-05-03 00:00:00: allocated $4914.50 to NGG exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $4590.95 to T exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $2889.58 to BABA exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $1989.03 to SNP exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $223.20 to BUD exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $713.07 to V exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $467.08 to SPLP exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $549.59 to LMT exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $201.91 to MDT exiting on 2017-05-10 00:00:00
[EXIT] 2017-05-04 00:00:00: NGG r=0.0071, PnL=$36.58
[EXIT] 2017-05-04 00:00:00: AAPL r=0.0191, PnL=$95.63
[EXIT] 2017-05-04 00:00:00: CELG r=0.0040, PnL=$18.42
[EXIT] 2017-05-04 00:00:00: VZ r=-0.0169, PnL=$-50.59
[EXIT] 2017-05-04 00:00:00: BABA r=0.0037, PnL=$11.73
[EXIT] 2017-05-04 00:00:00: SPLP r=-0.0136, PnL=$-29.30
[EXIT] 2017-05-04 00:00:00: SNP r=-0.0329, PnL=$-41.23
[EXIT] 2017-05-04 00:00:00: LMT r=-0.0023, PnL=$-1.88
[EXIT] 2017-05-04 00:00:00: V r=0.0111, PnL=$4.53

Simulating Trading Days:  17%|█▋        | 17/100 [10:37<02:23,  1.73s/it]

[SIM] 2017-05-04 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0016, p_up=0.677)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0073, p_up=0.809)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0044, p_up=0.561)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.786)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0078, p_up=0.970)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0054, p_up=0.557)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.667)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0028, p_up=0.649)
[SIM] 2017-05-04 00:00:00: 8 trades proposed.
[TRADE] 2017-05-04 00:00:00: allocated $5818.40 to GD exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $3829.85 to MO exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $3741.08 to CELG exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $2193.86 to SNP exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $2452.08 to CHL exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $1681.32 to PPL exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $1061.39 to V exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $1010.18 to AMZN exiting on 2017-05-11 00:00:00
[EXIT] 2017-05-05 00:00:00: NGG r=0.0193, PnL=$94.66
[EXIT] 2017-05-05 00:00:00: GD r=0.0112, PnL=$53.63
[EXIT] 2017-05-05 00:00:00: CELG r=-0.0132, PnL=$-62.54
[EXIT] 2017-05-05 00:00:00: T r=-0.0270, PnL=$-123.68
[EXIT] 2017-05-05 00:00:00: CVX r=-0.0085, PnL=$-23.20
[EXIT] 2017-05-05 00:00:00: BABA r=0.0047, PnL=$3.62

Simulating Trading Days:  18%|█▊        | 18/100 [10:38<02:06,  1.54s/it]

[SIM] 2017-05-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0014, p_up=0.658)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0025, p_up=0.783)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0046, p_up=0.578)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0072, p_up=0.592)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0038, p_up=0.514)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0049, p_up=0.525)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0065, p_up=0.960)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0026, p_up=0.536)
[SIM] 2017-05-05 00:00:00: 8 trades proposed.
[TRADE] 2017-05-05 00:00:00: allocated $5710.49 to VZ exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $3541.32 to PG exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $1988.54 to SNP exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $1566.64 to CELG exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $1268.52 to V exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $698.66 to PCG exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $647.63 to AMZN exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $629.34 to LMT exiting on 2017-05-12 00:00:00

Simulating Trading Days:  19%|█▉        | 19/100 [10:39<01:54,  1.41s/it]

[SIM] 2017-05-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0012, p_up=0.642)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.938)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0021, p_up=0.669)
[PORT] Sector Healthcare: sampled MDT from top-2 (expected=0.0034, p_up=0.659)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0038, p_up=0.512)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.544)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.678)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0034, p_up=0.724)
[SIM] 2017-05-08 00:00:00: 8 trades proposed.
[TRADE] 2017-05-08 00:00:00: allocated $4092.21 to AAPL exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1985.90 to PPL exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1927.51 to CHL exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1530.81 to MA exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $1554.18 to MDT exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $864.61 to CHTR exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $447.90 to LMT exiting on 2017-05-15 00:00:00

Simulating Trading Days:  20%|██        | 20/100 [10:40<01:45,  1.32s/it]

[SIM] 2017-05-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0010, p_up=0.624)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0075, p_up=0.831)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0047, p_up=0.597)
[PORT] Sector Healthcare: sampled MDT from top-2 (expected=0.0035, p_up=0.699)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0039, p_up=0.870)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.545)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0069, p_up=0.974)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0026, p_up=0.538)
[SIM] 2017-05-09 00:00:00: 8 trades proposed.
[TRADE] 2017-05-09 00:00:00: allocated $3201.61 to VZ exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $477.82 to BA exiting on 2017-05-16 00:00:00
[EXIT] 2017-05-10 00:00:00: NGG r=0.0276, PnL=$135.49
[EXIT] 2017-05-10 00:00:00: T r=0.0013, PnL=$5.98
[EXIT] 2017-05-10 00:00:00: BABA r=0.0293, PnL=$84.53
[EXIT] 2017-05-10 00:00:00: SNP r=0.0046, PnL=$9.15
[EXIT] 2017-05-10 00:00:00: BUD r=0.0526, PnL=$11.75
[EXIT] 2017-05-10 00:00:00: V r=-0.0021, PnL=$-1.47
[EXIT] 2017-05-10 00:00:00: SPLP r=0.0016, PnL=$0.77
[EXIT] 2017-05-10 00:00:00: LMT r=0.0079, PnL=$4.36
[EXIT] 2017-05-10 00:00:00: MDT r=-0.0143, PnL=$-2.88

Simulating Trading Days:  21%|██        | 21/100 [10:41<01:39,  1.25s/it]

[SIM] 2017-05-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0009, p_up=0.613)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.938)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0047, p_up=0.596)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0037, p_up=0.749)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0080, p_up=0.980)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0035, p_up=0.749)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0070, p_up=0.977)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0036, p_up=0.753)
[SIM] 2017-05-10 00:00:00: 8 trades proposed.
[TRADE] 2017-05-10 00:00:00: allocated $4520.14 to GD exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $4471.24 to VZ exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $4147.68 to AAPL exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $2296.49 to PPL exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $1276.72 to MDT exiting on 2017-05-17 00:00:00
[EXIT] 2017-05-11 00:00:00: GD r=0.0022, PnL=$12.86
[EXIT] 2017-05-11 00:00:00: MO r=0.0024, PnL=$9.26
[EXIT] 2017-05-11 00:00:00: CELG r=-0.0397, PnL=$-148.49
[EXIT] 2017-05-11 00:00:00: SNP r=0.0188, PnL=$41.19
[EXIT] 2017-05-11 00:00:00: CHL r=0.0200, PnL=$49.01
[EXIT] 2017-05-11 00:00:00: PPL r=0.0026, PnL=$4.37
[EXIT] 2017-05-11 00:00:00: V r=-0.0056, PnL=$-5.96
[EXIT] 2017-05-11 00:00:00: AMZN r=0.0108, PnL=$10.87

Simulating Trading Days:  22%|██▏       | 22/100 [10:43<01:34,  1.21s/it]

[SIM] 2017-05-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0008, p_up=0.612)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0023, p_up=0.604)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.717)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0080, p_up=0.676)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.887)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0034, p_up=0.746)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0050, p_up=0.692)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0026, p_up=0.632)
[SIM] 2017-05-11 00:00:00: 8 trades proposed.
[TRADE] 2017-05-11 00:00:00: allocated $4035.98 to BA exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $2693.92 to PCLN exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $2223.09 to MA exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $2298.94 to CHL exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $2102.79 to CELG exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $1332.67 to SO exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $1177.24 to SNP exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $1128.89 to UN exiting on 2017-05-18 00:00:00
[EXIT] 2017-05-12 00:00:00: VZ r=-0.0182, PnL=$-103.96
[EXIT] 2017-05-12 00:00:00: PG r=-0.0036, PnL=$-12.69
[EXIT] 2017-05-12 00:00:00: SNP r=0.0294, PnL=$58.43
[EXIT] 2017-05-12 00:00:00: CELG r=-0.0252, PnL=$-39.55
[EXIT] 2017-05-12 00:00:00: V r=0.0069, PnL=$8.82
[EXIT] 2017-05-12 00:00:00: PCG r=-0.0121, PnL=$-8.43
[EXIT] 2017-05-12 00:00:00: AMZN r=0.0291, PnL=$18.86
[EXIT] 2017-05-12 00:00:00: LMT r=-0.0065, PnL=$-4.08

Simulating Trading Days:  23%|██▎       | 23/100 [10:44<01:30,  1.18s/it]

[SIM] 2017-05-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0010, p_up=0.621)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0076, p_up=0.837)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.728)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0012, p_up=0.613)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.891)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0091, p_up=0.885)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0071, p_up=0.979)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0024, p_up=0.518)
[SIM] 2017-05-12 00:00:00: 8 trades proposed.
[TRADE] 2017-05-12 00:00:00: allocated $4879.91 to VZ exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $4002.05 to BA exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $4046.59 to BABA exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $3446.73 to MO exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $2298.49 to MA exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $1249.74 to SNP exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $845.66 to MRK exiting on 2017-05-19 00:00:00
[EXIT] 2017-05-15 00:00:00: AAPL r=0.0176, PnL=$71.94
[EXIT] 2017-05-15 00:00:00: PPL r=0.0036, PnL=$7.19
[EXIT] 2017-05-15 00:00:00: CHL r=0.0162, PnL=$31.24
[EXIT] 2017-05-15 00:00:00: MA r=0.0137, PnL=$21.00
[EXIT] 2017-05-15 00:00:00: MDT r=0.0101, PnL=$15.67
[EXIT] 2017-05-15 00:00:00: CHTR r=-0.0085, PnL=$-7.32
[EXIT] 2017-05-15 00:00:00: LMT r=-0.0006, PnL=$-0.25

Simulating Trading Days:  24%|██▍       | 24/100 [10:45<01:28,  1.17s/it]

[SIM] 2017-05-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0014, p_up=0.656)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0024, p_up=0.615)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.740)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0041, p_up=0.858)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0082, p_up=0.986)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.897)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0026, p_up=0.983)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0023, p_up=0.590)
[SIM] 2017-05-15 00:00:00: 8 trades proposed.
[TRADE] 2017-05-15 00:00:00: allocated $4161.63 to GD exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $4124.95 to T exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $3488.85 to BABA exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $725.33 to MDT exiting on 2017-05-22 00:00:00
[EXIT] 2017-05-16 00:00:00: VZ r=-0.0239, PnL=$-76.56
[EXIT] 2017-05-16 00:00:00: BA r=-0.0225, PnL=$-10.76

Simulating Trading Days:  25%|██▌       | 25/100 [10:46<01:27,  1.17s/it]

[SIM] 2017-05-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0018, p_up=0.693)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.939)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.807)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.934)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0082, p_up=0.987)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0054, p_up=0.559)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.673)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0022, p_up=0.570)
[SIM] 2017-05-16 00:00:00: 8 trades proposed.
[TRADE] 2017-05-16 00:00:00: allocated $3303.90 to GD exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $314.40 to AAPL exiting on 2017-05-23 00:00:00
[EXIT] 2017-05-17 00:00:00: GD r=-0.0122, PnL=$-55.34
[EXIT] 2017-05-17 00:00:00: VZ r=-0.0410, PnL=$-183.17
[EXIT] 2017-05-17 00:00:00: AAPL r=-0.0196, PnL=$-81.46
[EXIT] 2017-05-17 00:00:00: PPL r=0.0042, PnL=$9.54
[EXIT] 2017-05-17 00:00:00: MDT r=-0.0028, PnL=$-3.54

Simulating Trading Days:  26%|██▌       | 26/100 [10:47<01:26,  1.17s/it]

[SIM] 2017-05-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-1 (expected=0.0021, p_up=0.717)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0063, p_up=0.717)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0046, p_up=0.584)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0091, p_up=0.965)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0036, p_up=0.495)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0059, p_up=0.595)
[PORT] Sector Technology: sampled T from top-3 (expected=0.0027, p_up=0.991)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0024, p_up=0.588)
[SIM] 2017-05-17 00:00:00: 8 trades proposed.
[TRADE] 2017-05-17 00:00:00: allocated $4582.84 to T exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $4361.48 to CELG exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $2054.54 to MO exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $2036.11 to SNP exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $1077.56 to AMZN exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $660.66 to PPL exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $1002.46 to V exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $309.31 to LMT exiting on 2017-05-24 00:00:00
[EXIT] 2017-05-18 00:00:00: BA r=-0.0356, PnL=$-143.50
[EXIT] 2017-05-18 00:00:00: PCLN r=-0.0097, PnL=$-26.04
[EXIT] 2017-05-18 00:00:00: MA r=-0.0025, PnL=$-5.53
[EXIT] 2017-05-18 00:00:00: CHL r=0.0051, PnL=$11.79
[EXIT] 2017-05-18 00:00:00: CELG r=-0.0177, PnL=$-37.30
[EXIT] 2017-05-18 00:00:00: SO r=0.0000, PnL=$0.00
[EXIT] 2017-05-18 00:00:00: SNP r=0.0035, PnL=$4.10
[EXIT] 2017-05-18 00:00:00: UN r=0.0083, PnL=$9.42

Simulating Trading Days:  27%|██▋       | 27/100 [10:48<01:27,  1.19s/it]

[SIM] 2017-05-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0002, p_up=0.594)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.940)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0045, p_up=0.574)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.975)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0083, p_up=0.990)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.600)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0049, p_up=0.629)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0022, p_up=0.503)
[SIM] 2017-05-18 00:00:00: 8 trades proposed.
[TRADE] 2017-05-18 00:00:00: allocated $4644.93 to GD exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $4518.22 to CELG exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $4204.01 to AAPL exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $1551.33 to CHL exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $1339.30 to CHTR exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $931.55 to CVX exiting on 2017-05-25 00:00:00
[EXIT] 2017-05-19 00:00:00: VZ r=-0.0092, PnL=$-44.71
[EXIT] 2017-05-19 00:00:00: BA r=-0.0136, PnL=$-54.38
[EXIT] 2017-05-19 00:00:00: BABA r=0.0239, PnL=$96.84
[EXIT] 2017-05-19 00:00:00: MO r=0.0035, PnL=$12.20
[EXIT] 2017-05-19 00:00:00: MA r=0.0038, PnL=$8.83
[EXIT] 2017-05-19 00:00:00: SNP r=0.0065, PnL=$8.19
[EXIT] 2017-05-19 00:00:00: MRK r=0.0033, PnL=$2.79

Simulating Trading Days:  28%|██▊       | 28/100 [10:50<01:27,  1.22s/it]

[SIM] 2017-05-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0006, p_up=0.647)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0024, p_up=0.619)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.799)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0044, p_up=0.914)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.887)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.921)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0048, p_up=0.603)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0030, p_up=0.675)
[SIM] 2017-05-19 00:00:00: 8 trades proposed.
[TRADE] 2017-05-19 00:00:00: allocated $4373.90 to BABA exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $4252.98 to MDT exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $3952.88 to BA exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $3026.23 to MA exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $1769.07 to SO exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $1533.18 to CVX exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $1253.28 to UN exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $709.21 to CHL exiting on 2017-05-26 00:00:00
[EXIT] 2017-05-22 00:00:00: GD r=0.0132, PnL=$54.80
[EXIT] 2017-05-22 00:00:00: T r=-0.0088, PnL=$-36.34
[EXIT] 2017-05-22 00:00:00: BABA r=0.0276, PnL=$96.27
[EXIT] 2017-05-22 00:00:00: MDT r=-0.0018, PnL=$-1.29

Simulating Trading Days:  29%|██▉       | 29/100 [10:51<01:24,  1.19s/it]

[SIM] 2017-05-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0019, p_up=0.704)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0051, p_up=0.611)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0043, p_up=0.553)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0021, p_up=0.827)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0037, p_up=0.498)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.617)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0048, p_up=0.580)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0031, p_up=0.694)
[SIM] 2017-05-22 00:00:00: 8 trades proposed.
[TRADE] 2017-05-22 00:00:00: allocated $2686.46 to SNY exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $1751.32 to SNP exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $1636.57 to SO exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $1340.98 to CHTR exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $969.27 to MO exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $1017.22 to CHL exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $683.26 to V exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $304.67 to LMT exiting on 2017-05-30 00:00:00
[EXIT] 2017-05-23 00:00:00: GD r=0.0206, PnL=$68.18
[EXIT] 2017-05-23 00:00:00: AAPL r=-0.0107, PnL=$-3.38

Simulating Trading Days:  30%|███       | 30/100 [10:52<01:21,  1.16s/it]

[SIM] 2017-05-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0012, p_up=0.754)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0048, p_up=0.581)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.806)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0022, p_up=0.857)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0037, p_up=0.857)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.920)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0052, p_up=0.621)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0020, p_up=0.493)
[SIM] 2017-05-23 00:00:00: 8 trades proposed.
[TRADE] 2017-05-23 00:00:00: allocated $3083.88 to BABA exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $2500.30 to SNY exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $269.89 to ABB exiting on 2017-05-31 00:00:00
[EXIT] 2017-05-24 00:00:00: T r=0.0184, PnL=$84.41
[EXIT] 2017-05-24 00:00:00: CELG r=0.0056, PnL=$24.21
[EXIT] 2017-05-24 00:00:00: MO r=0.0326, PnL=$66.98
[EXIT] 2017-05-24 00:00:00: SNP r=0.0060, PnL=$12.15
[EXIT] 2017-05-24 00:00:00: AMZN r=0.0377, PnL=$40.59
[EXIT] 2017-05-24 00:00:00: PPL r=0.0227, PnL=$15.03
[EXIT] 2017-05-24 00:00:00: V r=0.0332, PnL=$33.32
[EXIT] 2017-05-24 00:00:00: LMT r=0.0402, PnL=$12.42

Simulating Trading Days:  31%|███       | 31/100 [10:53<01:23,  1.21s/it]

[SIM] 2017-05-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0015, p_up=0.808)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.945)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.822)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0023, p_up=0.867)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.891)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0069, p_up=0.661)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0066, p_up=0.681)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0032, p_up=0.697)
[SIM] 2017-05-24 00:00:00: 8 trades proposed.
[TRADE] 2017-05-24 00:00:00: allocated $4177.21 to AAPL exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $3645.64 to BA exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $3326.84 to SNY exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $2981.55 to MA exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $2156.09 to CVX exiting on 2017-06-01 00:00:00
[EXIT] 2017-05-25 00:00:00: GD r=0.0439, PnL=$203.75
[EXIT] 2017-05-25 00:00:00: CELG r=-0.0056, PnL=$-25.40
[EXIT] 2017-05-25 00:00:00: AAPL r=0.0087, PnL=$36.65
[EXIT] 2017-05-25 00:00:00: CHL r=0.0169, PnL=$26.29
[EXIT] 2017-05-25 00:00:00: CHTR r=0.0566, PnL=$75.81
[EXIT] 2017-05-25 00:00:00: CVX r=-0.0006, PnL=$-0.53

Simulating Trading Days:  32%|███▏      | 32/100 [10:54<01:22,  1.21s/it]

[SIM] 2017-05-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0008, p_up=0.611)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0075, p_up=0.947)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.818)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0023, p_up=0.869)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0039, p_up=0.867)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0069, p_up=0.661)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0068, p_up=0.972)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0033, p_up=0.704)
[SIM] 2017-05-25 00:00:00: 8 trades proposed.
[TRADE] 2017-05-25 00:00:00: allocated $4497.58 to VZ exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $4302.71 to AAPL exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $3459.35 to ABB exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $3022.04 to MA exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $1822.12 to PPL exiting on 2017-06-02 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $307.14 to AMZN exiting on 2017-06-02 00:00:00
[EXIT] 2017-05-26 00:00:00: BABA r=0.0062, PnL=$27.33
[EXIT] 2017-05-26 00:00:00: MDT r=0.0223, PnL=$95.04
[EXIT] 2017-05-26 00:00:00: BA r=0.0323, PnL=$127.49
[EXIT] 2017-05-26 00:00:00: MA r=0.0344, PnL=$104.24
[EXIT] 2017-05-26 00:00:00: SO r=0.0114, PnL=$20.22
[EXIT] 2017-05-26 00:00:00: CVX r=-0.0169, PnL=$-25.91
[EXIT] 2017-05-26 00:00:00: UN r=0.0271, PnL=$33.98
[EXIT] 2017-05-26 00:00:00: CHL r=0.0029, PnL=$2.05

Simulating Trading Days:  33%|███▎      | 33/100 [10:56<01:20,  1.20s/it]

[SIM] 2017-05-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-2 (expected=0.0018, p_up=0.853)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0025, p_up=0.630)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.802)
[PORT] Sector Healthcare: sampled AMGN from top-3 (expected=0.0025, p_up=0.528)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0039, p_up=0.879)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0070, p_up=0.663)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0071, p_up=0.982)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0021, p_up=0.498)
[SIM] 2017-05-26 00:00:00: 8 trades proposed.
[TRADE] 2017-05-26 00:00:00: allocated $4964.86 to VZ exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $3928.67 to BA exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $3662.99 to CVX exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $3058.73 to C exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $1868.92 to AMZN exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $1379.42 to UN exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $474.78 to AMGN exiting on 2017-06-05 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $222.51 to PCG exiting on 2017-06-05 00:00:00
[EXIT] 2017-05-30 00:00:00: SNY r=-0.0020, PnL=$-5.46
[EXIT] 2017-05-30 00:00:00: SNP r=0.0103, PnL=$18.08
[EXIT] 2017-05-30 00:00:00: SO r=0.0112, PnL=$18.33
[EXIT] 2017-05-30 00:00:00: CHTR r=0.0711, PnL=$95.35
[EXIT] 2017-05-30 00:00:00: MO r=0.0421, PnL=$40.77
[EXIT] 2017-05-30 00:00:00: CHL r=-0.0023, PnL=$-2.37
[EXIT] 2017-05-30 00:00:00: V r=0.0151, PnL=$10.32
[EXIT] 2017-05-30 00:00:00: LMT r=0.0110, PnL=$3.37

Simulating Trading Days:  34%|███▍      | 34/100 [10:57<01:17,  1.18s/it]

[SIM] 2017-05-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0004, p_up=0.576)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0053, p_up=0.627)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.810)
[PORT] Sector Healthcare: sampled AMGN from top-3 (expected=0.0027, p_up=0.538)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.995)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.901)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0091, p_up=0.794)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0027, p_up=0.637)
[SIM] 2017-05-30 00:00:00: 8 trades proposed.
[TRADE] 2017-05-30 00:00:00: allocated $4223.90 to GD exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $3498.46 to BABA exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $2592.82 to C exiting on 2017-06-06 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $1778.40 to INTC exiting on 2017-06-06 00:00:00
[EXIT] 2017-05-31 00:00:00: BABA r=-0.0038, PnL=$-11.79
[EXIT] 2017-05-31 00:00:00: SNY r=0.0106, PnL=$26.50
[EXIT] 2017-05-31 00:00:00: ABB r=0.0113, PnL=$3.04

Simulating Trading Days:  35%|███▌      | 35/100 [10:58<01:18,  1.20s/it]

[SIM] 2017-05-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0014, p_up=0.776)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0054, p_up=0.634)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.805)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.862)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0043, p_up=0.894)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0092, p_up=0.896)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0090, p_up=0.788)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0021, p_up=0.495)
[SIM] 2017-05-31 00:00:00: 8 trades proposed.
[TRADE] 2017-05-31 00:00:00: allocated $2961.84 to BABA exiting on 2017-06-07 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $2837.36 to ABB exiting on 2017-06-07 00:00:00
[EXIT] 2017-06-01 00:00:00: AAPL r=-0.0010, PnL=$-4.36
[EXIT] 2017-06-01 00:00:00: BA r=0.0112, PnL=$40.74
[EXIT] 2017-06-01 00:00:00: SNY r=0.0026, PnL=$8.80
[EXIT] 2017-06-01 00:00:00: MA r=0.0224, PnL=$66.70
[EXIT] 2017-06-01 00:00:00: CVX r=-0.0184, PnL=$-39.58

Simulating Trading Days:  36%|███▌      | 36/100 [10:59<01:19,  1.25s/it]

[SIM] 2017-06-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0004, p_up=0.681)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.954)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.796)
[PORT] Sector Healthcare: sampled AMGN from top-3 (expected=0.0028, p_up=0.547)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.995)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0065, p_up=0.636)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0084, p_up=0.763)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0034, p_up=0.726)
[SIM] 2017-06-01 00:00:00: 8 trades proposed.
[TRADE] 2017-06-01 00:00:00: allocated $4655.17 to GD exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $4287.67 to AAPL exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $2765.15 to MA exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $2478.95 to INTC exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $2095.52 to SO exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $122.77 to SLB exiting on 2017-06-08 00:00:00
[EXIT] 2017-06-02 00:00:00: VZ r=0.0249, PnL=$112.17
[EXIT] 2017-06-02 00:00:00: AAPL r=0.0103, PnL=$44.18
[EXIT] 2017-06-02 00:00:00: ABB r=0.0291, PnL=$100.73
[EXIT] 2017-06-02 00:00:00: MA r=0.0269, PnL=$81.30
[EXIT] 2017-06-02 00:00:00: PPL r=0.0040, PnL=$7.31
[EXIT] 2017-06-02 00:00:00: AMZN r=0.0134, PnL=$4.13

Simulating Trading Days:  37%|███▋      | 37/100 [11:01<01:19,  1.26s/it]

[SIM] 2017-06-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0007, p_up=0.713)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0056, p_up=0.656)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.784)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0057, p_up=0.876)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0037, p_up=0.504)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0062, p_up=0.616)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0074, p_up=0.989)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0020, p_up=0.694)
[SIM] 2017-06-02 00:00:00: 8 trades proposed.
[TRADE] 2017-06-02 00:00:00: allocated $4723.57 to VZ exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $3642.58 to ABBV exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $2726.16 to MA exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $2064.07 to SLB exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $1800.99 to D exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $1558.22 to MO exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $1140.23 to AMZN exiting on 2017-06-09 00:00:00
[EXIT] 2017-06-05 00:00:00: VZ r=0.0232, PnL=$115.03
[EXIT] 2017-06-05 00:00:00: BA r=0.0126, PnL=$49.69
[EXIT] 2017-06-05 00:00:00: CVX r=-0.0146, PnL=$-53.52
[EXIT] 2017-06-05 00:00:00: C r=-0.0132, PnL=$-40.41
[EXIT] 2017-06-05 00:00:00: AMZN r=0.0156, PnL=$29.20
[EXIT] 2017-06-05 00:00:00: UN r=0.0204, PnL=$28.10
[EXIT] 2017-06-05 00:00:00: AMGN r=0.0336, PnL=$15.96
[EXIT] 2017-06-05 00:00:00: PCG r=0.0200, PnL=$4.46

Simulating Trading Days:  38%|███▊      | 38/100 [11:02<01:15,  1.22s/it]

[SIM] 2017-06-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0008, p_up=0.727)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0057, p_up=0.666)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0037, p_up=0.489)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0087, p_up=0.748)
[PORT] Sector Industrial Goods: sampled LMT from top-3 (expected=0.0038, p_up=0.509)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.625)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0070, p_up=0.518)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0030, p_up=0.825)
[SIM] 2017-06-05 00:00:00: 8 trades proposed.
[TRADE] 2017-06-05 00:00:00: allocated $3227.42 to D exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $2715.82 to CELG exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $2297.03 to SLB exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $1719.07 to MO exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $1679.36 to CHTR exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $510.79 to FB exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $484.06 to LMT exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $185.74 to V exiting on 2017-06-12 00:00:00
[EXIT] 2017-06-06 00:00:00: GD r=-0.0177, PnL=$-74.65
[EXIT] 2017-06-06 00:00:00: BABA r=0.0057, PnL=$20.05
[EXIT] 2017-06-06 00:00:00: C r=-0.0102, PnL=$-26.50
[EXIT] 2017-06-06 00:00:00: INTC r=-0.0014, PnL=$-2.46

Simulating Trading Days:  39%|███▉      | 39/100 [11:03<01:12,  1.19s/it]

[SIM] 2017-06-06 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0007, p_up=0.720)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.955)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0038, p_up=0.496)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0078, p_up=0.653)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0049, p_up=0.929)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0056, p_up=0.572)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0073, p_up=0.986)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0023, p_up=0.515)
[SIM] 2017-06-06 00:00:00: 8 trades proposed.
[TRADE] 2017-06-06 00:00:00: allocated $4810.57 to VZ exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $4541.36 to AAPL exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $4224.93 to ABB exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $1801.24 to CELG exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $932.58 to AMZN exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $385.54 to PCG exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $249.88 to V exiting on 2017-06-13 00:00:00
[EXIT] 2017-06-07 00:00:00: BABA r=0.0260, PnL=$76.91
[EXIT] 2017-06-07 00:00:00: ABB r=0.0068, PnL=$19.19

Simulating Trading Days:  40%|████      | 40/100 [11:04<01:11,  1.19s/it]

[SIM] 2017-06-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0002, p_up=0.553)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0063, p_up=0.724)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.744)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0075, p_up=0.621)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0091, p_up=0.857)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0048, p_up=0.572)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0042, p_up=0.954)
[SIM] 2017-06-07 00:00:00: 8 trades proposed.
[TRADE] 2017-06-07 00:00:00: allocated $3818.06 to GD exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $3490.78 to D exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $492.18 to BABA exiting on 2017-06-14 00:00:00
[EXIT] 2017-06-08 00:00:00: GD r=-0.0142, PnL=$-66.20
[EXIT] 2017-06-08 00:00:00: AAPL r=0.0118, PnL=$50.66
[EXIT] 2017-06-08 00:00:00: MA r=0.0110, PnL=$30.47
[EXIT] 2017-06-08 00:00:00: INTC r=0.0100, PnL=$24.71
[EXIT] 2017-06-08 00:00:00: SO r=-0.0037, PnL=$-7.82
[EXIT] 2017-06-08 00:00:00: SLB r=-0.0211, PnL=$-2.59

Simulating Trading Days:  41%|████      | 41/100 [11:06<01:17,  1.31s/it]

[SIM] 2017-06-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0005, p_up=0.636)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.505)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0022, p_up=0.845)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0051, p_up=0.938)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0054, p_up=0.557)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.506)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0043, p_up=0.835)
[SIM] 2017-06-08 00:00:00: 8 trades proposed.
[TRADE] 2017-06-08 00:00:00: allocated $4321.25 to AAPL exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $4102.86 to ABB exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $3150.91 to SNY exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $3138.74 to SO exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $1319.51 to CVX exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $392.43 to AMZN exiting on 2017-06-15 00:00:00
[EXIT] 2017-06-09 00:00:00: VZ r=0.0060, PnL=$28.48
[EXIT] 2017-06-09 00:00:00: ABBV r=0.0360, PnL=$131.08
[EXIT] 2017-06-09 00:00:00: MA r=-0.0173, PnL=$-47.03
[EXIT] 2017-06-09 00:00:00: SLB r=0.0104, PnL=$21.55
[EXIT] 2017-06-09 00:00:00: D r=-0.0236, PnL=$-42.58
[EXIT] 2017-06-09 00:00:00: MO r=0.0045, PnL=$7.05
[EXIT] 2017-06-09 00:00:00: AMZN r=-0.0282, PnL=$-32.19

Simulating Trading Days:  42%|████▏     | 42/100 [11:07<01:15,  1.31s/it]

[SIM] 2017-06-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0004, p_up=0.571)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.955)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.733)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0089, p_up=0.782)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0051, p_up=0.940)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0055, p_up=0.565)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.503)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0043, p_up=0.960)
[SIM] 2017-06-09 00:00:00: 8 trades proposed.
[TRADE] 2017-06-09 00:00:00: allocated $4442.34 to D exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $4437.25 to AAPL exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $4233.65 to ABB exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $2907.81 to CELG exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $1681.20 to MA exiting on 2017-06-16 00:00:00
[EXIT] 2017-06-12 00:00:00: D r=-0.0151, PnL=$-48.80
[EXIT] 2017-06-12 00:00:00: CELG r=0.0106, PnL=$28.74
[EXIT] 2017-06-12 00:00:00: SLB r=0.0006, PnL=$1.33
[EXIT] 2017-06-12 00:00:00: MO r=0.0045, PnL=$7.79
[EXIT] 2017-06-12 00:00:00: CHTR r=-0.0168, PnL=$-28.18
[EXIT] 2017-06-12 00:00:00: FB r=-0.0338, PnL=$-17.26
[EXIT] 2017-06-12 00:00:00: LMT r=-0.0116, PnL=$-5.60
[EXIT] 2017-06-12 00:00:00: V r=-0.0316, PnL=$-5.87

Simulating Trading Days:  43%|████▎     | 43/100 [11:08<01:11,  1.26s/it]

[SIM] 2017-06-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0004, p_up=0.574)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0074, p_up=0.817)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.998)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0066, p_up=0.904)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.812)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0059, p_up=0.941)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0043, p_up=0.840)
[SIM] 2017-06-12 00:00:00: 8 trades proposed.
[TRADE] 2017-06-12 00:00:00: allocated $4329.77 to BRK-A exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $4312.76 to GD exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $3814.74 to VZ exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $314.52 to ABBV exiting on 2017-06-19 00:00:00
[EXIT] 2017-06-13 00:00:00: VZ r=0.0004, PnL=$2.07
[EXIT] 2017-06-13 00:00:00: AAPL r=-0.0509, PnL=$-231.11
[EXIT] 2017-06-13 00:00:00: ABB r=-0.0078, PnL=$-33.08
[EXIT] 2017-06-13 00:00:00: CELG r=0.0234, PnL=$42.23
[EXIT] 2017-06-13 00:00:00: AMZN r=-0.0221, PnL=$-20.65
[EXIT] 2017-06-13 00:00:00: PCG r=-0.0178, PnL=$-6.85
[EXIT] 2017-06-13 00:00:00: V r=-0.0074, PnL=$-1.85

Simulating Trading Days:  44%|████▍     | 44/100 [11:09<01:10,  1.25s/it]

[SIM] 2017-06-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0004, p_up=0.570)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0032, p_up=0.703)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.744)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.867)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0050, p_up=0.934)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0061, p_up=0.607)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0056, p_up=0.927)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0034, p_up=0.607)
[SIM] 2017-06-13 00:00:00: 8 trades proposed.
[TRADE] 2017-06-13 00:00:00: allocated $4090.36 to ABB exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $4011.44 to VZ exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $3582.99 to CELG exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $2296.68 to MA exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $1950.70 to UN exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $839.46 to AMZN exiting on 2017-06-20 00:00:00
[EXIT] 2017-06-14 00:00:00: GD r=0.0121, PnL=$46.27
[EXIT] 2017-06-14 00:00:00: D r=-0.0058, PnL=$-20.39
[EXIT] 2017-06-14 00:00:00: BABA r=0.0878, PnL=$43.21

Simulating Trading Days:  45%|████▌     | 45/100 [11:10<01:07,  1.22s/it]

[SIM] 2017-06-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0003, p_up=0.709)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0035, p_up=0.892)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0021, p_up=0.727)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.895)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.803)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0072, p_up=0.492)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0042, p_up=0.825)
[SIM] 2017-06-14 00:00:00: 8 trades proposed.
[TRADE] 2017-06-14 00:00:00: allocated $3818.92 to GD exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $3107.29 to CELG exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $923.17 to PG exiting on 2017-06-21 00:00:00
[EXIT] 2017-06-15 00:00:00: AAPL r=-0.0690, PnL=$-298.32
[EXIT] 2017-06-15 00:00:00: ABB r=-0.0170, PnL=$-69.62
[EXIT] 2017-06-15 00:00:00: SNY r=-0.0069, PnL=$-21.62
[EXIT] 2017-06-15 00:00:00: SO r=0.0191, PnL=$60.00
[EXIT] 2017-06-15 00:00:00: CVX r=0.0224, PnL=$29.56
[EXIT] 2017-06-15 00:00:00: AMZN r=-0.0456, PnL=$-17.91

Simulating Trading Days:  46%|████▌     | 46/100 [11:12<01:04,  1.19s/it]

[SIM] 2017-06-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0004, p_up=0.575)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0077, p_up=0.848)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0043, p_up=0.551)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0036, p_up=0.714)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0050, p_up=0.541)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0072, p_up=0.489)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0040, p_up=0.809)
[SIM] 2017-06-15 00:00:00: 8 trades proposed.
[TRADE] 2017-06-15 00:00:00: allocated $4637.98 to GD exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $3271.31 to MO exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $2864.06 to SO exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $2092.15 to MDT exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $788.70 to PTR exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $715.94 to V exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $855.91 to CHTR exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $209.19 to FB exiting on 2017-06-22 00:00:00
[EXIT] 2017-06-16 00:00:00: D r=0.0180, PnL=$80.13
[EXIT] 2017-06-16 00:00:00: AAPL r=-0.0450, PnL=$-199.85
[EXIT] 2017-06-16 00:00:00: ABB r=0.0004, PnL=$1.67
[EXIT] 2017-06-16 00:00:00: CELG r=0.0353, PnL=$102.59
[EXIT] 2017-06-16 00:00:00: MA r=-0.0088, PnL=$-14.76

Simulating Trading Days:  47%|████▋     | 47/100 [11:13<01:02,  1.17s/it]

[SIM] 2017-06-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0002, p_up=0.700)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.998)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0044, p_up=0.815)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0041, p_up=0.893)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0089, p_up=0.791)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0072, p_up=0.487)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0034, p_up=0.720)
[SIM] 2017-06-16 00:00:00: 8 trades proposed.
[TRADE] 2017-06-16 00:00:00: allocated $4884.27 to BRK-A exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $4491.85 to AAPL exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $3864.25 to BA exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $3109.43 to ABBV exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $2099.22 to BABA exiting on 2017-06-23 00:00:00
[EXIT] 2017-06-19 00:00:00: BRK-A r=0.0055, PnL=$24.03
[EXIT] 2017-06-19 00:00:00: GD r=0.0308, PnL=$133.04
[EXIT] 2017-06-19 00:00:00: VZ r=-0.0131, PnL=$-50.12
[EXIT] 2017-06-19 00:00:00: ABBV r=0.0260, PnL=$8.19

Simulating Trading Days:  48%|████▊     | 48/100 [11:14<01:01,  1.18s/it]

[SIM] 2017-06-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-1 (expected=0.0007, p_up=0.590)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0040, p_up=0.941)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.777)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.969)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0041, p_up=0.899)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0088, p_up=0.777)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0052, p_up=0.909)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0034, p_up=0.717)
[SIM] 2017-06-19 00:00:00: 8 trades proposed.
[TRADE] 2017-06-19 00:00:00: allocated $4097.58 to CELG exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $3834.22 to PG exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $3514.00 to VZ exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $1406.57 to BA exiting on 2017-06-26 00:00:00
[EXIT] 2017-06-20 00:00:00: ABB r=-0.0114, PnL=$-46.81
[EXIT] 2017-06-20 00:00:00: VZ r=-0.0112, PnL=$-44.90
[EXIT] 2017-06-20 00:00:00: CELG r=0.0552, PnL=$197.69
[EXIT] 2017-06-20 00:00:00: MA r=0.0050, PnL=$11.45
[EXIT] 2017-06-20 00:00:00: UN r=0.0040, PnL=$7.75
[EXIT] 2017-06-20 00:00:00: AMZN r=0.0120, PnL=$10.10

Simulating Trading Days:  49%|████▉     | 49/100 [11:15<00:59,  1.17s/it]

[SIM] 2017-06-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-2 (expected=0.0008, p_up=0.595)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0041, p_up=0.948)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.998)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.975)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0041, p_up=0.901)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0087, p_up=0.757)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0052, p_up=0.909)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0042, p_up=0.670)
[SIM] 2017-06-20 00:00:00: 8 trades proposed.
[TRADE] 2017-06-20 00:00:00: allocated $4727.98 to BRK-A exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $4534.21 to CELG exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $4266.48 to PG exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $3337.65 to VZ exiting on 2017-06-27 00:00:00
[EXIT] 2017-06-21 00:00:00: GD r=0.0130, PnL=$49.52
[EXIT] 2017-06-21 00:00:00: CELG r=0.0974, PnL=$302.67
[EXIT] 2017-06-21 00:00:00: PG r=0.0109, PnL=$10.02

Simulating Trading Days:  50%|█████     | 50/100 [11:16<00:57,  1.16s/it]

[SIM] 2017-06-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0004, p_up=0.573)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0039, p_up=0.514)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0032, p_up=0.761)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.994)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0096, p_up=0.821)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0053, p_up=0.788)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0022, p_up=0.582)
[SIM] 2017-06-21 00:00:00: 8 trades proposed.
[TRADE] 2017-06-21 00:00:00: allocated $3839.85 to GD exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $3561.82 to AAPL exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $701.25 to AMZN exiting on 2017-06-28 00:00:00
[EXIT] 2017-06-22 00:00:00: GD r=-0.0038, PnL=$-17.68
[EXIT] 2017-06-22 00:00:00: MO r=0.0009, PnL=$3.00
[EXIT] 2017-06-22 00:00:00: SO r=-0.0257, PnL=$-73.66
[EXIT] 2017-06-22 00:00:00: MDT r=0.0163, PnL=$34.13
[EXIT] 2017-06-22 00:00:00: PTR r=-0.0181, PnL=$-14.24
[EXIT] 2017-06-22 00:00:00: V r=-0.0023, PnL=$-1.67
[EXIT] 2017-06-22 00:00:00: CHTR r=-0.0124, PnL=$-10.65
[EXIT] 2017-06-22 00:00:00: FB r=0.0240, PnL=$5.03

Simulating Trading Days:  51%|█████     | 51/100 [11:17<00:56,  1.15s/it]

[SIM] 2017-06-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0007, p_up=0.600)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.777)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0090, p_up=0.972)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.993)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0085, p_up=0.694)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0054, p_up=0.794)
[PORT] Sector Utilities: sampled SRE from top-3 (expected=0.0016, p_up=0.584)
[SIM] 2017-06-22 00:00:00: 8 trades proposed.
[TRADE] 2017-06-22 00:00:00: allocated $4551.30 to GD exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $4372.17 to CELG exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $4225.56 to AAPL exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $2233.19 to CHL exiting on 2017-06-29 00:00:00
[EXIT] 2017-06-23 00:00:00: BRK-A r=-0.0181, PnL=$-88.56
[EXIT] 2017-06-23 00:00:00: AAPL r=0.0282, PnL=$126.61
[EXIT] 2017-06-23 00:00:00: BA r=0.0295, PnL=$113.90
[EXIT] 2017-06-23 00:00:00: ABBV r=0.0224, PnL=$69.58
[EXIT] 2017-06-23 00:00:00: BABA r=0.0604, PnL=$126.70

Simulating Trading Days:  52%|█████▏    | 52/100 [11:18<00:55,  1.15s/it]

[SIM] 2017-06-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0005, p_up=0.637)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.778)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0091, p_up=0.968)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0053, p_up=0.945)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0083, p_up=0.650)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0054, p_up=0.793)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0038, p_up=0.641)
[SIM] 2017-06-23 00:00:00: 8 trades proposed.
[TRADE] 2017-06-23 00:00:00: allocated $4533.48 to AAPL exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $4386.14 to ABB exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $3090.54 to CHL exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $2727.28 to MA exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $1905.91 to BABA exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $1582.04 to PCG exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $467.40 to CVX exiting on 2017-06-30 00:00:00
[EXIT] 2017-06-26 00:00:00: CELG r=0.0694, PnL=$284.50
[EXIT] 2017-06-26 00:00:00: PG r=-0.0056, PnL=$-21.33
[EXIT] 2017-06-26 00:00:00: VZ r=-0.0176, PnL=$-61.87
[EXIT] 2017-06-26 00:00:00: BA r=0.0045, PnL=$6.36

Simulating Trading Days:  53%|█████▎    | 53/100 [11:20<00:54,  1.15s/it]

[SIM] 2017-06-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0016, p_up=0.679)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.955)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.785)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0038, p_up=0.782)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0096, p_up=0.818)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0068, p_up=0.569)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0037, p_up=0.628)
[SIM] 2017-06-26 00:00:00: 8 trades proposed.
[TRADE] 2017-06-26 00:00:00: allocated $4323.21 to GD exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $2859.43 to AMZN exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $2464.98 to C exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $2533.40 to MDT exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $816.70 to SNP exiting on 2017-07-03 00:00:00
[EXIT] 2017-06-27 00:00:00: BRK-A r=-0.0178, PnL=$-84.08
[EXIT] 2017-06-27 00:00:00: CELG r=0.0367, PnL=$166.32
[EXIT] 2017-06-27 00:00:00: PG r=-0.0114, PnL=$-48.55
[EXIT] 2017-06-27 00:00:00: VZ r=-0.0239, PnL=$-79.92

Simulating Trading Days:  54%|█████▍    | 54/100 [11:21<00:52,  1.15s/it]

[SIM] 2017-06-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0007, p_up=0.591)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0064, p_up=0.729)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0036, p_up=0.483)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.943)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0041, p_up=0.896)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0092, p_up=0.797)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0114, p_up=0.895)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0005, p_up=0.628)
[SIM] 2017-06-27 00:00:00: 8 trades proposed.
[TRADE] 2017-06-27 00:00:00: allocated $4271.90 to CELG exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $3792.78 to BA exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $3768.35 to INTC exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $2928.32 to AMZN exiting on 2017-07-05 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $2072.61 to MO exiting on 2017-07-05 00:00:00
[EXIT] 2017-06-28 00:00:00: GD r=-0.0150, PnL=$-57.63
[EXIT] 2017-06-28 00:00:00: AAPL r=-0.0003, PnL=$-0.98
[EXIT] 2017-06-28 00:00:00: AMZN r=-0.0119, PnL=$-8.33

Simulating Trading Days:  55%|█████▌    | 55/100 [11:22<00:51,  1.15s/it]

[SIM] 2017-06-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0009, p_up=0.763)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0042, p_up=0.803)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0021, p_up=0.995)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.891)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0083, p_up=0.992)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0051, p_up=0.569)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0068, p_up=0.575)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0010, p_up=0.532)
[SIM] 2017-06-28 00:00:00: 8 trades proposed.
[TRADE] 2017-06-28 00:00:00: allocated $3853.74 to BRK-A exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $3828.64 to GD exiting on 2017-07-06 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $373.69 to CELG exiting on 2017-07-06 00:00:00
[EXIT] 2017-06-29 00:00:00: GD r=-0.0214, PnL=$-97.24
[EXIT] 2017-06-29 00:00:00: CELG r=-0.0148, PnL=$-64.76
[EXIT] 2017-06-29 00:00:00: AAPL r=-0.0134, PnL=$-56.58
[EXIT] 2017-06-29 00:00:00: CHL r=-0.0166, PnL=$-37.09

Simulating Trading Days:  56%|█████▌    | 56/100 [11:23<00:50,  1.15s/it]

[SIM] 2017-06-29 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0011, p_up=0.779)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.516)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0050, p_up=0.598)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.875)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0040, p_up=0.823)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0083, p_up=0.992)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0079, p_up=0.723)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0114, p_up=0.894)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0010, p_up=0.524)
[SIM] 2017-06-29 00:00:00: 9 trades proposed.
[TRADE] 2017-06-29 00:00:00: allocated $4523.88 to GD exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $3629.61 to INTC exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $3425.52 to C exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $3022.27 to MDT exiting on 2017-07-07 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $601.96 to BBL exiting on 2017-07-07 00:00:00
[EXIT] 2017-06-30 00:00:00: AAPL r=-0.0154, PnL=$-70.04
[EXIT] 2017-06-30 00:00:00: ABB r=-0.0197, PnL=$-86.34
[EXIT] 2017-06-30 00:00:00: CHL r=-0.0097, PnL=$-29.98
[EXIT] 2017-06-30 00:00:00: MA r=-0.0206, PnL=$-56.30
[EXIT] 2017-06-30 00:00:00: BABA r=-0.0148, PnL=$-28.12
[EXIT] 2017-06-30 00:00:00: PCG r=-0.0244, PnL=$-38.60
[EXIT] 2017-06-30 00:00:00: CVX r=-0.0064, PnL=$-2.98

Simulating Trading Days:  57%|█████▋    | 57/100 [11:24<00:49,  1.15s/it]

[SIM] 2017-06-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0012, p_up=0.783)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.522)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.809)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.795)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0073, p_up=0.598)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0042, p_up=0.907)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0071, p_up=0.672)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0065, p_up=0.962)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0031, p_up=0.583)
[SIM] 2017-06-30 00:00:00: 9 trades proposed.
[TRADE] 2017-06-30 00:00:00: allocated $4520.32 to VZ exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $4010.13 to BA exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $3053.34 to UN exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $2884.66 to MA exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $2762.56 to BBL exiting on 2017-07-10 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $1243.13 to AMZN exiting on 2017-07-10 00:00:00
[EXIT] 2017-07-03 00:00:00: GD r=-0.0027, PnL=$-11.66
[EXIT] 2017-07-03 00:00:00: AMZN r=-0.0406, PnL=$-115.99
[EXIT] 2017-07-03 00:00:00: C r=0.0702, PnL=$173.14
[EXIT] 2017-07-03 00:00:00: MDT r=-0.0038, PnL=$-9.66
[EXIT] 2017-07-03 00:00:00: SNP r=-0.0158, PnL=$-12.87

Simulating Trading Days:  58%|█████▊    | 58/100 [11:25<00:48,  1.16s/it]

[SIM] 2017-07-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0010, p_up=0.772)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.530)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.811)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.797)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0022, p_up=0.510)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0065, p_up=0.633)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0067, p_up=0.582)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0031, p_up=0.577)
[SIM] 2017-07-03 00:00:00: 9 trades proposed.
[TRADE] 2017-07-03 00:00:00: allocated $4303.17 to GD exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $2732.50 to UN exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $2574.23 to MA exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $2362.97 to BBL exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $1040.94 to AMZN exiting on 2017-07-11 00:00:00
[EXIT] 2017-07-05 00:00:00: CELG r=0.0180, PnL=$76.72
[EXIT] 2017-07-05 00:00:00: BA r=0.0147, PnL=$55.68
[EXIT] 2017-07-05 00:00:00: INTC r=0.0205, PnL=$77.27
[EXIT] 2017-07-05 00:00:00: AMZN r=-0.0055, PnL=$-16.13
[EXIT] 2017-07-05 00:00:00: MO r=-0.0102, PnL=$-21.17

Simulating Trading Days:  59%|█████▉    | 59/100 [11:27<00:47,  1.16s/it]

[SIM] 2017-07-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0016, p_up=0.827)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.532)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.812)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.797)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0029, p_up=0.928)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0043, p_up=0.917)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0064, p_up=0.625)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0102, p_up=0.843)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.638)
[SIM] 2017-07-05 00:00:00: 9 trades proposed.
[TRADE] 2017-07-05 00:00:00: allocated $4101.41 to PFE exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $3986.92 to BA exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $3277.13 to INTC exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $3145.44 to CVX exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $2443.73 to UN exiting on 2017-07-12 00:00:00
[EXIT] 2017-07-06 00:00:00: BRK-A r=0.0035, PnL=$13.47
[EXIT] 2017-07-06 00:00:00: GD r=-0.0090, PnL=$-34.51
[EXIT] 2017-07-06 00:00:00: CELG r=-0.0170, PnL=$-6.35

Simulating Trading Days:  60%|██████    | 60/100 [11:28<00:46,  1.17s/it]

[SIM] 2017-07-06 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0005, p_up=0.583)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.536)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.811)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.797)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0040, p_up=0.830)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0051, p_up=0.935)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0064, p_up=0.625)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0072, p_up=0.985)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0029, p_up=0.565)
[SIM] 2017-07-06 00:00:00: 9 trades proposed.
[TRADE] 2017-07-06 00:00:00: allocated $3751.07 to VZ exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $3351.29 to ABB exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $934.55 to MDT exiting on 2017-07-13 00:00:00
[EXIT] 2017-07-07 00:00:00: GD r=0.0218, PnL=$98.76
[EXIT] 2017-07-07 00:00:00: INTC r=0.0101, PnL=$36.79
[EXIT] 2017-07-07 00:00:00: C r=0.0139, PnL=$47.56
[EXIT] 2017-07-07 00:00:00: MDT r=-0.0085, PnL=$-25.55
[EXIT] 2017-07-07 00:00:00: BBL r=0.0443, PnL=$26.68

Simulating Trading Days:  61%|██████    | 61/100 [11:29<00:45,  1.17s/it]

[SIM] 2017-07-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0005, p_up=0.579)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.538)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0042, p_up=0.807)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.793)
[PORT] Sector Healthcare: sampled MDT from top-3 (expected=0.0040, p_up=0.818)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0044, p_up=0.928)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.609)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0106, p_up=0.857)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.645)
[SIM] 2017-07-07 00:00:00: 9 trades proposed.
[TRADE] 2017-07-07 00:00:00: allocated $3951.80 to BA exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $3300.51 to INTC exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $2989.87 to MDT exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $2682.83 to MA exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $1051.85 to NGG exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $1355.37 to CHTR exiting on 2017-07-14 00:00:00
[EXIT] 2017-07-10 00:00:00: VZ r=-0.0327, PnL=$-147.78
[EXIT] 2017-07-10 00:00:00: BA r=0.0314, PnL=$125.93
[EXIT] 2017-07-10 00:00:00: UN r=-0.0014, PnL=$-4.42
[EXIT] 2017-07-10 00:00:00: MA r=0.0105, PnL=$30.40
[EXIT] 2017-07-10 00:00:00: BBL r=0.0592, PnL=$163.45
[EXIT] 2017-07-10 00:00:00: AMZN r=0.0294, PnL=$36.56

Simulating Trading Days:  62%|██████▏   | 62/100 [11:30<00:44,  1.17s/it]

[SIM] 2017-07-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled PTR from top-3 (expected=0.0003, p_up=0.571)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.538)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0038, p_up=0.917)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.831)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0030, p_up=0.920)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0045, p_up=0.931)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0030, p_up=0.710)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0106, p_up=0.861)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0028, p_up=0.557)
[SIM] 2017-07-10 00:00:00: 9 trades proposed.
[TRADE] 2017-07-10 00:00:00: allocated $4275.10 to BA exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $4182.74 to PFE exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $4137.09 to PG exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $3572.32 to INTC exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $2449.78 to C exiting on 2017-07-17 00:00:00
[EXIT] 2017-07-11 00:00:00: GD r=0.0013, PnL=$5.39
[EXIT] 2017-07-11 00:00:00: UN r=0.0096, PnL=$26.34
[EXIT] 2017-07-11 00:00:00: MA r=0.0286, PnL=$73.53
[EXIT] 2017-07-11 00:00:00: BBL r=0.0526, PnL=$124.41
[EXIT] 2017-07-11 00:00:00: AMZN r=0.0424, PnL=$44.17

Simulating Trading Days:  63%|██████▎   | 63/100 [11:31<00:42,  1.16s/it]

[SIM] 2017-07-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.982)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.536)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0037, p_up=0.909)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.771)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0031, p_up=0.893)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.993)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0030, p_up=0.708)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0067, p_up=0.588)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.666)
[SIM] 2017-07-11 00:00:00: 9 trades proposed.
[TRADE] 2017-07-11 00:00:00: allocated $4351.06 to GD exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $4252.61 to CVX exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $3620.35 to PG exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $981.48 to PFE exiting on 2017-07-18 00:00:00
[EXIT] 2017-07-12 00:00:00: PFE r=-0.0125, PnL=$-51.21
[EXIT] 2017-07-12 00:00:00: BA r=0.0229, PnL=$91.47
[EXIT] 2017-07-12 00:00:00: INTC r=-0.0026, PnL=$-8.59
[EXIT] 2017-07-12 00:00:00: CVX r=-0.0070, PnL=$-21.95
[EXIT] 2017-07-12 00:00:00: UN r=0.0199, PnL=$48.56

Simulating Trading Days:  64%|██████▍   | 64/100 [11:32<00:41,  1.16s/it]

[SIM] 2017-07-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0018, p_up=0.988)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.531)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0074, p_up=0.928)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.765)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0026, p_up=0.602)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0045, p_up=0.933)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0030, p_up=0.705)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0067, p_up=0.593)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0007, p_up=0.682)
[SIM] 2017-07-12 00:00:00: 9 trades proposed.
[TRADE] 2017-07-12 00:00:00: allocated $4680.75 to CVX exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $4161.48 to BA exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $4138.17 to AAPL exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $2518.52 to MA exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $1496.50 to PCLN exiting on 2017-07-19 00:00:00
[EXIT] 2017-07-13 00:00:00: VZ r=-0.0007, PnL=$-2.59
[EXIT] 2017-07-13 00:00:00: ABB r=0.0069, PnL=$22.96
[EXIT] 2017-07-13 00:00:00: MDT r=0.0063, PnL=$5.89

Simulating Trading Days:  65%|██████▌   | 65/100 [11:34<00:40,  1.16s/it]

[SIM] 2017-07-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0002, p_up=0.654)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.526)
[PORT] Sector Consumer Goods: sampled PG from top-3 (expected=0.0031, p_up=0.852)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.764)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0032, p_up=0.797)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0029, p_up=0.702)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0075, p_up=0.993)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0027, p_up=0.547)
[SIM] 2017-07-13 00:00:00: 9 trades proposed.
[TRADE] 2017-07-13 00:00:00: allocated $3840.35 to VZ exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $3844.28 to GD exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $370.66 to PG exiting on 2017-07-20 00:00:00
[EXIT] 2017-07-14 00:00:00: BA r=0.0303, PnL=$119.90
[EXIT] 2017-07-14 00:00:00: INTC r=0.0236, PnL=$77.93
[EXIT] 2017-07-14 00:00:00: MDT r=0.0069, PnL=$20.73
[EXIT] 2017-07-14 00:00:00: MA r=0.0394, PnL=$105.60
[EXIT] 2017-07-14 00:00:00: NGG r=0.0080, PnL=$8.43
[EXIT] 2017-07-14 00:00:00: CHTR r=0.0312, PnL=$42.28

Simulating Trading Days:  66%|██████▌   | 66/100 [11:35<00:39,  1.18s/it]

[SIM] 2017-07-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.972)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.525)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0073, p_up=0.922)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.766)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0028, p_up=0.661)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0049, p_up=0.927)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0029, p_up=0.701)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0075, p_up=0.993)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0008, p_up=0.743)
[SIM] 2017-07-14 00:00:00: 9 trades proposed.
[TRADE] 2017-07-14 00:00:00: allocated $4599.66 to VZ exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $4406.93 to CVX exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $3958.78 to ABB exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $2629.26 to AAPL exiting on 2017-07-21 00:00:00
[EXIT] 2017-07-17 00:00:00: BA r=0.0247, PnL=$105.64
[EXIT] 2017-07-17 00:00:00: PFE r=-0.0048, PnL=$-20.03
[EXIT] 2017-07-17 00:00:00: PG r=0.0053, PnL=$21.85
[EXIT] 2017-07-17 00:00:00: INTC r=0.0244, PnL=$87.05
[EXIT] 2017-07-17 00:00:00: C r=-0.0121, PnL=$-29.69

Simulating Trading Days:  67%|██████▋   | 67/100 [11:36<00:38,  1.17s/it]

[SIM] 2017-07-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0020, p_up=0.953)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.526)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0023, p_up=0.961)
[PORT] Sector Financial: sampled BRK-A from top-3 (expected=0.0023, p_up=0.970)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0032, p_up=0.719)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0029, p_up=0.702)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0076, p_up=0.994)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0008, p_up=0.762)
[SIM] 2017-07-17 00:00:00: 9 trades proposed.
[TRADE] 2017-07-17 00:00:00: allocated $4922.39 to VZ exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $4910.65 to GD exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $4711.17 to BRK-A exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $4188.20 to UL exiting on 2017-07-24 00:00:00
[EXIT] 2017-07-18 00:00:00: GD r=0.0076, PnL=$32.87
[EXIT] 2017-07-18 00:00:00: CVX r=0.0058, PnL=$24.74
[EXIT] 2017-07-18 00:00:00: PG r=0.0216, PnL=$78.02
[EXIT] 2017-07-18 00:00:00: PFE r=0.0057, PnL=$5.62

Simulating Trading Days:  68%|██████▊   | 68/100 [11:37<00:37,  1.17s/it]

[SIM] 2017-07-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0031, p_up=0.791)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.530)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0072, p_up=0.913)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.793)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0028, p_up=0.622)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.992)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.624)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0060, p_up=0.654)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0026, p_up=0.540)
[SIM] 2017-07-18 00:00:00: 9 trades proposed.
[TRADE] 2017-07-18 00:00:00: allocated $4379.63 to GD exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $3714.87 to AAPL exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $2583.88 to C exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $2593.87 to SNP exiting on 2017-07-25 00:00:00
[EXIT] 2017-07-19 00:00:00: CVX r=0.0055, PnL=$25.68
[EXIT] 2017-07-19 00:00:00: BA r=0.0215, PnL=$89.50
[EXIT] 2017-07-19 00:00:00: AAPL r=0.0362, PnL=$149.92
[EXIT] 2017-07-19 00:00:00: MA r=0.0220, PnL=$55.48
[EXIT] 2017-07-19 00:00:00: PCLN r=0.0236, PnL=$35.31

Simulating Trading Days:  69%|██████▉   | 69/100 [11:38<00:36,  1.16s/it]

[SIM] 2017-07-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0032, p_up=0.797)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.534)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0071, p_up=0.907)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.762)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0018, p_up=0.750)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0042, p_up=0.902)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0067, p_up=0.649)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0053, p_up=0.789)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0027, p_up=0.542)
[SIM] 2017-07-19 00:00:00: 9 trades proposed.
[TRADE] 2017-07-19 00:00:00: allocated $4002.00 to AAPL exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $3913.09 to BA exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $2893.89 to SNP exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $3001.06 to CHL exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $2524.12 to MA exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $942.53 to SNY exiting on 2017-07-26 00:00:00
[EXIT] 2017-07-20 00:00:00: VZ r=0.0168, PnL=$64.46
[EXIT] 2017-07-20 00:00:00: GD r=0.0112, PnL=$43.22
[EXIT] 2017-07-20 00:00:00: PG r=0.0219, PnL=$8.12

Simulating Trading Days:  70%|███████   | 70/100 [11:39<00:34,  1.16s/it]

[SIM] 2017-07-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0031, p_up=0.791)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.535)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0023, p_up=0.956)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.754)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0043, p_up=0.806)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0049, p_up=0.926)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0062, p_up=0.612)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0077, p_up=0.996)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0027, p_up=0.550)
[SIM] 2017-07-20 00:00:00: 9 trades proposed.
[TRADE] 2017-07-20 00:00:00: allocated $3913.26 to VZ exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $3588.12 to UL exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $634.97 to ABB exiting on 2017-07-27 00:00:00
[EXIT] 2017-07-21 00:00:00: VZ r=0.0154, PnL=$70.75
[EXIT] 2017-07-21 00:00:00: CVX r=-0.0114, PnL=$-50.21
[EXIT] 2017-07-21 00:00:00: ABB r=-0.0541, PnL=$-213.99
[EXIT] 2017-07-21 00:00:00: AAPL r=0.0083, PnL=$21.70

Simulating Trading Days:  71%|███████   | 71/100 [11:41<00:33,  1.16s/it]

[SIM] 2017-07-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0028, p_up=0.772)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.536)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0070, p_up=0.894)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.745)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0050, p_up=0.848)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.993)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0028, p_up=0.690)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0068, p_up=0.567)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0009, p_up=0.815)
[SIM] 2017-07-21 00:00:00: 9 trades proposed.
[TRADE] 2017-07-21 00:00:00: allocated $4610.13 to GD exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $3735.27 to AAPL exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $3265.72 to ABBV exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $2799.07 to NGG exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $1064.21 to SNP exiting on 2017-07-28 00:00:00
[EXIT] 2017-07-24 00:00:00: VZ r=0.0011, PnL=$5.64
[EXIT] 2017-07-24 00:00:00: GD r=0.0239, PnL=$117.53
[EXIT] 2017-07-24 00:00:00: BRK-A r=0.0058, PnL=$27.38
[EXIT] 2017-07-24 00:00:00: UL r=0.0118, PnL=$49.50

Simulating Trading Days:  72%|███████▏  | 72/100 [11:42<00:33,  1.20s/it]

[SIM] 2017-07-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0025, p_up=0.748)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.531)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0070, p_up=0.893)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0036, p_up=0.480)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0054, p_up=0.862)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.993)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0055, p_up=0.567)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0076, p_up=0.996)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0014, p_up=0.598)
[SIM] 2017-07-24 00:00:00: 9 trades proposed.
[TRADE] 2017-07-24 00:00:00: allocated $4978.58 to VZ exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $4955.10 to GD exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $3649.59 to ABBV exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $865.04 to D exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $875.73 to AMZN exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $300.52 to HRG exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $112.17 to V exiting on 2017-07-31 00:00:00
[EXIT] 2017-07-25 00:00:00: GD r=0.0106, PnL=$46.53
[EXIT] 2017-07-25 00:00:00: AAPL r=0.0177, PnL=$65.84
[EXIT] 2017-07-25 00:00:00: C r=0.0170, PnL=$44.04
[EXIT] 2017-07-25 00:00:00: SNP r=-0.0155, PnL=$-40.30

Simulating Trading Days:  73%|███████▎  | 73/100 [11:43<00:35,  1.30s/it]

[SIM] 2017-07-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0022, p_up=0.727)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.520)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0040, p_up=0.779)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.727)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0053, p_up=0.857)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0040, p_up=0.890)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.597)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0076, p_up=0.996)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0009, p_up=0.816)
[SIM] 2017-07-25 00:00:00: 9 trades proposed.
[TRADE] 2017-07-25 00:00:00: allocated $4738.49 to VZ exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $3737.64 to BA exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $3434.05 to ABBV exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $2873.13 to NGG exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $1705.92 to UN exiting on 2017-08-01 00:00:00
[EXIT] 2017-07-26 00:00:00: AAPL r=0.0162, PnL=$64.66
[EXIT] 2017-07-26 00:00:00: BA r=0.1070, PnL=$418.81
[EXIT] 2017-07-26 00:00:00: SNP r=-0.0104, PnL=$-29.98
[EXIT] 2017-07-26 00:00:00: CHL r=0.0103, PnL=$30.97
[EXIT] 2017-07-26 00:00:00: MA r=0.0230, PnL=$58.16
[EXIT] 2017-07-26 00:00:00: SNY r=0.0258, PnL=$24.36

Simulating Trading Days:  74%|███████▍  | 74/100 [11:45<00:33,  1.30s/it]

[SIM] 2017-07-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0005, p_up=0.691)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.512)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0071, p_up=0.899)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.727)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0009, p_up=0.604)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.994)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0056, p_up=0.573)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0070, p_up=0.530)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0031, p_up=0.837)
[SIM] 2017-07-26 00:00:00: 9 trades proposed.
[TRADE] 2017-07-26 00:00:00: allocated $4862.40 to GD exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $3976.10 to AAPL exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $3270.35 to D exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $2215.34 to MA exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $1891.61 to SLB exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $766.21 to SNY exiting on 2017-08-02 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $691.55 to AMZN exiting on 2017-08-02 00:00:00
[EXIT] 2017-07-27 00:00:00: VZ r=0.0812, PnL=$317.70
[EXIT] 2017-07-27 00:00:00: UL r=0.0039, PnL=$13.88
[EXIT] 2017-07-27 00:00:00: ABB r=-0.0426, PnL=$-27.08

Simulating Trading Days:  75%|███████▌  | 75/100 [11:46<00:32,  1.32s/it]

[SIM] 2017-07-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.875)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0071, p_up=0.903)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.860)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0012, p_up=0.646)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.994)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0058, p_up=0.583)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0070, p_up=0.521)
[PORT] Sector Utilities: sampled NGG from top-3 (expected=0.0009, p_up=0.806)
[SIM] 2017-07-27 00:00:00: 8 trades proposed.
[TRADE] 2017-07-27 00:00:00: allocated $3258.81 to AAPL exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $3006.30 to CVX exiting on 2017-08-03 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $2084.40 to C exiting on 2017-08-03 00:00:00
[EXIT] 2017-07-28 00:00:00: GD r=-0.0323, PnL=$-148.98
[EXIT] 2017-07-28 00:00:00: AAPL r=-0.0051, PnL=$-19.14
[EXIT] 2017-07-28 00:00:00: ABBV r=-0.0561, PnL=$-183.35
[EXIT] 2017-07-28 00:00:00: NGG r=-0.0113, PnL=$-31.59
[EXIT] 2017-07-28 00:00:00: SNP r=-0.0040, PnL=$-4.30

Simulating Trading Days:  76%|███████▌  | 76/100 [11:48<00:39,  1.65s/it]

[SIM] 2017-07-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0016, p_up=0.827)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.515)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0072, p_up=0.909)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.855)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0019, p_up=0.716)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.994)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0061, p_up=0.607)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0070, p_up=0.515)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0043, p_up=0.959)
[SIM] 2017-07-28 00:00:00: 9 trades proposed.
[TRADE] 2017-07-28 00:00:00: allocated $4618.16 to GD exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $4271.25 to D exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $3865.06 to AAPL exiting on 2017-08-04 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $2448.79 to C exiting on 2017-08-04 00:00:00
[EXIT] 2017-07-31 00:00:00: VZ r=0.1073, PnL=$534.19
[EXIT] 2017-07-31 00:00:00: GD r=-0.0420, PnL=$-207.94
[EXIT] 2017-07-31 00:00:00: ABBV r=-0.0541, PnL=$-197.52
[EXIT] 2017-07-31 00:00:00: D r=0.0053, PnL=$4.62
[EXIT] 2017-07-31 00:00:00: AMZN r=-0.0493, PnL=$-43.13
[EXIT] 2017-07-31 00:00:00: HRG r=-0.0389, PnL=$-11.68
[EXIT] 2017-07-31 00:00:00: V r=-0.0081, PnL=$-0.91

Simulating Trading Days:  77%|███████▋  | 77/100 [11:50<00:35,  1.55s/it]

[SIM] 2017-07-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0019, p_up=0.700)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0026, p_up=0.516)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0072, p_up=0.916)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0044, p_up=0.563)
[PORT] Sector Healthcare: sampled SNY from top-3 (expected=0.0016, p_up=0.715)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0042, p_up=0.904)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0065, p_up=0.631)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0050, p_up=0.723)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0041, p_up=0.662)
[SIM] 2017-07-31 00:00:00: 9 trades proposed.
[TRADE] 2017-07-31 00:00:00: allocated $3841.23 to BA exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $2351.19 to CHL exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $1857.39 to SNY exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $1918.93 to SNP exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $1692.19 to PCG exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $1401.99 to AMZN exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $845.86 to V exiting on 2017-08-07 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $140.29 to HRG exiting on 2017-08-07 00:00:00
[EXIT] 2017-08-01 00:00:00: VZ r=0.1116, PnL=$529.01
[EXIT] 2017-08-01 00:00:00: BA r=0.1270, PnL=$474.64
[EXIT] 2017-08-01 00:00:00: ABBV r=-0.0295, PnL=$-101.34
[EXIT] 2017-08-01 00:00:00: NGG r=0.0218, PnL=$62.76
[EXIT] 2017-08-01 00:00:00: UN r=0.0059, PnL=$10.04

Simulating Trading Days:  78%|███████▊  | 78/100 [11:51<00:31,  1.44s/it]

[SIM] 2017-08-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0018, p_up=0.692)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.521)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0038, p_up=0.756)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0023, p_up=0.746)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0082, p_up=0.942)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0084, p_up=0.995)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0071, p_up=0.483)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.504)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0042, p_up=0.674)
[SIM] 2017-08-01 00:00:00: 9 trades proposed.
[TRADE] 2017-08-01 00:00:00: allocated $5018.34 to GD exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $4484.46 to ABBV exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $2627.49 to UN exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $2484.60 to MA exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $1977.44 to SNP exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $1935.78 to PCG exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $196.01 to HRG exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $189.71 to FB exiting on 2017-08-08 00:00:00
[EXIT] 2017-08-02 00:00:00: GD r=0.0174, PnL=$84.43
[EXIT] 2017-08-02 00:00:00: AAPL r=0.0240, PnL=$95.35
[EXIT] 2017-08-02 00:00:00: D r=0.0105, PnL=$34.38
[EXIT] 2017-08-02 00:00:00: MA r=-0.0029, PnL=$-6.43
[EXIT] 2017-08-02 00:00:00: SLB r=0.0319, PnL=$60.43
[EXIT] 2017-08-02 00:00:00: SNY r=-0.0112, PnL=$-8.62
[EXIT] 2017-08-02 00:00:00: AMZN r=-0.0541, PnL=$-37.38

Simulating Trading Days:  79%|███████▉  | 79/100 [11:52<00:28,  1.36s/it]

[SIM] 2017-08-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0014, p_up=0.777)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.523)
[PORT] Sector Consumer Goods: sampled UL from top-3 (expected=0.0023, p_up=0.958)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0024, p_up=0.824)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0088, p_up=0.952)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.995)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0074, p_up=0.522)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0073, p_up=0.987)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0043, p_up=0.682)
[SIM] 2017-08-02 00:00:00: 9 trades proposed.
[TRADE] 2017-08-02 00:00:00: allocated $4920.69 to GD exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $4838.49 to VZ exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $4547.90 to UL exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $3521.99 to ABBV exiting on 2017-08-09 00:00:00
[EXIT] 2017-08-03 00:00:00: AAPL r=0.0333, PnL=$108.44
[EXIT] 2017-08-03 00:00:00: CVX r=0.0313, PnL=$94.06
[EXIT] 2017-08-03 00:00:00: C r=0.0078, PnL=$16.34

Simulating Trading Days:  80%|████████  | 80/100 [11:53<00:26,  1.30s/it]

[SIM] 2017-08-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0020, p_up=0.708)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0027, p_up=0.524)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0074, p_up=0.932)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.797)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0095, p_up=0.963)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0048, p_up=0.924)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0074, p_up=0.689)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0050, p_up=0.726)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0044, p_up=0.688)
[SIM] 2017-08-03 00:00:00: 9 trades proposed.
[TRADE] 2017-08-03 00:00:00: allocated $3748.02 to ABBV exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $3519.03 to AAPL exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $1235.65 to ABB exiting on 2017-08-10 00:00:00
[EXIT] 2017-08-04 00:00:00: GD r=0.0108, PnL=$49.70
[EXIT] 2017-08-04 00:00:00: D r=0.0142, PnL=$60.47
[EXIT] 2017-08-04 00:00:00: AAPL r=0.0461, PnL=$178.13
[EXIT] 2017-08-04 00:00:00: C r=0.0230, PnL=$56.29

Simulating Trading Days:  81%|████████  | 81/100 [11:55<00:24,  1.27s/it]

[SIM] 2017-08-04 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0010, p_up=0.758)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.533)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0038, p_up=0.760)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.768)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0104, p_up=0.975)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0078, p_up=0.713)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0051, p_up=0.730)
[PORT] Sector Utilities: sampled D from top-3 (expected=0.0037, p_up=0.907)
[SIM] 2017-08-04 00:00:00: 9 trades proposed.
[TRADE] 2017-08-04 00:00:00: allocated $4710.61 to GD exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $3839.73 to D exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $2529.08 to C exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $2499.78 to UN exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $1865.26 to SLB exiting on 2017-08-11 00:00:00
[EXIT] 2017-08-07 00:00:00: BA r=-0.0092, PnL=$-35.33
[EXIT] 2017-08-07 00:00:00: CHL r=0.0022, PnL=$5.28
[EXIT] 2017-08-07 00:00:00: SNY r=0.0129, PnL=$23.92
[EXIT] 2017-08-07 00:00:00: SNP r=-0.0063, PnL=$-12.09
[EXIT] 2017-08-07 00:00:00: PCG r=0.0185, PnL=$31.25
[EXIT] 2017-08-07 00:00:00: AMZN r=0.0045, PnL=$6.37
[EXIT] 2017-08-07 00:00:00: V r=0.0194, PnL=$16.40
[EXIT] 2017-08-07 00:00:00: HRG r=-0.0187, PnL=$-2.62

Simulating Trading Days:  82%|████████▏ | 82/100 [11:56<00:22,  1.25s/it]

[SIM] 2017-08-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0009, p_up=0.749)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0028, p_up=0.542)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0038, p_up=0.765)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0049, p_up=0.611)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0108, p_up=0.980)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0050, p_up=0.933)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0078, p_up=0.579)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.512)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0044, p_up=0.694)
[SIM] 2017-08-07 00:00:00: 9 trades proposed.
[TRADE] 2017-08-07 00:00:00: allocated $3969.36 to ABB exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $2468.90 to UN exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $2314.87 to SLB exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $1923.76 to PCG exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $1241.04 to V exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $1220.91 to BABA exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $375.61 to HRG exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $429.97 to FB exiting on 2017-08-14 00:00:00
[EXIT] 2017-08-08 00:00:00: GD r=0.0116, PnL=$57.96
[EXIT] 2017-08-08 00:00:00: ABBV r=0.0155, PnL=$69.45
[EXIT] 2017-08-08 00:00:00: UN r=0.0079, PnL=$20.80
[EXIT] 2017-08-08 00:00:00: MA r=0.0027, PnL=$6.72
[EXIT] 2017-08-08 00:00:00: SNP r=-0.0103, PnL=$-20.38
[EXIT] 2017-08-08 00:00:00: PCG r=0.0151, PnL=$29.23
[EXIT] 2017-08-08 00:00:00: HRG r=-0.0354, PnL=$-6.94
[EXIT] 2017-08-08 00:00:00: FB r=0.0081, PnL=$1.53

Simulating Trading Days:  83%|████████▎ | 83/100 [11:57<00:20,  1.22s/it]

[SIM] 2017-08-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-2 (expected=0.0009, p_up=0.744)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0029, p_up=0.559)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0073, p_up=0.816)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0049, p_up=0.609)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.872)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0050, p_up=0.933)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0087, p_up=0.771)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.512)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0044, p_up=0.692)
[SIM] 2017-08-08 00:00:00: 9 trades proposed.
[TRADE] 2017-08-08 00:00:00: allocated $4410.79 to ABB exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $3920.71 to CELG exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $3209.55 to MO exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $2880.83 to AMZN exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $2518.20 to SLB exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $2120.57 to PCG exiting on 2017-08-15 00:00:00
[EXIT] 2017-08-09 00:00:00: GD r=0.0149, PnL=$73.55
[EXIT] 2017-08-09 00:00:00: VZ r=0.0002, PnL=$1.00
[EXIT] 2017-08-09 00:00:00: UL r=0.0184, PnL=$83.55
[EXIT] 2017-08-09 00:00:00: ABBV r=0.0185, PnL=$65.25

Simulating Trading Days:  84%|████████▍ | 84/100 [11:58<00:19,  1.21s/it]

[SIM] 2017-08-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-2 (expected=0.0020, p_up=0.710)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0031, p_up=0.581)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0081, p_up=0.882)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0022, p_up=0.752)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0111, p_up=0.985)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0050, p_up=0.932)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.595)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0062, p_up=0.951)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0033, p_up=0.708)
[SIM] 2017-08-09 00:00:00: 9 trades proposed.
[TRADE] 2017-08-09 00:00:00: allocated $4869.95 to ABBV exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $4516.31 to VZ exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $3824.43 to MO exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $2504.88 to C exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $2143.27 to SNP exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $218.49 to PPL exiting on 2017-08-16 00:00:00
[EXIT] 2017-08-10 00:00:00: ABBV r=-0.0077, PnL=$-29.04
[EXIT] 2017-08-10 00:00:00: AAPL r=-0.0016, PnL=$-5.66
[EXIT] 2017-08-10 00:00:00: ABB r=-0.0281, PnL=$-34.73

Simulating Trading Days:  85%|████████▌ | 85/100 [11:59<00:17,  1.19s/it]

[SIM] 2017-08-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0009, p_up=0.745)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0032, p_up=0.594)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0040, p_up=0.781)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.771)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0012, p_up=0.626)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled BABA from top-3 (expected=0.0074, p_up=0.522)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0051, p_up=0.754)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0043, p_up=0.678)
[SIM] 2017-08-10 00:00:00: 9 trades proposed.
[TRADE] 2017-08-10 00:00:00: allocated $4031.43 to GD exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $2298.46 to UN exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $2124.21 to C exiting on 2017-08-17 00:00:00
[EXIT] 2017-08-11 00:00:00: GD r=-0.0109, PnL=$-51.33
[EXIT] 2017-08-11 00:00:00: D r=-0.0088, PnL=$-33.93
[EXIT] 2017-08-11 00:00:00: C r=-0.0316, PnL=$-79.93
[EXIT] 2017-08-11 00:00:00: UN r=-0.0043, PnL=$-10.74
[EXIT] 2017-08-11 00:00:00: SLB r=-0.0549, PnL=$-102.46

Simulating Trading Days:  86%|████████▌ | 86/100 [12:00<00:16,  1.20s/it]

[SIM] 2017-08-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0018, p_up=0.696)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0032, p_up=0.603)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.950)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0023, p_up=0.798)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0121, p_up=0.996)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0045, p_up=0.936)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0094, p_up=0.809)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0071, p_up=0.512)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0042, p_up=0.668)
[SIM] 2017-08-11 00:00:00: 9 trades proposed.
[TRADE] 2017-08-11 00:00:00: allocated $4689.35 to ABBV exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $4285.31 to AAPL exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $4147.57 to BA exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $2127.38 to AMZN exiting on 2017-08-18 00:00:00
[EXIT] 2017-08-14 00:00:00: ABB r=-0.0176, PnL=$-69.67
[EXIT] 2017-08-14 00:00:00: UN r=-0.0019, PnL=$-4.64
[EXIT] 2017-08-14 00:00:00: SLB r=-0.0391, PnL=$-90.44
[EXIT] 2017-08-14 00:00:00: PCG r=0.0033, PnL=$6.42
[EXIT] 2017-08-14 00:00:00: V r=0.0037, PnL=$4.65
[EXIT] 2017-08-14 00:00:00: BABA r=-0.0266, PnL=$-32.51
[EXIT] 2017-08-14 00:00:00: HRG r=-0.0160, PnL=$-6.01
[EXIT] 2017-08-14 00:00:00: FB r=-0.0072, PnL=$-3.08

Simulating Trading Days:  87%|████████▋ | 87/100 [12:02<00:15,  1.20s/it]

[SIM] 2017-08-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0010, p_up=0.752)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0033, p_up=0.610)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.951)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0047, p_up=0.588)
[PORT] Sector Healthcare: sampled MRK from top-3 (expected=0.0011, p_up=0.612)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.997)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.615)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0057, p_up=0.930)
[PORT] Sector Utilities: sampled EXC from top-3 (expected=0.0031, p_up=0.626)
[SIM] 2017-08-14 00:00:00: 9 trades proposed.
[TRADE] 2017-08-14 00:00:00: allocated $4550.56 to GD exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $4153.76 to AAPL exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $3921.80 to VZ exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $1181.61 to SLB exiting on 2017-08-21 00:00:00
[EXIT] 2017-08-15 00:00:00: ABB r=-0.0197, PnL=$-87.04
[EXIT] 2017-08-15 00:00:00: CELG r=-0.0288, PnL=$-113.04
[EXIT] 2017-08-15 00:00:00: MO r=-0.0012, PnL=$-3.93
[EXIT] 2017-08-15 00:00:00: AMZN r=-0.0072, PnL=$-20.66
[EXIT] 2017-08-15 00:00:00: SLB r=-0.0313, PnL=$-78.83
[EXIT] 2017-08-15 00:00:00: PCG r=0.0014, PnL=$3.06

Simulating Trading Days:  88%|████████▊ | 88/100 [12:03<00:14,  1.19s/it]

[SIM] 2017-08-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0018, p_up=0.692)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0033, p_up=0.616)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.951)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.798)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0124, p_up=0.998)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0046, p_up=0.942)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0091, p_up=0.794)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0056, p_up=0.926)
[PORT] Sector Utilities: sampled SO from top-3 (expected=0.0026, p_up=0.623)
[SIM] 2017-08-15 00:00:00: 9 trades proposed.
[TRADE] 2017-08-15 00:00:00: allocated $5056.58 to ABBV exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $4606.03 to AAPL exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $4509.01 to BA exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $4304.52 to VZ exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $374.20 to MA exiting on 2017-08-22 00:00:00
[EXIT] 2017-08-16 00:00:00: ABBV r=-0.0222, PnL=$-108.19
[EXIT] 2017-08-16 00:00:00: VZ r=0.0039, PnL=$17.80
[EXIT] 2017-08-16 00:00:00: MO r=0.0021, PnL=$8.20
[EXIT] 2017-08-16 00:00:00: C r=-0.0105, PnL=$-26.36
[EXIT] 2017-08-16 00:00:00: SNP r=-0.0347, PnL=$-74.33
[EXIT] 2017-08-16 00:00:00: PPL r=0.0117, PnL=$2.55

Simulating Trading Days:  89%|████████▉ | 89/100 [12:04<00:13,  1.19s/it]

[SIM] 2017-08-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0018, p_up=0.694)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0033, p_up=0.619)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0042, p_up=0.802)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.800)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0125, p_up=0.999)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.997)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.617)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0056, p_up=0.929)
[PORT] Sector Utilities: sampled EXC from top-3 (expected=0.0032, p_up=0.635)
[SIM] 2017-08-16 00:00:00: 9 trades proposed.
[TRADE] 2017-08-16 00:00:00: allocated $4970.76 to ABBV exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $4947.90 to GD exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $4250.87 to VZ exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $3031.12 to UN exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $750.44 to MA exiting on 2017-08-23 00:00:00
[EXIT] 2017-08-17 00:00:00: GD r=-0.0015, PnL=$-5.90
[EXIT] 2017-08-17 00:00:00: UN r=0.0081, PnL=$18.64
[EXIT] 2017-08-17 00:00:00: C r=-0.0092, PnL=$-19.59

Simulating Trading Days:  90%|█████████ | 90/100 [12:05<00:11,  1.19s/it]

[SIM] 2017-08-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SLB from top-3 (expected=0.0007, p_up=0.712)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.620)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0086, p_up=0.924)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0045, p_up=0.574)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0126, p_up=1.000)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0045, p_up=0.908)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0086, p_up=0.761)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0059, p_up=0.941)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0026, p_up=0.618)
[SIM] 2017-08-17 00:00:00: 9 trades proposed.
[TRADE] 2017-08-17 00:00:00: allocated $3408.38 to MO exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $3253.15 to ABB exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $1787.77 to AMZN exiting on 2017-08-24 00:00:00
[EXIT] 2017-08-18 00:00:00: ABBV r=-0.0095, PnL=$-44.48
[EXIT] 2017-08-18 00:00:00: AAPL r=0.0001, PnL=$0.54
[EXIT] 2017-08-18 00:00:00: BA r=0.0038, PnL=$15.72
[EXIT] 2017-08-18 00:00:00: AMZN r=-0.0098, PnL=$-20.92

Simulating Trading Days:  91%|█████████ | 91/100 [12:06<00:10,  1.20s/it]

[SIM] 2017-08-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0010, p_up=0.767)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.622)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0042, p_up=0.806)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0045, p_up=0.570)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0027, p_up=0.578)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0083, p_up=0.748)
[PORT] Sector Technology: sampled CHL from top-3 (expected=0.0054, p_up=0.803)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0038, p_up=0.640)
[SIM] 2017-08-18 00:00:00: 9 trades proposed.
[TRADE] 2017-08-18 00:00:00: allocated $4670.87 to GD exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $2900.37 to UN exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $3025.76 to CHL exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $2500.78 to BBL exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $2117.42 to AMZN exiting on 2017-08-25 00:00:00
[EXIT] 2017-08-21 00:00:00: GD r=-0.0078, PnL=$-35.67
[EXIT] 2017-08-21 00:00:00: AAPL r=-0.0165, PnL=$-68.60
[EXIT] 2017-08-21 00:00:00: VZ r=-0.0131, PnL=$-51.45
[EXIT] 2017-08-21 00:00:00: SLB r=-0.0149, PnL=$-17.55

Simulating Trading Days:  92%|█████████▏| 92/100 [12:08<00:09,  1.19s/it]

[SIM] 2017-08-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0020, p_up=0.712)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.621)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.951)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.810)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0088, p_up=0.766)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0046, p_up=0.943)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0079, p_up=0.724)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0069, p_up=0.544)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0038, p_up=0.637)
[SIM] 2017-08-21 00:00:00: 9 trades proposed.
[TRADE] 2017-08-21 00:00:00: allocated $4125.33 to AAPL exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $4049.97 to BA exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $2814.97 to MA exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $2593.15 to CELG exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $103.02 to AMZN exiting on 2017-08-28 00:00:00
[EXIT] 2017-08-22 00:00:00: ABBV r=0.0200, PnL=$101.36
[EXIT] 2017-08-22 00:00:00: AAPL r=-0.0113, PnL=$-51.88
[EXIT] 2017-08-22 00:00:00: BA r=0.0024, PnL=$10.93
[EXIT] 2017-08-22 00:00:00: VZ r=-0.0027, PnL=$-11.54
[EXIT] 2017-08-22 00:00:00: MA r=0.0169, PnL=$6.31

Simulating Trading Days:  93%|█████████▎| 93/100 [12:09<00:08,  1.20s/it]

[SIM] 2017-08-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled BBL from top-3 (expected=0.0012, p_up=0.788)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0033, p_up=0.619)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.952)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.810)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0027, p_up=0.580)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0054, p_up=0.621)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0069, p_up=0.552)
[PORT] Sector Utilities: sampled PPL from top-3 (expected=0.0024, p_up=0.597)
[SIM] 2017-08-22 00:00:00: 9 trades proposed.
[TRADE] 2017-08-22 00:00:00: allocated $5028.04 to GD exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $4607.04 to AAPL exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $3134.42 to MA exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $2911.95 to BBL exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $1679.88 to CHTR exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $1196.94 to HRG exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $330.71 to PPL exiting on 2017-08-29 00:00:00
[EXIT] 2017-08-23 00:00:00: ABBV r=0.0156, PnL=$77.65
[EXIT] 2017-08-23 00:00:00: GD r=-0.0043, PnL=$-21.21
[EXIT] 2017-08-23 00:00:00: VZ r=-0.0027, PnL=$-11.42
[EXIT] 2017-08-23 00:00:00: UN r=0.0015, PnL=$4.63
[EXIT] 2017-08-23 00:00:00: MA r=0.0053, PnL=$3.97

Simulating Trading Days:  94%|█████████▍| 94/100 [12:10<00:07,  1.20s/it]

[SIM] 2017-08-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0021, p_up=0.720)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.621)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.816)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.809)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0094, p_up=0.889)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0045, p_up=0.903)
[PORT] Sector Services: sampled HD from top-3 (expected=0.0053, p_up=0.652)
[PORT] Sector Technology: sampled VZ from top-3 (expected=0.0071, p_up=0.982)
[PORT] Sector Utilities: sampled EXC from top-3 (expected=0.0021, p_up=0.533)
[SIM] 2017-08-23 00:00:00: 9 trades proposed.
[TRADE] 2017-08-23 00:00:00: allocated $4793.66 to VZ exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $3974.17 to ABB exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $3958.79 to CELG exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $3164.77 to UN exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $2097.23 to MA exiting on 2017-08-30 00:00:00
[EXIT] 2017-08-24 00:00:00: MO r=-0.0109, PnL=$-37.11
[EXIT] 2017-08-24 00:00:00: ABB r=0.0083, PnL=$26.98
[EXIT] 2017-08-24 00:00:00: AMZN r=-0.0085, PnL=$-15.11

Simulating Trading Days:  95%|█████████▌| 95/100 [12:11<00:05,  1.20s/it]

[SIM] 2017-08-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0014, p_up=0.778)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.627)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.954)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.912)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0027, p_up=0.580)
[PORT] Sector Industrial Goods: sampled BA from top-3 (expected=0.0045, p_up=0.931)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0067, p_up=0.645)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0065, p_up=0.677)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0007, p_up=0.936)
[SIM] 2017-08-24 00:00:00: 9 trades proposed.
[TRADE] 2017-08-24 00:00:00: allocated $3674.42 to AAPL exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $3465.49 to NGG exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $1291.73 to BA exiting on 2017-08-31 00:00:00
[EXIT] 2017-08-25 00:00:00: GD r=0.0016, PnL=$7.52
[EXIT] 2017-08-25 00:00:00: UN r=0.0126, PnL=$36.67
[EXIT] 2017-08-25 00:00:00: CHL r=0.0143, PnL=$43.18
[EXIT] 2017-08-25 00:00:00: BBL r=0.0641, PnL=$160.28
[EXIT] 2017-08-25 00:00:00: AMZN r=-0.0138, PnL=$-29.18

Simulating Trading Days:  96%|█████████▌| 96/100 [12:12<00:04,  1.19s/it]

[SIM] 2017-08-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0024, p_up=0.736)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.630)
[PORT] Sector Consumer Goods: sampled UN from top-3 (expected=0.0043, p_up=0.817)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0025, p_up=0.796)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0093, p_up=0.929)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0065, p_up=0.630)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0084, p_up=0.761)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.941)
[SIM] 2017-08-25 00:00:00: 9 trades proposed.
[EXIT] 2017-08-28 00:00:00: AAPL r=0.0271, PnL=$111.79
[EXIT] 2017-08-28 00:00:00: BA r=0.0064, PnL=$25.78
[EXIT] 2017-08-28 00:00:00: MA r=0.0145, PnL=$40.75
[EXIT] 2017-08-28 00:00:00: CELG r=0.0331, PnL=$85.88
[EXIT] 2017-08-28 00:00:00: AMZN r=-0.0076, PnL=$-0.79

Simulating Trading Days:  97%|█████████▋| 97/100 [12:14<00:03,  1.19s/it]

[SIM] 2017-08-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0026, p_up=0.758)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.630)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.955)
[PORT] Sector Financial: sampled C from top-3 (expected=0.0025, p_up=0.907)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0027, p_up=0.590)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0063, p_up=0.620)
[PORT] Sector Technology: sampled FB from top-3 (expected=0.0067, p_up=0.580)
[PORT] Sector Utilities: sampled PCG from top-2 (expected=0.0037, p_up=0.626)
[SIM] 2017-08-28 00:00:00: 9 trades proposed.
[EXIT] 2017-08-29 00:00:00: GD r=-0.0014, PnL=$-7.00
[EXIT] 2017-08-29 00:00:00: AAPL r=0.0196, PnL=$90.25
[EXIT] 2017-08-29 00:00:00: MA r=0.0003, PnL=$0.94
[EXIT] 2017-08-29 00:00:00: BBL r=0.0467, PnL=$136.04
[EXIT] 2017-08-29 00:00:00: CHTR r=-0.0207, PnL=$-34.82
[EXIT] 2017-08-29 00:00:00: HRG r=0.0091, PnL=$10.91
[EXIT] 2017-08-29 00:00:00: PPL r=0.0087, PnL=$2.88

Simulating Trading Days:  98%|█████████▊| 98/100 [12:15<00:02,  1.19s/it]

[SIM] 2017-08-29 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled SNP from top-3 (expected=0.0029, p_up=0.774)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.630)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0081, p_up=0.882)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0046, p_up=0.579)
[PORT] Sector Healthcare: sampled CELG from top-3 (expected=0.0092, p_up=0.951)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled PCLN from top-3 (expected=0.0034, p_up=0.747)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0113, p_up=0.890)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0006, p_up=0.948)
[SIM] 2017-08-29 00:00:00: 9 trades proposed.
[EXIT] 2017-08-30 00:00:00: VZ r=-0.0033, PnL=$-15.89
[EXIT] 2017-08-30 00:00:00: ABB r=-0.0125, PnL=$-49.83
[EXIT] 2017-08-30 00:00:00: CELG r=0.0399, PnL=$157.81
[EXIT] 2017-08-30 00:00:00: UN r=0.0003, PnL=$1.07
[EXIT] 2017-08-30 00:00:00: MA r=0.0055, PnL=$11.50

Simulating Trading Days:  99%|█████████▉| 99/100 [12:16<00:01,  1.18s/it]

[SIM] 2017-08-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0019, p_up=0.983)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0034, p_up=0.632)
[PORT] Sector Consumer Goods: sampled AAPL from top-3 (expected=0.0076, p_up=0.956)
[PORT] Sector Financial: sampled V from top-3 (expected=0.0046, p_up=0.585)
[PORT] Sector Healthcare: sampled PFE from top-3 (expected=0.0029, p_up=0.623)
[PORT] Sector Industrial Goods: sampled GD from top-3 (expected=0.0085, p_up=0.996)
[PORT] Sector Services: sampled CHTR from top-3 (expected=0.0053, p_up=0.596)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0119, p_up=0.916)
[PORT] Sector Utilities: sampled NGG from top-2 (expected=0.0005, p_up=0.952)
[SIM] 2017-08-30 00:00:00: 9 trades proposed.
[EXIT] 2017-08-31 00:00:00: AAPL r=0.0297, PnL=$109.12
[EXIT] 2017-08-31 00:00:00: NGG r=0.0073, PnL=$25.16
[EXIT] 2017-08-31 00:00:00: BA r=0.0039, PnL=$4.98

Simulating Trading Days: 100%|██████████| 100/100 [12:17<00:00,  7.38s/it]

[SIM] 2017-08-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: sampled CVX from top-3 (expected=0.0018, p_up=0.986)
[PORT] Sector Conglomerates: sampled HRG from top-1 (expected=0.0035, p_up=0.638)
[PORT] Sector Consumer Goods: sampled MO from top-3 (expected=0.0081, p_up=0.885)
[PORT] Sector Financial: sampled MA from top-3 (expected=0.0024, p_up=0.773)
[PORT] Sector Healthcare: sampled ABBV from top-3 (expected=0.0124, p_up=0.998)
[PORT] Sector Industrial Goods: sampled ABB from top-3 (expected=0.0039, p_up=0.869)
[PORT] Sector Services: sampled AMZN from top-3 (expected=0.0061, p_up=0.606)
[PORT] Sector Technology: sampled INTC from top-3 (expected=0.0121, p_up=0.921)
[PORT] Sector Utilities: sampled PCG from top-3 (expected=0.0035, p_up=0.608)
[SIM] 2017-08-31 00:00:00: 9 trades proposed.

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
1,2017-04-12,70000.000000,51748.680716,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
2,2017-04-13,51748.680716,30000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'BRK-A', 'sector': 'Financial', 'p..."
3,2017-04-17,30000.000000,30000.000000,100000.000000,100000.000000,0.000000,0.000000,[]
4,2017-04-18,30000.000000,30000.000000,100000.000000,100000.000000,0.000000,0.000000,[]
...,...,...,...,...,...,...,...,...
95,2017-08-25,47238.330431,47238.330431,106234.009396,106234.009396,218.465186,0.002061,[]
96,2017-08-28,61188.168067,61188.168067,106497.411553,106497.411553,263.402157,0.002479,[]
97,2017-08-29,80276.352118,80276.352118,106696.613245,106696.613245,199.201692,0.001870,[]
98,2017-08-30,98369.650983,98369.650983,106801.289756,106801.289756,104.676511,0.000981,[]
99,2017-08-31,106940.546340,106940.546340,106940.546340,106940.546340,139.256584,0.001304,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'AAPL', 'sector': 'Consumer Goods'..."
1,2017-04-12,70000.000000,51748.680716,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'VZ', 'sector': 'Technology', 'pro..."
2,2017-04-13,51748.680716,30000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'BRK-A', 'sector': 'Financial', 'p..."
3,2017-04-17,30000.000000,30000.000000,100000.000000,100000.000000,0.000000,0.000000,[]
4,2017-04-18,30000.000000,30000.000000,100000.000000,100000.000000,0.000000,0.000000,[]
...,...,...,...,...,...,...,...,...
95,2017-08-25,47238.330431,47238.330431,106234.009396,106234.009396,218.465186,0.002061,[]
96,2017-08-28,61188.168067,61188.168067,106497.411553,106497.411553,263.402157,0.002479,[]
97,2017-08-29,80276.352118,80276.352118,106696.613245,106696.613245,199.201692,0.001870,[]
98,2017-08-30,98369.650983,98369.650983,106801.289756,106801.289756,104.676511,0.000981,[]
99,2017-08-31,106940.546340,106940.546340,106940.546340,106940.546340,139.256584,0.001304,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $106,940.55
Total Return on Investment (ROI): 6.94%
Annualized Sharpe Ratio: 5.36
--------------------------

In [36]:
master_df_with_target = add_horizon_targets(master_df.copy(), H=5, price_col="close")
import numpy as np
import pandas as pd

ret_col = f"ret_{5}d"

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
        # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 484
Total capital allocated: $1,368,594.89
Average position size:  $2,827.68
Completed trades with returns: 484
Winning trades: 281 (58.1%)
Losing trades:  202 (41.7%)
Total PnL: $6,940.55
Average PnL per trade: $14.34
Average return: 0.45%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Industrial Goods,82,294590.137812,3592.562656,1679.685719,20.483972,0.004949
Healthcare,62,182156.284214,2938.004584,1306.247978,21.068516,0.007215
Consumer Goods,73,237626.381161,3255.155906,938.569191,12.857112,0.006135
Financial,57,129905.004971,2279.035175,861.128183,15.107512,0.006762
Services,50,97313.726052,1946.274521,824.981493,16.499630,0.006974
Technology,60,214997.375135,3583.289586,603.785571,10.063093,0.002459
Utilities,42,93902.972308,2235.785055,428.437355,10.200889,0.002297
Basic Matierials,46,100687.982429,2188.869183,263.646666,5.731449,0.000042
Conglomerates,12,17415.024256,1451.252021,34.064184,2.838682,-0.009197

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
361,2017-07-24,2017-07-31,VZ,Technology,4978.580473,0.996357,0.007649,0.107298,534.192585
368,2017-07-25,2017-08-01,VZ,Technology,4738.486666,0.995663,0.007623,0.111642,529.012387
369,2017-07-25,2017-08-01,BA,Industrial Goods,3737.637427,0.889525,0.004033,0.126989,474.637276
348,2017-07-19,2017-07-26,BA,Industrial Goods,3913.086602,0.901949,0.004151,0.107028,418.808475
353,2017-07-20,2017-07-27,VZ,Technology,3913.262786,0.996462,0.007653,0.081185,317.698170
238,2017-06-14,2017-06-21,CELG,Healthcare,3107.288201,0.894899,0.009391,0.097406,302.667967
253,2017-06-19,2017-06-26,CELG,Healthcare,4097.583662,0.969172,0.009047,0.069431,284.499913
135,2017-05-18,2017-05-25,GD,Industrial Goods,4644.929672,0.989621,0.008289,0.043864,203.746065
233,2017-06-13,2017-06-20,CELG,Healthcare,3582.991127,0.866964,0.009352,0.055175,197.690467
385,2017-07-28,2017-08-04,AAPL,Consumer Goods,3865.063673,0.909364,0.007170,0.046087,178.128996

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
216,2017-06-08,2017-06-15,AAPL,Consumer Goods,4321.246375,0.955613,0.007633,-0.069037,-298.324967
43,2017-04-26,2017-05-03,T,Technology,5214.093672,0.934153,0.002361,-0.050445,-263.025117
207,2017-06-06,2017-06-13,AAPL,Consumer Goods,4541.356714,0.955398,0.007631,-0.050890,-231.110838
337,2017-07-14,2017-07-21,ABB,Industrial Goods,3958.781194,0.926864,0.004901,-0.054054,-213.988330
362,2017-07-24,2017-07-31,GD,Industrial Goods,4955.104173,0.993415,0.008405,-0.041966,-207.943457
223,2017-06-09,2017-06-16,AAPL,Consumer Goods,4437.253867,0.955323,0.007630,-0.045040,-199.851918
363,2017-07-24,2017-07-31,ABBV,Healthcare,3649.594631,0.862003,0.005372,-0.054120,-197.515596
358,2017-07-21,2017-07-28,ABBV,Healthcare,3265.724283,0.847622,0.005037,-0.056144,-183.349443
102,2017-05-10,2017-05-17,VZ,Technology,4471.239511,0.976858,0.006974,-0.040966,-183.168593
22,2017-04-19,2017-04-26,VZ,Technology,4694.875901,0.894780,0.004854,-0.032284,-151.571203

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Industrial Goods  1679.685719
Healthcare        1306.247978
Consumer Goods     938.569191
Financial          861.128183
Services           824.981493
Technology         603.785571
Utilities          428.437355
Basic Matierials   263.646666
Conglomerates       34.064184

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Industrial Goods  1679.685719
Healthcare        1306.247978
Consumer Goods     938.569191
Financial          861.128183
Services           824.981493
Technology         603.785571
Utilities          428.437355
Basic Matierials   263.646666
Conglomerates       34.064184

Top 10 Most Invested Tickers:

ticker
GD      35
AAPL    32
VZ      31
MA      27
AMZN    23
BA      21
CELG    20
ABBV    18
ABB     17
BABA    17
Name: count, dtype: int64

Tickers Never Invested In (42):
{'UTX', 'KO', 'ORCL', 'UPS', 'DUK', 'MCD', 'AEP', 'BAC', 'BSAC', 'BHP', 'CODI', 'BP', 'SRE', 'MSFT', 'TM', 'RDS-B', 'CMCSA', 'DHR', 'XOM', 'IEP', 'BCH', 'HON', 'DIS', 'CAT', 'NEE', 'WMT', 'REX', 'AGFS', 'GE', 'GOOG', 'HD', 'PEP', 'JPM', 'UNH', 'WFC', 'TOT', 'JNJ', 'TSM', 'CSCO', 'HSBC', 'PM', 'PICO'}

In [37]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]