# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as Fnn
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [7]:
pandas_ta_classic_path = None
for sp in site.getsitepackages():
    pandas_ta_classic_path = os.path.join(sp, 'pandas_ta_classic')
    if os.path.exists(pandas_ta_classic_path):
        break

if pandas_ta_classic_path:
    squeeze_pro_path = os.path.join(pandas_ta_classic_path, 'momentum', 'squeeze_pro.py')
    if os.path.exists(squeeze_pro_path):
        try:
            with open(squeeze_pro_path, 'r') as f:
                lines = f.readlines()

            new_lines = []
            fixed = False
            for line in lines:
                if "from numpy import NaN as npNaN" in line:
                    new_lines.append(line.replace("from numpy import NaN as npNaN", "# from numpy import NaN as npNaN\nimport numpy as np\n"))
                    fixed = True
                    print("Modified import statement in squeeze_pro.py")
                else:
                    new_lines.append(line)

            if fixed:
                with open(squeeze_pro_path, 'w') as f:
                    f.writelines(new_lines)
                print("Successfully patched pandas_ta_classic/momentum/squeeze_pro.py")
            else:
                print("Could not find the problematic import line in squeeze_pro.py")

        except Exception as e:
            print(f"Error modifying squeeze_pro.py: {e}")
    else:
        print(f"Could not find squeeze_pro.py at {squeeze_pro_path}")
else:
    print("Could not find the pandas_ta_classic library installation path.")

import pandas_ta_classic as ta

Could not find the problematic import line in squeeze_pro.py

### Configurations

In [8]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 1100  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [9]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [10]:
BUCKET_BINS   = [-np.inf, -0.02, -0.005, 0.0, 0.005, 0.02, np.inf]
K = len(BUCKET_BINS) - 1

In [11]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

In [12]:
CALIBRATION_LOGGED = set()

In [13]:
def bucketize_with_edges(x, edges):
    # x: 1D np array of returns; edges: len K+1
    return np.clip(np.digitize(x, edges[1:-1], right=True), 0, len(edges)-2).astype(np.int64)

def make_cumulative_targets(y_idx, K):
    # y_idx in [0..K-1] -> T: [N,K-1] with T[:,k]=1(y>k)
    y = y_idx.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def ordinal_to_class_probs(P_rep):
    # P_rep: [N,K-1] with P(y>k) (after sigmoid), repaired monotone
    N, K1 = P_rep.shape; K = K1+1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:,0] = 1.0 - P_rep[:,0]
    for c in range(1, K-1):
        Pc[:,c] = np.clip(P_rep[:,c-1] - P_rep[:,c], 0., 1.)
    Pc[:,K-1] = P_rep[:,K1-1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)

def monotone_repair_numpy(P):
    P = np.asarray(P, dtype=np.float32).copy()
    for k in range(P.shape[1]-2, -1, -1):
        P[:,k] = np.maximum(P[:,k], P[:,k+1])
    return P

In [ ]:
# multiclass calibration tuned for macro-F1 balance
def _class_dist(y_hat, K):
    hist = np.bincount(y_hat, minlength=K).astype(np.float32)
    return hist / max(1, y_hat.size)

def _balance_penalty(p_hat, p_target, norm="l1"):
    if norm == "l1":
        return float(np.abs(p_hat - p_target).sum())
    elif norm == "l2":
        return float(np.sqrt(((p_hat - p_target) ** 2).sum()))
    else:
        return float(np.abs(p_hat - p_target).sum())

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    # decode ordinal cumulative probs to class indices using per-head taus.
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def tune_temperature_and_taus(
    Z_val,
    y_val_idx,
    K,
    T_grid=np.linspace(0.6, 2.5, 15),
    tau_grid=np.linspace(0.2, 0.8, 31),
    lambda_balance=0.05,
    target_priors="uniform",
    coord_rounds=3,
):
    """Learn a temperature T and per-head taus by maximizing macro-F1 with a balance penalty."""
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.detach().cpu().numpy()

    N, K_1 = Z_val.shape
    assert K_1 == K - 1

    if isinstance(target_priors, str) and target_priors == "uniform":
        p_target = np.ones(K, dtype=np.float32) / K
    else:
        p_target = np.asarray(target_priors, dtype=np.float32)
        p_target = p_target / p_target.sum()

    best = {"score": -1e9, "T": 1.0, "taus": np.full(K_1, 0.5, np.float32)}

    for T in T_grid:
        P_cum = 1.0 / (1.0 + np.exp(-(Z_val / T)))
        P_rep = monotone_repair_numpy(P_cum)

        taus = np.full(K_1, 0.5, dtype=np.float32)
        for _ in range(coord_rounds):
            for k in range(K_1):
                best_k = (taus[k], -1e9)
                for tau in tau_grid:
                    taus_try = taus.copy()
                    taus_try[k] = tau
                    y_hat = decode_ordinal_with_taus(P_rep, taus_try)
                    f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
                    p_hat = _class_dist(y_hat, K)
                    score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")
                    if score > best_k[1]:
                        best_k = (tau, score)
                taus[k] = best_k[0]

        y_hat = decode_ordinal_with_taus(P_rep, taus)
        f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
        p_hat = _class_dist(y_hat, K)
        score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")

        if score > best["score"]:
            best.update({"score": score, "T": float(T), "taus": taus.astype(np.float32)})

    return best["T"], best["taus"]

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [15]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [16]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # end current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [17]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [18]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [19]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [20]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [21]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [22]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [23]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [24]:
class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):  # T: float32 matrix [N, K-1] with 0/1
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)
    def __len__(self): return len(self.X)
    def __getitem__(self, i): return self.X[i], self.T[i]
    
class LSTMOrdinal(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, head='CORAL', K=6):
        super().__init__()
        self.K = K
        self.lstm1 = nn.LSTM(n_features, hidden1, num_layers=1, batch_first=True, dropout=0.1)
        self.inter_drop = nn.Dropout(inter_dropout)
        self.lstm2 = nn.LSTM(hidden1, hidden2, num_layers=1, batch_first=True, dropout=0.1)

        self.norm = nn.BatchNorm1d(hidden2)
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(dropout)

        if head.upper() == 'CORAL':
            self.w = nn.Linear(fc, 1, bias=False)
            self._beta = nn.Parameter(torch.zeros(K-1))
            self.softplus = nn.Softplus()
            self.head_type = 'CORAL'
        else:
            self.fc_out = nn.Linear(fc, K-1)
            self.head_type = 'CORN'

    def forward(self, x):
        out1,_ = self.lstm1(x)
        out1 = self.inter_drop(out1)
        out2,_ = self.lstm2(out1)
        last = out2[:, -1, :]
        last = self.norm(last)
        z = self.relu(self.fc1(last))
        z = self.drop(z)
        if self.head_type == 'CORAL':
            base = self.w(z)                              # [B,1]
            deltas = self.softplus(self._beta)            # ≥0
            b = torch.cumsum(deltas, dim=0)               # [K-1]
            logits = base - b                              # broadcast -> [B,K-1]
        else:
            logits = self.fc_out(z)                        # [B,K-1]
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [25]:
def train_company_models(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 sequence_length: int = None,
                                 H: int = 1,
                                 K: int = K,        # global K
                                 head_type: str = 'CORAL'):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"[TRAIN] {ticker}: preparing data (H={H}) with {len(company_data_df)} rows")

    ret_col = f"ret_{H}d"
    if ret_col not in company_data_df.columns:
        company_data_df = add_horizon_targets(company_data_df, H=H, price_col='close')

    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)
    if len(company_data_df) < sequence_length + H + 10:
        print(f"[TRAIN] {ticker}: insufficient history for sequence length {sequence_length}")
        return False, sequence_length

    contigs = identify_contiguous_periods(company_data_df)
    if not contigs:
        print(f"[TRAIN] {ticker}: no contiguous periods found")
        return False, sequence_length

    rets = company_data_df[ret_col].values
    y_idx_all = bucketize_with_edges(rets, BUCKET_BINS)
    X_all = company_data_df[feature_cols].values

    X_seq, y_seq = create_contiguous_sequences(
        X_all, y_idx_all, contigs, sequence_length, H
    )
    if len(X_seq) < 40:
        print(f"[TRAIN] {ticker}: too few sequences ({len(X_seq)})")
        return False, sequence_length
    print(f"[TRAIN] {ticker}: built {len(X_seq)} sequences (seq_len={sequence_length})")

    X_tr, X_val, y_tr, y_val = train_test_split(X_seq, y_seq, test_size=0.2, shuffle=False)

    scaler = MinMaxScaler()
    F = X_tr.shape[-1]
    X_tr = scaler.fit_transform(X_tr.reshape(-1, F)).reshape(X_tr.shape)
    X_val = scaler.transform(X_val.reshape(-1, F)).reshape(X_val.shape)
    print(f"[TRAIN] {ticker}: scaler fitted on {X_tr.shape[0]} training sequences")
    # Sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_tr has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    sector_feature_indices = [feature_cols.index('sector_ret_1d'),
                          feature_cols.index('sector_ret_5d'),
                          feature_cols.index('sector_vol_20d')]

    print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")


    T_tr  = make_cumulative_targets(y_tr, K)
    T_val = make_cumulative_targets(y_val, K)

    train_ds = OrdinalSequenceDataset(X_tr, T_tr)
    val_ds   = OrdinalSequenceDataset(X_val, T_val)
    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, drop_last=True)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_tr.shape[-1]
    model = LSTMOrdinal(n_features=n_features, head=head_type, K=K).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    pos_rate = T_tr.mean(axis=0)
    pos_w = ((1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)).astype(np.float32)
    pos_w = torch.tensor(pos_w, dtype=torch.float32, device=device) 
    print(f"[TRAIN] {ticker}: model n_features = {n_features}")

    
    def loss_fn(logits, T):
        losses = []
        for k in range(logits.shape[1]):
            losses.append(Fnn.binary_cross_entropy_with_logits(logits[:,k], T[:,k], pos_weight=pos_w[k]))
        return torch.stack(losses).mean()

    early = EarlyStopper(patience=15, mode='min')
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)

    for epoch in range(100):
        model.train()
        tot = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            l = loss_fn(logits, yb)
            l.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tot += l.item() * xb.size(0)

        model.eval()
        with torch.no_grad():
            vtot = 0.0
            for xb, yb in val_loader:
                xb, yb = xb.to(device), yb.to(device)
                logits = model(xb)
                l = loss_fn(logits, yb)
                vtot += l.item() * xb.size(0)
            val_loss = vtot / len(val_loader.dataset)

        scheduler.step(val_loss)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:
            break

    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    ret_seq_full = company_data_df[ret_col].values[sequence_length:]
    ret_train = ret_seq_full[:len(y_tr)]
    mu_c = np.array([ret_train[y_tr==c].mean() if np.any(y_tr==c) else 0.0 for c in range(K)], dtype=np.float32)


    taus = None
    temperature = 1.0
    try:
        model.eval()
        batch = 256
        logits_list = []
        for start in range(0, len(X_val), batch):
            xb = torch.from_numpy(X_val[start:start+batch].astype(np.float32)).to(device)
            with torch.no_grad():
                logits = model(xb)
            logits_list.append(logits.cpu().numpy())
        if logits_list:
            val_logits = np.vstack(logits_list)
            T_star, taus = tune_temperature_and_taus(
                Z_val=val_logits,
                y_val_idx=y_val,
                K=K,
                T_grid=np.linspace(0.6, 2.5, 15),
                tau_grid=np.linspace(0.2, 0.8, 31),
                lambda_balance=0.05,
                target_priors="uniform",
                coord_rounds=3,
            )
            temperature = float(T_star)
            print(f"[CAL] {ticker}: taus={np.round(taus, 3)} | temperature={temperature:.3f}")
        else:
            print(f"[CAL] {ticker}: no validation logits -> skipping calibration")
    except Exception as exc:
        print(f"[CAL] {ticker}: calibration failed ({exc})")
        taus = None
        temperature = 1.0

    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt"))
    joblib.dump(scaler, os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
    joblib.dump(BUCKET_BINS, os.path.join(model_save_path, f"{ticker}_edges_H{H}.pkl"))
    joblib.dump(mu_c, os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))
    if taus is not None and len(taus) == (K - 1) and np.all(np.isfinite(taus)):
        joblib.dump(taus, os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored taus")
    if temperature is not None and np.isfinite(temperature):
        joblib.dump(float(temperature), os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored temperature scale {temperature:.3f}")
    print(f"[SAVE] {ticker}: artifacts persisted (H={H})")

    del model, scaler, train_loader, val_loader, train_ds, val_ds
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [26]:

def predict_next_horizon(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         H: int,
                         K: int = 6,
                         head: str = "CORAL") -> dict | None:
    """
    Ordinal inference with optional calibration artifacts. Returns class probs plus
    summary stats so the simulator can log decisions.
    """
    try:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt")
        if not os.path.isfile(state_dict_path):
            return None

        scaler   = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        seq_len  = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
        mu_c     = joblib.load(os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))

        taus_path = os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl")
        T_path    = os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl")
        taus = joblib.load(taus_path) if os.path.isfile(taus_path) else None
        temperature = float(joblib.load(T_path)) if os.path.isfile(T_path) else 1.0

        n_features = len(feature_cols)
        model = LSTMOrdinal(n_features=n_features, head=head.upper(), K=K).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    if 'CALIBRATION_LOGGED' not in globals():
        globals()['CALIBRATION_LOGGED'] = set()
    if ticker not in CALIBRATION_LOGGED:
        if taus is not None:
            print(f"[CAL] {ticker}: loaded taus {np.round(taus,3)}")
        else:
            print(f"[CAL] {ticker}: no taus artifact found")
        print(f"[CAL] {ticker}: temperature scaling {temperature:.3f}")
        CALIBRATION_LOGGED.add(ticker)

    contiguous = identify_contiguous_periods(company_data_df)
    if not contiguous:
        return None
    start, end = contiguous[-1]
    period = company_data_df.iloc[start:end+1]
    if len(period) < seq_len:
        return None

    try:
        last_seq = period.tail(seq_len)
        X_scaled = scaler.transform(last_seq[feature_cols])
    except Exception:
        return None

    x = torch.from_numpy(np.asarray([X_scaled], dtype=np.float32)).to(device)

    with torch.no_grad():
        z = model(x)
        if temperature and temperature > 0 and temperature != 1.0:
            z = z / temperature
        P_cum = torch.sigmoid(z).cpu().numpy()
        P_cum = monotone_repair_numpy(P_cum)
        Pc    = ordinal_to_class_probs(P_cum)

    mu_c = np.asarray(mu_c, dtype=np.float32).reshape(-1)
    if mu_c.shape[0] != K:
        return None
    expected_rise = float((Pc[0] * mu_c).sum())

    top_bucket_idx = K - 1
    prob_top_bucket = float(Pc[0, top_bucket_idx])
    bucket_idx = int(np.argmax(Pc[0]))

    class_idx = None
    if taus is not None:
        taus = np.asarray(taus, dtype=np.float32).reshape(-1)
        if taus.shape[0] == (K - 1):
            class_idx = int(decode_ordinal_with_taus(P_cum, taus=taus)[0])

    positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
    prob_up = float(Pc[0, positive_buckets].sum()) if positive_buckets else prob_top_bucket

    return {
        'ticker': ticker,
        'expected_rise': expected_rise,
        'predicted_prob': prob_up,  # probability of positive move
        'prob_up': prob_up,
        'prob_bucket_top': prob_top_bucket,
        'bucket_idx': bucket_idx,
        'class_idx': class_idx,
        'class_probs': Pc[0].tolist(),
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [27]:

def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                              total_capital: float, sector_threshold: float,
                              kelly_fraction: float) -> pd.DataFrame:
    """Pick strongest candidates per sector and size using Kelly on prob_up and horizon payoffs."""
    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")
    df = daily_predictions_df.copy()

    if 'prob_up' not in df.columns and 'class_probs' in df.columns:
        positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
        def _sum_up(probs):
            if isinstance(probs, (list, tuple)) and len(probs) == K and positive_buckets:
                return float(sum(probs[i] for i in positive_buckets))
            return np.nan
        df['prob_up'] = df['class_probs'].apply(_sum_up)

    if 'prob_up' not in df.columns and 'predicted_prob' in df.columns:
        df['prob_up'] = df['predicted_prob']

    if 'expected_rise' not in df.columns:
        print("[PORT] Missing expected_rise; cannot size portfolio.")
        return pd.DataFrame()

    df = df[(df['prob_up'] >= sector_threshold) & (df['expected_rise'] > 0)]
    print(f"[PORT] {len(df)} tickers cleared prob_up ≥ {sector_threshold:.3f} and positive expected return.")
    if df.empty:
        return pd.DataFrame()

    winners = (df.sort_values(['sector', 'expected_rise'], ascending=[True, False])
                 .groupby('sector', as_index=False)
                 .head(1))
    if winners.empty:
        print("[PORT] No sector winners after grouping.")
        return pd.DataFrame()

    rows = []
    for _, row in winners.iterrows():
        ticker = row['ticker']
        sector = row['sector']
        p_up = float(row['prob_up'])
        payout = payout_map.get(ticker, {})
        b = payout.get('b') if isinstance(payout, dict) else float(payout)
        if not np.isfinite(b) or b <= 0:
            print(f"[PORT] Sector {sector}: skipping {ticker} due to invalid payout ratio {b}.")
            continue
        kelly_pct = p_up - (1.0 - p_up) / b
        if kelly_pct <= 0:
            print(f"[PORT] Sector {sector}: Kelly <= 0 for {ticker} (p_up={p_up:.3f}, b={b:.3f}).")
            continue
        investment_fraction = min(MAX_POSITION_SIZE, kelly_pct * kelly_fraction)
        investment_fraction = max(0.0, investment_fraction)
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            print(f"[PORT] Sector {sector}: allocation ${investment_amount:.2f} below minimum; skipping {ticker}.")
            continue
        print(f"[PORT] Sector {sector}: selecting {ticker} (p_up={p_up:.3f}, kelly={kelly_pct:.3f}) "
              f"with ${investment_amount:.2f} allocation")
        rows.append({
            'ticker': ticker,
            'sector': sector,
            'prob_up': p_up,
            'predicted_prob': p_up,
            'expected_rise': row['expected_rise'],
            'bucket_idx': row.get('bucket_idx', np.nan),
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount
        })

    if not rows:
        print("[PORT] All sector winners rejected after Kelly sizing.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [28]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    """Check the minimal set of artifacts needed for ordinal inference."""
    required = [
        f"{ticker}_lstmORD_H{H}.pt",      # model weights (ordinal head)
        f"{ticker}_scaler_H{H}.pkl",      # feature scaler
        f"{ticker}_seq_length_H{H}.pkl",  # sequence length
        f"{ticker}_mu_c_H{H}.pkl",        # per-class train means μ_c for expected return
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in required)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [29]:
def run_simulation(master_df: pd.DataFrame, payout_map: dict, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"\nStarting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    # precompute horizon returns if not already present
    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"
    if ret_col not in master_df.columns or tgt_col not in master_df.columns:
        print("Adding horizon targets to master_df...")
        master_df = add_horizon_targets(master_df, H=H, price_col='close')

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    # overlapping book
    open_positions = []  # each: {'ticker','invest','entry_date','exit_date'}
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                # realize H-day return measured from entry date
                row = master_df[(master_df['date'] == pos['entry_date']) & (master_df['ticker'] == pos['ticker'])]
                if not row.empty:
                    rH = row.iloc[0][ret_col]
                    if pd.notna(rH):
                        pnl = pos['invest'] * rH
                        total_pnl_today += pnl
                        print(f"[EXIT] {current_date}: {pos['ticker']} r={rH:.4f}, PnL=${pnl:.2f}")
                        capital += pos['invest'] + pnl  # release capital
                # else silently drop if missing
            else:
                still_open.append(pos)
        open_positions = still_open

        # equity at START (after settlements, before new entries)
        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # build prediction universe using info strictly before current_date
        historical_data = master_df[master_df['date'] < current_date]
        if i == 0:  # no yesterday slice for display
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                print("Retraining model for ticker:", ticker)
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)
        print(f"[SIM] {current_date}: built {len(daily_predictions_df)} predictions")
        if (not daily_predictions_df.empty and
            'predicted_prob' not in daily_predictions_df.columns and
            'calibrated_prediction' not in daily_predictions_df.columns):
            print("[WARN] predicted_prob missing from daily_predictions_df columns:",
                  sorted(daily_predictions_df.columns))


        # size raw trades via Kelly
        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df,
            payout_map,
            capital,
            sector_threshold=SECTOR_CONFIDENCE_THRESHOLD,
            kelly_fraction=KELLY_FRACTION,
        )
        if investment_decision_df.empty:
            print(f"[SIM] {current_date}: no trades proposed today.")
        else:
            print(f"[SIM] {current_date}: {len(investment_decision_df)} trades proposed.")

        # entry logic (allow_overlap controls laddering)
        exit_idx = i + H
        if exit_idx < len(unique_dates):
            exit_date = unique_dates[exit_idx]
        else:
            exit_date = None  # can't open new trades that we cannot exit within data

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            # ensure the column exists even if future changes rename it
            if 'predicted_prob' not in investment_decision_df.columns:
                if 'calibrated_prediction' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'calibrated_prediction': 'predicted_prob'}
                    )
                elif 'score' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'score': 'predicted_prob'}
                    )
                else:
                    # nothing to sort by
                    investment_decision_df = pd.DataFrame()

            if not investment_decision_df.empty:
                investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)


            # current exposures (post-settlement)
            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                # per-ticker ladder depth
                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue  # no overlapping allowed

                # base size from Kelly (already scaled by KELLY_FRACTION)
                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))  # vs equity

                # clamp by remaining budgets
                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                # lock capital and record position
                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})
                print(f"[TRADE] {current_date}: allocated ${amt:.2f} to {tkr} exiting on {exit_date}")

        # equity at END (after entries)
        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        # log the day
        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,  # cash only
            'capital_end': capital,                               # cash only
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,                # realized PnL today
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [30]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [31]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_features.parquet')

In [32]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)

columns_to_check = ['EMA_12', 'EMA_26','EMA_50','MACD_12_26_9','MACDh_12_26_9','MACDs_12_26_9','RSI_14','ATRr_14',
                    'STOCHRSIk_14_14_3_3','STOCHRSId_14_14_3_3','ATRr_14','BB_upper','BB_middle','BB_lower','OBV',
                    
                    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
                    # 'sector_ret_60d', 
                    'sector_vol_20d', 'sector_dispersion_1d',
                    # 'sector_rel_strength',
                    
                    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
                    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,sector_close_mean,sector_volume_mean,sector_ret_1d,sector_ret_5d,sector_ret_20d,sector_range,sector_vol_20d,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-12-13,75.878571,76.805717,75.114288,75.669998,156314900.0,AAPL,0.0,0.0,Consumer Goods,...,62.547998,19829560.0,-0.006623,-0.002006,0.056416,0.698142,0.008085,1554.712849,0.002853,0.005430
1,2012-12-14,73.535713,74.018570,72.225716,72.827141,252394800.0,AAPL,0.0,0.0,Consumer Goods,...,62.332714,29416920.0,-0.003442,-0.007518,0.045959,0.581286,0.008149,1550.069802,-0.007258,0.013233
2,2012-12-17,72.704285,74.285713,71.604286,74.118568,189401800.0,AAPL,0.0,0.0,Consumer Goods,...,62.372857,24089840.0,0.000644,-0.005215,0.039231,0.782143,0.008074,1562.391712,-0.017465,0.008229
3,2012-12-18,75.000000,76.414284,74.321426,76.271431,156421300.0,AAPL,0.0,0.0,Consumer Goods,...,62.862143,22884370.0,0.007845,-0.001921,0.021354,1.029286,0.006088,1572.637095,-0.030002,0.014815
4,2012-12-19,75.924286,76.242859,75.071426,75.187141,112342300.0,AAPL,0.0,0.0,Consumer Goods,...,62.554713,17363510.0,-0.004891,-0.006516,0.012048,0.846144,0.006179,1566.784191,-0.032355,0.010914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102535,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,61.025001,2428780.0,-0.001767,0.021766,-0.016313,0.593999,0.006240,3101.328695,-0.007883,0.005228
102536,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,61.073999,2215970.0,0.000803,0.015446,-0.022362,0.690000,0.005981,3102.507723,-0.016661,0.002030
102537,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,60.999000,2459030.0,-0.001228,0.010118,-0.024219,0.485999,0.005966,3128.753695,-0.017629,0.004873
102538,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,61.345000,4155760.0,0.005672,0.012494,-0.011871,0.461999,0.005997,3141.201722,-0.008376,0.006185
102539,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,61.787000,2870660.0,0.007205,0.010698,-0.007804,0.636000,0.006197,3136.813139,-0.001766,0.007085

In [33]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength']
Total number of features: 28

In [34]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,sector_close_mean,sector_volume_mean,sector_ret_1d,sector_ret_5d,sector_ret_20d,sector_range,sector_vol_20d,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-12-13,75.878571,76.805717,75.114288,75.669998,156314900.0,AAPL,0.0,0.0,Consumer Goods,...,62.547998,19829560.0,-0.006623,-0.002006,0.056416,0.698142,0.008085,1554.712849,0.002853,0.005430
1,2012-12-14,73.535713,74.018570,72.225716,72.827141,252394800.0,AAPL,0.0,0.0,Consumer Goods,...,62.332714,29416920.0,-0.003442,-0.007518,0.045959,0.581286,0.008149,1550.069802,-0.007258,0.013233
2,2012-12-17,72.704285,74.285713,71.604286,74.118568,189401800.0,AAPL,0.0,0.0,Consumer Goods,...,62.372857,24089840.0,0.000644,-0.005215,0.039231,0.782143,0.008074,1562.391712,-0.017465,0.008229
3,2012-12-18,75.000000,76.414284,74.321426,76.271431,156421300.0,AAPL,0.0,0.0,Consumer Goods,...,62.862143,22884370.0,0.007845,-0.001921,0.021354,1.029286,0.006088,1572.637095,-0.030002,0.014815
4,2012-12-19,75.924286,76.242859,75.071426,75.187141,112342300.0,AAPL,0.0,0.0,Consumer Goods,...,62.554713,17363510.0,-0.004891,-0.006516,0.012048,0.846144,0.006179,1566.784191,-0.032355,0.010914
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102535,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,61.025001,2428780.0,-0.001767,0.021766,-0.016313,0.593999,0.006240,3101.328695,-0.007883,0.005228
102536,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,61.073999,2215970.0,0.000803,0.015446,-0.022362,0.690000,0.005981,3102.507723,-0.016661,0.002030
102537,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,60.999000,2459030.0,-0.001228,0.010118,-0.024219,0.485999,0.005966,3128.753695,-0.017629,0.004873
102538,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,61.345000,4155760.0,0.005672,0.012494,-0.011871,0.461999,0.005997,3141.201722,-0.008376,0.006185
102539,2017-09-01,76.370003,76.849998,76.320000,76.570000,7340800.0,XOM,0.0,0.0,Basic Matierials,...,61.787000,2870660.0,0.007205,0.010698,-0.007804,0.636000,0.006197,3136.813139,-0.001766,0.007085

# Execute Pipeline

In [35]:

master_df_with_target = create_target_variable(master_df)
master_df_with_target = add_horizon_targets(master_df_with_target, H=1)
payout_map = calculate_historical_payouts(master_df_with_target)

initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df_with_target,
    payout_map,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=1,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Creating target variable...
Target variable created.

Starting simulation with 1100 initial training days... (H=1)
Starting predictions from day 1100 (after 1100 training days)

Simulating Trading Days:   0%|          | 0/88 [00:00<?, ?it/s]

Retraining model for ticker: AAPL
[TRAIN] AAPL: preparing data (H=1) with 1100 rows
[TRAIN] AAPL: built 1088 sequences (seq_len=12)
[TRAIN] AAPL: scaler fitted on 870 training sequences
[TRAIN] AAPL: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AAPL: sector feature mins = [-0.03295625 -0.09440794  0.00364845]
[TRAIN] AAPL: sector feature maxs = [0.03194691 0.05042416 0.01893123]
[TRAIN] AAPL: model n_features = 28
[CAL] AAPL: taus=[0.78 0.74 0.48 0.36 0.28] | temperature=0.871
[SAVE] AAPL: stored taus
[SAVE] AAPL: stored temperature scale 0.871
[SAVE] AAPL: artifacts persisted (H=1)
[CAL] AAPL: loaded taus [0.78 0.74 0.48 0.36 0.28]
[CAL] AAPL: temperature scaling 0.871
Retraining model for ticker: ABB
[TRAIN] ABB: preparing data (H=1) with 1100 rows
[TRAIN] ABB: built 1088 sequences (seq_len=12)
[TRAIN] ABB: scaler fitted on 870 training sequences
[TRAIN] ABB: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] ABB: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] ABB: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
[TRAIN] ABB: model n_features = 28
[CAL] ABB: taus=[0.8  0.78 0.68 0.42 0.48] | temperature=1.007
[SAVE] ABB: stored taus
[SAVE] ABB: stored temperature scale 1.007
[SAVE] ABB: artifacts persisted (H=1)
[CAL] ABB: loaded taus [0.8  0.78 0.68 0.42 0.48]
[CAL] ABB: temperature scaling 1.007
Retraining model for ticker: ABBV
[TRAIN] ABBV: preparing data (H=1) with 1039 rows
[TRAIN] ABBV: built 1027 sequences (seq_len=12)
[TRAIN] ABBV: scaler fitted on 821 training sequences
[TRAIN] ABBV: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] ABBV: sector feature mins = [-0.0410257  -0.11491243  0.00426767]
[TRAIN] ABBV: sector feature maxs = [0.04369867 0.0870226  0.02237914]
[TRAIN] ABBV: model n_features = 28
[CAL] ABBV: taus=[0.66 0.54 0.5  0.44 0.42] | temperature=2.229
[SAVE] ABBV: stored taus
[SAVE] ABBV: stored temperature scale 2.229
[SAVE] ABBV: artifacts persisted (H=1)
[CAL] ABBV: loaded taus [0.66 0.54 0.5  0.44 0.42]
[CAL] ABBV: temperature scaling 2.229
Retraining model for ticker: AEP
[TRAIN] AEP: preparing data (H=1) with 1100 rows
[TRAIN] AEP: built 1088 sequences (seq_len=12)
[TRAIN] AEP: scaler fitted on 870 training sequences
[TRAIN] AEP: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AEP: sector feature mins = [-0.04000807 -0.08164836  0.00362283]
[TRAIN] AEP: sector feature maxs = [0.03053178 0.06078573 0.01557388]
[TRAIN] AEP: model n_features = 28
[CAL] AEP: taus=[0.62 0.54 0.48 0.4  0.4 ] | temperature=2.364
[SAVE] AEP: stored taus
[SAVE] AEP: stored temperature scale 2.364
[SAVE] AEP: artifacts persisted (H=1)
[CAL] AEP: loaded taus [0.62 0.54 0.48 0.4  0.4 ]
[CAL] AEP: temperature scaling 2.364
Retraining model for ticker: AGFS
[TRAIN] AGFS: preparing data (H=1) with 563 rows
[TRAIN] AGFS: built 551 sequences (seq_len=12)
[TRAIN] AGFS: scaler fitted on 440 training sequences
[TRAIN] AGFS: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AGFS: sector feature mins = [-0.21470837 -0.24019047  0.00438277]
[TRAIN] AGFS: sector feature maxs = [0.35098106 0.39009354 0.07892018]
[TRAIN] AGFS: model n_features = 28
[CAL] AGFS: taus=[0.76 0.7  0.62 0.5  0.46] | temperature=1.821
[SAVE] AGFS: stored taus
[SAVE] AGFS: stored temperature scale 1.821
[SAVE] AGFS: artifacts persisted (H=1)
[CAL] AGFS: loaded taus [0.76 0.7  0.62 0.5  0.46]
[CAL] AGFS: temperature scaling 1.821
Retraining model for ticker: AMGN
[TRAIN] AMGN: preparing data (H=1) with 1100 rows
[TRAIN] AMGN: built 1088 sequences (seq_len=12)
[TRAIN] AMGN: scaler fitted on 870 training sequences
[TRAIN] AMGN: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AMGN: sector feature mins = [-0.0410257  -0.11491243  0.00426767]
[TRAIN] AMGN: sector feature maxs = [0.04369867 0.0870226  0.02237914]
[TRAIN] AMGN: model n_features = 28
[CAL] AMGN: taus=[0.76 0.56 0.52 0.5  0.48] | temperature=2.093
[SAVE] AMGN: stored taus
[SAVE] AMGN: stored temperature scale 2.093
[SAVE] AMGN: artifacts persisted (H=1)
[CAL] AMGN: loaded taus [0.76 0.56 0.52 0.5  0.48]
[CAL] AMGN: temperature scaling 2.093
Retraining model for ticker: AMZN
[TRAIN] AMZN: preparing data (H=1) with 1100 rows
[TRAIN] AMZN: built 1088 sequences (seq_len=12)
[TRAIN] AMZN: scaler fitted on 870 training sequences
[TRAIN] AMZN: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] AMZN: sector feature mins = [-0.05028515 -0.10466671  0.00567241]
[TRAIN] AMZN: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] AMZN: model n_features = 28
[CAL] AMZN: taus=[0.72 0.66 0.48 0.5  0.44] | temperature=1.414
[SAVE] AMZN: stored taus
[SAVE] AMZN: stored temperature scale 1.414
[SAVE] AMZN: artifacts persisted (H=1)
[CAL] AMZN: loaded taus [0.72 0.66 0.48 0.5  0.44]
[CAL] AMZN: temperature scaling 1.414
Retraining model for ticker: BA
[TRAIN] BA: preparing data (H=1) with 1100 rows
[TRAIN] BA: built 1088 sequences (seq_len=12)
[TRAIN] BA: scaler fitted on 870 training sequences
[TRAIN] BA: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BA: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] BA: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
[TRAIN] BA: model n_features = 28
[CAL] BA: taus=[0.8  0.74 0.52 0.42 0.28] | temperature=0.871
[SAVE] BA: stored taus
[SAVE] BA: stored temperature scale 0.871
[SAVE] BA: artifacts persisted (H=1)
[CAL] BA: loaded taus [0.8  0.74 0.52 0.42 0.28]
[CAL] BA: temperature scaling 0.871
Retraining model for ticker: BABA
[TRAIN] BABA: preparing data (H=1) with 607 rows
[TRAIN] BABA: built 595 sequences (seq_len=12)
[TRAIN] BABA: scaler fitted on 476 training sequences
[TRAIN] BABA: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BABA: sector feature mins = [-0.06810713 -0.10466671  0.00432136]
[TRAIN] BABA: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] BABA: model n_features = 28
[CAL] BABA: taus=[0.6  0.6  0.56 0.54 0.42] | temperature=0.736
[SAVE] BABA: stored taus
[SAVE] BABA: stored temperature scale 0.736
[SAVE] BABA: artifacts persisted (H=1)
[CAL] BABA: loaded taus [0.6  0.6  0.56 0.54 0.42]
[CAL] BABA: temperature scaling 0.736
Retraining model for ticker: BAC
[TRAIN] BAC: preparing data (H=1) with 1100 rows
[TRAIN] BAC: built 1088 sequences (seq_len=12)
[TRAIN] BAC: scaler fitted on 870 training sequences
[TRAIN] BAC: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BAC: sector feature mins = [-0.03209885 -0.0844463   0.00394133]
[TRAIN] BAC: sector feature maxs = [0.04134683 0.0680742  0.01782321]
[TRAIN] BAC: model n_features = 28
[CAL] BAC: taus=[0.78 0.76 0.5  0.4  0.66] | temperature=0.600
[SAVE] BAC: stored taus
[SAVE] BAC: stored temperature scale 0.600
[SAVE] BAC: artifacts persisted (H=1)
[CAL] BAC: loaded taus [0.78 0.76 0.5  0.4  0.66]
[CAL] BAC: temperature scaling 0.600
Retraining model for ticker: BBL
[TRAIN] BBL: preparing data (H=1) with 1100 rows
[TRAIN] BBL: built 1088 sequences (seq_len=12)
[TRAIN] BBL: scaler fitted on 870 training sequences
[TRAIN] BBL: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BBL: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BBL: sector feature maxs = [0.05341933 0.13994116 0.03044324]
[TRAIN] BBL: model n_features = 28
[CAL] BBL: taus=[0.7  0.62 0.54 0.5  0.48] | temperature=1.821
[SAVE] BBL: stored taus
[SAVE] BBL: stored temperature scale 1.821
[SAVE] BBL: artifacts persisted (H=1)
[CAL] BBL: loaded taus [0.7  0.62 0.54 0.5  0.48]
[CAL] BBL: temperature scaling 1.821
Retraining model for ticker: BCH
[TRAIN] BCH: preparing data (H=1) with 1100 rows
[TRAIN] BCH: built 1088 sequences (seq_len=12)
[TRAIN] BCH: scaler fitted on 870 training sequences
[TRAIN] BCH: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BCH: sector feature mins = [-0.03209885 -0.0844463   0.00394133]
[TRAIN] BCH: sector feature maxs = [0.04134683 0.0680742  0.01782321]
[TRAIN] BCH: model n_features = 28
[CAL] BCH: taus=[0.76 0.62 0.46 0.48 0.48] | temperature=1.821
[SAVE] BCH: stored taus
[SAVE] BCH: stored temperature scale 1.821
[SAVE] BCH: artifacts persisted (H=1)
[CAL] BCH: loaded taus [0.76 0.62 0.46 0.48 0.48]
[CAL] BCH: temperature scaling 1.821
Retraining model for ticker: BHP
[TRAIN] BHP: preparing data (H=1) with 1100 rows
[TRAIN] BHP: built 1088 sequences (seq_len=12)
[TRAIN] BHP: scaler fitted on 870 training sequences
[TRAIN] BHP: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BHP: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BHP: sector feature maxs = [0.05341933 0.13994116 0.03044324]
[TRAIN] BHP: model n_features = 28
[CAL] BHP: taus=[0.8  0.72 0.52 0.48 0.42] | temperature=1.143
[SAVE] BHP: stored taus
[SAVE] BHP: stored temperature scale 1.143
[SAVE] BHP: artifacts persisted (H=1)
[CAL] BHP: loaded taus [0.8  0.72 0.52 0.48 0.42]
[CAL] BHP: temperature scaling 1.143
Retraining model for ticker: BP
[TRAIN] BP: preparing data (H=1) with 1100 rows
[TRAIN] BP: built 1088 sequences (seq_len=12)
[TRAIN] BP: scaler fitted on 870 training sequences
[TRAIN] BP: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BP: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] BP: sector feature maxs = [0.05341933 0.13994116 0.03044324]
[TRAIN] BP: model n_features = 28
[CAL] BP: taus=[0.8  0.74 0.56 0.44 0.34] | temperature=1.007
[SAVE] BP: stored taus
[SAVE] BP: stored temperature scale 1.007
[SAVE] BP: artifacts persisted (H=1)
[CAL] BP: loaded taus [0.8  0.74 0.56 0.44 0.34]
[CAL] BP: temperature scaling 1.007
Retraining model for ticker: BRK-A
[TRAIN] BRK-A: preparing data (H=1) with 1100 rows
[TRAIN] BRK-A: built 1088 sequences (seq_len=12)
[TRAIN] BRK-A: scaler fitted on 870 training sequences
[TRAIN] BRK-A: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BRK-A: sector feature mins = [-0.03209885 -0.0844463   0.00394133]
[TRAIN] BRK-A: sector feature maxs = [0.04134683 0.0680742  0.01782321]
[TRAIN] BRK-A: model n_features = 28
[CAL] BRK-A: taus=[0.78 0.8  0.52 0.52 0.46] | temperature=0.736
[SAVE] BRK-A: stored taus
[SAVE] BRK-A: stored temperature scale 0.736
[SAVE] BRK-A: artifacts persisted (H=1)
[CAL] BRK-A: loaded taus [0.78 0.8  0.52 0.52 0.46]
[CAL] BRK-A: temperature scaling 0.736
Retraining model for ticker: BSAC
[TRAIN] BSAC: preparing data (H=1) with 1100 rows
[TRAIN] BSAC: built 1088 sequences (seq_len=12)
[TRAIN] BSAC: scaler fitted on 870 training sequences
[TRAIN] BSAC: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BSAC: sector feature mins = [-0.03209885 -0.0844463   0.00394133]
[TRAIN] BSAC: sector feature maxs = [0.04134683 0.0680742  0.01782321]
[TRAIN] BSAC: model n_features = 28
[CAL] BSAC: taus=[0.2  0.46 0.38 0.32 0.28] | temperature=1.007
[SAVE] BSAC: stored taus
[SAVE] BSAC: stored temperature scale 1.007
[SAVE] BSAC: artifacts persisted (H=1)
[CAL] BSAC: loaded taus [0.2  0.46 0.38 0.32 0.28]
[CAL] BSAC: temperature scaling 1.007
Retraining model for ticker: BUD
[TRAIN] BUD: preparing data (H=1) with 1100 rows
[TRAIN] BUD: built 1088 sequences (seq_len=12)
[TRAIN] BUD: scaler fitted on 870 training sequences
[TRAIN] BUD: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] BUD: sector feature mins = [-0.03295625 -0.09440794  0.00364845]
[TRAIN] BUD: sector feature maxs = [0.03194691 0.05042416 0.01893123]
[TRAIN] BUD: model n_features = 28
[CAL] BUD: taus=[0.74 0.66 0.58 0.5  0.5 ] | temperature=2.364
[SAVE] BUD: stored taus
[SAVE] BUD: stored temperature scale 2.364
[SAVE] BUD: artifacts persisted (H=1)
[CAL] BUD: loaded taus [0.74 0.66 0.58 0.5  0.5 ]
[CAL] BUD: temperature scaling 2.364
Retraining model for ticker: C
[TRAIN] C: preparing data (H=1) with 1100 rows
[TRAIN] C: built 1088 sequences (seq_len=12)
[TRAIN] C: scaler fitted on 870 training sequences
[TRAIN] C: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] C: sector feature mins = [-0.03209885 -0.0844463   0.00394133]
[TRAIN] C: sector feature maxs = [0.04134683 0.0680742  0.01782321]
[TRAIN] C: model n_features = 28
[CAL] C: taus=[0.74 0.78 0.54 0.5  0.56] | temperature=0.736
[SAVE] C: stored taus
[SAVE] C: stored temperature scale 0.736
[SAVE] C: artifacts persisted (H=1)
[CAL] C: loaded taus [0.74 0.78 0.54 0.5  0.56]
[CAL] C: temperature scaling 0.736
Retraining model for ticker: CAT
[TRAIN] CAT: preparing data (H=1) with 1100 rows
[TRAIN] CAT: built 1088 sequences (seq_len=12)
[TRAIN] CAT: scaler fitted on 870 training sequences
[TRAIN] CAT: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CAT: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] CAT: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
[TRAIN] CAT: model n_features = 28
[CAL] CAT: taus=[0.8  0.78 0.58 0.5  0.44] | temperature=0.871
[SAVE] CAT: stored taus
[SAVE] CAT: stored temperature scale 0.871
[SAVE] CAT: artifacts persisted (H=1)
[CAL] CAT: loaded taus [0.8  0.78 0.58 0.5  0.44]
[CAL] CAT: temperature scaling 0.871
Retraining model for ticker: CELG
[TRAIN] CELG: preparing data (H=1) with 1100 rows
[TRAIN] CELG: built 1088 sequences (seq_len=12)
[TRAIN] CELG: scaler fitted on 870 training sequences
[TRAIN] CELG: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CELG: sector feature mins = [-0.0410257  -0.11491243  0.00426767]
[TRAIN] CELG: sector feature maxs = [0.04369867 0.0870226  0.02237914]
[TRAIN] CELG: model n_features = 28
[CAL] CELG: taus=[0.68 0.54 0.52 0.46 0.4 ] | temperature=1.414
[SAVE] CELG: stored taus
[SAVE] CELG: stored temperature scale 1.414
[SAVE] CELG: artifacts persisted (H=1)
[CAL] CELG: loaded taus [0.68 0.54 0.52 0.46 0.4 ]
[CAL] CELG: temperature scaling 1.414
Retraining model for ticker: CHL
[TRAIN] CHL: preparing data (H=1) with 1100 rows
[TRAIN] CHL: built 1088 sequences (seq_len=12)
[TRAIN] CHL: scaler fitted on 870 training sequences
[TRAIN] CHL: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CHL: sector feature mins = [-0.0442555  -0.11070618  0.00543296]
[TRAIN] CHL: sector feature maxs = [0.09751891 0.16866831 0.02562898]
[TRAIN] CHL: model n_features = 28
[CAL] CHL: taus=[0.8  0.66 0.5  0.38 0.36] | temperature=1.143
[SAVE] CHL: stored taus
[SAVE] CHL: stored temperature scale 1.143
[SAVE] CHL: artifacts persisted (H=1)
[CAL] CHL: loaded taus [0.8  0.66 0.5  0.38 0.36]
[CAL] CHL: temperature scaling 1.143
Retraining model for ticker: CHTR
[TRAIN] CHTR: preparing data (H=1) with 1100 rows
[TRAIN] CHTR: built 1088 sequences (seq_len=12)
[TRAIN] CHTR: scaler fitted on 870 training sequences
[TRAIN] CHTR: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CHTR: sector feature mins = [-0.05028515 -0.10466671  0.00567241]
[TRAIN] CHTR: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] CHTR: model n_features = 28
[CAL] CHTR: taus=[0.8  0.54 0.52 0.42 0.42] | temperature=1.279
[SAVE] CHTR: stored taus
[SAVE] CHTR: stored temperature scale 1.279
[SAVE] CHTR: artifacts persisted (H=1)
[CAL] CHTR: loaded taus [0.8  0.54 0.52 0.42 0.42]
[CAL] CHTR: temperature scaling 1.279
Retraining model for ticker: CMCSA
[TRAIN] CMCSA: preparing data (H=1) with 1100 rows
[TRAIN] CMCSA: built 1088 sequences (seq_len=12)
[TRAIN] CMCSA: scaler fitted on 870 training sequences
[TRAIN] CMCSA: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CMCSA: sector feature mins = [-0.05028515 -0.10466671  0.00567241]
[TRAIN] CMCSA: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] CMCSA: model n_features = 28
[CAL] CMCSA: taus=[0.2  0.8  0.64 0.46 0.36] | temperature=0.736
[SAVE] CMCSA: stored taus
[SAVE] CMCSA: stored temperature scale 0.736
[SAVE] CMCSA: artifacts persisted (H=1)
[CAL] CMCSA: loaded taus [0.2  0.8  0.64 0.46 0.36]
[CAL] CMCSA: temperature scaling 0.736
Retraining model for ticker: CODI
[TRAIN] CODI: preparing data (H=1) with 1100 rows
[TRAIN] CODI: built 1088 sequences (seq_len=12)
[TRAIN] CODI: scaler fitted on 870 training sequences
[TRAIN] CODI: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CODI: sector feature mins = [-0.10312178 -0.11217154  0.00438277]
[TRAIN] CODI: sector feature maxs = [0.07760173 0.18492148 0.03571163]
[TRAIN] CODI: model n_features = 28
[CAL] CODI: taus=[0.2  0.78 0.66 0.48 0.36] | temperature=0.736
[SAVE] CODI: stored taus
[SAVE] CODI: stored temperature scale 0.736
[SAVE] CODI: artifacts persisted (H=1)
[CAL] CODI: loaded taus [0.2  0.78 0.66 0.48 0.36]
[CAL] CODI: temperature scaling 0.736
Retraining model for ticker: CSCO
[TRAIN] CSCO: preparing data (H=1) with 1100 rows
[TRAIN] CSCO: built 1088 sequences (seq_len=12)
[TRAIN] CSCO: scaler fitted on 870 training sequences
[TRAIN] CSCO: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CSCO: sector feature mins = [-0.0442555  -0.11070618  0.00543296]
[TRAIN] CSCO: sector feature maxs = [0.09751891 0.16866831 0.02562898]
[TRAIN] CSCO: model n_features = 28
[CAL] CSCO: taus=[0.8  0.56 0.44 0.32 0.5 ] | temperature=0.736
[SAVE] CSCO: stored taus
[SAVE] CSCO: stored temperature scale 0.736
[SAVE] CSCO: artifacts persisted (H=1)
[CAL] CSCO: loaded taus [0.8  0.56 0.44 0.32 0.5 ]
[CAL] CSCO: temperature scaling 0.736
Retraining model for ticker: CVX
[TRAIN] CVX: preparing data (H=1) with 1100 rows
[TRAIN] CVX: built 1088 sequences (seq_len=12)
[TRAIN] CVX: scaler fitted on 870 training sequences
[TRAIN] CVX: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] CVX: sector feature mins = [-0.05743685 -0.13001529  0.00413216]
[TRAIN] CVX: sector feature maxs = [0.05341933 0.13994116 0.03044324]
[TRAIN] CVX: model n_features = 28
[CAL] CVX: taus=[0.8  0.74 0.52 0.4  0.3 ] | temperature=0.736
[SAVE] CVX: stored taus
[SAVE] CVX: stored temperature scale 0.736
[SAVE] CVX: artifacts persisted (H=1)
[CAL] CVX: loaded taus [0.8  0.74 0.52 0.4  0.3 ]
[CAL] CVX: temperature scaling 0.736
Retraining model for ticker: D
[TRAIN] D: preparing data (H=1) with 1100 rows
[TRAIN] D: built 1088 sequences (seq_len=12)
[TRAIN] D: scaler fitted on 870 training sequences
[TRAIN] D: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] D: sector feature mins = [-0.04000807 -0.08164836  0.00362283]
[TRAIN] D: sector feature maxs = [0.03053178 0.06078573 0.01557388]
[TRAIN] D: model n_features = 28
[CAL] D: taus=[0.2  0.74 0.52 0.38 0.32] | temperature=0.736
[SAVE] D: stored taus
[SAVE] D: stored temperature scale 0.736
[SAVE] D: artifacts persisted (H=1)
[CAL] D: loaded taus [0.2  0.74 0.52 0.38 0.32]
[CAL] D: temperature scaling 0.736
Retraining model for ticker: DHR
[TRAIN] DHR: preparing data (H=1) with 1100 rows
[TRAIN] DHR: built 1088 sequences (seq_len=12)
[TRAIN] DHR: scaler fitted on 870 training sequences
[TRAIN] DHR: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] DHR: sector feature mins = [-0.03072437 -0.09246348  0.00306991]
[TRAIN] DHR: sector feature maxs = [0.03096942 0.06308523 0.0175623 ]
[TRAIN] DHR: model n_features = 28
[CAL] DHR: taus=[0.8  0.7  0.46 0.28 0.2 ] | temperature=0.600
[SAVE] DHR: stored taus
[SAVE] DHR: stored temperature scale 0.600
[SAVE] DHR: artifacts persisted (H=1)
[CAL] DHR: loaded taus [0.8  0.7  0.46 0.28 0.2 ]
[CAL] DHR: temperature scaling 0.600
Retraining model for ticker: DIS
[TRAIN] DIS: preparing data (H=1) with 1100 rows
[TRAIN] DIS: built 1088 sequences (seq_len=12)
[TRAIN] DIS: scaler fitted on 870 training sequences
[TRAIN] DIS: scaler.n_features_in_ = 28, len(feature_cols) = 28
[TRAIN] DIS: sector feature mins = [-0.05028515 -0.10466671  0.00567241]
[TRAIN] DIS: sector feature maxs = [0.06055893 0.14495416 0.025178  ]
[TRAIN] DIS: model n_features = 28
[CAL] DIS: taus=[0.2  0.54 0.48 0.4  0.42] | temperature=0.736
[SAVE] DIS: stored taus
[SAVE] DIS: stored temperature scale 0.736
[SAVE] DIS: artifacts persisted (H=1)
[CAL] DIS: loaded taus [0.2  0.54 0.48 0.4  0.42]
[CAL] DIS: temperature scaling 0.736
Retraining model for ticker: DUK
[TRAIN] DUK: preparing data (H=1) with 1100 rows
[TRAIN] DUK: built 1088 sequences (seq_len=12)
[TRAIN] DUK: scaler fitted on 870 training sequences

Simulating Trading Days:   1%|          | 1/88 [14:48<21:27:52, 888.18s/it]

[CAL] XOM: taus=[0.8  0.5  0.48 0.34 0.32] | temperature=0.736
[SAVE] XOM: stored taus
[SAVE] XOM: stored temperature scale 0.736
[SAVE] XOM: artifacts persisted (H=1)
[CAL] XOM: loaded taus [0.8  0.5  0.48 0.34 0.32]
[CAL] XOM: temperature scaling 0.736
[SIM] 2017-04-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.717, kelly=0.454) with $4543.98 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.782, kelly=0.582) with $5821.25 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.820, kelly=0.642) with $6424.29 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.747, kelly=0.515) with $5149.32 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.596, kelly=0.203) with $2032.63 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.787, kelly=0.567) with $5669.93 allocation
[PORT] Sector Services: selecting WMT (p_up=0.808, kelly=0.610) with $6102.50 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.620, kelly=0.232) with $2320.64 allocation
[PORT] Sector Utilities: selecting DUK (p_up=0.838, kelly=0.662) with $6620.89 allocation
[SIM] 2017-04-28 00:00:00: 9 trades proposed.
[TRADE] 2017-04-28 00:00:00: allocated $6620.89 to DUK exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $6424.29 to PM exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $6102.50 to WMT exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $5669.93 to ABB exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $5182.39 to PICO exiting on 2017-05-01 00:00:00
[EXIT] 2017-05-01 00:00:00: DUK r=-0.0052, PnL=$-34.51
[EXIT] 2017-05-01 00:00:00: PM r=-0.0026, PnL=$-16.81
[EXIT] 2017-05-01 00:00:00: WMT r=0.0007, PnL=$4.06
[EXIT] 2017-05-01 00:00:00: ABB r=-0.0012, PnL=$-6.91
[EXIT] 2017-05-01 00:00:00: PICO r=0.0435, PnL=$225.32

Simulating Trading Days:   2%|▏         | 2/88 [14:49<8:45:33, 366.66s/it]

[SIM] 2017-05-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.743, kelly=0.505) with $5054.03 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.772, kelly=0.563) with $5637.90 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.823, kelly=0.648) with $6490.07 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.760, kelly=0.540) with $5412.54 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.588, kelly=0.188) with $1885.36 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.774, kelly=0.539) with $5403.59 allocation
[PORT] Sector Services: selecting WMT (p_up=0.809, kelly=0.613) with $6136.72 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.635, kelly=0.263) with $2637.08 allocation
[PORT] Sector Utilities: selecting DUK (p_up=0.814, kelly=0.611) with $6120.53 allocation
[SIM] 2017-05-01 00:00:00: 9 trades proposed.
[TRADE] 2017-05-01 00:00:00: allocated $6490.07 to PM exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $6120.53 to DUK exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $6136.72 to WMT exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $5403.59 to ABB exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $5637.90 to PICO exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $262.53 to BAC exiting on 2017-05-02 00:00:00
[EXIT] 2017-05-02 00:00:00: PM r=-0.0007, PnL=$-4.70
[EXIT] 2017-05-02 00:00:00: DUK r=0.0039, PnL=$23.86
[EXIT] 2017-05-02 00:00:00: WMT r=0.0039, PnL=$23.66
[EXIT] 2017-05-02 00:00:00: ABB r=0.0053, PnL=$28.59
[EXIT] 2017-05-02 00:00:00: PICO r=-0.0149, PnL=$-83.90
[EXIT] 2017-05-02 00:00:00: BAC r=-0.0034, PnL=$-0.89

Simulating Trading Days:   3%|▎         | 3/88 [14:51<4:43:22, 200.03s/it]

[SIM] 2017-05-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.759, kelly=0.536) with $5366.89 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.760, kelly=0.540) with $5411.96 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.823, kelly=0.648) with $6485.80 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.762, kelly=0.545) with $5453.87 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.583, kelly=0.178) with $1780.28 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.750, kelly=0.491) with $4921.87 allocation
[PORT] Sector Services: selecting WMT (p_up=0.803, kelly=0.599) with $5995.38 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.641, kelly=0.275) with $2752.35 allocation
[PORT] Sector Utilities: selecting DUK (p_up=0.780, kelly=0.541) with $5417.34 allocation
[SIM] 2017-05-02 00:00:00: 9 trades proposed.
[TRADE] 2017-05-02 00:00:00: allocated $6485.80 to PM exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $5995.38 to WMT exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $5417.34 to DUK exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $5453.87 to BAC exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $5411.96 to PICO exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $1282.99 to SLB exiting on 2017-05-03 00:00:00
[EXIT] 2017-05-03 00:00:00: PM r=0.0013, PnL=$8.22
[EXIT] 2017-05-03 00:00:00: WMT r=0.0032, PnL=$19.05
[EXIT] 2017-05-03 00:00:00: DUK r=-0.0042, PnL=$-23.01
[EXIT] 2017-05-03 00:00:00: BAC r=0.0102, PnL=$55.63
[EXIT] 2017-05-03 00:00:00: PICO r=0.0091, PnL=$49.05
[EXIT] 2017-05-03 00:00:00: SLB r=0.0011, PnL=$1.44

Simulating Trading Days:   5%|▍         | 4/88 [14:53<2:50:19, 121.66s/it]

[SIM] 2017-05-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.779, kelly=0.574) with $5759.57 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.731, kelly=0.485) with $4861.43 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.819, kelly=0.639) with $6406.74 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.764, kelly=0.547) with $5481.68 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.579, kelly=0.170) with $1707.46 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.722, kelly=0.434) with $4354.38 allocation
[PORT] Sector Services: selecting WMT (p_up=0.796, kelly=0.585) with $5869.87 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.637, kelly=0.267) with $2681.61 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.698, kelly=0.384) with $3848.12 allocation
[SIM] 2017-05-03 00:00:00: 9 trades proposed.
[TRADE] 2017-05-03 00:00:00: allocated $6406.74 to PM exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $5869.87 to WMT exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $5759.57 to SLB exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $5481.68 to BAC exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $4861.43 to PICO exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $1701.14 to ABB exiting on 2017-05-04 00:00:00
[EXIT] 2017-05-04 00:00:00: PM r=0.0053, PnL=$34.17
[EXIT] 2017-05-04 00:00:00: WMT r=0.0077, PnL=$44.94
[EXIT] 2017-05-04 00:00:00: SLB r=-0.0082, PnL=$-47.51
[EXIT] 2017-05-04 00:00:00: BAC r=0.0034, PnL=$18.45
[EXIT] 2017-05-04 00:00:00: PICO r=-0.0060, PnL=$-29.11
[EXIT] 2017-05-04 00:00:00: ABB r=0.0073, PnL=$12.44

Simulating Trading Days:   6%|▌         | 5/88 [14:54<1:48:21, 78.33s/it]

[SIM] 2017-05-04 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.799, kelly=0.612) with $6136.58 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.782, kelly=0.572) with $5737.36 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.812, kelly=0.626) with $6276.80 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.757, kelly=0.533) with $5348.36 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.577, kelly=0.166) with $1666.01 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.711, kelly=0.412) with $4134.58 allocation
[PORT] Sector Services: selecting WMT (p_up=0.792, kelly=0.578) with $5793.49 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.657, kelly=0.317) with $3179.04 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.709, kelly=0.406) with $4071.10 allocation
[SIM] 2017-05-04 00:00:00: 9 trades proposed.
[TRADE] 2017-05-04 00:00:00: allocated $6276.80 to PM exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $6136.58 to SLB exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $5793.49 to WMT exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $5737.36 to CODI exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $5348.36 to BAC exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $797.86 to ABB exiting on 2017-05-05 00:00:00
[EXIT] 2017-05-05 00:00:00: PM r=0.0094, PnL=$59.27
[EXIT] 2017-05-05 00:00:00: SLB r=0.0145, PnL=$89.10
[EXIT] 2017-05-05 00:00:00: WMT r=0.0021, PnL=$12.14
[EXIT] 2017-05-05 00:00:00: CODI r=-0.0091, PnL=$-52.48
[EXIT] 2017-05-05 00:00:00: BAC r=-0.0046, PnL=$-24.67
[EXIT] 2017-05-05 00:00:00: ABB r=0.0048, PnL=$3.86

Simulating Trading Days:   7%|▋         | 6/88 [14:55<1:11:18, 52.17s/it]

[SIM] 2017-05-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.822, kelly=0.657) with $6595.63 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.792, kelly=0.591) with $5930.79 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.807, kelly=0.616) with $6183.08 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.755, kelly=0.531) with $5326.38 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.575, kelly=0.161) with $1620.11 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.720, kelly=0.431) with $4329.19 allocation
[PORT] Sector Services: selecting WMT (p_up=0.792, kelly=0.577) with $5793.02 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.679, kelly=0.360) with $3612.54 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.715, kelly=0.418) with $4201.01 allocation
[SIM] 2017-05-05 00:00:00: 9 trades proposed.
[TRADE] 2017-05-05 00:00:00: allocated $6595.63 to SLB exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $6183.08 to PM exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $5793.02 to WMT exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $5930.79 to CODI exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $5326.38 to BAC exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $287.74 to ABB exiting on 2017-05-08 00:00:00
[EXIT] 2017-05-08 00:00:00: SLB r=0.0035, PnL=$22.91
[EXIT] 2017-05-08 00:00:00: PM r=0.0034, PnL=$20.93
[EXIT] 2017-05-08 00:00:00: WMT r=-0.0050, PnL=$-28.78
[EXIT] 2017-05-08 00:00:00: CODI r=-0.0031, PnL=$-18.25
[EXIT] 2017-05-08 00:00:00: BAC r=0.0093, PnL=$49.36
[EXIT] 2017-05-08 00:00:00: ABB r=-0.0112, PnL=$-3.23

Simulating Trading Days:   8%|▊         | 7/88 [14:57<48:03, 35.59s/it]

[SIM] 2017-05-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.832, kelly=0.676) with $6792.02 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.807, kelly=0.620) with $6226.16 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.800, kelly=0.602) with $6045.17 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.745, kelly=0.511) with $5129.30 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.574, kelly=0.160) with $1605.70 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.722, kelly=0.435) with $4370.96 allocation
[PORT] Sector Services: selecting WMT (p_up=0.799, kelly=0.590) with $5930.39 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.679, kelly=0.360) with $3619.08 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.716, kelly=0.421) with $4228.74 allocation
[SIM] 2017-05-08 00:00:00: 9 trades proposed.
[TRADE] 2017-05-08 00:00:00: allocated $6792.02 to SLB exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $6226.16 to CODI exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $6045.17 to PM exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $5930.39 to WMT exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $5129.30 to BAC exiting on 2017-05-09 00:00:00
[EXIT] 2017-05-09 00:00:00: SLB r=0.0008, PnL=$5.64
[EXIT] 2017-05-09 00:00:00: CODI r=0.0000, PnL=$0.00
[EXIT] 2017-05-09 00:00:00: PM r=-0.0062, PnL=$-37.57
[EXIT] 2017-05-09 00:00:00: WMT r=0.0079, PnL=$46.74
[EXIT] 2017-05-09 00:00:00: BAC r=0.0008, PnL=$4.28

Simulating Trading Days:   9%|▉         | 8/88 [14:58<32:56, 24.70s/it]

[SIM] 2017-05-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.827, kelly=0.666) with $6688.39 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.823, kelly=0.652) with $6551.92 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.791, kelly=0.584) with $5866.64 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.751, kelly=0.524) with $5258.72 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.576, kelly=0.163) with $1640.27 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.723, kelly=0.436) with $4381.46 allocation
[PORT] Sector Services: selecting WMT (p_up=0.806, kelly=0.605) with $6080.08 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.662, kelly=0.327) with $3285.81 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.713, kelly=0.415) with $4168.48 allocation
[SIM] 2017-05-09 00:00:00: 9 trades proposed.
[TRADE] 2017-05-09 00:00:00: allocated $6688.39 to SLB exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $6551.92 to CODI exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $6080.08 to WMT exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $5866.64 to PM exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $4948.22 to BAC exiting on 2017-05-10 00:00:00
[EXIT] 2017-05-10 00:00:00: SLB r=0.0054, PnL=$36.09
[EXIT] 2017-05-10 00:00:00: CODI r=0.0031, PnL=$20.22
[EXIT] 2017-05-10 00:00:00: WMT r=-0.0003, PnL=$-1.59
[EXIT] 2017-05-10 00:00:00: PM r=-0.0098, PnL=$-57.65
[EXIT] 2017-05-10 00:00:00: BAC r=0.0071, PnL=$35.08

Simulating Trading Days:  10%|█         | 9/88 [15:00<22:55, 17.41s/it]

[SIM] 2017-05-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.812, kelly=0.637) with $6401.69 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.834, kelly=0.673) with $6761.51 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.784, kelly=0.571) with $5734.42 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.734, kelly=0.471) with $4727.77 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.655, kelly=0.338) with $3394.01 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.715, kelly=0.420) with $4219.47 allocation
[PORT] Sector Services: selecting WMT (p_up=0.804, kelly=0.602) with $6044.23 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.633, kelly=0.270) with $2709.25 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.710, kelly=0.409) with $4105.12 allocation
[SIM] 2017-05-10 00:00:00: 9 trades proposed.
[TRADE] 2017-05-10 00:00:00: allocated $6761.51 to CODI exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $6401.69 to SLB exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $6044.23 to WMT exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $5734.42 to PM exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $4727.77 to HSBC exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $475.27 to ABB exiting on 2017-05-11 00:00:00
[EXIT] 2017-05-11 00:00:00: CODI r=-0.0031, PnL=$-20.80
[EXIT] 2017-05-11 00:00:00: SLB r=-0.0122, PnL=$-78.40
[EXIT] 2017-05-11 00:00:00: WMT r=-0.0074, PnL=$-44.92
[EXIT] 2017-05-11 00:00:00: PM r=0.0032, PnL=$18.63
[EXIT] 2017-05-11 00:00:00: HSBC r=0.0032, PnL=$15.24
[EXIT] 2017-05-11 00:00:00: ABB r=0.0000, PnL=$0.00

Simulating Trading Days:  11%|█▏        | 10/88 [15:01<16:12, 12.47s/it]

[SIM] 2017-05-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.785, kelly=0.584) with $5864.84 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.841, kelly=0.688) with $6904.99 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.782, kelly=0.566) with $5677.35 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.733, kelly=0.468) with $4699.03 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.703, kelly=0.430) with $4311.96 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.703, kelly=0.397) with $3981.54 allocation
[PORT] Sector Services: selecting BABA (p_up=0.809, kelly=0.638) with $6403.80 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.532, kelly=0.120) with $1202.39 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.705, kelly=0.398) with $3994.26 allocation
[SIM] 2017-05-11 00:00:00: 9 trades proposed.
[TRADE] 2017-05-11 00:00:00: allocated $6904.99 to CODI exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $6403.80 to BABA exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $5864.84 to SLB exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $5677.35 to PM exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $4699.03 to HSBC exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $561.80 to EXC exiting on 2017-05-12 00:00:00
[EXIT] 2017-05-12 00:00:00: CODI r=0.0031, PnL=$21.31
[EXIT] 2017-05-12 00:00:00: BABA r=0.0015, PnL=$9.59
[EXIT] 2017-05-12 00:00:00: SLB r=-0.0106, PnL=$-62.10
[EXIT] 2017-05-12 00:00:00: PM r=0.0047, PnL=$26.55
[EXIT] 2017-05-12 00:00:00: HSBC r=0.0037, PnL=$17.26
[EXIT] 2017-05-12 00:00:00: EXC r=0.0188, PnL=$10.57

Simulating Trading Days:  12%|█▎        | 11/88 [15:02<11:38,  9.07s/it]

[SIM] 2017-05-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.753, kelly=0.524) with $5256.41 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.843, kelly=0.692) with $6948.21 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.781, kelly=0.564) with $5661.19 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.732, kelly=0.466) with $4680.20 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.736, kelly=0.493) with $4945.57 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.682, kelly=0.352) with $3538.75 allocation
[PORT] Sector Services: selecting BABA (p_up=0.805, kelly=0.631) with $6330.66 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.534, kelly=0.123) with $1237.46 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.705, kelly=0.397) with $3990.05 allocation
[SIM] 2017-05-12 00:00:00: 9 trades proposed.
[TRADE] 2017-05-12 00:00:00: allocated $6948.21 to CODI exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $6330.66 to BABA exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $5661.19 to PM exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $5256.41 to SLB exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $4945.57 to PFE exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $976.72 to HSBC exiting on 2017-05-15 00:00:00
[EXIT] 2017-05-15 00:00:00: CODI r=0.0123, PnL=$85.52
[EXIT] 2017-05-15 00:00:00: BABA r=0.0088, PnL=$55.76
[EXIT] 2017-05-15 00:00:00: PM r=0.0058, PnL=$32.94
[EXIT] 2017-05-15 00:00:00: SLB r=0.0138, PnL=$72.53
[EXIT] 2017-05-15 00:00:00: PFE r=0.0033, PnL=$16.48
[EXIT] 2017-05-15 00:00:00: HSBC r=0.0114, PnL=$11.17

Simulating Trading Days:  14%|█▎        | 12/88 [15:04<08:33,  6.75s/it]

[SIM] 2017-05-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.726, kelly=0.471) with $4738.28 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.836, kelly=0.678) with $6824.75 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.779, kelly=0.559) with $5629.40 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.728, kelly=0.458) with $4614.96 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.744, kelly=0.507) with $5108.43 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.665, kelly=0.319) with $3213.75 allocation
[PORT] Sector Services: selecting BABA (p_up=0.796, kelly=0.613) with $6170.94 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.536, kelly=0.127) with $1280.63 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.699, kelly=0.386) with $3882.70 allocation
[SIM] 2017-05-15 00:00:00: 9 trades proposed.
[TRADE] 2017-05-15 00:00:00: allocated $6824.75 to CODI exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $6170.94 to BABA exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $5629.40 to PM exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $5108.43 to PFE exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $4614.96 to HSBC exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $1852.60 to SLB exiting on 2017-05-16 00:00:00
[EXIT] 2017-05-16 00:00:00: CODI r=-0.0061, PnL=$-41.49
[EXIT] 2017-05-16 00:00:00: BABA r=0.0216, PnL=$133.18
[EXIT] 2017-05-16 00:00:00: PM r=0.0103, PnL=$58.12
[EXIT] 2017-05-16 00:00:00: PFE r=-0.0157, PnL=$-80.21
[EXIT] 2017-05-16 00:00:00: HSBC r=0.0041, PnL=$18.78
[EXIT] 2017-05-16 00:00:00: SLB r=-0.0087, PnL=$-16.21

Simulating Trading Days:  15%|█▍        | 13/88 [15:05<06:24,  5.13s/it]

[SIM] 2017-05-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.697, kelly=0.415) with $4176.06 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.823, kelly=0.652) with $6570.99 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.773, kelly=0.549) with $5529.16 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.725, kelly=0.452) with $4555.67 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.727, kelly=0.476) with $4792.90 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.659, kelly=0.347) with $3497.46 allocation
[PORT] Sector Services: selecting BABA (p_up=0.784, kelly=0.591) with $5954.50 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.538, kelly=0.131) with $1324.22 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.716, kelly=0.422) with $4253.97 allocation
[SIM] 2017-05-16 00:00:00: 9 trades proposed.
[TRADE] 2017-05-16 00:00:00: allocated $6570.99 to CODI exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $5954.50 to BABA exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $5529.16 to PM exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $4792.90 to PFE exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $4555.67 to HSBC exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $2819.51 to SRE exiting on 2017-05-17 00:00:00
[EXIT] 2017-05-17 00:00:00: CODI r=-0.0092, PnL=$-60.28
[EXIT] 2017-05-17 00:00:00: BABA r=-0.0266, PnL=$-158.44
[EXIT] 2017-05-17 00:00:00: PM r=0.0020, PnL=$11.20
[EXIT] 2017-05-17 00:00:00: PFE r=-0.0113, PnL=$-54.40
[EXIT] 2017-05-17 00:00:00: HSBC r=-0.0295, PnL=$-134.38
[EXIT] 2017-05-17 00:00:00: SRE r=-0.0005, PnL=$-1.53

Simulating Trading Days:  16%|█▌        | 14/88 [15:07<04:57,  4.02s/it]

[SIM] 2017-05-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.668, kelly=0.359) with $3606.89 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.686, kelly=0.374) with $3750.30 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.767, kelly=0.537) with $5387.39 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.725, kelly=0.453) with $4542.99 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.744, kelly=0.507) with $5087.56 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.605, kelly=0.223) with $2237.57 allocation
[PORT] Sector Services: selecting BABA (p_up=0.766, kelly=0.555) with $5571.19 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.539, kelly=0.134) with $1341.90 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.728, kelly=0.448) with $4494.04 allocation
[SIM] 2017-05-17 00:00:00: 9 trades proposed.
[TRADE] 2017-05-17 00:00:00: allocated $5387.39 to PM exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $5571.19 to BABA exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $5087.56 to PFE exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $4494.04 to SRE exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $4542.99 to HSBC exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $3750.30 to GMRE exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $1269.92 to SLB exiting on 2017-05-18 00:00:00
[EXIT] 2017-05-18 00:00:00: PM r=-0.0015, PnL=$-8.05
[EXIT] 2017-05-18 00:00:00: BABA r=0.0046, PnL=$25.38
[EXIT] 2017-05-18 00:00:00: PFE r=-0.0003, PnL=$-1.58
[EXIT] 2017-05-18 00:00:00: SRE r=0.0018, PnL=$8.13
[EXIT] 2017-05-18 00:00:00: HSBC r=0.0005, PnL=$2.11
[EXIT] 2017-05-18 00:00:00: GMRE r=0.0149, PnL=$56.03
[EXIT] 2017-05-18 00:00:00: SLB r=0.0062, PnL=$7.87

Simulating Trading Days:  17%|█▋        | 15/88 [15:08<03:55,  3.23s/it]

[SIM] 2017-05-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.642, kelly=0.309) with $3100.59 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.665, kelly=0.332) with $3337.34 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.762, kelly=0.526) with $5286.19 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.751, kelly=0.522) with $5246.29 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.774, kelly=0.566) with $5684.00 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.620, kelly=0.253) with $2537.38 allocation
[PORT] Sector Services: selecting BABA (p_up=0.756, kelly=0.537) with $5389.64 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.544, kelly=0.142) with $1430.17 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.757, kelly=0.507) with $5093.48 allocation
[SIM] 2017-05-18 00:00:00: 9 trades proposed.
[TRADE] 2017-05-18 00:00:00: allocated $5684.00 to PFE exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $5286.19 to PM exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $5093.48 to SRE exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $5389.64 to BABA exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $5246.29 to BAC exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $3337.34 to GMRE exiting on 2017-05-19 00:00:00
[EXIT] 2017-05-19 00:00:00: PFE r=0.0074, PnL=$42.34
[EXIT] 2017-05-19 00:00:00: PM r=0.0102, PnL=$53.99
[EXIT] 2017-05-19 00:00:00: SRE r=0.0067, PnL=$34.03
[EXIT] 2017-05-19 00:00:00: BABA r=0.0161, PnL=$86.66
[EXIT] 2017-05-19 00:00:00: BAC r=0.0136, PnL=$71.52
[EXIT] 2017-05-19 00:00:00: GMRE r=0.0095, PnL=$31.58

Simulating Trading Days:  18%|█▊        | 16/88 [15:10<03:13,  2.69s/it]

[SIM] 2017-05-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.613, kelly=0.254) with $2560.35 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.761, kelly=0.531) with $5352.94 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.761, kelly=0.524) with $5282.04 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.760, kelly=0.540) with $5438.04 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.796, kelly=0.609) with $6132.25 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.630, kelly=0.272) with $2744.13 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.711, kelly=0.473) with $4767.13 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.655, kelly=0.314) with $3164.75 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.768, kelly=0.529) with $5332.78 allocation
[SIM] 2017-05-19 00:00:00: 9 trades proposed.
[TRADE] 2017-05-19 00:00:00: allocated $6132.25 to PFE exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $5332.78 to SRE exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $5352.94 to CODI exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $5282.04 to PM exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $5438.04 to BAC exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $2688.34 to CHTR exiting on 2017-05-22 00:00:00
[EXIT] 2017-05-22 00:00:00: PFE r=-0.0105, PnL=$-64.23
[EXIT] 2017-05-22 00:00:00: SRE r=0.0123, PnL=$65.52
[EXIT] 2017-05-22 00:00:00: CODI r=0.0062, PnL=$32.94
[EXIT] 2017-05-22 00:00:00: PM r=0.0129, PnL=$68.13
[EXIT] 2017-05-22 00:00:00: BAC r=-0.0004, PnL=$-2.36
[EXIT] 2017-05-22 00:00:00: CHTR r=0.0020, PnL=$5.45

Simulating Trading Days:  19%|█▉        | 17/88 [15:11<02:44,  2.32s/it]

[SIM] 2017-05-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.581, kelly=0.192) with $1938.10 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.754, kelly=0.516) with $5201.56 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.762, kelly=0.525) with $5298.09 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.746, kelly=0.513) with $5174.00 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.795, kelly=0.606) with $6111.25 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.640, kelly=0.290) with $2929.49 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.722, kelly=0.492) with $4963.60 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.714, kelly=0.431) with $4351.37 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.785, kelly=0.564) with $5689.36 allocation
[SIM] 2017-05-22 00:00:00: 9 trades proposed.
[TRADE] 2017-05-22 00:00:00: allocated $6111.25 to PFE exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $5689.36 to SRE exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $5298.09 to PM exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $5201.56 to CODI exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $5174.00 to BAC exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $2783.77 to CHTR exiting on 2017-05-23 00:00:00
[EXIT] 2017-05-23 00:00:00: PFE r=0.0006, PnL=$3.81
[EXIT] 2017-05-23 00:00:00: SRE r=0.0035, PnL=$20.16
[EXIT] 2017-05-23 00:00:00: PM r=0.0021, PnL=$10.94
[EXIT] 2017-05-23 00:00:00: CODI r=-0.0061, PnL=$-31.81
[EXIT] 2017-05-23 00:00:00: BAC r=0.0152, PnL=$78.60
[EXIT] 2017-05-23 00:00:00: CHTR r=0.0075, PnL=$20.85

Simulating Trading Days:  20%|██        | 18/88 [15:12<02:23,  2.04s/it]

[SIM] 2017-05-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BP (p_up=0.579, kelly=0.164) with $1652.06 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.735, kelly=0.480) with $4844.11 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.764, kelly=0.529) with $5341.99 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.729, kelly=0.480) with $4843.93 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.795, kelly=0.606) with $6123.12 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.722, kelly=0.439) with $4436.19 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.732, kelly=0.511) with $5154.75 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.741, kelly=0.484) with $4890.49 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.853, kelly=0.702) with $7086.13 allocation
[SIM] 2017-05-23 00:00:00: 9 trades proposed.
[TRADE] 2017-05-23 00:00:00: allocated $7086.13 to SRE exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $6123.12 to PFE exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $5341.99 to PM exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $4890.49 to ORCL exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $4844.11 to CODI exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $2002.96 to CHTR exiting on 2017-05-24 00:00:00
[EXIT] 2017-05-24 00:00:00: SRE r=0.0043, PnL=$30.65
[EXIT] 2017-05-24 00:00:00: PFE r=-0.0028, PnL=$-17.15
[EXIT] 2017-05-24 00:00:00: PM r=0.0083, PnL=$44.49
[EXIT] 2017-05-24 00:00:00: ORCL r=0.0061, PnL=$29.63
[EXIT] 2017-05-24 00:00:00: CODI r=0.0031, PnL=$14.90
[EXIT] 2017-05-24 00:00:00: CHTR r=0.0322, PnL=$64.40

Simulating Trading Days:  22%|██▏       | 19/88 [15:14<02:07,  1.85s/it]

[SIM] 2017-05-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BP (p_up=0.575, kelly=0.155) with $1564.61 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.722, kelly=0.453) with $4581.82 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.765, kelly=0.533) with $5387.70 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.716, kelly=0.456) with $4608.61 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.753, kelly=0.525) with $5313.15 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.738, kelly=0.470) with $4754.69 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.742, kelly=0.529) with $5351.24 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.749, kelly=0.502) with $5072.54 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.842, kelly=0.680) with $6874.58 allocation
[SIM] 2017-05-24 00:00:00: 9 trades proposed.
[TRADE] 2017-05-24 00:00:00: allocated $6874.58 to SRE exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $5387.70 to PM exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $5313.15 to PFE exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $5072.54 to ORCL exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $5351.24 to CHTR exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $2339.68 to MMM exiting on 2017-05-25 00:00:00
[EXIT] 2017-05-25 00:00:00: SRE r=0.0069, PnL=$47.74
[EXIT] 2017-05-25 00:00:00: PM r=0.0175, PnL=$94.05
[EXIT] 2017-05-25 00:00:00: PFE r=0.0034, PnL=$18.24
[EXIT] 2017-05-25 00:00:00: ORCL r=0.0083, PnL=$41.87
[EXIT] 2017-05-25 00:00:00: CHTR r=0.0143, PnL=$76.76
[EXIT] 2017-05-25 00:00:00: MMM r=0.0104, PnL=$24.29

Simulating Trading Days:  23%|██▎       | 20/88 [15:15<01:57,  1.73s/it]

[SIM] 2017-05-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BP (p_up=0.571, kelly=0.146) with $1485.39 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.713, kelly=0.435) with $4414.08 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.768, kelly=0.537) with $5450.23 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.710, kelly=0.445) with $4512.14 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.695, kelly=0.383) with $3882.69 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.741, kelly=0.478) with $4843.59 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.748, kelly=0.540) with $5482.35 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.740, kelly=0.483) with $4903.96 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.793, kelly=0.580) with $5882.96 allocation
[SIM] 2017-05-25 00:00:00: 9 trades proposed.
[TRADE] 2017-05-25 00:00:00: allocated $5882.96 to SRE exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $5450.23 to PM exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $5482.35 to CHTR exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $4843.59 to MMM exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $4903.96 to ORCL exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $3866.67 to CODI exiting on 2017-05-26 00:00:00
[EXIT] 2017-05-26 00:00:00: SRE r=-0.0006, PnL=$-3.59
[EXIT] 2017-05-26 00:00:00: PM r=0.0029, PnL=$15.97
[EXIT] 2017-05-26 00:00:00: CHTR r=0.0110, PnL=$60.45
[EXIT] 2017-05-26 00:00:00: MMM r=0.0057, PnL=$27.43
[EXIT] 2017-05-26 00:00:00: ORCL r=0.0013, PnL=$6.51
[EXIT] 2017-05-26 00:00:00: CODI r=0.0062, PnL=$23.94

Simulating Trading Days:  24%|██▍       | 21/88 [15:17<01:51,  1.66s/it]

[SIM] 2017-05-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.559, kelly=0.103) with $1044.24 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.712, kelly=0.434) with $4409.16 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.772, kelly=0.546) with $5541.01 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.703, kelly=0.430) with $4367.54 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.727, kelly=0.447) with $4538.65 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.728, kelly=0.451) with $4580.96 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.754, kelly=0.551) with $5597.81 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.709, kelly=0.421) with $4272.39 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.724, kelly=0.439) with $4460.19 allocation
[SIM] 2017-05-26 00:00:00: 9 trades proposed.
[TRADE] 2017-05-26 00:00:00: allocated $5541.01 to PM exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $5597.81 to CHTR exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4580.96 to MMM exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4538.65 to SNY exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4460.19 to SRE exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $4409.16 to CODI exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $1341.19 to ORCL exiting on 2017-05-30 00:00:00
[EXIT] 2017-05-30 00:00:00: PM r=0.0010, PnL=$5.55
[EXIT] 2017-05-30 00:00:00: CHTR r=0.0044, PnL=$24.55
[EXIT] 2017-05-30 00:00:00: MMM r=0.0088, PnL=$40.41
[EXIT] 2017-05-30 00:00:00: SNY r=0.0012, PnL=$5.56
[EXIT] 2017-05-30 00:00:00: SRE r=0.0103, PnL=$45.97
[EXIT] 2017-05-30 00:00:00: CODI r=-0.0062, PnL=$-27.13
[EXIT] 2017-05-30 00:00:00: ORCL r=0.0035, PnL=$4.74

Simulating Trading Days:  25%|██▌       | 22/88 [15:18<01:44,  1.58s/it]

[SIM] 2017-05-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.566, kelly=0.118) with $1199.58 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.717, kelly=0.443) with $4505.53 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.776, kelly=0.554) with $5633.77 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.700, kelly=0.424) with $4311.70 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.751, kelly=0.497) with $5048.21 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.696, kelly=0.387) with $3935.45 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.756, kelly=0.555) with $5638.08 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.657, kelly=0.319) with $3238.75 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.648, kelly=0.286) with $2910.14 allocation
[SIM] 2017-05-30 00:00:00: 9 trades proposed.
[TRADE] 2017-05-30 00:00:00: allocated $5633.77 to PM exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $5638.08 to CHTR exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $5048.21 to SNY exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $4505.53 to CODI exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $4311.70 to BAC exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $3935.45 to MMM exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $1426.12 to ORCL exiting on 2017-05-31 00:00:00
[EXIT] 2017-05-31 00:00:00: PM r=-0.0013, PnL=$-7.04
[EXIT] 2017-05-31 00:00:00: CHTR r=0.0196, PnL=$110.29
[EXIT] 2017-05-31 00:00:00: SNY r=0.0108, PnL=$54.54
[EXIT] 2017-05-31 00:00:00: CODI r=0.0000, PnL=$0.00
[EXIT] 2017-05-31 00:00:00: BAC r=-0.0218, PnL=$-94.10
[EXIT] 2017-05-31 00:00:00: MMM r=0.0100, PnL=$39.46
[EXIT] 2017-05-31 00:00:00: ORCL r=-0.0007, PnL=$-0.94

Simulating Trading Days:  26%|██▌       | 23/88 [15:20<01:42,  1.57s/it]

[SIM] 2017-05-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.574, kelly=0.134) with $1364.48 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.728, kelly=0.465) with $4732.87 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.780, kelly=0.561) with $5713.32 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.718, kelly=0.459) with $4666.44 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.765, kelly=0.525) with $5341.54 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.616, kelly=0.245) with $2491.98 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.758, kelly=0.559) with $5684.37 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.565, kelly=0.183) with $1860.27 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.674, kelly=0.339) with $3449.08 allocation
[SIM] 2017-05-31 00:00:00: 9 trades proposed.
[TRADE] 2017-05-31 00:00:00: allocated $5713.32 to PM exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $5341.54 to SNY exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $5684.37 to CHTR exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $4732.87 to CODI exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $4666.44 to BAC exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $3449.08 to NGG exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $941.90 to HON exiting on 2017-06-01 00:00:00
[EXIT] 2017-06-01 00:00:00: PM r=0.0092, PnL=$52.46
[EXIT] 2017-06-01 00:00:00: SNY r=-0.0063, PnL=$-33.39
[EXIT] 2017-06-01 00:00:00: CHTR r=0.0024, PnL=$13.82
[EXIT] 2017-06-01 00:00:00: CODI r=0.0093, PnL=$43.96
[EXIT] 2017-06-01 00:00:00: BAC r=0.0098, PnL=$45.81
[EXIT] 2017-06-01 00:00:00: NGG r=-0.0026, PnL=$-9.06
[EXIT] 2017-06-01 00:00:00: HON r=0.0035, PnL=$3.26

Simulating Trading Days:  27%|██▋       | 24/88 [15:21<01:37,  1.53s/it]

[SIM] 2017-06-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.672, kelly=0.355) with $3619.84 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.744, kelly=0.498) with $5070.26 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.783, kelly=0.568) with $5787.48 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.742, kelly=0.505) with $5149.98 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.767, kelly=0.528) with $5376.67 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.610, kelly=0.233) with $2372.43 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.761, kelly=0.563) with $5736.23 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.564, kelly=0.180) with $1836.59 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.715, kelly=0.423) with $4307.04 allocation
[SIM] 2017-06-01 00:00:00: 9 trades proposed.
[TRADE] 2017-06-01 00:00:00: allocated $5787.48 to PM exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5376.67 to SNY exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5736.23 to CHTR exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5070.26 to CODI exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5149.98 to BAC exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $3443.96 to NGG exiting on 2017-06-02 00:00:00
[EXIT] 2017-06-02 00:00:00: PM r=0.0074, PnL=$42.60
[EXIT] 2017-06-02 00:00:00: SNY r=0.0148, PnL=$79.65
[EXIT] 2017-06-02 00:00:00: CHTR r=0.0192, PnL=$109.96
[EXIT] 2017-06-02 00:00:00: CODI r=-0.0092, PnL=$-46.66
[EXIT] 2017-06-02 00:00:00: BAC r=-0.0080, PnL=$-40.96
[EXIT] 2017-06-02 00:00:00: NGG r=-0.0105, PnL=$-36.29

Simulating Trading Days:  28%|██▊       | 25/88 [15:23<01:33,  1.49s/it]

[SIM] 2017-06-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.687, kelly=0.385) with $3928.55 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.751, kelly=0.511) with $5210.03 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.788, kelly=0.578) with $5898.81 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.741, kelly=0.504) with $5141.08 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.762, kelly=0.518) with $5284.05 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.606, kelly=0.225) with $2292.53 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.762, kelly=0.565) with $5765.06 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.564, kelly=0.180) with $1834.39 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.748, kelly=0.489) with $4988.17 allocation
[SIM] 2017-06-02 00:00:00: 9 trades proposed.
[TRADE] 2017-06-02 00:00:00: allocated $5898.81 to PM exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $5284.05 to SNY exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $5765.06 to CHTR exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $5210.03 to CODI exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $4988.17 to NGG exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $3450.94 to BAC exiting on 2017-06-05 00:00:00
[EXIT] 2017-06-05 00:00:00: PM r=0.0015, PnL=$8.72
[EXIT] 2017-06-05 00:00:00: SNY r=-0.0010, PnL=$-5.28
[EXIT] 2017-06-05 00:00:00: CHTR r=-0.0244, PnL=$-140.44
[EXIT] 2017-06-05 00:00:00: CODI r=0.0093, PnL=$48.39
[EXIT] 2017-06-05 00:00:00: NGG r=-0.0013, PnL=$-6.64
[EXIT] 2017-06-05 00:00:00: BAC r=-0.0018, PnL=$-6.15

Simulating Trading Days:  30%|██▉       | 26/88 [15:24<01:31,  1.48s/it]

[SIM] 2017-06-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.750, kelly=0.509) with $5189.83 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.758, kelly=0.525) with $5347.03 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.794, kelly=0.590) with $6006.96 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.751, kelly=0.523) with $5324.44 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.743, kelly=0.480) with $4890.62 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.601, kelly=0.215) with $2189.88 allocation
[PORT] Sector Services: selecting WMT (p_up=0.819, kelly=0.632) with $6439.98 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.565, kelly=0.182) with $1857.12 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.776, kelly=0.547) with $5569.91 allocation
[SIM] 2017-06-05 00:00:00: 9 trades proposed.
[TRADE] 2017-06-05 00:00:00: allocated $6439.98 to WMT exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $6006.96 to PM exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $5569.91 to NGG exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $5347.03 to CODI exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $5324.44 to BAC exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $1878.32 to XOM exiting on 2017-06-06 00:00:00
[EXIT] 2017-06-06 00:00:00: WMT r=-0.0166, PnL=$-106.72
[EXIT] 2017-06-06 00:00:00: PM r=0.0002, PnL=$1.48
[EXIT] 2017-06-06 00:00:00: NGG r=-0.0114, PnL=$-63.53
[EXIT] 2017-06-06 00:00:00: CODI r=0.0000, PnL=$0.00
[EXIT] 2017-06-06 00:00:00: BAC r=-0.0080, PnL=$-42.77
[EXIT] 2017-06-06 00:00:00: XOM r=0.0136, PnL=$25.55

Simulating Trading Days:  31%|███       | 27/88 [15:25<01:28,  1.45s/it]

[SIM] 2017-06-06 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.737, kelly=0.484) with $4924.00 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.751, kelly=0.511) with $5197.25 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.800, kelly=0.601) with $6115.38 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.748, kelly=0.517) with $5260.73 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.722, kelly=0.438) with $4450.23 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.600, kelly=0.213) with $2162.92 allocation
[PORT] Sector Services: selecting WMT (p_up=0.832, kelly=0.659) with $6703.20 allocation
[PORT] Sector Technology: selecting T (p_up=0.652, kelly=0.290) with $2953.01 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.803, kelly=0.601) with $6110.22 allocation
[SIM] 2017-06-06 00:00:00: 9 trades proposed.
[TRADE] 2017-06-06 00:00:00: allocated $6703.20 to WMT exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $6110.22 to NGG exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $6115.38 to PM exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $5197.25 to CODI exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $5260.73 to BAC exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $1124.06 to XOM exiting on 2017-06-07 00:00:00
[EXIT] 2017-06-07 00:00:00: WMT r=0.0028, PnL=$18.68
[EXIT] 2017-06-07 00:00:00: NGG r=0.0018, PnL=$10.99
[EXIT] 2017-06-07 00:00:00: PM r=0.0025, PnL=$15.04
[EXIT] 2017-06-07 00:00:00: CODI r=0.0092, PnL=$47.83
[EXIT] 2017-06-07 00:00:00: BAC r=0.0166, PnL=$87.56
[EXIT] 2017-06-07 00:00:00: XOM r=-0.0037, PnL=$-4.15

Simulating Trading Days:  32%|███▏      | 28/88 [15:27<01:26,  1.44s/it]

[SIM] 2017-06-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.643, kelly=0.273) with $2784.89 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.742, kelly=0.493) with $5020.22 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.805, kelly=0.611) with $6224.62 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.755, kelly=0.531) with $5406.35 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.707, kelly=0.407) with $4145.29 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.604, kelly=0.221) with $2252.29 allocation
[PORT] Sector Services: selecting WMT (p_up=0.850, kelly=0.696) with $7085.81 allocation
[PORT] Sector Technology: selecting T (p_up=0.659, kelly=0.304) with $3092.33 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.825, kelly=0.646) with $6581.76 allocation
[SIM] 2017-06-07 00:00:00: 9 trades proposed.
[TRADE] 2017-06-07 00:00:00: allocated $7085.81 to WMT exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $6581.76 to NGG exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $6224.62 to PM exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $5406.35 to BAC exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $5020.22 to CODI exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $244.88 to SNY exiting on 2017-06-08 00:00:00
[EXIT] 2017-06-08 00:00:00: WMT r=-0.0028, PnL=$-19.70
[EXIT] 2017-06-08 00:00:00: NGG r=0.0000, PnL=$0.00
[EXIT] 2017-06-08 00:00:00: PM r=-0.0097, PnL=$-60.57
[EXIT] 2017-06-08 00:00:00: BAC r=0.0164, PnL=$88.51
[EXIT] 2017-06-08 00:00:00: CODI r=0.0152, PnL=$76.30
[EXIT] 2017-06-08 00:00:00: SNY r=-0.0050, PnL=$-1.22

Simulating Trading Days:  33%|███▎      | 29/88 [15:28<01:25,  1.44s/it]

[SIM] 2017-06-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.667, kelly=0.346) with $3525.46 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.719, kelly=0.448) with $4567.54 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.809, kelly=0.619) with $6312.85 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.750, kelly=0.520) with $5304.62 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.709, kelly=0.410) with $4184.62 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.611, kelly=0.235) with $2396.99 allocation
[PORT] Sector Services: selecting WMT (p_up=0.856, kelly=0.707) with $7203.82 allocation
[PORT] Sector Technology: selecting T (p_up=0.662, kelly=0.311) with $3173.30 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.847, kelly=0.691) with $7040.89 allocation
[SIM] 2017-06-08 00:00:00: 9 trades proposed.
[TRADE] 2017-06-08 00:00:00: allocated $7203.82 to WMT exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $7040.89 to NGG exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $6312.85 to PM exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $5304.62 to BAC exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $4567.54 to CODI exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $158.92 to SNY exiting on 2017-06-09 00:00:00
[EXIT] 2017-06-09 00:00:00: WMT r=0.0062, PnL=$44.72
[EXIT] 2017-06-09 00:00:00: NGG r=-0.0251, PnL=$-176.92
[EXIT] 2017-06-09 00:00:00: PM r=-0.0082, PnL=$-51.60
[EXIT] 2017-06-09 00:00:00: BAC r=0.0305, PnL=$161.66
[EXIT] 2017-06-09 00:00:00: CODI r=0.0090, PnL=$41.03
[EXIT] 2017-06-09 00:00:00: SNY r=0.0021, PnL=$0.33

Simulating Trading Days:  34%|███▍      | 30/88 [15:30<01:27,  1.51s/it]

[SIM] 2017-06-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.705, kelly=0.419) with $4277.25 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.677, kelly=0.380) with $3879.13 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.816, kelly=0.634) with $6466.87 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.734, kelly=0.491) with $5004.82 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.725, kelly=0.442) with $4508.38 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.617, kelly=0.247) with $2518.95 allocation
[PORT] Sector Services: selecting WMT (p_up=0.820, kelly=0.635) with $6470.98 allocation
[PORT] Sector Technology: selecting T (p_up=0.660, kelly=0.307) with $3130.03 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.865, kelly=0.726) with $7405.17 allocation
[SIM] 2017-06-09 00:00:00: 9 trades proposed.
[TRADE] 2017-06-09 00:00:00: allocated $7405.17 to NGG exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $6470.98 to WMT exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $6466.87 to PM exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $5004.82 to BAC exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $4508.38 to SNY exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $738.18 to PTR exiting on 2017-06-12 00:00:00
[EXIT] 2017-06-12 00:00:00: NGG r=-0.0071, PnL=$-52.26
[EXIT] 2017-06-12 00:00:00: WMT r=-0.0023, PnL=$-14.67
[EXIT] 2017-06-12 00:00:00: PM r=-0.0079, PnL=$-51.15
[EXIT] 2017-06-12 00:00:00: BAC r=0.0046, PnL=$23.26
[EXIT] 2017-06-12 00:00:00: SNY r=-0.0131, PnL=$-58.93
[EXIT] 2017-06-12 00:00:00: PTR r=-0.0105, PnL=$-7.73

Simulating Trading Days:  35%|███▌      | 31/88 [15:32<01:29,  1.57s/it]

[SIM] 2017-06-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.729, kelly=0.468) with $4766.77 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.706, kelly=0.437) with $4449.31 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.828, kelly=0.656) with $6684.39 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.706, kelly=0.436) with $4438.65 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.741, kelly=0.475) with $4836.60 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.618, kelly=0.248) with $2524.65 allocation
[PORT] Sector Services: selecting WMT (p_up=0.795, kelly=0.583) with $5940.27 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.578, kelly=0.207) with $2110.30 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.878, kelly=0.752) with $7660.22 allocation
[SIM] 2017-06-12 00:00:00: 9 trades proposed.
[TRADE] 2017-06-12 00:00:00: allocated $7660.22 to NGG exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $6684.39 to PM exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $5940.27 to WMT exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $4836.60 to SNY exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $4766.77 to PTR exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $657.71 to PICO exiting on 2017-06-13 00:00:00
[EXIT] 2017-06-13 00:00:00: NGG r=0.0127, PnL=$97.05
[EXIT] 2017-06-13 00:00:00: PM r=-0.0040, PnL=$-26.92
[EXIT] 2017-06-13 00:00:00: WMT r=0.0035, PnL=$20.99
[EXIT] 2017-06-13 00:00:00: SNY r=0.0006, PnL=$3.05
[EXIT] 2017-06-13 00:00:00: PTR r=0.0061, PnL=$28.93
[EXIT] 2017-06-13 00:00:00: PICO r=-0.0399, PnL=$-26.23

Simulating Trading Days:  36%|███▋      | 32/88 [15:33<01:26,  1.54s/it]

[SIM] 2017-06-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.744, kelly=0.496) with $5059.57 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.717, kelly=0.457) with $4661.76 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.838, kelly=0.677) with $6898.58 allocation
[PORT] Sector Financial: selecting MA (p_up=0.738, kelly=0.477) with $4860.90 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.757, kelly=0.509) with $5182.75 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.636, kelly=0.283) with $2885.95 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.725, kelly=0.498) with $5074.97 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.589, kelly=0.227) with $2309.43 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.888, kelly=0.773) with $7880.93 allocation
[SIM] 2017-06-13 00:00:00: 9 trades proposed.
[TRADE] 2017-06-13 00:00:00: allocated $7880.93 to NGG exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $6898.58 to PM exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $5182.75 to SNY exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $5059.57 to PTR exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $4860.90 to MA exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $692.28 to CHTR exiting on 2017-06-14 00:00:00
[EXIT] 2017-06-14 00:00:00: NGG r=0.0011, PnL=$8.42
[EXIT] 2017-06-14 00:00:00: PM r=0.0089, PnL=$61.61
[EXIT] 2017-06-14 00:00:00: SNY r=0.0013, PnL=$6.53
[EXIT] 2017-06-14 00:00:00: PTR r=-0.0138, PnL=$-69.65
[EXIT] 2017-06-14 00:00:00: MA r=0.0015, PnL=$7.15
[EXIT] 2017-06-14 00:00:00: CHTR r=-0.0102, PnL=$-7.05

Simulating Trading Days:  38%|███▊      | 33/88 [15:35<01:22,  1.50s/it]

[SIM] 2017-06-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.753, kelly=0.515) with $5250.34 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.698, kelly=0.420) with $4281.83 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.844, kelly=0.689) with $7018.99 allocation
[PORT] Sector Financial: selecting MA (p_up=0.746, kelly=0.494) with $5033.00 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.774, kelly=0.541) with $5516.72 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.640, kelly=0.291) with $2965.17 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.718, kelly=0.485) with $4940.64 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.598, kelly=0.245) with $2494.78 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.891, kelly=0.780) with $7947.64 allocation
[SIM] 2017-06-14 00:00:00: 9 trades proposed.
[TRADE] 2017-06-14 00:00:00: allocated $7947.64 to NGG exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $7018.99 to PM exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $5516.72 to SNY exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $5250.34 to PTR exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $4843.43 to MA exiting on 2017-06-15 00:00:00
[EXIT] 2017-06-15 00:00:00: NGG r=-0.0037, PnL=$-29.07
[EXIT] 2017-06-15 00:00:00: PM r=0.0063, PnL=$44.55
[EXIT] 2017-06-15 00:00:00: SNY r=0.0023, PnL=$12.73
[EXIT] 2017-06-15 00:00:00: PTR r=-0.0099, PnL=$-51.88
[EXIT] 2017-06-15 00:00:00: MA r=-0.0088, PnL=$-42.70

Simulating Trading Days:  39%|███▊      | 34/88 [15:36<01:20,  1.48s/it]

[SIM] 2017-06-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.760, kelly=0.527) with $5372.74 allocation
[PORT] Sector Conglomerates: selecting PICO (p_up=0.634, kelly=0.298) with $3036.28 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.845, kelly=0.692) with $7044.15 allocation
[PORT] Sector Financial: selecting MA (p_up=0.718, kelly=0.437) with $4456.24 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.786, kelly=0.566) with $5767.70 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.635, kelly=0.281) with $2861.11 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.713, kelly=0.477) with $4857.08 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.606, kelly=0.260) with $2646.66 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.891, kelly=0.780) with $7943.28 allocation
[SIM] 2017-06-15 00:00:00: 9 trades proposed.
[TRADE] 2017-06-15 00:00:00: allocated $7943.28 to NGG exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $7044.15 to PM exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $5767.70 to SNY exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $5372.74 to PTR exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $4429.33 to MA exiting on 2017-06-16 00:00:00
[EXIT] 2017-06-16 00:00:00: NGG r=0.0092, PnL=$72.91
[EXIT] 2017-06-16 00:00:00: PM r=0.0110, PnL=$77.74
[EXIT] 2017-06-16 00:00:00: SNY r=-0.0008, PnL=$-4.83
[EXIT] 2017-06-16 00:00:00: PTR r=0.0073, PnL=$39.15
[EXIT] 2017-06-16 00:00:00: MA r=0.0044, PnL=$19.70

Simulating Trading Days:  40%|███▉      | 35/88 [15:37<01:18,  1.48s/it]

[SIM] 2017-06-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.764, kelly=0.537) with $5476.79 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.559, kelly=0.136) with $1386.41 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.845, kelly=0.692) with $7064.14 allocation
[PORT] Sector Financial: selecting MA (p_up=0.731, kelly=0.462) with $4718.83 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.793, kelly=0.581) with $5933.32 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.626, kelly=0.263) with $2688.39 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.710, kelly=0.471) with $4811.87 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.695, kelly=0.394) with $4016.44 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.887, kelly=0.770) with $7863.44 allocation
[SIM] 2017-06-16 00:00:00: 9 trades proposed.
[TRADE] 2017-06-16 00:00:00: allocated $7863.44 to NGG exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $7064.14 to PM exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $5933.32 to SNY exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $5476.79 to PTR exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $4280.92 to MA exiting on 2017-06-19 00:00:00
[EXIT] 2017-06-19 00:00:00: NGG r=-0.0042, PnL=$-33.38
[EXIT] 2017-06-19 00:00:00: PM r=0.0087, PnL=$61.46
[EXIT] 2017-06-19 00:00:00: SNY r=0.0176, PnL=$104.42
[EXIT] 2017-06-19 00:00:00: PTR r=-0.0002, PnL=$-0.86
[EXIT] 2017-06-19 00:00:00: MA r=0.0093, PnL=$39.66

Simulating Trading Days:  41%|████      | 36/88 [15:39<01:15,  1.46s/it]

[SIM] 2017-06-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.765, kelly=0.538) with $5500.90 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.558, kelly=0.118) with $1207.67 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.844, kelly=0.690) with $7054.90 allocation
[PORT] Sector Financial: selecting MA (p_up=0.725, kelly=0.452) with $4623.62 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.795, kelly=0.584) with $5973.30 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.620, kelly=0.252) with $2580.31 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.710, kelly=0.471) with $4811.01 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.741, kelly=0.485) with $4953.99 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.879, kelly=0.755) with $7716.20 allocation
[SIM] 2017-06-19 00:00:00: 9 trades proposed.
[TRADE] 2017-06-19 00:00:00: allocated $7716.20 to NGG exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $7054.90 to PM exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $5973.30 to SNY exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $5500.90 to PTR exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $4424.69 to ORCL exiting on 2017-06-20 00:00:00
[EXIT] 2017-06-20 00:00:00: NGG r=-0.0091, PnL=$-70.48
[EXIT] 2017-06-20 00:00:00: PM r=-0.0064, PnL=$-45.35
[EXIT] 2017-06-20 00:00:00: SNY r=-0.0054, PnL=$-31.98
[EXIT] 2017-06-20 00:00:00: PTR r=-0.0193, PnL=$-106.42
[EXIT] 2017-06-20 00:00:00: ORCL r=0.0024, PnL=$10.64

Simulating Trading Days:  42%|████▏     | 37/88 [15:40<01:13,  1.44s/it]

[SIM] 2017-06-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.754, kelly=0.516) with $5259.51 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.559, kelly=0.134) with $1369.34 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.846, kelly=0.692) with $7062.34 allocation
[PORT] Sector Financial: selecting MA (p_up=0.714, kelly=0.430) with $4381.60 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.787, kelly=0.569) with $5800.87 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.609, kelly=0.230) with $2342.33 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.712, kelly=0.474) with $4829.31 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.744, kelly=0.491) with $5011.44 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.862, kelly=0.720) with $7345.76 allocation
[SIM] 2017-06-20 00:00:00: 9 trades proposed.
[TRADE] 2017-06-20 00:00:00: allocated $7345.76 to NGG exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $7062.34 to PM exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5800.87 to SNY exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5259.51 to PTR exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5011.44 to ORCL exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $116.99 to MA exiting on 2017-06-21 00:00:00
[EXIT] 2017-06-21 00:00:00: NGG r=-0.0094, PnL=$-68.84
[EXIT] 2017-06-21 00:00:00: PM r=-0.0157, PnL=$-111.04
[EXIT] 2017-06-21 00:00:00: SNY r=0.0060, PnL=$34.82
[EXIT] 2017-06-21 00:00:00: PTR r=-0.0019, PnL=$-10.12
[EXIT] 2017-06-21 00:00:00: ORCL r=0.0107, PnL=$53.57
[EXIT] 2017-06-21 00:00:00: MA r=0.0014, PnL=$0.16

Simulating Trading Days:  43%|████▎     | 38/88 [15:42<01:14,  1.49s/it]

[SIM] 2017-06-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.742, kelly=0.492) with $5013.49 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.558, kelly=0.133) with $1356.29 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.846, kelly=0.694) with $7067.93 allocation
[PORT] Sector Financial: selecting MA (p_up=0.719, kelly=0.439) with $4470.23 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.769, kelly=0.532) with $5418.37 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.674, kelly=0.337) with $3428.96 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.716, kelly=0.482) with $4914.24 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.736, kelly=0.475) with $4840.87 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.839, kelly=0.675) with $6873.70 allocation
[SIM] 2017-06-21 00:00:00: 9 trades proposed.
[TRADE] 2017-06-21 00:00:00: allocated $7067.93 to PM exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $6873.70 to NGG exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $5418.37 to SNY exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $5013.49 to PTR exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $4840.87 to ORCL exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $1352.13 to MA exiting on 2017-06-22 00:00:00
[EXIT] 2017-06-22 00:00:00: PM r=-0.0040, PnL=$-28.23
[EXIT] 2017-06-22 00:00:00: NGG r=-0.0067, PnL=$-45.84
[EXIT] 2017-06-22 00:00:00: SNY r=0.0208, PnL=$112.60
[EXIT] 2017-06-22 00:00:00: PTR r=-0.0039, PnL=$-19.34
[EXIT] 2017-06-22 00:00:00: ORCL r=0.0857, PnL=$414.81
[EXIT] 2017-06-22 00:00:00: MA r=0.0016, PnL=$2.20

Simulating Trading Days:  44%|████▍     | 39/88 [15:43<01:12,  1.47s/it]

[SIM] 2017-06-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.743, kelly=0.495) with $5065.31 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.558, kelly=0.133) with $1365.59 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.849, kelly=0.699) with $7155.74 allocation
[PORT] Sector Financial: selecting MA (p_up=0.718, kelly=0.437) with $4470.81 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.737, kelly=0.468) with $4789.03 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.695, kelly=0.379) with $3879.53 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.721, kelly=0.490) with $5013.99 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.698, kelly=0.399) with $4081.29 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.819, kelly=0.633) with $6476.27 allocation
[SIM] 2017-06-22 00:00:00: 9 trades proposed.
[TRADE] 2017-06-22 00:00:00: allocated $7155.74 to PM exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $6476.27 to NGG exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $5065.31 to PTR exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $4789.03 to SNY exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $5013.99 to CHTR exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $2197.01 to MA exiting on 2017-06-23 00:00:00
[EXIT] 2017-06-23 00:00:00: PM r=-0.0013, PnL=$-8.97
[EXIT] 2017-06-23 00:00:00: NGG r=0.0025, PnL=$16.18
[EXIT] 2017-06-23 00:00:00: PTR r=-0.0003, PnL=$-1.63
[EXIT] 2017-06-23 00:00:00: SNY r=-0.0056, PnL=$-27.03
[EXIT] 2017-06-23 00:00:00: CHTR r=-0.0100, PnL=$-49.97
[EXIT] 2017-06-23 00:00:00: MA r=0.0058, PnL=$12.65

Simulating Trading Days:  45%|████▌     | 40/88 [15:45<01:10,  1.46s/it]

[SIM] 2017-06-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.752, kelly=0.513) with $5246.95 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.631, kelly=0.275) with $2808.70 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.851, kelly=0.703) with $7186.45 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.737, kelly=0.495) with $5062.74 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.702, kelly=0.396) with $4054.32 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.647, kelly=0.300) with $3067.85 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.725, kelly=0.498) with $5096.87 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.619, kelly=0.284) with $2903.75 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.806, kelly=0.607) with $6206.25 allocation
[SIM] 2017-06-23 00:00:00: 9 trades proposed.
[TRADE] 2017-06-23 00:00:00: allocated $7186.45 to PM exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $6206.25 to NGG exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $5246.95 to PTR exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $5062.74 to BAC exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $5096.87 to CHTR exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $1880.45 to SNY exiting on 2017-06-26 00:00:00
[EXIT] 2017-06-26 00:00:00: PM r=-0.0004, PnL=$-3.01
[EXIT] 2017-06-26 00:00:00: NGG r=0.0083, PnL=$51.23
[EXIT] 2017-06-26 00:00:00: PTR r=0.0040, PnL=$21.17
[EXIT] 2017-06-26 00:00:00: BAC r=0.0031, PnL=$15.53
[EXIT] 2017-06-26 00:00:00: CHTR r=0.0056, PnL=$28.50
[EXIT] 2017-06-26 00:00:00: SNY r=0.0053, PnL=$9.91

Simulating Trading Days:  47%|████▋     | 41/88 [15:46<01:08,  1.45s/it]

[SIM] 2017-06-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.767, kelly=0.541) with $5542.29 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.645, kelly=0.302) with $3095.32 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.851, kelly=0.702) with $7192.10 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.748, kelly=0.516) with $5282.29 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.673, kelly=0.337) with $3447.63 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.658, kelly=0.322) with $3295.00 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.732, kelly=0.510) with $5221.44 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.617, kelly=0.280) with $2869.32 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.801, kelly=0.598) with $6118.95 allocation
[SIM] 2017-06-26 00:00:00: 9 trades proposed.
[TRADE] 2017-06-26 00:00:00: allocated $7192.10 to PM exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $6118.95 to NGG exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $5542.29 to PTR exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $5282.29 to BAC exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $5221.44 to CHTR exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $1359.65 to SNY exiting on 2017-06-27 00:00:00
[EXIT] 2017-06-27 00:00:00: PM r=-0.0115, PnL=$-82.45
[EXIT] 2017-06-27 00:00:00: NGG r=-0.0144, PnL=$-87.90
[EXIT] 2017-06-27 00:00:00: PTR r=-0.0058, PnL=$-32.07
[EXIT] 2017-06-27 00:00:00: BAC r=0.0166, PnL=$87.69
[EXIT] 2017-06-27 00:00:00: CHTR r=-0.0084, PnL=$-43.64
[EXIT] 2017-06-27 00:00:00: SNY r=-0.0060, PnL=$-8.23

Simulating Trading Days:  48%|████▊     | 42/88 [15:48<01:07,  1.46s/it]

[SIM] 2017-06-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 58 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.775, kelly=0.557) with $5696.19 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.647, kelly=0.306) with $3125.07 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.848, kelly=0.697) with $7126.63 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.750, kelly=0.520) with $5316.95 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.638, kelly=0.266) with $2718.97 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.664, kelly=0.334) with $3411.74 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.727, kelly=0.502) with $5129.13 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.616, kelly=0.279) with $2847.42 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.795, kelly=0.585) with $5975.44 allocation
[SIM] 2017-06-27 00:00:00: 9 trades proposed.
[TRADE] 2017-06-27 00:00:00: allocated $7126.63 to PM exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $5975.44 to NGG exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $5696.19 to PTR exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $5316.95 to BAC exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $5129.13 to CHTR exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $1422.40 to GE exiting on 2017-06-28 00:00:00
[EXIT] 2017-06-28 00:00:00: PM r=0.0067, PnL=$47.66
[EXIT] 2017-06-28 00:00:00: NGG r=-0.0034, PnL=$-20.60
[EXIT] 2017-06-28 00:00:00: PTR r=0.0074, PnL=$42.36
[EXIT] 2017-06-28 00:00:00: BAC r=0.0262, PnL=$139.38
[EXIT] 2017-06-28 00:00:00: CHTR r=0.0316, PnL=$162.18
[EXIT] 2017-06-28 00:00:00: GE r=-0.0048, PnL=$-6.80

Simulating Trading Days:  49%|████▉     | 43/88 [15:49<01:05,  1.44s/it]

[SIM] 2017-06-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.772, kelly=0.553) with $5669.09 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.638, kelly=0.288) with $2957.81 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.846, kelly=0.692) with $7102.88 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.738, kelly=0.497) with $5101.64 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.600, kelly=0.190) with $1948.80 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.669, kelly=0.344) with $3524.54 allocation
[PORT] Sector Services: selecting WMT (p_up=0.790, kelly=0.573) with $5881.92 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.618, kelly=0.282) with $2889.61 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.788, kelly=0.571) with $5853.21 allocation
[SIM] 2017-06-28 00:00:00: 9 trades proposed.
[TRADE] 2017-06-28 00:00:00: allocated $7102.88 to PM exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $5881.92 to WMT exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $5853.21 to NGG exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $5669.09 to PTR exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $5101.64 to BAC exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $1167.26 to GE exiting on 2017-06-29 00:00:00
[EXIT] 2017-06-29 00:00:00: PM r=-0.0156, PnL=$-110.49
[EXIT] 2017-06-29 00:00:00: WMT r=-0.0076, PnL=$-44.59
[EXIT] 2017-06-29 00:00:00: NGG r=-0.0104, PnL=$-60.75
[EXIT] 2017-06-29 00:00:00: PTR r=-0.0112, PnL=$-63.68
[EXIT] 2017-06-29 00:00:00: BAC r=0.0184, PnL=$94.00
[EXIT] 2017-06-29 00:00:00: GE r=-0.0022, PnL=$-2.59

Simulating Trading Days:  50%|█████     | 44/88 [15:50<01:03,  1.44s/it]

[SIM] 2017-06-29 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.736, kelly=0.480) with $4919.26 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.625, kelly=0.263) with $2695.81 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.844, kelly=0.690) with $7062.68 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.702, kelly=0.428) with $4379.97 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.553, kelly=0.095) with $977.02 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.660, kelly=0.326) with $3335.76 allocation
[PORT] Sector Services: selecting WMT (p_up=0.796, kelly=0.586) with $5998.87 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.620, kelly=0.285) with $2917.52 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.779, kelly=0.552) with $5648.35 allocation
[SIM] 2017-06-29 00:00:00: 9 trades proposed.
[TRADE] 2017-06-29 00:00:00: allocated $7062.68 to PM exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $5998.87 to WMT exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $5648.35 to NGG exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $4919.26 to PTR exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $4379.97 to BAC exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $2710.43 to GE exiting on 2017-06-30 00:00:00
[EXIT] 2017-06-30 00:00:00: PM r=0.0032, PnL=$22.32
[EXIT] 2017-06-30 00:00:00: WMT r=-0.0033, PnL=$-19.75
[EXIT] 2017-06-30 00:00:00: NGG r=-0.0017, PnL=$-9.87
[EXIT] 2017-06-30 00:00:00: PTR r=-0.0055, PnL=$-27.14
[EXIT] 2017-06-30 00:00:00: BAC r=-0.0025, PnL=$-10.81
[EXIT] 2017-06-30 00:00:00: GE r=-0.0004, PnL=$-1.00

Simulating Trading Days:  51%|█████     | 45/88 [15:52<01:02,  1.46s/it]

[SIM] 2017-06-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.743, kelly=0.504) with $5155.78 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.562, kelly=0.141) with $1440.47 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.873, kelly=0.745) with $7628.80 allocation
[PORT] Sector Financial: selecting MA (p_up=0.753, kelly=0.506) with $5183.01 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.619, kelly=0.268) with $2741.53 allocation
[PORT] Sector Industrial Goods: selecting GE (p_up=0.663, kelly=0.331) with $3389.18 allocation
[PORT] Sector Services: selecting WMT (p_up=0.816, kelly=0.625) with $6398.53 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.623, kelly=0.292) with $2985.12 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.786, kelly=0.567) with $5800.01 allocation
[SIM] 2017-06-30 00:00:00: 9 trades proposed.
[TRADE] 2017-06-30 00:00:00: allocated $7628.80 to UL exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $6398.53 to WMT exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $5800.01 to NGG exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $5183.01 to MA exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $5155.78 to SLB exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $539.56 to GE exiting on 2017-07-03 00:00:00
[EXIT] 2017-07-03 00:00:00: UL r=-0.0054, PnL=$-40.88
[EXIT] 2017-07-03 00:00:00: WMT r=-0.0042, PnL=$-27.06
[EXIT] 2017-07-03 00:00:00: NGG r=-0.0067, PnL=$-38.78
[EXIT] 2017-07-03 00:00:00: MA r=-0.0055, PnL=$-28.59
[EXIT] 2017-07-03 00:00:00: SLB r=0.0172, PnL=$88.49
[EXIT] 2017-07-03 00:00:00: GE r=0.0163, PnL=$8.79

Simulating Trading Days:  52%|█████▏    | 46/88 [15:53<01:00,  1.44s/it]

[SIM] 2017-07-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.754, kelly=0.525) with $5369.79 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.565, kelly=0.146) with $1494.00 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.875, kelly=0.749) with $7665.64 allocation
[PORT] Sector Financial: selecting MA (p_up=0.735, kelly=0.470) with $4812.09 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.668, kelly=0.362) with $3705.14 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.684, kelly=0.378) with $3863.29 allocation
[PORT] Sector Services: selecting WMT (p_up=0.834, kelly=0.662) with $6775.78 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.627, kelly=0.298) with $3051.25 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.804, kelly=0.603) with $6172.90 allocation
[SIM] 2017-07-03 00:00:00: 9 trades proposed.
[TRADE] 2017-07-03 00:00:00: allocated $7665.64 to UL exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $6775.78 to WMT exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $6172.90 to NGG exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $5369.79 to SLB exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $4710.17 to MA exiting on 2017-07-05 00:00:00
[EXIT] 2017-07-05 00:00:00: UL r=-0.0017, PnL=$-12.82
[EXIT] 2017-07-05 00:00:00: WMT r=-0.0005, PnL=$-3.60
[EXIT] 2017-07-05 00:00:00: NGG r=-0.0077, PnL=$-47.48
[EXIT] 2017-07-05 00:00:00: SLB r=-0.0184, PnL=$-98.62
[EXIT] 2017-07-05 00:00:00: MA r=0.0099, PnL=$46.80

Simulating Trading Days:  53%|█████▎    | 47/88 [15:55<00:58,  1.43s/it]

[SIM] 2017-07-05 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.745, kelly=0.507) with $5183.19 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.567, kelly=0.150) with $1536.07 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.885, kelly=0.770) with $7871.01 allocation
[PORT] Sector Financial: selecting MA (p_up=0.741, kelly=0.483) with $4939.92 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.685, kelly=0.394) with $4030.95 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.680, kelly=0.369) with $3775.16 allocation
[PORT] Sector Services: selecting WMT (p_up=0.850, kelly=0.694) with $7095.24 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.630, kelly=0.305) with $3117.52 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.828, kelly=0.651) with $6655.56 allocation
[SIM] 2017-07-05 00:00:00: 9 trades proposed.
[TRADE] 2017-07-05 00:00:00: allocated $7871.01 to UL exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $7095.24 to WMT exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $6655.56 to NGG exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $5183.19 to SLB exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $3854.56 to MA exiting on 2017-07-06 00:00:00
[EXIT] 2017-07-06 00:00:00: UL r=-0.0050, PnL=$-39.55
[EXIT] 2017-07-06 00:00:00: WMT r=0.0020, PnL=$14.13
[EXIT] 2017-07-06 00:00:00: NGG r=-0.0079, PnL=$-52.67
[EXIT] 2017-07-06 00:00:00: SLB r=-0.0093, PnL=$-48.09
[EXIT] 2017-07-06 00:00:00: MA r=-0.0097, PnL=$-37.29

Simulating Trading Days:  55%|█████▍    | 48/88 [15:56<00:57,  1.45s/it]

[SIM] 2017-07-06 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.744, kelly=0.506) with $5163.10 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.574, kelly=0.150) with $1527.03 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.891, kelly=0.782) with $7980.09 allocation
[PORT] Sector Financial: selecting MA (p_up=0.748, kelly=0.497) with $5075.88 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.683, kelly=0.390) with $3978.73 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.757, kelly=0.509) with $5194.36 allocation
[PORT] Sector Services: selecting WMT (p_up=0.849, kelly=0.694) with $7081.09 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.633, kelly=0.309) with $3155.31 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.855, kelly=0.706) with $7202.63 allocation
[SIM] 2017-07-06 00:00:00: 9 trades proposed.
[TRADE] 2017-07-06 00:00:00: allocated $7980.09 to UL exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $7202.63 to NGG exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $7081.09 to WMT exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $5194.36 to MMM exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $3152.36 to MA exiting on 2017-07-07 00:00:00
[EXIT] 2017-07-07 00:00:00: UL r=0.0047, PnL=$37.31
[EXIT] 2017-07-07 00:00:00: NGG r=-0.0042, PnL=$-30.49
[EXIT] 2017-07-07 00:00:00: WMT r=-0.0019, PnL=$-13.14
[EXIT] 2017-07-07 00:00:00: MMM r=0.0075, PnL=$39.20
[EXIT] 2017-07-07 00:00:00: MA r=0.0116, PnL=$36.53

Simulating Trading Days:  56%|█████▌    | 49/88 [15:58<00:56,  1.44s/it]

[SIM] 2017-07-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.742, kelly=0.502) with $5128.32 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.610, kelly=0.222) with $2266.18 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.903, kelly=0.806) with $8227.76 allocation
[PORT] Sector Financial: selecting MA (p_up=0.760, kelly=0.522) with $5330.91 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.689, kelly=0.370) with $3781.04 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.785, kelly=0.567) with $5788.10 allocation
[PORT] Sector Services: selecting WMT (p_up=0.854, kelly=0.703) with $7181.50 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.634, kelly=0.312) with $3185.37 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.879, kelly=0.755) with $7705.53 allocation
[SIM] 2017-07-07 00:00:00: 9 trades proposed.
[TRADE] 2017-07-07 00:00:00: allocated $8227.76 to UL exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $7705.53 to NGG exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $7181.50 to WMT exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $5788.10 to MMM exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $1728.46 to MA exiting on 2017-07-10 00:00:00
[EXIT] 2017-07-10 00:00:00: UL r=0.0056, PnL=$45.95
[EXIT] 2017-07-10 00:00:00: NGG r=-0.0065, PnL=$-50.39
[EXIT] 2017-07-10 00:00:00: WMT r=-0.0279, PnL=$-200.20
[EXIT] 2017-07-10 00:00:00: MMM r=0.0043, PnL=$24.85
[EXIT] 2017-07-10 00:00:00: MA r=0.0043, PnL=$7.50

Simulating Trading Days:  57%|█████▋    | 50/88 [15:59<00:54,  1.43s/it]

[SIM] 2017-07-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 67 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.738, kelly=0.495) with $5046.59 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.636, kelly=0.273) with $2782.98 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.907, kelly=0.813) with $8288.75 allocation
[PORT] Sector Financial: selecting MA (p_up=0.713, kelly=0.427) with $4350.40 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.742, kelly=0.477) with $4866.40 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.800, kelly=0.597) with $6084.02 allocation
[PORT] Sector Services: selecting WMT (p_up=0.855, kelly=0.705) with $7186.46 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.633, kelly=0.311) with $3169.67 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.898, kelly=0.794) with $8090.66 allocation
[SIM] 2017-07-10 00:00:00: 9 trades proposed.
[TRADE] 2017-07-10 00:00:00: allocated $8288.75 to UL exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $8090.66 to NGG exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $7186.46 to WMT exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $6084.02 to MMM exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $929.77 to SNY exiting on 2017-07-11 00:00:00
[EXIT] 2017-07-11 00:00:00: UL r=0.0057, PnL=$47.57
[EXIT] 2017-07-11 00:00:00: NGG r=-0.0059, PnL=$-47.93
[EXIT] 2017-07-11 00:00:00: WMT r=0.0033, PnL=$23.55
[EXIT] 2017-07-11 00:00:00: MMM r=-0.0039, PnL=$-23.99
[EXIT] 2017-07-11 00:00:00: SNY r=0.0029, PnL=$2.73

Simulating Trading Days:  58%|█████▊    | 51/88 [16:01<00:54,  1.46s/it]

[SIM] 2017-07-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.726, kelly=0.472) with $4808.50 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.650, kelly=0.302) with $3081.69 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.914, kelly=0.827) with $8434.31 allocation
[PORT] Sector Financial: selecting MA (p_up=0.715, kelly=0.431) with $4393.87 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.782, kelly=0.558) with $5685.14 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.808, kelly=0.612) with $6243.46 allocation
[PORT] Sector Services: selecting WMT (p_up=0.856, kelly=0.708) with $7218.42 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.631, kelly=0.307) with $3125.52 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.913, kelly=0.823) with $8389.66 allocation
[SIM] 2017-07-11 00:00:00: 9 trades proposed.
[TRADE] 2017-07-11 00:00:00: allocated $8434.31 to UL exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $8389.66 to NGG exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $7218.42 to WMT exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $6243.46 to MMM exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $294.39 to SNY exiting on 2017-07-12 00:00:00
[EXIT] 2017-07-12 00:00:00: UL r=0.0087, PnL=$72.96
[EXIT] 2017-07-12 00:00:00: NGG r=0.0094, PnL=$79.16
[EXIT] 2017-07-12 00:00:00: WMT r=0.0064, PnL=$46.18
[EXIT] 2017-07-12 00:00:00: MMM r=0.0078, PnL=$48.84
[EXIT] 2017-07-12 00:00:00: SNY r=0.0228, PnL=$6.71

Simulating Trading Days:  59%|█████▉    | 52/88 [16:02<00:52,  1.45s/it]

[SIM] 2017-07-12 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 65 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.705, kelly=0.430) with $4397.28 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.655, kelly=0.312) with $3191.09 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.919, kelly=0.837) with $8549.56 allocation
[PORT] Sector Financial: selecting MA (p_up=0.690, kelly=0.381) with $3890.72 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.797, kelly=0.589) with $6017.91 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.817, kelly=0.630) with $6441.17 allocation
[PORT] Sector Services: selecting WMT (p_up=0.858, kelly=0.711) with $7265.13 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.628, kelly=0.300) with $3068.28 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.924, kelly=0.845) with $8637.88 allocation
[SIM] 2017-07-12 00:00:00: 9 trades proposed.
[TRADE] 2017-07-12 00:00:00: allocated $8637.88 to NGG exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $8549.56 to UL exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $7265.13 to WMT exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $6203.83 to MMM exiting on 2017-07-13 00:00:00
[EXIT] 2017-07-13 00:00:00: NGG r=0.0054, PnL=$46.74
[EXIT] 2017-07-13 00:00:00: UL r=0.0089, PnL=$76.45
[EXIT] 2017-07-13 00:00:00: WMT r=0.0150, PnL=$109.07
[EXIT] 2017-07-13 00:00:00: MMM r=-0.0010, PnL=$-6.17

Simulating Trading Days:  60%|██████    | 53/88 [16:03<00:50,  1.44s/it]

[SIM] 2017-07-13 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 62 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.677, kelly=0.376) with $3855.71 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.654, kelly=0.311) with $3180.55 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.912, kelly=0.824) with $8438.58 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.700, kelly=0.402) with $4116.95 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.874, kelly=0.759) with $7769.86 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.819, kelly=0.635) with $6506.34 allocation
[PORT] Sector Services: selecting WMT (p_up=0.855, kelly=0.704) with $7214.84 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.624, kelly=0.293) with $2996.70 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.928, kelly=0.854) with $8744.40 allocation
[SIM] 2017-07-13 00:00:00: 9 trades proposed.
[TRADE] 2017-07-13 00:00:00: allocated $8744.40 to NGG exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $8438.58 to UL exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $7769.86 to PFE exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $5771.39 to WMT exiting on 2017-07-14 00:00:00
[EXIT] 2017-07-14 00:00:00: NGG r=0.0057, PnL=$49.92
[EXIT] 2017-07-14 00:00:00: UL r=0.0114, PnL=$96.15
[EXIT] 2017-07-14 00:00:00: PFE r=0.0045, PnL=$35.02
[EXIT] 2017-07-14 00:00:00: WMT r=0.0172, PnL=$99.20

Simulating Trading Days:  61%|██████▏   | 54/88 [16:05<00:49,  1.45s/it]

[SIM] 2017-07-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.637, kelly=0.300) with $3079.26 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.648, kelly=0.297) with $3050.87 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.907, kelly=0.813) with $8347.34 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.712, kelly=0.427) with $4381.92 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.892, kelly=0.793) with $8141.77 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.817, kelly=0.630) with $6469.05 allocation
[PORT] Sector Services: selecting WMT (p_up=0.855, kelly=0.705) with $7242.84 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.619, kelly=0.285) with $2922.16 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.922, kelly=0.842) with $8646.84 allocation
[SIM] 2017-07-14 00:00:00: 9 trades proposed.
[TRADE] 2017-07-14 00:00:00: allocated $8646.84 to NGG exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $8347.34 to UL exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $8141.77 to PFE exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $5672.37 to WMT exiting on 2017-07-17 00:00:00
[EXIT] 2017-07-17 00:00:00: NGG r=0.0008, PnL=$7.01
[EXIT] 2017-07-17 00:00:00: UL r=-0.0014, PnL=$-11.94
[EXIT] 2017-07-17 00:00:00: PFE r=-0.0054, PnL=$-43.84
[EXIT] 2017-07-17 00:00:00: WMT r=0.0004, PnL=$2.23

Simulating Trading Days:  62%|██████▎   | 55/88 [16:06<00:47,  1.45s/it]

[SIM] 2017-07-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.595, kelly=0.219) with $2243.07 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.631, kelly=0.264) with $2704.88 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.890, kelly=0.780) with $8010.44 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.722, kelly=0.447) with $4591.15 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.895, kelly=0.798) with $8192.79 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.806, kelly=0.608) with $6236.30 allocation
[PORT] Sector Services: selecting WMT (p_up=0.860, kelly=0.716) with $7352.01 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.615, kelly=0.276) with $2829.83 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.904, kelly=0.806) with $8271.34 allocation
[SIM] 2017-07-17 00:00:00: 9 trades proposed.
[TRADE] 2017-07-17 00:00:00: allocated $8271.34 to NGG exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $8192.79 to PFE exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $8010.44 to UL exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $6319.79 to WMT exiting on 2017-07-18 00:00:00
[EXIT] 2017-07-18 00:00:00: NGG r=0.0079, PnL=$65.68
[EXIT] 2017-07-18 00:00:00: PFE r=0.0033, PnL=$27.10
[EXIT] 2017-07-18 00:00:00: UL r=0.0000, PnL=$0.00
[EXIT] 2017-07-18 00:00:00: WMT r=-0.0022, PnL=$-14.07

Simulating Trading Days:  64%|██████▎   | 56/88 [16:08<00:46,  1.46s/it]

[SIM] 2017-07-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.572, kelly=0.174) with $1790.96 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.608, kelly=0.218) with $2237.17 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.879, kelly=0.758) with $7785.53 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.726, kelly=0.455) with $4670.03 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.904, kelly=0.816) with $8380.47 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.788, kelly=0.573) with $5885.41 allocation
[PORT] Sector Services: selecting WMT (p_up=0.878, kelly=0.752) with $7729.17 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.611, kelly=0.268) with $2753.21 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.871, kelly=0.739) with $7591.65 allocation
[SIM] 2017-07-18 00:00:00: 9 trades proposed.
[TRADE] 2017-07-18 00:00:00: allocated $8380.47 to PFE exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $7785.53 to UL exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $7729.17 to WMT exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $6922.79 to NGG exiting on 2017-07-19 00:00:00
[EXIT] 2017-07-19 00:00:00: PFE r=0.0078, PnL=$65.31
[EXIT] 2017-07-19 00:00:00: UL r=0.0013, PnL=$9.76
[EXIT] 2017-07-19 00:00:00: WMT r=-0.0043, PnL=$-33.47
[EXIT] 2017-07-19 00:00:00: NGG r=0.0016, PnL=$11.13

Simulating Trading Days:  65%|██████▍   | 57/88 [16:09<00:44,  1.45s/it]

[SIM] 2017-07-19 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.575, kelly=0.179) with $1841.09 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.685, kelly=0.381) with $3915.62 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.862, kelly=0.723) with $7427.57 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.725, kelly=0.452) with $4642.52 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.902, kelly=0.813) with $8350.84 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.764, kelly=0.524) with $5382.18 allocation
[PORT] Sector Services: selecting WMT (p_up=0.894, kelly=0.785) with $8063.47 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.691, kelly=0.385) with $3958.75 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.823, kelly=0.641) with $6587.85 allocation
[SIM] 2017-07-19 00:00:00: 9 trades proposed.
[TRADE] 2017-07-19 00:00:00: allocated $8350.84 to PFE exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $8063.47 to WMT exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $7427.57 to UL exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $6587.85 to NGG exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $404.05 to MMM exiting on 2017-07-20 00:00:00
[EXIT] 2017-07-20 00:00:00: PFE r=-0.0024, PnL=$-19.87
[EXIT] 2017-07-20 00:00:00: WMT r=0.0020, PnL=$15.94
[EXIT] 2017-07-20 00:00:00: UL r=0.0170, PnL=$126.21
[EXIT] 2017-07-20 00:00:00: NGG r=0.0079, PnL=$51.81
[EXIT] 2017-07-20 00:00:00: MMM r=0.0017, PnL=$0.67

Simulating Trading Days:  66%|██████▌   | 58/88 [16:11<00:43,  1.45s/it]

[SIM] 2017-07-20 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.580, kelly=0.189) with $1941.83 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.702, kelly=0.415) with $4276.76 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.839, kelly=0.678) with $6977.38 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.717, kelly=0.437) with $4498.21 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.888, kelly=0.784) with $8070.74 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.723, kelly=0.441) with $4543.73 allocation
[PORT] Sector Services: selecting WMT (p_up=0.911, kelly=0.818) with $8422.45 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.699, kelly=0.401) with $4131.33 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.763, kelly=0.519) with $5341.92 allocation
[SIM] 2017-07-20 00:00:00: 9 trades proposed.
[TRADE] 2017-07-20 00:00:00: allocated $8422.45 to WMT exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $8070.74 to PFE exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $6977.38 to UL exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $5341.92 to NGG exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $2073.74 to MMM exiting on 2017-07-21 00:00:00
[EXIT] 2017-07-21 00:00:00: WMT r=0.0017, PnL=$14.40
[EXIT] 2017-07-21 00:00:00: PFE r=-0.0018, PnL=$-14.44
[EXIT] 2017-07-21 00:00:00: UL r=0.0040, PnL=$28.22
[EXIT] 2017-07-21 00:00:00: NGG r=0.0021, PnL=$11.06
[EXIT] 2017-07-21 00:00:00: MMM r=-0.0061, PnL=$-12.59

Simulating Trading Days:  67%|██████▋   | 59/88 [16:12<00:42,  1.47s/it]

[SIM] 2017-07-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.591, kelly=0.211) with $2170.58 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.722, kelly=0.453) with $4667.44 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.827, kelly=0.655) with $6740.79 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.705, kelly=0.412) with $4242.66 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.866, kelly=0.742) with $7636.41 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.666, kelly=0.321) with $3301.69 allocation
[PORT] Sector Services: selecting WMT (p_up=0.920, kelly=0.838) with $8631.43 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.706, kelly=0.415) with $4275.58 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.701, kelly=0.393) with $4049.04 allocation
[SIM] 2017-07-21 00:00:00: 9 trades proposed.
[TRADE] 2017-07-21 00:00:00: allocated $8631.43 to WMT exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $7636.41 to PFE exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $6740.79 to PM exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $4667.44 to CODI exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $3218.14 to ORCL exiting on 2017-07-24 00:00:00
[EXIT] 2017-07-24 00:00:00: WMT r=0.0097, PnL=$83.88
[EXIT] 2017-07-24 00:00:00: PFE r=-0.0048, PnL=$-36.49
[EXIT] 2017-07-24 00:00:00: PM r=-0.0058, PnL=$-38.90
[EXIT] 2017-07-24 00:00:00: CODI r=0.0029, PnL=$13.49
[EXIT] 2017-07-24 00:00:00: ORCL r=-0.0008, PnL=$-2.53

Simulating Trading Days:  68%|██████▊   | 60/88 [16:14<00:40,  1.46s/it]

[SIM] 2017-07-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.599, kelly=0.225) with $2321.22 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.738, kelly=0.484) with $4988.70 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.834, kelly=0.669) with $6888.03 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.684, kelly=0.370) with $3807.19 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.851, kelly=0.713) with $7342.89 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.635, kelly=0.282) with $2901.05 allocation
[PORT] Sector Services: selecting WMT (p_up=0.927, kelly=0.852) with $8778.65 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.710, kelly=0.423) with $4352.21 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.656, kelly=0.302) with $3110.73 allocation
[SIM] 2017-07-24 00:00:00: 9 trades proposed.
[TRADE] 2017-07-24 00:00:00: allocated $8778.65 to WMT exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $7342.89 to PFE exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $6888.03 to PM exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $4988.70 to CODI exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $2901.78 to ORCL exiting on 2017-07-25 00:00:00
[EXIT] 2017-07-25 00:00:00: WMT r=0.0212, PnL=$186.10
[EXIT] 2017-07-25 00:00:00: PFE r=-0.0066, PnL=$-48.48
[EXIT] 2017-07-25 00:00:00: PM r=-0.0090, PnL=$-61.99
[EXIT] 2017-07-25 00:00:00: CODI r=0.0029, PnL=$14.38
[EXIT] 2017-07-25 00:00:00: ORCL r=0.0081, PnL=$23.44

Simulating Trading Days:  69%|██████▉   | 61/88 [16:15<00:39,  1.45s/it]

[SIM] 2017-07-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.603, kelly=0.234) with $2414.24 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.747, kelly=0.503) with $5181.68 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.839, kelly=0.680) with $7008.81 allocation
[PORT] Sector Financial: selecting HSBC (p_up=0.656, kelly=0.315) with $3251.67 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.859, kelly=0.728) with $7509.37 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.646, kelly=0.303) with $3128.60 allocation
[PORT] Sector Services: selecting WMT (p_up=0.929, kelly=0.855) with $8820.46 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.704, kelly=0.411) with $4240.41 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.642, kelly=0.275) with $2838.96 allocation
[SIM] 2017-07-25 00:00:00: 9 trades proposed.
[TRADE] 2017-07-25 00:00:00: allocated $8820.46 to WMT exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $7509.37 to PFE exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $7008.81 to PM exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $5181.68 to CODI exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $2413.75 to ORCL exiting on 2017-07-26 00:00:00
[EXIT] 2017-07-26 00:00:00: WMT r=0.0048, PnL=$42.69
[EXIT] 2017-07-26 00:00:00: PFE r=-0.0063, PnL=$-47.64
[EXIT] 2017-07-26 00:00:00: PM r=-0.0014, PnL=$-10.11
[EXIT] 2017-07-26 00:00:00: CODI r=0.0000, PnL=$0.00
[EXIT] 2017-07-26 00:00:00: ORCL r=0.0000, PnL=$0.00

Simulating Trading Days:  70%|███████   | 62/88 [16:17<00:38,  1.47s/it]

[SIM] 2017-07-26 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.677, kelly=0.366) with $3773.17 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.752, kelly=0.513) with $5284.41 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.843, kelly=0.687) with $7083.59 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.627, kelly=0.276) with $2846.88 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.891, kelly=0.790) with $8148.78 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.674, kelly=0.358) with $3693.84 allocation
[PORT] Sector Services: selecting WMT (p_up=0.924, kelly=0.845) with $8716.84 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.709, kelly=0.422) with $4352.40 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.636, kelly=0.263) with $2716.04 allocation
[SIM] 2017-07-26 00:00:00: 9 trades proposed.
[TRADE] 2017-07-26 00:00:00: allocated $8716.84 to WMT exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $8148.78 to PFE exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $7083.59 to PM exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $5284.41 to CODI exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $1695.94 to ORCL exiting on 2017-07-27 00:00:00
[EXIT] 2017-07-27 00:00:00: WMT r=0.0112, PnL=$97.22
[EXIT] 2017-07-27 00:00:00: PFE r=0.0033, PnL=$27.25
[EXIT] 2017-07-27 00:00:00: PM r=0.0046, PnL=$32.51
[EXIT] 2017-07-27 00:00:00: CODI r=0.0000, PnL=$0.00
[EXIT] 2017-07-27 00:00:00: ORCL r=-0.0141, PnL=$-23.86

Simulating Trading Days:  72%|███████▏  | 63/88 [16:18<00:36,  1.46s/it]

[SIM] 2017-07-27 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.682, kelly=0.375) with $3875.86 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.748, kelly=0.505) with $5208.43 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.844, kelly=0.689) with $7115.91 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.628, kelly=0.278) with $2873.79 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.925, kelly=0.856) with $8841.77 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.708, kelly=0.425) with $4388.71 allocation
[PORT] Sector Services: selecting WMT (p_up=0.918, kelly=0.834) with $8606.49 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.722, kelly=0.447) with $4613.33 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.631, kelly=0.253) with $2609.67 allocation
[SIM] 2017-07-27 00:00:00: 9 trades proposed.
[TRADE] 2017-07-27 00:00:00: allocated $8841.77 to PFE exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $8606.49 to WMT exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $7115.91 to PM exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $5208.43 to CODI exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $1196.90 to ORCL exiting on 2017-07-28 00:00:00
[EXIT] 2017-07-28 00:00:00: PFE r=0.0045, PnL=$40.19
[EXIT] 2017-07-28 00:00:00: WMT r=0.0004, PnL=$3.24
[EXIT] 2017-07-28 00:00:00: PM r=0.0027, PnL=$19.27
[EXIT] 2017-07-28 00:00:00: CODI r=0.0000, PnL=$0.00
[EXIT] 2017-07-28 00:00:00: ORCL r=-0.0030, PnL=$-3.56

Simulating Trading Days:  73%|███████▎  | 64/88 [16:20<00:34,  1.45s/it]

[SIM] 2017-07-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.610, kelly=0.247) with $2546.49 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.732, kelly=0.473) with $4882.14 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.843, kelly=0.687) with $7094.03 allocation
[PORT] Sector Financial: selecting MA (p_up=0.654, kelly=0.309) with $3194.87 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.950, kelly=0.903) with $9327.97 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.773, kelly=0.539) with $5566.41 allocation
[PORT] Sector Services: selecting WMT (p_up=0.908, kelly=0.813) with $8399.35 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.764, kelly=0.531) with $5481.03 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.629, kelly=0.249) with $2574.36 allocation
[SIM] 2017-07-28 00:00:00: 9 trades proposed.
[TRADE] 2017-07-28 00:00:00: allocated $9327.97 to PFE exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $8399.35 to WMT exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $7094.03 to PM exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $5566.41 to ABB exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $599.49 to ORCL exiting on 2017-07-31 00:00:00
[EXIT] 2017-07-31 00:00:00: PFE r=0.0003, PnL=$2.81
[EXIT] 2017-07-31 00:00:00: WMT r=0.0023, PnL=$18.94
[EXIT] 2017-07-31 00:00:00: PM r=-0.0152, PnL=$-107.75
[EXIT] 2017-07-31 00:00:00: ABB r=0.0000, PnL=$0.00
[EXIT] 2017-07-31 00:00:00: ORCL r=-0.0074, PnL=$-4.41

Simulating Trading Days:  74%|███████▍  | 65/88 [16:21<00:33,  1.47s/it]

[SIM] 2017-07-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.669, kelly=0.349) with $3601.89 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.714, kelly=0.438) with $4523.94 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.848, kelly=0.697) with $7198.19 allocation
[PORT] Sector Financial: selecting MA (p_up=0.713, kelly=0.427) with $4411.81 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.949, kelly=0.901) with $9299.85 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.798, kelly=0.588) with $6071.55 allocation
[PORT] Sector Services: selecting WMT (p_up=0.900, kelly=0.797) with $8227.13 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.783, kelly=0.568) with $5858.88 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.626, kelly=0.242) with $2494.06 allocation
[SIM] 2017-07-31 00:00:00: 9 trades proposed.
[TRADE] 2017-07-31 00:00:00: allocated $9299.85 to PFE exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $8227.13 to WMT exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $7198.19 to PM exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $6071.55 to ABB exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $163.40 to ORCL exiting on 2017-08-01 00:00:00
[EXIT] 2017-08-01 00:00:00: PFE r=-0.0024, PnL=$-22.44
[EXIT] 2017-08-01 00:00:00: WMT r=0.0064, PnL=$52.45
[EXIT] 2017-08-01 00:00:00: PM r=-0.0071, PnL=$-51.19
[EXIT] 2017-08-01 00:00:00: ABB r=0.0060, PnL=$36.17
[EXIT] 2017-08-01 00:00:00: ORCL r=0.0046, PnL=$0.75

Simulating Trading Days:  75%|███████▌  | 66/88 [16:22<00:32,  1.46s/it]

[SIM] 2017-08-01 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.672, kelly=0.356) with $3669.37 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.694, kelly=0.399) with $4122.67 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.854, kelly=0.710) with $7328.75 allocation
[PORT] Sector Financial: selecting MA (p_up=0.756, kelly=0.514) with $5302.07 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.938, kelly=0.880) with $9087.63 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.823, kelly=0.640) with $6601.07 allocation
[PORT] Sector Services: selecting WMT (p_up=0.890, kelly=0.776) with $8005.66 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.812, kelly=0.627) with $6470.16 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.638, kelly=0.264) with $2722.94 allocation
[SIM] 2017-08-01 00:00:00: 9 trades proposed.
[TRADE] 2017-08-01 00:00:00: allocated $9087.63 to PFE exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $8005.66 to WMT exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $7328.75 to PM exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $6542.81 to ABB exiting on 2017-08-02 00:00:00
[EXIT] 2017-08-02 00:00:00: PFE r=-0.0048, PnL=$-43.96
[EXIT] 2017-08-02 00:00:00: WMT r=0.0004, PnL=$2.98
[EXIT] 2017-08-02 00:00:00: PM r=-0.0123, PnL=$-89.81
[EXIT] 2017-08-02 00:00:00: ABB r=-0.0013, PnL=$-8.30

Simulating Trading Days:  76%|███████▌  | 67/88 [16:24<00:30,  1.45s/it]

[SIM] 2017-08-02 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.684, kelly=0.380) with $3913.50 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.678, kelly=0.367) with $3783.79 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.858, kelly=0.717) with $7385.83 allocation
[PORT] Sector Financial: selecting MA (p_up=0.749, kelly=0.499) with $5141.57 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.929, kelly=0.863) with $8899.17 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.838, kelly=0.670) with $6910.51 allocation
[PORT] Sector Services: selecting WMT (p_up=0.885, kelly=0.766) with $7894.73 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.838, kelly=0.679) with $6995.26 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.646, kelly=0.280) with $2887.99 allocation
[SIM] 2017-08-02 00:00:00: 9 trades proposed.
[TRADE] 2017-08-02 00:00:00: allocated $8899.17 to PFE exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $7894.73 to WMT exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $7385.83 to PM exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $6743.39 to ORCL exiting on 2017-08-03 00:00:00
[EXIT] 2017-08-03 00:00:00: PFE r=0.0155, PnL=$137.87
[EXIT] 2017-08-03 00:00:00: WMT r=0.0042, PnL=$33.33
[EXIT] 2017-08-03 00:00:00: PM r=0.0003, PnL=$1.94
[EXIT] 2017-08-03 00:00:00: ORCL r=0.0092, PnL=$62.33

Simulating Trading Days:  77%|███████▋  | 68/88 [16:25<00:29,  1.46s/it]

[SIM] 2017-08-03 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.631, kelly=0.288) with $2979.72 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.666, kelly=0.344) with $3548.85 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.860, kelly=0.720) with $7442.17 allocation
[PORT] Sector Financial: selecting MA (p_up=0.714, kelly=0.429) with $4431.50 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.932, kelly=0.870) with $8984.44 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.844, kelly=0.682) with $7047.50 allocation
[PORT] Sector Services: selecting WMT (p_up=0.882, kelly=0.759) with $7843.13 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.864, kelly=0.730) with $7540.80 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.650, kelly=0.289) with $2987.34 allocation
[SIM] 2017-08-03 00:00:00: 9 trades proposed.
[TRADE] 2017-08-03 00:00:00: allocated $8984.44 to PFE exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $7843.13 to WMT exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $7540.80 to ORCL exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $6625.39 to PM exiting on 2017-08-04 00:00:00
[EXIT] 2017-08-04 00:00:00: PFE r=0.0063, PnL=$56.44
[EXIT] 2017-08-04 00:00:00: WMT r=-0.0048, PnL=$-37.82
[EXIT] 2017-08-04 00:00:00: ORCL r=-0.0054, PnL=$-40.53
[EXIT] 2017-08-04 00:00:00: PM r=0.0024, PnL=$15.62

Simulating Trading Days:  78%|███████▊  | 69/88 [16:27<00:27,  1.45s/it]

[SIM] 2017-08-04 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.638, kelly=0.302) with $3122.01 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.662, kelly=0.335) with $3462.57 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.858, kelly=0.716) with $7399.16 allocation
[PORT] Sector Financial: selecting MA (p_up=0.692, kelly=0.386) with $3988.19 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.927, kelly=0.860) with $8882.32 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.842, kelly=0.678) with $7004.69 allocation
[PORT] Sector Services: selecting WMT (p_up=0.880, kelly=0.755) with $7801.91 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.881, kelly=0.762) with $7875.77 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.636, kelly=0.261) with $2700.45 allocation
[SIM] 2017-08-04 00:00:00: 9 trades proposed.
[TRADE] 2017-08-04 00:00:00: allocated $8882.32 to PFE exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $7875.77 to ORCL exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $7801.91 to WMT exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $6431.87 to PM exiting on 2017-08-07 00:00:00
[EXIT] 2017-08-07 00:00:00: PFE r=-0.0098, PnL=$-87.13
[EXIT] 2017-08-07 00:00:00: ORCL r=-0.0064, PnL=$-50.45
[EXIT] 2017-08-07 00:00:00: WMT r=0.0099, PnL=$77.55
[EXIT] 2017-08-07 00:00:00: PM r=0.0096, PnL=$61.65

Simulating Trading Days:  80%|███████▉  | 70/88 [16:28<00:26,  1.46s/it]

[SIM] 2017-08-07 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.642, kelly=0.309) with $3189.79 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.612, kelly=0.226) with $2335.06 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.853, kelly=0.708) with $7313.08 allocation
[PORT] Sector Financial: selecting MA (p_up=0.707, kelly=0.416) with $4299.81 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.911, kelly=0.829) with $8566.40 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.836, kelly=0.666) with $6881.85 allocation
[PORT] Sector Services: selecting WMT (p_up=0.878, kelly=0.752) with $7772.36 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.892, kelly=0.785) with $8107.42 allocation
[PORT] Sector Utilities: selecting SRE (p_up=0.614, kelly=0.216) with $2229.66 allocation
[SIM] 2017-08-07 00:00:00: 9 trades proposed.
[TRADE] 2017-08-07 00:00:00: allocated $8566.40 to PFE exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $8107.42 to ORCL exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $7772.36 to WMT exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $6546.18 to PM exiting on 2017-08-08 00:00:00
[EXIT] 2017-08-08 00:00:00: PFE r=-0.0009, PnL=$-7.72
[EXIT] 2017-08-08 00:00:00: ORCL r=-0.0109, PnL=$-88.20
[EXIT] 2017-08-08 00:00:00: WMT r=0.0038, PnL=$29.64
[EXIT] 2017-08-08 00:00:00: PM r=-0.0103, PnL=$-67.24

Simulating Trading Days:  81%|████████  | 71/88 [16:30<00:24,  1.45s/it]

[SIM] 2017-08-08 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.635, kelly=0.296) with $3058.72 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.654, kelly=0.309) with $3188.24 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.848, kelly=0.698) with $7197.63 allocation
[PORT] Sector Financial: selecting MA (p_up=0.729, kelly=0.460) with $4746.34 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.893, kelly=0.795) with $8200.07 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.828, kelly=0.650) with $6709.47 allocation
[PORT] Sector Services: selecting WMT (p_up=0.873, kelly=0.741) with $7648.66 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.901, kelly=0.802) with $8278.60 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.594, kelly=0.178) with $1838.91 allocation
[SIM] 2017-08-08 00:00:00: 9 trades proposed.
[TRADE] 2017-08-08 00:00:00: allocated $8278.60 to ORCL exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $8200.07 to PFE exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $7648.66 to WMT exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $6824.98 to PM exiting on 2017-08-09 00:00:00
[EXIT] 2017-08-09 00:00:00: ORCL r=-0.0008, PnL=$-6.74
[EXIT] 2017-08-09 00:00:00: PFE r=0.0051, PnL=$41.89
[EXIT] 2017-08-09 00:00:00: WMT r=0.0002, PnL=$1.88
[EXIT] 2017-08-09 00:00:00: PM r=0.0065, PnL=$44.04

Simulating Trading Days:  82%|████████▏ | 72/88 [16:31<00:23,  1.44s/it]

[SIM] 2017-08-09 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.623, kelly=0.273) with $2814.25 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.678, kelly=0.357) with $3685.97 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.842, kelly=0.686) with $7082.71 allocation
[PORT] Sector Financial: selecting MA (p_up=0.753, kelly=0.506) with $5227.57 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.886, kelly=0.781) with $8064.57 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.817, kelly=0.628) with $6484.78 allocation
[PORT] Sector Services: selecting WMT (p_up=0.868, kelly=0.732) with $7562.49 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.910, kelly=0.822) with $8486.91 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.604, kelly=0.197) with $2030.61 allocation
[SIM] 2017-08-09 00:00:00: 9 trades proposed.
[TRADE] 2017-08-09 00:00:00: allocated $8486.91 to ORCL exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $8064.57 to PFE exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $7562.49 to WMT exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $6862.66 to PM exiting on 2017-08-10 00:00:00
[EXIT] 2017-08-10 00:00:00: ORCL r=-0.0196, PnL=$-166.07
[EXIT] 2017-08-10 00:00:00: PFE r=-0.0009, PnL=$-7.23
[EXIT] 2017-08-10 00:00:00: WMT r=-0.0116, PnL=$-88.03
[EXIT] 2017-08-10 00:00:00: PM r=-0.0103, PnL=$-70.76

Simulating Trading Days:  83%|████████▎ | 73/88 [16:33<00:21,  1.46s/it]

[SIM] 2017-08-10 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.602, kelly=0.232) with $2391.32 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.691, kelly=0.385) with $3958.39 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.836, kelly=0.674) with $6933.60 allocation
[PORT] Sector Financial: selecting BSAC (p_up=0.739, kelly=0.489) with $5035.80 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.887, kelly=0.783) with $8059.49 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.809, kelly=0.611) with $6287.39 allocation
[PORT] Sector Services: selecting WMT (p_up=0.872, kelly=0.739) with $7607.68 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.918, kelly=0.838) with $8622.54 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.616, kelly=0.221) with $2277.25 allocation
[SIM] 2017-08-10 00:00:00: 9 trades proposed.
[TRADE] 2017-08-10 00:00:00: allocated $8622.54 to ORCL exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $8059.49 to PFE exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $7607.68 to WMT exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $6587.29 to PM exiting on 2017-08-11 00:00:00
[EXIT] 2017-08-11 00:00:00: ORCL r=0.0029, PnL=$25.10
[EXIT] 2017-08-11 00:00:00: PFE r=-0.0051, PnL=$-41.00
[EXIT] 2017-08-11 00:00:00: WMT r=-0.0032, PnL=$-24.52
[EXIT] 2017-08-11 00:00:00: PM r=0.0058, PnL=$38.06

Simulating Trading Days:  84%|████████▍ | 74/88 [16:34<00:20,  1.47s/it]

[SIM] 2017-08-11 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.645, kelly=0.302) with $3108.06 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.709, kelly=0.419) with $4309.65 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.873, kelly=0.746) with $7681.79 allocation
[PORT] Sector Financial: selecting MA (p_up=0.780, kelly=0.562) with $5783.30 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.898, kelly=0.804) with $8273.01 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.796, kelly=0.585) with $6016.60 allocation
[PORT] Sector Services: selecting WMT (p_up=0.882, kelly=0.760) with $7817.91 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.932, kelly=0.866) with $8909.14 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.627, kelly=0.244) with $2509.44 allocation
[SIM] 2017-08-11 00:00:00: 9 trades proposed.
[TRADE] 2017-08-11 00:00:00: allocated $8909.14 to ORCL exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $8273.01 to PFE exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $7817.91 to WMT exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $5876.22 to UL exiting on 2017-08-14 00:00:00
[EXIT] 2017-08-14 00:00:00: ORCL r=0.0126, PnL=$112.66
[EXIT] 2017-08-14 00:00:00: PFE r=0.0018, PnL=$14.93
[EXIT] 2017-08-14 00:00:00: WMT r=0.0037, PnL=$29.17
[EXIT] 2017-08-14 00:00:00: UL r=0.0092, PnL=$53.85

Simulating Trading Days:  85%|████████▌ | 75/88 [16:36<00:19,  1.46s/it]

[SIM] 2017-08-14 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.730, kelly=0.470) with $4843.10 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.717, kelly=0.435) with $4489.42 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.885, kelly=0.769) with $7928.54 allocation
[PORT] Sector Financial: selecting MA (p_up=0.792, kelly=0.584) with $6024.08 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.891, kelly=0.791) with $8154.43 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.782, kelly=0.557) with $5748.85 allocation
[PORT] Sector Services: selecting WMT (p_up=0.881, kelly=0.759) with $7822.98 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.940, kelly=0.880) with $9078.65 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.635, kelly=0.261) with $2695.70 allocation
[SIM] 2017-08-14 00:00:00: 9 trades proposed.
[TRADE] 2017-08-14 00:00:00: allocated $9078.65 to ORCL exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $8154.43 to PFE exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $7928.54 to UL exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $5777.85 to WMT exiting on 2017-08-15 00:00:00
[EXIT] 2017-08-15 00:00:00: ORCL r=-0.0004, PnL=$-3.72
[EXIT] 2017-08-15 00:00:00: PFE r=0.0021, PnL=$17.14
[EXIT] 2017-08-15 00:00:00: UL r=0.0056, PnL=$44.31
[EXIT] 2017-08-15 00:00:00: WMT r=0.0009, PnL=$5.01

Simulating Trading Days:  86%|████████▋ | 76/88 [16:37<00:17,  1.48s/it]

[SIM] 2017-08-15 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.789, kelly=0.586) with $6046.20 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.702, kelly=0.406) with $4194.43 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.885, kelly=0.769) with $7937.86 allocation
[PORT] Sector Financial: selecting BSAC (p_up=0.730, kelly=0.472) with $4865.99 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.885, kelly=0.779) with $8034.50 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.776, kelly=0.545) with $5621.06 allocation
[PORT] Sector Services: selecting WMT (p_up=0.866, kelly=0.727) with $7500.46 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.942, kelly=0.884) with $9127.05 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.638, kelly=0.267) with $2750.81 allocation
[SIM] 2017-08-15 00:00:00: 9 trades proposed.
[TRADE] 2017-08-15 00:00:00: allocated $9127.05 to ORCL exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $7937.86 to UL exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $8034.50 to PFE exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $5858.88 to WMT exiting on 2017-08-16 00:00:00
[EXIT] 2017-08-16 00:00:00: ORCL r=0.0086, PnL=$78.50
[EXIT] 2017-08-16 00:00:00: UL r=-0.0007, PnL=$-5.51
[EXIT] 2017-08-16 00:00:00: PFE r=-0.0006, PnL=$-4.81
[EXIT] 2017-08-16 00:00:00: WMT r=0.0026, PnL=$15.23

Simulating Trading Days:  88%|████████▊ | 77/88 [16:39<00:16,  1.47s/it]

[SIM] 2017-08-16 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.826, kelly=0.658) with $6798.83 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.672, kelly=0.346) with $3576.75 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.878, kelly=0.756) with $7805.89 allocation
[PORT] Sector Financial: selecting BSAC (p_up=0.725, kelly=0.462) with $4772.76 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.883, kelly=0.775) with $8005.87 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.772, kelly=0.535) with $5530.21 allocation
[PORT] Sector Services: selecting WMT (p_up=0.844, kelly=0.684) with $7061.55 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.939, kelly=0.878) with $9064.89 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.644, kelly=0.280) with $2887.86 allocation
[SIM] 2017-08-16 00:00:00: 9 trades proposed.
[TRADE] 2017-08-16 00:00:00: allocated $9064.89 to ORCL exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $8005.87 to PFE exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $7805.89 to UL exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $6106.66 to WMT exiting on 2017-08-17 00:00:00
[EXIT] 2017-08-17 00:00:00: ORCL r=-0.0142, PnL=$-128.84
[EXIT] 2017-08-17 00:00:00: PFE r=-0.0123, PnL=$-98.39
[EXIT] 2017-08-17 00:00:00: UL r=-0.0085, PnL=$-66.47
[EXIT] 2017-08-17 00:00:00: WMT r=-0.0158, PnL=$-96.52

Simulating Trading Days:  89%|████████▊ | 78/88 [16:40<00:14,  1.46s/it]

[SIM] 2017-08-17 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.855, kelly=0.716) with $7365.99 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.753, kelly=0.515) with $5294.48 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.877, kelly=0.753) with $7750.55 allocation
[PORT] Sector Financial: selecting BSAC (p_up=0.721, kelly=0.454) with $4672.02 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.875, kelly=0.761) with $7825.08 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.771, kelly=0.534) with $5499.06 allocation
[PORT] Sector Services: selecting WMT (p_up=0.818, kelly=0.629) with $6473.90 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.929, kelly=0.859) with $8840.05 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.647, kelly=0.285) with $2927.57 allocation
[SIM] 2017-08-17 00:00:00: 9 trades proposed.
[TRADE] 2017-08-17 00:00:00: allocated $8840.05 to ORCL exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $7750.55 to UL exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $7825.08 to PFE exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $6450.56 to XOM exiting on 2017-08-18 00:00:00
[EXIT] 2017-08-18 00:00:00: ORCL r=0.0014, PnL=$12.75
[EXIT] 2017-08-18 00:00:00: UL r=0.0025, PnL=$19.02
[EXIT] 2017-08-18 00:00:00: PFE r=-0.0085, PnL=$-66.50
[EXIT] 2017-08-18 00:00:00: XOM r=0.0050, PnL=$32.14

Simulating Trading Days:  90%|████████▉ | 79/88 [16:42<00:13,  1.49s/it]

[SIM] 2017-08-18 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.879, kelly=0.762) with $7840.91 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.751, kelly=0.511) with $5259.14 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.890, kelly=0.779) with $8011.01 allocation
[PORT] Sector Financial: selecting BSAC (p_up=0.715, kelly=0.442) with $4545.21 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.893, kelly=0.795) with $8182.06 allocation
[PORT] Sector Industrial Goods: selecting ABB (p_up=0.766, kelly=0.524) with $5389.41 allocation
[PORT] Sector Services: selecting WMT (p_up=0.797, kelly=0.587) with $6036.30 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.922, kelly=0.845) with $8696.54 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.662, kelly=0.314) with $3231.84 allocation
[SIM] 2017-08-18 00:00:00: 9 trades proposed.
[TRADE] 2017-08-18 00:00:00: allocated $8696.54 to ORCL exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $8182.06 to PFE exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $8011.01 to UL exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $5975.85 to XOM exiting on 2017-08-21 00:00:00
[EXIT] 2017-08-21 00:00:00: ORCL r=0.0058, PnL=$50.08
[EXIT] 2017-08-21 00:00:00: PFE r=0.0028, PnL=$22.54
[EXIT] 2017-08-21 00:00:00: UL r=0.0070, PnL=$56.03
[EXIT] 2017-08-21 00:00:00: XOM r=-0.0034, PnL=$-20.27

Simulating Trading Days:  91%|█████████ | 80/88 [16:43<00:11,  1.48s/it]

[SIM] 2017-08-21 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.881, kelly=0.767) with $7896.68 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.760, kelly=0.528) with $5435.46 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.894, kelly=0.787) with $8107.42 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.685, kelly=0.389) with $4007.18 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.915, kelly=0.837) with $8616.12 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.717, kelly=0.444) with $4569.24 allocation
[PORT] Sector Services: selecting WMT (p_up=0.781, kelly=0.554) with $5707.76 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.912, kelly=0.825) with $8492.85 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.692, kelly=0.376) with $3871.60 allocation
[SIM] 2017-08-21 00:00:00: 9 trades proposed.
[TRADE] 2017-08-21 00:00:00: allocated $8616.12 to PFE exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $8492.85 to ORCL exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $8107.42 to UL exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $5681.59 to XOM exiting on 2017-08-22 00:00:00
[EXIT] 2017-08-22 00:00:00: PFE r=0.0119, PnL=$102.57
[EXIT] 2017-08-22 00:00:00: ORCL r=0.0074, PnL=$62.52
[EXIT] 2017-08-22 00:00:00: UL r=0.0057, PnL=$46.46
[EXIT] 2017-08-22 00:00:00: XOM r=0.0047, PnL=$26.78

Simulating Trading Days:  92%|█████████▏| 81/88 [16:44<00:10,  1.47s/it]

[SIM] 2017-08-22 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.813, kelly=0.633) with $6539.52 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.763, kelly=0.535) with $5524.47 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.889, kelly=0.778) with $8034.70 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.688, kelly=0.395) with $4079.31 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.937, kelly=0.879) with $9074.43 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.720, kelly=0.449) with $4637.98 allocation
[PORT] Sector Services: selecting WMT (p_up=0.772, kelly=0.537) with $5542.71 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.896, kelly=0.794) with $8195.78 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.735, kelly=0.462) with $4770.03 allocation
[SIM] 2017-08-22 00:00:00: 9 trades proposed.
[TRADE] 2017-08-22 00:00:00: allocated $9074.43 to PFE exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $8195.78 to ORCL exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $8034.70 to UL exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $5664.58 to PTR exiting on 2017-08-23 00:00:00
[EXIT] 2017-08-23 00:00:00: PFE r=0.0027, PnL=$24.64
[EXIT] 2017-08-23 00:00:00: ORCL r=-0.0039, PnL=$-31.61
[EXIT] 2017-08-23 00:00:00: UL r=-0.0014, PnL=$-11.10
[EXIT] 2017-08-23 00:00:00: PTR r=0.0045, PnL=$25.36

Simulating Trading Days:  93%|█████████▎| 82/88 [16:46<00:08,  1.48s/it]

[SIM] 2017-08-23 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.811, kelly=0.628) with $6482.22 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.754, kelly=0.517) with $5338.25 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.884, kelly=0.767) with $7923.16 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.682, kelly=0.384) with $3959.31 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.939, kelly=0.882) with $9109.06 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.714, kelly=0.437) with $4516.28 allocation
[PORT] Sector Services: selecting WMT (p_up=0.762, kelly=0.516) with $5328.89 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.869, kelly=0.740) with $7637.15 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.767, kelly=0.528) with $5453.90 allocation
[SIM] 2017-08-23 00:00:00: 9 trades proposed.
[TRADE] 2017-08-23 00:00:00: allocated $9109.06 to PFE exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $7923.16 to UL exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $7637.15 to ORCL exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $6302.30 to PTR exiting on 2017-08-24 00:00:00
[EXIT] 2017-08-24 00:00:00: PFE r=-0.0003, PnL=$-2.74
[EXIT] 2017-08-24 00:00:00: UL r=-0.0031, PnL=$-24.66
[EXIT] 2017-08-24 00:00:00: ORCL r=0.0024, PnL=$18.68
[EXIT] 2017-08-24 00:00:00: PTR r=0.0234, PnL=$147.45

Simulating Trading Days:  94%|█████████▍| 83/88 [16:47<00:07,  1.47s/it]

[SIM] 2017-08-24 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 60 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.790, kelly=0.588) with $6075.37 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.738, kelly=0.485) with $5010.22 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.883, kelly=0.764) with $7902.94 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.678, kelly=0.374) with $3870.85 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.925, kelly=0.856) with $8845.30 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.713, kelly=0.435) with $4491.85 allocation
[PORT] Sector Services: selecting WMT (p_up=0.767, kelly=0.525) with $5431.11 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.836, kelly=0.674) with $6962.66 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.773, kelly=0.540) with $5582.63 allocation
[SIM] 2017-08-24 00:00:00: 9 trades proposed.
[TRADE] 2017-08-24 00:00:00: allocated $8845.30 to PFE exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $7902.94 to UL exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $6962.66 to ORCL exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $6075.37 to PTR exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $1227.02 to NGG exiting on 2017-08-25 00:00:00
[EXIT] 2017-08-25 00:00:00: PFE r=0.0048, PnL=$42.59
[EXIT] 2017-08-25 00:00:00: UL r=0.0064, PnL=$50.71
[EXIT] 2017-08-25 00:00:00: ORCL r=0.0010, PnL=$7.08
[EXIT] 2017-08-25 00:00:00: PTR r=0.0047, PnL=$28.34
[EXIT] 2017-08-25 00:00:00: NGG r=0.0008, PnL=$0.97

Simulating Trading Days:  95%|█████████▌| 84/88 [16:49<00:05,  1.49s/it]

[SIM] 2017-08-25 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 61 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.783, kelly=0.582) with $6024.69 allocation
[PORT] Sector Conglomerates: selecting CODI (p_up=0.734, kelly=0.478) with $4946.99 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.882, kelly=0.763) with $7898.23 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.671, kelly=0.362) with $3750.33 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.879, kelly=0.768) with $7945.10 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.707, kelly=0.423) with $4381.74 allocation
[PORT] Sector Services: selecting WMT (p_up=0.776, kelly=0.544) with $5627.11 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.797, kelly=0.596) with $6171.95 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.752, kelly=0.498) with $5152.20 allocation
[SIM] 2017-08-25 00:00:00: 9 trades proposed.
[TRADE] 2017-08-25 00:00:00: allocated $7898.23 to UL exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $7945.10 to PFE exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $6171.95 to ORCL exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $6024.69 to SLB exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $3012.22 to WMT exiting on 2017-08-28 00:00:00
[EXIT] 2017-08-28 00:00:00: UL r=0.0016, PnL=$12.25
[EXIT] 2017-08-28 00:00:00: PFE r=0.0024, PnL=$19.04
[EXIT] 2017-08-28 00:00:00: ORCL r=0.0000, PnL=$0.00
[EXIT] 2017-08-28 00:00:00: SLB r=-0.0067, PnL=$-40.55
[EXIT] 2017-08-28 00:00:00: WMT r=-0.0076, PnL=$-22.99

Simulating Trading Days:  97%|█████████▋| 85/88 [16:50<00:04,  1.48s/it]

[SIM] 2017-08-28 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 59 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.772, kelly=0.560) with $5798.63 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.633, kelly=0.268) with $2772.91 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.873, kelly=0.746) with $7714.75 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.665, kelly=0.351) with $3631.27 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.818, kelly=0.651) with $6731.08 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.703, kelly=0.415) with $4292.90 allocation
[PORT] Sector Services: selecting WMT (p_up=0.787, kelly=0.567) with $5865.03 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.753, kelly=0.509) with $5265.85 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.711, kelly=0.415) with $4290.77 allocation
[SIM] 2017-08-28 00:00:00: 9 trades proposed.
[TRADE] 2017-08-28 00:00:00: allocated $7714.75 to UL exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $6731.08 to PFE exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $5865.03 to WMT exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $5798.63 to SLB exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $4933.03 to ORCL exiting on 2017-08-29 00:00:00
[EXIT] 2017-08-29 00:00:00: UL r=0.0000, PnL=$0.00
[EXIT] 2017-08-29 00:00:00: PFE r=0.0009, PnL=$6.03
[EXIT] 2017-08-29 00:00:00: WMT r=0.0095, PnL=$55.62
[EXIT] 2017-08-29 00:00:00: SLB r=0.0008, PnL=$4.57
[EXIT] 2017-08-29 00:00:00: ORCL r=0.0043, PnL=$21.04

Simulating Trading Days:  98%|█████████▊| 86/88 [16:52<00:02,  1.49s/it]

[SIM] 2017-08-29 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 57 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.757, kelly=0.531) with $5498.62 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.637, kelly=0.277) with $2866.00 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.866, kelly=0.732) with $7576.44 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.709, kelly=0.442) with $4582.48 allocation
[PORT] Sector Healthcare: selecting PFE (p_up=0.755, kelly=0.528) with $5470.39 allocation
[PORT] Sector Industrial Goods: selecting HON (p_up=0.695, kelly=0.399) with $4132.98 allocation
[PORT] Sector Services: selecting WMT (p_up=0.793, kelly=0.578) with $5990.23 allocation
[PORT] Sector Technology: selecting ORCL (p_up=0.707, kelly=0.418) with $4325.59 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.659, kelly=0.310) with $3210.38 allocation
[SIM] 2017-08-29 00:00:00: 9 trades proposed.
[TRADE] 2017-08-29 00:00:00: allocated $7576.44 to UL exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $5990.23 to WMT exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $5498.62 to SLB exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $5470.39 to PFE exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $4582.48 to BAC exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $1950.53 to ORCL exiting on 2017-08-30 00:00:00
[EXIT] 2017-08-30 00:00:00: UL r=-0.0083, PnL=$-62.57
[EXIT] 2017-08-30 00:00:00: WMT r=-0.0029, PnL=$-17.49
[EXIT] 2017-08-30 00:00:00: SLB r=-0.0017, PnL=$-9.53
[EXIT] 2017-08-30 00:00:00: PFE r=-0.0015, PnL=$-8.16
[EXIT] 2017-08-30 00:00:00: BAC r=0.0123, PnL=$56.36
[EXIT] 2017-08-30 00:00:00: ORCL r=0.0071, PnL=$13.81

Simulating Trading Days:  99%|█████████▉| 87/88 [16:53<00:01,  1.48s/it]

[SIM] 2017-08-30 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.732, kelly=0.484) with $5007.03 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.633, kelly=0.268) with $2778.63 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.853, kelly=0.705) with $7296.75 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.720, kelly=0.463) with $4791.33 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.615, kelly=0.240) with $2485.14 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.781, kelly=0.558) with $5779.07 allocation
[PORT] Sector Services: selecting WMT (p_up=0.793, kelly=0.579) with $5991.75 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.603, kelly=0.254) with $2627.30 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.629, kelly=0.248) with $2565.36 allocation
[SIM] 2017-08-30 00:00:00: 9 trades proposed.
[TRADE] 2017-08-30 00:00:00: allocated $7296.75 to UL exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $5991.75 to WMT exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $5779.07 to MMM exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $5007.03 to SLB exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $4791.33 to BAC exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $2194.48 to GMRE exiting on 2017-08-31 00:00:00
[EXIT] 2017-08-31 00:00:00: UL r=0.0099, PnL=$72.16
[EXIT] 2017-08-31 00:00:00: WMT r=-0.0060, PnL=$-35.86
[EXIT] 2017-08-31 00:00:00: MMM r=0.0031, PnL=$17.87
[EXIT] 2017-08-31 00:00:00: SLB r=0.0019, PnL=$9.48
[EXIT] 2017-08-31 00:00:00: BAC r=0.0008, PnL=$4.01
[EXIT] 2017-08-31 00:00:00: GMRE r=-0.0024, PnL=$-5.18

Simulating Trading Days: 100%|██████████| 88/88 [16:55<00:00, 11.54s/it]

[SIM] 2017-08-31 00:00:00: built 88 predictions
[PORT] Received 88 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.701, kelly=0.423) with $4382.26 allocation
[PORT] Sector Conglomerates: selecting GMRE (p_up=0.626, kelly=0.253) with $2622.32 allocation
[PORT] Sector Consumer Goods: selecting UL (p_up=0.846, kelly=0.691) with $7155.77 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.715, kelly=0.454) with $4700.16 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.670, kelly=0.331) with $3431.69 allocation
[PORT] Sector Industrial Goods: selecting MMM (p_up=0.801, kelly=0.597) with $6189.66 allocation
[PORT] Sector Services: selecting DIS (p_up=0.873, kelly=0.747) with $7741.34 allocation
[PORT] Sector Technology: selecting GOOG (p_up=0.602, kelly=0.252) with $2609.57 allocation
[PORT] Sector Utilities: selecting NGG (p_up=0.615, kelly=0.220) with $2277.37 allocation
[SIM] 2017-08-31 00:00:00: 9 trades proposed.

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-28,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'DUK', 'sector': 'Utilities', 'pro..."
1,2017-05-01,100171.148458,70119.803921,100171.148458,100171.148458,171.148458,0.001711,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
2,2017-05-02,100157.775605,70110.442924,100157.775605,100157.775605,-13.372853,-0.000134,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
3,2017-05-03,100268.151471,70187.706030,100268.151471,100268.151471,110.375866,0.001102,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
4,2017-05-04,100301.537359,70211.076151,100301.537359,100301.537359,33.385888,0.000333,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
...,...,...,...,...,...,...,...,...
83,2017-08-25,103507.316786,72455.121750,103507.316786,103507.316786,129.692485,0.001255,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
84,2017-08-28,103475.063041,72432.544129,103475.063041,103475.063041,-32.253745,-0.000312,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
85,2017-08-29,103562.324864,72493.627405,103562.324864,103562.324864,87.261823,0.000843,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
86,2017-08-30,103534.736008,72474.315206,103534.736008,103534.736008,-27.588856,-0.000266,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
87,2017-08-31,103597.222553,103597.222553,103597.222553,103597.222553,62.486544,0.000604,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-28,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'DUK', 'sector': 'Utilities', 'pro..."
1,2017-05-01,100171.148458,70119.803921,100171.148458,100171.148458,171.148458,0.001711,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
2,2017-05-02,100157.775605,70110.442924,100157.775605,100157.775605,-13.372853,-0.000134,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
3,2017-05-03,100268.151471,70187.706030,100268.151471,100268.151471,110.375866,0.001102,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
4,2017-05-04,100301.537359,70211.076151,100301.537359,100301.537359,33.385888,0.000333,"[{'ticker': 'PM', 'sector': 'Consumer Goods', ..."
...,...,...,...,...,...,...,...,...
83,2017-08-25,103507.316786,72455.121750,103507.316786,103507.316786,129.692485,0.001255,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
84,2017-08-28,103475.063041,72432.544129,103475.063041,103475.063041,-32.253745,-0.000312,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
85,2017-08-29,103562.324864,72493.627405,103562.324864,103562.324864,87.261823,0.000843,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
86,2017-08-30,103534.736008,72474.315206,103534.736008,103534.736008,-27.588856,-0.000266,"[{'ticker': 'UL', 'sector': 'Consumer Goods', ..."
87,2017-08-31,103597.222553,103597.222553,103597.222553,103597.222553,62.486544,0.000604,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $103,597.22
Total Return on Investment (ROI): 3.60%
Annualized Sharpe Ratio: 4.27
--------------------------

In [36]:
import numpy as np
import pandas as pd

ret_col = f"ret_{1}d"
if ret_col not in master_df_with_target.columns:
    master_df_with_target = add_horizon_targets(master_df_with_target, H=1, price_col='close')

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
        # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 457
Total capital allocated: $2,665,367.11
Average position size:  $5,832.31
Completed trades with returns: 457
Winning trades: 262 (57.3%)
Losing trades:  182 (39.8%)
Total PnL: $3,597.22
Average PnL per trade: $7.87
Average return: 0.15%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Services,75,476093.468160,6347.912909,987.427366,13.165698,0.002155
Financial,44,191032.529005,4341.648386,887.925381,20.180122,0.004174
Consumer Goods,87,597386.249015,6866.508609,622.414735,7.154192,0.001140
Technology,35,197816.390050,5651.896859,499.032404,14.258069,0.003030
Conglomerates,35,178146.035591,5089.886731,402.862851,11.510367,0.001527
Industrial Goods,26,92768.153747,3568.005913,284.551294,10.944281,0.002706
Healthcare,64,413506.479351,6461.038740,208.530994,3.258297,0.000706
Basic Matierials,41,205668.393978,5016.302292,-60.608532,-1.478257,-0.000474
Utilities,50,312949.410818,6258.988216,-234.913940,-4.698279,-0.000500

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
223,2017-06-21,2017-06-22,ORCL,Technology,4840.866798,0.736075,0.011756,0.085690,414.811695
4,2017-04-28,2017-05-01,PICO,Conglomerates,5182.392095,0.782144,0.016334,0.043478,225.321074
332,2017-07-24,2017-07-25,WMT,Services,8778.646905,0.927340,0.024163,0.021199,186.099325
247,2017-06-27,2017-06-28,CHTR,Services,5129.129961,0.727026,0.013597,0.031618,162.175373
172,2017-06-08,2017-06-09,BAC,Financial,5304.623818,0.749787,0.011007,0.030475,161.656166
429,2017-08-23,2017-08-24,PTR,Basic Matierials,6302.298680,0.810632,0.018504,0.023396,147.451617
246,2017-06-27,2017-06-28,BAC,Financial,5316.951825,0.749725,0.011004,0.026214,139.378397
366,2017-08-02,2017-08-03,PFE,Healthcare,8899.170531,0.928903,0.019070,0.015492,137.867407
64,2017-05-15,2017-05-16,BABA,Services,6170.937266,0.796001,0.014534,0.021582,133.178126
319,2017-07-19,2017-07-20,UL,Consumer Goods,7427.572850,0.861650,0.015368,0.016992,126.206432

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
284,2017-07-07,2017-07-10,WMT,Services,7181.500429,0.854069,0.018472,-0.027877,-200.201026
170,2017-06-08,2017-06-09,NGG,Utilities,7040.885926,0.847277,0.016215,-0.025127,-176.917368
386,2017-08-09,2017-08-10,ORCL,Technology,8486.906464,0.910464,0.022055,-0.019568,-166.071249
70,2017-05-16,2017-05-17,BABA,Services,5954.500806,0.784445,0.013837,-0.026609,-158.440810
147,2017-06-02,2017-06-05,CHTR,Services,5765.056732,0.761813,0.015792,-0.024361,-140.439970
73,2017-05-16,2017-05-17,HSBC,Financial,4555.667168,0.724970,0.010444,-0.029498,-134.382641
406,2017-08-16,2017-08-17,ORCL,Technology,9064.891784,0.938515,0.023911,-0.014213,-128.841286
214,2017-06-20,2017-06-21,PM,Consumer Goods,7062.338938,0.845586,0.015364,-0.015724,-111.044825
249,2017-06-28,2017-06-29,PM,Consumer Goods,7102.879204,0.845547,0.015361,-0.015555,-110.487785
354,2017-07-28,2017-07-31,PM,Consumer Goods,7094.029006,0.842747,0.015189,-0.015189,-107.748488

TOP 10 SECTORS BY TOTAL PnL

                   total_pnl
sector
Services          987.427366
Financial         887.925381
Consumer Goods    622.414735
Technology        499.032404
Conglomerates     402.862851
Industrial Goods  284.551294
Healthcare        208.530994
Basic Matierials  -60.608532
Utilities        -234.913940

BOTTOM 10 SECTORS BY TOTAL PnL

                   total_pnl
sector
Services          987.427366
Financial         887.925381
Consumer Goods    622.414735
Technology        499.032404
Conglomerates     402.862851
Industrial Goods  284.551294
Healthcare        208.530994
Basic Matierials  -60.608532
Utilities        -234.913940

Top 10 Most Invested Tickers:

ticker
PM      59
WMT     54
PFE     43
NGG     37
ORCL    35
UL      28
CODI    27
BAC     26
SNY     21
PTR     18
Name: count, dtype: int64

Tickers Never Invested In (63):
{'TOT', 'PCLN', 'MCD', 'CMCSA', 'CHL', 'MDT', 'PEP', 'V', 'AGFS', 'C', 'CVX', 'GOOG', 'VZ', 'HD', 'BP', 'UNH', 'HRG', 'BCH', 'MO', 'SNP', 'NEE', 'CAT', 'NVS', 'RDS-B', 'AAPL', 'DIS', 'UTX', 'UPS', 'JPM', 'AMGN', 'GD', 'PPL', 'TSM', 'CELG', 'MRK', 'FB', 'BA', 'AMZN', 'MSFT', 'BSAC', 'PCG', 'CSCO', 'BUD', 'T', 'ABBV', 'BBL', 'WFC', 'JNJ', 'BRK-A', 'BHP', 'REX', 'PG', 'DHR', 'AEP', 'INTC', 'D', 'LMT', 'UN', 'SO', 'IEP', 'KO', 'TM', 'SPLP'}

In [38]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]