# Investment Simulation System

In [1]:
!nvidia-smi

zsh:1: command not found: nvidia-smi

In [2]:
%pip install pandas_ta_classic

Requirement already satisfied: pandas_ta_classic in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (0.3.59)
Requirement already satisfied: numpy>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.1.2)
Requirement already satisfied: pandas>=2.0.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2.9.0)
Requirement already satisfied: pytz>=2021.1 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (2025.2)
Requirement already satisfied: six>=1.16.0 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas_ta_classic) (1.16.0)
Requirement already satisfied: tzdata>=2022.7 in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (from pandas>=2.0.0->pandas_ta_classic) (2025.2)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install tqdm

Requirement already satisfied: tqdm in /Users/dylanhuang/micromamba/envs/df_ae2/lib/python3.13/site-packages (4.67.1)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [4]:
import os
import site

import os
import shutil
import gc
import warnings
import pandas as pd
import numpy as np
import joblib
from tqdm import tqdm
from datetime import timedelta

warnings.filterwarnings('ignore')

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.isotonic import IsotonicRegression

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

In [6]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as Fnn
from torch.optim.lr_scheduler import ReduceLROnPlateau

In [7]:
pandas_ta_classic_path = None
for sp in site.getsitepackages():
    pandas_ta_classic_path = os.path.join(sp, 'pandas_ta_classic')
    if os.path.exists(pandas_ta_classic_path):
        break

if pandas_ta_classic_path:
    squeeze_pro_path = os.path.join(pandas_ta_classic_path, 'momentum', 'squeeze_pro.py')
    if os.path.exists(squeeze_pro_path):
        try:
            with open(squeeze_pro_path, 'r') as f:
                lines = f.readlines()

            new_lines = []
            fixed = False
            for line in lines:
                if "from numpy import NaN as npNaN" in line:
                    new_lines.append(line.replace("from numpy import NaN as npNaN", "# from numpy import NaN as npNaN\nimport numpy as np\n"))
                    fixed = True
                    print("Modified import statement in squeeze_pro.py")
                else:
                    new_lines.append(line)

            if fixed:
                with open(squeeze_pro_path, 'w') as f:
                    f.writelines(new_lines)
                print("Successfully patched pandas_ta_classic/momentum/squeeze_pro.py")
            else:
                print("Could not find the problematic import line in squeeze_pro.py")

        except Exception as e:
            print(f"Error modifying squeeze_pro.py: {e}")
    else:
        print(f"Could not find squeeze_pro.py at {squeeze_pro_path}")
else:
    print("Could not find the pandas_ta_classic library installation path.")

import pandas_ta_classic as ta

Could not find the problematic import line in squeeze_pro.py

### Configurations

In [8]:
MODEL_SAVE_PATH = "trained_models/"
MIN_SEQUENCE_LENGTH = 12  # Minimum sequence length for any company
MAX_SEQUENCE_LENGTH = 12  # Maximum sequence length to cap computational cost
INITIAL_TRAINING_DAYS = 783  # Number of days to use for initial training only
KELLY_FRACTION = 0.1
SECTOR_CONFIDENCE_THRESHOLD = 0.30
RETRAIN_INTERVAL = 200
MAX_DAY_GAP = 5  # Maximum allowed gap in trading days (to account for weekends/holidays)

In [9]:
MAX_TOTAL_UTILIZATION      = 0.70   # never deploy more than 70% of capital at once
MAX_NEW_DAILY_UTILIZATION  = 0.30   # new trades today ≤ 30% of capital
MAX_TICKER_UTILIZATION     = 0.20   # per ticker cap (sum of all overlapping trades)
MAX_SECTOR_UTILIZATION     = 0.45   # per sector cap (sum across its tickers)
MAX_POSITION_SIZE          = 0.1   # single-trade cap

MAX_POSITIONS_PER_TICKER   = 3      # ladder depth per ticker
MIN_TRADE_DOLLARS          = 100.0  # skip dust trades

KELLY_TRADE_CAP            = 0.30   # cap raw Kelly per trade (before other caps)
DRAWDOWN_THROTTLE_LEVELS   = [(0.05, 0.50), (0.10, 0.25)]  # (peak_dd, utilization_multiplier)

In [10]:
BUCKET_BINS   = [-np.inf, -0.02, -0.005, 0.0, 0.005, 0.02, np.inf]
K = len(BUCKET_BINS) - 1

In [11]:
import random


def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

In [12]:
CALIBRATION_LOGGED = set()

In [13]:
def bucketize_with_edges(x, edges):
    # x: 1D np array of returns; edges: len K+1
    return np.clip(np.digitize(x, edges[1:-1], right=True), 0, len(edges)-2).astype(np.int64)

def make_cumulative_targets(y_idx, K):
    # y_idx in [0..K-1] -> T: [N,K-1] with T[:,k]=1(y>k)
    y = y_idx.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def ordinal_to_class_probs(P_rep):
    # P_rep: [N,K-1] with P(y>k) (after sigmoid), repaired monotone
    N, K1 = P_rep.shape; K = K1+1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:,0] = 1.0 - P_rep[:,0]
    for c in range(1, K-1):
        Pc[:,c] = np.clip(P_rep[:,c-1] - P_rep[:,c], 0., 1.)
    Pc[:,K-1] = P_rep[:,K1-1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)

def monotone_repair_numpy(P):
    P = np.asarray(P, dtype=np.float32).copy()
    for k in range(P.shape[1]-2, -1, -1):
        P[:,k] = np.maximum(P[:,k], P[:,k+1])
    return P

In [14]:
# multiclass calibration tuned for macro-F1 balance
def _class_dist(y_hat, K):
    hist = np.bincount(y_hat, minlength=K).astype(np.float32)
    return hist / max(1, y_hat.size)

def _balance_penalty(p_hat, p_target, norm="l1"):
    if norm == "l1":
        return float(np.abs(p_hat - p_target).sum())
    elif norm == "l2":
        return float(np.sqrt(((p_hat - p_target) ** 2).sum()))
    else:
        return float(np.abs(p_hat - p_target).sum())

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    # decode ordinal cumulative probs to class indices using per-head taus.
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def tune_temperature_and_taus(
    Z_val,
    y_val_idx,
    K,
    T_grid=np.linspace(0.6, 2.5, 15),
    tau_grid=np.linspace(0.2, 0.8, 31),
    lambda_balance=0.05,
    target_priors="uniform",
    coord_rounds=3,
):
    """Learn a temperature T and per-head taus by maximizing macro-F1 with a balance penalty."""
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.detach().cpu().numpy()

    N, K_1 = Z_val.shape
    assert K_1 == K - 1

    if isinstance(target_priors, str) and target_priors == "uniform":
        p_target = np.ones(K, dtype=np.float32) / K
    else:
        p_target = np.asarray(target_priors, dtype=np.float32)
        p_target = p_target / p_target.sum()

    best = {"score": -1e9, "T": 1.0, "taus": np.full(K_1, 0.5, np.float32)}

    for T in T_grid:
        P_cum = 1.0 / (1.0 + np.exp(-(Z_val / T)))
        P_rep = monotone_repair_numpy(P_cum)

        taus = np.full(K_1, 0.5, dtype=np.float32)
        for _ in range(coord_rounds):
            for k in range(K_1):
                best_k = (taus[k], -1e9)
                for tau in tau_grid:
                    taus_try = taus.copy()
                    taus_try[k] = tau
                    y_hat = decode_ordinal_with_taus(P_rep, taus_try)
                    f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
                    p_hat = _class_dist(y_hat, K)
                    score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")
                    if score > best_k[1]:
                        best_k = (tau, score)
                taus[k] = best_k[0]

        y_hat = decode_ordinal_with_taus(P_rep, taus)
        f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
        p_hat = _class_dist(y_hat, K)
        score = f1 - lambda_balance * _balance_penalty(p_hat, p_target, norm="l1")

        if score > best["score"]:
            best.update({"score": score, "T": float(T), "taus": taus.astype(np.float32)})

    return best["T"], best["taus"]

#### Define Horizon Target
For a horizon H, compute both the direction and H-day return off the same base day t

In [15]:
def add_horizon_targets(df: pd.DataFrame, H: int, price_col='close') -> pd.DataFrame:
    df = df.sort_values(['ticker','date']).copy()
    df[f'ret_{H}d']    = df.groupby('ticker')[price_col].shift(-H) / df[price_col] - 1.0
    df[f'target_{H}d'] = (df[f'ret_{H}d'] > 0).astype(int)
    return df

#### Identify Contiguous Periods
Groups rows for a ticker into blocks where data gaps never exceed MAX_DAY_GAP

In [16]:
def identify_contiguous_periods(df: pd.DataFrame, max_gap_days: int = MAX_DAY_GAP) -> list:

    if df.empty:
        return []

    df = df.sort_values('date').reset_index(drop=True)
    dates = pd.to_datetime(df['date'])

    contiguous_periods = []
    start_idx = 0

    for i in range(1, len(dates)):
        gap = (dates[i] - dates[i-1]).days
        if gap > max_gap_days:
            # end current period and start new one
            contiguous_periods.append((start_idx, i-1))
            start_idx = i


    contiguous_periods.append((start_idx, len(dates)-1))


    contiguous_periods = [(s, e) for s, e in contiguous_periods if e - s >= MIN_SEQUENCE_LENGTH]

    return contiguous_periods

#### Calculate Dynamic Sequence Length 
Pick a sequence length tailored to the amount of history available for a ticker.
Avoids hard-coding a single window size for short vs long histories.

In [17]:
def calculate_dynamic_sequence_length(company_data_df: pd.DataFrame,
                                     min_length: int = MIN_SEQUENCE_LENGTH,
                                     max_length: int = MAX_SEQUENCE_LENGTH,
                                     target_fraction: float = 0.15) -> int:

    total_days = len(company_data_df)


    dynamic_length = int(total_days * target_fraction)
    dynamic_length = max(min_length, min(dynamic_length, max_length))

    return dynamic_length

#### Create Contiguous Sequences
Turn each contiguous period into overlapping (sequence_length) windows (X) and next-step labels (y).
Produces the actual training/validation tensors for the model.

In [18]:
def create_contiguous_sequences(data: np.ndarray, targets: np.ndarray,
                               contiguous_periods: list, sequence_length: int, H: int):

    X, y = [], []

    for start_idx, end_idx in contiguous_periods:
        usable_end = end_idx - H
        period_length = usable_end - start_idx + 1
        if period_length < sequence_length + 1:
            continue

        for i in range(start_idx + sequence_length -1 , usable_end + 1):
            X.append(data[i-sequence_length + 1 : i +1])
            y.append(targets[i + H])

    return np.array(X) if X else np.array([]), np.array(y) if y else np.array([])

#### Create Target Variable
Build the binary classification target per row.

In [19]:
def create_target_variable(df: pd.DataFrame) -> pd.DataFrame:

    print("Creating target variable...")
    df = df.sort_values(by=['ticker', 'date']).copy()
    df['next_day_close'] = df.groupby('ticker')['close'].shift(-1)
    df['target'] = (df['next_day_close'] > df['close']).astype(int)
    df.dropna(subset=['next_day_close'], inplace=True)
    df['target'] = df['target'].astype(int)
    print("Target variable created.")
    return df

#### Track Current Exposures from Open Trades
Settle exits first each day, then compute exposure books before opening new ones.

In [20]:
from collections import defaultdict

def compute_exposures(open_positions, sectors_by_ticker):
    expo_ticker = defaultdict(float)
    expo_sector = defaultdict(float)
    total = 0.0
    for pos in open_positions:
        amt = pos['invest']
        tkr = pos['ticker']
        sec = sectors_by_ticker.get(tkr, 'UNKNOWN')
        expo_ticker[tkr] += amt
        expo_sector[sec] += amt
        total += amt
    return total, dict(expo_ticker), dict(expo_sector)

#### Throttle Book When in Drawdown 
Apply multiplicative haircut to utilisation caps based on current peak to trough drawdown

In [21]:
def utilization_throttle(equity_curve):
    if not equity_curve:
        return 1.0
    peak = max(equity_curve)
    curr = equity_curve[-1]
    dd = 0.0 if peak == 0 else (peak - curr)/peak
    mult = 1.0
    for level, m in DRAWDOWN_THROTTLE_LEVELS:
        if dd >= level:
            mult = min(mult, m)
    return mult

#### Cap Each Proposed Trade
When sizing a new trade, clamp it by all remaining budgets

In [22]:
def clamp_by_caps(proposed_amt, capital, 
                  total_open, new_today_open, expo_ticker, expo_sector,
                  ticker, sector,
                  util_mult=1.0):
    # remaining dollar budgets
    rem_total  = MAX_TOTAL_UTILIZATION*util_mult*capital - total_open
    rem_new    = MAX_NEW_DAILY_UTILIZATION*util_mult*capital - new_today_open
    rem_ticker = MAX_TICKER_UTILIZATION*util_mult*capital - expo_ticker.get(ticker, 0.0)
    rem_sector = MAX_SECTOR_UTILIZATION*util_mult*capital - expo_sector.get(sector, 0.0)
    per_trade  = MAX_POSITION_SIZE*util_mult*capital

    # clamp
    max_affordable = max(0.0, min(proposed_amt, rem_total, rem_new, rem_ticker, rem_sector, per_trade))
    return max_affordable

#### Calculate Historical Payouts
Estimate average upside “b” per winning trade for Kelly sizing. 

Only looks at wins; losses are implicit in Kelly’s (1-p)/b term.

In [23]:

def calculate_historical_payouts(df, ret_col: str = None):
    """
    Returns a dict per ticker with:
      - 'b': avg_win / avg_loss_abs  (Kelly 'odds' ratio)
      - 'avg_win': mean positive return for the chosen horizon
      - 'avg_loss_abs': mean absolute negative return for the chosen horizon
    Uses the same horizon return column as the multiclass model (ret_{H}d).
    """
    if ret_col is None:
        ret_cols = [c for c in df.columns if c.startswith('ret_') and c.endswith('d')]
        ret_col = ret_cols[0] if ret_cols else None
    if ret_col is None or ret_col not in df.columns:
        raise ValueError("Return column for payout computation not found.")

    out = {}
    for t, g in df.groupby('ticker'):
        r = g[ret_col]
        wins = r[r > 0]
        losses = r[r < 0]
        avg_win = wins.mean() if not wins.empty else np.nan
        avg_loss_abs = (-losses).mean() if not losses.empty else np.nan

        if np.isfinite(avg_win) and np.isfinite(avg_loss_abs) and avg_loss_abs > 0:
            b = avg_win / avg_loss_abs
        else:
            b = np.nan

        out[t] = {'b': b, 'avg_win': avg_win, 'avg_loss_abs': avg_loss_abs}
    return out

##### PyTorch Helpers

In [24]:
class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):  # T: float32 matrix [N, K-1] with 0/1
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)
    def __len__(self): return len(self.X)
    def __getitem__(self, i): return self.X[i], self.T[i]
    
class LSTMOrdinal(nn.Module):
    def __init__(self, n_features, hidden1=128, hidden2=64, fc=32, dropout=0.3, inter_dropout=0.1, head='CORAL', K=6):
        super().__init__()
        self.K = K
        self.lstm1 = nn.LSTM(n_features, hidden1, num_layers=1, batch_first=True, dropout=0.1)
        self.inter_drop = nn.Dropout(inter_dropout)
        self.lstm2 = nn.LSTM(hidden1, hidden2, num_layers=1, batch_first=True, dropout=0.1)

        self.norm = nn.BatchNorm1d(hidden2)
        self.fc1 = nn.Linear(hidden2, fc)
        self.relu = nn.ReLU(inplace=True)
        self.drop = nn.Dropout(dropout)

        if head.upper() == 'CORAL':
            self.w = nn.Linear(fc, 1, bias=False)
            self._beta = nn.Parameter(torch.zeros(K-1))
            self.softplus = nn.Softplus()
            self.head_type = 'CORAL'
        else:
            self.fc_out = nn.Linear(fc, K-1)
            self.head_type = 'CORN'

    def forward(self, x):
        out1,_ = self.lstm1(x)
        out1 = self.inter_drop(out1)
        out2,_ = self.lstm2(out1)
        last = out2[:, -1, :]
        last = self.norm(last)
        z = self.relu(self.fc1(last))
        z = self.drop(z)
        if self.head_type == 'CORAL':
            base = self.w(z)                              # [B,1]
            deltas = self.softplus(self._beta)            # ≥0
            b = torch.cumsum(deltas, dim=0)               # [K-1]
            logits = base - b                              # broadcast -> [B,K-1]
        else:
            logits = self.fc_out(z)                        # [B,K-1]
        return logits

class EarlyStopper:
    def __init__(self, patience=15, mode='min'):
        self.patience = patience
        self.counter = 0
        self.best_metric = None
        self.best_state_dict = None
        self.mode = mode  # 'min' for val_loss
    def step(self, metric, model):
        if self.best_metric is None:
            improved = True
        else:
            improved = (metric < self.best_metric) if self.mode == 'min' else (metric > self.best_metric)
        if improved:
            self.best_metric = metric
            self.best_state_dict = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
            self.counter = 0
        else:
            self.counter += 1
        return improved

@torch.no_grad()
def _evaluate(model, loader, device, loss_fn):
    model.eval()
    total_loss = 0.0
    all_logits = []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = loss_fn(logits, yb)
        total_loss += loss.item() * xb.size(0)
        all_logits.append(logits.detach().cpu())
    avg_loss = total_loss / len(loader.dataset)
    logits = torch.cat(all_logits, dim=0).numpy()
    probs = 1.0 / (1.0 + np.exp(-logits))  # sigmoid
    return avg_loss, probs

#### Train Company Models
Train, calibrate, and persist a per-ticker classifier.
This encapsulates per-asset modelling with proper scaling and probability calibration, which is crucial since Kelly needs probabilities (not raw logits).

In [25]:
def train_company_models(company_data_df: pd.DataFrame,
                                 ticker: str,
                                 feature_cols: list,
                                 model_save_path: str,
                                 sequence_length: int = None,
                                 H: int = 1,
                                 K: int = K,        # global K
                                 head_type: str = 'CORAL'):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    print(f"[TRAIN] {ticker}: preparing data (H={H}) with {len(company_data_df)} rows")

    ret_col = f"ret_{H}d"
    if ret_col not in company_data_df.columns:
        company_data_df = add_horizon_targets(company_data_df, H=H, price_col='close')

    if sequence_length is None:
        sequence_length = calculate_dynamic_sequence_length(company_data_df)
    if len(company_data_df) < sequence_length + H + 10:
        print(f"[TRAIN] {ticker}: insufficient history for sequence length {sequence_length}")
        return False, sequence_length

    contigs = identify_contiguous_periods(company_data_df)
    if not contigs:
        print(f"[TRAIN] {ticker}: no contiguous periods found")
        return False, sequence_length

    rets = company_data_df[ret_col].values
    y_idx_all = bucketize_with_edges(rets, BUCKET_BINS)
    X_all = company_data_df[feature_cols].values

    X_seq, y_seq = create_contiguous_sequences(
        X_all, y_idx_all, contigs, sequence_length, H
    )
    if len(X_seq) < 40:
        print(f"[TRAIN] {ticker}: too few sequences ({len(X_seq)})")
        return False, sequence_length
    print(f"[TRAIN] {ticker}: built {len(X_seq)} sequences (seq_len={sequence_length})")

    X_tr, X_val, y_tr, y_val = train_test_split(X_seq, y_seq, test_size=0.2, shuffle=False)

    scaler = MinMaxScaler()
    F = X_tr.shape[-1]
    X_tr = scaler.fit_transform(X_tr.reshape(-1, F)).reshape(X_tr.shape)
    X_val = scaler.transform(X_val.reshape(-1, F)).reshape(X_val.shape)
    print(f"[TRAIN] {ticker}: scaler fitted on {X_tr.shape[0]} training sequences")
    # sanity checks
    assert F == len(feature_cols), \
        f"[TRAIN] {ticker}: feature dimension mismatch: X_tr has {F}, feature_cols has {len(feature_cols)}"

    print(f"[TRAIN] {ticker}: scaler.n_features_in_ = {scaler.n_features_in_}, len(feature_cols) = {len(feature_cols)}")
    assert scaler.n_features_in_ == len(feature_cols), \
        f"[TRAIN] {ticker}: scaler expects {scaler.n_features_in_} features, but feature_cols has {len(feature_cols)}"

    # sector_feature_indices = [feature_cols.index('sector_ret_1d'),
    #                       feature_cols.index('sector_ret_5d'),
    #                       feature_cols.index('sector_vol_20d')]

    # print(f"[TRAIN] {ticker}: sector feature mins = {scaler.data_min_[sector_feature_indices]}")
    # print(f"[TRAIN] {ticker}: sector feature maxs = {scaler.data_max_[sector_feature_indices]}")


    T_tr  = make_cumulative_targets(y_tr, K)
    T_val = make_cumulative_targets(y_val, K)

    train_ds = OrdinalSequenceDataset(X_tr, T_tr)
    val_ds   = OrdinalSequenceDataset(X_val, T_val)
    train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, drop_last=False)
    val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, drop_last=False)

    n_features = X_tr.shape[-1]
    model = LSTMOrdinal(n_features=n_features, head=head_type, K=K).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    pos_rate = T_tr.mean(axis=0)
    pos_w = ((1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)).astype(np.float32)
    pos_w = torch.tensor(pos_w, dtype=torch.float32, device=device) 
    print(f"[TRAIN] {ticker}: model n_features = {n_features}")

    
    def loss_fn(logits, T):
        losses = []
        for k in range(logits.shape[1]):
            losses.append(Fnn.binary_cross_entropy_with_logits(logits[:,k], T[:,k], pos_weight=pos_w[k]))
        return torch.stack(losses).mean()

    early = EarlyStopper(patience=15, mode='min')
    scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=7, min_lr=1e-7)

    for epoch in range(100):
        model.train()
        tot = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad(set_to_none=True)
            logits = model(xb)
            l = loss_fn(logits, yb)
            l.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            tot += l.item() * xb.size(0)

        model.eval()
        with torch.no_grad():
            vtot = 0.0
            for xb, yb in val_loader:
                xb, yb = xb.to(device), yb.to(device)
                logits = model(xb)
                l = loss_fn(logits, yb)
                vtot += l.item() * xb.size(0)
            val_loss = vtot / len(val_loader.dataset)

        scheduler.step(val_loss)
        _ = early.step(val_loss, model)
        if early.counter >= early.patience:
            break

    if early.best_state_dict is not None:
        model.load_state_dict(early.best_state_dict)

    ret_seq_full = company_data_df[ret_col].values[sequence_length:]
    ret_train = ret_seq_full[:len(y_tr)]
    mu_c = np.array([ret_train[y_tr==c].mean() if np.any(y_tr==c) else 0.0 for c in range(K)], dtype=np.float32)


    taus = None
    temperature = 1.0
    try:
        model.eval()
        batch = 256
        logits_list = []
        for start in range(0, len(X_val), batch):
            xb = torch.from_numpy(X_val[start:start+batch].astype(np.float32)).to(device)
            with torch.no_grad():
                logits = model(xb)
            logits_list.append(logits.cpu().numpy())
        if logits_list:
            val_logits = np.vstack(logits_list)
            T_star, taus = tune_temperature_and_taus(
                Z_val=val_logits,
                y_val_idx=y_val,
                K=K,
                T_grid=np.linspace(0.6, 2.5, 15),
                tau_grid=np.linspace(0.2, 0.8, 31),
                lambda_balance=0.05,
                target_priors="uniform",
                coord_rounds=3,
            )
            temperature = float(T_star)
            print(f"[CAL] {ticker}: taus={np.round(taus, 3)} | temperature={temperature:.3f}")
        else:
            print(f"[CAL] {ticker}: no validation logits -> skipping calibration")
    except Exception as exc:
        print(f"[CAL] {ticker}: calibration failed ({exc})")
        taus = None
        temperature = 1.0

    os.makedirs(model_save_path, exist_ok=True)
    torch.save(model.state_dict(), os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt"))
    joblib.dump(scaler, os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
    joblib.dump(sequence_length, os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
    joblib.dump(BUCKET_BINS, os.path.join(model_save_path, f"{ticker}_edges_H{H}.pkl"))
    joblib.dump(mu_c, os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))
    if taus is not None and len(taus) == (K - 1) and np.all(np.isfinite(taus)):
        joblib.dump(taus, os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored taus")
    if temperature is not None and np.isfinite(temperature):
        joblib.dump(float(temperature), os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl"))
        print(f"[SAVE] {ticker}: stored temperature scale {temperature:.3f}")
    print(f"[SAVE] {ticker}: artifacts persisted (H={H})")

    del model, scaler, train_loader, val_loader, train_ds, val_ds
    gc.collect()
    if torch.cuda.is_available(): torch.cuda.empty_cache()
    return True, sequence_length

#### Predict Next Day Performance 
One-step-ahead inference for a ticker on a given day.

Feeds calibrated p(up) into the portfolio/Kelly step.

In [26]:

def predict_next_horizon(company_data_df: pd.DataFrame,
                         ticker: str,
                         feature_cols: list,
                         model_save_path: str,
                         H: int,
                         K: int = 6,
                         head: str = "CORAL") -> dict | None:
    """
    Ordinal inference with optional calibration artifacts. Returns class probs plus
    summary stats so the simulator can log decisions.
    """
    try:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        state_dict_path = os.path.join(model_save_path, f"{ticker}_lstmORD_H{H}.pt")
        if not os.path.isfile(state_dict_path):
            return None

        scaler   = joblib.load(os.path.join(model_save_path, f"{ticker}_scaler_H{H}.pkl"))
        seq_len  = joblib.load(os.path.join(model_save_path, f"{ticker}_seq_length_H{H}.pkl"))
        mu_c     = joblib.load(os.path.join(model_save_path, f"{ticker}_mu_c_H{H}.pkl"))

        taus_path = os.path.join(model_save_path, f"{ticker}_taus_H{H}.pkl")
        T_path    = os.path.join(model_save_path, f"{ticker}_temperature_H{H}.pkl")
        taus = joblib.load(taus_path) if os.path.isfile(taus_path) else None
        temperature = float(joblib.load(T_path)) if os.path.isfile(T_path) else 1.0

        n_features = len(feature_cols)
        model = LSTMOrdinal(n_features=n_features, head=head.upper(), K=K).to(device)
        model.load_state_dict(torch.load(state_dict_path, map_location=device))
        model.eval()
    except Exception:
        return None

    if 'CALIBRATION_LOGGED' not in globals():
        globals()['CALIBRATION_LOGGED'] = set()
    if ticker not in CALIBRATION_LOGGED:
        if taus is not None:
            print(f"[CAL] {ticker}: loaded taus {np.round(taus,3)}")
        else:
            print(f"[CAL] {ticker}: no taus artifact found")
        print(f"[CAL] {ticker}: temperature scaling {temperature:.3f}")
        CALIBRATION_LOGGED.add(ticker)

    contiguous = identify_contiguous_periods(company_data_df)
    if not contiguous:
        return None
    start, end = contiguous[-1]
    period = company_data_df.iloc[start:end+1]
    if len(period) < seq_len:
        return None

    try:
        last_seq = period.tail(seq_len)
        X_scaled = scaler.transform(last_seq[feature_cols])
    except Exception:
        return None

    x = torch.from_numpy(np.asarray([X_scaled], dtype=np.float32)).to(device)

    with torch.no_grad():
        z = model(x)
        if temperature and temperature > 0 and temperature != 1.0:
            z = z / temperature
        P_cum = torch.sigmoid(z).cpu().numpy()
        P_cum = monotone_repair_numpy(P_cum)
        Pc    = ordinal_to_class_probs(P_cum)

    mu_c = np.asarray(mu_c, dtype=np.float32).reshape(-1)
    if mu_c.shape[0] != K:
        return None
    expected_rise = float((Pc[0] * mu_c).sum())

    top_bucket_idx = K - 1
    prob_top_bucket = float(Pc[0, top_bucket_idx])
    bucket_idx = int(np.argmax(Pc[0]))

    class_idx = None
    if taus is not None:
        taus = np.asarray(taus, dtype=np.float32).reshape(-1)
        if taus.shape[0] == (K - 1):
            class_idx = int(decode_ordinal_with_taus(P_cum, taus=taus)[0])

    positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
    prob_up = float(Pc[0, positive_buckets].sum()) if positive_buckets else prob_top_bucket

    return {
        'ticker': ticker,
        'expected_rise': expected_rise,
        'predicted_prob': prob_up,  # probability of positive move
        'prob_up': prob_up,
        'prob_bucket_top': prob_top_bucket,
        'bucket_idx': bucket_idx,
        'class_idx': class_idx,
        'class_probs': Pc[0].tolist(),
    }

#### Select and Size Portfolio
Turn a cross-section of calibrated predictions into position sizes.

Enforces diversification (one per sector) and risk discipline (Fractional Kelly).

In [27]:

def select_and_size_portfolio(daily_predictions_df: pd.DataFrame, payout_map: dict,
                              total_capital: float, sector_threshold: float,
                              kelly_fraction: float) -> pd.DataFrame:
    """Pick strongest candidates per sector and size using Kelly on prob_up and horizon payoffs."""
    if daily_predictions_df.empty:
        print("[PORT] No predictions provided today.")
        return pd.DataFrame()

    print(f"[PORT] Received {len(daily_predictions_df)} predictions for sizing.")
    df = daily_predictions_df.copy()

    if 'prob_up' not in df.columns and 'class_probs' in df.columns:
        positive_buckets = [i for i in range(K) if BUCKET_BINS[i] >= 0]
        def _sum_up(probs):
            if isinstance(probs, (list, tuple)) and len(probs) == K and positive_buckets:
                return float(sum(probs[i] for i in positive_buckets))
            return np.nan
        df['prob_up'] = df['class_probs'].apply(_sum_up)

    if 'prob_up' not in df.columns and 'predicted_prob' in df.columns:
        df['prob_up'] = df['predicted_prob']

    if 'expected_rise' not in df.columns:
        print("[PORT] Missing expected_rise; cannot size portfolio.")
        return pd.DataFrame()

    df = df[(df['prob_up'] >= sector_threshold) & (df['expected_rise'] > 0)]
    print(f"[PORT] {len(df)} tickers cleared prob_up ≥ {sector_threshold:.3f} and positive expected return.")
    if df.empty:
        return pd.DataFrame()

    winners = (df.sort_values(['sector', 'expected_rise'], ascending=[True, False])
                 .groupby('sector', as_index=False)
                 .head(1))
    if winners.empty:
        print("[PORT] No sector winners after grouping.")
        return pd.DataFrame()

    rows = []
    for _, row in winners.iterrows():
        ticker = row['ticker']
        sector = row['sector']
        p_up = float(row['prob_up'])
        payout = payout_map.get(ticker, {})
        b = payout.get('b') if isinstance(payout, dict) else float(payout)
        if not np.isfinite(b) or b <= 0:
            print(f"[PORT] Sector {sector}: skipping {ticker} due to invalid payout ratio {b}.")
            continue
        kelly_pct = p_up - (1.0 - p_up) / b
        if kelly_pct <= 0:
            print(f"[PORT] Sector {sector}: Kelly <= 0 for {ticker} (p_up={p_up:.3f}, b={b:.3f}).")
            continue
        investment_fraction = min(MAX_POSITION_SIZE, kelly_pct * kelly_fraction)
        investment_fraction = max(0.0, investment_fraction)
        investment_amount = total_capital * investment_fraction
        if investment_amount < MIN_TRADE_DOLLARS:
            print(f"[PORT] Sector {sector}: allocation ${investment_amount:.2f} below minimum; skipping {ticker}.")
            continue
        print(f"[PORT] Sector {sector}: selecting {ticker} (p_up={p_up:.3f}, kelly={kelly_pct:.3f}) "
              f"with ${investment_amount:.2f} allocation")
        rows.append({
            'ticker': ticker,
            'sector': sector,
            'prob_up': p_up,
            'predicted_prob': p_up,
            'expected_rise': row['expected_rise'],
            'bucket_idx': row.get('bucket_idx', np.nan),
            'investment_fraction': investment_fraction,
            'investment_amount': investment_amount
        })

    if not rows:
        print("[PORT] All sector winners rejected after Kelly sizing.")
        return pd.DataFrame()

    return pd.DataFrame(rows)

#### Models Exist for Ticker
Quick guard to avoid retraining if a ticker’s artifacts already exist.

Decide whether to train.

In [28]:
def models_exist_for_ticker(ticker: str, model_path: str, H: int = 1) -> bool:
    """Check the minimal set of artifacts needed for ordinal inference."""
    required = [
        f"{ticker}_lstmORD_H{H}.pt",      # model weights (ordinal head)
        f"{ticker}_scaler_H{H}.pkl",      # feature scaler
        f"{ticker}_seq_length_H{H}.pkl",  # sequence length
        f"{ticker}_mu_c_H{H}.pkl",        # per-class train means μ_c for expected return
    ]
    return all(os.path.exists(os.path.join(model_path, f)) for f in required)

#### Run Simulation
The “engine” — walks forward over dates, trains as needed, predicts, sizes, books PnL, and updates capital.

Enforces chronological integrity, periodic retraining, diversification, and proper capital tracking.

In [29]:
def run_simulation(master_df: pd.DataFrame, feature_cols: list,
                   initial_capital: float, initial_training_days: int = INITIAL_TRAINING_DAYS,
                   H: int = 1, allow_overlap: bool = True):

    print(f"Starting simulation with {initial_training_days} initial training days... (H={H})")
    capital = initial_capital
    equity_curve = [capital]
    simulation_log = []

    ret_col = f"ret_{H}d"
    tgt_col = f"target_{H}d"

    # precompute realized returns for settlement only (not used for training)
    master_df_returns = add_horizon_targets(master_df.copy(), H=H, price_col='close')
    ret_lookup = master_df_returns.set_index(['ticker', 'date'])[ret_col].to_dict()

    sectors_by_ticker = master_df.groupby('ticker')['sector'].first().to_dict()

    all_tickers = master_df['ticker'].unique()
    retrain_counter = {ticker: 0 for ticker in all_tickers}
    ticker_sequence_lengths = {}

    unique_dates = sorted(master_df['date'].unique())
    start_index = min(initial_training_days, len(unique_dates) - 1)
    print(f"Starting predictions from day {start_index} (after {initial_training_days} training days)")

    # overlapping book
    open_positions = []  # each: {'ticker','invest','entry_date','exit_date'}
    prev_equity_end = capital

    for i in tqdm(range(start_index, len(unique_dates)), desc="Simulating Trading Days"):
        current_date = unique_dates[i]

        # settle positions exiting today
        total_pnl_today = 0.0
        still_open = []
        for pos in open_positions:
            if pos['exit_date'] == current_date:
                rH = ret_lookup.get((pos['ticker'], pos['entry_date']), np.nan)
                if pd.notna(rH):
                    pnl = pos['invest'] * rH
                    total_pnl_today += pnl
                    print(f"[EXIT] {current_date}: {pos['ticker']} r={rH:.4f}, PnL=${pnl:.2f}")
                    capital += pos['invest'] + pnl  # release capital
            else:
                still_open.append(pos)
        open_positions = still_open

        # equity at START (after settlements, before new entries)
        open_notional_start = sum(p['invest'] for p in open_positions)
        equity_start = capital + open_notional_start
        daily_return = (equity_start / prev_equity_end) - 1.0 if prev_equity_end > 0 else 0.0

        # build prediction universe using info strictly before current_date
        historical_data = master_df[master_df['date'] < current_date].copy()
        historical_data = historical_data.drop(columns=[ret_col, tgt_col], errors='ignore')
        if historical_data.empty:
            continue
        historical_data = add_horizon_targets(historical_data, H=H, price_col='close')
        historical_data = historical_data.dropna(subset=[ret_col])
        if historical_data.empty:
            continue
        payout_map_day = calculate_historical_payouts(historical_data, ret_col=ret_col)

        if i == 0:  # no yesterday slice for display
            todays_data_for_prediction = pd.DataFrame(columns=master_df.columns)
        else:
            todays_data_for_prediction = master_df[master_df['date'] == unique_dates[i-1]]

        daily_predictions = []
        for ticker in todays_data_for_prediction['ticker'].unique():
            company_hist_data = historical_data[historical_data['ticker'] == ticker]
            if company_hist_data.empty:
                continue

            need_retrain = retrain_counter.get(ticker, 0) >= RETRAIN_INTERVAL
            have_models  = models_exist_for_ticker(ticker, MODEL_SAVE_PATH, H=H)
            if need_retrain or not have_models:
                print("Retraining model for ticker:", ticker)
                training_success, seq_length = train_company_models(
                    company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H
                )
                if training_success:
                    ticker_sequence_lengths[ticker] = seq_length
                    retrain_counter[ticker] = 0
                else:
                    continue

            pred = predict_next_horizon(company_hist_data, ticker, feature_cols, MODEL_SAVE_PATH, H=H)
            if pred:
                info = todays_data_for_prediction[todays_data_for_prediction['ticker'] == ticker].iloc[0]
                pred.update({'company_name': info['company_name'], 'sector': info['sector']})
                daily_predictions.append(pred)
                retrain_counter[ticker] += 1

        daily_predictions_df = pd.DataFrame(daily_predictions)
        print(f"[SIM] {current_date}: built {len(daily_predictions_df)} predictions")
        if (not daily_predictions_df.empty and
            'predicted_prob' not in daily_predictions_df.columns and
            'calibrated_prediction' not in daily_predictions_df.columns):
            print("[WARN] predicted_prob missing from daily_predictions_df columns:",
                  sorted(daily_predictions_df.columns))


        # size raw trades via Kelly
        investment_decision_df = select_and_size_portfolio(
            daily_predictions_df,
            payout_map_day,
            capital,
            sector_threshold=SECTOR_CONFIDENCE_THRESHOLD,
            kelly_fraction=KELLY_FRACTION,
        )
        if investment_decision_df.empty:
            print(f"[SIM] {current_date}: no trades proposed today.")
        else:
            print(f"[SIM] {current_date}: {len(investment_decision_df)} trades proposed.")

        # entry logic (allow_overlap controls laddering)
        exit_idx = i + H
        if exit_idx < len(unique_dates):
            exit_date = unique_dates[exit_idx]
        else:
            exit_date = None  # can't open new trades that we cannot exit within data

        entries_today = []
        if exit_date is not None and not investment_decision_df.empty:
            # ensure the column exists even if future changes rename it
            if 'predicted_prob' not in investment_decision_df.columns:
                if 'calibrated_prediction' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'calibrated_prediction': 'predicted_prob'}
                    )
                elif 'score' in investment_decision_df.columns:
                    investment_decision_df = investment_decision_df.rename(
                        columns={'score': 'predicted_prob'}
                    )
                else:
                    # nothing to sort by
                    investment_decision_df = pd.DataFrame()

            if not investment_decision_df.empty:
                investment_decision_df = investment_decision_df.sort_values('predicted_prob', ascending=False)


            # current exposures (post-settlement)
            util_mult = utilization_throttle(equity_curve)
            total_open, expo_ticker, expo_sector = compute_exposures(open_positions, sectors_by_ticker)
            new_today_open = 0.0

            for _, trade in investment_decision_df.iterrows():
                tkr = trade['ticker']
                sec = sectors_by_ticker.get(tkr, 'UNKNOWN')

                # per-ticker ladder depth
                open_count = sum(1 for p in open_positions if p['ticker'] == tkr)
                if allow_overlap:
                    if open_count >= MAX_POSITIONS_PER_TICKER:
                        continue
                else:
                    if open_count >= 1:
                        continue  # no overlapping allowed

                # base size from Kelly (already scaled by KELLY_FRACTION)
                base_amt = float(trade['investment_amount'])
                base_amt = min(base_amt, KELLY_TRADE_CAP * (capital + sum(p['invest'] for p in open_positions)))  # vs equity

                # clamp by remaining budgets
                amt = clamp_by_caps(base_amt, (capital + sum(p['invest'] for p in open_positions)),
                                    total_open, new_today_open, expo_ticker, expo_sector,
                                    tkr, sec, util_mult)
                if amt < MIN_TRADE_DOLLARS:
                    continue

                # lock capital and record position
                capital -= amt
                total_open += amt
                new_today_open += amt
                expo_ticker[tkr] = expo_ticker.get(tkr, 0.0) + amt
                expo_sector[sec] = expo_sector.get(sec, 0.0) + amt

                pos = {'ticker': tkr, 'invest': amt, 'entry_date': current_date, 'exit_date': exit_date}
                open_positions.append(pos)
                entries_today.append({**trade.to_dict(), 'allocated_amount': amt, 'exit_date': exit_date})
                print(f"[TRADE] {current_date}: allocated ${amt:.2f} to {tkr} exiting on {exit_date}")

        # equity at END (after entries)
        open_notional_end = sum(p['invest'] for p in open_positions)
        equity_end = capital + open_notional_end

        # log the day
        simulation_log.append({
            'date': current_date,
            'capital_start': equity_start - open_notional_start,  # cash only
            'capital_end': capital,                               # cash only
            'equity_start': equity_start,
            'equity_end': equity_end,
            'daily_pnl_realized': total_pnl_today,                # realized PnL today
            'daily_return': daily_return,
            'investments_made': entries_today
        })

        equity_curve.append(equity_end)
        prev_equity_end = equity_end

    return pd.DataFrame(simulation_log)

#### Calculate Final Results

In [30]:
def calculate_final_results(simulation_log: pd.DataFrame, initial_capital: float, rf_annual: float = 0.0):
    if simulation_log.empty:
        print("Simulation log is empty. No results to calculate.")
        return

    use_equity = {'equity_start', 'equity_end'}.issubset(simulation_log.columns)

    # precomputed daily_return if available and sane
    if 'daily_return' in simulation_log.columns:
        daily_returns = simulation_log['daily_return'].astype(float).values
    elif use_equity:
        eq_start = simulation_log['equity_start'].astype(float).values
        eq_end   = simulation_log['equity_end'].astype(float).values
        # r_t = equity_start_t / equity_end_{t-1} - 1
        prev_end = np.roll(eq_end, 1)
        prev_end[0] = eq_end[0] if eq_end[0] != 0 else eq_start[0]
        daily_returns = (eq_start / prev_end) - 1.0
    else:
        # cash-based (not ideal for H>0)
        print("Warning: Using cash-based returns")
        cap_start = simulation_log['capital_start'].astype(float).values
        cap_end   = simulation_log['capital_end'].astype(float).values
        prev_end  = np.roll(cap_end, 1)
        prev_end[0] = cap_end[0] if cap_end[0] != 0 else cap_start[0]
        daily_returns = (cap_start / prev_end) - 1.0

    daily_returns = np.where(np.isfinite(daily_returns), daily_returns, 0.0)

    # ROI from final equity if present, else cash
    end_col = 'equity_end' if use_equity else 'capital_end'
    final_value = float(simulation_log[end_col].iloc[-1])
    total_roi = (final_value / initial_capital) - 1.0

    # Sharpe
    excess = daily_returns - (rf_annual / 252.0)
    vol = excess.std(ddof=1)
    sharpe_ratio = (excess.mean() / vol * np.sqrt(252.0)) if vol > 1e-12 else 0.0

    print("\n--- Simulation Results ---")
    print(f"Initial Capital: ${initial_capital:,.2f}")
    print(f"Final Capital:   ${final_value:,.2f}")
    print(f"Total Return on Investment (ROI): {total_roi:.2%}")
    print(f"Annualized Sharpe Ratio: {sharpe_ratio:.2f}")
    print("--------------------------")

### Load Data

In [31]:
# master_df = pd.read_parquet('stocknet-dataset/master_df.parquet')
master_df = pd.read_parquet('stocknet-dataset/master_df_with_sector_and_bimeta_features.parquet')

In [32]:
master_df.drop(columns=['text','adj close','sentiment','emotion_anger','emotion_disgust','emotion_fear','emotion_joy','emotion_neutral','emotion_sadness','emotion_surprize'], inplace=True)
# Exclude ticker with missing meta-features across all rows
master_df = master_df[master_df['ticker'] != 'GMRE']

columns_to_check = ['EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    'lstm_prob_up_1d', 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
                    ]

master_df = master_df.dropna(subset=columns_to_check)

master_df.reset_index(drop=True, inplace=True)

display(master_df)

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

In [33]:
feature_columns = ['open','high','low', 'volume',
                   
                   'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean',
    
                    # 'stance_positive','stance_negative'
                ]

new_indicator_columns = [
    'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9',
    'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3',
    'BB_upper', 'BB_middle', 'BB_lower', 'OBV',
    
    'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 
    # 'sector_ret_60d',
    'sector_vol_20d', 'sector_dispersion_1d',
    'sector_rel_strength',
    
    # 'EMA_12_sector', 'EMA_26_sector', 'EMA_50_sector', 'MACD_12_26_9_sector', 'MACDh_12_26_9_sector', 
    # 'MACDs_12_26_9_sector', 'RSI_14_sector', 'sector_BB_upper', 'sector_BB_middle','sector_BB_lower'
    
    # 'lstm_prob_up_1d', 
    # 'lstm_brier_20', 'lstm_logloss_20', 'lstm_acc_20',
    
    'gru_pred_ret_1d', 
    'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20',
]

feature_columns.extend(new_indicator_columns)
print(f"Final feature columns: {feature_columns}")
print(f"Total number of features: {len(feature_columns)}")

Final feature columns: ['open', 'high', 'low', 'volume', 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_volume_mean', 'EMA_12', 'EMA_26', 'EMA_50', 'MACD_12_26_9', 'MACDh_12_26_9', 'MACDs_12_26_9', 'RSI_14', 'ATRr_14', 'STOCHRSIk_14_14_3_3', 'STOCHRSId_14_14_3_3', 'BB_upper', 'BB_middle', 'BB_lower', 'OBV', 'sector_ret_1d', 'sector_ret_5d', 'sector_ret_20d', 'sector_vol_20d', 'sector_dispersion_1d', 'sector_rel_strength', 'gru_pred_ret_1d', 'gru_abs_err_lag1', 'gru_mae_20', 'gru_rmse_20', 'gru_dir_acc_20']
Total number of features: 33

In [34]:
master_df.reset_index(drop=True, inplace=True)
master_df

,date,open,high,low,close,volume,ticker,stance_positive,stance_negative,sector,...,gru_rmse_20,gru_dir_acc_20,lstm_prob_up_1d,lstm_logit_up_1d,lstm_brier,lstm_logloss,lstm_correct,lstm_brier_20,lstm_logloss_20,lstm_acc_20
0,2014-03-04,75.857140,76.091431,75.395714,75.891426,64785000.0,AAPL,17.0,17.0,Consumer Goods,...,0.047611,0.600000,0.743493,1.064202,0.552781,1.360598,0.0,0.265279,0.723950,0.400000
1,2014-03-05,75.845711,76.392860,75.589996,76.051430,50015700.0,AAPL,13.0,8.0,Consumer Goods,...,0.045507,0.666667,0.728888,0.988988,0.073502,0.316235,1.0,0.313196,0.830058,0.333333
2,2014-03-06,76.112854,76.348572,75.442856,75.821426,46372200.0,AAPL,10.0,4.0,Consumer Goods,...,0.047723,0.571429,0.722673,0.957758,0.076910,0.324799,1.0,0.278954,0.756655,0.428571
3,2014-03-07,75.870003,75.997147,75.150002,75.777145,55182400.0,AAPL,23.0,5.0,Consumer Goods,...,0.049173,0.500000,0.686132,0.782095,0.470776,1.158781,0.0,0.253699,0.702673,0.500000
4,2014-03-10,75.480003,76.190002,75.477142,75.845711,44646000.0,AAPL,17.0,3.0,Consumer Goods,...,0.051356,0.555556,0.703303,0.863078,0.494636,1.215045,0.0,0.277818,0.753352,0.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75662,2017-08-25,76.559998,77.129997,76.430000,76.720001,6844900.0,XOM,0.0,0.0,Basic Matierials,...,0.024094,0.550000,0.518448,0.073827,0.231892,0.656915,1.0,0.253057,0.699271,0.450000
75663,2017-08-28,76.900002,76.940002,76.260002,76.470001,8229700.0,XOM,0.0,0.0,Basic Matierials,...,0.021807,0.550000,0.514868,0.059490,0.235353,0.663845,1.0,0.253938,0.701038,0.450000
75664,2017-08-29,76.209999,76.489998,76.080002,76.449997,7060400.0,XOM,0.0,0.0,Basic Matierials,...,0.020675,0.550000,0.523837,0.095419,0.226731,0.646575,1.0,0.255041,0.703251,0.450000
75665,2017-08-30,76.239998,76.449997,76.059998,76.099998,8218000.0,XOM,0.0,0.0,Basic Matierials,...,0.018285,0.550000,0.525389,0.101644,0.276034,0.745260,0.0,0.256353,0.705892,0.450000
75666,2017-08-31,76.269997,76.489998,76.050003,76.330002,15641700.0,XOM,0.0,0.0,Basic Matierials,...,0.018683,0.550000,0.551672,0.207429,0.304342,0.802230,0.0,0.254995,0.703159,0.450000

# Execute Pipeline

In [35]:
initial_capital = 100_000.0
simulation_results = run_simulation(
    master_df,
    feature_columns,
    initial_capital,
    initial_training_days=INITIAL_TRAINING_DAYS,
    H=1,
    allow_overlap=True
)

display(simulation_results.head(100))
display(simulation_results.tail(100))
calculate_final_results(simulation_results, initial_capital)

Starting simulation with 783 initial training days... (H=1)
Starting predictions from day 783 (after 783 training days)

Simulating Trading Days:   0%|          | 0/100 [00:00<?, ?it/s]

Retraining model for ticker: AAPL
[TRAIN] AAPL: preparing data (H=1) with 782 rows
[TRAIN] AAPL: built 770 sequences (seq_len=12)
[TRAIN] AAPL: scaler fitted on 616 training sequences
[TRAIN] AAPL: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AAPL: model n_features = 33
[CAL] AAPL: taus=[0.8  0.6  0.56 0.34 0.34] | temperature=1.007
[SAVE] AAPL: stored taus
[SAVE] AAPL: stored temperature scale 1.007
[SAVE] AAPL: artifacts persisted (H=1)
[CAL] AAPL: loaded taus [0.8  0.6  0.56 0.34 0.34]
[CAL] AAPL: temperature scaling 1.007
Retraining model for ticker: ABB
[TRAIN] ABB: preparing data (H=1) with 782 rows
[TRAIN] ABB: built 770 sequences (seq_len=12)
[TRAIN] ABB: scaler fitted on 616 training sequences
[TRAIN] ABB: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] ABB: model n_features = 33
[CAL] ABB: taus=[0.72 0.62 0.46 0.5  0.48] | temperature=1.821
[SAVE] ABB: stored taus
[SAVE] ABB: stored temperature scale 1.821
[SAVE] ABB: artifacts persisted (H=1)
[CAL] ABB: loaded taus [0.72 0.62 0.46 0.5  0.48]
[CAL] ABB: temperature scaling 1.821
Retraining model for ticker: ABBV
[TRAIN] ABBV: preparing data (H=1) with 720 rows
[TRAIN] ABBV: built 708 sequences (seq_len=12)
[TRAIN] ABBV: scaler fitted on 566 training sequences
[TRAIN] ABBV: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] ABBV: model n_features = 33
[CAL] ABBV: taus=[0.8  0.58 0.48 0.36 0.38] | temperature=0.736
[SAVE] ABBV: stored taus
[SAVE] ABBV: stored temperature scale 0.736
[SAVE] ABBV: artifacts persisted (H=1)
[CAL] ABBV: loaded taus [0.8  0.58 0.48 0.36 0.38]
[CAL] ABBV: temperature scaling 0.736
Retraining model for ticker: AEP
[TRAIN] AEP: preparing data (H=1) with 782 rows
[TRAIN] AEP: built 770 sequences (seq_len=12)
[TRAIN] AEP: scaler fitted on 616 training sequences
[TRAIN] AEP: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AEP: model n_features = 33
[CAL] AEP: taus=[0.74 0.5  0.4  0.2  0.32] | temperature=0.736
[SAVE] AEP: stored taus
[SAVE] AEP: stored temperature scale 0.736
[SAVE] AEP: artifacts persisted (H=1)
[CAL] AEP: loaded taus [0.74 0.5  0.4  0.2  0.32]
[CAL] AEP: temperature scaling 0.736
Retraining model for ticker: AGFS
[TRAIN] AGFS: preparing data (H=1) with 244 rows
[TRAIN] AGFS: built 232 sequences (seq_len=12)
[TRAIN] AGFS: scaler fitted on 185 training sequences
[TRAIN] AGFS: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AGFS: model n_features = 33
[CAL] AGFS: taus=[0.72 0.7  0.62 0.48 0.48] | temperature=1.957
[SAVE] AGFS: stored taus
[SAVE] AGFS: stored temperature scale 1.957
[SAVE] AGFS: artifacts persisted (H=1)
[CAL] AGFS: loaded taus [0.72 0.7  0.62 0.48 0.48]
[CAL] AGFS: temperature scaling 1.957
Retraining model for ticker: AMGN
[TRAIN] AMGN: preparing data (H=1) with 782 rows
[TRAIN] AMGN: built 770 sequences (seq_len=12)
[TRAIN] AMGN: scaler fitted on 616 training sequences
[TRAIN] AMGN: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AMGN: model n_features = 33
[CAL] AMGN: taus=[0.76 0.46 0.46 0.38 0.72] | temperature=0.736
[SAVE] AMGN: stored taus
[SAVE] AMGN: stored temperature scale 0.736
[SAVE] AMGN: artifacts persisted (H=1)
[CAL] AMGN: loaded taus [0.76 0.46 0.46 0.38 0.72]
[CAL] AMGN: temperature scaling 0.736
Retraining model for ticker: AMZN
[TRAIN] AMZN: preparing data (H=1) with 782 rows
[TRAIN] AMZN: built 770 sequences (seq_len=12)
[TRAIN] AMZN: scaler fitted on 616 training sequences
[TRAIN] AMZN: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] AMZN: model n_features = 33
[CAL] AMZN: taus=[0.8  0.58 0.5  0.32 0.22] | temperature=0.736
[SAVE] AMZN: stored taus
[SAVE] AMZN: stored temperature scale 0.736
[SAVE] AMZN: artifacts persisted (H=1)
[CAL] AMZN: loaded taus [0.8  0.58 0.5  0.32 0.22]
[CAL] AMZN: temperature scaling 0.736
Retraining model for ticker: BA
[TRAIN] BA: preparing data (H=1) with 782 rows
[TRAIN] BA: built 770 sequences (seq_len=12)
[TRAIN] BA: scaler fitted on 616 training sequences
[TRAIN] BA: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BA: model n_features = 33
[CAL] BA: taus=[0.76 0.52 0.54 0.46 0.44] | temperature=1.007
[SAVE] BA: stored taus
[SAVE] BA: stored temperature scale 1.007
[SAVE] BA: artifacts persisted (H=1)
[CAL] BA: loaded taus [0.76 0.52 0.54 0.46 0.44]
[CAL] BA: temperature scaling 1.007
Retraining model for ticker: BABA
[TRAIN] BABA: preparing data (H=1) with 288 rows
[TRAIN] BABA: built 276 sequences (seq_len=12)
[TRAIN] BABA: scaler fitted on 220 training sequences
[TRAIN] BABA: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BABA: model n_features = 33
[CAL] BABA: taus=[0.58 0.2  0.46 0.38 0.36] | temperature=2.364
[SAVE] BABA: stored taus
[SAVE] BABA: stored temperature scale 2.364
[SAVE] BABA: artifacts persisted (H=1)
[CAL] BABA: loaded taus [0.58 0.2  0.46 0.38 0.36]
[CAL] BABA: temperature scaling 2.364
Retraining model for ticker: BAC
[TRAIN] BAC: preparing data (H=1) with 782 rows
[TRAIN] BAC: built 770 sequences (seq_len=12)
[TRAIN] BAC: scaler fitted on 616 training sequences
[TRAIN] BAC: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BAC: model n_features = 33
[CAL] BAC: taus=[0.2  0.8  0.54 0.58 0.5 ] | temperature=0.736
[SAVE] BAC: stored taus
[SAVE] BAC: stored temperature scale 0.736
[SAVE] BAC: artifacts persisted (H=1)
[CAL] BAC: loaded taus [0.2  0.8  0.54 0.58 0.5 ]
[CAL] BAC: temperature scaling 0.736
Retraining model for ticker: BBL
[TRAIN] BBL: preparing data (H=1) with 782 rows
[TRAIN] BBL: built 770 sequences (seq_len=12)
[TRAIN] BBL: scaler fitted on 616 training sequences
[TRAIN] BBL: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BBL: model n_features = 33
[CAL] BBL: taus=[0.78 0.42 0.52 0.32 0.24] | temperature=0.871
[SAVE] BBL: stored taus
[SAVE] BBL: stored temperature scale 0.871
[SAVE] BBL: artifacts persisted (H=1)
[CAL] BBL: loaded taus [0.78 0.42 0.52 0.32 0.24]
[CAL] BBL: temperature scaling 0.871
Retraining model for ticker: BCH
[TRAIN] BCH: preparing data (H=1) with 782 rows
[TRAIN] BCH: built 770 sequences (seq_len=12)
[TRAIN] BCH: scaler fitted on 616 training sequences
[TRAIN] BCH: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BCH: model n_features = 33
[CAL] BCH: taus=[0.8  0.64 0.52 0.48 0.5 ] | temperature=2.500
[SAVE] BCH: stored taus
[SAVE] BCH: stored temperature scale 2.500
[SAVE] BCH: artifacts persisted (H=1)
[CAL] BCH: loaded taus [0.8  0.64 0.52 0.48 0.5 ]
[CAL] BCH: temperature scaling 2.500
Retraining model for ticker: BHP
[TRAIN] BHP: preparing data (H=1) with 782 rows
[TRAIN] BHP: built 770 sequences (seq_len=12)
[TRAIN] BHP: scaler fitted on 616 training sequences
[TRAIN] BHP: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BHP: model n_features = 33
[CAL] BHP: taus=[0.64 0.66 0.54 0.5  0.5 ] | temperature=2.364
[SAVE] BHP: stored taus
[SAVE] BHP: stored temperature scale 2.364
[SAVE] BHP: artifacts persisted (H=1)
[CAL] BHP: loaded taus [0.64 0.66 0.54 0.5  0.5 ]
[CAL] BHP: temperature scaling 2.364
Retraining model for ticker: BP
[TRAIN] BP: preparing data (H=1) with 782 rows
[TRAIN] BP: built 770 sequences (seq_len=12)
[TRAIN] BP: scaler fitted on 616 training sequences
[TRAIN] BP: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BP: model n_features = 33
[CAL] BP: taus=[0.7  0.6  0.5  0.44 0.44] | temperature=2.229
[SAVE] BP: stored taus
[SAVE] BP: stored temperature scale 2.229
[SAVE] BP: artifacts persisted (H=1)
[CAL] BP: loaded taus [0.7  0.6  0.5  0.44 0.44]
[CAL] BP: temperature scaling 2.229
Retraining model for ticker: BRK-A
[TRAIN] BRK-A: preparing data (H=1) with 782 rows
[TRAIN] BRK-A: built 770 sequences (seq_len=12)
[TRAIN] BRK-A: scaler fitted on 616 training sequences
[TRAIN] BRK-A: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BRK-A: model n_features = 33
[CAL] BRK-A: taus=[0.72 0.5  0.42 0.32 0.3 ] | temperature=0.871
[SAVE] BRK-A: stored taus
[SAVE] BRK-A: stored temperature scale 0.871
[SAVE] BRK-A: artifacts persisted (H=1)
[CAL] BRK-A: loaded taus [0.72 0.5  0.42 0.32 0.3 ]
[CAL] BRK-A: temperature scaling 0.871
Retraining model for ticker: BSAC
[TRAIN] BSAC: preparing data (H=1) with 782 rows
[TRAIN] BSAC: built 770 sequences (seq_len=12)
[TRAIN] BSAC: scaler fitted on 616 training sequences
[TRAIN] BSAC: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BSAC: model n_features = 33
[CAL] BSAC: taus=[0.76 0.7  0.52 0.38 0.2 ] | temperature=0.600
[SAVE] BSAC: stored taus
[SAVE] BSAC: stored temperature scale 0.600
[SAVE] BSAC: artifacts persisted (H=1)
[CAL] BSAC: loaded taus [0.76 0.7  0.52 0.38 0.2 ]
[CAL] BSAC: temperature scaling 0.600
Retraining model for ticker: BUD
[TRAIN] BUD: preparing data (H=1) with 782 rows
[TRAIN] BUD: built 770 sequences (seq_len=12)
[TRAIN] BUD: scaler fitted on 616 training sequences
[TRAIN] BUD: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] BUD: model n_features = 33
[CAL] BUD: taus=[0.6  0.5  0.34 0.26 0.22] | temperature=1.143
[SAVE] BUD: stored taus
[SAVE] BUD: stored temperature scale 1.143
[SAVE] BUD: artifacts persisted (H=1)
[CAL] BUD: loaded taus [0.6  0.5  0.34 0.26 0.22]
[CAL] BUD: temperature scaling 1.143
Retraining model for ticker: C
[TRAIN] C: preparing data (H=1) with 782 rows
[TRAIN] C: built 770 sequences (seq_len=12)
[TRAIN] C: scaler fitted on 616 training sequences
[TRAIN] C: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] C: model n_features = 33
[CAL] C: taus=[0.54 0.46 0.4  0.34 0.62] | temperature=0.600
[SAVE] C: stored taus
[SAVE] C: stored temperature scale 0.600
[SAVE] C: artifacts persisted (H=1)
[CAL] C: loaded taus [0.54 0.46 0.4  0.34 0.62]
[CAL] C: temperature scaling 0.600
Retraining model for ticker: CAT
[TRAIN] CAT: preparing data (H=1) with 782 rows
[TRAIN] CAT: built 770 sequences (seq_len=12)
[TRAIN] CAT: scaler fitted on 616 training sequences
[TRAIN] CAT: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CAT: model n_features = 33
[CAL] CAT: taus=[0.76 0.8  0.48 0.44 0.36] | temperature=0.600
[SAVE] CAT: stored taus
[SAVE] CAT: stored temperature scale 0.600
[SAVE] CAT: artifacts persisted (H=1)
[CAL] CAT: loaded taus [0.76 0.8  0.48 0.44 0.36]
[CAL] CAT: temperature scaling 0.600
Retraining model for ticker: CELG
[TRAIN] CELG: preparing data (H=1) with 782 rows
[TRAIN] CELG: built 770 sequences (seq_len=12)
[TRAIN] CELG: scaler fitted on 616 training sequences
[TRAIN] CELG: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CELG: model n_features = 33
[CAL] CELG: taus=[0.78 0.5  0.54 0.46 0.46] | temperature=0.871
[SAVE] CELG: stored taus
[SAVE] CELG: stored temperature scale 0.871
[SAVE] CELG: artifacts persisted (H=1)
[CAL] CELG: loaded taus [0.78 0.5  0.54 0.46 0.46]
[CAL] CELG: temperature scaling 0.871
Retraining model for ticker: CHL
[TRAIN] CHL: preparing data (H=1) with 782 rows
[TRAIN] CHL: built 770 sequences (seq_len=12)
[TRAIN] CHL: scaler fitted on 616 training sequences
[TRAIN] CHL: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CHL: model n_features = 33
[CAL] CHL: taus=[0.58 0.52 0.44 0.38 0.34] | temperature=1.279
[SAVE] CHL: stored taus
[SAVE] CHL: stored temperature scale 1.279
[SAVE] CHL: artifacts persisted (H=1)
[CAL] CHL: loaded taus [0.58 0.52 0.44 0.38 0.34]
[CAL] CHL: temperature scaling 1.279
Retraining model for ticker: CHTR
[TRAIN] CHTR: preparing data (H=1) with 782 rows
[TRAIN] CHTR: built 770 sequences (seq_len=12)
[TRAIN] CHTR: scaler fitted on 616 training sequences
[TRAIN] CHTR: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CHTR: model n_features = 33
[CAL] CHTR: taus=[0.8  0.74 0.7  0.52 0.42] | temperature=1.007
[SAVE] CHTR: stored taus
[SAVE] CHTR: stored temperature scale 1.007
[SAVE] CHTR: artifacts persisted (H=1)
[CAL] CHTR: loaded taus [0.8  0.74 0.7  0.52 0.42]
[CAL] CHTR: temperature scaling 1.007
Retraining model for ticker: CMCSA
[TRAIN] CMCSA: preparing data (H=1) with 782 rows
[TRAIN] CMCSA: built 770 sequences (seq_len=12)
[TRAIN] CMCSA: scaler fitted on 616 training sequences
[TRAIN] CMCSA: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CMCSA: model n_features = 33
[CAL] CMCSA: taus=[0.8  0.62 0.52 0.5  0.42] | temperature=1.143
[SAVE] CMCSA: stored taus
[SAVE] CMCSA: stored temperature scale 1.143
[SAVE] CMCSA: artifacts persisted (H=1)
[CAL] CMCSA: loaded taus [0.8  0.62 0.52 0.5  0.42]
[CAL] CMCSA: temperature scaling 1.143
Retraining model for ticker: CODI
[TRAIN] CODI: preparing data (H=1) with 782 rows
[TRAIN] CODI: built 770 sequences (seq_len=12)
[TRAIN] CODI: scaler fitted on 616 training sequences
[TRAIN] CODI: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CODI: model n_features = 33
[CAL] CODI: taus=[0.8  0.68 0.52 0.52 0.42] | temperature=1.279
[SAVE] CODI: stored taus
[SAVE] CODI: stored temperature scale 1.279
[SAVE] CODI: artifacts persisted (H=1)
[CAL] CODI: loaded taus [0.8  0.68 0.52 0.52 0.42]
[CAL] CODI: temperature scaling 1.279
Retraining model for ticker: CSCO
[TRAIN] CSCO: preparing data (H=1) with 782 rows
[TRAIN] CSCO: built 770 sequences (seq_len=12)
[TRAIN] CSCO: scaler fitted on 616 training sequences
[TRAIN] CSCO: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CSCO: model n_features = 33
[CAL] CSCO: taus=[0.78 0.54 0.62 0.32 0.2 ] | temperature=0.871
[SAVE] CSCO: stored taus
[SAVE] CSCO: stored temperature scale 0.871
[SAVE] CSCO: artifacts persisted (H=1)
[CAL] CSCO: loaded taus [0.78 0.54 0.62 0.32 0.2 ]
[CAL] CSCO: temperature scaling 0.871
Retraining model for ticker: CVX
[TRAIN] CVX: preparing data (H=1) with 782 rows
[TRAIN] CVX: built 770 sequences (seq_len=12)
[TRAIN] CVX: scaler fitted on 616 training sequences
[TRAIN] CVX: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] CVX: model n_features = 33
[CAL] CVX: taus=[0.62 0.48 0.48 0.4  0.38] | temperature=1.007
[SAVE] CVX: stored taus
[SAVE] CVX: stored temperature scale 1.007
[SAVE] CVX: artifacts persisted (H=1)
[CAL] CVX: loaded taus [0.62 0.48 0.48 0.4  0.38]
[CAL] CVX: temperature scaling 1.007
Retraining model for ticker: D
[TRAIN] D: preparing data (H=1) with 782 rows
[TRAIN] D: built 770 sequences (seq_len=12)
[TRAIN] D: scaler fitted on 616 training sequences
[TRAIN] D: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] D: model n_features = 33
[CAL] D: taus=[0.62 0.54 0.52 0.44 0.42] | temperature=2.364
[SAVE] D: stored taus
[SAVE] D: stored temperature scale 2.364
[SAVE] D: artifacts persisted (H=1)
[CAL] D: loaded taus [0.62 0.54 0.52 0.44 0.42]
[CAL] D: temperature scaling 2.364
Retraining model for ticker: DHR
[TRAIN] DHR: preparing data (H=1) with 782 rows
[TRAIN] DHR: built 770 sequences (seq_len=12)
[TRAIN] DHR: scaler fitted on 616 training sequences
[TRAIN] DHR: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] DHR: model n_features = 33
[CAL] DHR: taus=[0.2  0.76 0.5  0.4  0.26] | temperature=0.736
[SAVE] DHR: stored taus
[SAVE] DHR: stored temperature scale 0.736
[SAVE] DHR: artifacts persisted (H=1)
[CAL] DHR: loaded taus [0.2  0.76 0.5  0.4  0.26]
[CAL] DHR: temperature scaling 0.736
Retraining model for ticker: DIS
[TRAIN] DIS: preparing data (H=1) with 782 rows
[TRAIN] DIS: built 770 sequences (seq_len=12)
[TRAIN] DIS: scaler fitted on 616 training sequences
[TRAIN] DIS: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] DIS: model n_features = 33
[CAL] DIS: taus=[0.2  0.58 0.58 0.5  0.4 ] | temperature=0.600
[SAVE] DIS: stored taus
[SAVE] DIS: stored temperature scale 0.600
[SAVE] DIS: artifacts persisted (H=1)
[CAL] DIS: loaded taus [0.2  0.58 0.58 0.5  0.4 ]
[CAL] DIS: temperature scaling 0.600
Retraining model for ticker: DUK
[TRAIN] DUK: preparing data (H=1) with 782 rows
[TRAIN] DUK: built 770 sequences (seq_len=12)
[TRAIN] DUK: scaler fitted on 616 training sequences
[TRAIN] DUK: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] DUK: model n_features = 33
[CAL] DUK: taus=[0.72 0.78 0.78 0.28 0.68] | temperature=0.736
[SAVE] DUK: stored taus
[SAVE] DUK: stored temperature scale 0.736
[SAVE] DUK: artifacts persisted (H=1)
[CAL] DUK: loaded taus [0.72 0.78 0.78 0.28 0.68]
[CAL] DUK: temperature scaling 0.736
Retraining model for ticker: EXC
[TRAIN] EXC: preparing data (H=1) with 782 rows
[TRAIN] EXC: built 770 sequences (seq_len=12)
[TRAIN] EXC: scaler fitted on 616 training sequences
[TRAIN] EXC: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] EXC: model n_features = 33
[CAL] EXC: taus=[0.7  0.5  0.44 0.36 0.36] | temperature=1.007
[SAVE] EXC: stored taus
[SAVE] EXC: stored temperature scale 1.007
[SAVE] EXC: artifacts persisted (H=1)
[CAL] EXC: loaded taus [0.7  0.5  0.44 0.36 0.36]
[CAL] EXC: temperature scaling 1.007
Retraining model for ticker: FB
[TRAIN] FB: preparing data (H=1) with 782 rows
[TRAIN] FB: built 770 sequences (seq_len=12)
[TRAIN] FB: scaler fitted on 616 training sequences
[TRAIN] FB: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] FB: model n_features = 33
[CAL] FB: taus=[0.78 0.58 0.46 0.38 0.3 ] | temperature=1.550
[SAVE] FB: stored taus
[SAVE] FB: stored temperature scale 1.550
[SAVE] FB: artifacts persisted (H=1)
[CAL] FB: loaded taus [0.78 0.58 0.46 0.38 0.3 ]
[CAL] FB: temperature scaling 1.550
Retraining model for ticker: GD
[TRAIN] GD: preparing data (H=1) with 782 rows
[TRAIN] GD: built 770 sequences (seq_len=12)
[TRAIN] GD: scaler fitted on 616 training sequences
[TRAIN] GD: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] GD: model n_features = 33
[CAL] GD: taus=[0.7  0.2  0.5  0.44 0.34] | temperature=1.686
[SAVE] GD: stored taus
[SAVE] GD: stored temperature scale 1.686
[SAVE] GD: artifacts persisted (H=1)
[CAL] GD: loaded taus [0.7  0.2  0.5  0.44 0.34]
[CAL] GD: temperature scaling 1.686
Retraining model for ticker: GE
[TRAIN] GE: preparing data (H=1) with 782 rows
[TRAIN] GE: built 770 sequences (seq_len=12)
[TRAIN] GE: scaler fitted on 616 training sequences
[TRAIN] GE: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] GE: model n_features = 33
[CAL] GE: taus=[0.2  0.52 0.4  0.28 0.36] | temperature=0.871
[SAVE] GE: stored taus
[SAVE] GE: stored temperature scale 0.871
[SAVE] GE: artifacts persisted (H=1)
[CAL] GE: loaded taus [0.2  0.52 0.4  0.28 0.36]
[CAL] GE: temperature scaling 0.871
Retraining model for ticker: GOOG
[TRAIN] GOOG: preparing data (H=1) with 782 rows
[TRAIN] GOOG: built 770 sequences (seq_len=12)
[TRAIN] GOOG: scaler fitted on 616 training sequences
[TRAIN] GOOG: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] GOOG: model n_features = 33
[CAL] GOOG: taus=[0.6  0.46 0.36 0.32 0.24] | temperature=0.736
[SAVE] GOOG: stored taus
[SAVE] GOOG: stored temperature scale 0.736
[SAVE] GOOG: artifacts persisted (H=1)
[CAL] GOOG: loaded taus [0.6  0.46 0.36 0.32 0.24]
[CAL] GOOG: temperature scaling 0.736
Retraining model for ticker: HD
[TRAIN] HD: preparing data (H=1) with 782 rows
[TRAIN] HD: built 770 sequences (seq_len=12)
[TRAIN] HD: scaler fitted on 616 training sequences
[TRAIN] HD: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] HD: model n_features = 33
[CAL] HD: taus=[0.8  0.64 0.2  0.34 0.36] | temperature=1.007
[SAVE] HD: stored taus
[SAVE] HD: stored temperature scale 1.007
[SAVE] HD: artifacts persisted (H=1)
[CAL] HD: loaded taus [0.8  0.64 0.2  0.34 0.36]
[CAL] HD: temperature scaling 1.007
Retraining model for ticker: HON
[TRAIN] HON: preparing data (H=1) with 782 rows
[TRAIN] HON: built 770 sequences (seq_len=12)
[TRAIN] HON: scaler fitted on 616 training sequences
[TRAIN] HON: scaler.n_features_in_ = 33, len(feature_cols) = 33
[TRAIN] HON: model n_features = 33
[CAL] HON: taus=[0.76 0.62 0.2  0.56 0.38] | temperature=1.414
[SAVE] HON: stored taus
[SAVE] HON: stored temperature scale 1.414
[SAVE] HON: artifacts persisted (H=1)
[CAL] HON: loaded taus [0.76 0.62 0.2  0.56 0.38]
[CAL] HON: temperature scaling 1.414
Retraining model for ticker: HRG
[TRAIN] HRG: preparing data (H=1) with 782 rows
[TRAIN] HRG: built 770 sequences (seq_len=12)

Simulating Trading Days:   1%|          | 1/100 [13:17<21:56:30, 797.88s/it]

[CAL] XOM: taus=[0.2  0.6  0.5  0.42 0.34] | temperature=0.871
[SAVE] XOM: stored taus
[SAVE] XOM: stored temperature scale 0.871
[SAVE] XOM: artifacts persisted (H=1)
[CAL] XOM: loaded taus [0.2  0.6  0.5  0.42 0.34]
[CAL] XOM: temperature scaling 0.871
[SIM] 2017-04-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.624, kelly=0.267) with $2670.16 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.803, kelly=0.603) with $6025.85 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.849, kelly=0.702) with $7020.76 allocation
[PORT] Sector Financial: selecting C (p_up=0.756, kelly=0.518) with $5182.94 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.719, kelly=0.439) with $4394.94 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.816, kelly=0.629) with $6293.81 allocation
[PORT] Sector Services: selecting WMT (p_up=0.669, kelly=0.334) with $3344.88 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.677, kelly=0.353) with $3531.68 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.636, kelly=0.234) with $2343.85 allocation
[SIM] 2017-04-11 00:00:00: 9 trades proposed.
[TRADE] 2017-04-11 00:00:00: allocated $7020.76 to UN exiting on 2017-04-12 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $6293.81 to BA exiting on 2017-04-12 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $6025.85 to IEP exiting on 2017-04-12 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $5182.94 to C exiting on 2017-04-12 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $4394.94 to NVS exiting on 2017-04-12 00:00:00
[TRADE] 2017-04-11 00:00:00: allocated $1081.70 to VZ exiting on 2017-04-12 00:00:00
[EXIT] 2017-04-12 00:00:00: UN r=0.0094, PnL=$66.21
[EXIT] 2017-04-12 00:00:00: BA r=-0.0141, PnL=$-88.82
[EXIT] 2017-04-12 00:00:00: IEP r=-0.0008, PnL=$-4.95
[EXIT] 2017-04-12 00:00:00: C r=-0.0088, PnL=$-45.66
[EXIT] 2017-04-12 00:00:00: NVS r=0.0007, PnL=$2.97
[EXIT] 2017-04-12 00:00:00: VZ r=0.0045, PnL=$4.89

Simulating Trading Days:   2%|▏         | 2/100 [13:19<8:58:13, 329.52s/it]

[SIM] 2017-04-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.643, kelly=0.304) with $3037.60 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.820, kelly=0.638) with $6371.07 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.841, kelly=0.685) with $6848.18 allocation
[PORT] Sector Financial: selecting V (p_up=0.791, kelly=0.586) with $5860.82 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.740, kelly=0.480) with $4799.60 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.810, kelly=0.617) with $6169.58 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.674, kelly=0.393) with $3926.46 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.691, kelly=0.382) with $3816.72 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.626, kelly=0.212) with $2122.87 allocation
[SIM] 2017-04-12 00:00:00: 9 trades proposed.
[TRADE] 2017-04-12 00:00:00: allocated $6848.18 to UN exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $6371.07 to IEP exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $6169.58 to BA exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $5860.82 to V exiting on 2017-04-13 00:00:00
[TRADE] 2017-04-12 00:00:00: allocated $4730.75 to NVS exiting on 2017-04-13 00:00:00
[EXIT] 2017-04-13 00:00:00: UN r=-0.0072, PnL=$-49.32
[EXIT] 2017-04-13 00:00:00: IEP r=-0.0144, PnL=$-91.58
[EXIT] 2017-04-13 00:00:00: BA r=-0.0024, PnL=$-15.07
[EXIT] 2017-04-13 00:00:00: V r=0.0021, PnL=$12.56
[EXIT] 2017-04-13 00:00:00: NVS r=-0.0116, PnL=$-54.97

Simulating Trading Days:   3%|▎         | 3/100 [13:20<4:50:19, 179.59s/it]

[SIM] 2017-04-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.652, kelly=0.322) with $3207.11 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.840, kelly=0.678) with $6766.25 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.825, kelly=0.654) with $6523.90 allocation
[PORT] Sector Financial: selecting V (p_up=0.858, kelly=0.720) with $7178.28 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.754, kelly=0.507) with $5059.43 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.803, kelly=0.603) with $6009.55 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.691, kelly=0.424) with $4232.28 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.702, kelly=0.403) with $4021.98 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.634, kelly=0.229) with $2286.48 allocation
[SIM] 2017-04-13 00:00:00: 9 trades proposed.
[TRADE] 2017-04-13 00:00:00: allocated $7178.28 to V exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $6766.25 to IEP exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $6523.90 to UN exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $6009.55 to BA exiting on 2017-04-17 00:00:00
[TRADE] 2017-04-13 00:00:00: allocated $3442.90 to NVS exiting on 2017-04-17 00:00:00
[EXIT] 2017-04-17 00:00:00: V r=0.0106, PnL=$75.93
[EXIT] 2017-04-17 00:00:00: IEP r=0.0023, PnL=$15.51
[EXIT] 2017-04-17 00:00:00: UN r=0.0047, PnL=$30.69
[EXIT] 2017-04-17 00:00:00: BA r=0.0194, PnL=$116.35
[EXIT] 2017-04-17 00:00:00: NVS r=0.0025, PnL=$8.47

Simulating Trading Days:   4%|▍         | 4/100 [13:21<2:54:41, 109.18s/it]

[SIM] 2017-04-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.661, kelly=0.341) with $3407.94 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.855, kelly=0.708) with $7078.48 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.804, kelly=0.611) with $6109.88 allocation
[PORT] Sector Financial: selecting V (p_up=0.888, kelly=0.779) with $7787.37 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.761, kelly=0.521) with $5205.89 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.805, kelly=0.606) with $6063.76 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.700, kelly=0.441) with $4407.36 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.697, kelly=0.393) with $3930.27 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.632, kelly=0.226) with $2256.34 allocation
[SIM] 2017-04-17 00:00:00: 9 trades proposed.
[TRADE] 2017-04-17 00:00:00: allocated $7787.37 to V exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $7078.48 to IEP exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $6063.76 to BA exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $6109.88 to UN exiting on 2017-04-18 00:00:00
[TRADE] 2017-04-17 00:00:00: allocated $2955.46 to NVS exiting on 2017-04-18 00:00:00
[EXIT] 2017-04-18 00:00:00: V r=-0.0009, PnL=$-6.94
[EXIT] 2017-04-18 00:00:00: IEP r=0.0021, PnL=$14.71
[EXIT] 2017-04-18 00:00:00: BA r=-0.0065, PnL=$-39.63
[EXIT] 2017-04-18 00:00:00: UN r=0.0012, PnL=$7.15
[EXIT] 2017-04-18 00:00:00: NVS r=-0.0055, PnL=$-16.12

Simulating Trading Days:   5%|▌         | 5/100 [13:23<1:51:12, 70.24s/it]

[SIM] 2017-04-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.668, kelly=0.355) with $3543.62 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.867, kelly=0.731) with $7310.61 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.785, kelly=0.575) with $5743.07 allocation
[PORT] Sector Financial: selecting V (p_up=0.917, kelly=0.836) with $8355.66 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.772, kelly=0.544) with $5436.08 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.809, kelly=0.615) with $6150.76 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.714, kelly=0.467) with $4664.37 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.684, kelly=0.368) with $3674.65 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.622, kelly=0.206) with $2054.13 allocation
[SIM] 2017-04-18 00:00:00: 9 trades proposed.
[TRADE] 2017-04-18 00:00:00: allocated $8355.66 to V exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $7310.61 to IEP exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $6150.76 to BA exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $5743.07 to UN exiting on 2017-04-19 00:00:00
[TRADE] 2017-04-18 00:00:00: allocated $2422.61 to NVS exiting on 2017-04-19 00:00:00
[EXIT] 2017-04-19 00:00:00: V r=0.0002, PnL=$1.86
[EXIT] 2017-04-19 00:00:00: IEP r=-0.0097, PnL=$-71.27
[EXIT] 2017-04-19 00:00:00: BA r=0.0031, PnL=$19.02
[EXIT] 2017-04-19 00:00:00: UN r=-0.0062, PnL=$-35.82
[EXIT] 2017-04-19 00:00:00: NVS r=-0.0026, PnL=$-6.31

Simulating Trading Days:   6%|▌         | 6/100 [13:24<1:13:25, 46.87s/it]

[SIM] 2017-04-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.674, kelly=0.365) with $3639.77 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.874, kelly=0.747) with $7454.73 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.764, kelly=0.532) with $5310.61 allocation
[PORT] Sector Financial: selecting C (p_up=0.884, kelly=0.771) with $7696.60 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.783, kelly=0.566) with $5652.23 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.809, kelly=0.614) with $6134.23 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.728, kelly=0.493) with $4923.59 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.655, kelly=0.309) with $3089.97 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.593, kelly=0.144) with $1436.46 allocation
[SIM] 2017-04-19 00:00:00: 9 trades proposed.
[TRADE] 2017-04-19 00:00:00: allocated $7696.60 to C exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $7454.73 to IEP exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $6134.23 to BA exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $5652.23 to NVS exiting on 2017-04-20 00:00:00
[TRADE] 2017-04-19 00:00:00: allocated $3017.17 to UN exiting on 2017-04-20 00:00:00
[EXIT] 2017-04-20 00:00:00: C r=0.0118, PnL=$90.66
[EXIT] 2017-04-20 00:00:00: IEP r=0.0308, PnL=$229.54
[EXIT] 2017-04-20 00:00:00: BA r=0.0050, PnL=$30.95
[EXIT] 2017-04-20 00:00:00: NVS r=0.0121, PnL=$68.38
[EXIT] 2017-04-20 00:00:00: UN r=0.0029, PnL=$8.88

Simulating Trading Days:   7%|▋         | 7/100 [13:25<49:30, 31.94s/it]

[SIM] 2017-04-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.681, kelly=0.380) with $3805.85 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.883, kelly=0.764) with $7660.68 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.751, kelly=0.506) with $5075.61 allocation
[PORT] Sector Financial: selecting C (p_up=0.884, kelly=0.772) with $7740.18 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.803, kelly=0.606) with $6079.39 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.805, kelly=0.607) with $6090.39 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.748, kelly=0.530) with $5312.08 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.669, kelly=0.333) with $3340.10 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.562, kelly=0.078) with $787.07 allocation
[SIM] 2017-04-20 00:00:00: 9 trades proposed.
[TRADE] 2017-04-20 00:00:00: allocated $7740.18 to C exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $7660.68 to IEP exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $6090.39 to BA exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $6079.39 to NVS exiting on 2017-04-21 00:00:00
[TRADE] 2017-04-20 00:00:00: allocated $2512.84 to UN exiting on 2017-04-21 00:00:00
[EXIT] 2017-04-21 00:00:00: C r=-0.0118, PnL=$-91.43
[EXIT] 2017-04-21 00:00:00: IEP r=-0.0043, PnL=$-32.69
[EXIT] 2017-04-21 00:00:00: BA r=0.0060, PnL=$36.69
[EXIT] 2017-04-21 00:00:00: NVS r=-0.0030, PnL=$-18.17
[EXIT] 2017-04-21 00:00:00: UN r=-0.0027, PnL=$-6.88

Simulating Trading Days:   8%|▊         | 8/100 [13:26<33:56, 22.13s/it]

[SIM] 2017-04-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 56 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.729, kelly=0.460) with $4609.00 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.892, kelly=0.782) with $7831.14 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.754, kelly=0.511) with $5119.01 allocation
[PORT] Sector Financial: selecting C (p_up=0.867, kelly=0.739) with $7402.88 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.816, kelly=0.632) with $6333.80 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.799, kelly=0.595) with $5959.58 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.755, kelly=0.542) with $5433.13 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.746, kelly=0.488) with $4888.20 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.551, kelly=0.071) with $711.32 allocation
[SIM] 2017-04-21 00:00:00: 9 trades proposed.
[TRADE] 2017-04-21 00:00:00: allocated $7831.14 to IEP exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $7402.88 to C exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $6333.80 to NVS exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $5959.58 to BA exiting on 2017-04-24 00:00:00
[TRADE] 2017-04-21 00:00:00: allocated $2522.34 to CHTR exiting on 2017-04-24 00:00:00
[EXIT] 2017-04-24 00:00:00: IEP r=0.0122, PnL=$95.89
[EXIT] 2017-04-24 00:00:00: C r=0.0298, PnL=$220.60
[EXIT] 2017-04-24 00:00:00: NVS r=0.0165, PnL=$104.41
[EXIT] 2017-04-24 00:00:00: BA r=0.0093, PnL=$55.51
[EXIT] 2017-04-24 00:00:00: CHTR r=0.0056, PnL=$14.01

Simulating Trading Days:   9%|▉         | 9/100 [13:28<23:37, 15.58s/it]

[SIM] 2017-04-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.701, kelly=0.417) with $4201.54 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.895, kelly=0.789) with $7937.14 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.771, kelly=0.546) with $5498.31 allocation
[PORT] Sector Financial: selecting C (p_up=0.811, kelly=0.628) with $6324.20 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.812, kelly=0.625) with $6293.62 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.790, kelly=0.577) with $5805.01 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.752, kelly=0.537) with $5409.34 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.792, kelly=0.580) with $5837.94 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.573, kelly=0.119) with $1196.68 allocation
[SIM] 2017-04-24 00:00:00: 9 trades proposed.
[TRADE] 2017-04-24 00:00:00: allocated $7937.14 to IEP exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $6293.62 to NVS exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $6324.20 to C exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $5837.94 to INTC exiting on 2017-04-25 00:00:00
[TRADE] 2017-04-24 00:00:00: allocated $3803.96 to BA exiting on 2017-04-25 00:00:00
[EXIT] 2017-04-25 00:00:00: IEP r=0.0054, PnL=$43.21
[EXIT] 2017-04-25 00:00:00: NVS r=0.0218, PnL=$137.50
[EXIT] 2017-04-25 00:00:00: C r=0.0130, PnL=$81.93
[EXIT] 2017-04-25 00:00:00: INTC r=0.0033, PnL=$19.06
[EXIT] 2017-04-25 00:00:00: BA r=0.0080, PnL=$30.30

Simulating Trading Days:  10%|█         | 10/100 [13:29<16:43, 11.15s/it]

[SIM] 2017-04-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.708, kelly=0.431) with $4355.02 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.887, kelly=0.773) with $7809.37 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.788, kelly=0.580) with $5854.54 allocation
[PORT] Sector Financial: selecting C (p_up=0.790, kelly=0.588) with $5932.41 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.804, kelly=0.610) with $6154.53 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.838, kelly=0.684) with $6908.09 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.740, kelly=0.514) with $5186.32 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.835, kelly=0.668) with $6743.45 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.592, kelly=0.158) with $1593.48 allocation
[SIM] 2017-04-25 00:00:00: 9 trades proposed.
[TRADE] 2017-04-25 00:00:00: allocated $7809.37 to IEP exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $6908.09 to CAT exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $6743.45 to INTC exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $6154.53 to NVS exiting on 2017-04-26 00:00:00
[TRADE] 2017-04-25 00:00:00: allocated $2675.02 to C exiting on 2017-04-26 00:00:00
[EXIT] 2017-04-26 00:00:00: IEP r=0.0199, PnL=$155.03
[EXIT] 2017-04-26 00:00:00: CAT r=0.0023, PnL=$15.88
[EXIT] 2017-04-26 00:00:00: INTC r=0.0016, PnL=$10.97
[EXIT] 2017-04-26 00:00:00: NVS r=0.0014, PnL=$8.88
[EXIT] 2017-04-26 00:00:00: C r=-0.0018, PnL=$-4.89

Simulating Trading Days:  11%|█         | 11/100 [13:30<12:03,  8.13s/it]

[SIM] 2017-04-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.714, kelly=0.441) with $4465.18 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.866, kelly=0.729) with $7378.43 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.796, kelly=0.596) with $6031.14 allocation
[PORT] Sector Financial: selecting C (p_up=0.768, kelly=0.544) with $5502.31 allocation
[PORT] Sector Healthcare: selecting NVS (p_up=0.768, kelly=0.537) with $5436.69 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.832, kelly=0.675) with $6824.32 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.724, kelly=0.485) with $4905.77 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.829, kelly=0.654) with $6613.40 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.601, kelly=0.177) with $1791.80 allocation
[SIM] 2017-04-26 00:00:00: 9 trades proposed.
[TRADE] 2017-04-26 00:00:00: allocated $7378.43 to IEP exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $6824.32 to CAT exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $6613.40 to INTC exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $6031.14 to UN exiting on 2017-04-27 00:00:00
[TRADE] 2017-04-26 00:00:00: allocated $3498.93 to C exiting on 2017-04-27 00:00:00
[EXIT] 2017-04-27 00:00:00: IEP r=0.0324, PnL=$239.37
[EXIT] 2017-04-27 00:00:00: CAT r=-0.0189, PnL=$-129.11
[EXIT] 2017-04-27 00:00:00: INTC r=0.0135, PnL=$89.54
[EXIT] 2017-04-27 00:00:00: UN r=0.0012, PnL=$6.96
[EXIT] 2017-04-27 00:00:00: C r=-0.0118, PnL=$-41.34

Simulating Trading Days:  12%|█▏        | 12/100 [13:31<08:49,  6.02s/it]

[SIM] 2017-04-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.710, kelly=0.436) with $4413.24 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.837, kelly=0.673) with $6815.98 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.793, kelly=0.590) with $5980.99 allocation
[PORT] Sector Financial: selecting C (p_up=0.761, kelly=0.531) with $5377.59 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.716, kelly=0.431) with $4371.82 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.862, kelly=0.732) with $7412.13 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.705, kelly=0.448) with $4541.81 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.772, kelly=0.538) with $5453.94 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.607, kelly=0.190) with $1923.61 allocation
[SIM] 2017-04-27 00:00:00: 9 trades proposed.
[TRADE] 2017-04-27 00:00:00: allocated $7412.13 to CAT exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $6815.98 to IEP exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $5980.99 to UN exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $5453.94 to INTC exiting on 2017-04-28 00:00:00
[TRADE] 2017-04-27 00:00:00: allocated $4732.80 to C exiting on 2017-04-28 00:00:00
[EXIT] 2017-04-28 00:00:00: CAT r=-0.0041, PnL=$-30.32
[EXIT] 2017-04-28 00:00:00: IEP r=0.0065, PnL=$44.13
[EXIT] 2017-04-28 00:00:00: UN r=0.0038, PnL=$22.99
[EXIT] 2017-04-28 00:00:00: INTC r=-0.0342, PnL=$-186.51
[EXIT] 2017-04-28 00:00:00: C r=-0.0045, PnL=$-21.52

Simulating Trading Days:  13%|█▎        | 13/100 [13:33<06:40,  4.61s/it]

[SIM] 2017-04-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 45 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.702, kelly=0.419) with $4233.30 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.808, kelly=0.615) with $6216.94 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.792, kelly=0.588) with $5950.54 allocation
[PORT] Sector Financial: selecting C (p_up=0.760, kelly=0.530) with $5356.87 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.693, kelly=0.385) with $3898.50 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.806, kelly=0.624) with $6313.32 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.683, kelly=0.408) with $4122.85 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.779, kelly=0.557) with $5629.98 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.608, kelly=0.192) with $1941.86 allocation
[SIM] 2017-04-28 00:00:00: 9 trades proposed.
[TRADE] 2017-04-28 00:00:00: allocated $6216.94 to IEP exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $6313.32 to CAT exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $5950.54 to UN exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $5629.98 to VZ exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $5356.87 to C exiting on 2017-05-01 00:00:00
[TRADE] 2017-04-28 00:00:00: allocated $876.83 to PTR exiting on 2017-05-01 00:00:00
[EXIT] 2017-05-01 00:00:00: IEP r=0.0066, PnL=$41.17
[EXIT] 2017-05-01 00:00:00: CAT r=-0.0025, PnL=$-16.05
[EXIT] 2017-05-01 00:00:00: UN r=-0.0006, PnL=$-3.42
[EXIT] 2017-05-01 00:00:00: VZ r=-0.0007, PnL=$-3.68
[EXIT] 2017-05-01 00:00:00: C r=0.0058, PnL=$30.81
[EXIT] 2017-05-01 00:00:00: PTR r=-0.0011, PnL=$-1.00

Simulating Trading Days:  14%|█▍        | 14/100 [13:34<05:10,  3.61s/it]

[SIM] 2017-05-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 46 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.694, kelly=0.405) with $4093.99 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.784, kelly=0.565) with $5713.56 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.791, kelly=0.586) with $5930.61 allocation
[PORT] Sector Financial: selecting C (p_up=0.797, kelly=0.602) with $6094.90 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.644, kelly=0.294) with $2974.07 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.749, kelly=0.493) with $4992.68 allocation
[PORT] Sector Services: selecting DIS (p_up=0.789, kelly=0.577) with $5840.84 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.797, kelly=0.591) with $5981.95 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.605, kelly=0.186) with $1884.81 allocation
[SIM] 2017-05-01 00:00:00: 9 trades proposed.
[TRADE] 2017-05-01 00:00:00: allocated $6094.90 to C exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $5981.95 to VZ exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $5930.61 to UN exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $5840.84 to DIS exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $5713.56 to IEP exiting on 2017-05-02 00:00:00
[TRADE] 2017-05-01 00:00:00: allocated $796.98 to BA exiting on 2017-05-02 00:00:00
[EXIT] 2017-05-02 00:00:00: C r=0.0042, PnL=$25.63
[EXIT] 2017-05-02 00:00:00: VZ r=0.0007, PnL=$3.91
[EXIT] 2017-05-02 00:00:00: UN r=0.0109, PnL=$64.75
[EXIT] 2017-05-02 00:00:00: DIS r=-0.0031, PnL=$-18.33
[EXIT] 2017-05-02 00:00:00: IEP r=0.0017, PnL=$9.67
[EXIT] 2017-05-02 00:00:00: BA r=0.0058, PnL=$4.59

Simulating Trading Days:  15%|█▌        | 15/100 [13:35<04:04,  2.88s/it]

[SIM] 2017-05-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 45 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.685, kelly=0.388) with $3933.52 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.758, kelly=0.514) with $5204.02 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.791, kelly=0.587) with $5943.96 allocation
[PORT] Sector Financial: selecting C (p_up=0.814, kelly=0.635) with $6433.78 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.641, kelly=0.283) with $2862.90 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.748, kelly=0.492) with $4979.59 allocation
[PORT] Sector Services: selecting DIS (p_up=0.809, kelly=0.617) with $6252.05 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.826, kelly=0.651) with $6591.40 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.606, kelly=0.190) with $1919.63 allocation
[SIM] 2017-05-02 00:00:00: 9 trades proposed.
[TRADE] 2017-05-02 00:00:00: allocated $6591.40 to VZ exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $6433.78 to C exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $6252.05 to DIS exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $5943.96 to UN exiting on 2017-05-03 00:00:00
[TRADE] 2017-05-02 00:00:00: allocated $5164.70 to IEP exiting on 2017-05-03 00:00:00
[EXIT] 2017-05-03 00:00:00: VZ r=0.0052, PnL=$34.46
[EXIT] 2017-05-03 00:00:00: C r=0.0089, PnL=$57.11
[EXIT] 2017-05-03 00:00:00: DIS r=-0.0240, PnL=$-150.33
[EXIT] 2017-05-03 00:00:00: UN r=-0.0072, PnL=$-42.79
[EXIT] 2017-05-03 00:00:00: IEP r=-0.0236, PnL=$-122.12

Simulating Trading Days:  16%|█▌        | 16/100 [13:36<03:21,  2.40s/it]

[SIM] 2017-05-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 46 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.677, kelly=0.373) with $3769.36 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.734, kelly=0.464) with $4686.30 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.794, kelly=0.593) with $5989.15 allocation
[PORT] Sector Financial: selecting C (p_up=0.828, kelly=0.662) with $6689.16 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.685, kelly=0.371) with $3751.40 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.756, kelly=0.506) with $5112.32 allocation
[PORT] Sector Services: selecting DIS (p_up=0.818, kelly=0.637) with $6436.09 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.836, kelly=0.671) with $6779.88 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.608, kelly=0.193) with $1949.85 allocation
[SIM] 2017-05-03 00:00:00: 9 trades proposed.
[TRADE] 2017-05-03 00:00:00: allocated $6779.88 to VZ exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $6689.16 to C exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $6436.09 to DIS exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $5989.15 to UN exiting on 2017-05-04 00:00:00
[TRADE] 2017-05-03 00:00:00: allocated $4424.51 to BA exiting on 2017-05-04 00:00:00
[EXIT] 2017-05-04 00:00:00: VZ r=-0.0059, PnL=$-39.67
[EXIT] 2017-05-04 00:00:00: C r=-0.0005, PnL=$-3.33
[EXIT] 2017-05-04 00:00:00: DIS r=-0.0040, PnL=$-25.95
[EXIT] 2017-05-04 00:00:00: UN r=0.0095, PnL=$57.15
[EXIT] 2017-05-04 00:00:00: BA r=-0.0017, PnL=$-7.72

Simulating Trading Days:  17%|█▋        | 17/100 [13:38<02:48,  2.03s/it]

[SIM] 2017-05-04 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 46 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.676, kelly=0.370) with $3740.77 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.721, kelly=0.437) with $4416.99 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.862, kelly=0.723) with $7302.13 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.765, kelly=0.540) with $5455.69 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.725, kelly=0.451) with $4554.64 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.761, kelly=0.518) with $5232.50 allocation
[PORT] Sector Services: selecting DIS (p_up=0.813, kelly=0.624) with $6307.52 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.847, kelly=0.691) with $6982.66 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.608, kelly=0.192) with $1937.98 allocation
[SIM] 2017-05-04 00:00:00: 9 trades proposed.
[TRADE] 2017-05-04 00:00:00: allocated $7302.13 to TM exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $6982.66 to VZ exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $6307.52 to DIS exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $5455.69 to JPM exiting on 2017-05-05 00:00:00
[TRADE] 2017-05-04 00:00:00: allocated $4264.94 to BA exiting on 2017-05-05 00:00:00
[EXIT] 2017-05-05 00:00:00: TM r=0.0069, PnL=$50.17
[EXIT] 2017-05-05 00:00:00: VZ r=0.0177, PnL=$123.28
[EXIT] 2017-05-05 00:00:00: DIS r=0.0074, PnL=$46.52
[EXIT] 2017-05-05 00:00:00: JPM r=-0.0011, PnL=$-6.26
[EXIT] 2017-05-05 00:00:00: BA r=0.0106, PnL=$45.20

Simulating Trading Days:  18%|█▊        | 18/100 [13:39<02:33,  1.87s/it]

[SIM] 2017-05-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.679, kelly=0.376) with $3808.71 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.712, kelly=0.418) with $4230.83 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.882, kelly=0.763) with $7725.64 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.772, kelly=0.553) with $5603.07 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.763, kelly=0.527) with $5338.69 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.768, kelly=0.533) with $5397.20 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.715, kelly=0.466) with $4716.49 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.862, kelly=0.721) with $7307.86 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.610, kelly=0.196) with $1987.42 allocation
[SIM] 2017-05-05 00:00:00: 9 trades proposed.
[TRADE] 2017-05-05 00:00:00: allocated $7725.64 to TM exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $7307.86 to VZ exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $5603.07 to JPM exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $5397.20 to BA exiting on 2017-05-08 00:00:00
[TRADE] 2017-05-05 00:00:00: allocated $4356.84 to SNY exiting on 2017-05-08 00:00:00
[EXIT] 2017-05-08 00:00:00: TM r=0.0025, PnL=$19.68
[EXIT] 2017-05-08 00:00:00: VZ r=-0.0013, PnL=$-9.39
[EXIT] 2017-05-08 00:00:00: JPM r=0.0011, PnL=$6.44
[EXIT] 2017-05-08 00:00:00: BA r=0.0055, PnL=$29.46
[EXIT] 2017-05-08 00:00:00: SNY r=-0.0100, PnL=$-43.46

Simulating Trading Days:  19%|█▉        | 19/100 [13:40<02:15,  1.67s/it]

[SIM] 2017-05-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.687, kelly=0.391) with $3964.23 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.700, kelly=0.394) with $3990.56 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.890, kelly=0.778) with $7880.14 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.776, kelly=0.562) with $5695.25 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.780, kelly=0.560) with $5674.57 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.775, kelly=0.546) with $5534.98 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.755, kelly=0.542) with $5488.85 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.881, kelly=0.761) with $7709.65 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.609, kelly=0.193) with $1957.16 allocation
[SIM] 2017-05-08 00:00:00: 9 trades proposed.
[TRADE] 2017-05-08 00:00:00: allocated $7880.14 to TM exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $7709.65 to VZ exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $5674.57 to SNY exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $5695.25 to JPM exiting on 2017-05-09 00:00:00
[TRADE] 2017-05-08 00:00:00: allocated $3431.81 to BA exiting on 2017-05-09 00:00:00
[EXIT] 2017-05-09 00:00:00: TM r=-0.0157, PnL=$-123.72
[EXIT] 2017-05-09 00:00:00: VZ r=-0.0045, PnL=$-34.72
[EXIT] 2017-05-09 00:00:00: SNY r=0.0099, PnL=$56.01
[EXIT] 2017-05-09 00:00:00: JPM r=-0.0040, PnL=$-22.89
[EXIT] 2017-05-09 00:00:00: BA r=0.0048, PnL=$16.42

Simulating Trading Days:  20%|██        | 20/100 [13:42<02:03,  1.54s/it]

[SIM] 2017-05-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.696, kelly=0.409) with $4139.03 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.695, kelly=0.383) with $3880.79 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.894, kelly=0.787) with $7965.79 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.775, kelly=0.560) with $5662.43 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.793, kelly=0.587) with $5941.96 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.777, kelly=0.549) with $5557.95 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.776, kelly=0.580) with $5871.76 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.886, kelly=0.770) with $7795.85 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.604, kelly=0.183) with $1848.37 allocation
[SIM] 2017-05-09 00:00:00: 9 trades proposed.
[TRADE] 2017-05-09 00:00:00: allocated $7965.79 to TM exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $7795.85 to VZ exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $5941.96 to SNY exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $5557.95 to BA exiting on 2017-05-10 00:00:00
[TRADE] 2017-05-09 00:00:00: allocated $3097.21 to CHTR exiting on 2017-05-10 00:00:00
[EXIT] 2017-05-10 00:00:00: TM r=-0.0244, PnL=$-194.63
[EXIT] 2017-05-10 00:00:00: VZ r=-0.0009, PnL=$-6.72
[EXIT] 2017-05-10 00:00:00: SNY r=0.0114, PnL=$67.76
[EXIT] 2017-05-10 00:00:00: BA r=-0.0200, PnL=$-110.92
[EXIT] 2017-05-10 00:00:00: CHTR r=0.0002, PnL=$0.57

Simulating Trading Days:  21%|██        | 21/100 [13:43<01:54,  1.45s/it]

[SIM] 2017-05-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.701, kelly=0.419) with $4232.14 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.693, kelly=0.379) with $3822.39 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.897, kelly=0.793) with $8009.52 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.784, kelly=0.577) with $5829.27 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.805, kelly=0.611) with $6164.74 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.777, kelly=0.550) with $5555.73 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.796, kelly=0.618) with $6239.06 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.882, kelly=0.764) with $7707.98 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.599, kelly=0.173) with $1744.63 allocation
[SIM] 2017-05-10 00:00:00: 9 trades proposed.
[TRADE] 2017-05-10 00:00:00: allocated $8009.52 to TM exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $7707.98 to VZ exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $6164.74 to SNY exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $6239.06 to CHTR exiting on 2017-05-11 00:00:00
[TRADE] 2017-05-10 00:00:00: allocated $2164.29 to JPM exiting on 2017-05-11 00:00:00
[EXIT] 2017-05-11 00:00:00: TM r=0.0097, PnL=$77.97
[EXIT] 2017-05-11 00:00:00: VZ r=-0.0078, PnL=$-59.83
[EXIT] 2017-05-11 00:00:00: SNY r=-0.0268, PnL=$-165.07
[EXIT] 2017-05-11 00:00:00: CHTR r=-0.0030, PnL=$-18.59
[EXIT] 2017-05-11 00:00:00: JPM r=-0.0031, PnL=$-6.68

Simulating Trading Days:  22%|██▏       | 22/100 [13:44<01:46,  1.37s/it]

[SIM] 2017-05-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 46 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.702, kelly=0.420) with $4229.22 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.716, kelly=0.424) with $4273.33 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.903, kelly=0.805) with $8110.25 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.783, kelly=0.575) with $5798.57 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.808, kelly=0.618) with $6224.38 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.774, kelly=0.543) with $5470.27 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.807, kelly=0.638) with $6431.47 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.879, kelly=0.757) with $7632.02 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.601, kelly=0.176) with $1777.80 allocation
[SIM] 2017-05-11 00:00:00: 9 trades proposed.
[TRADE] 2017-05-11 00:00:00: allocated $8110.25 to TM exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $7632.02 to VZ exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $6224.38 to SNY exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $6431.47 to CHTR exiting on 2017-05-12 00:00:00
[TRADE] 2017-05-11 00:00:00: allocated $1835.80 to JPM exiting on 2017-05-12 00:00:00
[EXIT] 2017-05-12 00:00:00: TM r=-0.0036, PnL=$-28.85
[EXIT] 2017-05-12 00:00:00: VZ r=-0.0039, PnL=$-29.85
[EXIT] 2017-05-12 00:00:00: SNY r=0.0180, PnL=$112.02
[EXIT] 2017-05-12 00:00:00: CHTR r=-0.0080, PnL=$-51.71
[EXIT] 2017-05-12 00:00:00: JPM r=-0.0028, PnL=$-5.06

Simulating Trading Days:  23%|██▎       | 23/100 [13:45<01:39,  1.30s/it]

[SIM] 2017-05-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.696, kelly=0.408) with $4107.88 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.735, kelly=0.461) with $4647.92 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.928, kelly=0.854) with $8608.17 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.774, kelly=0.558) with $5623.55 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.805, kelly=0.611) with $6153.24 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.779, kelly=0.553) with $5575.91 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.819, kelly=0.661) with $6657.75 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.874, kelly=0.747) with $7530.34 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.597, kelly=0.168) with $1690.15 allocation
[SIM] 2017-05-12 00:00:00: 9 trades proposed.
[TRADE] 2017-05-12 00:00:00: allocated $8608.17 to TM exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $7530.34 to VZ exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $6657.75 to CHTR exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $6153.24 to SNY exiting on 2017-05-15 00:00:00
[TRADE] 2017-05-12 00:00:00: allocated $1283.38 to BA exiting on 2017-05-15 00:00:00
[EXIT] 2017-05-15 00:00:00: TM r=-0.0005, PnL=$-4.04
[EXIT] 2017-05-15 00:00:00: VZ r=-0.0100, PnL=$-75.57
[EXIT] 2017-05-15 00:00:00: CHTR r=-0.0029, PnL=$-19.23
[EXIT] 2017-05-15 00:00:00: SNY r=0.0041, PnL=$25.01
[EXIT] 2017-05-15 00:00:00: BA r=-0.0047, PnL=$-6.02

Simulating Trading Days:  24%|██▍       | 24/100 [13:46<01:35,  1.26s/it]

[SIM] 2017-05-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.684, kelly=0.385) with $3873.68 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.758, kelly=0.508) with $5119.18 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.956, kelly=0.912) with $9183.22 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.769, kelly=0.548) with $5521.03 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.792, kelly=0.583) with $5874.31 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.788, kelly=0.572) with $5764.10 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.825, kelly=0.672) with $6763.17 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.871, kelly=0.742) with $7466.67 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.596, kelly=0.166) with $1671.42 allocation
[SIM] 2017-05-15 00:00:00: 9 trades proposed.
[TRADE] 2017-05-15 00:00:00: allocated $9183.22 to TM exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $7466.67 to VZ exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $6763.17 to CHTR exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $5874.31 to SNY exiting on 2017-05-16 00:00:00
[TRADE] 2017-05-15 00:00:00: allocated $921.56 to BA exiting on 2017-05-16 00:00:00
[EXIT] 2017-05-16 00:00:00: TM r=0.0048, PnL=$44.01
[EXIT] 2017-05-16 00:00:00: VZ r=-0.0015, PnL=$-11.52
[EXIT] 2017-05-16 00:00:00: CHTR r=-0.0033, PnL=$-22.33
[EXIT] 2017-05-16 00:00:00: SNY r=0.0162, PnL=$95.11
[EXIT] 2017-05-16 00:00:00: BA r=0.0017, PnL=$1.57

Simulating Trading Days:  25%|██▌       | 25/100 [13:48<01:36,  1.28s/it]

[SIM] 2017-05-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.667, kelly=0.352) with $3546.30 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.781, kelly=0.555) with $5594.97 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.971, kelly=0.941) with $9485.87 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.756, kelly=0.523) with $5271.71 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.758, kelly=0.517) with $5209.07 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.805, kelly=0.605) with $6101.64 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.830, kelly=0.682) with $6874.44 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.871, kelly=0.741) with $7471.18 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.589, kelly=0.154) with $1548.51 allocation
[SIM] 2017-05-16 00:00:00: 9 trades proposed.
[TRADE] 2017-05-16 00:00:00: allocated $9485.87 to TM exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $7471.18 to VZ exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $6874.44 to CHTR exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $6101.64 to BA exiting on 2017-05-17 00:00:00
[TRADE] 2017-05-16 00:00:00: allocated $307.85 to IEP exiting on 2017-05-17 00:00:00
[EXIT] 2017-05-17 00:00:00: TM r=-0.0106, PnL=$-100.25
[EXIT] 2017-05-17 00:00:00: VZ r=-0.0183, PnL=$-136.86
[EXIT] 2017-05-17 00:00:00: CHTR r=-0.0216, PnL=$-148.23
[EXIT] 2017-05-17 00:00:00: BA r=-0.0215, PnL=$-130.92
[EXIT] 2017-05-17 00:00:00: IEP r=-0.0356, PnL=$-10.96

Simulating Trading Days:  26%|██▌       | 26/100 [13:49<01:32,  1.26s/it]

[SIM] 2017-05-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.647, kelly=0.312) with $3132.80 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.800, kelly=0.594) with $5960.36 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.973, kelly=0.946) with $9485.95 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.735, kelly=0.482) with $4830.54 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.711, kelly=0.423) with $4239.77 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.817, kelly=0.631) with $6325.95 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.836, kelly=0.693) with $6948.70 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.887, kelly=0.774) with $7761.31 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.579, kelly=0.133) with $1335.94 allocation
[SIM] 2017-05-17 00:00:00: 9 trades proposed.
[TRADE] 2017-05-17 00:00:00: allocated $9485.95 to TM exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $7761.31 to VZ exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $6948.70 to CHTR exiting on 2017-05-18 00:00:00
[TRADE] 2017-05-17 00:00:00: allocated $5886.86 to BA exiting on 2017-05-18 00:00:00
[EXIT] 2017-05-18 00:00:00: TM r=0.0093, PnL=$87.87
[EXIT] 2017-05-18 00:00:00: VZ r=0.0126, PnL=$97.71
[EXIT] 2017-05-18 00:00:00: CHTR r=0.0088, PnL=$61.47
[EXIT] 2017-05-18 00:00:00: BA r=-0.0077, PnL=$-45.44

Simulating Trading Days:  27%|██▋       | 27/100 [13:50<01:31,  1.25s/it]

[SIM] 2017-05-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 46 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.625, kelly=0.271) with $2720.27 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.806, kelly=0.606) with $6093.17 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.969, kelly=0.937) with $9409.82 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.716, kelly=0.441) with $4427.63 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.671, kelly=0.341) with $3428.91 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.827, kelly=0.650) with $6532.63 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.845, kelly=0.709) with $7121.13 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.901, kelly=0.802) with $8061.83 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.568, kelly=0.111) with $1115.13 allocation
[SIM] 2017-05-18 00:00:00: 9 trades proposed.
[TRADE] 2017-05-18 00:00:00: allocated $9409.82 to TM exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $8061.83 to VZ exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $7121.13 to CHTR exiting on 2017-05-19 00:00:00
[TRADE] 2017-05-18 00:00:00: allocated $5550.53 to BA exiting on 2017-05-19 00:00:00
[EXIT] 2017-05-19 00:00:00: TM r=0.0074, PnL=$69.62
[EXIT] 2017-05-19 00:00:00: VZ r=0.0084, PnL=$68.02
[EXIT] 2017-05-19 00:00:00: CHTR r=-0.0003, PnL=$-2.25
[EXIT] 2017-05-19 00:00:00: BA r=0.0189, PnL=$105.13

Simulating Trading Days:  28%|██▊       | 28/100 [13:51<01:27,  1.22s/it]

[SIM] 2017-05-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 55 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.654, kelly=0.312) with $3141.18 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.808, kelly=0.611) with $6149.81 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.960, kelly=0.920) with $9265.92 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.733, kelly=0.476) with $4792.14 allocation
[PORT] Sector Healthcare: selecting CELG (p_up=0.635, kelly=0.277) with $2785.22 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.840, kelly=0.676) with $6805.71 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.859, kelly=0.736) with $7411.77 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.938, kelly=0.876) with $8823.53 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.553, kelly=0.079) with $800.18 allocation
[SIM] 2017-05-19 00:00:00: 9 trades proposed.
[TRADE] 2017-05-19 00:00:00: allocated $9265.92 to TM exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $8823.53 to VZ exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $7411.77 to CHTR exiting on 2017-05-22 00:00:00
[TRADE] 2017-05-19 00:00:00: allocated $4714.24 to BA exiting on 2017-05-22 00:00:00
[EXIT] 2017-05-22 00:00:00: TM r=-0.0006, PnL=$-5.17
[EXIT] 2017-05-22 00:00:00: VZ r=0.0013, PnL=$11.66
[EXIT] 2017-05-22 00:00:00: CHTR r=0.0020, PnL=$15.02
[EXIT] 2017-05-22 00:00:00: BA r=0.0161, PnL=$75.89

Simulating Trading Days:  29%|██▉       | 29/100 [13:52<01:23,  1.18s/it]

[SIM] 2017-05-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 54 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.666, kelly=0.336) with $3386.58 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.810, kelly=0.613) with $6180.30 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.938, kelly=0.876) with $8826.81 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.733, kelly=0.476) with $4800.35 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.672, kelly=0.333) with $3360.82 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.848, kelly=0.693) with $6982.96 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.867, kelly=0.751) with $7566.73 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.953, kelly=0.906) with $9132.86 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.588, kelly=0.152) with $1530.85 allocation
[SIM] 2017-05-22 00:00:00: 9 trades proposed.
[TRADE] 2017-05-22 00:00:00: allocated $9132.86 to VZ exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $8826.81 to TM exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $7566.73 to CHTR exiting on 2017-05-23 00:00:00
[TRADE] 2017-05-22 00:00:00: allocated $4718.28 to BA exiting on 2017-05-23 00:00:00
[EXIT] 2017-05-23 00:00:00: VZ r=0.0000, PnL=$0.00
[EXIT] 2017-05-23 00:00:00: TM r=0.0054, PnL=$47.62
[EXIT] 2017-05-23 00:00:00: CHTR r=0.0075, PnL=$56.68
[EXIT] 2017-05-23 00:00:00: BA r=-0.0010, PnL=$-4.62

Simulating Trading Days:  30%|███       | 30/100 [13:54<01:24,  1.21s/it]

[SIM] 2017-05-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.676, kelly=0.355) with $3578.05 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.810, kelly=0.615) with $6201.97 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.899, kelly=0.797) with $8044.58 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.713, kelly=0.436) with $4400.54 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.701, kelly=0.392) with $3954.45 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.847, kelly=0.691) with $6973.17 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.868, kelly=0.753) with $7596.61 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.951, kelly=0.902) with $9099.18 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.593, kelly=0.161) with $1629.66 allocation
[SIM] 2017-05-23 00:00:00: 9 trades proposed.
[TRADE] 2017-05-23 00:00:00: allocated $9099.18 to VZ exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $8044.58 to TM exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $7596.61 to CHTR exiting on 2017-05-24 00:00:00
[TRADE] 2017-05-23 00:00:00: allocated $5534.22 to BA exiting on 2017-05-24 00:00:00
[EXIT] 2017-05-24 00:00:00: VZ r=-0.0097, PnL=$-88.03
[EXIT] 2017-05-24 00:00:00: TM r=-0.0070, PnL=$-56.57
[EXIT] 2017-05-24 00:00:00: CHTR r=0.0322, PnL=$244.25
[EXIT] 2017-05-24 00:00:00: BA r=0.0096, PnL=$53.08

Simulating Trading Days:  31%|███       | 31/100 [13:55<01:23,  1.21s/it]

[SIM] 2017-05-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.625, kelly=0.253) with $2554.66 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.810, kelly=0.615) with $6213.68 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.849, kelly=0.696) with $7035.42 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.690, kelly=0.393) with $3968.84 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.766, kelly=0.523) with $5289.18 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.840, kelly=0.677) with $6839.63 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.862, kelly=0.741) with $7489.36 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.940, kelly=0.880) with $8893.11 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.620, kelly=0.217) with $2194.09 allocation
[SIM] 2017-05-24 00:00:00: 9 trades proposed.
[TRADE] 2017-05-24 00:00:00: allocated $8893.11 to VZ exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $7489.36 to CHTR exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $7035.42 to TM exiting on 2017-05-25 00:00:00
[TRADE] 2017-05-24 00:00:00: allocated $6839.63 to BA exiting on 2017-05-25 00:00:00
[EXIT] 2017-05-25 00:00:00: VZ r=0.0060, PnL=$53.31
[EXIT] 2017-05-25 00:00:00: CHTR r=0.0143, PnL=$107.43
[EXIT] 2017-05-25 00:00:00: TM r=-0.0002, PnL=$-1.31
[EXIT] 2017-05-25 00:00:00: BA r=0.0098, PnL=$67.20

Simulating Trading Days:  32%|███▏      | 32/100 [13:56<01:21,  1.20s/it]

[SIM] 2017-05-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 46 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.570, kelly=0.161) with $1626.40 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.805, kelly=0.602) with $6102.66 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.710, kelly=0.429) with $4349.09 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.678, kelly=0.370) with $3746.37 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.789, kelly=0.570) with $5774.40 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.831, kelly=0.659) with $6672.61 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.850, kelly=0.719) with $7281.81 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.931, kelly=0.861) with $8719.78 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.601, kelly=0.177) with $1797.91 allocation
[SIM] 2017-05-25 00:00:00: 9 trades proposed.
[TRADE] 2017-05-25 00:00:00: allocated $8719.78 to VZ exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $7281.81 to CHTR exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $6672.61 to BA exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $6102.66 to IEP exiting on 2017-05-26 00:00:00
[TRADE] 2017-05-25 00:00:00: allocated $1611.54 to AMGN exiting on 2017-05-26 00:00:00
[EXIT] 2017-05-26 00:00:00: VZ r=0.0002, PnL=$1.92
[EXIT] 2017-05-26 00:00:00: CHTR r=0.0110, PnL=$80.29
[EXIT] 2017-05-26 00:00:00: BA r=-0.0026, PnL=$-17.12
[EXIT] 2017-05-26 00:00:00: IEP r=0.0018, PnL=$11.28
[EXIT] 2017-05-26 00:00:00: AMGN r=-0.0027, PnL=$-4.35

Simulating Trading Days:  33%|███▎      | 33/100 [13:57<01:21,  1.22s/it]

[SIM] 2017-05-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 44 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.560, kelly=0.142) with $1434.37 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.803, kelly=0.600) with $6077.71 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.725, kelly=0.459) with $4651.77 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.670, kelly=0.354) with $3588.48 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.796, kelly=0.584) with $5924.83 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.819, kelly=0.634) with $6431.33 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.819, kelly=0.661) with $6695.54 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.934, kelly=0.868) with $8800.68 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.537, kelly=0.047) with $480.74 allocation
[SIM] 2017-05-26 00:00:00: 9 trades proposed.
[TRADE] 2017-05-26 00:00:00: allocated $8800.68 to VZ exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $6431.33 to BA exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $6695.54 to CHTR exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $6077.71 to IEP exiting on 2017-05-30 00:00:00
[TRADE] 2017-05-26 00:00:00: allocated $2404.73 to AMGN exiting on 2017-05-30 00:00:00
[EXIT] 2017-05-30 00:00:00: VZ r=0.0194, PnL=$170.89
[EXIT] 2017-05-30 00:00:00: BA r=0.0016, PnL=$10.00
[EXIT] 2017-05-30 00:00:00: CHTR r=0.0044, PnL=$29.37
[EXIT] 2017-05-30 00:00:00: IEP r=-0.0053, PnL=$-32.39
[EXIT] 2017-05-30 00:00:00: AMGN r=-0.0075, PnL=$-18.00

Simulating Trading Days:  34%|███▍      | 34/100 [13:58<01:19,  1.20s/it]

[SIM] 2017-05-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 41 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.559, kelly=0.140) with $1417.03 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.800, kelly=0.594) with $6029.14 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.737, kelly=0.482) with $4897.64 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.662, kelly=0.338) with $3434.56 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.791, kelly=0.575) with $5836.65 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.804, kelly=0.605) with $6137.72 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.775, kelly=0.579) with $5877.34 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.937, kelly=0.874) with $8875.05 allocation
[PORT] Sector Utilities: selecting EXC (p_up=0.522, kelly=0.018) with $187.35 allocation
[SIM] 2017-05-30 00:00:00: 9 trades proposed.
[TRADE] 2017-05-30 00:00:00: allocated $8875.05 to VZ exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $6137.72 to BA exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $6029.14 to IEP exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $5836.65 to AMGN exiting on 2017-05-31 00:00:00
[TRADE] 2017-05-30 00:00:00: allocated $3579.39 to CHTR exiting on 2017-05-31 00:00:00
[EXIT] 2017-05-31 00:00:00: VZ r=0.0095, PnL=$84.52
[EXIT] 2017-05-31 00:00:00: BA r=0.0040, PnL=$24.63
[EXIT] 2017-05-31 00:00:00: IEP r=-0.0171, PnL=$-103.12
[EXIT] 2017-05-31 00:00:00: AMGN r=0.0090, PnL=$52.73
[EXIT] 2017-05-31 00:00:00: CHTR r=0.0196, PnL=$70.02

Simulating Trading Days:  35%|███▌      | 35/100 [14:00<01:18,  1.20s/it]

[SIM] 2017-05-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 40 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.575, kelly=0.156) with $1587.23 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.800, kelly=0.593) with $6027.66 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.748, kelly=0.504) with $5125.42 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.700, kelly=0.405) with $4118.46 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.784, kelly=0.559) with $5685.34 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.792, kelly=0.580) with $5899.52 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.723, kelly=0.481) with $4892.66 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.940, kelly=0.879) with $8936.08 allocation
[PORT] Sector Utilities: Kelly <= 0 for EXC (p_up=0.508, b=0.948).
[SIM] 2017-05-31 00:00:00: 8 trades proposed.
[TRADE] 2017-05-31 00:00:00: allocated $8936.08 to VZ exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $6027.66 to IEP exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $5899.52 to BA exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $5685.34 to AMGN exiting on 2017-06-01 00:00:00
[TRADE] 2017-05-31 00:00:00: allocated $3948.00 to PM exiting on 2017-06-01 00:00:00
[EXIT] 2017-06-01 00:00:00: VZ r=-0.0028, PnL=$-24.91
[EXIT] 2017-06-01 00:00:00: IEP r=0.0166, PnL=$99.83
[EXIT] 2017-06-01 00:00:00: BA r=-0.0017, PnL=$-9.75
[EXIT] 2017-06-01 00:00:00: AMGN r=0.0064, PnL=$36.62
[EXIT] 2017-06-01 00:00:00: PM r=0.0092, PnL=$36.25

Simulating Trading Days:  36%|███▌      | 36/100 [14:01<01:15,  1.19s/it]

[SIM] 2017-06-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 38 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.635, kelly=0.275) with $2802.36 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.798, kelly=0.589) with $5993.48 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.756, kelly=0.519) with $5286.93 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.728, kelly=0.461) with $4690.27 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.778, kelly=0.547) with $5571.96 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.780, kelly=0.556) with $5664.52 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.678, kelly=0.398) with $4048.41 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.945, kelly=0.890) with $9055.47 allocation
[SIM] 2017-06-01 00:00:00: 8 trades proposed.
[TRADE] 2017-06-01 00:00:00: allocated $9055.47 to VZ exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5993.48 to IEP exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5664.52 to BA exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $5571.96 to AMGN exiting on 2017-06-02 00:00:00
[TRADE] 2017-06-01 00:00:00: allocated $4252.58 to PM exiting on 2017-06-02 00:00:00
[EXIT] 2017-06-02 00:00:00: VZ r=-0.0015, PnL=$-13.63
[EXIT] 2017-06-02 00:00:00: IEP r=-0.0006, PnL=$-3.71
[EXIT] 2017-06-02 00:00:00: BA r=0.0155, PnL=$88.00
[EXIT] 2017-06-02 00:00:00: AMGN r=0.0186, PnL=$103.78
[EXIT] 2017-06-02 00:00:00: PM r=0.0074, PnL=$31.31

Simulating Trading Days:  37%|███▋      | 37/100 [14:02<01:15,  1.21s/it]

[SIM] 2017-06-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 39 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.699, kelly=0.401) with $4094.96 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.802, kelly=0.598) with $6099.37 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.760, kelly=0.527) with $5373.77 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.762, kelly=0.528) with $5383.41 allocation
[PORT] Sector Healthcare: selecting AMGN (p_up=0.776, kelly=0.545) with $5554.00 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.838, kelly=0.687) with $7002.63 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.638, kelly=0.321) with $3271.69 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.954, kelly=0.908) with $9265.83 allocation
[PORT] Sector Utilities: allocation $28.30 below minimum; skipping EXC.
[SIM] 2017-06-02 00:00:00: 8 trades proposed.
[TRADE] 2017-06-02 00:00:00: allocated $9265.83 to VZ exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $7002.63 to CAT exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $6099.37 to IEP exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $5554.00 to AMGN exiting on 2017-06-05 00:00:00
[TRADE] 2017-06-02 00:00:00: allocated $2677.91 to WFC exiting on 2017-06-05 00:00:00
[EXIT] 2017-06-05 00:00:00: VZ r=-0.0015, PnL=$-13.97
[EXIT] 2017-06-05 00:00:00: CAT r=-0.0071, PnL=$-49.57
[EXIT] 2017-06-05 00:00:00: IEP r=-0.0124, PnL=$-75.52
[EXIT] 2017-06-05 00:00:00: AMGN r=0.0067, PnL=$37.34
[EXIT] 2017-06-05 00:00:00: WFC r=-0.0017, PnL=$-4.65

Simulating Trading Days:  38%|███▊      | 38/100 [14:04<01:30,  1.47s/it]

[SIM] 2017-06-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 39 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.675, kelly=0.353) with $3593.64 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.807, kelly=0.608) with $6193.99 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.763, kelly=0.533) with $5434.35 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.737, kelly=0.479) with $4878.32 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.776, kelly=0.553) with $5631.59 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.865, kelly=0.738) with $7523.28 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.602, kelly=0.255) with $2600.00 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.954, kelly=0.909) with $9260.01 allocation
[PORT] Sector Utilities: Kelly <= 0 for EXC (p_up=0.508, b=0.949).
[SIM] 2017-06-05 00:00:00: 8 trades proposed.
[TRADE] 2017-06-05 00:00:00: allocated $9260.01 to VZ exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $7523.28 to CAT exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $6193.99 to IEP exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $5631.59 to SNY exiting on 2017-06-06 00:00:00
[TRADE] 2017-06-05 00:00:00: allocated $1958.95 to PM exiting on 2017-06-06 00:00:00
[EXIT] 2017-06-06 00:00:00: VZ r=0.0015, PnL=$13.98
[EXIT] 2017-06-06 00:00:00: CAT r=-0.0062, PnL=$-46.48
[EXIT] 2017-06-06 00:00:00: IEP r=-0.0002, PnL=$-1.29
[EXIT] 2017-06-06 00:00:00: SNY r=-0.0152, PnL=$-85.67
[EXIT] 2017-06-06 00:00:00: PM r=0.0002, PnL=$0.48

Simulating Trading Days:  39%|███▉      | 39/100 [14:05<01:25,  1.40s/it]

[SIM] 2017-06-06 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 41 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.700, kelly=0.403) with $4102.84 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.808, kelly=0.610) with $6207.81 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.765, kelly=0.538) with $5473.10 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.720, kelly=0.445) with $4528.44 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.761, kelly=0.524) with $5333.61 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.879, kelly=0.766) with $7799.97 allocation
[PORT] Sector Services: selecting BABA (p_up=0.595, kelly=0.255) with $2591.58 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.955, kelly=0.909) with $9255.99 allocation
[PORT] Sector Utilities: Kelly <= 0 for EXC (p_up=0.502, b=0.947).
[SIM] 2017-06-06 00:00:00: 8 trades proposed.
[TRADE] 2017-06-06 00:00:00: allocated $9255.99 to VZ exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $7799.97 to CAT exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $6207.81 to IEP exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $5473.10 to PM exiting on 2017-06-07 00:00:00
[TRADE] 2017-06-06 00:00:00: allocated $1795.26 to SNY exiting on 2017-06-07 00:00:00
[EXIT] 2017-06-07 00:00:00: VZ r=0.0013, PnL=$11.96
[EXIT] 2017-06-07 00:00:00: CAT r=-0.0099, PnL=$-77.59
[EXIT] 2017-06-07 00:00:00: IEP r=-0.0008, PnL=$-5.19
[EXIT] 2017-06-07 00:00:00: PM r=0.0025, PnL=$13.46
[EXIT] 2017-06-07 00:00:00: SNY r=-0.0175, PnL=$-31.38

Simulating Trading Days:  40%|████      | 40/100 [14:07<01:19,  1.33s/it]

[SIM] 2017-06-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 40 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.706, kelly=0.427) with $4344.93 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.803, kelly=0.600) with $6104.62 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.768, kelly=0.543) with $5523.92 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.691, kelly=0.387) with $3932.53 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.738, kelly=0.477) with $4852.18 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.900, kelly=0.806) with $8200.40 allocation
[PORT] Sector Services: selecting BABA (p_up=0.592, kelly=0.250) with $2538.50 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.950, kelly=0.900) with $9148.50 allocation
[SIM] 2017-06-07 00:00:00: 8 trades proposed.
[TRADE] 2017-06-07 00:00:00: allocated $9148.50 to VZ exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $8200.40 to CAT exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $6104.62 to IEP exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $5523.92 to PM exiting on 2017-06-08 00:00:00
[TRADE] 2017-06-07 00:00:00: allocated $1528.07 to SNY exiting on 2017-06-08 00:00:00
[EXIT] 2017-06-08 00:00:00: VZ r=-0.0067, PnL=$-60.99
[EXIT] 2017-06-08 00:00:00: CAT r=0.0145, PnL=$118.83
[EXIT] 2017-06-08 00:00:00: IEP r=0.0023, PnL=$14.04
[EXIT] 2017-06-08 00:00:00: PM r=-0.0097, PnL=$-53.75
[EXIT] 2017-06-08 00:00:00: SNY r=-0.0050, PnL=$-7.59

Simulating Trading Days:  41%|████      | 41/100 [14:08<01:16,  1.30s/it]

[SIM] 2017-06-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 40 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.725, kelly=0.464) with $4715.07 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.794, kelly=0.583) with $5925.85 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.772, kelly=0.551) with $5599.92 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.692, kelly=0.390) with $3963.80 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.724, kelly=0.450) with $4576.42 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.916, kelly=0.838) with $8526.34 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.588, kelly=0.228) with $2314.12 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.949, kelly=0.897) with $9122.54 allocation
[SIM] 2017-06-08 00:00:00: 8 trades proposed.
[TRADE] 2017-06-08 00:00:00: allocated $9122.54 to VZ exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $8526.34 to CAT exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $5925.85 to IEP exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $5599.92 to PM exiting on 2017-06-09 00:00:00
[TRADE] 2017-06-08 00:00:00: allocated $1334.03 to PTR exiting on 2017-06-09 00:00:00
[EXIT] 2017-06-09 00:00:00: VZ r=0.0115, PnL=$104.68
[EXIT] 2017-06-09 00:00:00: CAT r=0.0087, PnL=$73.89
[EXIT] 2017-06-09 00:00:00: IEP r=0.0196, PnL=$116.24
[EXIT] 2017-06-09 00:00:00: PM r=-0.0082, PnL=$-45.78
[EXIT] 2017-06-09 00:00:00: PTR r=-0.0023, PnL=$-3.07

Simulating Trading Days:  42%|████▏     | 42/100 [14:09<01:20,  1.38s/it]

[SIM] 2017-06-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 39 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.741, kelly=0.496) with $5060.63 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.784, kelly=0.562) with $5733.48 allocation
[PORT] Sector Consumer Goods: selecting PM (p_up=0.774, kelly=0.554) with $5647.12 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.695, kelly=0.396) with $4031.85 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.730, kelly=0.462) with $4713.30 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.924, kelly=0.853) with $8692.62 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.600, kelly=0.248) with $2533.01 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.943, kelly=0.886) with $9036.57 allocation
[SIM] 2017-06-09 00:00:00: 8 trades proposed.
[TRADE] 2017-06-09 00:00:00: allocated $9036.57 to VZ exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $8692.62 to CAT exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $5733.48 to IEP exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $5647.12 to PM exiting on 2017-06-12 00:00:00
[TRADE] 2017-06-09 00:00:00: allocated $1472.66 to PTR exiting on 2017-06-12 00:00:00
[EXIT] 2017-06-12 00:00:00: VZ r=0.0101, PnL=$90.91
[EXIT] 2017-06-12 00:00:00: CAT r=0.0014, PnL=$12.31
[EXIT] 2017-06-12 00:00:00: IEP r=0.0020, PnL=$11.73
[EXIT] 2017-06-12 00:00:00: PM r=-0.0079, PnL=$-44.66
[EXIT] 2017-06-12 00:00:00: PTR r=-0.0105, PnL=$-15.42

Simulating Trading Days:  43%|████▎     | 43/100 [14:11<01:23,  1.47s/it]

[SIM] 2017-06-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 42 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.754, kelly=0.522) with $5328.66 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.779, kelly=0.552) with $5631.37 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.895, kelly=0.789) with $8051.74 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.698, kelly=0.401) with $4091.26 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.754, kelly=0.509) with $5189.67 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.914, kelly=0.833) with $8499.29 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.632, kelly=0.308) with $3146.15 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.943, kelly=0.885) with $9029.40 allocation
[SIM] 2017-06-12 00:00:00: 8 trades proposed.
[TRADE] 2017-06-12 00:00:00: allocated $9029.40 to VZ exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $8499.29 to CAT exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $8051.74 to TM exiting on 2017-06-13 00:00:00
[TRADE] 2017-06-12 00:00:00: allocated $5018.49 to IEP exiting on 2017-06-13 00:00:00
[EXIT] 2017-06-13 00:00:00: VZ r=-0.0155, PnL=$-139.68
[EXIT] 2017-06-13 00:00:00: CAT r=-0.0030, PnL=$-25.64
[EXIT] 2017-06-13 00:00:00: TM r=0.0090, PnL=$72.61
[EXIT] 2017-06-13 00:00:00: IEP r=0.0092, PnL=$46.13

Simulating Trading Days:  44%|████▍     | 44/100 [14:13<01:30,  1.62s/it]

[SIM] 2017-06-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 43 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.766, kelly=0.545) with $5556.94 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.769, kelly=0.531) with $5415.69 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.930, kelly=0.860) with $8766.90 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.679, kelly=0.364) with $3705.96 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.779, kelly=0.559) with $5700.04 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.894, kelly=0.794) with $8099.82 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.664, kelly=0.368) with $3753.91 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.934, kelly=0.865) with $8815.24 allocation
[SIM] 2017-06-13 00:00:00: 8 trades proposed.
[TRADE] 2017-06-13 00:00:00: allocated $8815.24 to INTC exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $8766.90 to TM exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $8099.82 to CAT exiting on 2017-06-14 00:00:00
[TRADE] 2017-06-13 00:00:00: allocated $4902.98 to SNY exiting on 2017-06-14 00:00:00
[EXIT] 2017-06-14 00:00:00: INTC r=-0.0098, PnL=$-85.99
[EXIT] 2017-06-14 00:00:00: TM r=-0.0066, PnL=$-57.95
[EXIT] 2017-06-14 00:00:00: CAT r=-0.0098, PnL=$-79.66
[EXIT] 2017-06-14 00:00:00: SNY r=0.0013, PnL=$6.18

Simulating Trading Days:  45%|████▌     | 45/100 [14:14<01:22,  1.50s/it]

[SIM] 2017-06-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 46 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.775, kelly=0.563) with $5723.56 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.751, kelly=0.495) with $5035.60 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.946, kelly=0.892) with $9075.40 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.679, kelly=0.363) with $3695.95 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.807, kelly=0.615) with $6253.10 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.892, kelly=0.791) with $8047.23 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.692, kelly=0.421) with $4281.34 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.963, kelly=0.924) with $9396.19 allocation
[PORT] Sector Utilities: Kelly <= 0 for NEE (p_up=0.512, b=0.895).
[SIM] 2017-06-14 00:00:00: 8 trades proposed.
[TRADE] 2017-06-14 00:00:00: allocated $9396.19 to INTC exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $9075.40 to TM exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $8047.23 to CAT exiting on 2017-06-15 00:00:00
[TRADE] 2017-06-14 00:00:00: allocated $4000.90 to SNY exiting on 2017-06-15 00:00:00
[EXIT] 2017-06-15 00:00:00: INTC r=-0.0062, PnL=$-58.18
[EXIT] 2017-06-15 00:00:00: TM r=-0.0086, PnL=$-78.25
[EXIT] 2017-06-15 00:00:00: CAT r=0.0161, PnL=$129.88
[EXIT] 2017-06-15 00:00:00: SNY r=0.0023, PnL=$9.23

Simulating Trading Days:  46%|████▌     | 46/100 [14:15<01:16,  1.42s/it]

[SIM] 2017-06-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 45 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.778, kelly=0.568) with $5776.45 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.724, kelly=0.440) with $4473.42 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.940, kelly=0.879) with $8940.77 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.687, kelly=0.378) with $3848.47 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.829, kelly=0.659) with $6701.74 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.884, kelly=0.775) with $7885.97 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.705, kelly=0.446) with $4540.32 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.972, kelly=0.944) with $9600.72 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.549, kelly=0.045) with $462.54 allocation
[SIM] 2017-06-15 00:00:00: 9 trades proposed.
[TRADE] 2017-06-15 00:00:00: allocated $9600.72 to INTC exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $8940.77 to TM exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $7885.97 to CAT exiting on 2017-06-16 00:00:00
[TRADE] 2017-06-15 00:00:00: allocated $4093.05 to SNY exiting on 2017-06-16 00:00:00
[EXIT] 2017-06-16 00:00:00: INTC r=-0.0028, PnL=$-27.19
[EXIT] 2017-06-16 00:00:00: TM r=-0.0083, PnL=$-74.38
[EXIT] 2017-06-16 00:00:00: CAT r=0.0113, PnL=$88.94
[EXIT] 2017-06-16 00:00:00: SNY r=-0.0008, PnL=$-3.43

Simulating Trading Days:  47%|████▋     | 47/100 [14:17<01:10,  1.34s/it]

[SIM] 2017-06-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.776, kelly=0.565) with $5751.98 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.691, kelly=0.371) with $3769.00 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.909, kelly=0.816) with $8304.81 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.701, kelly=0.406) with $4130.24 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.848, kelly=0.696) with $7081.10 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.882, kelly=0.772) with $7855.78 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.716, kelly=0.465) with $4730.06 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.978, kelly=0.956) with $9720.30 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.569, kelly=0.087) with $888.70 allocation
[SIM] 2017-06-16 00:00:00: 9 trades proposed.
[TRADE] 2017-06-16 00:00:00: allocated $9720.30 to INTC exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $8304.81 to TM exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $7855.78 to CAT exiting on 2017-06-19 00:00:00
[TRADE] 2017-06-16 00:00:00: allocated $4634.82 to SNY exiting on 2017-06-19 00:00:00
[EXIT] 2017-06-19 00:00:00: INTC r=0.0085, PnL=$82.82
[EXIT] 2017-06-19 00:00:00: TM r=-0.0019, PnL=$-15.83
[EXIT] 2017-06-19 00:00:00: CAT r=-0.0010, PnL=$-8.03
[EXIT] 2017-06-19 00:00:00: SNY r=0.0176, PnL=$81.57

Simulating Trading Days:  48%|████▊     | 48/100 [14:18<01:14,  1.43s/it]

[SIM] 2017-06-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.774, kelly=0.560) with $5699.49 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.658, kelly=0.305) with $3107.76 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.881, kelly=0.761) with $7748.50 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.721, kelly=0.448) with $4558.53 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.861, kelly=0.722) with $7358.88 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.867, kelly=0.744) with $7574.56 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.728, kelly=0.488) with $4966.67 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.983, kelly=0.965) with $9833.14 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.561, kelly=0.071) with $723.02 allocation
[SIM] 2017-06-19 00:00:00: 9 trades proposed.
[TRADE] 2017-06-19 00:00:00: allocated $9833.14 to INTC exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $7748.50 to TM exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $7574.56 to CAT exiting on 2017-06-20 00:00:00
[TRADE] 2017-06-19 00:00:00: allocated $5401.66 to SNY exiting on 2017-06-20 00:00:00
[EXIT] 2017-06-20 00:00:00: INTC r=-0.0183, PnL=$-179.99
[EXIT] 2017-06-20 00:00:00: TM r=-0.0084, PnL=$-65.13
[EXIT] 2017-06-20 00:00:00: CAT r=-0.0042, PnL=$-31.71
[EXIT] 2017-06-20 00:00:00: SNY r=-0.0054, PnL=$-28.92

Simulating Trading Days:  49%|████▉     | 49/100 [14:19<01:09,  1.37s/it]

[SIM] 2017-06-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.770, kelly=0.553) with $5616.60 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.640, kelly=0.270) with $2739.31 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.894, kelly=0.788) with $8001.51 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.728, kelly=0.460) with $4673.60 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.870, kelly=0.739) with $7507.50 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.849, kelly=0.709) with $7200.43 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.748, kelly=0.526) with $5337.01 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.986, kelly=0.972) with $9875.32 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.590, kelly=0.158) with $1601.24 allocation
[SIM] 2017-06-20 00:00:00: 9 trades proposed.
[TRADE] 2017-06-20 00:00:00: allocated $9875.32 to INTC exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $8001.51 to TM exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $7507.50 to SNY exiting on 2017-06-21 00:00:00
[TRADE] 2017-06-20 00:00:00: allocated $5081.81 to CAT exiting on 2017-06-21 00:00:00
[EXIT] 2017-06-21 00:00:00: INTC r=-0.0080, PnL=$-79.32
[EXIT] 2017-06-21 00:00:00: TM r=0.0071, PnL=$57.03
[EXIT] 2017-06-21 00:00:00: SNY r=0.0060, PnL=$45.07
[EXIT] 2017-06-21 00:00:00: CAT r=-0.0334, PnL=$-169.49

Simulating Trading Days:  50%|█████     | 50/100 [14:21<01:05,  1.32s/it]

[SIM] 2017-06-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.759, kelly=0.532) with $5396.20 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.663, kelly=0.307) with $3117.95 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.928, kelly=0.855) with $8671.91 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.716, kelly=0.437) with $4434.81 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.865, kelly=0.730) with $7402.91 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.835, kelly=0.682) with $6914.14 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.751, kelly=0.531) with $5388.01 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.982, kelly=0.963) with $9764.56 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.563, kelly=0.101) with $1020.72 allocation
[SIM] 2017-06-21 00:00:00: 9 trades proposed.
[TRADE] 2017-06-21 00:00:00: allocated $9764.56 to INTC exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $8671.91 to TM exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $7402.91 to SNY exiting on 2017-06-22 00:00:00
[TRADE] 2017-06-21 00:00:00: allocated $4582.75 to CAT exiting on 2017-06-22 00:00:00
[EXIT] 2017-06-22 00:00:00: INTC r=-0.0064, PnL=$-62.12
[EXIT] 2017-06-22 00:00:00: TM r=0.0089, PnL=$77.13
[EXIT] 2017-06-22 00:00:00: SNY r=0.0208, PnL=$153.85
[EXIT] 2017-06-22 00:00:00: CAT r=0.0036, PnL=$16.39

Simulating Trading Days:  51%|█████     | 51/100 [14:22<01:03,  1.29s/it]

[SIM] 2017-06-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.749, kelly=0.512) with $5203.02 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.656, kelly=0.293) with $2979.58 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.955, kelly=0.909) with $9236.27 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.715, kelly=0.435) with $4417.58 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.856, kelly=0.713) with $7242.71 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.844, kelly=0.698) with $7094.33 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.764, kelly=0.555) with $5638.29 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.976, kelly=0.952) with $9667.55 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.530, kelly=0.035) with $352.25 allocation
[SIM] 2017-06-22 00:00:00: 9 trades proposed.
[TRADE] 2017-06-22 00:00:00: allocated $9667.55 to INTC exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $9236.27 to TM exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $7242.71 to SNY exiting on 2017-06-23 00:00:00
[TRADE] 2017-06-22 00:00:00: allocated $4331.17 to CAT exiting on 2017-06-23 00:00:00
[EXIT] 2017-06-23 00:00:00: INTC r=-0.0049, PnL=$-47.83
[EXIT] 2017-06-23 00:00:00: TM r=-0.0024, PnL=$-21.89
[EXIT] 2017-06-23 00:00:00: SNY r=-0.0056, PnL=$-40.88
[EXIT] 2017-06-23 00:00:00: CAT r=0.0026, PnL=$11.26

Simulating Trading Days:  52%|█████▏    | 52/100 [14:23<01:00,  1.26s/it]

[SIM] 2017-06-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.773, kelly=0.550) with $5586.98 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.660, kelly=0.300) with $3048.49 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.963, kelly=0.926) with $9401.98 allocation
[PORT] Sector Financial: selecting JPM (p_up=0.711, kelly=0.435) with $4410.96 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.837, kelly=0.675) with $6850.70 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.889, kelly=0.785) with $7971.07 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.779, kelly=0.583) with $5913.36 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.972, kelly=0.943) with $9575.84 allocation
[SIM] 2017-06-23 00:00:00: 8 trades proposed.
[TRADE] 2017-06-23 00:00:00: allocated $9575.84 to INTC exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $9401.98 to TM exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $7971.07 to CAT exiting on 2017-06-26 00:00:00
[TRADE] 2017-06-23 00:00:00: allocated $3499.01 to SNY exiting on 2017-06-26 00:00:00
[EXIT] 2017-06-26 00:00:00: INTC r=-0.0035, PnL=$-33.61
[EXIT] 2017-06-26 00:00:00: TM r=-0.0025, PnL=$-23.23
[EXIT] 2017-06-26 00:00:00: CAT r=0.0013, PnL=$10.72
[EXIT] 2017-06-26 00:00:00: SNY r=0.0053, PnL=$18.44

Simulating Trading Days:  53%|█████▎    | 53/100 [14:24<00:57,  1.23s/it]

[SIM] 2017-06-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting XOM (p_up=0.756, kelly=0.517) with $5241.67 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.640, kelly=0.270) with $2734.76 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.954, kelly=0.907) with $9204.32 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.775, kelly=0.558) with $5659.95 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.814, kelly=0.628) with $6374.68 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.901, kelly=0.808) with $8197.77 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.790, kelly=0.604) with $6125.93 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.974, kelly=0.947) with $9612.05 allocation
[SIM] 2017-06-26 00:00:00: 8 trades proposed.
[TRADE] 2017-06-26 00:00:00: allocated $9612.05 to INTC exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $9204.32 to TM exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $8197.77 to CAT exiting on 2017-06-27 00:00:00
[TRADE] 2017-06-26 00:00:00: allocated $3425.46 to SNY exiting on 2017-06-27 00:00:00
[EXIT] 2017-06-27 00:00:00: INTC r=-0.0123, PnL=$-118.49
[EXIT] 2017-06-27 00:00:00: TM r=-0.0042, PnL=$-38.58
[EXIT] 2017-06-27 00:00:00: CAT r=-0.0031, PnL=$-25.16
[EXIT] 2017-06-27 00:00:00: SNY r=-0.0060, PnL=$-20.72

Simulating Trading Days:  54%|█████▍    | 54/100 [14:25<00:55,  1.22s/it]

[SIM] 2017-06-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.737, kelly=0.471) with $4766.03 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.650, kelly=0.291) with $2946.60 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.938, kelly=0.875) with $8860.14 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.796, kelly=0.600) with $6072.12 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.799, kelly=0.600) with $6070.99 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.893, kelly=0.792) with $8019.60 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.807, kelly=0.636) with $6438.36 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.952, kelly=0.903) with $9143.95 allocation
[SIM] 2017-06-27 00:00:00: 8 trades proposed.
[TRADE] 2017-06-27 00:00:00: allocated $9143.95 to INTC exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $8860.14 to TM exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $8019.60 to CAT exiting on 2017-06-28 00:00:00
[TRADE] 2017-06-27 00:00:00: allocated $4355.03 to CHTR exiting on 2017-06-28 00:00:00
[EXIT] 2017-06-28 00:00:00: INTC r=0.0163, PnL=$149.46
[EXIT] 2017-06-28 00:00:00: TM r=0.0074, PnL=$65.26
[EXIT] 2017-06-28 00:00:00: CAT r=0.0242, PnL=$194.45
[EXIT] 2017-06-28 00:00:00: CHTR r=0.0316, PnL=$137.70

Simulating Trading Days:  55%|█████▌    | 55/100 [14:27<00:53,  1.19s/it]

[SIM] 2017-06-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.740, kelly=0.477) with $4856.95 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.659, kelly=0.308) with $3137.31 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.919, kelly=0.838) with $8529.75 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.808, kelly=0.624) with $6349.79 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.793, kelly=0.587) with $5979.70 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.876, kelly=0.760) with $7741.13 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.815, kelly=0.650) with $6615.57 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.965, kelly=0.930) with $9471.07 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.537, kelly=0.022) with $227.40 allocation
[SIM] 2017-06-28 00:00:00: 9 trades proposed.
[TRADE] 2017-06-28 00:00:00: allocated $9471.07 to VZ exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $8529.75 to TM exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $7741.13 to CAT exiting on 2017-06-29 00:00:00
[TRADE] 2017-06-28 00:00:00: allocated $4800.82 to CHTR exiting on 2017-06-29 00:00:00
[EXIT] 2017-06-29 00:00:00: VZ r=-0.0096, PnL=$-90.82
[EXIT] 2017-06-29 00:00:00: TM r=-0.0092, PnL=$-78.57
[EXIT] 2017-06-29 00:00:00: CAT r=-0.0076, PnL=$-58.90
[EXIT] 2017-06-29 00:00:00: CHTR r=-0.0134, PnL=$-64.33

Simulating Trading Days:  56%|█████▌    | 56/100 [14:28<00:56,  1.29s/it]

[SIM] 2017-06-29 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.712, kelly=0.441) with $4477.55 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.671, kelly=0.331) with $3356.95 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.916, kelly=0.831) with $8438.82 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.803, kelly=0.614) with $6234.50 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.819, kelly=0.640) with $6495.25 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.859, kelly=0.726) with $7370.32 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.821, kelly=0.662) with $6725.21 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.973, kelly=0.946) with $9604.70 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.566, kelly=0.084) with $849.54 allocation
[SIM] 2017-06-29 00:00:00: 9 trades proposed.
[TRADE] 2017-06-29 00:00:00: allocated $9604.70 to VZ exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $8438.82 to TM exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $7370.32 to CAT exiting on 2017-06-30 00:00:00
[TRADE] 2017-06-29 00:00:00: allocated $5041.15 to CHTR exiting on 2017-06-30 00:00:00
[EXIT] 2017-06-30 00:00:00: VZ r=0.0056, PnL=$54.07
[EXIT] 2017-06-30 00:00:00: TM r=0.0065, PnL=$55.00
[EXIT] 2017-06-30 00:00:00: CAT r=0.0172, PnL=$126.98
[EXIT] 2017-06-30 00:00:00: CHTR r=0.0033, PnL=$16.67

Simulating Trading Days:  57%|█████▋    | 57/100 [14:30<00:59,  1.38s/it]

[SIM] 2017-06-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.706, kelly=0.431) with $4381.20 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.692, kelly=0.376) with $3821.65 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.919, kelly=0.837) with $8520.91 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.785, kelly=0.579) with $5895.76 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.839, kelly=0.679) with $6907.13 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.822, kelly=0.655) with $6664.38 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.808, kelly=0.637) with $6481.75 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.976, kelly=0.953) with $9696.61 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.585, kelly=0.123) with $1254.98 allocation
[SIM] 2017-06-30 00:00:00: 9 trades proposed.
[TRADE] 2017-06-30 00:00:00: allocated $9696.61 to VZ exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $8520.91 to TM exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $6907.13 to SNY exiting on 2017-07-03 00:00:00
[TRADE] 2017-06-30 00:00:00: allocated $5406.14 to CAT exiting on 2017-07-03 00:00:00
[EXIT] 2017-07-03 00:00:00: VZ r=0.0076, PnL=$73.82
[EXIT] 2017-07-03 00:00:00: TM r=0.0096, PnL=$81.95
[EXIT] 2017-07-03 00:00:00: SNY r=-0.0023, PnL=$-15.86
[EXIT] 2017-07-03 00:00:00: CAT r=-0.0046, PnL=$-24.65

Simulating Trading Days:  58%|█████▊    | 58/100 [14:32<01:04,  1.53s/it]

[SIM] 2017-07-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.698, kelly=0.415) with $4231.37 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.711, kelly=0.413) with $4210.08 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.926, kelly=0.852) with $8675.76 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.769, kelly=0.549) with $5590.74 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.862, kelly=0.725) with $7388.08 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.765, kelly=0.525) with $5349.02 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.795, kelly=0.612) with $6236.66 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.981, kelly=0.962) with $9805.79 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.616, kelly=0.187) with $1904.73 allocation
[SIM] 2017-07-03 00:00:00: 9 trades proposed.
[TRADE] 2017-07-03 00:00:00: allocated $9805.79 to VZ exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $8675.76 to TM exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $7388.08 to SNY exiting on 2017-07-05 00:00:00
[TRADE] 2017-07-03 00:00:00: allocated $4695.74 to CHTR exiting on 2017-07-05 00:00:00
[EXIT] 2017-07-05 00:00:00: VZ r=-0.0078, PnL=$-76.27
[EXIT] 2017-07-05 00:00:00: TM r=0.0236, PnL=$204.56
[EXIT] 2017-07-05 00:00:00: SNY r=0.0006, PnL=$4.64
[EXIT] 2017-07-05 00:00:00: CHTR r=0.0196, PnL=$92.01

Simulating Trading Days:  59%|█████▉    | 59/100 [14:34<01:14,  1.82s/it]

[SIM] 2017-07-05 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.687, kelly=0.394) with $4018.22 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.725, kelly=0.443) with $4518.56 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.928, kelly=0.856) with $8745.43 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.753, kelly=0.517) with $5276.33 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.873, kelly=0.746) with $7617.33 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.777, kelly=0.550) with $5617.04 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.771, kelly=0.567) with $5786.45 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.983, kelly=0.966) with $9868.10 allocation
[PORT] Sector Utilities: selecting SO (p_up=0.633, kelly=0.224) with $2287.27 allocation
[SIM] 2017-07-05 00:00:00: 9 trades proposed.
[TRADE] 2017-07-05 00:00:00: allocated $9868.10 to VZ exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $8745.43 to TM exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $7617.33 to SNY exiting on 2017-07-06 00:00:00
[TRADE] 2017-07-05 00:00:00: allocated $4401.99 to BA exiting on 2017-07-06 00:00:00
[EXIT] 2017-07-06 00:00:00: VZ r=-0.0253, PnL=$-249.74
[EXIT] 2017-07-06 00:00:00: TM r=-0.0100, PnL=$-87.03
[EXIT] 2017-07-06 00:00:00: SNY r=-0.0128, PnL=$-97.15
[EXIT] 2017-07-06 00:00:00: BA r=-0.0016, PnL=$-7.20

Simulating Trading Days:  60%|██████    | 60/100 [14:35<01:06,  1.67s/it]

[SIM] 2017-07-06 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.678, kelly=0.376) with $3822.60 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.740, kelly=0.474) with $4815.78 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.919, kelly=0.837) with $8510.84 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.742, kelly=0.496) with $5044.61 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.866, kelly=0.733) with $7452.52 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.787, kelly=0.570) with $5799.31 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.771, kelly=0.567) with $5763.79 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.983, kelly=0.966) with $9825.07 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.635, kelly=0.248) with $2520.33 allocation
[SIM] 2017-07-06 00:00:00: 9 trades proposed.
[TRADE] 2017-07-06 00:00:00: allocated $9825.07 to VZ exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $8510.84 to TM exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $7452.52 to SNY exiting on 2017-07-07 00:00:00
[TRADE] 2017-07-06 00:00:00: allocated $4712.09 to BA exiting on 2017-07-07 00:00:00
[EXIT] 2017-07-07 00:00:00: VZ r=-0.0009, PnL=$-9.03
[EXIT] 2017-07-07 00:00:00: TM r=0.0095, PnL=$80.79
[EXIT] 2017-07-07 00:00:00: SNY r=0.0144, PnL=$107.32
[EXIT] 2017-07-07 00:00:00: BA r=0.0044, PnL=$20.81

Simulating Trading Days:  61%|██████    | 61/100 [14:37<01:00,  1.55s/it]

[SIM] 2017-07-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.671, kelly=0.362) with $3691.08 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.757, kelly=0.508) with $5179.70 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.885, kelly=0.775) with $7892.55 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.746, kelly=0.503) with $5121.73 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.851, kelly=0.703) with $7157.23 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.790, kelly=0.577) with $5878.49 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.769, kelly=0.564) with $5741.00 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.983, kelly=0.966) with $9836.40 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.594, kelly=0.141) with $1438.19 allocation
[SIM] 2017-07-07 00:00:00: 9 trades proposed.
[TRADE] 2017-07-07 00:00:00: allocated $9836.40 to VZ exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $7892.55 to UN exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $7157.23 to SNY exiting on 2017-07-10 00:00:00
[TRADE] 2017-07-07 00:00:00: allocated $5674.30 to BA exiting on 2017-07-10 00:00:00
[EXIT] 2017-07-10 00:00:00: VZ r=-0.0064, PnL=$-63.34
[EXIT] 2017-07-10 00:00:00: UN r=0.0084, PnL=$66.34
[EXIT] 2017-07-10 00:00:00: SNY r=-0.0050, PnL=$-35.86
[EXIT] 2017-07-10 00:00:00: BA r=0.0079, PnL=$44.58

Simulating Trading Days:  62%|██████▏   | 62/100 [14:38<00:56,  1.49s/it]

[SIM] 2017-07-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.680, kelly=0.357) with $3636.75 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.779, kelly=0.553) with $5635.33 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.899, kelly=0.802) with $8167.15 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.756, kelly=0.521) with $5312.90 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.854, kelly=0.708) with $7210.15 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.792, kelly=0.581) with $5921.84 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.771, kelly=0.566) with $5769.29 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.985, kelly=0.970) with $9877.36 allocation
[PORT] Sector Utilities: selecting NEE (p_up=0.593, kelly=0.139) with $1419.32 allocation
[SIM] 2017-07-10 00:00:00: 9 trades proposed.
[TRADE] 2017-07-10 00:00:00: allocated $9877.36 to VZ exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $8167.15 to UN exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $7210.15 to SNY exiting on 2017-07-11 00:00:00
[TRADE] 2017-07-10 00:00:00: allocated $5309.35 to BA exiting on 2017-07-11 00:00:00
[EXIT] 2017-07-11 00:00:00: VZ r=-0.0072, PnL=$-70.88
[EXIT] 2017-07-11 00:00:00: UN r=0.0058, PnL=$47.35
[EXIT] 2017-07-11 00:00:00: SNY r=0.0029, PnL=$21.18
[EXIT] 2017-07-11 00:00:00: BA r=0.0113, PnL=$60.13

Simulating Trading Days:  63%|██████▎   | 63/100 [14:39<00:53,  1.44s/it]

[SIM] 2017-07-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.722, kelly=0.440) with $4486.54 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.796, kelly=0.587) with $5981.26 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.908, kelly=0.820) with $8354.95 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.764, kelly=0.538) with $5487.63 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.864, kelly=0.729) with $7431.25 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.790, kelly=0.576) with $5875.61 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.767, kelly=0.560) with $5707.43 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.985, kelly=0.970) with $9887.57 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.630, kelly=0.239) with $2431.41 allocation
[SIM] 2017-07-11 00:00:00: 9 trades proposed.
[TRADE] 2017-07-11 00:00:00: allocated $9887.57 to VZ exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $8354.95 to UN exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $7431.25 to SNY exiting on 2017-07-12 00:00:00
[TRADE] 2017-07-11 00:00:00: allocated $4907.57 to IEP exiting on 2017-07-12 00:00:00
[EXIT] 2017-07-12 00:00:00: VZ r=0.0077, PnL=$76.08
[EXIT] 2017-07-12 00:00:00: UN r=0.0077, PnL=$64.72
[EXIT] 2017-07-12 00:00:00: SNY r=0.0228, PnL=$169.46
[EXIT] 2017-07-12 00:00:00: IEP r=0.0023, PnL=$11.51

Simulating Trading Days:  64%|██████▍   | 64/100 [14:40<00:49,  1.37s/it]

[SIM] 2017-07-12 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.715, kelly=0.426) with $4359.99 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.802, kelly=0.600) with $6131.73 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.915, kelly=0.833) with $8519.46 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.785, kelly=0.578) with $5913.08 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.875, kelly=0.751) with $7679.11 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.788, kelly=0.572) with $5847.63 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.759, kelly=0.544) with $5562.78 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.985, kelly=0.970) with $9918.25 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.623, kelly=0.225) with $2301.76 allocation
[SIM] 2017-07-12 00:00:00: 9 trades proposed.
[TRADE] 2017-07-12 00:00:00: allocated $9918.25 to VZ exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $8519.46 to UN exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $7679.11 to SNY exiting on 2017-07-13 00:00:00
[TRADE] 2017-07-12 00:00:00: allocated $4561.05 to IEP exiting on 2017-07-13 00:00:00
[EXIT] 2017-07-13 00:00:00: VZ r=0.0062, PnL=$61.96
[EXIT] 2017-07-13 00:00:00: UN r=0.0045, PnL=$38.07
[EXIT] 2017-07-13 00:00:00: SNY r=-0.0051, PnL=$-39.27
[EXIT] 2017-07-13 00:00:00: IEP r=0.0121, PnL=$55.15

Simulating Trading Days:  65%|██████▌   | 65/100 [14:42<00:46,  1.32s/it]

[SIM] 2017-07-13 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting TOT (p_up=0.672, kelly=0.339) with $3466.53 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.799, kelly=0.593) with $6073.26 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.918, kelly=0.839) with $8588.47 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.806, kelly=0.621) with $6355.44 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.880, kelly=0.761) with $7789.25 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.783, kelly=0.561) with $5747.13 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.744, kelly=0.515) with $5272.33 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.986, kelly=0.971) with $9942.82 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.617, kelly=0.214) with $2188.46 allocation
[SIM] 2017-07-13 00:00:00: 9 trades proposed.
[TRADE] 2017-07-13 00:00:00: allocated $9942.82 to VZ exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $8588.47 to UN exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $7789.25 to SNY exiting on 2017-07-14 00:00:00
[TRADE] 2017-07-13 00:00:00: allocated $4392.10 to BAC exiting on 2017-07-14 00:00:00
[EXIT] 2017-07-14 00:00:00: VZ r=0.0016, PnL=$16.00
[EXIT] 2017-07-14 00:00:00: UN r=0.0123, PnL=$105.46
[EXIT] 2017-07-14 00:00:00: SNY r=-0.0095, PnL=$-73.66
[EXIT] 2017-07-14 00:00:00: BAC r=-0.0167, PnL=$-73.14

Simulating Trading Days:  66%|██████▌   | 66/100 [14:43<00:42,  1.26s/it]

[SIM] 2017-07-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.647, kelly=0.315) with $3220.51 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.790, kelly=0.574) with $5878.66 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.916, kelly=0.836) with $8553.07 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.828, kelly=0.662) with $6776.94 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.873, kelly=0.746) with $7634.87 allocation
[PORT] Sector Industrial Goods: selecting BA (p_up=0.776, kelly=0.549) with $5619.76 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.717, kelly=0.464) with $4745.30 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.986, kelly=0.972) with $9948.51 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.613, kelly=0.206) with $2103.64 allocation
[SIM] 2017-07-14 00:00:00: 9 trades proposed.
[TRADE] 2017-07-14 00:00:00: allocated $9948.51 to VZ exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $8553.07 to UN exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $7634.87 to SNY exiting on 2017-07-17 00:00:00
[TRADE] 2017-07-14 00:00:00: allocated $4568.59 to BAC exiting on 2017-07-17 00:00:00
[EXIT] 2017-07-17 00:00:00: VZ r=0.0023, PnL=$22.84
[EXIT] 2017-07-17 00:00:00: UN r=-0.0002, PnL=$-1.50
[EXIT] 2017-07-17 00:00:00: SNY r=0.0000, PnL=$0.00
[EXIT] 2017-07-17 00:00:00: BAC r=-0.0078, PnL=$-35.85

Simulating Trading Days:  67%|██████▋   | 67/100 [14:44<00:40,  1.23s/it]

[SIM] 2017-07-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.641, kelly=0.303) with $3101.22 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.777, kelly=0.547) with $5600.38 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.912, kelly=0.826) with $8455.76 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.841, kelly=0.689) with $7047.10 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.860, kelly=0.720) with $7370.47 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.831, kelly=0.672) with $6872.69 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.700, kelly=0.433) with $4428.28 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.986, kelly=0.973) with $9953.07 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.611, kelly=0.200) with $2051.82 allocation
[SIM] 2017-07-17 00:00:00: 9 trades proposed.
[TRADE] 2017-07-17 00:00:00: allocated $9953.07 to VZ exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $8455.76 to UN exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $7370.47 to SNY exiting on 2017-07-18 00:00:00
[TRADE] 2017-07-17 00:00:00: allocated $4921.38 to BAC exiting on 2017-07-18 00:00:00
[EXIT] 2017-07-18 00:00:00: VZ r=-0.0069, PnL=$-68.39
[EXIT] 2017-07-18 00:00:00: UN r=0.0002, PnL=$1.49
[EXIT] 2017-07-18 00:00:00: SNY r=-0.0091, PnL=$-67.31
[EXIT] 2017-07-18 00:00:00: BAC r=-0.0050, PnL=$-24.59

Simulating Trading Days:  68%|██████▊   | 68/100 [14:45<00:38,  1.20s/it]

[SIM] 2017-07-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.636, kelly=0.294) with $3001.26 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.759, kelly=0.512) with $5232.42 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.903, kelly=0.809) with $8266.70 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.855, kelly=0.716) with $7311.82 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.855, kelly=0.712) with $7272.05 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.838, kelly=0.686) with $7012.77 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.682, kelly=0.398) with $4069.75 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.986, kelly=0.972) with $9927.77 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.589, kelly=0.156) with $1590.65 allocation
[SIM] 2017-07-18 00:00:00: 9 trades proposed.
[TRADE] 2017-07-18 00:00:00: allocated $9927.77 to VZ exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $8266.70 to UN exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $7272.05 to SNY exiting on 2017-07-19 00:00:00
[TRADE] 2017-07-18 00:00:00: allocated $5186.53 to BAC exiting on 2017-07-19 00:00:00
[EXIT] 2017-07-19 00:00:00: VZ r=0.0021, PnL=$20.61
[EXIT] 2017-07-19 00:00:00: UN r=0.0000, PnL=$0.00
[EXIT] 2017-07-19 00:00:00: SNY r=-0.0195, PnL=$-141.66
[EXIT] 2017-07-19 00:00:00: BAC r=0.0067, PnL=$34.72

Simulating Trading Days:  69%|██████▉   | 69/100 [14:46<00:37,  1.20s/it]

[SIM] 2017-07-19 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.629, kelly=0.280) with $2858.46 allocation
[PORT] Sector Conglomerates: selecting SPLP (p_up=0.750, kelly=0.501) with $5112.10 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.895, kelly=0.794) with $8105.45 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.859, kelly=0.723) with $7382.76 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.860, kelly=0.720) with $7354.34 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.849, kelly=0.707) with $7222.23 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.672, kelly=0.380) with $3884.26 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.986, kelly=0.971) with $9914.74 allocation
[PORT] Sector Utilities: selecting PCG (p_up=0.560, kelly=0.096) with $975.51 allocation
[SIM] 2017-07-19 00:00:00: 9 trades proposed.
[TRADE] 2017-07-19 00:00:00: allocated $9914.74 to VZ exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $8105.45 to UN exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $7354.34 to SNY exiting on 2017-07-20 00:00:00
[TRADE] 2017-07-19 00:00:00: allocated $5252.61 to BAC exiting on 2017-07-20 00:00:00
[EXIT] 2017-07-20 00:00:00: VZ r=0.0177, PnL=$175.70
[EXIT] 2017-07-20 00:00:00: UN r=0.0172, PnL=$139.65
[EXIT] 2017-07-20 00:00:00: SNY r=0.0267, PnL=$196.39
[EXIT] 2017-07-20 00:00:00: BAC r=-0.0050, PnL=$-26.20

Simulating Trading Days:  70%|███████   | 70/100 [14:47<00:35,  1.19s/it]

[SIM] 2017-07-20 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 45 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.602, kelly=0.176) with $1801.22 allocation
[PORT] Sector Conglomerates: selecting SPLP (p_up=0.748, kelly=0.496) with $5088.70 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.885, kelly=0.774) with $7938.97 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.857, kelly=0.720) with $7381.70 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.866, kelly=0.732) with $7509.51 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.879, kelly=0.765) with $7852.16 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.661, kelly=0.359) with $3681.88 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.987, kelly=0.973) with $9980.72 allocation
[SIM] 2017-07-20 00:00:00: 8 trades proposed.
[TRADE] 2017-07-20 00:00:00: allocated $9980.72 to VZ exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $7938.97 to UN exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $7852.16 to CAT exiting on 2017-07-21 00:00:00
[TRADE] 2017-07-20 00:00:00: allocated $5000.97 to SNY exiting on 2017-07-21 00:00:00
[EXIT] 2017-07-21 00:00:00: VZ r=0.0002, PnL=$2.26
[EXIT] 2017-07-21 00:00:00: UN r=0.0045, PnL=$35.67
[EXIT] 2017-07-21 00:00:00: CAT r=-0.0068, PnL=$-53.41
[EXIT] 2017-07-21 00:00:00: SNY r=-0.0073, PnL=$-36.42

Simulating Trading Days:  71%|███████   | 71/100 [14:49<00:34,  1.19s/it]

[SIM] 2017-07-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 44 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.608, kelly=0.189) with $1934.77 allocation
[PORT] Sector Conglomerates: selecting SPLP (p_up=0.747, kelly=0.496) with $5082.40 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.879, kelly=0.762) with $7809.61 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.842, kelly=0.691) with $7084.27 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.871, kelly=0.743) with $7620.19 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.891, kelly=0.787) with $8072.82 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.651, kelly=0.340) with $3489.56 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.988, kelly=0.975) with $9999.96 allocation
[SIM] 2017-07-21 00:00:00: 8 trades proposed.
[TRADE] 2017-07-21 00:00:00: allocated $9999.96 to VZ exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $8072.82 to CAT exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $7809.61 to UN exiting on 2017-07-24 00:00:00
[TRADE] 2017-07-21 00:00:00: allocated $4874.84 to SNY exiting on 2017-07-24 00:00:00
[EXIT] 2017-07-24 00:00:00: VZ r=-0.0118, PnL=$-117.57
[EXIT] 2017-07-24 00:00:00: CAT r=0.0149, PnL=$120.42
[EXIT] 2017-07-24 00:00:00: UN r=-0.0088, PnL=$-68.53
[EXIT] 2017-07-24 00:00:00: SNY r=0.0000, PnL=$0.00

Simulating Trading Days:  72%|███████▏  | 72/100 [14:50<00:32,  1.18s/it]

[SIM] 2017-07-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 43 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.614, kelly=0.201) with $2060.99 allocation
[PORT] Sector Conglomerates: selecting SPLP (p_up=0.744, kelly=0.488) with $5001.36 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.877, kelly=0.758) with $7765.61 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.819, kelly=0.647) with $6625.26 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.874, kelly=0.750) with $7686.07 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.910, kelly=0.826) with $8460.05 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.650, kelly=0.338) with $3465.98 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.989, kelly=0.978) with $10025.16 allocation
[SIM] 2017-07-24 00:00:00: 8 trades proposed.
[TRADE] 2017-07-24 00:00:00: allocated $10025.16 to VZ exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $8460.05 to CAT exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $7765.61 to UN exiting on 2017-07-25 00:00:00
[TRADE] 2017-07-24 00:00:00: allocated $4486.72 to SNY exiting on 2017-07-25 00:00:00
[EXIT] 2017-07-25 00:00:00: VZ r=0.0062, PnL=$61.93
[EXIT] 2017-07-25 00:00:00: CAT r=0.0588, PnL=$497.37
[EXIT] 2017-07-25 00:00:00: UN r=0.0028, PnL=$21.57
[EXIT] 2017-07-25 00:00:00: SNY r=0.0075, PnL=$33.86

Simulating Trading Days:  73%|███████▎  | 73/100 [14:51<00:31,  1.18s/it]

[SIM] 2017-07-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 44 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.623, kelly=0.219) with $2262.01 allocation
[PORT] Sector Conglomerates: selecting SPLP (p_up=0.741, kelly=0.482) with $4966.26 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.874, kelly=0.753) with $7761.78 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.787, kelly=0.583) with $6007.67 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.880, kelly=0.761) with $7846.25 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.924, kelly=0.853) with $8793.44 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.643, kelly=0.325) with $3347.63 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.989, kelly=0.977) with $10074.52 allocation
[SIM] 2017-07-25 00:00:00: 8 trades proposed.
[TRADE] 2017-07-25 00:00:00: allocated $10074.52 to VZ exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $8793.44 to CAT exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $7846.25 to SNY exiting on 2017-07-26 00:00:00
[TRADE] 2017-07-25 00:00:00: allocated $4207.74 to UN exiting on 2017-07-26 00:00:00
[EXIT] 2017-07-26 00:00:00: VZ r=0.0095, PnL=$96.21
[EXIT] 2017-07-26 00:00:00: CAT r=-0.0089, PnL=$-78.31
[EXIT] 2017-07-26 00:00:00: SNY r=-0.0010, PnL=$-8.16
[EXIT] 2017-07-26 00:00:00: UN r=0.0092, PnL=$38.60

Simulating Trading Days:  74%|███████▍  | 74/100 [14:52<00:30,  1.17s/it]

[SIM] 2017-07-26 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 47 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.636, kelly=0.247) with $2548.89 allocation
[PORT] Sector Conglomerates: selecting SPLP (p_up=0.740, kelly=0.480) with $4946.40 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.876, kelly=0.756) with $7792.52 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.743, kelly=0.498) with $5136.05 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.887, kelly=0.775) with $7988.28 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.926, kelly=0.856) with $8832.04 allocation
[PORT] Sector Services: selecting DIS (p_up=0.757, kelly=0.513) with $5289.61 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.988, kelly=0.975) with $10056.15 allocation
[SIM] 2017-07-26 00:00:00: 8 trades proposed.
[TRADE] 2017-07-26 00:00:00: allocated $10056.15 to VZ exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $8832.04 to CAT exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $7988.28 to SNY exiting on 2017-07-27 00:00:00
[TRADE] 2017-07-26 00:00:00: allocated $4060.00 to UN exiting on 2017-07-27 00:00:00
[EXIT] 2017-07-27 00:00:00: VZ r=0.0768, PnL=$772.33
[EXIT] 2017-07-27 00:00:00: CAT r=0.0075, PnL=$66.13
[EXIT] 2017-07-27 00:00:00: SNY r=0.0015, PnL=$11.64
[EXIT] 2017-07-27 00:00:00: UN r=-0.0005, PnL=$-2.09

Simulating Trading Days:  75%|███████▌  | 75/100 [14:53<00:29,  1.17s/it]

[SIM] 2017-07-27 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.651, kelly=0.277) with $2880.30 allocation
[PORT] Sector Conglomerates: selecting SPLP (p_up=0.729, kelly=0.458) with $4763.61 allocation
[PORT] Sector Consumer Goods: selecting TM (p_up=0.920, kelly=0.841) with $8741.07 allocation
[PORT] Sector Financial: selecting BAC (p_up=0.679, kelly=0.373) with $3873.10 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.889, kelly=0.779) with $8103.37 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.933, kelly=0.871) with $9052.87 allocation
[PORT] Sector Services: selecting DIS (p_up=0.765, kelly=0.530) with $5506.47 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.989, kelly=0.977) with $10156.56 allocation
[SIM] 2017-07-27 00:00:00: 8 trades proposed.
[TRADE] 2017-07-27 00:00:00: allocated $10156.56 to VZ exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $9052.87 to CAT exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $8741.07 to TM exiting on 2017-07-28 00:00:00
[TRADE] 2017-07-27 00:00:00: allocated $3240.36 to SNY exiting on 2017-07-28 00:00:00
[EXIT] 2017-07-28 00:00:00: VZ r=0.0027, PnL=$27.62
[EXIT] 2017-07-28 00:00:00: CAT r=-0.0024, PnL=$-21.37
[EXIT] 2017-07-28 00:00:00: TM r=0.0053, PnL=$46.18
[EXIT] 2017-07-28 00:00:00: SNY r=-0.0110, PnL=$-35.71

Simulating Trading Days:  76%|███████▌  | 76/100 [14:55<00:28,  1.19s/it]

[SIM] 2017-07-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.660, kelly=0.295) with $3072.79 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.741, kelly=0.465) with $4838.56 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.880, kelly=0.764) with $7939.79 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.611, kelly=0.232) with $2407.63 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.889, kelly=0.778) with $8090.49 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.943, kelly=0.891) with $9261.79 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.667, kelly=0.373) with $3877.32 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.990, kelly=0.980) with $10189.04 allocation
[SIM] 2017-07-28 00:00:00: 8 trades proposed.
[TRADE] 2017-07-28 00:00:00: allocated $10189.04 to VZ exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $9261.79 to CAT exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $8090.49 to SNY exiting on 2017-07-31 00:00:00
[TRADE] 2017-07-28 00:00:00: allocated $3654.56 to UN exiting on 2017-07-31 00:00:00
[EXIT] 2017-07-31 00:00:00: VZ r=0.0096, PnL=$97.77
[EXIT] 2017-07-31 00:00:00: CAT r=-0.0013, PnL=$-12.18
[EXIT] 2017-07-31 00:00:00: SNY r=-0.0042, PnL=$-34.02
[EXIT] 2017-07-31 00:00:00: UN r=0.0022, PnL=$8.19

Simulating Trading Days:  77%|███████▋  | 77/100 [14:56<00:27,  1.19s/it]

[SIM] 2017-07-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.662, kelly=0.298) with $3100.57 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.774, kelly=0.533) with $5541.04 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.883, kelly=0.771) with $8016.81 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.589, kelly=0.186) with $1933.48 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.887, kelly=0.775) with $8068.59 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.940, kelly=0.883) with $9191.35 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.669, kelly=0.376) with $3914.12 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.992, kelly=0.985) with $10246.29 allocation
[SIM] 2017-07-31 00:00:00: 8 trades proposed.
[TRADE] 2017-07-31 00:00:00: allocated $10246.29 to VZ exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $9191.35 to CAT exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $8068.59 to SNY exiting on 2017-08-01 00:00:00
[TRADE] 2017-07-31 00:00:00: allocated $3707.58 to UN exiting on 2017-08-01 00:00:00
[EXIT] 2017-08-01 00:00:00: VZ r=0.0101, PnL=$103.73
[EXIT] 2017-08-01 00:00:00: CAT r=-0.0075, PnL=$-68.56
[EXIT] 2017-08-01 00:00:00: SNY r=-0.0068, PnL=$-54.52
[EXIT] 2017-08-01 00:00:00: UN r=-0.0010, PnL=$-3.82

Simulating Trading Days:  78%|███████▊  | 78/100 [14:57<00:26,  1.18s/it]

[SIM] 2017-08-01 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.655, kelly=0.285) with $2966.60 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.787, kelly=0.560) with $5828.45 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.893, kelly=0.790) with $8216.24 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.624, kelly=0.256) with $2658.65 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.885, kelly=0.772) with $8027.92 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.922, kelly=0.850) with $8842.72 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.658, kelly=0.358) with $3721.88 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.989, kelly=0.977) with $10164.79 allocation
[SIM] 2017-08-01 00:00:00: 8 trades proposed.
[TRADE] 2017-08-01 00:00:00: allocated $10164.79 to VZ exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $8842.72 to CAT exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $8216.24 to UN exiting on 2017-08-02 00:00:00
[TRADE] 2017-08-01 00:00:00: allocated $3983.10 to SNY exiting on 2017-08-02 00:00:00
[EXIT] 2017-08-02 00:00:00: VZ r=-0.0139, PnL=$-141.38
[EXIT] 2017-08-02 00:00:00: CAT r=-0.0001, PnL=$-0.78
[EXIT] 2017-08-02 00:00:00: UN r=-0.0029, PnL=$-24.04
[EXIT] 2017-08-02 00:00:00: SNY r=0.0094, PnL=$37.26

Simulating Trading Days:  79%|███████▉  | 79/100 [14:58<00:24,  1.18s/it]

[SIM] 2017-08-02 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting BHP (p_up=0.642, kelly=0.257) with $2673.54 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.794, kelly=0.575) with $5972.76 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.898, kelly=0.800) with $8314.62 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.619, kelly=0.246) with $2555.50 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.885, kelly=0.772) with $8016.26 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.905, kelly=0.818) with $8494.32 allocation
[PORT] Sector Services: selecting DIS (p_up=0.767, kelly=0.536) with $5572.19 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.984, kelly=0.969) with $10065.48 allocation
[SIM] 2017-08-02 00:00:00: 8 trades proposed.
[TRADE] 2017-08-02 00:00:00: allocated $10065.48 to VZ exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $8494.32 to CAT exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $8314.62 to UN exiting on 2017-08-03 00:00:00
[TRADE] 2017-08-02 00:00:00: allocated $4293.75 to SNY exiting on 2017-08-03 00:00:00
[EXIT] 2017-08-03 00:00:00: VZ r=0.0083, PnL=$83.51
[EXIT] 2017-08-03 00:00:00: CAT r=0.0042, PnL=$35.30
[EXIT] 2017-08-03 00:00:00: UN r=0.0047, PnL=$38.75
[EXIT] 2017-08-03 00:00:00: SNY r=0.0042, PnL=$18.09

Simulating Trading Days:  80%|████████  | 80/100 [14:59<00:23,  1.16s/it]

[SIM] 2017-08-03 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.682, kelly=0.384) with $3993.78 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.808, kelly=0.603) with $6275.65 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.901, kelly=0.805) with $8381.36 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.616, kelly=0.240) with $2498.33 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.883, kelly=0.768) with $7990.00 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.900, kelly=0.807) with $8400.77 allocation
[PORT] Sector Services: selecting DIS (p_up=0.798, kelly=0.596) with $6202.38 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.976, kelly=0.951) with $9901.42 allocation
[SIM] 2017-08-03 00:00:00: 8 trades proposed.
[TRADE] 2017-08-03 00:00:00: allocated $9901.42 to VZ exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $8381.36 to UN exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $8400.77 to CAT exiting on 2017-08-04 00:00:00
[TRADE] 2017-08-03 00:00:00: allocated $4537.32 to SNY exiting on 2017-08-04 00:00:00
[EXIT] 2017-08-04 00:00:00: VZ r=0.0062, PnL=$61.11
[EXIT] 2017-08-04 00:00:00: UN r=0.0000, PnL=$0.00
[EXIT] 2017-08-04 00:00:00: CAT r=0.0070, PnL=$58.44
[EXIT] 2017-08-04 00:00:00: SNY r=0.0084, PnL=$38.06

Simulating Trading Days:  81%|████████  | 81/100 [15:00<00:22,  1.18s/it]

[SIM] 2017-08-04 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.686, kelly=0.390) with $4065.73 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.810, kelly=0.607) with $6330.89 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.906, kelly=0.815) with $8493.88 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.613, kelly=0.234) with $2436.96 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.875, kelly=0.752) with $7833.55 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.892, kelly=0.791) with $8248.85 allocation
[PORT] Sector Services: selecting DIS (p_up=0.812, kelly=0.625) with $6511.35 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.960, kelly=0.920) with $9592.58 allocation
[SIM] 2017-08-04 00:00:00: 8 trades proposed.
[TRADE] 2017-08-04 00:00:00: allocated $9592.58 to VZ exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $8493.88 to UN exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $8248.85 to CAT exiting on 2017-08-07 00:00:00
[TRADE] 2017-08-04 00:00:00: allocated $4932.85 to SNY exiting on 2017-08-07 00:00:00
[EXIT] 2017-08-07 00:00:00: VZ r=-0.0010, PnL=$-9.81
[EXIT] 2017-08-07 00:00:00: UN r=0.0053, PnL=$45.23
[EXIT] 2017-08-07 00:00:00: CAT r=0.0031, PnL=$25.97
[EXIT] 2017-08-07 00:00:00: SNY r=-0.0023, PnL=$-11.29

Simulating Trading Days:  82%|████████▏ | 82/100 [15:02<00:21,  1.18s/it]

[SIM] 2017-08-07 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.688, kelly=0.394) with $4104.95 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.811, kelly=0.611) with $6369.02 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.910, kelly=0.823) with $8585.00 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.626, kelly=0.259) with $2700.32 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.861, kelly=0.722) with $7531.60 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.883, kelly=0.775) with $8081.38 allocation
[PORT] Sector Services: selecting DIS (p_up=0.812, kelly=0.624) with $6505.57 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.939, kelly=0.878) with $9151.60 allocation
[SIM] 2017-08-07 00:00:00: 8 trades proposed.
[TRADE] 2017-08-07 00:00:00: allocated $9151.60 to VZ exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $8585.00 to UN exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $8081.38 to CAT exiting on 2017-08-08 00:00:00
[TRADE] 2017-08-07 00:00:00: allocated $5465.21 to SNY exiting on 2017-08-08 00:00:00
[EXIT] 2017-08-08 00:00:00: VZ r=-0.0053, PnL=$-48.70
[EXIT] 2017-08-08 00:00:00: UN r=0.0009, PnL=$7.34
[EXIT] 2017-08-08 00:00:00: CAT r=-0.0026, PnL=$-21.13
[EXIT] 2017-08-08 00:00:00: SNY r=-0.0010, PnL=$-5.70

Simulating Trading Days:  83%|████████▎ | 83/100 [15:03<00:20,  1.20s/it]

[SIM] 2017-08-08 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.690, kelly=0.398) with $4150.49 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.810, kelly=0.609) with $6341.77 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.912, kelly=0.826) with $8612.13 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.672, kelly=0.351) with $3656.01 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.848, kelly=0.697) with $7261.07 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.873, kelly=0.755) with $7863.92 allocation
[PORT] Sector Services: selecting DIS (p_up=0.788, kelly=0.576) with $6005.59 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.915, kelly=0.830) with $8649.76 allocation
[SIM] 2017-08-08 00:00:00: 8 trades proposed.
[TRADE] 2017-08-08 00:00:00: allocated $8649.76 to VZ exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $8612.13 to UN exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $7863.92 to CAT exiting on 2017-08-09 00:00:00
[TRADE] 2017-08-08 00:00:00: allocated $6136.92 to SNY exiting on 2017-08-09 00:00:00
[EXIT] 2017-08-09 00:00:00: VZ r=-0.0078, PnL=$-67.63
[EXIT] 2017-08-09 00:00:00: UN r=0.0039, PnL=$33.82
[EXIT] 2017-08-09 00:00:00: CAT r=-0.0006, PnL=$-4.81
[EXIT] 2017-08-09 00:00:00: SNY r=-0.0035, PnL=$-21.77

Simulating Trading Days:  84%|████████▍ | 84/100 [15:04<00:20,  1.31s/it]

[SIM] 2017-08-09 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.698, kelly=0.413) with $4302.68 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.809, kelly=0.606) with $6313.44 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.908, kelly=0.819) with $8533.24 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.700, kelly=0.405) with $4218.52 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.839, kelly=0.680) with $7085.07 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.879, kelly=0.767) with $7990.87 allocation
[PORT] Sector Services: selecting DIS (p_up=0.739, kelly=0.479) with $4987.55 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.885, kelly=0.771) with $8026.16 allocation
[SIM] 2017-08-09 00:00:00: 8 trades proposed.
[TRADE] 2017-08-09 00:00:00: allocated $8533.24 to UN exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $8026.16 to VZ exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $7990.87 to CAT exiting on 2017-08-10 00:00:00
[TRADE] 2017-08-09 00:00:00: allocated $6694.34 to SNY exiting on 2017-08-10 00:00:00
[EXIT] 2017-08-10 00:00:00: UN r=-0.0145, PnL=$-123.35
[EXIT] 2017-08-10 00:00:00: VZ r=-0.0041, PnL=$-33.29
[EXIT] 2017-08-10 00:00:00: CAT r=-0.0104, PnL=$-83.16
[EXIT] 2017-08-10 00:00:00: SNY r=-0.0071, PnL=$-47.67

Simulating Trading Days:  85%|████████▌ | 85/100 [15:06<00:19,  1.27s/it]

[SIM] 2017-08-10 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.706, kelly=0.430) with $4465.01 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.771, kelly=0.537) with $5578.24 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.903, kelly=0.809) with $8403.38 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.717, kelly=0.439) with $4558.84 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.839, kelly=0.681) with $7072.62 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.885, kelly=0.778) with $8083.03 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.628, kelly=0.304) with $3161.41 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.860, kelly=0.721) with $7484.66 allocation
[SIM] 2017-08-10 00:00:00: 8 trades proposed.
[TRADE] 2017-08-10 00:00:00: allocated $8403.38 to UN exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $8083.03 to CAT exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $7484.66 to VZ exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $7072.62 to SNY exiting on 2017-08-11 00:00:00
[TRADE] 2017-08-10 00:00:00: allocated $114.68 to IEP exiting on 2017-08-11 00:00:00
[EXIT] 2017-08-11 00:00:00: UN r=0.0002, PnL=$1.45
[EXIT] 2017-08-11 00:00:00: CAT r=-0.0027, PnL=$-21.43
[EXIT] 2017-08-11 00:00:00: VZ r=0.0008, PnL=$6.23
[EXIT] 2017-08-11 00:00:00: SNY r=0.0030, PnL=$20.89
[EXIT] 2017-08-11 00:00:00: IEP r=-0.0198, PnL=$-2.27

Simulating Trading Days:  86%|████████▌ | 86/100 [15:07<00:17,  1.25s/it]

[SIM] 2017-08-11 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.716, kelly=0.448) with $4654.12 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.799, kelly=0.587) with $6095.51 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.894, kelly=0.791) with $8219.39 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.693, kelly=0.392) with $4069.70 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.839, kelly=0.680) with $7068.05 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.898, kelly=0.804) with $8348.64 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.640, kelly=0.326) with $3387.88 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.853, kelly=0.708) with $7356.17 allocation
[SIM] 2017-08-11 00:00:00: 8 trades proposed.
[TRADE] 2017-08-11 00:00:00: allocated $8348.64 to CAT exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $8219.39 to UN exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $7356.17 to VZ exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $7068.05 to SNY exiting on 2017-08-14 00:00:00
[TRADE] 2017-08-11 00:00:00: allocated $167.58 to HRG exiting on 2017-08-14 00:00:00
[EXIT] 2017-08-14 00:00:00: CAT r=0.0076, PnL=$63.62
[EXIT] 2017-08-14 00:00:00: UN r=0.0078, PnL=$63.82
[EXIT] 2017-08-14 00:00:00: VZ r=0.0150, PnL=$110.20
[EXIT] 2017-08-14 00:00:00: SNY r=0.0038, PnL=$26.76
[EXIT] 2017-08-14 00:00:00: HRG r=0.0006, PnL=$0.10

Simulating Trading Days:  87%|████████▋ | 87/100 [15:08<00:15,  1.22s/it]

[SIM] 2017-08-14 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 52 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.729, kelly=0.474) with $4938.59 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.798, kelly=0.585) with $6090.53 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.893, kelly=0.790) with $8224.38 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.707, kelly=0.420) with $4373.30 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.837, kelly=0.676) with $7040.77 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.911, kelly=0.829) with $8637.55 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.639, kelly=0.325) with $3388.10 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.858, kelly=0.718) with $7472.21 allocation
[SIM] 2017-08-14 00:00:00: 8 trades proposed.
[TRADE] 2017-08-14 00:00:00: allocated $8637.55 to CAT exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $8224.38 to UN exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $7472.21 to VZ exiting on 2017-08-15 00:00:00
[TRADE] 2017-08-14 00:00:00: allocated $6905.04 to SNY exiting on 2017-08-15 00:00:00
[EXIT] 2017-08-15 00:00:00: CAT r=-0.0005, PnL=$-4.56
[EXIT] 2017-08-15 00:00:00: UN r=0.0062, PnL=$50.69
[EXIT] 2017-08-15 00:00:00: VZ r=-0.0062, PnL=$-45.95
[EXIT] 2017-08-15 00:00:00: SNY r=0.0021, PnL=$14.47

Simulating Trading Days:  88%|████████▊ | 88/100 [15:09<00:14,  1.21s/it]

[SIM] 2017-08-15 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 53 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.743, kelly=0.501) with $5221.03 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.797, kelly=0.581) with $6049.31 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.895, kelly=0.794) with $8269.47 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.722, kelly=0.449) with $4672.23 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.825, kelly=0.652) with $6787.88 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.913, kelly=0.833) with $8679.36 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.640, kelly=0.328) with $3412.66 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.855, kelly=0.712) with $7419.58 allocation
[SIM] 2017-08-15 00:00:00: 8 trades proposed.
[TRADE] 2017-08-15 00:00:00: allocated $8679.36 to CAT exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $8269.47 to UN exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $7419.58 to VZ exiting on 2017-08-16 00:00:00
[TRADE] 2017-08-15 00:00:00: allocated $6787.88 to SNY exiting on 2017-08-16 00:00:00
[EXIT] 2017-08-16 00:00:00: CAT r=0.0041, PnL=$35.89
[EXIT] 2017-08-16 00:00:00: UN r=0.0024, PnL=$19.70
[EXIT] 2017-08-16 00:00:00: VZ r=-0.0014, PnL=$-10.71
[EXIT] 2017-08-16 00:00:00: SNY r=0.0125, PnL=$85.15

Simulating Trading Days:  89%|████████▉ | 89/100 [15:10<00:13,  1.23s/it]

[SIM] 2017-08-16 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 51 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.754, kelly=0.522) with $5447.75 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.791, kelly=0.570) with $5938.62 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.896, kelly=0.795) with $8294.43 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.704, kelly=0.412) with $4299.98 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.811, kelly=0.623) with $6498.13 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.908, kelly=0.824) with $8591.16 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.644, kelly=0.334) with $3480.29 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.847, kelly=0.695) with $7245.02 allocation
[SIM] 2017-08-16 00:00:00: 8 trades proposed.
[TRADE] 2017-08-16 00:00:00: allocated $8591.16 to CAT exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $8294.43 to UN exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $7245.02 to VZ exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $6498.13 to SNY exiting on 2017-08-17 00:00:00
[TRADE] 2017-08-16 00:00:00: allocated $653.85 to HRG exiting on 2017-08-17 00:00:00
[EXIT] 2017-08-17 00:00:00: CAT r=-0.0086, PnL=$-73.78
[EXIT] 2017-08-17 00:00:00: UN r=-0.0083, PnL=$-68.99
[EXIT] 2017-08-17 00:00:00: VZ r=-0.0107, PnL=$-77.82
[EXIT] 2017-08-17 00:00:00: SNY r=-0.0072, PnL=$-46.96
[EXIT] 2017-08-17 00:00:00: HRG r=-0.0095, PnL=$-6.19

Simulating Trading Days:  90%|█████████ | 90/100 [15:12<00:12,  1.22s/it]

[SIM] 2017-08-17 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.764, kelly=0.543) with $5644.55 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.799, kelly=0.585) with $6082.69 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.892, kelly=0.788) with $8191.26 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.689, kelly=0.384) with $3996.38 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.801, kelly=0.605) with $6289.37 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.904, kelly=0.816) with $8481.57 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.657, kelly=0.359) with $3728.78 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.840, kelly=0.682) with $7096.30 allocation
[PORT] Sector Utilities: Kelly <= 0 for D (p_up=0.515, b=0.887).
[SIM] 2017-08-17 00:00:00: 8 trades proposed.
[TRADE] 2017-08-17 00:00:00: allocated $8481.57 to CAT exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $8191.26 to UN exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $7096.30 to VZ exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $6289.37 to SNY exiting on 2017-08-18 00:00:00
[TRADE] 2017-08-17 00:00:00: allocated $1141.95 to HRG exiting on 2017-08-18 00:00:00
[EXIT] 2017-08-18 00:00:00: CAT r=0.0069, PnL=$58.47
[EXIT] 2017-08-18 00:00:00: UN r=0.0019, PnL=$15.42
[EXIT] 2017-08-18 00:00:00: VZ r=-0.0042, PnL=$-29.64
[EXIT] 2017-08-18 00:00:00: SNY r=0.0023, PnL=$14.39
[EXIT] 2017-08-18 00:00:00: HRG r=-0.0172, PnL=$-19.64

Simulating Trading Days:  91%|█████████ | 91/100 [15:13<00:10,  1.21s/it]

[SIM] 2017-08-18 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 49 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.775, kelly=0.563) with $5854.06 allocation
[PORT] Sector Conglomerates: selecting HRG (p_up=0.819, kelly=0.627) with $6521.55 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.889, kelly=0.780) with $8119.86 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.681, kelly=0.368) with $3831.67 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.791, kelly=0.584) with $6080.18 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.901, kelly=0.809) with $8413.18 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.670, kelly=0.383) with $3989.26 allocation
[PORT] Sector Technology: selecting VZ (p_up=0.836, kelly=0.673) with $7003.74 allocation
[PORT] Sector Utilities: Kelly <= 0 for D (p_up=0.516, b=0.889).
[SIM] 2017-08-18 00:00:00: 8 trades proposed.
[TRADE] 2017-08-18 00:00:00: allocated $8413.18 to CAT exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $8119.86 to UN exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $7003.74 to VZ exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $6521.55 to HRG exiting on 2017-08-21 00:00:00
[TRADE] 2017-08-18 00:00:00: allocated $1153.83 to SNY exiting on 2017-08-21 00:00:00
[EXIT] 2017-08-21 00:00:00: CAT r=-0.0028, PnL=$-23.63
[EXIT] 2017-08-21 00:00:00: UN r=0.0050, PnL=$40.23
[EXIT] 2017-08-21 00:00:00: VZ r=0.0094, PnL=$66.09
[EXIT] 2017-08-21 00:00:00: HRG r=-0.0039, PnL=$-25.36
[EXIT] 2017-08-21 00:00:00: SNY r=0.0006, PnL=$0.72

Simulating Trading Days:  92%|█████████▏| 92/100 [15:14<00:10,  1.28s/it]

[SIM] 2017-08-21 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.782, kelly=0.576) with $5999.23 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.800, kelly=0.594) with $6188.03 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.889, kelly=0.780) with $8120.48 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.708, kelly=0.422) with $4388.99 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.792, kelly=0.587) with $6109.43 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.900, kelly=0.808) with $8406.93 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.698, kelly=0.435) with $4533.45 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.855, kelly=0.706) with $7348.70 allocation
[PORT] Sector Utilities: Kelly <= 0 for D (p_up=0.516, b=0.889).
[SIM] 2017-08-21 00:00:00: 8 trades proposed.
[TRADE] 2017-08-21 00:00:00: allocated $8406.93 to CAT exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $8120.48 to UN exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $7348.70 to INTC exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $6188.03 to IEP exiting on 2017-08-22 00:00:00
[TRADE] 2017-08-21 00:00:00: allocated $1165.43 to SNY exiting on 2017-08-22 00:00:00
[EXIT] 2017-08-22 00:00:00: CAT r=0.0195, PnL=$164.29
[EXIT] 2017-08-22 00:00:00: UN r=0.0037, PnL=$30.37
[EXIT] 2017-08-22 00:00:00: INTC r=-0.0077, PnL=$-56.82
[EXIT] 2017-08-22 00:00:00: IEP r=0.0076, PnL=$47.30
[EXIT] 2017-08-22 00:00:00: SNY r=0.0050, PnL=$5.80

Simulating Trading Days:  93%|█████████▎| 93/100 [15:16<00:09,  1.32s/it]

[SIM] 2017-08-22 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 50 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.788, kelly=0.589) with $6142.79 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.818, kelly=0.632) with $6587.88 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.889, kelly=0.780) with $8138.89 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.730, kelly=0.466) with $4855.76 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.792, kelly=0.586) with $6109.67 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.897, kelly=0.802) with $8369.23 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.719, kelly=0.474) with $4942.50 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.906, kelly=0.809) with $8434.26 allocation
[SIM] 2017-08-22 00:00:00: 8 trades proposed.
[TRADE] 2017-08-22 00:00:00: allocated $8434.26 to INTC exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $8369.23 to CAT exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $8138.89 to UN exiting on 2017-08-23 00:00:00
[TRADE] 2017-08-22 00:00:00: allocated $6344.48 to IEP exiting on 2017-08-23 00:00:00
[EXIT] 2017-08-23 00:00:00: INTC r=0.0003, PnL=$2.43
[EXIT] 2017-08-23 00:00:00: CAT r=-0.0092, PnL=$-77.32
[EXIT] 2017-08-23 00:00:00: UN r=-0.0007, PnL=$-5.51
[EXIT] 2017-08-23 00:00:00: IEP r=0.0102, PnL=$64.60

Simulating Trading Days:  94%|█████████▍| 94/100 [15:17<00:08,  1.34s/it]

[SIM] 2017-08-23 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.791, kelly=0.593) with $6183.93 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.829, kelly=0.653) with $6811.02 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.890, kelly=0.783) with $8159.93 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.743, kelly=0.491) with $5121.00 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.785, kelly=0.572) with $5965.61 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.889, kelly=0.786) with $8193.08 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.731, kelly=0.497) with $5179.19 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.939, kelly=0.877) with $9143.65 allocation
[SIM] 2017-08-23 00:00:00: 8 trades proposed.
[TRADE] 2017-08-23 00:00:00: allocated $9143.65 to INTC exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $8159.93 to UN exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $8193.08 to CAT exiting on 2017-08-24 00:00:00
[TRADE] 2017-08-23 00:00:00: allocated $5785.46 to IEP exiting on 2017-08-24 00:00:00
[EXIT] 2017-08-24 00:00:00: INTC r=0.0014, PnL=$13.19
[EXIT] 2017-08-24 00:00:00: UN r=-0.0029, PnL=$-23.51
[EXIT] 2017-08-24 00:00:00: CAT r=0.0003, PnL=$2.14
[EXIT] 2017-08-24 00:00:00: IEP r=0.0018, PnL=$10.29

Simulating Trading Days:  95%|█████████▌| 95/100 [15:18<00:06,  1.31s/it]

[SIM] 2017-08-24 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 46 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.785, kelly=0.581) with $6060.34 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.834, kelly=0.664) with $6923.08 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.892, kelly=0.787) with $8210.24 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.734, kelly=0.473) with $4932.65 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.771, kelly=0.544) with $5671.55 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.874, kelly=0.758) with $7901.78 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.736, kelly=0.506) with $5274.06 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.956, kelly=0.911) with $9501.06 allocation
[SIM] 2017-08-24 00:00:00: 8 trades proposed.
[TRADE] 2017-08-24 00:00:00: allocated $9501.06 to INTC exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $8210.24 to UN exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $7901.78 to CAT exiting on 2017-08-25 00:00:00
[TRADE] 2017-08-24 00:00:00: allocated $5669.67 to IEP exiting on 2017-08-25 00:00:00
[EXIT] 2017-08-25 00:00:00: INTC r=-0.0012, PnL=$-10.95
[EXIT] 2017-08-25 00:00:00: UN r=0.0075, PnL=$61.41
[EXIT] 2017-08-25 00:00:00: CAT r=0.0050, PnL=$39.24
[EXIT] 2017-08-25 00:00:00: IEP r=0.0158, PnL=$89.48

Simulating Trading Days:  96%|█████████▌| 96/100 [15:20<00:05,  1.46s/it]

[SIM] 2017-08-25 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 48 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.770, kelly=0.553) with $5780.11 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.832, kelly=0.659) with $6888.06 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.894, kelly=0.791) with $8259.52 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.758, kelly=0.520) with $5428.10 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.765, kelly=0.531) with $5546.86 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.878, kelly=0.765) with $7991.72 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.746, kelly=0.525) with $5486.33 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.959, kelly=0.916) with $9571.11 allocation
[SIM] 2017-08-25 00:00:00: 8 trades proposed.
[TRADE] 2017-08-25 00:00:00: allocated $9571.11 to INTC exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $8259.52 to UN exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $7991.72 to CAT exiting on 2017-08-28 00:00:00
[TRADE] 2017-08-25 00:00:00: allocated $5514.15 to IEP exiting on 2017-08-28 00:00:00
[EXIT] 2017-08-28 00:00:00: INTC r=-0.0006, PnL=$-5.52
[EXIT] 2017-08-28 00:00:00: UN r=0.0034, PnL=$27.87
[EXIT] 2017-08-28 00:00:00: CAT r=-0.0024, PnL=$-19.40
[EXIT] 2017-08-28 00:00:00: IEP r=-0.0068, PnL=$-37.48

Simulating Trading Days:  97%|█████████▋| 97/100 [15:22<00:04,  1.65s/it]

[SIM] 2017-08-28 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 44 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.750, kelly=0.513) with $5358.70 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.825, kelly=0.644) with $6728.41 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.895, kelly=0.793) with $8277.44 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.776, kelly=0.555) with $5795.50 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.759, kelly=0.519) with $5418.69 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.879, kelly=0.767) with $8006.53 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.759, kelly=0.549) with $5730.95 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.963, kelly=0.925) with $9659.62 allocation
[SIM] 2017-08-28 00:00:00: 8 trades proposed.
[TRADE] 2017-08-28 00:00:00: allocated $9659.62 to INTC exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $8277.44 to UN exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $8006.53 to CAT exiting on 2017-08-29 00:00:00
[TRADE] 2017-08-28 00:00:00: allocated $5382.55 to IEP exiting on 2017-08-29 00:00:00
[EXIT] 2017-08-29 00:00:00: INTC r=0.0023, PnL=$22.30
[EXIT] 2017-08-29 00:00:00: UN r=0.0003, PnL=$2.78
[EXIT] 2017-08-29 00:00:00: CAT r=0.0082, PnL=$65.41
[EXIT] 2017-08-29 00:00:00: IEP r=-0.0025, PnL=$-13.68

Simulating Trading Days:  98%|█████████▊| 98/100 [15:24<00:03,  1.64s/it]

[SIM] 2017-08-29 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 43 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.718, kelly=0.453) with $4732.89 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.813, kelly=0.621) with $6490.55 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.893, kelly=0.790) with $8251.48 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.784, kelly=0.572) with $5975.37 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.758, kelly=0.517) with $5407.36 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.882, kelly=0.773) with $8077.54 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.770, kelly=0.570) with $5953.81 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.966, kelly=0.932) with $9735.39 allocation
[SIM] 2017-08-29 00:00:00: 8 trades proposed.
[TRADE] 2017-08-29 00:00:00: allocated $9735.39 to INTC exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $8251.48 to UN exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $8077.54 to CAT exiting on 2017-08-30 00:00:00
[TRADE] 2017-08-29 00:00:00: allocated $5284.78 to IEP exiting on 2017-08-30 00:00:00
[EXIT] 2017-08-30 00:00:00: INTC r=0.0046, PnL=$44.85
[EXIT] 2017-08-30 00:00:00: UN r=-0.0079, PnL=$-65.19
[EXIT] 2017-08-30 00:00:00: CAT r=0.0133, PnL=$107.23
[EXIT] 2017-08-30 00:00:00: IEP r=0.0041, PnL=$21.76

Simulating Trading Days:  99%|█████████▉| 99/100 [15:25<00:01,  1.66s/it]

[SIM] 2017-08-30 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 41 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting PTR (p_up=0.682, kelly=0.382) with $3998.21 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.799, kelly=0.594) with $6213.20 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.887, kelly=0.777) with $8130.53 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.799, kelly=0.602) with $6296.12 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.756, kelly=0.513) with $5371.01 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.882, kelly=0.773) with $8087.58 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.778, kelly=0.585) with $6115.75 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.967, kelly=0.934) with $9766.83 allocation
[SIM] 2017-08-30 00:00:00: 8 trades proposed.
[TRADE] 2017-08-30 00:00:00: allocated $9766.83 to INTC exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $8130.53 to UN exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $8087.58 to CAT exiting on 2017-08-31 00:00:00
[TRADE] 2017-08-30 00:00:00: allocated $5396.84 to IEP exiting on 2017-08-31 00:00:00
[EXIT] 2017-08-31 00:00:00: INTC r=0.0052, PnL=$50.39
[EXIT] 2017-08-31 00:00:00: UN r=0.0081, PnL=$66.12
[EXIT] 2017-08-31 00:00:00: CAT r=-0.0005, PnL=$-4.13
[EXIT] 2017-08-31 00:00:00: IEP r=-0.0008, PnL=$-4.21

Simulating Trading Days: 100%|██████████| 100/100 [15:28<00:00,  9.29s/it]

[SIM] 2017-08-31 00:00:00: built 87 predictions
[PORT] Received 87 predictions for sizing.
[PORT] 40 tickers cleared prob_up ≥ 0.300 and positive expected return.
[PORT] Sector Basic Matierials: selecting SLB (p_up=0.642, kelly=0.301) with $3154.53 allocation
[PORT] Sector Conglomerates: selecting IEP (p_up=0.782, kelly=0.559) with $5851.17 allocation
[PORT] Sector Consumer Goods: selecting UN (p_up=0.879, kelly=0.762) with $7975.81 allocation
[PORT] Sector Financial: selecting WFC (p_up=0.818, kelly=0.639) with $6691.62 allocation
[PORT] Sector Healthcare: selecting SNY (p_up=0.756, kelly=0.514) with $5379.13 allocation
[PORT] Sector Industrial Goods: selecting CAT (p_up=0.887, kelly=0.783) with $8201.38 allocation
[PORT] Sector Services: selecting CHTR (p_up=0.784, kelly=0.596) with $6239.70 allocation
[PORT] Sector Technology: selecting INTC (p_up=0.976, kelly=0.950) with $9952.16 allocation
[SIM] 2017-08-31 00:00:00: 8 trades proposed.

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'UN', 'sector': 'Consumer Goods', ..."
1,2017-04-12,99934.643626,69954.250538,99934.643626,99934.643626,-65.356374,-0.000654,"[{'ticker': 'UN', 'sector': 'Consumer Goods', ..."
2,2017-04-13,99736.268018,69815.387613,99736.268018,99736.268018,-198.375608,-0.001985,"[{'ticker': 'V', 'sector': 'Financial', 'prob_..."
3,2017-04-17,99983.212156,69988.248509,99983.212156,99983.212156,246.944138,0.002476,"[{'ticker': 'V', 'sector': 'Financial', 'prob_..."
4,2017-04-18,99942.390141,69959.673098,99942.390141,99942.390141,-40.822015,-0.000408,"[{'ticker': 'V', 'sector': 'Financial', 'prob_..."
...,...,...,...,...,...,...,...,...
95,2017-08-25,104455.011697,73118.508188,104455.011697,104455.011697,179.176833,0.001718,"[{'ticker': 'INTC', 'sector': 'Technology', 'p..."
96,2017-08-28,104420.481154,73094.336807,104420.481154,104420.481154,-34.530543,-0.000331,"[{'ticker': 'INTC', 'sector': 'Technology', 'p..."
97,2017-08-29,104497.288862,73148.102204,104497.288862,104497.288862,76.807709,0.000736,"[{'ticker': 'INTC', 'sector': 'Technology', 'p..."
98,2017-08-30,104605.932295,73224.152607,104605.932295,104605.932295,108.643433,0.001040,"[{'ticker': 'INTC', 'sector': 'Technology', 'p..."
99,2017-08-31,104714.101455,104714.101455,104714.101455,104714.101455,108.169159,0.001034,[]

,date,capital_start,capital_end,equity_start,equity_end,daily_pnl_realized,daily_return,investments_made
0,2017-04-11,100000.000000,70000.000000,100000.000000,100000.000000,0.000000,0.000000,"[{'ticker': 'UN', 'sector': 'Consumer Goods', ..."
1,2017-04-12,99934.643626,69954.250538,99934.643626,99934.643626,-65.356374,-0.000654,"[{'ticker': 'UN', 'sector': 'Consumer Goods', ..."
2,2017-04-13,99736.268018,69815.387613,99736.268018,99736.268018,-198.375608,-0.001985,"[{'ticker': 'V', 'sector': 'Financial', 'prob_..."
3,2017-04-17,99983.212156,69988.248509,99983.212156,99983.212156,246.944138,0.002476,"[{'ticker': 'V', 'sector': 'Financial', 'prob_..."
4,2017-04-18,99942.390141,69959.673098,99942.390141,99942.390141,-40.822015,-0.000408,"[{'ticker': 'V', 'sector': 'Financial', 'prob_..."
...,...,...,...,...,...,...,...,...
95,2017-08-25,104455.011697,73118.508188,104455.011697,104455.011697,179.176833,0.001718,"[{'ticker': 'INTC', 'sector': 'Technology', 'p..."
96,2017-08-28,104420.481154,73094.336807,104420.481154,104420.481154,-34.530543,-0.000331,"[{'ticker': 'INTC', 'sector': 'Technology', 'p..."
97,2017-08-29,104497.288862,73148.102204,104497.288862,104497.288862,76.807709,0.000736,"[{'ticker': 'INTC', 'sector': 'Technology', 'p..."
98,2017-08-30,104605.932295,73224.152607,104605.932295,104605.932295,108.643433,0.001040,"[{'ticker': 'INTC', 'sector': 'Technology', 'p..."
99,2017-08-31,104714.101455,104714.101455,104714.101455,104714.101455,108.169159,0.001034,[]

--- Simulation Results ---
Initial Capital: $100,000.00
Final Capital:   $104,714.10
Total Return on Investment (ROI): 4.71%
Annualized Sharpe Ratio: 3.55
--------------------------

In [36]:
master_df_with_target = add_horizon_targets(master_df.copy(), H=1, price_col="close")
import numpy as np
import pandas as pd

ret_col = f"ret_{1}d"

all_trades = []
ret_lookup = master_df_with_target.set_index(['ticker','date'])[ret_col].to_dict()
sector_lookup = None
if 'sector' in master_df_with_target.columns:
    sector_lookup = master_df_with_target.set_index(['ticker'])['sector'].to_dict()

for _, row in simulation_results.iterrows():
    invs = row.get('investments_made', [])
    if not isinstance(invs, list):
        continue
    entry_date = row['date']
    for inv in invs:
        if not isinstance(inv, dict):
            continue
        ticker = inv.get('ticker')
        if ticker is None:
            continue
        allocated = inv.get('allocated_amount', inv.get('investment_amount', np.nan))
        sector = inv.get('sector')
        if sector is None and sector_lookup is not None:
            sector = sector_lookup.get(ticker, 'UNKNOWN')
        prob_up = inv.get('prob_up', inv.get('predicted_prob', np.nan))
        expected_rise = inv.get('expected_rise', np.nan)
        exit_date = inv.get('exit_date')
        ret_H = ret_lookup.get((ticker, entry_date), np.nan)
        pnl = allocated * ret_H if np.isfinite(allocated) and np.isfinite(ret_H) else np.nan
        all_trades.append({
            'date': entry_date,
            'exit_date': exit_date,
            'ticker': ticker,
            'sector': sector if sector is not None else 'UNKNOWN',
            'allocated_amount': allocated,
            'prob_up': prob_up,
            'expected_rise': expected_rise,
            'actual_return': ret_H,
            'pnl': pnl,
        })

trades_df = pd.DataFrame(all_trades)
print("="*80)
print("INVESTMENT SUMMARY")
print("="*80)
print(f"Total trades: {len(trades_df)}")
if trades_df.empty:
    print("No trades recorded.")
else:
    print(f"Total capital allocated: ${trades_df['allocated_amount'].sum():,.2f}")
    print(f"Average position size:  ${trades_df['allocated_amount'].mean():,.2f}")
    completed = trades_df[trades_df['pnl'].notna()].copy()
    print(f"Completed trades with returns: {len(completed)}")
    if not completed.empty:
        wins = (completed['pnl'] > 0).sum()
        losses = (completed['pnl'] < 0).sum()
        print(f"Winning trades: {wins} ({wins/len(completed)*100:.1f}%)")
        print(f"Losing trades:  {losses} ({losses/len(completed)*100:.1f}%)")
        total_pnl = completed['pnl'].sum()
        avg_pnl = completed['pnl'].mean()
        avg_ret = completed['actual_return'].mean()
        print(f"Total PnL: ${total_pnl:,.2f}")
        print(f"Average PnL per trade: ${avg_pnl:,.2f}")
        print(f"Average return: {avg_ret*100:.2f}%")
    else:
        total_pnl = np.nan
        avg_pnl = np.nan
        avg_ret = np.nan

    if 'sector' in trades_df.columns:
        sector_stats = trades_df.groupby('sector').agg(
            trades=('ticker','count'),
            allocated=('allocated_amount','sum'),
            avg_alloc=('allocated_amount','mean'),
            pnl_sum=('pnl','sum'),
            pnl_mean=('pnl','mean'),
            ret_mean=('actual_return','mean'),
        ).sort_values('pnl_sum', ascending=False)
        print("Sector breakdown (sorted by total PnL):")
        display(sector_stats)

    if not trades_df.empty:
        print("TOP 10 BIGGEST EARNERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=False).head(10))
        print("TOP 10 BIGGEST LOSERS (trades)")
        display(trades_df.dropna(subset=['pnl']).sort_values('pnl', ascending=True).head(10))

    if not trades_df.empty and 'sector' in trades_df.columns:
        top_sectors = trades_df.dropna(subset=['pnl']).groupby('sector')['pnl'].sum().sort_values(ascending=False)
        print("TOP 10 SECTORS BY TOTAL PnL")
        display(top_sectors.head(10).to_frame('total_pnl'))
        print("BOTTOM 10 SECTORS BY TOTAL PnL")
        display(top_sectors.tail(10).to_frame('total_pnl'))
        
        # identify tickers that were most invested in
        most_invested_tickers = trades_df['ticker'].value_counts().head(10)
        print("Top 10 Most Invested Tickers:")
        display(most_invested_tickers)

        # identify tickers that were never invested in
        all_tickers = master_df_with_target['ticker'].unique()
        invested_tickers = trades_df['ticker'].unique()
        never_invested_tickers = set(all_tickers) - set(invested_tickers)
        print(f"Tickers Never Invested In ({len(never_invested_tickers)}):")
        print(never_invested_tickers)

================================================================================
INVESTMENT SUMMARY
================================================================================
Total trades: 441
Total capital allocated: $3,032,270.58
Average position size:  $6,875.90
Completed trades with returns: 441
Winning trades: 232 (52.6%)
Losing trades:  204 (46.3%)
Total PnL: $4,714.10
Average PnL per trade: $10.69
Average return: 0.12%
Sector breakdown (sorted by total PnL):

,trades,allocated,avg_alloc,pnl_sum,pnl_mean,ret_mean
sector,,,,,,
Industrial Goods,88,602578.538239,6847.483389,1251.396599,14.220416,0.001973
Consumer Goods,92,693226.590473,7535.071636,831.538429,9.038461,0.001194
Conglomerates,43,238991.268159,5557.936469,824.074596,19.164525,0.000947
Healthcare,72,401424.568303,5575.341226,719.370265,9.991254,0.001338
Services,24,144005.715013,6000.238126,450.739410,18.780809,0.003490
Technology,92,801596.763241,8713.008296,438.663706,4.768084,0.000369
Financial,27,146763.613669,5435.689395,217.811690,8.067100,0.000249
Basic Matierials,3,3683.522627,1227.840876,-19.493241,-6.497747,-0.004638

TOP 10 BIGGEST EARNERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
331,2017-07-26,2017-07-27,VZ,Technology,10056.147700,0.987680,0.024329,0.076802,772.330001
324,2017-07-24,2017-07-25,CAT,Industrial Goods,8460.047939,0.910242,0.018733,0.058791,497.373945
146,2017-05-23,2017-05-24,CHTR,Services,7596.605984,0.868167,0.021621,0.032153,244.252358
51,2017-04-26,2017-04-27,IEP,Conglomerates,7378.429291,0.865729,0.021234,0.032442,239.370546
27,2017-04-19,2017-04-20,IEP,Conglomerates,7454.734057,0.874491,0.021945,0.030792,229.544119
37,2017-04-21,2017-04-24,C,Financial,7402.875208,0.867417,0.017409,0.029799,220.598239
268,2017-07-03,2017-07-05,TM,Consumer Goods,8675.759762,0.925966,0.019596,0.023578,204.559083
313,2017-07-19,2017-07-20,SNY,Healthcare,7354.338775,0.859688,0.017583,0.026704,196.388021
253,2017-06-27,2017-06-28,CAT,Industrial Goods,8019.598864,0.892821,0.017364,0.024247,194.451699
311,2017-07-19,2017-07-20,VZ,Technology,9914.740789,0.985677,0.024125,0.017722,175.704263

TOP 10 BIGGEST LOSERS (trades)

,date,exit_date,ticker,sector,allocated_amount,prob_up,expected_rise,actual_return,pnl
271,2017-07-05,2017-07-06,VZ,Technology,9868.102439,0.983257,0.023880,-0.025308,-249.741881
98,2017-05-09,2017-05-10,TM,Consumer Goods,7965.793015,0.894275,0.017000,-0.024433,-194.628062
59,2017-04-27,2017-04-28,INTC,Technology,5453.941812,0.771608,0.011485,-0.034197,-186.509073
227,2017-06-19,2017-06-20,INTC,Technology,9833.142580,0.983005,0.028417,-0.018305,-179.991933
234,2017-06-20,2017-06-21,CAT,Industrial Goods,5081.809182,0.849419,0.014422,-0.033352,-169.488589
105,2017-05-10,2017-05-11,SNY,Healthcare,6164.743805,0.804984,0.014390,-0.026777,-165.071417
75,2017-05-02,2017-05-03,DIS,Services,6252.053017,0.808861,0.010700,-0.024045,-150.329154
125,2017-05-16,2017-05-17,CHTR,Services,6874.441612,0.830342,0.018911,-0.021562,-148.226048
309,2017-07-18,2017-07-19,SNY,Healthcare,7272.048785,0.855363,0.017320,-0.019481,-141.663434
347,2017-08-01,2017-08-02,VZ,Technology,10164.793184,0.988542,0.024418,-0.013909,-141.379822

TOP 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Industrial Goods  1251.396599
Consumer Goods     831.538429
Conglomerates      824.074596
Healthcare         719.370265
Services           450.739410
Technology         438.663706
Financial          217.811690
Basic Matierials   -19.493241

BOTTOM 10 SECTORS BY TOTAL PnL

                    total_pnl
sector
Industrial Goods  1251.396599
Consumer Goods     831.538429
Conglomerates      824.074596
Healthcare         719.370265
Services           450.739410
Technology         438.663706
Financial          217.811690
Basic Matierials   -19.493241

Top 10 Most Invested Tickers:

ticker
VZ      69
SNY     56
CAT     55
UN      51
IEP     39
TM      34
BA      33
INTC    23
CHTR    20
C       12
Name: count, dtype: int64

Tickers Never Invested In (67):
{'RDS-B', 'SNP', 'MCD', 'HD', 'SRE', 'BBL', 'PG', 'SO', 'D', 'LMT', 'GD', 'BUD', 'TOT', 'MSFT', 'T', 'CMCSA', 'MDT', 'MRK', 'CVX', 'NEE', 'CSCO', 'BHP', 'GOOG', 'AEP', 'SLB', 'UNH', 'BSAC', 'MA', 'PCLN', 'BRK-A', 'DHR', 'PCG', 'UL', 'REX', 'BABA', 'NGG', 'PPL', 'HSBC', 'EXC', 'AAPL', 'ORCL', 'UTX', 'DUK', 'BCH', 'CHL', 'FB', 'KO', 'BP', 'SPLP', 'ABB', 'AGFS', 'WMT', 'MO', 'CODI', 'XOM', 'GE', 'CELG', 'ABBV', 'JNJ', 'PICO', 'AMZN', 'PEP', 'PFE', 'TSM', 'MMM', 'HON', 'UPS'}

In [37]:
folder_path = 'trained_models/'
if os.path.exists(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f'Failed to delete {file_path}. Reason: {e}')
else:
    print(f"Folder not found: {folder_path}")

print(f"Contents of {folder_path} after deletion attempt:")
if os.path.exists(folder_path):
    print(os.listdir(folder_path))
else:
    print("Folder does not exist.")

Contents of trained_models/ after deletion attempt:
[]