#

# Unifying Emotion

In [1]:
import pandas as pd

In [2]:
tweets = pd.read_parquet("../data/dataset/stock_tweets_sentiment_emotion_nomerge.parquet")
tweets

,ticker,text,created_at,user_id,date,sentiment,emotion_anger,emotion_disgust,emotion_fear,emotion_joy,emotion_neutral,emotion_sadness,emotion_surprize
0,AAPL,summary of yesterdays webcast featuring wynn g...,2013-12-31 23:10:08+00:00,1864753100,2013-12-31,4,0.677257,0.148463,0.143604,0.021908,0.004223,0.003426,0.001120
1,AAPL,summary of yesterdays webcast featuring wynn g...,2014-01-01 01:18:36+00:00,1937591882,2014-01-01,4,0.677257,0.148463,0.143604,0.021908,0.004223,0.003426,0.001120
2,AAPL,iphone users are more intelligent than samsung...,2014-01-01 01:52:31+00:00,23954327,2014-01-01,5,0.651749,0.290809,0.032565,0.017082,0.004068,0.001948,0.001778
3,AAPL,summary of yesterdays webcast featuring wynn g...,2014-01-01 03:29:29+00:00,1933063572,2014-01-01,4,0.677257,0.148463,0.143604,0.021908,0.004223,0.003426,0.001120
4,AAPL,summary of yesterdays webcast featuring wynn g...,2014-01-01 03:59:03+00:00,1938270918,2014-01-01,4,0.677257,0.148463,0.143604,0.021908,0.004223,0.003426,0.001120
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106333,XOM,t active morning movers at t nyse t exxon mobil …,2015-12-28 17:15:13+00:00,2342763212,2015-12-28,5,0.793153,0.089309,0.077659,0.018933,0.011689,0.007353,0.001905
106334,XOM,divest from stopcommoncore optout because chil...,2015-12-28 19:39:46+00:00,4399710563,2015-12-28,1,0.763934,0.115369,0.071567,0.021422,0.012145,0.009175,0.006386
106335,XOM,zsl stock forum zsl gold uslv zsl investing na...,2015-12-29 16:52:36+00:00,2181314366,2015-12-29,5,0.488881,0.242657,0.201586,0.045692,0.012491,0.007334,0.001360
106336,XOM,nptn recent news updated tuesday december pm g...,2015-12-29 19:03:17+00:00,2197054086,2015-12-29,1,0.456476,0.355527,0.112046,0.067945,0.003791,0.003206,0.001009
106337,XOM,exxon mobils buy rating reiterated at morningstar,2015-12-30 06:17:34+00:00,992182100,2015-12-30,5,0.796823,0.070970,0.051782,0.047200,0.020052,0.011534,0.001639

In [3]:


def unify_emotion_features(df: pd.DataFrame) -> pd.DataFrame:

    processed_df = df.copy()


    positive_emotions = ['emotion_joy']
    negative_emotions = ['emotion_anger', 'emotion_disgust', 'emotion_sadness']
    uncertainty_emotions = ['emotion_fear', 'emotion_surprize'] # Note: 'surprize' matches the typo in your notebook


    processed_df['positive_emotion'] = processed_df[positive_emotions].sum(axis=1)
    processed_df['negative_emotion'] = processed_df[negative_emotions].sum(axis=1)
    processed_df['uncertainty_emotion'] = processed_df[uncertainty_emotions].sum(axis=1)


    columns_to_drop = [
        'emotion_anger', 'emotion_disgust', 'emotion_fear',
        'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize'
    ]


    processed_df = processed_df.drop(columns=columns_to_drop)

    return processed_df

In [4]:

tweets_processed = unify_emotion_features(tweets)


print("DataFrame with Unified Emotion Features:")
print(tweets_processed.head())


print("\nNew DataFrame Columns:")
print(tweets_processed.columns)

DataFrame with Unified Emotion Features:
  ticker                                               text  \
0   AAPL  summary of yesterdays webcast featuring wynn g...
1   AAPL  summary of yesterdays webcast featuring wynn g...
2   AAPL  iphone users are more intelligent than samsung...
3   AAPL  summary of yesterdays webcast featuring wynn g...
4   AAPL  summary of yesterdays webcast featuring wynn g...

                 created_at     user_id        date  sentiment  \
0 2013-12-31 23:10:08+00:00  1864753100  2013-12-31          4
1 2014-01-01 01:18:36+00:00  1937591882  2014-01-01          4
2 2014-01-01 01:52:31+00:00    23954327  2014-01-01          5
3 2014-01-01 03:29:29+00:00  1933063572  2014-01-01          4
4 2014-01-01 03:59:03+00:00  1938270918  2014-01-01          4

   positive_emotion  negative_emotion  uncertainty_emotion
0          0.021908          0.829146             0.144724
1          0.021908          0.829146             0.144724
2          0.017082          0.944506             0.034343
3          0.021908          0.829146             0.144724
4          0.021908          0.829146             0.144724

New DataFrame Columns:
Index(['ticker', 'text', 'created_at', 'user_id', 'date', 'sentiment',
       'positive_emotion', 'negative_emotion', 'uncertainty_emotion'],
      dtype='object')

In [5]:
tweets_processed

,ticker,text,created_at,user_id,date,sentiment,positive_emotion,negative_emotion,uncertainty_emotion
0,AAPL,summary of yesterdays webcast featuring wynn g...,2013-12-31 23:10:08+00:00,1864753100,2013-12-31,4,0.021908,0.829146,0.144724
1,AAPL,summary of yesterdays webcast featuring wynn g...,2014-01-01 01:18:36+00:00,1937591882,2014-01-01,4,0.021908,0.829146,0.144724
2,AAPL,iphone users are more intelligent than samsung...,2014-01-01 01:52:31+00:00,23954327,2014-01-01,5,0.017082,0.944506,0.034343
3,AAPL,summary of yesterdays webcast featuring wynn g...,2014-01-01 03:29:29+00:00,1933063572,2014-01-01,4,0.021908,0.829146,0.144724
4,AAPL,summary of yesterdays webcast featuring wynn g...,2014-01-01 03:59:03+00:00,1938270918,2014-01-01,4,0.021908,0.829146,0.144724
...,...,...,...,...,...,...,...,...,...
106333,XOM,t active morning movers at t nyse t exxon mobil …,2015-12-28 17:15:13+00:00,2342763212,2015-12-28,5,0.018933,0.889814,0.079564
106334,XOM,divest from stopcommoncore optout because chil...,2015-12-28 19:39:46+00:00,4399710563,2015-12-28,1,0.021422,0.888479,0.077954
106335,XOM,zsl stock forum zsl gold uslv zsl investing na...,2015-12-29 16:52:36+00:00,2181314366,2015-12-29,5,0.045692,0.738872,0.202946
106336,XOM,nptn recent news updated tuesday december pm g...,2015-12-29 19:03:17+00:00,2197054086,2015-12-29,1,0.067945,0.815209,0.113054
106337,XOM,exxon mobils buy rating reiterated at morningstar,2015-12-30 06:17:34+00:00,992182100,2015-12-30,5,0.047200,0.879327,0.053421

In [6]:
tweets_processed.to_parquet("../data/dataset/stock_tweets_sentiment_unify_emotion_nomerge_.parquet", index=False)